export const albuquerqueData = {
  city: {
    name: "Albuquerque",
    state: "New Mexico",
    region: "Southwest",
    lat: 35.0844,
    lng: -106.6504,
    dogFriendlinessScore: 7,
    description:
      "Albuquerque sits at the crossroads of desert and mountain, offering dogs an incredible range of terrain from the Rio Grande bosque to the Sandia Mountain foothills. The city's strong outdoor culture and vibrant Old Town make it a wonderful Southwest destination for adventurous pups.",
    heroImage: "https://images.unsplash.com/photo-1580974928064-f0aeef70895a?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 564559,
  },

  hotels: [
    {
      name: "Hotel Albuquerque at Old Town",
      address: "800 Rio Grande Blvd NW, Albuquerque, NM 87104",
      lat: 35.0920,
      lng: -106.6690,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 80 lbs welcome with a one-time fee. Hacienda-style hotel steps from Old Town.",
      maxDogWeight: 80,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Old Town walking access", "Courtyard", "Walking maps"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hotelalbuquerque.com",
      phone: "(505) 843-6300",
    },
    {
      name: "Los Poblanos Historic Inn & Organic Farm",
      address: "4803 Rio Grande Blvd NW, Albuquerque, NM 87107",
      lat: 35.1320,
      lng: -106.6510,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with a pet fee. Lavender farm and organic inn on the bosque.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Farm grounds", "Lavender fields", "Bosque trails", "Organic treats", "Garden walks"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.lospoblanos.com",
      phone: "(505) 344-9297",
    },
    {
      name: "Sandia Resort & Casino",
      address: "30 Rainbow Rd NE, Albuquerque, NM 87113",
      lat: 35.1690,
      lng: -106.5530,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in pet-friendly rooms with a nightly fee. Stunning Sandia Mountain views.",
      maxDogWeight: 50,
      petFee: 40,
      amenities: ["Mountain views", "Walking paths", "Grassy grounds", "Near foothills trails"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sandiacasino.com",
      phone: "(505) 796-7500",
    },
    {
      name: "La Quinta Inn Albuquerque Old Town",
      address: "2116 Central Ave SW, Albuquerque, NM 87104",
      lat: 35.0840,
      lng: -106.6660,
      priceRange: "$" as const,
      dogPolicy: "All dogs welcome at no extra charge. On historic Route 66 near Old Town.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Near Old Town", "Route 66 location", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(505) 243-2494",
    },
  ],

  nationalParks: [
    {
      name: "Petroglyph National Monument",
      state: "New Mexico",
      lat: 35.1390,
      lng: -106.7570,
      dogPolicy: "Leashed dogs allowed on the Rinconada Canyon Trail and Piedras Marcadas Canyon Trail.",
      dogTrails: ["Rinconada Canyon Trail", "Piedras Marcadas Canyon Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on Boca Negra Canyon trails",
        "Carry water - no shade on trails",
        "Do not touch or disturb petroglyphs",
      ],
      description:
        "This national monument preserves over 24,000 ancient petroglyphs carved into volcanic rock along Albuquerque's west mesa. Dogs can join you on select trails to see these remarkable rock carvings up to 700 years old.",
      imageUrl: "",
      website: "https://www.nps.gov/petr",
    },
    {
      name: "Cibola National Forest - Sandia Ranger District",
      state: "New Mexico",
      lat: 35.2050,
      lng: -106.4500,
      dogPolicy: "Dogs welcome on all trails. Voice control or leash recommended.",
      dogTrails: ["La Luz Trail", "Embudito Trail", "Piedra Lisa Trail", "Tree Spring Trail"],
      restrictions: [
        "Leash required in developed areas",
        "Carry water for your dog",
        "Watch for wildlife on mountain trails",
      ],
      description:
        "The Sandia Mountains rising over 10,000 feet directly east of Albuquerque offer dramatic mountain hiking. The La Luz Trail climbs 3,800 feet through multiple life zones, from desert to spruce forest.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/cibola",
    },
    {
      name: "Rio Grande Bosque Trail",
      state: "New Mexico",
      lat: 35.0850,
      lng: -106.6680,
      dogPolicy: "Leashed dogs welcome on the entire 16-mile trail. A cottonwood forest corridor through the city.",
      dogTrails: ["Bosque Trail North", "Bosque Trail South", "Tingley Beach Loop"],
      restrictions: [
        "Must be on leash at all times",
        "Stay on paved trail",
        "Do not disturb wildlife in the bosque",
      ],
      description:
        "A 16-mile paved trail through the cottonwood bosque along the Rio Grande, running the length of Albuquerque. Dogs love the shaded riverside path, especially the Tingley Beach area with its ponds.",
      imageUrl: "",
      website: "https://www.cabq.gov/parksandrecreation",
    },
  ],

  restaurants: [
    {
      name: "Marble Brewery",
      address: "111 Marble Ave NW, Albuquerque, NM 87102",
      lat: 35.0880,
      lng: -106.6500,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Extremely dog-friendly with a large outdoor beer garden. Dogs are the star attraction.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.marblebrewery.com",
    },
    {
      name: "Farm & Table",
      address: "8917 4th St NW, Albuquerque, NM 87114",
      lat: 35.1580,
      lng: -106.6480,
      cuisine: "Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the garden patio. Seasonal New Mexican cuisine from their own farm.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.farmandtablenm.com",
    },
    {
      name: "El Pinto Restaurant",
      address: "10500 4th St NW, Albuquerque, NM 87114",
      lat: 35.1750,
      lng: -106.6480,
      cuisine: "New Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the expansive outdoor patio. Famous for their green chile.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.elpinto.com",
    },
    {
      name: "Tractor Brewing Wells Park",
      address: "1800 4th St NW, Albuquerque, NM 87102",
      lat: 35.1020,
      lng: -106.6490,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly taproom with outdoor yard. One of ABQ's most welcoming spots for pups.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.getplowed.com",
    },
    {
      name: "Cervantes Restaurant",
      address: "5801 Gibson Blvd SE, Albuquerque, NM 87108",
      lat: 35.0580,
      lng: -106.5790,
      cuisine: "New Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor patio tables. Classic New Mexican comfort food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cervantesrestaurant.com",
    },
  ],

  cafes: [
    {
      name: "Zendo Coffee",
      address: "413 2nd St SW, Albuquerque, NM 87102",
      lat: 35.0830,
      lng: -106.6510,
      dogPolicy: "Dogs welcome on the spacious outdoor patio. Specialty coffee in a zen-like setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.zendocoffee.com",
    },
    {
      name: "Humble Coffee Co.",
      address: "4200 Lomas Blvd NE, Albuquerque, NM 87110",
      lat: 35.0870,
      lng: -106.6010,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Third-wave coffee with New Mexican flair.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.humblecoffeeco.com",
    },
    {
      name: "Prismatic Coffee",
      address: "3516 CNM Dr NE, Albuquerque, NM 87106",
      lat: 35.0740,
      lng: -106.6200,
      dogPolicy: "Patio seating welcomes dogs. Award-winning Albuquerque coffee roasters.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.prismaticcoffee.com",
    },
    {
      name: "Michael Thomas Coffee",
      address: "1111 Carlisle Blvd SE, Albuquerque, NM 87106",
      lat: 35.0760,
      lng: -106.6150,
      dogPolicy: "Leashed dogs welcome at outdoor tables. A Nob Hill coffee favorite.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.michaelthomascoffee.com",
    },
  ],

  dogParks: [
    {
      name: "North Domingo Baca Dog Park",
      address: "7521 Carmel Ave NE, Albuquerque, NM 87113",
      lat: 35.1580,
      lng: -106.5870,
      offLeash: true,
      fenced: true,
      acres: 6.0,
      amenities: ["Separate small dog area", "Water stations", "Shade structures", "Agility equipment", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Albuquerque's best dog park with mountain views, excellent shade, and agility equipment. The separate small dog area and well-maintained grounds make it popular year-round.",
    },
    {
      name: "Skyline Dog Park",
      address: "10900 Skyline Dr NE, Albuquerque, NM 87123",
      lat: 35.0980,
      lng: -106.5170,
      offLeash: true,
      fenced: true,
      acres: 4.0,
      amenities: ["Mountain views", "Water fountains", "Shade ramadas", "Waste stations", "Benches"],
      rating: 4.4,
      imageUrl: "",
      description:
        "An east-side dog park with stunning Sandia Mountain views. The elevated location provides a beautiful backdrop for off-leash play, and the high-desert air keeps things pleasant.",
    },
    {
      name: "Rio Grande Bosque Trail",
      address: "Tingley Beach, Albuquerque, NM 87102",
      lat: 35.0770,
      lng: -106.6700,
      offLeash: false,
      fenced: false,
      acres: 200.0,
      amenities: ["Paved trail", "Cottonwood shade", "River views", "Ponds", "Benches"],
      rating: 4.7,
      imageUrl: "",
      description:
        "The shaded bosque trail along the Rio Grande is Albuquerque's most beloved on-leash walking path. The cottonwood canopy provides welcome relief from the sun while dogs enjoy the riverside terrain.",
    },
    {
      name: "Coronado Dog Park",
      address: "301 McKnight Ave NW, Albuquerque, NM 87102",
      lat: 35.1000,
      lng: -106.6530,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Double-gated entry", "Water fountain", "Shade trees", "Waste stations", "Benches"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A neighborhood dog park near the bosque with easy access to river trails. The compact, fenced area is ideal for a quick off-leash session before heading to the nearby bosque path.",
    },
  ],
};
