export const ameliaIslandData = {
  city: {
    name: "Amelia Island",
    state: "Florida",
    region: "Southeast",
    lat: 30.6698,
    lng: -81.4626,
    dogFriendlinessScore: 8,
    description:
      "This barrier island off northeast Florida is a dog paradise with 13 miles of uncrowded beaches where dogs can roam, a walkable Victorian downtown in Fernandina Beach, and a wealth of nature preserves. The relaxed island atmosphere and pet-friendly businesses make it one of Florida's best destinations for dogs.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 13945,
  },
  hotels: [
    {
      name: "The Ritz-Carlton, Amelia Island",
      address: "4750 Amelia Island Pkwy, Amelia Island, FL 32034",
      lat: 30.6370,
      lng: -81.4400,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs under 30 lbs welcome with a non-refundable pet fee. Luxury beachfront resort with exceptional service.",
      maxDogWeight: 30,
      petFee: 150,
      amenities: ["Dog bed", "Water and food bowls", "Treats at check-in", "Pet concierge", "Beach access guide"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.ritzcarlton.com/en/hotels/florida/amelia-island",
      phone: "(904) 277-1100",
    },
    {
      name: "Omni Amelia Island Resort",
      address: "39 Beach Lagoon Rd, Amelia Island, FL 32034",
      lat: 30.6220,
      lng: -81.4350,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 25 lbs welcome with a non-refundable pet fee. A sprawling oceanfront resort with golf and nature trails.",
      maxDogWeight: 25,
      petFee: 100,
      amenities: ["Dog bed", "Water bowls", "Nature trail access", "Waste bags", "Pet walking guide"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.omnihotels.com/hotels/amelia-island",
      phone: "(904) 261-6161",
    },
    {
      name: "Hampton Inn Amelia Island",
      address: "19 S 2nd St, Fernandina Beach, FL 32034",
      lat: 30.6700,
      lng: -81.4625,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a nightly pet fee. Located in the heart of downtown Fernandina Beach.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Pet-friendly rooms", "Walking access to downtown", "Water bowls", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com/en/hotels/jaxfbhx",
      phone: "(904) 491-4911",
    },
    {
      name: "Elizabeth Pointe Lodge",
      address: "98 S Fletcher Ave, Fernandina Beach, FL 32034",
      lat: 30.6650,
      lng: -81.4440,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in the Ocean House cottage with a pet fee. A Nantucket-style oceanfront bed & breakfast.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Cottage accommodation", "Beach access", "Water bowls", "Waste bags", "Private porch"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.elizabethpointelodge.com",
      phone: "(904) 277-4851",
    },
  ],
  nationalParks: [
    {
      name: "Fort Clinch State Park",
      state: "Florida",
      lat: 30.6990,
      lng: -81.4360,
      dogPolicy: "Dogs welcome on the beach and trails on a 6-foot leash. One of the most dog-friendly state parks in Florida.",
      dogTrails: ["Willow Pond Trail", "Magnolia Trail", "Beach Trail", "Fort Loop Trail"],
      restrictions: ["6-foot leash required", "Not allowed inside the fort", "Must clean up after pet"],
      description: "At the northern tip of Amelia Island, Fort Clinch State Park offers pristine beaches, Civil War-era fortifications, and miles of trails through maritime forest. Dogs can walk the beach, explore the trails, and enjoy the river and ocean views.",
      imageUrl: "",
      website: "https://www.floridastateparks.org/fortclinch",
    },
    {
      name: "Amelia Island State Park",
      state: "Florida",
      lat: 30.5870,
      lng: -81.4380,
      dogPolicy: "Dogs welcome on the beach and trails on a 6-foot leash. The only Florida state park offering horseback riding on the beach.",
      dogTrails: ["Beach Walk", "George Crady Bridge Trail"],
      restrictions: ["6-foot leash required", "Must clean up after pet", "No dogs near horse areas"],
      description: "At the southern tip of the island, this state park offers a beautiful beach and the George Crady Bridge fishing pier. Dogs enjoy the uncrowded shoreline and the chance to spot shorebirds and dolphins.",
      imageUrl: "",
      website: "https://www.floridastateparks.org/ameliaisland",
    },
    {
      name: "Timucuan Ecological and Historic Preserve",
      state: "Florida",
      lat: 30.4540,
      lng: -81.5010,
      dogPolicy: "Dogs welcome on most trails on a 6-foot leash. A 46,000-acre preserve of salt marshes, islands, and waterways.",
      dogTrails: ["Willie Browne Trail", "Ribault Club Trail", "Theodore Roosevelt Area Trails"],
      restrictions: ["6-foot leash required", "Not in buildings", "Must clean up after pet"],
      description: "About 30 minutes south of Amelia Island, this vast preserve protects one of the last unspoiled coastal wetlands on the Atlantic Coast. Dogs can explore upland trails with marsh views.",
      imageUrl: "",
      website: "https://www.nps.gov/timu",
    },
  ],
  restaurants: [
    {
      name: "The Salty Pelican Bar & Grill",
      address: "12 N Front St, Fernandina Beach, FL 32034",
      lat: 30.6710,
      lng: -81.4650,
      cuisine: "Seafood & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the waterfront deck overlooking the marina. Fresh seafood and cold drinks with shrimp boat views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.saltypelican.net",
    },
    {
      name: "Espana Restaurant & Tapas Bar",
      address: "22 S 4th St, Fernandina Beach, FL 32034",
      lat: 30.6700,
      lng: -81.4600,
      cuisine: "Spanish Tapas",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the courtyard patio. Authentic Spanish tapas and paella in a romantic courtyard setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.espanadowntown.com",
    },
    {
      name: "T-Rays Burger Station",
      address: "202 S 8th St, Fernandina Beach, FL 32034",
      lat: 30.6680,
      lng: -81.4560,
      cuisine: "Burgers & Breakfast",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor picnic tables. A converted gas station famous for breakfast and burgers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.traysburgerstation.com",
    },
    {
      name: "Timoti's Seafood Shak",
      address: "21 N 3rd St, Fernandina Beach, FL 32034",
      lat: 30.6710,
      lng: -81.4610,
      cuisine: "Seafood",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor window-side seating. Fresh fish tacos, poke bowls, and seafood baskets.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.timotis.com",
    },
    {
      name: "Pogo's Kitchen",
      address: "1603 N 14th St, Fernandina Beach, FL 32034",
      lat: 30.6790,
      lng: -81.4490,
      cuisine: "New American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the spacious outdoor patio. Creative seasonal fare with a neighborhood feel.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.pogoskitchen.com",
    },
  ],
  cafes: [
    {
      name: "Amelia Island Coffee",
      address: "207 Centre St, Fernandina Beach, FL 32034",
      lat: 30.6710,
      lng: -81.4590,
      dogPolicy: "Dogs welcome on the Centre Street patio. A cozy coffee shop in the heart of the historic downtown.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ameliaislandcoffee.com",
    },
    {
      name: "Peterbrooke Chocolatier",
      address: "218 Centre St, Fernandina Beach, FL 32034",
      lat: 30.6710,
      lng: -81.4585,
      dogPolicy: "Dogs welcome at the outdoor tables. Gourmet chocolates and coffee on the main shopping street.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.peterbrooke.com",
    },
    {
      name: "Provisions",
      address: "12 N 2nd St, Fernandina Beach, FL 32034",
      lat: 30.6710,
      lng: -81.4620,
      dogPolicy: "Dogs welcome on the outdoor patio. Fresh coffee, pastries, and gourmet provisions in a charming shop.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.provisionsfb.com",
    },
    {
      name: "Island Bagel & Grill",
      address: "2418 Sadler Rd, Fernandina Beach, FL 32034",
      lat: 30.6550,
      lng: -81.4530,
      dogPolicy: "Dog-friendly outdoor seating. Fresh-baked bagels, breakfast sandwiches, and coffee south of downtown.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.islandbagelandgrill.com",
    },
  ],
  dogParks: [
    {
      name: "Peters Point Beach",
      address: "1974 S Fletcher Ave, Fernandina Beach, FL 32034",
      lat: 30.6480,
      lng: -81.4420,
      offLeash: false,
      fenced: false,
      acres: 10,
      amenities: ["Beach access", "Boardwalk", "Picnic pavilion", "Outdoor showers", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "One of the best beach access points on Amelia Island for dogs. The wide, uncrowded beach allows leashed dogs to enjoy the sand and surf. The adjacent park has picnic areas and shade.",
    },
    {
      name: "Scott Road Dog Park",
      address: "Scott Rd, Fernandina Beach, FL 32034",
      lat: 30.6600,
      lng: -81.4530,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade trees", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "The island's dedicated off-leash dog park provides fenced play areas for both large and small dogs. A great option when your pup needs off-leash time away from the beach.",
    },
    {
      name: "Fort Clinch Beach Walk",
      address: "2601 Atlantic Ave, Fernandina Beach, FL 32034",
      lat: 30.6990,
      lng: -81.4360,
      offLeash: false,
      fenced: false,
      acres: 20,
      amenities: ["Beach access", "Jetty views", "Fort exploration", "Nature trails", "Waste bag stations"],
      rating: 4.7,
      imageUrl: "",
      description: "The beach at Fort Clinch offers one of the most scenic dog walks on the island with views of the St. Marys River jetties and the historic fort. Leashed dogs can explore the beach and adjacent trails.",
    },
    {
      name: "Egans Creek Greenway",
      address: "Atlantic Ave, Fernandina Beach, FL 32034",
      lat: 30.6700,
      lng: -81.4520,
      offLeash: false,
      fenced: false,
      acres: 300,
      amenities: ["Boardwalk trails", "Marsh views", "Bird watching", "Shaded canopy", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "A stunning 300-acre urban greenway following Egans Creek through maritime forest and salt marsh. Dogs on leash can explore the boardwalk trails and elevated overlooks with views of wading birds and marsh wildlife.",
    },
  ],
};
