export const annArborData = {
  city: {
    name: "Ann Arbor",
    state: "Michigan",
    region: "Midwest",
    lat: 42.2808,
    lng: -83.7430,
    dogFriendlinessScore: 8,
    description:
      "Ann Arbor is a progressive college town where dogs are practically honorary University of Michigan students. With an impressive network of nature areas, a vibrant downtown full of dog-friendly patios, and a community that adores pets, this is one of the Midwest's best cities for dogs.",
    heroImage: "https://images.unsplash.com/photo-1568992688065-536aad8a12f6?w=1200&fit=crop",
    climate: "Humid continental",
    population: 123851,
  },

  hotels: [
    {
      name: "Graduate Ann Arbor",
      address: "615 E Huron St, Ann Arbor, MI 48104",
      lat: 42.2820,
      lng: -83.7400,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a one-time pet fee. University-themed boutique hotel steps from campus.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Treats", "Walking maps", "Central campus location"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.graduatehotels.com",
      phone: "(734) 769-2200",
    },
    {
      name: "Residence Inn Ann Arbor Downtown",
      address: "120 W Huron St, Ann Arbor, MI 48104",
      lat: 42.2815,
      lng: -83.7490,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a non-refundable fee. Spacious suites with full kitchens ideal for longer stays.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Full kitchen", "Grassy areas", "Near Huron River", "Waste stations", "Grocery delivery"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(734) 662-9999",
    },
    {
      name: "Weber's Boutique Hotel",
      address: "3050 Jackson Ave, Ann Arbor, MI 48103",
      lat: 42.2780,
      lng: -83.7870,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 60 lbs welcome in designated pet rooms. Classic Ann Arbor establishment.",
      maxDogWeight: 60,
      petFee: 40,
      amenities: ["Dog bed", "Water bowls", "Grassy grounds", "Near trails", "Restaurant on-site"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.webershotel.com",
      phone: "(734) 769-2500",
    },
    {
      name: "The Bell Tower Hotel",
      address: "300 S Thayer St, Ann Arbor, MI 48104",
      lat: 42.2790,
      lng: -83.7405,
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome with advance notice and pet deposit. Elegant campus-adjacent hotel.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Walking route to Arboretum", "Campus views", "Concierge services"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.belltowerhotel.com",
      phone: "(734) 769-3010",
    },
  ],

  nationalParks: [
    {
      name: "Nichols Arboretum",
      state: "Michigan",
      lat: 42.2810,
      lng: -83.7260,
      dogPolicy: "Leashed dogs welcome on all trails. A 123-acre living museum of trees and natural areas.",
      dogTrails: ["Peony Garden Loop", "Huron River Trail", "Prairie Trail", "Ridge Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Stay on designated trails",
        "Clean up after your pet",
      ],
      description:
        "Known locally as 'the Arb,' this 123-acre nature area features rolling hills, a Huron River shoreline, and diverse plant collections. Dogs love the varied terrain and river access at the eastern edge.",
      imageUrl: "",
      website: "https://mbgna.umich.edu/nichols-arboretum",
    },
    {
      name: "Waterloo State Recreation Area",
      state: "Michigan",
      lat: 42.3400,
      lng: -84.1020,
      dogPolicy: "Leashed dogs welcome on trails and in campgrounds. Michigan's largest state park at over 20,000 acres.",
      dogTrails: ["Waterloo-Pinckney Trail", "Bog Trail", "Oak Woods Trail", "Sackrider Hill Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on swimming beaches",
        "Must stay on designated trails",
      ],
      description:
        "About 30 minutes west of Ann Arbor, this massive recreation area offers lakes, forests, and rolling hills. The Waterloo-Pinckney Trail provides a challenging and rewarding hike through diverse Michigan landscapes.",
      imageUrl: "",
      website: "https://www.michigan.gov/waterloo",
    },
    {
      name: "Huron Meadows Metropark",
      state: "Michigan",
      lat: 42.3740,
      lng: -83.8450,
      dogPolicy: "Leashed dogs allowed on all trails. Scenic Huron River frontage with gentle terrain.",
      dogTrails: ["River Trail", "Meadow Loop", "Fitness Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed in the golf course area",
        "Not permitted on cross-country ski trails in winter",
      ],
      description:
        "This Metropark north of Ann Arbor features gentle trails along the Huron River, meadows, and mature forests. The flat terrain makes it accessible for dogs of all ages and abilities.",
      imageUrl: "",
      website: "https://www.metroparks.com",
    },
  ],

  restaurants: [
    {
      name: "Jolly Pumpkin Cafe & Brewery",
      address: "311 S Main St, Ann Arbor, MI 48104",
      lat: 42.2786,
      lng: -83.7485,
      cuisine: "American Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the spacious outdoor patio. Artisan ales and creative pub food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.jollypumpkin.com",
    },
    {
      name: "Frita Batidos",
      address: "117 W Washington St, Ann Arbor, MI 48104",
      lat: 42.2810,
      lng: -83.7495,
      cuisine: "Cuban-Inspired Street Food",
      priceRange: "$" as const,
      dogPolicy: "Leashed dogs welcome at sidewalk tables. Cuban-style burgers and tropical shakes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.fritabatidos.com",
    },
    {
      name: "Mani Osteria",
      address: "341 E Liberty St, Ann Arbor, MI 48104",
      lat: 42.2795,
      lng: -83.7440,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the patio. Wood-fired pizzas and handmade pasta.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.maniosteria.com",
    },
    {
      name: "Zingerman's Roadhouse",
      address: "2501 Jackson Ave, Ann Arbor, MI 48103",
      lat: 42.2790,
      lng: -83.7810,
      cuisine: "American Regional",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Part of the legendary Zingerman's community of businesses.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.zingermansroadhouse.com",
    },
    {
      name: "Sava's",
      address: "216 S State St, Ann Arbor, MI 48104",
      lat: 42.2793,
      lng: -83.7430,
      cuisine: "Mediterranean",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the State Street patio. A vibrant campus-area favorite.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.savasrestaurant.com",
    },
  ],

  cafes: [
    {
      name: "Literati Bookstore & Cafe",
      address: "124 E Washington St, Ann Arbor, MI 48104",
      lat: 42.2810,
      lng: -83.7470,
      dogPolicy: "Dogs welcome at outdoor tables. Independent bookstore with a charming upstairs cafe.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.literatibookstore.com",
    },
    {
      name: "Comet Coffee",
      address: "205 N Main St, Ann Arbor, MI 48104",
      lat: 42.2825,
      lng: -83.7490,
      dogPolicy: "Patio seating welcomes dogs. Precision-brewed specialty coffee in a sleek space.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cometcoffee.com",
    },
    {
      name: "Roos Roast Coffee",
      address: "1155 Rosewood St, Ann Arbor, MI 48104",
      lat: 42.2700,
      lng: -83.7350,
      dogPolicy: "Very dog-friendly with outdoor seating and treats for pups. Locally roasted beans.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.roosroast.com",
    },
    {
      name: "Mighty Good Coffee",
      address: "217 N Main St, Ann Arbor, MI 48104",
      lat: 42.2827,
      lng: -83.7490,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Quality coffee in a laid-back downtown setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.mightygoodcoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Swift Run Dog Park",
      address: "2401 Ellsworth Rd, Ann Arbor, MI 48108",
      lat: 42.2480,
      lng: -83.7240,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: ["Separate small dog area", "Water fountains", "Shade shelters", "Agility equipment", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Ann Arbor's largest fenced dog park offers separate areas for large and small dogs, plus agility equipment. The well-maintained grounds and active community make it the city's top off-leash destination.",
    },
    {
      name: "Olson Park Dog Park",
      address: "1515 Dhu Varren Rd, Ann Arbor, MI 48105",
      lat: 42.3050,
      lng: -83.7310,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Double-gated entry", "Water spigots", "Benches", "Shade trees", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A well-loved north-side dog park with a friendly community. The grassy terrain and shade trees make it comfortable even on warm summer days.",
    },
    {
      name: "Bandemer Park",
      address: "1352 Lakeshore Dr, Ann Arbor, MI 48103",
      lat: 42.2920,
      lng: -83.7630,
      offLeash: false,
      fenced: false,
      acres: 25.0,
      amenities: ["Huron River access", "Walking trails", "Open fields", "Canoe launch", "Picnic areas"],
      rating: 4.4,
      imageUrl: "",
      description:
        "While on-leash, this park along the Huron River is a dog favorite thanks to river access for swimming and wading. The trails connect to the Border-to-Border Trail for extended walks.",
    },
    {
      name: "Dixboro Dog Park",
      address: "5765 Plymouth Rd, Ann Arbor, MI 48105",
      lat: 42.3020,
      lng: -83.6940,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Double-gated entry", "Water fountain", "Benches", "Waste stations", "Parking"],
      rating: 4.1,
      imageUrl: "",
      description:
        "A cozy east-side dog park that rarely gets overcrowded. Perfect for dogs who prefer a quieter, more relaxed play environment with familiar faces.",
    },
  ],
};
