export const annapolisData = {
  city: {
    name: "Annapolis",
    state: "Maryland",
    region: "Northeast",
    lat: 38.9784,
    lng: -76.4922,
    dogFriendlinessScore: 7,
    description:
      "Maryland's charming capital city on the Chesapeake Bay offers dogs a waterfront wonderland of sailing harbor views, historic brick streets, and nearby state parks. The compact downtown is highly walkable, and the maritime culture creates a relaxed atmosphere where dogs are welcomed warmly.",
    heroImage: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 40812,
  },
  hotels: [
    {
      name: "Graduate Annapolis",
      address: "126 West St, Annapolis, MD 21401",
      lat: 38.9779,
      lng: -76.4968,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a $50 per stay fee. Walking distance to City Dock and the Naval Academy.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Downtown location", "Pet bed", "Near City Dock", "Walking maps", "Restaurant"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.graduatehotels.com/annapolis",
      phone: "(410) 263-7777",
    },
    {
      name: "Loews Annapolis Hotel",
      address: "126 West St, Annapolis, MD 21401",
      lat: 38.9776,
      lng: -76.4972,
      priceRange: "$$$" as const,
      dogPolicy: "Loews Loves Pets program welcomes dogs with no deposit required. Pet room service menu and walking routes provided.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pet room service", "Walking routes", "Dog bed", "Downtown location"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.loewshotels.com/annapolis",
      phone: "(410) 263-7777",
    },
    {
      name: "Country Inn & Suites Annapolis",
      address: "2600 Housley Rd, Annapolis, MD 21401",
      lat: 38.9964,
      lng: -76.5354,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a $50 non-refundable fee. Free breakfast and grassy pet exercise area.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Pet exercise area", "Free breakfast", "Pool", "Free parking"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.radissonhotels.com",
      phone: "(410) 571-6700",
    },
    {
      name: "Westin Annapolis",
      address: "100 Westgate Cir, Annapolis, MD 21401",
      lat: 38.9726,
      lng: -76.5039,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a $50 per stay fee. Heavenly Pet Bed and food bowls provided.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Pet bed", "Food bowls", "Near Park Place", "Pool", "Spa"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(410) 972-4300",
    },
  ],
  nationalParks: [
    {
      name: "Sandy Point State Park",
      state: "Maryland",
      lat: 39.0139,
      lng: -76.4005,
      dogPolicy: "Leashed dogs welcome on trails and in picnic areas. Chesapeake Bay beaches with Bay Bridge views.",
      dogTrails: ["East Beach Trail", "South Beach Trail", "Nature Trail", "Bay Shore Path"],
      restrictions: ["Leash required", "No dogs on guarded beaches Memorial Day-Labor Day", "Clean up required"],
      description:
        "A 786-acre park on the western shore of the Chesapeake Bay with sandy beaches, nature trails, and spectacular views of the Bay Bridge. During the off-season, dogs can explore the beaches and wade in the bay. The nature trails through maritime forest are lovely year-round.",
      imageUrl: "",
      website: "https://dnr.maryland.gov/publiclands/pages/southern/sandypoint.aspx",
    },
    {
      name: "Quiet Waters Park",
      state: "Maryland",
      lat: 38.9505,
      lng: -76.4847,
      dogPolicy: "Dogs welcome on all trails and at the dedicated dog beach. One of the best dog parks in Maryland.",
      dogTrails: ["South River Trail", "Harness Creek Trail", "Blue Heron Trail", "Dog Beach Trail"],
      restrictions: ["Leash required on trails", "Off-leash only in dog park and dog beach", "Clean up required"],
      description:
        "A 340-acre park along the South River featuring six miles of paved and natural trails, formal gardens, and a beloved dog beach where pups can swim in the river. The dedicated off-leash dog park is one of the best in Maryland. Art galleries, a cafe, and stunning water views complete the picture.",
      imageUrl: "",
      website: "https://www.aacounty.org/departments/recreation-parks/parks/quiet-waters",
    },
    {
      name: "Bacon Ridge Natural Area",
      state: "Maryland",
      lat: 38.9895,
      lng: -76.604,
      dogPolicy: "Dogs welcome on all trails. An extensive mountain biking and hiking trail network through forested hills.",
      dogTrails: ["Bacon Ridge Trail", "Ridge Runner Trail", "Lollipop Loop", "Perimeter Trail"],
      restrictions: ["Leash required", "Share trails with mountain bikers", "Clean up required"],
      description:
        "Over 400 acres of forested trails just west of Annapolis offering a surprisingly rugged outdoor experience close to the city. The rolling terrain and diverse forest provide excellent hiking for dogs, and the network of trails allows for loops of varying distance and difficulty.",
      imageUrl: "",
      website: "https://www.aacounty.org",
    },
  ],
  restaurants: [
    {
      name: "Boatyard Bar & Grill",
      address: "400 4th St, Annapolis, MD 21403",
      lat: 38.9698,
      lng: -76.4784,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Sailing-themed restaurant with a dog-friendly outdoor deck. Fresh Chesapeake Bay seafood with harbor views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.boatyardbarandgrill.com",
    },
    {
      name: "Iron Rooster",
      address: "12 Market Space, Annapolis, MD 21401",
      lat: 38.9773,
      lng: -76.4912,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "All-day breakfast spot with outdoor seating at City Dock. Dogs welcome on the patio. Famous for their bacon.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ironroosterallday.com",
    },
    {
      name: "Preserve",
      address: "164 Main St, Annapolis, MD 21401",
      lat: 38.9781,
      lng: -76.4922,
      cuisine: "American",
      priceRange: "$$$" as const,
      dogPolicy: "Farm-to-table restaurant with a seasonal patio on Main Street. Leashed dogs welcome outside.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.preserveannapolis.com",
    },
    {
      name: "Sailors Tavern",
      address: "123 Main St, Annapolis, MD 21401",
      lat: 38.9778,
      lng: -76.4919,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Main Street tavern with sidewalk seating. Dogs welcome at outdoor tables. Classic pub fare and craft cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Eastport Kitchen",
      address: "909 Bay Ridge Ave, Annapolis, MD 21403",
      lat: 38.9693,
      lng: -76.4804,
      cuisine: "Southern",
      priceRange: "$$" as const,
      dogPolicy: "Maritime district restaurant with a dog-friendly patio. Southern comfort food in the heart of Eastport.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
  ],
  cafes: [
    {
      name: "City Dock Coffee",
      address: "18 Market Space, Annapolis, MD 21401",
      lat: 38.9772,
      lng: -76.4913,
      dogPolicy: "Waterfront coffee shop with outdoor seating overlooking City Dock. Dogs welcome while you watch sailboats come and go.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.citydockcoffee.com",
    },
    {
      name: "Ceremony Coffee Roasters",
      address: "130 Dock St, Annapolis, MD 21401",
      lat: 38.9775,
      lng: -76.4908,
      dogPolicy: "Third-wave coffee roaster near the waterfront. Outdoor seating and dog-friendly vibes.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ceremonycoffee.com",
    },
    {
      name: "49 West Coffeehouse",
      address: "49 West St, Annapolis, MD 21401",
      lat: 38.978,
      lng: -76.4963,
      dogPolicy: "Artsy coffeehouse with live music and a patio. Dogs welcome outside. A cozy local gathering spot.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.49westcoffeehouse.com",
    },
    {
      name: "Rise Up Coffee Roasters",
      address: "201 Main St, Annapolis, MD 21401",
      lat: 38.9785,
      lng: -76.4928,
      dogPolicy: "Eastern Shore roaster with a Main Street location. Outdoor tables for enjoying coffee with your pup in the historic district.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.riseupcoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Quiet Waters Dog Park",
      address: "600 Quiet Waters Park Rd, Annapolis, MD 21403",
      lat: 38.9505,
      lng: -76.4847,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Dog beach", "Separate small dog area", "Water fountains", "Shade", "River access"],
      rating: 4.7,
      imageUrl: "",
      description:
        "One of Maryland's best dog parks with a fenced off-leash area, separate small dog section, and a dog beach on the South River where pups can swim. The park's beautiful setting along the water with mature trees and well-maintained grounds makes it worth the trip from anywhere in the region.",
    },
    {
      name: "City Dock & Ego Alley",
      address: "1 Dock St, Annapolis, MD 21401",
      lat: 38.9766,
      lng: -76.4898,
      offLeash: false,
      fenced: false,
      acres: 2.0,
      amenities: ["Harbor views", "Boat watching", "Shops nearby", "Restaurants", "Benches"],
      rating: 4.4,
      imageUrl: "",
      description:
        "The heart of Annapolis where Ego Alley's parade of boats provides endless entertainment for dogs and humans alike. Walk your leashed pup along the city dock, past the Market House, and along the waterfront. The compact downtown means treats and patio dining are always steps away.",
    },
    {
      name: "Jonas Green State Park Area",
      address: "Chesapeake Bay, Annapolis, MD 21409",
      lat: 39.0045,
      lng: -76.4322,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Bay Bridge views", "Fishing pier", "Walking paths", "Beach access", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A waterfront park beneath the Bay Bridge with dramatic views of the span crossing the Chesapeake. Your leashed dog can walk along the shoreline and enjoy the bay breezes while watching massive ships pass underneath the bridge. A unique perspective on Maryland's most iconic structure.",
    },
    {
      name: "Truxtun Park",
      address: "273 Hilltop Ln, Annapolis, MD 21403",
      lat: 38.9695,
      lng: -76.5012,
      offLeash: true,
      fenced: true,
      acres: 1.0,
      amenities: ["Fenced dog park", "Water fountain", "Benches", "Shade", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A community dog park within Truxtun Park offering a fenced off-leash area for dogs of all sizes. The well-shaded space is popular with neighborhood regulars and provides a reliable off-leash option close to downtown Annapolis.",
    },
  ],
};
