export const ashevilleData = {
  city: {
    name: "Asheville",
    state: "North Carolina",
    region: "Southeast",
    lat: 35.5951,
    lng: -82.5515,
    dogFriendlinessScore: 8,
    description:
      "Nestled in the Blue Ridge Mountains, Asheville is a bohemian mountain town where dogs are woven into the fabric of daily life. With more breweries per capita than almost anywhere in the US (most of them dog-friendly), stunning Appalachian trail access, and a quirky downtown where pups are greeted like celebrities, Asheville is a tail-wagging mountain retreat.",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1200&fit=crop",
    climate: "Humid Subtropical (Mountain)",
    population: 94589,
  },
  hotels: [
    {
      name: "Aloft Asheville Downtown",
      address: "51 Biltmore Ave, Asheville, NC 28801",
      lat: 35.5935,
      lng: -82.5524,
      priceRange: "$$" as const,
      dogPolicy: "Arf (Animals R Fun) program — dogs of all sizes welcome",
      maxDogWeight: 0,
      petFee: 0,
      amenities: [
        "Dog bed",
        "Food and water bowls",
        "Treats at check-in",
        "Pet relief area",
        "Toy lending library",
      ],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.marriott.com/aloft-asheville",
      phone: "(828) 232-2838",
    },
    {
      name: "Foundry Hotel Asheville",
      address: "51 S Market St, Asheville, NC 28801",
      lat: 35.5922,
      lng: -82.5565,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome, max 1 per room",
      maxDogWeight: 50,
      petFee: 75,
      amenities: [
        "Luxury dog bed",
        "Artisan treat bag",
        "Walking map of downtown trails",
        "Dog-sitting referrals",
      ],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.foundryhotelasheville.com",
      phone: "(828) 552-8545",
    },
    {
      name: "The Omni Grove Park Inn",
      address: "290 Macon Ave, Asheville, NC 28804",
      lat: 35.6106,
      lng: -82.5637,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 25 lbs welcome in select rooms",
      maxDogWeight: 25,
      petFee: 125,
      amenities: [
        "Dog bed",
        "Mountain trail access",
        "Gourmet treats",
        "Dog walking service",
        "Sunset terrace access",
      ],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.omnihotels.com/grove-park-inn",
      phone: "(828) 252-2711",
    },
    {
      name: "Sweet Biscuit Inn",
      address: "73 Kenilworth Rd, Asheville, NC 28803",
      lat: 35.5831,
      lng: -82.5405,
      priceRange: "$$" as const,
      dogPolicy:
        "Dog-friendly B&B — all sizes welcome with advance notice, 2 pets max",
      maxDogWeight: 0,
      petFee: 40,
      amenities: [
        "Dog treats on pillow",
        "Fenced backyard access",
        "Cozy dog blankets",
        "Trail recommendations from innkeeper",
      ],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.sweetbiscuitinn.com",
      phone: "(828) 250-0170",
    },
    {
      name: "AC Hotel by Marriott Asheville Downtown",
      address: "10 Broadway St, Asheville, NC 28801",
      lat: 35.5953,
      lng: -82.5539,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome, 2 pets max",
      maxDogWeight: 50,
      petFee: 50,
      amenities: [
        "Dog bed",
        "Welcome treats",
        "Rooftop bar access (dogs on leash)",
        "Downtown walking proximity",
      ],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.marriott.com/ac-asheville",
      phone: "(828) 258-2522",
    },
  ],
  nationalParks: [
    {
      name: "Blue Ridge Parkway",
      state: "North Carolina",
      lat: 35.5652,
      lng: -82.4883,
      dogPolicy: "Dogs allowed on most trails and overlooks on leash",
      dogTrails: [
        "Craggy Gardens Trail",
        "Graveyard Fields Loop",
        "Waterrock Knob Trail",
        "Folk Art Center Nature Trail",
        "Bad Fork Valley Overlook Trail",
      ],
      restrictions: [
        "Must be on 6-foot leash",
        "Not allowed in visitor center buildings",
        "Some tunnel trails restricted",
        "Clean up after pet",
      ],
      description:
        "America's favorite scenic drive winds through the Blue Ridge Mountains with jaw-dropping overlooks, wildflower meadows, and misty peaks. Dogs can join on most trails, making this one of the most dog-friendly national park experiences in the Southeast.",
      imageUrl: "",
      website: "https://www.nps.gov/blri",
    },
    {
      name: "Great Smoky Mountains National Park",
      state: "North Carolina",
      lat: 35.6118,
      lng: -83.4895,
      dogPolicy:
        "Dogs allowed on two specific trails and in campgrounds on leash",
      dogTrails: ["Gatlinburg Trail", "Oconaluftee River Trail"],
      restrictions: [
        "Must be on 6-foot leash",
        "Only allowed on 2 designated trails",
        "Not allowed on any other trails or in the backcountry",
        "Not allowed in buildings",
        "Cannot be left unattended",
      ],
      description:
        "The most visited national park in America offers limited but beautiful dog-friendly options. The Oconaluftee River Trail is a paved riverside path where dogs can enjoy the sounds of rushing water and towering old-growth trees.",
      imageUrl: "",
      website: "https://www.nps.gov/grsm",
    },
    {
      name: "Pisgah National Forest",
      state: "North Carolina",
      lat: 35.3421,
      lng: -82.7718,
      dogPolicy: "Dogs welcome on all trails on leash",
      dogTrails: [
        "Looking Glass Rock Trail",
        "Moore Cove Falls Trail",
        "Catawba Falls Trail",
        "Daniel Ridge Falls Trail",
        "Black Balsam Knob Trail",
      ],
      restrictions: [
        "Must be on leash in developed areas",
        "Voice control acceptable on remote trails (varies by area)",
        "Clean up after pet",
      ],
      description:
        "Over 500,000 acres of ancient Appalachian forest with thundering waterfalls, swimming holes, and panoramic balds. Dogs can tackle nearly every trail, from easy waterfall walks to challenging summit hikes through rhododendron tunnels.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/nfsnc/pisgah",
    },
    {
      name: "DuPont State Recreational Forest",
      state: "North Carolina",
      lat: 35.2087,
      lng: -82.6178,
      dogPolicy: "Dogs welcome on all trails on leash",
      dogTrails: [
        "Triple Falls Trail",
        "Hooker Falls Trail",
        "High Falls Trail",
        "Bridal Veil Falls Trail",
        "Lake Julia Trail",
      ],
      restrictions: [
        "Must be on leash",
        "No swimming in falls areas (for dogs or humans)",
        "Clean up after pet",
      ],
      description:
        "A waterfall wonderland featured in The Hunger Games films. Dogs can explore miles of trails past six major waterfalls, through hardwood forests, and around serene mountain lakes. The Hooker Falls trail is an easy, pup-perfect stroll.",
      imageUrl: "",
      website: "https://www.dupontstaterecreationalforest.com",
    },
    {
      name: "Bent Creek Experimental Forest",
      state: "North Carolina",
      lat: 35.4862,
      lng: -82.6307,
      dogPolicy: "Dogs welcome on all trails — off-leash in some areas",
      dogTrails: [
        "Homestead Trail",
        "Deerfield Loop",
        "Pine Tree Loop",
        "Explorer Loop",
        "Small Creek Trail",
      ],
      restrictions: [
        "Must be under voice control if off-leash",
        "Leash required near Lake Powhatan",
        "Clean up after pet",
      ],
      description:
        "A local favorite just minutes from downtown Asheville with gentle forest trails perfect for dogs of all fitness levels. The extensive trail network winds through hardwood forests and alongside creeks, and many locals let well-trained dogs run off-leash here.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/bentcreek",
    },
  ],
  restaurants: [
    {
      name: "Wedge Brewing Company",
      address: "37 Paynes Way, Asheville, NC 28801",
      lat: 35.5849,
      lng: -82.5653,
      cuisine: "Brewery & Food Trucks",
      priceRange: "$" as const,
      dogPolicy:
        "Dogs welcome everywhere — outdoor taproom is a dog party every evening",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.wedgebrewing.com",
    },
    {
      name: "Biscuit Head",
      address: "733 Haywood Rd, Asheville, NC 28806",
      lat: 35.5908,
      lng: -82.5757,
      cuisine: "Southern Breakfast",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the patio — get there early, lines are long",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.biscuitheads.com",
    },
    {
      name: "White Duck Taco Shop",
      address: "12 Biltmore Ave, Asheville, NC 28801",
      lat: 35.5941,
      lng: -82.5518,
      cuisine: "Creative Tacos",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.whiteducktacoshop.com",
    },
    {
      name: "Burial Beer Co.",
      address: "40 Collier Ave, Asheville, NC 28801",
      lat: 35.5849,
      lng: -82.5572,
      cuisine: "Brewery & Bites",
      priceRange: "$$" as const,
      dogPolicy:
        "Dogs welcome in the outdoor beer garden — dark and moody vibes for your goth pup",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.burialbeer.com",
    },
    {
      name: "Chai Pani",
      address: "22 Battery Park Ave, Asheville, NC 28801",
      lat: 35.5951,
      lng: -82.5545,
      cuisine: "Indian Street Food",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor sidewalk tables",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.8,
      imageUrl: "",
      website: "https://www.chaipaniasheville.com",
    },
    {
      name: "Sunny Point Café",
      address: "626 Haywood Rd, Asheville, NC 28806",
      lat: 35.5905,
      lng: -82.5731,
      cuisine: "Farm-to-Table Brunch",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the garden patio area — treats on request",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.sunnypointcafe.com",
    },
    {
      name: "12 Bones Smokehouse",
      address: "5 Foundy St, Asheville, NC 28801",
      lat: 35.5722,
      lng: -82.5627,
      cuisine: "BBQ",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in outdoor seating area — famous for a reason",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.12bones.com",
    },
    {
      name: "Rhubarb",
      address: "7 SW Pack Square, Asheville, NC 28801",
      lat: 35.5944,
      lng: -82.5519,
      cuisine: "Appalachian Fine Dining",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the Pack Square patio during lunch and brunch",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.rhubarbasheville.com",
    },
  ],
  cafes: [
    {
      name: "Vortex Doughnuts & Coffee",
      address: "32 Banks Ave, Asheville, NC 28801",
      lat: 35.5873,
      lng: -82.5574,
      dogPolicy:
        "Patio friendly with some of the best doughnuts your human will ever taste",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.vortexdoughnuts.com",
    },
    {
      name: "Trade and Lore Coffee",
      address: "37 Wall St, Asheville, NC 28801",
      lat: 35.5947,
      lng: -82.5512,
      dogPolicy: "Outdoor seating welcomes dogs, cozy mountain coffee vibes",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.tradeandlore.com",
    },
    {
      name: "PennyCup Coffee Co.",
      address: "67 Broadway St, Asheville, NC 28801",
      lat: 35.5955,
      lng: -82.5538,
      dogPolicy: "Patio dogs welcome, locally roasted beans",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.pennycupcoffee.com",
    },
    {
      name: "Odd's Café",
      address: "800 Haywood Rd, Asheville, NC 28806",
      lat: 35.5912,
      lng: -82.5773,
      dogPolicy: "Garden patio is a dog haven with water bowls and shade",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Ultra Coffeebar",
      address: "242 Clingman Ave, Asheville, NC 28801",
      lat: 35.5868,
      lng: -82.5626,
      dogPolicy:
        "Spacious patio with dog-friendly seating and River Arts District views",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.ultracoffeebar.com",
    },
  ],
  dogParks: [
    {
      name: "Azalea Dog Park",
      address: "Azalea Rd, Asheville, NC 28803",
      lat: 35.5617,
      lng: -82.5287,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: [
        "Separate small dog area",
        "Water fountains",
        "Shade structures",
        "Agility equipment",
        "Benches",
      ],
      rating: 4.5,
      imageUrl: "",
      description:
        "Asheville's premier fenced dog park with separate areas for large and small dogs, agility equipment to keep active pups entertained, and mountain views peeking through the trees. A beloved gathering spot for the local dog community.",
    },
    {
      name: "French Broad River Dog Park",
      address: "508 Riverview Dr, Asheville, NC 28806",
      lat: 35.5814,
      lng: -82.5718,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: [
        "River access",
        "Walking trails",
        "Water fountains",
        "Waste stations",
        "Shade trees",
      ],
      rating: 4.6,
      imageUrl: "",
      description:
        "A riverside dog park where pups can splash in the French Broad River and then dry off with a romp through the fenced play area. The river access makes this park special — water dogs lose their minds here.",
    },
    {
      name: "Carrier Park Dog Run",
      address: "220 Amboy Rd, Asheville, NC 28806",
      lat: 35.576,
      lng: -82.5756,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: [
        "Walking paths",
        "Water fountains",
        "Benches",
        "Adjacent greenway trail",
        "Waste stations",
      ],
      rating: 4.3,
      imageUrl: "",
      description:
        "A fenced off-leash area within the larger Carrier Park complex along the French Broad River. After playtime, leash up and explore the adjacent greenway trail for a riverside stroll with mountain views.",
    },
    {
      name: "Biltmore Park Dog Area",
      address: "Biltmore Park Town Square, Asheville, NC 28803",
      lat: 35.5432,
      lng: -82.5313,
      offLeash: true,
      fenced: true,
      acres: 1.0,
      amenities: [
        "Water fountains",
        "Benches",
        "Shade trees",
        "Double-gated entry",
        "Nearby shops and restaurants",
      ],
      rating: 4.2,
      imageUrl: "",
      description:
        "A convenient fenced dog park within the Biltmore Park development. While compact, it's perfect for a quick play session before or after visiting the nearby shops and restaurants — many of which are dog-friendly too.",
    },
    {
      name: "Hominy Creek Dog Park",
      address: "Shelburne Rd, Asheville, NC 28806",
      lat: 35.5726,
      lng: -82.5982,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: [
        "Creek access",
        "Open meadow",
        "Water fountains",
        "Shade structures",
        "Waste stations",
      ],
      rating: 4.4,
      imageUrl: "",
      description:
        "A tucked-away gem in West Asheville with creek access for water-loving dogs and a wide open meadow for zoomies. The surrounding trees and mountain backdrop make it feel more like a private estate than a public park.",
    },
  ],
};
