export const ashlandOrData = {
  city: {
    name: "Ashland",
    state: "Oregon",
    region: "Pacific Northwest",
    lat: 42.1946,
    lng: -122.7095,
    dogFriendlinessScore: 8,
    description:
      "Ashland is a cultured mountain town famous for the Oregon Shakespeare Festival, but dogs love it for the extensive trail system in the Siskiyou Mountains and Lithia Park. The artsy downtown is full of dog-friendly patios and boutiques, and the mild Rogue Valley climate means year-round outdoor adventures.",
    heroImage: "https://images.unsplash.com/photo-1510797215324-95aa89f43c33?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 21360,
  },

  hotels: [
    {
      name: "Ashland Hills Hotel & Suites",
      address: "2525 Ashland St, Ashland, OR 97520",
      lat: 42.1870,
      lng: -122.6850,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in designated pet rooms with a per-night fee. Large grounds with walking paths.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Dog bed", "Water bowls", "Walking trails on property", "Grassy areas", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.ashlandhillshotel.com",
      phone: "(541) 482-8310",
    },
    {
      name: "The Ashland Springs Hotel",
      address: "212 E Main St, Ashland, OR 97520",
      lat: 42.1948,
      lng: -122.7085,
      priceRange: "$$$" as const,
      dogPolicy: "Small dogs welcome in select rooms. Historic 1925 landmark hotel in the heart of downtown.",
      maxDogWeight: 25,
      petFee: 50,
      amenities: ["Dog bed", "Treats at check-in", "Water bowls", "Walking map", "Near Lithia Park"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.ashlandspringshotel.com",
      phone: "(541) 488-1700",
    },
    {
      name: "Best Western Windsor Inn",
      address: "2520 Ashland St, Ashland, OR 97520",
      lat: 42.1872,
      lng: -122.6860,
      priceRange: "$" as const,
      dogPolicy: "Two dogs per room allowed with a modest pet fee. Convenient location near I-5.",
      maxDogWeight: 80,
      petFee: 20,
      amenities: ["Pet waste stations", "Grassy areas", "Water bowls at front desk", "Near walking trails"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(541) 488-2330",
    },
    {
      name: "Plaza Inn & Suites at Ashland Creek",
      address: "98 Central Ave, Ashland, OR 97520",
      lat: 42.1940,
      lng: -122.7105,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in garden-level suites with direct patio access. Steps from Lithia Park and Ashland Creek.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Private patio", "Dog bed", "Treats", "Creek access nearby", "Lithia Park walking"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.plazainnashland.com",
      phone: "(541) 488-8900",
    },
  ],

  nationalParks: [
    {
      name: "Rogue River-Siskiyou National Forest",
      state: "Oregon",
      lat: 42.1500,
      lng: -122.7500,
      dogPolicy: "Dogs welcome on most trails. Leash required in developed areas; voice control acceptable in backcountry.",
      dogTrails: ["Wagner Butte Trail", "Grizzly Peak Trail", "Bull Gap Trail", "Sterling Mine Ditch Trail"],
      restrictions: [
        "Leash required in campgrounds and trailheads",
        "Voice control in backcountry",
        "Not allowed in designated wilderness swimming holes",
      ],
      description:
        "The mountains surrounding Ashland offer hundreds of miles of dog-friendly trails through old-growth forests, alpine meadows, and along rushing creeks. The diverse terrain from valley floor to mountain peaks provides adventures for every fitness level.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/rogue-siskiyou",
    },
    {
      name: "Oregon Caves National Monument",
      state: "Oregon",
      lat: 42.0975,
      lng: -123.4075,
      dogPolicy: "Dogs not allowed in the caves. Leashed dogs welcome on surface trails and in the picnic area.",
      dogTrails: ["Big Tree Loop Trail", "Cliff Nature Trail", "No Name Trail"],
      restrictions: [
        "No dogs in caves",
        "Must be on leash on surface trails",
        "Not allowed in buildings",
      ],
      description:
        "While the marble caves are off-limits to dogs, the surrounding old-growth forest offers beautiful surface trails. About 90 minutes from Ashland, the drive through the Siskiyou Mountains is scenic and rewarding.",
      imageUrl: "",
      website: "https://www.nps.gov/orca",
    },
    {
      name: "Cascade-Siskiyou National Monument",
      state: "Oregon",
      lat: 42.0833,
      lng: -122.5500,
      dogPolicy: "Leashed dogs welcome on all trails. This unique biological crossroads has excellent dog-friendly hiking.",
      dogTrails: ["Pilot Rock Trail", "Hobart Bluff Trail", "Pacific Crest Trail sections"],
      restrictions: [
        "Must be on leash at all times",
        "Stay on designated trails",
        "Pack out all waste",
      ],
      description:
        "Where the Cascades meet the Siskiyous, this national monument protects an extraordinary area of biodiversity. The hiking is excellent with panoramic views and diverse ecosystems, and all trails welcome leashed dogs.",
      imageUrl: "",
      website: "https://www.blm.gov/programs/national-conservation-lands",
    },
  ],

  restaurants: [
    {
      name: "Standing Stone Brewing Company",
      address: "101 Oak St, Ashland, OR 97520",
      lat: 42.1952,
      lng: -122.7098,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the spacious outdoor patio. Organic brewpub with sustainably sourced menu items.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.standingstonebrewing.com",
    },
    {
      name: "Oberon's Restaurant & Bar",
      address: "45 N Main St, Ashland, OR 97520",
      lat: 42.1955,
      lng: -122.7100,
      cuisine: "Pacific Northwest",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio during lunch and dinner. Shakespeare-inspired dining experience.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.oberonsrestaurant.com",
    },
    {
      name: "Smithfields Restaurant & Bar",
      address: "36 S 2nd St, Ashland, OR 97520",
      lat: 42.1942,
      lng: -122.7088,
      cuisine: "Southern Comfort",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Southern-inspired comfort food in a lively atmosphere.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.smithfieldsashland.com",
    },
    {
      name: "Thai Pepper",
      address: "84 N Main St, Ashland, OR 97520",
      lat: 42.1960,
      lng: -122.7102,
      cuisine: "Thai",
      priceRange: "$" as const,
      dogPolicy: "Dogs allowed at the few sidewalk tables. Affordable, flavorful Thai cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.thaipepperashland.com",
    },
    {
      name: "Caldera Tap House",
      address: "31 Water St, Ashland, OR 97520",
      lat: 42.1945,
      lng: -122.7095,
      cuisine: "Brewpub & American",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly outdoor seating area with water bowls always available. Local craft beer on tap.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.calderabrewing.com",
    },
  ],

  cafes: [
    {
      name: "Noble Coffee Roasting",
      address: "281 4th St, Ashland, OR 97520",
      lat: 42.1935,
      lng: -122.7080,
      dogPolicy: "Dogs welcome on the outdoor patio. Third-wave coffee roaster with a commitment to sustainability.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.noblecoffeeroasting.com",
    },
    {
      name: "Mix Bakeshop",
      address: "57 N Main St, Ashland, OR 97520",
      lat: 42.1956,
      lng: -122.7100,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Artisan bakery with seasonal pastries and espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.mixbakeshop.com",
    },
    {
      name: "Evo's Java House",
      address: "376 E Main St, Ashland, OR 97520",
      lat: 42.1946,
      lng: -122.7060,
      dogPolicy: "Outdoor seating welcomes dogs. Eclectic coffee house with live music and local art.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.evosjavahouse.com",
    },
    {
      name: "Ashland Creek Coffee Company",
      address: "92 N Main St, Ashland, OR 97520",
      lat: 42.1962,
      lng: -122.7103,
      dogPolicy: "Dog-friendly patio with Ashland Creek views. Locally roasted coffee and fresh pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ashlandcreekcoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Ashland Dog Park",
      address: "Nevada St & Helman St, Ashland, OR 97520",
      lat: 42.1905,
      lng: -122.7135,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Separate small dog area", "Water fountains", "Waste stations", "Benches", "Shade trees"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Ashland's dedicated off-leash dog park with separate areas for large and small dogs. Well-maintained with good shade and a friendly community atmosphere. Walking distance from downtown.",
    },
    {
      name: "Lithia Park Trails",
      address: "59 Winburn Way, Ashland, OR 97520",
      lat: 42.1920,
      lng: -122.7120,
      offLeash: false,
      fenced: false,
      acres: 93.0,
      amenities: ["Creek access", "Hiking trails", "Japanese garden", "Duck pond", "Picnic areas", "Waste stations"],
      rating: 4.8,
      imageUrl: "",
      description:
        "Ashland's crown jewel, this 93-acre park stretches from downtown into the Siskiyou foothills along Ashland Creek. Dogs must be leashed but will love the extensive trails, creek splashing, and stunning natural beauty.",
    },
    {
      name: "North Mountain Park",
      address: "620 N Mountain Ave, Ashland, OR 97520",
      lat: 42.2005,
      lng: -122.7085,
      offLeash: false,
      fenced: false,
      acres: 35.0,
      amenities: ["Nature trails", "Bear Creek access", "Nature center", "Wetland viewing", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A nature park on the north end of Ashland with trails along Bear Creek and through riparian habitat. Leashed dogs enjoy the diverse bird life and gentle terrain perfect for easy walks.",
    },
    {
      name: "Oredson-Todd Woods",
      address: "Glenview Dr, Ashland, OR 97520",
      lat: 42.1835,
      lng: -122.7180,
      offLeash: false,
      fenced: false,
      acres: 50.0,
      amenities: ["Forested trails", "Mountain views", "Wildflower meadows", "Waste stations", "Trailhead parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A beautiful forested nature preserve on the hillside above Ashland with looping trails through oak woodlands and meadows. Leashed dogs love the peaceful wooded paths with views of the Rogue Valley below.",
    },
  ],
};
