export const astoriaData = {
  city: {
    name: "Astoria",
    state: "Oregon",
    region: "Pacific Northwest",
    lat: 46.1879,
    lng: -123.8313,
    dogFriendlinessScore: 8,
    description:
      "Perched where the mighty Columbia River meets the Pacific Ocean, Astoria is a tail-wagging paradise of misty forests, historic waterfront boardwalks, and film-famous charm (yes, Goonies fans, your pup can sniff the very streets). With dog-friendly beaches stretching for miles, pet-welcoming breweries, and enough maritime adventure to make any sea dog howl with joy, this Victorian-era gem is a must-visit for four-legged explorers and their humans alike.",
    heroImage: "https://images.unsplash.com/photo-1596465756390-1db82f691b04?w=1200&fit=crop",
    climate: "Oceanic",
    population: 10181,
  },
  hotels: [
    {
      name: "Cannery Pier Hotel & Spa",
      address: "10 Basin St, Astoria, OR 97103",
      lat: 46.1901,
      lng: -123.8382,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome with a two-pet maximum per room. Complimentary dog bed and bowl provided at check-in.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Dog beds", "Water bowls", "Treats at front desk", "Waterfront walking path", "Pet waste stations"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.cannerypierhotel.com",
      phone: "(503) 325-4996",
    },
    {
      name: "Hotel Elliott",
      address: "357 12th St, Astoria, OR 97103",
      lat: 46.1889,
      lng: -123.8292,
      priceRange: "$$$" as const,
      dogPolicy: "Pets welcome in designated rooms. $25 per night pet fee applies. Dogs must be leashed in common areas.",
      maxDogWeight: 80,
      petFee: 25,
      amenities: ["Rooftop terrace", "Dog-friendly rooms", "Nearby riverwalk", "Concierge pet recommendations"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hotelelliott.com",
      phone: "(503) 325-2222",
    },
    {
      name: "Astoria Riverwalk Inn",
      address: "400 Industry St, Astoria, OR 97103",
      lat: 46.1912,
      lng: -123.8345,
      priceRange: "$$" as const,
      dogPolicy: "All dogs welcome regardless of size or breed. Two pets per room. Pet deposit required.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["River views", "Pet waste bags", "Ground-floor pet rooms", "Walking trail access"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.astoriariverwalkinn.com",
      phone: "(503) 325-2013",
    },
    {
      name: "Norblad Hotel",
      address: "443 14th St, Astoria, OR 97103",
      lat: 46.1876,
      lng: -123.8268,
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly boutique hotel. Well-behaved dogs of all sizes are welcome. Treats available at check-in.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Boutique rooms", "Dog treats", "Local walking maps", "Pet-friendly common areas"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.norbladhotel.com",
      phone: "(503) 325-6989",
    },
    {
      name: "Holiday Inn Express Astoria",
      address: "204 W Marine Dr, Astoria, OR 97103",
      lat: 46.1845,
      lng: -123.8401,
      priceRange: "$$" as const,
      dogPolicy: "Pets allowed in select rooms with a non-refundable cleaning fee. Maximum two pets per room.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Grassy pet relief area", "Pet waste stations", "Close to riverwalk", "Complimentary breakfast"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(503) 325-6222",
    },
  ],
  nationalParks: [
    {
      name: "Lewis and Clark National Historical Park",
      state: "Oregon",
      lat: 46.134,
      lng: -123.8787,
      dogPolicy: "Dogs allowed on most trails on a leash no longer than six feet. Not permitted inside Fort Clatsop replica.",
      dogTrails: ["Fort to Sea Trail", "Netul River Trail", "Kwis Kwis Trail"],
      restrictions: ["No dogs inside fort buildings", "Leash required at all times", "Clean up after your pet"],
      description:
        "Follow in the pawprints of explorers Lewis and Clark at this coastal park where the Corps of Discovery spent a soggy winter in 1805. Miles of forested trails wind through old-growth Sitka spruce, and the Fort to Sea Trail takes you and your adventurous pup all the way to the beach.",
      imageUrl: "",
      website: "https://www.nps.gov/lewi",
    },
    {
      name: "Ecola State Park",
      state: "Oregon",
      lat: 45.9224,
      lng: -123.975,
      dogPolicy: "Dogs welcome on leash throughout the park. Beach access varies by season due to wildlife closures.",
      dogTrails: ["Tillamook Head Trail", "Indian Beach Trail", "Crescent Beach Trail"],
      restrictions: ["Leash required (6 ft max)", "Seasonal beach closures for nesting birds", "No dogs in tidepools"],
      description:
        "Where the rainforest tumbles into the Pacific, Ecola State Park delivers jaw-dropping (and jaw-panting) views of Haystack Rock and rugged coastline. Your pup will love the woodsy trails and windswept beaches — just be ready for some serious nose-to-the-ground action on the Tillamook Head Trail.",
      imageUrl: "",
      website: "https://stateparks.oregon.gov/index.cfm?do=park.profile&parkId=136",
    },
    {
      name: "Fort Stevens State Park",
      state: "Oregon",
      lat: 46.2074,
      lng: -123.9617,
      dogPolicy: "Leashed dogs welcome on trails, beach, and in the campground. Off-leash not permitted.",
      dogTrails: ["Peter Iredale Shipwreck Trail", "Coffenbury Lake Loop", "Battery Russell Trail"],
      restrictions: ["Leash required at all times", "No dogs in swimming areas of Coffenbury Lake", "Clean up required"],
      description:
        "History-sniffing dogs will love exploring the concrete bunkers of this Civil War-era fort, while beach-loving pups can pose next to the iconic Peter Iredale shipwreck jutting from the sand. Miles of paved and unpaved trails make this a four-paw favorite for every breed.",
      imageUrl: "",
      website: "https://stateparks.oregon.gov/index.cfm?do=park.profile&parkId=129",
    },
  ],
  restaurants: [
    {
      name: "Bowpicker Fish & Chips",
      address: "1634 Duane St, Astoria, OR 97103",
      lat: 46.1893,
      lng: -123.8252,
      cuisine: "Seafood",
      priceRange: "$" as const,
      dogPolicy: "Order-window only with outdoor seating — dogs are always welcome at the picnic tables.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.8,
      imageUrl: "",
      website: "https://www.bowpicker.com",
    },
    {
      name: "Buoy Beer Company",
      address: "1 8th St, Astoria, OR 97103",
      lat: 46.1909,
      lng: -123.8336,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio overlooking the Columbia River. Water bowls provided.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.buoybeer.com",
    },
    {
      name: "Columbian Cafe",
      address: "1114 Marine Dr, Astoria, OR 97103",
      lat: 46.1903,
      lng: -123.8308,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Well-behaved dogs welcome at outdoor sidewalk tables. Leash required.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Fort George Brewery & Public House",
      address: "1483 Duane St, Astoria, OR 97103",
      lat: 46.1891,
      lng: -123.8263,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs allowed on the spacious outdoor patio. Treats and water bowls available from staff.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.fortgeorgebrewery.com",
    },
    {
      name: "Drina Daisy Bosnian Restaurant",
      address: "915 Commercial St, Astoria, OR 97103",
      lat: 46.188,
      lng: -123.8323,
      cuisine: "Bosnian",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor tables during warmer months.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "",
    },
    {
      name: "Bridgewater Bistro",
      address: "20 Basin St, Astoria, OR 97103",
      lat: 46.1903,
      lng: -123.838,
      cuisine: "Pacific Northwest",
      priceRange: "$$$" as const,
      dogPolicy: "Small, well-behaved dogs welcome on the heated riverside patio. Water bowls provided upon request.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bridgewaterbistro.com",
    },
    {
      name: "Pig 'n Pancake",
      address: "146 W Bond St, Astoria, OR 97103",
      lat: 46.1896,
      lng: -123.8355,
      cuisine: "Breakfast",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the covered outdoor seating area. Breakfast served all day.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.0,
      imageUrl: "",
      website: "https://www.pignpancake.com",
    },
    {
      name: "Rogue Ales Bayfront Public House",
      address: "100 39th St, Astoria, OR 97103",
      lat: 46.1907,
      lng: -123.8195,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor deck. Dog-friendly atmosphere with water and occasional treats.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.rogue.com",
    },
  ],
  cafes: [
    {
      name: "Street 14 Coffee",
      address: "1410 Commercial St, Astoria, OR 97103",
      lat: 46.1886,
      lng: -123.827,
      dogPolicy: "Leashed dogs welcome on the front patio. Dog treats available behind the counter — just ask!",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "",
    },
    {
      name: "Astoria Coffeehouse & Bistro",
      address: "243 11th St, Astoria, OR 97103",
      lat: 46.1888,
      lng: -123.8302,
      dogPolicy: "Dogs welcome at outdoor sidewalk seating. Water bowls set out daily.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Cafe Uniontown",
      address: "218 W Marine Dr, Astoria, OR 97103",
      lat: 46.1848,
      lng: -123.84,
      dogPolicy: "Patio seating is open to leashed pups. Cozy vibes and fresh pastries for the humans.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Columbian Theater Coffee",
      address: "1102 Marine Dr, Astoria, OR 97103",
      lat: 46.1902,
      lng: -123.831,
      dogPolicy: "Dogs allowed at the outdoor tables. A calm, artsy spot to share a quiet moment with your pup.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Blue Scorcher Bakery Cafe",
      address: "1493 Duane St, Astoria, OR 97103",
      lat: 46.1891,
      lng: -123.8261,
      dogPolicy: "Worker-owned co-op with a lovely patio. Leashed dogs welcome outside, organic treats sometimes available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.bluescorcher.coop",
    },
  ],
  dogParks: [
    {
      name: "Astoria Dog Park at Tapiola Park",
      address: "300 Tapiola Park Rd, Astoria, OR 97103",
      lat: 46.1822,
      lng: -123.8148,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Separate small dog area", "Water spigot", "Waste bag stations", "Benches", "Agility ramp"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Astoria's beloved off-leash haven where local pups convene for zoomies, sniff circles, and the occasional dramatic standoff over a tennis ball. Separate areas for big and small dogs keep everyone happy.",
    },
    {
      name: "Youngs River Falls Trail (Off-Leash Friendly Area)",
      address: "Youngs River Loop Rd, Astoria, OR 97103",
      lat: 46.1234,
      lng: -123.7891,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Hiking trail", "Waterfall viewpoint", "Natural water access", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A scenic walk to a stunning waterfall where your dog can splash in the shallows downstream. Leash required on trail, but the creek area gives pups room to wade and play in the cool Pacific Northwest waters.",
    },
    {
      name: "Shively Park",
      address: "Shively Park Rd, Astoria, OR 97103",
      lat: 46.1812,
      lng: -123.8225,
      offLeash: false,
      fenced: false,
      acres: 17.0,
      amenities: ["Wooded trails", "Picnic areas", "Historic cathedral trees", "Benches"],
      rating: 4.4,
      imageUrl: "",
      description:
        "An enchanting old-growth forest right in town. Walk under towering Sitka spruce with your leashed pup and pretend you're both in a fairytale. The dappled light and mossy trails make for magical photo ops.",
    },
    {
      name: "Sunset Beach Dog Area",
      address: "Sunset Beach Ln, Warrenton, OR 97146",
      lat: 46.1672,
      lng: -123.9523,
      offLeash: true,
      fenced: false,
      acres: 20.0,
      amenities: ["Beach access", "Dunes", "Driftwood", "Parking lot", "Waste bag dispensers"],
      rating: 4.7,
      imageUrl: "",
      description:
        "Miles of windswept beach where your dog can run free, chase waves, and investigate every piece of driftwood. The wide-open sand flats at low tide are a retriever's absolute dream. Bring a towel — sandy paws guaranteed.",
    },
    {
      name: "Cathedral Tree Trail Dog Walk",
      address: "Irving Ave, Astoria, OR 97103",
      lat: 46.1798,
      lng: -123.8247,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["Forest trail", "Historic trees", "Quiet atmosphere", "Bench at summit"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A short but memorable trail through a grove of massive old-growth trees that form a natural cathedral. Your leashed pup will love the earthy smells while you admire trees that were old when Lewis and Clark passed through.",
    },
  ],
};
