export const atlantaData = {
  city: {
    name: "Atlanta",
    state: "Georgia",
    region: "Southeast",
    lat: 33.749,
    lng: -84.388,
    dogFriendlinessScore: 7,
    description:
      "Atlanta's BeltLine trail system, abundance of dog parks, and brewery culture make it one of the most dog-friendly cities in the Southeast. The city in a forest lives up to its nickname with a tree canopy that dogs love to explore, and the patio dining scene is exceptional.",
    heroImage: "https://images.unsplash.com/photo-1575917649111-0cee4e7e8852?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 498715,
  },
  hotels: [
    {
      name: "Kimpton Overland Hotel",
      address: "1 Vireo Walk, Atlanta, GA 30329",
      lat: 33.8121,
      lng: -84.3564,
      priceRange: "$$$" as const,
      dogPolicy: "All pets welcome at no extra charge. Complimentary pet bed, bowls, and treats. Near PATH trails.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pet bed", "Treats", "Near trails", "Pool"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.theoverlandhotel.com",
      phone: "(470) 485-8700",
    },
    {
      name: "Hotel Clermont",
      address: "789 Ponce de Leon Ave NE, Atlanta, GA 30306",
      lat: 33.7723,
      lng: -84.3615,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique hotel welcoming dogs with a $50 per stay fee. Walking distance to Ponce City Market and the BeltLine.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["BeltLine access", "Rooftop bar", "Ponce City Market nearby", "Pet amenities"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelclermont.com",
      phone: "(404) 874-0420",
    },
    {
      name: "Staybridge Suites Atlanta Midtown",
      address: "1132 Techwood Dr NW, Atlanta, GA 30318",
      lat: 33.786,
      lng: -84.393,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a $75 non-refundable fee. Suite-style rooms with kitchens near Georgia Tech.",
      maxDogWeight: 80,
      petFee: 75,
      amenities: ["Full kitchen", "Pet relief area", "Free breakfast", "Near Midtown", "Pool"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(404) 874-0824",
    },
    {
      name: "The Candler Hotel Atlanta",
      address: "127 Peachtree St NE, Atlanta, GA 30303",
      lat: 33.7572,
      lng: -84.387,
      priceRange: "$$$$" as const,
      dogPolicy: "Luxury downtown hotel welcoming dogs under 50 lbs with a $100 per stay fee. Historic Beaux-Arts building.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Historic building", "Downtown location", "Pet bed", "Concierge", "Restaurant"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thecandlerhotel.com",
      phone: "(404) 523-1234",
    },
  ],
  nationalParks: [
    {
      name: "Chattahoochee River National Recreation Area",
      state: "Georgia",
      lat: 33.9963,
      lng: -84.3427,
      dogPolicy: "Leashed dogs welcome on all trails. Miles of riverside trails through forested corridors within the metro area.",
      dogTrails: ["East Palisades Trail", "Vickery Creek Trail", "Cochran Shoals Trail", "Jones Bridge Trail"],
      restrictions: ["Leash required at all times", "No dogs on Cochran Shoals fitness trail", "Clean up required"],
      description:
        "A 48-mile stretch of the Chattahoochee River protected within the metro Atlanta area, offering wooded trails, river access, and surprisingly wild scenery minutes from the city. The East Palisades trail features bamboo forests and rocky rapids. Your dog can wade in the river at numerous access points.",
      imageUrl: "",
      website: "https://www.nps.gov/chat",
    },
    {
      name: "Kennesaw Mountain National Battlefield Park",
      state: "Georgia",
      lat: 33.9831,
      lng: -84.5783,
      dogPolicy: "Leashed dogs welcome on all trails including the summit trail. Civil War battlefield with mountain views.",
      dogTrails: ["Mountain Summit Trail", "Pigeon Hill Trail", "Cheatham Hill Trail", "Kolb's Farm Trail"],
      restrictions: ["Leash required", "Clean up required", "Stay on designated trails"],
      description:
        "A 2,965-acre Civil War battlefield with 18 miles of trails climbing to the summit of Kennesaw Mountain. The top offers panoramic views of the Atlanta skyline and surrounding mountains. Your leashed dog gets a solid workout on the mountain trails while you walk through history.",
      imageUrl: "",
      website: "https://www.nps.gov/kemo",
    },
    {
      name: "Sweetwater Creek State Park",
      state: "Georgia",
      lat: 33.7516,
      lng: -84.6302,
      dogPolicy: "Leashed dogs welcome on all trails. A beautiful creek gorge with Civil War factory ruins.",
      dogTrails: ["Red Trail to Factory Ruins", "Blue Trail", "Yellow Trail", "White Trail"],
      restrictions: ["Leash required", "No dogs in lake swimming area", "Clean up required"],
      description:
        "Just 20 minutes from downtown Atlanta, this state park preserves a stunning creek gorge with rapids, waterfalls, and the ruins of a Civil War-era textile mill. The Red Trail follows the creek to the photogenic factory ruins. Your dog will love the rocky creek access and shaded forest trails.",
      imageUrl: "",
      website: "https://gastateparks.org/SweetwaterCreek",
    },
  ],
  restaurants: [
    {
      name: "Monday Night Brewing Garage",
      address: "933 Lee St SW, Atlanta, GA 30310",
      lat: 33.7307,
      lng: -84.4174,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Massive indoor/outdoor brewery in a converted garage. Extremely dog-friendly with water bowls throughout.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.mondaynightbrewing.com",
    },
    {
      name: "Ladybird Grove & Mess Hall",
      address: "684 John Wesley Dobbs Ave NE, Atlanta, GA 30312",
      lat: 33.7603,
      lng: -84.3717,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Giant outdoor dining area on the BeltLine. One of Atlanta's most dog-friendly restaurants with a treehouse-like setting.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ladybirdatlanta.com",
    },
    {
      name: "Orpheus Brewing",
      address: "1440 Dutch Valley Pl NE, Atlanta, GA 30324",
      lat: 33.7912,
      lng: -84.3672,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly brewery across from Piedmont Park. Expansive outdoor area with Midtown skyline views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.orpheusbrewing.com",
    },
    {
      name: "Ponce City Market Food Hall",
      address: "675 Ponce de Leon Ave NE, Atlanta, GA 30308",
      lat: 33.7728,
      lng: -84.3654,
      cuisine: "Food Hall",
      priceRange: "$$" as const,
      dogPolicy: "Massive food hall with dog-friendly outdoor areas along the BeltLine. Multiple cuisine options under one roof.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.poncecitymarket.com",
    },
    {
      name: "Fox Bros Bar-B-Q",
      address: "1238 DeKalb Ave NE, Atlanta, GA 30307",
      lat: 33.7539,
      lng: -84.3418,
      cuisine: "BBQ",
      priceRange: "$$" as const,
      dogPolicy: "Legendary Atlanta BBQ with a dog-friendly covered patio. Brisket, ribs, and southern sides.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.foxbrosbbq.com",
    },
  ],
  cafes: [
    {
      name: "Chrome Yellow Trading Co.",
      address: "813 Highland Ave NE, Atlanta, GA 30306",
      lat: 33.7662,
      lng: -84.3528,
      dogPolicy: "Virginia-Highland coffee shop with a dog-friendly patio. Quality espresso and light bites in a hip neighborhood setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.chromeyellow.co",
    },
    {
      name: "Revelator Coffee Company",
      address: "1065 Peachtree St NE, Atlanta, GA 30309",
      lat: 33.7849,
      lng: -84.3831,
      dogPolicy: "Specialty coffee roaster in Midtown with outdoor seating near Piedmont Park. Dogs welcome at patio tables.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.revelatorcoffee.com",
    },
    {
      name: "Chattahoochee Coffee Company",
      address: "1401 Chattahoochee Ave NW, Atlanta, GA 30318",
      lat: 33.7895,
      lng: -84.4262,
      dogPolicy: "Westside coffee shop near the Chattahoochee River with a spacious patio. Dogs welcome in this industrial-chic setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "East Pole Coffee Co.",
      address: "225 Baker St NE, Atlanta, GA 30308",
      lat: 33.7653,
      lng: -84.3816,
      dogPolicy: "Roastery with outdoor seating near the BeltLine. Dogs welcome at patio tables. Single-origin pour-overs and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.eastpolecoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Piedmont Park Dog Park",
      address: "400 Park Dr NE, Atlanta, GA 30306",
      lat: 33.7839,
      lng: -84.3703,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water fountains", "Midtown skyline views", "Shade trees", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Atlanta's most popular dog park sits within iconic Piedmont Park with Midtown skyline views as a backdrop. The fenced area has separate sections for large and small dogs, and the adjacent park offers miles of additional walking paths. The social scene is as much for humans as for dogs.",
    },
    {
      name: "Atlanta BeltLine Eastside Trail",
      address: "Multiple access points, Atlanta, GA",
      lat: 33.7711,
      lng: -84.3624,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Paved trail", "Public art", "Restaurants along route", "Parks", "Shopping"],
      rating: 4.7,
      imageUrl: "",
      description:
        "The 2.25-mile Eastside Trail is Atlanta's most beloved walking path, connecting Piedmont Park to Inman Park through a former rail corridor. The paved path passes murals, restaurants with dog-friendly patios, and Ponce City Market. Your leashed dog will love the people-watching and the abundant social opportunities.",
    },
    {
      name: "Fetch Dog Park at Westside Quarry",
      address: "1600 Howell Mill Rd NW, Atlanta, GA 30318",
      lat: 33.7944,
      lng: -84.413,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced", "Agility equipment", "Water features", "Shade structures", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A well-designed off-leash dog park on the Westside with agility equipment, water features, and plenty of running room. The park is a favorite of Atlanta's west side dog community and features some of the best dog park amenities in the city.",
    },
    {
      name: "Freedom Park Trail",
      address: "Freedom Pkwy NE, Atlanta, GA 30307",
      lat: 33.765,
      lng: -84.3538,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Paved path", "Carter Center views", "Shade trees", "Connects to BeltLine", "Benches"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A paved greenway connecting the BeltLine to the Carter Presidential Center through mature urban forest. The shaded path passes gardens, meadows, and the grounds of the Carter Center. Your leashed dog gets a peaceful walk through one of Atlanta's most beautiful in-town corridors.",
    },
  ],
};
