export const austinData = {
  city: {
    name: "Austin",
    state: "Texas",
    region: "Southwest",
    lat: 30.2672,
    lng: -97.7431,
    dogFriendlinessScore: 9,
    description:
      "Austin is a tail-wagging paradise where 'Keep Austin Weird' extends to four-legged residents too. With over 300 days of sunshine, dozens of off-leash parks, dog-friendly patios on nearly every block of South Congress, and swimming holes perfect for pups, this live-music capital treats dogs like VIPs. From Barton Springs splashing to food truck feasting, your dog will feel right at home in the Live Music Capital of the World.",
    heroImage: "https://images.unsplash.com/photo-1531218150217-54595bc2b934?w=1200&fit=crop",
    climate: "Subtropical",
    population: 978908,
  },
  hotels: [
    {
      name: "Hotel San José",
      address: "1316 S Congress Ave, Austin, TX 78704",
      lat: 30.2498,
      lng: -97.7497,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome, all sizes, max 2 pets per room",
      maxDogWeight: 0,
      petFee: 75,
      amenities: [
        "Dog bed",
        "Welcome treats",
        "Pet relief area",
        "Water bowls in lobby",
      ],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.sanjosehotel.com",
      phone: "(512) 444-7322",
    },
    {
      name: "Kimpton Hotel Van Zandt",
      address: "605 Davis St, Austin, TX 78701",
      lat: 30.2603,
      lng: -97.7386,
      priceRange: "$$$" as const,
      dogPolicy: "All pets welcome, no size or breed restrictions",
      maxDogWeight: 0,
      petFee: 0,
      amenities: [
        "Dog bed",
        "Food and water bowls",
        "Welcome treats",
        "Pet concierge",
        "Rooftop pet lounge",
      ],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.hotelvanzandt.com",
      phone: "(512) 542-5300",
    },
    {
      name: "Lone Star Court",
      address: "10901 Domain Dr, Austin, TX 78758",
      lat: 30.4021,
      lng: -97.7253,
      priceRange: "$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome",
      maxDogWeight: 50,
      petFee: 50,
      amenities: [
        "Dog bed",
        "Outdoor fire pit area",
        "Walking trail access",
        "Welcome biscuits",
      ],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.lonestarcourt.com",
      phone: "(512) 814-2625",
    },
    {
      name: "Austin Motel",
      address: "1220 S Congress Ave, Austin, TX 78704",
      lat: 30.2512,
      lng: -97.7496,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with signed pet waiver, all sizes",
      maxDogWeight: 0,
      petFee: 40,
      amenities: [
        "Poolside pet area",
        "Dog waste stations",
        "Retro dog bandanas at check-in",
      ],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.austinmotel.com",
      phone: "(512) 441-1157",
    },
    {
      name: "Driskill Hotel",
      address: "604 Brazos St, Austin, TX 78701",
      lat: 30.2672,
      lng: -97.7408,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 40 lbs welcome, limit 1 per room",
      maxDogWeight: 40,
      petFee: 100,
      amenities: [
        "Luxury dog bed",
        "Gourmet pet treats",
        "Dog walking service",
        "Monogrammed water bowl",
      ],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.driskillhotel.com",
      phone: "(512) 474-5911",
    },
  ],
  nationalParks: [
    {
      name: "Lyndon B. Johnson National Historical Park",
      state: "Texas",
      lat: 30.2388,
      lng: -98.6234,
      dogPolicy: "Dogs allowed on most outdoor trails on leash",
      dogTrails: ["LBJ Ranch Trail", "Sauer-Beckmann Trail", "Nature Loop"],
      restrictions: [
        "Must be on 6-foot leash",
        "Not allowed inside historic buildings",
        "Clean up after pet",
      ],
      description:
        "Walk the rolling Hill Country terrain where President Johnson once roamed. Dogs can explore the ranch grounds and scenic trails with sweeping views of the Pedernales River valley.",
      imageUrl: "",
      website: "https://www.nps.gov/lyjo",
    },
    {
      name: "Big Bend National Park",
      state: "Texas",
      lat: 29.2498,
      lng: -103.25,
      dogPolicy:
        "Dogs allowed on paved roads and in developed areas only; limited trail access",
      dogTrails: ["Rio Grande Village Nature Trail (paved)", "Window View Trail"],
      restrictions: [
        "Must be on 6-foot leash at all times",
        "Not allowed on unpaved trails",
        "Not allowed in backcountry",
        "Cannot be left unattended",
      ],
      description:
        "A vast desert wilderness where the Rio Grande carves dramatic canyons. While trail access for dogs is limited, the scenic drives and developed areas still offer an unforgettable Big Bend experience with your pup.",
      imageUrl: "",
      website: "https://www.nps.gov/bibe",
    },
    {
      name: "Guadalupe Mountains National Park",
      state: "Texas",
      lat: 31.8913,
      lng: -104.8607,
      dogPolicy: "Dogs allowed on Guadalupe Peak Trail and select areas on leash",
      dogTrails: ["Guadalupe Peak Trail", "Pinery Trail"],
      restrictions: [
        "Must be on 6-foot leash",
        "Not allowed in McKittrick Canyon",
        "Carry extra water for pets — arid conditions",
      ],
      description:
        "Home to the highest point in Texas, this rugged park features ancient marine fossils and dramatic Chihuahuan Desert scenery. Adventurous dogs can tackle the challenging summit trail alongside their humans.",
      imageUrl: "",
      website: "https://www.nps.gov/gumo",
    },
    {
      name: "Enchanted Rock State Natural Area",
      state: "Texas",
      lat: 30.5057,
      lng: -98.8198,
      dogPolicy: "Dogs welcome on all trails on leash",
      dogTrails: [
        "Summit Trail",
        "Loop Trail",
        "Echo Canyon Trail",
        "Turkey Pass Trail",
      ],
      restrictions: [
        "Must be on 6-foot leash",
        "Bring water — granite surfaces get extremely hot",
        "Clean up after pet",
      ],
      description:
        "A massive pink granite dome rising from the Hill Country, Enchanted Rock is a must-visit for hikers and their dogs. The summit trail rewards with 360-degree views, and the surrounding loop trails offer shady creek crossings.",
      imageUrl: "",
      website: "https://tpwd.texas.gov/state-parks/enchanted-rock",
    },
  ],
  restaurants: [
    {
      name: "Terry Black's Barbecue",
      address: "1003 Barton Springs Rd, Austin, TX 78704",
      lat: 30.2614,
      lng: -97.7568,
      cuisine: "BBQ",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.terryblacksbbq.com",
    },
    {
      name: "Yard Bar",
      address: "6700 Burnet Rd, Austin, TX 78757",
      lat: 30.3383,
      lng: -97.7378,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy:
        "Full off-leash dog park and bar combo — dogs run free while you dine",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.yardbar.com",
    },
    {
      name: "Loro Asian Smokehouse",
      address: "2115 S Lamar Blvd, Austin, TX 78704",
      lat: 30.2471,
      lng: -97.7721,
      cuisine: "Asian Fusion BBQ",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the spacious outdoor patio",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.8,
      imageUrl: "",
      website: "https://www.loroeats.com",
    },
    {
      name: "Bouldin Creek Café",
      address: "1900 S 1st St, Austin, TX 78704",
      lat: 30.2471,
      lng: -97.7554,
      cuisine: "Vegetarian",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on covered front patio",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bouldincreekcafe.com",
    },
    {
      name: "Jacoby's Restaurant & Mercantile",
      address: "3235 E Cesar Chavez St, Austin, TX 78702",
      lat: 30.2551,
      lng: -97.7162,
      cuisine: "Texas Ranch",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the riverside patio — treats available",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.jacobysaustin.com",
    },
    {
      name: "Güero's Taco Bar",
      address: "1412 S Congress Ave, Austin, TX 78704",
      lat: 30.2489,
      lng: -97.7498,
      cuisine: "Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the oak garden patio area",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.guerostacobar.com",
    },
    {
      name: "Contigo",
      address: "2027 Anchor Ln, Austin, TX 78723",
      lat: 30.2974,
      lng: -97.7062,
      cuisine: "Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in the ranch-style outdoor area",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.contigotexas.com",
    },
    {
      name: "Cosmic Coffee + Beer Garden",
      address: "121 Pickle Rd, Austin, TX 78704",
      lat: 30.2351,
      lng: -97.7672,
      cuisine: "American Casual",
      priceRange: "$" as const,
      dogPolicy: "Extremely dog-friendly — off-leash areas and dog water stations",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cosmiccoffeebeer.com",
    },
  ],
  cafes: [
    {
      name: "Mozart's Coffee Roasters",
      address: "3825 Lake Austin Blvd, Austin, TX 78703",
      lat: 30.2962,
      lng: -97.7878,
      dogPolicy: "Dogs welcome on the lakeside deck — stunning views",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.mozartscoffee.com",
    },
    {
      name: "Flitch Coffee",
      address: "2700 S Lamar Blvd, Austin, TX 78704",
      lat: 30.2409,
      lng: -97.7721,
      dogPolicy: "Patio friendly, dog water bowls always out",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.flitchcoffee.com",
    },
    {
      name: "Radio Coffee & Beer",
      address: "4204 Manchaca Rd, Austin, TX 78704",
      lat: 30.2277,
      lng: -97.7882,
      dogPolicy:
        "Dogs welcome everywhere — large outdoor yard with live music stage",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.radiocoffeeandbeer.com",
    },
    {
      name: "Spokesman Coffee",
      address: "1236 S Lamar Blvd, Austin, TX 78704",
      lat: 30.2534,
      lng: -97.7652,
      dogPolicy: "Patio seating, dogs on leash welcome",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.spokesmancoffee.com",
    },
    {
      name: "Cenote",
      address: "1010 E Cesar Chavez St, Austin, TX 78702",
      lat: 30.2555,
      lng: -97.7336,
      dogPolicy: "Shaded garden patio is very dog-friendly, treats at the counter",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cenoteaustin.com",
    },
  ],
  dogParks: [
    {
      name: "Zilker Park Off-Leash Area",
      address: "2100 Barton Springs Rd, Austin, TX 78704",
      lat: 30.2669,
      lng: -97.7729,
      offLeash: true,
      fenced: false,
      acres: 8.0,
      amenities: [
        "Water fountains",
        "Swimming access in Barton Creek",
        "Shade trees",
        "Waste stations",
      ],
      rating: 4.7,
      imageUrl: "",
      description:
        "A sprawling unfenced off-leash haven along Barton Creek where dogs can splash, swim, and romp through grassy fields. One of Austin's most beloved dog destinations with postcard-worthy views of the downtown skyline.",
    },
    {
      name: "Red Bud Isle",
      address: "3401 Red Bud Trail, Austin, TX 78746",
      lat: 30.2922,
      lng: -97.7856,
      offLeash: true,
      fenced: false,
      acres: 13.0,
      amenities: [
        "Lake swimming",
        "Nature trails",
        "Wildlife viewing",
        "Waste stations",
      ],
      rating: 4.8,
      imageUrl: "",
      description:
        "A magical 13-acre island peninsula on Lady Bird Lake where dogs roam free through wooded trails and plunge into the calm waters. A true off-leash paradise that feels worlds away from the city.",
    },
    {
      name: "Norwood Estate Dog Park",
      address: "1009 Riverside Dr, Austin, TX 78704",
      lat: 30.258,
      lng: -97.7448,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: [
        "Separate small dog area",
        "Water fountains",
        "Benches",
        "Double-gated entry",
        "Lake views",
      ],
      rating: 4.5,
      imageUrl: "",
      description:
        "A fully fenced downtown dog park right along the Lady Bird Lake hike-and-bike trail. Features separate areas for small and large dogs with gorgeous skyline and lake views.",
    },
    {
      name: "Auditorium Shores Off-Leash Area",
      address: "800 W Riverside Dr, Austin, TX 78704",
      lat: 30.2608,
      lng: -97.7523,
      offLeash: true,
      fenced: false,
      acres: 4.0,
      amenities: [
        "Lake access",
        "Open fields",
        "Trail connections",
        "Waste stations",
        "Water fountains",
      ],
      rating: 4.4,
      imageUrl: "",
      description:
        "A scenic off-leash area along Lady Bird Lake with skyline views that double as the perfect backdrop for fetch. Dogs love the gentle shoreline entry to the lake and the wide open grassy spaces.",
    },
    {
      name: "West Austin Neighborhood Park Dog Area",
      address: "1317 W 10th St, Austin, TX 78703",
      lat: 30.2773,
      lng: -97.7567,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: [
        "Agility equipment",
        "Shade structures",
        "Water fountains",
        "Benches",
        "Double-gated entry",
      ],
      rating: 4.3,
      imageUrl: "",
      description:
        "A charming neighborhood dog park tucked into the Clarksville area with agility obstacles and mature pecan trees providing ample shade. A favorite for locals who want a quick off-leash romp.",
    },
  ],
};
