export const barHarborData = {
  city: {
    name: "Bar Harbor",
    state: "Maine",
    region: "Northeast",
    lat: 44.3876,
    lng: -68.2039,
    dogFriendlinessScore: 8,
    description:
      "Perched on the edge of Mount Desert Island, Bar Harbor is a gateway to Acadia National Park and one of New England's most dog-friendly coastal towns. Rocky shorelines, evergreen-lined carriage roads, and a walkable village center with pet-welcoming shops and restaurants make it a top pick for adventurous dogs and their people.",
    heroImage: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1200&fit=crop",
    climate: "Humid continental",
    population: 5089,
  },
  hotels: [
    {
      name: "Bar Harbor Grand Hotel",
      address: "269 Main St, Bar Harbor, ME 04609",
      lat: 44.3888,
      lng: -68.2040,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in designated pet-friendly rooms. Walking distance to the village green.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Waste bags", "Walking map"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.barharborgrand.com/",
      phone: "(207) 288-5226",
    },
    {
      name: "Balance Rock Inn",
      address: "21 Albert Meadow, Bar Harbor, ME 04609",
      lat: 44.3907,
      lng: -68.2009,
      priceRange: "$$$$" as const,
      dogPolicy: "Well-behaved dogs welcome in select oceanfront rooms. Stunning shoreline grounds to explore.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Plush dog bed", "Gourmet treats", "Oceanfront walking paths", "Concierge recommendations"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.barharborhotel.com/",
      phone: "(207) 288-2610",
    },
    {
      name: "Acadia Inn",
      address: "98 Eden St, Bar Harbor, ME 04609",
      lat: 44.3942,
      lng: -68.2098,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 60 lbs in pet-friendly rooms. Close to Acadia entrance.",
      maxDogWeight: 60,
      petFee: 30,
      amenities: ["Outdoor pet relief area", "Dog bowls", "Proximity to park trails", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.acadiainn.com/",
      phone: "(207) 288-3500",
    },
    {
      name: "The Bayview Hotel",
      address: "111 Eden St, Bar Harbor, ME 04609",
      lat: 44.3951,
      lng: -68.2084,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome. Waterfront property with harbor views.",
      maxDogWeight: 0,
      petFee: 65,
      amenities: ["Dog bed", "Treats at check-in", "Harbor-view rooms", "Walking paths"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thebayviewbarharbor.com/",
      phone: "(207) 288-5861",
    },
    {
      name: "Atlantic Oceanside Hotel & Event Center",
      address: "150 Eden St, Bar Harbor, ME 04609",
      lat: 44.3966,
      lng: -68.2133,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms available with ocean views. Large grounds for walking.",
      maxDogWeight: 75,
      petFee: 25,
      amenities: ["Oceanfront grounds", "Dog bowls", "Private beach access", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.barharbormainehotel.com/",
      phone: "(207) 288-5801",
    },
  ],
  nationalParks: [
    {
      name: "Acadia National Park",
      state: "Maine",
      lat: 44.3386,
      lng: -68.2733,
      dogPolicy: "Dogs allowed on most trails and all 45 miles of carriage roads. Not permitted on ladder trails, Sand Beach (June 15-Sept 15), Echo Lake Beach, or on Island Explorer buses.",
      dogTrails: [
        "Carriage Roads (45 miles)",
        "Ocean Path",
        "Jordan Pond Path",
        "Witch Hole Pond Loop",
        "Bar Island Trail",
        "Great Head Trail",
        "Wonderland Trail",
        "Ship Harbor Trail",
      ],
      restrictions: [
        "Must be on leash no longer than 6 feet at all times",
        "Not allowed on ladder/rung trails (Precipice, Beehive, Jordan Cliffs)",
        "Not allowed on Sand Beach June 15 - September 15",
        "Not allowed on Echo Lake Beach",
        "Not permitted on Island Explorer buses",
      ],
      description:
        "The crown jewel of the Maine coast, Acadia is exceptionally dog-friendly by national park standards. The historic carriage roads offer 45 miles of crushed-gravel paths through forests, around lakes, and over stone bridges — perfect for dogs of all sizes and energy levels.",
      imageUrl: "",
      website: "https://www.nps.gov/acad/",
    },
    {
      name: "Saint Croix Island International Historic Site",
      state: "Maine",
      lat: 45.1284,
      lng: -67.1335,
      dogPolicy: "Leashed dogs welcome on the mainland trail and interpretive areas. Dogs cannot access the island.",
      dogTrails: ["Mainland Trail and Overlook"],
      restrictions: [
        "Must be on leash",
        "Cannot access Saint Croix Island",
        "Not allowed in visitor contact station",
      ],
      description:
        "Commemorating the site of the first French settlement attempt in North America in 1604. The mainland trail offers views across the river to the island and interpretive panels telling the story of early European contact.",
      imageUrl: "",
      website: "https://www.nps.gov/sacr/",
    },
    {
      name: "Roosevelt Campobello International Park",
      state: "Maine",
      lat: 44.8742,
      lng: -66.9622,
      dogPolicy: "Leashed dogs welcome on park grounds, trails, and beaches. Not permitted inside the Roosevelt Cottage.",
      dogTrails: ["Friar's Head Trail", "Con Robinson's Point Trail", "Eagle Hill Bog Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed inside any buildings",
        "Clean up after your dog",
      ],
      description:
        "Franklin Roosevelt's beloved summer retreat on Campobello Island, accessible from Maine via bridge. The park features coastal trails, rocky beaches, and dense spruce forests with spectacular Bay of Fundy views.",
      imageUrl: "",
      website: "https://www.rooseveltcampobello.org/",
    },
  ],
  restaurants: [
    {
      name: "Side Street Cafe",
      address: "49 Rodick St, Bar Harbor, ME 04609",
      lat: 44.3882,
      lng: -68.2052,
      cuisine: "American Comfort Food",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Known for lobster mac and cheese.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sidestreetatbarharbor.com/",
    },
    {
      name: "Stewman's Lobster Pound",
      address: "35 West St, Bar Harbor, ME 04609",
      lat: 44.3901,
      lng: -68.2050,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Dogs allowed on the waterfront deck with harbor views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.stewmanslobsterpound.com/",
    },
    {
      name: "Thirsty Whale Tavern",
      address: "40 Cottage St, Bar Harbor, ME 04609",
      lat: 44.3879,
      lng: -68.2048,
      cuisine: "Pub Fare",
      priceRange: "$" as const,
      dogPolicy: "Leashed dogs welcome on the front patio area.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.thirstywhaletavern.com/",
    },
    {
      name: "Geddy's",
      address: "19 Main St, Bar Harbor, ME 04609",
      lat: 44.3895,
      lng: -68.2040,
      cuisine: "Seafood & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs allowed on the rooftop deck and ground-level patio.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.geddys.com/",
    },
    {
      name: "Galyn's",
      address: "17 Main St, Bar Harbor, ME 04609",
      lat: 44.3894,
      lng: -68.2041,
      cuisine: "Seafood & Steak",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the covered porch seating.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.galynsbarharbor.com/",
    },
    {
      name: "Jordan's Restaurant",
      address: "80 Cottage St, Bar Harbor, ME 04609",
      lat: 44.3873,
      lng: -68.2055,
      cuisine: "Breakfast & Brunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the small outdoor seating area. Famous for wild Maine blueberry pancakes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.jordansrestaurant.com/",
    },
    {
      name: "Atlantic Brewing Company",
      address: "15 Knox Rd, Bar Harbor, ME 04609",
      lat: 44.3713,
      lng: -68.2552,
      cuisine: "Brewery & BBQ",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly brewery with a spacious outdoor beer garden and lawn.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.atlanticbrewing.com/",
    },
    {
      name: "Blaze Restaurant",
      address: "70 Main St, Bar Harbor, ME 04609",
      lat: 44.3886,
      lng: -68.2037,
      cuisine: "Wood-Fired Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome at outdoor sidewalk tables.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.blazebh.com/",
    },
  ],
  cafes: [
    {
      name: "Cafe This Way",
      address: "14 1/2 Mount Desert St, Bar Harbor, ME 04609",
      lat: 44.3877,
      lng: -68.2059,
      dogPolicy: "Dogs welcome in the garden patio. A beloved brunch and dinner spot.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.cafethisway.com/",
    },
    {
      name: "Mount Desert Island Ice Cream",
      address: "7 Firefly Ln, Bar Harbor, ME 04609",
      lat: 44.3889,
      lng: -68.2046,
      dogPolicy: "Order at the window and enjoy with your pup on the benches outside. Dog cups available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.8,
      imageUrl: "",
      website: "https://www.mdiic.com/",
    },
    {
      name: "Cottage Street Bakery & Deli",
      address: "59 Cottage St, Bar Harbor, ME 04609",
      lat: 44.3880,
      lng: -68.2051,
      dogPolicy: "Dogs welcome at the outdoor tables. Fresh pastries and coffee daily.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.cottagestreetbakery.com/",
    },
    {
      name: "Bark Harbor Coffee",
      address: "62 Main St, Bar Harbor, ME 04609",
      lat: 44.3887,
      lng: -68.2038,
      dogPolicy: "Dog-themed coffee shop that welcomes pups at outdoor seating and offers dog treats.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.barkharborcoffee.com/",
    },
    {
      name: "Morning Glory Bakery",
      address: "39 Rodick St, Bar Harbor, ME 04609",
      lat: 44.3883,
      lng: -68.2050,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Known for scratch-made pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.morningglorybakery.com/",
    },
  ],
  dogParks: [
    {
      name: "Bar Island Trail & Beach",
      address: "Bridge St, Bar Harbor, ME 04609",
      lat: 44.3933,
      lng: -68.2038,
      offLeash: false,
      fenced: false,
      acres: 12.0,
      amenities: ["Tidal beach access", "Hiking trail", "Scenic views", "Natural terrain"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A unique tidal land bridge connects Bar Harbor to Bar Island at low tide, revealing a gravel bar where leashed dogs can walk across to the island. The trail climbs to panoramic views of Frenchman Bay and Cadillac Mountain.",
    },
    {
      name: "Bar Harbor Village Green",
      address: "Main St & Mt Desert St, Bar Harbor, ME 04609",
      lat: 44.3890,
      lng: -68.2043,
      offLeash: false,
      fenced: false,
      acres: 1.0,
      amenities: ["Open green space", "Benches", "Central location", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      description:
        "The heart of Bar Harbor's downtown, this manicured village green is a popular gathering spot where dogs and their owners can relax between exploring the town's shops and restaurants.",
    },
    {
      name: "Compass Harbor Trail",
      address: "Compass Harbor Dr, Bar Harbor, ME 04609",
      lat: 44.3802,
      lng: -68.2108,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Ocean access", "Forest trail", "Historic ruins", "Rocky shore"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A hidden gem just south of town, this easy trail winds through spruce forest to a rocky shoreline with tide pools and the ruins of George Dorr's estate. Leashed dogs love exploring the coastal terrain.",
    },
    {
      name: "Glen Mary Wading Pool & Park",
      address: "Glen Mary Rd, Bar Harbor, ME 04609",
      lat: 44.3861,
      lng: -68.2085,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["Natural wading pool", "Shaded picnic area", "Walking paths", "Stream access"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A peaceful park with a natural freshwater wading pool formed by a stream cascading over rocks. Dogs enjoy cooling off in the shallow water while surrounded by towering evergreens.",
    },
    {
      name: "Hadley Point Beach",
      address: "Hadley Point Rd, Bar Harbor, ME 04609",
      lat: 44.4198,
      lng: -68.2499,
      offLeash: true,
      fenced: false,
      acres: 5.0,
      amenities: ["Sandy beach", "Shallow water", "Parking", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A quiet public beach on the western shore of Mount Desert Island where dogs can run off-leash during the off-season. The gentle slope into Frenchman Bay creates perfect wading conditions for water-loving dogs.",
    },
  ],
};
