export const bayfieldData = {
  city: {
    name: "Bayfield",
    state: "Wisconsin",
    region: "Midwest",
    lat: 46.8108,
    lng: -90.8202,
    dogFriendlinessScore: 8,
    description:
      "Bayfield is a tiny gem on Lake Superior's south shore, serving as the gateway to the Apostle Islands. This artsy village embraces dogs with open arms, offering lakefront trails, orchards, and a laid-back atmosphere that makes every pup feel at home.",
    heroImage: "https://images.unsplash.com/photo-1517483000871-1dbf64a6e1c6?w=1200&fit=crop",
    climate: "Humid continental with lake effect",
    population: 487,
  },

  hotels: [
    {
      name: "Bayfield Inn",
      address: "20 Rittenhouse Ave, Bayfield, WI 54814",
      lat: 46.8110,
      lng: -90.8200,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in designated pet rooms with a nightly fee. Walking distance to everything.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Dog bed", "Water bowls", "Near lakefront", "Downtown location", "Walking maps"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bayfieldinn.com",
      phone: "(715) 779-3363",
    },
    {
      name: "Seagull Bay Motel",
      address: "325 S 7th St, Bayfield, WI 54814",
      lat: 46.8080,
      lng: -90.8180,
      priceRange: "$" as const,
      dogPolicy: "Very dog-friendly with no size restrictions. Affordable waterfront motel with lake views.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Lake Superior views", "Grassy grounds", "Beach access", "Waste stations"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.seagullbay.com",
      phone: "(715) 779-5558",
    },
    {
      name: "Pinehurst Inn Bed & Breakfast",
      address: "83645 WI-13, Bayfield, WI 54814",
      lat: 46.8130,
      lng: -90.8240,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in the garden cottage with advance notice. Eco-friendly B&B with organic breakfast.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Private cottage", "Garden grounds", "Organic breakfast", "Near trails", "Quiet setting"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.pinehurstinn.com",
      phone: "(715) 779-3676",
    },
    {
      name: "Apostle Islands Condo Association",
      address: "401 Old Dairy Rd, Bayfield, WI 54814",
      lat: 46.8090,
      lng: -90.8230,
      priceRange: "$$" as const,
      dogPolicy: "Select condos allow dogs with a pet deposit. Spacious accommodations with full kitchens.",
      maxDogWeight: 60,
      petFee: 50,
      amenities: ["Full kitchen", "Wooded grounds", "Near ferry dock", "Parking", "Laundry"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.apostleislandscondo.com",
      phone: "(715) 779-5111",
    },
  ],

  nationalParks: [
    {
      name: "Apostle Islands National Lakeshore",
      state: "Wisconsin",
      lat: 46.9300,
      lng: -90.6600,
      dogPolicy: "Leashed dogs welcome on mainland trails and beaches. Dogs allowed on island beaches but not on inland island trails.",
      dogTrails: ["Lakeshore Trail (mainland)", "Meyers Beach Sea Caves Trail", "Little Sand Bay Trail"],
      restrictions: [
        "Must be on a 6-foot leash at all times",
        "Not allowed on inland island trails",
        "Allowed on island beaches only",
        "Not allowed on the ice caves trail in winter",
      ],
      description:
        "The Apostle Islands feature sea caves, lighthouses, and pristine Lake Superior beaches across 21 islands. The mainland section offers dog-friendly trails to stunning sea caves and sandstone formations.",
      imageUrl: "",
      website: "https://www.nps.gov/apis",
    },
    {
      name: "Big Bay State Park",
      state: "Wisconsin",
      lat: 46.7870,
      lng: -90.6730,
      dogPolicy: "Leashed dogs welcome on all trails and in campgrounds. Located on Madeline Island, accessible by ferry.",
      dogTrails: ["Bay View Trail", "Point Trail", "Nature Trail", "Boardwalk Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Dogs must be leashed on the ferry",
        "Not allowed on the swimming beach in summer",
      ],
      description:
        "On Madeline Island, a short ferry ride from Bayfield, this state park features a mile-long sand beach and forested trails along the Lake Superior shoreline. The ferry ride with your dog is part of the adventure.",
      imageUrl: "",
      website: "https://www.dnr.wi.gov/bigbay",
    },
    {
      name: "Mount Ashwabay",
      state: "Wisconsin",
      lat: 46.7920,
      lng: -90.8530,
      dogPolicy: "Leashed dogs welcome on hiking trails in summer months. Scenic bluff trails with lake views.",
      dogTrails: ["Summit Trail", "Bluff Trail", "North Connector"],
      restrictions: [
        "Must be on leash",
        "Not allowed during ski season on groomed trails",
        "Stay on designated hiking paths",
      ],
      description:
        "A small ski area south of Bayfield that transforms into a hiking destination in summer. The bluff-top trails offer panoramic views of Lake Superior and the Apostle Islands that are well worth the climb.",
      imageUrl: "",
      website: "https://www.mtashwabay.org",
    },
  ],

  restaurants: [
    {
      name: "The Fat Radish",
      address: "200 Rittenhouse Ave, Bayfield, WI 54814",
      lat: 46.8112,
      lng: -90.8195,
      cuisine: "Farm-to-Table American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Seasonal menu featuring local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thefatradishbayfield.com",
    },
    {
      name: "Maggie's Restaurant",
      address: "257 Manypenny Ave, Bayfield, WI 54814",
      lat: 46.8115,
      lng: -90.8190,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. A colorful Bayfield institution known for burgers and fish.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.maggiesbayfield.com",
    },
    {
      name: "The Pier Restaurant",
      address: "1 Rittenhouse Ave, Bayfield, WI 54814",
      lat: 46.8118,
      lng: -90.8200,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the lakefront deck. Fresh Lake Superior whitefish and stunning views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.pierbayfield.com",
    },
    {
      name: "Bayfield Winery & Blue Ox Cidery",
      address: "86685 County Rd J, Bayfield, WI 54814",
      lat: 46.7950,
      lng: -90.8350,
      cuisine: "Wine & Cider Bar",
      priceRange: "$" as const,
      dogPolicy: "Very dog-friendly with an outdoor tasting area among the orchards.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bayfieldwinery.com",
    },
    {
      name: "Egg Toss Cafe",
      address: "41 Manypenny Ave, Bayfield, WI 54814",
      lat: 46.8113,
      lng: -90.8198,
      cuisine: "Breakfast & Lunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Farm-fresh breakfast in a cozy setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.eggtosscafe.com",
    },
  ],

  cafes: [
    {
      name: "Blue Wave Cafe",
      address: "120 Rittenhouse Ave, Bayfield, WI 54814",
      lat: 46.8111,
      lng: -90.8197,
      dogPolicy: "Dogs welcome at outdoor tables. Coffee, smoothies, and lakeside vibes.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bluewavebayfield.com",
    },
    {
      name: "Brickhouse Coffee & Tea",
      address: "15 S Broad St, Bayfield, WI 54814",
      lat: 46.8108,
      lng: -90.8205,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Cozy coffee shop on Broad Street.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.brickhousebayfield.com",
    },
    {
      name: "Good Thyme Restaurant & Cafe",
      address: "108 Rittenhouse Ave, Bayfield, WI 54814",
      lat: 46.8110,
      lng: -90.8198,
      dogPolicy: "Dogs welcome on the patio. Coffee, tea, and light meals with a garden feel.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.goodthymebayfield.com",
    },
    {
      name: "Apostle Islands Booksellers & Coffee",
      address: "21 S Broad St, Bayfield, WI 54814",
      lat: 46.8107,
      lng: -90.8206,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Books, coffee, and lake town charm.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.apostleislandsbooks.com",
    },
  ],

  dogParks: [
    {
      name: "Bayfield Waterfront Trail",
      address: "Front St, Bayfield, WI 54814",
      lat: 46.8120,
      lng: -90.8190,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Lake Superior views", "Walking path", "Benches", "Ferry dock views", "Public art"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A scenic waterfront path along Bayfield's harbor with views of the Apostle Islands, the ferry dock, and sailboats. Dogs love the lake breezes and the activity of this charming working waterfront.",
    },
    {
      name: "Brownstone Trail",
      address: "WI-13, Bayfield, WI 54814",
      lat: 46.7990,
      lng: -90.8280,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Wooded trail", "Lake views", "Historic brownstone quarry", "Benches", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A beautiful trail south of Bayfield passing through forest and along former brownstone quarry sites. Dogs enjoy the wooded terrain and the occasional Lake Superior glimpses through the trees.",
    },
    {
      name: "Dalrymple Park & Campground",
      address: "Rittenhouse Ave, Bayfield, WI 54814",
      lat: 46.8125,
      lng: -90.8175,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Lake Superior beach", "Campground", "Picnic areas", "Restrooms", "Boat launch"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A lakefront park and campground right in Bayfield with a sand beach on Lake Superior. Dogs enjoy the beach walks and the bracing Lake Superior water, especially on warm summer days.",
    },
    {
      name: "Iron Bridge Trail",
      address: "Washington Ave, Bayfield, WI 54814",
      lat: 46.8060,
      lng: -90.8250,
      offLeash: true,
      fenced: false,
      acres: 15.0,
      amenities: ["Wooded trails", "Creek crossings", "Bridge views", "Quiet setting", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A lesser-known trail on the outskirts of Bayfield where dogs can enjoy off-leash freedom in the woods. The creek crossings and varied forest terrain make it an exciting sniffing adventure.",
    },
  ],
};
