export const beaufortData = {
  city: {
    name: "Beaufort",
    state: "South Carolina",
    region: "Southeast",
    lat: 32.4316,
    lng: -80.6698,
    dogFriendlinessScore: 7,
    description:
      "Beaufort is a Lowcountry gem where moss-draped live oaks arch over streets, tidal creeks wind through salt marshes, and dogs are treated like Southern royalty. This small waterfront town on Port Royal Island has antebellum mansions, a thriving arts scene, and some of the friendliest people and pups you will ever meet. The barrier islands nearby offer pristine beaches, and the Lowcountry lifestyle means everything moves at a pace your dog will deeply appreciate. Shrimp boats, sea breezes, and salty dog kisses. That is Beaufort.",
    heroImage: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 13417,
  },

  hotels: [
    {
      name: "City Loft Hotel",
      address: "301 Carteret St, Beaufort, SC 29902",
      lat: 32.4318,
      lng: -80.6700,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome at this modern boutique hotel in the heart of downtown Beaufort. Walking distance to the waterfront and all the best patios.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowl", "Treats", "Walking map", "Near Henry C. Chambers Waterfront Park"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.citylofthotel.com",
      phone: "(843) 379-5638",
    },
    {
      name: "Best Western Sea Island Inn",
      address: "1015 Bay St, Beaufort, SC 29902",
      lat: 32.4310,
      lng: -80.6685,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms available with a per-night fee. Right on Bay Street with views of the Beaufort River and easy access to downtown.",
      maxDogWeight: 80,
      petFee: 30,
      amenities: ["Dog bed on request", "Grassy walking area", "Waterfront proximity", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(843) 522-2090",
    },
    {
      name: "The Beaufort Inn",
      address: "809 Port Republic St, Beaufort, SC 29902",
      lat: 32.4298,
      lng: -80.6720,
      priceRange: "$$$" as const,
      dogPolicy: "Small dogs welcome in select cottage rooms at this historic inn. Beautiful gardens and courtyards perfect for leisurely dog walks.",
      maxDogWeight: 25,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Garden walking", "Historic district location"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.beaufortinn.com",
      phone: "(843) 379-4667",
    },
    {
      name: "Holiday Inn Express Beaufort",
      address: "2221 Boundary St, Beaufort, SC 29902",
      lat: 32.4420,
      lng: -80.6880,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a one-time pet fee. Clean, reliable, and close to the highway for easy island-hopping adventures.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Outdoor walking area", "Waste stations", "Parking"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.ihg.com/holidayinnexpress",
      phone: "(843) 379-8600",
    },
    {
      name: "Tabby Creek Cottage Rentals",
      address: "1002 Port Republic St, Beaufort, SC 29902",
      lat: 32.4285,
      lng: -80.6735,
      priceRange: "$$$" as const,
      dogPolicy: "Dog-friendly cottage rentals in the historic district with private yards. Your pup gets their own Southern garden while you get the Lowcountry dream.",
      maxDogWeight: 0,
      petFee: 60,
      amenities: ["Private yard", "Full kitchen", "Historic neighborhood", "Porch rocking chairs", "Walking distance to waterfront"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.tabbycreekcottages.com",
      phone: "(843) 770-0303",
    },
  ],

  nationalParks: [
    {
      name: "Hunting Island State Park",
      state: "South Carolina",
      lat: 32.3582,
      lng: -80.4410,
      dogPolicy: "Leashed dogs welcome on the beach, trails, and in the campground. One of the most dog-friendly beach parks in the Southeast.",
      dogTrails: ["Beach Trail", "Maritime Forest Trail", "Lagoon Nature Trail", "Marsh Boardwalk"],
      restrictions: [
        "Must be on leash (6 ft max) at all times",
        "Owners must clean up after dogs",
        "Not allowed in rental cabins",
      ],
      description:
        "Just 20 minutes from Beaufort, this stunning barrier island park features five miles of beach, maritime forest, a historic lighthouse, and a saltwater lagoon. Your leashed pup can run the beach, explore forest trails, and wade in the warm Atlantic. The driftwood-strewn north beach is particularly magical.",
      imageUrl: "",
      website: "https://www.southcarolinaparks.com/hunting-island",
    },
    {
      name: "ACE Basin National Wildlife Refuge",
      state: "South Carolina",
      lat: 32.5140,
      lng: -80.4460,
      dogPolicy: "Leashed dogs allowed on refuge roads and select trails. One of the largest undeveloped estuaries on the East Coast.",
      dogTrails: ["Grove Plantation Trail", "Edisto Nature Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed during organized hunts",
        "Check seasonal closures",
      ],
      description:
        "The ACE Basin encompasses 350,000 acres of pristine Lowcountry estuary where rivers, marshes, and maritime forests harbor incredible wildlife. Your leashed dog can walk the plantation trails and boardwalks, spotting eagles, alligators, and wading birds in one of the South's most unspoiled landscapes.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/ace-basin",
    },
    {
      name: "Fort Sumter and Fort Moultrie National Historical Park",
      state: "South Carolina",
      lat: 32.7524,
      lng: -79.8747,
      dogPolicy: "Leashed dogs welcome at Fort Moultrie on Sullivan's Island. Dogs not allowed on the ferry to Fort Sumter or on Fort Sumter island.",
      dogTrails: ["Fort Moultrie grounds", "Sullivan's Island beach (adjacent)"],
      restrictions: [
        "No dogs on Fort Sumter ferry or island",
        "Dogs allowed at Fort Moultrie only",
        "Must be on leash at all times",
      ],
      description:
        "While Fort Sumter itself is off-limits to dogs (ferry access only), Fort Moultrie on Sullivan's Island welcomes leashed pups. After exploring the Revolutionary War fort, head to Sullivan's Island beach where dogs are allowed and the sand stretches wide. About 75 minutes from Beaufort but worth the trip.",
      imageUrl: "",
      website: "https://www.nps.gov/fosu",
    },
    {
      name: "Pinckney Island National Wildlife Refuge",
      state: "South Carolina",
      lat: 32.2340,
      lng: -80.7530,
      dogPolicy: "Leashed dogs welcome on all trails. A Lowcountry paradise of marshes, ponds, and maritime forest teeming with wildlife.",
      dogTrails: ["Ibis Pond Trail", "White Point Trail", "Clubhouse Road Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Owners must clean up after dogs",
        "No swimming in refuge ponds",
      ],
      description:
        "Just 30 minutes south of Beaufort near Hilton Head, this 4,053-acre refuge offers 14 miles of trails through some of the most beautiful Lowcountry habitat. Your leashed dog can spot white ibis, painted buntings, and alligators along the pond trails. The Spanish moss and live oaks are straight out of a painting.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/pinckney-island",
    },
  ],

  restaurants: [
    {
      name: "Saltus River Grill",
      address: "802 Bay St, Beaufort, SC 29902",
      lat: 32.4315,
      lng: -80.6690,
      cuisine: "Seafood & Steaks",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the waterfront patio overlooking the Beaufort River. Watch shrimp boats pass while enjoying fresh Lowcountry seafood.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.saltusrivergrill.com",
    },
    {
      name: "Lowcountry Produce",
      address: "302 Carteret St, Beaufort, SC 29902",
      lat: 32.4320,
      lng: -80.6702,
      cuisine: "Farm-to-Table Southern",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the garden patio. Farm-fresh Southern cooking using produce from local Sea Island farms. Your pup will love the relaxed garden atmosphere.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.lowcountryproduce.com",
    },
    {
      name: "Plums Restaurant",
      address: "904 Bay St, Beaufort, SC 29902",
      lat: 32.4312,
      lng: -80.6680,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the front porch and outdoor tables. A Beaufort institution with waterfront views and Southern comfort food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.plumsrestaurant.com",
    },
    {
      name: "Breakwater Restaurant & Bar",
      address: "203 Carteret St, Beaufort, SC 29902",
      lat: 32.4325,
      lng: -80.6705,
      cuisine: "Southern Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the courtyard patio. Elevated Lowcountry cuisine with creative cocktails in a beautifully renovated downtown space.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.breakwatersc.com",
    },
    {
      name: "Q on Bay",
      address: "822 Bay St, Beaufort, SC 29902",
      lat: 32.4313,
      lng: -80.6687,
      cuisine: "Barbecue",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly patio with picnic tables overlooking the waterfront. Slow-smoked Lowcountry barbecue that will have both you and your pup drooling.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.qonbay.com",
    },
    {
      name: "Panini's on the Waterfront",
      address: "926 Bay St, Beaufort, SC 29902",
      lat: 32.4310,
      lng: -80.6675,
      cuisine: "Italian",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio with Beaufort River views. Fresh pasta, paninis, and a relaxed waterfront atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.paninisonthewaterfront.com",
    },
    {
      name: "Old Bull Tavern",
      address: "205 West St, Beaufort, SC 29902",
      lat: 32.4330,
      lng: -80.6715,
      cuisine: "Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Craft cocktails and creative pub fare in a downtown Beaufort setting with Southern charm to spare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.oldbulltavern.com",
    },
    {
      name: "Blackstone's Cafe",
      address: "205 Scott St, Beaufort, SC 29902",
      lat: 32.4328,
      lng: -80.6708,
      cuisine: "Breakfast & Brunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. A Beaufort breakfast legend serving heaping Southern plates that fuel you for a full day of Lowcountry exploring.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.blackstonescafe.com",
    },
  ],

  cafes: [
    {
      name: "Common Ground Coffee",
      address: "102 West St, Beaufort, SC 29902",
      lat: 32.4332,
      lng: -80.6710,
      dogPolicy: "Downtown coffee shop with a dog-friendly front patio. The morning meeting place for Beaufort's dog-walking crowd.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.commongroundbeaufort.com",
    },
    {
      name: "Beaufort Coffee Shop",
      address: "601 Bay St, Beaufort, SC 29902",
      lat: 32.4320,
      lng: -80.6710,
      dogPolicy: "Sidewalk seating where dogs can watch the Bay Street scene unfold. Locally roasted coffee and homemade muffins.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.beaufortcoffeeshop.com",
    },
    {
      name: "Southern Sweets Ice Cream & Candy",
      address: "917 Bay St, Beaufort, SC 29902",
      lat: 32.4311,
      lng: -80.6677,
      dogPolicy: "Dogs welcome at the outdoor window counter. Homemade ice cream and a pup cup that dogs lose their minds over.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.southernsweetsbeaufort.com",
    },
    {
      name: "Kazoobie Kafe",
      address: "1006 Bay St, Beaufort, SC 29902",
      lat: 32.4308,
      lng: -80.6670,
      dogPolicy: "Quirky waterfront cafe with outdoor seating where dogs are part of the fun. Next to the Kazoo Museum, which is exactly as delightful as it sounds.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.kazoobie.com",
    },
    {
      name: "Magnolia Bakery Cafe",
      address: "703 Congress St, Beaufort, SC 29902",
      lat: 32.4340,
      lng: -80.6730,
      dogPolicy: "Garden patio seating under a magnolia canopy where leashed dogs are welcome. Fresh pastries and espresso in a quintessentially Southern setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.magnoliabakerybeaufort.com",
    },
  ],

  dogParks: [
    {
      name: "Henry C. Chambers Waterfront Park",
      address: "Bay St, Beaufort, SC 29902",
      lat: 32.4310,
      lng: -80.6695,
      offLeash: false,
      fenced: false,
      acres: 7.0,
      amenities: ["Waterfront promenade", "Swings", "Gazebo", "Beaufort River views", "Waste stations", "Benches"],
      rating: 4.7,
      imageUrl: "",
      description:
        "Beaufort's crown jewel stretches along the waterfront with a sweeping promenade, live oak shade, and stunning views of the Beaufort River and tidal marshes. Leashed dogs love the breezes and the constant stream of admirers. Sunset walks here are a Beaufort must-do.",
    },
    {
      name: "Spanish Moss Trail",
      address: "Spanish Moss Trail, Beaufort, SC 29902",
      lat: 32.4450,
      lng: -80.6800,
      offLeash: false,
      fenced: false,
      acres: 40.0,
      amenities: ["Paved trail", "Marsh views", "Shade", "Waste stations", "Parking", "Connects to Port Royal"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A beautiful paved rail-trail that winds through Lowcountry landscape connecting Beaufort to Port Royal. Leashed dogs trot under canopies of live oaks draped in Spanish moss with tidal creek views. The trail is flat, shaded, and perfect for dogs of all ages and abilities.",
    },
    {
      name: "Port Royal Cypress Wetlands Dog Park",
      address: "Port Royal, SC 29935",
      lat: 32.3780,
      lng: -80.6930,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Water station", "Shade shelter", "Waste stations", "Benches", "Adjacent wetlands boardwalk"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A fenced off-leash park in nearby Port Royal with the bonus of an adjacent boardwalk through a cypress wetland where you can spot egrets, herons, and even the occasional roseate spoonbill. Your dog plays off-leash while surrounded by one of the coolest natural habitats in the Lowcountry.",
    },
    {
      name: "Pigeon Point Park",
      address: "Pigeon Point Rd, Beaufort, SC 29902",
      lat: 32.4265,
      lng: -80.6755,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Walking paths", "Marsh views", "Playground", "Boat ramp", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A neighborhood park on the south end of downtown with walking paths, marsh views, and a boat ramp. Leashed dogs enjoy the quiet atmosphere and the chance to watch the tide flow through the salt marsh. A local favorite away from the tourist bustle.",
    },
    {
      name: "Hunting Island Beach (Off-season)",
      address: "2555 Sea Island Pkwy, Hunting Island, SC 29920",
      lat: 32.3580,
      lng: -80.4420,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Sandy beach", "Ocean swimming", "Driftwood", "Nature trails", "Lighthouse views", "Parking"],
      rating: 4.8,
      imageUrl: "",
      description:
        "Five miles of wild, undeveloped beach on a barrier island 20 minutes from Beaufort. Leashed dogs can run the sand, splash in the warm Atlantic, and explore driftwood-scattered shoreline. The boneyard beach section with its ghostly standing dead trees is hauntingly beautiful and a photographer's dream.",
    },
  ],
};
