export const bellinghamData = {
  city: {
    name: "Bellingham",
    state: "Washington",
    region: "Pacific Northwest",
    lat: 48.7519,
    lng: -122.4787,
    dogFriendlinessScore: 9,
    description:
      "Nestled between the San Juan Islands and Mount Baker, Bellingham is one of the most dog-friendly cities in the Pacific Northwest. With extensive trail networks, off-leash parks, a vibrant brewery scene, and a community that treats dogs as family, this college town is a dog lover's paradise.",
    heroImage: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1200&fit=crop",
    climate: "Oceanic",
    population: 92314,
  },
  hotels: [
    {
      name: "Hotel Bellwether",
      address: "1 Bellwether Way, Bellingham, WA 98225",
      lat: 48.7560,
      lng: -122.5060,
      priceRange: "$$$$" as const,
      dogPolicy: "Luxury waterfront hotel on Bellingham Bay welcoming dogs of all sizes. No pet fee at this boutique property with marina views.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Waterfront location", "Dog bed", "Treats", "Marina walks", "No pet fee"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.hotelbellwether.com",
      phone: "(360) 392-3100",
    },
    {
      name: "Fairhaven Village Inn",
      address: "1200 10th St, Bellingham, WA 98225",
      lat: 48.7200,
      lng: -122.5000,
      priceRange: "$$$" as const,
      dogPolicy: "Charming inn in the walkable Fairhaven district with pet-friendly rooms. Dogs welcome near shops, restaurants, and the waterfront.",
      maxDogWeight: 50,
      petFee: 30,
      amenities: ["Fairhaven location", "Dog bed", "Walking map", "Water bowls", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.fairhavenvillageinn.com",
      phone: "(360) 733-1311",
    },
    {
      name: "SpringHill Suites Bellingham",
      address: "4040 Northwest Ave, Bellingham, WA 98226",
      lat: 48.7800,
      lng: -122.4900,
      priceRange: "$$" as const,
      dogPolicy: "Modern hotel with spacious pet-friendly suites. Dogs welcome with easy access to Whatcom Falls Park and Lake Padden.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Suites", "Pool", "Breakfast", "Pet-friendly rooms", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(360) 714-9600",
    },
    {
      name: "GuestHouse Inn Bellingham",
      address: "805 Lakeway Dr, Bellingham, WA 98229",
      lat: 48.7400,
      lng: -122.4600,
      priceRange: "$" as const,
      dogPolicy: "Affordable hotel welcoming dogs of all sizes. Close to Lake Padden and Whatcom Falls for dog-friendly recreation.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Pet-friendly rooms", "Parking", "Near parks", "Waste bags", "Water bowls"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.guesthouseintl.com",
      phone: "(360) 671-9600",
    },
  ],
  nationalParks: [
    {
      name: "Mount Baker-Snoqualmie National Forest",
      state: "Washington",
      lat: 48.7800,
      lng: -121.8100,
      dogPolicy: "Dogs welcome on most national forest trails on leash or under voice control. Spectacular volcanic mountain scenery with varied terrain.",
      dogTrails: ["Heliotrope Ridge Trail", "Chain Lakes Loop", "Park Butte Trail", "Baker Lake Trail"],
      restrictions: ["Leash or voice control required", "Not allowed in North Cascades National Park", "Snow possible year-round at elevation", "Northwest Forest Pass required"],
      description: "Mount Baker dominates the skyline east of Bellingham, and the surrounding national forest offers incredible dog-friendly hiking through old-growth forest, alpine meadows, and glacier viewpoints. The mountain trails are among the most spectacular in Washington.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/mbs",
    },
    {
      name: "Chuckanut Mountains",
      state: "Washington",
      lat: 48.6800,
      lng: -122.4800,
      dogPolicy: "Dogs welcome on most trails on leash. A scenic mountain range between Bellingham and the Skagit Valley with bay views.",
      dogTrails: ["Fragrance Lake Trail", "Pine & Cedar Lakes Trail", "Oyster Dome Trail", "Teddy Bear Cove Trail"],
      restrictions: ["Leash required on county park trails", "Muddy in wet season", "Steep sections on some trails", "Parking limited at popular trailheads"],
      description: "The Chuckanut Mountains south of Bellingham offer stunning trails with views of the San Juan Islands and Bellingham Bay. The Oyster Dome trail is particularly famous for its panoramic summit views over the Samish Bay.",
      imageUrl: "",
      website: "https://www.wta.org",
    },
    {
      name: "San Juan Islands (ferry access)",
      state: "Washington",
      lat: 48.5300,
      lng: -123.0200,
      dogPolicy: "Dogs welcome on the Washington State Ferry and allowed in many island parks on leash. A unique island-hopping experience for dogs.",
      dogTrails: ["Lime Kiln State Park Trail (San Juan)", "Moran State Park roads (Orcas)", "Shark Reef Sanctuary Trail (Lopez)"],
      restrictions: ["Leash required in all parks", "Dogs must stay in vehicle or on car deck on ferry", "Limited off-leash areas on islands", "Not all beaches allow dogs"],
      description: "Accessible by ferry from Bellingham, the San Juan Islands offer a dog-friendly island escape. While some areas restrict dogs, many parks, trails, and beaches welcome leashed dogs with stunning Pacific Northwest scenery.",
      imageUrl: "",
      website: "https://www.visitsanjuans.com",
    },
  ],
  restaurants: [
    {
      name: "Keenan's at the Pier",
      address: "1 Bellwether Way, Bellingham, WA 98225",
      lat: 48.7558,
      lng: -122.5055,
      cuisine: "Pacific Northwest Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Waterfront seafood restaurant with a patio overlooking Bellingham Bay. Dogs welcome with fresh Pacific Northwest cuisine and marina views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.keenansatthepier.com",
    },
    {
      name: "Aslan Brewing Company",
      address: "1330 N Forest St, Bellingham, WA 98225",
      lat: 48.7600,
      lng: -122.4780,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Certified organic brewery with a large dog-friendly patio. Craft beers and pub fare in a community-minded setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.aslanbrewing.com",
    },
    {
      name: "Colophon Café",
      address: "1208 11th St, Bellingham, WA 98225",
      lat: 48.7210,
      lng: -122.4990,
      cuisine: "Café & Soups",
      priceRange: "$" as const,
      dogPolicy: "Fairhaven bookstore café with outdoor seating where dogs are welcome. Famous soups, salads, and sandwiches in a literary setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.villagebooks.com",
    },
    {
      name: "Boundary Bay Brewery",
      address: "1107 Railroad Ave, Bellingham, WA 98225",
      lat: 48.7520,
      lng: -122.4760,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Bellingham's beloved brewery with a huge beer garden that's extremely dog-friendly. Award-winning beers and pub food.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bbaybrewery.com",
    },
    {
      name: "Hundred North",
      address: "100 N Commercial St, Bellingham, WA 98225",
      lat: 48.7530,
      lng: -122.4770,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Upscale downtown restaurant with a seasonal patio where dogs are welcome. Creative Pacific Northwest cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hundrednorth.com",
    },
  ],
  cafes: [
    {
      name: "Woods Coffee",
      address: "100 E Holly St, Bellingham, WA 98225",
      lat: 48.7530,
      lng: -122.4750,
      dogPolicy: "Beloved Pacific Northwest coffee chain with a downtown patio where dogs are welcome. Locally roasted coffee and pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.woodscoffee.com",
    },
    {
      name: "Camber Coffee",
      address: "315 E Holly St, Bellingham, WA 98225",
      lat: 48.7525,
      lng: -122.4730,
      dogPolicy: "Specialty roaster with a small patio in downtown Bellingham. Dogs welcome outside with expertly roasted single-origin coffees.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.cambercoffee.com",
    },
    {
      name: "Black Drop Coffee",
      address: "300 W Champion St, Bellingham, WA 98225",
      lat: 48.7535,
      lng: -122.4800,
      dogPolicy: "Community coffeehouse with outdoor seating and a creative atmosphere. Dogs welcome on the patio with local art and good vibes.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.blackdropcoffee.com",
    },
    {
      name: "Tony's Coffee",
      address: "1101 Harris Ave, Bellingham, WA 98225",
      lat: 48.7205,
      lng: -122.4985,
      dogPolicy: "Fairhaven roaster with a patio where dogs are regular visitors. Fair-trade organic coffee from a local institution.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.tonyscoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Whatcom Falls Park Off-Leash Area",
      address: "1401 Electric Ave, Bellingham, WA 98229",
      lat: 48.7450,
      lng: -122.4400,
      offLeash: true,
      fenced: false,
      acres: 10,
      amenities: ["Off-leash trails", "Waterfall views", "Swimming holes", "Forest paths", "Waste bag stations"],
      rating: 4.7,
      imageUrl: "",
      description: "A designated off-leash area within the stunning Whatcom Falls Park. Dogs swim in the creek pools below the waterfall and explore the forested trails in one of the most beautiful urban parks in Washington.",
    },
    {
      name: "Padden Creek Dog Park",
      address: "1005 Lakeway Dr, Bellingham, WA 98229",
      lat: 48.7350,
      lng: -122.4550,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Water stations", "Shade trees", "Benches", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "A fenced off-leash dog park near Lake Padden with separate areas for large and small dogs. Well-maintained grounds with a friendly community of regular dog owners.",
    },
    {
      name: "Lake Padden Trail",
      address: "4882 Samish Way, Bellingham, WA 98229",
      lat: 48.7250,
      lng: -122.4450,
      offLeash: false,
      fenced: false,
      acres: 745,
      amenities: ["Lake loop trail", "Swimming access", "Forest trails", "Picnic areas", "Restrooms"],
      rating: 4.6,
      imageUrl: "",
      description: "A 2.6-mile loop trail around scenic Lake Padden through mixed forest. Leashed dogs enjoy the gentle terrain and can swim at the lake in designated areas. A beloved Bellingham outdoor destination.",
    },
    {
      name: "Boulevard Park & Taylor Dock",
      address: "470 Bayview Dr, Bellingham, WA 98225",
      lat: 48.7350,
      lng: -122.5050,
      offLeash: false,
      fenced: false,
      acres: 8,
      amenities: ["Boardwalk", "Bay views", "Beach access", "Benches", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "A stunning waterfront park with a boardwalk extending over Bellingham Bay. Leashed dogs enjoy the ocean views, beach access, and the scenic walk along Taylor Dock to the Fairhaven neighborhood.",
    },
  ],
};
