export const bigSkyData = {
  city: {
    name: "Big Sky",
    state: "Montana",
    region: "Mountain West",
    lat: 45.2833,
    lng: -111.4014,
    dogFriendlinessScore: 7,
    description:
      "Where the Gallatin River carves through a canyon and the Spanish Peaks pierce the sky, Big Sky is Montana's outdoor playground for dogs who dream big. This mountain resort community sits at the gateway to Yellowstone, surrounded by millions of acres of national forest where your pup can hike, splash, and sniff to their heart's content. The off-season is especially dog-friendly, with quieter trails and welcoming patios.",
    heroImage: "https://images.unsplash.com/photo-1508389377389-918442e3626b?w=1200&fit=crop",
    climate: "Continental",
    population: 3591,
  },
  hotels: [
    {
      name: "Big Sky Resort Village Center",
      address: "50 Big Sky Resort Rd, Big Sky, MT 59716",
      lat: 45.2839,
      lng: -111.4015,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select slopeside rooms. $50 per night pet fee. Two dogs maximum per room.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Mountain views", "Trail access", "Dog-friendly lobby", "Close to gondola", "Concierge"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bigskyresort.com",
      phone: "(406) 995-5000",
    },
    {
      name: "Buck's T-4 Lodge",
      address: "46625 Gallatin Rd, Big Sky, MT 59716",
      lat: 45.2613,
      lng: -111.3284,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly lodge rooms with a $25 per night fee. Close to Gallatin River for pup-approved wading.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["River access", "Restaurant on-site", "Rustic Montana charm", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.buckst4.com",
      phone: "(406) 995-4111",
    },
    {
      name: "The Wilson Hotel",
      address: "135 Town Center Ave, Big Sky, MT 59716",
      lat: 45.2844,
      lng: -111.375,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique hotel welcoming dogs under 75 lbs. $75 per stay fee includes a treat bag and plush dog bed.",
      maxDogWeight: 75,
      petFee: 75,
      amenities: ["Dog bed", "Treat bag", "Town Center location", "Rooftop hot tub (humans only)", "Walking paths"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thewilsonhotel.com",
      phone: "(406) 995-9000",
    },
    {
      name: "Rainbow Ranch Lodge",
      address: "42950 Gallatin Rd, Big Sky, MT 59716",
      lat: 45.2358,
      lng: -111.2841,
      priceRange: "$$$" as const,
      dogPolicy: "Luxury riverside lodge welcoming dogs in cabin rooms. $50 per night fee. River access right from your door.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Riverside cabins", "Fine dining", "Fly fishing access", "Mountain views", "Private balconies"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.rainbowranch.com",
      phone: "(406) 995-4132",
    },
    {
      name: "Best Western Buck's T-4 Lodge",
      address: "46625 Gallatin Rd, Big Sky, MT 59716",
      lat: 45.261,
      lng: -111.328,
      priceRange: "$$" as const,
      dogPolicy: "Standard pet-friendly rooms available. Two-pet limit. Grassy area for exercise behind property.",
      maxDogWeight: 80,
      petFee: 20,
      amenities: ["Pet exercise area", "On-site restaurant", "Highway access", "Waste stations"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.buckst4.com",
      phone: "(406) 995-4111",
    },
  ],
  nationalParks: [
    {
      name: "Yellowstone National Park",
      state: "Montana/Wyoming",
      lat: 44.428,
      lng: -110.5885,
      dogPolicy: "Dogs are very restricted — allowed only within 100 feet of roads, parking areas, and campgrounds. Not permitted on trails, boardwalks, or in the backcountry.",
      dogTrails: ["Old Faithful parking area", "Mammoth Hot Springs campground roads"],
      restrictions: ["No dogs on any trails", "No dogs on boardwalks", "Must be leashed at all times", "Cannot be left unattended", "No dogs in thermal areas"],
      description:
        "America's first national park is spectacular but tough on traveling dogs. The strict pet rules mean your pup mostly stays roadside, but the drive-through scenery — geysers, bison herds, and mountain vistas — is still world-class. Pro tip: take turns at trailheads, or hire a local dog-sitter for the day.",
      imageUrl: "",
      website: "https://www.nps.gov/yell",
    },
    {
      name: "Gallatin National Forest (Custer Gallatin)",
      state: "Montana",
      lat: 45.35,
      lng: -111.2,
      dogPolicy: "Dogs welcome on all trails. Voice control acceptable on most trails; leash required in developed recreation areas.",
      dogTrails: ["Ousel Falls Trail", "Beehive Basin Trail", "Lava Lake Trail", "Porcupine Creek Trail", "Storm Castle Peak Trail"],
      restrictions: ["Leash in campgrounds", "Pack out waste", "Be aware of bears — carry bear spray"],
      description:
        "The real dog paradise near Big Sky. Millions of acres of alpine meadows, mountain lakes, and forested trails where your dog can roam with relative freedom. Beehive Basin is the crown jewel — a moderate hike to a stunning alpine basin surrounded by peaks. Ousel Falls is a quick, rewarding waterfall walk. Always carry bear spray.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/custergallatin",
    },
    {
      name: "Lee Metcalf Wilderness",
      state: "Montana",
      lat: 45.3,
      lng: -111.45,
      dogPolicy: "Dogs allowed under voice control throughout the wilderness. No mechanical equipment permitted.",
      dogTrails: ["Spanish Creek Trail", "South Fork Trail", "Sage Creek Trail"],
      restrictions: ["No mechanized equipment", "Pack out all waste", "Bear country — carry spray", "Practice Leave No Trace"],
      description:
        "Named for the Montana senator who championed wilderness preservation, this roadless expanse of peaks and valleys offers true backcountry solitude. Your dog can explore pristine alpine meadows and crystal streams without seeing another soul. It's wild Montana at its finest — just you, your pup, and the mountains.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/recarea/custergallatin/recarea/?recid=60904",
    },
  ],
  restaurants: [
    {
      name: "Lone Mountain Ranch Dining Room",
      address: "750 Lone Mountain Ranch Rd, Big Sky, MT 59716",
      lat: 45.2716,
      lng: -111.413,
      cuisine: "American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the outdoor terrace with stunning Lone Mountain views. Upscale ranch dining.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.lonemountainranch.com",
    },
    {
      name: "Beehive Basin Brewery",
      address: "4 Marketplace Dr, Big Sky, MT 59716",
      lat: 45.2841,
      lng: -111.374,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Extremely dog-friendly brewery with a large patio. Water bowls, treats, and a loyal local dog following.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.beehivebasinbrewery.com",
    },
    {
      name: "Blue Moon Bakery",
      address: "3090 Pine Dr, Big Sky, MT 59716",
      lat: 45.2837,
      lng: -111.376,
      cuisine: "Bakery",
      priceRange: "$" as const,
      dogPolicy: "Walk-up window with outdoor seating. Dogs welcome. Grab a breakfast burrito and a coffee before hitting the trails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "The Corral Bar & Steakhouse",
      address: "42895 Gallatin Rd, Big Sky, MT 59716",
      lat: 45.2293,
      lng: -111.2736,
      cuisine: "Steakhouse",
      priceRange: "$$" as const,
      dogPolicy: "Classic Montana roadhouse with a dog-friendly outdoor area. Burgers, steaks, and cold beer after a hike.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Gallatin Riverhouse Grill",
      address: "45130 Gallatin Rd, Big Sky, MT 59716",
      lat: 45.2475,
      lng: -111.3067,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Riverside patio where dogs can watch kayakers float by. Water bowls and a relaxed mountain vibe.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Horn & Cantle",
      address: "750 Lone Mountain Ranch Rd, Big Sky, MT 59716",
      lat: 45.272,
      lng: -111.4132,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the ranch patio during summer months. Montana-sourced ingredients and craft cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.lonemountainranch.com",
    },
    {
      name: "Olive B's Big Sky Bistro",
      address: "15 Center Ln, Big Sky, MT 59716",
      lat: 45.2842,
      lng: -111.3748,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Outdoor patio welcomes leashed dogs during summer dining season.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.olivebsbigsky.com",
    },
    {
      name: "Hungry Moose Market & Deli",
      address: "39 Town Center Ave, Big Sky, MT 59716",
      lat: 45.2843,
      lng: -111.3752,
      cuisine: "Deli",
      priceRange: "$" as const,
      dogPolicy: "Quick-service deli with outdoor picnic tables. Dogs welcome. Great for packing trail lunches.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
  ],
  cafes: [
    {
      name: "Caliber Coffee",
      address: "24 Town Center Ave, Big Sky, MT 59716",
      lat: 45.284,
      lng: -111.3754,
      dogPolicy: "Local roastery with outdoor seating. Dogs welcome for a post-hike caffeine stop. Excellent espresso.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "",
    },
    {
      name: "Blue Moon Bakery Coffee Bar",
      address: "3090 Pine Dr, Big Sky, MT 59716",
      lat: 45.2837,
      lng: -111.376,
      dogPolicy: "Morning coffee and fresh pastries with a sunny outdoor patio. Dogs get biscuits and head scratches.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "Yeti Dogs & Coffee",
      address: "47 Town Center Ave, Big Sky, MT 59716",
      lat: 45.2845,
      lng: -111.3749,
      dogPolicy: "Hot dogs and hot coffee — what more could you and your pup want? Outdoor picnic tables welcome dogs.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Bugaboo Cafe",
      address: "204 Aspen Leaf Dr, Big Sky, MT 59716",
      lat: 45.2835,
      lng: -111.4012,
      dogPolicy: "Mountain village cafe with a patio. Leashed dogs welcome while you fuel up for resort activities.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "The Hungry Moose Espresso Bar",
      address: "39 Town Center Ave, Big Sky, MT 59716",
      lat: 45.2843,
      lng: -111.3752,
      dogPolicy: "Grab-and-go espresso with outdoor benches. Your pup can lounge while you get caffeinated.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.1,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Big Sky Community Park Dog Area",
      address: "Park Loop, Big Sky, MT 59716",
      lat: 45.2801,
      lng: -111.371,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Water station", "Benches", "Mountain views", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Big Sky's community dog park offers a fenced off-leash area with jaw-dropping mountain views as a backdrop. After a day on the trails, this is a great spot to let your pup burn off remaining energy while you take in the Lone Mountain sunset.",
    },
    {
      name: "Ousel Falls Park Trail",
      address: "Ousel Falls Rd, Big Sky, MT 59716",
      lat: 45.2688,
      lng: -111.3862,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Waterfall", "Paved trail", "Benches", "River views", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A beautiful 1.6-mile round-trip trail along the South Fork of the Gallatin River leading to a stunning 50-foot waterfall. Your leashed pup will love the riverside walk, and the mist from the falls provides a refreshing cool-down. Arguably Big Sky's most accessible scenic trail.",
    },
    {
      name: "Gallatin River Access Points",
      address: "Gallatin Rd (Hwy 191), Big Sky, MT 59716",
      lat: 45.2553,
      lng: -111.318,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["River access", "Fishing spots", "Pull-off parking", "Scenic canyon views"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Multiple pull-offs along the Gallatin Canyon give dogs access to the river's edge for wading and splashing. The cold, clear mountain water is irresistible to water-loving pups. Watch the flow — spring runoff makes it swift. The canyon scenery is A River Runs Through It-level gorgeous.",
    },
    {
      name: "Hummocks Trail Network",
      address: "Little Coyote Rd, Big Sky, MT 59716",
      lat: 45.275,
      lng: -111.38,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Trail system", "Meadow views", "Wildlife viewing", "Parking", "Trail map at kiosk"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A network of gentle trails through meadows and aspen groves in the Big Sky community. Moose, elk, and deer sightings are common, so keep your leashed pup close. The flat terrain makes it accessible for dogs of all ages and fitness levels.",
    },
    {
      name: "Town Center Park Green",
      address: "Town Center Ave, Big Sky, MT 59716",
      lat: 45.2842,
      lng: -111.375,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["Open green space", "Benches", "Restaurants nearby", "Events lawn", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "The central gathering space in Big Sky Town Center where dogs and their people congregate after shopping and dining. Summer concerts and farmers markets add to the lively atmosphere. A convenient place to let your leashed pup stretch their legs between restaurant patios.",
    },
  ],
};
