export const billingsData = {
  city: {
    name: "Billings",
    state: "Montana",
    region: "Mountain West",
    lat: 45.7833,
    lng: -108.5007,
    dogFriendlinessScore: 6,
    description:
      "Billings is Montana's largest city, set beneath the dramatic Rimrocks sandstone cliffs. Dogs enjoy the extensive trail system along the Yellowstone River, the Rimrock trails with city views, and a growing downtown brewery scene. As a gateway to the Beartooth Highway and Yellowstone, Billings is a practical base for dog-friendly mountain adventures.",
    heroImage: "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7c?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 119510,
  },

  hotels: [
    {
      name: "The Northern Hotel",
      address: "19 N Broadway, Billings, MT 59101",
      lat: 45.7835,
      lng: -108.5010,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a pet fee. Historic luxury hotel in the heart of downtown.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Walking map", "Near Yellowstone River", "Treats"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.northernhotel.com",
      phone: "(406) 867-6767",
    },
    {
      name: "Hilton Garden Inn Billings",
      address: "2465 Grant Rd, Billings, MT 59102",
      lat: 45.7680,
      lng: -108.5600,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a non-refundable pet fee. Modern hotel on the west end near shopping.",
      maxDogWeight: 75,
      petFee: 35,
      amenities: ["Pet waste stations", "Grassy areas", "Water bowls", "Near walking paths"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(406) 655-8800",
    },
    {
      name: "La Quinta Inn & Suites Billings",
      address: "5110 Southgate Dr, Billings, MT 59101",
      lat: 45.7600,
      lng: -108.5100,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome at no extra charge. Budget-friendly near the interstate.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Pet waste stations", "Grassy areas", "Near Riverfront Park", "Water bowls"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta",
      phone: "(406) 252-6800",
    },
    {
      name: "Boothill Inn & Suites",
      address: "242 E Airport Rd, Billings, MT 59105",
      lat: 45.8010,
      lng: -108.5050,
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome with a small per-night fee. No weight restrictions. Near the Rimrocks.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Pet waste stations", "Near Rimrock trails", "Grassy areas", "Water bowls"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.boothillinn.com",
      phone: "(406) 245-2000",
    },
  ],

  nationalParks: [
    {
      name: "Custer Gallatin National Forest (Beartooth District)",
      state: "Montana",
      lat: 45.3000,
      lng: -109.5000,
      dogPolicy: "Dogs welcome on all trails. Voice control in backcountry; leash in developed areas.",
      dogTrails: ["West Fork Rock Creek Trail", "Basin Creek Lakes Trail", "Glacier Lake Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on trails",
        "Be aware of grizzly bears",
        "Bear spray recommended",
      ],
      description:
        "The Beartooth Mountains south of Billings offer dramatic alpine scenery with granite peaks, glacial lakes, and meadows. The Beartooth Highway (US-212) is one of America's most scenic drives, and the trails are spectacular for adventurous dogs.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/custergallatin",
    },
    {
      name: "Pompeys Pillar National Monument",
      state: "Montana",
      lat: 45.9930,
      lng: -108.0040,
      dogPolicy: "Leashed dogs welcome on the grounds. Not allowed inside the visitor center or on the rock formation.",
      dogTrails: ["Riverbank Trail", "Grounds walking paths"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed on the rock formation",
        "Not allowed in buildings",
      ],
      description:
        "A sandstone butte on the Yellowstone River where William Clark carved his name in 1806. While dogs cannot climb the rock, they can enjoy the riverbank trails and the surrounding grounds of this Lewis and Clark landmark.",
      imageUrl: "",
      website: "https://www.blm.gov/visit/pompeys-pillar",
    },
    {
      name: "Pictograph Cave State Park",
      state: "Montana",
      lat: 45.7600,
      lng: -108.4300,
      dogPolicy: "Leashed dogs welcome on the trail to the cave viewpoints. Dogs not allowed inside the caves.",
      dogTrails: ["Cave Trail", "Rim Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed in caves",
        "Stay on designated trails",
      ],
      description:
        "Just south of Billings, this state park features sandstone caves with ancient pictographs dating back 2,000 years. The short trail to the cave viewpoints is a nice leashed dog walk with interpretive history.",
      imageUrl: "",
      website: "https://fwp.mt.gov/stateparks/pictograph-cave",
    },
  ],

  restaurants: [
    {
      name: "Uberbrew",
      address: "2305 Montana Ave, Billings, MT 59101",
      lat: 45.7825,
      lng: -108.4920,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Award-winning craft brewery with rotating food trucks.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.uberbrew.com",
    },
    {
      name: "Walkers Grill",
      address: "2700 1st Ave N, Billings, MT 59101",
      lat: 45.7840,
      lng: -108.4880,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Upscale dining with locally sourced Montana ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.walkersgrill.com",
    },
    {
      name: "The Burger Dive",
      address: "114 N Broadway, Billings, MT 59101",
      lat: 45.7842,
      lng: -108.5005,
      cuisine: "Burgers",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Award-winning gourmet burgers.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.theburgerdive.com",
    },
    {
      name: "Lilac",
      address: "2515 Montana Ave, Billings, MT 59101",
      lat: 45.7828,
      lng: -108.4900,
      cuisine: "Mediterranean & Wine Bar",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the courtyard patio. Mediterranean-inspired small plates and natural wines.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.lilacbillings.com",
    },
    {
      name: "Montana Brewing Company",
      address: "113 N Broadway, Billings, MT 59101",
      lat: 45.7843,
      lng: -108.5008,
      cuisine: "Brewpub & American",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio seating. Billings' original craft brewery.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.montanabrewingcompany.com",
    },
  ],

  cafes: [
    {
      name: "Mazevo Coffee",
      address: "2812 2nd Ave N, Billings, MT 59101",
      lat: 45.7850,
      lng: -108.4870,
      dogPolicy: "Dogs welcome on the outdoor patio. Specialty coffee roaster with multiple Billings locations.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.mazevocoffee.com",
    },
    {
      name: "Rock Creek Coffee Roasters",
      address: "2919 Montana Ave, Billings, MT 59101",
      lat: 45.7830,
      lng: -108.4860,
      dogPolicy: "Outdoor seating welcomes dogs. Locally roasted single-origin coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.rockcreekcoffee.com",
    },
    {
      name: "Ebon Coffee Collective",
      address: "3005 1st Ave N, Billings, MT 59101",
      lat: 45.7845,
      lng: -108.4850,
      dogPolicy: "Dog-friendly patio area. Modern coffee shop with a creative community vibe.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.eboncoffee.com",
    },
    {
      name: "Yellowstone Valley Brewing",
      address: "2123 1st Ave N, Billings, MT 59101",
      lat: 45.7838,
      lng: -108.4940,
      dogPolicy: "Dogs welcome at outdoor tables. Taproom with coffee and beer in a converted warehouse.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.yellowstonevalleybrewing.com",
    },
  ],

  dogParks: [
    {
      name: "Yellowstone River Dog Park",
      address: "Coulson Park, Billings, MT 59101",
      lat: 45.7750,
      lng: -108.4950,
      offLeash: true,
      fenced: true,
      acres: 4.0,
      amenities: ["Separate small dog area", "River access", "Water stations", "Waste bags", "Benches"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Billings' best off-leash dog park along the Yellowstone River with river access for water-loving dogs. Separate areas for large and small dogs plus direct access to the river trail.",
    },
    {
      name: "Rimrock Trail",
      address: "Zimmerman Trail, Billings, MT 59102",
      lat: 45.7900,
      lng: -108.5200,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Sandstone cliffs", "City views", "Hiking trails", "Parking", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Trails along the top of the Rimrocks above Billings offer dramatic cliff-edge walks with panoramic views of the city, Yellowstone River valley, and distant mountains. Leashed dogs enjoy the unique terrain and expansive vistas.",
    },
    {
      name: "Riverfront Park Trail",
      address: "S Billings Blvd, Billings, MT 59101",
      lat: 45.7700,
      lng: -108.5000,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Paved path", "River access", "Benches", "Waste stations", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A paved trail along the Yellowstone River through Billings with cottonwood shade, river access points, and views of the Rimrocks. A popular route for leashed dog walks.",
    },
    {
      name: "Norm Schoenthal Island",
      address: "S Billings Blvd, Billings, MT 59101",
      lat: 45.7720,
      lng: -108.4980,
      offLeash: true,
      fenced: false,
      acres: 15.0,
      amenities: ["Island trails", "River swimming", "Nature walks", "Wildlife viewing", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A large island in the Yellowstone River accessible by bridge, offering off-leash trails through cottonwood forest. Dogs love swimming in the river and exploring the island's nature paths.",
    },
  ],
};
