export const bisbeeData = {
  city: {
    name: "Bisbee",
    state: "Arizona",
    region: "Southwest",
    lat: 31.4484,
    lng: -109.9284,
    dogFriendlinessScore: 8,
    description:
      "Bisbee is a quirky former copper mining town nestled in the Mule Mountains that has become one of Arizona's most dog-friendly destinations. The steep, stairway-laced streets, eclectic art galleries, and welcoming culture make this bohemian enclave a delight for dogs and their humans alike.",
    heroImage: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&fit=crop",
    climate: "Semi-arid highland",
    population: 5225,
  },

  hotels: [
    {
      name: "Bisbee Grand Hotel",
      address: "61 Main St, Bisbee, AZ 85603",
      lat: 31.4480,
      lng: -109.9280,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select rooms with advance notice. Victorian-era hotel on Main Street.",
      maxDogWeight: 40,
      petFee: 30,
      amenities: ["Historic setting", "Main Street location", "Walking distance to galleries", "Dog bed"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bisbeegrandhotel.com",
      phone: "(520) 432-5900",
    },
    {
      name: "Shady Dell Vintage Trailers",
      address: "1 Old Douglas Rd, Bisbee, AZ 85603",
      lat: 31.4350,
      lng: -109.9200,
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome in select vintage trailers with a small fee. Retro camping at its finest.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Vintage trailer", "Outdoor space", "Unique experience", "Near hiking"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.theshadydell.com",
      phone: "(520) 432-3567",
    },
    {
      name: "Letson Loft Hotel",
      address: "26 Main St, Bisbee, AZ 85603",
      lat: 31.4482,
      lng: -109.9285,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome with a pet fee. Upscale loft accommodations above Main Street.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Loft suites", "Main Street views", "Dog bed", "Water bowls", "Walking maps"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.letsonlofthotel.com",
      phone: "(520) 432-3210",
    },
    {
      name: "Jonquil Motel",
      address: "317 Tombstone Canyon, Bisbee, AZ 85603",
      lat: 31.4510,
      lng: -109.9260,
      priceRange: "$" as const,
      dogPolicy: "Pets welcome with a small nightly fee. Charming retro motel in the canyon.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Canyon setting", "Parking", "Walking distance to town", "Outdoor seating"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.jonquilmotel.com",
      phone: "(520) 432-7371",
    },
  ],

  nationalParks: [
    {
      name: "Coronado National Memorial",
      state: "Arizona",
      lat: 31.3460,
      lng: -110.2340,
      dogPolicy: "Leashed dogs welcome on most trails including the Coronado Peak Trail.",
      dogTrails: ["Coronado Peak Trail", "Joe's Canyon Trail", "Montezuma Pass Road"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed in the visitor center",
        "Carry water - limited shade",
      ],
      description:
        "About 30 minutes from Bisbee, this memorial commemorates the first European expedition into the American Southwest. The Coronado Peak Trail offers sweeping views of the San Pedro Valley and into Mexico.",
      imageUrl: "",
      website: "https://www.nps.gov/coro",
    },
    {
      name: "San Pedro Riparian National Conservation Area",
      state: "Arizona",
      lat: 31.5580,
      lng: -110.1380,
      dogPolicy: "Leashed dogs welcome on trails and along the San Pedro River. Premier birding destination.",
      dogTrails: ["San Pedro Trail", "Murray Springs Trail", "Kingfisher Pond Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Stay on designated trails",
        "Do not disturb wildlife or archaeological sites",
      ],
      description:
        "One of the last free-flowing rivers in the Southwest, the San Pedro supports an incredible diversity of birds and wildlife. Dogs enjoy the shaded riverside trails through cottonwood groves.",
      imageUrl: "",
      website: "https://www.blm.gov/visit/san-pedro-riparian-nca",
    },
    {
      name: "Chiricahua National Monument",
      state: "Arizona",
      lat: 32.0130,
      lng: -109.3420,
      dogPolicy: "Dogs allowed on paved roads, in parking areas, and in the campground. Not permitted on trails.",
      dogTrails: ["Campground loops", "Bonita Canyon Drive pullouts"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on any hiking trails",
        "Limited to developed areas only",
      ],
      description:
        "About 90 minutes from Bisbee, the 'Wonderland of Rocks' features striking volcanic spires and columns. While dogs cannot access the trails, the scenic Bonita Canyon Drive offers views of this geological wonder.",
      imageUrl: "",
      website: "https://www.nps.gov/chir",
    },
  ],

  restaurants: [
    {
      name: "Bisbee Breakfast Club",
      address: "75A Erie St, Bisbee, AZ 85603",
      lat: 31.4478,
      lng: -109.9288,
      cuisine: "Breakfast & Brunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Famous breakfast spot with huge portions.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bisbeebreakfastclub.com",
    },
    {
      name: "Screaming Banshee Pizza",
      address: "200 Tombstone Canyon, Bisbee, AZ 85603",
      lat: 31.4500,
      lng: -109.9270,
      cuisine: "Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Creative artisan pizza in a funky setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.screamingbansheepizza.com",
    },
    {
      name: "Cafe Roka",
      address: "35 Main St, Bisbee, AZ 85603",
      lat: 31.4481,
      lng: -109.9283,
      cuisine: "Contemporary American",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome at the seasonal outdoor seating.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.caferoka.com",
    },
    {
      name: "Old Bisbee Brewing Company",
      address: "200 Review Alley, Bisbee, AZ 85603",
      lat: 31.4485,
      lng: -109.9278,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly brewery with outdoor seating. Craft beer in an old downtown building.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.oldbisbeebrewingcompany.com",
    },
    {
      name: "Santiago's Mexican Restaurant",
      address: "1 Howell Ave, Bisbee, AZ 85603",
      lat: 31.4476,
      lng: -109.9290,
      cuisine: "Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Authentic Mexican food with Sonoran influence.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.santiagosbisbee.com",
    },
  ],

  cafes: [
    {
      name: "Bisbee Coffee Company",
      address: "2 Copper Queen Plz, Bisbee, AZ 85603",
      lat: 31.4483,
      lng: -109.9282,
      dogPolicy: "Dogs welcome at outdoor tables. Fresh-roasted coffee on the plaza.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bisbeecoffee.com",
    },
    {
      name: "Cafe Cornucopia",
      address: "14 Main St, Bisbee, AZ 85603",
      lat: 31.4482,
      lng: -109.9287,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Organic coffee and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cafecornucopiabisbee.com",
    },
    {
      name: "High Desert Market & Cafe",
      address: "203 Tombstone Canyon, Bisbee, AZ 85603",
      lat: 31.4502,
      lng: -109.9268,
      dogPolicy: "Dogs welcome at the outdoor seating area. Natural foods market and cafe.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.highdesertmarket.com",
    },
    {
      name: "Copper Queen Library Coffee Cart",
      address: "6 Main St, Bisbee, AZ 85603",
      lat: 31.4481,
      lng: -109.9288,
      dogPolicy: "Leashed dogs welcome at the outdoor standing area. Quick coffee stop on Main Street.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.bisbeelibrarycoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Bisbee Stairway Hikes",
      address: "Various stairways, Bisbee, AZ 85603",
      lat: 31.4490,
      lng: -109.9275,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Historic stairways", "Mountain views", "Colorful houses", "Exercise workout", "Photo opportunities"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Bisbee's famous network of over 1,000 stairways connecting hillside neighborhoods is one of the most unique dog walks in America. The steep climbs reward with stunning views and quirky yard art.",
    },
    {
      name: "Warren Ballpark Dog Area",
      address: "Arizona St, Bisbee, AZ 85603",
      lat: 31.4310,
      lng: -109.9190,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Open field", "Shade trees", "Water fountain", "Parking"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A fenced off-leash area near the historic Warren Ballpark. Dogs enjoy the open space while owners appreciate the mountain views and relaxed Bisbee atmosphere.",
    },
    {
      name: "Tombstone Canyon Trail",
      address: "Tombstone Canyon, Bisbee, AZ 85603",
      lat: 31.4530,
      lng: -109.9240,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Canyon hiking", "Mining history", "Mountain views", "Desert plants", "Quiet trails"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Hiking up Tombstone Canyon takes you past historic mining structures and into the Mule Mountains. Leashed dogs enjoy the varied desert terrain and the fascinating remnants of Bisbee's mining past.",
    },
    {
      name: "Vista Park",
      address: "Vista Park, Bisbee, AZ 85603",
      lat: 31.4470,
      lng: -109.9295,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["Panoramic views", "Benches", "Shade trees", "Walking paths", "Photography spot"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A small hilltop park offering panoramic views of old Bisbee and the surrounding Mule Mountains. The on-leash walk to the viewpoint is short but rewarding for both dogs and their photographers.",
    },
  ],
};
