export const blockIslandData = {
  city: {
    name: "Block Island",
    state: "Rhode Island",
    region: "Northeast",
    lat: 41.1761,
    lng: -71.5775,
    dogFriendlinessScore: 7,
    description:
      "This car-free-feeling island off the Rhode Island coast is a magical escape where dogs can explore dramatic bluffs, pristine beaches, and miles of nature trails. Block Island's laid-back island culture means your pup is welcome at outdoor restaurants, on bike paths, and at the stunning Mohegan Bluffs.",
    heroImage: "https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 1033,
  },
  hotels: [
    {
      name: "The 1661 Inn",
      address: "1 Spring St, Block Island, RI 02807",
      lat: 41.1733,
      lng: -71.5571,
      priceRange: "$$$" as const,
      dogPolicy: "Select pet-friendly rooms with a $50 per night fee. Ocean views and a deck where guests bring their dogs.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Ocean views", "Deck seating", "Walking distance to town", "Farm animals on property"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.blockislandresorts.com",
      phone: "(401) 466-2421",
    },
    {
      name: "The National Hotel",
      address: "36 Water St, Block Island, RI 02807",
      lat: 41.1742,
      lng: -71.5574,
      priceRange: "$$$" as const,
      dogPolicy: "Historic grand hotel welcoming dogs in select rooms with a $75 per stay fee. Wrap-around porch and harbor views.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Wrap-around porch", "Harbor views", "Downtown location", "Historic charm"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.blockislandhotels.com",
      phone: "(401) 466-2901",
    },
    {
      name: "Rose Farm Inn",
      address: "1 Roslyn Rd, Block Island, RI 02807",
      lat: 41.1698,
      lng: -71.5601,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms in this charming farmhouse inn with a $30 per night fee. Garden grounds for dog walks.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Garden grounds", "Ocean views", "Quiet setting", "Near bike rentals"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.rosefarminn.com",
      phone: "(401) 466-2034",
    },
    {
      name: "The Hygeia House",
      address: "Beach Ave, Block Island, RI 02807",
      lat: 41.1723,
      lng: -71.5558,
      priceRange: "$$" as const,
      dogPolicy: "Cottage-style inn welcoming dogs with a $25 per night fee. Near Crescent Beach with island charm.",
      maxDogWeight: 60,
      petFee: 25,
      amenities: ["Near beach", "Cottage style", "Porch seating", "Bike rentals nearby"],
      rating: 4.1,
      imageUrl: "",
      website: "",
      phone: "(401) 466-2616",
    },
  ],
  nationalParks: [
    {
      name: "Block Island National Wildlife Refuge",
      state: "Rhode Island",
      lat: 41.2097,
      lng: -71.5826,
      dogPolicy: "Leashed dogs welcome on trails. The northern tip of Block Island with sandy beaches and maritime shrubland.",
      dogTrails: ["Sandy Point Trail", "Settler's Rock Trail", "North Light Trail"],
      restrictions: ["Leash required at all times", "Stay on marked trails during nesting season", "Clean up required"],
      description:
        "The wild northern tip of Block Island where sandy beaches, dunes, and maritime shrubland create a dramatic landscape. The trail to the 1867 North Light lighthouse crosses a sandy spit with ocean on both sides — your leashed dog will be surrounded by salt air and sea breezes in every direction.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/block-island",
    },
    {
      name: "Mohegan Bluffs",
      state: "Rhode Island",
      lat: 41.1509,
      lng: -71.5684,
      dogPolicy: "Leashed dogs welcome on the bluff-top trail. One of the most dramatic coastal landscapes in New England.",
      dogTrails: ["Bluff Trail", "Beach Stairway (141 steps)", "Greenway Trail Connection"],
      restrictions: ["Leash required", "Stay back from bluff edges", "Steep stairs to beach"],
      description:
        "Towering 200-foot clay cliffs dropping dramatically to the Atlantic Ocean, with views stretching to Montauk on clear days. The bluff-top trail offers jaw-dropping overlooks, and 141 wooden stairs descend to a private-feeling beach below. Your leashed dog will love the wind at the top and the sand at the bottom.",
      imageUrl: "",
      website: "https://www.blockislandinfo.com",
    },
    {
      name: "The Greenway Trails",
      state: "Rhode Island",
      lat: 41.1724,
      lng: -71.5733,
      dogPolicy: "Leashed dogs welcome on all 28 miles of interconnected trails crisscrossing the island.",
      dogTrails: ["Rodman's Hollow Trail", "Fresh Pond Trail", "Enchanted Forest Trail", "Clay Head Trail"],
      restrictions: ["Leash required", "Respect private property boundaries", "Clean up required"],
      description:
        "A remarkable network of 28 miles of nature trails maintained by conservation organizations, threading through meadows, along stone walls, past freshwater ponds, and through maritime forest. The Clay Head Trail along the eastern bluffs is a highlight. Block Island has protected over 40% of its land for trails.",
      imageUrl: "",
      website: "https://www.biconservancy.org",
    },
  ],
  restaurants: [
    {
      name: "The Oar",
      address: "221 Jobs Hill Rd, Block Island, RI 02807",
      lat: 41.162,
      lng: -71.6007,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Waterfront restaurant at New Harbor with a dog-friendly deck. Fresh seafood and sunset views over Great Salt Pond.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.theoarbi.com",
    },
    {
      name: "Mohegan Cafe & Brewery",
      address: "213 Water St, Block Island, RI 02807",
      lat: 41.1741,
      lng: -71.5578,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Island brewery with a dog-friendly outdoor area. House-brewed beers and solid pub fare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.mohegancafe.com",
    },
    {
      name: "The Beachhead",
      address: "Corn Neck Rd, Block Island, RI 02807",
      lat: 41.1815,
      lng: -71.5616,
      cuisine: "American",
      priceRange: "$" as const,
      dogPolicy: "Casual beach bar with outdoor seating. Dogs welcome on the patio. Cold drinks and simple fare with ocean breezes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "",
    },
    {
      name: "Eli's",
      address: "456 Chapel St, Block Island, RI 02807",
      lat: 41.1734,
      lng: -71.5574,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Upscale island dining with a garden patio. Leashed dogs welcome outside. Italian-inspired menu with island ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.elisblocksisland.com",
    },
    {
      name: "Kimberly's",
      address: "High St, Block Island, RI 02807",
      lat: 41.1725,
      lng: -71.5585,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Cozy restaurant with a porch. Leashed dogs welcome in outdoor seating. Classic American fare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
  ],
  cafes: [
    {
      name: "Juice n' Java",
      address: "Dodge St, Block Island, RI 02807",
      lat: 41.1735,
      lng: -71.5579,
      dogPolicy: "Island coffee shop with outdoor seating near the ferry landing. Dogs welcome. Great smoothies and coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Block Island Coffee Roasters",
      address: "Water St, Block Island, RI 02807",
      lat: 41.1738,
      lng: -71.5575,
      dogPolicy: "Local roaster with a patio overlooking the harbor. Dogs welcome while you sip island-roasted coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Aldo's Bakery & Coffee",
      address: "130 Weldon's Way, Block Island, RI 02807",
      lat: 41.1729,
      lng: -71.5583,
      dogPolicy: "Italian bakery with outdoor benches. Dogs welcome outside while you enjoy fresh pastries and espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "The Yellow Kittens",
      address: "Corn Neck Rd, Block Island, RI 02807",
      lat: 41.1805,
      lng: -71.561,
      dogPolicy: "Casual cafe near the beaches with outdoor seating. Dogs welcome for a coffee and pastry stop during beach explorations.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Crescent Beach",
      address: "Corn Neck Rd, Block Island, RI 02807",
      lat: 41.1858,
      lng: -71.5596,
      offLeash: true,
      fenced: false,
      acres: 8.0,
      amenities: ["Sandy beach", "Off-leash seasonal", "Ocean swimming", "Mile-long stretch", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A gorgeous mile-long crescent of sand on the island's eastern shore where dogs can run off-leash during the off-season. The gentle surf, clean sand, and stunning views make this one of the finest dog beaches in New England. During summer, dogs are restricted to early morning and evening hours.",
    },
    {
      name: "Rodman's Hollow",
      address: "Black Rock Rd, Block Island, RI 02807",
      lat: 41.1574,
      lng: -71.5773,
      offLeash: false,
      fenced: false,
      acres: 40.0,
      amenities: ["Glacial hollow", "Wildflower meadows", "Ocean views", "Trail connections", "Nature preserve"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A dramatic glacial outwash basin that was Block Island's first protected land. Trails descend through the hollow's wildflower meadows and maritime shrubland to the dramatic southern coast. Your leashed dog will experience a unique landscape found nowhere else in Rhode Island.",
    },
    {
      name: "Clay Head Nature Trail",
      address: "Clay Head, Block Island, RI 02807",
      lat: 41.1979,
      lng: -71.5479,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Bluff-top views", "Maze-like trails", "Wildflowers", "Clay cliffs", "Quiet setting"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Known locally as 'The Maze,' this network of trails wanders through thickets and meadows atop clay bluffs on the island's northeast shore. The bluff-top views of the Atlantic are spectacular, and the maze-like trail system creates a sense of exploration and discovery for both you and your leashed dog.",
    },
    {
      name: "Sachem Pond Area",
      address: "Corn Neck Rd, Block Island, RI 02807",
      lat: 41.2011,
      lng: -71.575,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Pond views", "Walking paths", "Bird watching", "Quiet setting", "Nature photography"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A peaceful area around Sachem Pond on the island's northern end, with walking paths through grasslands and coastal scrub. The pond attracts migrating birds and the surrounding landscape has a wild, windswept beauty. A quiet spot for a contemplative walk with your leashed dog.",
    },
  ],
};
