export const blowingRockData = {
  city: {
    name: "Blowing Rock",
    state: "North Carolina",
    region: "Southeast",
    lat: 36.1351,
    lng: -81.6776,
    dogFriendlinessScore: 8,
    description:
      "This charming Blue Ridge Mountain village is one of the most dog-friendly small towns in the Southeast, with nearly every shop and restaurant welcoming four-legged visitors. Cool mountain air, stunning parkway vistas, and miles of hiking trails make it a perfect pup-friendly escape.",
    heroImage: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1200&fit=crop",
    climate: "Humid continental",
    population: 1241,
  },
  hotels: [
    {
      name: "The New Public House & Hotel",
      address: "239 Sunset Dr, Blowing Rock, NC 28605",
      lat: 36.1340,
      lng: -81.6790,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in designated pet rooms with a pet fee. A charming boutique hotel in the heart of the village.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking map", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thenewpublichouse.com",
      phone: "(828) 295-3487",
    },
    {
      name: "Meadowbrook Inn",
      address: "711 Main St, Blowing Rock, NC 28605",
      lat: 36.1330,
      lng: -81.6730,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome with a per-night pet fee. A comfortable inn on Main Street with mountain views.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Pet-friendly rooms", "Grounds for walking", "Water bowls", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.meadowbrook-inn.com",
      phone: "(828) 295-4300",
    },
    {
      name: "Chetola Resort",
      address: "185 Chetola Lake Dr, Blowing Rock, NC 28605",
      lat: 36.1280,
      lng: -81.6880,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select lodge rooms with a non-refundable pet fee. A lakeside mountain resort with extensive grounds.",
      maxDogWeight: 75,
      petFee: 100,
      amenities: ["Dog bed", "Lake access", "Walking trails on property", "Waste bags", "Pet blanket"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.chetola.com",
      phone: "(828) 295-5500",
    },
    {
      name: "Hillwinds Inn",
      address: "315 Sunset Dr, Blowing Rock, NC 28605",
      lat: 36.1345,
      lng: -81.6800,
      priceRange: "$$" as const,
      dogPolicy: "Dogs under 40 lbs welcome with a pet fee. A cozy inn within walking distance of shops and restaurants.",
      maxDogWeight: 40,
      petFee: 50,
      amenities: ["Pet-friendly rooms", "Garden area", "Water bowls", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.hillwindsinn.com",
      phone: "(828) 295-7660",
    },
  ],
  nationalParks: [
    {
      name: "Blue Ridge Parkway",
      state: "North Carolina",
      lat: 36.1000,
      lng: -81.6800,
      dogPolicy: "Dogs welcome on most trails on a 6-foot leash. The scenic parkway passes directly through Blowing Rock with numerous dog-friendly overlooks.",
      dogTrails: ["Bass Lake Trail", "Glen Burney Trail", "Trout Lake Trail", "Price Lake Trail"],
      restrictions: ["6-foot leash required", "Not allowed in buildings", "Must clean up after pet", "Keep distance from wildlife"],
      description: "America's most-visited parkway stretches through the heart of Blowing Rock with spectacular mountain vistas, wildflower meadows, and forested trails. Dogs enjoy the cool high-elevation breezes and stunning scenery.",
      imageUrl: "",
      website: "https://www.nps.gov/blri",
    },
    {
      name: "Moses H. Cone Memorial Park",
      state: "North Carolina",
      lat: 36.1500,
      lng: -81.6940,
      dogPolicy: "Dogs welcome on all carriage roads and trails on a 6-foot leash. Over 25 miles of gentle carriage roads through a beautiful estate.",
      dogTrails: ["Rich Mountain Trail", "Flat Top Road", "Bass Lake Loop", "Figure Eight Trail"],
      restrictions: ["6-foot leash required", "Not allowed in Flat Top Manor", "Must clean up after pet"],
      description: "Adjacent to Blowing Rock, this Blue Ridge Parkway property features a grand estate with over 25 miles of carriage roads winding through forests and around picturesque lakes. Dogs love the gentle grades and scenic surroundings.",
      imageUrl: "",
      website: "https://www.nps.gov/blri/planyourvisit/moses-h-cone-memorial-park.htm",
    },
    {
      name: "Julian Price Memorial Park",
      state: "North Carolina",
      lat: 36.1330,
      lng: -81.7280,
      dogPolicy: "Dogs welcome on trails and in campgrounds on a 6-foot leash. A popular Blue Ridge Parkway recreation area.",
      dogTrails: ["Price Lake Trail", "Boone Fork Trail", "Green Knob Trail"],
      restrictions: ["6-foot leash required", "Not allowed in buildings", "Must clean up after pet"],
      description: "Just south of Blowing Rock on the Blue Ridge Parkway, this park features Price Lake and the beautiful Boone Fork Loop trail. Dogs can hike through rhododendron tunnels and along mountain streams.",
      imageUrl: "",
      website: "https://www.nps.gov/blri/planyourvisit/julian-price-memorial-park.htm",
    },
  ],
  restaurants: [
    {
      name: "The Speckled Trout Restaurant & Bottle Shop",
      address: "922 Main St, Blowing Rock, NC 28605",
      lat: 36.1320,
      lng: -81.6720,
      cuisine: "Southern American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Creative Southern fare with trout, craft beer, and mountain views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thespeckledtrout.com",
    },
    {
      name: "Bistro Roca & Antlers Bar",
      address: "143 Wonderland Trail, Blowing Rock, NC 28605",
      lat: 36.1350,
      lng: -81.6770,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the covered patio. Upscale mountain dining with a cozy lodge atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bistroroca.com",
    },
    {
      name: "Foggy Rock Eatery & Pub",
      address: "8163 Valley Blvd, Blowing Rock, NC 28605",
      lat: 36.1300,
      lng: -81.6840,
      cuisine: "American Pub",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the patio. Casual pub fare with generous portions and a friendly mountain vibe.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.foggyrock.com",
    },
    {
      name: "Timberlake's Restaurant at Chetola",
      address: "185 Chetola Lake Dr, Blowing Rock, NC 28605",
      lat: 36.1280,
      lng: -81.6880,
      cuisine: "Fine Dining American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the lakeside terrace during seasonal dining. Elegant resort dining with stunning lake views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.chetola.com/dining",
    },
    {
      name: "Knight Spirits",
      address: "938 Main St, Blowing Rock, NC 28605",
      lat: 36.1320,
      lng: -81.6715,
      cuisine: "Wine Bar & Small Plates",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. A cozy wine bar with artisan cheese and charcuterie boards.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.knightspirits.com",
    },
  ],
  cafes: [
    {
      name: "Bald Guy Brew",
      address: "8890 Valley Blvd, Blowing Rock, NC 28605",
      lat: 36.1310,
      lng: -81.6850,
      dogPolicy: "Dogs welcome on the patio and even inside during quiet hours. A beloved local roaster with mountain character.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.baldguybrew.com",
    },
    {
      name: "Camp Coffee",
      address: "1105 Main St, Blowing Rock, NC 28605",
      lat: 36.1310,
      lng: -81.6700,
      dogPolicy: "Dogs welcome on the outdoor deck. Camp-themed coffee shop with specialty drinks and a fun atmosphere.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.campcoffee.co",
    },
    {
      name: "Blowing Rock Ale House & Inn",
      address: "152 Sunset Dr, Blowing Rock, NC 28605",
      lat: 36.1345,
      lng: -81.6785,
      dogPolicy: "Dogs welcome on the outdoor patio. Craft beer and coffee with a mountain lodge feel.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.blowingrockbrewing.com",
    },
    {
      name: "Mountain Bakery & Cafe",
      address: "920 Main St, Blowing Rock, NC 28605",
      lat: 36.1320,
      lng: -81.6720,
      dogPolicy: "Dog-friendly outdoor seating on Main Street. Fresh baked goods, sandwiches, and coffee in the village center.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.mountainbakerycafe.com",
    },
  ],
  dogParks: [
    {
      name: "Broyhill Park",
      address: "Main St, Blowing Rock, NC 28605",
      lat: 36.1340,
      lng: -81.6750,
      offLeash: false,
      fenced: false,
      acres: 3,
      amenities: ["Mountain views", "Walking paths", "Gazebo", "Benches", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "A scenic village park at the end of Main Street with panoramic mountain views of the Johns River Gorge. While not off-leash, the gentle walking paths and stunning vistas make it a must-visit for dog walkers.",
    },
    {
      name: "Bass Lake Park",
      address: "301 Bass Lake Dr, Blowing Rock, NC 28605",
      lat: 36.1410,
      lng: -81.6960,
      offLeash: false,
      fenced: false,
      acres: 10,
      amenities: ["Lake loop trail", "Fishing pier", "Picnic areas", "Benches", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "A picturesque mountain lake within the Moses H. Cone Memorial Park. The 0.6-mile loop trail around the lake is a favorite on-leash dog walk with beautiful reflections and rhododendron-lined shores.",
    },
    {
      name: "Glen Burney Trail",
      address: "Annie Cannon Park, Blowing Rock, NC 28605",
      lat: 36.1370,
      lng: -81.6810,
      offLeash: false,
      fenced: false,
      acres: 25,
      amenities: ["Waterfall views", "Forest trails", "Stream crossings", "Natural terrain"],
      rating: 4.4,
      imageUrl: "",
      description: "A moderately challenging trail starting from the village that leads to two stunning waterfalls. Dogs on leash can navigate the forest path and enjoy the cool mountain stream crossings.",
    },
    {
      name: "Blowing Rock Community Park",
      address: "150 Wallingford St, Blowing Rock, NC 28605",
      lat: 36.1355,
      lng: -81.6765,
      offLeash: false,
      fenced: false,
      acres: 5,
      amenities: ["Walking paths", "Green space", "Benches", "Shade trees", "Waste bag stations"],
      rating: 4.1,
      imageUrl: "",
      description: "A pleasant community park in the village with open green space and walking paths. Dogs enjoy the central location and easy access to Main Street shops and restaurants.",
    },
  ],
};
