export const bostonData = {
  city: {
    name: "Boston",
    state: "Massachusetts",
    region: "Northeast",
    lat: 40.3601,
    lng: -71.0589,
    dogFriendlinessScore: 7,
    description:
      "Boston's historic charm extends to its four-legged residents, with the Emerald Necklace park system offering miles of connected green space perfect for dog walks. From the dog-friendly patios of the South End to off-leash romps on Carson Beach, Beantown knows how to welcome pups.",
    heroImage: "https://images.unsplash.com/photo-1501979376754-1d0497e0f0ec?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 675647,
  },
  hotels: [
    {
      name: "The Liberty Hotel",
      address: "215 Charles St, Boston, MA 02114",
      lat: 42.3632,
      lng: -71.0703,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs of any size welcome with no additional fee. Complimentary dog bed, bowls, and treats. Located steps from the Charles River Esplanade.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Dog bed", "Treats", "Charles River access", "Beacon Hill location"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.libertyhotel.com",
      phone: "(617) 224-4000",
    },
    {
      name: "Kimpton Marlowe Hotel",
      address: "25 Edwin H Land Blvd, Cambridge, MA 02141",
      lat: 42.3679,
      lng: -71.0764,
      priceRange: "$$$" as const,
      dogPolicy: "All pets welcome regardless of size at no extra charge. Kimpton's signature pet program includes beds, bowls, and a welcome treat.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pet bed", "Welcome treats", "Cambridge Riverwalk", "Near MIT"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hotelmarlowe.com",
      phone: "(617) 868-8000",
    },
    {
      name: "The Verb Hotel",
      address: "1271 Boylston St, Boston, MA 02215",
      lat: 42.3467,
      lng: -71.0969,
      priceRange: "$$$" as const,
      dogPolicy: "Rock-and-roll themed hotel welcomes dogs under 50 lbs with a $50 per stay fee. Near Fenway Park.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Fenway Park location", "Retro pool", "Dog walking area", "Music memorabilia"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.theverbhotel.com",
      phone: "(617) 566-4500",
    },
    {
      name: "Residence Inn Boston Harbor",
      address: "370 Congress St, Boston, MA 02210",
      lat: 42.3514,
      lng: -71.0474,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a $100 non-refundable pet fee. Suite-style rooms with full kitchens near the Seaport.",
      maxDogWeight: 75,
      petFee: 100,
      amenities: ["Full kitchen", "Seaport location", "Harborwalk access", "Grocery delivery", "Pet relief area"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(617) onal-9000",
    },
  ],
  nationalParks: [
    {
      name: "Boston Harbor Islands National Recreation Area",
      state: "Massachusetts",
      lat: 42.3199,
      lng: -70.9286,
      dogPolicy: "Leashed dogs welcome on Spectacle Island and Georges Island. Not permitted on ferries during peak season — check schedules.",
      dogTrails: ["Spectacle Island Loop Trail", "Georges Island Fort Walk", "North Drumlin Trail"],
      restrictions: ["Leash required at all times", "Not allowed on all islands", "Check ferry pet policy", "Clean up required"],
      description:
        "A chain of 34 islands in Boston Harbor offering hiking trails, beaches, and Civil War-era forts. Spectacle Island is the most dog-friendly, with five miles of trails and a pet-friendly beach. The views of the Boston skyline from the water are unforgettable for humans — dogs prefer the smells.",
      imageUrl: "",
      website: "https://www.nps.gov/boha",
    },
    {
      name: "Blue Hills Reservation",
      state: "Massachusetts",
      lat: 42.2168,
      lng: -71.1009,
      dogPolicy: "Dogs welcome on all trails on leash. Over 7,000 acres of forests, ponds, and rocky summits just south of the city.",
      dogTrails: ["Great Blue Hill Summit Trail", "Skyline Trail", "Ponkapoag Pond Trail", "Buck Hill Trail"],
      restrictions: ["Leash required", "No dogs at Houghtons Pond swimming area", "Clean up required"],
      description:
        "The largest open space within 35 miles of Boston, Blue Hills offers rugged trails through rocky terrain with sweeping views of the city skyline. The Skyline Trail traverses multiple summits and feels like a mountain adventure despite being minutes from downtown. Your pup will love the diverse terrain.",
      imageUrl: "",
      website: "https://www.mass.gov/locations/blue-hills-reservation",
    },
    {
      name: "Middlesex Fells Reservation",
      state: "Massachusetts",
      lat: 42.4483,
      lng: -71.1052,
      dogPolicy: "Dogs allowed on leash throughout the reservation. Rocky trails and reservoir views await.",
      dogTrails: ["Skyline Trail", "Cross Fells Trail", "Rock Circuit Trail", "Reservoir Trail"],
      restrictions: ["Leash required at all times", "No swimming in reservoirs", "Stay on marked trails"],
      description:
        "Over 2,500 acres of rocky forest just north of Boston, the Fells feels wild and rugged despite its suburban location. The trails wind past glacial boulders, through hemlock groves, and along sparkling reservoirs. It's a favorite year-round destination for Boston dog owners seeking a quick nature fix.",
      imageUrl: "",
      website: "https://www.mass.gov/locations/middlesex-fells-reservation",
    },
  ],
  restaurants: [
    {
      name: "The Barking Crab",
      address: "88 Sleeper St, Boston, MA 02210",
      lat: 42.3522,
      lng: -71.0484,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Iconic waterfront seafood shack with a massive outdoor tent. Dogs welcome at outdoor picnic tables.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.barkingcrab.com",
    },
    {
      name: "Tatte Bakery & Cafe",
      address: "70 Charles St, Boston, MA 02114",
      lat: 42.3589,
      lng: -71.0714,
      cuisine: "Mediterranean",
      priceRange: "$$" as const,
      dogPolicy: "Beacon Hill location with sidewalk tables where leashed dogs are welcome. Israeli-inspired pastries and brunch.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.tattebakery.com",
    },
    {
      name: "The Salty Pig",
      address: "130 Dartmouth St, Boston, MA 02116",
      lat: 42.3473,
      lng: -71.0774,
      cuisine: "Italian",
      priceRange: "$$" as const,
      dogPolicy: "South End gastropub with a dog-friendly patio. Charcuterie boards, house-made pasta, and craft beer.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thesaltypig.com",
    },
    {
      name: "Night Shift Brewing Lovejoy Wharf",
      address: "1 Lovejoy Wharf, Boston, MA 02114",
      lat: 42.3668,
      lng: -71.0578,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Waterfront taproom with a huge dog-friendly outdoor area overlooking the Charles River. Dogs are regulars here.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.nightshiftbrewing.com",
    },
    {
      name: "Coppa Enoteca",
      address: "253 Shawmut Ave, Boston, MA 02118",
      lat: 42.3427,
      lng: -71.072,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Cozy South End wine bar with sidewalk seating. Leashed dogs welcome outside while you enjoy wood-fired pizza and Italian small plates.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.coppaboston.com",
    },
  ],
  cafes: [
    {
      name: "George Howell Coffee",
      address: "505 Washington St, Boston, MA 02111",
      lat: 42.3535,
      lng: -71.0612,
      dogPolicy: "Specialty coffee pioneer with outdoor seating in Downtown Crossing. Leashed dogs welcome at patio tables.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.georgehowellcoffee.com",
    },
    {
      name: "Thinking Cup",
      address: "165 Tremont St, Boston, MA 02111",
      lat: 42.3536,
      lng: -71.0632,
      dogPolicy: "Stumptown coffee served near Boston Common. Outdoor benches perfect for dog-watching on Tremont Street.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thinkingcup.com",
    },
    {
      name: "Pavement Coffeehouse",
      address: "286 Newbury St, Boston, MA 02115",
      lat: 42.3493,
      lng: -71.0867,
      dogPolicy: "Local favorite on Newbury Street with prime people-and-dog-watching sidewalk seating. Bagel sandwiches are legendary.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.pavementcoffeehouse.com",
    },
    {
      name: "Broadsheet Coffee Roasters",
      address: "100 Hanover St, Boston, MA 02108",
      lat: 42.3636,
      lng: -71.0544,
      dogPolicy: "North End coffee roaster with a small outdoor seating area. Dogs welcome while you enjoy expertly roasted espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.broadsheetcoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Peter's Park Dog Run",
      address: "230 E Berkeley St, Boston, MA 02118",
      lat: 42.3414,
      lng: -71.0656,
      offLeash: true,
      fenced: true,
      acres: 0.25,
      amenities: ["Fully fenced", "Water fountain", "Benches", "Shade", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "The South End's beloved fenced dog park is a social hub for neighborhood pups. The compact but well-maintained space features a water fountain, shade trees, and benches for tired owners. The community vibe is strong — regulars know every dog by name.",
    },
    {
      name: "Charles River Esplanade Dog Exercise Area",
      address: "Charles River Esplanade, Boston, MA 02114",
      lat: 42.3565,
      lng: -71.0786,
      offLeash: true,
      fenced: true,
      acres: 0.5,
      amenities: ["River views", "Fenced area", "Water access", "Walking paths", "Benches"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A fenced off-leash area along the Charles River Esplanade with stunning views of Cambridge across the water. After play time, leash up and stroll the miles of riverfront paths. Sailboats glide by on the Charles while your pup makes new friends.",
    },
    {
      name: "Ronan Park Dog Run",
      address: "92 Mt Ida Rd, Dorchester, MA 02122",
      lat: 42.3062,
      lng: -71.0594,
      offLeash: true,
      fenced: true,
      acres: 0.75,
      amenities: ["Double-gated entry", "Hilltop views", "Benches", "Water fountain", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      description:
        "Perched atop a hill in Dorchester, this fenced dog park offers panoramic views of the Boston skyline and harbor. The grassy terrain is well-maintained and the double-gated entry keeps escapees in check. A hidden gem that locals prefer to keep secret.",
    },
    {
      name: "Magazine Beach Dog Park",
      address: "719 Memorial Dr, Cambridge, MA 02139",
      lat: 42.3541,
      lng: -71.1102,
      offLeash: true,
      fenced: true,
      acres: 0.6,
      amenities: ["Charles River views", "Fenced", "Water spigot", "Benches", "Adjacent walking paths"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Cambridge's popular riverside dog park sits along the Charles River with views of the Boston skyline. The fenced area is spacious enough for serious zoomies, and the adjacent riverfront path is perfect for a post-play cool-down walk.",
    },
  ],
};
