export const boulderData = {
  city: {
    name: "Boulder",
    state: "Colorado",
    region: "Mountain West",
    lat: 40.0150,
    lng: -105.2705,
    dogFriendlinessScore: 9,
    description:
      "Boulder is a dog lover's dream nestled against the dramatic Flatirons. With an extensive voice-and-sight off-leash trail system, dog-friendly patios on Pearl Street, and a community that treats dogs as first-class citizens, this outdoor-obsessed college town consistently ranks among the most dog-friendly cities in the nation.",
    heroImage: "https://images.unsplash.com/photo-1546156929-a4c0ac411f47?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 105880,
  },

  hotels: [
    {
      name: "St Julien Hotel & Spa",
      address: "900 Walnut St, Boulder, CO 80302",
      lat: 40.0169,
      lng: -105.2777,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 100 lbs welcome with a one-time pet fee. Luxury pet amenities upon arrival.",
      maxDogWeight: 100,
      petFee: 75,
      amenities: ["Orthopedic dog bed", "Food and water bowls", "Gourmet treats", "Walking route maps", "Dog-sitting referral"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.stjulien.com",
      phone: "(720) 406-9696",
    },
    {
      name: "Hotel Boulderado",
      address: "2115 13th St, Boulder, CO 80302",
      lat: 40.0193,
      lng: -105.2774,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in designated pet-friendly rooms. Historic charm meets modern pet hospitality.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Treats", "Steps from Pearl Street Mall"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.boulderado.com",
      phone: "(303) 442-4344",
    },
    {
      name: "Basecamp Boulder",
      address: "2020 Arapahoe Ave, Boulder, CO 80302",
      lat: 40.0145,
      lng: -105.2721,
      priceRange: "$$" as const,
      dogPolicy: "Adventure-minded hotel welcoming all dogs. No size limits, no breed restrictions.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Dog bed", "Bowls", "Trail recommendation guide", "Gear rinse station", "Nearby creek trail"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.basecampboulder.com",
      phone: "(303) 449-7550",
    },
    {
      name: "Bradley Boulder Inn",
      address: "2040 16th St, Boulder, CO 80302",
      lat: 40.0210,
      lng: -105.2815,
      priceRange: "$$$" as const,
      dogPolicy: "Select rooms are dog-friendly. Well-behaved dogs of any size welcome with advance notice.",
      maxDogWeight: 0,
      petFee: 45,
      amenities: ["Dog bed", "Organic treats", "Water bowl", "Fenced garden area", "Complimentary breakfast"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thebradleyboulder.com",
      phone: "(303) 545-5200",
    },
    {
      name: "Residence Inn by Marriott Boulder",
      address: "3030 Center Green Dr, Boulder, CO 80301",
      lat: 40.0248,
      lng: -105.2486,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a nightly pet fee. Extended-stay suites with full kitchens are great for longer trips.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Full kitchen", "Grassy walking areas", "Near Boulder Creek Path", "Waste stations", "Grocery delivery"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(303) 449-5545",
    },
  ],

  nationalParks: [
    {
      name: "Rocky Mountain National Park",
      state: "Colorado",
      lat: 40.3428,
      lng: -105.6836,
      dogPolicy: "Dogs allowed on roads, in parking areas, picnic areas, and campgrounds only. Not permitted on any trails or in the backcountry.",
      dogTrails: ["Campground loops at Moraine Park", "Glacier Basin Campground roads"],
      restrictions: [
        "No dogs on any trails",
        "Must be on leash (6 ft max) at all times",
        "Not allowed in meadows, along waterways, or in backcountry",
        "Not permitted on the shuttle bus",
      ],
      description:
        "Just 40 minutes from Boulder, Rocky Mountain National Park features soaring peaks above 14,000 feet, alpine lakes, and abundant wildlife. While trail access for dogs is not permitted, the scenic drives and campgrounds still offer a taste of the high country with your pup.",
      imageUrl: "",
      website: "https://www.nps.gov/romo",
    },
    {
      name: "Great Sand Dunes National Park",
      state: "Colorado",
      lat: 37.7326,
      lng: -105.5943,
      dogPolicy: "Dogs allowed on Medano Creek, the sand dunes themselves, the Medano Pass road, and in campgrounds. One of the more dog-friendly national parks.",
      dogTrails: [
        "Medano Creek beach area",
        "Sand dunes (open roaming, leashed)",
        "Medano Pass Primitive Road",
        "Point of No Return Trail (first mile)",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Not allowed on backcountry trails beyond dunes",
        "Watch for hot sand temperatures in summer",
      ],
      description:
        "Home to North America's tallest sand dunes rising over 700 feet, this surreal landscape allows leashed dogs on the dunes themselves and along the seasonal Medano Creek. A rare national park where your dog can share the main attraction with you.",
      imageUrl: "",
      website: "https://www.nps.gov/grsa",
    },
    {
      name: "Black Canyon of the Gunnison National Park",
      state: "Colorado",
      lat: 38.5754,
      lng: -107.7416,
      dogPolicy: "Dogs allowed on the rim roads, overlooks, campgrounds, and three specific trails on the South Rim.",
      dogTrails: [
        "Rim Rock Trail",
        "Cedar Point Nature Trail",
        "North Rim Chasm View Nature Trail",
      ],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed in the inner canyon",
        "Not allowed on most hiking trails",
      ],
      description:
        "The Black Canyon's steep, narrow gorge plunges over 2,000 feet to the Gunnison River below. While inner canyon access is off-limits to dogs, the rim trails and overlooks offer stunning views of one of Colorado's most dramatic landscapes.",
      imageUrl: "",
      website: "https://www.nps.gov/blca",
    },
    {
      name: "Florissant Fossil Beds National Monument",
      state: "Colorado",
      lat: 38.9145,
      lng: -105.2814,
      dogPolicy: "Leashed dogs welcome on all trails. One of the most dog-friendly NPS sites in Colorado.",
      dogTrails: [
        "Petrified Forest Loop",
        "Walk Through Time Trail",
        "Hornbek Wildlife Loop",
        "Boulder Creek Trail",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Not allowed in the visitor center",
        "Must stay on established trails",
      ],
      description:
        "This hidden gem preserves an ancient lake bed filled with exquisitely detailed fossils from 34 million years ago, including petrified redwood stumps. All trails welcome leashed dogs, making it a perfect day trip from Boulder.",
      imageUrl: "",
      website: "https://www.nps.gov/flfo",
    },
  ],

  restaurants: [
    {
      name: "The Kitchen",
      address: "1039 Pearl St, Boulder, CO 80302",
      lat: 40.0186,
      lng: -105.2768,
      cuisine: "Farm-to-Table American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor patio overlooking Pearl Street.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thekitchenbistros.com",
    },
    {
      name: "Avery Brewing Taproom",
      address: "4910 Nautilus Ct N, Boulder, CO 80301",
      lat: 40.0635,
      lng: -105.2113,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Extremely dog-friendly with a large outdoor beer garden. Dog treats behind the bar.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.averybrewing.com",
    },
    {
      name: "West Flanders Brewing Co.",
      address: "1125 Pearl St, Boulder, CO 80302",
      lat: 40.0186,
      lng: -105.2753,
      cuisine: "Belgian-American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the large Pearl Street patio. Water bowls and treats available.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.wfbrews.com",
    },
    {
      name: "The Sink",
      address: "1165 13th St, Boulder, CO 80302",
      lat: 40.0084,
      lng: -105.2770,
      cuisine: "American",
      priceRange: "$" as const,
      dogPolicy: "Boulder institution with a dog-friendly patio. Burgers, pizza, and a legendary atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.thesink.com",
    },
    {
      name: "Mountain Sun Pub & Brewery",
      address: "1535 Pearl St, Boulder, CO 80302",
      lat: 40.0189,
      lng: -105.2690,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. A cash-only Boulder favorite since 1993.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.mountainsunpub.com",
    },
    {
      name: "Blackbelly Market",
      address: "1606 Conestoga St, Boulder, CO 80301",
      lat: 40.0272,
      lng: -105.2487,
      cuisine: "Whole-Animal Butcher & Restaurant",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved, leashed dogs welcome at the outdoor patio tables.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.blackbelly.com",
    },
    {
      name: "Rincon Argentino",
      address: "2525 Arapahoe Ave, Boulder, CO 80302",
      lat: 40.0140,
      lng: -105.2602,
      cuisine: "Argentinian",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor seating area. Empanadas and mate in a cozy setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.rinconargentinoboulder.com",
    },
    {
      name: "Illegal Pete's",
      address: "1447 Pearl St, Boulder, CO 80302",
      lat: 40.0188,
      lng: -105.2704,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the front patio along Pearl Street. Mission-style burritos and a laid-back vibe.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.illegalpetes.com",
    },
  ],

  cafes: [
    {
      name: "Ozo Coffee Company",
      address: "1015 Pearl St, Boulder, CO 80302",
      lat: 40.0186,
      lng: -105.2772,
      dogPolicy: "Spacious patio on Pearl Street where leashed dogs are always welcome. Water bowls provided.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ozocoffee.com",
    },
    {
      name: "The Laughing Goat",
      address: "1709 Pearl St, Boulder, CO 80302",
      lat: 40.0190,
      lng: -105.2665,
      dogPolicy: "Dogs welcome at outdoor tables along the Pearl Street Mall.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thelaughinggoat.com",
    },
    {
      name: "Boxcar Coffee Roasters",
      address: "1825 Pearl St, Boulder, CO 80302",
      lat: 40.0191,
      lng: -105.2646,
      dogPolicy: "Minimalist, high-quality coffee with a dog-friendly outdoor patio.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.boxcarcoffeeroasters.com",
    },
    {
      name: "Alpine Modern Cafe",
      address: "901 Pearl St, Boulder, CO 80302",
      lat: 40.0184,
      lng: -105.2788,
      dogPolicy: "Stylish cafe with a front patio where leashed dogs are welcome. Dog biscuits available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.alpinemodern.com",
    },
    {
      name: "Trident Booksellers & Cafe",
      address: "940 Pearl St, Boulder, CO 80302",
      lat: 40.0185,
      lng: -105.2782,
      dogPolicy: "Legendary Boulder bookstore-cafe with sidewalk seating where dogs are welcome.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tridentcafe.com",
    },
  ],

  dogParks: [
    {
      name: "Valmont Dog Park",
      address: "5275 Valmont Rd, Boulder, CO 80301",
      lat: 40.0228,
      lng: -105.2371,
      offLeash: true,
      fenced: true,
      acres: 6.0,
      amenities: ["Separate small dog area", "Water spigots", "Shade shelters", "Waste stations", "Agility equipment", "Parking lot"],
      rating: 4.7,
      imageUrl: "",
      description:
        "Boulder's premier off-leash dog park features six acres of open space with a separate small-dog area, water features, and agility equipment. The Flatirons provide a stunning backdrop while your pup plays.",
    },
    {
      name: "East Boulder Community Park Dog Run",
      address: "5660 Sioux Dr, Boulder, CO 80303",
      lat: 39.9916,
      lng: -105.2276,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Double-gated entry", "Benches", "Waste stations", "Water fountain", "Shade trees"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A spacious fenced dog park on the east side of town with a relaxed atmosphere. Less crowded than Valmont, it is a great option for dogs that prefer a quieter play environment.",
    },
    {
      name: "Shanahan Ridge Trail (Voice & Sight)",
      address: "Shanahan Trailhead, Boulder, CO 80305",
      lat: 39.9812,
      lng: -105.2647,
      offLeash: true,
      fenced: false,
      acres: 50.0,
      amenities: ["Mountain trails", "Flatirons views", "Waste stations", "Parking"],
      rating: 4.8,
      imageUrl: "",
      description:
        "Part of Boulder's unique voice-and-sight off-leash program, this trail network lets well-trained dogs hike off-leash through meadows and forests below the Flatirons. Dogs must respond to voice commands to be off-leash.",
    },
    {
      name: "Foothills Community Park Dog Area",
      address: "800 Cherry Ave, Boulder, CO 80304",
      lat: 40.0275,
      lng: -105.2622,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Double-gated entry", "Water station", "Shade structures", "Benches", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A well-maintained neighborhood dog park in north Boulder with reliable water access and good shade. Popular with locals for early morning and evening visits.",
    },
    {
      name: "Boulder Creek Path (Voice & Sight Area)",
      address: "Boulder Creek Path, Boulder, CO 80302",
      lat: 40.0172,
      lng: -105.2625,
      offLeash: true,
      fenced: false,
      acres: 20.0,
      amenities: ["Creek access for swimming", "Paved multi-use path", "Shade trees", "Waste stations", "Benches"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Sections of Boulder's beloved creek path are designated voice-and-sight off-leash zones. Dogs love splashing in the creek on hot summer days while their owners enjoy the tree-lined path through the heart of town.",
    },
  ],
};
