export const bozemanData = {
  city: {
    name: "Bozeman",
    state: "Montana",
    region: "Mountain West",
    lat: 45.6770,
    lng: -111.0429,
    dogFriendlinessScore: 9,
    description:
      "Bozeman is one of the most dog-friendly mountain towns in America, where it often feels like dogs outnumber people. Nestled in the Gallatin Valley with four mountain ranges visible from town, dogs enjoy endless trail access, a vibrant downtown with dog-friendly breweries, and a community that genuinely celebrates canine companions.",
    heroImage: "https://images.unsplash.com/photo-1571417373053-4c96b0a00538?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 56908,
  },

  hotels: [
    {
      name: "The Lark",
      address: "122 W Main St, Bozeman, MT 59715",
      lat: 45.6797,
      lng: -111.0380,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a per-stay pet fee. Boutique hotel in the heart of downtown.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking map", "Near trails"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.larkbozeman.com",
      phone: "(406) 624-3070",
    },
    {
      name: "Element Bozeman",
      address: "25 E Mendenhall St, Bozeman, MT 59715",
      lat: 45.6790,
      lng: -111.0350,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with no weight limit and no pet fee. Eco-friendly extended stay hotel.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Near Peets Hill", "Pet waste stations", "Walking paths"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.marriott.com/element",
      phone: "(406) 582-4092",
    },
    {
      name: "Kimpton Armory Hotel",
      address: "24 W Mendenhall St, Bozeman, MT 59715",
      lat: 45.6792,
      lng: -111.0370,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs of all sizes welcome at no extra charge. Luxury boutique hotel in a restored armory building.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Plush dog bed", "Gourmet treats", "Water bowls", "Pet-sitting referrals", "Walking map"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.armoryhotelbozeman.com",
      phone: "(406) 551-7700",
    },
    {
      name: "Homewood Suites by Hilton Bozeman",
      address: "1023 Baxter Ln, Bozeman, MT 59715",
      lat: 45.6920,
      lng: -111.0580,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a non-refundable pet fee. Extended stay suites with full kitchens.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Grassy areas", "Pet waste stations", "Near trails", "Water bowls at front desk"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com/homewood-suites",
      phone: "(406) 587-7100",
    },
  ],

  nationalParks: [
    {
      name: "Yellowstone National Park (North Entrance)",
      state: "Montana",
      lat: 44.9775,
      lng: -110.6983,
      dogPolicy: "Dogs are NOT allowed on trails, boardwalks, or in the backcountry. They are permitted in parking areas, campgrounds, and within 100 feet of roads.",
      dogTrails: ["No dog-friendly trails available"],
      restrictions: [
        "No dogs on any trails or boardwalks",
        "Must be on leash (6 ft max) at all times",
        "Allowed only in parking areas, campgrounds, and within 100 feet of roads",
        "Not allowed in buildings or on thermal areas",
      ],
      description:
        "While Yellowstone is famously restrictive for dogs, the drive through the park from the north entrance at Gardiner offers incredible scenery. Plan for a human to stay with the dog or arrange a pet-sitting service in Bozeman.",
      imageUrl: "",
      website: "https://www.nps.gov/yell",
    },
    {
      name: "Gallatin National Forest / Custer Gallatin",
      state: "Montana",
      lat: 45.5000,
      lng: -111.0000,
      dogPolicy: "Dogs welcome on all trails. Leash required in developed areas; voice control in backcountry.",
      dogTrails: ["Hyalite Creek Trail", "Palisade Falls Trail", "Lava Lake Trail", "History Rock Trail"],
      restrictions: [
        "Leash required in campgrounds and trailheads",
        "Voice control on backcountry trails",
        "Not allowed in developed swim areas",
      ],
      description:
        "The national forest surrounding Bozeman offers some of the best dog-friendly hiking in Montana. Hyalite Canyon is the local favorite with waterfalls, alpine lakes, and creek access. The Bridger Mountains north of town also offer excellent trails.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/custergallatin",
    },
    {
      name: "Lee Metcalf Wilderness",
      state: "Montana",
      lat: 45.2500,
      lng: -111.3500,
      dogPolicy: "Dogs welcome off-leash under voice control in the wilderness. A pristine backcountry experience.",
      dogTrails: ["Spanish Creek Trail", "South Fork Trail", "Sentinel Creek Trail"],
      restrictions: [
        "Must be under voice control",
        "Pack out all waste",
        "Not allowed to chase wildlife",
      ],
      description:
        "This wilderness area in the Madison Range south of Bozeman offers remote alpine adventures. Dogs can roam off-leash on trails that climb through forests to high mountain meadows and peaks.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/custergallatin",
    },
  ],

  restaurants: [
    {
      name: "Bozeman Brewing Company",
      address: "504 N Broadway Ave, Bozeman, MT 59715",
      lat: 45.6830,
      lng: -111.0360,
      cuisine: "Brewery & Food Trucks",
      priceRange: "$" as const,
      dogPolicy: "One of the most dog-friendly spots in Bozeman with a huge outdoor area. Dogs everywhere, always.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bozemanbrewing.com",
    },
    {
      name: "Mountains Walking Brewery",
      address: "422 N Plum Ave, Bozeman, MT 59715",
      lat: 45.6820,
      lng: -111.0330,
      cuisine: "Brewery & Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly taproom and outdoor area. Award-winning craft beer with wood-fired pizza.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.mountainswalking.com",
    },
    {
      name: "Jam!",
      address: "25 W Main St, Bozeman, MT 59715",
      lat: 45.6795,
      lng: -111.0365,
      cuisine: "Breakfast & Brunch",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Beloved breakfast spot with creative dishes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.jamrestaurant.com",
    },
    {
      name: "Blackbird Kitchen",
      address: "140 E Main St, Bozeman, MT 59715",
      lat: 45.6795,
      lng: -111.0340,
      cuisine: "Italian & Wood-Fired",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Wood-fired Italian cuisine in a stylish downtown setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.blackbirdkitchen.com",
    },
    {
      name: "Feed Cafe",
      address: "1530 W Main St, Bozeman, MT 59715",
      lat: 45.6795,
      lng: -111.0530,
      cuisine: "Farm-to-Table Southern",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at patio seating. Southern-inspired farm-to-table cuisine in a casual atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.feedcafebozeman.com",
    },
  ],

  cafes: [
    {
      name: "Treeline Coffee Roasters",
      address: "110 N Tracy Ave, Bozeman, MT 59715",
      lat: 45.6800,
      lng: -111.0350,
      dogPolicy: "Dogs welcome on the outdoor patio. Premier specialty coffee roaster in Bozeman.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.treelinecoffee.com",
    },
    {
      name: "Cold Smoke Coffeehouse",
      address: "225 E Main St, Bozeman, MT 59715",
      lat: 45.6795,
      lng: -111.0330,
      dogPolicy: "Dog-friendly patio on Main Street. Community coffee shop popular with the outdoor crowd.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.coldsmokecoffeehouse.com",
    },
    {
      name: "Wild Joe*s Coffee Spot",
      address: "18 W Main St, Bozeman, MT 59715",
      lat: 45.6797,
      lng: -111.0370,
      dogPolicy: "Outdoor seating welcomes dogs. Live music venue and coffee shop with a local vibe.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.wildjoescoffee.com",
    },
    {
      name: "Rockford Coffee",
      address: "120 N Main St, Bozeman, MT 59715",
      lat: 45.6802,
      lng: -111.0360,
      dogPolicy: "Leashed dogs welcome at patio tables. Locally roasted coffee with housemade pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.rockfordcoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Snowfill Dog Park",
      address: "S Willson Ave, Bozeman, MT 59715",
      lat: 45.6700,
      lng: -111.0340,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: ["Separate small dog area", "Water stations", "Agility equipment", "Waste stations", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Bozeman's largest and most popular fenced off-leash dog park with separate areas, agility equipment, and great mountain views. A hub for the local dog community.",
    },
    {
      name: "Peets Hill / Burke Park",
      address: "S Church Ave, Bozeman, MT 59715",
      lat: 45.6750,
      lng: -111.0300,
      offLeash: true,
      fenced: false,
      acres: 40.0,
      amenities: ["Hilltop trails", "Mountain views", "Creek access", "Waste stations", "Multiple access points"],
      rating: 4.8,
      imageUrl: "",
      description:
        "An iconic Bozeman off-leash area with trails climbing a grassy hill above downtown. The views of the Bridger, Gallatin, and Spanish Peaks ranges are spectacular. Dogs love running the open hillsides and splashing in Sourdough Creek.",
    },
    {
      name: "Gallatin Regional Park",
      address: "4895 Gallatin Park Dr, Bozeman, MT 59718",
      lat: 45.6940,
      lng: -111.0800,
      offLeash: true,
      fenced: false,
      acres: 54.0,
      amenities: ["Trail system", "Pond access", "Open meadows", "Waste stations", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A large regional park on the west side of Bozeman with meadow trails, a pond, and mountain views. Dogs can run off-leash on the trails and swim in the pond during warmer months.",
    },
    {
      name: "East Gallatin Recreation Area",
      address: "Manley Rd, Bozeman, MT 59715",
      lat: 45.7050,
      lng: -111.0100,
      offLeash: true,
      fenced: false,
      acres: 30.0,
      amenities: ["Lake access", "Swimming", "Walking trails", "Picnic areas", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A recreation area north of town with a lake, swimming access, and walking trails. Dogs can be off-leash and enjoy swimming in the lake during summer months. A great spot for water-loving pups.",
    },
  ],
};
