export const bransonData = {
  city: {
    name: "Branson",
    state: "Missouri",
    region: "Midwest",
    lat: 36.6437,
    lng: -93.2185,
    dogFriendlinessScore: 6,
    description:
      "Branson sits in the heart of the Ozark Mountains with stunning Table Rock Lake and miles of forested trails. While best known for its entertainment shows, the surrounding natural beauty and growing number of pet-friendly attractions make it a fun destination for adventurous dogs.",
    heroImage: "https://images.unsplash.com/photo-1504567961542-e24d9439a724?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 12638,
  },

  hotels: [
    {
      name: "Big Cedar Lodge",
      address: "190 Top of the Rock Rd, Ridgedale, MO 65739",
      lat: 36.5650,
      lng: -93.2340,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in select cabins and lodges with a pet fee. Sprawling Ozark resort on Table Rock Lake.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Nature trails", "Lake access", "Spacious cabins"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.bigcedar.com",
      phone: "(417) 335-2777",
    },
    {
      name: "Best Western Music Capital Inn",
      address: "3257 Shepherd of the Hills Expy, Branson, MO 65616",
      lat: 36.6480,
      lng: -93.2620,
      priceRange: "$" as const,
      dogPolicy: "Pets welcome with a nightly fee. Convenient location near attractions.",
      maxDogWeight: 80,
      petFee: 20,
      amenities: ["Grassy area", "Near attractions", "Complimentary breakfast", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(417) 334-8378",
    },
    {
      name: "Hilton Branson Convention Center",
      address: "200 Sycamore St, Branson, MO 65616",
      lat: 36.6430,
      lng: -93.2180,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a non-refundable fee. Downtown Branson Landing location.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Branson Landing access", "Lake views", "Walking paths"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(417) 243-3433",
    },
    {
      name: "La Quinta Inn & Suites",
      address: "2700 Green Mountain Dr, Branson, MO 65616",
      lat: 36.6510,
      lng: -93.2400,
      priceRange: "$" as const,
      dogPolicy: "All dogs welcome at no extra charge. No size or breed restrictions.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Grassy area", "Near trails", "Complimentary breakfast"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(417) 332-0707",
    },
  ],

  nationalParks: [
    {
      name: "Table Rock Lake State Park",
      state: "Missouri",
      lat: 36.5850,
      lng: -93.3110,
      dogPolicy: "Leashed dogs welcome on trails and in campgrounds. Beautiful Ozark lake setting.",
      dogTrails: ["Lakeshore Trail", "White River Valley Trail", "Chinquapin Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on the swim beach",
        "Not permitted in cabins",
      ],
      description:
        "Table Rock Lake's crystal-clear waters and forested shoreline create a stunning backdrop for hiking with your dog. The Lakeshore Trail winds through Ozark forest with occasional lake views.",
      imageUrl: "",
      website: "https://www.mostateparks.com/tablerock",
    },
    {
      name: "Ruth and Paul Henning Conservation Area",
      state: "Missouri",
      lat: 36.6530,
      lng: -93.2800,
      dogPolicy: "Leashed dogs welcome on all trails. Scenic Ozark hiking right in Branson.",
      dogTrails: ["Homesteaders Trail", "Dewey Bald Trail", "Streamside Trail"],
      restrictions: [
        "Must be on leash",
        "Stay on marked trails",
        "No hunting with dogs except during season",
      ],
      description:
        "A 1,534-acre conservation area within Branson city limits offering Ozark forest trails with views of the surrounding hills. The Dewey Bald Trail climbs to a scenic glade with panoramic views.",
      imageUrl: "",
      website: "https://www.mdc.mo.gov",
    },
    {
      name: "Roaring River State Park",
      state: "Missouri",
      lat: 36.5850,
      lng: -93.8370,
      dogPolicy: "Leashed dogs welcome on hiking trails and in campgrounds. Famous for its spring-fed stream.",
      dogTrails: ["Deer Leap Trail", "Fire Tower Trail", "River Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed in the trout fishing area",
        "Not permitted in park pool",
      ],
      description:
        "About an hour west of Branson, this park features a massive spring, limestone bluffs, and forested trails. The Fire Tower Trail rewards hikers with sweeping Ozark views that dogs seem to appreciate too.",
      imageUrl: "",
      website: "https://www.mostateparks.com/roaringriver",
    },
  ],

  restaurants: [
    {
      name: "Branson Landing Boardwalk",
      address: "100 Branson Landing Blvd, Branson, MO 65616",
      lat: 36.6425,
      lng: -93.2170,
      cuisine: "Various",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome along the outdoor boardwalk and at many restaurant patios.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bransonlanding.com",
    },
    {
      name: "Level 2 Steakhouse",
      address: "200 Sycamore St, Branson, MO 65616",
      lat: 36.6432,
      lng: -93.2182,
      cuisine: "Steakhouse",
      priceRange: "$$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the outdoor terrace overlooking Lake Taneycomo.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.level2steakhouse.com",
    },
    {
      name: "Clockers Cafe",
      address: "103 S Commercial St, Branson, MO 65616",
      lat: 36.6440,
      lng: -93.2190,
      cuisine: "Breakfast & Lunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor sidewalk tables. Beloved local breakfast joint.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.clockerscafe.com",
    },
    {
      name: "Vintage Paris Coffee & Wine Cafe",
      address: "100 S Commercial St, Branson, MO 65616",
      lat: 36.6438,
      lng: -93.2188,
      cuisine: "French Cafe",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. French-inspired dishes in downtown Branson.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.vintagepariscafe.com",
    },
    {
      name: "Andy's Frozen Custard",
      address: "3415 W 76 Country Blvd, Branson, MO 65616",
      lat: 36.6460,
      lng: -93.2650,
      cuisine: "Frozen Custard",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly with a pup cup option. A Branson favorite for frozen treats.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.eatandys.com",
    },
  ],

  cafes: [
    {
      name: "Vintage Paris Coffee",
      address: "100 S Commercial St, Branson, MO 65616",
      lat: 46.6438,
      lng: -93.2188,
      dogPolicy: "Dogs welcome on the outdoor terrace. French press coffee and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.vintagepariscoffee.com",
    },
    {
      name: "Branson Bean Coffee Company",
      address: "205 S Commercial St, Branson, MO 65616",
      lat: 36.6435,
      lng: -93.2192,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Locally roasted coffee downtown.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bransonbean.com",
    },
    {
      name: "Sugar Leaf Bakery & Cafe",
      address: "112 W Main St, Branson, MO 65616",
      lat: 36.6442,
      lng: -93.2195,
      dogPolicy: "Dogs welcome at outdoor tables. Fresh baked goods and coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.sugarleafbakery.com",
    },
    {
      name: "Lakeside Coffee & Tea",
      address: "Branson Landing, Branson, MO 65616",
      lat: 36.6428,
      lng: -93.2175,
      dogPolicy: "Leashed dogs welcome on the boardwalk patio. Coffee with lake views.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.lakesidecoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Branson RecPlex Dog Park",
      address: "1501 Branson Hills Pkwy, Branson, MO 65616",
      lat: 36.6570,
      lng: -93.2530,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water fountains", "Shade structures", "Waste stations", "Benches"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Branson's main off-leash dog park features separate areas for large and small dogs. The well-maintained grounds and good shade make it a reliable spot for letting your dog run free.",
    },
    {
      name: "Branson Landing Boardwalk",
      address: "100 Branson Landing Blvd, Branson, MO 65616",
      lat: 36.6425,
      lng: -93.2170,
      offLeash: false,
      fenced: false,
      acres: 12.0,
      amenities: ["Lake Taneycomo waterfront", "Paved walkway", "Fountain show", "Shops", "Restaurants"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A mile-long boardwalk along Lake Taneycomo with shops, restaurants, and a spectacular fountain show. Dogs love the on-leash waterfront stroll and the attention from passersby.",
    },
    {
      name: "Lakeside Forest Wilderness Area",
      address: "Owen Ln, Branson, MO 65616",
      lat: 36.6390,
      lng: -93.2280,
      offLeash: false,
      fenced: false,
      acres: 130.0,
      amenities: ["Forest trails", "Lake views", "Wildlife viewing", "Quiet setting", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A 130-acre wilderness area within Branson city limits offering forested trails and lake views. The natural Ozark terrain provides an excellent on-leash hiking experience minutes from the strip.",
    },
    {
      name: "North Beach Park",
      address: "N Beach Park Rd, Branson, MO 65616",
      lat: 36.6460,
      lng: -93.2130,
      offLeash: false,
      fenced: false,
      acres: 6.0,
      amenities: ["Lake Taneycomo access", "Walking paths", "Picnic areas", "Shade trees", "Parking"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A quiet lakefront park on Lake Taneycomo offering scenic walks and water access. Dogs enjoy the cool lake breezes and the chance to dip their paws in the trout-filled waters.",
    },
  ],
};
