export const burlingtonData = {
  city: {
    name: "Burlington",
    state: "Vermont",
    region: "Northeast",
    lat: 44.4759,
    lng: -73.2121,
    dogFriendlinessScore: 8,
    description:
      "Perched on the shores of Lake Champlain with the Green Mountains as a backdrop, Burlington is a progressive college town that treats dogs as first-class citizens. From the Church Street Marketplace where pups window-shop between craft breweries to the stunning waterfront bike path and nearby mountain trails, Burlington offers a four-season paradise for adventurous dogs who love lake swims, forest hikes, and patio hangs.",
    heroImage: "https://images.unsplash.com/photo-1520962880247-cfaf541c8724?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 44743,
  },

  hotels: [
    {
      name: "Hotel Vermont",
      address: "41 Cherry St, Burlington, VT 05401",
      lat: 44.4770,
      lng: -73.2195,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with no pet fee. Boutique hotel with custom dog beds and a dedicated pet program.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Custom dog bed", "Treats", "Water bowls", "Dog walking map", "Waterfront access"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.hotelvt.com",
      phone: "(802) 651-0080",
    },
    {
      name: "Hilton Burlington Lake Champlain",
      address: "60 Battery St, Burlington, VT 05401",
      lat: 44.4782,
      lng: -73.2208,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a nightly pet fee. Lakefront property with stunning Adirondack views.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Lake views", "Dog bed", "Near bike path", "Waterfront park", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(802) 658-6500",
    },
    {
      name: "La Quinta Inn Burlington",
      address: "1068 Williston Rd, Burlington, VT 05403",
      lat: 44.4535,
      lng: -73.1785,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with no pet fee. Reliable budget option near the university.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pet relief area", "Waste bags", "Free breakfast", "Near UVM trails"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(802) 859-4747",
    },
    {
      name: "The Essex Resort & Spa",
      address: "70 Essex Way, Essex Junction, VT 05452",
      lat: 44.5025,
      lng: -73.1205,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome in select rooms with a pet fee. Resort set on 18 acres of Vermont countryside.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["18-acre grounds", "Dog walking paths", "Dog bed", "Treats", "Near hiking trails", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.essexresort.com",
      phone: "(802) 878-1100",
    },
    {
      name: "TownePlace Suites Burlington Williston",
      address: "66 Zephyr Rd, Williston, VT 05495",
      lat: 44.4425,
      lng: -73.1350,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a one-time fee. Extended-stay suites with full kitchens for road-tripping pups.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Full kitchen", "Pet relief area", "Grocery nearby", "Waste stations", "Spacious suites"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(802) 872-5900",
    },
  ],

  nationalParks: [
    {
      name: "Marsh-Billings-Rockefeller National Historical Park",
      state: "Vermont",
      lat: 43.6318,
      lng: -72.5305,
      dogPolicy: "Leashed dogs welcome on the carriage roads and forest trails. Not permitted inside the mansion or formal gardens.",
      dogTrails: ["Carriage Road loop", "Pogue Trail", "South Summit Trail", "Mountain Tom Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed inside Marsh-Billings mansion",
        "Not allowed in formal gardens",
        "Not allowed in visitor center",
      ],
      description:
        "About 90 minutes south of Burlington in Woodstock, this park celebrates conservation history across 550 acres of managed forest. Leashed dogs can hike the beautiful carriage roads and trails through some of the oldest professionally managed woodlands in America.",
      imageUrl: "",
      website: "https://www.nps.gov/mabi",
    },
    {
      name: "Green Mountain National Forest",
      state: "Vermont",
      lat: 43.8700,
      lng: -72.8900,
      dogPolicy: "Leashed dogs welcome on all trails and in campgrounds. Over 900 miles of trails through Vermont's iconic green mountains.",
      dogTrails: ["Long Trail sections", "Appalachian Trail sections", "Middlebury Gap trails", "Robert Frost Interpretive Trail"],
      restrictions: [
        "Must be on leash or under voice control depending on area",
        "Not allowed in swimming areas at some locations",
        "Must stay on designated trails",
      ],
      description:
        "Stretching through central and southern Vermont, this vast national forest offers hundreds of miles of dog-friendly trails through hardwood forests, alpine meadows, and along mountain streams. The Robert Frost Interpretive Trail is a particular delight for leashed pups and poetry lovers.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/greenmountain",
    },
    {
      name: "Missisquoi National Wildlife Refuge",
      state: "Vermont",
      lat: 44.9570,
      lng: -73.1340,
      dogPolicy: "Leashed dogs welcome on designated trails from October through March. Restricted during nesting season (April-September).",
      dogTrails: ["Black Creek and Maquam Creek trails (seasonal)", "Stephen Young Marsh Trail (seasonal)"],
      restrictions: [
        "Dogs restricted April through September",
        "Must be on leash when permitted",
        "Not allowed in wildlife viewing blinds",
        "Seasonal access only",
      ],
      description:
        "About 45 minutes north of Burlington on Lake Champlain's delta, this wetland refuge hosts migratory birds and diverse wildlife. During fall and winter, leashed dogs can explore the trails through marsh and bottomland forest when bird nesting season has ended.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/missisquoi",
    },
  ],

  restaurants: [
    {
      name: "Hen of the Wood",
      address: "55 Cherry St, Burlington, VT 05401",
      lat: 44.4772,
      lng: -73.2192,
      cuisine: "Farm-to-Table",
      priceRange: "$$$$" as const,
      dogPolicy: "Well-behaved dogs welcome at the outdoor terrace. Vermont's most celebrated farm-to-table restaurant.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.8,
      imageUrl: "",
      website: "https://www.henofthewood.com",
    },
    {
      name: "Foam Brewers",
      address: "112 Lake St, Burlington, VT 05401",
      lat: 44.4785,
      lng: -73.2215,
      cuisine: "Brewery & Small Plates",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly taproom and waterfront patio. Nationally acclaimed craft beer on the Lake Champlain shore.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.foambrewers.com",
    },
    {
      name: "Farmhouse Tap & Grill",
      address: "160 Bank St, Burlington, VT 05401",
      lat: 44.4768,
      lng: -73.2135,
      cuisine: "Farm-to-Table Burgers",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Local grass-fed burgers and Vermont craft beer downtown.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.farmhousetg.com",
    },
    {
      name: "El Cortijo Taqueria",
      address: "189 Bank St, Burlington, VT 05401",
      lat: 44.4770,
      lng: -73.2128,
      cuisine: "Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the sidewalk patio. Fresh Mexican fare from the Hen of the Wood team.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.cortijovt.com",
    },
    {
      name: "Pizzeria Verita",
      address: "156 St. Paul St, Burlington, VT 05401",
      lat: 44.4765,
      lng: -73.2148,
      cuisine: "Neapolitan Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Authentic Neapolitan pizza fired in a hand-built Italian oven.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.pizzeriaverita.com",
    },
    {
      name: "Switchback Brewing Co.",
      address: "160 Flynn Ave, Burlington, VT 05401",
      lat: 44.4620,
      lng: -73.2175,
      cuisine: "Brewery & Pub",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly taproom and outdoor area. Burlington's hometown brewery with a loyal following.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.switchbackvt.com",
    },
    {
      name: "Leunig's Bistro & Cafe",
      address: "115 Church St, Burlington, VT 05401",
      lat: 44.4770,
      lng: -73.2128,
      cuisine: "French Bistro",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome at the Church Street sidewalk tables. Classic French bistro dining in the heart of Burlington.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.leunigs.com",
    },
    {
      name: "American Flatbread Burlington Hearth",
      address: "115 St Paul St, Burlington, VT 05401",
      lat: 44.4762,
      lng: -73.2152,
      cuisine: "Wood-Fired Flatbread",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the outdoor seating area. Wood-fired organic flatbreads and local drafts.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.americanflatbread.com",
    },
  ],

  cafes: [
    {
      name: "Scout & Co.",
      address: "237 N Winooski Ave, Burlington, VT 05401",
      lat: 44.4800,
      lng: -73.2085,
      dogPolicy: "Dog-friendly patio seating. Specialty coffee, fresh-baked goods, and a dog named Scout who inspired it all.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.scoutandcocoffee.com",
    },
    {
      name: "Maglianero Cafe",
      address: "47 Maple St, Burlington, VT 05401",
      lat: 44.4755,
      lng: -73.2095,
      dogPolicy: "Leashed dogs welcome at the outdoor tables. Italian-inspired espresso bar with a focus on quality.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.maglianero.com",
    },
    {
      name: "Onyx Tonics Craft Cocktails & Coffee",
      address: "166 Church St, Burlington, VT 05401",
      lat: 44.4775,
      lng: -73.2128,
      dogPolicy: "Dogs welcome at the Church Street outdoor seating. Coffee by day, cocktails by night.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.onyxtonics.com",
    },
    {
      name: "Uncommon Grounds",
      address: "42 Church St, Burlington, VT 05401",
      lat: 44.4758,
      lng: -73.2128,
      dogPolicy: "Leashed dogs welcome at the sidewalk tables on Church Street. A Burlington institution for coffee lovers.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.uncommongroundscoffee.com",
    },
    {
      name: "Speeder & Earl's Coffee",
      address: "104 Church St, Burlington, VT 05401",
      lat: 44.4770,
      lng: -73.2128,
      dogPolicy: "Dogs welcome outside on the Church Street Marketplace. House-roasted coffee since 1993.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.speederandearls.com",
    },
  ],

  dogParks: [
    {
      name: "Starr Farm Dog Park",
      address: "20 Starr Farm Rd, Burlington, VT 05408",
      lat: 44.4960,
      lng: -73.2310,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small and large dog areas", "Lake Champlain beach access", "Water stations", "Benches", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Burlington's best dog park with a fenced off-leash area AND direct access to a Lake Champlain beach where dogs can swim. Separate areas for big and small pups, plus stunning sunset views over the Adirondacks. It does not get better than this.",
    },
    {
      name: "Oakledge Dog Park",
      address: "Flynn Ave, Burlington, VT 05401",
      lat: 44.4570,
      lng: -73.2270,
      offLeash: true,
      fenced: false,
      acres: 5.0,
      amenities: ["Lake access", "Forest trails", "Rocky beach", "Parking", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A wooded off-leash area within Oakledge Park with access to Lake Champlain's rocky shore. Dogs love swimming in the lake, exploring the forest trails, and discovering the famous 'Tree House of Oakledge.' An unforgettable adventure for water-loving pups.",
    },
    {
      name: "Burlington Waterfront Park",
      address: "1 College St, Burlington, VT 05401",
      lat: 44.4778,
      lng: -73.2228,
      offLeash: false,
      fenced: false,
      acres: 9.0,
      amenities: ["Lake Champlain waterfront", "Walking paths", "Benches", "Restrooms", "Waste stations", "Festival grounds"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Burlington's vibrant waterfront park stretching along Lake Champlain. Leashed dogs can enjoy the paved paths, grassy areas, and stunning views of the lake and Adirondack Mountains. Home to festivals and farmers markets throughout the warmer months.",
    },
    {
      name: "North Beach Park",
      address: "52 Institute Rd, Burlington, VT 05408",
      lat: 44.4935,
      lng: -73.2325,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Sandy beach", "Lake swimming", "Walking trails", "Picnic areas", "Restrooms", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A beautiful sandy beach on Lake Champlain where leashed dogs are welcome during off-peak hours. The adjacent trails through the woods make for wonderful walks, and the lake views with the Adirondacks across the water are unbeatable.",
    },
    {
      name: "Ethan Allen Park",
      address: "1840 North Ave, Burlington, VT 05408",
      lat: 44.5045,
      lng: -73.2340,
      offLeash: false,
      fenced: false,
      acres: 67.0,
      amenities: ["Forest trails", "Observation tower", "Lake Champlain views", "Historic sites", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A rugged, hilly park with forest trails leading to a stone observation tower with panoramic views of Lake Champlain, the Adirondacks, and the Green Mountains. Leashed dogs love the wooded trails and the sense of wilderness just minutes from downtown.",
    },
  ],
};
