export const cambriaData = {
  city: {
    name: "Cambria",
    state: "California",
    region: "West Coast",
    lat: 35.5644,
    lng: -121.0808,
    dogFriendlinessScore: 8,
    description:
      "Nestled between Hearst Castle and the rugged Big Sur coast, Cambria is a storybook village of pine forests, moonstone-strewn beaches, and art galleries that welcome your pup through the front door. The elephant seals at nearby Piedras Blancas provide unforgettable wildlife viewing (from a safe distance, of course), and the Fiscalini Ranch Preserve offers coastal bluff trails that will make your dog's nose work overtime with sea-salt air and wildflower scents.",
    heroImage: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 5678,
  },
  hotels: [
    {
      name: "Cambria Pines Lodge",
      address: "2905 Burton Dr, Cambria, CA 93428",
      lat: 35.5681,
      lng: -121.085,
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly rooms available with a $30 per night pet fee. 25-acre wooded property with walking paths.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["25-acre grounds", "Walking paths", "Indoor pool", "Garden setting", "Pet waste stations"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cambriapineslodge.com",
      phone: "(805) 927-4200",
    },
    {
      name: "Moonstone Landing",
      address: "6240 Moonstone Beach Dr, Cambria, CA 93428",
      lat: 35.5757,
      lng: -121.1012,
      priceRange: "$$$" as const,
      dogPolicy: "Select pet rooms available with ocean views. $25 per night fee. Direct access to the Moonstone Beach boardwalk.",
      maxDogWeight: 50,
      petFee: 25,
      amenities: ["Ocean views", "Boardwalk access", "Fireplaces", "In-room spa tubs", "Dog-friendly grounds"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.moonstonelanding.com",
      phone: "(805) 927-0012",
    },
    {
      name: "Fog Catcher Inn",
      address: "6400 Moonstone Beach Dr, Cambria, CA 93428",
      lat: 35.578,
      lng: -121.1041,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in garden-view rooms. $20 per night pet fee. English garden with paths for leashed walks.",
      maxDogWeight: 40,
      petFee: 20,
      amenities: ["English gardens", "Ocean proximity", "Heated pool", "Dog-friendly garden paths"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.fogcatcherinn.com",
      phone: "(805) 927-1400",
    },
    {
      name: "Blue Dolphin Inn",
      address: "6470 Moonstone Beach Dr, Cambria, CA 93428",
      lat: 35.5791,
      lng: -121.1053,
      priceRange: "$$$" as const,
      dogPolicy: "Pet-friendly rooms with a $35 per night fee. Steps from Moonstone Beach boardwalk for morning dog walks.",
      maxDogWeight: 30,
      petFee: 35,
      amenities: ["Ocean views", "Fireplace rooms", "Boardwalk access", "Afternoon cookies"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bluedolphininn.com",
      phone: "(805) 927-3300",
    },
    {
      name: "Her Castle Homestay Inn",
      address: "1978 Londonderry Ln, Cambria, CA 93428",
      lat: 35.5701,
      lng: -121.0923,
      priceRange: "$$" as const,
      dogPolicy: "Charming B&B welcoming dogs with treats, blankets, and a fenced garden for off-leash play.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Fenced garden", "Dog treats", "Blankets", "Homemade breakfast", "Quiet neighborhood"],
      rating: 4.4,
      imageUrl: "",
      website: "",
      phone: "(805) 927-2670",
    },
  ],
  nationalParks: [
    {
      name: "Fiscalini Ranch Preserve",
      state: "California",
      lat: 35.5576,
      lng: -121.0826,
      dogPolicy: "Dogs welcome on leash on all trails. One of the most scenic coastal walks on the Central Coast.",
      dogTrails: ["Bluff Trail", "Marine Terrace Trail", "Santa Rosa Creek Trail"],
      restrictions: ["Leash required at all times", "Stay on designated trails", "Clean up required", "No dogs in sensitive habitat areas"],
      description:
        "A 430-acre public open space with dramatic bluff-top trails overlooking the Pacific. Your leashed pup will trot along windswept coastal paths with whales spouting offshore, sea otters floating in the kelp, and wildflowers carpeting the meadows in spring. This is Central Coast dog-walking at its absolute finest.",
      imageUrl: "",
      website: "https://www.ffrpcambria.org",
    },
    {
      name: "San Simeon State Park",
      state: "California",
      lat: 35.6094,
      lng: -121.1253,
      dogPolicy: "Dogs allowed on leash in the campground and on San Simeon Creek Trail. Not allowed on the beach in the natural preserve.",
      dogTrails: ["San Simeon Creek Trail", "Washburn Campground loop"],
      restrictions: ["Leash required", "No dogs on natural preserve beach", "No dogs in Washburn Day Use beach area"],
      description:
        "Coastal bluffs, Monterey pine forests, and wetland habitats make up this diverse state park just north of Cambria. The San Simeon Creek Trail winds through a riparian corridor that is a birding hotspot. Your pup may not appreciate the birds, but they'll love the smells.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/?page_id=590",
    },
    {
      name: "Montana de Oro State Park",
      state: "California",
      lat: 35.2717,
      lng: -120.8818,
      dogPolicy: "Dogs allowed on leash on the Bluff Trail and in the campground. Not permitted on most other trails or beaches.",
      dogTrails: ["Bluff Trail (3.5 miles)"],
      restrictions: ["Leash required", "Dogs only on Bluff Trail", "No dogs on Spooner's Cove beach", "No dogs on Valencia Peak Trail"],
      description:
        "Meaning 'Mountain of Gold' for its golden wildflower displays, this stunning park offers dramatic bluffs, hidden coves, and crashing waves. The dog-friendly Bluff Trail hugs the coastline with jaw-dropping views and tidepools below. It's worth the 40-minute drive south from Cambria.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/?page_id=592",
    },
    {
      name: "Piedras Blancas Elephant Seal Rookery",
      state: "California",
      lat: 35.6652,
      lng: -121.2548,
      dogPolicy: "Dogs not allowed on the boardwalk viewing area. Can remain in vehicles or in the parking area on leash.",
      dogTrails: [],
      restrictions: ["No dogs on boardwalk", "No dogs near elephant seals", "Dogs must remain leashed in parking area"],
      description:
        "Thousands of elephant seals haul out on this beach just north of Cambria — one of nature's most jaw-dropping wildlife spectacles. While your dog must sit this one out from the parking lot (for good reason), it's still worth a quick stop for the humans. Take turns seal-watching!",
      imageUrl: "",
      website: "https://www.elephantseal.org",
    },
  ],
  restaurants: [
    {
      name: "Linn's Restaurant",
      address: "2277 Main St, Cambria, CA 93428",
      lat: 35.5635,
      lng: -121.0761,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the garden patio. Famous for olallieberry pie — your pup will smell it and demand a bite.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.linnsfruitbin.com",
    },
    {
      name: "Moonstone Beach Bar & Grill",
      address: "6550 Moonstone Beach Dr, Cambria, CA 93428",
      lat: 35.58,
      lng: -121.1065,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Large oceanview patio welcomes dogs. Watch for whales while dining on fresh seafood.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.moonstonebeach.com",
    },
    {
      name: "Robin's Restaurant",
      address: "4095 Burton Dr, Cambria, CA 93428",
      lat: 35.5651,
      lng: -121.0823,
      cuisine: "International",
      priceRange: "$$$" as const,
      dogPolicy: "Beautiful garden patio that warmly welcomes leashed dogs. Eclectic menu with global flavors.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.robinsrestaurant.com",
    },
    {
      name: "Madeline's Restaurant & Wine Cellar",
      address: "788 Main St, Cambria, CA 93428",
      lat: 35.5596,
      lng: -121.0689,
      cuisine: "French",
      priceRange: "$$$" as const,
      dogPolicy: "Courtyard patio allows well-behaved leashed dogs. French-inspired cuisine with California flair.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Sea Chest Oyster Bar",
      address: "6216 Moonstone Beach Dr, Cambria, CA 93428",
      lat: 35.5753,
      lng: -121.1007,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Outdoor bench seating available for those with dogs. Cash only. Legendary seafood worth the wait.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.8,
      imageUrl: "",
      website: "",
    },
    {
      name: "Main Street Grill",
      address: "603 Main St, Cambria, CA 93428",
      lat: 35.558,
      lng: -121.0668,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Covered patio welcomes dogs. Comfort food and craft beer in the heart of the East Village.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Centrally Grown",
      address: "3564 Main St, Cambria, CA 93428",
      lat: 35.5644,
      lng: -121.078,
      cuisine: "Farm-to-Table",
      priceRange: "$$" as const,
      dogPolicy: "Patio seating welcomes leashed dogs. Organic and locally sourced menu with excellent wine list.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Wild Ginger Cafe",
      address: "2380 Main St, Cambria, CA 93428",
      lat: 35.5638,
      lng: -121.0768,
      cuisine: "Asian Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Small patio allows leashed dogs. Pan-Asian flavors with fresh California ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
  ],
  cafes: [
    {
      name: "Cambria Coffee Roasting Company",
      address: "761 Main St, Cambria, CA 93428",
      lat: 35.5593,
      lng: -121.0685,
      dogPolicy: "Charming East Village cafe with a sunny patio. Dogs welcome and dog treats available at the counter.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "",
    },
    {
      name: "Lily's Coffee House",
      address: "2244 Main St, Cambria, CA 93428",
      lat: 35.5633,
      lng: -121.0756,
      dogPolicy: "Cozy West Village cafe with outdoor seating. Dogs are welcome and regulars are known by name (the dogs, that is).",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "Moonstone Beach Coffee",
      address: "6101 Moonstone Beach Dr, Cambria, CA 93428",
      lat: 35.5742,
      lng: -121.0989,
      dogPolicy: "Grab a latte before your boardwalk stroll. Outdoor benches welcome dogs. Ocean breeze included.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "The French Corner Bakery",
      address: "2214 Main St, Cambria, CA 93428",
      lat: 35.563,
      lng: -121.0752,
      dogPolicy: "French pastries and espresso with a small outdoor patio. Leashed dogs welcome. Croissants to swoon over.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.7,
      imageUrl: "",
      website: "",
    },
    {
      name: "Creekside Gardens Cafe",
      address: "2948 Main St, Cambria, CA 93428",
      lat: 35.564,
      lng: -121.0773,
      dogPolicy: "Garden patio beside Santa Rosa Creek. Dogs adore the shaded, creekside setting. Homemade soups and salads.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Moonstone Beach Boardwalk",
      address: "Moonstone Beach Dr, Cambria, CA 93428",
      lat: 35.5773,
      lng: -121.103,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Boardwalk trail", "Ocean views", "Beach access", "Benches", "Waste bags", "Parking"],
      rating: 4.8,
      imageUrl: "",
      description:
        "A scenic one-mile boardwalk perched on coastal bluffs above the Pacific. Your leashed pup will be mesmerized by the crashing waves, sea otters bobbing in the kelp, and the salty breeze. At low tide, descend to the beach to hunt for moonstones and let your dog splash in tidepools.",
    },
    {
      name: "Fiscalini Ranch Bluff Trail",
      address: "Windsor Blvd, Cambria, CA 93428",
      lat: 35.5576,
      lng: -121.0826,
      offLeash: false,
      fenced: false,
      acres: 430.0,
      amenities: ["Coastal bluff trail", "Whale watching", "Wildflower meadows", "Benches", "Trail markers"],
      rating: 4.9,
      imageUrl: "",
      description:
        "The Bluff Trail at Fiscalini Ranch is arguably the finest dog walk on the Central Coast. A 1.5-mile path along dramatic coastal cliffs with whales, otters, and dolphins offshore, and carpets of wildflowers in spring. Your leashed dog will strut like they own the Pacific.",
    },
    {
      name: "Shamel Park",
      address: "5455 Windsor Blvd, Cambria, CA 93428",
      lat: 35.556,
      lng: -121.077,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["Ocean views", "Playground", "Picnic tables", "Restrooms", "Open grass field"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A community park right on the coast with grassy fields for fetch and picnic areas with ocean views. Leashed dogs are welcome on the grass, and the adjacent beach access lets you wander down to the rocky shore. Bring a ball and enjoy the California sunshine.",
    },
    {
      name: "Santa Rosa Creek Trail",
      address: "Main St, Cambria, CA 93428",
      lat: 35.5633,
      lng: -121.075,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Riparian trail", "Creek access", "Bird watching", "Shade", "Village access"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A peaceful trail along Santa Rosa Creek running through the heart of Cambria. Willow trees arch over the path, dappling sunlight on the water. Leashed dogs love wading in the shallow creek, and the trail connects the East and West Villages for a nice through-walk.",
    },
    {
      name: "Leffingwell Landing State Beach",
      address: "6207 Moonstone Beach Dr, Cambria, CA 93428",
      lat: 35.575,
      lng: -121.1005,
      offLeash: false,
      fenced: false,
      acres: 4.0,
      amenities: ["Beach access", "Tide pools", "Picnic area", "Parking", "Coastal views"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A rocky cove with tide pools, kelp forests, and a grassy picnic area overlooking the ocean. Leashed dogs can explore the shoreline at low tide, and the grassy bluffs make a perfect spot for a scenic break. Sea otters are regular visitors just offshore.",
    },
  ],
};
