export const camdenMeData = {
  city: {
    name: "Camden",
    state: "Maine",
    region: "Northeast",
    lat: 44.2098,
    lng: -69.0648,
    dogFriendlinessScore: 8,
    description:
      "Where the mountains meet the sea, Camden offers a rare combination of summit hikes with ocean views and a charming harbor village. Dogs love the trails on Mount Battie, the waterfront parks, and the welcoming attitude of this classic Maine sailing town.",
    heroImage: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 5074,
  },
  hotels: [
    {
      name: "Camden Harbour Inn",
      address: "83 Bayview St, Camden, ME 04843",
      lat: 44.2118,
      lng: -69.0629,
      priceRange: "$$$$" as const,
      dogPolicy: "Luxury inn welcoming dogs with a $75 per stay fee. Harbor views and walking distance to Camden Hills trails.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Harbor views", "Luxury amenities", "Near hiking trails", "Downtown location", "Restaurant"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.camdenharbourinn.com",
      phone: "(207) 236-4200",
    },
    {
      name: "Lord Camden Inn",
      address: "24 Main St, Camden, ME 04843",
      lat: 44.2094,
      lng: -69.0649,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with a $40 per night fee. Balcony rooms overlooking Main Street and the harbor.",
      maxDogWeight: 40,
      petFee: 40,
      amenities: ["Main Street location", "Balconies", "Harbor views", "Rooftop deck", "Continental breakfast"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.lordcamdeninn.com",
      phone: "(207) 236-4325",
    },
    {
      name: "Cedar Crest Inn",
      address: "115 Elm St, Camden, ME 04843",
      lat: 44.2141,
      lng: -69.068,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms with a $30 per night fee. Quiet residential setting with garden grounds for dog walks.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Garden grounds", "Quiet setting", "Free parking", "Near downtown", "Pet exercise area"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.cedarcrestinn.com",
      phone: "(207) 236-4839",
    },
    {
      name: "High Tide Inn",
      address: "505 Belfast Rd, Camden, ME 04843",
      lat: 44.2308,
      lng: -69.0414,
      priceRange: "$$" as const,
      dogPolicy: "Oceanfront inn welcoming dogs with a $25 per night fee. Private beach and lawn with Penobscot Bay views.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Private beach", "Ocean views", "Lawn area", "Adirondack chairs", "Pet-friendly cottages"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hightideinn.com",
      phone: "(207) 236-3724",
    },
  ],
  nationalParks: [
    {
      name: "Camden Hills State Park",
      state: "Maine",
      lat: 44.2246,
      lng: -69.0594,
      dogPolicy: "Leashed dogs welcome on all trails including the iconic Mount Battie summit. One of Maine's most popular state parks.",
      dogTrails: ["Mount Battie Trail", "Megunticook Trail", "Maiden Cliff Trail", "Multi-Use Trail"],
      restrictions: ["Leash required", "No dogs in picnic shelters", "Clean up required"],
      description:
        "The jewel of midcoast Maine, this 5,700-acre park offers mountains rising directly from the sea. Mount Battie's summit provides one of the most famous views in Maine — Penobscot Bay dotted with islands stretching to the horizon. The trail network ranges from easy walks to challenging scrambles, all dog-friendly on leash.",
      imageUrl: "",
      website: "https://www.maine.gov/dacf/parks/park-activities/camden-hills.shtml",
    },
    {
      name: "Merryspring Nature Center",
      state: "Maine",
      lat: 44.1961,
      lng: -69.0742,
      dogPolicy: "Leashed dogs welcome on all trails through this 66-acre preserve of gardens, meadows, and forest.",
      dogTrails: ["Main Trail Loop", "Perimeter Trail", "Arboretum Walk", "Wildflower Meadow Path"],
      restrictions: ["Leash required at all times", "Stay on designated trails", "Clean up required"],
      description:
        "A peaceful 66-acre nature preserve with gentle trails through cultivated gardens, wildflower meadows, and forest. The varied habitats provide an ever-changing sensory experience for dogs, from fragrant herb gardens to quiet woodland. Educational programs and well-maintained trails make this a year-round favorite.",
      imageUrl: "",
      website: "https://www.merryspring.org",
    },
    {
      name: "Bald Rock Mountain Preserve",
      state: "Maine",
      lat: 44.2546,
      lng: -69.0347,
      dogPolicy: "Leashed dogs welcome on the trail to the summit. A quieter alternative to Mount Battie with equally stunning views.",
      dogTrails: ["Bald Rock Summit Trail", "Cameron Mountain Connector"],
      restrictions: ["Leash required", "Rocky terrain near summit", "Clean up required"],
      description:
        "A Coastal Mountains Land Trust preserve offering a moderate hike to a bald granite summit with panoramic views of Penobscot Bay, the Camden Hills, and distant mountains. Less crowded than Mount Battie, this is a perfect choice for dogs and owners seeking a quieter summit experience.",
      imageUrl: "",
      website: "https://www.coastalmountains.org",
    },
  ],
  restaurants: [
    {
      name: "Waterfront Restaurant",
      address: "48 Bayview St, Camden, ME 04843",
      lat: 44.2107,
      lng: -69.0625,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Harbor-front deck welcomes leashed dogs. Fresh lobster and seafood with working harbor views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.waterfrontcamden.com",
    },
    {
      name: "Long Grain",
      address: "20 Washington St, Camden, ME 04843",
      lat: 44.2089,
      lng: -69.0659,
      cuisine: "Thai",
      priceRange: "$$" as const,
      dogPolicy: "Acclaimed Thai restaurant with seasonal outdoor seating. Leashed dogs welcome at patio tables.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.longgraincamden.com",
    },
    {
      name: "Cuzzy's",
      address: "1 Main St, Camden, ME 04843",
      lat: 44.2088,
      lng: -69.0644,
      cuisine: "American",
      priceRange: "$" as const,
      dogPolicy: "Casual harbor-side pub with a dog-friendly outdoor deck. Classic pub food and cold beers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "",
    },
    {
      name: "Hartstone Inn",
      address: "41 Elm St, Camden, ME 04843",
      lat: 44.2103,
      lng: -69.0665,
      cuisine: "New American",
      priceRange: "$$$$" as const,
      dogPolicy: "Fine dining inn with a garden patio. Leashed dogs welcome outside during seasonal service.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.hartstoneinn.com",
    },
    {
      name: "Sea Dog Brewing Company",
      address: "1 Main St, Camden, ME 04843",
      lat: 44.2091,
      lng: -69.0641,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Aptly named brewery with a waterfront deck. Dogs welcome on the outdoor patio overlooking Camden Harbor.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.seadogbrewing.com",
    },
  ],
  cafes: [
    {
      name: "Zoot Coffee",
      address: "31 Elm St, Camden, ME 04843",
      lat: 44.2099,
      lng: -69.066,
      dogPolicy: "Camden's go-to specialty coffee with outdoor seating. Dogs welcome at sidewalk tables on Elm Street.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "Boynton-McKay Food Co.",
      address: "30 Main St, Camden, ME 04843",
      lat: 44.2094,
      lng: -69.0648,
      dogPolicy: "Converted pharmacy turned cafe with outdoor benches on Main Street. Dogs welcome outside this beloved local institution.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.boynton-mckay.com",
    },
    {
      name: "Camden Deli",
      address: "37 Main St, Camden, ME 04843",
      lat: 44.2096,
      lng: -69.0649,
      dogPolicy: "Harbor-view deli with a rooftop deck. Dogs welcome on the outdoor deck overlooking the waterfall and harbor.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.camdendeli.com",
    },
    {
      name: "The Drouthy Bear",
      address: "84 Main St, Camden, ME 04843",
      lat: 44.2079,
      lng: -69.0655,
      dogPolicy: "Scottish-themed pub and coffee house with a small patio. Dogs welcome outside for a cup of coffee or a pint.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Mount Battie Summit & Trails",
      address: "280 Belfast Rd, Camden, ME 04843",
      lat: 44.2246,
      lng: -69.0594,
      offLeash: false,
      fenced: false,
      acres: 25.0,
      amenities: ["Summit tower", "Ocean views", "Multiple trail options", "Parking", "Restrooms"],
      rating: 4.8,
      imageUrl: "",
      description:
        "The iconic Mount Battie trail climbs 800 feet to a stone tower with arguably the most beautiful view in Maine — Penobscot Bay stretching to infinity, dotted with islands and schooners. Your leashed dog gets a great workout on the moderate trail, and the summit wind in their fur is pure joy.",
    },
    {
      name: "Camden Harbor Park & Amphitheatre",
      address: "Atlantic Ave, Camden, ME 04843",
      lat: 44.21,
      lng: -69.0617,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["Harbor views", "Walking paths", "Amphitheatre", "Benches", "Public landing"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A beautiful waterfront park in the heart of Camden with walking paths along the harbor, views of schooners at anchor, and a grass amphitheatre. Your leashed dog can enjoy the sea breeze while you watch the boats come and go. Connects to the downtown shopping district.",
    },
    {
      name: "Shirttail Point Preserve",
      address: "Shirttail Point Rd, Camden, ME 04843",
      lat: 44.1975,
      lng: -69.0483,
      offLeash: false,
      fenced: false,
      acres: 12.0,
      amenities: ["Waterfront trails", "Penobscot Bay views", "Forest paths", "Quiet setting", "Bird watching"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A coastal preserve with trails winding through forest to rocky shoreline on Penobscot Bay. The peaceful setting and water views make this a lovely leashed dog walk away from the busier downtown trails. Seals are sometimes spotted from the shore.",
    },
    {
      name: "Ragged Mountain Preserve",
      address: "Barnestown Rd, Camden, ME 04843",
      lat: 44.2175,
      lng: -69.1048,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Mountain trails", "Lake views", "Varied terrain", "Parking", "Trail maps"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A Coastal Mountains Land Trust preserve with trails climbing to Ragged Mountain's summit and the shores of Mirror Lake. The terrain is more rugged than Mount Battie, offering a satisfying challenge for athletic dogs. Summit views span from the ocean to the western mountains.",
    },
  ],
};
