export const cannonBeachData = {
  city: {
    name: "Cannon Beach",
    state: "Oregon",
    region: "Pacific Northwest",
    lat: 45.8918,
    lng: -123.9615,
    dogFriendlinessScore: 9,
    description:
      "Where Haystack Rock meets happy paws! This iconic Oregon coast village is a dog lover's dream — miles of wide, sandy beaches where dogs run free, cozy galleries and shops that welcome four-legged browsers, and a laid-back vibe that says 'bring your whole pack.' Misty mornings, dramatic sea stacks, and the sound of your pup splashing through tide pools make this one of the Pacific Northwest's most magical pet-friendly escapes.",
    heroImage: "https://images.unsplash.com/photo-1541701494587-cb553e5e0b15?w=1200&fit=crop",
    climate: "Oceanic",
    population: 1489,
  },

  hotels: [
    {
      name: "Surfsand Resort",
      address: "148 W Gower Ave, Cannon Beach, OR 97110",
      lat: 45.8885,
      lng: -123.9621,
      priceRange: "$$$" as const,
      dogPolicy:
        "Dogs are VIPs at Surfsand! No weight limits, no breed restrictions. Dog amenities delivered to your room. Direct beach access for those sunset romps.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: [
        "Dog bed and bowls",
        "Dog treats at check-in",
        "Direct beach access",
        "Pet towels",
        "Waste bags",
      ],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.surfsand.com",
      phone: "(503) 436-2274",
    },
    {
      name: "The Ocean Lodge",
      address: "2864 S Pacific St, Cannon Beach, OR 97110",
      lat: 45.8815,
      lng: -123.9625,
      priceRange: "$$$" as const,
      dogPolicy:
        "Beachfront lodge that loves dogs as much as you do. Two dogs max per room, all sizes welcome.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: [
        "Beachfront location",
        "Dog-friendly rooms",
        "Fireplace suites",
        "Pet towels",
        "Grassy courtyard",
      ],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.theoceanlodge.com",
      phone: "(503) 436-2241",
    },
    {
      name: "Tolovana Inn",
      address: "3400 S Hemlock St, Cannon Beach, OR 97110",
      lat: 45.8792,
      lng: -123.9608,
      priceRange: "$$" as const,
      dogPolicy:
        "Pet-friendly suites with full kitchens. Dogs under 50 lbs welcome with a nightly pet fee.",
      maxDogWeight: 50,
      petFee: 20,
      amenities: [
        "Full kitchen",
        "Indoor pool",
        "Beach access",
        "Pet-friendly suites",
        "Waste stations",
      ],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.tolovanainn.com",
      phone: "(503) 436-2211",
    },
    {
      name: "Inn at Cannon Beach",
      address: "3215 S Hemlock St, Cannon Beach, OR 97110",
      lat: 45.88,
      lng: -123.961,
      priceRange: "$$$" as const,
      dogPolicy:
        "Cottage-style inn with pet-friendly rooms. Dogs up to 60 lbs welcomed with a complimentary treat and toy.",
      maxDogWeight: 60,
      petFee: 20,
      amenities: [
        "Cottage rooms",
        "Garden courtyard",
        "Dog treat and toy",
        "Close to beach",
        "Fireplace",
      ],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.atcannonbeach.com",
      phone: "(503) 436-9085",
    },
    {
      name: "Waves Motel",
      address: "188 W 2nd St, Cannon Beach, OR 97110",
      lat: 45.8895,
      lng: -123.9618,
      priceRange: "$$" as const,
      dogPolicy:
        "Budget-friendly oceanfront rooms where dogs stay free! No pet fee, no weight limit, just happy tails.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: [
        "Oceanfront rooms",
        "No pet fee",
        "Beach access",
        "Free parking",
        "Kitchenettes",
      ],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.thewavesmotel.com",
      phone: "(503) 436-2205",
    },
  ],

  nationalParks: [
    {
      name: "Ecola State Park",
      state: "Oregon",
      lat: 45.9196,
      lng: -123.9742,
      dogPolicy:
        "Leashed dogs allowed on Crescent Beach Trail and in picnic areas. Some trails restrict dogs due to wildlife habitat.",
      dogTrails: [
        "Crescent Beach Trail",
        "Ecola Point viewpoints",
        "Picnic area paths",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash",
        "Not permitted on Tillamook Head Trail",
        "Not allowed on Indian Beach during snowy plover nesting season",
        "Must clean up after pets",
      ],
      description:
        "Perched on dramatic cliffs above the Pacific, Ecola State Park offers jaw-dropping views of the coastline and Tillamook Rock Lighthouse. Leashed dogs can hike the Crescent Beach Trail down to a secluded cove where the only footprints are yours and your pup's paw prints.",
      imageUrl: "",
      website: "https://stateparks.oregon.gov/index.cfm?do=park.profile&parkId=136",
    },
    {
      name: "Oswald West State Park",
      state: "Oregon",
      lat: 45.7627,
      lng: -123.9631,
      dogPolicy:
        "Leashed dogs allowed on Short Sand Beach and the trail to the beach. A rainforest hike to a surfer's cove!",
      dogTrails: [
        "Short Sand Beach Trail",
        "Neahkahnie Mountain Trail (partial)",
        "Cape Falcon Trail (limited sections)",
      ],
      restrictions: [
        "Dogs must be on a leash at all times",
        "Some trails closed to dogs seasonally",
        "Must clean up after pets",
        "Dogs not allowed in campground area",
      ],
      description:
        "A half-mile trail through old-growth rainforest leads to the stunning Short Sand Beach cove, where leashed dogs can play in the surf surrounded by towering headlands. The lush canopy, fern-draped trees, and sound of crashing waves make this a truly magical Oregon coast experience.",
      imageUrl: "",
      website: "https://stateparks.oregon.gov/index.cfm?do=park.profile&parkId=139",
    },
    {
      name: "Lewis and Clark National Historical Park",
      state: "Oregon",
      lat: 46.134,
      lng: -123.8786,
      dogPolicy:
        "Leashed dogs welcome on most trails and grounds at Fort Clatsop. Explore where Lewis, Clark, and Seaman the dog spent the winter of 1805.",
      dogTrails: [
        "Fort to Sea Trail",
        "Netul River Trail",
        "Fort Clatsop grounds",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash",
        "Not allowed inside the fort replica",
        "Must clean up after pets",
      ],
      description:
        "Walk in the pawprints of Seaman, the Newfoundland who accompanied Lewis and Clark on their epic journey! Leashed dogs can explore the Fort to Sea Trail, a 6.5-mile path from the fort replica to the Pacific Ocean. History and tail wags collide beautifully here.",
      imageUrl: "",
      website: "https://www.nps.gov/lewi",
    },
    {
      name: "Hug Point State Recreation Site",
      state: "Oregon",
      lat: 45.8625,
      lng: -123.9615,
      dogPolicy:
        "Dogs welcome on the beach and trails. A hidden gem with sea caves, waterfalls, and tide pools to explore.",
      dogTrails: [
        "Beach walk to sea caves",
        "Waterfall trail",
        "Tide pool exploration area",
      ],
      restrictions: [
        "Dogs must be under voice control on the beach",
        "Watch tides — trail can be impassable at high tide",
        "Must clean up after pets",
      ],
      description:
        "Just south of Cannon Beach, this enchanting spot features a waterfall cascading onto the sand, sea caves carved by the Pacific, and tide pools teeming with marine life. Dogs can explore the beach freely and wade through the waterfall pool. Time your visit with low tide for maximum adventure.",
      imageUrl: "",
      website: "https://stateparks.oregon.gov/index.cfm?do=park.profile&parkId=135",
    },
  ],

  restaurants: [
    {
      name: "Pelican Brewing Company",
      address: "1371 S Hemlock St, Cannon Beach, OR 97110",
      lat: 45.8845,
      lng: -123.9605,
      cuisine: "Brewery / Seafood",
      priceRange: "$$" as const,
      dogPolicy:
        "Award-winning coastal brewery with a dog-friendly patio. Enjoy ocean views, craft beer, and the company of your salty pup.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.pelicanbrewing.com",
    },
    {
      name: "Mo's Restaurant",
      address: "195 Warren Way, Cannon Beach, OR 97110",
      lat: 45.8892,
      lng: -123.9605,
      cuisine: "Seafood / Chowder",
      priceRange: "$" as const,
      dogPolicy:
        "Oregon coast institution with dog-friendly outdoor picnic tables. Famous clam chowder pairs perfectly with sandy paws.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.moschowder.com",
    },
    {
      name: "The Wayfarer Restaurant & Lounge",
      address: "1190 Pacific Dr, Cannon Beach, OR 97110",
      lat: 45.8862,
      lng: -123.9622,
      cuisine: "Pacific Northwest / Seafood",
      priceRange: "$$$" as const,
      dogPolicy:
        "Upscale oceanfront dining with a dog-friendly patio overlooking Haystack Rock. Fine dining with your finest companion.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.wayfarer-restaurant.com",
    },
    {
      name: "Bill's Tavern & Brewhouse",
      address: "188 N Hemlock St, Cannon Beach, OR 97110",
      lat: 45.8908,
      lng: -123.9605,
      cuisine: "Pub / American",
      priceRange: "$$" as const,
      dogPolicy:
        "Local favorite with a covered patio where dogs are always welcome. Great burgers and house-brewed beer.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.billstavernandbrewhouse.com",
    },
    {
      name: "Insomnia Coffee Co.",
      address: "256 N Hemlock St, Cannon Beach, OR 97110",
      lat: 45.8915,
      lng: -123.9605,
      cuisine: "Café / Light Fare",
      priceRange: "$" as const,
      dogPolicy:
        "Cozy coffee spot with outdoor seating where sandy, salty dogs are welcomed with open arms and fresh water.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.insomniacoffeeco.com",
    },
    {
      name: "Pig 'n Pancake",
      address: "223 S Hemlock St, Cannon Beach, OR 97110",
      lat: 45.889,
      lng: -123.9605,
      cuisine: "Breakfast / American",
      priceRange: "$" as const,
      dogPolicy:
        "Oregon coast breakfast chain with covered patio seating. Dogs welcome outside while you fuel up on pancakes for a beach day.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.0,
      imageUrl: "",
      website: "https://www.pignpancake.com",
    },
    {
      name: "Sweet Basil's Café",
      address: "271 N Hemlock St, Cannon Beach, OR 97110",
      lat: 45.8918,
      lng: -123.9605,
      cuisine: "Thai / Asian Fusion",
      priceRange: "$$" as const,
      dogPolicy:
        "Thai-inspired dishes with a dog-friendly patio. A surprising culinary gem on the Oregon coast.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sweetbasilscafe.com",
    },
    {
      name: "Driftwood Restaurant & Lounge",
      address: "179 N Hemlock St, Cannon Beach, OR 97110",
      lat: 45.8905,
      lng: -123.9605,
      cuisine: "American / Seafood",
      priceRange: "$$" as const,
      dogPolicy:
        "Casual beachside dining with an outdoor patio that welcomes dogs. Classic fish and chips with a Pacific soundtrack.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.driftwoodcannonbeach.com",
    },
  ],

  cafes: [
    {
      name: "Sleepy Monk Coffee Roasters",
      address: "1235 S Hemlock St, Cannon Beach, OR 97110",
      lat: 45.885,
      lng: -123.9605,
      dogPolicy:
        "Organic, fair-trade coffee roasted on-site with a dog-friendly outdoor window. Your pup can sniff the ocean air while you sip the best coffee on the coast.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.sleepymonkcoffee.com",
    },
    {
      name: "Insomnia Coffee Co.",
      address: "256 N Hemlock St, Cannon Beach, OR 97110",
      lat: 45.8915,
      lng: -123.9605,
      dogPolicy:
        "Bright, welcoming café with benches outside where dogs can rest their sandy paws. Treats sometimes available!",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.insomniacoffeeco.com",
    },
    {
      name: "Sea Level Bakery + Coffee",
      address: "3116 S Hemlock St, Cannon Beach, OR 97110",
      lat: 45.8805,
      lng: -123.9605,
      dogPolicy:
        "Artisan bakery with a patio where dogs are welcome. Grab a pastry and a latte before hitting the beach.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sealevelbakery.com",
    },
    {
      name: "Cannon Beach Bakery",
      address: "240 N Hemlock St, Cannon Beach, OR 97110",
      lat: 45.8912,
      lng: -123.9605,
      dogPolicy:
        "Famous for their haystack bread! Dogs welcome at the outdoor seating area. Grab a loaf and share the vibes.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.cannonbeachbakery.com",
    },
    {
      name: "Waves of Grain Bakery",
      address: "3116 S Hemlock St, Cannon Beach, OR 97110",
      lat: 45.8808,
      lng: -123.9608,
      dogPolicy:
        "Wholesome baked goods and coffee with outdoor seating. Dogs welcome on the patio while you enjoy fresh-baked bread.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.wavesofgrainbakery.com",
    },
  ],

  dogParks: [
    {
      name: "Cannon Beach (Off-Leash Beach)",
      address: "Cannon Beach, OR 97110",
      lat: 45.8885,
      lng: -123.9635,
      offLeash: true,
      fenced: false,
      acres: 50,
      amenities: [
        "Miles of sandy beach",
        "Ocean swimming",
        "Tide pools",
        "Public restrooms nearby",
        "Waste stations at access points",
      ],
      rating: 4.9,
      imageUrl: "",
      description:
        "The main event! Oregon law allows dogs to run off-leash on most public beaches, and Cannon Beach is the crown jewel. Miles of wide, sandy shoreline with Haystack Rock as the backdrop, tide pools to explore, and waves to chase. This is the dog beach experience of a lifetime.",
    },
    {
      name: "Tolovana Beach Wayside",
      address: "S Hemlock St, Cannon Beach, OR 97110",
      lat: 45.878,
      lng: -123.963,
      offLeash: true,
      fenced: false,
      acres: 20,
      amenities: [
        "Free parking",
        "Beach access ramp",
        "Restrooms",
        "Waste stations",
        "Picnic area",
      ],
      rating: 4.7,
      imageUrl: "",
      description:
        "The southern stretch of Cannon Beach is typically less crowded and equally gorgeous. Easy parking and a gentle ramp to the sand make this the perfect access point for dogs who want to run free along the coastline with views of Haystack Rock in the distance.",
    },
    {
      name: "Ecola Creek Beach",
      address: "N Spruce St, Cannon Beach, OR 97110",
      lat: 45.897,
      lng: -123.963,
      offLeash: true,
      fenced: false,
      acres: 10,
      amenities: [
        "Creek for wading",
        "Sandy beach",
        "Driftwood play areas",
        "Quieter atmosphere",
      ],
      rating: 4.5,
      imageUrl: "",
      description:
        "Where Ecola Creek meets the Pacific, this quieter northern beach is perfect for dogs who prefer a calmer scene. Shallow creek water for wading, sandy stretches for zoomies, and plenty of driftwood for an epic game of fetch.",
    },
    {
      name: "Chapman Point Trail Area",
      address: "N Laurel St, Cannon Beach, OR 97110",
      lat: 45.9,
      lng: -123.965,
      offLeash: false,
      fenced: false,
      acres: 5,
      amenities: [
        "Forest trail",
        "Beach access at low tide",
        "Scenic viewpoints",
        "Wildlife watching",
      ],
      rating: 4.3,
      imageUrl: "",
      description:
        "A wooded trail leading to a rocky headland with tide pool access at low tide. Leashed dogs can explore the forested path and scramble over rocks at the point. Keep an eye on the tides — this area is best explored during low water.",
    },
    {
      name: "Les Shirley Park",
      address: "N Hemlock St, Cannon Beach, OR 97110",
      lat: 45.895,
      lng: -123.96,
      offLeash: false,
      fenced: false,
      acres: 3,
      amenities: [
        "Creek access",
        "Walking paths",
        "Benches",
        "Shade trees",
        "Waste stations",
      ],
      rating: 4.2,
      imageUrl: "",
      description:
        "A peaceful park along Ecola Creek in the heart of town. Leashed dogs can stroll the paths, wade in the creek, and relax under towering Sitka spruce. A perfect calm spot between beach adventures.",
    },
  ],
};
