export const capeMayData = {
  city: {
    name: "Cape May",
    state: "New Jersey",
    region: "Northeast",
    lat: 38.9351,
    lng: -74.906,
    dogFriendlinessScore: 8,
    description:
      "America's oldest seaside resort is also one of its most dog-friendly. Cape May's colorful Victorian gingerbread houses, pristine beaches, and charming pedestrian mall create a storybook setting where pups are celebrated guests. From seasonal dog beaches to pet-friendly B&Bs, this Jersey Shore gem proves that the good life is even better with four legs.",
    heroImage: "https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 3446,
  },

  hotels: [
    {
      name: "Congress Hall",
      address: "200 Congress Pl, Cape May, NJ 08204",
      lat: 38.9323,
      lng: -74.9067,
      priceRange: "$$$$" as const,
      dogPolicy:
        "Historic grand hotel welcoming dogs up to 50 lbs with a luxury pet package including a monogrammed bandana and treats.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: [
        "Dog bed",
        "Monogrammed bandana",
        "Gourmet dog treats",
        "Walking map",
        "Concierge pet services",
      ],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.congresshall.com",
      phone: "(609) 884-8421",
    },
    {
      name: "The Virginia Hotel",
      address: "25 Jackson St, Cape May, NJ 08204",
      lat: 38.9344,
      lng: -74.9065,
      priceRange: "$$$" as const,
      dogPolicy:
        "Boutique hotel in the heart of the historic district. Dogs up to 40 lbs welcome in select pet-friendly rooms.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: [
        "Dog bed",
        "Water bowls",
        "Waste bags",
        "Walking distance to beach",
      ],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.virginiahotel.com",
      phone: "(609) 884-5700",
    },
    {
      name: "The Montreal Beach Resort",
      address: "1025 Beach Ave, Cape May, NJ 08204",
      lat: 38.9308,
      lng: -74.9012,
      priceRange: "$$" as const,
      dogPolicy:
        "Oceanfront resort with pet-friendly rooms. Dogs of all sizes welcome with a nightly pet fee during shoulder season.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: [
        "Oceanfront location",
        "Pet-friendly ground floor rooms",
        "Beach towels",
        "Outdoor rinse station",
      ],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.montrealbeachresort.com",
      phone: "(609) 884-7011",
    },
    {
      name: "La Mer Beachfront Resort",
      address: "1317 Beach Ave, Cape May, NJ 08204",
      lat: 38.9302,
      lng: -74.8975,
      priceRange: "$$$" as const,
      dogPolicy:
        "Beachfront inn with pet-friendly suites. Dogs up to 60 lbs welcome. Steps from the promenade for morning walks.",
      maxDogWeight: 60,
      petFee: 50,
      amenities: [
        "Beach access",
        "Pet-friendly suites",
        "Outdoor shower",
        "Promenade access",
        "Dog bowls",
      ],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.lamerresort.com",
      phone: "(609) 884-9000",
    },
    {
      name: "The Carroll Villa Hotel",
      address: "19 Jackson St, Cape May, NJ 08204",
      lat: 38.9342,
      lng: -74.9063,
      priceRange: "$$" as const,
      dogPolicy:
        "Charming Victorian hotel welcoming small dogs. An affordable, historic option in the heart of Cape May.",
      maxDogWeight: 30,
      petFee: 25,
      amenities: [
        "Victorian charm",
        "Dog-friendly rooms",
        "Walking distance to everything",
        "Waste bags",
      ],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.carrollvilla.com",
      phone: "(609) 884-9619",
    },
  ],

  nationalParks: [
    {
      name: "Cape May Point State Park",
      state: "New Jersey",
      lat: 38.9282,
      lng: -74.9658,
      dogPolicy:
        "Leashed dogs welcome on all trails and grounds. A birder's and dog walker's paradise at the southern tip of New Jersey.",
      dogTrails: [
        "Red Trail (Lighthouse Loop)",
        "Blue Trail (Marsh Loop)",
        "Yellow Trail (Dune Overlook)",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash",
        "Not permitted on the beach during bird nesting season (April–August)",
        "Must clean up after pets",
      ],
      description:
        "Home to the iconic Cape May Lighthouse, this park offers diverse habitats from coastal dunes to freshwater wetlands. Leashed dogs can explore multiple trails, spot migrating birds, and enjoy views of the Delaware Bay. The lighthouse grounds are particularly scenic at sunset.",
      imageUrl: "",
      website: "https://www.state.nj.us/dep/parksandforests/parks/capemay.html",
    },
    {
      name: "Higbee Beach Wildlife Management Area",
      state: "New Jersey",
      lat: 38.9465,
      lng: -74.9725,
      dogPolicy:
        "Dogs welcome on-leash during most of the year. A peaceful, undeveloped beach and forest area teeming with wildlife.",
      dogTrails: [
        "Beach walk along Delaware Bay",
        "Forest trails through canopy",
        "Meadow paths",
      ],
      restrictions: [
        "Dogs must be on a leash",
        "Seasonal restrictions during bird migration",
        "Must clean up after pets",
        "No dogs during hunting season in designated areas",
      ],
      description:
        "A wild, undeveloped stretch of Delaware Bay beach backed by coastal forest. Leashed dogs can explore the sandy shoreline, walk through sun-dappled forest trails, and enjoy one of the least crowded natural areas on the Jersey Shore. A hidden gem for nature-loving pups.",
      imageUrl: "",
      website: "https://www.state.nj.us/dep/fgw/wmaland.htm",
    },
    {
      name: "Cape May National Wildlife Refuge",
      state: "New Jersey",
      lat: 39.0177,
      lng: -74.8944,
      dogPolicy:
        "Leashed dogs allowed on the Woodcock Trail and songbird trail. A wonderful nature walk for you and your birding pup.",
      dogTrails: [
        "Woodcock Trail",
        "Songbird Trail",
        "Refuge entrance road walk",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash at all times",
        "Must stay on designated trails",
        "Must clean up after pets",
        "Not allowed in closed habitat areas",
      ],
      description:
        "This 11,000-acre refuge protects critical habitat for migratory birds along the Atlantic Flyway. Leashed dogs can enjoy the easy Woodcock Trail through pine and oak forests and open meadows. Keep your eyes (and your dog's nose) open for wildlife!",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/cape-may",
    },
  ],

  restaurants: [
    {
      name: "The Lobster House",
      address: "906 Schellengers Landing Rd, Cape May, NJ 08204",
      lat: 38.9389,
      lng: -74.8917,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy:
        "Dogs welcome on the outdoor raw bar and dock area. Watch fishing boats unload while sharing the salt air with your pup.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thelobsterhouse.com",
    },
    {
      name: "The Rusty Nail",
      address: "205 Beach Ave, Cape May, NJ 08204",
      lat: 38.9322,
      lng: -74.907,
      cuisine: "American / Bar & Grill",
      priceRange: "$$" as const,
      dogPolicy:
        "Beachfront bar with a spacious dog-friendly outdoor deck. Live music, ocean views, and plenty of pup-friendly vibes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.therustynailcapemay.com",
    },
    {
      name: "Cape May Brewing Company",
      address: "1288 Hornet Rd, Cape May, NJ 08204",
      lat: 38.9485,
      lng: -74.9072,
      cuisine: "Brewery / Pub",
      priceRange: "$" as const,
      dogPolicy:
        "Dogs are welcome in the huge outdoor tasting room and beer garden. One of the most popular dog hangouts in Cape May.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.capemaybrewery.com",
    },
    {
      name: "Lucky Bones Backwater Grille",
      address: "1200 RT-109, Cape May, NJ 08204",
      lat: 38.9405,
      lng: -74.8935,
      cuisine: "American / Seafood",
      priceRange: "$$" as const,
      dogPolicy:
        "Dog-friendly outdoor patio with a fun, casual atmosphere. Water bowls always available for thirsty beach dogs.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.luckybones.com",
    },
    {
      name: "The Blue Pig Tavern",
      address: "200 Congress Pl, Cape May, NJ 08204",
      lat: 38.9323,
      lng: -74.9067,
      cuisine: "Farm-to-Table American",
      priceRange: "$$$" as const,
      dogPolicy:
        "Congress Hall's signature restaurant with a dog-friendly porch and lawn seating. Farm-fresh cuisine with sea breezes and tail wags.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.congresshall.com/dining",
    },
    {
      name: "C-View Inn",
      address: "1400 Broadway, Cape May, NJ 08204",
      lat: 38.942,
      lng: -74.907,
      cuisine: "American / Pizza",
      priceRange: "$" as const,
      dogPolicy:
        "Casual neighborhood spot with a pet-friendly patio. Dogs welcome at outdoor tables year-round.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.0,
      imageUrl: "",
      website: "https://www.cviewinn.com",
    },
    {
      name: "George's Place",
      address: "301 Beach Ave, Cape May, NJ 08204",
      lat: 38.932,
      lng: -74.906,
      cuisine: "Greek / Breakfast",
      priceRange: "$" as const,
      dogPolicy:
        "Beloved breakfast spot with outdoor seating where dogs are always welcome. Start your beach day with a Greek omelet and your best friend.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.georgesplacecapemay.com",
    },
    {
      name: "Key West Tacos",
      address: "600 Park Blvd, Cape May, NJ 08204",
      lat: 38.935,
      lng: -74.91,
      cuisine: "Mexican / Tacos",
      priceRange: "$" as const,
      dogPolicy:
        "Taco truck vibes with picnic table seating. Dogs welcome in the outdoor area while you devour fish tacos.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.keywesttacoscapemay.com",
    },
  ],

  cafes: [
    {
      name: "Cape May Peanut Butter Co.",
      address: "315 Ocean St, Cape May, NJ 08204",
      lat: 38.934,
      lng: -74.908,
      dogPolicy:
        "A peanut butter café that literally sells dog-friendly PB treats! Outdoor seating where your pup can enjoy their own PB cup.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.capemaypeanutbutter.com",
    },
    {
      name: "Seaside Cheese Company",
      address: "614 Park Blvd, Cape May, NJ 08204",
      lat: 38.935,
      lng: -74.91,
      dogPolicy:
        "Artisan cheese shop and café with sidewalk seating where well-behaved dogs are welcome. Grab a cheese board and soak up the Cape May sun.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.seasidecheese.com",
    },
    {
      name: "Tisha's Fine Dining Coffee Bar",
      address: "322 Washington St, Cape May, NJ 08204",
      lat: 38.935,
      lng: -74.905,
      dogPolicy:
        "Morning coffee on the Victorian porch with your pup. A charming Cape May tradition.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tishas.com",
    },
    {
      name: "Café Loren",
      address: "404 Washington St Mall, Cape May, NJ 08204",
      lat: 38.935,
      lng: -74.906,
      dogPolicy:
        "European-style café on the pedestrian mall. Dogs welcome at outdoor tables along the brick walkway.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.cafeloren.com",
    },
    {
      name: "The Shoppe at Congress Hall",
      address: "200 Congress Pl, Cape May, NJ 08204",
      lat: 38.9324,
      lng: -74.907,
      dogPolicy:
        "Grab coffee and pastries from the shop and enjoy them on the iconic Congress Hall lawn with your dog. Treats available for pups too!",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.congresshall.com",
    },
  ],

  dogParks: [
    {
      name: "Cape May Dog Beach",
      address: "Beach Ave at Broadway, Cape May, NJ 08204",
      lat: 38.932,
      lng: -74.911,
      offLeash: true,
      fenced: false,
      acres: 10,
      amenities: [
        "Ocean swimming",
        "Sandy beach",
        "Waste stations",
        "Seasonal access",
        "Public restrooms nearby",
      ],
      rating: 4.7,
      imageUrl: "",
      description:
        "Cape May's designated dog beach allows off-leash fun in the surf from October through April. Your pup can sprint along the shoreline, splash in the waves, and dig to their heart's content against a backdrop of Victorian houses and the Cape May Lighthouse.",
    },
    {
      name: "Cape May Point Beach (Off-Season)",
      address: "Cape May Point, NJ 08212",
      lat: 38.928,
      lng: -74.966,
      offLeash: true,
      fenced: false,
      acres: 15,
      amenities: [
        "Beach access",
        "Lighthouse views",
        "Sunset watching",
        "Waste stations",
      ],
      rating: 4.6,
      imageUrl: "",
      description:
        "During the off-season, Cape May Point's quiet beach becomes a dog paradise. Run off-leash along the Delaware Bay shore with views of the lighthouse and stunning sunsets. The WWII bunker ruins add a touch of adventure to every beach walk.",
    },
    {
      name: "Cape May City Dog Park",
      address: "Lafayette St Park, Cape May, NJ 08204",
      lat: 38.937,
      lng: -74.908,
      offLeash: true,
      fenced: true,
      acres: 1,
      amenities: [
        "Fenced area",
        "Separate small dog section",
        "Water fountain",
        "Benches",
        "Waste stations",
      ],
      rating: 4.2,
      imageUrl: "",
      description:
        "A convenient fenced dog park in the heart of Cape May. Perfect for a quick off-leash play session when the beach isn't accessible. Separate areas for large and small dogs ensure everyone plays safely.",
    },
    {
      name: "Higbee Beach Dog Walk",
      address: "New England Rd, Cape May, NJ 08204",
      lat: 38.946,
      lng: -74.972,
      offLeash: false,
      fenced: false,
      acres: 20,
      amenities: [
        "Wild beach",
        "Forest trails",
        "Bird watching",
        "Parking area",
        "Nature trails",
      ],
      rating: 4.5,
      imageUrl: "",
      description:
        "An undeveloped Delaware Bay beach backed by coastal forest. Leashed dogs can explore miles of wild shoreline and shaded forest trails. The sunrise views across the bay are spectacular, and the lack of crowds means your dog can enjoy nature in peace.",
    },
    {
      name: "The Meadows Dog Walk",
      address: "The Meadows, Cape May, NJ 08204",
      lat: 38.94,
      lng: -74.915,
      offLeash: false,
      fenced: false,
      acres: 5,
      amenities: [
        "Paved paths",
        "Wetland views",
        "Bird watching",
        "Waste stations",
        "Benches",
      ],
      rating: 4.1,
      imageUrl: "",
      description:
        "A scenic walking area through Cape May's wetlands and open meadows. Leashed dogs can enjoy the paved paths with views of herons, egrets, and other shorebirds. A peaceful respite from the bustle of beach season.",
    },
  ],
};
