export const carmelData = {
  city: {
    name: "Carmel-by-the-Sea",
    state: "California",
    region: "West Coast",
    lat: 36.5554,
    lng: -121.9233,
    dogFriendlinessScore: 10,
    description:
      "If dogs could plan a vacation, they'd choose Carmel-by-the-Sea every single time. This fairy-tale village on the Monterey Peninsula is quite possibly the most dog-friendly town in America — dogs outnumber children, they're welcome off-leash on the white-sand beach, and nearly every shop, gallery, and restaurant rolls out the red carpet (and the water bowl) for four-legged visitors. With a former dog-owner mayor (Clint Eastwood) and a culture that genuinely revolves around canine happiness, Carmel earns a perfect 10.",
    heroImage: "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 3897,
  },

  hotels: [
    {
      name: "Cypress Inn",
      address: "Lincoln St & 7th Ave, Carmel-by-the-Sea, CA 93921",
      lat: 36.5553,
      lng: -121.9229,
      priceRange: "$$$" as const,
      dogPolicy:
        "Co-owned by the late Doris Day, this is perhaps the most famous dog-friendly hotel in America. All dogs welcome with no size or breed restrictions. Dog heaven on Earth.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: [
        "Dog bed",
        "Water and food bowls",
        "Dog treats",
        "Welcome letter for your dog",
        "Dog-sitting referrals",
      ],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.cypressinn.com",
      phone: "(831) 624-3871",
    },
    {
      name: "Hofsas House Hotel",
      address: "San Carlos St, Carmel-by-the-Sea, CA 93921",
      lat: 36.5565,
      lng: -121.9215,
      priceRange: "$$" as const,
      dogPolicy:
        "Family-owned Bavarian-style hotel that has welcomed dogs for decades. No weight limits and a reasonable pet fee.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: [
        "Grassy courtyard",
        "Dog-friendly rooms",
        "Close to beach",
        "Free parking",
        "Pet towels",
      ],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hofsashouse.com",
      phone: "(831) 624-2745",
    },
    {
      name: "Pine Inn",
      address: "Ocean Ave & Monte Verde St, Carmel-by-the-Sea, CA 93921",
      lat: 36.555,
      lng: -121.923,
      priceRange: "$$$" as const,
      dogPolicy:
        "Historic hotel in the heart of Carmel welcoming dogs in pet-friendly rooms. Walking distance to the beach and all the shops.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: [
        "Central location",
        "Dog-friendly rooms",
        "Restaurant on-site",
        "Garden courtyard",
      ],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.pineinn.com",
      phone: "(831) 624-3851",
    },
    {
      name: "Tradewinds Carmel",
      address: "Mission St & 3rd Ave, Carmel-by-the-Sea, CA 93921",
      lat: 36.557,
      lng: -121.922,
      priceRange: "$$$$" as const,
      dogPolicy:
        "Zen-inspired luxury boutique hotel. Dogs up to 40 lbs receive a welcome amenity and premium pet bed.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: [
        "Premium dog bed",
        "Welcome treats",
        "Zen garden",
        "Walking distance to beach",
        "Concierge pet services",
      ],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.tradewindscarmel.com",
      phone: "(831) 624-2776",
    },
    {
      name: "Carmel Mission Inn",
      address: "3665 Rio Rd, Carmel, CA 93923",
      lat: 36.5402,
      lng: -121.9125,
      priceRange: "$$" as const,
      dogPolicy:
        "Spacious rooms with easy outdoor access for dogs. All sizes welcome with a pet fee. Great base for exploring the area.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: [
        "Large grassy area",
        "Ground floor pet rooms",
        "Waste stations",
        "Pool area",
        "Free parking",
      ],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.carmelmissioninn.com",
      phone: "(831) 624-1841",
    },
  ],

  nationalParks: [
    {
      name: "Point Lobos State Natural Reserve",
      state: "California",
      lat: 36.5156,
      lng: -121.9426,
      dogPolicy:
        "Dogs allowed ONLY in the Bird Island parking lot and on the paved Sea Lion Point Trail. Very limited but still worth visiting.",
      dogTrails: ["Sea Lion Point Trail (paved section only)"],
      restrictions: [
        "Dogs only allowed on Sea Lion Point Trail and Bird Island parking area",
        "Must be on a 6-foot leash at all times",
        "Not allowed on any other trails, beaches, or in the water",
        "Must clean up after pets",
      ],
      description:
        "Often called the 'Crown Jewel of the California State Park System,' Point Lobos is extraordinarily beautiful but quite restrictive for dogs. The one dog-friendly trail offers incredible views of sea lions, crashing waves, and cypress groves. Even limited access here is worth the visit.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/?page_id=571",
    },
    {
      name: "Garland Ranch Regional Park",
      state: "California",
      lat: 36.4285,
      lng: -121.7648,
      dogPolicy:
        "Off-leash dog paradise with miles of trails through river valleys, oak woodlands, and mountain meadows. One of the best dog hiking spots in California.",
      dogTrails: [
        "Lupine Loop",
        "Waterfall Trail",
        "Mesa Trail",
        "Buckeye Nature Trail",
        "Fern Trail",
      ],
      restrictions: [
        "Dogs must be under voice control when off-leash",
        "Leash required in visitor center area",
        "Must clean up after pets",
      ],
      description:
        "This 4,462-acre park is a dog's version of paradise. Off-leash exploration through sun-dappled oak forests, seasonal waterfalls, and wildflower meadows with views of the Carmel Valley. The Lupine Loop is perfect for an easy stroll, while the Mesa Trail offers a challenging climb with panoramic rewards.",
      imageUrl: "",
      website: "https://www.mprpd.org/garland-ranch-regional-park",
    },
    {
      name: "Carmel River State Beach",
      state: "California",
      lat: 36.537,
      lng: -121.9287,
      dogPolicy:
        "Dogs allowed on-leash on the south end of the beach. A beautiful spot where the Carmel River meets the Pacific.",
      dogTrails: [
        "South Beach walk",
        "Carmel River lagoon path",
        "Bluff trail",
      ],
      restrictions: [
        "Dogs must be on a leash",
        "Stay in designated dog-friendly area on south end",
        "Not allowed in bird sanctuary areas",
        "Must clean up after pets",
      ],
      description:
        "Where the Carmel River lagoon meets the Pacific Ocean, this beautiful state beach allows leashed dogs on its southern section. Watch for harbor seals, explore the lagoon shore, and enjoy the dramatic coastal scenery that has inspired artists and photographers for generations.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/?page_id=567",
    },
    {
      name: "Pinnacles National Park",
      state: "California",
      lat: 36.4906,
      lng: -121.1825,
      dogPolicy:
        "Dogs are NOT permitted on any trails in Pinnacles. They are allowed in the campground and on paved roads only.",
      dogTrails: [],
      restrictions: [
        "No dogs on any trails",
        "No dogs in the wilderness",
        "Allowed only in campground, paved roads, and parking areas",
        "Must be on leash in permitted areas",
      ],
      description:
        "While the dramatic volcanic rock formations and talus caves of Pinnacles are off-limits to dogs, it's worth noting for trip planning. If visiting, consider a dog-sitting service in Carmel while you explore the park's trails solo.",
      imageUrl: "",
      website: "https://www.nps.gov/pinn",
    },
  ],

  restaurants: [
    {
      name: "The Forge in the Forest",
      address: "5th Ave & Junipero, Carmel-by-the-Sea, CA 93921",
      lat: 36.554,
      lng: -121.922,
      cuisine: "American / Continental",
      priceRange: "$$" as const,
      dogPolicy:
        "Legendary dog-friendly restaurant with a massive patio featuring heat lamps, fire pits, and a dedicated dog menu. THE spot for dining with your pup in Carmel.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.forgeintheforest.com",
    },
    {
      name: "Barmel",
      address: "San Carlos St, Carmel-by-the-Sea, CA 93921",
      lat: 36.556,
      lng: -121.922,
      cuisine: "Spanish Tapas / Wine Bar",
      priceRange: "$$" as const,
      dogPolicy:
        "Covered courtyard patio where dogs lounge under string lights while you enjoy tapas and local wines.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.barmelcarmel.com",
    },
    {
      name: "Vesuvio",
      address: "6th Ave & Junipero, Carmel-by-the-Sea, CA 93921",
      lat: 36.5538,
      lng: -121.922,
      cuisine: "Italian / Pizza",
      priceRange: "$$" as const,
      dogPolicy:
        "Rooftop terrace with ocean views where dogs are welcome. Wood-fired pizza and wagging tails — what more could you want?",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.vesuviocarmel.com",
    },
    {
      name: "Terry's Lounge at Cypress Inn",
      address: "Lincoln St & 7th Ave, Carmel-by-the-Sea, CA 93921",
      lat: 36.5553,
      lng: -121.9229,
      cuisine: "American / Mediterranean",
      priceRange: "$$$" as const,
      dogPolicy:
        "Dogs are literally welcome INSIDE the restaurant — one of very few in California. The Doris Day legacy lives on with water bowls and treats at every table.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.cypressinn.com",
    },
    {
      name: "Stationaery",
      address: "San Carlos & 6th, Carmel-by-the-Sea, CA 93921",
      lat: 36.554,
      lng: -121.923,
      cuisine: "Modern American / Brunch",
      priceRange: "$$$" as const,
      dogPolicy:
        "Beautiful courtyard patio where dogs are welcome during brunch and dinner. Locally sourced cuisine in a stunning setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.thestationaery.com",
    },
    {
      name: "Brophy's Tavern",
      address: "San Carlos St, Carmel-by-the-Sea, CA 93921",
      lat: 36.555,
      lng: -121.922,
      cuisine: "Pub / American",
      priceRange: "$" as const,
      dogPolicy:
        "Casual neighborhood pub with a dog-friendly patio. Great place to watch the game while your pup people-watches.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.brophystavern.com",
    },
    {
      name: "Yafa Restaurant",
      address: "6th Ave, Carmel-by-the-Sea, CA 93921",
      lat: 36.554,
      lng: -121.921,
      cuisine: "Mediterranean / Middle Eastern",
      priceRange: "$$" as const,
      dogPolicy:
        "Garden courtyard dining with a welcoming dog policy. Mediterranean flavors under Carmel's gorgeous weather.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.yafarestaurant.com",
    },
    {
      name: "Cultura Comida y Bebida",
      address: "Dolores St, Carmel-by-the-Sea, CA 93921",
      lat: 36.556,
      lng: -121.924,
      cuisine: "Oaxacan Mexican",
      priceRange: "$$" as const,
      dogPolicy:
        "Vibrant Oaxacan cuisine with a sunny patio where dogs are welcome. Handcrafted mezcal cocktails and homemade mole.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.culturacarmel.com",
    },
  ],

  cafes: [
    {
      name: "Carmel Coffee House",
      address: "Ocean Ave, Carmel-by-the-Sea, CA 93921",
      lat: 36.555,
      lng: -121.923,
      dogPolicy:
        "The quintessential Carmel coffee stop. Dogs are welcomed with treats and the patio is always buzzing with pups and their people.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.carmelcoffee.com",
    },
    {
      name: "Café Carmel",
      address: "Ocean Ave & Mission St, Carmel-by-the-Sea, CA 93921",
      lat: 36.5548,
      lng: -121.9235,
      dogPolicy:
        "Sidewalk seating on Ocean Avenue where dogs are welcomed with biscuits. Watch the parade of Carmel's most stylish dogs walk by.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cafecarmel.com",
    },
    {
      name: "Carmel Valley Coffee Roasting Co.",
      address: "Ocean Ave, Carmel-by-the-Sea, CA 93921",
      lat: 36.555,
      lng: -121.924,
      dogPolicy:
        "Locally roasted coffee with a sunny courtyard patio. Dogs are so common here it would be weird NOT to bring one.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.carmelcoffeeroasters.com",
    },
    {
      name: "Acme Coffee",
      address: "6th Ave, Carmel-by-the-Sea, CA 93921",
      lat: 36.554,
      lng: -121.922,
      dogPolicy:
        "Trendy coffee shop with outdoor seating right in the village. Dogs welcome and dog treats usually available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.acmecoffeecarmel.com",
    },
    {
      name: "Patisserie Boissiere",
      address: "Mission St, Carmel-by-the-Sea, CA 93921",
      lat: 36.556,
      lng: -121.923,
      dogPolicy:
        "French bakery and café with a charming patio. Your dog can sit at your feet while you enjoy a croissant and café au lait in this little slice of Paris on the Pacific.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.patisserieboissiere.com",
    },
  ],

  dogParks: [
    {
      name: "Carmel Beach (Off-Leash)",
      address: "Ocean Ave at Scenic Rd, Carmel-by-the-Sea, CA 93921",
      lat: 36.553,
      lng: -121.9275,
      offLeash: true,
      fenced: false,
      acres: 30,
      amenities: [
        "White sand beach",
        "Ocean swimming",
        "Sunset views",
        "Waste stations",
        "Rinse stations at beach access",
      ],
      rating: 4.9,
      imageUrl: "",
      description:
        "The holy grail of dog beaches. This stunning white-sand crescent allows off-leash dogs all day, every day. Watch dozens of happy dogs sprinting through the surf, digging in the sand, and playing together against a backdrop of Monterey cypress and dramatic Point Lobos headlands. Sunsets here with your pup are pure magic.",
    },
    {
      name: "Carmel River Beach (Dog-Friendly Section)",
      address: "Carmelo St at 15th Ave, Carmel-by-the-Sea, CA 93921",
      lat: 36.538,
      lng: -121.928,
      offLeash: true,
      fenced: false,
      acres: 8,
      amenities: [
        "River lagoon",
        "Sandy beach",
        "Bird watching",
        "Waste stations",
        "Parking lot",
      ],
      rating: 4.6,
      imageUrl: "",
      description:
        "Where the Carmel River meets the ocean, this beach offers a different vibe than the main Carmel Beach. Dogs can splash in the calm lagoon, run on the sand, and explore the dunes. Often less crowded and great for dogs who prefer calmer water.",
    },
    {
      name: "Mission Trail Nature Preserve",
      address: "Rio Rd at Lasuen Dr, Carmel-by-the-Sea, CA 93923",
      lat: 36.547,
      lng: -121.92,
      offLeash: false,
      fenced: false,
      acres: 35,
      amenities: [
        "Nature trails",
        "Meadows",
        "Creek crossings",
        "Benches",
        "Waste stations",
      ],
      rating: 4.5,
      imageUrl: "",
      description:
        "A 35-acre nature preserve with five miles of trails winding through native gardens, oak woodlands, and open meadows right in town. Leashed dogs can explore the peaceful trails, cross wooden bridges over seasonal creeks, and enjoy the lush landscape that makes Carmel so special.",
    },
    {
      name: "Scenic Road Bluff Path",
      address: "Scenic Rd, Carmel-by-the-Sea, CA 93921",
      lat: 36.552,
      lng: -121.927,
      offLeash: false,
      fenced: false,
      acres: 3,
      amenities: [
        "Ocean views",
        "Paved pathway",
        "Benches",
        "Beach access points",
        "Waste stations",
      ],
      rating: 4.7,
      imageUrl: "",
      description:
        "A stunning paved bluff path above Carmel Beach with panoramic ocean views. Walk your leashed dog along the cliff edge, then descend any of several stairways to the off-leash beach below. The best of both worlds — coastal views and beach romps in one walk.",
    },
    {
      name: "Quail Lodge Dog Walking Area",
      address: "8000 Valley Greens Dr, Carmel, CA 93923",
      lat: 36.535,
      lng: -121.889,
      offLeash: false,
      fenced: false,
      acres: 10,
      amenities: [
        "Manicured grounds",
        "Lake views",
        "Walking paths",
        "Wildlife watching",
        "Waste stations",
      ],
      rating: 4.3,
      imageUrl: "",
      description:
        "The grounds around Quail Lodge in Carmel Valley offer beautiful walking paths alongside lakes, golf greens, and oak-studded hills. Leashed dogs can enjoy a leisurely stroll through some of the most manicured scenery in the valley.",
    },
  ],
};
