export const charlotteData = {
  city: {
    name: "Charlotte",
    state: "North Carolina",
    region: "Southeast",
    lat: 35.2271,
    lng: -80.8431,
    dogFriendlinessScore: 7,
    description:
      "Charlotte's brewery scene, greenway trail system, and welcoming Southern culture create a great environment for dogs. The city's extensive network of greenway trails connects neighborhoods, and the NoDa and Plaza Midwood districts are packed with dog-friendly patios and taprooms.",
    heroImage: "https://images.unsplash.com/photo-1605429523419-d828acb941d9?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 874579,
  },
  hotels: [
    {
      name: "Kimpton Tryon Park Hotel",
      address: "303 S Church St, Charlotte, NC 28202",
      lat: 35.2236,
      lng: -80.8451,
      priceRange: "$$$" as const,
      dogPolicy: "All pets welcome at no extra charge. Complimentary pet beds, bowls, and treats. Evening wine hour welcomes dogs.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pet bed", "Wine hour", "Uptown location", "Rooftop bar"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.tryonparkhotel.com",
      phone: "(704) 445-2626",
    },
    {
      name: "The Ivey's Hotel",
      address: "127 N Tryon St, Charlotte, NC 28202",
      lat: 35.228,
      lng: -80.8429,
      priceRange: "$$$$" as const,
      dogPolicy: "Luxury boutique hotel welcoming dogs under 35 lbs with a $100 per stay fee. Uptown location.",
      maxDogWeight: 35,
      petFee: 100,
      amenities: ["Luxury boutique", "Uptown location", "Spa", "Restaurant", "Historic building"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.iveyshotel.com",
      phone: "(704) 375-2600",
    },
    {
      name: "Aloft Charlotte Uptown",
      address: "210 E Trade St, Charlotte, NC 28202",
      lat: 35.2277,
      lng: -80.8396,
      priceRange: "$$" as const,
      dogPolicy: "Arf program welcomes dogs of any size at no extra charge. Walking distance to Romare Bearden Park.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Uptown location", "Near Romare Bearden Park", "Pool", "W XYZ Bar"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(704) 333-1999",
    },
    {
      name: "Home2 Suites Charlotte NoDa",
      address: "2301 N Tryon St, Charlotte, NC 28206",
      lat: 35.2433,
      lng: -80.828,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly suites in the NoDa arts district with a $75 non-refundable fee. Kitchen in every room.",
      maxDogWeight: 75,
      petFee: 75,
      amenities: ["Kitchen", "NoDa location", "Pet relief area", "Laundry", "Near breweries"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(704) 817-3300",
    },
  ],
  nationalParks: [
    {
      name: "U.S. National Whitewater Center",
      state: "North Carolina",
      lat: 35.2629,
      lng: -81.0073,
      dogPolicy: "Leashed dogs welcome on over 50 miles of trails. Craft beer, outdoor activities, and endless trails.",
      dogTrails: ["Lake Loop Trail", "Long Lake Trail", "South Main Trail", "North Main Trail"],
      restrictions: ["Leash required", "No dogs on whitewater course", "Clean up required"],
      description:
        "A 1,300-acre outdoor recreation center with over 50 miles of singletrack and multiuse trails through forests along the Catawba River. While dogs can't join the whitewater rafting, the trail system is one of the best urban hiking networks in the Southeast. The on-site brewpub is dog-friendly too.",
      imageUrl: "",
      website: "https://whitewater.org",
    },
    {
      name: "Crowders Mountain State Park",
      state: "North Carolina",
      lat: 35.2132,
      lng: -81.2949,
      dogPolicy: "Leashed dogs welcome on all trails. A monadnock mountain with dramatic cliff faces and panoramic views.",
      dogTrails: ["Crowders Trail", "Pinnacle Trail", "Backside Trail", "Lake Trail"],
      restrictions: ["Leash required", "Rocky terrain near summit", "Clean up required"],
      description:
        "Twin peaks rising dramatically above the Piedmont offer challenging hikes with rewarding cliff-top views stretching to Charlotte and beyond. The Crowders Trail to the summit is the most popular, with exposed rock faces and panoramic overlooks. About 30 minutes from Charlotte, it's the go-to day hike for locals with dogs.",
      imageUrl: "",
      website: "https://www.ncparks.gov/crowders-mountain-state-park",
    },
    {
      name: "Little Sugar Creek Greenway",
      state: "North Carolina",
      lat: 35.1972,
      lng: -80.8467,
      dogPolicy: "Leashed dogs welcome on the entire paved greenway. Charlotte's signature urban trail.",
      dogTrails: ["Little Sugar Creek Greenway (19 miles)", "Freedom Park Section", "Midtown Section"],
      restrictions: ["Leash required", "Yield to cyclists", "Clean up required"],
      description:
        "A 19-mile paved greenway following Little Sugar Creek through the heart of Charlotte, connecting Uptown to SouthPark through diverse neighborhoods. The trail passes Freedom Park, midtown restaurants, and shaded creek corridors. It's Charlotte's most popular leashed dog walk and an essential city experience.",
      imageUrl: "",
      website: "https://www.mecknc.gov",
    },
  ],
  restaurants: [
    {
      name: "NoDa Brewing Company",
      address: "2921 N Tryon St, Charlotte, NC 28206",
      lat: 35.2472,
      lng: -80.8244,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Charlotte's favorite craft brewery with a huge dog-friendly taproom and outdoor area. Dogs are locals here.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.nodabrewing.com",
    },
    {
      name: "Growlers Pourhouse",
      address: "3121 N Davidson St, Charlotte, NC 28205",
      lat: 35.2477,
      lng: -80.8185,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "NoDa gastropub with a massive dog-friendly patio. Craft beer selection and elevated bar food.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.growlerspourhouse.com",
    },
    {
      name: "The Dumpling Lady",
      address: "1600 E Woodlawn Rd, Charlotte, NC 28209",
      lat: 35.1892,
      lng: -80.8317,
      cuisine: "Asian",
      priceRange: "$" as const,
      dogPolicy: "Popular dumpling spot with a dog-friendly outdoor patio. Hand-made dumplings and Asian-inspired dishes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thedumplinglady.com",
    },
    {
      name: "Optimist Hall",
      address: "1115 N Brevard St, Charlotte, NC 28206",
      lat: 35.2347,
      lng: -80.8348,
      cuisine: "Food Hall",
      priceRange: "$$" as const,
      dogPolicy: "Massive food hall in a converted textile mill with dog-friendly outdoor areas. Dozens of local food vendors.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.optimisthall.com",
    },
    {
      name: "Haberdish",
      address: "3106 N Davidson St, Charlotte, NC 28205",
      lat: 35.2475,
      lng: -80.8189,
      cuisine: "Southern",
      priceRange: "$$" as const,
      dogPolicy: "NoDa Southern restaurant with a porch and patio. Leashed dogs welcome outside. Family-style Southern fare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.haberdishclt.com",
    },
  ],
  cafes: [
    {
      name: "Not Just Coffee",
      address: "224 E 7th St, Charlotte, NC 28202",
      lat: 35.2292,
      lng: -80.8377,
      dogPolicy: "Charlotte's craft coffee pioneer with an outdoor patio. Dogs welcome at patio tables in the heart of Uptown.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.notjustcoffee.com",
    },
    {
      name: "Undercurrent Coffee",
      address: "2825 N Davidson St, Charlotte, NC 28205",
      lat: 35.2465,
      lng: -80.8196,
      dogPolicy: "NoDa specialty coffee with outdoor seating. Dogs welcome. Thoughtfully sourced and prepared coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.undercurrentcoffee.com",
    },
    {
      name: "Magnolia Coffee",
      address: "2028 Scott Ave, Charlotte, NC 28203",
      lat: 35.2165,
      lng: -80.8507,
      dogPolicy: "South End coffee shop near the Light Rail with a dog-friendly patio. Perfect stop along the Rail Trail.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Brakeman's Coffee",
      address: "1320 S Church St, Charlotte, NC 28203",
      lat: 35.2146,
      lng: -80.8481,
      dogPolicy: "South End coffee shop next to the Rail Trail. Dogs welcome on the outdoor patio. Great pre-walk fuel.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Frazier Dog Park",
      address: "1201 W 4th St, Charlotte, NC 28202",
      lat: 35.2259,
      lng: -80.8583,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water fountains", "Shade trees", "Uptown skyline views", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Charlotte's most popular dog park sits near Uptown with skyline views. The large fenced area has separate sections for big and small dogs, water fountains, and plenty of shade. The community is friendly and the park is well-maintained by active volunteers.",
    },
    {
      name: "Charlotte Rail Trail",
      address: "S Tryon St, Charlotte, NC 28203",
      lat: 35.2142,
      lng: -80.8517,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Paved trail", "Public art", "Breweries along route", "Restaurants", "Light Rail access"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A 3.5-mile urban trail through South End connecting Uptown to the South Boulevard corridor, passing dozens of breweries, restaurants, and shops with dog-friendly patios. The paved path follows the Light Rail line and is Charlotte's premier see-and-be-seen dog walking route.",
    },
    {
      name: "Reedy Creek Nature Center & Park",
      address: "2900 Rocky River Rd, Charlotte, NC 28215",
      lat: 35.2797,
      lng: -80.7399,
      offLeash: false,
      fenced: false,
      acres: 100.0,
      amenities: ["Nature trails", "Creek access", "Nature center", "Wooded paths", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A 737-acre nature preserve with 10 miles of trails through Piedmont forest along Reedy Creek. The terrain varies from flat creek-side paths to rolling wooded hills. Your leashed dog will love the creek crossings and diverse forest habitats. It feels remarkably wild for a city park.",
    },
    {
      name: "Romare Bearden Park",
      address: "300 S Church St, Charlotte, NC 28202",
      lat: 35.2239,
      lng: -80.847,
      offLeash: false,
      fenced: false,
      acres: 5.4,
      amenities: ["Uptown location", "Water features", "Open lawns", "Skyline views", "Events"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Charlotte's signature Uptown park offers manicured lawns, art installations, and stunning skyline views. Leashed dogs are welcome to stroll the paths and enjoy the fountains. The park hosts regular events and is surrounded by restaurants, making it a perfect start or end point for an Uptown dog walk.",
    },
  ],
};
