export const charlestonData = {
  city: {
    name: "Charleston",
    state: "South Carolina",
    region: "Southeast",
    lat: 32.7765,
    lng: -79.9311,
    dogFriendlinessScore: 7,
    description:
      "Charleston's pastel-colored historic homes, horse-drawn carriages, and world-class dining scene extend a warm Southern welcome to four-legged visitors. With dog-friendly beaches on the barrier islands, lush waterfront parks, and restaurant patios serving Lowcountry cuisine, Charleston offers a genteel getaway for you and your pup.",
    heroImage: "https://images.unsplash.com/photo-1569878698889-7bffa1896872?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 150227,
  },

  hotels: [
    {
      name: "The Spectator Hotel",
      address: "67 State St, Charleston, SC 29401",
      lat: 32.7794,
      lng: -79.9289,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 40 lbs welcome with a pet fee. Boutique luxury in the heart of the Historic District.",
      maxDogWeight: 40,
      petFee: 100,
      amenities: ["Dog bed", "Ceramic bowls", "Gourmet treats", "Butler service for pet requests", "Walking map"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.thespectatorhotel.com",
      phone: "(843) 724-4326",
    },
    {
      name: "Hotel Bennett",
      address: "404 King St, Charleston, SC 29403",
      lat: 32.7850,
      lng: -79.9376,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome. Upscale pet program with luxury amenities.",
      maxDogWeight: 50,
      petFee: 150,
      amenities: ["Custom dog bed", "Bowls", "Premium treats", "Turndown treats", "Pet concierge"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.hotelbennett.com",
      phone: "(843) 445-6336",
    },
    {
      name: "The Kimpton Hotel Bella Grace",
      address: "115 Calhoun St, Charleston, SC 29401",
      lat: 32.7838,
      lng: -79.9334,
      priceRange: "$$$" as const,
      dogPolicy: "All dogs welcome regardless of size or breed. No pet fees. True dog-first hospitality.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking route suggestions", "Pet-sitting referrals"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelbellagrace.com",
      phone: "(843) 990-7500",
    },
    {
      name: "Francis Marion Hotel",
      address: "387 King St, Charleston, SC 29403",
      lat: 32.7846,
      lng: -79.9372,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 25 lbs welcome in pet-friendly rooms. Historic hotel with modern amenities.",
      maxDogWeight: 25,
      petFee: 50,
      amenities: ["Dog bed", "Water and food bowls", "Waste bags", "Near Marion Square park"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.francismarionhotel.com",
      phone: "(843) 722-0600",
    },
    {
      name: "Home2 Suites by Hilton Charleston",
      address: "1640 Savannah Hwy, Charleston, SC 29407",
      lat: 32.7614,
      lng: -79.9724,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a nightly fee. Suite-style rooms with kitchenettes.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Kitchenette", "Grassy pet area", "Waste stations", "Nearby West Ashley Greenway", "Pet treat at check-in"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(843) 573-2222",
    },
  ],

  nationalParks: [
    {
      name: "Fort Sumter and Fort Moultrie National Historical Park",
      state: "South Carolina",
      lat: 32.7524,
      lng: -79.8746,
      dogPolicy: "Dogs are NOT allowed on the Fort Sumter ferry or on Fort Sumter island. Leashed dogs are welcome at Fort Moultrie on Sullivan's Island.",
      dogTrails: ["Fort Moultrie grounds (leashed)", "Sullivan's Island beach walk (nearby)"],
      restrictions: [
        "No dogs on Fort Sumter ferry",
        "No dogs on Fort Sumter island",
        "Dogs must be leashed at Fort Moultrie",
        "Not allowed inside historic structures",
      ],
      description:
        "Where the Civil War began, Fort Sumter sits in Charleston Harbor and is only accessible by ferry that does not allow pets. However, Fort Moultrie on Sullivan's Island welcomes leashed dogs and offers fascinating Revolutionary and Civil War history with harbor views.",
      imageUrl: "",
      website: "https://www.nps.gov/fosu",
    },
    {
      name: "Charles Pinckney National Historic Site",
      state: "South Carolina",
      lat: 32.8463,
      lng: -79.8265,
      dogPolicy: "Leashed dogs welcome on the grounds and along the nature trail. A peaceful, lesser-known NPS site.",
      dogTrails: ["Snee Farm nature trail", "Grounds walking path"],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Not allowed inside the historic house",
        "Must stay on designated trails",
      ],
      description:
        "This 28-acre site preserves the remnants of Snee Farm, the colonial plantation of Founding Father Charles Pinckney. Leashed dogs can explore the scenic grounds and a short nature trail through Lowcountry landscape.",
      imageUrl: "",
      website: "https://www.nps.gov/chpi",
    },
    {
      name: "Congaree National Park",
      state: "South Carolina",
      lat: 33.7948,
      lng: -80.7821,
      dogPolicy: "Leashed dogs welcome on all trails and in campgrounds. One of the most dog-friendly national parks in the Southeast.",
      dogTrails: ["Boardwalk Loop Trail", "Weston Lake Loop", "Bluff Trail", "Kingsnake Trail", "River Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed in buildings",
        "Must stay on designated trails",
      ],
      description:
        "About 90 minutes from Charleston, Congaree protects the largest intact expanse of old-growth bottomland hardwood forest in North America. The elevated boardwalk and extensive trail system welcome leashed dogs through a primeval landscape of towering trees and dark waters.",
      imageUrl: "",
      website: "https://www.nps.gov/cong",
    },
  ],

  restaurants: [
    {
      name: "The Obstinate Daughter",
      address: "2063 Middle St, Sullivan's Island, SC 29482",
      lat: 32.7637,
      lng: -79.8387,
      cuisine: "Italian-Lowcountry",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the spacious outdoor patio. Popular after a day at the beach on Sullivan's Island.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.theobstinatedaughter.com",
    },
    {
      name: "Home Team BBQ",
      address: "126 Williman St, Charleston, SC 29403",
      lat: 32.7870,
      lng: -79.9404,
      cuisine: "Barbecue",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly outdoor area with picnic tables and a lively atmosphere.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hometeambbq.com",
    },
    {
      name: "The Darling Oyster Bar",
      address: "513 King St, Charleston, SC 29403",
      lat: 32.7878,
      lng: -79.9384,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome at the outdoor sidewalk tables on Upper King Street.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thedarling.com",
    },
    {
      name: "Poe's Tavern",
      address: "2210 Middle St, Sullivan's Island, SC 29482",
      lat: 32.7637,
      lng: -79.8369,
      cuisine: "American Pub",
      priceRange: "$$" as const,
      dogPolicy: "Edgar Allan Poe-themed burger joint with a large dog-friendly patio. Steps from the beach.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.poestavern.com",
    },
    {
      name: "Edmunds Oast Brewing Co.",
      address: "1505 King St, Charleston, SC 29405",
      lat: 32.8041,
      lng: -79.9403,
      cuisine: "Brewery & Southern",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly taproom with outdoor seating. Known for creative beers and a welcoming vibe.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.edmundsoast.com",
    },
    {
      name: "Lewis Barbecue",
      address: "464 N Nassau St, Charleston, SC 29403",
      lat: 32.7925,
      lng: -79.9448,
      cuisine: "Texas-Style Barbecue",
      priceRange: "$$" as const,
      dogPolicy: "Large outdoor picnic area welcomes dogs. Texas-style brisket in a casual setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.lewisbarbecue.com",
    },
    {
      name: "The Tattooed Moose",
      address: "1137 Morrison Dr, Charleston, SC 29403",
      lat: 32.8011,
      lng: -79.9478,
      cuisine: "American",
      priceRange: "$" as const,
      dogPolicy: "Casual dive-bar atmosphere with a dog-friendly outdoor seating area. Legendary duck club sandwich.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tattooedmoose.com",
    },
    {
      name: "167 Raw",
      address: "289 E Bay St, Charleston, SC 29401",
      lat: 32.7812,
      lng: -79.9270,
      cuisine: "Seafood & Raw Bar",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome at a few outdoor tables. Fresh New England-meets-Lowcountry seafood.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.167raw.com",
    },
  ],

  cafes: [
    {
      name: "Harbinger Cafe & Bakery",
      address: "498 King St, Charleston, SC 29403",
      lat: 32.7872,
      lng: -79.9381,
      dogPolicy: "Leashed dogs welcome at the outdoor tables along King Street. Fresh pastries and specialty coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.harbingercafe.com",
    },
    {
      name: "Black Tap Coffee",
      address: "215 Meeting St, Charleston, SC 29401",
      lat: 32.7802,
      lng: -79.9322,
      dogPolicy: "Dog-friendly sidewalk seating in the Historic District. Craft coffee and cold brew on tap.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.blacktapcoffee.com",
    },
    {
      name: "Collective Coffee",
      address: "2 N Market St, Charleston, SC 29401",
      lat: 32.7813,
      lng: -79.9274,
      dogPolicy: "Small but charming patio where leashed dogs are welcome. Steps from the City Market.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.collectivecoffeechs.com",
    },
    {
      name: "Kudu Coffee & Craft Beer",
      address: "4 Vanderhorst St, Charleston, SC 29403",
      lat: 32.7852,
      lng: -79.9370,
      dogPolicy: "Hidden courtyard oasis where dogs are welcome among lush tropical plants. A local favorite.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.kuducharleston.com",
    },
    {
      name: "Second State Coffee",
      address: "70 1/2 Beaufain St, Charleston, SC 29401",
      lat: 32.7785,
      lng: -79.9349,
      dogPolicy: "Leashed dogs welcome at the outdoor seating area. Thoughtfully sourced single-origin coffees.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.secondstatecoffee.com",
    },
  ],

  dogParks: [
    {
      name: "James Island County Park Dog Park",
      address: "871 Riverland Dr, Charleston, SC 29412",
      lat: 32.7342,
      lng: -79.9516,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Separate small and large dog areas", "Water stations", "Shade shelters", "Agility equipment", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Part of the larger James Island County Park, this off-leash area features separate zones for large and small dogs, shade structures for hot Charleston days, and water stations to keep pups cool.",
    },
    {
      name: "Wannamaker County Park Dog Park",
      address: "8888 University Blvd, North Charleston, SC 29406",
      lat: 32.9203,
      lng: -80.0509,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Double-gated entry", "Water fountains", "Benches", "Shade trees", "Waste stations", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A well-maintained fenced dog park within Wannamaker County Park. Two acres of open space with shade and water make it a reliable spot for off-leash play year-round.",
    },
    {
      name: "Hampton Park",
      address: "30 Mary Murray Dr, Charleston, SC 29403",
      lat: 32.7947,
      lng: -79.9468,
      offLeash: false,
      fenced: false,
      acres: 60.0,
      amenities: ["Walking paths", "Gardens", "Gazebo", "Shade trees", "Benches", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Charleston's largest park features a scenic one-mile walking loop through beautiful gardens and under towering live oaks. Dogs must be leashed, but the peaceful atmosphere and gorgeous grounds make it a beloved walking destination.",
    },
    {
      name: "Sullivan's Island Beach",
      address: "Station 22, Sullivan's Island, SC 29482",
      lat: 32.7627,
      lng: -79.8408,
      offLeash: true,
      fenced: false,
      acres: 10.0,
      amenities: ["Beach access", "Ocean swimming", "Free parking", "Waste stations"],
      rating: 4.7,
      imageUrl: "",
      description:
        "One of the most dog-friendly beaches in the Charleston area, Sullivan's Island allows off-leash dogs during certain hours. Your pup can run free on the sand and splash in the Atlantic waves.",
    },
    {
      name: "Palmetto Islands County Park",
      address: "444 Needlerush Pkwy, Mt Pleasant, SC 29464",
      lat: 32.8330,
      lng: -79.8274,
      offLeash: false,
      fenced: false,
      acres: 943.0,
      amenities: ["Nature trails", "Boardwalks", "Marsh views", "Picnic shelters", "Waste stations", "Parking"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A sprawling Lowcountry nature park with miles of trails through maritime forests and salt marshes. Leashed dogs can explore boardwalks, creekside paths, and shaded picnic areas in this natural setting.",
    },
  ],
};
