export const chattanoogaData = {
  city: {
    name: "Chattanooga",
    state: "Tennessee",
    region: "Southeast",
    lat: 35.0456,
    lng: -85.3097,
    dogFriendlinessScore: 7,
    description:
      "Where the Tennessee River bends through a dramatic valley flanked by Lookout Mountain and Signal Mountain, Chattanooga is a revitalized Southern city that loves its dogs. From the world-famous Riverwalk to dog-friendly patios lining the Northshore district, this outdoor-adventure hub pairs mountain hikes, rock climbing, and river paddling with a warm, welcoming attitude toward four-legged explorers.",
    heroImage: "https://images.unsplash.com/photo-1570641963303-92ce4845ed4c?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 181099,
  },

  hotels: [
    {
      name: "The Edwin Hotel",
      address: "102 Walnut St, Chattanooga, TN 37403",
      lat: 35.0566,
      lng: -85.3088,
      priceRange: "$$$$" as const,
      dogPolicy:
        "Luxury boutique hotel on the riverfront welcoming dogs up to 40 lbs. Pet amenity package at check-in.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: [
        "Dog bed",
        "Bowls and treats",
        "Riverwalk access",
        "Pet concierge",
        "Waste bags",
      ],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.theedwinhotel.com",
      phone: "(423) 777-7007",
    },
    {
      name: "The Dwell Hotel",
      address: "120 E 10th St, Chattanooga, TN 37402",
      lat: 35.0485,
      lng: -85.3055,
      priceRange: "$$$" as const,
      dogPolicy:
        "Mid-century modern boutique hotel welcoming dogs of all sizes. Hip design and dog-friendly vibes.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: [
        "Dog bed",
        "Water bowls",
        "Walking distance to Riverwalk",
        "Rooftop bar",
      ],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thedwellhotel.com",
      phone: "(423) 267-7866",
    },
    {
      name: "Kinley Chattanooga Southside",
      address: "1218 Market St, Chattanooga, TN 37402",
      lat: 35.039,
      lng: -85.308,
      priceRange: "$$" as const,
      dogPolicy:
        "Trendy Southside hotel welcoming dogs under 50 lbs. Walking distance to restaurants and the Chattanooga Choo Choo.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: [
        "Dog-friendly rooms",
        "Grassy area",
        "Waste stations",
        "Walking distance to Southside district",
      ],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.kinleyhotels.com",
      phone: "(423) 475-2600",
    },
    {
      name: "Home2 Suites Downtown Chattanooga",
      address: "437 Market St, Chattanooga, TN 37402",
      lat: 35.047,
      lng: -85.308,
      priceRange: "$$" as const,
      dogPolicy:
        "All-suite hotel that welcomes dogs of all sizes with no breed restrictions. Full kitchen in every suite.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: [
        "Full kitchen",
        "Pet relief area",
        "Waste stations",
        "Free breakfast",
        "Laundry facilities",
      ],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(423) 531-0002",
    },
    {
      name: "Crash Pad: An Uncommon Hostel",
      address: "29 Johnson St, Chattanooga, TN 37408",
      lat: 35.038,
      lng: -85.307,
      priceRange: "$" as const,
      dogPolicy:
        "Budget-friendly hostel for adventurers and their dogs. Pet-friendly private rooms available with a small fee.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: [
        "Outdoor hangout area",
        "Climber-friendly",
        "Waste bags",
        "Bike storage",
      ],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.crashpadchattanooga.com",
      phone: "(423) 648-8393",
    },
  ],

  nationalParks: [
    {
      name: "Chickamauga and Chattanooga National Military Park",
      state: "Georgia / Tennessee",
      lat: 34.9194,
      lng: -85.2598,
      dogPolicy:
        "Leashed dogs welcome on all trails, roads, and grounds of this historic Civil War battlefield. A wonderful way to walk through history with your pup.",
      dogTrails: [
        "Chickamauga Battlefield Loop",
        "Lookout Mountain Battlefield trails",
        "Point Park paths",
        "Cravens House Trail",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash at all times",
        "Not allowed inside visitor center or historic buildings",
        "Must clean up after pets",
      ],
      description:
        "America's oldest and largest military park preserves the sites of two major Civil War battles. Miles of trails wind through open fields, dense forests, and past hundreds of monuments. Leashed dogs can explore the vast grounds where history echoes in every footstep (and paw print).",
      imageUrl: "",
      website: "https://www.nps.gov/chch",
    },
    {
      name: "Lookout Mountain",
      state: "Tennessee",
      lat: 35.0106,
      lng: -85.3455,
      dogPolicy:
        "Leashed dogs welcome on many trails around Lookout Mountain. Some attractions have restrictions but the outdoor areas are great for dogs.",
      dogTrails: [
        "Bluff Trail",
        "Sunset Rock Trail",
        "Guild Trail",
        "Cravens House Trail",
      ],
      restrictions: [
        "Dogs not allowed inside Rock City, Ruby Falls, or Incline Railway",
        "Must be on a leash on all trails",
        "Must clean up after pets",
      ],
      description:
        "Rising 2,389 feet above the city, Lookout Mountain offers spectacular views of seven states. While dogs can't enter the commercial attractions, the hiking trails are excellent. The Bluff Trail to Sunset Rock offers jaw-dropping views of the Tennessee Valley that will leave both you and your pup breathless.",
      imageUrl: "",
      website: "https://www.lookoutmountain.com",
    },
    {
      name: "Cloudland Canyon State Park",
      state: "Georgia",
      lat: 34.8367,
      lng: -85.4814,
      dogPolicy:
        "Leashed dogs welcome on all trails including the spectacular canyon rim and waterfall trails.",
      dogTrails: [
        "West Rim Trail",
        "Waterfalls Trail",
        "Overlook Trail",
        "Sitton Gulch Trail",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash",
        "Not allowed in cottages or yurts",
        "Must clean up after pets",
        "Waterfall trail involves many stairs — consider your dog's fitness",
      ],
      description:
        "One of Georgia's most scenic parks features a deep sandstone canyon with two waterfalls accessible by trail. Leashed dogs can tackle the canyon rim, descend to the waterfalls (bring your stamina — 600+ stairs!), and enjoy camping amid the wild beauty of the Cumberland Plateau.",
      imageUrl: "",
      website: "https://gastateparks.org/CloudlandCanyon",
    },
    {
      name: "Prentice Cooper State Forest",
      state: "Tennessee",
      lat: 35.088,
      lng: -85.4429,
      dogPolicy:
        "Dogs welcome off-leash in most areas of this vast state forest. An adventure dog's paradise with rugged trails and river bluffs.",
      dogTrails: [
        "Pot Point Loop",
        "Mullens Cove Loop",
        "Ritchie Hollow Trail",
        "Ransom Hollow Trail",
      ],
      restrictions: [
        "Dogs should be under voice control",
        "Be aware of hunting seasons — wear blaze orange",
        "Must clean up after pets in camping areas",
      ],
      description:
        "Over 26,000 acres of rugged forest along the Tennessee River Gorge with trails offering stunning bluff views. Dogs can explore off-leash through this wild landscape of sandstone cliffs, hardwood forests, and seasonal creeks. The Pot Point Loop offers spectacular river gorge views.",
      imageUrl: "",
      website: "https://www.tn.gov/agriculture/forests/state-forests.html",
    },
  ],

  restaurants: [
    {
      name: "The Feed Co. Table & Tavern",
      address: "201 W Main St, Chattanooga, TN 37408",
      lat: 35.0395,
      lng: -85.3095,
      cuisine: "Southern / Farm-to-Table",
      priceRange: "$$" as const,
      dogPolicy:
        "Large covered patio in the Southside district where dogs are welcomed with water and lots of love.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thefeedco.com",
    },
    {
      name: "Oddstory Brewing Company",
      address: "734 Cherry St, Chattanooga, TN 37402",
      lat: 35.051,
      lng: -85.312,
      cuisine: "Brewery / Snacks",
      priceRange: "$" as const,
      dogPolicy:
        "Dogs are welcome inside the taproom and on the outdoor patio. One of Chattanooga's most dog-forward breweries.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.oddstorybrewing.com",
    },
    {
      name: "Taco Mamacita",
      address: "109 N Market St, Chattanooga, TN 37405",
      lat: 35.059,
      lng: -85.311,
      cuisine: "Mexican / Tacos",
      priceRange: "$" as const,
      dogPolicy:
        "Northshore favorite with a dog-friendly patio. Creative tacos and margaritas while your pup watches the Walnut Street Bridge crowd.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.tacomamacita.com",
    },
    {
      name: "Stir",
      address: "1444 Market St, Chattanooga, TN 37402",
      lat: 35.037,
      lng: -85.308,
      cuisine: "Asian Fusion / Ramen",
      priceRange: "$$" as const,
      dogPolicy:
        "Sidewalk patio seating where leashed dogs are welcome. Slurp ramen while your pup soaks up the Southside scene.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.stirchattanooga.com",
    },
    {
      name: "Hutton & Smith Brewing Co.",
      address: "431 E M.L.K. Blvd, Chattanooga, TN 37403",
      lat: 35.0475,
      lng: -85.303,
      cuisine: "Brewery / Pub",
      priceRange: "$" as const,
      dogPolicy:
        "Adventure-themed brewery with a spacious dog-friendly taproom and patio. Named after the first summiteers of Everest — bring your adventurous pup!",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.huttonandsmith.com",
    },
    {
      name: "The Meeting Place",
      address: "90 Cherokee Blvd, Chattanooga, TN 37405",
      lat: 35.066,
      lng: -85.319,
      cuisine: "Brunch / American",
      priceRange: "$$" as const,
      dogPolicy:
        "Weekend brunch spot with a gorgeous patio overlooking the Tennessee River. Dogs welcome and often get extra bacon from the kitchen.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.themeetingplacechatt.com",
    },
    {
      name: "Clyde's on Main",
      address: "200 E Main St, Chattanooga, TN 37408",
      lat: 35.0395,
      lng: -85.307,
      cuisine: "Gastropub / American",
      priceRange: "$$" as const,
      dogPolicy:
        "Southside gastropub with covered outdoor seating. Dogs welcome on the patio with water provided.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.clydesonmain.com",
    },
    {
      name: "State of Confusion",
      address: "1001 Market St, Chattanooga, TN 37402",
      lat: 35.042,
      lng: -85.308,
      cuisine: "Southern Fusion",
      priceRange: "$$" as const,
      dogPolicy:
        "Massive patio space with fire pits where dogs are always welcome. Southern comfort food with a twist and live music on weekends.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.stateofconfusionchattanooga.com",
    },
  ],

  cafes: [
    {
      name: "Velo Coffee Roasters",
      address: "1097 Market St, Chattanooga, TN 37402",
      lat: 35.041,
      lng: -85.308,
      dogPolicy:
        "Specialty coffee roaster with a dog-friendly outdoor seating area. Cyclists and dog walkers converge here for exceptional pour-overs.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.velocoffee.com",
    },
    {
      name: "Mean Mug Coffeehouse",
      address: "114 W Main St, Chattanooga, TN 37408",
      lat: 35.0393,
      lng: -85.309,
      dogPolicy:
        "Beloved Southside coffee shop with a covered patio where dogs are always welcome. Known for their cold brew and warm dog greetings.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.meanmugcoffee.com",
    },
    {
      name: "Rembrandt's Coffee House",
      address: "204 High St, Chattanooga, TN 37403",
      lat: 35.049,
      lng: -85.304,
      dogPolicy:
        "Long-running Chattanooga coffee institution with a charming patio. Dogs welcome outside while you enjoy pastries and espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.rfrembrandts.com",
    },
    {
      name: "Frothy Monkey",
      address: "1400 Market St, Chattanooga, TN 37408",
      lat: 35.0375,
      lng: -85.308,
      dogPolicy:
        "Nashville transplant with a spacious Southside patio. Dogs welcome and treats occasionally available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.frothymonkey.com",
    },
    {
      name: "The Camp House",
      address: "149 E M.L.K. Blvd, Chattanooga, TN 37403",
      lat: 35.048,
      lng: -85.306,
      dogPolicy:
        "Coworking-meets-coffee-shop with a patio where dogs can relax while you work or sip. A Chattanooga original.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thecamphouse.com",
    },
  ],

  dogParks: [
    {
      name: "Riverwalk (Tennessee Riverpark)",
      address: "4301 Amnicola Hwy, Chattanooga, TN 37402",
      lat: 35.072,
      lng: -85.282,
      offLeash: false,
      fenced: false,
      acres: 75,
      amenities: [
        "13-mile paved path",
        "River views",
        "Fishing piers",
        "Playgrounds nearby",
        "Waste stations",
      ],
      rating: 4.8,
      imageUrl: "",
      description:
        "Chattanooga's crown jewel — a 13-mile paved riverwalk stretching along the Tennessee River. Leashed dogs love the scenic path that passes parks, bridges, and public art. You can walk from downtown across the iconic Walnut Street Pedestrian Bridge to the Northshore and back for a perfect urban adventure.",
    },
    {
      name: "Camp Jordan Dog Park",
      address: "323 Camp Jordan Pkwy, East Ridge, TN 37412",
      lat: 35.007,
      lng: -85.263,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: [
        "Separate small and large dog areas",
        "Water fountains",
        "Agility equipment",
        "Shade structures",
        "Waste stations",
        "Parking",
      ],
      rating: 4.4,
      imageUrl: "",
      description:
        "A well-maintained fenced dog park with separate areas for large and small dogs. Agility equipment keeps athletic pups entertained, while shaded benches give their humans a break. Adjacent to the larger Camp Jordan Park with walking trails.",
    },
    {
      name: "Renaissance Park Dog Run",
      address: "300 Manufacturer's Rd, Chattanooga, TN 37405",
      lat: 35.064,
      lng: -85.315,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: [
        "Fenced area",
        "River views",
        "Walking distance to Northshore",
        "Waste stations",
        "Water access",
      ],
      rating: 4.2,
      imageUrl: "",
      description:
        "A fenced off-leash area along the Tennessee River on the Northshore. Dogs can play with views of downtown Chattanooga and the river. After playtime, walk to nearby Northshore restaurants for a patio lunch.",
    },
    {
      name: "Coolidge Park",
      address: "150 River St, Chattanooga, TN 37405",
      lat: 35.06,
      lng: -85.309,
      offLeash: false,
      fenced: false,
      acres: 10,
      amenities: [
        "Riverwalk access",
        "Walnut Street Bridge",
        "Splash pad (humans)",
        "Carousel",
        "Waste stations",
      ],
      rating: 4.5,
      imageUrl: "",
      description:
        "A beautiful riverfront park at the north end of the iconic Walnut Street Pedestrian Bridge. Leashed dogs can enjoy the park's paths, watch the fountain, and cross the historic bridge to downtown. The bridge walk offers stunning river and mountain views.",
    },
    {
      name: "Greenway Farm Dog Park",
      address: "1385 Greenway View Dr, Chattanooga, TN 37415",
      lat: 35.088,
      lng: -85.312,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: [
        "Fenced area",
        "Water spigots",
        "Benches",
        "Shade trees",
        "Waste stations",
        "Parking",
      ],
      rating: 4.1,
      imageUrl: "",
      description:
        "A neighborhood dog park in North Chattanooga with a fully fenced play area. Regulars are friendly and welcoming. Features water spigots, shade trees, and enough room for even the zoomiest dogs to stretch their legs.",
    },
  ],
};
