export const chicagoData = {
  city: {
    name: "Chicago",
    state: "Illinois",
    region: "Midwest",
    lat: 41.8781,
    lng: -87.6298,
    dogFriendlinessScore: 8,
    description:
      "The Windy City is a top-tier destination for dogs with its lakefront trails stretching 18 miles, dedicated dog-friendly beaches, and a thriving restaurant scene where patio season is celebrated with gusto. Chicago's neighborhoods each offer unique dog-walking experiences from Lincoln Park to Wicker Park.",
    heroImage: "https://images.unsplash.com/photo-1494522855154-9297ac14b55f?w=1200&fit=crop",
    climate: "Humid continental",
    population: 2746388,
  },
  hotels: [
    {
      name: "Kimpton Hotel Monaco Chicago",
      address: "225 N Wabash Ave, Chicago, IL 60601",
      lat: 41.8865,
      lng: -87.6265,
      priceRange: "$$$" as const,
      dogPolicy: "All pets welcome regardless of size or breed at no extra charge. Kimpton's signature pet-friendly hospitality in the Loop.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Loaner leashes", "Pet concierge"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ihg.com/kimptonhotels/hotels/us/en/chicago/chimn",
      phone: "(312) 960-8500",
    },
    {
      name: "The Langham Chicago",
      address: "330 N Wabash Ave, Chicago, IL 60611",
      lat: 41.8886,
      lng: -87.6265,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs under 30 lbs welcome with a pet fee. Luxury waterfront hotel along the Chicago River.",
      maxDogWeight: 30,
      petFee: 150,
      amenities: ["Plush dog bed", "Personalized pet tag", "Water and food bowls", "Pet amenity kit", "Dog walking referral"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.langhamhotels.com/en/the-langham/chicago",
      phone: "(312) 923-9988",
    },
    {
      name: "Hotel Lincoln",
      address: "1816 N Clark St, Chicago, IL 60614",
      lat: 41.9145,
      lng: -87.6338,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome with a per-stay fee. A fun boutique hotel across from Lincoln Park Zoo.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Lincoln Park access", "Waste bags", "Treats"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.jdvhotels.com/hotels/illinois/chicago/hotel-lincoln",
      phone: "(312) 254-4700",
    },
    {
      name: "Virgin Hotels Chicago",
      address: "203 N Wabash Ave, Chicago, IL 60601",
      lat: 41.8860,
      lng: -87.6260,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of any size welcome with no pet fee. A stylish downtown hotel with a dog-loving attitude.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treats", "Waste bags", "Pet-friendly common areas"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.virginhotels.com/chicago",
      phone: "(312) 940-4400",
    },
  ],
  nationalParks: [
    {
      name: "Indiana Dunes National Park",
      state: "Indiana",
      lat: 41.6533,
      lng: -87.0524,
      dogPolicy: "Dogs allowed on most beaches and the Portage Lakefront and Riverwalk Trail on a 6-foot leash. Not permitted on other trails or in dune areas.",
      dogTrails: ["Portage Lakefront and Riverwalk Trail", "West Beach (leashed)", "Central Beach (leashed)"],
      restrictions: ["6-foot leash required", "Not allowed on most hiking trails", "No dogs in dune areas", "Must clean up after pet"],
      description: "About an hour southeast of Chicago, Indiana Dunes features 15 miles of Lake Michigan shoreline with towering sand dunes. Dogs can enjoy the beaches and selected trails with stunning lake views.",
      imageUrl: "",
      website: "https://www.nps.gov/indu",
    },
    {
      name: "Starved Rock State Park",
      state: "Illinois",
      lat: 41.3201,
      lng: -88.9937,
      dogPolicy: "Dogs welcome on all trails on a leash. Stunning sandstone canyons and waterfalls along the Illinois River.",
      dogTrails: ["French Canyon Trail", "Wildcat Canyon Trail", "St. Louis Canyon Trail", "Lover's Leap Trail"],
      restrictions: ["Leash required", "Not in lodge", "Must clean up after pet", "Some canyon trails may be slippery"],
      description: "About 90 minutes southwest of Chicago, Starved Rock features 18 dramatic sandstone canyons carved by glacial meltwater. Dogs can hike all trails through the forested bluffs above the Illinois River.",
      imageUrl: "",
      website: "https://www.starvedrockstatepark.org",
    },
    {
      name: "Chicago Lakefront Trail",
      state: "Illinois",
      lat: 41.9000,
      lng: -87.6160,
      dogPolicy: "Dogs welcome on the entire 18-mile trail on a leash. Connects parks, beaches, and harbors along Lake Michigan.",
      dogTrails: ["North Lakefront Trail", "Central Lakefront Trail", "South Lakefront Trail"],
      restrictions: ["Leash required", "Not on designated swimming beaches during beach season", "Must clean up after pet"],
      description: "Chicago's crown jewel trail stretches 18 miles along the Lake Michigan shoreline from Ardmore to 71st Street. Dogs can enjoy the paved path passing parks, harbors, museums, and skyline views.",
      imageUrl: "",
      website: "https://www.chicagoparkdistrict.com/parks-facilities/lakefront-trail",
    },
  ],
  restaurants: [
    {
      name: "Big Star",
      address: "1531 N Damen Ave, Chicago, IL 60622",
      lat: 41.9092,
      lng: -87.6770,
      cuisine: "Mexican & Tacos",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the large outdoor patio. A Wicker Park institution for tacos, whiskey, and honky-tonk vibes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bigstarchicago.com",
    },
    {
      name: "Parson's Chicken & Fish",
      address: "2952 W Armitage Ave, Chicago, IL 60647",
      lat: 41.9170,
      lng: -87.6987,
      cuisine: "Fried Chicken & Seafood",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome in the expansive outdoor area with picnic tables. Famous for their frozen negronis and fried chicken.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.parsonschickenandfish.com",
    },
    {
      name: "The Patio at Cafe Brauer",
      address: "2021 N Stockton Dr, Chicago, IL 60614",
      lat: 41.9213,
      lng: -87.6335,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor terrace overlooking the Lincoln Park lagoon. Beautiful park setting with skyline views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cafebrauer.com",
    },
    {
      name: "Half Acre Tap Room",
      address: "4257 N Lincoln Ave, Chicago, IL 60618",
      lat: 41.9574,
      lng: -87.6846,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome in the beer garden. One of Chicago's most beloved craft breweries in the Lincoln Square neighborhood.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.halfacrebeer.com",
    },
    {
      name: "Beatnik on the River",
      address: "180 N Upper Wacker Dr, Chicago, IL 60601",
      lat: 41.8860,
      lng: -87.6360,
      cuisine: "Mediterranean",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the riverfront patio. A stunning riverfront setting with globally inspired cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.beatnikontheriver.com",
    },
  ],
  cafes: [
    {
      name: "Intelligentsia Coffee",
      address: "3123 N Broadway, Chicago, IL 60657",
      lat: 41.9383,
      lng: -87.6449,
      dogPolicy: "Dogs welcome on the outdoor patio. The flagship roaster of Chicago's specialty coffee scene.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.intelligentsia.com",
    },
    {
      name: "Dark Matter Coffee - Star Lounge",
      address: "738 N Western Ave, Chicago, IL 60612",
      lat: 41.8956,
      lng: -87.6873,
      dogPolicy: "Dogs welcome on the patio. An eclectic coffee roaster known for bold blends and psychedelic branding.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.darkmattercoffee.com",
    },
    {
      name: "Metric Coffee Co.",
      address: "2021 W Fulton St, Chicago, IL 60612",
      lat: 41.8866,
      lng: -87.6784,
      dogPolicy: "Dogs welcome in the outdoor area. A minimalist Fulton Market roastery with exceptional single-origin coffees.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.metriccoffee.com",
    },
    {
      name: "Colectivo Coffee",
      address: "1801 N Damen Ave, Chicago, IL 60647",
      lat: 41.9140,
      lng: -87.6770,
      dogPolicy: "Dog-friendly outdoor seating in the Bucktown neighborhood. A Milwaukee-born roaster with spacious patios.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.colectivocoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Montrose Dog Beach",
      address: "4400 N Simonds Dr, Chicago, IL 60640",
      lat: 41.9632,
      lng: -87.6385,
      offLeash: true,
      fenced: true,
      acres: 4,
      amenities: ["Beach access", "Lake swimming", "Wash station", "Water fountains", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "Chicago's most popular dog beach offers off-leash access to Lake Michigan with sandy shores and dedicated swimming areas. Dogs splash in the lake while owners enjoy skyline views. A must-visit for water-loving dogs.",
    },
    {
      name: "Wiggly Field Dog Park",
      address: "2645 N Sheffield Ave, Chicago, IL 60614",
      lat: 41.9290,
      lng: -87.6540,
      offLeash: true,
      fenced: true,
      acres: 1,
      amenities: ["Double-gated entry", "Benches", "Water fountain", "Turf surface", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "This cleverly named dog park in Lincoln Park offers a compact but popular off-leash space near Wrigley Field. The well-maintained turf surface is easy on paws year-round.",
    },
    {
      name: "Churchill Field Dog Park",
      address: "1825 N Damen Ave, Chicago, IL 60647",
      lat: 41.9145,
      lng: -87.6770,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Separate small dog area", "Benches", "Water fountain", "Shade trees", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "A popular Bucktown dog park with separate areas for large and small dogs. The community of regular dog owners makes it a social hub for neighborhood pups.",
    },
    {
      name: "Belmont Harbor Dog Park",
      address: "3600 N Recreation Dr, Chicago, IL 60613",
      lat: 41.9400,
      lng: -87.6366,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Lake views", "Water fountains", "Benches", "Sandy surface", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "A lakefront dog park with stunning views of Lake Michigan and the Chicago skyline. Dogs enjoy the sandy surface and lake breezes in this prime Lakeview location.",
    },
  ],
};
