export const cincinnatiData = {
  city: {
    name: "Cincinnati",
    state: "Ohio",
    region: "Midwest",
    lat: 39.1031,
    lng: -84.5120,
    dogFriendlinessScore: 7,
    description:
      "The Queen City offers dogs a surprising wealth of experiences from the riverfront Smale Riverfront Park to the charming neighborhoods of Over-the-Rhine and Mount Adams. Cincinnati's hilly terrain provides scenic walks with Ohio River views, and its brewery scene is among the most dog-friendly in the Midwest.",
    heroImage: "https://images.unsplash.com/photo-1570710891163-6d3b5c47f2c0?w=1200&fit=crop",
    climate: "Humid continental",
    population: 309317,
  },
  hotels: [
    {
      name: "21c Museum Hotel Cincinnati",
      address: "609 Walnut St, Cincinnati, OH 45202",
      lat: 39.1010,
      lng: -84.5110,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a pet fee. A contemporary art museum and hotel that started the 21c brand here in Cincinnati.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Art-filled lobby", "Treats at check-in", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.21cmuseumhotels.com/cincinnati",
      phone: "(513) 578-6600",
    },
    {
      name: "Hotel Covington",
      address: "638 Madison Ave, Covington, KY 41011",
      lat: 39.0840,
      lng: -84.5090,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of any size welcome with a per-stay fee. A stylish boutique hotel across the river in Covington with Cincinnati skyline views.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Riverfront walking access", "Waste bags", "Treats"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hotelcovington.com",
      phone: "(859) 905-5500",
    },
    {
      name: "Graduate Cincinnati",
      address: "151 Goodman Dr, Cincinnati, OH 45219",
      lat: 39.1310,
      lng: -84.5090,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a one-time pet fee. A UC-themed boutique hotel near the university campus.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Treats", "Waste bags", "Walking suggestions"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.graduatehotels.com/cincinnati",
      phone: "(513) 487-3800",
    },
    {
      name: "Residence Inn Cincinnati Downtown",
      address: "506 E 4th St, Cincinnati, OH 45202",
      lat: 39.0990,
      lng: -84.5050,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a non-refundable pet fee. Extended-stay suites near the riverfront.",
      maxDogWeight: 75,
      petFee: 75,
      amenities: ["Pet-friendly suites", "Full kitchen", "Waste bags", "Riverfront access", "Dog treat at check-in"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com/hotels/travel/cvgri",
      phone: "(513) 651-1234",
    },
  ],
  nationalParks: [
    {
      name: "East Fork State Park",
      state: "Ohio",
      lat: 39.0170,
      lng: -84.1350,
      dogPolicy: "Dogs welcome on all trails and in campgrounds on a 6-foot leash. A large state park about 30 minutes east of Cincinnati.",
      dogTrails: ["Steve Newman Worldwalker Perimeter Trail", "Backpack Trail", "Nature Trail"],
      restrictions: ["6-foot leash required", "Not on swimming beach", "Must clean up after pet"],
      description: "With a 2,160-acre lake and nearly 10,000 acres of rolling hills, East Fork offers extensive trails and water recreation. Dogs enjoy the long perimeter trail that circles the reservoir through forests and meadows.",
      imageUrl: "",
      website: "https://www.ohiodnr.gov/go-and-do/plan-a-visit/find-a-property/east-fork-state-park",
    },
    {
      name: "Cincinnati Nature Center",
      state: "Ohio",
      lat: 39.1180,
      lng: -84.2690,
      dogPolicy: "Dogs welcome on all trails on a 6-foot leash. A 1,025-acre nature preserve east of the city.",
      dogTrails: ["Geology Trail", "Upland Trail", "Lookout Trail", "Powel Crosley Lake Trail"],
      restrictions: ["6-foot leash required", "Not in buildings", "Must clean up after pet"],
      description: "About 25 minutes from downtown, this nature center features over 16 miles of trails through old-growth forest, meadows, and along a scenic lake. Dogs love the varied terrain and abundant wildlife.",
      imageUrl: "",
      website: "https://www.cincynature.org",
    },
    {
      name: "Smale Riverfront Park",
      state: "Ohio",
      lat: 39.0960,
      lng: -84.5130,
      dogPolicy: "Dogs welcome throughout the park on a leash. A beautifully designed riverfront park connecting to the Roebling Suspension Bridge.",
      dogTrails: ["Riverwalk", "Moerlein Lager House Path", "Serpentine Wall Walk"],
      restrictions: ["Leash required", "Must clean up after pet", "Not in splash pads"],
      description: "This stunning riverfront park stretches along the Ohio River with views of the Roebling Suspension Bridge and the Kentucky hillside. Dogs enjoy the wide promenades, river breezes, and the connected trail system.",
      imageUrl: "",
      website: "https://www.cincinnatiparks.com/smale-riverfront-park",
    },
  ],
  restaurants: [
    {
      name: "Rhinegeist Brewery",
      address: "1910 Elm St, Cincinnati, OH 45202",
      lat: 39.1150,
      lng: -84.5200,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome in the massive taproom and outdoor patio. A Cincinnati craft brewery in a restored bottling plant in OTR.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.rhinegeist.com",
    },
    {
      name: "Bakersfield OTR",
      address: "1213 Vine St, Cincinnati, OH 45202",
      lat: 39.1090,
      lng: -84.5160,
      cuisine: "Tacos & Whiskey",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the Vine Street patio in Over-the-Rhine. Creative tacos and an extensive whiskey selection.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bakersfieldtacos.com",
    },
    {
      name: "Senate",
      address: "1212 Vine St, Cincinnati, OH 45202",
      lat: 39.1090,
      lng: -84.5160,
      cuisine: "Gourmet Hot Dogs & Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Elevated hot dogs and craft cocktails in OTR.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.senatecincy.com",
    },
    {
      name: "Madtree Brewing",
      address: "3301 Madison Rd, Cincinnati, OH 45209",
      lat: 39.1550,
      lng: -84.4380,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome in the expansive outdoor beer garden. One of Cincinnati's largest breweries in Oakley.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.madtreebrewing.com",
    },
    {
      name: "Keystone Bar & Grill",
      address: "4101 Hamilton Ave, Cincinnati, OH 45223",
      lat: 39.1530,
      lng: -84.5510,
      cuisine: "American Bar & Grill",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the Northside patio. A neighborhood bar with great burgers and a welcoming vibe.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.keystonebarandgrill.com",
    },
  ],
  cafes: [
    {
      name: "Deeper Roots Coffee",
      address: "1814 Race St, Cincinnati, OH 45202",
      lat: 39.1140,
      lng: -84.5170,
      dogPolicy: "Dogs welcome on the outdoor patio. Cincinnati's acclaimed specialty roaster in Over-the-Rhine.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.deeperrootscoffee.com",
    },
    {
      name: "Coffee Emporium",
      address: "110 E Central Pkwy, Cincinnati, OH 45202",
      lat: 39.1060,
      lng: -84.5130,
      dogPolicy: "Dogs welcome at the outdoor tables downtown. A Cincinnati institution roasting coffee since 1981.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.coffeeemporium.com",
    },
    {
      name: "Collective Espresso",
      address: "207 Woodward St, Cincinnati, OH 45202",
      lat: 39.1070,
      lng: -84.5110,
      dogPolicy: "Dog-friendly outdoor seating. A precision espresso bar and OTR gathering spot.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.collectiveespresso.com",
    },
    {
      name: "Carabello Coffee",
      address: "107 E 9th St, Newport, KY 41071",
      lat: 39.0910,
      lng: -84.4960,
      dogPolicy: "Dogs welcome on the outdoor patio. A mission-driven roaster just across the river in Newport, KY.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.carabellocoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Washington Park Dog Park",
      address: "1230 Elm St, Cincinnati, OH 45202",
      lat: 39.1100,
      lng: -84.5200,
      offLeash: true,
      fenced: true,
      acres: 1,
      amenities: ["Double-gated entry", "Water fountain", "Benches", "Turf surface", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "A popular urban dog park in the heart of Over-the-Rhine, right next to Music Hall. The compact fenced area is the social hub for OTR's dog-loving community.",
    },
    {
      name: "Otto Armleder Dog Park",
      address: "5057 Wooster Pike, Cincinnati, OH 45226",
      lat: 39.0810,
      lng: -84.4340,
      offLeash: true,
      fenced: true,
      acres: 5,
      amenities: ["Separate small dog area", "Water stations", "Creek access", "Benches", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "One of Cincinnati's best dog parks with five acres of fenced off-leash space and creek access for dogs who love water. The separate small dog area and abundant shade make it comfortable for all.",
    },
    {
      name: "Mt. Airy Dog Park",
      address: "5083 Colerain Ave, Cincinnati, OH 45223",
      lat: 39.1690,
      lng: -84.5610,
      offLeash: true,
      fenced: true,
      acres: 4,
      amenities: ["Wooded setting", "Water stations", "Benches", "Natural terrain", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "Set within Cincinnati's largest park, Mt. Airy Dog Park offers a wooded setting for off-leash play. The natural terrain and mature trees create a forest-like atmosphere for adventurous dogs.",
    },
    {
      name: "Kellogg Park Dog Area",
      address: "7075 Kellogg Ave, Cincinnati, OH 45228",
      lat: 39.0720,
      lng: -84.3960,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Ohio River views", "Open fields", "Water stations", "Benches", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      description: "A scenic dog park along the Ohio River in eastern Cincinnati. Dogs enjoy the off-leash freedom with river views and breezes from this well-maintained east-side park.",
    },
  ],
};
