export const codyData = {
  city: {
    name: "Cody",
    state: "Wyoming",
    region: "Mountain West",
    lat: 44.5263,
    lng: -109.0565,
    dogFriendlinessScore: 7,
    description:
      "Cody is the gateway to Yellowstone's east entrance and a quintessential Western town founded by Buffalo Bill. While Yellowstone itself restricts dogs, the Shoshone National Forest and Absaroka Range surrounding Cody offer spectacular dog-friendly trails. The town's Western heritage, nightly rodeos, and friendly locals make it a memorable stop.",
    heroImage: "https://images.unsplash.com/photo-1508389377389-918442e3626b?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 10014,
  },

  hotels: [
    {
      name: "Chamberlin Inn",
      address: "1032 12th St, Cody, WY 82414",
      lat: 44.5240,
      lng: -109.0560,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in the cottage suites with private patios. Historic boutique inn with courtyard gardens.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Private patio", "Dog bed", "Water bowls", "Garden walks", "Downtown location"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.chamberlininn.com",
      phone: "(307) 587-0202",
    },
    {
      name: "Best Western Premier Ivy Inn & Suites",
      address: "1800 8th St, Cody, WY 82414",
      lat: 44.5250,
      lng: -109.0640,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 80 lbs welcome with a per-night pet fee. Modern hotel near downtown.",
      maxDogWeight: 80,
      petFee: 25,
      amenities: ["Pet waste stations", "Grassy areas", "Water bowls", "Near walking paths"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(307) 587-2572",
    },
    {
      name: "Cody Cowboy Village",
      address: "203 W Yellowstone Ave, Cody, WY 82414",
      lat: 44.5270,
      lng: -109.0580,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select log cabins with a pet fee. Western-themed cabin resort.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Private cabin porches", "Grassy areas", "Water bowls", "BBQ grills", "Parking"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.codycowboyvillage.com",
      phone: "(307) 587-7555",
    },
    {
      name: "AmericInn by Wyndham Cody",
      address: "508 Yellowstone Ave, Cody, WY 82414",
      lat: 44.5265,
      lng: -109.0540,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome with a modest pet fee. Comfortable budget option near the rodeo.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Pet waste stations", "Grassy exercise area", "Water bowls at front desk"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/americinn",
      phone: "(307) 587-7716",
    },
  ],

  nationalParks: [
    {
      name: "Shoshone National Forest",
      state: "Wyoming",
      lat: 44.5000,
      lng: -109.3000,
      dogPolicy: "Dogs welcome on all trails. Voice control in backcountry; leash in developed areas.",
      dogTrails: ["Blackwater Creek Trail", "Elk Fork Trail", "Dead Indian Trail", "Clarks Fork Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on trails",
        "Be aware of grizzly bears in all areas",
        "Bear spray recommended",
      ],
      description:
        "America's first national forest surrounds Cody with dramatic mountain scenery, deep canyons, and abundant wildlife. The trails through the Absaroka Range offer some of the most spectacular and wild hiking in the lower 48 states.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/shoshone",
    },
    {
      name: "Buffalo Bill State Park",
      state: "Wyoming",
      lat: 44.4900,
      lng: -109.1800,
      dogPolicy: "Leashed dogs welcome on trails and in the campground. Scenic reservoir in the Shoshone Canyon.",
      dogTrails: ["Bartlett Lane Trail", "Lakeside Trail", "Reservoir shoreline walks"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed on swim beaches",
        "Clean up after your pet",
      ],
      description:
        "A state park on the Buffalo Bill Reservoir between the dramatic Shoshone Canyon walls. Leashed dogs enjoy the trails and shoreline walks with views of the Absaroka Mountains and the dam.",
      imageUrl: "",
      website: "https://wyoparks.wyo.gov/index.php/places-to-go/buffalo-bill",
    },
    {
      name: "Yellowstone National Park (East Entrance)",
      state: "Wyoming",
      lat: 44.4900,
      lng: -110.0000,
      dogPolicy: "Dogs NOT allowed on trails or in the backcountry. Permitted in parking areas, campgrounds, and within 100 feet of roads only.",
      dogTrails: ["No dog-friendly trails"],
      restrictions: [
        "No dogs on any trails",
        "Must be on leash (6 ft max) at all times",
        "Allowed only in parking areas and campgrounds",
        "Not allowed on boardwalks or thermal features",
      ],
      description:
        "The east entrance to Yellowstone is 52 miles from Cody via the scenic Buffalo Bill Cody Scenic Byway. While dog access is extremely limited inside the park, the drive through the canyon is spectacular and worth doing even with pups in the car.",
      imageUrl: "",
      website: "https://www.nps.gov/yell",
    },
  ],

  restaurants: [
    {
      name: "Pat O'Hara Brewing Company",
      address: "1244 Sheridan Ave, Cody, WY 82414",
      lat: 44.5245,
      lng: -109.0540,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Craft brewery named after a local mountain peak.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.patoharabrewing.com",
    },
    {
      name: "The Local",
      address: "1134 13th St, Cody, WY 82414",
      lat: 44.5238,
      lng: -109.0550,
      cuisine: "Farm-to-Table American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Locally sourced seasonal cuisine with Wyoming beef and game.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thelocalcody.com",
    },
    {
      name: "Wyoming's Rib & Chop House",
      address: "1367 Sheridan Ave, Cody, WY 82414",
      lat: 44.5248,
      lng: -109.0520,
      cuisine: "Steakhouse",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the covered patio. Premium Wyoming steaks and ribs.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ribandchophouse.com",
    },
    {
      name: "Cody Cattle Company",
      address: "1910 Demaris Dr, Cody, WY 82414",
      lat: 44.5300,
      lng: -109.0620,
      cuisine: "Western BBQ & Dinner Show",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at the outdoor chuck wagon tables. Western dinner show with live music.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.codycattlecompany.com",
    },
    {
      name: "Zapata's Mexican Restaurant",
      address: "1362 Sheridan Ave, Cody, WY 82414",
      lat: 44.5247,
      lng: -109.0522,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables on Sheridan Avenue. Authentic Mexican fare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.zapatascody.com",
    },
  ],

  cafes: [
    {
      name: "Beta Coffeehouse",
      address: "1132 12th St, Cody, WY 82414",
      lat: 44.5242,
      lng: -109.0555,
      dogPolicy: "Dogs welcome on the patio. Artisan coffee and community gathering spot in downtown Cody.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.betacoffeehouse.com",
    },
    {
      name: "Rawhide Coffee Company",
      address: "1202 Sheridan Ave, Cody, WY 82414",
      lat: 44.5244,
      lng: -109.0545,
      dogPolicy: "Outdoor seating welcomes dogs. Western-themed coffee shop on the main drag.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.rawhidecoffee.com",
    },
    {
      name: "Cody Coffee Co. & Eatery",
      address: "1502 Sheridan Ave, Cody, WY 82414",
      lat: 44.5250,
      lng: -109.0510,
      dogPolicy: "Dog-friendly patio seating. Full breakfast and lunch menu with specialty coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.codycoffeeco.com",
    },
    {
      name: "Juniper Mountain Coffee",
      address: "1240 Sheridan Ave, Cody, WY 82414",
      lat: 44.5245,
      lng: -109.0542,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Small-batch roaster with Yellowstone-country flair.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.junipermountaincoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Cody Dog Park",
      address: "City Park, Cody, WY 82414",
      lat: 44.5230,
      lng: -109.0600,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Water station", "Waste bags", "Benches", "Mountain views"],
      rating: 4.2,
      imageUrl: "",
      description:
        "Cody's fenced off-leash dog park adjacent to the city park. Surrounded by mountain views and offering a safe space for dogs to run and play. A friendly community spot in this welcoming Western town.",
    },
    {
      name: "Beck Lake Park",
      address: "Beck Lake Rd, Cody, WY 82414",
      lat: 44.5200,
      lng: -109.0480,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Lake trail", "Fishing", "Picnic areas", "Wildlife viewing", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A peaceful lake park on the edge of Cody with a walking trail around the lake. Leashed dogs enjoy the gentle terrain, waterfowl watching, and views of the Absaroka Mountains.",
    },
    {
      name: "Paul Stock Nature Trail",
      address: "Nature Trail Rd, Cody, WY 82414",
      lat: 44.5180,
      lng: -109.0700,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Nature trail", "Shoshone River access", "Wildlife viewing", "Interpretive signs", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A scenic nature trail along the Shoshone River with cottonwood groves and mountain views. Leashed dogs love the river access and the chance to explore this wildlife-rich riparian corridor on the edge of town.",
    },
    {
      name: "Shoshone Riverway Trail",
      address: "Sheridan Ave, Cody, WY 82414",
      lat: 44.5260,
      lng: -109.0580,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Paved trail", "River views", "Benches", "Waste stations", "Multiple access points"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A paved path following the Shoshone River through Cody connecting parks and neighborhoods. Leashed dogs enjoy the easy walking, river views, and the connection between downtown and the parks.",
    },
  ],
};
