export const coeurDAleneData = {
  city: {
    name: "Coeur d'Alene",
    state: "Idaho",
    region: "Pacific Northwest",
    lat: 47.6777,
    lng: -116.7805,
    dogFriendlinessScore: 8,
    description:
      "Coeur d'Alene sits on the shores of one of the most beautiful lakes in America, and dogs are welcome to enjoy nearly every bit of it. The lakeside promenade, extensive trail system, and dog-friendly patios downtown make this a top-tier destination for active pups. Surrounded by national forests, the outdoor recreation options are endless.",
    heroImage: "https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=1200&fit=crop",
    climate: "Humid continental",
    population: 54628,
  },

  hotels: [
    {
      name: "The Coeur d'Alene Resort",
      address: "115 S 2nd St, Coeur d'Alene, ID 83814",
      lat: 47.6740,
      lng: -116.7800,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in select lakeside rooms with advance notice. Premier resort on Lake Coeur d'Alene.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Lakeside walking path", "Water bowls", "Concierge pet services"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.cdaresort.com",
      phone: "(208) 765-4000",
    },
    {
      name: "Best Western Plus Coeur d'Alene Inn",
      address: "506 W Appleway Ave, Coeur d'Alene, ID 83814",
      lat: 47.6850,
      lng: -116.7870,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a per-night pet fee. Comfortable rooms with easy access to trails and downtown.",
      maxDogWeight: 80,
      petFee: 25,
      amenities: ["Pet waste stations", "Grassy areas", "Water bowls", "Near Centennial Trail"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(208) 765-3200",
    },
    {
      name: "The Roosevelt Inn",
      address: "105 E Wallace Ave, Coeur d'Alene, ID 83814",
      lat: 47.6770,
      lng: -116.7790,
      priceRange: "$$$" as const,
      dogPolicy: "Small dogs welcome in the Carriage House suite. Historic schoolhouse turned B&B near downtown.",
      maxDogWeight: 30,
      petFee: 40,
      amenities: ["Dog bed", "Treats", "Garden walking area", "Downtown location"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.therooseveltinn.com",
      phone: "(208) 765-5200",
    },
    {
      name: "SpringHill Suites by Marriott",
      address: "2250 W Seltice Way, Coeur d'Alene, ID 83814",
      lat: 47.6810,
      lng: -116.8060,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a non-refundable pet fee. Modern suites near the Centennial Trail.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Grassy exercise area", "Near Centennial Trail", "Pet waste stations", "Water bowls at front desk"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(208) 667-2212",
    },
  ],

  nationalParks: [
    {
      name: "Coeur d'Alene National Forest",
      state: "Idaho",
      lat: 47.5500,
      lng: -116.5000,
      dogPolicy: "Dogs welcome on all trails. Leash required in developed areas; voice control acceptable in backcountry.",
      dogTrails: ["Mineral Ridge Trail", "Independence Creek Trail", "Canfield Mountain Trail System", "English Point Trail"],
      restrictions: [
        "Leash required in campgrounds and trailheads",
        "Voice control in backcountry",
        "Not allowed in developed swimming areas",
      ],
      description:
        "The national forest surrounding Lake Coeur d'Alene offers hundreds of miles of trails through dense forests, along ridgelines with panoramic lake views, and through mountain meadows. The Mineral Ridge Trail is a particular favorite for dogs and their owners.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/ipnf",
    },
    {
      name: "Heyburn State Park",
      address: "Plummer, ID 83851",
      state: "Idaho",
      lat: 47.3520,
      lng: -116.7830,
      dogPolicy: "Leashed dogs welcome on all trails and in campground areas. Idaho's oldest state park.",
      dogTrails: ["Indian Cliffs Trail", "Plummer Creek Trail", "Lakeshore Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed on designated swimming beaches",
        "Clean up after your pet",
      ],
      description:
        "Idaho's oldest state park sits on the shores of Chatcolet Lake and offers forested trails, lakeside paths, and abundant wildlife viewing. The varied terrain and water access make it a great dog-friendly day trip from Coeur d'Alene.",
      imageUrl: "",
      website: "https://parksandrecreation.idaho.gov/parks/heyburn",
    },
    {
      name: "Tubbs Hill Natural Area",
      state: "Idaho",
      lat: 47.6710,
      lng: -116.7760,
      dogPolicy: "Leashed dogs welcome on the trail. A beloved natural area right in downtown Coeur d'Alene.",
      dogTrails: ["Tubbs Hill Loop Trail", "Summit Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Stay on designated trails",
        "No dogs on beaches during summer",
      ],
      description:
        "This 120-acre natural area in the heart of Coeur d'Alene offers a 2-mile loop trail with stunning lake views, rocky beaches, and old-growth ponderosa pines. It is the most popular dog walk in town and an absolute must-do.",
      imageUrl: "",
      website: "https://www.cdaid.org",
    },
  ],

  restaurants: [
    {
      name: "Dockside Restaurant",
      address: "115 S 2nd St, Coeur d'Alene, ID 83814",
      lat: 47.6738,
      lng: -116.7798,
      cuisine: "Seafood & American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the lakeside patio with water and shade. Stunning lake views with fresh seafood.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cdaresort.com/dine/dockside",
    },
    {
      name: "Bardenay Restaurant & Distillery",
      address: "1501 Sherman Ave, Coeur d'Alene, ID 83814",
      lat: 47.6768,
      lng: -116.7818,
      cuisine: "American & Craft Cocktails",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Craft distillery with house-made spirits and hearty American fare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bardenay.com",
    },
    {
      name: "Crafted Tap House + Kitchen",
      address: "523 Sherman Ave, Coeur d'Alene, ID 83814",
      lat: 47.6760,
      lng: -116.7835,
      cuisine: "Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio with water bowls. Extensive craft beer selection and upscale pub food.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.craftedtaphouse.com",
    },
    {
      name: "Taco Bus",
      address: "901 Sherman Ave, Coeur d'Alene, ID 83814",
      lat: 47.6765,
      lng: -116.7825,
      cuisine: "Mexican Street Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at all outdoor tables. Authentic street tacos from a converted bus.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.tacobuscda.com",
    },
    {
      name: "Fire Artisan Pizza",
      address: "1016 N 4th St, Coeur d'Alene, ID 83814",
      lat: 47.6790,
      lng: -116.7770,
      cuisine: "Pizza & Italian",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Wood-fired artisan pizzas with local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.fireartisanpizza.com",
    },
  ],

  cafes: [
    {
      name: "Evans Brothers Coffee",
      address: "524 Sherman Ave, Coeur d'Alene, ID 83814",
      lat: 47.6762,
      lng: -116.7836,
      dogPolicy: "Dogs welcome on the outdoor patio. Local favorite for specialty coffee and pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.evansbrotherscoffee.com",
    },
    {
      name: "Vault Coffee",
      address: "315 Sherman Ave, Coeur d'Alene, ID 83814",
      lat: 47.6758,
      lng: -116.7845,
      dogPolicy: "Outdoor seating welcomes dogs. Third-wave coffee in a historic downtown building.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.vaultcoffee.com",
    },
    {
      name: "The Culinary Stone",
      address: "2129 N Main St, Coeur d'Alene, ID 83814",
      lat: 47.6820,
      lng: -116.7780,
      dogPolicy: "Dog-friendly patio area. Bakery and cafe featuring artisan breads and gourmet coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.theculinarystone.com",
    },
    {
      name: "Calypso's Coffee & Creamery",
      address: "516 Sherman Ave, Coeur d'Alene, ID 83814",
      lat: 47.6761,
      lng: -116.7837,
      dogPolicy: "Leashed dogs welcome outside. Coffee, ice cream, and dog-friendly frozen treats available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.calypsosmenu.com",
    },
  ],

  dogParks: [
    {
      name: "Coeur d'Alene Dog Park",
      address: "1515 N 15th St, Coeur d'Alene, ID 83814",
      lat: 47.6850,
      lng: -116.7680,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water stations", "Agility equipment", "Benches", "Shade structures", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Coeur d'Alene's premier off-leash dog park with separate areas for large and small dogs, agility equipment, and plenty of space to run. Well-maintained with an active community of dog owners.",
    },
    {
      name: "Centennial Trail Waterfront",
      address: "Centennial Trail, Coeur d'Alene, ID 83814",
      lat: 47.6735,
      lng: -116.7830,
      offLeash: false,
      fenced: false,
      acres: 25.0,
      amenities: ["Paved trail", "Lake views", "Benches", "Water fountains", "Waste stations", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "The Centennial Trail runs 23 miles from Coeur d'Alene to the Washington border along the lake and Spokane River. The waterfront section through town offers stunning lake views and is the most popular dog walking route in the city.",
    },
    {
      name: "McEuen Park",
      address: "501 E Front Ave, Coeur d'Alene, ID 83814",
      lat: 47.6745,
      lng: -116.7775,
      offLeash: false,
      fenced: false,
      acres: 12.0,
      amenities: ["Lakefront paths", "Open lawns", "Playground", "Splash pad", "Waste stations", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A beautifully redeveloped lakefront park in downtown Coeur d'Alene with paths, lawns, and direct lake access. Leashed dogs enjoy the open space and the promenade along the waterfront.",
    },
    {
      name: "Canfield Mountain Trail System",
      address: "Canfield Mountain Trailhead, Coeur d'Alene, ID 83815",
      lat: 47.7050,
      lng: -116.7650,
      offLeash: true,
      fenced: false,
      acres: 200.0,
      amenities: ["Mountain trails", "Forest setting", "Mountain views", "Parking", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "An extensive trail network on the mountain above Coeur d'Alene with forested singletrack, meadows, and panoramic views of the lake. Dogs can run off-leash under voice control on these popular hiking and biking trails.",
    },
  ],
};
