export const columbusData = {
  city: {
    name: "Columbus",
    state: "Ohio",
    region: "Midwest",
    lat: 39.9612,
    lng: -82.9988,
    dogFriendlinessScore: 7,
    description:
      "Ohio's capital surprises with its vibrant dog culture, from the beloved Short North arts district patios to sprawling metro parks. Columbus boasts one of the best park systems in the Midwest with dedicated dog parks in nearly every neighborhood, plus a thriving brewery scene that welcomes pups.",
    heroImage: "https://images.unsplash.com/photo-1564594736624-def7a10ab047?w=1200&fit=crop",
    climate: "Humid continental",
    population: 905748,
  },
  hotels: [
    {
      name: "Graduate Columbus",
      address: "750 N High St, Columbus, OH 43215",
      lat: 39.9770,
      lng: -83.0030,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome with a one-time pet fee. An OSU-themed boutique hotel in the Short North.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Treats", "Waste bags", "Walking route suggestions"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.graduatehotels.com/columbus",
      phone: "(614) 299-5050",
    },
    {
      name: "Hotel LeVeque",
      address: "50 W Broad St, Columbus, OH 43215",
      lat: 39.9616,
      lng: -83.0010,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a non-refundable pet fee. An Art Deco gem in the historic LeVeque Tower.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking map", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelleveque.com",
      phone: "(614) 220-5100",
    },
    {
      name: "Canopy by Hilton Columbus Short North",
      address: "77 E Nationwide Blvd, Columbus, OH 43215",
      lat: 39.9700,
      lng: -82.9990,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a per-stay fee. A modern hotel between the Arena District and Short North.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Short North access", "Waste bags", "Pet amenity kit"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hilton.com/en/hotels/cmhcnpy",
      phone: "(614) 223-1400",
    },
    {
      name: "Aloft Columbus Westerville",
      address: "8192 Carters Commerce Dr, Westerville, OH 43081",
      lat: 40.0880,
      lng: -82.8770,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome at no extra charge. Aloft's pet-forward Arf program in the north suburbs.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Pet toys", "Waste bags", "Treats at front desk"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.marriott.com/hotels/travel/cmhal",
      phone: "(614) 839-8800",
    },
  ],
  nationalParks: [
    {
      name: "Cuyahoga Valley National Park",
      state: "Ohio",
      lat: 41.2808,
      lng: -81.5678,
      dogPolicy: "Dogs welcome on the Towpath Trail and several other trails on a 6-foot leash. Not permitted on Brandywine Falls boardwalk.",
      dogTrails: ["Ohio & Erie Canal Towpath Trail", "Stanford Trail", "Buckeye Trail sections", "Old Carriage Trail"],
      restrictions: ["6-foot leash required", "Not on Brandywine Falls boardwalk", "Not in buildings", "Must clean up after pet"],
      description: "About two hours north of Columbus, Ohio's only national park protects a lush river valley with waterfalls, forests, and the historic Ohio & Erie Canal. Dogs enjoy the flat Towpath Trail along the canal.",
      imageUrl: "",
      website: "https://www.nps.gov/cuva",
    },
    {
      name: "Hocking Hills State Park",
      state: "Ohio",
      lat: 39.4350,
      lng: -82.5380,
      dogPolicy: "Dogs welcome on most trails on a 6-foot leash. Spectacular caves, waterfalls, and sandstone formations.",
      dogTrails: ["Old Man's Cave Trail", "Cedar Falls Trail", "Ash Cave Trail", "Conkle's Hollow Rim Trail"],
      restrictions: ["6-foot leash required", "Not in caves", "Must clean up after pet", "Some areas slippery"],
      description: "About an hour south of Columbus, Hocking Hills features dramatic sandstone gorges, caves, and waterfalls. Dogs can hike most of the trails through this stunning landscape of hemlock forests and rock formations.",
      imageUrl: "",
      website: "https://www.hockinghills.com",
    },
    {
      name: "Columbus Metro Parks - Highbanks",
      state: "Ohio",
      lat: 40.1480,
      lng: -83.0230,
      dogPolicy: "Dogs welcome on all trails on a 6-foot leash. Part of the excellent Columbus Metro Parks system.",
      dogTrails: ["Dripping Rock Trail", "Overlook Trail", "Big Meadows Trail", "Wetland Spur Trail"],
      restrictions: ["6-foot leash required", "Not in nature center", "Must clean up after pet"],
      description: "Highbanks Metro Park features scenic bluffs overlooking the Olentangy River, ancient earthworks, and diverse habitats. Dogs enjoy the forested trails and river overlooks just 20 minutes from downtown Columbus.",
      imageUrl: "",
      website: "https://www.metroparks.net/parks-trails/highbanks",
    },
  ],
  restaurants: [
    {
      name: "North Market",
      address: "59 Spruce St, Columbus, OH 43215",
      lat: 39.9710,
      lng: -83.0040,
      cuisine: "Food Hall",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the outdoor market area. Columbus's historic public market with dozens of local food vendors.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.northmarket.org",
    },
    {
      name: "Seventh Son Brewing Co.",
      address: "1101 N 4th St, Columbus, OH 43201",
      lat: 39.9850,
      lng: -82.9960,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome in the outdoor beer garden. An Italian Village craft brewery with creative seasonal beers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.seventhsonbrewing.com",
    },
    {
      name: "The Pearl",
      address: "641 N High St, Columbus, OH 43215",
      lat: 39.9750,
      lng: -83.0030,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the Short North patio. Upscale-casual American fare with a lively bar scene.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thepearlcolumbus.com",
    },
    {
      name: "Hot Chicken Takeover",
      address: "59 Spruce St, Columbus, OH 43215",
      lat: 39.9710,
      lng: -83.0035,
      cuisine: "Nashville Hot Chicken",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor seating near North Market. Columbus's beloved hot chicken with a social mission.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hotchickentakeover.com",
    },
    {
      name: "Northstar Cafe",
      address: "951 N High St, Columbus, OH 43201",
      lat: 39.9820,
      lng: -83.0020,
      cuisine: "Farm-to-Table Vegetarian-Friendly",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the Short North patio. Seasonal, health-conscious fare using locally sourced ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thenorthstarcafe.com",
    },
  ],
  cafes: [
    {
      name: "Fox in the Snow Cafe",
      address: "1031 N 4th St, Columbus, OH 43201",
      lat: 39.9840,
      lng: -82.9960,
      dogPolicy: "Dogs welcome on the outdoor patio. A wildly popular bakery-cafe known for flaky pastries and excellent coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.foxinthesnow.com",
    },
    {
      name: "One Line Coffee",
      address: "648 N High St, Columbus, OH 43215",
      lat: 39.9760,
      lng: -83.0030,
      dogPolicy: "Dogs welcome at the outdoor tables in the Short North. A specialty coffee shop with a focus on sourcing.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.onelinecoffee.com",
    },
    {
      name: "Brioso Coffee",
      address: "61 E Gay St, Columbus, OH 43215",
      lat: 39.9630,
      lng: -82.9990,
      dogPolicy: "Dogs welcome at the sidewalk tables downtown. Columbus's first specialty coffee roaster since 1994.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.briosocoffee.com",
    },
    {
      name: "Stauf's Coffee Roasters",
      address: "1277 Grandview Ave, Columbus, OH 43212",
      lat: 39.9840,
      lng: -83.0340,
      dogPolicy: "Dog-friendly outdoor seating in Grandview Heights. A Columbus institution with house-roasted coffee since 1988.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.staufs.com",
    },
  ],
  dogParks: [
    {
      name: "Scioto Audubon Metro Park Dog Park",
      address: "400 W Whittier St, Columbus, OH 43215",
      lat: 39.9390,
      lng: -83.0140,
      offLeash: true,
      fenced: true,
      acres: 6,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade structures", "Climbing wall views"],
      rating: 4.6,
      imageUrl: "",
      description: "One of Columbus's best dog parks, set within the Scioto Audubon Metro Park with views of the downtown skyline. The large fenced area includes separate sections and is adjacent to a climbing wall and nature trails.",
    },
    {
      name: "Godown Dog Park",
      address: "1675 Godown Rd, Columbus, OH 43235",
      lat: 40.0740,
      lng: -83.0500,
      offLeash: true,
      fenced: true,
      acres: 4,
      amenities: ["Separate small dog area", "Water fountains", "Benches", "Shade trees", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "A popular north Columbus dog park with a large fenced area and separate small dog section. Well-maintained with good shade coverage and an active community of regulars.",
    },
    {
      name: "Wheeler Dog Park",
      address: "725 Thurber Dr W, Columbus, OH 43215",
      lat: 39.9650,
      lng: -83.0200,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Double-gated entry", "Benches", "Water fountain", "Waste bag stations"],
      rating: 4.2,
      imageUrl: "",
      description: "A convenient in-town dog park in the Victorian Village neighborhood. The compact fenced area provides off-leash fun within walking distance of the Short North district.",
    },
    {
      name: "Three Creeks Metro Park Dog Area",
      address: "3860 Bixby Rd, Groveport, OH 43125",
      lat: 39.8700,
      lng: -82.8920,
      offLeash: true,
      fenced: true,
      acres: 5,
      amenities: ["Creek access", "Open fields", "Water stations", "Benches", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "A spacious off-leash area within the Three Creeks Metro Park where three creeks converge. Dogs love the creek access for wading and the large open fields for running.",
    },
  ],
};
