export const crestedButteData = {
  city: {
    name: "Crested Butte",
    state: "Colorado",
    region: "Mountain West",
    lat: 38.8697,
    lng: -106.9878,
    dogFriendlinessScore: 9,
    description:
      "Crested Butte is the wildflower capital of Colorado and one of the most dog-friendly mountain towns anywhere. The colorful Victorian downtown is walkable and welcoming to pups, while the surrounding Gunnison National Forest offers trails through stunning alpine meadows. Dogs are everywhere here and truly part of the community fabric.",
    heroImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&fit=crop",
    climate: "Subarctic continental",
    population: 1740,
  },

  hotels: [
    {
      name: "The Grand Lodge Crested Butte",
      address: "6 Emmons Rd, Crested Butte, CO 81225",
      lat: 38.8988,
      lng: -106.9660,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms at the ski area base. Full-service lodge with mountain access.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Trail access", "Grassy areas", "Mountain views"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.grandlodgecrestedbutte.com",
      phone: "(970) 349-8000",
    },
    {
      name: "Elk Mountain Lodge",
      address: "129 Gothic Ave, Crested Butte, CO 81224",
      lat: 38.8700,
      lng: -106.9870,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a modest pet fee. Historic lodge in the heart of downtown.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Dog bed", "Treats", "Walking distance to trails", "Downtown location", "Water bowls"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.elkmountainlodge.com",
      phone: "(970) 349-7533",
    },
    {
      name: "Old Town Inn",
      address: "708 6th St, Crested Butte, CO 81224",
      lat: 38.8690,
      lng: -106.9880,
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome with advance notice. Budget-friendly option walking distance to Elk Avenue.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Pet waste stations", "Near town trail", "Grassy areas", "Water bowls at front desk"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.oldtowninn.com",
      phone: "(970) 349-6184",
    },
    {
      name: "Cristiana Guesthaus",
      address: "621 Maroon Ave, Crested Butte, CO 81224",
      lat: 38.8695,
      lng: -106.9865,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in ground-floor rooms with garden access. Charming European-style guesthouse.",
      maxDogWeight: 60,
      petFee: 30,
      amenities: ["Garden access", "Dog bed", "Water bowls", "Walking map", "Near trailheads"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cristianaguesthaus.com",
      phone: "(970) 349-5326",
    },
  ],

  nationalParks: [
    {
      name: "Gunnison National Forest",
      state: "Colorado",
      lat: 38.8500,
      lng: -107.0500,
      dogPolicy: "Dogs welcome on all trails. Voice control in backcountry; leash in developed areas.",
      dogTrails: ["Lower Loop Trail", "Upper Loop Trail", "Snodgrass Mountain Trail", "Gothic Road Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on trails",
        "Not allowed in developed swim areas",
      ],
      description:
        "The national forest surrounding Crested Butte is a hiking paradise with wildflower meadows, alpine lakes, and mountain peaks. The trail system right from town connects to hundreds of miles of backcountry paths.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/gmug",
    },
    {
      name: "Maroon Bells-Snowmass Wilderness (Crested Butte Side)",
      state: "Colorado",
      lat: 39.0000,
      lng: -107.0500,
      dogPolicy: "Leashed dogs welcome on wilderness trails. Access the wilderness from the Crested Butte side for fewer crowds.",
      dogTrails: ["West Maroon Pass Trail", "East Maroon Trail", "Copper Creek Trail"],
      restrictions: [
        "Must be on leash in wilderness",
        "Stay on designated trails",
        "High altitude - acclimatize dogs gradually",
      ],
      description:
        "The Crested Butte approach to the Maroon Bells wilderness offers spectacular passes and alpine meadows. The West Maroon Pass trail is one of Colorado's most beautiful hikes, crossing a 12,500-foot pass between wildflower-filled basins.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/whiteriver",
    },
    {
      name: "Curecanti National Recreation Area",
      state: "Colorado",
      lat: 38.4600,
      lng: -107.3300,
      dogPolicy: "Leashed dogs welcome on trails and in campgrounds. Beautiful reservoir system in a canyon setting.",
      dogTrails: ["Neversink Trail", "Dillon Pinnacles Trail", "Hermits Rest Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed on swim beaches",
        "Not allowed on boat tours",
      ],
      description:
        "About an hour south of Crested Butte, this recreation area features three reservoirs in dramatic canyon scenery. The Dillon Pinnacles Trail offers unique geological formations and leashed dogs enjoy the varied lakeside and canyon hikes.",
      imageUrl: "",
      website: "https://www.nps.gov/cure",
    },
  ],

  restaurants: [
    {
      name: "The Brick Oven",
      address: "229 Elk Ave, Crested Butte, CO 81224",
      lat: 38.8697,
      lng: -106.9875,
      cuisine: "Pizza & Italian",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the sidewalk patio along Elk Avenue. Wood-fired pizza in a historic building.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.brickovencb.com",
    },
    {
      name: "Secret Stash",
      address: "21 Elk Ave, Crested Butte, CO 81224",
      lat: 38.8698,
      lng: -106.9895,
      cuisine: "Creative Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio area. Unique pizza creations in an eclectic Victorian house.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.secretstash.com",
    },
    {
      name: "Bonez Tequila Bar & Grill",
      address: "127 Elk Ave, Crested Butte, CO 81224",
      lat: 38.8698,
      lng: -106.9885,
      cuisine: "Mexican & Tequila Bar",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the lively outdoor patio. Great tacos and a massive tequila selection.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bonezcb.com",
    },
    {
      name: "Soupcon",
      address: "127A Elk Ave, Crested Butte, CO 81224",
      lat: 38.8697,
      lng: -106.9884,
      cuisine: "French Fine Dining",
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome on the intimate outdoor patio during summer. French-inspired fine dining in a log cabin.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.soupconcb.com",
    },
    {
      name: "The Last Steep",
      address: "208 Elk Ave, Crested Butte, CO 81224",
      lat: 38.8697,
      lng: -106.9878,
      cuisine: "Pub & Bar Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the deck. Classic mountain town bar with burgers and cold beer.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.thelaststeepcb.com",
    },
  ],

  cafes: [
    {
      name: "Camp 4 Coffee Roasters",
      address: "402 Elk Ave, Crested Butte, CO 81224",
      lat: 38.8698,
      lng: -106.9860,
      dogPolicy: "Dogs welcome on the outdoor patio. Locally roasted specialty coffee in a mountain town vibe.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.camp4coffee.com",
    },
    {
      name: "Izzy's",
      address: "218 Maroon Ave, Crested Butte, CO 81224",
      lat: 38.8693,
      lng: -106.9875,
      dogPolicy: "Outdoor seating welcomes dogs. Breakfast burritos, coffee, and a friendly morning atmosphere.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.izzyscb.com",
    },
    {
      name: "Third Bowl Homemade Ice Cream",
      address: "307 Elk Ave, Crested Butte, CO 81224",
      lat: 38.8698,
      lng: -106.9870,
      dogPolicy: "Dog-friendly patio. Handmade ice cream with a special doggy cup available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thirdbowl.com",
    },
    {
      name: "Rumors Coffee & Tea House",
      address: "412 Elk Ave, Crested Butte, CO 81224",
      lat: 38.8698,
      lng: -106.9858,
      dogPolicy: "Leashed dogs welcome at patio tables. Cozy coffee house with teas, pastries, and free WiFi.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.rumorscb.com",
    },
  ],

  dogParks: [
    {
      name: "Crested Butte Dog Park",
      address: "2nd St & Whiterock Ave, Crested Butte, CO 81224",
      lat: 38.8680,
      lng: -106.9850,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Water station", "Waste bags", "Benches", "Mountain views"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Crested Butte's fenced off-leash dog park with views of the ski mountain. A friendly community gathering spot where local and visiting dogs play together.",
    },
    {
      name: "Town Trail / Lower Loop",
      address: "Lower Loop Trailhead, Crested Butte, CO 81224",
      lat: 38.8720,
      lng: -106.9830,
      offLeash: true,
      fenced: false,
      acres: 25.0,
      amenities: ["Paved and dirt trails", "Meadow views", "Creek access", "Wildflowers", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "The Lower Loop Trail circles the town through wildflower meadows and along the Slate River. Dogs can be off-leash under voice control and the gentle, scenic trail is accessible to all fitness levels.",
    },
    {
      name: "Snodgrass Mountain Trail",
      address: "Gothic Rd Trailhead, Crested Butte, CO 81224",
      lat: 38.8880,
      lng: -106.9900,
      offLeash: true,
      fenced: false,
      acres: 50.0,
      amenities: ["Alpine trails", "Wildflower meadows", "Mountain views", "Parking", "Waste stations"],
      rating: 4.8,
      imageUrl: "",
      description:
        "One of the most spectacular dog-friendly hikes in Colorado with panoramic views of the Elk Mountains and Crested Butte. Off-leash under voice control, dogs and owners ascend through world-famous wildflower meadows.",
    },
    {
      name: "Slate River Trail",
      address: "Slate River Rd, Crested Butte, CO 81224",
      lat: 38.8900,
      lng: -107.0050,
      offLeash: true,
      fenced: false,
      acres: 40.0,
      amenities: ["River access", "Valley views", "Wildlife viewing", "Parking", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A scenic trail following the Slate River through the valley north of Crested Butte. Dogs love the river access and the open meadows with views of towering peaks on all sides.",
    },
  ],
};
