export const dahlonegaData = {
  city: {
    name: "Dahlonega",
    state: "Georgia",
    region: "Southeast",
    lat: 34.5326,
    lng: -83.9849,
    dogFriendlinessScore: 7,
    description:
      "This charming North Georgia mountain town, site of the first major gold rush in the US, welcomes dogs with open arms to its historic square, vineyard patios, and surrounding national forest trails. The combination of wine tasting, waterfall hikes, and small-town hospitality makes it a delightful dog-friendly getaway.",
    heroImage: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 7360,
  },
  hotels: [
    {
      name: "The Smith House",
      address: "84 S Chestatee St, Dahlonega, GA 30533",
      lat: 34.5310,
      lng: -83.9850,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in designated pet-friendly rooms with a pet fee. A historic inn on the town square since 1884.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Pet-friendly rooms", "Walking access to square", "Water bowls", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.smithhouse.com",
      phone: "(706) 867-7000",
    },
    {
      name: "Dahlonega Resort & Vineyard",
      address: "400 Blueberry Hill, Dahlonega, GA 30533",
      lat: 34.5240,
      lng: -83.9730,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select cabins with a non-refundable pet fee. A vineyard resort with mountain views and wine tasting.",
      maxDogWeight: 75,
      petFee: 100,
      amenities: ["Dog bed", "Private cabin porch", "Vineyard walking trails", "Water bowls", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.dahlonegaresort.com",
      phone: "(706) 867-9862",
    },
    {
      name: "Quality Inn Dahlonega",
      address: "833 S Chestatee St, Dahlonega, GA 30533",
      lat: 34.5230,
      lng: -83.9860,
      priceRange: "$" as const,
      dogPolicy: "Dogs of any size welcome with a per-night pet fee. Budget-friendly lodging near the historic square.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Pet-friendly rooms", "Waste bags", "Nearby walking areas"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.choicehotels.com/georgia/dahlonega",
      phone: "(706) 864-6191",
    },
    {
      name: "Mountain Laurel Creek Inn & Spa",
      address: "202 Bearden-Thompson Rd, Dahlonega, GA 30533",
      lat: 34.5200,
      lng: -83.9920,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in the cottage rooms with a pet fee. A peaceful mountain retreat with gardens and creek access.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Dog bed", "Creek access", "Garden walks", "Water bowls", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.mountainlaurelcreekinn.com",
      phone: "(706) 867-8134",
    },
  ],
  nationalParks: [
    {
      name: "Chattahoochee National Forest",
      state: "Georgia",
      lat: 34.6500,
      lng: -83.9500,
      dogPolicy: "Dogs welcome on all trails on a leash. Nearly 750,000 acres of mountain forest surrounding Dahlonega.",
      dogTrails: ["Springer Mountain Trail", "DeSoto Falls Trail", "Dockery Lake Trail", "Jarrard Gap Trail"],
      restrictions: ["Leash recommended on all trails", "Must clean up after pet", "Check seasonal conditions"],
      description: "The vast Chattahoochee National Forest surrounds Dahlonega with mountain peaks, waterfalls, and the southern terminus of the Appalachian Trail at Springer Mountain. Dogs can explore hundreds of miles of trails through lush hardwood forests.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/conf",
    },
    {
      name: "Amicalola Falls State Park",
      state: "Georgia",
      lat: 34.5690,
      lng: -84.2480,
      dogPolicy: "Dogs welcome on most trails on a 6-foot leash, including the trail to the base of the falls. Not allowed on the approach trail to Springer Mountain.",
      dogTrails: ["Falls Base Trail", "Creek Trail", "Mountain Laurel Loop"],
      restrictions: ["6-foot leash required", "Not allowed on Springer Mountain approach trail", "Not in lodge", "Must clean up after pet"],
      description: "Home to the tallest cascading waterfall east of the Mississippi at 729 feet, Amicalola Falls is about 30 minutes from Dahlonega. Dogs can hike to the base of the falls and enjoy the surrounding mountain trails.",
      imageUrl: "",
      website: "https://www.gastateparks.org/AmicalolaFalls",
    },
    {
      name: "DeSoto Falls Scenic Area",
      state: "Georgia",
      lat: 34.7020,
      lng: -83.9180,
      dogPolicy: "Dogs welcome on the trail to the lower falls on a leash. A beautiful two-mile round-trip hike to cascading waterfalls.",
      dogTrails: ["DeSoto Falls Trail Lower Loop", "DeSoto Falls Trail Upper Loop"],
      restrictions: ["Leash required", "Rocky terrain near falls", "Must clean up after pet"],
      description: "About 15 miles north of Dahlonega, DeSoto Falls features two scenic waterfalls accessible by a moderate trail through rhododendron-covered slopes. Dogs enjoy the creek crossings and cool mountain air.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/recarea/conf/recarea/?recid=10497",
    },
  ],
  restaurants: [
    {
      name: "The Crimson Moon",
      address: "24 N Park St, Dahlonega, GA 30533",
      lat: 34.5330,
      lng: -83.9845,
      cuisine: "American & Live Music Venue",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor deck. A beloved music venue and restaurant on the historic square.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thecrimsonmoon.com",
    },
    {
      name: "Shenanigans",
      address: "1 S Public Square, Dahlonega, GA 30533",
      lat: 34.5325,
      lng: -83.9850,
      cuisine: "Irish Pub & American",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the patio overlooking the square. A lively pub with generous portions and cold beer.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.shenanigansofga.com",
    },
    {
      name: "Picnic Café & Dessertery",
      address: "49 S Park St, Dahlonega, GA 30533",
      lat: 34.5320,
      lng: -83.9845,
      cuisine: "Cafe & Bakery",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the covered patio. Fresh sandwiches, salads, and homemade desserts on the square.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.picniccafe.net",
    },
    {
      name: "Bourbon Street Grille",
      address: "56 N Chestatee St, Dahlonega, GA 30533",
      lat: 34.5335,
      lng: -83.9850,
      cuisine: "Cajun & Southern",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the sidewalk patio. Cajun-inspired dishes and craft cocktails steps from the square.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bourbonstreetgrille.com",
    },
    {
      name: "Spirits Tavern",
      address: "19 E Main St, Dahlonega, GA 30533",
      lat: 34.5325,
      lng: -83.9840,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Upscale dining with seasonal menus and a curated wine list.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.spiritstavern.com",
    },
  ],
  cafes: [
    {
      name: "Dahlonega Roasting Company",
      address: "34 N Park St, Dahlonega, GA 30533",
      lat: 34.5332,
      lng: -83.9845,
      dogPolicy: "Dogs welcome on the patio overlooking the historic square. Locally roasted coffee and homemade pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.dahlonegaroasting.com",
    },
    {
      name: "Gold City Coffee",
      address: "12 W Main St, Dahlonega, GA 30533",
      lat: 34.5325,
      lng: -83.9855,
      dogPolicy: "Dogs welcome at outdoor tables on the square. Specialty espresso drinks and fresh baked goods.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.goldcitycoffee.com",
    },
    {
      name: "The Velvet Cup",
      address: "15 S Chestatee St, Dahlonega, GA 30533",
      lat: 34.5318,
      lng: -83.9850,
      dogPolicy: "Dog-friendly outdoor seating just off the square. Cozy cafe with artisan coffee and light bites.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thevelvetcup.com",
    },
    {
      name: "Back Porch Coffee",
      address: "82 S Public Square, Dahlonega, GA 30533",
      lat: 34.5320,
      lng: -83.9852,
      dogPolicy: "Dogs welcome on the namesake back porch. A relaxed gathering spot with fair-trade coffee and local art.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.backporchcoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Hancock Park",
      address: "Warwoman St, Dahlonega, GA 30533",
      lat: 34.5340,
      lng: -83.9870,
      offLeash: false,
      fenced: false,
      acres: 5,
      amenities: ["Walking paths", "Creek access", "Picnic areas", "Shade trees", "Waste bag stations"],
      rating: 4.2,
      imageUrl: "",
      description: "A peaceful town park along a mountain creek with walking paths and picnic areas. Dogs on leash can enjoy the shaded trails and cool creek access just steps from the historic square.",
    },
    {
      name: "Yahoola Creek Park",
      address: "175 Yahoola Church Rd, Dahlonega, GA 30533",
      lat: 34.5260,
      lng: -83.9780,
      offLeash: false,
      fenced: false,
      acres: 8,
      amenities: ["Paved walking trail", "Creek access", "Benches", "Covered pavilion", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "A scenic park along Yahoola Creek with a paved walking trail and creek access points where dogs can wade. The shaded trail offers a pleasant walk through a mountain valley setting.",
    },
    {
      name: "Dahlonega Gold Museum Historic Site Grounds",
      address: "1 Public Square, Dahlonega, GA 30533",
      lat: 34.5325,
      lng: -83.9848,
      offLeash: false,
      fenced: false,
      acres: 2,
      amenities: ["Historic square access", "Benches", "Shade trees", "Water fountain", "Waste bag stations"],
      rating: 4.0,
      imageUrl: "",
      description: "The grassy grounds surrounding the historic gold museum courthouse provide a central gathering spot for dogs and their owners. Leashed walks around the square pass shops, restaurants, and friendly locals.",
    },
    {
      name: "Wimpy Mill Park",
      address: "Wimpy Mill Rd, Dahlonega, GA 30533",
      lat: 34.5180,
      lng: -83.9700,
      offLeash: false,
      fenced: false,
      acres: 12,
      amenities: ["Creek swimming", "Nature trails", "Picnic areas", "Natural terrain", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description: "A local favorite for swimming and picnicking along the Chestatee River, south of town. Dogs enjoy wading in the creek and exploring the natural trails through the surrounding forest.",
    },
  ],
};
