export const dallasData = {
  city: {
    name: "Dallas",
    state: "Texas",
    region: "Southwest",
    lat: 32.7767,
    lng: -96.7970,
    dogFriendlinessScore: 7,
    description:
      "Dallas is a big-hearted city that loves its dogs as much as its barbecue and football. With an impressive network of trails, trendy neighborhoods full of dog-friendly patios, and some of the best dog parks in Texas, Big D rolls out the red carpet for four-legged visitors.",
    heroImage: "https://images.unsplash.com/photo-1545194445-dddb8f4487c6?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 1304379,
  },

  hotels: [
    {
      name: "The Joule",
      address: "1530 Main St, Dallas, TX 75201",
      lat: 32.7830,
      lng: -96.7990,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 40 lbs welcome with a one-time pet fee. Luxury boutique hotel downtown.",
      maxDogWeight: 40,
      petFee: 100,
      amenities: ["Dog bed", "Gourmet treats", "Water bowls", "Walking service", "Rooftop pool access"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.thejouledallas.com",
      phone: "(214) 748-1300",
    },
    {
      name: "Kimpton Pittman Hotel",
      address: "2551 Elm St, Dallas, TX 75226",
      lat: 32.7870,
      lng: -96.7840,
      priceRange: "$$$" as const,
      dogPolicy: "All Kimpton properties welcome dogs of any size at no extra charge. Deep Ellum location.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Dog bed", "Water bowls", "Treats", "Deep Ellum nightlife"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ihg.com/kimpton",
      phone: "(214) 443-9000",
    },
    {
      name: "Canopy by Hilton Dallas Uptown",
      address: "2771 N Harwood St, Dallas, TX 75201",
      lat: 32.7950,
      lng: -96.8020,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a non-refundable fee. Near Katy Trail.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Dog bed", "Near Katy Trail", "Walking maps", "Grassy area", "Uptown dining access"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(214) 975-3500",
    },
    {
      name: "La Quinta Inn Dallas Uptown",
      address: "4440 N Central Expy, Dallas, TX 75206",
      lat: 32.8110,
      lng: -96.7820,
      priceRange: "$" as const,
      dogPolicy: "All dogs welcome at no extra charge. Convenient location near parks.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Near White Rock Lake", "Grassy area", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(214) 821-4220",
    },
  ],

  nationalParks: [
    {
      name: "Cedar Ridge Preserve",
      state: "Texas",
      lat: 32.6330,
      lng: -96.9560,
      dogPolicy: "Leashed dogs welcome on all trails. A 600-acre nature preserve with Hill Country-like terrain.",
      dogTrails: ["Cattail Pond Trail", "Cedar Brake Trail", "Escarpment Trail", "Fossil Valley Trail"],
      restrictions: [
        "Must be on a 6-foot leash at all times",
        "Stay on marked trails",
        "Carry water for your dog",
      ],
      description:
        "Managed by Audubon Dallas, this preserve offers rolling limestone terrain, panoramic views, and surprisingly rugged hiking just south of the city. Dogs enjoy the varied terrain and wooded paths.",
      imageUrl: "",
      website: "https://www.audubondallas.org/cedar-ridge-preserve",
    },
    {
      name: "White Rock Lake Park",
      state: "Texas",
      lat: 32.8230,
      lng: -96.7220,
      dogPolicy: "Leashed dogs welcome on the 9.3-mile trail loop and throughout the park.",
      dogTrails: ["White Rock Lake Trail", "Sunset Bay Trail", "Winfrey Point Loop"],
      restrictions: [
        "Must be on leash",
        "Not allowed on the swimming beach",
        "Stay on designated trails",
      ],
      description:
        "Dallas's beloved urban lake offers a 9.3-mile paved trail circling the water with skyline views. The diverse bird life, lakeside scenery, and shaded sections make it the city's most popular dog walking destination.",
      imageUrl: "",
      website: "https://www.whiterocklake.org",
    },
    {
      name: "Trinity River Audubon Center",
      state: "Texas",
      lat: 32.6990,
      lng: -96.7140,
      dogPolicy: "Leashed dogs welcome on the trail system. A restored floodplain forest in south Dallas.",
      dogTrails: ["Blackland Prairie Trail", "River Bottom Trail", "Trinity Forest Trail"],
      restrictions: [
        "Must be on leash",
        "Not allowed inside the nature center",
        "Stay on designated trails",
      ],
      description:
        "A 120-acre nature center in the Great Trinity Forest featuring wetlands, prairie, and riparian forest. Dogs enjoy the diverse habitats and the chance to spot wildlife along the well-maintained trails.",
      imageUrl: "",
      website: "https://www.trinityriver.audubon.org",
    },
  ],

  restaurants: [
    {
      name: "Mutts Canine Cantina",
      address: "2889 Cityplace West Blvd, Dallas, TX 75204",
      lat: 32.8000,
      lng: -96.8060,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Restaurant + off-leash dog park combo. Dogs play while you eat. The ultimate dog-friendly dining.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.muttscantina.com",
    },
    {
      name: "Pecan Lodge",
      address: "2702 Main St, Dallas, TX 75226",
      lat: 32.7850,
      lng: -96.7830,
      cuisine: "Texas Barbecue",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor picnic tables. Legendary Dallas barbecue in Deep Ellum.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.pecanlodge.com",
    },
    {
      name: "Katy Trail Ice House",
      address: "3127 Routh St, Dallas, TX 75201",
      lat: 32.7990,
      lng: -96.8010,
      cuisine: "Pub & Grill",
      priceRange: "$" as const,
      dogPolicy: "Extremely dog-friendly with a large outdoor area right on the Katy Trail. Dogs are welcome regulars.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.katytrailicehouse.com",
    },
    {
      name: "Truck Yard",
      address: "5624 Sears St, Dallas, TX 75206",
      lat: 32.8090,
      lng: -96.7660,
      cuisine: "Food Trucks & Bar",
      priceRange: "$" as const,
      dogPolicy: "Very dog-friendly outdoor beer garden with food trucks. A Dallas institution.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.truckyarddallas.com",
    },
    {
      name: "The Rustic",
      address: "3656 Howell St, Dallas, TX 75204",
      lat: 32.7980,
      lng: -96.7960,
      cuisine: "Texas Country",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome in the outdoor area. Live music and Texas comfort food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.therustic.com",
    },
  ],

  cafes: [
    {
      name: "Houndstooth Coffee",
      address: "1900 N Henderson Ave, Dallas, TX 75206",
      lat: 32.8060,
      lng: -96.7750,
      dogPolicy: "Dogs welcome on the patio. Award-winning specialty coffee on Henderson Ave.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.houndstoothcoffee.com",
    },
    {
      name: "Weekend Coffee",
      address: "1510 N Fitzhugh Ave, Dallas, TX 75204",
      lat: 32.8010,
      lng: -96.7830,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Minimalist coffee shop with great beans.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.weekendcoffee.com",
    },
    {
      name: "Davis Street Espresso",
      address: "819 W Davis St, Dallas, TX 75208",
      lat: 32.7500,
      lng: -96.8290,
      dogPolicy: "Dog-friendly patio in the Bishop Arts District. Quality espresso drinks.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.davisstreetespresso.com",
    },
    {
      name: "Ascension Coffee",
      address: "1621 Oak Lawn Ave, Dallas, TX 75207",
      lat: 32.7880,
      lng: -96.8050,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Design District coffee and cafe.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ascensioncoffee.com",
    },
  ],

  dogParks: [
    {
      name: "White Rock Dog Park",
      address: "8000 E Mockingbird Ln, Dallas, TX 75214",
      lat: 32.8200,
      lng: -96.7100,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: ["Lake access", "Separate small dog area", "Water stations", "Shade trees", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Dallas's most popular dog park sits on the shore of White Rock Lake with water access for swimming dogs. The combination of fenced off-leash play and lake swimming makes it irresistible.",
    },
    {
      name: "Katy Trail",
      address: "3601 Turtle Creek Blvd, Dallas, TX 75219",
      lat: 32.8020,
      lng: -96.8040,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Paved trail", "Shade trees", "Water fountains", "Restaurants nearby", "Urban scenery"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A 3.5-mile paved trail on a former railroad corridor through Uptown Dallas. Dogs love this popular on-leash route that passes by restaurants, parks, and the energy of the city.",
    },
    {
      name: "NorthBark Dog Park",
      address: "9950 Grady Niblo Rd, Dallas, TX 75220",
      lat: 32.8680,
      lng: -96.8630,
      offLeash: true,
      fenced: true,
      acres: 22.0,
      amenities: ["Swimming pond", "Agility equipment", "Trails", "Separate small dog area", "Wash station"],
      rating: 4.7,
      imageUrl: "",
      description:
        "One of the largest and best-equipped dog parks in Dallas, featuring a swimming pond, agility equipment, and wooded trails. The 22-acre facility feels more like a dog resort.",
    },
    {
      name: "Wagging Tail Dog Park",
      address: "8100 Greenville Ave, Dallas, TX 75231",
      lat: 32.8580,
      lng: -96.7550,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water fountain", "Shade structures", "Benches", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A popular neighborhood dog park in the Lake Highlands area with separate areas for different sized dogs. Well-maintained and conveniently located near shops and restaurants.",
    },
  ],
};
