export const deadwoodData = {
  city: {
    name: "Deadwood",
    state: "South Dakota",
    region: "Mountain West",
    lat: 44.3768,
    lng: -103.7296,
    dogFriendlinessScore: 6,
    description:
      "Deadwood is a legendary Wild West town turned gaming destination in the heart of the Black Hills. Dogs enjoy the historic Main Street, surrounding forest trails, and a surprisingly welcoming attitude from local businesses. The George S. Mickelson Trail and Spearfish Canyon nearby provide excellent hiking for adventurous pups.",
    heroImage: "https://images.unsplash.com/photo-1500049242364-5f500807cdd7?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 1340,
  },

  hotels: [
    {
      name: "Deadwood Mountain Grand",
      address: "1906 Deadwood Mountain Dr, Deadwood, SD 57732",
      lat: 44.3800,
      lng: -103.7230,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with a per-stay pet fee. Full-service resort with gaming and entertainment.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Walking areas", "Near trails", "Pet-sitting referrals"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.deadwoodmountaingrand.com",
      phone: "(605) 559-0386",
    },
    {
      name: "SpringHill Suites by Marriott Deadwood",
      address: "322 Main St, Deadwood, SD 57732",
      lat: 44.3770,
      lng: -103.7295,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a non-refundable fee. Modern suites on historic Main Street.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Walking distance to trails", "Pet waste stations", "Water bowls", "Near Main Street"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(605) 559-1600",
    },
    {
      name: "Celebrity Hotel",
      address: "629 Main St, Deadwood, SD 57732",
      lat: 44.3775,
      lng: -103.7280,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome with a modest pet fee. Budget-friendly on historic Main Street.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Walking distance to everything", "Pet waste stations", "Near trailheads"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.celebrityhoteldeadwood.com",
      phone: "(605) 578-1909",
    },
    {
      name: "The Lodge at Deadwood",
      address: "100 Pine Crest Ln, Deadwood, SD 57732",
      lat: 44.3830,
      lng: -103.7350,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in designated pet rooms. Resort lodge with indoor pool and gaming.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Grassy areas", "Forest trails nearby", "Pet waste stations", "Water bowls"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.deadwoodlodge.com",
      phone: "(605) 584-4800",
    },
  ],

  nationalParks: [
    {
      name: "Black Hills National Forest (Northern Section)",
      state: "South Dakota",
      lat: 44.4000,
      lng: -103.8000,
      dogPolicy: "Dogs welcome on all trails. Voice control in backcountry; leash in developed areas.",
      dogTrails: ["George S. Mickelson Trail", "Roughlock Falls Trail", "Little Spearfish Trail", "Iron Creek Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on trails",
        "Bikes and horses share Mickelson Trail",
      ],
      description:
        "The northern Black Hills around Deadwood offer pine forests, limestone canyons, and the spectacular Spearfish Canyon. The 109-mile Mickelson Trail passes right through Deadwood and is perfect for long dog walks.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/blackhills",
    },
    {
      name: "Spearfish Canyon Scenic Byway",
      state: "South Dakota",
      lat: 44.3500,
      lng: -103.8200,
      dogPolicy: "Leashed dogs welcome on trails and at waterfall viewpoints along the canyon.",
      dogTrails: ["Roughlock Falls Trail", "Spearfish Falls Trail", "Eleventh Hour Gulch Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Stay on designated trails",
        "Be cautious on cliff edges",
      ],
      description:
        "One of the most beautiful canyons in the Black Hills with waterfalls, towering limestone walls, and a creek running through it. The Roughlock Falls trail is an easy, beautiful walk perfect for dogs.",
      imageUrl: "",
      website: "https://www.spearfishcanyon.com",
    },
    {
      name: "Bear Butte State Park",
      state: "South Dakota",
      lat: 44.4750,
      lng: -103.4220,
      dogPolicy: "Leashed dogs welcome on the summit trail. Sacred site for Native Americans - be respectful.",
      dogTrails: ["Summit Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Do not disturb prayer cloths or offerings",
        "Stay on designated trail",
        "No dogs near ceremonial areas",
      ],
      description:
        "A volcanic laccolith rising above the plains, Bear Butte is sacred to the Lakota and Cheyenne. The summit trail offers panoramic views of the Black Hills and surrounding plains. Dogs must be leashed and visitors should be respectful of sacred items along the trail.",
      imageUrl: "",
      website: "https://gfp.sd.gov/parks/detail/bear-butte-state-park",
    },
  ],

  restaurants: [
    {
      name: "Deadwood Social Club",
      address: "657 Main St, Deadwood, SD 57732",
      lat: 44.3776,
      lng: -103.7278,
      cuisine: "Italian & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the balcony patio overlooking Main Street. Italian cuisine above the famous saloon.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.deadwoodsocialclub.com",
    },
    {
      name: "Mavericks",
      address: "31 Deadwood St, Deadwood, SD 57732",
      lat: 44.3768,
      lng: -103.7298,
      cuisine: "Steakhouse",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor deck. Premium steaks in a Western atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.mavericksdeadwood.com",
    },
    {
      name: "Legends Steakhouse",
      address: "1906 Deadwood Mountain Dr, Deadwood, SD 57732",
      lat: 44.3802,
      lng: -103.7232,
      cuisine: "Steakhouse & Seafood",
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome on the patio with mountain views. Upscale dining at the resort.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.deadwoodmountaingrand.com/dining",
    },
    {
      name: "Bully's",
      address: "679 Main St, Deadwood, SD 57732",
      lat: 44.3777,
      lng: -103.7275,
      cuisine: "American Sports Bar",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Casual bar and grill on Main Street.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.bullysdeadwood.com",
    },
    {
      name: "Dakotah Steakhouse",
      address: "63 Sherman St, Deadwood, SD 57732",
      lat: 44.3772,
      lng: -103.7290,
      cuisine: "Steakhouse & Western",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the patio. Traditional steakhouse with Wild West character.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.dakotahsteakhouse.com",
    },
  ],

  cafes: [
    {
      name: "Deadwood Coffee Company",
      address: "580 Main St, Deadwood, SD 57732",
      lat: 44.3772,
      lng: -103.7285,
      dogPolicy: "Dogs welcome on the sidewalk patio. Fresh-roasted coffee on historic Main Street.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.deadwoodcoffeecompany.com",
    },
    {
      name: "Cheyenne Crossing Cafe",
      address: "21415 US-14A, Lead, SD 57754",
      lat: 44.3200,
      lng: -103.8100,
      dogPolicy: "Outdoor seating welcomes dogs. Rustic mountain cafe at the entrance to Spearfish Canyon.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cheyennecrossing.org",
    },
    {
      name: "Lewie's Saloon & Eatery",
      address: "700 Main St, Deadwood, SD 57732",
      lat: 44.3778,
      lng: -103.7272,
      dogPolicy: "Dog-friendly outdoor area. Coffee, breakfast, and sandwiches on Main Street.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.lewiesdeadwood.com",
    },
    {
      name: "Phat Tire Coffee",
      address: "644 Main St, Deadwood, SD 57732",
      lat: 44.3774,
      lng: -103.7280,
      dogPolicy: "Leashed dogs welcome at patio tables. Cozy coffee shop with mountain town character.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.phattirecoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Deadwood Recreational Trail",
      address: "Main St Trailhead, Deadwood, SD 57732",
      lat: 44.3780,
      lng: -103.7310,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Paved trail", "Mountain views", "Creek access", "Waste stations", "Multiple access points"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A section of the George S. Mickelson Trail running through Deadwood on a converted rail bed. Leashed dogs enjoy the gentle grade, forest scenery, and creek crossings on this well-maintained path.",
    },
    {
      name: "Deadwood Gulch Trail",
      address: "Lower Main St, Deadwood, SD 57732",
      lat: 44.3760,
      lng: -103.7310,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Creek trail", "Historic sites", "Benches", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A short trail following Whitewood Creek through the gulch where gold was first discovered. Leashed dogs can explore the historic area where Wild Bill Hickok once walked.",
    },
    {
      name: "Terry Peak Trail System",
      address: "Terry Peak Rd, Lead, SD 57754",
      lat: 44.3700,
      lng: -103.7600,
      offLeash: true,
      fenced: false,
      acres: 50.0,
      amenities: ["Mountain trails", "Forest hiking", "Summit views", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Trails on and around Terry Peak offer forested mountain hiking with panoramic Black Hills views from the summit. Dogs can run off-leash under voice control on these less-traveled trails above Deadwood.",
    },
    {
      name: "Whitewood Creek Park",
      address: "Sherman St, Deadwood, SD 57732",
      lat: 44.3765,
      lng: -103.7292,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["Creek access", "Picnic area", "Benches", "Waste stations", "Shade trees"],
      rating: 4.1,
      imageUrl: "",
      description:
        "A small park along Whitewood Creek in Deadwood where leashed dogs can splash in the creek and rest in the shade. A pleasant stop during a walk through the historic town.",
    },
  ],
};
