export const denverData = {
  city: {
    name: "Denver",
    state: "Colorado",
    region: "Mountain West",
    lat: 39.7392,
    lng: -104.9903,
    dogFriendlinessScore: 8,
    description:
      "The Mile High City is also the Mile High Dog City. Denver's outdoor obsession extends to its four-legged residents with mountain trailheads within an hour's drive, a thriving brewery scene that welcomes pups, and wide-open dog parks with Rocky Mountain views. With 300 days of sunshine and a culture built around adventure, Denver is where active dogs come to thrive.",
    heroImage: "https://images.unsplash.com/photo-1546156929-a4c0ac411f47?w=1200&fit=crop",
    climate: "Semi-arid Continental",
    population: 715522,
  },
  hotels: [
    {
      name: "The Crawford Hotel",
      address: "1701 Wynkoop St, Denver, CO 80202",
      lat: 39.7531,
      lng: -104.9998,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome, all sizes, max 2 per room",
      maxDogWeight: 0,
      petFee: 75,
      amenities: [
        "Dog bed",
        "Welcome treats",
        "Union Station walking area",
        "Nearby pet shops",
      ],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.thecrawfordhotel.com",
      phone: "(720) 460-3700",
    },
    {
      name: "Kimpton Hotel Born",
      address: "1600 Wewatta St, Denver, CO 80202",
      lat: 39.7536,
      lng: -105.0009,
      priceRange: "$$$" as const,
      dogPolicy: "All pets welcome — no size limits, no breed restrictions",
      maxDogWeight: 0,
      petFee: 0,
      amenities: [
        "Dog bed",
        "Food and water bowls",
        "Treats",
        "Pet concierge with local park recommendations",
      ],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.hotelborn.com",
      phone: "(303) 323-0024",
    },
    {
      name: "The Rally Hotel",
      address: "1600 19th St, Denver, CO 80202",
      lat: 39.7558,
      lng: -104.9952,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome",
      maxDogWeight: 50,
      petFee: 100,
      amenities: [
        "Luxury dog bed",
        "Gourmet treat bag",
        "Rooftop access",
        "Dog walking service",
      ],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.therallyhotel.com",
      phone: "(303) 223-8000",
    },
    {
      name: "Moxy Denver Cherry Creek",
      address: "240 Josephine St, Denver, CO 80206",
      lat: 39.7178,
      lng: -104.9605,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome, 2 per room, all sizes",
      maxDogWeight: 0,
      petFee: 50,
      amenities: [
        "Dog bed",
        "Welcome toy",
        "Cherry Creek Trail access nearby",
        "Treats at front desk",
      ],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.marriott.com/moxy-denver",
      phone: "(303) 333-3333",
    },
    {
      name: "The Patterson Inn",
      address: "420 E 11th Ave, Denver, CO 80203",
      lat: 39.7325,
      lng: -104.9785,
      priceRange: "$$" as const,
      dogPolicy: "Well-behaved dogs welcome in select rooms, call ahead",
      maxDogWeight: 40,
      petFee: 35,
      amenities: [
        "Dog blanket",
        "Biscuits at check-in",
        "Fenced garden access",
        "Walking route map",
      ],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.pattersoninn.com",
      phone: "(303) 955-5142",
    },
  ],
  nationalParks: [
    {
      name: "Rocky Mountain National Park",
      state: "Colorado",
      lat: 40.3428,
      lng: -105.6836,
      dogPolicy:
        "Dogs allowed on specific roads and in picnic areas; not permitted on trails",
      dogTrails: [
        "Paved paths around Bear Lake parking area",
        "Moraine Park area roads",
      ],
      restrictions: [
        "Must be on 6-foot leash",
        "Not allowed on any hiking trails",
        "Not allowed in meadows or tundra",
        "Cannot be left unattended in vehicles",
      ],
      description:
        "Colorado's crown jewel with alpine lakes, elk herds, and peaks over 14,000 feet. While dogs can't hit the trails, the scenic Trail Ridge Road offers pull-offs with mountain panoramas that will take your breath away — sometimes literally at this altitude.",
      imageUrl: "",
      website: "https://www.nps.gov/romo",
    },
    {
      name: "Garden of the Gods",
      state: "Colorado",
      lat: 38.8786,
      lng: -104.8699,
      dogPolicy: "Dogs welcome on all paved and unpaved trails on leash",
      dogTrails: [
        "Perkins Central Garden Trail",
        "Siamese Twins Trail",
        "Palmer Trail",
        "Scotsman Trail",
        "Buckskin Charlie Trail",
      ],
      restrictions: [
        "Must be on 6-foot leash",
        "Clean up after pet",
        "Stay on designated trails",
      ],
      description:
        "Towering red sandstone formations jutting dramatically against Pikes Peak create one of Colorado's most photographed landscapes. Dogs can explore every trail in this free city park, making it one of the best dog-friendly natural attractions in the state.",
      imageUrl: "",
      website: "https://www.gardenofgods.com",
    },
    {
      name: "Great Sand Dunes National Park",
      state: "Colorado",
      lat: 37.7329,
      lng: -105.5121,
      dogPolicy:
        "Dogs allowed on Medano Creek, in picnic areas, and along the road; not on dunes",
      dogTrails: ["Medano Creek beach area", "Dunes Parking Area paths"],
      restrictions: [
        "Must be on 6-foot leash",
        "Not allowed on sand dunes",
        "Not allowed on backcountry trails",
        "Sand can be extremely hot — check surface temperature",
      ],
      description:
        "North America's tallest sand dunes rise against the Sangre de Cristo Mountains. Dogs can splash in the seasonal Medano Creek at the base of the dunes — a unique beach experience in the middle of Colorado.",
      imageUrl: "",
      website: "https://www.nps.gov/grsa",
    },
    {
      name: "Red Rocks Park and Amphitheatre",
      state: "Colorado",
      lat: 39.6654,
      lng: -105.2057,
      dogPolicy: "Dogs welcome on all trails on leash",
      dogTrails: [
        "Trading Post Trail",
        "Red Rocks Trail",
        "Geologic Overlook Trail",
      ],
      restrictions: [
        "Must be on leash",
        "Not allowed in amphitheatre during events",
        "Clean up after pet",
      ],
      description:
        "Famous for its concert venue, Red Rocks also offers stunning hiking trails through 300-million-year-old red sandstone formations. Dogs love the Trading Post Trail loop with its panoramic views of Denver and the Great Plains.",
      imageUrl: "",
      website: "https://www.redrocksonline.com",
    },
  ],
  restaurants: [
    {
      name: "Resolute Brewing Company",
      address: "7286 S Yosemite St, Centennial, CO 80112",
      lat: 39.5977,
      lng: -104.9073,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on patio and in taproom — extremely dog-friendly",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.resolutebrewing.com",
    },
    {
      name: "The Hornet",
      address: "76 Broadway, Denver, CO 80203",
      lat: 39.7171,
      lng: -104.9873,
      cuisine: "American Comfort",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on large patio, water bowls always available",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hornetrestaurant.com",
    },
    {
      name: "Linger",
      address: "2030 W 30th Ave, Denver, CO 80211",
      lat: 39.7612,
      lng: -105.0108,
      cuisine: "Global Street Food",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on rooftop patio with mountain views",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.lingerdenver.com",
    },
    {
      name: "Biker Jim's Gourmet Dogs",
      address: "2148 Larimer St, Denver, CO 80205",
      lat: 39.7554,
      lng: -104.9895,
      cuisine: "Gourmet Hot Dogs",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables — yes, dogs eating dogs",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bikerjimsdogs.com",
    },
    {
      name: "Adelitas Cocina y Cantina",
      address: "1294 S Broadway, Denver, CO 80210",
      lat: 39.6998,
      lng: -104.9873,
      cuisine: "Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on outdoor patio",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.adelitasdenver.com",
    },
    {
      name: "Lowdown Brewery + Kitchen",
      address: "800 Lincoln St, Denver, CO 80203",
      lat: 39.7289,
      lng: -104.9838,
      cuisine: "Pizza & Beer",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on heated patio year-round",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.lowdownbrewery.com",
    },
    {
      name: "Work & Class",
      address: "2500 Larimer St, Denver, CO 80205",
      lat: 39.7589,
      lng: -104.9857,
      cuisine: "Southern & Latin Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio with advance notice",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.workandclassdenver.com",
    },
    {
      name: "Snooze an A.M. Eatery",
      address: "2262 Larimer St, Denver, CO 80205",
      lat: 39.7561,
      lng: -104.9889,
      cuisine: "Brunch",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the sunny patio — pancake crumbs guaranteed",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.snoozeeatery.com",
    },
  ],
  cafes: [
    {
      name: "Thump Coffee",
      address: "1201 E 13th Ave, Denver, CO 80218",
      lat: 39.7347,
      lng: -104.9714,
      dogPolicy: "Front patio is dog-friendly, treats sometimes available",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thumpcoffee.com",
    },
    {
      name: "Little Owl Coffee",
      address: "1555 Blake St, Denver, CO 80202",
      lat: 39.7498,
      lng: -104.9956,
      dogPolicy: "Patio seating welcomes dogs, water bowls provided",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.littleowlcoffee.com",
    },
    {
      name: "Novo Coffee",
      address: "1700 E 6th Ave, Denver, CO 80218",
      lat: 39.7234,
      lng: -104.9681,
      dogPolicy: "Dog-friendly patio with mountain views",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.novocoffee.com",
    },
    {
      name: "Harbinger Coffee",
      address: "3563 Wazee St, Denver, CO 80216",
      lat: 39.7701,
      lng: -104.9812,
      dogPolicy: "Covered patio welcomes well-behaved dogs",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.harbingercoffee.com",
    },
    {
      name: "Sweet Bloom Coffee Roasters",
      address: "1619 Platte St, Denver, CO 80202",
      lat: 39.7573,
      lng: -105.0089,
      dogPolicy: "Patio and courtyard are dog-friendly zones",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.sweetbloomcoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Cherry Creek Dog Park",
      address: "4000 S Parker Rd, Aurora, CO 80014",
      lat: 39.6505,
      lng: -104.8835,
      offLeash: true,
      fenced: true,
      acres: 107.0,
      amenities: [
        "Creek swimming",
        "Prairie trails",
        "Water fountains",
        "Shade shelters",
        "Waste stations",
      ],
      rating: 4.7,
      imageUrl: "",
      description:
        "One of the largest off-leash dog parks in the entire country at 107 acres. Dogs can swim in Cherry Creek, run through tallgrass prairie, and explore miles of trails. It's basically a national park for dogs.",
    },
    {
      name: "Railyard Dog Park",
      address: "19th St & Chestnut Pl, Denver, CO 80202",
      lat: 39.7562,
      lng: -104.9988,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: [
        "Water fountains",
        "Benches",
        "Downtown skyline views",
        "Double-gated entry",
        "Waste stations",
      ],
      rating: 4.3,
      imageUrl: "",
      description:
        "A convenient downtown dog park near Union Station where city pups can socialize against a backdrop of Denver's skyline. Small but lively, it's the go-to spot for LoDo and RiNo dog owners.",
    },
    {
      name: "Berkeley Dog Park",
      address: "4601 W 46th Ave, Denver, CO 80212",
      lat: 39.7787,
      lng: -105.0412,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: [
        "Lake access",
        "Separate small dog area",
        "Agility equipment",
        "Water fountains",
        "Shade structures",
      ],
      rating: 4.6,
      imageUrl: "",
      description:
        "A beloved neighborhood dog park with access to Berkeley Lake. Dogs can splash in the water, navigate agility equipment, or simply bask in the Colorado sunshine. The separate small dog area keeps tiny pups safe.",
    },
    {
      name: "Kennedy Soccer Complex Dog Park",
      address: "10401 E Dartmouth Ave, Denver, CO 80231",
      lat: 39.6783,
      lng: -104.8653,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: [
        "Open fields",
        "Water fountains",
        "Benches",
        "Waste stations",
        "Separate areas by size",
      ],
      rating: 4.4,
      imageUrl: "",
      description:
        "A spacious fenced dog park with separate areas for large and small dogs. The wide open fields are perfect for dogs who love to sprint, and the mountain views on clear days are a bonus for their humans.",
    },
    {
      name: "Greenway Dog Park",
      address: "2298 S Platte River Dr, Denver, CO 80223",
      lat: 39.7049,
      lng: -105.0044,
      offLeash: true,
      fenced: true,
      acres: 4.0,
      amenities: [
        "River access",
        "Paved trail connections",
        "Water fountains",
        "Agility features",
        "Shade trees",
      ],
      rating: 4.5,
      imageUrl: "",
      description:
        "Situated along the South Platte River trail, this dog park offers water access, open play areas, and connections to Denver's extensive trail network. Dogs love cooling off in the river on hot summer days.",
    },
  ],
};
