export const desMoinesData = {
  city: {
    name: "Des Moines",
    state: "Iowa",
    region: "Midwest",
    lat: 41.5868,
    lng: -93.6250,
    dogFriendlinessScore: 7,
    description:
      "Iowa's capital has quietly become one of the Midwest's most dog-friendly cities with its extensive trail system, a revitalized downtown with patio dining, and a genuine welcoming attitude toward four-legged visitors. The Des Moines River trails and numerous off-leash parks make it a great stop for dogs on a cross-country adventure.",
    heroImage: "https://images.unsplash.com/photo-1565118531796-763e5082d113?w=1200&fit=crop",
    climate: "Humid continental",
    population: 214133,
  },
  hotels: [
    {
      name: "Hotel Fort Des Moines",
      address: "1000 Walnut St, Des Moines, IA 50309",
      lat: 41.5850,
      lng: -93.6260,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a non-refundable pet fee. A historic downtown hotel recently restored to its 1919 grandeur.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking map", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hotelfortdesmoines.com",
      phone: "(515) 243-1161",
    },
    {
      name: "Surety Hotel",
      address: "206 6th Ave, Des Moines, IA 50309",
      lat: 41.5870,
      lng: -93.6300,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of any size welcome with a per-stay fee. A sleek boutique hotel in a restored 1913 building downtown.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Walking access to downtown", "Waste bags", "Treats"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.suretyhotel.com",
      phone: "(515) 985-2000",
    },
    {
      name: "Hilton Des Moines Downtown",
      address: "435 Park St, Des Moines, IA 50309",
      lat: 41.5860,
      lng: -93.6330,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a nightly pet fee. Connected to the skywalk system and near the river.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Pet-friendly rooms", "Water bowls", "Waste bags", "River trail access"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com/en/hotels/dsmhhhh",
      phone: "(515) 241-1456",
    },
    {
      name: "Staybridge Suites Des Moines Downtown",
      address: "515 Walnut St, Des Moines, IA 50309",
      lat: 41.5860,
      lng: -93.6280,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a non-refundable pet fee. Extended-stay suites with full kitchens downtown.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Pet-friendly suites", "Full kitchen", "Waste bags", "Walking areas", "Dog treat at check-in"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.ihg.com/staybridge/hotels/us/en/des-moines",
      phone: "(515) 280-3838",
    },
  ],
  nationalParks: [
    {
      name: "Ledges State Park",
      state: "Iowa",
      lat: 42.0060,
      lng: -93.8780,
      dogPolicy: "Dogs welcome on all trails on a leash. Dramatic sandstone ledges and canyons about 45 minutes from Des Moines.",
      dogTrails: ["Canyon Trail", "Table Rock Trail", "Ledges Trail", "Inspiration Point Trail"],
      restrictions: ["Leash required", "Some trails steep and rocky", "Must clean up after pet"],
      description: "One of Iowa's most scenic state parks features 100-foot sandstone ledges carved by Pease Creek. Dogs can hike the canyon trails and climb to stunning overlooks above the Des Moines River valley.",
      imageUrl: "",
      website: "https://www.iowadnr.gov/Places-to-Go/State-Parks/Iowa-State-Parks/Ledges",
    },
    {
      name: "Big Creek State Park",
      state: "Iowa",
      lat: 41.7830,
      lng: -93.7380,
      dogPolicy: "Dogs welcome on trails and in campgrounds on a leash. A 3,550-acre lake recreation area just north of Des Moines.",
      dogTrails: ["Big Creek Trail", "Neal Smith Trail connection", "Lakeshore Trail"],
      restrictions: ["Leash required", "Not on swimming beach", "Must clean up after pet"],
      description: "Just 20 minutes north of downtown, Big Creek offers a large lake with forested trails and prairie areas. Dogs enjoy the lake views and the connected trail system that links to the Neal Smith National Wildlife Refuge.",
      imageUrl: "",
      website: "https://www.iowadnr.gov/Places-to-Go/State-Parks/Iowa-State-Parks/Big-Creek",
    },
    {
      name: "Neal Smith National Wildlife Refuge",
      state: "Iowa",
      lat: 41.5700,
      lng: -93.2700,
      dogPolicy: "Dogs welcome on the auto tour route on a leash. Not permitted on hiking trails to protect the reconstructed tallgrass prairie.",
      dogTrails: ["Auto Tour Route Walk"],
      restrictions: ["Not permitted on hiking trails", "Leash required on auto route", "Not in visitor center", "Must clean up after pet"],
      description: "About 30 minutes east of Des Moines, this refuge is rebuilding one of the largest tallgrass prairies in the country. While dog trail access is limited, the auto tour provides views of bison and elk on the restored prairie.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/neal-smith",
    },
  ],
  restaurants: [
    {
      name: "Zombie Burger + Drink Lab",
      address: "300 E Grand Ave, Des Moines, IA 50309",
      lat: 41.5910,
      lng: -93.6190,
      cuisine: "Creative Burgers",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the East Village patio. Wildly creative burgers and shakes with horror-themed fun.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.zombieburgerdm.com",
    },
    {
      name: "Exile Brewing Company",
      address: "1514 Walnut St, Des Moines, IA 50309",
      lat: 41.5830,
      lng: -93.6190,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the outdoor beer garden. Des Moines' premier craft brewery with creative seasonal releases.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.exilebrewing.com",
    },
    {
      name: "Centro",
      address: "1003 Locust St, Des Moines, IA 50309",
      lat: 41.5850,
      lng: -93.6250,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the downtown outdoor patio. Upscale Italian dining in the heart of Des Moines.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.centrodesmoines.com",
    },
    {
      name: "Fong's Pizza",
      address: "223 4th St, Des Moines, IA 50309",
      lat: 41.5870,
      lng: -93.6310,
      cuisine: "Pizza & Chinese Fusion",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor seating. A unique pizza joint in a former Chinese restaurant, keeping the original decor.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.fongspizza.com",
    },
    {
      name: "Harbinger",
      address: "2724 Ingersoll Ave, Des Moines, IA 50312",
      lat: 41.5870,
      lng: -93.6590,
      cuisine: "Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the Ingersoll Avenue patio. A James Beard-nominated farm-to-table gem with seasonal tasting menus.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.harbingerdsm.com",
    },
  ],
  cafes: [
    {
      name: "Horizon Line Coffee",
      address: "2201 E University Ave, Des Moines, IA 50317",
      lat: 41.5940,
      lng: -93.5930,
      dogPolicy: "Dogs welcome on the outdoor patio. A specialty roaster in the East Village area with a focus on sourcing.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.horizonlinecoffee.com",
    },
    {
      name: "Scenic Route Bakery",
      address: "350 E Locust St, Des Moines, IA 50309",
      lat: 41.5900,
      lng: -93.6190,
      dogPolicy: "Dogs welcome at the outdoor tables. Artisan baked goods and coffee in the East Village.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.scenicroutebakery.com",
    },
    {
      name: "Mars Cafe",
      address: "2318 University Ave, Des Moines, IA 50311",
      lat: 41.5940,
      lng: -93.6470,
      dogPolicy: "Dog-friendly outdoor seating. A funky neighborhood cafe in the Drake area with strong coffee and creative fare.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marscafe.net",
    },
    {
      name: "Daisy Chain",
      address: "617 Center St, Des Moines, IA 50309",
      lat: 41.5870,
      lng: -93.6260,
      dogPolicy: "Dogs welcome on the patio. A charming flower shop and coffee bar downtown with seasonal drinks.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.daisychaindsm.com",
    },
  ],
  dogParks: [
    {
      name: "Racoon River Off-Leash Dog Park",
      address: "2500 Grand Ave, Des Moines, IA 50312",
      lat: 41.5810,
      lng: -93.6560,
      offLeash: true,
      fenced: true,
      acres: 6,
      amenities: ["River access", "Separate small dog area", "Water stations", "Benches", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "Des Moines' most popular dog park sits along the Raccoon River with water access for dogs who love to swim. The large fenced area includes separate sections and shaded rest areas.",
    },
    {
      name: "Ewing Dog Park",
      address: "901 S Polk Blvd, Des Moines, IA 50315",
      lat: 41.5730,
      lng: -93.6380,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water fountains", "Benches", "Shade trees", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "A well-maintained south-side dog park with separate areas for large and small dogs. The shade trees and water stations keep dogs comfortable during warm Iowa summers.",
    },
    {
      name: "Principal Riverwalk Trail",
      address: "Des Moines River Trail, Des Moines, IA 50309",
      lat: 41.5870,
      lng: -93.6280,
      offLeash: false,
      fenced: false,
      acres: 100,
      amenities: ["Paved trail", "River views", "Downtown access", "Public art", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "The riverwalk trail follows the Des Moines River through downtown with scenic bridges, public art installations, and connections to the broader trail network. Dogs on leash enjoy one of the best urban walks in Iowa.",
    },
    {
      name: "Greenwood-Ashworth Dog Park",
      address: "3400 Grand Ave, Des Moines, IA 50312",
      lat: 41.5800,
      lng: -93.6690,
      offLeash: true,
      fenced: true,
      acres: 4,
      amenities: ["Open fields", "Water stations", "Benches", "Double-gated entry", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      description: "A spacious off-leash park in the Beaverdale neighborhood with wide open fields for running. The well-fenced area provides plenty of room for dogs to stretch their legs.",
    },
  ],
};
