export const doorCountyData = {
  city: {
    name: "Door County",
    state: "Wisconsin",
    region: "Midwest",
    lat: 44.8341,
    lng: -87.3770,
    dogFriendlinessScore: 7,
    description:
      "Wisconsin's thumb-shaped peninsula jutting into Lake Michigan is a dog-friendly escape of cherry orchards, lighthouses, and limestone bluffs. With eleven charming villages, miles of shoreline trails, and a fish boil tradition that will make any hound howl with delight, Door County is the Midwest's answer to Cape Cod — only friendlier to four-legged visitors.",
    heroImage: "https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 30195,
  },

  hotels: [
    {
      name: "Landmark Resort",
      address: "7643 Hillside Rd, Egg Harbor, WI 54209",
      lat: 44.9958,
      lng: -87.2842,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select rooms with a per-night fee. Stunning bluff-top resort overlooking Green Bay.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Bay views", "Indoor pool", "Walking trails", "Dog bowls on request", "Grassy play areas"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.thelandmarkresort.com",
      phone: "(920) 868-3205",
    },
    {
      name: "Homestead Suites",
      address: "8096 Hwy 57, Baileys Harbor, WI 54202",
      lat: 45.0668,
      lng: -87.1232,
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly suites with full kitchens and private decks. Your pup gets the full Door County cottage experience.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Full kitchen", "Private deck", "Wooded grounds", "Dog bed", "Near Ridges Sanctuary"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.homesteadsuites.com",
      phone: "(920) 839-9811",
    },
    {
      name: "Country House Resort",
      address: "2468 Sunnyside Rd, Sister Bay, WI 54234",
      lat: 45.1820,
      lng: -87.1245,
      priceRange: "$$" as const,
      dogPolicy: "Well-behaved dogs welcome in designated rooms. Waterfront location with beach access on Green Bay.",
      maxDogWeight: 75,
      petFee: 35,
      amenities: ["Waterfront", "Beach access", "Walking paths", "Dog bowls", "Kayak rentals"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.countryhouseresort.com",
      phone: "(920) 854-4551",
    },
    {
      name: "Edgewater Resort",
      address: "10040 WI-42, Ephraim, WI 54211",
      lat: 45.1548,
      lng: -87.1680,
      priceRange: "$$$" as const,
      dogPolicy: "Pet-friendly cottages with bay views. Dogs enjoy the grounds while you enjoy the sunsets.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Cottages", "Bay views", "Private beach", "Grassy areas", "Sunset watching"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.edge-waterresort.com",
      phone: "(920) 854-2734",
    },
    {
      name: "Open Hearth Lodge",
      address: "1169 S Bay Shore Dr, Sister Bay, WI 54234",
      lat: 45.1760,
      lng: -87.1265,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome. A family-friendly lodge surrounded by 40 acres of Door County woodland.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["40 acres of grounds", "Walking trails", "Indoor pool", "Fireplace rooms", "Dog bowls on request"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.openhearth-lodge.com",
      phone: "(920) 854-4890",
    },
  ],

  nationalParks: [
    {
      name: "Apostle Islands National Lakeshore",
      state: "Wisconsin",
      lat: 46.9385,
      lng: -90.6593,
      dogPolicy: "Leashed dogs welcome on all mainland trails and most island trails. One of the most dog-friendly NPS sites in the Midwest.",
      dogTrails: [
        "Lakeshore Trail (mainland)",
        "Meyers Beach sea caves trail",
        "Sand Point Trail",
        "Stockton Island Tombolo Trail",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Not allowed on guided tours of sea caves",
        "Not allowed in buildings",
        "Some island beaches restricted during nesting season",
      ],
      description:
        "A collection of 21 islands on Lake Superior with sea caves, lighthouses, and pristine beaches. While a four-hour drive from Door County, leashed dogs are welcome on most trails, making it worth the journey for a truly wild Great Lakes experience.",
      imageUrl: "",
      website: "https://www.nps.gov/apis",
    },
    {
      name: "Ice Age National Scenic Trail",
      state: "Wisconsin",
      lat: 43.8000,
      lng: -89.4000,
      dogPolicy: "Leashed dogs welcome on most segments of this 1,200-mile trail following the edge of the last glaciation.",
      dogTrails: [
        "Potawatomi State Park segment (Door County)",
        "Ahnapee State Trail segment",
        "Devil's Lake segment",
        "Kettle Moraine segments",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Some state park segments may have additional rules",
        "Check specific segment regulations",
      ],
      description:
        "Wisconsin's 1,200-mile Ice Age Trail traces the edge of the last glacier. The Door County segment through Potawatomi State Park offers stunning bluff-top views of Sturgeon Bay. Leashed dogs are welcome companions on this geological journey.",
      imageUrl: "",
      website: "https://www.nps.gov/iatr",
    },
    {
      name: "Saint Croix National Scenic Riverway",
      state: "Wisconsin",
      lat: 45.3890,
      lng: -92.6420,
      dogPolicy: "Leashed dogs welcome along the riverway, in campgrounds, and on river access points.",
      dogTrails: [
        "Riverside trails at various access points",
        "Campground loops",
        "Sandbar beaches along the river",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Dogs must be in or on a watercraft if on the river",
        "Not allowed in buildings",
      ],
      description:
        "Over 200 miles of wild and scenic river through Wisconsin's forests offer sandbar beaches, riverside trails, and canoe camping with your dog. A longer drive from Door County but a quintessential Midwest wilderness adventure.",
      imageUrl: "",
      website: "https://www.nps.gov/sacn",
    },
  ],

  restaurants: [
    {
      name: "The Cookery",
      address: "4135 WI-42, Fish Creek, WI 54212",
      lat: 45.1280,
      lng: -87.2395,
      cuisine: "Farm-to-Table American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the garden patio. A Fish Creek fine dining tradition with seasonal, local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.cookeryfishcreek.com",
    },
    {
      name: "Wild Tomato",
      address: "4023 WI-42, Fish Creek, WI 54212",
      lat: 45.1275,
      lng: -87.2402,
      cuisine: "Wood-Fired Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Wood-fired pizza with local toppings like cherry sausage.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.wildtomatopizza.com",
    },
    {
      name: "Fred & Fuzzy's Waterfront Bar & Grill",
      address: "10987 WI-42, Sister Bay, WI 54234",
      lat: 45.1870,
      lng: -87.1190,
      cuisine: "Casual American",
      priceRange: "$$" as const,
      dogPolicy: "Extremely dog-friendly waterfront spot. Dogs are practically required at this beloved Sister Bay hangout.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.fredandfuzzys.com",
    },
    {
      name: "Door County Brewing Co.",
      address: "8099 WI-57, Baileys Harbor, WI 54202",
      lat: 45.0670,
      lng: -87.1228,
      cuisine: "Brewery & Taproom",
      priceRange: "$$" as const,
      dogPolicy: "Large dog-friendly outdoor area with live music. Craft ales and a rotating food truck lineup.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.doorcountybrewingco.com",
    },
    {
      name: "The White Gull Inn",
      address: "4225 Main St, Fish Creek, WI 54212",
      lat: 45.1285,
      lng: -87.2388,
      cuisine: "Traditional American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome at outdoor tables during the famous fish boils. A Door County tradition since 1896.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.whitegullinn.com",
    },
    {
      name: "Al Johnson's Swedish Restaurant",
      address: "10698 N Bay Shore Dr, Sister Bay, WI 54234",
      lat: 45.1850,
      lng: -87.1220,
      cuisine: "Swedish",
      priceRange: "$$" as const,
      dogPolicy: "Outdoor patio seating for guests with dogs. Famous for goats grazing on the grass roof — your dog may do a double take.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.aljohnsons.com",
    },
    {
      name: "Harbor Fish Market & Grille",
      address: "8080 WI-57, Baileys Harbor, WI 54202",
      lat: 45.0665,
      lng: -87.1235,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio. Fresh Lake Michigan fish alongside Door County cherry dishes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.harborfishmarket-grille.com",
    },
    {
      name: "Base Camp Coffee House & Eatery",
      address: "4124 WI-42, Fish Creek, WI 54212",
      lat: 45.1278,
      lng: -87.2398,
      cuisine: "Cafe & Breakfast",
      priceRange: "$" as const,
      dogPolicy: "Patio seating welcomes leashed dogs. Coffee, breakfast sandwiches, and cherry scones to start your Door County day.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
  ],

  cafes: [
    {
      name: "Discourse Coffee",
      address: "8082 WI-57, Baileys Harbor, WI 54202",
      lat: 45.0666,
      lng: -87.1233,
      dogPolicy: "Dog-friendly outdoor seating in Baileys Harbor. Third-wave coffee in Door County's quietest village.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.discoursecoffee.com",
    },
    {
      name: "Not Licked Yet Frozen Custard",
      address: "4054 WI-42, Fish Creek, WI 54212",
      lat: 45.1277,
      lng: -87.2400,
      dogPolicy: "Walk-up window with outdoor benches — perfect for dogs. Pup cups of vanilla custard available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.notlickedyet.com",
    },
    {
      name: "Sister Bay Bowl & Cafe",
      address: "10640 N Bay Shore Dr, Sister Bay, WI 54234",
      lat: 45.1845,
      lng: -87.1225,
      dogPolicy: "Outdoor seating area for guests with dogs. Coffee and classic cafe fare in the heart of Sister Bay.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "",
    },
    {
      name: "Cherry Republic",
      address: "10600 N Bay Shore Dr, Sister Bay, WI 54234",
      lat: 45.1840,
      lng: -87.1230,
      dogPolicy: "Outdoor tasting area where leashed dogs are welcome. Everything cherry — from cherry salsa to cherry soda.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cherryrepublic.com",
    },
    {
      name: "Bier Zot",
      address: "10576 N Bay Shore Dr, Sister Bay, WI 54234",
      lat: 45.1838,
      lng: -87.1232,
      dogPolicy: "Belgian beer cafe with an outdoor terrace welcoming dogs. Waffles, frites, and abbey ales.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bierzot.com",
    },
  ],

  dogParks: [
    {
      name: "Peninsula State Park",
      address: "9462 Shore Rd, Fish Creek, WI 54212",
      lat: 45.1550,
      lng: -87.2280,
      offLeash: false,
      fenced: false,
      acres: 3776.0,
      amenities: ["20+ miles of trails", "Beach access", "Eagle Bluff lighthouse", "Bike trails", "Campgrounds"],
      rating: 4.8,
      imageUrl: "",
      description:
        "Door County's crown jewel offers 3,776 acres of forests, bluffs, and shoreline. Leashed dogs can explore over 20 miles of trails with views of Eagle Bluff, swim at Nicolet Beach, and camp under the stars. The sunset from Eagle Tower is legendary.",
    },
    {
      name: "Potawatomi State Park",
      address: "3740 Park Dr, Sturgeon Bay, WI 54235",
      lat: 44.8625,
      lng: -87.3150,
      offLeash: false,
      fenced: false,
      acres: 1225.0,
      amenities: ["Bluff-top trails", "Tower overlook", "Fishing pier", "Campground", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Dramatic limestone bluffs overlooking Sturgeon Bay with trails through dense forest and along the shoreline. Leashed dogs can hike to the observation tower for panoramic views of the bay and distant islands.",
    },
    {
      name: "Whitefish Dunes State Park",
      address: "3275 S Clark Lake Rd, Sturgeon Bay, WI 54235",
      lat: 44.9295,
      lng: -87.1862,
      offLeash: false,
      fenced: false,
      acres: 867.0,
      amenities: ["Sand dunes", "Beach", "Nature trails", "Boardwalks", "Visitor center"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Wisconsin's largest sand dunes along Lake Michigan with trails through forests and along the shore. Leashed dogs can explore the Old Baldy trail for dune-top views and enjoy the longest sand beach in Door County.",
    },
    {
      name: "Ellison Bay Community Dog Park",
      address: "Garrett Bay Rd, Ellison Bay, WI 54210",
      lat: 45.2525,
      lng: -87.0735,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Water station", "Shade trees", "Benches", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A fenced off-leash park at the tip of the peninsula where local and visiting dogs socialize with Lake Michigan breezes. A great spot to let your pup burn off energy before a Door County fish boil dinner.",
    },
    {
      name: "Newport State Park",
      address: "475 County Highway NP, Ellison Bay, WI 54210",
      lat: 45.2350,
      lng: -86.9985,
      offLeash: false,
      fenced: false,
      acres: 2373.0,
      amenities: ["Wilderness trails", "Lake Michigan beach", "Backcountry camping", "Dark sky park", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "Wisconsin's only designated wilderness state park offers rugged trails through boreal forest to wild Lake Michigan beaches. Leashed dogs can explore miles of untouched shoreline and camp under some of the darkest skies in the Midwest.",
    },
  ],
};
