export const driggsData = {
  city: {
    name: "Driggs",
    state: "Idaho",
    region: "Mountain West",
    lat: 43.7233,
    lng: -111.1113,
    dogFriendlinessScore: 8,
    description:
      "Driggs sits on the quiet side of the Teton Range, offering dramatic Grand Teton views without the crowds of Jackson Hole. Dogs love the Teton Valley for its extensive trail networks, off-leash opportunities in the Caribou-Targhee National Forest, and a friendly small-town community that treats every dog like a local.",
    heroImage: "https://images.unsplash.com/photo-1508389377389-918442e3626b?w=1200&fit=crop",
    climate: "Subarctic continental",
    population: 2110,
  },

  hotels: [
    {
      name: "Teton Valley Lodge",
      address: "379 Adams St, Driggs, ID 83422",
      lat: 43.7240,
      lng: -111.1100,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in cabin suites with advance notice. Fly fishing lodge with Teton views.",
      maxDogWeight: 60,
      petFee: 50,
      amenities: ["Cabin porches", "Teton views", "Dog bed", "River access nearby", "Walking paths"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.tetonvalleylodge.com",
      phone: "(208) 354-2386",
    },
    {
      name: "Fin Hotel & Lodge",
      address: "65 S Main St, Driggs, ID 83422",
      lat: 43.7230,
      lng: -111.1115,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a per-night pet fee. Modern mountain hotel in downtown Driggs.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Dog bed", "Water bowls", "Downtown location", "Near trails", "Teton views"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.finhotelandlodge.com",
      phone: "(208) 354-2500",
    },
    {
      name: "Best Western Teton West",
      address: "476 N Main St, Driggs, ID 83422",
      lat: 43.7265,
      lng: -111.1118,
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome with a per-night fee. Comfortable rooms with Grand Teton views.",
      maxDogWeight: 80,
      petFee: 20,
      amenities: ["Pet waste stations", "Grassy areas", "Teton views", "Water bowls at front desk"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(208) 354-2363",
    },
    {
      name: "Grand Targhee Resort Lodging",
      address: "3300 Ski Hill Rd, Alta, WY 83414",
      lat: 43.7870,
      lng: -110.9600,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in select slope-side rooms during summer. Ski resort at the base of the Tetons.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Mountain trail access", "Dog bed", "Water bowls", "Hiking from door", "Alpine meadows"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.grandtarghee.com",
      phone: "(307) 353-2300",
    },
  ],

  nationalParks: [
    {
      name: "Caribou-Targhee National Forest",
      state: "Idaho",
      lat: 43.7500,
      lng: -111.0500,
      dogPolicy: "Dogs welcome on all trails. Voice control in backcountry; leash in developed areas.",
      dogTrails: ["Teton Canyon Trail", "Alaska Basin Trail", "Table Mountain Trail", "South Leigh Creek Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on trails",
        "Not allowed in developed swim areas",
      ],
      description:
        "The Teton Range's west slope offers spectacular hiking with views of the Grand Teton from the back side. The trails climb through wildflower meadows to alpine basins and passes with some of the most dramatic mountain scenery in the West.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/caribou-targhee",
    },
    {
      name: "Grand Teton National Park (West Side Access)",
      state: "Wyoming",
      lat: 43.7904,
      lng: -110.6818,
      dogPolicy: "Dogs NOT allowed on trails or in the backcountry. Permitted on roads, in parking areas, and in campgrounds only.",
      dogTrails: ["No dog-friendly trails"],
      restrictions: [
        "No dogs on any trails",
        "Must be on leash (6 ft max) at all times",
        "Allowed only on roads and in parking areas",
        "Not allowed in buildings",
      ],
      description:
        "While Grand Teton National Park restricts dogs severely, the view of the Tetons from the Idaho side and the Caribou-Targhee trails provide a superior dog-friendly alternative with equally stunning scenery.",
      imageUrl: "",
      website: "https://www.nps.gov/grte",
    },
    {
      name: "Jedediah Smith Wilderness",
      state: "Wyoming",
      lat: 43.7500,
      lng: -110.9500,
      dogPolicy: "Dogs welcome under voice control on all wilderness trails. The west slope wilderness of the Tetons.",
      dogTrails: ["Alaska Basin via Teton Shelf", "South Leigh Lake Trail", "Moose Meadows Trail"],
      restrictions: [
        "Must be under voice control",
        "Pack out all waste",
        "Be aware of bears and moose",
      ],
      description:
        "The wilderness on the west slope of the Tetons offers access to dramatic alpine terrain without the crowds of the national park. Dogs can hike off-leash under voice control to stunning alpine basins at the foot of the Grand Teton.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/caribou-targhee",
    },
  ],

  restaurants: [
    {
      name: "Forage Bistro & Lounge",
      address: "285 Little Ave, Driggs, ID 83422",
      lat: 43.7228,
      lng: -111.1105,
      cuisine: "Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the garden patio. Seasonal farm-to-table cuisine with Teton Valley ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.foragebistro.com",
    },
    {
      name: "Tatanka Tavern",
      address: "18 N Main St, Driggs, ID 83422",
      lat: 43.7235,
      lng: -111.1112,
      cuisine: "American Tavern",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio with mountain views. Craft cocktails and elevated pub fare.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tatankatavern.com",
    },
    {
      name: "Pendl's Bakery & Cafe",
      address: "40 Depot St, Driggs, ID 83422",
      lat: 43.7230,
      lng: -111.1120,
      cuisine: "Austrian Bakery & Cafe",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Austrian-style bakery with strudels and espresso.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.pendlsbakery.com",
    },
    {
      name: "Agave Teton Mexican Grill",
      address: "310 N Main St, Driggs, ID 83422",
      lat: 43.7255,
      lng: -111.1115,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the patio. Authentic Mexican in a mountain town setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.agaveteton.com",
    },
    {
      name: "The Royal Wolf",
      address: "63 Depot St, Driggs, ID 83422",
      lat: 43.7228,
      lng: -111.1118,
      cuisine: "Pub & American",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Local gathering spot with live music and pub food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.theroyalwolf.com",
    },
  ],

  cafes: [
    {
      name: "Provisions",
      address: "36 S Main St, Driggs, ID 83422",
      lat: 43.7228,
      lng: -111.1113,
      dogPolicy: "Dogs welcome on the outdoor patio. Local market and cafe with espresso and baked goods.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.provisionsdriggs.com",
    },
    {
      name: "Citizen 33 Coffee",
      address: "72 S Main St, Driggs, ID 83422",
      lat: 43.7225,
      lng: -111.1113,
      dogPolicy: "Outdoor seating welcomes dogs. Third-wave coffee with Teton views from the patio.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.citizen33coffee.com",
    },
    {
      name: "Rise Coffee House",
      address: "20 N Main St, Driggs, ID 83422",
      lat: 43.7236,
      lng: -111.1112,
      dogPolicy: "Dog-friendly patio area. Cozy coffee house in the heart of Driggs.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.risecoffeehouse.com",
    },
    {
      name: "Peaked Sports & Espresso",
      address: "70 E Little Ave, Driggs, ID 83422",
      lat: 43.7230,
      lng: -111.1100,
      dogPolicy: "Leashed dogs welcome at the outdoor seating. Gear shop meets coffee bar.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.peakedsports.com",
    },
  ],

  dogParks: [
    {
      name: "Driggs City Dog Park",
      address: "W Center St, Driggs, ID 83422",
      lat: 43.7220,
      lng: -111.1140,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Water station", "Waste bags", "Benches", "Teton views"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Driggs' fenced off-leash dog park with unobstructed Grand Teton views. A perfect spot for dogs to play while their owners gaze at the most dramatic mountain skyline in the lower 48.",
    },
    {
      name: "Teton Creek Trail",
      address: "Teton Creek Trailhead, Driggs, ID 83422",
      lat: 43.7500,
      lng: -111.0800,
      offLeash: true,
      fenced: false,
      acres: 60.0,
      amenities: ["Mountain trails", "Creek access", "Wildflowers", "Teton views", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A trail climbing into the Tetons from the west side with creek crossings, wildflower meadows, and jaw-dropping mountain scenery. Dogs can be off-leash under voice control on this spectacular forest service trail.",
    },
    {
      name: "Driggs Community Pathway",
      address: "Main St, Driggs, ID 83422",
      lat: 43.7235,
      lng: -111.1115,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Paved path", "Teton views", "Benches", "Waste stations", "Multiple access points"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A paved pathway connecting Driggs to Victor through the Teton Valley with Grand Teton views the entire way. Leashed dogs enjoy the flat, easy walking with the most stunning mountain backdrop imaginable.",
    },
    {
      name: "Teton Springs Resort Trails",
      address: "10 Warm Creek Ln, Victor, ID 83455",
      lat: 43.6100,
      lng: -111.1100,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Nature trails", "Creek access", "Wildlife viewing", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Open trails through the Teton Springs area south of Driggs with creek access and Teton views. Leashed dogs enjoy the gentle paths through sage flats and riparian areas.",
    },
  ],
};
