export const duluthData = {
  city: {
    name: "Duluth",
    state: "Minnesota",
    region: "Midwest",
    lat: 46.7867,
    lng: -92.1005,
    dogFriendlinessScore: 7,
    description:
      "Perched on the rugged shores of Lake Superior, Duluth is a northern paradise where dogs can feel the spray of the world's largest freshwater lake and explore endless boreal forests. With a vibrant craft brewery scene that welcomes four-legged patrons, miles of lakefront trails, and a community that treats dogs like honorary citizens, Duluth is where every pup can channel their inner sled dog.",
    heroImage: "https://images.unsplash.com/photo-1517483000871-1dbf64a6e1c6?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 90880,
  },

  hotels: [
    {
      name: "Pier B Resort",
      address: "800 W Railroad St, Duluth, MN 55802",
      lat: 46.7810,
      lng: -92.1072,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in designated pet-friendly rooms with a nightly fee. Lakefront resort with stunning harbor views.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Lakefront access", "Dog bed", "Water bowls", "Walking paths", "Near Lakewalk"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.pierbresort.com",
      phone: "(218) 481-8888",
    },
    {
      name: "The Inn on Lake Superior",
      address: "350 Canal Park Dr, Duluth, MN 55802",
      lat: 46.7825,
      lng: -92.0960,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a per-night pet fee. Steps from Canal Park and the Lakewalk.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Lake views", "Near Lakewalk", "Pet relief area", "Waste bags", "Treats at check-in"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.theinnonlakesuperior.com",
      phone: "(218) 726-1111",
    },
    {
      name: "South Pier Inn",
      address: "701 S Lake Ave, Duluth, MN 55802",
      lat: 46.7805,
      lng: -92.0930,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome in select rooms. Boutique inn right on the ship canal with Aerial Lift Bridge views.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Bridge views", "Dog bed", "Gourmet treats", "Canal Park walking", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.southpierinn.com",
      phone: "(218) 786-9007",
    },
    {
      name: "Comfort Suites Canal Park",
      address: "408 Canal Park Dr, Duluth, MN 55802",
      lat: 46.7828,
      lng: -92.0950,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a one-time fee. Suite-style rooms with space for the whole pack.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Suite rooms", "Indoor pool", "Pet relief area", "Waste bags", "Free breakfast"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.choicehotels.com",
      phone: "(218) 727-1378",
    },
    {
      name: "Larsmont Cottages on Lake Superior",
      address: "596 Larsmont Way, Two Harbors, MN 55616",
      lat: 47.0165,
      lng: -91.6935,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in select cottages with a pet fee. Private lakefront cabins with direct Superior access.",
      maxDogWeight: 0,
      petFee: 100,
      amenities: ["Private lakefront", "Full kitchen", "Fireplace", "Hiking trails", "Dog-friendly beach"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.larsmontcottages.com",
      phone: "(218) 834-6603",
    },
  ],

  nationalParks: [
    {
      name: "Voyageurs National Park",
      state: "Minnesota",
      lat: 48.4839,
      lng: -92.8279,
      dogPolicy: "Leashed dogs welcome on designated trails and in developed campgrounds. Not allowed on backcountry trails or beaches.",
      dogTrails: ["Oberholtzer Trail", "Blind Ash Bay Trail", "Rainy Lake Recreation Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on backcountry trails",
        "Not allowed on swimming beaches",
        "Not allowed in boats operated by NPS",
      ],
      description:
        "About 4 hours north of Duluth, this water-based park of interconnected lakes and islands offers select trails where leashed dogs can explore the boreal forest. The Oberholtzer Trail near the visitor center provides a taste of the northern wilderness.",
      imageUrl: "",
      website: "https://www.nps.gov/voya",
    },
    {
      name: "Grand Portage National Monument",
      state: "Minnesota",
      lat: 47.9600,
      lng: -89.6850,
      dogPolicy: "Leashed dogs welcome on the Grand Portage trail and monument grounds. A historic fur trade route along Lake Superior.",
      dogTrails: ["Grand Portage Trail (8.5 miles)", "Heritage Center grounds"],
      restrictions: [
        "Must be on leash",
        "Not allowed inside historic buildings",
        "Must stay on designated trails",
      ],
      description:
        "At the tip of Minnesota's Arrowhead, this monument preserves the historic 8.5-mile portage trail used by fur traders. Leashed dogs can hike the forested trail between Lake Superior and the Pigeon River.",
      imageUrl: "",
      website: "https://www.nps.gov/grpo",
    },
    {
      name: "Apostle Islands National Lakeshore",
      state: "Wisconsin",
      lat: 46.9200,
      lng: -90.6600,
      dogPolicy: "Leashed dogs welcome on trails and beaches on the mainland unit. Limited access on some islands.",
      dogTrails: ["Lakeshore Trail", "Meyers Beach to Sea Caves", "Sand Point Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed in visitor center",
        "Check individual island rules",
        "Not allowed on guided tours",
      ],
      description:
        "About 90 miles east of Duluth along the Wisconsin shore, this stunning collection of 21 islands and mainland features sea caves, sandstone cliffs, and pristine beaches. Leashed dogs can explore the mainland trails and beaches, including the iconic route to the sea caves.",
      imageUrl: "",
      website: "https://www.nps.gov/apis",
    },
  ],

  restaurants: [
    {
      name: "Northern Waters Smokehaus",
      address: "394 S Lake Ave, Duluth, MN 55802",
      lat: 46.7820,
      lng: -92.0938,
      cuisine: "Smoked Meats & Deli",
      priceRange: "$" as const,
      dogPolicy: "Grab a legendary smoked meat sandwich and eat outside with your pup at the Canal Park benches.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.8,
      imageUrl: "",
      website: "https://www.northernwaterssmokehaus.com",
    },
    {
      name: "Fitger's Brewhouse",
      address: "600 E Superior St, Duluth, MN 55802",
      lat: 46.7888,
      lng: -92.0890,
      cuisine: "Brewery & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio overlooking Lake Superior. Local craft beer and hearty pub food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.fitgersbrewhouse.com",
    },
    {
      name: "Hoops Brewing",
      address: "325 S Lake Ave, Duluth, MN 55802",
      lat: 46.7815,
      lng: -92.0938,
      cuisine: "Brewery & Pub",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly taproom and outdoor seating in Canal Park. Award-winning craft beers.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hoopsbrewing.com",
    },
    {
      name: "Lake Avenue Restaurant",
      address: "394 Lake Ave S, Duluth, MN 55802",
      lat: 46.7818,
      lng: -92.0940,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor terrace with lake views. Upscale dining featuring local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.lakeavenuerestaurant.com",
    },
    {
      name: "Grandma's Saloon & Grill",
      address: "522 S Lake Ave, Duluth, MN 55802",
      lat: 46.7808,
      lng: -92.0935,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the waterfront patio. A Duluth institution since 1976 with massive portions.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.grandmasrestaurants.com",
    },
    {
      name: "OMC Smokehouse",
      address: "1909 W Superior St, Duluth, MN 55806",
      lat: 46.7590,
      lng: -92.1280,
      cuisine: "Barbecue",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly outdoor picnic area. Texas-style BBQ smoked in-house daily until it runs out.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.omcsmokehouse.com",
    },
    {
      name: "Vikre Distillery Cocktail Room",
      address: "525 S Lake Ave, Duluth, MN 55802",
      lat: 46.7808,
      lng: -92.0932,
      cuisine: "Craft Cocktails & Small Plates",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome in the outdoor area. Craft spirits made with Lake Superior water.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.vikredistillery.com",
    },
    {
      name: "At Sara's Table Chester Creek Cafe",
      address: "1902 E 8th St, Duluth, MN 55812",
      lat: 46.7810,
      lng: -92.0685,
      cuisine: "American Farm-to-Table",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the garden patio. Organic and locally sourced comfort food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.astcc.net",
    },
  ],

  cafes: [
    {
      name: "Duluth Coffee Company",
      address: "105 E Superior St, Duluth, MN 55802",
      lat: 46.7870,
      lng: -92.0975,
      dogPolicy: "Leashed dogs welcome at the outdoor sidewalk tables downtown. Freshly roasted single-origin coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.duluthcoffeecompany.com",
    },
    {
      name: "Alakef Coffee Roasters",
      address: "301 W 1st St, Duluth, MN 55802",
      lat: 46.7858,
      lng: -92.1040,
      dogPolicy: "Dog-friendly patio seating. Roasting coffee in Duluth since 1990 with a focus on fair trade beans.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.alakef.com",
    },
    {
      name: "Isles Bun & Coffee",
      address: "394 S Lake Ave #106, Duluth, MN 55802",
      lat: 46.7820,
      lng: -92.0940,
      dogPolicy: "Grab a famous caramel pecan roll and enjoy it at the Canal Park outdoor tables with your pup.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.islesbun.com",
    },
    {
      name: "Brewhouse Coffee & Tea",
      address: "601 W Superior St, Duluth, MN 55802",
      lat: 46.7862,
      lng: -92.1075,
      dogPolicy: "Patio tables welcome leashed dogs. A relaxed spot for espresso drinks and fresh pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.brewhousecoffeedlh.com",
    },
    {
      name: "Vintage Italian Pizza & Coffee",
      address: "111 E Superior St, Duluth, MN 55802",
      lat: 46.7872,
      lng: -92.0972,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Italian espresso, pizza by the slice, and gelato.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.vintageitalianduluth.com",
    },
  ],

  dogParks: [
    {
      name: "Hartley Park Off-Leash Dog Area",
      address: "3001 Woodland Ave, Duluth, MN 55803",
      lat: 46.8140,
      lng: -92.0810,
      offLeash: true,
      fenced: false,
      acres: 10.0,
      amenities: ["Forest trails", "Creek access", "Open meadow", "Parking", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A beloved off-leash area within Hartley Nature Center featuring wooded trails, open meadows, and a creek where dogs can splash and play. The boreal forest setting makes every romp feel like a wilderness expedition.",
    },
    {
      name: "Lester Park Off-Leash Area",
      address: "6100 E Superior St, Duluth, MN 55804",
      lat: 46.8092,
      lng: -92.0105,
      offLeash: true,
      fenced: false,
      acres: 8.0,
      amenities: ["River access", "Forest trails", "Open fields", "Waste stations", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A scenic off-leash area along the Lester River where dogs can wade in the water, explore forest trails, and bound through open fields. The river provides natural cooling on warm summer days.",
    },
    {
      name: "Brighton Beach Dog Area",
      address: "4601 N Shore Dr, Duluth, MN 55804",
      lat: 46.8305,
      lng: -92.0185,
      offLeash: true,
      fenced: false,
      acres: 3.0,
      amenities: ["Lake Superior beach access", "Rocky shoreline", "Parking", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Where dogs meet Lake Superior. This rocky beach area allows off-leash dogs to wade into the world's largest freshwater lake. Watching your pup discover the endless water is pure magic, but beware of cold temps even in summer.",
    },
    {
      name: "Keene Creek Dog Park",
      address: "525 W Skyline Pkwy, Duluth, MN 55806",
      lat: 46.7715,
      lng: -92.1250,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Separate small dog zone", "Water fountain", "Benches", "Shade trees", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A well-maintained fenced dog park with separate areas for large and small dogs. Perched on the hillside, it offers views of the city and harbor while your pup plays off-leash in a safe enclosure.",
    },
    {
      name: "Lakewalk Trail",
      address: "S Lake Ave to 26th Ave E, Duluth, MN 55802",
      lat: 46.7860,
      lng: -92.0900,
      offLeash: false,
      fenced: false,
      acres: 25.0,
      amenities: ["Paved path", "Lake views", "Benches", "Public restrooms", "Waste stations", "Water fountains"],
      rating: 4.7,
      imageUrl: "",
      description:
        "Duluth's crown jewel: a 7.5-mile paved trail running along the shores of Lake Superior from Canal Park through gorgeous lakeside neighborhoods. Leashed dogs adore the sights, sounds, and smells of the greatest Great Lake.",
    },
  ],
};
