export const durangoData = {
  city: {
    name: "Durango",
    state: "Colorado",
    region: "Mountain West",
    lat: 37.2753,
    lng: -107.8801,
    dogFriendlinessScore: 8,
    description:
      "Nestled in the San Juan Mountains at 6,500 feet, Durango is a high-altitude playground where dogs live their best adventure lives. From historic narrow-gauge train rides (yes, dogs can ride!) to rushing rivers perfect for splashing, this Old West town pairs rugged mountain trails with a lively downtown packed with dog-friendly patios and craft breweries. If your pup loves hiking, this is the motherlode.",
    heroImage: "https://images.unsplash.com/photo-1570641963303-92ce4845ed4c?w=1200&fit=crop",
    climate: "Semi-arid",
    population: 19071,
  },
  hotels: [
    {
      name: "The Rochester Hotel",
      address: "726 E 2nd Ave, Durango, CO 81301",
      lat: 37.2742,
      lng: -107.878,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome. Complimentary dog bed, bowls, and treats. Large courtyard for leashed walks.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Dog beds", "Treats at check-in", "Courtyard", "Close to riverwalk", "Pet sitting referrals"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.rochesterhotel.com",
      phone: "(970) 385-1920",
    },
    {
      name: "Strater Hotel",
      address: "699 Main Ave, Durango, CO 81301",
      lat: 37.2738,
      lng: -107.8798,
      priceRange: "$$$" as const,
      dogPolicy: "Pets welcome in select rooms. Two-pet limit. Dogs must be crated when left unattended.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Historic Victorian rooms", "Downtown location", "Dog-friendly saloon patio", "Walking distance to trails"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.strater.com",
      phone: "(970) 247-4431",
    },
    {
      name: "DoubleTree by Hilton Durango",
      address: "501 Camino Del Rio, Durango, CO 81301",
      lat: 37.2684,
      lng: -107.8823,
      priceRange: "$$" as const,
      dogPolicy: "Pets up to 75 lbs welcome. Non-refundable cleaning fee. Riverside walking path adjacent to hotel.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Riverside trail", "Pet relief area", "Waste stations", "Indoor pool (humans only)"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(970) 259-6580",
    },
    {
      name: "Homewood Suites by Hilton Durango",
      address: "15 Town Plaza, Durango, CO 81301",
      lat: 37.2762,
      lng: -107.8812,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a $75 non-refundable fee. Grassy area available for exercise.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Full kitchen suites", "Grassy pet area", "Evening social", "Complimentary breakfast"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(970) 259-4800",
    },
    {
      name: "General Palmer Hotel",
      address: "567 Main Ave, Durango, CO 81301",
      lat: 37.2731,
      lng: -107.8801,
      priceRange: "$$$" as const,
      dogPolicy: "Small to medium dogs welcome in designated pet rooms. Treats and water bowl provided.",
      maxDogWeight: 40,
      petFee: 30,
      amenities: ["Historic charm", "Downtown location", "Dog treats", "Concierge trail recommendations"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.generalpalmerhotel.com",
      phone: "(970) 247-4747",
    },
  ],
  nationalParks: [
    {
      name: "Mesa Verde National Park",
      state: "Colorado",
      lat: 37.1838,
      lng: -108.4887,
      dogPolicy: "Dogs are restricted to campgrounds, parking areas, and a few paved roads. Not allowed on trails or in archaeological sites.",
      dogTrails: ["Campground loop paths"],
      restrictions: ["No dogs on any hiking trails", "No dogs in cliff dwellings", "Must be leashed at all times", "Cannot be left unattended in vehicles"],
      description:
        "While the ancient cliff dwellings are off-limits to four-legged visitors, Mesa Verde still offers stunning mesa-top views from dog-friendly pullouts. Pro tip: take turns with your travel partner so everyone gets to explore — including your pup who will enjoy the piñon-scented campground strolls.",
      imageUrl: "",
      website: "https://www.nps.gov/meve",
    },
    {
      name: "San Juan National Forest",
      state: "Colorado",
      lat: 37.4667,
      lng: -107.7833,
      dogPolicy: "Dogs welcome on all national forest trails. Voice control required on most trails; leash required in developed recreation areas.",
      dogTrails: ["Colorado Trail (Durango segment)", "Hermosa Creek Trail", "Animas Mountain Trail", "Engineer Mountain Trail"],
      restrictions: ["Leash in campgrounds and picnic areas", "Clean up after your pet", "Respect wildlife"],
      description:
        "Over 1.8 million acres of alpine meadows, dense forests, and jaw-dropping peaks where your dog can hike until their tail goes limp with happy exhaustion. The Colorado Trail segment out of Durango is an iconic thru-hike, and Hermosa Creek offers swimming holes that will make your water-loving pup lose their mind.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/sanjuan",
    },
    {
      name: "Weminuche Wilderness",
      state: "Colorado",
      lat: 37.6,
      lng: -107.55,
      dogPolicy: "Dogs allowed under voice control throughout the wilderness. No leash required but must be under handler control.",
      dogTrails: ["Vallecito Creek Trail", "Pine River Trail", "Endlich Mesa Trail"],
      restrictions: ["No mechanized equipment", "Pack out all waste", "Respect wildlife and other hikers"],
      description:
        "Colorado's largest wilderness area is a backcountry paradise for adventurous pups and their humans. Crystal-clear alpine lakes, 14,000-foot peaks, and endless ridgelines await. Your dog will drink from glacier-fed streams and sleep under more stars than they've ever seen.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/recarea/sanjuan/recarea/?recid=75490",
    },
    {
      name: "Chimney Rock National Monument",
      state: "Colorado",
      lat: 37.1917,
      lng: -107.3075,
      dogPolicy: "Dogs not permitted on guided tours but welcome in the parking area and picnic grounds on leash.",
      dogTrails: [],
      restrictions: ["No dogs on trails or tours", "Leash required in parking area", "No unattended pets in vehicles"],
      description:
        "Twin rock spires sacred to the ancestral Puebloans stand guard over the Piedra River valley. While your pup can't join the guided archaeological tours, the drive up offers spectacular views and the nearby national forest provides plenty of trail alternatives.",
      imageUrl: "",
      website: "https://www.chimneyrockco.org",
    },
  ],
  restaurants: [
    {
      name: "Steamworks Brewing Co.",
      address: "801 E 2nd Ave, Durango, CO 81301",
      lat: 37.2744,
      lng: -107.8771,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the large outdoor patio. Water bowls provided. Great people-watching spot for pups.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.steamworksbrewing.com",
    },
    {
      name: "11th Street Station",
      address: "1101 Main Ave, Durango, CO 81301",
      lat: 37.2782,
      lng: -107.8793,
      cuisine: "Food Truck Park",
      priceRange: "$" as const,
      dogPolicy: "Extremely dog-friendly outdoor venue with rotating food trucks. Dogs roam the patio freely on leash.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.11thstreetstation.com",
    },
    {
      name: "Ore House",
      address: "147 E College Dr, Durango, CO 81301",
      lat: 37.2754,
      lng: -107.8795,
      cuisine: "Steakhouse",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs allowed on the second-floor balcony patio overlooking Main Avenue.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.orehouserestaurant.com",
    },
    {
      name: "Zia Taqueria",
      address: "3101 Main Ave, Durango, CO 81301",
      lat: 37.2905,
      lng: -107.8763,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor picnic tables. Quick-service counter makes it easy to grab food and sit with your pup.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ziataqueria.com",
    },
    {
      name: "Ska Brewing Company",
      address: "225 Girard St, Durango, CO 81303",
      lat: 37.2693,
      lng: -107.8917,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs are practically co-owners here. Massive outdoor beer garden with water bowls, shade, and good vibes.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.skabrewing.com",
    },
    {
      name: "East by Southwest",
      address: "160 E College Dr, Durango, CO 81301",
      lat: 37.2756,
      lng: -107.8792,
      cuisine: "Asian Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor terrace. Sushi and stir-fry with mountain views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Animas Brewing Company",
      address: "1560 Florida Rd, Durango, CO 81301",
      lat: 37.2601,
      lng: -107.862,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio with a community vibe. Regular pup meetups on weekends.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.animasbrewing.com",
    },
    {
      name: "Cream Bean Berry",
      address: "121 W 9th St, Durango, CO 81301",
      lat: 37.2763,
      lng: -107.8815,
      cuisine: "Dessert",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at sidewalk seating. A pup cup of whipped cream is available on request.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "",
    },
  ],
  cafes: [
    {
      name: "Durango Joe's Coffee",
      address: "1124 Main Ave, Durango, CO 81301",
      lat: 37.2784,
      lng: -107.8791,
      dogPolicy: "Drive-through and walk-up window with outdoor seating. Dogs always welcome and often get a free pup cup.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.durangojoes.com",
    },
    {
      name: "Durango Coffee Company",
      address: "730 Main Ave, Durango, CO 81301",
      lat: 37.2741,
      lng: -107.8799,
      dogPolicy: "Leashed dogs welcome on the sidewalk patio. Local roastery with mountain-town charm.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.durangocoffee.com",
    },
    {
      name: "Animas Chocolate & Coffee Company",
      address: "900 Main Ave, Durango, CO 81301",
      lat: 37.276,
      lng: -107.8795,
      dogPolicy: "Dogs welcome at outdoor tables. Handmade chocolates for humans — don't share with your pup!",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Bread Bakery & Cafe",
      address: "42 County Rd 250, Durango, CO 81301",
      lat: 37.2632,
      lng: -107.8834,
      dogPolicy: "Spacious patio welcomes dogs. Fresh-baked bread aroma may cause excessive drooling in all species.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "",
    },
    {
      name: "The Bookcase & Barber Coffee",
      address: "601 E 2nd Ave, Durango, CO 81301",
      lat: 37.2737,
      lng: -107.8785,
      dogPolicy: "Hip coffee-bookstore-barbershop combo. Dogs welcome on the front patio while you browse and sip.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Durango Dog Park",
      address: "2500 Main Ave, Durango, CO 81301",
      lat: 37.2865,
      lng: -107.8778,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water fountains", "Benches", "Shade structures", "Waste bags", "Agility equipment"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Durango's premier off-leash destination sits along the Animas River trail with mountain views that'll make you forget you're at a dog park. Separate areas for big and small pups, plus enough room for even the zoomiest husky.",
    },
    {
      name: "Animas River Trail",
      address: "Animas River Trail, Durango, CO 81301",
      lat: 37.2753,
      lng: -107.8815,
      offLeash: false,
      fenced: false,
      acres: 50.0,
      amenities: ["Paved trail", "River access", "Benches", "Waste stations", "Scenic overlooks"],
      rating: 4.8,
      imageUrl: "",
      description:
        "Seven miles of paved riverside trail running through the heart of Durango. Your leashed pup will love the river access points for cooling off, and the constant parade of other dogs makes it a social highlight reel.",
    },
    {
      name: "Animas Mountain Trailhead",
      address: "4th Ave & W 32nd St, Durango, CO 81301",
      lat: 37.2958,
      lng: -107.8838,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Mountain trails", "Panoramic views", "Wildlife viewing", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A local favorite for serious hiking with your pup. The climb is steep but the 360-degree views of the San Juans from the summit are worth every pant. Leash required, but the trail is wide and well-maintained.",
    },
    {
      name: "Dalla Mountain Park",
      address: "Leyden St, Durango, CO 81301",
      lat: 37.268,
      lng: -107.8925,
      offLeash: true,
      fenced: false,
      acres: 40.0,
      amenities: ["Trails", "Open meadows", "Mountain views", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "An off-leash paradise on Durango's west side with open meadows and piñon-juniper forests. Dogs bound through the sage with reckless joy while owners soak in views of the La Plata Mountains. Voice control required.",
    },
    {
      name: "Oxbow Park & Preserve",
      address: "500 Animas View Dr, Durango, CO 81301",
      lat: 37.2951,
      lng: -107.8724,
      offLeash: false,
      fenced: false,
      acres: 25.0,
      amenities: ["Wetland trails", "River access", "Bird watching", "Educational signs", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A serene riverside preserve where your leashed pup can explore wetland habitats along the Animas River. Great blue herons, muskrats, and the occasional beaver keep nosy dogs thoroughly entertained.",
    },
  ],
};
