export const elPasoData = {
  city: {
    name: "El Paso",
    state: "Texas",
    region: "Southwest",
    lat: 31.7619,
    lng: -106.4850,
    dogFriendlinessScore: 6,
    description:
      "El Paso sits at the western tip of Texas with the stunning Franklin Mountains rising from its center. This bilingual border city offers unique desert hiking, a warm and welcoming culture, and the only urban state park in Texas where dogs can explore dramatic desert terrain.",
    heroImage: "https://images.unsplash.com/photo-1568667256531-7d5ac981de24?w=1200&fit=crop",
    climate: "Hot desert",
    population: 678815,
  },

  hotels: [
    {
      name: "Hotel Indigo El Paso Downtown",
      address: "325 N Kansas St, El Paso, TX 79901",
      lat: 31.7600,
      lng: -106.4870,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome with a one-time pet fee. Boutique hotel in downtown.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Downtown location", "Walking maps", "Near San Jacinto Plaza"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(915) 534-3000",
    },
    {
      name: "Stanton House El Paso",
      address: "222 W Overland Ave, El Paso, TX 79901",
      lat: 31.7580,
      lng: -106.4880,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with a pet fee. Historic building with modern luxury.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Rooftop access", "Walking distance to restaurants", "Concierge"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.stantonhouseelpaso.com",
      phone: "(915) 206-7862",
    },
    {
      name: "La Quinta Inn El Paso West",
      address: "7620 N Mesa St, El Paso, TX 79912",
      lat: 31.8190,
      lng: -106.5540,
      priceRange: "$" as const,
      dogPolicy: "All dogs welcome at no extra charge. Near Franklin Mountains State Park.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Near state park", "Grassy area", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(915) 833-2522",
    },
    {
      name: "Radisson Hotel El Paso Airport",
      address: "1770 Airway Blvd, El Paso, TX 79925",
      lat: 31.7710,
      lng: -106.3880,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a non-refundable fee. Convenient airport-adjacent location.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Grassy area", "Near freeway", "Pool area", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.radissonhotels.com",
      phone: "(915) 772-3333",
    },
  ],

  nationalParks: [
    {
      name: "Franklin Mountains State Park",
      state: "Texas",
      lat: 31.8830,
      lng: -106.4920,
      dogPolicy: "Leashed dogs welcome on all trails. The largest urban park in the nation at over 24,000 acres.",
      dogTrails: ["Aztec Caves Trail", "Ron Coleman Trail", "Mundy's Gap Trail", "North Franklin Peak Trail"],
      restrictions: [
        "Must be on a 6-foot leash at all times",
        "Carry plenty of water",
        "Avoid midday summer hiking",
        "Watch for rattlesnakes",
      ],
      description:
        "Rising directly from the city, the Franklin Mountains are the largest urban park in the contiguous US. The rugged Chihuahuan Desert trails offer dramatic views of El Paso, Juarez, and the Rio Grande valley.",
      imageUrl: "",
      website: "https://www.tpwd.texas.gov/state-parks/franklin-mountains",
    },
    {
      name: "Hueco Tanks State Park & Historic Site",
      state: "Texas",
      lat: 31.9190,
      lng: -106.0400,
      dogPolicy: "Leashed dogs welcome in the picnic area and on the self-guided trail. Not allowed in restricted areas.",
      dogTrails: ["Interpretive Trail", "Picnic Area Loop"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed on guided-only trails",
        "Not allowed in rock climbing areas",
        "Limited daily visitors - reserve ahead",
      ],
      description:
        "Ancient rock art, natural water pools (huecos), and dramatic rock formations make this park unique. While dog access is limited, the interpretive trail offers a taste of this culturally significant desert landscape.",
      imageUrl: "",
      website: "https://www.tpwd.texas.gov/state-parks/hueco-tanks",
    },
    {
      name: "Guadalupe Mountains National Park",
      state: "Texas",
      lat: 31.8912,
      lng: -104.8606,
      dogPolicy: "Dogs allowed on the Pinery Nature Trail, campgrounds, and parking areas only.",
      dogTrails: ["Pinery Nature Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on any backcountry trails",
        "Not permitted on Guadalupe Peak Trail",
        "Limited to campgrounds, parking areas, and Pinery Trail",
      ],
      description:
        "About two hours east of El Paso, Guadalupe Mountains features the highest point in Texas. While dog access to trails is extremely limited, the drive and the Pinery Nature Trail offer a glimpse of this dramatic park.",
      imageUrl: "",
      website: "https://www.nps.gov/gumo",
    },
  ],

  restaurants: [
    {
      name: "L&J Cafe",
      address: "3622 E Missouri Ave, El Paso, TX 79903",
      lat: 31.7720,
      lng: -106.4360,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Legendary El Paso Tex-Mex since 1927.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.landjcafe.com",
    },
    {
      name: "Craft & Social",
      address: "305 E Franklin Ave, El Paso, TX 79901",
      lat: 31.7590,
      lng: -106.4850,
      cuisine: "Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor patio. Craft cocktails and elevated pub fare downtown.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.craftandsocialep.com",
    },
    {
      name: "Elemi Restaurant",
      address: "313 N Kansas St, El Paso, TX 79901",
      lat: 31.7600,
      lng: -106.4870,
      cuisine: "Modern Mexican",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the patio. Innovative Mexican cuisine using local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.elemielpaso.com",
    },
    {
      name: "DeadBeach Brewery",
      address: "406 S Durango St, El Paso, TX 79901",
      lat: 31.7560,
      lng: -106.4870,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly brewery with a large outdoor space. Craft beer with border flair.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.deadbeachbrewery.com",
    },
    {
      name: "Café Central",
      address: "109 N Oregon St, El Paso, TX 79901",
      lat: 31.7595,
      lng: -106.4890,
      cuisine: "Continental",
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome on the seasonal sidewalk patio. El Paso's premier fine dining establishment.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.cafecentral.com",
    },
  ],

  cafes: [
    {
      name: "Kinley's Coffee & Tea",
      address: "226 N Stanton St, El Paso, TX 79901",
      lat: 31.7600,
      lng: -106.4870,
      dogPolicy: "Dogs welcome on the outdoor patio. Specialty coffee in the heart of downtown.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.kinleyscoffee.com",
    },
    {
      name: "Hillside Coffee Lounge",
      address: "4200 N Mesa St, El Paso, TX 79902",
      lat: 31.7930,
      lng: -106.5220,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Community-focused coffee shop.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hillsidecoffee.com",
    },
    {
      name: "District Coffee",
      address: "701 N Mesa St, El Paso, TX 79902",
      lat: 31.7630,
      lng: -106.4920,
      dogPolicy: "Dogs welcome at outdoor tables. Coffee and light bites near UTEP.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.districtcoffeeep.com",
    },
    {
      name: "Casa Coffee & Books",
      address: "3010 Gateway West, El Paso, TX 79903",
      lat: 31.7700,
      lng: -106.4500,
      dogPolicy: "Leashed dogs welcome outside. Coffee and used books in a relaxed atmosphere.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.casacoffeebooks.com",
    },
  ],

  dogParks: [
    {
      name: "Eastside Dog Park",
      address: "11501 Edgemere Blvd, El Paso, TX 79936",
      lat: 31.7380,
      lng: -106.3300,
      offLeash: true,
      fenced: true,
      acres: 4.0,
      amenities: ["Separate small dog area", "Water stations", "Shade ramadas", "Waste stations", "Benches"],
      rating: 4.3,
      imageUrl: "",
      description:
        "El Paso's largest dedicated dog park with good shade structures essential for the desert climate. Separate areas for small and large dogs with water access.",
    },
    {
      name: "Westside Dog Park",
      address: "7400 High Ridge Dr, El Paso, TX 79912",
      lat: 31.8150,
      lng: -106.5700,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Mountain views", "Water fountains", "Shade structures", "Waste stations", "Parking"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A west-side dog park with views of the Franklin Mountains. The elevated location catches desert breezes that help keep dogs comfortable during cooler months.",
    },
    {
      name: "Tom Lea Park Upper",
      address: "3001 N Mesa St, El Paso, TX 79902",
      lat: 31.7860,
      lng: -106.5120,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["City views", "Walking paths", "Benches", "Shade trees", "Historic markers"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A scenic hillside park offering panoramic views of El Paso, Juarez, and the Rio Grande. While on-leash, the elevated walking paths and dramatic views make this a memorable urban hike.",
    },
    {
      name: "Memorial Park Dog Area",
      address: "1701 N Copia St, El Paso, TX 79930",
      lat: 31.7790,
      lng: -106.4530,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Double-gated entry", "Water fountain", "Benches", "Waste stations", "Shade trees"],
      rating: 4.1,
      imageUrl: "",
      description:
        "A centrally located off-leash area within Memorial Park. The compact fenced space provides a convenient spot for dogs to play between desert adventures.",
    },
  ],
};
