export const estesParkData = {
  city: {
    name: "Estes Park",
    state: "Colorado",
    region: "Mountain West",
    lat: 40.3772,
    lng: -105.5217,
    dogFriendlinessScore: 8,
    description:
      "Perched at 7,522 feet as the gateway to Rocky Mountain National Park, Estes Park is a mountain town where elk roam downtown and dogs are treated like royalty. While the national park limits pup access, the surrounding Roosevelt National Forest and charming downtown more than make up for it with dog-friendly trails, patios, and shops that keep tails wagging at altitude.",
    heroImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&fit=crop",
    climate: "Subalpine",
    population: 6300,
  },

  hotels: [
    {
      name: "The Stanley Hotel",
      address: "333 Wonderview Ave, Estes Park, CO 80517",
      lat: 40.3830,
      lng: -105.5142,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select pet-friendly rooms. The hotel that inspired The Shining now inspires tail wags.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Bowls", "Treats", "Mountain views", "Historic tours"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.stanleyhotel.com",
      phone: "(970) 577-4000",
    },
    {
      name: "Ridgeline Hotel Estes Park",
      address: "101 S St Vrain Ave, Estes Park, CO 80517",
      lat: 40.3755,
      lng: -105.5198,
      priceRange: "$$" as const,
      dogPolicy: "All dogs welcome with no breed or size restrictions. Modern mountain lodge with river views.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Dog bed", "Bowls", "Riverside trails", "Mountain views", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.ridgelinehotel.com",
      phone: "(970) 586-3336",
    },
    {
      name: "Murphy's River Lodge",
      address: "481 W Elkhorn Ave, Estes Park, CO 80517",
      lat: 40.3780,
      lng: -105.5265,
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly rooms available along the Big Thompson River. Your pup can fall asleep to the sound of rushing water.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Riverside location", "Dog bowls", "Walking paths", "Kitchenette", "BBQ area"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.murphysriverlodge.com",
      phone: "(970) 586-0306",
    },
    {
      name: "Rocky Mountain Park Inn",
      address: "101 S St Vrain Ave, Estes Park, CO 80517",
      lat: 40.3758,
      lng: -105.5195,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms with mountain views. Close to downtown shops and the riverwalk.",
      maxDogWeight: 80,
      petFee: 30,
      amenities: ["Mountain views", "Walking distance to downtown", "Dog bowls on request", "Parking", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.rockymountainparkinn.com",
      phone: "(970) 586-2332",
    },
    {
      name: "YMCA of the Rockies - Estes Park Center",
      address: "2515 Tunnel Rd, Estes Park, CO 80511",
      lat: 40.3595,
      lng: -105.5620,
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome in select cabin units with a per-night fee. 860 acres of mountain property to explore.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Cabins", "860 acres of trails", "Dog-friendly grounds", "Campfire areas", "Playground"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.ymcarockies.org",
      phone: "(970) 586-3341",
    },
  ],

  nationalParks: [
    {
      name: "Rocky Mountain National Park",
      state: "Colorado",
      lat: 40.3428,
      lng: -105.6836,
      dogPolicy: "Dogs allowed on roads, in parking areas, picnic areas, and campgrounds only. Not permitted on any trails or in the backcountry.",
      dogTrails: [
        "Campground loops at Moraine Park",
        "Glacier Basin Campground roads",
        "Aspenglen Campground area",
      ],
      restrictions: [
        "No dogs on any trails",
        "Must be on leash (6 ft max) at all times",
        "Not allowed in meadows, along waterways, or in backcountry",
        "Not permitted on the shuttle bus",
      ],
      description:
        "The crown jewel right at Estes Park's doorstep features soaring peaks above 14,000 feet, alpine lakes, and abundant wildlife. While trail access is off-limits for dogs, the scenic Trail Ridge Road drive offers breathtaking views your pup can enjoy from the car window.",
      imageUrl: "",
      website: "https://www.nps.gov/romo",
    },
    {
      name: "Great Sand Dunes National Park",
      state: "Colorado",
      lat: 37.7326,
      lng: -105.5943,
      dogPolicy: "Dogs allowed on Medano Creek, the sand dunes themselves, and in campgrounds. One of the most dog-friendly national parks in Colorado.",
      dogTrails: [
        "Medano Creek beach area",
        "Sand dunes (open roaming, leashed)",
        "Medano Pass Primitive Road",
        "Point of No Return Trail (first mile)",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Not allowed on backcountry trails beyond dunes",
        "Watch for hot sand temperatures in summer",
      ],
      description:
        "North America's tallest sand dunes rise over 700 feet against the Sangre de Cristo Mountains. Leashed dogs can walk on the dunes themselves and splash in seasonal Medano Creek — a rare national park where your pup shares the main attraction.",
      imageUrl: "",
      website: "https://www.nps.gov/grsa",
    },
    {
      name: "Florissant Fossil Beds National Monument",
      state: "Colorado",
      lat: 38.9145,
      lng: -105.2814,
      dogPolicy: "Leashed dogs welcome on all trails. One of the most dog-friendly NPS sites in Colorado.",
      dogTrails: [
        "Petrified Forest Loop",
        "Walk Through Time Trail",
        "Hornbek Wildlife Loop",
        "Boulder Creek Trail",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Not allowed in the visitor center",
        "Must stay on established trails",
      ],
      description:
        "This hidden gem preserves an ancient lake bed filled with exquisitely detailed fossils from 34 million years ago. All trails welcome leashed dogs through meadows and forests, making it a fantastic day trip from Estes Park.",
      imageUrl: "",
      website: "https://www.nps.gov/flfo",
    },
    {
      name: "Black Canyon of the Gunnison National Park",
      state: "Colorado",
      lat: 38.5754,
      lng: -107.7416,
      dogPolicy: "Dogs allowed on the rim roads, overlooks, campgrounds, and three specific rim trails.",
      dogTrails: [
        "Rim Rock Trail",
        "Cedar Point Nature Trail",
        "North Rim Chasm View Nature Trail",
      ],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed in the inner canyon",
        "Not allowed on most hiking trails",
      ],
      description:
        "One of Colorado's most dramatic landscapes, the Black Canyon plunges over 2,000 feet to the Gunnison River. Dogs can join you on select rim trails for vertigo-inducing views that will make both your hearts race.",
      imageUrl: "",
      website: "https://www.nps.gov/blca",
    },
  ],

  restaurants: [
    {
      name: "Smokin' Dave's BBQ & Brew",
      address: "820 Moraine Ave, Estes Park, CO 80517",
      lat: 40.3770,
      lng: -105.5210,
      cuisine: "BBQ",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the large outdoor patio. Slow-smoked BBQ with mountain views — your pup will drool over more than the brisket.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.smokindavesbbq.com",
    },
    {
      name: "Rock Inn Mountain Tavern",
      address: "1675 CO-66, Estes Park, CO 80517",
      lat: 40.3685,
      lng: -105.4955,
      cuisine: "American Tavern",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio with a relaxed mountain vibe. Burgers, wings, and craft beers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.rockinnestespark.com",
    },
    {
      name: "Bird & Jim",
      address: "915 Moraine Ave, Estes Park, CO 80517",
      lat: 40.3768,
      lng: -105.5225,
      cuisine: "Farm-to-Table American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the seasonal patio. Locally sourced ingredients and craft cocktails in a cozy lodge setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.birdandjim.com",
    },
    {
      name: "The Egg & I",
      address: "393 E Elkhorn Ave, Estes Park, CO 80517",
      lat: 40.3780,
      lng: -105.5160,
      cuisine: "Breakfast & Brunch",
      priceRange: "$" as const,
      dogPolicy: "Patio seating available for guests with dogs. The ultimate mountain breakfast spot.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.theeggandirestaurants.com",
    },
    {
      name: "Nepal's Cafe",
      address: "184 E Elkhorn Ave, Estes Park, CO 80517",
      lat: 40.3775,
      lng: -105.5185,
      cuisine: "Nepalese & Indian",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio. Authentic Himalayan cuisine at the base of the Rockies.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.nepalscafe.com",
    },
    {
      name: "Estes Park Brewery",
      address: "470 Prospect Village Dr, Estes Park, CO 80517",
      lat: 40.3760,
      lng: -105.5140,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Large dog-friendly patio with mountain views. House-brewed ales and hearty pub fare at altitude.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.estesparkbrewery.com",
    },
    {
      name: "Poppy's Pizza & Grill",
      address: "342 E Elkhorn Ave, Estes Park, CO 80517",
      lat: 40.3778,
      lng: -105.5168,
      cuisine: "Pizza & Italian",
      priceRange: "$" as const,
      dogPolicy: "Outdoor patio welcomes leashed dogs. Hand-tossed pizza and calzones fuel post-hike appetites.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.poppyspizzaandgrill.com",
    },
    {
      name: "Mama Rose's",
      address: "338 E Elkhorn Ave, Estes Park, CO 80517",
      lat: 40.3777,
      lng: -105.5170,
      cuisine: "Italian",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Hearty Italian comfort food with a mountain-town warmth.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.mamaroses.com",
    },
  ],

  cafes: [
    {
      name: "Kind Coffee",
      address: "470 E Elkhorn Ave, Estes Park, CO 80517",
      lat: 40.3782,
      lng: -105.5152,
      dogPolicy: "Spacious dog-friendly patio in the heart of downtown. Locally roasted coffee with mountain views.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.kindcoffee.com",
    },
    {
      name: "Inkwell & Brew",
      address: "252 Moraine Ave, Estes Park, CO 80517",
      lat: 40.3765,
      lng: -105.5195,
      dogPolicy: "Dogs welcome at outdoor tables. Coffee, bookshop, and mountain ambiance — a pup parent's trifecta.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.inkwellandbrew.com",
    },
    {
      name: "Mountain Home Cafe",
      address: "457 E Wonderview Ave, Estes Park, CO 80517",
      lat: 40.3810,
      lng: -105.5155,
      dogPolicy: "Covered patio with dog-friendly seating. Homemade pastries and espresso with peak views.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.mountainhomecafe.com",
    },
    {
      name: "The Barrel",
      address: "124 W Elkhorn Ave, Estes Park, CO 80517",
      lat: 40.3773,
      lng: -105.5220,
      dogPolicy: "Outdoor seating area welcomes dogs. Coffee and donuts to fuel your morning hike.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Notchtop Bakery & Cafe",
      address: "459 E Wonderview Ave, Estes Park, CO 80517",
      lat: 40.3812,
      lng: -105.5150,
      dogPolicy: "Patio tables welcome leashed dogs. Famous cinnamon rolls the size of your dog's head.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.notchtop.com",
    },
  ],

  dogParks: [
    {
      name: "Estes Valley Dog Park",
      address: "Community Dr, Estes Park, CO 80517",
      lat: 40.3740,
      lng: -105.5130,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Fenced area", "Separate small dog area", "Water spigot", "Waste stations", "Mountain views"],
      rating: 4.4,
      imageUrl: "",
      description:
        "The town's dedicated off-leash dog park offers fenced romping with spectacular mountain views as a backdrop. A separate small dog area ensures all pups can play at their own pace.",
    },
    {
      name: "Riverwalk Trail",
      address: "E Elkhorn Ave, Estes Park, CO 80517",
      lat: 40.3775,
      lng: -105.5175,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Paved path", "River access", "Benches", "Waste stations", "Downtown access"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A scenic paved trail along the Big Thompson River through the heart of downtown Estes Park. Leashed dogs love the river access points and the chance to watch elk grazing on the adjacent meadows.",
    },
    {
      name: "Lily Lake Trail",
      address: "CO-7, Estes Park, CO 80517",
      lat: 40.3048,
      lng: -105.5388,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Paved loop trail", "Lake views", "Parking", "Accessible trail", "Waste stations"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A stunning 0.8-mile loop around a pristine alpine lake just outside Rocky Mountain National Park. Leashed dogs can enjoy the easy, flat trail with views of Longs Peak and Estes Cone reflected in the water.",
    },
    {
      name: "Kruger Rock Trail",
      address: "Pole Hill Rd, Estes Park, CO 80517",
      lat: 40.3420,
      lng: -105.4980,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Hiking trail", "Panoramic summit views", "Parking", "Forest setting", "Moderate difficulty"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A 3.8-mile roundtrip hike in Roosevelt National Forest that climbs to a rock outcrop with 360-degree views of the Continental Divide. Leashed dogs love this moderately challenging trail through pine forest.",
    },
    {
      name: "Fish Creek Trail",
      address: "Fish Creek Rd, Estes Park, CO 80517",
      lat: 40.3650,
      lng: -105.5350,
      offLeash: false,
      fenced: false,
      acres: 12.0,
      amenities: ["Creek access", "Forest trail", "Moderate difficulty", "Parking", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A beautiful trail following Fish Creek through dense forest with creek crossings that water-loving dogs adore. The gentle sound of rushing water makes this a peaceful escape just minutes from downtown.",
    },
  ],
};
