export const eugeneData = {
  city: {
    name: "Eugene",
    state: "Oregon",
    region: "Pacific Northwest",
    lat: 44.0521,
    lng: -123.0868,
    dogFriendlinessScore: 9,
    description:
      "Known as Track Town USA, Eugene is also one of the most dog-friendly cities in the Pacific Northwest with an extensive off-leash park system, miles of riverside trails, and a progressive culture that celebrates canine companions. The combination of urban amenities and easy access to wilderness makes it ideal for active dog owners.",
    heroImage: "https://images.unsplash.com/photo-1551523713-c1473ae81e1b?w=1200&fit=crop",
    climate: "Oceanic",
    population: 176654,
  },
  hotels: [
    {
      name: "Inn at the 5th",
      address: "205 E 6th Ave, Eugene, OR 97401",
      lat: 44.0530,
      lng: -123.0870,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique downtown hotel welcoming dogs of all sizes. Walking distance to the Saturday Market and Willamette River trails.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Treats", "Downtown location", "Walking map", "Waste bags"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.innat5th.com",
      phone: "(541) 743-4099",
    },
    {
      name: "Valley River Inn",
      address: "1000 Valley River Way, Eugene, OR 97401",
      lat: 44.0600,
      lng: -123.1100,
      priceRange: "$$" as const,
      dogPolicy: "Riverside hotel on the Willamette with pet-friendly rooms and river trail access. Dogs welcome with walking paths along the river.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["River trail access", "Dog bed", "Water bowls", "Garden", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.valleyriverinn.com",
      phone: "(541) 743-1000",
    },
    {
      name: "EVEN Hotel Eugene",
      address: "2133 Franklin Blvd, Eugene, OR 97403",
      lat: 44.0450,
      lng: -123.0700,
      priceRange: "$$" as const,
      dogPolicy: "Wellness-focused hotel near the University of Oregon welcoming dogs. Active travelers and their pets enjoy the fitness-oriented amenities.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Pet-friendly rooms", "Fitness center", "Near campus", "Waste bags", "Water bowls"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(541) 515-3836",
    },
    {
      name: "Budget Inn Eugene",
      address: "1190 W 6th Ave, Eugene, OR 97402",
      lat: 44.0520,
      lng: -123.1000,
      priceRange: "$" as const,
      dogPolicy: "Affordable option welcoming dogs of all sizes. Conveniently located near downtown and the Whiteaker neighborhood.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Pet-friendly rooms", "Parking", "Near downtown", "Waste bags", "Water bowls"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.budgetinn.com",
      phone: "(541) 342-7273",
    },
  ],
  nationalParks: [
    {
      name: "Willamette National Forest",
      state: "Oregon",
      lat: 44.0000,
      lng: -122.2000,
      dogPolicy: "Dogs welcome on most trails on leash or under voice control. Massive forest covering the western Cascades east of Eugene.",
      dogTrails: ["Proxy Falls Trail", "Sahalie & Koosah Falls Trail", "Tamolitch Blue Pool Trail", "McKenzie River Trail"],
      restrictions: ["Leash or voice control required", "Northwest Forest Pass required", "Some trails closed seasonally", "Carry extra water"],
      description: "The Willamette National Forest east of Eugene offers some of Oregon's most spectacular dog-friendly hiking. Waterfalls, volcanic blue pools, and ancient forest trails make the McKenzie River area a must-visit for dog owners.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/willamette",
    },
    {
      name: "Ridgeline Trail System",
      state: "Oregon",
      lat: 44.0200,
      lng: -123.1000,
      dogPolicy: "Dogs welcome on all trails on leash. A 12-mile urban trail system through forested ridges within Eugene city limits.",
      dogTrails: ["Ridgeline Trail", "Spencer Butte Trail", "Blanton Ridge Trail", "Fox Hollow Trail"],
      restrictions: ["Leash required", "Muddy in wet season", "Mountain bikes on some sections", "Steep sections near Spencer Butte"],
      description: "Eugene's Ridgeline Trail system offers 12 miles of forested hiking along the buttes south of the city. The trail to Spencer Butte summit provides panoramic views of the Willamette Valley, Cascades, and Coast Range.",
      imageUrl: "",
      website: "https://www.eugene-or.gov/ridgeline",
    },
    {
      name: "Mount Pisgah Arboretum",
      state: "Oregon",
      lat: 43.9800,
      lng: -122.9800,
      dogPolicy: "Dogs welcome on all trails on leash. A 209-acre nature preserve with wildflower meadows and summit views.",
      dogTrails: ["Summit Trail", "Arboretum Loop", "River Path", "Quarry Road Trail"],
      restrictions: ["Leash required", "Stay on designated trails", "Seasonal wildflower areas may be restricted", "Day use fee"],
      description: "Located where the Coast Fork and Middle Fork of the Willamette River meet, Mount Pisgah offers gentle trails through meadows and oak savanna to a summit with 360-degree views. It is one of Eugene's most beloved dog walking destinations.",
      imageUrl: "",
      website: "https://www.mountpisgaharboretum.com",
    },
  ],
  restaurants: [
    {
      name: "Marché",
      address: "296 E 5th Ave, Eugene, OR 97401",
      lat: 44.0525,
      lng: -123.0860,
      cuisine: "French-Northwest",
      priceRange: "$$$" as const,
      dogPolicy: "Eugene's premier farm-to-table restaurant with a sidewalk patio welcoming dogs. Seasonal French-Northwest cuisine from the 5th Street Market.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.marcherestaurant.com",
    },
    {
      name: "Ninkasi Better Living Room",
      address: "155 Blair Blvd, Eugene, OR 97402",
      lat: 44.0500,
      lng: -123.1050,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Ninkasi's tasting room with a large dog-friendly patio in the Whiteaker neighborhood. Award-winning beers and food trucks.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ninkasibrewing.com",
    },
    {
      name: "Beppe & Gianni's Trattoria",
      address: "1646 E 19th Ave, Eugene, OR 97403",
      lat: 44.0380,
      lng: -123.0700,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Beloved Italian trattoria with a garden patio where dogs are welcome. Handmade pasta and Italian wines in a cozy setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.beppeandgiannis.net",
    },
    {
      name: "Tacovore",
      address: "1601 Willamette St, Eugene, OR 97401",
      lat: 44.0420,
      lng: -123.0900,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Creative taco shop with outdoor seating where dogs are welcome. Locally sourced tacos and craft cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.tacovore.com",
    },
    {
      name: "Oakshire Brewing",
      address: "207 Madison St, Eugene, OR 97402",
      lat: 44.0510,
      lng: -123.1020,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Community brewery with a spacious dog-friendly patio in the Whiteaker. Rotating food trucks and craft beers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.oakshire.com",
    },
  ],
  cafes: [
    {
      name: "Tailored Coffee Roasters",
      address: "550 E Broadway, Eugene, OR 97401",
      lat: 44.0515,
      lng: -123.0820,
      dogPolicy: "Specialty roaster with a patio where dogs are welcome. Precision-roasted coffees and house-made pastries in downtown Eugene.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.tailoredcoffee.com",
    },
    {
      name: "Wandering Goat Coffee Co.",
      address: "268 Madison St, Eugene, OR 97402",
      lat: 44.0505,
      lng: -123.1010,
      dogPolicy: "Whiteaker neighborhood café with a garden patio where dogs are always welcome. Organic fair-trade coffee and live music.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.wanderinggoat.com",
    },
    {
      name: "Café Yumm!",
      address: "730 E Broadway, Eugene, OR 97401",
      lat: 44.0518,
      lng: -123.0800,
      dogPolicy: "Eugene-born café chain with outdoor seating and a dog-friendly atmosphere. Famous for their Yumm! bowls and organic offerings.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cafeyumm.com",
    },
    {
      name: "Perugino",
      address: "767 Willamette St, Eugene, OR 97401",
      lat: 44.0480,
      lng: -123.0890,
      dogPolicy: "Italian-inspired café with a sidewalk patio in downtown Eugene. Dogs welcome outside with espresso and panini.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.perugino.com",
    },
  ],
  dogParks: [
    {
      name: "Alton Baker Off-Leash Dog Park",
      address: "200 Day Island Rd, Eugene, OR 97401",
      lat: 44.0560,
      lng: -123.0700,
      offLeash: true,
      fenced: true,
      acres: 5,
      amenities: ["Separate small dog area", "Water stations", "Shade trees", "Agility equipment", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "Eugene's most popular off-leash park sits along the Willamette River within Alton Baker Park. Separate areas for large and small dogs, agility equipment, and river access create an ideal play environment.",
    },
    {
      name: "Amazon Dog Park",
      address: "2700 Hilyard St, Eugene, OR 97405",
      lat: 44.0300,
      lng: -123.0850,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "A well-loved south Eugene dog park within Amazon Park with separate fenced areas. The friendly community of regular dog walkers makes it a social hub for south Eugene dog owners.",
    },
    {
      name: "Pre's Trail & Ruth Bascom Riverbank Path",
      address: "Alton Baker Park, Eugene, OR 97401",
      lat: 44.0570,
      lng: -123.0650,
      offLeash: false,
      fenced: false,
      acres: 30,
      amenities: ["Bark chip trail", "River views", "Bridges", "Shade trees", "Waste bag stations"],
      rating: 4.7,
      imageUrl: "",
      description: "Named for legendary runner Steve Prefontaine, this soft-surface trail winds through Alton Baker Park along the Willamette River. Leashed dogs enjoy the bark-chip path through shaded riverside forest, one of Eugene's most scenic walks.",
    },
    {
      name: "Wayne Morse Family Farm Dog Park",
      address: "595 Crest Dr, Eugene, OR 97405",
      lat: 44.0250,
      lng: -123.0750,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Fenced area", "Water station", "Benches", "Views", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "An off-leash area within the historic Wayne Morse Family Farm property. The hilltop location offers views of the surrounding area, and the fenced enclosure provides a safe off-leash environment for dogs.",
    },
  ],
};
