export const flagstaffData = {
  city: {
    name: "Flagstaff",
    state: "Arizona",
    region: "Southwest",
    lat: 35.1983,
    lng: -111.6513,
    dogFriendlinessScore: 7,
    description:
      "Nestled among the world's largest contiguous ponderosa pine forest at 7,000 feet, Flagstaff is a mountain town where adventure-loving dogs thrive. With miles of forest trails, a charming historic downtown packed with dog-friendly breweries, and easy access to the Grand Canyon and Sedona, this four-season playground is a tail-wagging basecamp for exploring Northern Arizona.",
    heroImage: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200&fit=crop",
    climate: "Continental",
    population: 73964,
  },

  hotels: [
    {
      name: "Little America Hotel Flagstaff",
      address: "2515 E Butler Ave, Flagstaff, AZ 86004",
      lat: 35.1890,
      lng: -111.6055,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in pet-friendly rooms with a nightly fee. Set on 500 wooded acres with private trails perfect for morning walks.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Walking trails on property", "Dog bed", "Large rooms", "Wooded grounds", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.littleamerica.com/flagstaff",
      phone: "(928) 779-7900",
    },
    {
      name: "Drury Inn & Suites Flagstaff",
      address: "300 S Milton Rd, Flagstaff, AZ 86001",
      lat: 35.1920,
      lng: -111.6570,
      priceRange: "$$" as const,
      dogPolicy: "Up to two dogs welcome with no weight restriction and no pet fee. Hot breakfast included for the humans.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pet relief area", "Waste bags", "Near downtown", "Free breakfast"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.druryhotels.com",
      phone: "(928) 773-4900",
    },
    {
      name: "High Country Motor Lodge",
      address: "1000 W Route 66, Flagstaff, AZ 86001",
      lat: 35.1975,
      lng: -111.6620,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a flat pet fee. Retro Route 66 charm meets modern boutique style.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Dog bed", "Treats at check-in", "Outdoor fire pit", "Pet-friendly courtyard", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.highcountrymotorlodge.com",
      phone: "(928) 774-4581",
    },
    {
      name: "Residence Inn by Marriott Flagstaff",
      address: "3440 N Country Club Dr, Flagstaff, AZ 86004",
      lat: 35.2230,
      lng: -111.6385,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a one-time fee. Suite-style rooms with kitchenettes for preparing your pup's meals on the road.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Full kitchen", "Pet relief area", "Grocery delivery", "Waste stations", "Near trails"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(928) 526-5555",
    },
    {
      name: "The Inn at 410",
      address: "410 N Leroux St, Flagstaff, AZ 86001",
      lat: 35.2005,
      lng: -111.6530,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 30 lbs welcome in select suites with prior approval. Charming B&B with gourmet breakfast.",
      maxDogWeight: 30,
      petFee: 50,
      amenities: ["Garden access", "Gourmet breakfast", "Walking distance to downtown", "Cozy fireplace rooms", "Waste bags"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.inn410.com",
      phone: "(928) 774-0088",
    },
  ],

  nationalParks: [
    {
      name: "Grand Canyon National Park",
      state: "Arizona",
      lat: 36.1069,
      lng: -112.1129,
      dogPolicy: "Dogs are allowed on the South Rim paved trail (Rim Trail) and in developed areas. Not permitted below the rim or on unpaved trails.",
      dogTrails: ["Rim Trail (13 miles paved)", "Greenway Trail"],
      restrictions: [
        "Dogs NOT allowed below the rim",
        "Not allowed on unpaved trails",
        "Must be on a 6-foot leash",
        "Not allowed on shuttle buses",
        "Kennel available at South Rim",
      ],
      description:
        "Just 80 miles north of Flagstaff, the Grand Canyon's South Rim welcomes leashed dogs on the paved Rim Trail with jaw-dropping views at every turn. While pups cannot hike below the rim, the 13-mile Rim Trail offers more canyon splendor than most dogs (or humans) can handle in a day.",
      imageUrl: "",
      website: "https://www.nps.gov/grca",
    },
    {
      name: "Walnut Canyon National Monument",
      state: "Arizona",
      lat: 35.1718,
      lng: -111.5070,
      dogPolicy: "Leashed dogs welcome on the Rim Trail only. Not permitted on the Island Trail into the canyon.",
      dogTrails: ["Rim Trail (0.7 miles)"],
      restrictions: [
        "Not allowed on Island Trail",
        "Must be on leash",
        "Not allowed in visitor center",
      ],
      description:
        "Just 10 miles east of Flagstaff, this stunning canyon contains 800-year-old cliff dwellings. Leashed dogs can enjoy the Rim Trail with views into the forested canyon, though the Island Trail descending to the dwellings is off-limits to pets.",
      imageUrl: "",
      website: "https://www.nps.gov/waca",
    },
    {
      name: "Sunset Crater Volcano National Monument",
      state: "Arizona",
      lat: 35.3650,
      lng: -111.5000,
      dogPolicy: "Leashed dogs welcome on the Lava Flow Trail. A unique volcanic landscape experience for adventurous pups.",
      dogTrails: ["Lava Flow Trail (1 mile)", "Lenox Crater Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed off designated trails",
        "Not allowed in visitor center",
      ],
      description:
        "This 900-year-old volcanic landscape just north of Flagstaff offers otherworldly terrain. Leashed dogs can explore the Lava Flow Trail through cinder fields and twisted lava formations, sniffing volcanic rocks unlike anything they have encountered before.",
      imageUrl: "",
      website: "https://www.nps.gov/sucr",
    },
    {
      name: "Wupatki National Monument",
      state: "Arizona",
      lat: 35.5190,
      lng: -111.3700,
      dogPolicy: "Leashed dogs welcome on paved trails and in parking areas. Desert ruins with sweeping Painted Desert views.",
      dogTrails: ["Wupatki Pueblo Trail", "Lomaki Pueblo Trail", "Citadel Pueblo Trail"],
      restrictions: [
        "Must be on leash",
        "Not allowed inside pueblo structures",
        "Not allowed in visitor center",
        "Must stay on paved surfaces",
      ],
      description:
        "Ancient Puebloan ruins set against the red-rock Painted Desert, about 30 miles north of Flagstaff. Leashed dogs can accompany you on the short paved trails to several well-preserved pueblo sites with panoramic desert views.",
      imageUrl: "",
      website: "https://www.nps.gov/wupa",
    },
  ],

  restaurants: [
    {
      name: "Coppa Cafe",
      address: "1300 S Milton Rd #47, Flagstaff, AZ 86001",
      lat: 35.1858,
      lng: -111.6575,
      cuisine: "Italian-American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the shaded outdoor patio. Wood-fired pizzas and fresh pasta in a cozy setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.coppacafe.net",
    },
    {
      name: "Tourist Home All Day Cafe",
      address: "52 S San Francisco St, Flagstaff, AZ 86001",
      lat: 35.1978,
      lng: -111.6508,
      cuisine: "American Brunch",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor courtyard. A bright and cheerful spot for brunch with your best friend.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.touristhomecafe.com",
    },
    {
      name: "Brix Restaurant & Wine Bar",
      address: "413 N San Francisco St, Flagstaff, AZ 86001",
      lat: 35.2018,
      lng: -111.6508,
      cuisine: "New American",
      priceRange: "$$$$" as const,
      dogPolicy: "Well-behaved dogs welcome at outdoor tables. Upscale farm-to-table dining in a converted carriage house.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.brixflagstaff.com",
    },
    {
      name: "Mother Road Brewing Company",
      address: "7 S Mikes Pike, Flagstaff, AZ 86001",
      lat: 35.1970,
      lng: -111.6530,
      cuisine: "Brewery & Pub",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly taproom and patio. Craft beers inspired by Route 66 with food truck options.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.motherroadbeer.com",
    },
    {
      name: "Criollo Latin Kitchen",
      address: "16 N San Francisco St, Flagstaff, AZ 86001",
      lat: 35.1985,
      lng: -111.6508,
      cuisine: "Latin American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the heated patio. Creative Latin-inspired cuisine with craft cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.craboriollo.com",
    },
    {
      name: "Pizzicletta",
      address: "203 W Phoenix Ave, Flagstaff, AZ 86001",
      lat: 35.1975,
      lng: -111.6540,
      cuisine: "Neapolitan Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Limited outdoor seating where dogs are welcome. Authentic wood-fired Neapolitan pizza loved by locals.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.pizzicletta.com",
    },
    {
      name: "Salsa Brava",
      address: "2220 E Route 66, Flagstaff, AZ 86004",
      lat: 35.1962,
      lng: -111.6195,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly outdoor patio. Generous portions of New Mexican-style food at great prices.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.salsabravaflagstaff.com",
    },
    {
      name: "Lumberyard Tap Room & Grille",
      address: "5 S San Francisco St, Flagstaff, AZ 86001",
      lat: 35.1975,
      lng: -111.6505,
      cuisine: "American Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the large outdoor patio. Flagship brewpub in the heart of downtown.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.lumberyardbrewing.com",
    },
  ],

  cafes: [
    {
      name: "Firecreek Coffee Company",
      address: "22 E Route 66, Flagstaff, AZ 86001",
      lat: 35.1975,
      lng: -111.6490,
      dogPolicy: "Dogs welcome on the sunny outdoor patio along Route 66. Locally roasted beans and a cozy mountain vibe.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.firecreekcoffee.com",
    },
    {
      name: "Macy's European Coffee House",
      address: "14 S Beaver St, Flagstaff, AZ 86001",
      lat: 35.1972,
      lng: -111.6518,
      dogPolicy: "Leashed dogs welcome at the outdoor tables. A Flagstaff institution since 1980 with house-roasted coffee and fresh-baked goods.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.macyscoffee.net",
    },
    {
      name: "Late for the Train",
      address: "107 N San Francisco St, Flagstaff, AZ 86001",
      lat: 35.1992,
      lng: -111.6508,
      dogPolicy: "Small outdoor seating area where leashed dogs are welcome. Quick coffee and pastries near the train station.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.lateforthetrain.com",
    },
    {
      name: "Steep Craft Coffee & Tea",
      address: "119 N Leroux St, Flagstaff, AZ 86001",
      lat: 35.1988,
      lng: -111.6530,
      dogPolicy: "Dog-friendly patio perfect for sipping specialty tea and pour-over coffee in the mountain air.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.steepflagstaff.com",
    },
    {
      name: "Kickstand Kafe",
      address: "719 N Humphreys St, Flagstaff, AZ 86001",
      lat: 35.2050,
      lng: -111.6550,
      dogPolicy: "Bicycle and dog-friendly outdoor seating near the urban trail. Smoothies, coffee, and light bites.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.kickstandkafe.com",
    },
  ],

  dogParks: [
    {
      name: "Thorpe Park Off-Leash Dog Area",
      address: "245 N Thorpe Rd, Flagstaff, AZ 86001",
      lat: 35.2025,
      lng: -111.6410,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Separate small and large dog areas", "Water stations", "Benches", "Shade structures", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Flagstaff's premier fenced off-leash dog park with separate areas for big and little pups. The pine-scented mountain air at 7,000 feet makes every fetch session feel like a wilderness adventure.",
    },
    {
      name: "Bushmaster Park Dog Area",
      address: "3150 N Alta Vista Dr, Flagstaff, AZ 86004",
      lat: 35.2260,
      lng: -111.6370,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Water spigot", "Benches", "Parking", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      description:
        "A neighborhood favorite with a fenced off-leash area surrounded by ponderosa pines. A quieter alternative to Thorpe Park, great for dogs who prefer a calmer play environment.",
    },
    {
      name: "Buffalo Park",
      address: "2400 N Gemini Dr, Flagstaff, AZ 86001",
      lat: 35.2220,
      lng: -111.6680,
      offLeash: false,
      fenced: false,
      acres: 215.0,
      amenities: ["2-mile loop trail", "Mountain views", "Open meadows", "Wildlife viewing", "Waste stations", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A stunning 215-acre open space with a 2-mile loop trail offering panoramic views of the San Francisco Peaks. Leashed dogs love the wide trails through mountain meadows. Elk sightings are common, so keep a firm grip on that leash.",
    },
    {
      name: "Fort Tuthill County Park",
      address: "2446 Fort Tuthill Loop, Flagstaff, AZ 86005",
      lat: 35.1545,
      lng: -111.6680,
      offLeash: false,
      fenced: false,
      acres: 200.0,
      amenities: ["Mountain biking trails", "Hiking trails", "Picnic areas", "Amphitheater", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A massive county park with miles of forested trails winding through ponderosa pines. Leashed dogs can explore the interconnected trail system, and the shaded paths stay cool even on warm summer days.",
    },
    {
      name: "Foxglenn Park",
      address: "4000 E Butler Ave, Flagstaff, AZ 86004",
      lat: 35.1885,
      lng: -111.5925,
      offLeash: true,
      fenced: true,
      acres: 1.0,
      amenities: ["Fenced off-leash area", "Agility equipment", "Water fountain", "Benches", "Waste stations"],
      rating: 4.1,
      imageUrl: "",
      description:
        "A tidy fenced dog park on the east side of town with agility equipment for energetic pups. The elevation means cooler temps year-round, making it comfortable for dogs who overheat easily.",
    },
  ],
};
