export const fortCollinsData = {
  city: {
    name: "Fort Collins",
    state: "Colorado",
    region: "Mountain West",
    lat: 40.5853,
    lng: -105.0844,
    dogFriendlinessScore: 9,
    description:
      "Fort Collins is consistently ranked among America's most dog-friendly cities, with an incredible trail system, over 20 craft breweries with dog-friendly patios, and a community that genuinely revolves around outdoor recreation with dogs. Old Town's walkable streets, Horsetooth Reservoir, and easy access to Rocky Mountain National Park make FoCo a canine paradise.",
    heroImage: "https://images.unsplash.com/photo-1546156929-a4c0ac411f47?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 169810,
  },

  hotels: [
    {
      name: "The Elizabeth Hotel",
      address: "111 Chestnut St, Fort Collins, CO 80524",
      lat: 40.5870,
      lng: -105.0770,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a per-stay pet fee. Luxury boutique hotel in Old Town with music-themed rooms.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Dog bed", "Gourmet treats", "Water bowls", "Dog walking service", "Near Old Town trails"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.theelizabethcolorado.com",
      phone: "(970) 490-9292",
    },
    {
      name: "Armstrong Hotel",
      address: "259 S College Ave, Fort Collins, CO 80524",
      lat: 40.5845,
      lng: -105.0770,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with advance notice. Historic 1923 hotel in the heart of Old Town.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Treats", "Walking map", "Old Town location", "Near Spring Creek Trail"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thearmstronghotel.com",
      phone: "(970) 484-3883",
    },
    {
      name: "Hilton Fort Collins",
      address: "425 W Prospect Rd, Fort Collins, CO 80526",
      lat: 40.5730,
      lng: -105.0830,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a non-refundable pet fee. Full-service hotel near CSU campus.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Pet waste stations", "Grassy areas", "Near Spring Creek Trail", "Water bowls"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(970) 482-2626",
    },
    {
      name: "La Quinta Inn & Suites Fort Collins",
      address: "3709 E Mulberry St, Fort Collins, CO 80524",
      lat: 40.5870,
      lng: -105.0400,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome at no extra charge. Budget-friendly near I-25.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Pet waste stations", "Grassy areas", "Near Poudre Trail", "Water bowls at front desk"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta",
      phone: "(970) 461-2900",
    },
  ],

  nationalParks: [
    {
      name: "Rocky Mountain National Park",
      state: "Colorado",
      lat: 40.3428,
      lng: -105.6836,
      dogPolicy: "Dogs NOT allowed on any trails. Permitted on roads, in parking areas, and in picnic areas only.",
      dogTrails: ["No dog-friendly trails"],
      restrictions: [
        "No dogs on any trails",
        "Must be on leash (6 ft max) at all times",
        "Allowed only on roads and in parking/picnic areas",
        "Not allowed in buildings or on the shuttle bus",
      ],
      description:
        "While RMNP is famously restrictive for dogs, the drive over Trail Ridge Road at 12,183 feet is spectacular. For dog-friendly hiking, the Roosevelt National Forest surrounding the park offers excellent alternatives.",
      imageUrl: "",
      website: "https://www.nps.gov/romo",
    },
    {
      name: "Roosevelt National Forest",
      state: "Colorado",
      lat: 40.5000,
      lng: -105.5000,
      dogPolicy: "Dogs welcome on most trails. Leash required in developed areas; voice control in backcountry.",
      dogTrails: ["Greyrock Trail", "Young Gulch Trail", "Hewlett Gulch Trail", "Horsetooth Rock Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on trails",
        "Not allowed in designated swim areas",
      ],
      description:
        "The national forest west of Fort Collins offers the Poudre Canyon's spectacular trails as a dog-friendly alternative to RMNP. The hiking ranges from easy riverside walks to challenging summit scrambles with Front Range views.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/arp",
    },
    {
      name: "Horsetooth Mountain Open Space",
      state: "Colorado",
      lat: 40.5400,
      lng: -105.1700,
      dogPolicy: "Leashed dogs welcome on all trails. Popular foothill trails with reservoir and mountain views.",
      dogTrails: ["Horsetooth Rock Trail", "Soderberg Trail", "South Ridge Trail", "Wathen Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Stay on designated trails",
        "No dogs in reservoir swim areas",
      ],
      description:
        "A Larimer County open space offering dramatic rock formations, foothill trails, and views of Horsetooth Reservoir. The hike to Horsetooth Rock is iconic and leashed dogs love the varied terrain and panoramic views.",
      imageUrl: "",
      website: "https://www.larimer.gov/naturalresources",
    },
  ],

  restaurants: [
    {
      name: "New Belgium Brewing Company",
      address: "500 Linden St, Fort Collins, CO 80524",
      lat: 40.5930,
      lng: -105.0690,
      cuisine: "Brewery & Food Trucks",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the expansive outdoor patio and lawn. The flagship brewery with a bike-friendly, dog-friendly vibe.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.newbelgium.com",
    },
    {
      name: "Odell Brewing Company",
      address: "800 E Lincoln Ave, Fort Collins, CO 80524",
      lat: 40.5890,
      lng: -105.0640,
      cuisine: "Brewery & Food Trucks",
      priceRange: "$$" as const,
      dogPolicy: "One of the most dog-friendly breweries in Colorado. Huge outdoor area with dogs everywhere.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.odellbrewing.com",
    },
    {
      name: "The Mayor of Old Town",
      address: "632 S Mason St, Fort Collins, CO 80524",
      lat: 40.5810,
      lng: -105.0760,
      cuisine: "Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the heated patio. Craft beer bar with elevated bar food in Old Town.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.themayorofoldtown.com",
    },
    {
      name: "Cafe Vino",
      address: "1200 S College Ave, Fort Collins, CO 80524",
      lat: 40.5720,
      lng: -105.0770,
      cuisine: "Italian & Wine Bar",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Italian-inspired cuisine with an impressive wine list.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cafevino.com",
    },
    {
      name: "Choice City Butcher & Deli",
      address: "104 W Olive St, Fort Collins, CO 80524",
      lat: 40.5865,
      lng: -105.0785,
      cuisine: "Deli & Craft Beer",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Butcher shop, deli, and craft beer bar in one spot.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.choicecitybutcher.com",
    },
  ],

  cafes: [
    {
      name: "Harbinger Coffee",
      address: "320 E Vine Dr, Fort Collins, CO 80524",
      lat: 40.5900,
      lng: -105.0720,
      dogPolicy: "Dogs welcome on the outdoor patio. Premier specialty coffee roaster in Fort Collins.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.harbingercoffee.com",
    },
    {
      name: "The Bean Cycle",
      address: "144 N College Ave, Fort Collins, CO 80524",
      lat: 40.5875,
      lng: -105.0770,
      dogPolicy: "Dog-friendly patio on College Avenue. Community-focused coffee shop and roaster.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thebeancycle.com",
    },
    {
      name: "Bindle Coffee",
      address: "2201 S College Ave, Fort Collins, CO 80525",
      lat: 40.5610,
      lng: -105.0770,
      dogPolicy: "Outdoor seating welcomes dogs. Modern specialty coffee in the Midtown area.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bindlecoffee.com",
    },
    {
      name: "Mugs Coffee Lounge",
      address: "261 S College Ave, Fort Collins, CO 80524",
      lat: 40.5842,
      lng: -105.0770,
      dogPolicy: "Leashed dogs welcome at patio tables. Old Town coffee shop with local art.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.mugscoffeelounge.com",
    },
  ],

  dogParks: [
    {
      name: "Spring Canyon Community Park Dog Park",
      address: "2626 W Horsetooth Rd, Fort Collins, CO 80526",
      lat: 40.5540,
      lng: -105.1050,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: ["Separate small dog area", "Water stations", "Agility equipment", "Shade shelters", "Waste stations", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Fort Collins' best fenced off-leash dog park with separate areas, agility equipment, and Horsetooth Rock views. Always busy with happy dogs and a welcoming community.",
    },
    {
      name: "Poudre River Trail",
      address: "Poudre Trail, Fort Collins, CO 80524",
      lat: 40.5950,
      lng: -105.0600,
      offLeash: false,
      fenced: false,
      acres: 50.0,
      amenities: ["Paved trail", "River access", "Benches", "Waste stations", "Multiple trailheads"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A paved trail following the Cache la Poudre River through Fort Collins connecting to the regional trail network. Dogs must be leashed but love the river access and the cottonwood-shaded path.",
    },
    {
      name: "Horsetooth Reservoir Dog Areas",
      address: "4200 W County Rd 38E, Fort Collins, CO 80526",
      lat: 40.5500,
      lng: -105.1500,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Reservoir beach", "Swimming", "Hiking trails", "Boat ramps", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Horsetooth Reservoir west of Fort Collins offers beaches and trails with stunning foothill views. Leashed dogs can swim in designated areas and hike the surrounding trails with views of the reservoir and Rocky Mountains.",
    },
    {
      name: "Soft Gold Park Dog Park",
      address: "601 Soft Gold Park, Fort Collins, CO 80524",
      lat: 40.5920,
      lng: -105.0720,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Fenced area", "Water stations", "Waste bags", "Benches", "Near Poudre Trail"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A fenced off-leash dog park near the Poudre River Trail, making it easy to combine an off-leash play session with a riverside walk. Well-maintained with good drainage and river views.",
    },
  ],
};
