export const fortWorthData = {
  city: {
    name: "Fort Worth",
    state: "Texas",
    region: "Southwest",
    lat: 32.7555,
    lng: -97.3308,
    dogFriendlinessScore: 7,
    description:
      "Fort Worth pairs its cowboy heritage with a genuine love for dogs. The historic Stockyards welcome pups, the Trinity River trails wind through the city, and the booming Near Southside dining scene offers dog-friendly patios with some of the best food in North Texas.",
    heroImage: "https://images.unsplash.com/photo-1570089858601-5d8e28c69bc4?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 918915,
  },

  hotels: [
    {
      name: "Hotel Drover",
      address: "200 Mule Alley Dr, Fort Worth, TX 76164",
      lat: 32.7880,
      lng: -97.3490,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a pet fee. Luxury Western hotel in the Stockyards with a VIP pet program.",
      maxDogWeight: 0,
      petFee: 100,
      amenities: ["Dog bed", "Bandana", "Treats", "Walking service", "Mule Alley shopping"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.hoteldrover.com",
      phone: "(817) 755-5557",
    },
    {
      name: "The Worthington Renaissance",
      address: "200 Main St, Fort Worth, TX 76102",
      lat: 32.7560,
      lng: -97.3300,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a non-refundable fee. Downtown Sundance Square location.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Sundance Square access", "Walking maps"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(817) 870-1000",
    },
    {
      name: "Aloft Fort Worth Downtown",
      address: "334 W 3rd St, Fort Worth, TX 76102",
      lat: 32.7530,
      lng: -97.3340,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome with no weight limit. ARF pet-friendly program.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Dog bed", "Toys", "Near Trinity Trail", "Downtown location"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(817) 626-6000",
    },
    {
      name: "La Quinta Inn Fort Worth Stockyards",
      address: "2601 Cherry Ln, Fort Worth, TX 76164",
      lat: 32.7870,
      lng: -97.3450,
      priceRange: "$" as const,
      dogPolicy: "All dogs welcome at no extra charge. Near the Stockyards and Trinity River.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Near Stockyards", "Grassy area", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(817) 222-2500",
    },
  ],

  nationalParks: [
    {
      name: "Fort Worth Nature Center & Refuge",
      state: "Texas",
      lat: 32.8340,
      lng: -97.4660,
      dogPolicy: "Leashed dogs welcome on most trails. A 3,600-acre urban nature refuge.",
      dogTrails: ["Canyon Ridge Trail", "Prairie Trail", "Shoreline Trail", "Limestone Ledge Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on the Greer Island boardwalk",
        "Stay on designated trails",
      ],
      description:
        "One of the largest city-owned nature centers in the US, this 3,600-acre refuge features prairies, forests, and Lake Worth shoreline. Dogs enjoy the diverse terrain and abundant wildlife sightings.",
      imageUrl: "",
      website: "https://www.fwnaturecenter.org",
    },
    {
      name: "Trinity Trails System",
      state: "Texas",
      lat: 32.7550,
      lng: -97.3500,
      dogPolicy: "Leashed dogs welcome on all 70+ miles of paved trails through Fort Worth.",
      dogTrails: ["Trinity River Trail", "Marine Creek Trail", "Mary's Creek Trail", "Sycamore Creek Trail"],
      restrictions: [
        "Must be on leash on paved trails",
        "Yield to cyclists",
        "Clean up after your pet",
      ],
      description:
        "An extensive 70+ mile trail network following the Trinity River and its tributaries through Fort Worth. The paved trails connect parks, neighborhoods, and natural areas, offering endless dog walking options.",
      imageUrl: "",
      website: "https://www.trinitytrails.org",
    },
    {
      name: "Dinosaur Valley State Park",
      state: "Texas",
      lat: 32.2490,
      lng: -97.8120,
      dogPolicy: "Leashed dogs welcome on trails and in campgrounds. Famous for preserved dinosaur tracks.",
      dogTrails: ["Blue Trail", "Overlook Trail", "South Side Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Dogs can wade in the river but keep leashed",
        "Not allowed in group picnic areas",
      ],
      description:
        "About an hour southwest of Fort Worth, this park preserves real dinosaur footprints in the Paluxy River bed. Dogs can wade in the river with you while you explore 113-million-year-old tracks.",
      imageUrl: "",
      website: "https://www.tpwd.texas.gov/state-parks/dinosaur-valley",
    },
  ],

  restaurants: [
    {
      name: "Magnolia Motor Lounge",
      address: "3005 Bledsoe St, Fort Worth, TX 76107",
      lat: 32.7490,
      lng: -97.3510,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly with a large outdoor area. Live music and pub food in the Near Southside.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.magmotorlounge.com",
    },
    {
      name: "Heim Barbecue",
      address: "1109 W Magnolia Ave, Fort Worth, TX 76104",
      lat: 32.7410,
      lng: -97.3390,
      cuisine: "Texas Barbecue",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor picnic tables. Famous bacon burnt ends.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.heimbbq.com",
    },
    {
      name: "The Stockyards Brewing Co.",
      address: "140 E Exchange Ave, Fort Worth, TX 76164",
      lat: 32.7890,
      lng: -97.3460,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Extremely dog-friendly brewery in the historic Stockyards. Dogs are always welcome.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.stockyardsbrewing.com",
    },
    {
      name: "Bird Cafe",
      address: "155 E 4th St, Fort Worth, TX 76102",
      lat: 32.7530,
      lng: -97.3290,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the Sundance Square patio.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.birdcafefw.com",
    },
    {
      name: "Salsa Limon",
      address: "1320 S University Dr, Fort Worth, TX 76107",
      lat: 32.7380,
      lng: -97.3610,
      cuisine: "Mexican Street Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Authentic street tacos near TCU.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.salsalimon.com",
    },
  ],

  cafes: [
    {
      name: "Avoca Coffee Roasters",
      address: "1311 W Magnolia Ave, Fort Worth, TX 76104",
      lat: 32.7410,
      lng: -97.3410,
      dogPolicy: "Dogs welcome on the front patio. Locally roasted specialty coffee on Magnolia.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.avocacoffee.com",
    },
    {
      name: "Crude Coffee Bar",
      address: "3300 Ross Ave, Fort Worth, TX 76106",
      lat: 32.7650,
      lng: -97.3400,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Quality coffee in a modern setting.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.crudecoffee.com",
    },
    {
      name: "Roots Coffeehouse",
      address: "1201 6th Ave, Fort Worth, TX 76104",
      lat: 32.7430,
      lng: -97.3280,
      dogPolicy: "Dog-friendly patio near the Medical District. Community coffee shop.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.rootscoffeehouse.com",
    },
    {
      name: "Summer Moon Coffee",
      address: "2551 Forest Park Blvd, Fort Worth, TX 76110",
      lat: 32.7350,
      lng: -97.3500,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Moon milk lattes and a Texas vibe.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.summermoon.com",
    },
  ],

  dogParks: [
    {
      name: "Fort Woof Dog Park",
      address: "901 5th Ave, Fort Worth, TX 76104",
      lat: 32.7440,
      lng: -97.3270,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: ["Separate small dog area", "Swimming pond", "Agility equipment", "Water stations", "Shade"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Fort Worth's premier off-leash park features a swimming pond, agility equipment, and separate areas for large and small dogs. The fun name matches the fun atmosphere.",
    },
    {
      name: "ZBonz Dog Park",
      address: "2500 Panther Island Pkwy, Fort Worth, TX 76164",
      lat: 32.7700,
      lng: -97.3490,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Trinity River views", "Water stations", "Shade structures", "Waste stations", "Near trail"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A Trinity River-adjacent dog park near the Stockyards with nice views and good facilities. Dogs can play off-leash then enjoy an on-leash walk along the nearby Trinity Trail.",
    },
    {
      name: "Trinity Park",
      address: "2401 University Dr, Fort Worth, TX 76109",
      lat: 32.7450,
      lng: -97.3570,
      offLeash: false,
      fenced: false,
      acres: 250.0,
      amenities: ["Trinity River access", "Paved trails", "Shade trees", "Picnic areas", "Duck pond"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A beautiful 250-acre park along the Trinity River with shaded trails and river access. On-leash dogs enjoy the diverse scenery and connection to the greater Trinity Trail network.",
    },
    {
      name: "Gateway Dog Park",
      address: "1050 E Seminary Dr, Fort Worth, TX 76115",
      lat: 32.7210,
      lng: -97.3220,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Double-gated entry", "Water fountains", "Benches", "Waste stations", "Shade trees"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A south-side dog park with a friendly neighborhood feel. The well-fenced area provides a safe space for dogs of all sizes to run and socialize.",
    },
  ],
};
