export const fridayHarborData = {
  city: {
    name: "Friday Harbor",
    state: "Washington",
    region: "Pacific Northwest",
    lat: 48.5343,
    lng: -123.0170,
    dogFriendlinessScore: 7,
    description:
      "Friday Harbor on San Juan Island is a charming ferry-accessible village where dogs enjoy island life at its finest. With scenic coastal walks, whale watching from shore, and a walkable downtown full of galleries and eateries with dog-friendly patios, this island getaway is a tail-wagging adventure.",
    heroImage: "https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=1200&fit=crop",
    climate: "Oceanic marine",
    population: 2350,
  },

  hotels: [
    {
      name: "Friday Harbor House",
      address: "130 West St, Friday Harbor, WA 98250",
      lat: 48.5350,
      lng: -123.0175,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in select harbor-view rooms. Boutique hotel overlooking the marina and harbor.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Harbor views", "Walking map", "Near waterfront trails"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.fridayharborhouse.com",
      phone: "(360) 378-8455",
    },
    {
      name: "Island Inn at 123 West",
      address: "123 West St, Friday Harbor, WA 98250",
      lat: 48.5348,
      lng: -123.0172,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in pet-friendly suites with private balconies. Walking distance to everything.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Private balcony", "Dog bed", "Water bowls", "Downtown location", "Near ferry terminal"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.islandinn123.com",
      phone: "(360) 378-4400",
    },
    {
      name: "Discovery Inn",
      address: "1016 Guard St, Friday Harbor, WA 98250",
      lat: 48.5330,
      lng: -123.0140,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome with a small pet fee. Basic comfortable lodging near downtown.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Grassy areas", "Walking distance to town", "Pet waste stations", "Water bowls"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.discoveryinn.com",
      phone: "(360) 378-2000",
    },
    {
      name: "Lakedale Resort at Three Lakes",
      address: "4313 Roche Harbor Rd, Friday Harbor, WA 98250",
      lat: 48.5600,
      lng: -123.0800,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in log cabins and canvas cottages. Set on 82 acres with three lakes and forest trails.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Lake access", "Hiking trails", "Kayaking", "Private cabin yards", "Forest walks"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.lakedale.com",
      phone: "(360) 378-2350",
    },
  ],

  nationalParks: [
    {
      name: "San Juan Island National Historical Park",
      state: "Washington",
      lat: 48.5100,
      lng: -123.0300,
      dogPolicy: "Leashed dogs welcome on all trails and grounds at both American Camp and English Camp.",
      dogTrails: ["South Beach Trail", "Lagoon Trail", "Mount Finlayson Trail", "Bell Point Trail"],
      restrictions: [
        "Must be on leash (6 ft max) at all times",
        "Not allowed in buildings",
        "Clean up after your pet",
      ],
      description:
        "This national park spans two sites on San Juan Island commemorating the Pig War boundary dispute. Both American Camp and English Camp offer spectacular coastal trails, prairie walks, and forest paths where leashed dogs are welcome.",
      imageUrl: "",
      website: "https://www.nps.gov/sajh",
    },
    {
      name: "Moran State Park (Orcas Island)",
      state: "Washington",
      lat: 48.6560,
      lng: -122.8340,
      dogPolicy: "Leashed dogs welcome on most trails. A ferry ride away on Orcas Island but worth the day trip.",
      dogTrails: ["Mount Constitution Summit Trail", "Cascade Falls Trail", "Mountain Lake Loop"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed in swim areas",
        "Not allowed in buildings",
      ],
      description:
        "On neighboring Orcas Island, this 5,252-acre state park offers mountaintop views, waterfalls, and old-growth forest. The drive or hike to the top of Mount Constitution provides the best view in the San Juan Islands.",
      imageUrl: "",
      website: "https://www.parks.wa.gov/moranstatepark",
    },
    {
      name: "Lime Kiln Point State Park",
      state: "Washington",
      lat: 48.5160,
      lng: -123.1520,
      dogPolicy: "Leashed dogs welcome on the trails and whale watching areas. One of the best shore-based whale watching spots.",
      dogTrails: ["Lighthouse Trail", "Coastal Bluff Walk"],
      restrictions: [
        "Must be on leash at all times",
        "Stay on designated trails",
        "Not allowed in lighthouse interior",
      ],
      description:
        "Known as Whale Watch Park, this is one of the best places in the world to watch orcas from shore. Leashed dogs can join you on the rocky bluffs as you scan for whales in Haro Strait with the Olympic Mountains as a backdrop.",
      imageUrl: "",
      website: "https://www.parks.wa.gov/limekilnpoint",
    },
  ],

  restaurants: [
    {
      name: "The Bluff",
      address: "130 West St, Friday Harbor, WA 98250",
      lat: 48.5352,
      lng: -123.0178,
      cuisine: "Pacific Northwest",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the outdoor terrace with harbor views. Upscale island dining with local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.fridayharborhouse.com/dining",
    },
    {
      name: "Cask & Schooner Public House",
      address: "1 Front St, Friday Harbor, WA 98250",
      lat: 48.5345,
      lng: -123.0180,
      cuisine: "Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the waterfront patio. Casual pub overlooking the ferry landing.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.caskandschooner.com",
    },
    {
      name: "San Juan Island Brewing Company",
      address: "One Cannery Landing, Friday Harbor, WA 98250",
      lat: 48.5340,
      lng: -123.0190,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly outdoor seating area. Island-brewed craft beer with pub food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.sjibrewing.com",
    },
    {
      name: "Rocky Bay Cafe",
      address: "225 Spring St, Friday Harbor, WA 98250",
      lat: 48.5340,
      lng: -123.0155,
      cuisine: "American Breakfast & Lunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Beloved island breakfast spot with generous portions.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.rockybay.cafe",
    },
    {
      name: "Market Chef",
      address: "225 A St, Friday Harbor, WA 98250",
      lat: 48.5338,
      lng: -123.0160,
      cuisine: "Deli & Prepared Foods",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor seating area. Fresh prepared foods perfect for a picnic with your pup.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marketchef.com",
    },
  ],

  cafes: [
    {
      name: "San Juan Island Coffee Roasters",
      address: "18 Cannery Landing, Friday Harbor, WA 98250",
      lat: 48.5342,
      lng: -123.0188,
      dogPolicy: "Dogs welcome on the waterfront patio. Locally roasted coffee with harbor views.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sjicoffeeroasters.com",
    },
    {
      name: "Bakery San Juan",
      address: "175 1st St N, Friday Harbor, WA 98250",
      lat: 48.5356,
      lng: -123.0168,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Artisan bakery with organic breads and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bakerysanjuan.com",
    },
    {
      name: "Little Store & Deli",
      address: "315 Spring St, Friday Harbor, WA 98250",
      lat: 48.5342,
      lng: -123.0148,
      dogPolicy: "Outdoor bench seating welcomes dogs. Quick coffee and snacks for on-the-go island exploring.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.littlestoresji.com",
    },
    {
      name: "Harbor Cafe",
      address: "100 Spring St, Friday Harbor, WA 98250",
      lat: 48.5345,
      lng: -123.0170,
      dogPolicy: "Dog-friendly patio near the ferry terminal. Coffee and light fare for early morning ferry arrivals.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.harborcafesji.com",
    },
  ],

  dogParks: [
    {
      name: "San Juan Island Dog Park",
      address: "Mullis St, Friday Harbor, WA 98250",
      lat: 48.5300,
      lng: -123.0140,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Water station", "Benches", "Waste bags", "Shade trees"],
      rating: 4.2,
      imageUrl: "",
      description:
        "The island's dedicated off-leash dog park provides a fenced area for pups to play. A community gathering spot where island dogs and visiting pups meet and socialize.",
    },
    {
      name: "South Beach at American Camp",
      address: "American Camp, San Juan Island, WA 98250",
      lat: 48.4600,
      lng: -122.9650,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Sandy beach", "Driftwood", "Wildlife viewing", "Prairie walks", "Parking", "Restrooms"],
      rating: 4.7,
      imageUrl: "",
      description:
        "The longest public beach on San Juan Island, South Beach at American Camp offers over a mile of driftwood-strewn shoreline with views of the Olympic Mountains. Leashed dogs love the beach walks and prairie trails.",
    },
    {
      name: "Jackson Beach",
      address: "Argyle Ave, Friday Harbor, WA 98250",
      lat: 48.5250,
      lng: -123.0100,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Beach access", "Picnic tables", "Boat launch area", "Parking", "Restrooms"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A small but scenic beach south of Friday Harbor with easy access. Leashed dogs enjoy the rocky shoreline and calm waters of Griffin Bay. A peaceful spot for an afternoon walk.",
    },
    {
      name: "English Camp Grounds",
      address: "English Camp, San Juan Island, WA 98250",
      lat: 48.5830,
      lng: -123.1450,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Historic buildings", "Garden trails", "Beach access", "Forest trails", "Parking", "Restrooms"],
      rating: 4.5,
      imageUrl: "",
      description:
        "The English Camp unit of the national park features a formal English garden, old-growth forest, and a peaceful beach on Garrison Bay. Leashed dogs can explore the grounds, hike to Young Hill summit, and enjoy the tranquil setting.",
    },
  ],
};
