export const galenaData = {
  city: {
    name: "Galena",
    state: "Illinois",
    region: "Midwest",
    lat: 42.4167,
    lng: -90.4290,
    dogFriendlinessScore: 7,
    description:
      "Galena is a beautifully preserved 19th-century lead mining town in the rolling hills of northwest Illinois. Its Main Street is packed with dog-friendly shops and restaurants, and the surrounding countryside offers scenic drives and hiking that dogs adore.",
    heroImage: "https://images.unsplash.com/photo-1517164850305-99a3e65bb47e?w=1200&fit=crop",
    climate: "Humid continental",
    population: 3225,
  },

  hotels: [
    {
      name: "DeSoto House Hotel",
      address: "230 S Main St, Galena, IL 61036",
      lat: 42.4160,
      lng: -90.4290,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select pet-friendly rooms with a one-time fee. Historic hotel since 1855.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Historic setting", "Main Street location", "Walking maps"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.desotohouse.com",
      phone: "(815) 777-0090",
    },
    {
      name: "Stoney Creek Hotel Galena",
      address: "940 Galena Square Dr, Galena, IL 61036",
      lat: 42.4280,
      lng: -90.4170,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a non-refundable pet fee. Lodge-style hotel with spacious grounds.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Grassy grounds", "Near hiking trails", "Indoor pool", "Fire pit", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.stoneycreekhotels.com",
      phone: "(815) 777-2223",
    },
    {
      name: "Eagle Ridge Resort & Spa",
      address: "444 Eagle Ridge Dr, Galena, IL 61036",
      lat: 42.3720,
      lng: -90.3710,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in resort homes and inn rooms with a pet fee. Expansive wooded resort property.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Resort grounds", "Nature trails", "Lake access", "Spacious accommodations", "Dog walking paths"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.eagleridge.com",
      phone: "(815) 776-5000",
    },
    {
      name: "Best Western Designer Inn & Suites",
      address: "9923 US-20, Galena, IL 61036",
      lat: 42.4330,
      lng: -90.4100,
      priceRange: "$" as const,
      dogPolicy: "Pets welcome with a nightly fee. Affordable and convenient.",
      maxDogWeight: 80,
      petFee: 20,
      amenities: ["Grassy area", "Near restaurants", "Waste bags", "Easy highway access"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(815) 777-2577",
    },
  ],

  nationalParks: [
    {
      name: "Mississippi Palisades State Park",
      state: "Illinois",
      lat: 42.1010,
      lng: -90.1670,
      dogPolicy: "Leashed dogs welcome on all trails. Stunning bluffs overlooking the Mississippi River.",
      dogTrails: ["Sentinel Trail", "Indian Head Trail", "North Trail", "South Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Stay on marked trails near cliff edges",
        "Not allowed in lodges or shelters",
      ],
      description:
        "About 30 minutes south of Galena, this state park features dramatic limestone bluffs rising above the Mississippi River. The challenging trails reward dogs and hikers with breathtaking river valley views.",
      imageUrl: "",
      website: "https://www.dnr.illinois.gov",
    },
    {
      name: "Apple River Canyon State Park",
      state: "Illinois",
      lat: 42.4470,
      lng: -90.0990,
      dogPolicy: "Leashed dogs welcome on trails and in picnic areas. A hidden gem of northwest Illinois.",
      dogTrails: ["Canyon Trail", "Sunset Trail", "Pine Ridge Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed in the stream during spawning season",
        "Stay on designated trails",
      ],
      description:
        "This lesser-known state park features a scenic canyon carved by the Apple River, with limestone bluffs, pine forests, and wildflower meadows. The quiet trails make it a peaceful retreat for dogs.",
      imageUrl: "",
      website: "https://www.dnr.illinois.gov",
    },
    {
      name: "Casper Bluff Land and Water Reserve",
      state: "Illinois",
      lat: 42.4040,
      lng: -90.3880,
      dogPolicy: "Leashed dogs welcome on the trails. Native American effigy mounds and Mississippi River views.",
      dogTrails: ["Bluff Trail", "Mound Trail", "River Overlook Path"],
      restrictions: [
        "Must be on leash",
        "Do not walk on or disturb the effigy mounds",
        "Stay on marked trails",
      ],
      description:
        "A remarkable preserve near Galena featuring ancient Native American effigy mounds and panoramic views of the Mississippi River valley. The hilltop trails offer dogs a sensory-rich walk through prairie and woodland.",
      imageUrl: "",
      website: "https://www.jodaviesscounty.org",
    },
  ],

  restaurants: [
    {
      name: "Fried Green Tomatoes",
      address: "213 N Main St, Galena, IL 61036",
      lat: 42.4175,
      lng: -90.4290,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the outdoor patio. Award-winning Italian in a historic building.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.friedgreentomatoesrestaurant.com",
    },
    {
      name: "Galena Brewing Company",
      address: "227 N Main St, Galena, IL 61036",
      lat: 42.4177,
      lng: -90.4291,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Local craft beers and pub food on Main Street.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.galenabrewery.com",
    },
    {
      name: "Fritz and Frites",
      address: "317 N Main St, Galena, IL 61036",
      lat: 42.4183,
      lng: -90.4293,
      cuisine: "French-German",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Unique French-German cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.fritzandfrites.com",
    },
    {
      name: "Log Cabin Steakhouse",
      address: "201 N Main St, Galena, IL 61036",
      lat: 42.4173,
      lng: -90.4289,
      cuisine: "Steakhouse",
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome on the patio during season. Historic steakhouse in a Greek Revival building.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.logcabingalena.com",
    },
    {
      name: "Durty Gurt's Burger Joynt",
      address: "235 N Main St, Galena, IL 61036",
      lat: 42.4178,
      lng: -90.4291,
      cuisine: "Burgers",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor picnic tables. Gourmet burgers and shakes on Main Street.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.durtygurts.com",
    },
  ],

  cafes: [
    {
      name: "Galena Roasters",
      address: "223 S Main St, Galena, IL 61036",
      lat: 42.4155,
      lng: -90.4288,
      dogPolicy: "Dogs welcome at the outdoor sidewalk tables. Fresh-roasted coffee on Main Street.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.galenaroasters.com",
    },
    {
      name: "Bread & Vine Bakery",
      address: "219 S Main St, Galena, IL 61036",
      lat: 42.4153,
      lng: -90.4287,
      dogPolicy: "Leashed dogs welcome outside. Artisan breads, pastries, and espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.breadandvinegalena.com",
    },
    {
      name: "The Java Hut",
      address: "120 N Main St, Galena, IL 61036",
      lat: 42.4168,
      lng: -90.4288,
      dogPolicy: "Outdoor tables welcome leashed dogs. Quick coffee stop on Main Street.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.javahutgalena.com",
    },
    {
      name: "Gobbie's Sports Pub & Eatery",
      address: "219 N Main St, Galena, IL 61036",
      lat: 42.4176,
      lng: -90.4290,
      dogPolicy: "Dogs welcome on the outdoor seating area. Coffee and casual fare.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.gobbies.com",
    },
  ],

  dogParks: [
    {
      name: "Grant Park",
      address: "625 Park Ave, Galena, IL 61036",
      lat: 42.4140,
      lng: -90.4240,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Walking paths", "Historic monuments", "Hilltop views", "Benches", "Shade trees"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A historic hilltop park with panoramic views of Galena's rooftops and the surrounding valley. The shaded walking paths wind past Civil War monuments, making for a scenic on-leash stroll.",
    },
    {
      name: "Recreation Park",
      address: "1001 Dewey Ave, Galena, IL 61036",
      lat: 42.4200,
      lng: -90.4210,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced dog area", "Water fountain", "Waste stations", "Benches", "Shade"],
      rating: 4.2,
      imageUrl: "",
      description:
        "Galena's community park includes a fenced off-leash area where dogs can play freely. The friendly small-town atmosphere means your dog will quickly make new friends.",
    },
    {
      name: "Galena River Trail",
      address: "Depot Park, Galena, IL 61036",
      lat: 42.4165,
      lng: -90.4280,
      offLeash: false,
      fenced: false,
      acres: 50.0,
      amenities: ["Paved trail", "River views", "Benches", "Interpretive signs", "Parking at depot"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A beautiful 8.3-mile paved trail following the Galena River to the Mississippi. Dogs love this flat, scenic route that passes through farmland, marshes, and along the gentle river.",
    },
    {
      name: "Buehler Preserve",
      address: "Dewey Ave, Galena, IL 61036",
      lat: 42.4230,
      lng: -90.4250,
      offLeash: false,
      fenced: false,
      acres: 35.0,
      amenities: ["Nature trails", "Forest paths", "Wildlife viewing", "Quiet setting", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A peaceful nature preserve on the edge of Galena with wooded trails through rolling terrain. The quiet, uncrowded paths are ideal for dogs who prefer a tranquil nature walk.",
    },
  ],
};
