export const galvestonData = {
  city: {
    name: "Galveston",
    state: "Texas",
    region: "Southwest",
    lat: 29.3013,
    lng: -94.7977,
    dogFriendlinessScore: 7,
    description:
      "This historic island city on the Texas Gulf Coast is a tail-wagging beach town where salty breezes and sandy paws are a way of life. With miles of dog-friendly beaches, a vibrant Strand District welcoming pups on patios, and warm Gulf waters perfect for splashing, Galveston proves that everything really is bigger in Texas — including the love for dogs.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 53695,
  },

  hotels: [
    {
      name: "Hotel Galvez & Spa",
      address: "2024 Seawall Blvd, Galveston, TX 77550",
      lat: 29.2855,
      lng: -94.7913,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome in designated pet rooms. Historic beachfront elegance meets dog-friendly hospitality.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Bowls", "Treats at check-in", "Beachfront access", "Dog-walking service referral"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelgalvez.com",
      phone: "(409) 765-7721",
    },
    {
      name: "The Tremont House",
      address: "2300 Ships Mechanic Row, Galveston, TX 77550",
      lat: 29.3095,
      lng: -94.7912,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with advance notice. Boutique hotel in the heart of the historic Strand District.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Walking maps", "Steps from The Strand", "Rooftop bar access"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thetremonthouse.com",
      phone: "(409) 763-0300",
    },
    {
      name: "La Quinta Inn & Suites Galveston Seawall",
      address: "1402 Seawall Blvd, Galveston, TX 77550",
      lat: 29.2880,
      lng: -94.7850,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with no pet fee — a rarity on the island. Seawall location with beach access.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Beach access", "Pool", "Waste stations", "Walking paths"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta",
      phone: "(409) 763-1224",
    },
    {
      name: "Holiday Inn Resort Galveston",
      address: "5002 Seawall Blvd, Galveston, TX 77551",
      lat: 29.2762,
      lng: -94.8115,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms with ocean views. Dogs welcome with a nightly fee. Direct beach access for sandy adventures.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Beach access", "Pool", "Dog bowls on request", "Balcony rooms", "Waste stations"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(409) 740-3581",
    },
    {
      name: "Harbor House at Pier 21",
      address: "28 Pier 21, Galveston, TX 77550",
      lat: 29.3098,
      lng: -94.7875,
      priceRange: "$$$" as const,
      dogPolicy: "Select rooms welcome dogs with a one-time fee. Waterfront boutique hotel with harbor views.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Harbor views", "Dog bed", "Treats", "Walking along the pier", "Near Strand restaurants"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.harborhousepier21.com",
      phone: "(409) 763-3321",
    },
  ],

  nationalParks: [
    {
      name: "Padre Island National Seashore",
      state: "Texas",
      lat: 26.9319,
      lng: -97.4078,
      dogPolicy: "Dogs allowed on the beach on leash. One of the longest undeveloped barrier islands in the world. Open to dogs in most areas except turtle nesting zones.",
      dogTrails: [
        "North Beach area",
        "Malaquite Beach (leashed)",
        "South Beach vehicle area",
        "Campground areas",
      ],
      restrictions: [
        "Must be on leash (6 ft max) at all times",
        "Not allowed in turtle nesting areas during season",
        "Not allowed in the visitor center",
        "Carry water — limited shade on the beach",
      ],
      description:
        "A stunning 70-mile stretch of undeveloped Texas coastline where leashed dogs can run along the surf. While it is a longer drive from Galveston, the wild, empty beaches and shorebird watching make it an epic dog-friendly coastal adventure.",
      imageUrl: "",
      website: "https://www.nps.gov/pais",
    },
    {
      name: "Big Thicket National Preserve",
      state: "Texas",
      lat: 30.4579,
      lng: -94.3861,
      dogPolicy: "Leashed dogs welcome on all trails. A biological crossroads with an incredible diversity of ecosystems.",
      dogTrails: [
        "Kirby Nature Trail",
        "Turkey Creek Trail",
        "Sundew Trail",
        "Beaver Slide Trail",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Watch for alligators and snakes",
        "Carry insect repellent",
        "Stay on marked trails",
      ],
      description:
        "Called the 'biological crossroads of North America,' Big Thicket welcomes leashed dogs on all its trails through cypress swamps, pitcher plant bogs, and pine forests. A two-hour drive from Galveston with nine distinct ecosystems to explore.",
      imageUrl: "",
      website: "https://www.nps.gov/bith",
    },
    {
      name: "San Antonio Missions National Historical Park",
      state: "Texas",
      lat: 29.3275,
      lng: -98.4543,
      dogPolicy: "Leashed dogs welcome on the grounds and along the Mission Reach Trail. A UNESCO World Heritage Site with excellent dog-friendly walking.",
      dogTrails: [
        "Mission Reach Trail (8 miles)",
        "Mission grounds walking paths",
        "Hike-and-bike trail between missions",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Not allowed inside mission churches",
        "Must stay on paved paths",
      ],
      description:
        "Five Spanish colonial missions connected by a beautiful riverside trail make this a fantastic leashed dog destination. The eight-mile Mission Reach Trail follows the San Antonio River and is perfect for a history-rich walk with your pup.",
      imageUrl: "",
      website: "https://www.nps.gov/saan",
    },
  ],

  restaurants: [
    {
      name: "Mosquito Cafe",
      address: "628 14th St, Galveston, TX 77550",
      lat: 29.2987,
      lng: -94.7848,
      cuisine: "Eclectic American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the charming garden patio. A Galveston brunch institution with fresh, creative dishes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.mosquitocafe.com",
    },
    {
      name: "Shrimp N Stuff",
      address: "3901 Ave O, Galveston, TX 77550",
      lat: 29.2945,
      lng: -94.7735,
      cuisine: "Seafood",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor picnic tables. Fresh Gulf shrimp in every style imaginable.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.shrimpnstuff.com",
    },
    {
      name: "Brews Brothers",
      address: "2404 The Strand, Galveston, TX 77550",
      lat: 29.3093,
      lng: -94.7895,
      cuisine: "Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Pups welcome on the outdoor patio along The Strand. Craft beer and elevated pub grub.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.brewsbrothersgalveston.com",
    },
    {
      name: "The Spot",
      address: "3204 Seawall Blvd, Galveston, TX 77550",
      lat: 29.2810,
      lng: -94.7988,
      cuisine: "Beachside American",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly lower deck with Gulf views. A multi-level beach hangout serving burgers, tacos, and frozen drinks.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thespotgalveston.com",
    },
    {
      name: "Little Daddy's Gumbo Bar",
      address: "2107 Postoffice St, Galveston, TX 77550",
      lat: 29.3030,
      lng: -94.7918,
      cuisine: "Cajun & Creole",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Authentic Louisiana-style gumbo and po'boys on the island.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.littledaddysgumbobar.com",
    },
    {
      name: "Galveston Island Brewing",
      address: "8423 Stewart Rd, Galveston, TX 77554",
      lat: 29.2585,
      lng: -94.8690,
      cuisine: "Brewery & Food Trucks",
      priceRange: "$" as const,
      dogPolicy: "Extremely dog-friendly taproom with a big yard. Rotating food trucks and island-inspired craft brews.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.galvestonislandbrewing.com",
    },
    {
      name: "Rudy & Paco",
      address: "2028 Postoffice St, Galveston, TX 77550",
      lat: 29.3028,
      lng: -94.7930,
      cuisine: "Latin-Caribbean Steakhouse",
      priceRange: "$$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the sidewalk patio. Upscale dining with Caribbean flair.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.rudyandpaco.com",
    },
    {
      name: "Fish Tales",
      address: "25th St & Seawall Blvd, Galveston, TX 77550",
      lat: 29.2835,
      lng: -94.7953,
      cuisine: "Seafood & Oyster Bar",
      priceRange: "$$" as const,
      dogPolicy: "Dogs allowed on the spacious beach-facing patio. Fresh oysters, fried fish, and ocean views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.fishtalesgalveston.com",
    },
  ],

  cafes: [
    {
      name: "MOD Coffee House",
      address: "2126 Postoffice St, Galveston, TX 77550",
      lat: 29.3032,
      lng: -94.7915,
      dogPolicy: "Leashed dogs welcome on the covered patio. Hip coffee house in a historic Strand-area building.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.modcoffeehouse.com",
    },
    {
      name: "Galveston Coffee Roasters",
      address: "228 Tremont St, Galveston, TX 77550",
      lat: 29.3090,
      lng: -94.7928,
      dogPolicy: "Patio seating available for guests with dogs. Locally roasted beans with Gulf Coast soul.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.galvestoncoffeeroasters.com",
    },
    {
      name: "Cafe Kemah",
      address: "2024 Strand St, Galveston, TX 77550",
      lat: 29.3095,
      lng: -94.7935,
      dogPolicy: "Dogs welcome at outdoor tables in the historic Strand District. Pastries and espresso in island style.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Sunflower Bakery & Cafe",
      address: "512 14th St, Galveston, TX 77550",
      lat: 29.2990,
      lng: -94.7852,
      dogPolicy: "Garden patio welcomes leashed dogs. Fresh-baked goods and strong Texas coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.sunflowerbakeryandcafe.com",
    },
    {
      name: "Press Coffee",
      address: "2317 Market St, Galveston, TX 77550",
      lat: 29.3050,
      lng: -94.7900,
      dogPolicy: "Sidewalk seating for pup parents. Specialty coffee and cold brew to beat the island heat.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.1,
      imageUrl: "",
      website: "",
    },
  ],

  dogParks: [
    {
      name: "Galveston Island State Park Dog Beach",
      address: "14901 FM 3005, Galveston, TX 77554",
      lat: 29.2360,
      lng: -94.9180,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Beach access", "Bay and Gulf shoreline", "Waste stations", "Parking", "Kayak launch"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Galveston Island State Park offers both bay and Gulf shoreline where leashed dogs can splash in the surf, dig in the sand, and chase seagulls to their heart's content. The bay side is calmer for timid swimmers.",
    },
    {
      name: "East Beach Off-Leash Area",
      address: "1923 Boddeker Dr, Galveston, TX 77550",
      lat: 29.3210,
      lng: -94.7425,
      offLeash: true,
      fenced: false,
      acres: 8.0,
      amenities: ["Beach access", "Parking", "Restrooms", "Concession stands nearby", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "The easternmost beach on the island has a designated area where dogs can run off-leash in the sand and surf. Watching a Lab launch into the Gulf waves here is pure joy. Seasonal restrictions may apply.",
    },
    {
      name: "Schreiber Park Dog Area",
      address: "3302 Ave S, Galveston, TX 77550",
      lat: 29.2935,
      lng: -94.7715,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Water station", "Shade trees", "Benches", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A neighborhood fenced dog park where island pups gather for off-leash play. Shaded by live oaks and close to residential areas, it is a convenient spot for daily exercise.",
    },
    {
      name: "Seawall Urban Park Path",
      address: "Seawall Blvd, Galveston, TX 77550",
      lat: 29.2850,
      lng: -94.7950,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Paved walking path", "Ocean views", "Benches", "Waste stations", "Restaurant access"],
      rating: 4.5,
      imageUrl: "",
      description:
        "The 10-mile Seawall path is Galveston's premier dog walking route with unobstructed Gulf views, ocean breezes, and easy access to dog-friendly restaurants and shops along the boulevard.",
    },
    {
      name: "Lafitte's Cove Nature Preserve",
      address: "Eckert Dr, Galveston, TX 77554",
      lat: 29.2680,
      lng: -94.8550,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Nature trails", "Bird watching", "Wetland boardwalk", "Parking", "Scenic overlooks"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A hidden gem nature preserve with trails through coastal wetlands and maritime forest. Leashed dogs can enjoy birdwatching walks along boardwalks while spotting herons, roseate spoonbills, and migrating songbirds.",
    },
  ],
};
