export const glenwoodSpringsData = {
  city: {
    name: "Glenwood Springs",
    state: "Colorado",
    region: "Mountain West",
    lat: 39.5505,
    lng: -107.3248,
    dogFriendlinessScore: 7,
    description:
      "Glenwood Springs sits at the confluence of the Colorado and Roaring Fork Rivers, famous for its hot springs and Glenwood Canyon. Dogs enjoy the extensive trail system, the Rio Grande Trail connecting to Aspen, and a walkable downtown with dog-friendly restaurants. The dramatic canyon scenery and mountain trails make this a stellar dog destination.",
    heroImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 10070,
  },

  hotels: [
    {
      name: "Hotel Denver",
      address: "402 7th St, Glenwood Springs, CO 81601",
      lat: 39.5510,
      lng: -107.3240,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with advance notice. Historic 1906 hotel near the hot springs.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Walking map", "Near river trail", "Downtown location"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thehoteldenver.com",
      phone: "(970) 945-6565",
    },
    {
      name: "Hotel Colorado",
      address: "526 Pine St, Glenwood Springs, CO 81601",
      lat: 39.5515,
      lng: -107.3230,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in pet-friendly rooms with a per-night fee. Grand historic hotel since 1893.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Dog bed", "Treats", "Historic grounds", "Near hot springs pool", "Walking paths"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hotelcolorado.com",
      phone: "(970) 945-6511",
    },
    {
      name: "Residence Inn Glenwood Springs",
      address: "125 Wulfsohn Rd, Glenwood Springs, CO 81601",
      lat: 39.5420,
      lng: -107.3380,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a non-refundable pet fee. Extended stay suites with kitchens.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Grassy areas", "Pet waste stations", "Near bike path", "Water bowls"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(970) 928-0900",
    },
    {
      name: "Glenwood Hot Springs Lodge",
      address: "415 E 6th St, Glenwood Springs, CO 81601",
      lat: 39.5505,
      lng: -107.3225,
      priceRange: "$$" as const,
      dogPolicy: "Dogs allowed in select pet rooms. Located at the world's largest hot springs pool (no dogs in pool).",
      maxDogWeight: 40,
      petFee: 35,
      amenities: ["Near hot springs", "Walking paths", "Dog bed", "Water bowls", "River trail access"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.hotspringspool.com",
      phone: "(970) 945-6571",
    },
  ],

  nationalParks: [
    {
      name: "White River National Forest (Glenwood District)",
      state: "Colorado",
      lat: 39.6000,
      lng: -107.4000,
      dogPolicy: "Dogs welcome on most trails. Leash in developed areas; voice control in backcountry.",
      dogTrails: ["Hanging Lake Trail (no dogs)", "Grizzly Creek Trail", "Boy Scout Trail", "Jess Weaver Trail"],
      restrictions: [
        "No dogs on Hanging Lake Trail",
        "Leash required in campgrounds",
        "Voice control on backcountry trails",
      ],
      description:
        "The national forest around Glenwood Springs offers canyon trails, mountain hikes, and riverside paths. Note that Hanging Lake does NOT allow dogs, but many excellent alternatives exist in the surrounding forest.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/whiteriver",
    },
    {
      name: "Glenwood Canyon Recreation Path",
      state: "Colorado",
      lat: 39.5650,
      lng: -107.2400,
      dogPolicy: "Leashed dogs welcome on the entire 16-mile paved path through the canyon.",
      dogTrails: ["Glenwood Canyon Bike Path", "Grizzly Creek Rest Stop trails"],
      restrictions: [
        "Must be on leash at all times",
        "Stay on designated path",
        "Be aware of cyclists",
      ],
      description:
        "A spectacular 16-mile paved path through Glenwood Canyon along the Colorado River. The towering canyon walls rise 1,300 feet on either side, and leashed dogs enjoy the flat, scenic walk through one of Colorado's most dramatic landscapes.",
      imageUrl: "",
      website: "https://www.rfta.com",
    },
    {
      name: "Flat Tops Wilderness",
      state: "Colorado",
      lat: 39.9000,
      lng: -107.3000,
      dogPolicy: "Dogs welcome off-leash under voice control in the wilderness. Remote and uncrowded.",
      dogTrails: ["Devil's Causeway Trail", "Trappers Lake Trail", "Stillwater Trail"],
      restrictions: [
        "Must be under voice control",
        "Pack out all waste",
        "High altitude areas - acclimate dogs",
      ],
      description:
        "The Flat Tops Wilderness north of Glenwood Springs features a massive volcanic plateau with alpine lakes, meadows, and dramatic cliff formations. The Devil's Causeway is one of Colorado's most thrilling hikes.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/whiteriver",
    },
  ],

  restaurants: [
    {
      name: "Glenwood Canyon Brewing Company",
      address: "402 7th St, Glenwood Springs, CO 81601",
      lat: 39.5512,
      lng: -107.3242,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Local craft brewery in the Hotel Denver building.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.glenwoodcanyon.com",
    },
    {
      name: "Juicy Lucy's Steakhouse",
      address: "308 7th St, Glenwood Springs, CO 81601",
      lat: 39.5508,
      lng: -107.3248,
      cuisine: "Steakhouse",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor deck. Premium steaks and seafood downtown.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.juicylucyssteakhouse.com",
    },
    {
      name: "Slope & Hatch",
      address: "720 Grand Ave, Glenwood Springs, CO 81601",
      lat: 39.5502,
      lng: -107.3255,
      cuisine: "Mexican & Southwestern",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio. Creative Mexican cuisine with local ingredients.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.slopeandhatch.com",
    },
    {
      name: "Riviera Supper Club",
      address: "702 Grand Ave, Glenwood Springs, CO 81601",
      lat: 39.5500,
      lng: -107.3258,
      cuisine: "Italian-American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome at outdoor seating. Classic supper club ambiance with Italian flavors.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.rivieraglenwood.com",
    },
    {
      name: "Smoke Modern BBQ",
      address: "826 Grand Ave, Glenwood Springs, CO 81601",
      lat: 39.5498,
      lng: -107.3260,
      cuisine: "BBQ",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Slow-smoked BBQ with craft beer.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.smokebbqglenwood.com",
    },
  ],

  cafes: [
    {
      name: "Bluebird Cafe",
      address: "727 Grand Ave, Glenwood Springs, CO 81601",
      lat: 39.5503,
      lng: -107.3253,
      dogPolicy: "Dogs welcome on the sidewalk patio. Cozy cafe with fresh pastries and local coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bluebirdcafe.com",
    },
    {
      name: "Sacred Grounds Coffee",
      address: "729 Grand Ave, Glenwood Springs, CO 81601",
      lat: 39.5504,
      lng: -107.3252,
      dogPolicy: "Outdoor seating welcomes dogs. Community coffee shop on Grand Avenue.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.sacredgrounds.coffee",
    },
    {
      name: "Cream Puff Bakery & Cafe",
      address: "809 Grand Ave, Glenwood Springs, CO 81601",
      lat: 39.5497,
      lng: -107.3262,
      dogPolicy: "Dog-friendly outdoor seating. French-style bakery with cream puffs and espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.creampuffbakery.com",
    },
    {
      name: "Springs Coffee Co.",
      address: "519 Pine St, Glenwood Springs, CO 81601",
      lat: 39.5513,
      lng: -107.3232,
      dogPolicy: "Leashed dogs welcome at patio tables. Specialty coffee near the hot springs.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.springscoffeeco.com",
    },
  ],

  dogParks: [
    {
      name: "Glenwood Springs Dog Park at Veltus Park",
      address: "Midland Ave, Glenwood Springs, CO 81601",
      lat: 39.5480,
      lng: -107.3300,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Water station", "Waste bags", "Benches", "Mountain views"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Glenwood Springs' fenced off-leash dog park with mountain and river valley views. A well-maintained community spot for dogs to play and socialize.",
    },
    {
      name: "Rio Grande Trail",
      address: "7th St Trailhead, Glenwood Springs, CO 81601",
      lat: 39.5510,
      lng: -107.3245,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Paved trail", "River views", "Benches", "Waste stations", "Multiple access points"],
      rating: 4.6,
      imageUrl: "",
      description:
        "The 42-mile Rio Grande Trail starts in Glenwood Springs and follows the Roaring Fork River to Aspen. The Glenwood Springs section offers beautiful river views and a flat, accessible path for leashed dog walks.",
    },
    {
      name: "Red Mountain Trail",
      address: "Red Mountain Trailhead, Glenwood Springs, CO 81601",
      lat: 39.5600,
      lng: -107.3400,
      offLeash: true,
      fenced: false,
      acres: 40.0,
      amenities: ["Mountain trails", "Valley views", "Wildflowers", "Parking", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Trails on Red Mountain above Glenwood Springs offering panoramic views of the valley, the Colorado River, and the surrounding mountains. Dogs can be off-leash under voice control on these less-traveled paths.",
    },
    {
      name: "Two Rivers Park",
      address: "Devereux Rd, Glenwood Springs, CO 81601",
      lat: 39.5490,
      lng: -107.3280,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["River confluence", "Walking paths", "Open fields", "Picnic areas", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A park at the confluence of the Colorado and Roaring Fork Rivers with walking paths and open space. Leashed dogs enjoy the riverside setting and the unique vantage point where two great rivers meet.",
    },
  ],
};
