export const grandRapidsData = {
  city: {
    name: "Grand Rapids",
    state: "Michigan",
    region: "Midwest",
    lat: 42.9634,
    lng: -85.6681,
    dogFriendlinessScore: 7,
    description:
      "Grand Rapids is a craft beer capital with a surprisingly warm welcome for dogs. With dozens of dog-friendly brewery taprooms, expansive riverside trails, and a growing arts district that embraces pets, this west Michigan city is a must-visit for traveling dog owners.",
    heroImage: "https://images.unsplash.com/photo-1568992688065-536aad8a12f6?w=1200&fit=crop",
    climate: "Humid continental",
    population: 198917,
  },

  hotels: [
    {
      name: "Amway Grand Plaza Hotel",
      address: "187 Monroe Ave NW, Grand Rapids, MI 49503",
      lat: 42.9674,
      lng: -85.6728,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a one-time pet fee. Historic luxury hotel on the Grand River.",
      maxDogWeight: 75,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats", "Riverwalk access", "Concierge pet services"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.amwaygrand.com",
      phone: "(616) 774-2000",
    },
    {
      name: "CityFlats Hotel",
      address: "83 Monroe Center St NW, Grand Rapids, MI 49503",
      lat: 42.9668,
      lng: -85.6706,
      priceRange: "$$" as const,
      dogPolicy: "Boutique hotel welcoming dogs of all sizes. Green-certified and pet-friendly.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Dog bed", "Bowls", "Eco-friendly amenities", "Downtown location", "Walking maps"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cityflatshotel.com",
      phone: "(616) 608-1720",
    },
    {
      name: "Home2 Suites Downtown",
      address: "101 Ionia Ave SW, Grand Rapids, MI 49503",
      lat: 42.9635,
      lng: -85.6695,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly suites with a non-refundable fee. Extended-stay amenities and grassy areas nearby.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Kitchen suite", "Grassy area", "Near Ah-Nab-Awen Park", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(616) 451-2201",
    },
    {
      name: "JW Marriott Grand Rapids",
      address: "235 Louis St NW, Grand Rapids, MI 49503",
      lat: 42.9690,
      lng: -85.6740,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 40 lbs welcome with advance notice and pet fee. Premium riverfront accommodations.",
      maxDogWeight: 40,
      petFee: 100,
      amenities: ["Luxury dog bed", "Gourmet treats", "Water bowls", "Riverwalk access", "Pet-sitting referral"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(616) 242-1500",
    },
  ],

  nationalParks: [
    {
      name: "Sleeping Bear Dunes National Lakeshore",
      state: "Michigan",
      lat: 44.8084,
      lng: -86.0559,
      dogPolicy: "Leashed dogs allowed on some beaches and trails. Not permitted on the Dune Climb or Platte River trails.",
      dogTrails: ["Empire Bluff Trail", "Good Harbor Bay Trail", "Sleeping Bear Point Trail"],
      restrictions: [
        "Must be on a 6-foot leash at all times",
        "Not allowed on Dune Climb",
        "Not permitted on Platte River Point beach",
        "Not allowed on North Manitou or South Manitou islands",
      ],
      description:
        "About two hours north of Grand Rapids, Sleeping Bear Dunes features towering sand bluffs overlooking Lake Michigan. Select trails allow leashed dogs to experience the stunning dune landscapes and forested bluffs.",
      imageUrl: "",
      website: "https://www.nps.gov/slbe",
    },
    {
      name: "Manistee National Forest",
      state: "Michigan",
      lat: 44.2500,
      lng: -85.9800,
      dogPolicy: "Dogs welcome on all trails. Voice control or leash recommended on busy trails.",
      dogTrails: ["North Country Trail", "Manistee River Trail", "Nordhouse Dunes Trail", "Pine River Trail"],
      restrictions: [
        "Leash required in developed campgrounds",
        "Must be under control at all times",
        "Clean up after your pet",
      ],
      description:
        "Spanning over 540,000 acres of northern Michigan forest, Manistee National Forest offers some of the best dog-friendly hiking in the state. The Manistee River Trail loop is a classic backpacking adventure to share with your pup.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/manistee",
    },
    {
      name: "Hoffmaster State Park",
      state: "Michigan",
      lat: 43.1003,
      lng: -86.2593,
      dogPolicy: "Leashed dogs allowed on most trails and the beach. A beautiful Lake Michigan dune park close to Grand Rapids.",
      dogTrails: ["Dune Climb Stairway Trail", "Homestead Trail", "Beach Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed in the nature center",
        "Must stay on designated trails",
      ],
      description:
        "Just 30 minutes from Grand Rapids, this state park offers forested dune trails and a gorgeous Lake Michigan beach. The varied terrain of dunes, forest, and shoreline gives dogs an exciting sensory experience.",
      imageUrl: "",
      website: "https://www.michigan.gov/hoffmaster",
    },
  ],

  restaurants: [
    {
      name: "Brewery Vivant",
      address: "925 Cherry St SE, Grand Rapids, MI 49506",
      lat: 42.9562,
      lng: -85.6544,
      cuisine: "Belgian-Inspired",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the large outdoor beer garden. Belgian-inspired food and craft ales in a converted chapel.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.breweryvivant.com",
    },
    {
      name: "Founders Brewing Co.",
      address: "235 Grandville Ave SW, Grand Rapids, MI 49503",
      lat: 42.9581,
      lng: -85.6762,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor patio. One of the nation's top craft breweries.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.foundersbrewing.com",
    },
    {
      name: "The Chop House",
      address: "190 Monroe Ave NW, Grand Rapids, MI 49503",
      lat: 42.9675,
      lng: -85.6730,
      cuisine: "Steakhouse",
      priceRange: "$$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the riverfront patio during warmer months.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thechophouseusa.com",
    },
    {
      name: "Donkey Taqueria",
      address: "665 Wealthy St SE, Grand Rapids, MI 49503",
      lat: 42.9558,
      lng: -85.6578,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Creative tacos and margaritas in the Wealthy Street district.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.donkeygr.com",
    },
    {
      name: "Two Scotts BBQ",
      address: "1 Ionia Ave SW, Grand Rapids, MI 49503",
      lat: 42.9643,
      lng: -85.6693,
      cuisine: "Barbecue",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor picnic tables. Slow-smoked meats with Michigan craft beer.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.twoscottsbbq.com",
    },
  ],

  cafes: [
    {
      name: "Madcap Coffee",
      address: "98 Monroe Center St NW, Grand Rapids, MI 49503",
      lat: 42.9670,
      lng: -85.6710,
      dogPolicy: "Dogs welcome at the outdoor sidewalk tables. Nationally recognized specialty coffee roasters.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.madcapcoffee.com",
    },
    {
      name: "Squibb Coffee & Wine Bar",
      address: "501 Wealthy St SE, Grand Rapids, MI 49503",
      lat: 42.9555,
      lng: -85.6600,
      dogPolicy: "Leashed dogs welcome on the patio. Coffee by day, wine by night in a charming setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.squibbcoffee.com",
    },
    {
      name: "Ferris Coffee & Nut",
      address: "963 Wealthy St SE, Grand Rapids, MI 49506",
      lat: 42.9558,
      lng: -85.6510,
      dogPolicy: "Dog-friendly patio seating. A Grand Rapids institution roasting coffee since 1924.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ferriscoffee.com",
    },
    {
      name: "Roots Brew Shop",
      address: "40 Monroe Center NW, Grand Rapids, MI 49503",
      lat: 42.9667,
      lng: -85.6700,
      dogPolicy: "Outdoor seating welcomes dogs. Specialty drinks and a cozy downtown vibe.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.rootsbrewshop.com",
    },
  ],

  dogParks: [
    {
      name: "Riverside Dog Park",
      address: "2000 Monroe Ave NE, Grand Rapids, MI 49505",
      lat: 42.9780,
      lng: -85.6660,
      offLeash: true,
      fenced: true,
      acres: 4.0,
      amenities: ["River access", "Separate small dog area", "Water fountains", "Shade trees", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Grand Rapids' premier off-leash park sits along the Grand River, offering dogs a chance to splash and play. Separate areas for large and small dogs ensure safe fun for all.",
    },
    {
      name: "Covell Dog Park",
      address: "1531 Covell Ave NW, Grand Rapids, MI 49504",
      lat: 42.9750,
      lng: -85.6930,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Double-gated entry", "Water stations", "Benches", "Shade structures", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A well-maintained neighborhood dog park on the west side with a friendly community of regulars. The fenced area provides a safe space for dogs of all energy levels.",
    },
    {
      name: "Breton Downs Dog Park",
      address: "2200 Breton Rd SE, Grand Rapids, MI 49506",
      lat: 42.9410,
      lng: -85.6360,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Agility equipment", "Water fountains", "Benches", "Waste stations", "Parking"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A popular southeast-side dog park with agility equipment and plenty of room to run. The well-drained grounds stay usable even after Michigan rain.",
    },
    {
      name: "Ah-Nab-Awen Park Riverwalk",
      address: "220 Front Ave NW, Grand Rapids, MI 49504",
      lat: 42.9695,
      lng: -85.6760,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Paved riverwalk", "Scenic views", "Benches", "Public art", "Near downtown dining"],
      rating: 4.4,
      imageUrl: "",
      description:
        "While not off-leash, this beautiful riverfront park offers a paved walking path with views of the Grand River and downtown skyline. A perfect on-leash stroll before hitting the nearby brewery patios.",
    },
  ],
};
