export const greenvilleData = {
  city: {
    name: "Greenville",
    state: "South Carolina",
    region: "Southeast",
    lat: 34.8526,
    lng: -82.3940,
    dogFriendlinessScore: 7,
    description:
      "Greenville has quietly become one of the South's most dog-friendly cities, and locals are not quiet about it at all. The stunning Swamp Rabbit Trail stretches for miles along the Reedy River, downtown is packed with dog-welcoming patios, and Falls Park on the Reedy is an urban oasis where pups strut across the iconic Liberty Bridge. From brewery taprooms to boutique shops that keep treat jars by the door, Greenville treats every dog like a VIP.",
    heroImage: "https://images.unsplash.com/photo-1570641963303-92ce4845ed4c?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 72095,
  },

  hotels: [
    {
      name: "The Westin Poinsett",
      address: "120 S Main St, Greenville, SC 29601",
      lat: 34.8510,
      lng: -82.3999,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with Westin's signature Heavenly Dog Bed. Walking distance to Falls Park and the Swamp Rabbit Trail.",
      maxDogWeight: 50,
      petFee: 0,
      amenities: ["Heavenly Dog Bed", "Food and water bowls", "Dog walking map", "Near Falls Park", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.marriott.com/hotels/travel/gspwi-the-westin-poinsett-greenville",
      phone: "(864) 421-9700",
    },
    {
      name: "Aloft Greenville Downtown",
      address: "5 N Laurens St, Greenville, SC 29601",
      lat: 34.8520,
      lng: -82.3985,
      priceRange: "$$" as const,
      dogPolicy: "Arf program welcomes dogs of all sizes at no extra charge. Treats at check-in and a dog-friendly lounge atmosphere.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Bowls", "Treats at check-in", "Dog toy lending", "Downtown location"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marriott.com/hotels/travel/gspal-aloft-greenville-downtown",
      phone: "(864) 297-6100",
    },
    {
      name: "Grand Bohemian Hotel Greenville",
      address: "6 S Main St, Greenville, SC 29601",
      lat: 34.8530,
      lng: -82.3995,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in this art-inspired luxury hotel. A bone-shaped treat and plush bed await your pup at check-in.",
      maxDogWeight: 0,
      petFee: 100,
      amenities: ["Custom dog bed", "Gourmet treats", "Art-filled lobby walks", "Concierge pet services", "Near Reedy River"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.grandbohemianhotelgreenville.com",
      phone: "(864) 345-4600",
    },
    {
      name: "Hyatt Regency Greenville",
      address: "220 N Main St, Greenville, SC 29601",
      lat: 34.8545,
      lng: -82.3990,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a one-time pet fee. Connected to the downtown dining and entertainment district.",
      maxDogWeight: 75,
      petFee: 75,
      amenities: ["Dog bed", "Bowls", "Waste bags", "Walking routes", "Near Cleveland Park"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hyatt.com/en-US/hotel/south-carolina/hyatt-regency-greenville",
      phone: "(864) 235-1234",
    },
    {
      name: "Swamp Rabbit Inn",
      address: "320 Hampton Ave, Greenville, SC 29601",
      lat: 38.8550,
      lng: -82.4010,
      priceRange: "$$" as const,
      dogPolicy: "This cozy boutique inn sits right on the Swamp Rabbit Trail. Dogs are cherished guests with trail access from the front door.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Trail access", "Dog bed", "Treat bag", "Fenced courtyard", "Outdoor shower for muddy paws"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.swamprabbitinn.com",
      phone: "(864) 414-0079",
    },
  ],

  nationalParks: [
    {
      name: "Congaree National Park",
      state: "South Carolina",
      lat: 33.7948,
      lng: -80.7821,
      dogPolicy: "Leashed dogs allowed on all trails including the elevated Boardwalk Loop. One of the most dog-friendly national parks in the Southeast.",
      dogTrails: ["Boardwalk Loop Trail", "Weston Lake Loop Trail", "Oakridge Trail", "River Trail"],
      restrictions: [
        "Must be on leash (6 ft max) at all times",
        "Not allowed in backcountry camping areas",
        "Owners must clean up after dogs",
      ],
      description:
        "About two hours south of Greenville, this primeval old-growth bottomland hardwood forest is a hidden gem. Your leashed pup can walk the stunning 2.4-mile elevated boardwalk through a canopy of massive trees, champion-sized loblolly pines, and bald cypresses draped in Spanish moss.",
      imageUrl: "",
      website: "https://www.nps.gov/cong",
    },
    {
      name: "Great Smoky Mountains National Park",
      state: "North Carolina / Tennessee",
      lat: 35.6118,
      lng: -83.4895,
      dogPolicy: "Dogs allowed on two specific trails and in developed areas only. Very limited dog access but scenic driving is excellent.",
      dogTrails: ["Gatlinburg Trail", "Oconaluftee River Trail"],
      restrictions: [
        "Dogs only allowed on two trails",
        "Must be on leash (6 ft max) at all times",
        "Not allowed on other trails or in the backcountry",
        "Not allowed in buildings",
      ],
      description:
        "America's most visited national park is about two hours northwest of Greenville. While trail access for dogs is extremely limited, the Oconaluftee River Trail is a beautiful riverside walk, and scenic drives through the park offer jaw-dropping mountain views that you and your pup can enjoy together.",
      imageUrl: "",
      website: "https://www.nps.gov/grsm",
    },
    {
      name: "Blue Ridge Parkway",
      state: "North Carolina / Virginia",
      lat: 35.5651,
      lng: -82.4868,
      dogPolicy: "Leashed dogs welcome on most trails along the parkway. Excellent dog-friendly hiking with spectacular mountain views.",
      dogTrails: ["Graveyard Fields Trail", "Skinny Dip Falls Trail", "Craggy Gardens Trail", "Devil's Courthouse Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed in buildings or visitor centers",
        "Some trails may have seasonal closures",
      ],
      description:
        "The 469-mile scenic drive through the Blue Ridge Mountains passes just an hour from Greenville and offers hundreds of dog-friendly trailheads. Your pup can hike through wildflower meadows, past waterfalls, and along ridgelines with views that stretch forever. This is Appalachian tail-wagging at its finest.",
      imageUrl: "",
      website: "https://www.nps.gov/blri",
    },
    {
      name: "Kings Mountain National Military Park",
      state: "South Carolina",
      lat: 35.1391,
      lng: -81.3898,
      dogPolicy: "Leashed dogs welcome on all trails within the park. A great historical hiking destination for dogs and history buffs.",
      dogTrails: ["Battlefield Trail", "Browns Mountain Trail"],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Not allowed in buildings",
      ],
      description:
        "About 90 minutes east of Greenville, this Revolutionary War battlefield offers peaceful hiking trails through Southern Piedmont forest. The 1.5-mile Battlefield Trail is a shady, well-maintained loop that gives your dog a great walk while you soak in American history.",
      imageUrl: "",
      website: "https://www.nps.gov/kimo",
    },
  ],

  restaurants: [
    {
      name: "Lazy Goat",
      address: "170 River Pl, Greenville, SC 29601",
      lat: 34.8490,
      lng: -82.4010,
      cuisine: "Mediterranean",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the riverside patio overlooking the Reedy River and Falls Park. A top-tier dining experience with a view your pup will love.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thelazygote.com",
    },
    {
      name: "Swamp Rabbit Cafe & Grocery",
      address: "205 Cedar Lane Rd, Greenville, SC 29611",
      lat: 34.8610,
      lng: -82.4120,
      cuisine: "Farm-to-Table Cafe",
      priceRange: "$$" as const,
      dogPolicy: "Super dog-friendly cafe right on the Swamp Rabbit Trail. Dogs are the real regulars here with treats and water always available.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.swamprabbitcafe.com",
    },
    {
      name: "Jianna",
      address: "10 N Main St, Greenville, SC 29601",
      lat: 34.8530,
      lng: -82.3993,
      cuisine: "Italian Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the front patio. Upscale Italian seafood on Main Street with impeccable Southern hospitality for humans and hounds alike.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.jiannagreenville.com",
    },
    {
      name: "Brewery 85",
      address: "6 Whitlee Ct, Greenville, SC 29607",
      lat: 34.8425,
      lng: -82.3735,
      cuisine: "Brewery & Food Trucks",
      priceRange: "$$" as const,
      dogPolicy: "Dogs rule the taproom and patio at this popular brewery. Expect to see more dogs than people on a Saturday afternoon.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.brewery85.com",
    },
    {
      name: "The Anchorage",
      address: "547 S Main St, Greenville, SC 29601",
      lat: 34.8465,
      lng: -82.4005,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the patio of this James Beard-nominated restaurant. Upscale Southern cuisine in a converted gas station.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.theanchoragegvl.com",
    },
    {
      name: "Taco Boy",
      address: "110 Augusta St, Greenville, SC 29601",
      lat: 34.8488,
      lng: -82.4030,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly patio with a festive atmosphere. Tacos and margaritas while your pup soaks up the Augusta Street vibe.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tacoboy.net",
    },
    {
      name: "Nose Dive",
      address: "116 S Main St, Greenville, SC 29601",
      lat: 34.8505,
      lng: -82.3998,
      cuisine: "Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Spacious dog-friendly patio on Main Street. Creative gastropub fare and an impressive craft cocktail menu.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.nosedivegreenville.com",
    },
    {
      name: "Southern Pressed Juicery",
      address: "2 W Washington St, Greenville, SC 29601",
      lat: 34.8522,
      lng: -82.4002,
      cuisine: "Juice Bar & Health Food",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at the outdoor counter seating. Fresh juices and smoothie bowls for you, and a head pat from the friendly staff for your pup.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.southernpressedjuicery.com",
    },
  ],

  cafes: [
    {
      name: "Methodical Coffee",
      address: "101 N Main St, Greenville, SC 29601",
      lat: 34.8535,
      lng: -82.3992,
      dogPolicy: "Nationally acclaimed specialty coffee with a dog-friendly sidewalk patio on Main Street. Your pup becomes part of the downtown scene.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.methodicalcoffee.com",
    },
    {
      name: "Spill the Beans",
      address: "531 S Main St, Greenville, SC 29601",
      lat: 34.8468,
      lng: -82.4003,
      dogPolicy: "Cozy neighborhood coffee shop with outdoor seating where dogs are regulars. Known for their homemade pastries and friendly atmosphere.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.spillthebeansgvl.com",
    },
    {
      name: "Port City Java",
      address: "315 S Main St, Greenville, SC 29601",
      lat: 34.8490,
      lng: -82.3999,
      dogPolicy: "Dog-friendly patio in the West End district. A reliable caffeine stop with plenty of room for your leashed pup.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.portcityjava.com",
    },
    {
      name: "Grateful Brew",
      address: "200 Augusta St, Greenville, SC 29601",
      lat: 34.8492,
      lng: -82.4035,
      dogPolicy: "Chill coffeehouse on Augusta Street with outdoor seating and dog treats at the counter. A favorite among the Swamp Rabbit Trail crowd.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.gratefulbrew.com",
    },
    {
      name: "Coffee Underground",
      address: "1 E Coffee St, Greenville, SC 29601",
      lat: 34.8515,
      lng: -82.3990,
      dogPolicy: "Quirky basement coffee shop with a small sidewalk patio where dogs can join you. Live music and poetry nights add to the bohemian vibe.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.coffeeunderground.info",
    },
  ],

  dogParks: [
    {
      name: "Unleashed Dog Park",
      address: "1400 Cleveland Park Dr, Greenville, SC 29601",
      lat: 34.8620,
      lng: -82.3930,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water fountains", "Agility equipment", "Shade shelters", "Waste stations", "Benches"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Greenville's premier off-leash dog park in beautiful Cleveland Park offers separate areas for large and small dogs, agility equipment for the overachievers, and plenty of shade for the loungers. Conveniently located near the Swamp Rabbit Trail for a post-park stroll.",
    },
    {
      name: "Falls Park on the Reedy",
      address: "601 S Main St, Greenville, SC 29601",
      lat: 34.8460,
      lng: -82.4010,
      offLeash: false,
      fenced: false,
      acres: 32.0,
      amenities: ["Paved walkways", "Waterfall views", "Gardens", "Liberty Bridge", "Benches", "Waste stations"],
      rating: 4.8,
      imageUrl: "",
      description:
        "One of the most beautiful urban parks in America, Falls Park features a stunning waterfall, the curved Liberty Bridge, manicured gardens, and winding paths along the Reedy River. Leashed dogs are welcome throughout and will love the sounds of rushing water and the admiring attention of passersby.",
    },
    {
      name: "Swamp Rabbit Trail",
      address: "Swamp Rabbit Trail, Greenville, SC 29601",
      lat: 34.8580,
      lng: -82.4060,
      offLeash: false,
      fenced: false,
      acres: 50.0,
      amenities: ["Paved multi-use trail", "River views", "Water fountains", "Waste stations", "Restaurant access", "Restrooms"],
      rating: 4.7,
      imageUrl: "",
      description:
        "The beloved 22-mile Swamp Rabbit Trail follows the Reedy River from downtown Greenville to Travelers Rest. Leashed dogs love this paved path that passes breweries, cafes, parks, and river access points. It is the social spine of Greenville's dog community.",
    },
    {
      name: "Conestee Park Dog Park",
      address: "840 Mauldin Rd, Greenville, SC 29607",
      lat: 34.8180,
      lng: -82.3750,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Water station", "Shade trees", "Waste bags", "Parking"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A southside off-leash park adjacent to the Conestee Nature Preserve. After your dog burns off energy in the fenced area, snap on the leash and explore the preserve's boardwalks and wildlife-viewing platforms together.",
    },
    {
      name: "Cleveland Park",
      address: "150 Cleveland Park Dr, Greenville, SC 29601",
      lat: 34.8615,
      lng: -82.3920,
      offLeash: false,
      fenced: false,
      acres: 126.0,
      amenities: ["Walking trails", "Zoo proximity", "Playground", "Rock Quarry Garden", "Waste stations", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Greenville's largest urban park sprawls along the Reedy River with miles of walking trails through mature hardwoods. Leashed dogs enjoy the shaded paths, and the park connects to the Swamp Rabbit Trail for extended adventures. A Greenville dog essential.",
    },
  ],
};
