export const halfMoonBayData = {
  city: {
    name: "Half Moon Bay",
    state: "California",
    region: "West Coast",
    lat: 37.4636,
    lng: -122.4286,
    dogFriendlinessScore: 8,
    description:
      "This charming coastal town south of San Francisco offers spectacular dog-friendly beaches, coastal bluff trails, and a quaint downtown with farm-to-table restaurants. The dramatic Pacific coastline and laid-back agricultural community create a perfect escape for dogs and their owners.",
    heroImage: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=1200&fit=crop",
    climate: "Oceanic",
    population: 11324,
  },
  hotels: [
    {
      name: "The Ritz-Carlton, Half Moon Bay",
      address: "1 Miramontes Point Rd, Half Moon Bay, CA 94019",
      lat: 37.4350,
      lng: -122.4400,
      priceRange: "$$$$" as const,
      dogPolicy: "Luxury oceanfront resort welcoming dogs under 30 lbs. Coastal bluff trails and fire pits with dramatic Pacific views.",
      maxDogWeight: 30,
      petFee: 200,
      amenities: ["Dog bed", "Treats", "Coastal trails", "Fire pits", "Pet concierge"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.ritzcarlton.com/halfmoonbay",
      phone: "(650) 712-7000",
    },
    {
      name: "Beach House Hotel Half Moon Bay",
      address: "4100 N Cabrillo Hwy, Half Moon Bay, CA 94019",
      lat: 37.4800,
      lng: -122.4500,
      priceRange: "$$$" as const,
      dogPolicy: "Beachfront hotel with pet-friendly suites and full kitchens. Dogs welcome with direct beach access and ocean views.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Ocean views", "Full kitchen", "Beach access", "Dog bed", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.beach-house.com",
      phone: "(650) 712-0220",
    },
    {
      name: "Half Moon Bay Lodge",
      address: "2400 S Cabrillo Hwy, Half Moon Bay, CA 94019",
      lat: 37.4500,
      lng: -122.4350,
      priceRange: "$$" as const,
      dogPolicy: "Comfortable lodge welcoming dogs of all sizes near beaches and downtown. Spacious rooms with garden views.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Pet-friendly rooms", "Garden", "Pool", "Near beach", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.halfmoonbaylodge.com",
      phone: "(650) 726-9000",
    },
    {
      name: "Quality Inn Half Moon Bay",
      address: "2930 N Cabrillo Hwy, Half Moon Bay, CA 94019",
      lat: 37.4650,
      lng: -122.4400,
      priceRange: "$" as const,
      dogPolicy: "Affordable pet-friendly option with easy access to beaches and downtown. Dogs welcome with a small fee.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Pet-friendly rooms", "Parking", "Breakfast", "Near beach", "Waste bags"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.choicehotels.com",
      phone: "(650) 726-6400",
    },
  ],
  nationalParks: [
    {
      name: "Half Moon Bay State Beach",
      state: "California",
      lat: 37.4600,
      lng: -122.4450,
      dogPolicy: "Dogs allowed on the beach on leash. Multiple beach access points along the dramatic San Mateo Coast.",
      dogTrails: ["Coastal Trail", "Francis Beach Trail", "Venice Beach Access", "Dunes Beach Trail"],
      restrictions: ["6-foot leash required", "Day use fee at some parking areas", "Watch for sneaker waves", "Clean up after pet"],
      description: "The state beach stretches along several miles of Half Moon Bay's coast, offering broad sandy beaches, bluff trails, and dramatic ocean views. Dogs on leash can enjoy multiple beach areas and the connecting coastal trail.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/halfmoonbay",
    },
    {
      name: "Purisima Creek Redwoods Open Space Preserve",
      state: "California",
      lat: 37.4300,
      lng: -122.3700,
      dogPolicy: "Dogs allowed on the Purisima Creek Trail on leash. Stunning redwood forest hiking in the Santa Cruz Mountains.",
      dogTrails: ["Purisima Creek Trail", "North Ridge Trail"],
      restrictions: ["Leash required at all times", "Dogs on select trails only", "Muddy in wet season", "Steep terrain"],
      description: "This magnificent preserve in the Santa Cruz Mountains offers trails through towering redwood forests and along creek canyons. Dogs on leash can experience old-growth-scale trees within minutes of the coastline.",
      imageUrl: "",
      website: "https://www.openspace.org/purisima",
    },
    {
      name: "Pillar Point Bluff",
      state: "California",
      lat: 37.4900,
      lng: -122.4900,
      dogPolicy: "Dogs welcome on the bluff trails on leash. Spectacular coastal headland with views of Mavericks surf break and Pillar Point Harbor.",
      dogTrails: ["Pillar Point Bluff Trail", "Jean Lauer Trail"],
      restrictions: ["Leash required", "Stay back from cliff edges", "Muddy in wet season", "Wind can be strong"],
      description: "A dramatic coastal headland overlooking the famous Mavericks big wave surf break. Dogs on leash can walk the bluff trails with sweeping views of the Pacific, harbor, and surrounding coastline.",
      imageUrl: "",
      website: "https://www.smcgov.org/parks",
    },
  ],
  restaurants: [
    {
      name: "Sam's Chowder House",
      address: "4210 N Cabrillo Hwy, Half Moon Bay, CA 94019",
      lat: 37.4810,
      lng: -122.4510,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Oceanfront seafood restaurant with a large patio overlooking the Pacific. Dogs welcome on the patio with stunning sunset views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.samschowderhouse.com",
    },
    {
      name: "It's Italia",
      address: "401 Main St, Half Moon Bay, CA 94019",
      lat: 37.4640,
      lng: -122.4280,
      cuisine: "Italian",
      priceRange: "$$" as const,
      dogPolicy: "Downtown Italian restaurant with a garden patio where dogs are welcome. Handmade pasta and wood-fired pizzas.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.itsitalia.com",
    },
    {
      name: "Pasta Moon",
      address: "315 Main St, Half Moon Bay, CA 94019",
      lat: 37.4635,
      lng: -122.4275,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Acclaimed Italian restaurant with a sidewalk patio welcoming dogs. Farm-to-table Italian cuisine with local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.pastamoon.com",
    },
    {
      name: "The Half Moon Bay Brewing Company",
      address: "390 Capistrano Rd, Half Moon Bay, CA 94019",
      lat: 37.5020,
      lng: -122.4800,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Waterfront brewery with a huge dog-friendly patio overlooking the harbor. Craft beers and pub fare with ocean views.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hmbbrewingco.com",
    },
    {
      name: "San Benito House Deli",
      address: "356 Main St, Half Moon Bay, CA 94019",
      lat: 37.4638,
      lng: -122.4278,
      cuisine: "Deli & Café",
      priceRange: "$" as const,
      dogPolicy: "Charming downtown deli with outdoor seating where dogs are welcome. Sandwiches, salads, and garden dining.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.sanbenitohouse.com",
    },
  ],
  cafes: [
    {
      name: "Equator Coffees Half Moon Bay",
      address: "407 Main St, Half Moon Bay, CA 94019",
      lat: 37.4641,
      lng: -122.4282,
      dogPolicy: "Specialty roaster with a courtyard patio in downtown Half Moon Bay. Dogs welcome outside with excellent single-origin coffees.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.equatorcoffees.com",
    },
    {
      name: "Half Moon Bay Coffee Co.",
      address: "20 Stone Pine Center, Half Moon Bay, CA 94019",
      lat: 37.4620,
      lng: -122.4300,
      dogPolicy: "Local coffee shop with a patio where dogs are regular visitors. A community gathering spot with fresh coffee and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hmbcoffee.com",
    },
    {
      name: "Garden Deli Café",
      address: "325 Main St, Half Moon Bay, CA 94019",
      lat: 37.4636,
      lng: -122.4276,
      dogPolicy: "Garden café on Main Street with outdoor tables where dogs are welcome. Light bites, coffee, and a relaxed coastal vibe.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.gardendelicafe.com",
    },
    {
      name: "Moonside Bakery & Café",
      address: "604 Main St, Half Moon Bay, CA 94019",
      lat: 37.4650,
      lng: -122.4290,
      dogPolicy: "Popular bakery with outdoor bench seating where dogs can join you. Fresh pastries, artisan bread, and coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.moonsidebakery.com",
    },
  ],
  dogParks: [
    {
      name: "Poplar Beach",
      address: "Poplar St, Half Moon Bay, CA 94019",
      lat: 37.4550,
      lng: -122.4450,
      offLeash: true,
      fenced: false,
      acres: 10,
      amenities: ["Beach access", "Bluff trail", "Open sand", "Waste bag stations", "Free parking"],
      rating: 4.7,
      imageUrl: "",
      description: "Half Moon Bay's most popular dog-friendly beach where dogs run off-leash on the wide, sandy shore. The adjacent bluff trail offers stunning coastal views, and the free parking makes it an accessible everyday destination.",
    },
    {
      name: "Coastal Trail (Half Moon Bay)",
      address: "Kelly Ave & Cabrillo Hwy, Half Moon Bay, CA 94019",
      lat: 37.4630,
      lng: -122.4420,
      offLeash: false,
      fenced: false,
      acres: 20,
      amenities: ["Paved trail", "Ocean views", "Beach access points", "Benches", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "A scenic paved trail running along the bluffs above Half Moon Bay's beaches. Leashed dogs enjoy the ocean views, sea breezes, and multiple beach access points along this beautiful coastal corridor.",
    },
    {
      name: "Quarry Park",
      address: "Pilarcitos Creek Rd, Half Moon Bay, CA 94019",
      lat: 37.4680,
      lng: -122.4250,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Fenced area", "Water station", "Shade trees", "Benches", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "A fenced off-leash dog park near downtown Half Moon Bay with shade trees and water stations. A convenient spot for dogs to play and socialize in a contained environment.",
    },
    {
      name: "Wavecrest Open Space",
      address: "Wavecrest Rd, Half Moon Bay, CA 94019",
      lat: 37.4400,
      lng: -122.4400,
      offLeash: false,
      fenced: false,
      acres: 40,
      amenities: ["Walking trails", "Coastal views", "Open meadows", "Bird watching", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description: "An open space preserve on the southern end of Half Moon Bay with trails through coastal meadows to the bluffs. Leashed dogs enjoy the spacious terrain and sweeping ocean views on this less-crowded alternative.",
    },
  ],
};
