export const healdsburgData = {
  city: {
    name: "Healdsburg",
    state: "California",
    region: "West Coast",
    lat: 38.6105,
    lng: -122.8697,
    dogFriendlinessScore: 8,
    description:
      "Nestled in the heart of Sonoma County wine country, Healdsburg is a charming small town where vineyard dogs are practically celebrities. With a gorgeous central plaza, world-class tasting rooms that roll out the welcome mat for pups, and farm-to-table restaurants with shaded patios, this is the kind of place where your dog sips water from artisan bowls while you sip Pinot Noir. Trails wind through oak-studded hills and along the Russian River, making every walk a postcard moment.",
    heroImage: "https://images.unsplash.com/photo-1560840067-ddcaeb7831d2?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 11874,
  },

  hotels: [
    {
      name: "Hotel Healdsburg",
      address: "25 Matheson St, Healdsburg, CA 95448",
      lat: 38.6107,
      lng: -122.8689,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs of all sizes welcome. Boutique luxury on the plaza with custom dog beds delivered to your room upon arrival.",
      maxDogWeight: 0,
      petFee: 100,
      amenities: ["Designer dog bed", "Organic treats", "Water bowls", "Walking map of dog-friendly wineries", "Concierge pet services"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.hotelhealdsburg.com",
      phone: "(707) 431-2800",
    },
    {
      name: "Harmon Guest House",
      address: "227 Healdsburg Ave, Healdsburg, CA 95448",
      lat: 38.6115,
      lng: -122.8695,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with a per-night fee. Rooftop lounge offers stunning views you can share with your pup.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Bowls", "Treat bag", "Rooftop access", "Walking route guide"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.harmonguesthouse.com",
      phone: "(707) 922-5251",
    },
    {
      name: "Best Western Dry Creek Inn",
      address: "198 Dry Creek Rd, Healdsburg, CA 95448",
      lat: 38.6190,
      lng: -122.8712,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms available with a per-night pet fee. Close to Dry Creek Valley wineries and trails.",
      maxDogWeight: 80,
      petFee: 30,
      amenities: ["Dog bed on request", "Waste bags", "Grassy walking area", "Near Dry Creek Trail"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.drycreekinn.com",
      phone: "(707) 433-0300",
    },
    {
      name: "Duchamp Hotel",
      address: "421 Foss St, Healdsburg, CA 95448",
      lat: 38.6083,
      lng: -122.8705,
      priceRange: "$$$$" as const,
      dogPolicy: "Small dogs welcome in bungalow-style suites. Beautifully landscaped grounds perfect for morning strolls with your pup.",
      maxDogWeight: 25,
      petFee: 50,
      amenities: ["Dog bed", "Ceramic bowls", "Garden access", "Quiet courtyard"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.duchamphotel.com",
      phone: "(707) 431-1300",
    },
    {
      name: "Healdsburg Inn on the Plaza",
      address: "112 Matheson St, Healdsburg, CA 95448",
      lat: 38.6101,
      lng: -122.8682,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in designated pet-friendly rooms. Steps from the central plaza with its dog-friendly shops and restaurants.",
      maxDogWeight: 40,
      petFee: 50,
      amenities: ["Plush dog bed", "Treats", "Water bowl", "Plaza walking access"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.healdsburginn.com",
      phone: "(707) 433-6991",
    },
  ],

  nationalParks: [
    {
      name: "Point Reyes National Seashore",
      state: "California",
      lat: 38.0682,
      lng: -122.8808,
      dogPolicy: "Dogs allowed on four designated beaches and a few trails on leash. Some of the most dog-friendly national seashore access in California.",
      dogTrails: ["Kehoe Beach", "Limantour Beach", "North Beach", "South Beach"],
      restrictions: [
        "Dogs must be on leash (6 ft max) at all times",
        "Not allowed on most inland trails",
        "Prohibited in elk reserve areas",
        "Seasonal restrictions during snowy plover nesting",
      ],
      description:
        "About 90 minutes south of Healdsburg, this stunning national seashore offers dramatic coastal cliffs, misty beaches, and roaming tule elk. Four beaches welcome leashed dogs, and nothing beats watching your pup sprint along the windswept sand at Kehoe Beach.",
      imageUrl: "",
      website: "https://www.nps.gov/pore",
    },
    {
      name: "Muir Woods National Monument",
      state: "California",
      lat: 37.8970,
      lng: -122.5811,
      dogPolicy: "Dogs are not allowed on any trails within Muir Woods. However, leashed dogs are welcome on many adjacent trails in the Golden Gate National Recreation Area.",
      dogTrails: ["Miwok Trail (adjacent GGNRA)", "Coastal Trail (adjacent GGNRA)"],
      restrictions: [
        "No dogs on any trails within the monument",
        "No dogs inside the visitor center",
        "Service animals only within the park boundary",
      ],
      description:
        "The towering old-growth coastal redwoods are breathtaking but off-limits to pups. Luckily, the surrounding GGNRA trails welcome leashed dogs with sweeping views of the Pacific and Marin headlands. Plan a combo trip for maximum tail wags.",
      imageUrl: "",
      website: "https://www.nps.gov/muwo",
    },
    {
      name: "Armstrong Redwoods State Natural Reserve",
      state: "California",
      lat: 38.5330,
      lng: -122.9997,
      dogPolicy: "Leashed dogs allowed on the main paved trail through the old-growth redwood grove. One of the best dog-accessible redwood experiences in Northern California.",
      dogTrails: ["Pioneer Trail (paved)", "Discovery Trail"],
      restrictions: [
        "Dogs must be on leash at all times",
        "Not allowed on unpaved backcountry trails",
        "Not allowed in Austin Creek section",
      ],
      description:
        "Just 20 minutes from Healdsburg, this ancient redwood grove lets you and your leashed pup walk among 1,400-year-old giants. The paved Pioneer Trail is an easy stroll through cathedral-like forest, and your dog will love sniffing the massive fern-covered trunks.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/?page_id=450",
    },
  ],

  restaurants: [
    {
      name: "Willi's Seafood & Raw Bar",
      address: "403 Healdsburg Ave, Healdsburg, CA 95448",
      lat: 38.6120,
      lng: -122.8693,
      cuisine: "Seafood & Small Plates",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the spacious front patio. Staff brings water bowls and your pup can lounge while you enjoy ceviche and cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.willisseafood.net",
    },
    {
      name: "Bravas Bar de Tapas",
      address: "420 Center St, Healdsburg, CA 95448",
      lat: 38.6098,
      lng: -122.8688,
      cuisine: "Spanish Tapas",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the heated back patio. A favorite spot for wine country dogs and their humans to share an evening under the stars.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.starkrestaurants.com/bravas",
    },
    {
      name: "Costeaux French Bakery & Cafe",
      address: "417 Healdsburg Ave, Healdsburg, CA 95448",
      lat: 38.6122,
      lng: -122.8694,
      cuisine: "French Bakery & Cafe",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor sidewalk tables. A perfect morning stop for pastries, coffee, and a biscuit for your best friend.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.costeaux.com",
    },
    {
      name: "KINSmoke",
      address: "304 Center St, Healdsburg, CA 95448",
      lat: 38.6094,
      lng: -122.8691,
      cuisine: "Barbecue",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio with picnic tables. Smoky aromas guaranteed to make every tail wag uncontrollably.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.kinsmoke.com",
    },
    {
      name: "Campo Fina",
      address: "330 Healdsburg Ave, Healdsburg, CA 95448",
      lat: 38.6111,
      lng: -122.8691,
      cuisine: "Italian",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the charming back garden with bocce courts. Your pup can nap under the table while you enjoy wood-fired pizza and local wine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.campofina.com",
    },
    {
      name: "Guiso Latin Fusion",
      address: "117 North St, Healdsburg, CA 95448",
      lat: 38.6130,
      lng: -122.8685,
      cuisine: "Latin Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor patio. Flavorful tacos and creative cocktails with a Sonoma County twist.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.guisolatinfusion.com",
    },
    {
      name: "The Matheson",
      address: "106 Matheson St, Healdsburg, CA 95448",
      lat: 38.6102,
      lng: -122.8683,
      cuisine: "Contemporary American",
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome on the rooftop bar terrace. Upscale dining with panoramic views of the Healdsburg hills.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.themathesonhealdsburg.com",
    },
    {
      name: "Noble Folk Ice Cream & Pie Bar",
      address: "116 Matheson St, Healdsburg, CA 95448",
      lat: 38.6103,
      lng: -122.8681,
      cuisine: "Desserts & Ice Cream",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor benches. They offer a special pup cup that dogs go absolutely bonkers for.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.8,
      imageUrl: "",
      website: "https://www.noblefolkicecream.com",
    },
  ],

  cafes: [
    {
      name: "Flying Goat Coffee",
      address: "324 Center St, Healdsburg, CA 95448",
      lat: 38.6096,
      lng: -122.8690,
      dogPolicy: "Dog-friendly patio seating right on the plaza. Locally roasted single-origin coffees with a loyal dog-owner following.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.flyinggoatcoffee.com",
    },
    {
      name: "Acre Coffee",
      address: "302 Center St, Healdsburg, CA 95448",
      lat: 38.6093,
      lng: -122.8692,
      dogPolicy: "Spacious front patio where dogs are always welcome. Sonoma County's favorite community coffee spot.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.acrecoffee.com",
    },
    {
      name: "Quail & Condor",
      address: "131 Mill St, Healdsburg, CA 95448",
      lat: 38.6088,
      lng: -122.8700,
      dogPolicy: "Cute courtyard patio where pups are welcome. Specialty drinks and pastries in a relaxed wine country setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.quailandcondor.com",
    },
    {
      name: "Moustache Baked Goods",
      address: "381 Healdsburg Ave, Healdsburg, CA 95448",
      lat: 38.6117,
      lng: -122.8693,
      dogPolicy: "Small outdoor seating area where dogs can join you for a morning pastry run. Famous for their savory twists and croissants.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.moustachebakedgoods.com",
    },
    {
      name: "Healdsburg Roastery",
      address: "400 Healdsburg Ave, Healdsburg, CA 95448",
      lat: 38.6118,
      lng: -122.8694,
      dogPolicy: "Sidewalk tables where your pup can people-watch while you enjoy a fresh pour-over. A Healdsburg morning tradition.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.healdsburgroastery.com",
    },
  ],

  dogParks: [
    {
      name: "Healdsburg Ridge Open Space Preserve",
      address: "475 Healdsburg Ave, Healdsburg, CA 95448",
      lat: 38.6155,
      lng: -122.8650,
      offLeash: false,
      fenced: false,
      acres: 155.0,
      amenities: ["Hiking trails", "Panoramic vineyard views", "Waste stations", "Parking lot"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A stunning hilltop preserve with sweeping views of Alexander Valley vineyards and the Mayacamas Mountains. Leashed dogs can explore miles of trails through oak woodlands and grasslands. The sunset views alone are worth the climb.",
    },
    {
      name: "Badger Park Dog Run",
      address: "500 Badger St, Healdsburg, CA 95448",
      lat: 38.6070,
      lng: -122.8730,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Shade trees", "Benches", "Waste stations", "Water spigot"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Healdsburg's dedicated off-leash dog park is a local favorite for after-work romps. The fenced area gives dogs plenty of room to zoom while owners chat under the shade trees. A real community gathering spot for the dog crowd.",
    },
    {
      name: "Healdsburg Veterans Memorial Beach",
      address: "13839 Old Redwood Hwy, Healdsburg, CA 95448",
      lat: 38.6040,
      lng: -122.8640,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Russian River access", "Sandy beach", "Picnic tables", "Restrooms", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A beautiful stretch of Russian River beach where leashed dogs can wade and splash in the shallows. During the off-season, this becomes a quieter paradise for dogs who love water. Nothing beats a wine country afternoon at the river with your pup.",
    },
    {
      name: "Fitch Mountain Trail",
      address: "Fitch Mountain Rd, Healdsburg, CA 95448",
      lat: 38.6180,
      lng: -122.8540,
      offLeash: false,
      fenced: false,
      acres: 40.0,
      amenities: ["Hiking trail", "Mountain views", "Shade", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A moderately challenging loop trail up Fitch Mountain with gorgeous views of the Russian River and surrounding wine country. Leashed dogs love the varied terrain and forest smells. A great morning workout for active pups.",
    },
    {
      name: "West Plaza Park",
      address: "Plaza St, Healdsburg, CA 95448",
      lat: 38.6100,
      lng: -122.8695,
      offLeash: false,
      fenced: false,
      acres: 1.0,
      amenities: ["Shaded lawn", "Benches", "Water fountain", "Central location"],
      rating: 4.2,
      imageUrl: "",
      description:
        "The iconic Healdsburg Plaza is a grassy, tree-shaded town square where dogs and their owners gather daily. While leashes are required, it is the social hub of downtown and the perfect spot for your pup to meet new friends between winery visits.",
    },
  ],
};
