export const helenData = {
  city: {
    name: "Helen",
    state: "Georgia",
    region: "Southeast",
    lat: 34.7023,
    lng: -83.7282,
    dogFriendlinessScore: 7,
    description:
      "A Bavarian alpine village tucked into the Blue Ridge Mountains of North Georgia? Believe it. Helen transformed itself in the 1960s into a charming recreation of a German mountain town, complete with cobblestone alleys, bratwurst stands, and a gentle river running right through the middle. Dogs love the cool mountain air, the Chattahoochee River tubing (yes, dogs can float too), and the surrounding national forest trails that wind through Appalachian splendor.",
    heroImage: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 574,
  },
  hotels: [
    {
      name: "Valhalla Resort Hotel",
      address: "5 Chattahoochee St, Helen, GA 30545",
      lat: 34.7028,
      lng: -83.727,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms available with a $50 per stay fee. River views and walking paths on property.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["River views", "Walking paths", "Downtown location", "Balconies", "Bavarian decor"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.valhallaresorthotel.com",
      phone: "(706) 878-2200",
    },
    {
      name: "Best Western Riverpark Inn",
      address: "250 Edelweiss Strasse, Helen, GA 30545",
      lat: 34.7015,
      lng: -83.73,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a $20 per night fee. Riverside property with direct water access for wading.",
      maxDogWeight: 80,
      petFee: 20,
      amenities: ["River access", "Outdoor pool", "Pet exercise area", "Bavarian architecture", "Continental breakfast"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(706) 878-2111",
    },
    {
      name: "Helendorf River Inn & Conference Center",
      address: "33 Munichstrasse, Helen, GA 30545",
      lat: 34.7035,
      lng: -83.7278,
      priceRange: "$$" as const,
      dogPolicy: "Select pet-friendly suites available. $40 per stay pet fee. Riverside location with balcony rooms.",
      maxDogWeight: 40,
      petFee: 40,
      amenities: ["Riverside suites", "Balconies", "Indoor pool", "Downtown walkability", "Pet waste stations"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.helendorf.com",
      phone: "(706) 878-2271",
    },
    {
      name: "Country Inn & Suites Helen",
      address: "871 Edelweiss Strasse, Helen, GA 30545",
      lat: 34.699,
      lng: -83.7351,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a non-refundable $75 fee per stay. Grassy area on property for exercise.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Pet exercise area", "Indoor pool", "Free breakfast", "Near Unicoi State Park"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.radissonhotels.com",
      phone: "(706) 878-9000",
    },
    {
      name: "Unicoi State Park Lodge",
      address: "1788 Hwy 356, Helen, GA 30545",
      lat: 34.7215,
      lng: -83.7345,
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly rooms and cabins available. $40 per night in cabins, $15 per night in lodge rooms. Trail access from property.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Lake access", "Trail system", "Restaurant", "Adventure lodge", "Nature programs"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.unicoilodge.com",
      phone: "(706) 878-2201",
    },
  ],
  nationalParks: [
    {
      name: "Chattahoochee National Forest",
      state: "Georgia",
      lat: 34.75,
      lng: -83.75,
      dogPolicy: "Dogs welcome on all national forest trails on leash or under voice control. Campgrounds require leash.",
      dogTrails: ["Raven Cliff Falls Trail", "Andrews Cove Trail", "Dukes Creek Falls Trail", "Smithgall Woods Trail"],
      restrictions: ["Leash in campgrounds and developed areas", "Pack out waste", "Respect wildlife"],
      description:
        "Nearly 750,000 acres of Blue Ridge Mountain wilderness wrap around Helen like a green blanket. Waterfalls cascade through laurel-choked gorges, trout streams gurgle through hemlock forests, and ridgeline trails offer views stretching into the Carolinas. Your dog will think they've discovered a forest without end.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/conf",
    },
    {
      name: "Unicoi State Park",
      state: "Georgia",
      lat: 34.7215,
      lng: -83.7345,
      dogPolicy: "Dogs allowed on all trails on a leash no longer than six feet. Also welcome in campgrounds and cabins.",
      dogTrails: ["Lake Loop Trail", "Unicoi to Helen Trail", "Bottoms Loop Trail", "Smith Creek Trail"],
      restrictions: ["Leash required at all times", "No dogs on the beach", "Clean up required"],
      description:
        "This gem of a state park offers a gorgeous lake, miles of wooded trails, and a paved path that connects directly to downtown Helen. The Unicoi to Helen Trail is a favorite — a 2-mile riverside walk that delivers your pup straight to bratwurst territory. The lake loop is perfect for morning jogs with your running buddy.",
      imageUrl: "",
      website: "https://gastateparks.org/Unicoi",
    },
    {
      name: "Anna Ruby Falls Recreation Area",
      state: "Georgia",
      lat: 34.7372,
      lng: -83.7234,
      dogPolicy: "Leashed dogs welcome on the paved trail to the falls observation deck.",
      dogTrails: ["Anna Ruby Falls Trail (0.4 miles paved)", "Smith Creek Trail to Unicoi (4.6 miles)"],
      restrictions: ["Leash required", "Stay on paved trail near falls", "No dogs in creek near falls"],
      description:
        "A stunning double waterfall where Curtis Creek and York Creek plunge side by side into a mossy gorge. The short, paved trail is easy for dogs of all sizes, and the cool mist from the falls is a welcome refresher on hot Georgia days. The longer Smith Creek Trail descends to Unicoi State Park for a full-day adventure.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/recarea/conf/recarea/?recid=10497",
    },
    {
      name: "Brasstown Bald",
      state: "Georgia",
      lat: 34.8743,
      lng: -83.8108,
      dogPolicy: "Dogs allowed on the paved trail to the summit on leash. Not permitted inside the visitor center.",
      dogTrails: ["Summit Trail (0.5 miles paved)", "Arkaquah Trail", "Jack's Knob Trail"],
      restrictions: ["Leash required", "No dogs inside visitor center", "Steep paved trail to summit"],
      description:
        "At 4,784 feet, this is Georgia's highest point — and your dog can summit it. The half-mile paved trail climbs steeply to an observation tower with 360-degree views across four states. On clear days you can see Atlanta's skyline. Your pup won't care about the view but will love the mountain-top wind in their fur.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/recarea/conf/recarea/?recid=10497",
    },
  ],
  restaurants: [
    {
      name: "Muller's Famous Fried Cheese",
      address: "8860 N Main St, Helen, GA 30545",
      lat: 34.7031,
      lng: -83.7279,
      cuisine: "German",
      priceRange: "$" as const,
      dogPolicy: "Walk-up window with outdoor picnic tables right on the Chattahoochee. Dogs are welcome and common.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Bodensee Restaurant",
      address: "1 Main St, Helen, GA 30545",
      lat: 34.7022,
      lng: -83.7277,
      cuisine: "German",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio overlooking the river. Traditional German fare with schnitzel, sausages, and pretzels.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bodenseerestaurant.com",
    },
    {
      name: "Troll Tavern",
      address: "7647 S Main St, Helen, GA 30545",
      lat: 34.6998,
      lng: -83.7292,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Riverside deck is dog-friendly. Burgers, wings, and cold beer with mountain views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Hofer's Bakery & Cafe",
      address: "8758 N Main St, Helen, GA 30545",
      lat: 34.7029,
      lng: -83.7281,
      cuisine: "Bakery",
      priceRange: "$" as const,
      dogPolicy: "Outdoor seating area welcomes dogs. German pastries, strudel, and strong coffee.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "Nacoochee Grill",
      address: "7277 S Main St, Helen, GA 30545",
      lat: 34.6991,
      lng: -83.7295,
      cuisine: "Southern",
      priceRange: "$$" as const,
      dogPolicy: "Large covered patio welcomes leashed dogs. Southern comfort food with a mountain twist.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Chattahoochee Brewing Company Biergarten",
      address: "1529 Chattahoochee St, Helen, GA 30545",
      lat: 34.703,
      lng: -83.7262,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Biergarten is extremely dog-friendly. Dogs get water bowls and the occasional head scratch from fellow patrons.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "Paul's Steakhouse",
      address: "8706 N Main St, Helen, GA 30545",
      lat: 34.7027,
      lng: -83.7282,
      cuisine: "Steakhouse",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. USDA prime steaks in a Bavarian-themed setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Sweetwater's Restaurant",
      address: "12 Munich Strasse, Helen, GA 30545",
      lat: 34.7033,
      lng: -83.7276,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Relaxed patio dining with dogs allowed. Located right on the Chattahoochee River.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "",
    },
  ],
  cafes: [
    {
      name: "Higher Ground Coffee Co.",
      address: "39 Yonah St, Helen, GA 30545",
      lat: 34.7019,
      lng: -83.7291,
      dogPolicy: "Mountain coffee shop with a patio. Dogs welcome outside. Freshly roasted beans and friendly baristas.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "Betty's Country Store & Cafe",
      address: "8594 N Main St, Helen, GA 30545",
      lat: 34.7024,
      lng: -83.7284,
      dogPolicy: "Country store with a covered porch. Leashed dogs welcome while you enjoy house-made biscuits and jam.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Alpine Hilltop Coffee",
      address: "30 Bruckenstrasse, Helen, GA 30545",
      lat: 34.7037,
      lng: -83.7268,
      dogPolicy: "Hilltop cafe with outdoor seating and village views. Dogs welcome. Bavarian-themed interior.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Sautee Coffee House",
      address: "2765 Hwy 17, Sautee Nacoochee, GA 30571",
      lat: 34.6833,
      lng: -83.6978,
      dogPolicy: "Worth the short drive. Garden patio with Appalachian views. Leashed dogs welcome. Local art on the walls.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "",
    },
    {
      name: "Hansel & Gretel Candy Kitchen Coffee Counter",
      address: "8660 N Main St, Helen, GA 30545",
      lat: 34.7026,
      lng: -83.7283,
      dogPolicy: "Fudge and candy shop with a small coffee counter. Outdoor benches welcome leashed pups (but no chocolate for dogs!).",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Chattahoochee Riverwalk",
      address: "Main St, Helen, GA 30545",
      lat: 34.7025,
      lng: -83.7275,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Paved riverwalk", "River access points", "Downtown shops", "Benches", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Helen's charming riverwalk follows the Chattahoochee right through the heart of the Bavarian village. Your leashed pup can wade in the gentle river at access points while you window-shop. In summer, watch tubers float by — a spectacle that keeps dogs endlessly entertained.",
    },
    {
      name: "Unicoi State Park Trails",
      address: "1788 Hwy 356, Helen, GA 30545",
      lat: 34.7215,
      lng: -83.7345,
      offLeash: false,
      fenced: false,
      acres: 50.0,
      amenities: ["Lakeside trails", "Mountain trails", "Lake access", "Campground", "Picnic areas"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Miles of wooded trails winding around a beautiful mountain lake. The Lake Loop is flat and easy, while the mountain trails offer more challenging terrain. Your leashed dog will love the forest smells, creek crossings, and the occasional squirrel chase (restrained, of course).",
    },
    {
      name: "Helen Tubing & Waterpark Dog Beach",
      address: "8990 S Main St, Helen, GA 30545",
      lat: 34.6985,
      lng: -83.73,
      offLeash: false,
      fenced: false,
      acres: 1.0,
      amenities: ["Shallow river access", "Sandy bank", "Shade trees", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A sandy bank on the Chattahoochee where locals bring their dogs for a splash. The gentle current and shallow water make it safe for dogs of all sizes. Not an official dog park, but the community has embraced it as an informal pup gathering spot.",
    },
    {
      name: "Nacoochee Valley Trail",
      address: "Hwy 75 S, Helen, GA 30545",
      lat: 34.6882,
      lng: -83.7227,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Valley trail", "Historic Indian Mound views", "Pastoral scenery", "Parking"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A gentle trail through the beautiful Nacoochee Valley with views of the famous Indian Mound and its hilltop gazebo. The pastoral farmland scenery is a peaceful change from the mountain trails, and your leashed dog will enjoy the flat, easy walking and abundant butterflies.",
    },
    {
      name: "Hardman Farm State Historic Site Grounds",
      address: "143 Hardman Farm Rd, Sautee Nacoochee, GA 30571",
      lat: 34.6871,
      lng: -83.718,
      offLeash: false,
      fenced: false,
      acres: 12.0,
      amenities: ["Historic farm", "Walking paths", "Mountain views", "Gazebo", "Picnic area"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A beautifully preserved plantation home set against the Blue Ridge Mountains. The grounds are open for leashed dog walks with rolling pastures, an iconic gazebo atop an ancient Indian Mound, and views that look like a painting. Your pup gets history and scenery in one outing.",
    },
  ],
};
