export const helenaData = {
  city: {
    name: "Helena",
    state: "Montana",
    region: "Mountain West",
    lat: 46.5884,
    lng: -112.0245,
    dogFriendlinessScore: 7,
    description:
      "Helena, Montana's capital city, sits in a valley between the Big Belt and Elkhorn Mountains with a remarkable trail system right from town. The South Hills trail network and Mount Helena provide off-leash adventures, while the historic Last Chance Gulch downtown offers dog-friendly dining and a genuine frontier-town atmosphere.",
    heroImage: "https://images.unsplash.com/photo-1508389377389-918442e3626b?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 32655,
  },

  hotels: [
    {
      name: "The Montana Club Hotel",
      address: "22 N Last Chance Gulch, Helena, MT 59601",
      lat: 46.5890,
      lng: -112.0340,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in pet-friendly rooms with a per-night fee. Historic building in the heart of downtown.",
      maxDogWeight: 50,
      petFee: 30,
      amenities: ["Dog bed", "Water bowls", "Walking map", "Near trails", "Downtown location"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.themontanaclub.com",
      phone: "(406) 442-5960",
    },
    {
      name: "DoubleTree by Hilton Helena Downtown",
      address: "22 N Last Chance Gulch, Helena, MT 59601",
      lat: 46.5888,
      lng: -112.0345,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a non-refundable fee. Full-service hotel on Last Chance Gulch.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Pet waste stations", "Grassy areas", "Near walking mall", "Water bowls"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com/doubletree",
      phone: "(406) 443-2200",
    },
    {
      name: "La Quinta Inn Helena",
      address: "750 N Fee St, Helena, MT 59601",
      lat: 46.6020,
      lng: -112.0170,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome at no extra charge. Budget-friendly with easy trail access.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Pet waste stations", "Grassy areas", "Near Centennial Park", "Water bowls"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta",
      phone: "(406) 449-4000",
    },
    {
      name: "Sanders - Helena's Bed & Breakfast",
      address: "328 N Ewing St, Helena, MT 59601",
      lat: 46.5920,
      lng: -112.0380,
      priceRange: "$$$" as const,
      dogPolicy: "Small dogs welcome in the carriage house with advance notice. Elegant 1875 Victorian mansion.",
      maxDogWeight: 30,
      petFee: 40,
      amenities: ["Garden walking area", "Dog bed", "Treats", "Historic neighborhood walks", "Water bowls"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.sandersbb.com",
      phone: "(406) 442-3309",
    },
  ],

  nationalParks: [
    {
      name: "Helena National Forest",
      state: "Montana",
      lat: 46.6000,
      lng: -111.8000,
      dogPolicy: "Dogs welcome on all trails. Leash in developed areas; voice control in backcountry.",
      dogTrails: ["Refrigerator Canyon Trail", "Mount Ascension Trail", "Grizzly Gulch Trail", "MacDonald Pass trails"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on backcountry trails",
        "Be aware of bears in all areas",
      ],
      description:
        "The national forest surrounding Helena offers mountain hiking, canyon trails, and alpine lake destinations. The proximity to town means you can be on a forest trail within minutes of leaving your hotel.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/helena",
    },
    {
      name: "Gates of the Mountains Wilderness",
      state: "Montana",
      lat: 46.8500,
      lng: -111.8700,
      dogPolicy: "Leashed dogs welcome on trails. Dogs allowed on the boat tour to the trailheads.",
      dogTrails: ["Meriwether Canyon Trail", "Refrigerator Canyon Trail"],
      restrictions: [
        "Must be on leash on trails",
        "Dogs must be well-behaved on boat",
        "Be aware of mountain goats and bears",
      ],
      description:
        "Named by Lewis and Clark, this wilderness features dramatic limestone canyon walls along the Missouri River. The boat ride through the canyon is spectacular, and leashed dogs are welcome on the trails accessed from the boat landing.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/helena",
    },
    {
      name: "Mount Helena City Park",
      state: "Montana",
      lat: 46.5810,
      lng: -112.0500,
      dogPolicy: "Dogs welcome off-leash under voice control on all trails. Helena's most popular outdoor destination.",
      dogTrails: ["1906 Trail", "Prairie Trail", "Prospect Shafts Trail", "Mount Helena Ridge Trail"],
      restrictions: [
        "Voice control required",
        "Aggressive dogs must be leashed",
        "Clean up after your pet",
      ],
      description:
        "A 620-acre city park with a trail network climbing to the summit of Mount Helena at 5,468 feet. Dogs can run off-leash on miles of trails with panoramic views of the Helena Valley, Big Belt Mountains, and the Continental Divide.",
      imageUrl: "",
      website: "https://www.helenamt.gov",
    },
  ],

  restaurants: [
    {
      name: "Blackfoot River Brewing Company",
      address: "66 S Park Ave, Helena, MT 59601",
      lat: 46.5870,
      lng: -112.0340,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Local craft brewery with Montana-inspired pub food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.blackfootriverbrewing.com",
    },
    {
      name: "Steve's Cafe",
      address: "1225 E Custer Ave, Helena, MT 59601",
      lat: 46.5870,
      lng: -112.0150,
      cuisine: "American Breakfast & Lunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Beloved Helena breakfast institution since 1941.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.stevescafehelena.com",
    },
    {
      name: "Benny's Bistro",
      address: "108 E 6th Ave, Helena, MT 59601",
      lat: 46.5892,
      lng: -112.0320,
      cuisine: "French-American Bistro",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the courtyard patio. Upscale bistro with seasonal Montana ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bennysbistro.com",
    },
    {
      name: "Brewhouse Pub & Grille",
      address: "939 Getchell St, Helena, MT 59601",
      lat: 46.5895,
      lng: -112.0280,
      cuisine: "Pub & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor deck. Spacious brewpub with a family-friendly atmosphere.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.brewhousepub.com",
    },
    {
      name: "Mediterranean Grill",
      address: "42 S Last Chance Gulch, Helena, MT 59601",
      lat: 46.5880,
      lng: -112.0345,
      cuisine: "Mediterranean",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor sidewalk tables on the walking mall. Fresh Mediterranean cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.medgrillhelena.com",
    },
  ],

  cafes: [
    {
      name: "Firetower Coffee House",
      address: "422 N Last Chance Gulch, Helena, MT 59601",
      lat: 46.5910,
      lng: -112.0340,
      dogPolicy: "Dogs welcome on the patio. Locally roasted coffee in a converted fire station.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.firetowercoffee.com",
    },
    {
      name: "General Mercantile",
      address: "413 N Last Chance Gulch, Helena, MT 59601",
      lat: 46.5908,
      lng: -112.0342,
      dogPolicy: "Outdoor seating welcomes dogs on the walking mall. Coffee, pastries, and Montana gifts.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.generalmercantile.com",
    },
    {
      name: "Morning Light Coffee Roasters",
      address: "800 Front St, Helena, MT 59601",
      lat: 46.5875,
      lng: -112.0290,
      dogPolicy: "Dog-friendly patio area. Small-batch roaster with a focus on quality and sustainability.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.morninglightcoffee.com",
    },
    {
      name: "The Parrot Confectionery",
      address: "42 N Last Chance Gulch, Helena, MT 59601",
      lat: 46.5888,
      lng: -112.0340,
      dogPolicy: "Outdoor sidewalk seating welcomes dogs. Historic candy shop and soda fountain since 1922.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.parrotconfectionery.com",
    },
  ],

  dogParks: [
    {
      name: "Centennial Park Dog Park",
      address: "N Fee St & Memorial Park Dr, Helena, MT 59601",
      lat: 46.6010,
      lng: -112.0180,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water stations", "Waste bags", "Benches", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Helena's primary fenced off-leash dog park with separate areas for large and small dogs. Well-maintained with reliable water stations and a welcoming community of dog owners.",
    },
    {
      name: "Mount Helena Trail System",
      address: "Mount Helena Trailhead, Helena, MT 59601",
      lat: 46.5810,
      lng: -112.0500,
      offLeash: true,
      fenced: false,
      acres: 620.0,
      amenities: ["Mountain trails", "Summit views", "Multiple trailheads", "Waste stations", "Parking"],
      rating: 4.8,
      imageUrl: "",
      description:
        "Helena's crown jewel for dog owners - over 600 acres of off-leash trails climbing Mount Helena with panoramic views. The trail system is extensive and connects to the South Hills, making multi-hour adventures possible right from town.",
    },
    {
      name: "South Hills Trail System",
      address: "South Hills Trailhead, Helena, MT 59601",
      lat: 46.5700,
      lng: -112.0300,
      offLeash: true,
      fenced: false,
      acres: 300.0,
      amenities: ["Singletrack trails", "Mountain views", "Wildlife viewing", "Multiple trailheads", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "An extensive network of trails on the hills south of Helena popular with hikers, runners, and mountain bikers. Dogs can run off-leash under voice control through grasslands and forests with Big Belt Mountain views.",
    },
    {
      name: "Spring Meadow Lake State Park",
      address: "2715 Country Club Ave, Helena, MT 59601",
      lat: 46.5930,
      lng: -112.0650,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Lake trail", "Swimming (seasonal)", "Picnic areas", "Wildlife viewing", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A spring-fed lake on the west side of Helena with a loop trail and swimming access. Leashed dogs enjoy the gentle lakeside walk and can wade in designated areas during warmer months.",
    },
  ],
};
