export const hiltonHeadData = {
  city: {
    name: "Hilton Head",
    state: "South Carolina",
    region: "Southeast",
    lat: 32.2163,
    lng: -80.7526,
    dogFriendlinessScore: 8,
    description:
      "This pristine barrier island off the South Carolina coast is a dog lover's dream, with miles of wide, hard-packed beaches where pups can run free during designated hours, lush nature preserves threaded with trails, and a relaxed Lowcountry vibe that makes every restaurant patio feel like home. Hilton Head's commitment to keeping the island natural means your dog will experience pristine maritime forests, tidal marshes, and ocean breezes that bring pure tail-wagging joy.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 40000,
  },

  hotels: [
    {
      name: "The Westin Hilton Head Island Resort & Spa",
      address: "2 Grasslawn Ave, Hilton Head Island, SC 29928",
      lat: 32.1980,
      lng: -80.7370,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 40 lbs welcome with Westin's Heavenly Dog Bed program. Oceanfront resort with direct beach access.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Heavenly Dog Bed", "Food and water bowls", "Beach access", "Dog walking service", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(843) 681-4000",
    },
    {
      name: "Omni Hilton Head Oceanfront Resort",
      address: "23 Ocean Ln, Hilton Head Island, SC 29928",
      lat: 32.1910,
      lng: -80.7290,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 25 lbs welcome with a one-time pet fee. Full oceanfront resort in Palmetto Dunes.",
      maxDogWeight: 25,
      petFee: 100,
      amenities: ["Dog bed", "Treats", "Beach access", "Pet relief area", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.omnihotels.com",
      phone: "(843) 842-8000",
    },
    {
      name: "Holiday Inn Express Hilton Head Island",
      address: "2 Tanglewood Dr, Hilton Head Island, SC 29928",
      lat: 32.2220,
      lng: -80.7470,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a nightly pet fee. Convenient mid-island location near shops and dining.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Pet relief area", "Waste bags", "Free breakfast", "Pool", "Near bike trails"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(843) 842-8888",
    },
    {
      name: "Sonesta Resort Hilton Head Island",
      address: "130 Shipyard Dr, Hilton Head Island, SC 29928",
      lat: 32.1870,
      lng: -80.7590,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a pet fee. Resort in Shipyard Plantation with beach, golf, and tennis.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Beach access", "Walking trails", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.sonesta.com",
      phone: "(843) 842-2400",
    },
    {
      name: "Red Roof Inn Hilton Head",
      address: "5 Regency Pkwy, Hilton Head Island, SC 29928",
      lat: 32.2180,
      lng: -80.7448,
      priceRange: "$" as const,
      dogPolicy: "One well-behaved pet welcome per room with no pet fee. Budget-friendly option for traveling with your pup.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pet relief area", "Waste bags", "Near restaurants", "Free parking"],
      rating: 3.8,
      imageUrl: "",
      website: "https://www.redroof.com",
      phone: "(843) 686-6808",
    },
  ],

  nationalParks: [
    {
      name: "Fort Pulaski National Monument",
      state: "Georgia",
      lat: 32.0295,
      lng: -80.8900,
      dogPolicy: "Leashed dogs welcome on the grounds, trails, and along the scenic dike system. Not permitted inside the fort.",
      dogTrails: ["North Pier dike trail", "Lighthouse overlook walk", "Fort grounds perimeter"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed inside the fort",
        "Not allowed in visitor center",
        "Not allowed at ranger programs",
      ],
      description:
        "About 45 minutes south near Savannah, this Civil War-era fort sits on Cockspur Island surrounded by salt marshes and tidal creeks. Leashed dogs can explore the scenic dike trails with panoramic marsh views and coastal breezes.",
      imageUrl: "",
      website: "https://www.nps.gov/fopu",
    },
    {
      name: "Reconstruction Era National Historical Park",
      state: "South Carolina",
      lat: 32.4320,
      lng: -80.6690,
      dogPolicy: "Leashed dogs welcome on the grounds and outdoor areas. A nationally significant site telling the story of Reconstruction.",
      dogTrails: ["Darrah Hall grounds", "Penn Center Historic District walking tour"],
      restrictions: [
        "Must be on leash",
        "Not allowed inside buildings",
        "Must stay on designated paths",
      ],
      description:
        "Located on nearby St. Helena Island in Beaufort, this park preserves the story of the Reconstruction era. Leashed dogs can explore the historic Penn Center grounds, where formerly enslaved people built a community and forged a path to freedom.",
      imageUrl: "",
      website: "https://www.nps.gov/reer",
    },
    {
      name: "Pinckney Island National Wildlife Refuge",
      state: "South Carolina",
      lat: 32.2340,
      lng: -80.7680,
      dogPolicy: "Leashed dogs welcome on the 14 miles of trails and roads. A hidden gem just before the bridge to Hilton Head.",
      dogTrails: ["Ibis Pond Trail", "White Point Trail", "Clubhouse Road", "Salt Marsh Trail"],
      restrictions: [
        "Must be on leash",
        "Not allowed in restricted wildlife areas",
        "Must stay on designated trails",
        "No dogs in water features",
      ],
      description:
        "Just before you cross the bridge to Hilton Head, this 4,053-acre refuge offers 14 miles of trails through maritime forest, salt marsh, and freshwater ponds teeming with alligators, herons, and eagles. Leashed dogs adore the flat, shaded trails.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/pinckney-island",
    },
  ],

  restaurants: [
    {
      name: "The Salty Dog Cafe",
      address: "232 S Sea Pines Dr, Hilton Head Island, SC 29928",
      lat: 32.1420,
      lng: -80.7975,
      cuisine: "Seafood & American",
      priceRange: "$$" as const,
      dogPolicy: "Iconic dog-friendly restaurant with a name that says it all. Dogs welcome on the waterfront deck overlooking Braddock Cove.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.saltydog.com",
    },
    {
      name: "Skull Creek Boathouse",
      address: "397 Squire Pope Rd, Hilton Head Island, SC 29926",
      lat: 32.2490,
      lng: -80.7620,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the expansive waterfront deck with stunning sunset views over Skull Creek.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.skullcreekboathouse.com",
    },
    {
      name: "Lucky Rooster Kitchen + Bar",
      address: "841 William Hilton Pkwy, Hilton Head Island, SC 29928",
      lat: 32.2115,
      lng: -80.7350,
      cuisine: "Southern Comfort",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Elevated Southern comfort food with Lowcountry flair.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.luckyroosterhhi.com",
    },
    {
      name: "One Hot Mama's",
      address: "74 Arrow Rd, Hilton Head Island, SC 29928",
      lat: 32.2070,
      lng: -80.7260,
      cuisine: "Barbecue & American",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly outdoor seating. Award-winning ribs and wings in a fun, laid-back atmosphere.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.onehotmamas.com",
    },
    {
      name: "Michael Anthony's Cucina Italiana",
      address: "37 New Orleans Rd, Hilton Head Island, SC 29928",
      lat: 32.2085,
      lng: -80.7310,
      cuisine: "Italian",
      priceRange: "$$$$" as const,
      dogPolicy: "Well-behaved dogs welcome at limited outdoor seating. Upscale Italian dining with house-made pasta.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.michaelanthonyscucina.com",
    },
    {
      name: "The Jazz Corner",
      address: "1000 William Hilton Pkwy, Hilton Head Island, SC 29928",
      lat: 32.2130,
      lng: -80.7310,
      cuisine: "Southern Fine Dining",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Live jazz nightly paired with refined Southern cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thejazzcorner.com",
    },
    {
      name: "Tiki Hut",
      address: "1 S Forest Beach Dr, Hilton Head Island, SC 29928",
      lat: 32.1540,
      lng: -80.7530,
      cuisine: "Beach Bar & Grill",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at this casual beachfront spot. Cold drinks, quick bites, and sandy paws welcome.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.tikihuthhi.com",
    },
    {
      name: "Nectar Farm Kitchen",
      address: "73 Arrow Rd, Hilton Head Island, SC 29928",
      lat: 32.2068,
      lng: -80.7258,
      cuisine: "Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the garden patio. Farm-fresh seasonal menu with ingredients from local growers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.nectarhhi.com",
    },
  ],

  cafes: [
    {
      name: "Corner Perk Downtown",
      address: "48 Calhoun St, Bluffton, SC 29910",
      lat: 32.2370,
      lng: -80.8610,
      dogPolicy: "Leashed dogs welcome on the patio in charming Old Town Bluffton. Fresh-roasted coffee and house-baked pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thecornerperk.com",
    },
    {
      name: "Watusi Coffee",
      address: "69 Lighthouse Rd, Hilton Head Island, SC 29928",
      lat: 32.1640,
      lng: -80.7665,
      dogPolicy: "Dog-friendly outdoor seating near Harbour Town. Specialty espresso and smoothies to fuel beach walks.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.watusicoffee.com",
    },
    {
      name: "Java Burrito Company",
      address: "810 William Hilton Pkwy, Hilton Head Island, SC 29928",
      lat: 32.2110,
      lng: -80.7360,
      dogPolicy: "Dogs welcome at outdoor tables. Coffee and burritos: the perfect combo for an early morning beach run with your pup.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.javaburritocompany.com",
    },
    {
      name: "Coligny Coffee",
      address: "1 N Forest Beach Dr, Hilton Head Island, SC 29928",
      lat: 32.1550,
      lng: -80.7520,
      dogPolicy: "Leashed dogs welcome on the patio near Coligny Beach Park. Grab a latte before hitting the sand.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.colignycoffee.com",
    },
    {
      name: "Hargray Coffee House",
      address: "430 William Hilton Pkwy, Hilton Head Island, SC 29926",
      lat: 32.2195,
      lng: -80.7455,
      dogPolicy: "Dog-friendly patio with shade and water bowls. A relaxed island coffee shop with local art on the walls.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.hargraycoffeehouse.com",
    },
  ],

  dogParks: [
    {
      name: "Hilton Head Island Dog Park",
      address: "Cordillo Pkwy, Hilton Head Island, SC 29928",
      lat: 32.2025,
      lng: -80.7405,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Separate small and large dog areas", "Water stations", "Shade structures", "Agility equipment", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "The island's dedicated fenced dog park with separate areas for big and small pups. Shaded by live oaks draped in Spanish moss, this park captures the Lowcountry charm while your dog makes new island friends.",
    },
    {
      name: "Coligny Beach Off-Leash Hours",
      address: "1 Coligny Circle, Hilton Head Island, SC 29928",
      lat: 32.1520,
      lng: -80.7510,
      offLeash: true,
      fenced: false,
      acres: 10.0,
      amenities: ["Beach access", "Ocean swimming", "Outdoor showers", "Restrooms", "Waste stations", "Free parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "During designated off-leash hours (typically before 10am and after 5pm April-September, all day October-March), dogs can run free on this beautiful wide beach. Watching your pup sprint across the hard-packed sand with the Atlantic Ocean as a backdrop is pure Hilton Head magic.",
    },
    {
      name: "Sea Pines Forest Preserve",
      address: "175 Greenwood Dr, Hilton Head Island, SC 29928",
      lat: 32.1490,
      lng: -80.7820,
      offLeash: false,
      fenced: false,
      acres: 605.0,
      amenities: ["Nature trails", "Boardwalks", "Ancient Indian Shell Ring", "Wildlife viewing", "Fishing dock", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A stunning 605-acre nature preserve within Sea Pines with trails through maritime forest, past a 4,000-year-old Indian Shell Ring, and along wetland boardwalks. Leashed dogs can explore this pristine landscape teeming with birds, deer, and alligators.",
    },
    {
      name: "Shelter Cove Community Park",
      address: "39 Shelter Cove Ln, Hilton Head Island, SC 29928",
      lat: 32.2060,
      lng: -80.7220,
      offLeash: false,
      fenced: false,
      acres: 12.0,
      amenities: ["Walking paths", "Waterfront boardwalk", "Playground", "Picnic areas", "Restrooms", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A beautifully landscaped community park on Broad Creek with a waterfront boardwalk, walking paths, and open green spaces. Leashed dogs love the creek-side strolls and the breeze off the water. Tuesday night concerts in summer are a bonus.",
    },
    {
      name: "Mitchelville Freedom Park",
      address: "438 Beach City Rd, Hilton Head Island, SC 29926",
      lat: 32.2505,
      lng: -80.7120,
      offLeash: false,
      fenced: false,
      acres: 25.0,
      amenities: ["Nature trails", "Beach access", "Historic markers", "Boardwalks", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A historically significant park marking the site of one of the first self-governed towns of formerly enslaved people in the US. Leashed dogs can walk the trails through maritime forest to the beach, combining history, nature, and coastal beauty in one meaningful visit.",
    },
  ],
};
