export const hollandMiData = {
  city: {
    name: "Holland",
    state: "Michigan",
    region: "Midwest",
    lat: 42.7876,
    lng: -86.1089,
    dogFriendlinessScore: 7,
    description:
      "Holland, Michigan is a charming Lake Michigan town with Dutch heritage, beautiful beaches, and a welcoming attitude toward dogs. From the iconic Big Red Lighthouse to the tulip-lined streets and dog-friendly brewery scene, Holland offers a delightful getaway for pup parents.",
    heroImage: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1200&fit=crop",
    climate: "Humid continental with lake effect",
    population: 33574,
  },

  hotels: [
    {
      name: "CityFlats Hotel Holland",
      address: "61 E 7th St, Holland, MI 49423",
      lat: 42.7877,
      lng: -86.1080,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a pet fee. LEED-certified boutique hotel in downtown.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Eco-friendly amenities", "Downtown location", "Walking maps"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cityflatshotel.com",
      phone: "(616) 796-2100",
    },
    {
      name: "Haworth Hotel",
      address: "225 College Ave, Holland, MI 49423",
      lat: 42.7885,
      lng: -86.1010,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a non-refundable fee. Comfortable hotel on the Hope College campus.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Grassy campus grounds", "Walking paths", "Near downtown", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.haworthhotel.com",
      phone: "(616) 395-7200",
    },
    {
      name: "Hampton Inn Holland",
      address: "12427 Felch St, Holland, MI 49424",
      lat: 42.8020,
      lng: -86.0710,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a nightly pet fee. Clean, reliable accommodations.",
      maxDogWeight: 75,
      petFee: 30,
      amenities: ["Grassy area", "Near bike paths", "Waste stations", "Complimentary breakfast"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(616) 399-8500",
    },
    {
      name: "Teusink's Pony Farm Cottages",
      address: "561 Howard Ave, Holland, MI 49424",
      lat: 42.7740,
      lng: -86.1950,
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly cottages near Lake Michigan. Spacious grounds with room to roam.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Private cottage", "Large yard", "Near beach", "BBQ grill", "Outdoor space"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.teusinkscottages.com",
      phone: "(616) 335-8935",
    },
  ],

  nationalParks: [
    {
      name: "Holland State Park",
      state: "Michigan",
      lat: 42.7730,
      lng: -86.2100,
      dogPolicy: "Leashed dogs allowed on the channel beach and in campgrounds. Views of Big Red Lighthouse.",
      dogTrails: ["Channel Walk", "Campground Loop", "Beach Walk (north side)"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on the main swimming beach",
        "Stay off the pier when crowded",
      ],
      description:
        "Home to the iconic Big Red Lighthouse, Holland State Park sits where Lake Macatawa meets Lake Michigan. Dogs enjoy the channel-side beach and watching the boats pass while taking in stunning sunsets.",
      imageUrl: "",
      website: "https://www.michigan.gov/hollandsp",
    },
    {
      name: "Saugatuck Dunes State Park",
      state: "Michigan",
      lat: 42.7100,
      lng: -86.2200,
      dogPolicy: "Leashed dogs welcome on the 2.5-mile trail through forests and coastal dunes.",
      dogTrails: ["Beach Trail", "North Trail Loop", "South Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Stay on marked trails through dune areas",
        "Not allowed on fragile dune vegetation",
      ],
      description:
        "Just south of Holland, this undeveloped state park features a beautiful hike through old-growth forest to a pristine Lake Michigan beach. The 2.5-mile trail to the beach is a favorite for dogs and their owners.",
      imageUrl: "",
      website: "https://www.michigan.gov/saugatuckdunes",
    },
    {
      name: "Pigeon Creek Park",
      state: "Michigan",
      lat: 42.8570,
      lng: -86.0860,
      dogPolicy: "Leashed dogs welcome on all trails year-round. Popular for hiking and cross-country skiing.",
      dogTrails: ["Meadow Loop", "Forest Trail", "Creek Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Yield to cross-country skiers in winter",
        "Stay on designated trails",
      ],
      description:
        "This Ottawa County park north of Holland offers rolling wooded trails perfect for a morning hike with your dog. The varied terrain of meadows, forests, and creek crossings keeps dogs engaged and happy.",
      imageUrl: "",
      website: "https://www.miottawa.org/parks",
    },
  ],

  restaurants: [
    {
      name: "New Holland Brewing",
      address: "66 E 8th St, Holland, MI 49423",
      lat: 42.7880,
      lng: -86.1078,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Award-winning craft beer and elevated pub food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.newhollandbrew.com",
    },
    {
      name: "Butch's Dry Dock",
      address: "44 E 8th St, Holland, MI 49423",
      lat: 42.7879,
      lng: -86.1082,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor seating area along 8th Street.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.butchsdrydock.com",
    },
    {
      name: "Hops at 84 East",
      address: "84 E 8th St, Holland, MI 49423",
      lat: 42.7881,
      lng: -86.1075,
      cuisine: "Gastropub",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the patio. Upscale comfort food and craft cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hopsat84east.com",
    },
    {
      name: "The Curragh Irish Pub",
      address: "73 E 8th St, Holland, MI 49423",
      lat: 42.7880,
      lng: -86.1076,
      cuisine: "Irish Pub",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Traditional Irish fare and a great beer selection.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.curraghirishpub.com",
    },
    {
      name: "Alpenrose Restaurant",
      address: "4 E 8th St, Holland, MI 49423",
      lat: 42.7878,
      lng: -86.1090,
      cuisine: "European",
      priceRange: "$$$$" as const,
      dogPolicy: "Leashed dogs welcome on the seasonal garden patio. Fine European dining in a historic setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.alpenroserestaurant.com",
    },
  ],

  cafes: [
    {
      name: "Lemonjello's Coffee",
      address: "106 E 8th St, Holland, MI 49423",
      lat: 42.7882,
      lng: -86.1072,
      dogPolicy: "Dogs welcome at outdoor tables. A beloved Holland coffee institution.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.lemonjellos.com",
    },
    {
      name: "JP's Coffee & Espresso Bar",
      address: "57 E 8th St, Holland, MI 49423",
      lat: 42.7880,
      lng: -86.1078,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Cozy downtown coffee shop.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.jpscoffee.com",
    },
    {
      name: "Windmill Island Coffee",
      address: "1 Lincoln Ave, Holland, MI 49423",
      lat: 42.7910,
      lng: -86.1120,
      dogPolicy: "Dogs welcome on the patio near the iconic Dutch windmill. Coffee with a view.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.windmillisland.org",
    },
    {
      name: "Collective Coffee",
      address: "141 E 8th St, Holland, MI 49423",
      lat: 42.7883,
      lng: -86.1068,
      dogPolicy: "Outdoor patio welcomes dogs. Specialty coffee and community vibes.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.collectivecoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Kollen Park",
      address: "150 Kollen Park Dr, Holland, MI 49423",
      lat: 42.7840,
      lng: -86.1230,
      offLeash: false,
      fenced: false,
      acres: 12.0,
      amenities: ["Lake Macatawa waterfront", "Walking paths", "Playground", "Picnic areas", "Restrooms"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Holland's premier waterfront park on Lake Macatawa offers scenic on-leash walks with views of the water and passing boats. The paved paths and grassy areas are perfect for a lakeside stroll.",
    },
    {
      name: "Dunton Park Dog Run",
      address: "50 Dunton Ave, Holland, MI 49423",
      lat: 42.7870,
      lng: -86.1200,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Water fountain", "Waste stations", "Benches", "Near downtown"],
      rating: 4.2,
      imageUrl: "",
      description:
        "Holland's off-leash dog area in Dunton Park provides a convenient fenced space close to downtown. Dogs enjoy the open area while owners appreciate the walkable location.",
    },
    {
      name: "Tunnel Park",
      address: "66 Lakeshore Ave, Holland, MI 49424",
      lat: 42.7870,
      lng: -86.2150,
      offLeash: false,
      fenced: false,
      acres: 22.0,
      amenities: ["Beach access through tunnel", "Dune trails", "Picnic areas", "Restrooms", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Named for its tunnel carved through the dune to Lake Michigan, this park offers a dramatic beach entrance. Leashed dogs love the sandy trails and beach walks, especially during the quieter off-season.",
    },
    {
      name: "Van Raalte Farm Park",
      address: "1190 Fairbanks Ave, Holland, MI 49423",
      lat: 42.7650,
      lng: -86.0810,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Nature trails", "Restored prairie", "Historic farm buildings", "Benches", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A historic farm turned nature preserve with walking trails through restored prairies and woodlands. The gentle terrain and quiet setting make it an ideal on-leash outing for dogs of all ages.",
    },
  ],
};
