export const hoodRiverData = {
  city: {
    name: "Hood River",
    state: "Oregon",
    region: "Pacific Northwest",
    lat: 45.7054,
    lng: -121.5215,
    dogFriendlinessScore: 8,
    description:
      "Wedged between Mount Hood and the Columbia River Gorge, Hood River is a wind-and-water playground where dogs are as common as kayaks and kiteboards. This small-town gem boasts world-class trails, orchards dripping with pears and apples, and a brewery scene that practically requires a furry designated driver. If your dog loves waterfalls, forests, and the smell of fresh hops, this is their happy place.",
    heroImage: "https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=1200&fit=crop",
    climate: "Oceanic",
    population: 8313,
  },

  hotels: [
    {
      name: "Best Western Plus Hood River Inn",
      address: "1108 E Marina Way, Hood River, OR 97031",
      lat: 45.7120,
      lng: -121.5045,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a nightly fee. Riverfront rooms with views of the Columbia River Gorge.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Riverfront access", "Dog bowls", "Walking paths", "Pool area", "Restaurant on-site"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hoodriverinn.com",
      phone: "(541) 386-2200",
    },
    {
      name: "Columbia Gorge Hotel & Spa",
      address: "4000 Westcliff Dr, Hood River, OR 97031",
      lat: 45.7105,
      lng: -121.5425,
      priceRange: "$$$" as const,
      dogPolicy: "Small dogs welcome in select rooms with advance notice. A historic cliffside hotel above a 208-foot waterfall.",
      maxDogWeight: 25,
      petFee: 50,
      amenities: ["Waterfall views", "Gardens", "Dog bed", "Walking paths", "Historic charm"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.columbiagorgehotel.com",
      phone: "(541) 386-5566",
    },
    {
      name: "Hampton Inn & Suites Hood River",
      address: "3101 Cascade Ave, Hood River, OR 97031",
      lat: 45.7030,
      lng: -121.5355,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms with a one-time fee. Modern amenities and easy access to Gorge trails.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Pool", "Breakfast included", "Walking area", "Close to trails", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com/hampton",
      phone: "(541) 386-1515",
    },
    {
      name: "Vagabond Lodge",
      address: "4070 Westcliff Dr, Hood River, OR 97031",
      lat: 45.7108,
      lng: -121.5440,
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly retro lodge with no size restrictions. Vintage Pacific Northwest vibes and Gorge views.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Kitchenettes", "Gorge views", "Garden area", "BBQ grills", "Dog bowls on request"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.vagabondlodge.com",
      phone: "(541) 386-2992",
    },
    {
      name: "Society Hotel Bingen",
      address: "287 Cedar St, Bingen, WA 98605",
      lat: 45.7175,
      lng: -121.4715,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in cabin rooms. A beautifully restored schoolhouse hotel just across the river from Hood River.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Restored schoolhouse", "Soaking pool", "Garden", "Gorge views", "Community kitchen"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thesocietyhotel.com",
      phone: "(541) 399-8897",
    },
  ],

  nationalParks: [
    {
      name: "Columbia River Gorge National Scenic Area",
      state: "Oregon",
      lat: 45.7115,
      lng: -121.5195,
      dogPolicy: "Dogs allowed on most trails on leash. One of the most spectacular and dog-accessible scenic areas in the Pacific Northwest.",
      dogTrails: [
        "Historic Columbia River Highway State Trail",
        "Catherine Creek Trail",
        "Coyote Wall Trail",
        "Tom McCall Point Trail",
        "Lyle Cherry Orchard Trail",
      ],
      restrictions: [
        "Must be on leash (6 ft max) on all trails",
        "Some trails closed seasonally for nesting birds",
        "Not allowed in Eagle Creek Trail burn zone",
        "Clean up after pets on all trails",
      ],
      description:
        "This 80-mile-long canyon carved by the Columbia River features over 90 waterfalls, dramatic basalt cliffs, and wildflower meadows. Many trails welcome leashed dogs, offering some of the most breathtaking hiking in the Pacific Northwest with your best trail companion.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/crgnsa",
    },
    {
      name: "Mount Rainier National Park",
      state: "Washington",
      lat: 46.8523,
      lng: -121.7603,
      dogPolicy: "Dogs allowed in campgrounds, parking areas, and on roads only. Not permitted on any trails or in the backcountry.",
      dogTrails: [
        "Campground loops at Cougar Rock",
        "Ohanapecosh Campground roads",
        "White River Campground area",
      ],
      restrictions: [
        "No dogs on any trails",
        "Must be on leash (6 ft max) at all times",
        "Not allowed in buildings or on shuttle buses",
      ],
      description:
        "The iconic volcanic peak dominates the skyline from Hood River on clear days. While trail access for dogs is restricted, the scenic drives and campgrounds offer views of glaciers, wildflower meadows, and old-growth forest.",
      imageUrl: "",
      website: "https://www.nps.gov/mora",
    },
    {
      name: "Lewis and Clark National Historical Park",
      state: "Oregon",
      lat: 46.1340,
      lng: -123.8816,
      dogPolicy: "Leashed dogs welcome on the Fort-to-Sea Trail and most park trails. A historic and scenic coastal experience for dog owners.",
      dogTrails: [
        "Fort-to-Sea Trail (6.5 miles)",
        "Netul River Trail",
        "Coastal Forest Loop",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Not allowed inside Fort Clatsop replica",
        "Not allowed in visitor center",
      ],
      description:
        "Follow in the pawprints of Seaman, the Newfoundland who traveled with Lewis and Clark, on trails through coastal forest to the Pacific Ocean. The Fort-to-Sea Trail is a dog-friendly masterpiece ending at the beach.",
      imageUrl: "",
      website: "https://www.nps.gov/lewi",
    },
  ],

  restaurants: [
    {
      name: "pFriem Family Brewers",
      address: "707 Portway Ave #101, Hood River, OR 97031",
      lat: 45.7118,
      lng: -121.5085,
      cuisine: "Belgian-Inspired Brewpub",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the spacious waterfront patio with Columbia River views. World-class Belgian-inspired ales.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.pfriembeer.com",
    },
    {
      name: "Double Mountain Brewery",
      address: "8 4th St, Hood River, OR 97031",
      lat: 45.7088,
      lng: -121.5120,
      cuisine: "Brewpub & Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly outdoor seating area. Wood-fired pizza and hop-forward ales in a lively downtown setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.doublemountainbrewery.com",
    },
    {
      name: "Celilo Restaurant & Bar",
      address: "16 Oak St, Hood River, OR 97031",
      lat: 45.7085,
      lng: -121.5115,
      cuisine: "Pacific Northwest",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Farm-to-table cuisine showcasing the best of the Gorge.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.celilorestaurant.com",
    },
    {
      name: "Kickstand Coffee & Kitchen",
      address: "1235 State St, Hood River, OR 97031",
      lat: 45.7068,
      lng: -121.5165,
      cuisine: "Breakfast & Lunch",
      priceRange: "$" as const,
      dogPolicy: "Patio seating for guests with dogs. Creative breakfast burritos and strong coffee to fuel Gorge adventures.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.kickstandhoodriver.com",
    },
    {
      name: "Solstice Wood Fire Cafe",
      address: "501 Portway Ave, Hood River, OR 97031",
      lat: 45.7112,
      lng: -121.5095,
      cuisine: "Wood-Fired Pizza & Italian",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Wood-fired dishes with Gorge-sourced ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.solsticewoodfirecafe.com",
    },
    {
      name: "Ferment Brewing Co.",
      address: "403 Portway Ave, Hood River, OR 97031",
      lat: 45.7110,
      lng: -121.5100,
      cuisine: "Brewery & Kitchen",
      priceRange: "$$" as const,
      dogPolicy: "Large dog-friendly patio with river views. Barrel-aged ales and creative pub fare.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.fermentbrewing.com",
    },
    {
      name: "River Daze Cafe",
      address: "202 Cascade Ave, Hood River, OR 97031",
      lat: 45.7075,
      lng: -121.5130,
      cuisine: "American Comfort",
      priceRange: "$" as const,
      dogPolicy: "Outdoor seating area welcomes leashed dogs. Hearty sandwiches and smoothies for post-adventure refueling.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.1,
      imageUrl: "",
      website: "",
    },
    {
      name: "Taqueria El Cuate",
      address: "1001 12th St, Hood River, OR 97031",
      lat: 45.7055,
      lng: -121.5180,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Authentic tacos and burritos from the Gorge's favorite taqueria.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
  ],

  cafes: [
    {
      name: "Doppio Coffee",
      address: "310 Oak St, Hood River, OR 97031",
      lat: 45.7090,
      lng: -121.5110,
      dogPolicy: "Leashed dogs welcome on the covered patio. Artisan roasts and a cozy downtown vibe.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.doppiocoffee.com",
    },
    {
      name: "Ground Espresso Bar",
      address: "12 Oak St, Hood River, OR 97031",
      lat: 45.7086,
      lng: -121.5118,
      dogPolicy: "Sidewalk seating where dogs are part of the family. Espresso and homemade chai.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.groundhoodriver.com",
    },
    {
      name: "Dog River Coffee",
      address: "411 Oak St, Hood River, OR 97031",
      lat: 45.7092,
      lng: -121.5105,
      dogPolicy: "A coffee shop named for a river — and they love actual dogs too. Patio seating with treats behind the counter.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.dogrivercoffee.com",
    },
    {
      name: "Broder Ost",
      address: "100 E Marina Way, Hood River, OR 97031",
      lat: 45.7115,
      lng: -121.5055,
      dogPolicy: "Waterfront patio where dogs can enjoy the river breeze while you enjoy Scandinavian pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.broderpdx.com",
    },
    {
      name: "Pine Street Bakery",
      address: "102 5th St, Hood River, OR 97031",
      lat: 45.7088,
      lng: -121.5125,
      dogPolicy: "Outdoor seating area welcomes leashed pups. Freshly baked bread, croissants, and seasonal treats.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.pinestreetbakery.com",
    },
  ],

  dogParks: [
    {
      name: "Hood River Waterfront Park Dog Area",
      address: "Portway Ave, Hood River, OR 97031",
      lat: 45.7122,
      lng: -121.5075,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "River views", "Water station", "Waste stations", "Benches"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A fenced off-leash area right on the Hood River waterfront with views of the Columbia River and windsurfers. Your pup can play while you watch kiteboarders catch air — peak Pacific Northwest living.",
    },
    {
      name: "Post Canyon Trail System",
      address: "Post Canyon Dr, Hood River, OR 97031",
      lat: 45.6890,
      lng: -121.5450,
      offLeash: true,
      fenced: false,
      acres: 300.0,
      amenities: ["Mountain biking trails", "Hiking trails", "Forest canopy", "Creek crossings", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "An extensive trail network through Douglas fir forest where dogs can run off-leash under voice control. Creek crossings, fern-lined paths, and forest canopy make this a dog's paradise in the Gorge.",
    },
    {
      name: "Tollbridge Park",
      address: "Toll Bridge Rd, Hood River, OR 97031",
      lat: 45.6720,
      lng: -121.5580,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["River access", "Picnic areas", "Shade trees", "Parking", "Restrooms"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A county park along the Hood River where leashed dogs can wade in the cool mountain water. Shaded picnic areas make it perfect for a lazy summer afternoon with your pup.",
    },
    {
      name: "Ruthton Park Trail",
      address: "Wasco St, Hood River, OR 97031",
      lat: 45.7100,
      lng: -121.5015,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Paved trail", "Columbia River views", "Wildflowers", "Benches", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A scenic trail along the Columbia River east of downtown with sweeping Gorge views, wildflower meadows in spring, and excellent birdwatching. Leashed dogs love the river breezes and endless sniffing opportunities.",
    },
    {
      name: "Tamanawas Falls Trail",
      address: "Hwy 35, Mount Hood, OR 97041",
      lat: 45.3920,
      lng: -121.5750,
      offLeash: false,
      fenced: false,
      acres: 25.0,
      amenities: ["Waterfall destination", "Creek crossings", "Forest trail", "Parking", "Moderate difficulty"],
      rating: 4.8,
      imageUrl: "",
      description:
        "A spectacular 3.4-mile roundtrip hike through old-growth forest to a 100-foot waterfall on Mount Hood. Leashed dogs adore the creek crossings and the misty grotto behind the falls. A must-do Gorge trail.",
    },
  ],
};
