export const hotSpringsData = {
  city: {
    name: "Hot Springs",
    state: "Arkansas",
    region: "Southeast",
    lat: 34.5037,
    lng: -93.0552,
    dogFriendlinessScore: 7,
    description:
      "This historic spa town nestled in the Ouachita Mountains offers dogs an unexpected paradise with miles of forested trails, a national park, and a charming downtown Bathhouse Row. While dogs cannot enter the hot springs, they can enjoy the surrounding mountains and pet-friendly shops along Central Avenue.",
    heroImage: "https://images.unsplash.com/photo-1504567961542-e24d9439a724?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 38797,
  },
  hotels: [
    {
      name: "Hotel Hale",
      address: "540 Central Ave, Hot Springs, AR 71901",
      lat: 34.5130,
      lng: -93.0540,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a pet fee. A beautifully restored boutique hotel on Bathhouse Row.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking map", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelhale.com",
      phone: "(501) 520-4253",
    },
    {
      name: "The Waters Hot Springs",
      address: "340 Central Ave, Hot Springs, AR 71901",
      lat: 34.5110,
      lng: -93.0530,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome with a per-night pet fee. A modern hotel on Central Avenue with spa services.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Pet-friendly rooms", "Water bowls", "Waste bags", "Central Avenue walking access"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.thewatershs.com",
      phone: "(501) 321-0001",
    },
    {
      name: "Lookout Point Lakeside Inn",
      address: "104 Lookout Circle, Hot Springs, AR 71913",
      lat: 34.4700,
      lng: -93.0650,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select suites with a non-refundable fee. A lakeside bed & breakfast with stunning views.",
      maxDogWeight: 60,
      petFee: 100,
      amenities: ["Dog bed", "Lake access", "Grounds for walking", "Water bowls", "Waste bags"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.lookoutpointinn.com",
      phone: "(501) 525-6155",
    },
    {
      name: "Best Western Winners Circle Inn",
      address: "2520 Central Ave, Hot Springs, AR 71901",
      lat: 34.4930,
      lng: -93.0520,
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome with a per-night pet fee. Convenient location near Oaklawn Racing Casino Resort.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Pet-friendly rooms", "Waste bags", "Parking", "Walking areas"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.bestwestern.com/en_US/book/hotels-in-hot-springs-arkansas",
      phone: "(501) 624-2531",
    },
  ],
  nationalParks: [
    {
      name: "Hot Springs National Park",
      state: "Arkansas",
      lat: 34.5216,
      lng: -93.0424,
      dogPolicy: "Dogs welcome on all trails in the national park on a 6-foot leash. Not permitted in bathhouse buildings. One of the most dog-friendly national parks.",
      dogTrails: ["Sunset Trail", "West Mountain Trail", "Hot Springs Mountain Trail", "Gulpha Gorge Trail", "Goat Rock Trail"],
      restrictions: ["6-foot leash required", "Not allowed in bathhouse buildings", "Not in visitor center", "Must clean up after pet"],
      description: "America's smallest national park packs a punch with mountain trails, thermal springs, and historic bathhouses. Dogs can hike all 26 miles of trails through the Ouachita Mountains, making this one of the most dog-friendly national parks in the system.",
      imageUrl: "",
      website: "https://www.nps.gov/hosp",
    },
    {
      name: "Lake Ouachita State Park",
      state: "Arkansas",
      lat: 34.5710,
      lng: -93.1780,
      dogPolicy: "Dogs welcome on all trails and in campgrounds on a leash. Arkansas's largest lake with forested shores.",
      dogTrails: ["Caddo Bend Trail", "Tompkins Bend Trail", "Dogwood Trail"],
      restrictions: ["Leash required", "Not allowed on swimming beaches", "Must clean up after pet"],
      description: "About 20 minutes from Hot Springs, Lake Ouachita offers over 40,000 acres of crystal-clear water surrounded by national forest. Dogs can hike the forested trails and enjoy the lakeside campgrounds.",
      imageUrl: "",
      website: "https://www.arkansasstateparks.com/parks/lake-ouachita-state-park",
    },
    {
      name: "Ouachita National Forest",
      state: "Arkansas",
      lat: 34.6200,
      lng: -93.2500,
      dogPolicy: "Dogs welcome on all trails. Nearly 1.8 million acres of mountain forest stretching across Arkansas and Oklahoma.",
      dogTrails: ["Ouachita National Recreation Trail", "Charlton Trail", "Lake Winona Loop", "Crystal Prong Trail"],
      restrictions: ["Leash recommended", "Check seasonal hunting dates", "Must clean up after pet"],
      description: "The oldest national forest in the South surrounds Hot Springs with nearly 1.8 million acres of mountains, streams, and lakes. Dogs have virtually unlimited trail access through this vast wilderness.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/ouachita",
    },
  ],
  restaurants: [
    {
      name: "Superior Bathhouse Brewery",
      address: "329 Central Ave, Hot Springs, AR 71901",
      lat: 34.5108,
      lng: -93.0528,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. The only brewery in a national park, using thermal spring water to brew beer.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.superiorbathhouse.com",
    },
    {
      name: "Rolando's Restaurante",
      address: "210 Central Ave, Hot Springs, AR 71901",
      lat: 34.5090,
      lng: -93.0520,
      cuisine: "Latin American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the covered patio. Authentic Latin cuisine from a James Beard-nominated chef.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.rolandosrestaurante.com",
    },
    {
      name: "The Pancake Shop",
      address: "216 Central Ave, Hot Springs, AR 71901",
      lat: 34.5095,
      lng: -93.0520,
      cuisine: "Breakfast & Brunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the sidewalk patio. A Hot Springs institution since 1940 serving fluffy pancakes and hearty breakfasts.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.thepancakeshop.com",
    },
    {
      name: "Bone-In BBQ",
      address: "3924 Central Ave, Hot Springs, AR 71913",
      lat: 34.4850,
      lng: -93.0510,
      cuisine: "Barbecue",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor picnic tables. Smoked meats and classic sides in a casual setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.boneinbbqar.com",
    },
    {
      name: "The Ohio Club",
      address: "336 Central Ave, Hot Springs, AR 71901",
      lat: 34.5110,
      lng: -93.0528,
      cuisine: "American Bar & Grill",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the front patio along Central Avenue. The oldest bar in Arkansas with live blues music.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.theohioclub.com",
    },
  ],
  cafes: [
    {
      name: "Kollective Coffee+Tea",
      address: "110 Central Ave, Hot Springs, AR 71901",
      lat: 34.5075,
      lng: -93.0515,
      dogPolicy: "Dogs welcome on the Central Avenue patio. A hip coffee shop with specialty drinks and a creative atmosphere.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.kollectivecoffee.com",
    },
    {
      name: "Fat Bottom Girl's Cupcakes",
      address: "510 Central Ave, Hot Springs, AR 71901",
      lat: 34.5125,
      lng: -93.0535,
      dogPolicy: "Dogs welcome at outdoor tables. Gourmet cupcakes, coffee, and treats on Bathhouse Row.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.fatbottomcupcakes.com",
    },
    {
      name: "Mountain Valley Coffee",
      address: "350 Central Ave, Hot Springs, AR 71901",
      lat: 34.5112,
      lng: -93.0530,
      dogPolicy: "Dog-friendly outdoor seating on the avenue. Fresh roasted coffee and light breakfast items.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.mountainvalleycoffee.com",
    },
    {
      name: "The Perk",
      address: "4610 Central Ave, Hot Springs, AR 71913",
      lat: 34.4800,
      lng: -93.0500,
      dogPolicy: "Dogs welcome on the patio. A neighborhood coffee spot with espresso drinks and baked goods.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.theperkhs.com",
    },
  ],
  dogParks: [
    {
      name: "K-9 Corral Dog Park",
      address: "Whittington Park, Hot Springs, AR 71901",
      lat: 34.5180,
      lng: -93.0620,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade trees", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "Hot Springs' dedicated off-leash dog park within Whittington Park offers separate areas for large and small dogs. Shaded by mature trees with water stations to keep pups cool.",
    },
    {
      name: "Hot Springs Mountain Trail",
      address: "Hot Springs National Park, Hot Springs, AR 71901",
      lat: 34.5200,
      lng: -93.0430,
      offLeash: false,
      fenced: false,
      acres: 50,
      amenities: ["Mountain views", "Observation tower", "Historic springs", "Benches", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "The signature trail in Hot Springs National Park climbs to the top of Hot Springs Mountain with panoramic city views. Dogs on leash can enjoy the forested path and visit the observation tower area.",
    },
    {
      name: "Gulpha Gorge Trail",
      address: "305 Gorge Rd, Hot Springs, AR 71901",
      lat: 34.5240,
      lng: -93.0310,
      offLeash: false,
      fenced: false,
      acres: 20,
      amenities: ["Creek access", "Campground", "Forested trail", "Picnic areas", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "A scenic gorge trail in Hot Springs National Park following Gulpha Creek through a forested valley. Dogs enjoy the creek crossings and shaded paths, with a campground nearby for overnight stays.",
    },
    {
      name: "Entergy Park",
      address: "161 Hobson Ave, Hot Springs, AR 71901",
      lat: 34.5050,
      lng: -93.0460,
      offLeash: false,
      fenced: false,
      acres: 6,
      amenities: ["Walking paths", "Green space", "Benches", "Shade structures", "Waste bag stations"],
      rating: 4.1,
      imageUrl: "",
      description: "A pleasant city park near downtown with paved walking paths and open green space. Dogs enjoy the shaded walks and the proximity to Central Avenue shops and restaurants.",
    },
  ],
};
