export const houstonData = {
  city: {
    name: "Houston",
    state: "Texas",
    region: "Southwest",
    lat: 29.7604,
    lng: -95.3698,
    dogFriendlinessScore: 7,
    description:
      "Houston is a sprawling, diverse metropolis that loves its dogs. With an impressive network of bayou trails, world-class dog parks, and a massive food scene that increasingly welcomes pups on patios, Space City offers more for dogs than many visitors expect.",
    heroImage: "https://images.unsplash.com/photo-1530089711124-9ca31fb9e863?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 2304580,
  },

  hotels: [
    {
      name: "Hotel Granduca Houston",
      address: "1080 Uptown Park Blvd, Houston, TX 77056",
      lat: 29.7540,
      lng: -95.4610,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 25 lbs welcome with a pet fee. Italian luxury in the Galleria area.",
      maxDogWeight: 25,
      petFee: 100,
      amenities: ["Dog bed", "Treats", "Water bowls", "Garden walks", "Pet-sitting referral"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.granducahouston.com",
      phone: "(713) 418-1000",
    },
    {
      name: "La Colombe d'Or Hotel",
      address: "3410 Montrose Blvd, Houston, TX 77006",
      lat: 29.7390,
      lng: -95.3870,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select suites with advance notice. Boutique mansion hotel in Montrose.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Garden grounds", "Art collection", "Montrose neighborhood", "Walking paths"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.lacolombedorhotel.com",
      phone: "(713) 524-7999",
    },
    {
      name: "Hotel ZaZa Houston",
      address: "5701 Main St, Houston, TX 77005",
      lat: 29.7260,
      lng: -95.3890,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 30 lbs welcome with a pet fee. Glamorous hotel in the Museum District.",
      maxDogWeight: 30,
      petFee: 50,
      amenities: ["Dog bed", "Treats", "Near Hermann Park", "Walking distance to trails"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelzaza.com",
      phone: "(713) 526-1991",
    },
    {
      name: "La Quinta Inn Houston Galleria",
      address: "1625 W Loop S, Houston, TX 77027",
      lat: 29.7430,
      lng: -95.4580,
      priceRange: "$" as const,
      dogPolicy: "All dogs welcome at no extra charge. Near Memorial Park and the Galleria.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Near Memorial Park", "Grassy area", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(713) 355-3440",
    },
  ],

  nationalParks: [
    {
      name: "Sam Houston National Forest",
      state: "Texas",
      lat: 30.5580,
      lng: -95.3970,
      dogPolicy: "Dogs welcome on all trails including the Lone Star Hiking Trail. Leash recommended.",
      dogTrails: ["Lone Star Hiking Trail", "Winters Bayou Trail", "Stubblefield Lake Trail"],
      restrictions: [
        "Leash required in developed areas",
        "Carry extra water in summer",
        "Watch for wild boar on trails",
      ],
      description:
        "About an hour north of Houston, this national forest offers the 128-mile Lone Star Hiking Trail through piney woods and bayou crossings. Dogs love the forest terrain and creek wading opportunities.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/detail/texas/about-forest/districts/?cid=fswdev3_008440",
    },
    {
      name: "Brazos Bend State Park",
      state: "Texas",
      lat: 29.3730,
      lng: -95.6190,
      dogPolicy: "Leashed dogs welcome on trails and in campgrounds. Watch for alligators along the trails.",
      dogTrails: ["40-Acre Lake Trail", "Elm Lake Trail", "Hale Lake Loop"],
      restrictions: [
        "Must be on a 6-foot leash at all times",
        "Keep distance from alligators",
        "Not allowed near the nature center",
        "Stay on designated trails",
      ],
      description:
        "This wetland state park southwest of Houston is famous for its alligator population. Leashed dogs are welcome but must stay alert on trails where alligators sun themselves by the path.",
      imageUrl: "",
      website: "https://www.tpwd.texas.gov/state-parks/brazos-bend",
    },
    {
      name: "Buffalo Bayou Park",
      state: "Texas",
      lat: 29.7620,
      lng: -95.3900,
      dogPolicy: "Leashed dogs welcome on all trails. A 160-acre urban park along the bayou in central Houston.",
      dogTrails: ["Bayou Trail", "Sandy Reed Trail", "Johnny Steele Dog Park Loop"],
      restrictions: [
        "Must be on leash except in designated dog park",
        "Stay on paved trails near bayou edge",
        "Avoid bayou water after rain",
      ],
      description:
        "Houston's premier urban park stretches along Buffalo Bayou with trails, gardens, and public art. The park includes the renowned Johnny Steele Dog Park, making it a complete dog-friendly destination.",
      imageUrl: "",
      website: "https://www.buffalobayou.org",
    },
  ],

  restaurants: [
    {
      name: "The Pit Room",
      address: "1201 Richmond Ave, Houston, TX 77006",
      lat: 29.7340,
      lng: -95.3870,
      cuisine: "Texas Barbecue",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the large outdoor patio. Central Texas-style barbecue in Montrose.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thepitroombbq.com",
    },
    {
      name: "Karbach Brewing Co.",
      address: "2032 Karbach St, Houston, TX 77092",
      lat: 29.8070,
      lng: -95.4660,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly beer garden with water bowls and a welcoming atmosphere.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.karbachbrewing.com",
    },
    {
      name: "Underbelly Hospitality",
      address: "1100 Westheimer Rd, Houston, TX 77006",
      lat: 29.7390,
      lng: -95.3850,
      cuisine: "Modern American",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the patio. Chef-driven cuisine celebrating Houston's diversity.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.underbellyhospitality.com",
    },
    {
      name: "Tacos Tierra Caliente",
      address: "1903 N Durham Dr, Houston, TX 77008",
      lat: 29.7900,
      lng: -95.4150,
      cuisine: "Mexican Street Tacos",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor picnic tables. Late-night taco truck turned brick-and-mortar.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.tacostierracaliente.com",
    },
    {
      name: "Eight Row Flint",
      address: "1039 Yale St, Houston, TX 77008",
      lat: 29.7870,
      lng: -95.4100,
      cuisine: "Tex-Mex & Whiskey",
      priceRange: "$$" as const,
      dogPolicy: "Extremely dog-friendly Heights icehouse with a large outdoor area. Dogs are the stars.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.eightrowflint.com",
    },
  ],

  cafes: [
    {
      name: "Boomtown Coffee",
      address: "242 W 19th St, Houston, TX 77008",
      lat: 29.7900,
      lng: -95.3980,
      dogPolicy: "Dogs welcome on the outdoor patio. Locally roasted specialty coffee in the Heights.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.boomtowncoffee.com",
    },
    {
      name: "Blacksmith",
      address: "1018 Westheimer Rd, Houston, TX 77006",
      lat: 29.7390,
      lng: -95.3840,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Montrose coffee shop and bar.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.blacksmithhouston.com",
    },
    {
      name: "Catalina Coffee",
      address: "2828 Washington Ave, Houston, TX 77007",
      lat: 29.7700,
      lng: -95.4010,
      dogPolicy: "Dog-friendly outdoor area. Quality coffee and pastries in a casual setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.catalinacoffeeshop.com",
    },
    {
      name: "Campesino Coffee House",
      address: "2602 Waugh Dr, Houston, TX 77006",
      lat: 29.7520,
      lng: -95.3920,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Fair-trade coffee in Montrose.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.campesinocoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Johnny Steele Dog Park",
      address: "100 Allen Pkwy, Houston, TX 77019",
      lat: 29.7600,
      lng: -95.3820,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Separate small dog area", "Water features", "Shade structures", "Waste stations", "Bayou views"],
      rating: 4.7,
      imageUrl: "",
      description:
        "Houston's premier dog park in Buffalo Bayou Park features a splash pad, great shade, and stunning skyline views. The well-designed space is a destination park that attracts dogs from across the city.",
    },
    {
      name: "Danny Jackson Dog Park",
      address: "4700 Dunlavy St, Houston, TX 77006",
      lat: 29.7320,
      lng: -95.3940,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate areas", "Water fountains", "Shade trees", "Benches", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A popular Montrose dog park with separate areas and good shade from mature trees. The neighborhood vibe and friendly regulars make it one of Houston's most social dog parks.",
    },
    {
      name: "Memorial Park Trails",
      address: "6501 Memorial Dr, Houston, TX 77007",
      lat: 29.7640,
      lng: -95.4320,
      offLeash: false,
      fenced: false,
      acres: 1500.0,
      amenities: ["Miles of trails", "Forest paths", "Bayou access", "Fitness equipment", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Houston's beloved 1,500-acre urban forest offers miles of on-leash trails through pine and hardwood forests. The extensive trail system provides a true nature escape in the heart of the city.",
    },
    {
      name: "Millie Bush Bark Park",
      address: "16756 Westheimer Pkwy, Houston, TX 77082",
      lat: 29.7320,
      lng: -95.6830,
      offLeash: true,
      fenced: true,
      acres: 15.0,
      amenities: ["Swimming pond", "Agility equipment", "Separate small dog area", "Shade", "Wash station"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Named after President George H.W. Bush's dog, this massive dog park in George Bush Park features a swimming pond and agility equipment. At 15 acres, it is one of the largest off-leash parks in Texas.",
    },
  ],
};
