export const hudsonNyData = {
  city: {
    name: "Hudson",
    state: "New York",
    region: "Northeast",
    lat: 42.2529,
    lng: -73.7910,
    dogFriendlinessScore: 7,
    description:
      "This revitalized Hudson Valley town blends antique charm with Brooklyn-transplant cool, creating a walkable destination where dogs are part of the culture. Warren Street's galleries and shops welcome pups, and the surrounding Catskill and Taconic landscapes offer gorgeous hiking.",
    heroImage: "https://images.unsplash.com/photo-1520962880247-cfaf541c8724?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 6042,
  },
  hotels: [
    {
      name: "The Wick Hotel",
      address: "41 Cross St, Hudson, NY 12534",
      lat: 42.2525,
      lng: -73.7876,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique hotel welcoming dogs with a $75 per stay fee. Industrial-chic design with garden courtyard.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Garden courtyard", "Restaurant", "Near Warren Street", "Bike rentals"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thewickhotel.com",
      phone: "(518) 751-7024",
    },
    {
      name: "The Rivertown Lodge",
      address: "731 Warren St, Hudson, NY 12534",
      lat: 42.2533,
      lng: -73.7856,
      priceRange: "$$$" as const,
      dogPolicy: "Dog-friendly rooms in a converted movie theater with a $50 per stay fee. Warren Street location.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Warren Street location", "Restaurant", "Bar", "Garden", "Pet bed"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.rivertownlodge.com",
      phone: "(518) 512-0954",
    },
    {
      name: "Hotel & Spa & Dog Friendly Inn",
      address: "348 Warren St, Hudson, NY 12534",
      lat: 42.2524,
      lng: -73.7918,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms with a $35 per night fee. Central Warren Street location near antique shops.",
      maxDogWeight: 60,
      petFee: 35,
      amenities: ["Central location", "Antique district", "Walking distance to everything", "Parking"],
      rating: 4.1,
      imageUrl: "",
      website: "",
      phone: "(518) 828-1011",
    },
    {
      name: "Kindred Spirits Farmhouse B&B",
      address: "5660 Rt 9H, Hudson, NY 12534",
      lat: 42.2784,
      lng: -73.7454,
      priceRange: "$$" as const,
      dogPolicy: "Farm B&B welcoming dogs with a $25 per night fee. 10 acres of farmland for dog walks with Catskill Mountain views.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["10 acres", "Farm setting", "Mountain views", "Full breakfast", "Peaceful retreat"],
      rating: 4.3,
      imageUrl: "",
      website: "",
      phone: "(518) 828-5652",
    },
  ],
  nationalParks: [
    {
      name: "Olana State Historic Site",
      state: "New York",
      lat: 42.2192,
      lng: -73.8297,
      dogPolicy: "Leashed dogs welcome on all grounds and carriage roads. One of the most beautiful designed landscapes in America.",
      dogTrails: ["Carriage Road Loop", "South Road Trail", "Lake Trail", "Ridge Road Trail"],
      restrictions: ["Leash required", "No dogs inside mansion", "Stay on carriage roads"],
      description:
        "The Persian-style home of Hudson River School painter Frederic Church sits atop a hill with jaw-dropping views of the Catskill Mountains and Hudson River. The 250-acre grounds feature designed landscapes and carriage roads perfect for leashed dog walks. Every turn reveals a view that Church himself would have painted.",
      imageUrl: "",
      website: "https://www.olana.org",
    },
    {
      name: "Greenport Conservation Area",
      state: "New York",
      lat: 42.2365,
      lng: -73.8123,
      dogPolicy: "Dogs welcome on all trails. A local favorite with river access and diverse habitats.",
      dogTrails: ["River Trail", "Upland Trail", "Creek Trail", "Connector Loop"],
      restrictions: ["Leash recommended", "Seasonal hunting", "Clean up required"],
      description:
        "Over 600 acres of Hudson River shoreline, forest, and wetland with a trail network that provides both easy waterfront walks and more challenging upland hikes. Your dog can wade in the creek and explore diverse habitats. The river views are especially beautiful at sunset.",
      imageUrl: "",
      website: "https://www.scenichudson.org",
    },
    {
      name: "Taconic State Park - Copake Falls Area",
      state: "New York",
      lat: 42.1148,
      lng: -73.5092,
      dogPolicy: "Leashed dogs welcome on all trails. Bash Bish Falls is a spectacular day trip from Hudson.",
      dogTrails: ["Bash Bish Falls Trail", "South Taconic Trail", "Harlem Valley Rail Trail"],
      restrictions: ["Leash required", "Rocky terrain near falls", "No dogs in swim areas"],
      description:
        "About 30 minutes from Hudson, this park offers dramatic scenery including Bash Bish Falls — Massachusetts' tallest single-drop waterfall accessible from the New York side. The South Taconic Trail runs along the ridge with spectacular views. Your adventurous dog will love the rocky, forested terrain.",
      imageUrl: "",
      website: "https://parks.ny.gov/parks/taconiccopakefalls",
    },
  ],
  restaurants: [
    {
      name: "Fish & Game",
      address: "13 S 3rd St, Hudson, NY 12534",
      lat: 42.2516,
      lng: -73.7907,
      cuisine: "New American",
      priceRange: "$$$$" as const,
      dogPolicy: "James Beard-winning restaurant with a garden patio. Leashed dogs welcome outside for Hudson Valley farm-to-table cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.fishandgamehudson.com",
    },
    {
      name: "Lil' Deb's Oasis",
      address: "747 Columbia St, Hudson, NY 12534",
      lat: 42.2546,
      lng: -73.7915,
      cuisine: "Latin American",
      priceRange: "$$" as const,
      dogPolicy: "Colorful tropical-themed restaurant with outdoor seating. Dogs welcome on the patio. Creative Latin-inspired dishes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.lildebs.com",
    },
    {
      name: "Cafe Mutton",
      address: "573 Warren St, Hudson, NY 12534",
      lat: 42.253,
      lng: -73.7879,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Neighborhood bistro with a garden patio. Leashed dogs welcome outside. Seasonal menu with local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.cafemutton.com",
    },
    {
      name: "BackBar",
      address: "347 Warren St, Hudson, NY 12534",
      lat: 42.2524,
      lng: -73.7919,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Cocktail bar with a large backyard patio. Dogs welcome in the outdoor space. Creative drinks and bar snacks.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "The Tavern at Hudson",
      address: "538 Warren St, Hudson, NY 12534",
      lat: 42.2528,
      lng: -73.7885,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Casual tavern with sidewalk seating on Warren Street. Dogs welcome outside. Burgers, brunch, and craft beers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
  ],
  cafes: [
    {
      name: "Flowercup Wine",
      address: "526 Warren St, Hudson, NY 12534",
      lat: 42.2527,
      lng: -73.7887,
      dogPolicy: "Natural wine bar doubling as a coffee shop by day. Dogs welcome at the outdoor tables on Warren Street.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "Verdigris Tea & Chocolate Bar",
      address: "135 Warren St, Hudson, NY 12534",
      lat: 42.2519,
      lng: -73.795,
      dogPolicy: "Artisan tea and chocolate shop with a small outdoor seating area. Dogs welcome outside this charming Warren Street gem.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.verdigristea.com",
    },
    {
      name: "Moto Coffee Machine",
      address: "357 Warren St, Hudson, NY 12534",
      lat: 42.2525,
      lng: -73.7917,
      dogPolicy: "Motorcycle-themed coffee shop with outdoor benches. Dogs welcome while you enjoy espresso and vintage moto culture.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Nolita Cafe",
      address: "426 Warren St, Hudson, NY 12534",
      lat: 42.2526,
      lng: -73.7903,
      dogPolicy: "Italian-inspired cafe with a sunny outdoor patio. Dogs welcome outside. Excellent espresso and light bites.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Promenade Hill Park",
      address: "Warren St & N Front St, Hudson, NY 12534",
      lat: 42.2538,
      lng: -73.7839,
      offLeash: false,
      fenced: false,
      acres: 2.0,
      amenities: ["Hudson River views", "Catskill Mountain views", "Walking paths", "Historic cannons", "Benches"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A hilltop park at the eastern end of Warren Street with breathtaking views of the Hudson River and Catskill Mountains. Your leashed dog can enjoy the elevated promenade while you take in one of the best river views in the Hudson Valley. Historic cannons and shade trees complete the scene.",
    },
    {
      name: "Oakdale Lake Park",
      address: "Oakdale Rd, Hudson, NY 12534",
      lat: 42.2468,
      lng: -73.7958,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Lake views", "Walking paths", "Picnic areas", "Playground", "Swimming beach"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A community park centered around a small lake with walking paths and picnic areas. Leashed dogs can walk the perimeter path and enjoy the lakeside scenery. A pleasant local park for a relaxed dog walk away from the Warren Street crowds.",
    },
    {
      name: "Olana Carriage Roads",
      address: "5720 State Rt 9G, Hudson, NY 12534",
      lat: 42.2192,
      lng: -73.8297,
      offLeash: false,
      fenced: false,
      acres: 250.0,
      amenities: ["Carriage roads", "Catskill views", "Hudson River views", "Designed landscape", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "The grounds of Frederic Church's Olana offer miles of carriage roads winding through a masterfully designed landscape with Hudson River and Catskill Mountain views at every turn. Your leashed dog gets a workout on the hilly terrain while you experience one of America's greatest artistic landscapes.",
    },
    {
      name: "Henry Hudson Riverfront Park",
      address: "S Front St, Hudson, NY 12534",
      lat: 42.2505,
      lng: -73.7832,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["River access", "Walking path", "Amtrak station nearby", "Benches", "Fishing pier"],
      rating: 4.1,
      imageUrl: "",
      description:
        "A waterfront park along the Hudson River with a walking path, fishing pier, and views of passing trains and river traffic. Your leashed dog can enjoy the river breezes and watch tugboats push barges upstream. The park connects to the Amtrak station, making it the first or last stop for train travelers.",
    },
  ],
};
