export const iowaCityData = {
  city: {
    name: "Iowa City",
    state: "Iowa",
    region: "Midwest",
    lat: 41.6611,
    lng: -91.5302,
    dogFriendlinessScore: 7,
    description:
      "Iowa City is a UNESCO City of Literature with a creative, progressive spirit that extends to its love of dogs. The University of Iowa campus, vibrant Pedestrian Mall, and extensive trail system along the Iowa River make this college town a surprisingly wonderful destination for dog owners.",
    heroImage: "https://images.unsplash.com/photo-1542621334-a254cf47733d?w=1200&fit=crop",
    climate: "Humid continental",
    population: 74828,
  },

  hotels: [
    {
      name: "Graduate Iowa City",
      address: "210 S Dubuque St, Iowa City, IA 52240",
      lat: 41.6600,
      lng: -91.5310,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a one-time pet fee. University-themed boutique hotel downtown.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Treats", "Ped Mall location", "Walking maps"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.graduatehotels.com",
      phone: "(319) 337-4058",
    },
    {
      name: "Hotel Vetro",
      address: "201 S Linn St, Iowa City, IA 52240",
      lat: 41.6595,
      lng: -91.5295,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in suites with advance notice and pet fee. Modern luxury near the Ped Mall.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Suite living", "Kitchen", "Near Iowa River", "Walking paths", "Concierge"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hotelvetro.com",
      phone: "(319) 337-9000",
    },
    {
      name: "Hyatt Place Iowa City Downtown",
      address: "114 E Washington St, Iowa City, IA 52240",
      lat: 41.6610,
      lng: -91.5295,
      priceRange: "$$" as const,
      dogPolicy: "Pets up to 50 lbs welcome with a non-refundable fee. Central downtown location.",
      maxDogWeight: 50,
      petFee: 40,
      amenities: ["Dog bed", "Near Ped Mall", "Grassy areas nearby", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hyatt.com",
      phone: "(319) 337-4200",
    },
    {
      name: "Coralville Marriott Hotel & Conference Center",
      address: "300 E 9th St, Coralville, IA 52241",
      lat: 41.6770,
      lng: -91.5620,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a nightly fee. Spacious rooms near Iowa River trails.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Near bike trail", "Grassy grounds", "Indoor pool", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(319) 688-4000",
    },
  ],

  nationalParks: [
    {
      name: "Herbert Hoover National Historic Site",
      state: "Iowa",
      lat: 41.6680,
      lng: -91.3480,
      dogPolicy: "Leashed dogs welcome on the grounds and prairie trails. Not permitted inside buildings.",
      dogTrails: ["Prairie Trail", "Hoover Creek Trail", "Grounds Loop"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed inside the Presidential Library or historic buildings",
        "Stay on designated paths",
      ],
      description:
        "The birthplace and burial site of President Herbert Hoover, set amid 187 acres of restored tallgrass prairie. Dogs enjoy the gentle walking paths through prairie grasses about 10 miles east of Iowa City.",
      imageUrl: "",
      website: "https://www.nps.gov/heho",
    },
    {
      name: "Coralville Lake Recreation Area",
      state: "Iowa",
      lat: 41.7250,
      lng: -91.5450,
      dogPolicy: "Leashed dogs welcome on trails and in campgrounds. Scenic reservoir north of Iowa City.",
      dogTrails: ["Woodpecker Trail", "Turkey Creek Trail", "Dam Overlook Trail"],
      restrictions: [
        "Must be on leash in developed areas",
        "Not allowed on designated swim beaches",
        "Off-leash in hunting areas during season only",
      ],
      description:
        "Coralville Lake offers forested trails, limestone bluffs, and a 5,430-acre reservoir. The Devonian Fossil Gorge, exposed by flooding, reveals 375-million-year-old fossils that make walks here uniquely educational.",
      imageUrl: "",
      website: "https://www.recreation.gov/coralville",
    },
    {
      name: "Lake Macbride State Park",
      state: "Iowa",
      lat: 41.7760,
      lng: -91.5620,
      dogPolicy: "Leashed dogs welcome on all trails and in campgrounds. Rolling terrain north of Iowa City.",
      dogTrails: ["Lakeview Trail", "Prairie Overlook Trail", "Woodland Loop"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on the swim beach",
        "Must stay on marked trails",
      ],
      description:
        "A beautiful state park with a lake surrounded by wooded hills about 20 minutes from Iowa City. The varied terrain of forests, prairies, and lakefront makes for engaging hikes with your dog.",
      imageUrl: "",
      website: "https://www.iowadnr.gov/lakemacbride",
    },
  ],

  restaurants: [
    {
      name: "Big Grove Brewery",
      address: "1225 S Gilbert St, Iowa City, IA 52240",
      lat: 41.6530,
      lng: -91.5270,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly with a large outdoor patio and garden. Craft beer and wood-fired food.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.biggrovebrewery.com",
    },
    {
      name: "Pullman Bar & Diner",
      address: "17 S Dubuque St, Iowa City, IA 52240",
      lat: 41.6610,
      lng: -91.5315,
      cuisine: "American Diner",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor sidewalk tables on the Ped Mall. Classic diner fare elevated.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.pullmandiner.com",
    },
    {
      name: "Bluebird Diner",
      address: "330 E Market St, Iowa City, IA 52245",
      lat: 41.6620,
      lng: -91.5250,
      cuisine: "Breakfast & American",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor patio tables. Beloved Iowa City breakfast institution.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bluebirddiner.com",
    },
    {
      name: "Basta",
      address: "121 Iowa Ave, Iowa City, IA 52240",
      lat: 41.6612,
      lng: -91.5305,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the patio. Handmade pasta and wood-fired dishes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bastaiowacity.com",
    },
    {
      name: "Clinton Street Social Club",
      address: "18 S Clinton St, Iowa City, IA 52240",
      lat: 41.6608,
      lng: -91.5300,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor seating area. Burgers, cocktails, and live music.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.clintonstreetsocialclub.com",
    },
  ],

  cafes: [
    {
      name: "Prairie Lights Books & Cafe",
      address: "15 S Dubuque St, Iowa City, IA 52240",
      lat: 41.6610,
      lng: -91.5316,
      dogPolicy: "Dogs welcome at outdoor Ped Mall tables. Iconic independent bookstore with a cafe.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.prairielights.com",
    },
    {
      name: "Dash Coffee Roasters",
      address: "287 N Linn St, Iowa City, IA 52245",
      lat: 41.6640,
      lng: -91.5290,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Locally roasted specialty coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.dashcoffeeroasters.com",
    },
    {
      name: "Cortado Coffee & Cafe",
      address: "26 S Clinton St, Iowa City, IA 52240",
      lat: 41.6607,
      lng: -91.5300,
      dogPolicy: "Dogs welcome at the outdoor sidewalk seating. Espresso and light bites downtown.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cortadoiowa.com",
    },
    {
      name: "Hatchet Coffee",
      address: "125 S Dubuque St, Iowa City, IA 52240",
      lat: 41.6598,
      lng: -91.5312,
      dogPolicy: "Leashed dogs welcome on the patio. Third-wave coffee in a minimalist space.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hatchetcoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Thornberry Off-Leash Dog Park",
      address: "2502 Miami Dr, Iowa City, IA 52240",
      lat: 41.6480,
      lng: -91.5440,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: ["Separate small dog area", "Water fountains", "Shade shelters", "Waste stations", "Benches"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Iowa City's premier off-leash dog park features separate areas for large and small dogs. The spacious, well-maintained grounds attract a friendly community of dog lovers.",
    },
    {
      name: "Iowa River Trail",
      address: "River St, Iowa City, IA 52240",
      lat: 41.6590,
      lng: -91.5340,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Paved trail", "River views", "Benches", "Public art", "Connects to campus"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A scenic paved trail along the Iowa River through the heart of the city and university campus. Dogs love the river views and the activity of this popular walking corridor.",
    },
    {
      name: "Hickory Hill Park",
      address: "1439 E Bloomington St, Iowa City, IA 52245",
      lat: 41.6690,
      lng: -91.5110,
      offLeash: false,
      fenced: false,
      acres: 185.0,
      amenities: ["Wooded trails", "Creek crossings", "Wildlife viewing", "Nature center", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A 185-acre urban wilderness with miles of forested trails through ravines and along creeks. Dogs enjoy the diverse terrain and the feeling of being deep in nature while still within city limits.",
    },
    {
      name: "Terry Trueblood Recreation Area",
      address: "579 McCollister Blvd, Iowa City, IA 52240",
      lat: 41.6410,
      lng: -91.5350,
      offLeash: false,
      fenced: false,
      acres: 85.0,
      amenities: ["Lake loop trail", "Prairie areas", "Picnic shelters", "Kayak launch", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A newer recreation area with a sand-bottom lake and prairie walking trails on the south side of town. The lake loop trail offers a pleasant on-leash walk with water views.",
    },
  ],
};
