export const jeromeData = {
  city: {
    name: "Jerome",
    state: "Arizona",
    region: "Southwest",
    lat: 34.7489,
    lng: -112.1138,
    dogFriendlinessScore: 6,
    description:
      "Perched on the side of Mingus Mountain, this former copper mining town turned artist colony welcomes dogs along its steep, winding streets and eclectic galleries. With panoramic Verde Valley views and a quirky small-town charm, Jerome offers a unique dog-friendly day trip or weekend getaway.",
    heroImage: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&fit=crop",
    climate: "Semi-arid",
    population: 455,
  },
  hotels: [
    {
      name: "Jerome Grand Hotel",
      address: "200 Hill St, Jerome, AZ 86331",
      lat: 34.7510,
      lng: -112.1140,
      priceRange: "$$$" as const,
      dogPolicy: "Historic hotel in the former United Verde Hospital welcomes dogs in select rooms. Stunning valley views from the veranda.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Valley view rooms", "Pet relief area", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.jeromegrandhotel.net",
      phone: "(928) 634-8200",
    },
    {
      name: "Connor Hotel of Jerome",
      address: "164 Main St, Jerome, AZ 86331",
      lat: 34.7492,
      lng: -112.1135,
      priceRange: "$$" as const,
      dogPolicy: "Boutique hotel on Main Street with pet-friendly rooms. Small dogs welcome with advance notice.",
      maxDogWeight: 30,
      petFee: 35,
      amenities: ["Downtown location", "Water bowls", "Treats", "Walking map", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.connorhotel.com",
      phone: "(928) 634-5006",
    },
    {
      name: "Ghost City Inn Bed & Breakfast",
      address: "541 Main St, Jerome, AZ 86331",
      lat: 34.7505,
      lng: -112.1150,
      priceRange: "$$" as const,
      dogPolicy: "Cozy B&B with one designated pet-friendly room. Dogs must be well-behaved and quiet due to the intimate setting.",
      maxDogWeight: 40,
      petFee: 40,
      amenities: ["Pet-friendly room", "Garden access", "Water bowls", "Breakfast included", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ghostcityinn.com",
      phone: "(928) 634-4678",
    },
    {
      name: "Clinkscale Cottage",
      address: "747 East Ave, Jerome, AZ 86331",
      lat: 34.7480,
      lng: -112.1120,
      priceRange: "$$$" as const,
      dogPolicy: "Private vacation rental cottage that welcomes dogs of all sizes. Fenced yard with panoramic views of the Verde Valley.",
      maxDogWeight: 0,
      petFee: 60,
      amenities: ["Fenced yard", "Full kitchen", "Valley views", "Dog bed", "Private entrance"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.vrbo.com",
      phone: "(928) 634-5000",
    },
  ],
  nationalParks: [
    {
      name: "Prescott National Forest (Mingus Mountain)",
      state: "Arizona",
      lat: 34.7100,
      lng: -112.1300,
      dogPolicy: "Dogs welcome on all national forest trails on leash or under voice control. Mingus Mountain offers cooler temperatures and pine forests above Jerome.",
      dogTrails: ["Woodchute Trail", "Mingus Rim Trail", "Coleman Trail", "Allen Spring Trail"],
      restrictions: ["Leash or voice control required", "Pack out waste", "Watch for wildlife", "Steep terrain in some areas"],
      description: "The Prescott National Forest blankets Mingus Mountain above Jerome with ponderosa pine and juniper woodland. Dogs can explore trails with sweeping views of the Verde Valley and San Francisco Peaks while enjoying cooler mountain temperatures.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/prescott",
    },
    {
      name: "Tuzigoot National Monument",
      state: "Arizona",
      lat: 34.7700,
      lng: -112.0267,
      dogPolicy: "Dogs allowed on outdoor trails on a leash. Not permitted inside the visitor center or pueblo ruins.",
      dogTrails: ["Tavasci Marsh Overlook Trail", "Main Loop Trail"],
      restrictions: ["6-foot leash required", "Not allowed in pueblo ruins", "Not allowed in visitor center", "Stay on designated trails"],
      description: "Just below Jerome in the Verde Valley, Tuzigoot preserves a hilltop Sinagua pueblo ruin with panoramic views. The trails around the monument welcome leashed dogs and offer a peaceful walk through ancient history.",
      imageUrl: "",
      website: "https://www.nps.gov/tuzi",
    },
    {
      name: "Dead Horse Ranch State Park",
      state: "Arizona",
      lat: 34.7690,
      lng: -111.9930,
      dogPolicy: "Dogs welcome on all trails on a leash. A green oasis along the Verde River with multiple trail options for dogs and their owners.",
      dogTrails: ["Lime Kiln Trail", "Raptor Hill Trail", "Thumper Trail", "Verde River Greenway"],
      restrictions: ["6-foot leash required", "Not allowed in lagoons", "Clean up after pet", "Day use fee required"],
      description: "Located in nearby Cottonwood, this state park offers lush riparian trails along the Verde River, lagoons, and desert terrain. Dogs love the variety of landscapes from river walks to desert hills, all within a short drive from Jerome.",
      imageUrl: "",
      website: "https://azstateparks.com/dead-horse",
    },
  ],
  restaurants: [
    {
      name: "The Asylum Restaurant",
      address: "200 Hill St, Jerome, AZ 86331",
      lat: 34.7510,
      lng: -112.1140,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the outdoor terrace with spectacular valley views. Fine dining in the historic Jerome Grand Hotel.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.theasylumrestaurant.com",
    },
    {
      name: "Haunted Hamburger",
      address: "410 N Clark St, Jerome, AZ 86331",
      lat: 34.7500,
      lng: -112.1145,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Iconic Jerome burger spot with a dog-friendly patio perched on the mountainside. Breathtaking views while you eat.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thehauntedhamburger.com",
    },
    {
      name: "Grapes Restaurant",
      address: "111 Main St, Jerome, AZ 86331",
      lat: 34.7488,
      lng: -112.1132,
      cuisine: "Mediterranean",
      priceRange: "$$$" as const,
      dogPolicy: "Mediterranean-inspired dishes with a small outdoor seating area where dogs are welcome. Local wine selection available.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.grapesjerome.com",
    },
    {
      name: "Bobby D's BBQ",
      address: "119 Jerome Ave, Jerome, AZ 86331",
      lat: 34.7495,
      lng: -112.1138,
      cuisine: "BBQ",
      priceRange: "$" as const,
      dogPolicy: "Casual BBQ spot with outdoor picnic tables where dogs are welcome. Slow-smoked meats with Verde Valley views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bobbydsbbq.com",
    },
    {
      name: "Quince Grill & Cantina",
      address: "226 Main St, Jerome, AZ 86331",
      lat: 34.7498,
      lng: -112.1142,
      cuisine: "Mexican-Southwest",
      priceRange: "$$" as const,
      dogPolicy: "Lively cantina with a patio that welcomes dogs. Creative Mexican-Southwest fare and margaritas with mountain views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.quincegrill.com",
    },
  ],
  cafes: [
    {
      name: "Jerome Flatiron Café",
      address: "416 Main St, Jerome, AZ 86331",
      lat: 34.7497,
      lng: -112.1140,
      dogPolicy: "Charming café in the iconic Flatiron building with a tiny patio where dogs are welcome. Fresh-baked goods and espresso.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.jeromeflatironcafe.com",
    },
    {
      name: "Puscifer the Store & Café",
      address: "140 Main St, Jerome, AZ 86331",
      lat: 34.7490,
      lng: -112.1134,
      dogPolicy: "Eclectic shop and café with outdoor seating where leashed dogs are welcome. Coffee, tea, and unique gifts.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.pfrstore.com",
    },
    {
      name: "Mile High Grill & Inn",
      address: "309 Main St, Jerome, AZ 86331",
      lat: 34.7495,
      lng: -112.1137,
      dogPolicy: "Cozy café with outdoor seating on Main Street. Dogs welcome while you enjoy breakfast or coffee at a mile-high elevation.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.jeromemilehighgrill.com",
    },
    {
      name: "Vaqueros Coffee",
      address: "317 Main St, Jerome, AZ 86331",
      lat: 34.7496,
      lng: -112.1139,
      dogPolicy: "Local coffee roaster with a small patio and mountain views. Dogs welcome outside with complimentary water bowls.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.vaqueroscoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Jerome Town Park",
      address: "Main St, Jerome, AZ 86331",
      lat: 34.7502,
      lng: -112.1148,
      offLeash: false,
      fenced: false,
      acres: 1,
      amenities: ["Benches", "Shade trees", "Valley views", "Waste bag stations"],
      rating: 4.0,
      imageUrl: "",
      description: "A small park along Main Street where leashed dogs can rest and enjoy the panoramic Verde Valley views. A great spot to take a break while exploring Jerome's steep streets.",
    },
    {
      name: "Upper Park / Hogback Trail",
      address: "Perkinsville Rd, Jerome, AZ 86331",
      lat: 34.7520,
      lng: -112.1160,
      offLeash: false,
      fenced: false,
      acres: 15,
      amenities: ["Hiking trail", "Mountain views", "Historic mining sites", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description: "A trail above Jerome that follows the old mining roads along Mingus Mountain. Dogs on leash can explore with their owners while taking in historic mine ruins and sweeping valley vistas.",
    },
    {
      name: "Cottonwood Dog Park",
      address: "1500 E Cherry St, Cottonwood, AZ 86326",
      lat: 34.7340,
      lng: -111.9890,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Shade structures", "Benches", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "Located in nearby Cottonwood, this fully fenced dog park offers the closest off-leash experience to Jerome. Separate areas for large and small dogs with shade structures and water stations.",
    },
    {
      name: "Verde River Greenway",
      address: "1284 W Mesquite Dr, Cottonwood, AZ 86326",
      lat: 34.7420,
      lng: -112.0100,
      offLeash: false,
      fenced: false,
      acres: 20,
      amenities: ["Paved trail", "River access", "Bird watching", "Benches", "Shade"],
      rating: 4.5,
      imageUrl: "",
      description: "A scenic riverside trail in the Verde Valley below Jerome where leashed dogs can enjoy a gentle walk along the Verde River. The cottonwood-lined path offers shade and water access for dogs on warm days.",
    },
  ],
};
