export const josephOrData = {
  city: {
    name: "Joseph",
    state: "Oregon",
    region: "Pacific Northwest",
    lat: 45.3546,
    lng: -117.2295,
    dogFriendlinessScore: 8,
    description:
      "Joseph is a tiny art town at the foot of the Wallowa Mountains, often called the Swiss Alps of Oregon. Dogs thrive here with access to pristine alpine lakes, vast wilderness trails, and a charming main street filled with bronze sculptures and dog-friendly shops. The remote location means fewer crowds and more nature for adventurous pups.",
    heroImage: "https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 1120,
  },

  hotels: [
    {
      name: "Bronze Antler Bed & Breakfast",
      address: "309 S Main St, Joseph, OR 97846",
      lat: 45.3540,
      lng: -117.2290,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in the pet-friendly suite with advance notice. Craftsman-style B&B in downtown Joseph.",
      maxDogWeight: 60,
      petFee: 35,
      amenities: ["Dog bed", "Treats", "Fenced yard access", "Walking map", "Near Wallowa Lake"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.bronzeantler.com",
      phone: "(541) 432-0230",
    },
    {
      name: "Wallowa Lake Lodge",
      address: "60060 Wallowa Lake Hwy, Joseph, OR 97846",
      lat: 45.2940,
      lng: -117.2110,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in cabins only with a per-night fee. Historic 1923 lodge on the shores of Wallowa Lake.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Lake access", "Cabin porches", "Hiking trails", "Dog bed", "Water bowls"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.wallowalakelodge.com",
      phone: "(541) 432-9821",
    },
    {
      name: "Indian Lodge Motel",
      address: "201 S Main St, Joseph, OR 97846",
      lat: 45.3545,
      lng: -117.2292,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome with a small pet fee. Simple, clean rooms in the heart of Joseph.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Pet waste stations", "Walking distance to trails", "Grassy areas", "Water bowls"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.indianlodgemotel.com",
      phone: "(541) 432-2651",
    },
    {
      name: "Jennings Hotel",
      address: "100 N Main St, Joseph, OR 97846",
      lat: 45.3555,
      lng: -117.2298,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with advance notice. Beautifully restored historic hotel on Main Street.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Gourmet treats", "Walking map", "Downtown location", "Mountain views"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.jenningshotel.com",
      phone: "(541) 432-0505",
    },
  ],

  nationalParks: [
    {
      name: "Eagle Cap Wilderness",
      state: "Oregon",
      lat: 45.2000,
      lng: -117.3000,
      dogPolicy: "Dogs welcome on all trails under voice control. No leash requirement in the wilderness but should be under control at all times.",
      dogTrails: ["Hurricane Creek Trail", "Ice Lake Trail", "Chimney Lake Trail", "East Fork Lostine Trail"],
      restrictions: [
        "Must be under voice control",
        "Not allowed to chase wildlife",
        "Pack out all waste in popular areas",
      ],
      description:
        "The largest wilderness area in Oregon features alpine lakes, granite peaks, and meadows of wildflowers. Dogs can hike off-leash under voice control on trails that reach above 9,000 feet, making it a premier backcountry dog adventure.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/recarea/wallowa-whitman",
    },
    {
      name: "Wallowa-Whitman National Forest",
      state: "Oregon",
      lat: 45.3000,
      lng: -117.2500,
      dogPolicy: "Leashed dogs in developed areas, voice control on trails. Vast forested lands surrounding Joseph.",
      dogTrails: ["Chief Joseph Trail", "BC Creek Trail", "Wallowa Lake Tramway trails", "West Fork Wallowa Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on trails",
        "Not allowed in designated swimming areas",
      ],
      description:
        "The national forest surrounding the Wallowa Valley offers thousands of acres of hiking, from riverside walks to mountain ridge traverses. Dogs love the diverse terrain, creek crossings, and the chance to explore true wilderness.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/wallowa-whitman",
    },
    {
      name: "Hells Canyon National Recreation Area",
      state: "Oregon",
      lat: 45.2500,
      lng: -116.7500,
      dogPolicy: "Leashed dogs welcome on most trails. Voice control acceptable on backcountry trails.",
      dogTrails: ["Hells Canyon Reservoir Trail", "Saddle Creek Trail", "Snake River Trail"],
      restrictions: [
        "Leash required in developed areas",
        "Voice control in backcountry",
        "Be aware of rattlesnakes in lower elevations",
      ],
      description:
        "North America's deepest river gorge offers dramatic canyon scenery and river access. The trail system provides challenging hikes with incredible views, and dogs love the rugged terrain and swimming holes along the Snake River.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/recarea/wallowa-whitman",
    },
  ],

  restaurants: [
    {
      name: "Embers Brewhouse",
      address: "204 N Main St, Joseph, OR 97846",
      lat: 45.3558,
      lng: -117.2300,
      cuisine: "Brewpub & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Local craft beer and hearty mountain food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.embersbrewhouse.com",
    },
    {
      name: "Red Horse Coffee Traders",
      address: "306 N Main St, Joseph, OR 97846",
      lat: 45.3562,
      lng: -117.2302,
      cuisine: "Cafe & Light Fare",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Local gathering spot with coffee, pastries, and light meals.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.redhorsecoffee.com",
    },
    {
      name: "Stubborn Mule Saloon",
      address: "302 N Main St, Joseph, OR 97846",
      lat: 45.3560,
      lng: -117.2300,
      cuisine: "Western American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the covered porch. Classic Western saloon with burgers and steaks.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.stubbornmulejoseph.com",
    },
    {
      name: "Calderas Restaurant",
      address: "300 N Lake St, Joseph, OR 97846",
      lat: 45.3550,
      lng: -117.2280,
      cuisine: "Pacific Northwest Fine Dining",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor terrace. Upscale seasonal dining with Wallowa Valley ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.calderasrestaurant.com",
    },
    {
      name: "Old Town Cafe",
      address: "8 S Main St, Joseph, OR 97846",
      lat: 45.3548,
      lng: -117.2295,
      cuisine: "American Breakfast & Lunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor tables. Hearty breakfast spot popular with hikers and ranchers alike.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.oldtowncafejoseph.com",
    },
  ],

  cafes: [
    {
      name: "Red Horse Coffee Traders",
      address: "306 N Main St, Joseph, OR 97846",
      lat: 45.3562,
      lng: -117.2302,
      dogPolicy: "Dogs welcome on the patio. The social hub of Joseph with excellent espresso and baked goods.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.redhorsecoffee.com",
    },
    {
      name: "Glacier Grind Espresso",
      address: "59951 Wallowa Lake Hwy, Joseph, OR 97846",
      lat: 45.3200,
      lng: -117.2180,
      dogPolicy: "Drive-through with walk-up window. Dogs welcome at the outdoor benches.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.glaciergrind.com",
    },
    {
      name: "Arrowhead Chocolates",
      address: "100 N Main St, Joseph, OR 97846",
      lat: 45.3555,
      lng: -117.2298,
      dogPolicy: "Leashed dogs welcome at outdoor seating. Artisan chocolates, espresso, and ice cream.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.arrowheadchocolates.com",
    },
    {
      name: "Mountain Air Cafe",
      address: "106 S Main St, Joseph, OR 97846",
      lat: 45.3542,
      lng: -117.2290,
      dogPolicy: "Outdoor patio welcomes dogs. Cozy mountain cafe with fresh pastries and specialty drinks.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.mountainaircafe.com",
    },
  ],

  dogParks: [
    {
      name: "Joseph City Park",
      address: "Main St & Wallowa Ave, Joseph, OR 97846",
      lat: 45.3545,
      lng: -117.2285,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Walking paths", "Open grass", "Picnic areas", "Restrooms", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "Joseph's central park offers open green spaces and walking paths with views of the Wallowa Mountains. Leashed dogs enjoy the spacious grounds and the chance to meet other pups in this friendly small town.",
    },
    {
      name: "Wallowa Lake State Park Beach",
      address: "72214 Marina Ln, Joseph, OR 97846",
      lat: 45.2930,
      lng: -117.2120,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Lake access", "Sandy beach", "Picnic areas", "Campground", "Boat launch", "Restrooms"],
      rating: 4.7,
      imageUrl: "",
      description:
        "The south shore of Wallowa Lake offers beach access with stunning mountain views. Leashed dogs can wade in the crystal-clear glacial lake and walk along the shoreline with the Wallowa Mountains towering above.",
    },
    {
      name: "Hurricane Creek Trailhead Area",
      address: "Hurricane Creek Rd, Joseph, OR 97846",
      lat: 45.3280,
      lng: -117.2900,
      offLeash: true,
      fenced: false,
      acres: 100.0,
      amenities: ["Trailhead parking", "Creek access", "Mountain trails", "Wilderness access"],
      rating: 4.8,
      imageUrl: "",
      description:
        "The Hurricane Creek Trail leads into the Eagle Cap Wilderness where dogs can run off-leash under voice control. The trail follows a rushing mountain creek through forests and meadows with towering granite peaks all around.",
    },
    {
      name: "Iwetemlaykin State Heritage Site",
      address: "Wallowa Lake Hwy, Joseph, OR 97846",
      lat: 45.3350,
      lng: -117.2200,
      offLeash: false,
      fenced: false,
      acres: 62.0,
      amenities: ["Nature trails", "Interpretive signs", "Mountain views", "Wildlife viewing", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A state heritage site preserving Nez Perce cultural landscapes with gentle trails through grasslands and along Wallowa Lake's moraine. Leashed dogs enjoy the easy walking and spectacular mountain scenery.",
    },
  ],
};
