export const joshuaTreeData = {
  city: {
    name: "Joshua Tree",
    state: "California",
    region: "West Coast",
    lat: 34.1347,
    lng: -116.3131,
    dogFriendlinessScore: 7,
    description:
      "Where the Mojave and Colorado deserts collide, Joshua Tree is a surreal wonderland of twisted trees, massive boulder formations, and star-filled skies. While the national park itself has limited dog access, the surrounding desert community embraces pups with quirky cafes, dog-friendly vacation rentals, and miles of BLM land where your four-legged explorer can channel their inner coyote.",
    heroImage: "https://images.unsplash.com/photo-1542552617-fadededf8ba2?w=1200&fit=crop",
    climate: "Desert",
    population: 7414,
  },

  hotels: [
    {
      name: "AutoCamp Joshua Tree",
      address: "62209 Verbena Rd, Joshua Tree, CA 92252",
      lat: 34.1312,
      lng: -116.3145,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in Airstream suites with a one-time pet fee. Desert glamping at its finest for you and your pup.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Airstream suites", "Private outdoor space", "Dog bed", "Water bowls", "Stargazing deck"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.autocamp.com/joshua-tree",
      phone: "(888) 405-7553",
    },
    {
      name: "Fairfield Inn & Suites Twentynine Palms",
      address: "5396 Adobe Rd, Twentynine Palms, CA 92277",
      lat: 34.1355,
      lng: -116.0541,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a nightly pet fee. Close to the park's north entrance for early morning desert adventures.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Pool area", "Grassy walk area", "Waste stations", "Breakfast included", "Refrigerator"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(760) 361-7400",
    },
    {
      name: "Joshua Tree Inn",
      address: "61259 Twentynine Palms Hwy, Joshua Tree, CA 92252",
      lat: 34.1318,
      lng: -116.3212,
      priceRange: "$$" as const,
      dogPolicy: "Historic desert inn welcoming well-behaved dogs in select rooms. A legendary spot with retro desert charm.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Courtyard", "Desert garden", "Vintage decor", "Dog bowls on request", "Close to downtown JT"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.joshuatreeinn.com",
      phone: "(760) 366-1188",
    },
    {
      name: "Holiday Inn Express & Suites Twentynine Palms",
      address: "71809 Twentynine Palms Hwy, Twentynine Palms, CA 92277",
      lat: 34.1364,
      lng: -116.0610,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms available with a per-night fee. Modern amenities and easy park access.",
      maxDogWeight: 75,
      petFee: 35,
      amenities: ["Pool", "Hot tub", "Waste stations", "Walking area", "Complimentary breakfast"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(760) 361-4900",
    },
    {
      name: "Sacred Sands Resort",
      address: "63155 Quail Springs Rd, Joshua Tree, CA 92252",
      lat: 34.1510,
      lng: -116.3380,
      priceRange: "$$$$" as const,
      dogPolicy: "Select suites welcome dogs with advance reservation. Private desert oasis with panoramic views.",
      maxDogWeight: 40,
      petFee: 100,
      amenities: ["Private hot tub", "Desert garden", "Panoramic views", "Full kitchen", "Stargazing"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.sacredsands.com",
      phone: "(760) 366-4535",
    },
  ],

  nationalParks: [
    {
      name: "Joshua Tree National Park",
      state: "California",
      lat: 33.8734,
      lng: -115.9010,
      dogPolicy: "Dogs allowed within 100 feet of roads, in campgrounds, and in picnic areas only. Not permitted on any trails or in the backcountry.",
      dogTrails: [
        "Campground loops at Jumbo Rocks",
        "Black Rock Canyon Campground roads",
        "Cottonwood Campground paved areas",
      ],
      restrictions: [
        "No dogs on any hiking trails",
        "Must stay within 100 feet of roads",
        "Must be on leash (6 ft max) at all times",
        "Never leave dogs in vehicles — desert heat is lethal",
        "Not allowed in backcountry",
      ],
      description:
        "The park's iconic twisted Joshua trees and surreal boulder landscapes are best enjoyed from the scenic drives with your pup. While trail access is extremely limited for dogs, the campgrounds and roadside pullouts still offer incredible desert scenery and world-class stargazing.",
      imageUrl: "",
      website: "https://www.nps.gov/jotr",
    },
    {
      name: "Death Valley National Park",
      state: "California",
      lat: 36.5054,
      lng: -116.9325,
      dogPolicy: "Dogs allowed on roads, in campgrounds, and within 100 feet of developed areas. Limited but dramatic desert scenery accessible with your pup.",
      dogTrails: [
        "Furnace Creek Campground area",
        "Stovepipe Wells area roads",
        "Mesquite Flat Sand Dunes (from parking area only)",
      ],
      restrictions: [
        "No dogs on any trails",
        "Must be on leash at all times",
        "Extreme heat danger — check conditions before visiting",
        "Carry extra water for your dog",
      ],
      description:
        "The hottest, driest, and lowest national park offers alien landscapes of salt flats, canyons, and sand dunes. A longer day trip from Joshua Tree, but the otherworldly scenery visible from the road is unforgettable for adventurous dog-and-human duos.",
      imageUrl: "",
      website: "https://www.nps.gov/deva",
    },
    {
      name: "Mojave National Preserve",
      state: "California",
      lat: 35.1415,
      lng: -115.5108,
      dogPolicy: "Dogs allowed on roads, in campgrounds, and on the Kelso Dunes trail — one of the more generous NPS dog policies in the desert.",
      dogTrails: [
        "Kelso Dunes Trail",
        "Teutonia Peak Trail",
        "Campground loops at Mid Hills and Hole-in-the-Wall",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Watch for extreme heat and rattlesnakes",
        "Carry plenty of water",
      ],
      description:
        "This vast desert preserve between LA and Las Vegas is a hidden gem for dog owners. Leashed pups can hike to the singing Kelso Dunes, explore Joshua tree forests, and camp under some of the darkest skies in California.",
      imageUrl: "",
      website: "https://www.nps.gov/moja",
    },
  ],

  restaurants: [
    {
      name: "Crossroads Cafe",
      address: "61715 Twentynine Palms Hwy, Joshua Tree, CA 92252",
      lat: 34.1318,
      lng: -116.3140,
      cuisine: "Eclectic American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the shaded desert patio. A beloved Joshua Tree institution with live music nights.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.crossroadsjtca.com",
    },
    {
      name: "La Copine",
      address: "848 Old Woman Springs Rd, Flamingo Heights, CA 92252",
      lat: 34.2018,
      lng: -116.3645,
      cuisine: "California Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome in the outdoor dining area. Seasonal brunch in the high desert.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.lacopinekitchen.com",
    },
    {
      name: "Pappy & Harriet's Pioneertown Palace",
      address: "53688 Pioneertown Rd, Pioneertown, CA 92268",
      lat: 34.1571,
      lng: -116.4938,
      cuisine: "BBQ & Tex-Mex",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio of this legendary desert honky-tonk. Live music, mesquite BBQ, and desert vibes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.pappyandharriets.com",
    },
    {
      name: "Natural Sisters Cafe",
      address: "61695 Twentynine Palms Hwy, Joshua Tree, CA 92252",
      lat: 34.1316,
      lng: -116.3155,
      cuisine: "Vegetarian & Juice Bar",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly patio with shade. Organic smoothies and veggie wraps to fuel your desert hikes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.naturalsisterscafe.com",
    },
    {
      name: "Joshua Tree Saloon",
      address: "61835 Twentynine Palms Hwy, Joshua Tree, CA 92252",
      lat: 34.1320,
      lng: -116.3118,
      cuisine: "American Pub",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the patio of this classic desert watering hole. Cold beer and good times under the stars.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.joshuatreesaloon.com",
    },
    {
      name: "JT Country Kitchen",
      address: "61768 Twentynine Palms Hwy, Joshua Tree, CA 92252",
      lat: 34.1319,
      lng: -116.3125,
      cuisine: "American Breakfast & Diner",
      priceRange: "$" as const,
      dogPolicy: "Outdoor seating available for dog owners. Hearty breakfast plates to start your desert day right.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Pie for the People",
      address: "61740 Twentynine Palms Hwy, Joshua Tree, CA 92252",
      lat: 34.1317,
      lng: -116.3130,
      cuisine: "Pizza",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor tables. New York-style pizza by the slice in the Mojave Desert.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.pieforthepeople.com",
    },
    {
      name: "29 Palms Inn Restaurant",
      address: "73950 Inn Ave, Twentynine Palms, CA 92277",
      lat: 34.1270,
      lng: -116.0522,
      cuisine: "California Contemporary",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome in the garden dining area. A desert oasis with farm-fresh ingredients grown on-site.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.29palmsinn.com",
    },
  ],

  cafes: [
    {
      name: "Joshua Tree Coffee Company",
      address: "61738 Twentynine Palms Hwy, Joshua Tree, CA 92252",
      lat: 34.1317,
      lng: -116.3132,
      dogPolicy: "Shaded patio where leashed dogs are always welcome. The go-to morning spot for desert dwellers and their pups.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.joshuatreecoffee.com",
    },
    {
      name: "Frontier Cafe",
      address: "55844 Twentynine Palms Hwy, Yucca Valley, CA 92284",
      lat: 34.1185,
      lng: -116.4310,
      dogPolicy: "Dog-friendly outdoor patio with desert garden views. Craft coffee and fresh pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.frontierjt.com",
    },
    {
      name: "Giant Rock Meeting Room",
      address: "61839 Twentynine Palms Hwy, Joshua Tree, CA 92252",
      lat: 34.1321,
      lng: -116.3115,
      dogPolicy: "Laid-back desert coffee spot with outdoor seating where dogs are part of the community.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Roadrunner Grab & Go",
      address: "55828 Twentynine Palms Hwy, Yucca Valley, CA 92284",
      lat: 34.1183,
      lng: -116.4315,
      dogPolicy: "Quick coffee and breakfast burritos with a patio for dogs. Fuel up before hitting the trails.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.0,
      imageUrl: "",
      website: "",
    },
    {
      name: "The Station",
      address: "61597 Twentynine Palms Hwy, Joshua Tree, CA 92252",
      lat: 34.1312,
      lng: -116.3180,
      dogPolicy: "Vintage gas station turned coffee shop with a dog-friendly patio and desert gift shop.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
  ],

  dogParks: [
    {
      name: "Luckie Park Off-Leash Area",
      address: "6748 Luckie Ave, Twentynine Palms, CA 92277",
      lat: 34.1388,
      lng: -116.0645,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Water station", "Waste stations", "Benches", "Shade structures"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A fenced off-leash area within Luckie Park where desert dogs can stretch their legs. Shade structures and water stations are essential in this sun-drenched landscape.",
    },
    {
      name: "Pioneertown Mountains Preserve",
      address: "Pioneertown Rd, Pioneertown, CA 92268",
      lat: 34.1635,
      lng: -116.4870,
      offLeash: false,
      fenced: false,
      acres: 2100.0,
      amenities: ["Hiking trails", "Desert views", "Wildlife viewing", "Parking area", "Trail maps"],
      rating: 4.7,
      imageUrl: "",
      description:
        "Over 2,000 acres of preserved desert wilderness with trails open to leashed dogs. Dramatic canyon landscapes and Joshua tree forests make this a world-class desert hiking destination for you and your pup.",
    },
    {
      name: "Yucca Valley Community Dog Park",
      address: "57401 Twentynine Palms Hwy, Yucca Valley, CA 92284",
      lat: 34.1165,
      lng: -116.4125,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Separate small dog area", "Water fountains", "Shade canopies", "Waste stations", "Benches"],
      rating: 4.3,
      imageUrl: "",
      description:
        "The best fenced dog park in the Joshua Tree area with separate small and large dog sections. Shade canopies provide critical relief from the desert sun while pups socialize.",
    },
    {
      name: "BLM Desert Trails (Flat Top Mesa)",
      address: "Flat Top Mesa, Joshua Tree, CA 92252",
      lat: 34.1450,
      lng: -116.2950,
      offLeash: true,
      fenced: false,
      acres: 500.0,
      amenities: ["Open desert terrain", "Hiking trails", "Mountain views", "Free access", "Unlimited space"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Bureau of Land Management land surrounding Joshua Tree offers vast open desert where dogs can roam off-leash. The sunsets over the desert floor will stop both you and your dog in your tracks.",
    },
    {
      name: "Black Rock Canyon Trail Area",
      address: "Black Rock Canyon Rd, Yucca Valley, CA 92284",
      lat: 34.0754,
      lng: -116.3878,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Campground", "Nature trails nearby", "Waste stations", "Parking", "Ranger station"],
      rating: 4.1,
      imageUrl: "",
      description:
        "The area outside Black Rock Canyon campground offers leashed walks along the campground roads with views into Joshua Tree National Park. A great staging area for desert dogs before hitting the open BLM land.",
    },
  ],
};
