export const kansasCityData = {
  city: {
    name: "Kansas City",
    state: "Missouri",
    region: "Midwest",
    lat: 39.0997,
    lng: -94.5786,
    dogFriendlinessScore: 8,
    description:
      "KC is a haven for dogs with its legendary barbecue patios, expansive off-leash parks, and a culture that genuinely celebrates canine companionship. From the trendy Crossroads district to the wide-open spaces of Swope Park, Kansas City delivers big on dog-friendly experiences at Midwest-friendly prices.",
    heroImage: "https://images.unsplash.com/photo-1578024639370-93b54e3c4c22?w=1200&fit=crop",
    climate: "Humid continental",
    population: 508090,
  },
  hotels: [
    {
      name: "Hotel Kansas City",
      address: "1228 Baltimore Ave, Kansas City, MO 64105",
      lat: 39.1010,
      lng: -94.5820,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of any size welcome with a per-stay fee. A stunning Art Deco hotel in the restored Kansas City Club building.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking map", "Waste bags"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hotelkansascity.com",
      phone: "(816) 771-7979",
    },
    {
      name: "21c Museum Hotel Kansas City",
      address: "219 W 9th St, Kansas City, MO 64105",
      lat: 39.1040,
      lng: -94.5850,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a pet fee. A contemporary art museum and hotel in a restored YMCA building.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Art-filled lobby", "Walking route map", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.21cmuseumhotels.com/kansas-city",
      phone: "(816) 931-2100",
    },
    {
      name: "The Raphael Hotel",
      address: "325 Ward Pkwy, Kansas City, MO 64112",
      lat: 39.0420,
      lng: -94.5890,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 40 lbs welcome with a non-refundable fee. An elegant hotel on the Country Club Plaza.",
      maxDogWeight: 40,
      petFee: 100,
      amenities: ["Dog bed", "Water bowls", "Plaza walking access", "Waste bags", "Concierge pet services"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.raphaelkc.com",
      phone: "(816) 756-3800",
    },
    {
      name: "Aloft Kansas City Country Club Plaza",
      address: "901 W 48th Pl, Kansas City, MO 64112",
      lat: 39.0410,
      lng: -94.5960,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome at no extra charge. Near the Country Club Plaza with Aloft's pet-forward program.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Pet toys", "Waste bags", "Treats at front desk"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com/hotels/travel/mcial",
      phone: "(816) 561-5500",
    },
  ],
  nationalParks: [
    {
      name: "Harry S. Truman National Historic Site",
      state: "Missouri",
      lat: 38.9240,
      lng: -94.5190,
      dogPolicy: "Dogs welcome on the grounds on a 6-foot leash. Not permitted inside the Truman home or visitor center.",
      dogTrails: ["Home Grounds Walk", "Neighborhood Walk"],
      restrictions: ["6-foot leash required", "Not inside buildings", "Must clean up after pet"],
      description: "About 15 minutes from downtown KC, the Truman home in Independence preserves the neighborhood where the 33rd president lived. Dogs can walk the grounds and the surrounding tree-lined residential streets.",
      imageUrl: "",
      website: "https://www.nps.gov/hstr",
    },
    {
      name: "Swope Park",
      state: "Missouri",
      lat: 39.0350,
      lng: -94.5100,
      dogPolicy: "Dogs welcome on all trails on a leash. One of the largest urban parks in the nation at 1,805 acres.",
      dogTrails: ["Blue River Trail", "Swope Park Trail", "Lakeside Nature Trail"],
      restrictions: ["Leash required except in designated dog parks", "Not in zoo", "Must clean up after pet"],
      description: "At 1,805 acres, Swope Park is one of the largest urban parks in the US. Dogs enjoy miles of forested trails, the Blue River, and extensive green spaces just minutes from downtown Kansas City.",
      imageUrl: "",
      website: "https://www.kcparks.org/places/swope-park",
    },
    {
      name: "Shawnee Mission Park",
      state: "Kansas",
      lat: 38.9520,
      lng: -94.8000,
      dogPolicy: "Dogs welcome on trails on a leash. A 1,655-acre county park with a lake and diverse habitats on the Kansas side.",
      dogTrails: ["Mountain Bike Trail", "Nature Trail", "Lake Loop Trail", "Prairie Trail"],
      restrictions: ["Leash required except at dog park", "Not on beach", "Must clean up after pet"],
      description: "The most-visited park in Johnson County features a 120-acre lake, forests, and extensive trails. About 20 minutes from downtown KC, dogs can hike varied terrain and visit the large off-leash dog park within the park.",
      imageUrl: "",
      website: "https://www.jcprd.com/facilities/shawnee-mission-park",
    },
  ],
  restaurants: [
    {
      name: "Joe's Kansas City Bar-B-Que",
      address: "3002 W 47th Ave, Kansas City, KS 66103",
      lat: 39.0550,
      lng: -94.6250,
      cuisine: "Barbecue",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor picnic tables. The legendary KC barbecue joint inside a gas station.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.joeskc.com",
    },
    {
      name: "Brewery Emperial",
      address: "1829 Oak St, Kansas City, MO 64108",
      lat: 39.0870,
      lng: -94.5800,
      cuisine: "Brewpub & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the spacious outdoor beer garden. A Crossroads craft brewery with creative food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.breweryemperial.com",
    },
    {
      name: "Gram & Dun",
      address: "600 Ward Pkwy, Kansas City, MO 64112",
      lat: 39.0410,
      lng: -94.5870,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the Country Club Plaza patio. Upscale American fare with a sophisticated atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.gramanddun.com",
    },
    {
      name: "Char Bar",
      address: "4050 Pennsylvania Ave, Kansas City, MO 64111",
      lat: 39.0560,
      lng: -94.5900,
      cuisine: "Barbecue & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the huge outdoor area with yard games. A dog-friendly BBQ spot with a massive patio in Westport.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.charbar.com",
    },
    {
      name: "Betty Rae's Ice Cream",
      address: "7140 Wornall Rd, Kansas City, MO 64114",
      lat: 38.9970,
      lng: -94.5920,
      cuisine: "Ice Cream",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor window and seating area. Creative small-batch ice cream in Waldo.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bettyraes.com",
    },
  ],
  cafes: [
    {
      name: "Messenger Coffee Co.",
      address: "1624 Grand Blvd, Kansas City, MO 64108",
      lat: 39.0870,
      lng: -94.5770,
      dogPolicy: "Dogs welcome on the Crossroads patio. KC's most celebrated specialty roaster in a stunning industrial space.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.messengercoffee.co",
    },
    {
      name: "Thou Mayest Coffee Roasters",
      address: "519 Walnut St, Kansas City, MO 64106",
      lat: 39.1010,
      lng: -94.5750,
      dogPolicy: "Dogs welcome on the outdoor patio in the City Market area. Creative coffee roaster with a free-spirited vibe.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thoumayest.com",
    },
    {
      name: "Oddly Correct Coffee Bar",
      address: "3039 Gillham Rd, Kansas City, MO 64108",
      lat: 39.0790,
      lng: -94.5730,
      dogPolicy: "Dog-friendly outdoor seating. A no-frills specialty coffee bar focused purely on the quality of the cup.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.oddlycorrect.com",
    },
    {
      name: "Parisi Artisan Coffee",
      address: "22 E 8th St, Kansas City, MO 64106",
      lat: 39.1040,
      lng: -94.5830,
      dogPolicy: "Dogs welcome at the outdoor tables downtown. Italian-inspired coffee with a focus on traditional espresso.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.parisiartisancoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Bark Park at Swope Park",
      address: "4701 E Gregory Blvd, Kansas City, MO 64132",
      lat: 39.0330,
      lng: -94.5090,
      offLeash: true,
      fenced: true,
      acres: 10,
      amenities: ["Separate small dog area", "Water stations", "Agility equipment", "Shade pavilion", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "One of KC's largest and best dog parks, set within Swope Park with 10 acres of fenced off-leash space. Agility equipment, water stations, and wooded shade areas keep dogs entertained.",
    },
    {
      name: "Penn Valley Dog Park",
      address: "2801 Main St, Kansas City, MO 64108",
      lat: 39.0770,
      lng: -94.5800,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["City views", "Double-gated entry", "Water fountain", "Benches", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "An urban dog park with stunning views of the downtown KC skyline from Penn Valley Park. The fenced area provides off-leash fun in a convenient midtown location.",
    },
    {
      name: "Shawnee Mission Off-Leash Dog Park",
      address: "7900 Renner Rd, Shawnee, KS 66219",
      lat: 38.9520,
      lng: -94.8010,
      offLeash: true,
      fenced: true,
      acres: 33,
      amenities: ["Massive open fields", "Wooded trails", "Water stations", "Benches", "Separate small dog area"],
      rating: 4.7,
      imageUrl: "",
      description: "At 33 acres, this is one of the largest off-leash dog parks in the KC metro. Dogs can run through open meadows, explore wooded trails, and enjoy the expansive space within Shawnee Mission Park.",
    },
    {
      name: "Kessler Park Dog Park",
      address: "2600 Kessler Rd, Kansas City, MO 64108",
      lat: 39.0700,
      lng: -94.5700,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Benches", "Water fountain", "Shade trees", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      description: "A neighborhood dog park near the Crossroads district with separate areas for large and small dogs. The convenient location makes it a popular after-work stop for midtown dog owners.",
    },
  ],
};
