export const kennebunkportData = {
  city: {
    name: "Kennebunkport",
    state: "Maine",
    region: "Northeast",
    lat: 43.3615,
    lng: -70.4762,
    dogFriendlinessScore: 8,
    description:
      "This quintessential Maine coastal village is a dog lover's paradise with sandy beaches, rocky coastline, and a charming downtown that rolls out the welcome mat for pups. Kennebunkport's off-season beach policies are especially generous, and the surrounding nature preserves offer miles of dog-friendly trails.",
    heroImage: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 3535,
  },
  hotels: [
    {
      name: "The Yachtsman Hotel & Marina Club",
      address: "59 Ocean Ave, Kennebunkport, ME 04046",
      lat: 43.3537,
      lng: -70.474,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome with a $50 per stay fee. Riverfront rooms with private patios and direct access to waterfront walks.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Riverfront patios", "Marina views", "Walking paths", "Downtown walkability"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.yachtsmanlodge.com",
      phone: "(207) 967-2511",
    },
    {
      name: "The Grand Hotel",
      address: "1 Chase Hill Rd, Kennebunkport, ME 04046",
      lat: 43.3578,
      lng: -70.4736,
      priceRange: "$$$" as const,
      dogPolicy: "Pet-friendly rooms with a $35 per night fee. Rooftop pool and walking distance to Dock Square shops.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Rooftop pool", "Dock Square location", "Ocean views", "Balconies"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.thegrandhotel.com",
      phone: "(207) 967-3931",
    },
    {
      name: "Lodge on the Cove",
      address: "29 S Main St, Kennebunkport, ME 04046",
      lat: 43.351,
      lng: -70.476,
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly lodge with a $40 per stay fee. Pool, hammocks, and walking trails on a wooded property.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Pool", "Wooded grounds", "Hammocks", "Shuttle to beaches", "Fire pit"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.lodgeonthecove.com",
      phone: "(207) 967-3993",
    },
    {
      name: "Seaside Inn",
      address: "80 Beach Ave, Kennebunk, ME 04043",
      lat: 43.3371,
      lng: -70.4718,
      priceRange: "$$" as const,
      dogPolicy: "Beachfront inn welcoming dogs with a $25 per night fee. Direct access to Kennebunk Beach.",
      maxDogWeight: 60,
      petFee: 25,
      amenities: ["Beach access", "Ocean views", "Pet walking area", "Continental breakfast"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.kennebunkbeach.com",
      phone: "(207) 967-4461",
    },
  ],
  nationalParks: [
    {
      name: "Rachel Carson National Wildlife Refuge",
      state: "Maine",
      lat: 43.3442,
      lng: -70.5393,
      dogPolicy: "Leashed dogs welcome on the Carson Trail. A mile-long loop through pristine salt marsh with ocean views.",
      dogTrails: ["Carson Trail (1 mile loop)", "Timber Point Trail"],
      restrictions: ["Leash required at all times", "Stay on boardwalk", "No dogs on refuge beaches"],
      description:
        "Named for the pioneering environmentalist, this refuge protects over 5,000 acres of salt marsh along the southern Maine coast. The Carson Trail is a beautiful mile-long loop through marsh and forest with interpretive signs. Your leashed dog will love the rich saltwater scents and the diversity of bird life.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/rachel-carson",
    },
    {
      name: "Kennebunk Plains Preserve",
      state: "Maine",
      lat: 43.4106,
      lng: -70.5948,
      dogPolicy: "Leashed dogs welcome on the trail through rare grassland habitat. A unique sandplain grassland ecosystem.",
      dogTrails: ["Grassland Loop Trail", "Blueberry Barren Path"],
      restrictions: ["Leash required", "Stay on trails during nesting season", "No collecting blueberries commercially"],
      description:
        "One of the rarest ecosystems in New England — a vast sandplain grassland that comes alive with wildflowers in summer and wild blueberries in late July. The open landscape gives your dog (and you) a sense of endless space rare in forested Maine. Grasshopper sparrows and wild lupine thrive here.",
      imageUrl: "",
      website: "https://www.nature.org",
    },
    {
      name: "Vaughns Island Preserve",
      state: "Maine",
      lat: 43.3478,
      lng: -70.4916,
      dogPolicy: "Leashed dogs welcome. Accessible only at low tide via a sandbar crossing — check tide charts.",
      dogTrails: ["Island Loop Trail", "Shoreline Path"],
      restrictions: ["Leash required", "Only accessible at low tide", "Check tide charts before crossing"],
      description:
        "A magical tidal island accessible only by crossing a sandbar at low tide. Once across, trails loop through spruce forest and along rocky shoreline with views of Goose Rocks Beach and the Kennebunk River. The adventure of the tide-dependent crossing makes this an unforgettable outing for you and your dog.",
      imageUrl: "",
      website: "https://www.kennebunklandtrust.org",
    },
  ],
  restaurants: [
    {
      name: "The Clam Shack",
      address: "2 Western Ave, Kennebunk, ME 04043",
      lat: 43.3521,
      lng: -70.4783,
      cuisine: "Seafood",
      priceRange: "$" as const,
      dogPolicy: "Iconic takeout window with outdoor picnic tables on the bridge. Dogs welcome. Best fried clams in Maine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.theclamshack.net",
    },
    {
      name: "Bandaloop",
      address: "2 Dock Square, Kennebunkport, ME 04046",
      lat: 43.3571,
      lng: -70.4737,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Upscale dining with a dog-friendly patio overlooking Dock Square. Seasonal New England cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bandaloop.biz",
    },
    {
      name: "Alisson's Restaurant",
      address: "11 Dock Square, Kennebunkport, ME 04046",
      lat: 43.3574,
      lng: -70.4733,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Dock Square staple with a spacious outdoor patio. Leashed dogs welcome. Pub fare and seafood.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.alissons.com",
    },
    {
      name: "Old Vines Wine Bar",
      address: "173 Port Rd, Kennebunk, ME 04043",
      lat: 43.3616,
      lng: -70.4768,
      cuisine: "Mediterranean",
      priceRange: "$$$" as const,
      dogPolicy: "Wine bar with a charming garden patio. Dogs welcome outside. Creative small plates and extensive wine list.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.oldvineswinebar.com",
    },
    {
      name: "Duffy's Tavern & Grill",
      address: "4 Main St, Kennebunk, ME 04043",
      lat: 43.3888,
      lng: -70.5427,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Casual neighborhood tavern with outdoor seating. Dogs welcome on the patio. Classic pub food and local beers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "",
    },
  ],
  cafes: [
    {
      name: "Coffee Roasters of the Kennebunks",
      address: "163 Port Rd, Kennebunk, ME 04043",
      lat: 43.3611,
      lng: -70.4771,
      dogPolicy: "Local roaster with outdoor seating on Port Road. Dogs welcome outside while you enjoy freshly roasted coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "Mornings in Paris",
      address: "21 Western Ave, Kennebunk, ME 04043",
      lat: 43.3532,
      lng: -70.4796,
      dogPolicy: "French-inspired bakery with outdoor benches overlooking the river. Dogs welcome while you enjoy croissants and cafe au lait.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.morningsinparis.com",
    },
    {
      name: "Port Bakery & Cafe",
      address: "181 Port Rd, Kennebunk, ME 04043",
      lat: 43.3621,
      lng: -70.4762,
      dogPolicy: "Beloved local bakery with a patio. Homemade pastries and strong coffee. Dogs welcome at outdoor tables.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Dock Square Coffee House",
      address: "18 Dock Square, Kennebunkport, ME 04046",
      lat: 43.3576,
      lng: -70.4731,
      dogPolicy: "Coffee shop in the heart of Dock Square with outdoor seating. Perfect for people- and dog-watching in the village center.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Goose Rocks Beach",
      address: "Kings Hwy, Kennebunkport, ME 04046",
      lat: 43.3923,
      lng: -70.4392,
      offLeash: true,
      fenced: false,
      acres: 15.0,
      amenities: ["Sandy beach", "Off-leash seasonal", "Ocean swimming", "Parking", "Tidal pools"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A magnificent 3-mile sandy beach where dogs can run off-leash during the off-season (October through March). The gentle surf is perfect for dogs who love to swim, and the expansive sand flats at low tide create a massive playground. One of the best dog beaches in New England.",
    },
    {
      name: "Kennebunk Dog Park",
      address: "36 Sea Rd, Kennebunk, ME 04043",
      lat: 43.3727,
      lng: -70.5117,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fully fenced", "Wooded trails", "Open field", "Water station", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A community-built fenced dog park with both an open field area and wooded trails within the enclosure. The mix of terrain keeps dogs entertained, and the well-maintained space reflects the community's dedication to their four-legged residents.",
    },
    {
      name: "Parsons Way Shore Walk",
      address: "Ocean Ave, Kennebunkport, ME 04046",
      lat: 43.3395,
      lng: -70.4629,
      offLeash: false,
      fenced: false,
      acres: 4.0,
      amenities: ["Ocean views", "Rocky coastline", "Walking path", "Benches", "Bush family compound views"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A stunning coastal walking path along Ocean Avenue with views of crashing waves, rocky coves, and the famous Bush family compound at Walker's Point. Your leashed dog will love the salty sea air and the dramatic coastal scenery. Bring a camera — the views are postcard-perfect.",
    },
    {
      name: "Bridle Path Trail",
      address: "Bridle Path Ln, Kennebunk, ME 04043",
      lat: 43.3749,
      lng: -70.4978,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Forest trail", "River views", "Bridge crossings", "Quiet setting", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A peaceful former horse trail that winds through forest along the Mousam River. The flat, wide path is perfect for a relaxed dog walk, and the riverside setting provides a cooling breeze in summer. Less trafficked than the beaches, it's a great option for dogs who prefer quiet forest walks.",
    },
  ],
};
