export const ketchumData = {
  city: {
    name: "Ketchum",
    state: "Idaho",
    region: "Mountain West",
    lat: 43.6807,
    lng: -114.3637,
    dogFriendlinessScore: 8,
    description:
      "Ketchum is a mountain town where dogs live their absolute best lives. Nestled in the Wood River Valley at the base of Bald Mountain and Sun Valley Resort, this tiny town packs a massive punch for pup-loving adventurers. Dogs outnumber parking meters here, and they are welcomed in shops, on patios, and on endless miles of trails through alpine meadows and riverside paths. Whether it is skiing in winter or hiking in summer, Ketchum is a four-season playground where your dog is always the guest of honor.",
    heroImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&fit=crop",
    climate: "Continental",
    population: 2788,
  },

  hotels: [
    {
      name: "Limelight Hotel Ketchum",
      address: "151 S Main St, Ketchum, ID 83340",
      lat: 43.6805,
      lng: -114.3635,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a per-stay pet fee. Modern mountain hotel with direct trail access and a dog-loving culture.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Dog bed", "Bowls", "Treats", "Trail access", "Gear storage", "Outdoor patio"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.limelighthotels.com/ketchum",
      phone: "(208) 726-5700",
    },
    {
      name: "Sun Valley Lodge",
      address: "1 Sun Valley Rd, Sun Valley, ID 83353",
      lat: 43.6975,
      lng: -114.3505,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in select lodge rooms and cottages. The legendary resort that started it all, with sprawling grounds perfect for morning dog walks.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Plush dog bed", "Gourmet treats", "Walking trails on property", "Concierge pet sitting"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.sunvalley.com",
      phone: "(208) 622-4111",
    },
    {
      name: "Hotel Ketchum",
      address: "180 S Main St, Ketchum, ID 83340",
      lat: 43.6800,
      lng: -114.3640,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a one-time fee. Walkable downtown location puts you steps from dog-friendly restaurants and shops.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Dog bed", "Water bowls", "Walking map", "Near bike path"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hotelketchum.com",
      phone: "(208) 726-3611",
    },
    {
      name: "Knob Hill Inn",
      address: "960 N Main St, Ketchum, ID 83340",
      lat: 43.6870,
      lng: -114.3640,
      priceRange: "$$$$" as const,
      dogPolicy: "Small dogs welcome in this elegant European-style inn. Quiet luxury with mountain views and impeccable service for pets and people.",
      maxDogWeight: 25,
      petFee: 50,
      amenities: ["Dog bed", "Organic treats", "Garden access", "Mountain views"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.knobhillinn.com",
      phone: "(208) 726-8010",
    },
    {
      name: "Tamarack Lodge",
      address: "291 Walnut Ave N, Ketchum, ID 83340",
      lat: 43.6830,
      lng: -114.3615,
      priceRange: "$$" as const,
      dogPolicy: "A laid-back, dog-loving lodge where pups are practically expected. Rustic mountain charm with easy trail access.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Dog bed", "Bowls", "Outdoor deck", "Near Wood River Trail", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.tamaracksunvalley.com",
      phone: "(208) 726-3344",
    },
  ],

  nationalParks: [
    {
      name: "Sawtooth National Recreation Area",
      state: "Idaho",
      lat: 43.8722,
      lng: -114.8311,
      dogPolicy: "Leashed dogs welcome on most trails. One of Idaho's most spectacular mountain landscapes with excellent dog access.",
      dogTrails: ["Redfish Lake Creek Trail", "Alpine Lake Trail", "Iron Creek to Sawtooth Lake", "Fourth of July Lake Trail"],
      restrictions: [
        "Must be on leash in developed areas",
        "Voice control allowed on backcountry trails (check regulations)",
        "Not allowed in swimming beaches in developed areas",
      ],
      description:
        "Just north of Ketchum, the Sawtooth NRA encompasses over 750,000 acres of jaw-dropping mountain scenery. Jagged granite peaks, over 300 alpine lakes, and wildflower-filled meadows await. Your dog can hike to pristine mountain lakes and splash in crystal-clear streams while surrounded by some of the most dramatic scenery in the Lower 48.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/recarea/sawtooth",
    },
    {
      name: "Craters of the Moon National Monument",
      state: "Idaho",
      lat: 43.4167,
      lng: -113.5167,
      dogPolicy: "Leashed dogs allowed on paved trails and roads only. The lunar landscape is worth the visit even with limited dog access.",
      dogTrails: ["North Crater Flow Trail (paved)", "Devil's Orchard Trail (paved)"],
      restrictions: [
        "Dogs only on paved surfaces",
        "Must be on leash (6 ft max)",
        "Not allowed on unpaved trails or in caves",
        "Not allowed in wilderness area",
      ],
      description:
        "About 90 minutes from Ketchum, this otherworldly landscape of volcanic cinder cones, lava tubes, and lava flows looks like the surface of the moon. Dogs can explore the paved trails through this bizarre terrain, and the drive through the monument is spectacular.",
      imageUrl: "",
      website: "https://www.nps.gov/crmo",
    },
    {
      name: "Yellowstone National Park",
      state: "Wyoming / Montana / Idaho",
      lat: 44.4280,
      lng: -110.5885,
      dogPolicy: "Dogs allowed in parking areas, campgrounds, and on roads only. Very limited access but the drive-through experience is still unforgettable.",
      dogTrails: ["Old Faithful parking area viewpoints", "Mammoth Hot Springs boardwalk (check current regulations)"],
      restrictions: [
        "No dogs on any trails or boardwalks (with limited exceptions)",
        "Must be on leash (6 ft max) at all times",
        "Not allowed in thermal areas",
        "Not allowed more than 100 feet from roads or parking areas",
        "Not allowed in the backcountry",
      ],
      description:
        "About four hours from Ketchum, Yellowstone's geysers, hot springs, and wildlife are world-famous. While dog access is extremely limited, you can still see Old Faithful and many roadside attractions with your leashed pup. The drive through the park is an experience unto itself.",
      imageUrl: "",
      website: "https://www.nps.gov/yell",
    },
  ],

  restaurants: [
    {
      name: "The Kneadery",
      address: "260 Leadville Ave N, Ketchum, ID 83340",
      lat: 43.6825,
      lng: -114.3625,
      cuisine: "Breakfast & Brunch",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the front patio. A Ketchum breakfast institution where you will see dogs at nearly every outdoor table.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thekneadery.com",
    },
    {
      name: "Sawtooth Brewery Public House",
      address: "270 N Main St, Ketchum, ID 83340",
      lat: 43.6830,
      lng: -114.3638,
      cuisine: "Brewery & Pub Food",
      priceRange: "$$" as const,
      dogPolicy: "Super dog-friendly patio where four-legged friends are celebrated. Local craft beers and hearty pub food after a day on the trails.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.sawtoothbrewery.com",
    },
    {
      name: "Enoteca",
      address: "300 N Main St, Ketchum, ID 83340",
      lat: 43.6835,
      lng: -114.3638,
      cuisine: "Italian Wine Bar",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the vine-covered patio. Italian small plates and an incredible wine list in a cozy mountain setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.enotecasunvalley.com",
    },
    {
      name: "Warfield Distillery & Brewery",
      address: "280 N Main St, Ketchum, ID 83340",
      lat: 43.6832,
      lng: -114.3636,
      cuisine: "Distillery & American",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly outdoor area. House-made spirits and craft beers in a converted warehouse with mountain town character.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.warfielddistillery.com",
    },
    {
      name: "Rickshaw",
      address: "460 Washington Ave N, Ketchum, ID 83340",
      lat: 43.6845,
      lng: -114.3620,
      cuisine: "Asian Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Creative Asian-inspired dishes that are a refreshing change from mountain town pub fare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.rickshawketchum.com",
    },
    {
      name: "The Pioneer Saloon",
      address: "308 N Main St, Ketchum, ID 83340",
      lat: 43.6838,
      lng: -114.3637,
      cuisine: "Steakhouse & Western",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the heated outdoor patio. A Ketchum legend since 1955, serving prime Idaho beef under the stars.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thepioneersaloon.com",
    },
    {
      name: "Cristina's Restaurant",
      address: "520 2nd St E, Ketchum, ID 83340",
      lat: 43.6810,
      lng: -114.3600,
      cuisine: "Pacific Northwest",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the garden patio. Seasonal Pacific Northwest cuisine in an intimate setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.cristinasrestaurant.com",
    },
    {
      name: "Lefty's Bar & Grill",
      address: "231 6th St W, Ketchum, ID 83340",
      lat: 43.6795,
      lng: -114.3660,
      cuisine: "American Bar & Grill",
      priceRange: "$" as const,
      dogPolicy: "Casual dog-friendly patio perfect for post-hike burgers and cold beers. No frills, just good times with your pup.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.leftysketchum.com",
    },
  ],

  cafes: [
    {
      name: "Java on Fourth",
      address: "191 4th St E, Ketchum, ID 83340",
      lat: 43.6808,
      lng: -114.3615,
      dogPolicy: "The town's go-to coffee spot with a dog-friendly outdoor area. Locals and their dogs gather here every morning like clockwork.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.javaonfourth.com",
    },
    {
      name: "Sturtevants Mountain Outfitters Cafe",
      address: "340 N Main St, Ketchum, ID 83340",
      lat: 43.6840,
      lng: -114.3638,
      dogPolicy: "Coffee counter inside a beloved gear shop with outdoor seating where dogs wait patiently while their humans browse hiking boots.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.stfrts.com",
    },
    {
      name: "Power House Cafe",
      address: "502 N Main St, Ketchum, ID 83340",
      lat: 43.6855,
      lng: -114.3640,
      dogPolicy: "Smoothies, juices, and espresso with a sunny patio where trail dogs refuel alongside their humans.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.powerhouseketchum.com",
    },
    {
      name: "Konditorei Austrian Bakery",
      address: "200 Leadville Ave N, Ketchum, ID 83340",
      lat: 43.6818,
      lng: -114.3625,
      dogPolicy: "Charming Austrian bakery with outdoor benches where dogs are welcome. Strudels, Sachertorte, and strong Viennese coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.konditorei.com",
    },
    {
      name: "Maude's Coffee & Provisions",
      address: "180 4th St E, Ketchum, ID 83340",
      lat: 43.6806,
      lng: -114.3612,
      dogPolicy: "A cozy provisions shop with excellent coffee and a small patio. Dogs are welcome to join while you stock up for trail adventures.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.maudesketchum.com",
    },
  ],

  dogParks: [
    {
      name: "Ketchum Dog Park",
      address: "Warm Springs Rd, Ketchum, ID 83340",
      lat: 43.6760,
      lng: -114.3600,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Mountain views", "Waste stations", "Benches", "Water spigot"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Ketchum's dedicated off-leash park sits with stunning views of Bald Mountain. The fenced area gives dogs room to run and play while owners take in the mountain panorama. After-work summer evenings here are a Ketchum social institution.",
    },
    {
      name: "Wood River Trail",
      address: "Wood River Trail, Ketchum, ID 83340",
      lat: 43.6790,
      lng: -114.3580,
      offLeash: false,
      fenced: false,
      acres: 50.0,
      amenities: ["Paved path", "River access", "Mountain views", "Waste stations", "Connects to Hailey and Bellevue"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A beautiful paved trail that follows the Big Wood River through the entire valley. Leashed dogs love the riverside stretches where they can cool their paws. The trail runs 30 miles from Ketchum to Bellevue, connecting charming mountain towns.",
    },
    {
      name: "Adams Gulch Trail",
      address: "Adams Gulch Trailhead, Ketchum, ID 83340",
      lat: 43.7050,
      lng: -114.3690,
      offLeash: false,
      fenced: false,
      acres: 80.0,
      amenities: ["Hiking trails", "Creek crossings", "Wildflower meadows", "Mountain views", "Parking"],
      rating: 4.8,
      imageUrl: "",
      description:
        "One of the most popular hiking destinations near Ketchum, Adams Gulch offers stunning alpine meadows, creek crossings, and panoramic mountain views. Leashed dogs absolutely light up on this trail, splashing through streams and sniffing wildflowers. Summer mornings here are pure magic.",
    },
    {
      name: "Bald Mountain Open Space",
      address: "River Run Rd, Ketchum, ID 83340",
      lat: 43.6690,
      lng: -114.3480,
      offLeash: false,
      fenced: false,
      acres: 100.0,
      amenities: ["Mountain trails", "Ski lift views", "Wildlife viewing", "Varied terrain"],
      rating: 4.5,
      imageUrl: "",
      description:
        "The flanks of Bald Mountain offer incredible hiking in summer and fall with trails that wind through aspen groves and up to sweeping valley views. Leashed dogs tackle the elevation with enthusiasm, and the fall aspens turning gold are a sight neither of you will forget.",
    },
    {
      name: "Hulen Meadows Open Space",
      address: "Hulen Meadows Rd, Ketchum, ID 83340",
      lat: 43.7100,
      lng: -114.3750,
      offLeash: true,
      fenced: false,
      acres: 20.0,
      amenities: ["Open meadows", "Creek access", "Mountain backdrop", "Parking area", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A gorgeous open meadow north of Ketchum where dogs can run off-leash under voice control. The Big Wood River runs nearby, and the Sawtooth and Boulder Mountain backdrop is postcard-perfect. This is the Idaho dog experience distilled to its purest form.",
    },
  ],
};
