export const keyWestData = {
  city: {
    name: "Key West",
    state: "Florida",
    region: "Southeast",
    lat: 24.5551,
    lng: -81.7800,
    dogFriendlinessScore: 8,
    description:
      "At the end of the Overseas Highway, Key West greets dogs with tropical breezes, laid-back island vibes, and a quirky culture that celebrates animals of every kind. From sunset celebrations at Mallory Square to lazy afternoons on dog-friendly beaches, this southernmost city is a bucket-list destination for pups who love sand between their toes.",
    heroImage: "https://images.unsplash.com/photo-1568515045052-f9a854d70bfd?w=1200&fit=crop",
    climate: "Tropical savanna",
    population: 25478,
  },
  hotels: [
    {
      name: "The Marker Waterfront Resort",
      address: "200 William St, Key West, FL 33040",
      lat: 24.5590,
      lng: -81.8044,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 40 lbs welcome with advance notice. Harbor-view rooms and a pool steps from Mallory Square.",
      maxDogWeight: 40,
      petFee: 100,
      amenities: ["Dog bed", "Water bowls", "Welcome treats", "Pet-friendly room locations", "Walking map"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.themarkerresort.com",
      phone: "(305) 501-5193",
    },
    {
      name: "Parrot Key Hotel & Villas",
      address: "2801 N Roosevelt Blvd, Key West, FL 33040",
      lat: 24.5702,
      lng: -81.7597,
      priceRange: "$$$" as const,
      dogPolicy: "Dog-friendly villas with private patios and direct access to waterfront grounds. Two dogs max, under 45 lbs each.",
      maxDogWeight: 45,
      petFee: 75,
      amenities: ["Private patio", "Dog bed", "Water bowls", "Waterfront walking paths", "Pet waste stations"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.parrotkeyresort.com",
      phone: "(305) 809-2200",
    },
    {
      name: "The Perry Hotel Key West",
      address: "7001 Shrimp Rd, Key West, FL 33040",
      lat: 24.5719,
      lng: -81.7403,
      priceRange: "$$$" as const,
      dogPolicy: "Waterfront hotel at Stock Island Marina welcomes dogs of all sizes. Spacious grounds perfect for walks.",
      maxDogWeight: 0,
      petFee: 150,
      amenities: ["Dog bed", "Treats", "Marina walking paths", "Outdoor shower for sandy paws", "Concierge pet services"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.perrykeywest.com",
      phone: "(305) 296-1717",
    },
    {
      name: "Kimpton Winslow's Bungalows",
      address: "725 Truman Ave, Key West, FL 33040",
      lat: 24.5563,
      lng: -81.7962,
      priceRange: "$$$$" as const,
      dogPolicy: "Kimpton's signature no-fee pet policy applies. All dogs welcome regardless of size. Tropical garden setting.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treats", "Loaner leashes", "Tropical garden walks"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.winslowsbungalows.com",
      phone: "(305) 407-4774",
    },
    {
      name: "The Gates Hotel Key West",
      address: "3824 N Roosevelt Blvd, Key West, FL 33040",
      lat: 24.5730,
      lng: -81.7520,
      priceRange: "$$" as const,
      dogPolicy: "Modern hotel on the quieter end of the island welcomes dogs under 50 lbs. Pool area and tiki bar on site.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Tiki bar patio", "Pet relief area", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.gateshotelkeywest.com",
      phone: "(305) 296-5000",
    },
  ],
  nationalParks: [
    {
      name: "Dry Tortugas National Park",
      state: "Florida",
      lat: 24.6285,
      lng: -82.8732,
      dogPolicy: "Dogs are NOT permitted on the island, the fort, or the ferry. Service animals only. Kennel services available on Key West before departure.",
      dogTrails: [],
      restrictions: ["No dogs allowed anywhere in park", "Not permitted on ferry", "Service animals only", "Kennel options in Key West"],
      description: "Seventy miles west of Key West, this remote island fortress is surrounded by pristine turquoise waters and vibrant coral reefs. While dogs cannot join the journey, the snorkeling and history of Fort Jefferson are worth arranging pet care for the day.",
      imageUrl: "",
      website: "https://www.nps.gov/drto",
    },
    {
      name: "Everglades National Park",
      state: "Florida",
      lat: 25.2866,
      lng: -80.8987,
      dogPolicy: "Dogs allowed only in parking areas, campgrounds, and on the main park road. Not permitted on trails, in waterways, or in the backcountry.",
      dogTrails: [],
      restrictions: ["No dogs on any trails", "Not allowed in waterways", "No backcountry access", "Must be on 6-foot leash", "Beware of alligators and crocodiles"],
      description: "The vast River of Grass sprawls across southern Florida with mangrove estuaries, sawgrass prairies, and an astonishing array of wildlife including alligators and manatees. While dog access is very limited, the scenic drives offer unforgettable glimpses into this unique ecosystem.",
      imageUrl: "",
      website: "https://www.nps.gov/ever",
    },
    {
      name: "Biscayne National Park",
      state: "Florida",
      lat: 25.4824,
      lng: -80.2100,
      dogPolicy: "Dogs allowed on the mainland area at Convoy Point on a leash. Not permitted on islands, boats, or in the water.",
      dogTrails: ["Convoy Point Jetty Walk", "Dante Fascell Visitor Center Grounds"],
      restrictions: ["Leash required at all times", "Not allowed on islands", "Not allowed on boats", "No swimming with dogs", "Limited to Convoy Point area"],
      description: "Ninety-five percent underwater, Biscayne National Park protects a stunning stretch of coral reefs and mangrove coastline south of Miami. Dogs can only visit the Convoy Point mainland area, but the visitor center offers beautiful bay views.",
      imageUrl: "",
      website: "https://www.nps.gov/bisc",
    },
  ],
  restaurants: [
    {
      name: "Louie's Backyard",
      address: "700 Waddell Ave, Key West, FL 33040",
      lat: 24.5483,
      lng: -81.7932,
      cuisine: "Caribbean-American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the lower outdoor deck with ocean views. One of Key West's most iconic dining spots.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.louiesbackyard.com",
    },
    {
      name: "Santiago's Bodega",
      address: "207 Petronia St, Key West, FL 33040",
      lat: 24.5580,
      lng: -81.8000,
      cuisine: "Tapas & Global Small Plates",
      priceRange: "$$" as const,
      dogPolicy: "Charming garden patio is dog-friendly. Shareable tapas and an extensive wine list in Bahama Village.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.santiagosbodega.com",
    },
    {
      name: "Blue Heaven",
      address: "729 Thomas St, Key West, FL 33040",
      lat: 24.5554,
      lng: -81.7999,
      cuisine: "Caribbean Brunch",
      priceRange: "$$" as const,
      dogPolicy: "Famous open-air restaurant where cats and chickens roam. Dogs welcome in the outdoor dining area, fitting right in with the menagerie.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.blueheavenkw.com",
    },
    {
      name: "Garbo's Grill",
      address: "409 Caroline St, Key West, FL 33040",
      lat: 24.5587,
      lng: -81.8015,
      cuisine: "Fusion Tacos & Street Food",
      priceRange: "$" as const,
      dogPolicy: "Outdoor-only food stand with picnic seating. Dogs welcome everywhere. Korean BBQ tacos are legendary.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.garbosgrill.com",
    },
    {
      name: "Latitudes on Sunset Key",
      address: "245 Front St, Key West, FL 33040",
      lat: 24.5594,
      lng: -81.8098,
      cuisine: "Upscale Coastal",
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome on the beachfront terrace during lunch hours. Arrive by complimentary boat launch from the Westin Marina.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.sunsetkeycottages.com/latitudes",
    },
    {
      name: "DJ's Clam Shack",
      address: "629 Duval St, Key West, FL 33040",
      lat: 24.5568,
      lng: -81.7993,
      cuisine: "Seafood Shack",
      priceRange: "$" as const,
      dogPolicy: "Casual walk-up window with outdoor seating where dogs hang out. Fresh clam strips and lobster rolls on Duval.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.djsclamshack.com",
    },
    {
      name: "Hogfish Bar & Grill",
      address: "6810 Front St, Key West, FL 33040",
      lat: 24.5704,
      lng: -81.7415,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Waterfront seafood spot on Stock Island where dogs lounge under the tables. Famous for the hogfish sandwich.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hogfishbar.com",
    },
    {
      name: "Bien",
      address: "900 Catherine St, Key West, FL 33040",
      lat: 24.5540,
      lng: -81.7972,
      cuisine: "Modern Latin",
      priceRange: "$$$" as const,
      dogPolicy: "Tropical courtyard dining area welcomes dogs. Creative cocktails and vibrant Latin-inspired dishes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bienkeywest.com",
    },
  ],
  cafes: [
    {
      name: "Cuban Coffee Queen",
      address: "284 Margaret St, Key West, FL 33040",
      lat: 24.5586,
      lng: -81.8030,
      dogPolicy: "Open-air walk-up window with picnic tables in a tropical garden. Dogs welcome and café con leche is unmissable.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.cubancoffeequeen.com",
    },
    {
      name: "Sippin' Internet Cafe",
      address: "424 Eaton St, Key West, FL 33040",
      lat: 24.5578,
      lng: -81.8009,
      dogPolicy: "Quiet side-street café with a courtyard that welcomes dogs. Smoothies, coffee, and a cool escape from the sun.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.sippinkeywest.com",
    },
    {
      name: "Coffee Plantation",
      address: "713 Caroline St, Key West, FL 33040",
      lat: 24.5569,
      lng: -81.8026,
      dogPolicy: "Shaded garden patio is a dog-friendly hideaway off Caroline Street. Fresh-roasted beans and homemade baked goods.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.coffeeplantationkeywest.com",
    },
    {
      name: "Old Town Bakery",
      address: "930 Eaton St, Key West, FL 33040",
      lat: 24.5566,
      lng: -81.7952,
      dogPolicy: "Locals' favorite bakery with outdoor tables where dogs are always welcome. Pastries, sandwiches, and strong coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.oldtownbakerykw.com",
    },
    {
      name: "Glazed Donuts Key West",
      address: "420 Eaton St, Key West, FL 33040",
      lat: 24.5579,
      lng: -81.8008,
      dogPolicy: "Grab an artisan donut and enjoy it at the outdoor tables with your pup. Dog-friendly and irresistibly sweet.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.glazeddonuts.com",
    },
  ],
  dogParks: [
    {
      name: "Higgs Beach Dog Park",
      address: "1000 Atlantic Blvd, Key West, FL 33040",
      lat: 24.5480,
      lng: -81.7900,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Beach-adjacent", "Water fountains", "Shade structures", "Waste bag stations", "Benches"],
      rating: 4.5,
      imageUrl: "",
      description: "Steps from the ocean at Higgs Beach, this fenced dog park lets pups play off-leash with the sound of waves as a soundtrack. After park time, the adjacent beach has a dog-friendly stretch where your pup can splash in the warm Atlantic.",
    },
    {
      name: "Wicker Dog Park at Bayview Park",
      address: "1320 Truman Ave, Key West, FL 33040",
      lat: 24.5556,
      lng: -81.7874,
      offLeash: true,
      fenced: true,
      acres: 0.75,
      amenities: ["Separate small dog area", "Water fountains", "Shade trees", "Benches", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      description: "A well-maintained community dog park at Bayview Park with separate areas for large and small dogs. Surrounded by tropical trees, it offers a shady respite and a social hub for local dog owners.",
    },
    {
      name: "Dog Beach",
      address: "Vernon Ave & Waddell Ave, Key West, FL 33040",
      lat: 24.5470,
      lng: -81.7945,
      offLeash: true,
      fenced: false,
      acres: 0.5,
      amenities: ["Sand beach", "Ocean swimming", "Natural shade", "Free parking nearby", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "The only official off-leash dog beach on the island, this small but beloved sandy stretch lets dogs swim in the warm turquoise waters of the Atlantic. Watching dogs barrel into the gentle surf at sunset is pure Key West magic.",
    },
    {
      name: "Fort Zachary Taylor State Park (Dog Area)",
      address: "601 Howard England Way, Key West, FL 33040",
      lat: 24.5457,
      lng: -81.8094,
      offLeash: false,
      fenced: false,
      acres: 54,
      amenities: ["Nature trails", "Beach views", "Restrooms", "Picnic areas", "Historic fort"],
      rating: 4.4,
      imageUrl: "",
      description: "While dogs must stay on-leash, Fort Zachary Taylor offers stunning coastal trails through tropical hardwood hammock with views of the harbor and open ocean. The park's natural beauty and Civil War-era fort make it a memorable outing.",
    },
    {
      name: "Smathers Beach Dog-Friendly Section",
      address: "2601 S Roosevelt Blvd, Key West, FL 33040",
      lat: 24.5462,
      lng: -81.7723,
      offLeash: false,
      fenced: false,
      acres: 2,
      amenities: ["Sandy beach", "Calm waters", "Palm tree shade", "Free parking", "Waste bag stations"],
      rating: 4.2,
      imageUrl: "",
      description: "Key West's longest beach has a dog-friendly section where leashed pups can enjoy the sand and shallow warm water. Early mornings are best when the beach is quiet and the sunrise paints the sky in tropical pastels.",
    },
  ],
};
