export const knoxvilleData = {
  city: {
    name: "Knoxville",
    state: "Tennessee",
    region: "Southeast",
    lat: 35.9606,
    lng: -83.9207,
    dogFriendlinessScore: 7,
    description:
      "Nestled at the gateway to the Great Smoky Mountains, Knoxville offers dogs a perfect blend of urban patios and mountain adventure. The city's vibrant Market Square, scenic greenways along the Tennessee River, and proximity to world-class hiking make it a top pick for dog-loving travelers.",
    heroImage: "https://images.unsplash.com/photo-1558349699-1e1c40c08c70?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 190740,
  },
  hotels: [
    {
      name: "The Oliver Hotel",
      address: "407 Union Ave, Knoxville, TN 37902",
      lat: 35.9657,
      lng: -83.9188,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome with a one-time pet fee. A boutique hotel in a beautifully restored 1876 building in downtown Knoxville.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking route map", "Waste bags"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.theoliverhotel.com",
      phone: "(865) 521-0050",
    },
    {
      name: "Hilton Knoxville",
      address: "501 W Church Ave, Knoxville, TN 37902",
      lat: 35.9660,
      lng: -83.9230,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a nightly fee. Downtown location with easy access to Market Square.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Pet-friendly rooms", "Water bowls", "Waste bags", "Nearby walking areas"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com/en/hotels/tysknhf",
      phone: "(865) 523-2300",
    },
    {
      name: "Graduate Knoxville",
      address: "1706 Cumberland Ave, Knoxville, TN 37916",
      lat: 35.9560,
      lng: -83.9350,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome with a pet fee. A playful UT-themed hotel on the Cumberland Strip near campus.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Treats", "Waste bags", "Walking suggestions"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.graduatehotels.com/knoxville",
      phone: "(865) 544-2721",
    },
    {
      name: "The Tennessean Hotel",
      address: "531 Henley St, Knoxville, TN 37902",
      lat: 35.9620,
      lng: -83.9210,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a non-refundable pet fee. Luxury hotel steps from the World's Fair Park.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Plush dog bed", "Water and food bowls", "Welcome treats", "Concierge pet services", "Walking map"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thetennesseanhotel.com",
      phone: "(865) 232-1800",
    },
  ],
  nationalParks: [
    {
      name: "Great Smoky Mountains National Park",
      state: "Tennessee",
      lat: 35.6118,
      lng: -83.4895,
      dogPolicy: "Dogs are only permitted on two trails and in parking areas, campgrounds, and along roads. They must be on a 6-foot leash at all times.",
      dogTrails: ["Gatlinburg Trail", "Oconaluftee River Trail"],
      restrictions: ["Dogs only on two trails", "6-foot leash required", "Not allowed on other hiking trails", "No dogs in backcountry", "No dogs in public buildings"],
      description: "America's most-visited national park is just 45 minutes from Knoxville, with misty mountain peaks and old-growth forest. While dog access is very limited, the two permitted trails offer gentle riverside walks through stunning scenery.",
      imageUrl: "",
      website: "https://www.nps.gov/grsm",
    },
    {
      name: "Big South Fork National River and Recreation Area",
      state: "Tennessee",
      lat: 36.4870,
      lng: -84.6970,
      dogPolicy: "Dogs welcome on all trails on a 6-foot leash. A lesser-known gem with dramatic gorges and river bluffs.",
      dogTrails: ["Angel Falls Trail", "Twin Arches Trail", "Blue Heron Loop", "Oscar Blevins Loop"],
      restrictions: ["6-foot leash required", "Not allowed in buildings", "Must clean up after pet"],
      description: "About ninety minutes northwest of Knoxville, Big South Fork protects spectacular gorges, natural arches, and river scenery. Dogs have much more trail access here than in the Smokies, making it ideal for adventurous pups.",
      imageUrl: "",
      website: "https://www.nps.gov/biso",
    },
    {
      name: "Ijams Nature Center",
      state: "Tennessee",
      lat: 35.9510,
      lng: -83.8730,
      dogPolicy: "Dogs welcome on all trails on a leash. A beloved Knoxville nature preserve with quarries, caves, and river access.",
      dogTrails: ["Mead's Quarry Loop", "River Trail", "Will Skelton Greenway", "Keyhole Trail"],
      restrictions: ["Leash required at all times", "Not allowed in buildings", "No swimming with dogs", "Must clean up after pet"],
      description: "Just minutes from downtown Knoxville, Ijams offers over 315 acres of forests, wetlands, and the stunning turquoise waters of Mead's Quarry. Dogs love the variety of trails from easy riverside walks to rugged woodland paths.",
      imageUrl: "",
      website: "https://www.ijams.org",
    },
  ],
  restaurants: [
    {
      name: "Stock & Barrel",
      address: "35 Market Square, Knoxville, TN 37902",
      lat: 35.9660,
      lng: -83.9195,
      cuisine: "Burgers & Craft Cocktails",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the Market Square patio. Creative burgers and bourbon cocktails in the heart of downtown.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.stockandbarrelknoxville.com",
    },
    {
      name: "Balter Beerworks",
      address: "100 S Broadway St, Knoxville, TN 37902",
      lat: 35.9640,
      lng: -83.9200,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the large outdoor patio. A popular downtown brewery with creative food and house-brewed beers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.balterbeerworks.com",
    },
    {
      name: "Tupelo Honey",
      address: "1 Market Square, Knoxville, TN 37902",
      lat: 35.9665,
      lng: -83.9190,
      cuisine: "Southern",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio overlooking Market Square. Scratch-made Southern cuisine with creative twists.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tupelohoneycafe.com",
    },
    {
      name: "Sweet P's BBQ & Soul House",
      address: "3725 Maryville Pike, Knoxville, TN 37920",
      lat: 35.9260,
      lng: -83.9160,
      cuisine: "Barbecue & Soul Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor picnic tables. Award-winning BBQ and Southern sides in a converted garage.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sweetpbbq.com",
    },
    {
      name: "Landing House",
      address: "911 N Central St, Knoxville, TN 37917",
      lat: 35.9730,
      lng: -83.9230,
      cuisine: "Asian Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio. A creative Asian-inspired menu in the Happy Holler neighborhood.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thelandinghouse.com",
    },
  ],
  cafes: [
    {
      name: "Old City Java",
      address: "109 S Central St, Knoxville, TN 37902",
      lat: 35.9680,
      lng: -83.9165,
      dogPolicy: "Dogs welcome on the outdoor patio in the heart of the Old City. A community coffeehouse with live music and local art.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.oldcityjava.com",
    },
    {
      name: "K Brew",
      address: "800 Tyson St, Knoxville, TN 37917",
      lat: 35.9710,
      lng: -83.9190,
      dogPolicy: "Dogs welcome at outdoor seating. A modern Knoxville roaster focusing on single-origin coffees and clean design.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.kbrewcoffee.com",
    },
    {
      name: "Honeybee Coffee",
      address: "119 S Central St, Knoxville, TN 37902",
      lat: 35.9675,
      lng: -83.9165,
      dogPolicy: "Dog-friendly outdoor tables on the sidewalk. A cozy Old City cafe with fresh pastries and specialty lattes.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.honeybeecoffee.com",
    },
    {
      name: "Wild Love Bakehouse",
      address: "1625 N Central St, Knoxville, TN 37917",
      lat: 35.9800,
      lng: -83.9230,
      dogPolicy: "Dogs welcome on the patio. Artisan sourdough bakery with excellent coffee and seasonal pastries in Happy Holler.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.wildlovebakehouse.com",
    },
  ],
  dogParks: [
    {
      name: "PetSafe Dog Park at Tommy Schumpert Park",
      address: "6518 Schaad Rd, Knoxville, TN 37921",
      lat: 35.9860,
      lng: -84.0050,
      offLeash: true,
      fenced: true,
      acres: 6,
      amenities: ["Separate small dog area", "Water stations", "Agility equipment", "Shade structures", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "One of Knoxville's best dog parks with PetSafe sponsorship providing excellent amenities. Six acres of fenced off-leash space include agility equipment, separate areas for large and small dogs, and plenty of shade.",
    },
    {
      name: "Concord Dog Park",
      address: "11808 S Northshore Dr, Knoxville, TN 37922",
      lat: 35.8860,
      lng: -84.0990,
      offLeash: true,
      fenced: true,
      acres: 4,
      amenities: ["Separate small dog area", "Water fountains", "Benches", "Open fields", "Paved paths"],
      rating: 4.4,
      imageUrl: "",
      description: "A well-maintained dog park in west Knoxville's Concord Park, offering both large and small dog areas with lake-area breezes. The surrounding park provides additional on-leash trails for longer walks.",
    },
    {
      name: "Lakeshore Park Dog Park",
      address: "5908 Lyons View Pike, Knoxville, TN 37919",
      lat: 35.9360,
      lng: -83.9640,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Double-gated entry", "Water stations", "Benches", "Shade trees", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      description: "Located within the beautifully redeveloped Lakeshore Park, this dog park offers off-leash fun with views of the Tennessee River. The surrounding park has paved greenways perfect for post-play strolls.",
    },
    {
      name: "Plumb Creek Dog Park",
      address: "1531 Plumb Creek Dr, Knoxville, TN 37932",
      lat: 35.9470,
      lng: -84.0800,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Benches", "Water spigot", "Shade structures", "Waste bag stations"],
      rating: 4.1,
      imageUrl: "",
      description: "A convenient neighborhood dog park in west Knoxville with separate areas for large and small dogs. The well-maintained fencing and ample shade make it a reliable spot for everyday off-leash play.",
    },
  ],
};
