export const lagunaBeachData = {
  city: {
    name: "Laguna Beach",
    state: "California",
    region: "West Coast",
    lat: 33.5427,
    lng: -117.7854,
    dogFriendlinessScore: 7,
    description:
      "This artistic coastal enclave in Orange County combines stunning ocean coves, world-class galleries, and a surprisingly dog-friendly culture. With designated dog beaches, canyon hiking trails, and charming downtown patios, Laguna Beach is a beautiful destination for dogs and art-loving owners.",
    heroImage: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 23032,
  },
  hotels: [
    {
      name: "The Ranch at Laguna Beach",
      address: "31106 S Coast Hwy, Laguna Beach, CA 92651",
      lat: 33.5200,
      lng: -117.7620,
      priceRange: "$$$$" as const,
      dogPolicy: "Canyon resort welcoming dogs under 60 lbs in designated rooms. Surrounded by Aliso Creek canyon with nature trails.",
      maxDogWeight: 60,
      petFee: 150,
      amenities: ["Dog bed", "Treats", "Canyon trails", "Dog walking service", "Water bowls"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.theranchlb.com",
      phone: "(949) 499-2271",
    },
    {
      name: "Laguna Beach House",
      address: "475 N Coast Hwy, Laguna Beach, CA 92651",
      lat: 33.5480,
      lng: -117.7870,
      priceRange: "$$$" as const,
      dogPolicy: "Surf-inspired boutique hotel near the village with pet-friendly rooms. Dogs welcome with beach access nearby.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Beach proximity", "Cruiser bikes", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.lagunabeachhouse.com",
      phone: "(949) 497-6645",
    },
    {
      name: "Holiday Inn Laguna Beach",
      address: "696 S Coast Hwy, Laguna Beach, CA 92651",
      lat: 33.5360,
      lng: -117.7800,
      priceRange: "$$" as const,
      dogPolicy: "Oceanview hotel with pet-friendly rooms and walkable beach access. Dogs under 50 lbs welcome in designated rooms.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Pet-friendly rooms", "Ocean views", "Pool", "Beach access", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(949) 494-1001",
    },
    {
      name: "La Casa del Camino",
      address: "1289 S Coast Hwy, Laguna Beach, CA 92651",
      lat: 33.5300,
      lng: -117.7760,
      priceRange: "$$$" as const,
      dogPolicy: "Historic Spanish-style hotel with pet-friendly rooms and rooftop bar ocean views. Dogs welcome with a one-time fee.",
      maxDogWeight: 40,
      petFee: 100,
      amenities: ["Rooftop bar", "Ocean views", "Dog bed", "Water bowls", "Historic charm"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.lacasadelcamino.com",
      phone: "(949) 497-2446",
    },
  ],
  nationalParks: [
    {
      name: "Laguna Coast Wilderness Park",
      state: "California",
      lat: 33.5400,
      lng: -117.7500,
      dogPolicy: "Dogs NOT allowed in the wilderness park to protect sensitive coastal sage scrub habitat. Alternative dog-friendly trails available nearby.",
      dogTrails: [],
      restrictions: ["No dogs allowed", "Sensitive habitat protection", "Check Laguna Canyon Foundation for alternatives"],
      description: "While this 7,000-acre wilderness park does not allow dogs, it's worth noting for planning purposes. Dog owners should head to Aliso and Wood Canyons or Top of the World instead for canyon hiking with their pups.",
      imageUrl: "",
      website: "https://www.lagunacanyon.org",
    },
    {
      name: "Aliso and Wood Canyons Wilderness Park",
      state: "California",
      lat: 33.5200,
      lng: -117.7400,
      dogPolicy: "Dogs welcome on all trails on a leash. Over 30 miles of trails through coastal canyon terrain with ocean views.",
      dogTrails: ["Wood Canyon Trail", "Lynx Trail", "Cholla Trail", "Aliso Creek Trail"],
      restrictions: ["6-foot leash required", "Pack out waste", "Stay on designated trails", "Carry water on warm days"],
      description: "This expansive wilderness park offers over 30 miles of dog-friendly trails through canyons, ridgelines, and coastal sage scrub. Dogs and their owners can hike from the canyon floor to ridgetop ocean views in a single outing.",
      imageUrl: "",
      website: "https://www.ocparks.com/aliso-wood-canyons",
    },
    {
      name: "Crystal Cove State Park",
      state: "California",
      lat: 33.5700,
      lng: -117.8100,
      dogPolicy: "Dogs allowed on the paved multi-use trail in the inland section on leash. Not allowed on the beach or coastal trails.",
      dogTrails: ["Moro Ridge Fire Road (inland portion)", "No Dogs Canyon alternate route"],
      restrictions: ["Not allowed on beaches", "Not allowed on coastal trails", "Leash required on inland trails", "Day use fee required"],
      description: "While beach access is restricted for dogs, the inland portion of Crystal Cove offers rolling hills and canyon trails through coastal sage scrub. The elevated trails provide ocean views from a distance.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/crystalcove",
    },
  ],
  restaurants: [
    {
      name: "The Deck on Laguna Beach",
      address: "627 Sleepy Hollow Ln, Laguna Beach, CA 92651",
      lat: 33.5350,
      lng: -117.7810,
      cuisine: "Seafood & American",
      priceRange: "$$$" as const,
      dogPolicy: "Oceanfront restaurant with a stunning deck patio welcoming dogs. Fresh seafood with panoramic Pacific views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thedeckonlagunabeach.com",
    },
    {
      name: "Driftwood Kitchen",
      address: "619 Sleepy Hollow Ln, Laguna Beach, CA 92651",
      lat: 33.5355,
      lng: -117.7815,
      cuisine: "Coastal American",
      priceRange: "$$$$" as const,
      dogPolicy: "Upscale oceanfront dining with a terrace patio where well-behaved dogs are welcome. Sustainable seafood and ocean views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.driftwoodkitchen.com",
    },
    {
      name: "Nick's Laguna Beach",
      address: "440 S Coast Hwy, Laguna Beach, CA 92651",
      lat: 33.5390,
      lng: -117.7830,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Vibrant restaurant with a spacious sidewalk patio on Coast Highway where dogs are welcome. Burgers, salads, and craft cocktails.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.nickslagunabeach.com",
    },
    {
      name: "Urth Caffé Laguna Beach",
      address: "308 N Coast Hwy, Laguna Beach, CA 92651",
      lat: 33.5450,
      lng: -117.7860,
      cuisine: "Organic Café",
      priceRange: "$$" as const,
      dogPolicy: "Organic café with a large dog-friendly patio near Main Beach. Famous for their boba teas and organic espresso drinks.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.urthcaffe.com",
    },
    {
      name: "Taco Loco",
      address: "640 S Coast Hwy, Laguna Beach, CA 92651",
      lat: 33.5370,
      lng: -117.7800,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Beloved local taco shop with an outdoor patio where dogs are always welcome. Fish tacos and margaritas steps from the beach.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.tacoloco.net",
    },
  ],
  cafes: [
    {
      name: "The Coffee Gallery",
      address: "218 Beach St, Laguna Beach, CA 92651",
      lat: 33.5430,
      lng: -117.7855,
      dogPolicy: "Local favorite with a sunny patio and art-filled walls. Dogs welcome outside with treats available at the counter.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.coffeegallerylb.com",
    },
    {
      name: "Kéan Coffee",
      address: "971 S Coast Hwy, Laguna Beach, CA 92651",
      lat: 33.5320,
      lng: -117.7780,
      dogPolicy: "Premium Orange County roaster with a patio where dogs are welcome. Specialty espresso drinks and single-origin pour-overs.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.keancoffee.com",
    },
    {
      name: "The Stand Natural Foods",
      address: "238 Thalia St, Laguna Beach, CA 92651",
      lat: 33.5435,
      lng: -117.7850,
      dogPolicy: "Health-focused café with a patio near downtown. Dogs welcome while you enjoy acai bowls and fresh juices.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.thestandnaturalfoods.com",
    },
    {
      name: "Laguna Coffee Company",
      address: "510 N Coast Hwy, Laguna Beach, CA 92651",
      lat: 33.5490,
      lng: -117.7875,
      dogPolicy: "Cozy neighborhood café with outdoor seating and a friendly vibe. Dogs welcome on the patio with water bowls provided.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.lagunacoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Laguna Beach Dog Park",
      address: "20612 Laguna Canyon Rd, Laguna Beach, CA 92651",
      lat: 33.5460,
      lng: -117.7600,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Separate small dog area", "Water stations", "Shade structures", "Agility equipment", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "The city's dedicated off-leash dog park in Laguna Canyon with separate areas for large and small dogs. Agility equipment and shade structures make it a well-equipped spot for dog socialization and exercise.",
    },
    {
      name: "Top of the World",
      address: "Alta Laguna Blvd, Laguna Beach, CA 92651",
      lat: 33.5300,
      lng: -117.7600,
      offLeash: false,
      fenced: false,
      acres: 20,
      amenities: ["Panoramic views", "Hiking trails", "Benches", "Parking", "Waste bag stations"],
      rating: 4.7,
      imageUrl: "",
      description: "One of the most scenic viewpoints in Orange County, Top of the World offers 360-degree views from the Pacific to the mountains. Leashed dogs can hike the trails leading to this stunning overlook above Laguna Beach.",
    },
    {
      name: "Dog Beach at Divers Cove",
      address: "Coast Hwy & Cliff Dr, Laguna Beach, CA 92651",
      lat: 33.5500,
      lng: -117.7900,
      offLeash: false,
      fenced: false,
      acres: 1,
      amenities: ["Beach access", "Ocean views", "Rocky cove", "Parking nearby"],
      rating: 4.3,
      imageUrl: "",
      description: "Laguna Beach allows leashed dogs on certain beaches during early morning and evening hours. Divers Cove offers a scenic rocky cove where dogs can explore the tide pools and enjoy the ocean breeze.",
    },
    {
      name: "Aliso Creek Trail",
      address: "Aliso Creek Rd, Laguna Beach, CA 92651",
      lat: 33.5250,
      lng: -117.7500,
      offLeash: false,
      fenced: false,
      acres: 15,
      amenities: ["Paved trail", "Creek access", "Shade trees", "Benches", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "A paved multi-use trail following Aliso Creek from the canyon to the beach. Leashed dogs enjoy the shaded creek-side walk with opportunities to wade in shallow water along the way.",
    },
  ],
};
