export const lakeTahoeData = {
  city: {
    name: "Lake Tahoe",
    state: "California",
    region: "West Coast",
    lat: 39.0968,
    lng: -120.0324,
    dogFriendlinessScore: 8,
    description:
      "Straddling the California-Nevada border at 6,225 feet, Lake Tahoe is a year-round paradise for dogs and their owners. Crystal-clear alpine water, miles of forested trails, and a thriving outdoor culture mean your pup will have endless opportunities to hike, swim, and play. The surrounding communities embrace pet-friendly dining, lodging, and recreation.",
    heroImage: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=1200&fit=crop",
    climate: "Alpine Mediterranean",
    population: 21403,
  },
  hotels: [
    {
      name: "The Landing Resort & Spa",
      address: "4104 Lakeshore Blvd, South Lake Tahoe, CA 96150",
      lat: 38.9547,
      lng: -119.9711,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a luxury pet package including bed, bowls, and treats.",
      maxDogWeight: 0,
      petFee: 100,
      amenities: ["Luxury dog bed", "Gourmet treats", "Lake access", "Dog-walking service"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.thelandingtahoe.com/",
      phone: "(530) 541-5263",
    },
    {
      name: "Basecamp Tahoe South",
      address: "4143 Cedar Ave, South Lake Tahoe, CA 96150",
      lat: 38.9545,
      lng: -119.9726,
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly boutique hotel. Dogs welcome in all rooms with no size restrictions.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Dog bed", "Treats at check-in", "Outdoor fire pit", "Walking trails nearby"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.basecamphotels.com/tahoe-south",
      phone: "(530) 208-0180",
    },
    {
      name: "The Coachman Hotel",
      address: "4100 Pine Blvd, South Lake Tahoe, CA 96150",
      lat: 38.9560,
      lng: -119.9735,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a one-time fee. Walking distance to the lake.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bowls", "Outdoor lounge", "S'mores fire pit", "Bike rentals"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.coachmantahoe.com/",
      phone: "(530) 545-6460",
    },
    {
      name: "PlumpJack Inn",
      address: "1920 Squaw Valley Rd, Olympic Valley, CA 96146",
      lat: 39.1965,
      lng: -120.2355,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in designated rooms at this slopeside retreat. Mountain setting with trail access.",
      maxDogWeight: 60,
      petFee: 75,
      amenities: ["Dog bed", "Food bowls", "Trail access", "Mountain views"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.plumpjacksquawvalleyinn.com/",
      phone: "(530) 583-1576",
    },
    {
      name: "Cedar Crest Cottages",
      address: "6549 N Lake Blvd, Tahoe Vista, CA 96148",
      lat: 39.2397,
      lng: -120.0546,
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly cottages with private yards. Perfect for dogs who love space to roam.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Private yard", "Dog bowls", "Beach access nearby", "BBQ grill"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.cedarcresttahoe.com/",
      phone: "(530) 546-4239",
    },
  ],
  nationalParks: [
    {
      name: "Desolation Wilderness",
      state: "California",
      lat: 38.9500,
      lng: -120.1500,
      dogPolicy: "Dogs allowed on trails when leashed. Permit required for day and overnight use.",
      dogTrails: [
        "Glen Alpine Trail",
        "Eagle Falls to Eagle Lake",
        "Bayview Trail to Granite Lake",
        "Lyons Creek Trail",
      ],
      restrictions: [
        "Wilderness permit required",
        "Dogs must be on leash at all times",
        "Pack out all waste",
        "Not recommended during heavy snow seasons without preparation",
      ],
      description:
        "A pristine 63,960-acre wilderness of granite peaks, alpine lakes, and subalpine forests just west of Lake Tahoe. Crystal-clear lakes and wildflower meadows reward hikers and their dogs on rugged mountain trails.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/recarea/eldorado/recarea/?recid=71002",
    },
    {
      name: "D.L. Bliss State Park",
      state: "California",
      lat: 38.9791,
      lng: -120.1024,
      dogPolicy: "Dogs allowed on paved roads and in campsites but not on trails or beaches.",
      dogTrails: ["Paved park roads only"],
      restrictions: [
        "Dogs NOT allowed on any trails",
        "Dogs NOT allowed on beaches",
        "Must be on leash at all times in campground",
        "Not permitted in buildings",
      ],
      description:
        "Home to some of Tahoe's most beautiful shoreline, including the famous Rubicon Trail. While trail access is restricted for dogs, the campground and paved roads still offer stunning lake views and a convenient base camp.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/?page_id=505",
    },
    {
      name: "Tahoe National Forest",
      state: "California",
      lat: 39.3236,
      lng: -120.2892,
      dogPolicy: "Dogs welcome on all trails when leashed or under voice control. One of the most dog-friendly national forests in the region.",
      dogTrails: [
        "Pacific Crest Trail segments",
        "Five Lakes Trail",
        "Loch Leven Lakes Trail",
        "Donner Lake Rim Trail",
        "Castle Peak Trail",
      ],
      restrictions: [
        "Leash required in developed recreation areas",
        "Voice control acceptable on most trails",
        "Clean up after your dog",
        "Check seasonal fire restrictions",
      ],
      description:
        "Over 800,000 acres of Sierra Nevada forest encompassing everything from rushing rivers and granite peaks to wildflower meadows. This vast national forest offers some of the best dog-friendly hiking in the Tahoe region.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/tahoe",
    },
    {
      name: "Emerald Bay State Park",
      state: "California",
      lat: 38.9532,
      lng: -120.1103,
      dogPolicy: "Dogs allowed in campgrounds and on paved roads only. Not permitted on trails or at Vikingsholm.",
      dogTrails: ["Paved roads and campground areas only"],
      restrictions: [
        "Dogs NOT allowed on any trails including Vikingsholm Trail",
        "Not permitted on beaches",
        "Must be on leash in campground",
        "Not allowed at Vikingsholm Castle",
      ],
      description:
        "One of the most photographed spots in North America, Emerald Bay features a stunning alpine lake within a lake, the historic Vikingsholm castle, and towering granite cliffs. Limited dog access but the views from the road are magnificent.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/?page_id=506",
    },
  ],
  restaurants: [
    {
      name: "Sidellis Lake Tahoe",
      address: "3350 Sandy Way, South Lake Tahoe, CA 96150",
      lat: 38.9399,
      lng: -119.9838,
      cuisine: "Brewery & Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly brewery with a large heated outdoor patio.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.sidellis.com/",
    },
    {
      name: "Sprouts Natural Cafe",
      address: "3123 Harrison Ave, South Lake Tahoe, CA 96150",
      lat: 38.9413,
      lng: -119.9823,
      cuisine: "Healthy & Organic",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the sunny patio. Organic and health-conscious menu.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sproutscafetahoe.com/",
    },
    {
      name: "The Red Hut Cafe",
      address: "2723 Lake Tahoe Blvd, South Lake Tahoe, CA 96150",
      lat: 38.9370,
      lng: -119.9779,
      cuisine: "Breakfast & Brunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs allowed at the outdoor picnic tables. Classic Tahoe breakfast spot.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.redhutcafe.com/",
    },
    {
      name: "Driftwood Cafe",
      address: "4118 Lake Tahoe Blvd, South Lake Tahoe, CA 96150",
      lat: 38.9555,
      lng: -119.9730,
      cuisine: "American Comfort",
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly outdoor seating with mountain views.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.driftwoodcafe.com/",
    },
    {
      name: "Cold Water Brewery & Grill",
      address: "2544 Lake Tahoe Blvd, South Lake Tahoe, CA 96150",
      lat: 38.9353,
      lng: -119.9738,
      cuisine: "Brewery & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor deck. Craft beer and hearty food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.coldwaterbrewery.com/",
    },
    {
      name: "Gar Woods Grill & Pier",
      address: "5000 N Lake Blvd, Carnelian Bay, CA 96140",
      lat: 39.2308,
      lng: -120.0780,
      cuisine: "Lakefront American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the lakefront patio deck. Stunning sunset views over the water.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.garwoods.com/",
    },
    {
      name: "Artemis Lakefront Cafe",
      address: "900 Ski Run Blvd, South Lake Tahoe, CA 96150",
      lat: 38.9371,
      lng: -119.9585,
      cuisine: "Mediterranean",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.artemislakefrontcafe.com/",
    },
    {
      name: "Base Camp Pizza Co.",
      address: "4000 Lake Tahoe Blvd, South Lake Tahoe, CA 96150",
      lat: 38.9552,
      lng: -119.9733,
      cuisine: "Pizza & Craft Beer",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly outdoor patio with a fun mountain-lodge vibe.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.basecamppizzaco.com/",
    },
  ],
  cafes: [
    {
      name: "Alpen Sierra Coffee Roasting Company",
      address: "4117 Lake Tahoe Blvd, South Lake Tahoe, CA 96150",
      lat: 38.9555,
      lng: -119.9728,
      dogPolicy: "Dogs welcome on the outdoor patio. Locally roasted coffee and fresh pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.alpensierra.com/",
    },
    {
      name: "Drink Coffee Bar",
      address: "4000 Lake Tahoe Blvd #24, South Lake Tahoe, CA 96150",
      lat: 38.9553,
      lng: -119.9732,
      dogPolicy: "Pet-friendly cafe with shaded outdoor seating.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.drinkcoffeebar.com/",
    },
    {
      name: "Camp Richardson's Mountain Coffee",
      address: "1900 Jameson Beach Rd, South Lake Tahoe, CA 96150",
      lat: 38.9382,
      lng: -120.0345,
      dogPolicy: "Lakeside coffee spot that welcomes dogs on the patio and nearby beach.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.camprichardson.com/",
    },
    {
      name: "Tahoe Art Haus & Cinema Cafe",
      address: "120 Country Club Dr, Tahoe City, CA 96145",
      lat: 39.1674,
      lng: -120.1432,
      dogPolicy: "Dogs welcome at outdoor tables before shows.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tahoearthauscinema.com/",
    },
    {
      name: "Firesign Cafe",
      address: "1785 W Lake Blvd, Tahoe City, CA 96145",
      lat: 39.1411,
      lng: -120.1577,
      dogPolicy: "Dog-friendly patio seating with lake views. Beloved local breakfast spot.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.firesigncafe.com/",
    },
  ],
  dogParks: [
    {
      name: "Kiva Beach",
      address: "Kiva Beach Rd, South Lake Tahoe, CA 96150",
      lat: 38.9334,
      lng: -120.0425,
      offLeash: true,
      fenced: false,
      acres: 5.0,
      amenities: ["Beach access", "Lake swimming", "Waste stations", "Parking lot", "Picnic tables"],
      rating: 4.8,
      imageUrl: "",
      description:
        "The most popular dog beach at Lake Tahoe, where dogs can run off-leash and splash in the crystal-clear alpine water. The sandy beach stretches along a gentle cove with stunning mountain views in every direction.",
    },
    {
      name: "Bijou Community Park Dog Park",
      address: "1201 Al Tahoe Blvd, South Lake Tahoe, CA 96150",
      lat: 38.9351,
      lng: -119.9690,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Separate small dog section", "Water fountains", "Benches", "Agility equipment"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A well-maintained fenced dog park within the larger Bijou Community Park. Features separate areas for large and small dogs, agility equipment, and water fountains. A reliable spot when you need a safe off-leash area.",
    },
    {
      name: "North Tahoe Regional Park Dog Area",
      address: "6600 Donner Rd, Tahoe Vista, CA 96148",
      lat: 39.2485,
      lng: -120.0595,
      offLeash: true,
      fenced: false,
      acres: 10.0,
      amenities: ["Forest trails", "Open meadows", "Disc golf course", "Waste stations", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A spacious park in the pines on Tahoe's north shore with designated off-leash areas through forested terrain and open meadows. Dogs love exploring the trails that wind through the tall Jeffrey pines.",
    },
    {
      name: "Regan Beach",
      address: "3199 Sacramento Ave, South Lake Tahoe, CA 96150",
      lat: 38.9430,
      lng: -119.9790,
      offLeash: true,
      fenced: false,
      acres: 3.0,
      amenities: ["Beach access", "Lake swimming", "Picnic area", "Walking paths"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A local favorite beach where dogs can play off-leash in the water and on the sand during certain seasons. Less crowded than Kiva Beach, with easy access from downtown South Lake Tahoe.",
    },
    {
      name: "Tahoe City Dog Park at Commons Beach",
      address: "400 N Lake Blvd, Tahoe City, CA 96145",
      lat: 39.1691,
      lng: -120.1408,
      offLeash: false,
      fenced: false,
      acres: 4.0,
      amenities: ["Lakefront access", "Grassy areas", "Picnic tables", "Public restrooms", "Walking path"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A scenic lakefront park in the heart of Tahoe City where leashed dogs can enjoy the grassy shoreline and watch boats on the lake. The adjacent walking path connects to the Truckee River bike trail.",
    },
  ],
};
