export const lasCrucesData = {
  city: {
    name: "Las Cruces",
    state: "New Mexico",
    region: "Southwest",
    lat: 32.3199,
    lng: -106.7637,
    dogFriendlinessScore: 7,
    description:
      "Las Cruces sits at the base of the striking Organ Mountains in southern New Mexico, offering dogs dramatic desert hiking and a warm, welcoming community. The mix of Chihuahuan Desert landscapes, farm-to-table dining, and affordable charm makes it an underrated gem for dog-loving travelers.",
    heroImage: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&fit=crop",
    climate: "Hot desert",
    population: 111385,
  },

  hotels: [
    {
      name: "Hotel Encanto de Las Cruces",
      address: "705 S Telshor Blvd, Las Cruces, NM 88011",
      lat: 32.3290,
      lng: -106.7430,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a pet fee. Full-service hotel with Southwest elegance.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Garden grounds", "Walking paths", "Near Organ Mountains"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hotelencanto.com",
      phone: "(575) 522-4300",
    },
    {
      name: "Hilton Garden Inn Las Cruces",
      address: "2550 S Don Roser Dr, Las Cruces, NM 88011",
      lat: 32.3180,
      lng: -106.7350,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a non-refundable pet fee. Modern hotel near NMSU campus.",
      maxDogWeight: 75,
      petFee: 40,
      amenities: ["Grassy area", "Near university", "Pool area", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(575) 532-0700",
    },
    {
      name: "La Quinta Inn Las Cruces Organ Mountains",
      address: "1500 Hickory Dr, Las Cruces, NM 88005",
      lat: 32.3250,
      lng: -106.7200,
      priceRange: "$" as const,
      dogPolicy: "All dogs welcome at no extra charge. Near Organ Mountains trailheads.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Near mountain trails", "Grassy area", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(575) 527-1010",
    },
    {
      name: "Lundeen Inn of the Arts",
      address: "618 S Alameda Blvd, Las Cruces, NM 88005",
      lat: 32.3370,
      lng: -106.7490,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select rooms with advance notice. Art-filled B&B in historic downtown.",
      maxDogWeight: 40,
      petFee: 25,
      amenities: ["Art collection", "Garden", "Historic district", "Walking distance to Mesilla"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.innofthearts.com",
      phone: "(575) 526-3326",
    },
  ],

  nationalParks: [
    {
      name: "Organ Mountains-Desert Peaks National Monument",
      state: "New Mexico",
      lat: 32.3170,
      lng: -106.5850,
      dogPolicy: "Leashed dogs welcome on most trails. Dramatic spire-like peaks rising from the desert floor.",
      dogTrails: ["Dripping Springs Trail", "Pine Tree Trail", "Baylor Pass Trail", "Aguirre Spring Loop"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Carry plenty of water",
        "Avoid midday summer hiking",
        "Watch for rattlesnakes",
      ],
      description:
        "The jagged Organ Mountains rise dramatically to nearly 9,000 feet directly east of Las Cruces. The trails through this national monument offer some of the most spectacular desert mountain hiking in the Southwest.",
      imageUrl: "",
      website: "https://www.blm.gov/visit/organ-mountains-desert-peaks",
    },
    {
      name: "White Sands National Park",
      state: "New Mexico",
      lat: 32.7872,
      lng: -106.3257,
      dogPolicy: "Leashed dogs allowed on the Dune Life Nature Trail and in picnic areas only.",
      dogTrails: ["Dune Life Nature Trail"],
      restrictions: [
        "Must be on a 6-foot leash at all times",
        "Not allowed on backcountry trails or Alkali Flat Trail",
        "Hot sand can burn paw pads",
        "Carry water",
      ],
      description:
        "About an hour from Las Cruces, White Sands features the world's largest gypsum dune field. While dog access is limited, the Dune Life Nature Trail lets your pup experience the surreal white landscape.",
      imageUrl: "",
      website: "https://www.nps.gov/whsa",
    },
    {
      name: "Mesilla Valley Bosque State Park",
      state: "New Mexico",
      lat: 32.2690,
      lng: -106.8090,
      dogPolicy: "Leashed dogs welcome on all trails. A Rio Grande bosque preserve south of Las Cruces.",
      dogTrails: ["Bosque Trail", "Wetland Loop", "River Overlook Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Stay on designated trails",
        "Do not disturb wildlife",
      ],
      description:
        "This state park preserves a stretch of Rio Grande cottonwood bosque south of Las Cruces. Dogs enjoy the shaded riverside trails, and the birding is spectacular during migration seasons.",
      imageUrl: "",
      website: "https://www.emnrd.nm.gov/spd/mesilla-valley-bosque",
    },
  ],

  restaurants: [
    {
      name: "Chala's Wood Fire Grill",
      address: "790 S Telshor Blvd, Las Cruces, NM 88011",
      lat: 32.3280,
      lng: -106.7420,
      cuisine: "Southwest Grill",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Wood-fired cuisine with New Mexican flair.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.chalasgrill.com",
    },
    {
      name: "Double Eagle Restaurant",
      address: "2355 Calle de Guadalupe, Mesilla, NM 88046",
      lat: 32.2715,
      lng: -106.7950,
      cuisine: "Continental & Southwestern",
      priceRange: "$$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the historic courtyard patio in Old Mesilla.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.double-eagle-mesilla.com",
    },
    {
      name: "Spotted Dog Brewery",
      address: "2900 Avenida de Mesilla, Las Cruces, NM 88005",
      lat: 32.2980,
      lng: -106.7740,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Named for a dog and very dog-friendly. Large outdoor patio with craft beer.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.spotteddogbrewery.com",
    },
    {
      name: "La Posta de Mesilla",
      address: "2410 Calle de San Albino, Mesilla, NM 88046",
      lat: 32.2720,
      lng: -106.7940,
      cuisine: "New Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the courtyard patio. Historic restaurant in a 17th-century adobe building.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.laposta-de-mesilla.com",
    },
    {
      name: "Andele's Dog House",
      address: "1983 Calle del Norte, Mesilla, NM 88046",
      lat: 32.2730,
      lng: -106.7920,
      cuisine: "New Mexican Hot Dogs",
      priceRange: "$" as const,
      dogPolicy: "Dog-themed restaurant that welcomes real dogs too. Outdoor picnic seating.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.andelesdoghouse.com",
    },
  ],

  cafes: [
    {
      name: "Milagro Coffee y Espresso",
      address: "1733 E University Ave, Las Cruces, NM 88001",
      lat: 32.3470,
      lng: -106.7370,
      dogPolicy: "Dogs welcome on the outdoor patio. Community coffee shop near NMSU.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.milagrocoffee.com",
    },
    {
      name: "Beck's Coffee",
      address: "130 N Mesquite St, Las Cruces, NM 88001",
      lat: 32.3500,
      lng: -106.7470,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Specialty coffee downtown.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.beckscoffee.com",
    },
    {
      name: "Picacho Peak Brewing Co. & Cafe",
      address: "3900 W Picacho Ave, Las Cruces, NM 88007",
      lat: 32.3480,
      lng: -106.8040,
      dogPolicy: "Dog-friendly outdoor area. Coffee and craft beer in one spot.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.picachopeakbrewing.com",
    },
    {
      name: "Dragonfly Coffee House",
      address: "2275 E Idaho Ave, Las Cruces, NM 88001",
      lat: 32.3530,
      lng: -106.7250,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Cozy coffee house with local art.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.dragonflycoffeelc.com",
    },
  ],

  dogParks: [
    {
      name: "Dog Park of Las Cruces",
      address: "3950 Stern Dr, Las Cruces, NM 88001",
      lat: 32.3450,
      lng: -106.7200,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: ["Separate small dog area", "Water stations", "Shade ramadas", "Agility equipment", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Las Cruces' main off-leash dog park with good shade structures essential for the desert climate. Separate areas for large and small dogs with agility equipment and reliable water access.",
    },
    {
      name: "Dripping Springs Natural Area",
      address: "Dripping Springs Rd, Las Cruces, NM 88011",
      lat: 32.3310,
      lng: -106.5920,
      offLeash: false,
      fenced: false,
      acres: 100.0,
      amenities: ["Desert mountain trails", "Historic ruins", "Organ Mountain views", "Visitor center", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "The gateway to the Organ Mountains, Dripping Springs offers stunning desert trails to historic ruins and a seasonal waterfall. Leashed dogs love the varied terrain and mountain scenery.",
    },
    {
      name: "Burn Lake Park",
      address: "500 Stern Dr, Las Cruces, NM 88001",
      lat: 32.3380,
      lng: -106.7220,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Walking paths", "Pond views", "Picnic areas", "Playground", "Open space"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A spacious park near the Rio Grande with a lake, walking paths, and open fields. Dogs enjoy the on-leash walks around the lake and the diverse bird life attracted to the water.",
    },
    {
      name: "Mesilla Plaza Walk",
      address: "2100 Avenida de Mesilla, Mesilla, NM 88046",
      lat: 32.2720,
      lng: -106.7945,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["Historic plaza", "Adobe architecture", "Shops", "Restaurants", "Shade trees"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A stroll around the historic Mesilla Plaza with your leashed dog is a step back in time. The centuries-old adobe buildings, galleries, and restaurants all welcome dogs in this charming village.",
    },
  ],
};
