export const lasVegasData = {
  city: {
    name: "Las Vegas",
    state: "Nevada",
    region: "Southwest",
    lat: 36.1699,
    lng: -115.1398,
    dogFriendlinessScore: 6,
    description:
      "Las Vegas surprises dog lovers with world-class hiking just minutes from the Strip. Red Rock Canyon and Lake Mead offer stunning desert adventures, while a growing number of off-Strip restaurants and hotels welcome four-legged guests to enjoy the desert playground.",
    heroImage: "https://images.unsplash.com/photo-1605833556294-ea5c7a74f57d?w=1200&fit=crop",
    climate: "Hot desert",
    population: 641903,
  },

  hotels: [
    {
      name: "Delano Las Vegas",
      address: "3940 S Las Vegas Blvd, Las Vegas, NV 89119",
      lat: 36.0920,
      lng: -115.1740,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 100 lbs welcome with a one-time fee. Luxury all-suite hotel on the Strip.",
      maxDogWeight: 100,
      petFee: 100,
      amenities: ["Dog bed", "Gourmet treats", "Water bowls", "Pet walking service", "Suite accommodations"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.delanolasvegas.com",
      phone: "(877) 632-5400",
    },
    {
      name: "The Westin Las Vegas",
      address: "160 E Flamingo Rd, Las Vegas, NV 89169",
      lat: 36.1160,
      lng: -115.1650,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 40 lbs welcome with Westin's Heavenly Dog Bed program.",
      maxDogWeight: 40,
      petFee: 50,
      amenities: ["Heavenly dog bed", "Water bowls", "Near Strip", "Walking area", "Treats"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(702) 836-5900",
    },
    {
      name: "La Quinta Inn Las Vegas Summerlin",
      address: "7101 Cascade Valley Ct, Las Vegas, NV 89128",
      lat: 36.1930,
      lng: -115.2890,
      priceRange: "$" as const,
      dogPolicy: "All dogs welcome at no extra charge. Near Red Rock Canyon.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Near Red Rock Canyon", "Grassy area", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(702) 360-1200",
    },
    {
      name: "Red Rock Casino Resort & Spa",
      address: "11011 W Charleston Blvd, Las Vegas, NV 89135",
      lat: 36.1730,
      lng: -115.3120,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome in select rooms with a pet fee. Luxury resort near Red Rock Canyon.",
      maxDogWeight: 50,
      petFee: 80,
      amenities: ["Dog bed", "Treats", "Near hiking trails", "Spacious rooms", "Resort grounds"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.redrockcasinoresort.com",
      phone: "(702) 797-7777",
    },
  ],

  nationalParks: [
    {
      name: "Red Rock Canyon National Conservation Area",
      state: "Nevada",
      lat: 36.1350,
      lng: -115.4270,
      dogPolicy: "Leashed dogs allowed on most trails and the scenic drive. Some trails restrict dogs.",
      dogTrails: ["Moenkopi Trail", "Calico Tanks Trail", "Keystone Thrust Trail", "White Rock Loop"],
      restrictions: [
        "Must be on a 6-foot leash at all times",
        "Not allowed on Ice Box Canyon or some scrambling trails",
        "Carry extra water - desert environment",
        "Avoid summer midday hiking",
      ],
      description:
        "Just 20 minutes from the Strip, Red Rock Canyon features stunning red sandstone formations and diverse desert hiking. The 13-mile scenic drive and numerous dog-friendly trails make it a must-do for visiting dog owners.",
      imageUrl: "",
      website: "https://www.blm.gov/redrocknca",
    },
    {
      name: "Lake Mead National Recreation Area",
      state: "Nevada",
      lat: 36.0160,
      lng: -114.7370,
      dogPolicy: "Leashed dogs welcome on trails, beaches, and in campgrounds. Water access for swimming dogs.",
      dogTrails: ["Historic Railroad Trail", "Goldstrike Canyon Trail", "Lakeview Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed in developed swimming areas",
        "Carry water - extreme heat in summer",
      ],
      description:
        "Lake Mead offers desert lake beaches, canyon hikes, and the remarkable Historic Railroad Trail through old tunnels. Dogs love the water access at quiet beach areas and the dramatic canyon scenery.",
      imageUrl: "",
      website: "https://www.nps.gov/lake",
    },
    {
      name: "Spring Mountains National Recreation Area (Mt. Charleston)",
      state: "Nevada",
      lat: 36.2720,
      lng: -115.6950,
      dogPolicy: "Leashed dogs welcome on most trails. A cool mountain escape from the desert heat.",
      dogTrails: ["Cathedral Rock Trail", "Fletcher Canyon Trail", "Mary Jane Falls Trail"],
      restrictions: [
        "Must be on leash",
        "Not allowed in Mount Charleston Wilderness",
        "Stay on designated trails",
      ],
      description:
        "Rising to nearly 12,000 feet just 45 minutes from the Strip, Mount Charleston offers a 30-degree temperature drop and alpine forest trails. Dogs and their owners escape the desert heat on these forested mountain paths.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/htnf",
    },
  ],

  restaurants: [
    {
      name: "Lazy Dog Restaurant & Bar",
      address: "6509 S Las Vegas Blvd, Las Vegas, NV 89119",
      lat: 36.0790,
      lng: -115.1720,
      cuisine: "American Comfort",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio with a special dog menu. Water bowls and treats included.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.lazydogrestaurants.com",
    },
    {
      name: "Freed's Bakery",
      address: "9815 S Eastern Ave, Las Vegas, NV 89183",
      lat: 36.0330,
      lng: -115.1190,
      cuisine: "Bakery & Cafe",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Famous Vegas bakery with pup-friendly treats.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.freedsbakery.com",
    },
    {
      name: "Tenaya Creek Brewery",
      address: "831 W Bonanza Rd, Las Vegas, NV 89106",
      lat: 36.1750,
      lng: -115.1540,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly brewery with an outdoor beer garden. Dogs are regulars.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.tenayacreek.com",
    },
    {
      name: "Echo & Rig Butcher and Steakhouse",
      address: "440 S Rampart Blvd, Las Vegas, NV 89145",
      lat: 36.1670,
      lng: -115.2790,
      cuisine: "Steakhouse",
      priceRange: "$$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the outdoor patio. Premium steaks in Summerlin.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.echoandrig.com",
    },
    {
      name: "Tacos El Gordo",
      address: "3049 S Las Vegas Blvd, Las Vegas, NV 89109",
      lat: 36.1290,
      lng: -115.1690,
      cuisine: "Mexican Street Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor counter seating. Authentic Tijuana-style street tacos.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tacoselgordo.com",
    },
  ],

  cafes: [
    {
      name: "Vesta Coffee Roasters",
      address: "1114 S Casino Center Blvd, Las Vegas, NV 89104",
      lat: 36.1590,
      lng: -115.1470,
      dogPolicy: "Dogs welcome on the patio. Quality specialty coffee in the Arts District.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.vestacoffee.com",
    },
    {
      name: "Mothership Coffee Roasters",
      address: "2708 N Green Valley Pkwy, Henderson, NV 89014",
      lat: 36.0780,
      lng: -115.0690,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Locally roasted specialty coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.mothershipcoffee.com",
    },
    {
      name: "Sunrise Coffee",
      address: "3130 E Sunset Rd, Las Vegas, NV 89120",
      lat: 36.0720,
      lng: -115.1210,
      dogPolicy: "Dog-friendly patio with a relaxed atmosphere. Coffee and art in the same space.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.sunrisecoffeelv.com",
    },
    {
      name: "PublicUs",
      address: "1126 Fremont St, Las Vegas, NV 89101",
      lat: 36.1680,
      lng: -115.1380,
      dogPolicy: "Leashed dogs welcome on the outdoor seating area. Eclectic cafe near Fremont East.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.publicus.com",
    },
  ],

  dogParks: [
    {
      name: "Charlie Frias Dog Park",
      address: "7050 W Alexander Rd, Las Vegas, NV 89129",
      lat: 36.2380,
      lng: -115.2490,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: ["Separate small dog area", "Water stations", "Shade structures", "Agility equipment", "Lights"],
      rating: 4.5,
      imageUrl: "",
      description:
        "One of Las Vegas's best dog parks with lights for evening use, essential for avoiding daytime desert heat. The agility equipment and spacious layout make it a favorite year-round.",
    },
    {
      name: "Desert Breeze Dog Park",
      address: "8275 Spring Mountain Rd, Las Vegas, NV 89147",
      lat: 36.1250,
      lng: -115.2410,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Water fountains", "Shade ramadas", "Benches", "Waste stations", "Separate areas"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A well-maintained west-side dog park with essential shade structures for the desert climate. The evening hours are the most popular as temperatures cool down.",
    },
    {
      name: "Red Rock Canyon Scenic Drive",
      address: "1000 Scenic Loop Dr, Las Vegas, NV 89161",
      lat: 36.1350,
      lng: -115.4270,
      offLeash: false,
      fenced: false,
      acres: 1000.0,
      amenities: ["Desert trails", "Scenic drive", "Rock formations", "Picnic areas", "Visitor center"],
      rating: 4.8,
      imageUrl: "",
      description:
        "While on-leash, the trails and scenic drive through Red Rock Canyon offer some of the most spectacular desert hiking near any major city. The red sandstone cliffs and desert scenery are unforgettable.",
    },
    {
      name: "Bark Park at Heritage Park",
      address: "350 S Racetrack Rd, Henderson, NV 89015",
      lat: 36.0360,
      lng: -114.9890,
      offLeash: true,
      fenced: true,
      acres: 4.0,
      amenities: ["Separate small dog area", "Water features", "Shade structures", "Agility equipment", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Henderson's premier dog park features water features for cooling off, agility equipment, and excellent shade. The well-designed facility is one of the best in the Las Vegas valley.",
    },
  ],
};
