export const leavenworthData = {
  city: {
    name: "Leavenworth",
    state: "Washington",
    region: "Pacific Northwest",
    lat: 47.5962,
    lng: -120.6615,
    dogFriendlinessScore: 8,
    description:
      "Leavenworth is a Bavarian-themed village nestled in the Cascade Mountains that looks like it was plucked straight from the Alps and dropped into Washington state. Dogs fit right into this fairy-tale setting, trotting along the cobblestone streets past timber-frame buildings, beer halls, and pretzel shops. The surrounding wilderness is staggering, with alpine trails, the Wenatchee River for swimming, and endless national forest for exploring. Whether your pup prefers a schnitzel-scented patio or a mountain summit, Leavenworth delivers.",
    heroImage: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=1200&fit=crop",
    climate: "Continental",
    population: 2094,
  },

  hotels: [
    {
      name: "Posthotel Leavenworth",
      address: "305 8th St, Leavenworth, WA 98826",
      lat: 47.5960,
      lng: -120.6610,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in designated pet suites at this luxury European-style hotel. Spa, rooftop pool, and alpine elegance where your pup is treated like royalty.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Luxury dog bed", "Artisan treats", "Garden walking", "Near Waterfront Park", "Concierge pet services"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.posthotelleavenworth.com",
      phone: "(509) 548-0400",
    },
    {
      name: "Enzian Inn",
      address: "590 US-2, Leavenworth, WA 98826",
      lat: 47.5945,
      lng: -120.6560,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in pet-friendly rooms with a per-night fee. Bavarian charm with mountain views, an outdoor pool, and putting green where dogs watch from the sidelines.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Dog bed", "Grassy walking area", "Mountain views", "Near trails"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.enzianinn.com",
      phone: "(509) 548-5269",
    },
    {
      name: "Bavarian Lodge",
      address: "810 US-2, Leavenworth, WA 98826",
      lat: 47.5940,
      lng: -120.6530,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select rooms at this classic Bavarian-style lodge. Hot tub, fire pit, and easy access to the village and river.",
      maxDogWeight: 75,
      petFee: 40,
      amenities: ["Dog bed", "Bowls", "Fire pit area", "River proximity", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.bavarianlodge.com",
      phone: "(509) 548-7878",
    },
    {
      name: "Sleeping Lady Mountain Resort",
      address: "7375 Icicle Rd, Leavenworth, WA 98826",
      lat: 47.5835,
      lng: -120.6990,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in cabin accommodations surrounded by old-growth forest and Icicle Creek. A nature-immersive resort where your pup can hear the creek from their bed.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Cabin with yard", "Creek access", "Forest trails", "Organic dining on site"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.sleepinglady.com",
      phone: "(509) 548-6344",
    },
    {
      name: "Fairbridge Inn & Suites",
      address: "185 US-2, Leavenworth, WA 98826",
      lat: 47.5970,
      lng: -120.6680,
      priceRange: "$" as const,
      dogPolicy: "Budget-friendly pet rooms available with a small per-night fee. A solid base camp for dog-loving adventurers who spend their money on trails, not threads.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Dog bed on request", "Outdoor walking area", "Near village", "Waste bags"],
      rating: 3.9,
      imageUrl: "",
      website: "https://www.fairbridgeinn.com",
      phone: "(509) 548-6200",
    },
  ],

  nationalParks: [
    {
      name: "Alpine Lakes Wilderness",
      state: "Washington",
      lat: 47.5500,
      lng: -120.8500,
      dogPolicy: "Leashed dogs welcome on most trails in the Alpine Lakes Wilderness. Some of the most stunning alpine scenery in the Cascades.",
      dogTrails: ["Colchuck Lake Trail", "The Enchantments (lottery required)", "Lake Stuart Trail", "Icicle Ridge Trail"],
      restrictions: [
        "Must be on leash on most trails",
        "Enchantments require a permit (lottery system)",
        "Pack out all waste",
        "Some trails may be snow-covered into July",
      ],
      description:
        "Just outside Leavenworth, the Alpine Lakes Wilderness contains over 700 mountain lakes, granite peaks, and alpine meadows. Your leashed dog can hike to crystal-clear mountain lakes surrounded by larches that turn gold in October. The Colchuck Lake hike is demanding but offers one of the most beautiful payoffs in Washington.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/recarea/okawen",
    },
    {
      name: "Okanogan-Wenatchee National Forest",
      state: "Washington",
      lat: 47.6000,
      lng: -120.7000,
      dogPolicy: "Dogs welcome on all trails with leash requirements in developed areas. Vast forest surrounding Leavenworth with endless hiking options.",
      dogTrails: ["Icicle Creek Trail", "Eightmile Lake Trail", "Fourth of July Trail", "Chatter Creek Trail"],
      restrictions: [
        "Must be on leash in campgrounds and trailheads",
        "Voice control on most forest trails",
        "Northwest Forest Pass required for parking",
      ],
      description:
        "The national forest surrounding Leavenworth offers hundreds of miles of trails through old-growth forest, along rushing creeks, and up to stunning alpine viewpoints. Your dog can splash in Icicle Creek, hike through wildflower meadows, and camp under the stars in one of Washington's most beautiful forests.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/okawen",
    },
    {
      name: "North Cascades National Park",
      state: "Washington",
      lat: 48.7718,
      lng: -121.2985,
      dogPolicy: "Dogs allowed on one trail (Pacific Crest Trail through the park) and in developed areas only. Very limited dog access.",
      dogTrails: ["Pacific Crest Trail (through-hikers)", "Sterling Munro Trail (paved, 330 feet)"],
      restrictions: [
        "Dogs only on PCT and in parking areas",
        "Must be on leash at all times",
        "Not allowed on any other trails",
        "Not allowed in backcountry camps",
      ],
      description:
        "About two hours north of Leavenworth, the North Cascades are often called the American Alps for their jagged peaks and glaciers. Dog access within the park is extremely limited, but the scenic drive on Highway 20 through the park is spectacular, and the adjacent national forest offers dog-friendly trails nearby.",
      imageUrl: "",
      website: "https://www.nps.gov/noca",
    },
  ],

  restaurants: [
    {
      name: "Munchen Haus",
      address: "709 Front St, Leavenworth, WA 98826",
      lat: 47.5958,
      lng: -120.6605,
      cuisine: "German Sausages & Beer",
      priceRange: "$" as const,
      dogPolicy: "The most dog-friendly spot in Leavenworth with a huge outdoor beer garden. Dogs are everywhere, and the staff keeps treats and water at the ready.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.munchenhaus.com",
    },
    {
      name: "Andreas Keller",
      address: "829 Front St, Leavenworth, WA 98826",
      lat: 47.5955,
      lng: -120.6590,
      cuisine: "German",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the upper patio. Authentic German fare with accordion music, beer steins, and Bavarian atmosphere that your pup might mistake for actual Bavaria.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.andreaskeller.com",
    },
    {
      name: "South",
      address: "913 Front St, Leavenworth, WA 98826",
      lat: 47.5953,
      lng: -120.6580,
      cuisine: "Southern American",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio with a Southern twist in a Bavarian village. Fried chicken and biscuits with a mountain view your pup will appreciate.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.southleavenworth.com",
    },
    {
      name: "Watershed Cafe",
      address: "201 8th St, Leavenworth, WA 98826",
      lat: 47.5962,
      lng: -120.6615,
      cuisine: "Pacific Northwest",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Seasonal Pacific Northwest cuisine sourced from local farms and the Wenatchee Valley.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.watershedcafe.com",
    },
    {
      name: "Icicle Brewing Company",
      address: "935 Front St, Leavenworth, WA 98826",
      lat: 47.5952,
      lng: -120.6575,
      cuisine: "Brewery & Pub Food",
      priceRange: "$$" as const,
      dogPolicy: "Massive dog-friendly beer garden that is the gathering place for Leavenworth's outdoor crowd. Cold craft beer after a hot mountain hike is a tradition here.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.iciclebrewing.com",
    },
    {
      name: "Yodelin Broth Company",
      address: "725 Front St, Leavenworth, WA 98826",
      lat: 47.5957,
      lng: -120.6600,
      cuisine: "Soups & Broth",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Warming bone broths and hearty soups perfect for warming up after a cold mountain hike with your pup.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.yodelinbroth.com",
    },
    {
      name: "Pavz Creperie",
      address: "833 Front St, Leavenworth, WA 98826",
      lat: 47.5954,
      lng: -120.6588,
      cuisine: "French Crepes",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome at outdoor seating. Sweet and savory crepes with a Bavarian village backdrop.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.pavzcreperie.com",
    },
    {
      name: "King Ludwig's Restaurant",
      address: "921 Front St, Leavenworth, WA 98826",
      lat: 47.5952,
      lng: -120.6578,
      cuisine: "German",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the beer garden terrace. Schnitzel, spaetzle, and steins in a setting that takes the Bavarian theme to the max.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.kingludwigs.com",
    },
  ],

  cafes: [
    {
      name: "J5 Coffee",
      address: "221 8th St, Leavenworth, WA 98826",
      lat: 47.5963,
      lng: -120.6612,
      dogPolicy: "Leavenworth's favorite specialty coffee shop with a dog-friendly patio. The morning caffeine ritual before hitting the trails.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.j5coffee.com",
    },
    {
      name: "The Gingerbread Factory",
      address: "828 Commercial St, Leavenworth, WA 98826",
      lat: 47.5950,
      lng: -120.6595,
      dogPolicy: "Dog-friendly outdoor benches at this beloved bakery. Gingerbread cookies, strudel, and Bavarian pastries straight out of a fairy tale.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.gingerbreadfactory.com",
    },
    {
      name: "Starbucks Leavenworth",
      address: "932 Front St, Leavenworth, WA 98826",
      lat: 47.5953,
      lng: -120.6577,
      dogPolicy: "Even the Starbucks here looks Bavarian. Dog-friendly outdoor seating along Front Street. A pup cup is always on the menu.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.0,
      imageUrl: "",
      website: "https://www.starbucks.com",
    },
    {
      name: "Homefires Bakery",
      address: "13013 Bayne Rd, Leavenworth, WA 98826",
      lat: 47.6000,
      lng: -120.6750,
      dogPolicy: "Country bakery just outside the village with outdoor seating and a dog-friendly yard. Wood-fired breads and pastries from a real hearth oven.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.homefiresbakery.com",
    },
    {
      name: "Wild Huckleberry",
      address: "723 Front St, Leavenworth, WA 98826",
      lat: 47.5957,
      lng: -120.6601,
      dogPolicy: "Ice cream and candy shop with outdoor benches on Front Street. Dogs can enjoy the village scene while you sample huckleberry everything.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.wildhuckleberry.com",
    },
  ],

  dogParks: [
    {
      name: "Waterfront Park",
      address: "1001 Front St, Leavenworth, WA 98826",
      lat: 47.5948,
      lng: -120.6565,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Wenatchee River access", "Gazebo", "Walking paths", "Mountain views", "Picnic areas", "Waste stations"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A beautiful riverfront park where the Wenatchee River curves through town with the Cascades as a backdrop. Leashed dogs love wading in the shallows and walking the paths. The mountain views from the gazebo at sunset are absolutely magical.",
    },
    {
      name: "Leavenworth Dog Park",
      address: "10768 Ski Hill Dr, Leavenworth, WA 98826",
      lat: 47.5990,
      lng: -120.6490,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Mountain backdrop", "Waste stations", "Benches", "Water spigot"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A fenced off-leash park near the Leavenworth Ski Hill with stunning mountain views. Dogs can run free against a backdrop of snow-capped peaks while you chat with other adventure-dog owners about trail conditions.",
    },
    {
      name: "Icicle Creek Trail",
      address: "Icicle Rd, Leavenworth, WA 98826",
      lat: 47.5820,
      lng: -120.7050,
      offLeash: false,
      fenced: false,
      acres: 60.0,
      amenities: ["Creek swimming", "Forest trails", "Campgrounds", "Mountain scenery", "Parking"],
      rating: 4.8,
      imageUrl: "",
      description:
        "Follow Icicle Road out of town and you enter a world of rushing creek water, old-growth forest, and trailheads leading to alpine wonderland. Leashed dogs can swim in the creek pools, hike through towering Douglas firs, and sleep under the stars at dog-friendly campgrounds along the way.",
    },
    {
      name: "Blackbird Island",
      address: "Blackbird Island, Leavenworth, WA 98826",
      lat: 47.5950,
      lng: -120.6555,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["River island trails", "Bridges", "Wildlife viewing", "Wenatchee River access"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A forested island in the Wenatchee River connected by pedestrian bridges. Leashed dogs can explore the loop trail through the trees, watch salmon spawning in the fall, and wade in the river shallows. A hidden gem steps from the Bavarian village.",
    },
    {
      name: "Ski Hill Loop Trail",
      address: "Ski Hill Dr, Leavenworth, WA 98826",
      lat: 47.6030,
      lng: -120.6480,
      offLeash: false,
      fenced: false,
      acres: 25.0,
      amenities: ["Loop trail", "Elevation gain", "Valley views", "Forest setting", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A moderate loop trail that climbs through forest above Leavenworth with sweeping views of the valley and surrounding peaks. Leashed dogs enjoy the workout and the varied terrain, and in winter the cross-country ski trails become snowy dog-walking wonderlands.",
    },
  ],
};
