export const lexingtonData = {
  city: {
    name: "Lexington",
    state: "Kentucky",
    region: "Southeast",
    lat: 38.0406,
    lng: -84.5037,
    dogFriendlinessScore: 7,
    description:
      "Known as the Horse Capital of the World, Lexington is equally welcoming to dogs with its rolling bluegrass pastures, charming downtown patios, and miles of scenic trails. Dogs enjoy the relaxed pace of life here, where bourbon country meets college-town energy.",
    heroImage: "https://images.unsplash.com/photo-1542282811-943ef1a977c3?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 322570,
  },
  hotels: [
    {
      name: "21c Museum Hotel Lexington",
      address: "167 W Main St, Lexington, KY 40507",
      lat: 38.0490,
      lng: -84.5020,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a pet fee. Contemporary art museum and hotel in a restored historic building downtown.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking map", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.21cmuseumhotels.com/lexington",
      phone: "(859) 899-6800",
    },
    {
      name: "Gratz Park Inn",
      address: "120 W 2nd St, Lexington, KY 40507",
      lat: 38.0500,
      lng: -84.5005,
      priceRange: "$$$" as const,
      dogPolicy: "Small dogs welcome in designated rooms with prior arrangement. A charming historic inn adjacent to a peaceful park.",
      maxDogWeight: 30,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Adjacent park access", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.gratzparkinn.com",
      phone: "(859) 231-1777",
    },
    {
      name: "Hilton Lexington Downtown",
      address: "369 W Vine St, Lexington, KY 40507",
      lat: 38.0480,
      lng: -84.5060,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a nightly pet fee. Connected to the convention center and close to Rupp Arena.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Pet-friendly rooms", "Water bowls", "Nearby park access", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com/en/hotels/lexdwhh",
      phone: "(859) 231-9000",
    },
    {
      name: "Graduate Lexington",
      address: "301 W Short St, Lexington, KY 40507",
      lat: 38.0505,
      lng: -84.5040,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a one-time pet fee. Kentucky-themed boutique hotel with a playful nod to UK Wildcats culture.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Treats", "Waste bags", "Walking route suggestions"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.graduatehotels.com/lexington",
      phone: "(859) 721-4700",
    },
  ],
  nationalParks: [
    {
      name: "Daniel Boone National Forest",
      state: "Kentucky",
      lat: 37.8200,
      lng: -83.6700,
      dogPolicy: "Dogs welcome on all trails on a leash. Over 700,000 acres of forested hills, cliffs, and natural arches in eastern Kentucky.",
      dogTrails: ["Natural Bridge Trail", "Auxier Ridge Trail", "Indian Creek Trail", "Whittleton Branch Trail"],
      restrictions: ["Leash recommended on all trails", "Must clean up after pet", "Check seasonal hunting restrictions"],
      description: "Spanning most of eastern Kentucky, Daniel Boone National Forest offers dramatic cliff views, sandstone arches, and pristine waterways. Dogs can hike through some of the most beautiful terrain in the Eastern United States.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/dbnf",
    },
    {
      name: "Raven Run Nature Sanctuary",
      state: "Kentucky",
      lat: 37.9480,
      lng: -84.4580,
      dogPolicy: "Dogs are NOT allowed at Raven Run Nature Sanctuary to protect the native wildlife and habitats.",
      dogTrails: [],
      restrictions: ["No dogs permitted", "No pets of any kind", "Preserve is a wildlife sanctuary"],
      description: "While dogs are not permitted, this 734-acre nature sanctuary on the Kentucky River palisades is worth noting for nearby alternatives. The sanctuary preserves meadows, forests, and dramatic cliff overlooks.",
      imageUrl: "",
      website: "https://www.lexingtonky.gov/raven-run",
    },
    {
      name: "Kentucky Horse Park",
      state: "Kentucky",
      lat: 38.1490,
      lng: -84.5140,
      dogPolicy: "Dogs welcome on the grounds on a leash. Not permitted inside exhibit buildings or near the horses during events.",
      dogTrails: ["Park Perimeter Trail", "Cross Country Course Walk", "Nature Trail"],
      restrictions: ["Leash required at all times", "Not allowed in buildings", "Keep distance from horses", "Must clean up after pet"],
      description: "This 1,200-acre working horse farm and educational theme park celebrates Kentucky's equestrian heritage. Dogs can stroll the beautiful grounds and enjoy the scenic bluegrass countryside just north of Lexington.",
      imageUrl: "",
      website: "https://www.kyhorsepark.com",
    },
  ],
  restaurants: [
    {
      name: "County Club",
      address: "555 Jefferson St, Lexington, KY 40508",
      lat: 38.0530,
      lng: -84.4980,
      cuisine: "Southern Comfort Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the large outdoor patio. Elevated comfort food with a lively beer garden atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.countyclubrestaurant.com",
    },
    {
      name: "West Sixth Brewing",
      address: "501 W 6th St, Lexington, KY 40508",
      lat: 38.0540,
      lng: -84.5070,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome in the taproom and outdoor area. A dog-friendly brewery in a converted bread factory in the Bread Box district.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.westsixth.com",
    },
    {
      name: "Sidebar Grill",
      address: "145 N Limestone, Lexington, KY 40507",
      lat: 38.0510,
      lng: -84.4960,
      cuisine: "American Grill",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the sidewalk patio. A downtown favorite for burgers, salads, and creative sandwiches.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.sidebargrill.com",
    },
    {
      name: "Lockbox at 21c",
      address: "167 W Main St, Lexington, KY 40507",
      lat: 38.0490,
      lng: -84.5020,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the outdoor terrace. Upscale dining inside the 21c Museum Hotel with a seasonal Kentucky-inspired menu.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.lockboxlex.com",
    },
    {
      name: "Athenian Grill",
      address: "107 S Limestone, Lexington, KY 40507",
      lat: 38.0480,
      lng: -84.4960,
      cuisine: "Greek & Mediterranean",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor tables. A beloved Lexington institution serving affordable Greek food since 1959.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.atheniangrill.com",
    },
  ],
  cafes: [
    {
      name: "Third Street Stuff & Coffee",
      address: "257 N Limestone, Lexington, KY 40507",
      lat: 38.0520,
      lng: -84.4955,
      dogPolicy: "Dogs welcome in the colorful outdoor garden. An eclectic, artsy coffeehouse that doubles as a community gathering space.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thirdstreetstuff.com",
    },
    {
      name: "A Cup of Commonwealth",
      address: "105 Eastern Ave, Lexington, KY 40508",
      lat: 38.0465,
      lng: -84.4960,
      dogPolicy: "Dogs welcome on the patio. A specialty coffee roaster in the Chevy Chase neighborhood with carefully sourced beans.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cupofcommonwealth.com",
    },
    {
      name: "North Lime Coffee & Donuts",
      address: "575 N Limestone, Lexington, KY 40508",
      lat: 38.0580,
      lng: -84.4940,
      dogPolicy: "Dogs welcome at outdoor seating. Known for creative craft donuts and strong coffee in the North Limestone district.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.northlimedoughnuts.com",
    },
    {
      name: "Coffea Coffee",
      address: "388 Woodland Ave, Lexington, KY 40508",
      lat: 38.0450,
      lng: -84.4970,
      dogPolicy: "Dog-friendly outdoor seating near UK campus. Specialty pour-overs and espresso drinks in a minimalist space.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.coffeacoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Masterson Station Dog Park",
      address: "3051 Leestown Rd, Lexington, KY 40511",
      lat: 38.0790,
      lng: -84.5530,
      offLeash: true,
      fenced: true,
      acres: 6,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade pavilion", "Agility equipment"],
      rating: 4.5,
      imageUrl: "",
      description: "Lexington's premier dog park features over six acres of fenced off-leash area with separate sections for large and small dogs. The park includes agility equipment and shaded rest areas within the larger Masterson Station Park.",
    },
    {
      name: "Jacobson Park Dog Park",
      address: "4001 Athens Boonesboro Rd, Lexington, KY 40509",
      lat: 38.0130,
      lng: -84.4230,
      offLeash: true,
      fenced: true,
      acres: 4,
      amenities: ["Lake views", "Open fields", "Water stations", "Benches", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "Set within the scenic Jacobson Park near a 47-acre lake, this fenced dog park offers open fields and water views. Dogs can enjoy off-leash play while their owners take in the beautiful bluegrass scenery.",
    },
    {
      name: "Wellington Dog Park",
      address: "200 Lexington Rd, Lexington, KY 40505",
      lat: 38.0550,
      lng: -84.4780,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Double-gated entry", "Water fountains", "Benches", "Shade trees", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      description: "A convenient in-town dog park near the historic Ashland estate, Wellington offers a compact but well-maintained space for off-leash play. Popular with the surrounding neighborhood dog community.",
    },
    {
      name: "Coldstream Park Dog Park",
      address: "4301 Clearwater Way, Lexington, KY 40515",
      lat: 38.0020,
      lng: -84.4440,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Benches", "Water spigot", "Open grassy area", "Waste bag stations"],
      rating: 4.2,
      imageUrl: "",
      description: "Located in the growing south side of Lexington, Coldstream Dog Park provides a well-fenced area for off-leash play. The rolling grass terrain gives dogs plenty of room to run and explore.",
    },
  ],
};
