export const livingstonData = {
  city: {
    name: "Livingston",
    state: "Montana",
    region: "Mountain West",
    lat: 45.6628,
    lng: -110.5609,
    dogFriendlinessScore: 8,
    description:
      "Livingston is a gritty, artistic railroad town on the Yellowstone River with a dog-friendly soul. Famous for world-class fly fishing and proximity to Yellowstone's north entrance, dogs love the river access, mountain trails, and a downtown where every other business has a water bowl out front. The wind blows hard but the hospitality is warm.",
    heroImage: "https://images.unsplash.com/photo-1508389377389-918442e3626b?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 8120,
  },

  hotels: [
    {
      name: "The Murray Hotel",
      address: "201 W Park St, Livingston, MT 59047",
      lat: 45.6630,
      lng: -110.5620,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with advance notice. Historic 1904 hotel where celebrities and cowboys mingle.",
      maxDogWeight: 50,
      petFee: 40,
      amenities: ["Dog bed", "Water bowls", "Downtown location", "Walking map", "Near Yellowstone River"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.murrayhotel.com",
      phone: "(406) 222-1350",
    },
    {
      name: "Yellowstone Pioneer Lodge",
      address: "1515 W Park St, Livingston, MT 59047",
      lat: 45.6625,
      lng: -110.5780,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a per-night fee. Updated lodge with mountain views.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Grassy areas", "Pet waste stations", "Near river trail", "Water bowls"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.yellowstonepioneer.com",
      phone: "(406) 222-6110",
    },
    {
      name: "Chico Hot Springs Resort & Day Spa",
      address: "163 Chico Rd, Pray, MT 59065",
      lat: 45.3700,
      lng: -110.6100,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select cabins and motel rooms. Historic hot springs resort in Paradise Valley.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Hot springs nearby", "Valley trails", "Dog bed", "Mountain views", "River access"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.chicohotsprings.com",
      phone: "(406) 333-4933",
    },
    {
      name: "Budget Host Parkway Motel",
      address: "1124 W Park St, Livingston, MT 59047",
      lat: 45.6627,
      lng: -110.5720,
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome with a small pet fee. Budget-friendly option on the main drag.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Pet waste stations", "Grassy areas", "Walking distance to downtown", "Water bowls"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.budgethost.com",
      phone: "(406) 222-3840",
    },
  ],

  nationalParks: [
    {
      name: "Absaroka-Beartooth Wilderness (Livingston Access)",
      state: "Montana",
      lat: 45.4000,
      lng: -110.5000,
      dogPolicy: "Dogs welcome off-leash under voice control in the wilderness.",
      dogTrails: ["Pine Creek Lake Trail", "Elbow Lake Trail", "Deep Creek Trail", "Mill Creek Trail"],
      restrictions: [
        "Must be under voice control",
        "Pack out all waste",
        "Grizzly bear country - carry bear spray",
      ],
      description:
        "The Absaroka Range rises dramatically south of Livingston, with trails leading from Paradise Valley into pristine alpine wilderness. Dogs can roam free under voice control on trails to alpine lakes and mountain passes.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/custergallatin",
    },
    {
      name: "Yellowstone National Park (North Entrance)",
      state: "Montana",
      lat: 45.0286,
      lng: -110.7068,
      dogPolicy: "Dogs NOT allowed on trails. Permitted in parking areas, campgrounds, and within 100 feet of roads only.",
      dogTrails: ["No dog-friendly trails"],
      restrictions: [
        "No dogs on any trails",
        "Must be on leash (6 ft max) at all times",
        "Allowed only in parking areas and campgrounds",
      ],
      description:
        "Livingston is 56 miles from Yellowstone's north entrance through the spectacular Paradise Valley. While dog access is limited in the park, the drive through the valley with the Yellowstone River and Absaroka Range is unforgettable.",
      imageUrl: "",
      website: "https://www.nps.gov/yell",
    },
    {
      name: "Gallatin National Forest (Crazy Mountains)",
      state: "Montana",
      lat: 46.0000,
      lng: -110.3000,
      dogPolicy: "Dogs welcome on trails. Voice control in backcountry; leash in developed areas.",
      dogTrails: ["Cottonwood Lake Trail", "Sweet Grass Creek Trail", "Big Timber Creek Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on trails",
        "Remote terrain - be prepared",
      ],
      description:
        "The Crazy Mountains northeast of Livingston offer some of Montana's most rugged and uncrowded alpine hiking. These isolated peaks rise dramatically from the plains and provide a true wilderness experience for adventurous dogs.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/custergallatin",
    },
  ],

  restaurants: [
    {
      name: "Gil's Goods",
      address: "207 W Park St, Livingston, MT 59047",
      lat: 45.6630,
      lng: -110.5625,
      cuisine: "Farm-to-Table & Market",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Local market and cafe with Montana-sourced ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.gilsgoods.com",
    },
    {
      name: "Katabatic Brewing",
      address: "117 W Park St, Livingston, MT 59047",
      lat: 45.6632,
      lng: -110.5610,
      cuisine: "Brewery & Food Trucks",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly taproom and outdoor area. Local craft brewery with rotating food trucks.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.katabaticbrewing.com",
    },
    {
      name: "Follow Yer' Nose BBQ",
      address: "112 N 2nd St, Livingston, MT 59047",
      lat: 45.6635,
      lng: -110.5600,
      cuisine: "BBQ",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor picnic tables. Slow-smoked BBQ with Montana character.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.followyernosebbq.com",
    },
    {
      name: "Montana's Rib & Chop House",
      address: "305 E Park St, Livingston, MT 59047",
      lat: 45.6628,
      lng: -110.5580,
      cuisine: "Steakhouse",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor deck. Premium Montana beef in a Western setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ribandchophouse.com",
    },
    {
      name: "Taco Montes",
      address: "119 E Park St, Livingston, MT 59047",
      lat: 45.6630,
      lng: -110.5598,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor seating. Authentic tacos from a local favorite.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.tacomontes.com",
    },
  ],

  cafes: [
    {
      name: "Neptune's Brewery & Taproom",
      address: "120 N Main St, Livingston, MT 59047",
      lat: 45.6638,
      lng: -110.5608,
      dogPolicy: "Dogs welcome on the patio. Coffee by morning, craft beer by afternoon.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.neptunesbrewery.com",
    },
    {
      name: "The Owlet",
      address: "101 N Main St, Livingston, MT 59047",
      lat: 45.6636,
      lng: -110.5605,
      dogPolicy: "Outdoor seating welcomes dogs. Cozy coffee shop with local art and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.theowletcoffee.com",
    },
    {
      name: "Wheatgrass Saloon & Espresso",
      address: "108 W Callender St, Livingston, MT 59047",
      lat: 45.6625,
      lng: -110.5612,
      dogPolicy: "Dog-friendly outdoor area. Health-focused cafe with smoothies and espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.wheatgrasssaloon.com",
    },
    {
      name: "Livingston Bar & Grille Coffee Service",
      address: "130 N Main St, Livingston, MT 59047",
      lat: 45.6640,
      lng: -110.5608,
      dogPolicy: "Leashed dogs welcome at patio tables during morning coffee hours.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.livingstonbarandgrille.com",
    },
  ],

  dogParks: [
    {
      name: "Sacajawea Park",
      address: "E Chinook St, Livingston, MT 59047",
      lat: 45.6610,
      lng: -110.5550,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Yellowstone River access", "Walking paths", "Lagoon", "Picnic areas", "Band shell"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Livingston's main park along the Yellowstone River with a lagoon, walking paths, and river access. Leashed dogs love this expansive park in the heart of town with mountain views in every direction.",
    },
    {
      name: "Yellowstone River Trail",
      address: "Mayor's Landing, Livingston, MT 59047",
      lat: 45.6600,
      lng: -110.5600,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["River trail", "Fishing access", "Mountain views", "Waste stations", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Trails along the Yellowstone River through and below Livingston with excellent mountain views and river access. Leashed dogs enjoy the cottonwood-shaded paths and the chance to wade in the famous river.",
    },
    {
      name: "Pine Creek Trail & Falls",
      address: "Pine Creek Rd, Livingston, MT 59047",
      lat: 45.5200,
      lng: -110.5500,
      offLeash: true,
      fenced: false,
      acres: 80.0,
      amenities: ["Mountain trail", "Waterfall", "Alpine lake access", "Parking", "Campground nearby"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A popular trail south of Livingston climbing to Pine Creek Falls and beyond to Pine Creek Lake. Dogs can be off-leash under voice control on this stunning trail into the Absaroka-Beartooth Wilderness.",
    },
    {
      name: "Livingston Dog Park",
      address: "View Vista Dr, Livingston, MT 59047",
      lat: 45.6680,
      lng: -110.5650,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Water station", "Waste bags", "Benches", "Mountain views"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Livingston's fenced off-leash dog park with views of the Absaroka and Crazy Mountains. A well-maintained community gathering spot for local and visiting dogs.",
    },
  ],
};
