export const longBeachData = {
  city: {
    name: "Long Beach",
    state: "California",
    region: "West Coast",
    lat: 33.7701,
    lng: -118.1937,
    dogFriendlinessScore: 8,
    description:
      "Long Beach is home to the only official off-leash dog beach in LA County and boasts a thriving urban dog culture with bike paths, waterfront restaurants, and a diverse neighborhoods vibe. The city's coastal setting, extensive parks, and progressive pet-friendly policies make it a standout destination for dog owners.",
    heroImage: "https://images.unsplash.com/photo-1512100356356-de1b84283e18?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 466742,
  },
  hotels: [
    {
      name: "Hotel Maya, a DoubleTree by Hilton",
      address: "700 Queensway Dr, Long Beach, CA 90802",
      lat: 33.7620,
      lng: -118.2020,
      priceRange: "$$$" as const,
      dogPolicy: "Waterfront resort welcoming dogs under 75 lbs. Tropical grounds with harbor views and beach access.",
      maxDogWeight: 75,
      petFee: 75,
      amenities: ["Dog bed", "Harbor views", "Tropical gardens", "Walking paths", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hotelmayalongbeach.com",
      phone: "(562) 435-7676",
    },
    {
      name: "Hyatt Regency Long Beach",
      address: "200 S Pine Ave, Long Beach, CA 90802",
      lat: 33.7670,
      lng: -118.1930,
      priceRange: "$$$" as const,
      dogPolicy: "Downtown hotel with pet-friendly rooms near the convention center. Dogs under 50 lbs welcome with waterfront walking access.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Dog bed", "Water bowls", "Waterfront proximity", "Downtown location", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hyatt.com",
      phone: "(562) 491-1234",
    },
    {
      name: "The Cove Hotel",
      address: "2555 E Pacific Coast Hwy, Long Beach, CA 90804",
      lat: 33.7700,
      lng: -118.1600,
      priceRange: "$$" as const,
      dogPolicy: "Mid-century boutique hotel welcoming dogs of all sizes. Pool, fire pits, and a relaxed retro vibe near Belmont Shore.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Pool", "Fire pits", "Dog bed", "Near dog beach", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.thecovehotel.com",
      phone: "(562) 434-0471",
    },
    {
      name: "Quality Inn Long Beach Airport",
      address: "3201 E Pacific Coast Hwy, Long Beach, CA 90804",
      lat: 33.7720,
      lng: -118.1480,
      priceRange: "$" as const,
      dogPolicy: "Affordable pet-friendly option near the airport and beaches. Dogs welcome with a small nightly fee.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Pet-friendly rooms", "Parking", "Near beach", "Breakfast", "Waste bags"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.choicehotels.com",
      phone: "(562) 597-4401",
    },
  ],
  nationalParks: [
    {
      name: "El Dorado Nature Center",
      state: "California",
      lat: 33.8200,
      lng: -118.0900,
      dogPolicy: "Dogs allowed on the paved outer trail on leash. A peaceful nature sanctuary within the urban landscape of Long Beach.",
      dogTrails: ["Outer Loop Trail (paved)"],
      restrictions: ["6-foot leash required", "Only on paved outer trail", "Not allowed on inner nature trails", "Small entrance fee"],
      description: "This 105-acre nature center offers a surprising wilderness experience within Long Beach. While dogs are limited to the paved outer trail, the walk through meadows and along the lake is a serene escape from the city.",
      imageUrl: "",
      website: "https://www.longbeach.gov/park/recreation-programs/el-dorado-nature-center",
    },
    {
      name: "Bolsa Chica Ecological Reserve",
      state: "California",
      lat: 33.7100,
      lng: -118.0500,
      dogPolicy: "Dogs allowed on the mesa trail and paved paths on leash. One of the premier bird watching sites in Southern California.",
      dogTrails: ["Mesa Loop Trail", "Bolsa Chica Paved Trail"],
      restrictions: ["6-foot leash required", "Stay on designated trails", "Do not disturb wildlife", "Clean up after pet"],
      description: "Southeast of Long Beach in Huntington Beach, this coastal wetland reserve offers excellent bird watching and nature walks. Dogs on leash can join their owners on the mesa trail overlooking the restored salt marsh.",
      imageUrl: "",
      website: "https://www.bolsachica.org",
    },
    {
      name: "Shoreline Aquatic Park",
      state: "California",
      lat: 33.7580,
      lng: -118.1900,
      dogPolicy: "Dogs welcome on leash throughout the waterfront park and along Rainbow Harbor. A scenic urban waterfront experience.",
      dogTrails: ["Shoreline Path", "Rainbow Harbor Walk", "Lighthouse Walk"],
      restrictions: ["Leash required", "Not allowed on Queen Mary", "Clean up after pet", "Watch for cyclists on path"],
      description: "Long Beach's waterfront park stretches along Rainbow Harbor with views of the Queen Mary and downtown skyline. Dogs on leash enjoy the breezy waterfront walks and the lively marina atmosphere.",
      imageUrl: "",
      website: "https://www.longbeach.gov/park",
    },
  ],
  restaurants: [
    {
      name: "The Attic on Broadway",
      address: "3441 E Broadway, Long Beach, CA 90803",
      lat: 33.7650,
      lng: -118.1500,
      cuisine: "Brunch & American",
      priceRange: "$$" as const,
      dogPolicy: "Popular Belmont Heights restaurant with a dog-friendly patio. Famous for creative brunch dishes and Bloody Marys.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.theatticonbroadway.com",
    },
    {
      name: "Schooner or Later",
      address: "241 Marina Dr, Long Beach, CA 90803",
      lat: 33.7520,
      lng: -118.1350,
      cuisine: "Breakfast & Seafood",
      priceRange: "$" as const,
      dogPolicy: "Marina-side breakfast spot with outdoor seating where dogs are welcome. Classic breakfasts with boat-filled harbor views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.schooneror later.com",
    },
    {
      name: "Ellie's",
      address: "214 Pine Ave, Long Beach, CA 90802",
      lat: 33.7680,
      lng: -118.1930,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Downtown restaurant with a stylish patio welcoming dogs. Seasonal menu with craft cocktails in a renovated historic space.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.ellieslb.com",
    },
    {
      name: "Playa Amor",
      address: "5217 E 2nd St, Long Beach, CA 90803",
      lat: 33.7600,
      lng: -118.1300,
      cuisine: "Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Belmont Shore Mexican restaurant with a colorful patio where dogs are welcome. Craft margaritas and elevated street food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.playaamorlb.com",
    },
    {
      name: "Berlin Bistro",
      address: "3345 E Broadway, Long Beach, CA 90803",
      lat: 33.7655,
      lng: -118.1510,
      cuisine: "German-American",
      priceRange: "$$" as const,
      dogPolicy: "Unique German-inspired bistro with outdoor seating where dogs are welcome. Schnitzel, pretzels, and craft German beers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.berlinbistro.com",
    },
  ],
  cafes: [
    {
      name: "Lord Windsor Coffee",
      address: "1101 E 3rd St, Long Beach, CA 90802",
      lat: 33.7700,
      lng: -118.1780,
      dogPolicy: "Hip Retro Row roaster with a spacious patio where dogs are welcome. Award-winning specialty coffee in a trendy neighborhood.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.lordwindsorcoffee.com",
    },
    {
      name: "Rose Park Roasters",
      address: "800 E 4th St, Long Beach, CA 90802",
      lat: 33.7710,
      lng: -118.1800,
      dogPolicy: "Local roaster in the Rose Park neighborhood with a sunny patio. Dogs welcome outside with craft coffee and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.roseparkroasters.com",
    },
    {
      name: "Recreational Coffee",
      address: "235 E Broadway, Long Beach, CA 90802",
      lat: 33.7690,
      lng: -118.1920,
      dogPolicy: "Downtown café with outdoor seating where dogs are welcome. Specialty coffee and light bites in the East Village Arts District.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.recreationalcoffee.com",
    },
    {
      name: "Polly's on 2nd",
      address: "3648 E 2nd St, Long Beach, CA 90803",
      lat: 33.7610,
      lng: -118.1480,
      dogPolicy: "Neighborhood café on 2nd Street with a patio where dogs are regulars. Coffee, smoothies, and breakfast in Belmont Shore.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.pollyson2nd.com",
    },
  ],
  dogParks: [
    {
      name: "Rosie's Dog Beach",
      address: "5000 E Ocean Blvd, Long Beach, CA 90803",
      lat: 33.7560,
      lng: -118.1330,
      offLeash: true,
      fenced: false,
      acres: 8,
      amenities: ["Beach access", "Ocean swimming", "Waste bag stations", "Parking", "Restrooms"],
      rating: 4.7,
      imageUrl: "",
      description: "The only official off-leash dog beach in LA County, Rosie's is a legendary stretch of sand between Granada Avenue and Roycroft Avenue. Dogs run free, swim in the waves, and socialize in this iconic Long Beach destination.",
    },
    {
      name: "Recreation Dog Park",
      address: "4900 E 7th St, Long Beach, CA 90804",
      lat: 33.7720,
      lng: -118.1350,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Shade trees", "Agility equipment", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "A well-equipped fenced dog park in the Recreation Park complex with separate areas for large and small dogs. Agility equipment and shade trees make it a popular year-round destination.",
    },
    {
      name: "El Dorado Dog Park",
      address: "2800 N Studebaker Rd, Long Beach, CA 90815",
      lat: 33.8100,
      lng: -118.0950,
      offLeash: true,
      fenced: true,
      acres: 4,
      amenities: ["Separate small dog area", "Water stations", "Shade structures", "Benches", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "A spacious off-leash park within El Dorado Regional Park with plenty of room for dogs to run. Shade structures and water stations keep dogs comfortable, and the nearby nature center adds variety to outings.",
    },
    {
      name: "Long Beach Bike Path (Shoreline Trail)",
      address: "Shoreline Dr, Long Beach, CA 90802",
      lat: 33.7590,
      lng: -118.1900,
      offLeash: false,
      fenced: false,
      acres: 15,
      amenities: ["Paved path", "Ocean views", "Harbor views", "Benches", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "A scenic paved trail along the Long Beach waterfront stretching from the harbor to Belmont Shore. Leashed dogs enjoy the ocean breeze, harbor views, and the bustling waterfront atmosphere.",
    },
  ],
};
