export const losAngelesData = {
  city: {
    name: "Los Angeles",
    state: "California",
    region: "West Coast",
    lat: 34.0522,
    lng: -118.2437,
    dogFriendlinessScore: 8,
    description:
      "The City of Angels is a sprawling dog paradise with year-round sunshine, world-class off-leash beaches, and a culture that treats dogs like A-list celebrities. From hiking in Griffith Park to brunching on dog-friendly patios in Silver Lake, LA offers endless adventures for pups and their people.",
    heroImage: "https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 3898747,
  },
  hotels: [
    {
      name: "Kimpton La Peer Hotel",
      address: "627 N La Peer Dr, West Hollywood, CA 90069",
      lat: 34.0828,
      lng: -118.3815,
      priceRange: "$$$$" as const,
      dogPolicy: "Kimpton's beloved all-pets-welcome policy with no size limits and no fees. Rooftop pool and WeHo location make it ideal for dog owners.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Loaner leashes", "Dog walking service"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.lapeerhotel.com",
      phone: "(310) 855-8585",
    },
    {
      name: "The LINE Hotel",
      address: "3515 Wilshire Blvd, Los Angeles, CA 90010",
      lat: 34.0617,
      lng: -118.3060,
      priceRange: "$$$" as const,
      dogPolicy: "Hip Koreatown hotel welcoming dogs under 50 lbs. Ground-floor rooms available with easy park access.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Dog bed", "Water bowls", "Treats", "Walking routes map", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thelinehotel.com",
      phone: "(213) 381-7411",
    },
    {
      name: "Hotel Erwin",
      address: "1697 Pacific Ave, Venice, CA 90291",
      lat: 33.9850,
      lng: -118.4695,
      priceRange: "$$$" as const,
      dogPolicy: "Beachfront Venice hotel with pet-friendly rooms and a rooftop bar. Dogs under 40 lbs welcome with beach access steps away.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Beach towels", "Rooftop access", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelerwin.com",
      phone: "(310) 452-1111",
    },
    {
      name: "Ace Hotel Downtown Los Angeles",
      address: "929 S Broadway, Los Angeles, CA 90015",
      lat: 34.0420,
      lng: -118.2570,
      priceRange: "$$" as const,
      dogPolicy: "Stylish DTLA hotel in a historic building that welcomes dogs of all sizes. Rooftop pool and walkable downtown location.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Downtown walking map", "Rooftop access", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.acehotel.com/losangeles",
      phone: "(213) 623-3233",
    },
  ],
  nationalParks: [
    {
      name: "Santa Monica Mountains National Recreation Area",
      state: "California",
      lat: 34.0750,
      lng: -118.6800,
      dogPolicy: "Dogs allowed on fire roads and select trails on leash. Some of the best dog-friendly hiking in the LA area with ocean and mountain views.",
      dogTrails: ["Backbone Trail (fire road sections)", "Solstice Canyon Trail", "Escondido Falls Road", "Upper Sycamore Canyon Fire Road"],
      restrictions: ["6-foot leash required", "Dogs only on fire roads and designated trails", "Not allowed on narrow single-track trails in most areas", "Pack out waste"],
      description: "Stretching from Griffith Park to Point Mugu, the Santa Monica Mountains offer incredible dog-friendly hiking with coastal views. While dogs are restricted from some single-track trails, the extensive fire road network provides miles of scenic walking with ocean panoramas.",
      imageUrl: "",
      website: "https://www.nps.gov/samo",
    },
    {
      name: "Angeles National Forest",
      state: "California",
      lat: 34.2500,
      lng: -118.1500,
      dogPolicy: "Dogs welcome on most trails on leash or under voice control. Vast forest covering the San Gabriel Mountains above LA.",
      dogTrails: ["Trail Canyon Falls", "Mt. Wilson Trail", "Eaton Canyon Trail", "Switzer Falls Trail"],
      restrictions: ["Leash recommended", "Adventure Pass required for parking", "Some trails closed seasonally", "Carry extra water"],
      description: "The Angeles National Forest covers over 700,000 acres of mountain terrain just north of LA. Dogs can explore waterfalls, mountain peaks, and shaded canyons within an hour of downtown, making it the city's backyard wilderness playground.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/angeles",
    },
    {
      name: "Channel Islands National Park",
      state: "California",
      lat: 34.0069,
      lng: -119.7785,
      dogPolicy: "Dogs are NOT allowed on the Channel Islands. However, the visitor center in Ventura Harbor is accessible with leashed dogs.",
      dogTrails: [],
      restrictions: ["No dogs allowed on any island", "Dogs permitted at Ventura Harbor visitor center only", "Leash required at visitor center"],
      description: "While the islands themselves do not allow dogs to protect sensitive wildlife, the Channel Islands Visitor Center at Ventura Harbor is a worthwhile stop for dog owners. The harbor area offers pleasant waterfront walks with your dog.",
      imageUrl: "",
      website: "https://www.nps.gov/chis",
    },
  ],
  restaurants: [
    {
      name: "Gjusta",
      address: "320 Sunset Ave, Venice, CA 90291",
      lat: 33.9920,
      lng: -118.4670,
      cuisine: "Bakery & Deli",
      priceRange: "$$" as const,
      dogPolicy: "Venice's legendary bakery-deli with expansive outdoor seating where dogs are welcome. Fresh pastries, smoked fish, and artisan sandwiches.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.gjusta.com",
    },
    {
      name: "The Butcher's Daughter",
      address: "1205 Abbot Kinney Blvd, Venice, CA 90291",
      lat: 33.9890,
      lng: -118.4660,
      cuisine: "Vegetable-Forward",
      priceRange: "$$$" as const,
      dogPolicy: "Gorgeous garden patio with a dog-friendly atmosphere on Abbot Kinney. Plant-based cuisine and craft cocktails.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thebutchersdaughter.com",
    },
    {
      name: "Republique",
      address: "624 S La Brea Ave, Los Angeles, CA 90036",
      lat: 34.0620,
      lng: -118.3440,
      cuisine: "French-Californian",
      priceRange: "$$$" as const,
      dogPolicy: "Award-winning restaurant in a Charlie Chaplin-era building with a courtyard patio welcoming dogs. Outstanding pastries and brunch.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.republiquela.com",
    },
    {
      name: "Guisados",
      address: "2100 E Cesar E Chavez Ave, Los Angeles, CA 90033",
      lat: 34.0490,
      lng: -118.2120,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Beloved taco spot with outdoor picnic tables where dogs are welcome. Handmade tortillas and slow-braised fillings.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.guisados.co",
    },
    {
      name: "Sage Plant Based Bistro",
      address: "1700 Sunset Blvd, Los Angeles, CA 90026",
      lat: 34.0770,
      lng: -118.2620,
      cuisine: "Vegan",
      priceRange: "$$" as const,
      dogPolicy: "Echo Park vegan restaurant with a dog-friendly patio and a dedicated dog menu. Organic, plant-based cuisine in a relaxed setting.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.sageveganbistro.com",
    },
  ],
  cafes: [
    {
      name: "Alfred Coffee",
      address: "8428 Melrose Pl, Los Angeles, CA 90069",
      lat: 34.0830,
      lng: -118.3730,
      dogPolicy: "Instagrammable coffee shop with a courtyard patio where dogs are practically required accessories. Specialty lattes and pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.alfred.la",
    },
    {
      name: "Intelligentsia Coffee Silver Lake",
      address: "3922 Sunset Blvd, Los Angeles, CA 90029",
      lat: 34.0880,
      lng: -118.2760,
      dogPolicy: "Third-wave coffee pioneer with a spacious patio in Silver Lake. Dogs welcome outside while you enjoy carefully sourced coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.intelligentsia.com",
    },
    {
      name: "Dinosaur Coffee",
      address: "4334 Sunset Blvd, Los Angeles, CA 90029",
      lat: 34.0900,
      lng: -118.2830,
      dogPolicy: "Silver Lake neighborhood café with a small patio where dogs are always welcome. Known for their pour-overs and friendly vibe.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.dinosaurcoffee.com",
    },
    {
      name: "Great White Venice",
      address: "1604 Pacific Ave, Venice, CA 90291",
      lat: 33.9870,
      lng: -118.4690,
      dogPolicy: "Australian-inspired café steps from the beach with a breezy patio perfect for dogs. Avocado toast and flat whites in Venice.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.greatwhitevenice.com",
    },
  ],
  dogParks: [
    {
      name: "Laurel Canyon Off-Leash Dog Park",
      address: "8260 Mulholland Dr, Los Angeles, CA 90046",
      lat: 34.1150,
      lng: -118.3690,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Shade trees", "Benches", "Canyon views"],
      rating: 4.5,
      imageUrl: "",
      description: "Nestled in the Hollywood Hills, this popular off-leash park offers canyon views and a community vibe. Separate areas for large and small dogs, with mature trees providing shade on hot LA days.",
    },
    {
      name: "Rosie's Dog Beach",
      address: "5000 E Ocean Blvd, Long Beach, CA 90803",
      lat: 33.7560,
      lng: -118.1330,
      offLeash: true,
      fenced: false,
      acres: 8,
      amenities: ["Beach access", "Ocean swimming", "Open sand", "Waste bag stations", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description: "The only official off-leash dog beach in LA County, Rosie's is a three-acre stretch of sand where dogs run free, swim in the Pacific, and socialize with hundreds of other pups. A quintessential LA dog experience.",
    },
    {
      name: "Runyon Canyon Dog Park",
      address: "2000 N Fuller Ave, Los Angeles, CA 90046",
      lat: 34.1060,
      lng: -118.3500,
      offLeash: true,
      fenced: false,
      acres: 160,
      amenities: ["Hiking trails", "City views", "Hollywood sign views", "Water fountain", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "LA's most famous dog park offers off-leash hiking with panoramic views of Hollywood, downtown, and the ocean. The trails wind through chaparral-covered hillsides where dogs and their owners see and be seen.",
    },
    {
      name: "Silver Lake Dog Park",
      address: "1850 W Silver Lake Dr, Los Angeles, CA 90026",
      lat: 34.0860,
      lng: -118.2640,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade structures", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "A beloved neighborhood dog park in the hip Silver Lake area, offering a fenced space for off-leash play with reservoir views. The park attracts a friendly crowd of local dog owners and their well-socialized pups.",
    },
  ],
};
