export const louisvilleData = {
  city: {
    name: "Louisville",
    state: "Kentucky",
    region: "Southeast",
    lat: 38.2527,
    lng: -85.7585,
    dogFriendlinessScore: 7,
    description:
      "Louisville pairs bourbon culture with a genuine love for dogs, featuring sprawling waterfront parks along the Ohio River and a thriving patio dining scene. From the trails at Cherokee Park to the dog-friendly bourbon distilleries, this city makes every outing with your pup a memorable one.",
    heroImage: "https://images.unsplash.com/photo-1567449696654-a67cc44d565f?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 633045,
  },
  hotels: [
    {
      name: "21c Museum Hotel Louisville",
      address: "700 W Main St, Louisville, KY 40202",
      lat: 38.2586,
      lng: -85.7620,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a pet fee. A contemporary art museum and boutique hotel in one, located on Museum Row.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Art-filled lobby", "Walking route map"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.21cmuseumhotels.com/louisville",
      phone: "(502) 217-6300",
    },
    {
      name: "The Brown Hotel",
      address: "335 W Broadway, Louisville, KY 40202",
      lat: 38.2545,
      lng: -85.7590,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 40 lbs welcome in designated rooms. A Louisville landmark since 1923 and the birthplace of the Hot Brown sandwich.",
      maxDogWeight: 40,
      petFee: 100,
      amenities: ["Dog bed", "Water bowls", "Welcome treats", "Waste bags", "Concierge pet services"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.brownhotel.com",
      phone: "(502) 583-1234",
    },
    {
      name: "Aloft Louisville Downtown",
      address: "102 W Main St, Louisville, KY 40202",
      lat: 38.2575,
      lng: -85.7555,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome at no extra charge. Modern, pet-forward hotel on Whiskey Row with an Arf program for pets.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Food and water bowls", "Pet toys", "Waste bags", "Treats at front desk"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marriott.com/hotels/travel/sdfly",
      phone: "(502) 583-1888",
    },
    {
      name: "Hotel Distil",
      address: "226 S 5th St, Louisville, KY 40202",
      lat: 38.2530,
      lng: -85.7575,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 75 lbs welcome with a one-time fee. Bourbon-themed boutique hotel in the heart of Whiskey Row.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Treat bag", "Walking map of downtown", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hoteldistil.com",
      phone: "(502) 566-4100",
    },
  ],
  nationalParks: [
    {
      name: "Mammoth Cave National Park",
      state: "Kentucky",
      lat: 37.1870,
      lng: -86.1007,
      dogPolicy: "Dogs are not allowed in the cave. Permitted on most above-ground trails on a 6-foot leash and in campgrounds.",
      dogTrails: ["Heritage Trail", "Echo River Spring Trail", "Dixon Cave Trail", "Green River Bluffs Trail"],
      restrictions: ["No dogs in the cave system", "6-foot leash required", "Not permitted in buildings", "Must clean up after pet"],
      description: "About ninety minutes south of Louisville, Mammoth Cave protects the world's longest known cave system. While dogs cannot venture underground, the rolling Kentucky hills above offer pleasant wooded trails along the Green River.",
      imageUrl: "",
      website: "https://www.nps.gov/maca",
    },
    {
      name: "Red River Gorge Geological Area",
      state: "Kentucky",
      lat: 37.7770,
      lng: -83.6740,
      dogPolicy: "Dogs welcome on most trails on a leash. Part of the Daniel Boone National Forest with spectacular natural arches and cliff lines.",
      dogTrails: ["Natural Bridge Trail", "Rock Garden Trail", "Whittleton Branch Trail"],
      restrictions: ["Leash required on all trails", "Not allowed in Natural Bridge Sky Lift", "Must clean up after pet"],
      description: "The Red River Gorge in eastern Kentucky features stunning sandstone arches, cliff lines, and forested hollows. Dogs can hike alongside their owners through this geological wonderland about two hours from Louisville.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/recarea/dbnf/recarea/?recid=39458",
    },
    {
      name: "Falls of the Ohio State Park",
      state: "Indiana",
      lat: 38.2770,
      lng: -85.7670,
      dogPolicy: "Dogs welcome on the fossil beds and trails on a leash. Located just across the river from downtown Louisville.",
      dogTrails: ["Fossil Bed Trail", "River Walk Trail", "Woodland Trail"],
      restrictions: ["Leash required", "Not allowed in interpretive center", "Watch for slippery fossil beds", "Must clean up after pet"],
      description: "Just across the Ohio River in Clarksville, Indiana, this state park features 390-million-year-old exposed fossil beds. Dogs can explore the ancient Devonian reef formations and riverside trails with views of the Louisville skyline.",
      imageUrl: "",
      website: "https://www.fallsoftheohio.org",
    },
  ],
  restaurants: [
    {
      name: "Against the Grain Brewery & Smokehouse",
      address: "401 E Main St, Louisville, KY 40202",
      lat: 38.2580,
      lng: -85.7480,
      cuisine: "Barbecue & Craft Beer",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the large outdoor patio overlooking Louisville Slugger Field. Craft beer and smoked meats in a lively setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.atgbrewery.com",
    },
    {
      name: "Hammerheads",
      address: "921 Swan St, Louisville, KY 40204",
      lat: 38.2430,
      lng: -85.7380,
      cuisine: "Eclectic American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the outdoor yard area. A Germantown neighborhood gem with creative, bold flavors and a cult following.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hammerheadslouisville.com",
    },
    {
      name: "Holy Grale",
      address: "1034 Bardstown Rd, Louisville, KY 40204",
      lat: 38.2380,
      lng: -85.7250,
      cuisine: "Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. A craft beer haven in a converted church on Bardstown Road.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.holygralelouisville.com",
    },
    {
      name: "Joella's Hot Chicken",
      address: "3400 Frankfort Ave, Louisville, KY 40207",
      lat: 38.2620,
      lng: -85.7080,
      cuisine: "Southern / Hot Chicken",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor seating area. Louisville's answer to Nashville hot chicken with a great patio.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.joellas.com",
    },
    {
      name: "The Pearl of Germantown",
      address: "702 E Market St, Louisville, KY 40202",
      lat: 38.2560,
      lng: -85.7450,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the sidewalk patio in the heart of NuLu. Upscale seasonal fare with craft cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thepearlofgermantown.com",
    },
  ],
  cafes: [
    {
      name: "Please & Thank You",
      address: "800 E Market St, Louisville, KY 40206",
      lat: 38.2558,
      lng: -85.7430,
      dogPolicy: "Dogs welcome at the outdoor window-side tables. Famous for their chocolate chip cookies and vinyl records.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.pleaseandthankyoulouisville.com",
    },
    {
      name: "Quills Coffee",
      address: "930 Baxter Ave, Louisville, KY 40204",
      lat: 38.2490,
      lng: -85.7310,
      dogPolicy: "Dog-friendly patio seating on bustling Baxter Avenue. A beloved local roaster with precise espresso drinks.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.quillscoffee.com",
    },
    {
      name: "Heine Brothers' Coffee",
      address: "1295 Bardstown Rd, Louisville, KY 40204",
      lat: 38.2340,
      lng: -85.7220,
      dogPolicy: "Dogs welcome on the Bardstown Road patio. Louisville's hometown coffee chain with organic, fair-trade beans.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.heinebroscoffee.com",
    },
    {
      name: "Sunergos Coffee",
      address: "2122 S Preston St, Louisville, KY 40217",
      lat: 38.2280,
      lng: -85.7485,
      dogPolicy: "Cozy Beechmont cafe with outdoor seating where dogs are welcome. Known for exceptional latte art and single-origin roasts.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.sunergoscoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Cherokee Park Dog Run",
      address: "745 Cochran Hill Rd, Louisville, KY 40206",
      lat: 38.2490,
      lng: -85.7120,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade trees", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "Set within Frederick Law Olmsted's stunning Cherokee Park, this fenced dog run offers off-leash freedom surrounded by rolling hills and mature trees. Dogs love the ample shade and room to roam.",
    },
    {
      name: "Beckley Creek Dog Park",
      address: "1411 Beckley Creek Pkwy, Louisville, KY 40245",
      lat: 38.2490,
      lng: -85.5500,
      offLeash: true,
      fenced: true,
      acres: 5,
      amenities: ["Large open fields", "Water fountains", "Benches", "Double-gated entry", "Agility equipment"],
      rating: 4.6,
      imageUrl: "",
      description: "Located within the expansive Parklands of Floyds Fork, this is one of Louisville's largest and best-maintained dog parks. Wide open spaces and agility equipment keep dogs entertained for hours.",
    },
    {
      name: "Sawyer Dog Park",
      address: "1525 Norris Pl, Louisville, KY 40205",
      lat: 38.2330,
      lng: -85.7140,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Water spigot", "Benches", "Shade structures", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      description: "A popular neighborhood dog park in the Highlands area, Sawyer provides a convenient spot for off-leash play. The separate small dog area makes it safe for pups of all sizes.",
    },
    {
      name: "Champions Park Dog Run",
      address: "2050 River Rd, Louisville, KY 40206",
      lat: 38.2720,
      lng: -85.7310,
      offLeash: true,
      fenced: true,
      acres: 4,
      amenities: ["River views", "Open fields", "Benches", "Water stations", "Gravel pathways"],
      rating: 4.3,
      imageUrl: "",
      description: "Situated along the Ohio River in the Crescent Hill neighborhood, Champions Park offers scenic off-leash play with river views. Dogs can enjoy the breezy waterfront setting and spacious fields.",
    },
  ],
};
