export const madisonData = {
  city: {
    name: "Madison",
    state: "Wisconsin",
    region: "Midwest",
    lat: 43.0731,
    lng: -89.4012,
    dogFriendlinessScore: 7,
    description:
      "Built on an isthmus between two sparkling lakes, Wisconsin's capital city is a progressive, outdoorsy paradise that takes its dog-friendliness seriously. With more dog parks per capita than almost any city in America, a culture of brewery-hopping with your pup, and lakeside paths that beg for an afternoon stroll, Madison proves that the Midwest does dog-friendly travel better than you might expect.",
    heroImage: "https://images.unsplash.com/photo-1568992688065-536aad8a12f6?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 269840,
  },

  hotels: [
    {
      name: "The Edgewater Hotel",
      address: "1001 Wisconsin Pl, Madison, WI 53703",
      lat: 43.0788,
      lng: -89.3899,
      priceRange: "$$$$" as const,
      dogPolicy:
        "Luxury lakefront hotel welcoming dogs up to 75 lbs with a VIP pet package including bed, bowls, and treats.",
      maxDogWeight: 75,
      petFee: 100,
      amenities: [
        "Dog bed",
        "Water and food bowls",
        "Gourmet treats",
        "Lake Mendota access",
        "Walking path",
      ],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.theedgewater.com",
      phone: "(608) 535-8200",
    },
    {
      name: "Graduate Madison",
      address: "601 Langdon St, Madison, WI 53703",
      lat: 43.0755,
      lng: -89.3951,
      priceRange: "$$$" as const,
      dogPolicy:
        "Fun, university-themed hotel welcoming dogs of all sizes. Quirky decor and a great location near State Street.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: [
        "Dog-friendly rooms",
        "Walking distance to State Street",
        "Lake views",
        "Rooftop bar",
      ],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.graduatehotels.com/madison",
      phone: "(608) 257-4391",
    },
    {
      name: "AC Hotel Madison Downtown",
      address: "18 N Carroll St, Madison, WI 53703",
      lat: 43.0735,
      lng: -89.3843,
      priceRange: "$$$" as const,
      dogPolicy:
        "Modern hotel steps from the Capitol Square. Dogs up to 50 lbs welcome in sleek, pet-friendly rooms.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: [
        "Capitol Square location",
        "Dog bed and bowls",
        "Walking distance to parks",
        "Rooftop lounge",
      ],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(608) 561-5000",
    },
    {
      name: "Best Western Premier Park Hotel",
      address: "22 S Carroll St, Madison, WI 53703",
      lat: 43.0725,
      lng: -89.384,
      priceRange: "$$" as const,
      dogPolicy:
        "Downtown hotel with reasonable rates and a welcoming dog policy. Two pets per room, all sizes.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: [
        "Central location",
        "Pet relief area",
        "Close to Capitol Square",
        "Waste bags",
      ],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(608) 285-8000",
    },
    {
      name: "La Quinta Inn Madison American Center",
      address: "5217 E Terrace Dr, Madison, WI 53718",
      lat: 43.0862,
      lng: -89.306,
      priceRange: "$" as const,
      dogPolicy:
        "Dogs of all sizes stay free — no pet fee and no weight restrictions. La Quinta's famously dog-friendly policy.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: [
        "No pet fee",
        "Grassy area",
        "Waste stations",
        "Free breakfast",
        "Easy highway access",
      ],
      rating: 3.9,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta",
      phone: "(608) 245-0123",
    },
  ],

  nationalParks: [
    {
      name: "Devil's Lake State Park",
      state: "Wisconsin",
      lat: 43.4278,
      lng: -89.7314,
      dogPolicy:
        "Leashed dogs welcome on most trails and in the park. One of Wisconsin's most spectacular natural areas.",
      dogTrails: [
        "East Bluff Trail",
        "West Bluff Trail",
        "Balanced Rock Trail",
        "CCC Trail",
        "Potholes Trail",
      ],
      restrictions: [
        "Dogs must be on a leash no longer than 8 feet",
        "Not permitted on swimming beaches",
        "Not allowed in nature center",
        "Must clean up after pets",
      ],
      description:
        "Wisconsin's most popular state park features dramatic 500-foot quartzite bluffs rising above a pristine lake. Leashed dogs can tackle the bluff trails for breathtaking views, explore rocky formations, and enjoy the forested paths. The views from the top are worth every pant and paw print.",
      imageUrl: "",
      website: "https://dnr.wisconsin.gov/topic/parks/devilslake",
    },
    {
      name: "Governor Nelson State Park",
      state: "Wisconsin",
      lat: 43.1153,
      lng: -89.4606,
      dogPolicy:
        "Leashed dogs welcome on trails and picnic areas. A convenient nature escape right on the shores of Lake Mendota.",
      dogTrails: [
        "Morningside Trail",
        "Woodland Trail",
        "Lakeshore Path",
      ],
      restrictions: [
        "Dogs must be on an 8-foot leash",
        "Not allowed on the beach",
        "Must clean up after pets",
      ],
      description:
        "Just minutes from downtown Madison on the north shore of Lake Mendota, this park offers gentle trails through oak savannas and prairies with lake views. Leashed dogs love the wooded paths and the chance to sniff the lake breeze. Perfect for a quick nature fix without leaving the city.",
      imageUrl: "",
      website: "https://dnr.wisconsin.gov/topic/parks/govnelson",
    },
    {
      name: "Blue Mound State Park",
      state: "Wisconsin",
      lat: 43.024,
      lng: -89.841,
      dogPolicy:
        "Leashed dogs welcome on all trails. The highest point in southern Wisconsin with panoramic views.",
      dogTrails: [
        "Indian Marker Tree Trail",
        "Flint Rock Nature Trail",
        "Ridgeview Trail",
        "Pleasure Valley Trail",
      ],
      restrictions: [
        "Dogs must be on an 8-foot leash",
        "Not allowed in the pool area",
        "Must clean up after pets",
      ],
      description:
        "Perched on the highest point in southern Wisconsin, Blue Mound offers miles of trails through hardwood forests and prairies with sweeping views of the surrounding farmland. Leashed dogs can hike to observation towers and enjoy the cool hilltop breezes. A great autumn destination when the leaves turn.",
      imageUrl: "",
      website: "https://dnr.wisconsin.gov/topic/parks/bluemound",
    },
  ],

  restaurants: [
    {
      name: "The Great Dane Pub & Brewing Co.",
      address: "123 E Doty St, Madison, WI 53703",
      lat: 43.071,
      lng: -89.383,
      cuisine: "Brewery / Pub",
      priceRange: "$$" as const,
      dogPolicy:
        "Named after a dog breed and living up to it! Dogs welcome on the massive outdoor patio and beer garden. A Madison institution.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.greatdanepub.com",
    },
    {
      name: "Olbrich Biergarten",
      address: "3527 Atwood Ave, Madison, WI 53714",
      lat: 43.089,
      lng: -89.338,
      cuisine: "German / Beer Garden",
      priceRange: "$" as const,
      dogPolicy:
        "Outdoor beer garden in beautiful Olbrich Park. Dogs are not only welcome but practically required. Brats, beer, and the best boy — the Madison trifecta.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.olbrichbiergarten.com",
    },
    {
      name: "Eno Vino Wine Bar & Bistro",
      address: "1 S Pinckney St, Madison, WI 53703",
      lat: 43.074,
      lng: -89.383,
      cuisine: "Wine Bar / New American",
      priceRange: "$$$" as const,
      dogPolicy:
        "Rooftop patio with Capitol views where leashed dogs are welcome. Pair a Wisconsin cheese plate with sunset views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.enovino.com",
    },
    {
      name: "Working Draft Beer Company",
      address: "1129 E Wilson St, Madison, WI 53703",
      lat: 43.072,
      lng: -89.373,
      cuisine: "Brewery / Snacks",
      priceRange: "$" as const,
      dogPolicy:
        "Eastside brewery with a dog-friendly taproom and outdoor area. Rotating food trucks and always rotating dogs.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.workingdraftbeer.com",
    },
    {
      name: "Tipsy Cow",
      address: "120 State St, Madison, WI 53703",
      lat: 43.074,
      lng: -89.392,
      cuisine: "Burgers / American",
      priceRange: "$$" as const,
      dogPolicy:
        "State Street burger joint with a patio where dogs are welcome. Wisconsin cheese curds and a happy pup — the perfect combo.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tipsycowmadison.com",
    },
    {
      name: "Cento",
      address: "20 N Carroll St, Madison, WI 53703",
      lat: 43.074,
      lng: -89.384,
      cuisine: "Italian / Wine",
      priceRange: "$$$" as const,
      dogPolicy:
        "Downtown Italian restaurant with sidewalk patio seating. Leashed dogs welcome while you twirl house-made pasta.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.centomadison.com",
    },
    {
      name: "Karben4 Brewing",
      address: "3698 Kinsman Blvd, Madison, WI 53704",
      lat: 43.128,
      lng: -89.323,
      cuisine: "Brewery / Pizza",
      priceRange: "$" as const,
      dogPolicy:
        "Comic-themed brewery with a massive patio and frequent food trucks. Dogs welcome and beer-garden regulars are very social pups.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.karben4.com",
    },
    {
      name: "Sardine",
      address: "617 Williamson St, Madison, WI 53703",
      lat: 43.074,
      lng: -89.375,
      cuisine: "French Bistro",
      priceRange: "$$$" as const,
      dogPolicy:
        "Lakeside French bistro on Lake Monona. Dogs welcome on the terrace with stunning water views at sunset.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.sardinemadison.com",
    },
  ],

  cafes: [
    {
      name: "Colectivo Coffee",
      address: "1 N Webster St, Madison, WI 53703",
      lat: 43.072,
      lng: -89.38,
      dogPolicy:
        "Lakeside café on Lake Monona with a huge outdoor terrace. Dogs are welcome on the patio and it's a favorite gathering spot for Madison's dog community.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.colectivocoffee.com",
    },
    {
      name: "Bradbury's Coffee",
      address: "127 N Hamilton St, Madison, WI 53703",
      lat: 43.075,
      lng: -89.385,
      dogPolicy:
        "Capitol Square coffee shop with outdoor seating. Dogs welcome on the patio steps from the Saturday farmers market.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bradburyscoffee.com",
    },
    {
      name: "Barriques Coffee",
      address: "127 W Washington Ave, Madison, WI 53703",
      lat: 43.073,
      lng: -89.386,
      dogPolicy:
        "Local roaster chain with patio seating downtown. Dogs welcome at outdoor tables while you sip and people-watch on the Capitol Square.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.barriques.com",
    },
    {
      name: "EVP Coffee",
      address: "4618 Monona Dr, Madison, WI 53716",
      lat: 43.058,
      lng: -89.356,
      dogPolicy:
        "Neighborhood coffee shop on the south side with a sunny patio. Dogs welcomed warmly with treats behind the counter.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.evpcoffee.com",
    },
    {
      name: "Aldo's Café",
      address: "117 Martin Luther King Jr Blvd, Madison, WI 53703",
      lat: 43.073,
      lng: -89.386,
      dogPolicy:
        "Classic campus-area café with sidewalk seating where dogs can join for morning coffee and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.aldoscafe.com",
    },
  ],

  dogParks: [
    {
      name: "Warner Park Dog Exercise Area",
      address: "1511 Northport Dr, Madison, WI 53704",
      lat: 43.116,
      lng: -89.362,
      offLeash: true,
      fenced: true,
      acres: 6,
      amenities: [
        "Fenced area",
        "Lake Mendota access",
        "Swimming area",
        "Waste stations",
        "Parking",
        "Water fountain",
      ],
      rating: 4.7,
      imageUrl: "",
      description:
        "One of Madison's best dog parks with direct Lake Mendota access for swimming! Your pup can sprint through the fenced area and then cool off with a dip in the lake. The views of the Capitol across the water are stunning and the dog community is wonderfully social.",
    },
    {
      name: "Brittingham Dog Park",
      address: "829 W Washington Ave, Madison, WI 53715",
      lat: 43.065,
      lng: -89.398,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: [
        "Fenced area",
        "Lake Monona views",
        "Benches",
        "Waste stations",
        "Walking distance to downtown",
      ],
      rating: 4.3,
      imageUrl: "",
      description:
        "A popular downtown-adjacent dog park along Lake Monona. Fenced off-leash area with lake views and a prime location for after-work play sessions. The sunset views over the lake are an added bonus for the humans.",
    },
    {
      name: "Quann Park Dog Park",
      address: "1802 Vilas Ave, Madison, WI 53711",
      lat: 43.056,
      lng: -89.41,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: [
        "Fenced area",
        "Shade trees",
        "Benches",
        "Waste stations",
        "Adjacent to bike path",
      ],
      rating: 4.2,
      imageUrl: "",
      description:
        "A well-loved neighborhood dog park near the Vilas neighborhood. Fully fenced with shade trees and a regular crew of friendly dogs. Adjacent to the Southwest Commuter Path for a leashed walk before or after off-leash playtime.",
    },
    {
      name: "Token Creek Dog Park",
      address: "6200 US-51, DeForest, WI 53532",
      lat: 43.17,
      lng: -89.36,
      offLeash: true,
      fenced: false,
      acres: 20,
      amenities: [
        "Creek access",
        "Wooded trails",
        "Open meadows",
        "Waste stations",
        "Parking lot",
      ],
      rating: 4.6,
      imageUrl: "",
      description:
        "A massive off-leash area in Dane County with creek access, wooded trails, and open meadows. Dogs can splash in Token Creek, explore the forest, and run through the fields. One of the largest off-leash areas near Madison and a favorite for dogs who need space to roam.",
    },
    {
      name: "Sycamore Dog Park",
      address: "4517 Sycamore Ave, Madison, WI 53714",
      lat: 43.1,
      lng: -89.34,
      offLeash: true,
      fenced: true,
      acres: 4,
      amenities: [
        "Separate small and large dog areas",
        "Water spigots",
        "Agility features",
        "Benches",
        "Waste stations",
        "Lighting for evening visits",
      ],
      rating: 4.4,
      imageUrl: "",
      description:
        "A well-designed eastside dog park with separate areas for large and small dogs, agility features, and even lighting for evening visits. Water spigots keep dogs hydrated and the regular crowd is wonderfully welcoming to newcomers.",
    },
  ],
};
