export const malibuData = {
  city: {
    name: "Malibu",
    state: "California",
    region: "West Coast",
    lat: 34.0259,
    lng: -118.7798,
    dogFriendlinessScore: 7,
    description:
      "Malibu's 27 miles of coastline and mountain backdrop create an unparalleled setting for dog adventures. With canyon trails in the Santa Monica Mountains, dog-friendly beaches, and oceanfront restaurants, this iconic beach community delivers a quintessential California dog experience.",
    heroImage: "https://images.unsplash.com/photo-1509233725247-49e657c54213?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 12645,
  },
  hotels: [
    {
      name: "Calamigos Guest Ranch and Beach Club",
      address: "327 Latigo Canyon Rd, Malibu, CA 90265",
      lat: 34.0500,
      lng: -118.7200,
      priceRange: "$$$$" as const,
      dogPolicy: "Luxury ranch retreat in Malibu Canyon welcoming dogs in select cottages. Expansive grounds with canyon trails and a vineyard.",
      maxDogWeight: 50,
      petFee: 150,
      amenities: ["Canyon trails", "Dog bed", "Treats", "Vineyard walks", "Ranch grounds"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.calamigos.com",
      phone: "(310) 589-2211",
    },
    {
      name: "Malibu Beach Inn",
      address: "22878 Pacific Coast Hwy, Malibu, CA 90265",
      lat: 34.0340,
      lng: -118.6850,
      priceRange: "$$$$" as const,
      dogPolicy: "Oceanfront luxury inn with select pet-friendly rooms. Small dogs under 25 lbs welcome on Carbon Beach with advance notice.",
      maxDogWeight: 25,
      petFee: 200,
      amenities: ["Ocean views", "Dog bed", "Beach access", "Water bowls", "Concierge"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.malibubeachinn.com",
      phone: "(310) 456-6444",
    },
    {
      name: "The M Malibu",
      address: "22541 Pacific Coast Hwy, Malibu, CA 90265",
      lat: 34.0355,
      lng: -118.6900,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique motel with ocean views and pet-friendly rooms. Dogs of all sizes welcome at this laid-back PCH property.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Ocean views", "Pet-friendly rooms", "Parking", "Beach access", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.themalibumotorinn.com",
      phone: "(310) 456-6169",
    },
    {
      name: "Malibu Country Inn",
      address: "6506 Westward Beach Rd, Malibu, CA 90265",
      lat: 34.0210,
      lng: -118.8100,
      priceRange: "$$" as const,
      dogPolicy: "Relaxed country-style inn near Zuma Beach with pet-friendly rooms. Easy beach access for dogs in the early morning hours.",
      maxDogWeight: 60,
      petFee: 50,
      amenities: ["Beach proximity", "Garden", "Parking", "Water bowls", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.malibucountryinn.com",
      phone: "(310) 457-9622",
    },
  ],
  nationalParks: [
    {
      name: "Santa Monica Mountains National Recreation Area",
      state: "California",
      lat: 34.0750,
      lng: -118.7500,
      dogPolicy: "Dogs allowed on fire roads and select trails on leash. Extensive trail network through the mountains above Malibu with ocean views.",
      dogTrails: ["Solstice Canyon Fire Road", "Escondido Falls Trail", "Backbone Trail (fire road sections)", "Malibu Creek Fire Road"],
      restrictions: ["6-foot leash required", "Only on fire roads and designated trails", "Not on narrow single-track trails", "Pack out waste"],
      description: "The Santa Monica Mountains rise dramatically above Malibu, offering hundreds of miles of fire roads and trails through chaparral-covered mountains. Dogs can hike to waterfalls, ocean viewpoints, and through peaceful canyons.",
      imageUrl: "",
      website: "https://www.nps.gov/samo",
    },
    {
      name: "Malibu Creek State Park",
      state: "California",
      lat: 34.1000,
      lng: -118.7300,
      dogPolicy: "Dogs allowed on the Crags Road fire road and in the campground on leash. Not permitted on single-track hiking trails.",
      dogTrails: ["Crags Road", "High Road (fire road)", "Campground Loop"],
      restrictions: ["6-foot leash required", "Only on fire roads", "Not allowed in swimming areas", "Day use fee required"],
      description: "Famous as the filming location for M*A*S*H, this state park offers beautiful canyon scenery with a creek, rock pools, and mountain views. Dogs can join on the main fire roads through the park's scenic terrain.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/malibucreek",
    },
    {
      name: "Point Mugu State Park",
      state: "California",
      lat: 34.0800,
      lng: -118.9800,
      dogPolicy: "Dogs allowed on fire roads on leash. Not permitted on beaches or single-track trails. Dramatic coastal canyon scenery.",
      dogTrails: ["La Jolla Canyon Fire Road", "Big Sycamore Canyon Fire Road"],
      restrictions: ["6-foot leash required", "Not allowed on beaches", "Fire roads only", "Day use fee required"],
      description: "At the western end of Malibu, Point Mugu offers dramatic coastal canyons and mountain terrain. The Big Sycamore Canyon fire road is a scenic walk through a sycamore-lined canyon that dogs enjoy on leash.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/pointmugu",
    },
  ],
  restaurants: [
    {
      name: "Nobu Malibu",
      address: "22706 Pacific Coast Hwy, Malibu, CA 90265",
      lat: 34.0350,
      lng: -118.6880,
      cuisine: "Japanese",
      priceRange: "$$$$" as const,
      dogPolicy: "Iconic oceanfront restaurant with a terrace where well-behaved small dogs may be accommodated. World-famous Japanese cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.noburestaurants.com/malibu",
    },
    {
      name: "Malibu Farm Restaurant",
      address: "23000 Pacific Coast Hwy, Malibu, CA 90265",
      lat: 34.0340,
      lng: -118.6830,
      cuisine: "Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Farm-to-table restaurant on the Malibu Pier with an outdoor area where dogs are welcome. Organic, locally sourced dishes with ocean views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.malibufarm.com",
    },
    {
      name: "Malibu Seafood Fresh Fish Market",
      address: "25653 Pacific Coast Hwy, Malibu, CA 90265",
      lat: 34.0400,
      lng: -118.7400,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Casual counter-service seafood market with outdoor picnic tables overlooking the ocean. Dogs welcome at outdoor seating.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.malibuseafood.com",
    },
    {
      name: "Reel Inn",
      address: "18661 Pacific Coast Hwy, Malibu, CA 90265",
      lat: 34.0280,
      lng: -118.6300,
      cuisine: "Seafood",
      priceRange: "$" as const,
      dogPolicy: "No-frills PCH seafood shack with outdoor picnic tables where dogs are always welcome. Fresh grilled fish in a casual beach setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.reelinnmalibu.com",
    },
    {
      name: "Lily's Malibu",
      address: "29169 Heathercliff Rd, Malibu, CA 90265",
      lat: 34.0320,
      lng: -118.8300,
      cuisine: "American Café",
      priceRange: "$$" as const,
      dogPolicy: "Neighborhood café with a garden patio welcoming dogs. Fresh salads, sandwiches, and baked goods in Point Dume.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.lilysmalibu.com",
    },
  ],
  cafes: [
    {
      name: "Malibu Farm Café",
      address: "23000 Pacific Coast Hwy, Malibu, CA 90265",
      lat: 34.0340,
      lng: -118.6835,
      dogPolicy: "Casual café outpost on the Malibu Pier with outdoor seating and ocean views. Dogs welcome on the pier-side patio.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.malibufarm.com",
    },
    {
      name: "Caffe Luxxe",
      address: "3535 Cross Creek Rd, Malibu, CA 90265",
      lat: 34.0310,
      lng: -118.6940,
      dogPolicy: "Premium café in the Malibu Country Mart with outdoor seating where dogs are welcome. Artisan espresso and Italian pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.caffeluxxe.com",
    },
    {
      name: "Coyote Coffee",
      address: "22601 Pacific Coast Hwy, Malibu, CA 90265",
      lat: 34.0357,
      lng: -118.6905,
      dogPolicy: "Casual PCH coffee stop with outdoor seating and a welcoming attitude toward dogs. Quick espresso and pastries for beachgoers.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.coyotecoffee.com",
    },
    {
      name: "SunLife Organics",
      address: "29169 Heathercliff Rd, Malibu, CA 90265",
      lat: 34.0322,
      lng: -118.8305,
      dogPolicy: "Organic superfood café with an outdoor patio in Point Dume. Dogs welcome while you enjoy acai bowls and cold-pressed juices.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.sunlifeorganics.com",
    },
  ],
  dogParks: [
    {
      name: "Malibu Bluffs Park",
      address: "24250 Pacific Coast Hwy, Malibu, CA 90265",
      lat: 34.0350,
      lng: -118.7150,
      offLeash: false,
      fenced: false,
      acres: 10,
      amenities: ["Ocean views", "Walking paths", "Picnic areas", "Restrooms", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description: "A blufftop park with stunning ocean views where leashed dogs can enjoy walking paths along the cliffs. The wide-open grassy areas and Pacific panoramas make it a scenic spot for a dog walk.",
    },
    {
      name: "Point Dume State Beach",
      address: "29000 Cliffside Dr, Malibu, CA 90265",
      lat: 34.0010,
      lng: -118.8060,
      offLeash: false,
      fenced: false,
      acres: 5,
      amenities: ["Beach access", "Tide pools", "Scenic cliffs", "Parking", "Trail"],
      rating: 4.6,
      imageUrl: "",
      description: "While dogs must be on leash, Point Dume offers a dramatic headland with tide pools and beach access. Early morning visits allow dogs to explore this stunning stretch of Malibu coastline before the crowds arrive.",
    },
    {
      name: "Escondido Falls Trail Area",
      address: "27200 Winding Way, Malibu, CA 90265",
      lat: 34.0500,
      lng: -118.7600,
      offLeash: false,
      fenced: false,
      acres: 25,
      amenities: ["Waterfall trail", "Canyon scenery", "Shade", "Parking", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "A scenic trail through a lush canyon to a 150-foot waterfall in the Santa Monica Mountains. Leashed dogs can enjoy the shaded canyon walk and the cool mist near the falls during wet season.",
    },
    {
      name: "Leo Carrillo State Park Beach",
      address: "35000 W Pacific Coast Hwy, Malibu, CA 90265",
      lat: 34.0450,
      lng: -118.9350,
      offLeash: false,
      fenced: false,
      acres: 8,
      amenities: ["Beach access", "Tide pools", "Sea caves", "Camping", "Restrooms"],
      rating: 4.5,
      imageUrl: "",
      description: "At the far western end of Malibu, Leo Carrillo allows leashed dogs on the beach north of Lifeguard Tower 3. The dramatic sea caves, tide pools, and rocky shoreline create an adventurous beach experience for dogs.",
    },
  ],
};
