export const marfaData = {
  city: {
    name: "Marfa",
    state: "Texas",
    region: "Southwest",
    lat: 30.3087,
    lng: -104.0214,
    dogFriendlinessScore: 8,
    description:
      "Marfa is a tiny West Texas art town where dogs roam as freely as the creative spirit. This remote desert outpost combines minimalist art installations, stunning Chihuahuan Desert landscapes, and a laid-back culture where dogs are welcome virtually everywhere in town.",
    heroImage: "https://images.unsplash.com/photo-1518128958364-65859d70aa41?w=1200&fit=crop",
    climate: "Semi-arid",
    population: 1831,
  },

  hotels: [
    {
      name: "Hotel Saint George",
      address: "105 S Highland Ave, Marfa, TX 79843",
      lat: 30.3080,
      lng: -104.0210,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with a pet fee. Minimalist luxury in the heart of Marfa.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Walking maps", "Rooftop pool", "Downtown location"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.marfahotel.com",
      phone: "(432) 729-3700",
    },
    {
      name: "El Cosmico",
      address: "802 S Highland Ave, Marfa, TX 79843",
      lat: 30.3030,
      lng: -104.0210,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in most accommodations with a pet fee. Glamping and vintage trailers in the desert.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Open desert space", "Campfire areas", "Walking paths", "Stars viewing", "Community kitchen"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.elcosmico.com",
      phone: "(432) 729-1950",
    },
    {
      name: "Thunderbird Hotel",
      address: "601 W San Antonio St, Marfa, TX 79843",
      lat: 30.3090,
      lng: -104.0260,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a pet deposit. Mid-century modern roadside hotel with desert vibes.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Courtyard", "Desert landscape", "Walking distance to town", "Outdoor seating"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thunderbirdmarfa.com",
      phone: "(432) 729-1984",
    },
    {
      name: "Riata Inn Marfa",
      address: "400 E Lincoln St, Marfa, TX 79843",
      lat: 30.3085,
      lng: -104.0170,
      priceRange: "$" as const,
      dogPolicy: "Pets welcome with a small nightly fee. Basic, clean accommodations.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Grassy area", "Parking", "Walking distance to town", "Waste bags"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.riatainnmarfa.com",
      phone: "(432) 729-3800",
    },
  ],

  nationalParks: [
    {
      name: "Big Bend National Park",
      state: "Texas",
      lat: 29.2498,
      lng: -103.2502,
      dogPolicy: "Dogs allowed on paved roads, in campgrounds, and along the Rio Grande Village Nature Trail.",
      dogTrails: ["Rio Grande Village Nature Trail (paved)", "Campground roads"],
      restrictions: [
        "Must be on a 6-foot leash at all times",
        "Not allowed on any dirt trails or in the backcountry",
        "Not permitted on the Window Trail, Lost Mine Trail, etc.",
        "Extreme heat - carry water and limit exposure",
      ],
      description:
        "About three hours south of Marfa, Big Bend's dramatic desert and river canyon landscape is awe-inspiring. While dog access to trails is very limited, the scenic drives and riverside areas offer a taste of this wild frontier.",
      imageUrl: "",
      website: "https://www.nps.gov/bibe",
    },
    {
      name: "Davis Mountains State Park",
      state: "Texas",
      lat: 30.5960,
      lng: -103.9280,
      dogPolicy: "Leashed dogs welcome on all trails and in campgrounds. A cool mountain retreat in West Texas.",
      dogTrails: ["Skyline Drive Trail", "CCC Trail", "Montezuma Quail Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed at McDonald Observatory events",
        "Carry water on trails",
      ],
      description:
        "About 30 minutes north of Marfa, the Davis Mountains offer some of the best hiking in West Texas at elevations above 5,000 feet. The cooler mountain air is a welcome relief for hiking dogs.",
      imageUrl: "",
      website: "https://www.tpwd.texas.gov/state-parks/davis-mountains",
    },
    {
      name: "Chinati Mountains State Natural Area",
      state: "Texas",
      lat: 30.0500,
      lng: -104.3200,
      dogPolicy: "Leashed dogs welcome on guided tours only. A remote and rugged natural area south of Marfa.",
      dogTrails: ["Guided hike routes only"],
      restrictions: [
        "Must be on leash",
        "Access by reservation and guided tour only",
        "Extremely remote - no services",
      ],
      description:
        "One of the most remote and wild state natural areas in Texas, the Chinati Mountains offer stark desert beauty accessible only by guided tour. Dogs can join on these infrequent but remarkable excursions.",
      imageUrl: "",
      website: "https://www.tpwd.texas.gov/state-parks/chinati-mountains",
    },
  ],

  restaurants: [
    {
      name: "Food Shark",
      address: "100 E San Antonio St, Marfa, TX 79843",
      lat: 30.3090,
      lng: -104.0200,
      cuisine: "Mediterranean Food Truck",
      priceRange: "$" as const,
      dogPolicy: "Very dog-friendly with outdoor seating. Legendary Marfa food truck with falafel and shawarma.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.foodsharkmarfa.com",
    },
    {
      name: "Stellina",
      address: "300 E San Antonio St, Marfa, TX 79843",
      lat: 30.3090,
      lng: -104.0180,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the patio. Wood-fired pizza and pasta in the desert.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.stellinamarfa.com",
    },
    {
      name: "The Capri",
      address: "310 N Highland Ave, Marfa, TX 79843",
      lat: 30.3100,
      lng: -104.0210,
      cuisine: "New American",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome in the outdoor dining area. Creative cuisine in a desert setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thecaprimarfa.com",
    },
    {
      name: "Do Your Thing Coffee",
      address: "209 W San Antonio St, Marfa, TX 79843",
      lat: 30.3088,
      lng: -104.0225,
      cuisine: "Coffee & Light Fare",
      priceRange: "$" as const,
      dogPolicy: "Dogs always welcome at this laid-back Marfa spot. Coffee, pastries, and good vibes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.doyourthingcoffee.com",
    },
    {
      name: "Jett's Grill at Hotel Paisano",
      address: "207 N Highland Ave, Marfa, TX 79843",
      lat: 30.3095,
      lng: -104.0210,
      cuisine: "Southwest American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the courtyard patio of this historic hotel where Giant was filmed.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hotelpaisano.com",
    },
  ],

  cafes: [
    {
      name: "Do Your Thing Coffee",
      address: "209 W San Antonio St, Marfa, TX 79843",
      lat: 30.3088,
      lng: -104.0225,
      dogPolicy: "Dogs welcome at all times. A true Marfa community gathering spot.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.doyourthingcoffee.com",
    },
    {
      name: "Frama Coffee",
      address: "100 Highland Ave, Marfa, TX 79843",
      lat: 30.3085,
      lng: -104.0212,
      dogPolicy: "Outdoor seating welcomes dogs. Specialty coffee in a minimalist space.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.framacoffee.com",
    },
    {
      name: "The Sentinel",
      address: "100 E San Antonio St, Marfa, TX 79843",
      lat: 30.3090,
      lng: -104.0200,
      dogPolicy: "Dogs welcome at outdoor tables. Coffee and community publications.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.thesentinelmarfa.com",
    },
    {
      name: "Squeeze Marfa",
      address: "215 N Highland Ave, Marfa, TX 79843",
      lat: 30.3097,
      lng: -104.0210,
      dogPolicy: "Leashed dogs welcome outside. Fresh juices, smoothies, and coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.squeezemarfa.com",
    },
  ],

  dogParks: [
    {
      name: "Marfa Lights Viewing Area",
      address: "US-90 E, Marfa, TX 79843",
      lat: 30.3260,
      lng: -103.9400,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Viewing platform", "Benches", "Restrooms", "Parking", "Desert views"],
      rating: 4.5,
      imageUrl: "",
      description:
        "The famous Marfa Lights viewing area east of town is dog-friendly and offers stunning sunset views. Bring your pup to watch for the mysterious lights that have appeared in the desert for generations.",
    },
    {
      name: "Marfa City Park",
      address: "111 W Lincoln St, Marfa, TX 79843",
      lat: 30.3080,
      lng: -104.0230,
      offLeash: true,
      fenced: false,
      acres: 3.0,
      amenities: ["Open field", "Shade trees", "Benches", "Near downtown", "Playground"],
      rating: 4.2,
      imageUrl: "",
      description:
        "Marfa's main town park where dogs often play off-leash in the open fields. The small-town atmosphere means dogs and their owners are on friendly terms with everyone.",
    },
    {
      name: "Vizcaino Park",
      address: "S Austin St, Marfa, TX 79843",
      lat: 30.3050,
      lng: -104.0200,
      offLeash: true,
      fenced: false,
      acres: 4.0,
      amenities: ["Open space", "Walking paths", "Mountain views", "Quiet setting", "Parking"],
      rating: 4.1,
      imageUrl: "",
      description:
        "A quiet park on the south side of Marfa with open desert views and space for dogs to run. The relaxed Marfa attitude means dogs enjoy a freedom rare in most towns.",
    },
    {
      name: "Highland Avenue Walk",
      address: "N Highland Ave, Marfa, TX 79843",
      lat: 30.3095,
      lng: -104.0210,
      offLeash: false,
      fenced: false,
      acres: 2.0,
      amenities: ["Art galleries", "Shops", "Restaurants", "Sidewalk walking", "Prada Marfa access"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Marfa's main street is itself a dog-friendly attraction, with galleries, shops, and restaurants all welcoming leashed dogs. The laid-back culture makes every walk through town a social event for pups.",
    },
  ],
};
