export const marquetteData = {
  city: {
    name: "Marquette",
    state: "Michigan",
    region: "Midwest",
    lat: 46.5436,
    lng: -87.3954,
    dogFriendlinessScore: 7,
    description:
      "Marquette is the rugged, beautiful heart of Michigan's Upper Peninsula, perched on the shores of Lake Superior where the water is impossibly blue and the sunsets are pure fire. This outdoorsy college town has miles of trails through boreal forest, red sandstone beaches where dogs can splash, and a downtown packed with breweries and cafes that keep treats behind the counter. If your dog loves swimming, snow, or just wild places, Marquette is their kind of town. Yoopers love their dogs, and it shows.",
    heroImage: "https://images.unsplash.com/photo-1517483000871-1dbf64a6e1c6?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 20629,
  },

  hotels: [
    {
      name: "Landmark Inn",
      address: "230 N Front St, Marquette, MI 49855",
      lat: 46.5465,
      lng: -87.3940,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in pet-friendly rooms at this beautifully restored 1930s hotel on the Lake Superior shore. Walking distance to everything downtown.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowl", "Lakefront walking", "Historic building", "Near downtown"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thelandmarkinn.com",
      phone: "(906) 228-2580",
    },
    {
      name: "Ramada by Wyndham Marquette",
      address: "412 W Washington St, Marquette, MI 49855",
      lat: 46.5430,
      lng: -87.4020,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a per-night pet fee. Reliable and comfortable with easy access to trails and downtown.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Dog bed on request", "Grassy walking area", "Waste bags", "Near Fit Strip trail"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/ramada",
      phone: "(906) 228-6000",
    },
    {
      name: "Country Inn & Suites Marquette",
      address: "2472 US-41 W, Marquette, MI 49855",
      lat: 46.5380,
      lng: -87.4380,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms available. Close to shopping and the Marquette Mountain ski area.",
      maxDogWeight: 75,
      petFee: 35,
      amenities: ["Dog bed", "Bowls", "Outdoor walking area", "Near hiking trails"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.countryinn.com",
      phone: "(906) 228-3100",
    },
    {
      name: "Blueberry Ridge Mountain Lodge",
      address: "1400 CR 510, Marquette, MI 49855",
      lat: 46.5800,
      lng: -87.3300,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in cabin-style rooms at this mountain lodge surrounded by forest trails. Your pup will think they have moved to paradise.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Trail access from door", "Forest setting", "Outdoor wash station", "Fire pit"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.blueberryridgemtb.com",
      phone: "(906) 228-5573",
    },
    {
      name: "Holiday Inn Marquette",
      address: "1951 US-41 W, Marquette, MI 49855",
      lat: 46.5400,
      lng: -87.4250,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a one-time pet fee. Indoor pool, lakeside location, and plenty of grassy area for walks.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Dog bed", "Waste bags", "Lakeside walking path", "Grassy areas"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.ihg.com/holidayinn",
      phone: "(906) 225-1351",
    },
  ],

  nationalParks: [
    {
      name: "Pictured Rocks National Lakeshore",
      state: "Michigan",
      lat: 46.5678,
      lng: -86.3187,
      dogPolicy: "Leashed dogs allowed on a few trails and beaches. The most spectacular shoreline on the Great Lakes, though dog access is limited.",
      dogTrails: ["Sand Point Beach area", "Miners Beach", "Twelvemile Beach"],
      restrictions: [
        "Dogs not allowed on North Country Trail within the park",
        "Must be on leash (6 ft max) at all times",
        "Not allowed on most hiking trails",
        "Not allowed on boat tours",
      ],
      description:
        "About an hour east of Marquette, these multicolored sandstone cliffs towering over Lake Superior are one of America's most stunning landscapes. While trail access for dogs is limited, the beaches welcome leashed pups, and Miners Beach offers unforgettable Lake Superior swimming for brave, cold-water-loving dogs.",
      imageUrl: "",
      website: "https://www.nps.gov/piro",
    },
    {
      name: "Hiawatha National Forest",
      state: "Michigan",
      lat: 46.3500,
      lng: -86.5000,
      dogPolicy: "Dogs welcome on all trails, with leash requirements varying by area. Nearly a million acres of Upper Peninsula wilderness.",
      dogTrails: ["Au Train Songbird Trail", "Bruno's Run Trail", "Grand Island Loop", "Bay de Noc - Grand Island Trail"],
      restrictions: [
        "Must be on leash in developed campgrounds",
        "Voice control required on most trails",
        "Check regulations for specific wilderness areas",
      ],
      description:
        "A vast national forest southeast of Marquette encompassing pristine lakes, rivers, waterfalls, and Great Lakes shoreline. Your dog can hike through old-growth hardwoods, splash in waterfalls, and explore wild Lake Superior beaches. This is Upper Peninsula dog adventure at its finest.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/hiawatha",
    },
    {
      name: "Isle Royale National Park",
      state: "Michigan",
      lat: 47.9959,
      lng: -88.9093,
      dogPolicy: "Dogs are not allowed on Isle Royale, including on trails, in the backcountry, or on island shores. One of the strictest no-dog policies in the NPS system.",
      dogTrails: [],
      restrictions: [
        "No dogs allowed anywhere on the island",
        "Service animals only",
        "Dogs not allowed on ferries to the island",
      ],
      description:
        "This remote wilderness island in Lake Superior is a no-go for dogs, but it is worth mentioning as it is Michigan's only national park. The wolf and moose ecosystem requires strict pet restrictions. Explore the mainland shores of Lake Superior with your pup instead.",
      imageUrl: "",
      website: "https://www.nps.gov/isro",
    },
    {
      name: "Marquette South Trails (Iron Ore Heritage Trail)",
      state: "Michigan",
      lat: 46.5300,
      lng: -87.4100,
      dogPolicy: "Leashed dogs welcome on all trails. A network of multi-use trails through Marquette's mining heritage landscape.",
      dogTrails: ["Iron Ore Heritage Trail", "Clark Lambros Beach Trail", "Fit Strip", "Noquemanon South Trails"],
      restrictions: [
        "Must be on leash on paved trails",
        "Voice control on mountain bike trails (check current rules)",
      ],
      description:
        "A fantastic network of trails right in Marquette that follows old mining railways and forest paths. Your dog can hike or run alongside you on miles of singletrack, paved rail-trail, and forest roads. The mining heritage adds a layer of history to every adventure.",
      imageUrl: "",
      website: "https://www.ironoreheritage.com",
    },
  ],

  restaurants: [
    {
      name: "Blackrocks Brewery",
      address: "424 N 3rd St, Marquette, MI 49855",
      lat: 46.5475,
      lng: -87.3925,
      cuisine: "Brewery",
      priceRange: "$" as const,
      dogPolicy: "Dogs rule the outdoor area at this beloved Marquette brewery. The house-turned-brewery vibe is as welcoming to pups as it is to humans.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.blackrocksbrewery.com",
    },
    {
      name: "Ore Dock Brewing Company",
      address: "114 Spring St, Marquette, MI 49855",
      lat: 46.5455,
      lng: -87.3945,
      cuisine: "Brewery & Food Trucks",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly outdoor beer garden with rotating food trucks. Craft beer culture meets UP outdoor culture in the best possible way.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.oredockbrewingcompany.com",
    },
    {
      name: "The Vierling Restaurant & Marquette Harbor Brewery",
      address: "119 S Front St, Marquette, MI 49855",
      lat: 46.5440,
      lng: -87.3930,
      cuisine: "American & Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the lakefront patio with views of the Marquette harbor and ore dock. Fresh Lake Superior whitefish is the move.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thevierling.com",
    },
    {
      name: "Iron Bay Restaurant & Drinkery",
      address: "400 S Front St, Marquette, MI 49855",
      lat: 46.5420,
      lng: -87.3920,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor terrace overlooking Lake Superior. Upscale lakeside dining in a converted railroad depot.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ironbayrestaurant.com",
    },
    {
      name: "Lagniappe Cajun Creole",
      address: "145 Jackson St, Marquette, MI 49855",
      lat: 46.5445,
      lng: -87.3960,
      cuisine: "Cajun & Creole",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio. A taste of New Orleans in the Upper Peninsula, with gumbo, jambalaya, and a Southern hospitality that extends to four-legged friends.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.lagniappemarquette.com",
    },
    {
      name: "Steinhaus",
      address: "100 Spring St, Marquette, MI 49855",
      lat: 46.5453,
      lng: -87.3948,
      cuisine: "German & American",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly outdoor seating area. German-inspired comfort food and a solid beer selection to warm you up after a Lake Superior hike.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.steinhausmarquette.com",
    },
    {
      name: "The Bodega",
      address: "315 S Front St, Marquette, MI 49855",
      lat: 46.5430,
      lng: -87.3925,
      cuisine: "Mediterranean Deli",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor counter window. Fresh wraps, salads, and deli sandwiches perfect for packing on a trail hike.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thebodegamarquette.com",
    },
    {
      name: "Portside Inn",
      address: "239 W Washington St, Marquette, MI 49855",
      lat: 46.5435,
      lng: -87.3985,
      cuisine: "American Comfort Food",
      priceRange: "$" as const,
      dogPolicy: "Casual outdoor seating where dogs are welcome. A Marquette classic for burgers, fish fry, and a cold beer after a long day on the trails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.portsideinn.net",
    },
  ],

  cafes: [
    {
      name: "Dead River Coffee",
      address: "119 W Washington St, Marquette, MI 49855",
      lat: 46.5440,
      lng: -87.3965,
      dogPolicy: "Marquette's favorite coffee shop with a front patio where dogs are always welcome. Locally roasted beans and a warm UP community feel.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.deadrivercoffee.com",
    },
    {
      name: "Velodrome Coffee Company",
      address: "229 W Washington St, Marquette, MI 49855",
      lat: 46.5438,
      lng: -87.3980,
      dogPolicy: "Bicycle-themed cafe with outdoor seating. Dogs and bikes create the most Marquette scene imaginable.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.velodromecoffee.com",
    },
    {
      name: "Contrast Coffee",
      address: "326 N 3rd St, Marquette, MI 49855",
      lat: 46.5468,
      lng: -87.3930,
      dogPolicy: "Specialty coffee roaster with a small outdoor area where pups are welcome. Precision-brewed coffee for the discerning UP explorer.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.contrastcoffee.com",
    },
    {
      name: "Huron Mountain Bakery",
      address: "1301 S Front St, Marquette, MI 49855",
      lat: 46.5350,
      lng: -87.3880,
      dogPolicy: "Beloved local bakery with outdoor benches. Grab a cinnamon roll the size of your head and enjoy it with your pup in the Lake Superior breeze.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.huronmountainbakery.com",
    },
    {
      name: "Marquette Baking Company",
      address: "117 W Front St, Marquette, MI 49855",
      lat: 46.5455,
      lng: -87.3950,
      dogPolicy: "Artisan bakery with sidewalk seating overlooking the harbor. Dogs are welcome at the outdoor tables while you enjoy fresh bread and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marquettebaking.com",
    },
  ],

  dogParks: [
    {
      name: "Marquette Dog Park (Harlow Park)",
      address: "Harlow Park, Marquette, MI 49855",
      lat: 46.5500,
      lng: -87.3880,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water stations", "Shade trees", "Waste stations", "Benches", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Marquette's primary off-leash dog park is well-maintained and popular with locals. Separate areas for large and small dogs, plus a shaded rest area for tired pups. The community here is friendly and welcoming, and summer evenings see a full house of happy dogs.",
    },
    {
      name: "Presque Isle Park",
      address: "Peter White Dr, Marquette, MI 49855",
      lat: 46.5790,
      lng: -87.3860,
      offLeash: false,
      fenced: false,
      acres: 323.0,
      amenities: ["Lake Superior shoreline", "Forest trails", "Rocky beach", "Scenic drive", "Bog walk", "Waste stations"],
      rating: 4.9,
      imageUrl: "",
      description:
        "A breathtaking peninsula jutting into Lake Superior with a loop road, forest trails, and dramatic rocky shoreline. Leashed dogs can explore the entire park, from ancient rock formations to dense boreal forest. The sunset views from the north end are some of the most spectacular in the entire Great Lakes region.",
    },
    {
      name: "South Beach (Marquette Lower Harbor)",
      address: "Lakeshore Blvd, Marquette, MI 49855",
      lat: 46.5410,
      lng: -87.3810,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Sandy beach", "Lake Superior swimming", "Walking path", "Parking", "Restrooms"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A beautiful sandy beach on Lake Superior where leashed dogs can wade in the crystal-clear water and dig in the sand. The lake is cold year-round, but dogs do not seem to mind one bit. The beach walk with the Marquette Harbor Lighthouse in view is unforgettable.",
    },
    {
      name: "Noquemanon Trail Network",
      address: "County Rd 510, Marquette, MI 49855",
      lat: 46.5600,
      lng: -87.3500,
      offLeash: false,
      fenced: false,
      acres: 200.0,
      amenities: ["Mountain bike trails", "Hiking trails", "Forest setting", "Creek crossings", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "An extensive trail network through Marquette's backcountry forest that is world-class for mountain biking and equally incredible for dog hiking. Leashed dogs tackle the rolling singletrack through maple and birch forest, crossing creeks and scrambling over roots. Pure UP adventure.",
    },
    {
      name: "Tourist Park",
      address: "2145 Sugar Loaf Ave, Marquette, MI 49855",
      lat: 46.5280,
      lng: -87.4300,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Dead River falls", "Swimming hole", "Forest trails", "Picnic areas", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A beautiful park along the Dead River with a waterfall, swimming hole, and forest trails. Leashed dogs love splashing in the river below the falls, and the shaded picnic area is perfect for a post-hike rest. A Marquette classic that every dog should experience.",
    },
  ],
};
