export const mccallData = {
  city: {
    name: "McCall",
    state: "Idaho",
    region: "Mountain West",
    lat: 44.7321,
    lng: -116.0988,
    dogFriendlinessScore: 8,
    description:
      "McCall is a mountain lake town on the shores of Payette Lake surrounded by the Payette National Forest. Dogs are everywhere in this outdoor recreation paradise, enjoying beach days, forest trails, and a walkable downtown with dog-friendly restaurants. The Winter Carnival and summer water activities make McCall a year-round dog destination.",
    heroImage: "https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=1200&fit=crop",
    climate: "Humid continental",
    population: 3686,
  },

  hotels: [
    {
      name: "Shore Lodge",
      address: "501 W Lake St, McCall, ID 83638",
      lat: 44.7330,
      lng: -116.1020,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in select lakeside rooms with a per-stay pet fee. Premier resort on Payette Lake.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Lake access", "Walking paths", "Water bowls"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.shorelodge.com",
      phone: "(208) 634-2244",
    },
    {
      name: "Hotel McCall",
      address: "1101 N 3rd St, McCall, ID 83638",
      lat: 44.7350,
      lng: -116.0970,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome. Boutique hotel with mountain lodge ambiance.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Dog bed", "Water bowls", "Near beach", "Walking map", "Downtown location"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelmccall.com",
      phone: "(208) 634-8105",
    },
    {
      name: "Best Western Plus McCall Lodge & Suites",
      address: "211 S 3rd St, McCall, ID 83638",
      lat: 44.7310,
      lng: -116.0975,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 80 lbs welcome with a per-night fee. Comfortable hotel near downtown.",
      maxDogWeight: 80,
      petFee: 25,
      amenities: ["Pet waste stations", "Grassy areas", "Near lake", "Water bowls"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(208) 634-2230",
    },
    {
      name: "Brundage Bungalows",
      address: "1005 W Lake St, McCall, ID 83638",
      lat: 44.7325,
      lng: -116.1060,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in cabins with fenced yards. Private cabins near the lake.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Fenced yards", "Lake proximity", "BBQ grills", "Dog bed", "Water bowls"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.brundagebungalows.com",
      phone: "(208) 634-3223",
    },
  ],

  nationalParks: [
    {
      name: "Payette National Forest",
      state: "Idaho",
      lat: 44.8000,
      lng: -116.1000,
      dogPolicy: "Dogs welcome on all trails. Voice control in backcountry; leash in developed areas.",
      dogTrails: ["Lick Creek Trail", "Bear Basin Trail", "Duck Lake Trail", "Brundage Mountain trails"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on trails",
        "Be aware of wildlife",
      ],
      description:
        "The vast national forest surrounding McCall offers alpine lakes, mountain meadows, and deep forest trails. The hiking is exceptional with options from easy lakeside walks to challenging mountain summit scrambles.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/payette",
    },
    {
      name: "Frank Church-River of No Return Wilderness",
      state: "Idaho",
      lat: 44.9000,
      lng: -115.2000,
      dogPolicy: "Dogs welcome off-leash under voice control. The largest wilderness area in the contiguous US.",
      dogTrails: ["Loon Creek Trail", "Big Creek Trail", "Middle Fork Salmon River Trail"],
      restrictions: [
        "Must be under voice control",
        "Pack out all waste",
        "Be prepared for remote conditions",
        "Bear awareness required",
      ],
      description:
        "At 2.4 million acres, this is the largest contiguous wilderness in the lower 48. Dogs can explore truly wild country with their owners on trails that follow the Middle Fork of the Salmon River through deep canyons.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/payette",
    },
    {
      name: "Ponderosa State Park",
      state: "Idaho",
      lat: 44.7400,
      lng: -116.1100,
      dogPolicy: "Leashed dogs welcome on trails and in the campground. Peninsula park on Payette Lake.",
      dogTrails: ["Meadow Marsh Nature Trail", "Lily Marsh Trail", "Peninsula Trail", "Huckleberry Bay Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed on swim beaches",
        "Clean up after your pet",
      ],
      description:
        "A stunning state park on a peninsula in Payette Lake with forested trails, lake views, and wildlife viewing. Leashed dogs enjoy miles of trails through ponderosa pine forest with lake access.",
      imageUrl: "",
      website: "https://parksandrecreation.idaho.gov/parks/ponderosa",
    },
  ],

  restaurants: [
    {
      name: "Broken Horn Brewing Company",
      address: "401 Railroad Ave, McCall, ID 83638",
      lat: 44.7318,
      lng: -116.0965,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Local craft brewery with mountain-town food.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.brokenhornbrewing.com",
    },
    {
      name: "Fogglifter Cafe",
      address: "203 E Lake St, McCall, ID 83638",
      lat: 44.7322,
      lng: -116.0960,
      cuisine: "Cafe & Brunch",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio. Popular brunch spot with lake views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.foggliftercafe.com",
    },
    {
      name: "My Father's Place",
      address: "901 N 3rd St, McCall, ID 83638",
      lat: 44.7345,
      lng: -116.0972,
      cuisine: "Italian & American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor deck. Family-owned Italian restaurant since the 1970s.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.myfathersplacemccall.com",
    },
    {
      name: "Salmon River Brewery",
      address: "300 Commerce St, McCall, ID 83638",
      lat: 44.7315,
      lng: -116.0970,
      cuisine: "Brewpub & Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio. Craft beer and wood-fired pizza in a casual atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.salmonriverbrewery.com",
    },
    {
      name: "The Cutwater",
      address: "501 W Lake St, McCall, ID 83638",
      lat: 44.7332,
      lng: -116.1022,
      cuisine: "Pacific Northwest Fine Dining",
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome on the lakeside terrace. Upscale dining with Payette Lake views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.shorelodge.com/dining",
    },
  ],

  cafes: [
    {
      name: "Stacey's Espresso & Coffee",
      address: "207 E Lake St, McCall, ID 83638",
      lat: 44.7323,
      lng: -116.0958,
      dogPolicy: "Dogs welcome on the patio. McCall's go-to morning coffee stop.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.staceyscoffee.com",
    },
    {
      name: "Mountain Java",
      address: "300 E Lake St, McCall, ID 83638",
      lat: 44.7320,
      lng: -116.0950,
      dogPolicy: "Outdoor seating welcomes dogs. Drive-through and walk-up coffee with lake views.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.mountainjava.com",
    },
    {
      name: "Ice Cream Alley",
      address: "305 E Lake St, McCall, ID 83638",
      lat: 44.7321,
      lng: -116.0948,
      dogPolicy: "Dog-friendly outdoor seating. Homemade ice cream with a doggy dish option.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.icecreamalley.com",
    },
    {
      name: "Steamers Steak & Seafood",
      address: "309 E Lake St, McCall, ID 83638",
      lat: 44.7321,
      lng: -116.0945,
      dogPolicy: "Leashed dogs welcome at patio tables. Morning coffee service before the dinner crowd.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.steamersmccall.com",
    },
  ],

  dogParks: [
    {
      name: "McCall Dog Park",
      address: "Davis Ave, McCall, ID 83638",
      lat: 44.7280,
      lng: -116.0960,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Water station", "Waste bags", "Benches", "Shade trees"],
      rating: 4.3,
      imageUrl: "",
      description:
        "McCall's fenced off-leash dog park where locals and visitors bring their pups to play. Well-maintained with good shade and a friendly community atmosphere.",
    },
    {
      name: "Legacy Park Beach",
      address: "1101 E Lake St, McCall, ID 83638",
      lat: 44.7330,
      lng: -116.0900,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Beach access", "Lake swimming", "Picnic areas", "Restrooms", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A beautiful public beach on Payette Lake where leashed dogs can wade and swim. The sandy beach and crystal-clear mountain lake make this one of the best dog swimming spots in Idaho.",
    },
    {
      name: "Ponderosa State Park Trails",
      address: "1920 Davis Ave, McCall, ID 83638",
      lat: 44.7410,
      lng: -116.1080,
      offLeash: false,
      fenced: false,
      acres: 1000,
      amenities: ["Forest trails", "Lake views", "Wildlife viewing", "Campground", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "Miles of forested trails on a peninsula in Payette Lake with stunning lake and mountain views. Leashed dogs enjoy the diverse terrain from lakeside beaches to ridgetop overlooks.",
    },
    {
      name: "Bear Basin Trailhead",
      address: "Bear Basin Rd, McCall, ID 83638",
      lat: 44.7500,
      lng: -116.1200,
      offLeash: true,
      fenced: false,
      acres: 100.0,
      amenities: ["Mountain trails", "Alpine meadows", "Creek crossings", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A trailhead into the Payette National Forest where dogs can run off-leash under voice control on mountain trails. The hike climbs through forest to alpine meadows with panoramic mountain views.",
    },
  ],
};
