export const miamiData = {
  city: {
    name: "Miami",
    state: "Florida",
    region: "Southeast",
    lat: 25.7617,
    lng: -80.1918,
    dogFriendlinessScore: 7,
    description:
      "Miami's year-round sunshine, dog-friendly beaches, and outdoor dining culture make it a tropical paradise for pups. From the dog parks of Coconut Grove to the pet-friendly patios of Wynwood, Miami's vibrant neighborhoods welcome four-legged visitors with open arms and water bowls.",
    heroImage: "https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=1200&fit=crop",
    climate: "Tropical Monsoon",
    population: 442241,
  },
  hotels: [
    {
      name: "Kimpton EPIC Hotel",
      address: "270 Biscayne Blvd Way, Miami, FL 33131",
      lat: 25.7678,
      lng: -80.1872,
      priceRange: "$$$$" as const,
      dogPolicy: "All pets welcome at no additional charge. Complimentary pet beds, bowls, and treats. Bayfront location.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pet bed", "Treats", "Bayfront", "Rooftop pool"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.epichotel.com",
      phone: "(305) 424-5226",
    },
    {
      name: "The Standard Spa Miami Beach",
      address: "40 Island Ave, Miami Beach, FL 33139",
      lat: 25.7858,
      lng: -80.168,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome with a $100 per stay fee. Waterfront spa resort on Belle Isle with bay views.",
      maxDogWeight: 40,
      petFee: 100,
      amenities: ["Spa", "Bay views", "Pool", "Restaurant", "Waterfront"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.standardhotels.com/miami",
      phone: "(305) 673-1717",
    },
    {
      name: "The Confidante Miami Beach",
      address: "4041 Collins Ave, Miami Beach, FL 33140",
      lat: 25.8118,
      lng: -80.1228,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 40 lbs welcome with a $75 per stay fee. Mid-Beach Art Deco hotel with pool and beach access.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Beach access", "Pool", "Art Deco style", "Restaurant", "Near dog beach"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.theconfidantehotel.com",
      phone: "(305) 424-1234",
    },
    {
      name: "Aloft Miami Brickell",
      address: "1001 SW 2nd Ave, Miami, FL 33130",
      lat: 25.764,
      lng: -80.198,
      priceRange: "$$" as const,
      dogPolicy: "Arf program welcomes dogs under 40 lbs at no additional fee. Walking distance to Brickell restaurants.",
      maxDogWeight: 40,
      petFee: 0,
      amenities: ["No pet fee", "Pet treats at check-in", "Brickell location", "Pool", "Near MetroMover"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(305) 854-6600",
    },
  ],
  nationalParks: [
    {
      name: "Oleta River State Park",
      state: "Florida",
      lat: 25.9222,
      lng: -80.1406,
      dogPolicy: "Leashed dogs welcome on designated trails. Florida's largest urban park with mangrove-lined waterways.",
      dogTrails: ["Nature Trail", "Blue Trail", "Mangrove Trail"],
      restrictions: ["Leash required at all times", "No dogs on beach", "No dogs in water", "Clean up required"],
      description:
        "Over 1,000 acres of mangrove forest, tropical hardwood hammock, and sandy beaches on Biscayne Bay. The nature trails wind through lush tropical vegetation and along the waterfront. While dogs can't access the beach, the shaded trails offer a cool escape from Miami's heat.",
      imageUrl: "",
      website: "https://www.floridastateparks.org/parks-and-trails/oleta-river-state-park",
    },
    {
      name: "Biscayne National Park (Convoy Point)",
      state: "Florida",
      lat: 25.4594,
      lng: -80.3301,
      dogPolicy: "Leashed dogs welcome on the mainland trails and jetty. No dogs on boats to islands.",
      dogTrails: ["Jetty Trail", "Convoy Point Shoreline Trail", "Mangrove Trail"],
      restrictions: ["Leash required", "No dogs on boats or islands", "No dogs in water", "Clean up required"],
      description:
        "While most of this underwater national park is inaccessible to dogs, the Convoy Point mainland area offers a beautiful shoreline walk along the edge of Biscayne Bay with views of the park's turquoise waters. The mangrove trails and jetty provide a taste of this unique marine environment.",
      imageUrl: "",
      website: "https://www.nps.gov/bisc",
    },
    {
      name: "Everglades National Park (Shark Valley)",
      state: "Florida",
      lat: 25.7617,
      lng: -80.7654,
      dogPolicy: "Leashed dogs welcome on the 15-mile Shark Valley tram road. One of the best ways to experience the Everglades with a dog.",
      dogTrails: ["Shark Valley Tram Road (15-mile loop)", "Bobcat Boardwalk Trail"],
      restrictions: ["Leash required", "Stay on paved road", "Be alert for alligators", "No dogs on boardwalks except Bobcat"],
      description:
        "The Shark Valley section of the Everglades offers a flat 15-mile paved loop through sawgrass prairies where alligators bask along the road and herons wade in sloughs. The observation tower at the halfway point provides sweeping views of the River of Grass. Keep your leashed dog close — gators are real here.",
      imageUrl: "",
      website: "https://www.nps.gov/ever",
    },
  ],
  restaurants: [
    {
      name: "Wynwood Yard (successor venues)",
      address: "56 NW 29th St, Miami, FL 33127",
      lat: 25.8014,
      lng: -80.1994,
      cuisine: "Food Trucks",
      priceRange: "$$" as const,
      dogPolicy: "Open-air food truck park in Wynwood that's extremely dog-friendly. Multiple cuisine options in a communal setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Greenstreet Cafe",
      address: "3468 Main Hwy, Miami, FL 33133",
      lat: 25.7276,
      lng: -80.2415,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Coconut Grove institution with a huge dog-friendly patio. Open all day with great people- and dog-watching.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.greenstreetcafe.net",
    },
    {
      name: "The Salty Dog",
      address: "7401 Biscayne Blvd, Miami, FL 33138",
      lat: 25.8385,
      lng: -80.1833,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Dog bar and restaurant in the MiMo District. Dogs welcome inside and out. Named for dogs, loved by dogs.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thesaltydogmiami.com",
    },
    {
      name: "J. Wakefield Brewing",
      address: "120 NW 24th St, Miami, FL 33127",
      lat: 25.7975,
      lng: -80.198,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Wynwood brewery with a dog-friendly indoor/outdoor space. Creative craft beers in Miami's art district.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.jwakefieldbrewing.com",
    },
    {
      name: "Lagniappe",
      address: "3425 NE 2nd Ave, Miami, FL 33137",
      lat: 25.8098,
      lng: -80.1926,
      cuisine: "Wine Bar",
      priceRange: "$$" as const,
      dogPolicy: "Relaxed outdoor wine and cheese garden in Midtown. Extremely dog-friendly with live music under the trees.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.lagniappehouse.com",
    },
  ],
  cafes: [
    {
      name: "Panther Coffee",
      address: "2390 NW 2nd Ave, Miami, FL 33127",
      lat: 25.7965,
      lng: -80.1996,
      dogPolicy: "Wynwood's premier coffee roaster with a large outdoor area. Dogs welcome in the breezy patio space.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.panthercoffee.com",
    },
    {
      name: "All Day",
      address: "1035 N Miami Ave, Miami, FL 33136",
      lat: 25.7837,
      lng: -80.1955,
      dogPolicy: "Brickell coffee shop with outdoor seating. Dogs welcome at patio tables. Australian-style flat whites.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.alldaymiami.com",
    },
    {
      name: "Vice City Bean",
      address: "1657 N Miami Ave, Miami, FL 33136",
      lat: 25.7898,
      lng: -80.1965,
      dogPolicy: "Specialty coffee in Wynwood with a sidewalk patio. Dogs welcome while you enjoy espresso and avocado toast.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Threefold Cafe",
      address: "141 NE 3rd Ave, Miami, FL 33132",
      lat: 25.7753,
      lng: -80.189,
      dogPolicy: "Australian-inspired cafe in downtown Miami. Dog-friendly patio with excellent flat whites and brunch fare.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.threefoldcafe.com",
    },
  ],
  dogParks: [
    {
      name: "Bark Park at Blanche Park",
      address: "4600 Collins Ave, Miami Beach, FL 33140",
      lat: 25.8152,
      lng: -80.126,
      offLeash: true,
      fenced: true,
      acres: 1.0,
      amenities: ["Fenced", "Separate small dog area", "Water fountains", "Shade structures", "Near beach"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Miami Beach's most popular dog park features separate areas for large and small dogs, water features, and shade structures. Located just a block from the beach, you can combine a park visit with a beach walk. The social scene is quintessentially Miami — fashionable dogs and their equally stylish owners.",
    },
    {
      name: "Hobie Island Dog Beach",
      address: "3501 Rickenbacker Cswy, Miami, FL 33149",
      lat: 25.735,
      lng: -80.1688,
      offLeash: true,
      fenced: false,
      acres: 4.0,
      amenities: ["Off-leash beach", "Bay swimming", "Shallow water", "Parking", "Views of downtown"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Miami's beloved off-leash dog beach on the Rickenbacker Causeway where dogs can swim in the calm bay waters with the downtown skyline as a backdrop. The shallow, warm water is perfect for dogs of all swimming abilities, and the sand is soft. Weekend mornings draw huge crowds of happy pups.",
    },
    {
      name: "Kennedy Park Dog Run",
      address: "2400 S Bayshore Dr, Miami, FL 33133",
      lat: 25.7236,
      lng: -80.2384,
      offLeash: true,
      fenced: true,
      acres: 0.75,
      amenities: ["Fenced", "Bay views", "Water fountain", "Benches", "Coconut Grove location"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A fenced dog park in Coconut Grove with views of Biscayne Bay. The park sits within the larger Kennedy Park, offering waterfront walking paths before or after off-leash play. The Coconut Grove village shops and restaurants are within walking distance.",
    },
    {
      name: "Miami Beach Boardwalk",
      address: "Miami Beach Boardwalk, Miami Beach, FL 33139",
      lat: 25.7826,
      lng: -80.1315,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Ocean views", "Paved boardwalk", "Beach access", "Restaurants nearby", "People-watching"],
      rating: 4.5,
      imageUrl: "",
      description:
        "The iconic Miami Beach boardwalk stretches along the ocean between high-rise hotels and the Atlantic. Leashed dogs are welcome on the boardwalk year-round, and the Art Deco architecture of South Beach provides a stunning backdrop. Early morning is best to beat the heat and crowds.",
    },
  ],
};
