export const minneapolisData = {
  city: {
    name: "Minneapolis",
    state: "Minnesota",
    region: "Midwest",
    lat: 44.9778,
    lng: -93.2650,
    dogFriendlinessScore: 7,
    description:
      "The City of Lakes lives up to its name with a sprawling chain of parks, urban lakes, and off-leash areas that make it a surprisingly great destination for dog owners. Minneapolis boasts one of the most extensive urban park systems in the country, and its culture of outdoor recreation means four-legged visitors are welcomed at patios, breweries, and trails across the metro.",
    heroImage: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=1200&fit=crop",
    climate: "Continental",
    population: 429954,
  },
  hotels: [
    {
      name: "Hotel Ivy, a Luxury Collection Hotel",
      address: "201 S 11th St, Minneapolis, MN 55403",
      lat: 44.9738,
      lng: -93.2716,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a signed pet waiver at check-in.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Dog bed", "Food and water bowls", "Pet-friendly room service", "Walking route map"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.marriott.com/hotels/travel/mspiv-hotel-ivy-a-luxury-collection-hotel-minneapolis/",
      phone: "(612) 746-4600",
    },
    {
      name: "Hewing Hotel",
      address: "300 Washington Ave N, Minneapolis, MN 55401",
      lat: 44.9843,
      lng: -93.2713,
      priceRange: "$$$" as const,
      dogPolicy: "Two dogs per room, any size. Dog-friendly rooftop access available.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Treats at check-in", "Rooftop lounge access", "Waste bags"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hewinghotel.com/",
      phone: "(651) 468-0400",
    },
    {
      name: "The Depot Minneapolis, a Doubletree by Hilton",
      address: "225 S 3rd Ave, Minneapolis, MN 55401",
      lat: 44.9793,
      lng: -93.2610,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome. Maximum two pets per room.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Dog bed", "Water bowl", "Indoor pool area", "Nearby riverwalk"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hilton.com/en/hotels/mspdtdt-the-depot-minneapolis/",
      phone: "(612) 375-1700",
    },
    {
      name: "Canopy by Hilton Minneapolis Mill District",
      address: "708 S 3rd St, Minneapolis, MN 55415",
      lat: 44.9773,
      lng: -93.2567,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome with no breed restrictions. Complimentary treats in lobby.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Welcome treats", "Dog bed", "Water bowls", "Pet waste stations nearby"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hilton.com/en/hotels/mspmdpy-canopy-minneapolis-mill-district/",
      phone: "(612) 236-5000",
    },
    {
      name: "Residence Inn Minneapolis Downtown at The Depot",
      address: "425 S 2nd St, Minneapolis, MN 55401",
      lat: 44.9781,
      lng: -93.2625,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a nonrefundable cleaning fee. Suite-style rooms with extra space.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Full kitchen", "Dog bed on request", "Grocery delivery service", "Outdoor walking paths"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com/hotels/travel/msprd-residence-inn-minneapolis-downtown-at-the-depot/",
      phone: "(612) 340-1300",
    },
  ],
  nationalParks: [
    {
      name: "Voyageurs National Park",
      state: "Minnesota",
      lat: 48.4839,
      lng: -92.8282,
      dogPolicy: "Dogs allowed on the Kab-Ash Trail, in developed areas, and on houseboats. Not permitted on backcountry trails or interior islands.",
      dogTrails: ["Kab-Ash Trail", "Rainy Lake Visitor Center area", "Ash River Visitor Center trails"],
      restrictions: [
        "Dogs must be on a leash no longer than 6 feet at all times",
        "Not allowed on backcountry trails or interior islands",
        "Not permitted in buildings",
      ],
      description:
        "A water-based park of interconnected lakes, old-growth forest, and rocky shores along the Canadian border. The Kab-Ash Trail offers a scenic 28-mile corridor where leashed dogs can explore boreal wilderness.",
      imageUrl: "",
      website: "https://www.nps.gov/voya/",
    },
    {
      name: "Mississippi National River and Recreation Area",
      state: "Minnesota",
      lat: 44.9103,
      lng: -93.1790,
      dogPolicy: "Dogs welcome on most trails and outdoor areas when leashed. Some partner-managed sites may have additional restrictions.",
      dogTrails: [
        "Minnehaha Falls Trail",
        "Mississippi Gorge Regional Trail",
        "Hidden Falls Trail",
        "Fort Snelling State Trail",
      ],
      restrictions: [
        "Leash required at all times",
        "Clean up after your dog",
        "Some partner sites may restrict pets",
      ],
      description:
        "Stretching 72 miles through the Twin Cities metro, this park preserves the Mississippi River corridor with forested bluffs, historic sites, and an extensive trail network right in Minneapolis's backyard.",
      imageUrl: "",
      website: "https://www.nps.gov/miss/",
    },
    {
      name: "Pipestone National Monument",
      state: "Minnesota",
      lat: 44.0134,
      lng: -96.3254,
      dogPolicy: "Leashed dogs allowed on the Circle Trail and in parking areas. Not permitted inside the cultural center or quarry areas.",
      dogTrails: ["Circle Trail"],
      restrictions: [
        "Must be on leash no longer than 6 feet",
        "Not allowed in cultural center",
        "Not permitted in active quarry areas",
      ],
      description:
        "A sacred site where Native Americans have quarried red pipestone for centuries. The Circle Trail loops through tallgrass prairie, quartzite cliffs, and past Winnewissa Falls.",
      imageUrl: "",
      website: "https://www.nps.gov/pipe/",
    },
  ],
  restaurants: [
    {
      name: "Surly Brewing Co.",
      address: "520 Malcolm Ave SE, Minneapolis, MN 55414",
      lat: 44.9731,
      lng: -93.2110,
      cuisine: "American Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor beer garden and patio areas.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://surlybrewing.com/",
    },
    {
      name: "Psycho Suzi's Motor Lounge",
      address: "1900 Marshall St NE, Minneapolis, MN 55418",
      lat: 44.9997,
      lng: -93.2497,
      cuisine: "Tiki Bar & Grill",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the large riverfront patio.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.psychosuzis.com/",
    },
    {
      name: "Pat's Tap",
      address: "3510 Nicollet Ave, Minneapolis, MN 55408",
      lat: 44.9371,
      lng: -93.2780,
      cuisine: "American Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the heated outdoor patio year-round.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.patstap.com/",
    },
    {
      name: "Sea Salt Eatery",
      address: "4825 Minnehaha Ave, Minneapolis, MN 55417",
      lat: 44.9155,
      lng: -93.2112,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Order-at-the-window spot with a large dog-friendly outdoor seating area near Minnehaha Falls.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://seasalteatery.com/",
    },
    {
      name: "Bauhaus Brew Labs",
      address: "1315 Tyler St NE, Minneapolis, MN 55413",
      lat: 44.9964,
      lng: -93.2460,
      cuisine: "Brewery & Food Trucks",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly taproom and large outdoor area. Rotating food trucks on site.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://bauhausbrewlabs.com/",
    },
    {
      name: "Birch's on the Lake",
      address: "4289 Upton Ave S, Minneapolis, MN 55410",
      lat: 44.9232,
      lng: -93.3115,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs allowed on the lakeside patio overlooking Lake Harriet.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://birchsonlake.com/",
    },
    {
      name: "Red Cow",
      address: "208 N 1st Ave, Minneapolis, MN 55401",
      lat: 44.9836,
      lng: -93.2693,
      cuisine: "Burgers & Craft Beer",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the sidewalk patio.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.redcowmn.com/",
    },
    {
      name: "World Street Kitchen",
      address: "2743 Lyndale Ave S, Minneapolis, MN 55408",
      lat: 44.9506,
      lng: -93.2878,
      cuisine: "Global Street Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables during warm months.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.worldstreetkitchen.com/",
    },
  ],
  cafes: [
    {
      name: "Dogwood Coffee Co.",
      address: "3001 Hennepin Ave, Minneapolis, MN 55408",
      lat: 44.9483,
      lng: -93.2978,
      dogPolicy: "Dog-themed cafe with outdoor seating where pups are welcome.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.dogwoodcoffee.com/",
    },
    {
      name: "Spyhouse Coffee Roasters",
      address: "945 Broadway NE, Minneapolis, MN 55413",
      lat: 44.9917,
      lng: -93.2484,
      dogPolicy: "Dogs welcome on the patio. Staff keeps water bowls out seasonally.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.spyhousecoffee.com/",
    },
    {
      name: "Quixotic Coffee",
      address: "769 Cleveland Ave S, St Paul, MN 55116",
      lat: 44.9261,
      lng: -93.1877,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Known for friendly baristas who love dogs.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.quixoticcoffee.com/",
    },
    {
      name: "Five Watt Coffee",
      address: "3745 Nicollet Ave, Minneapolis, MN 55409",
      lat: 44.9337,
      lng: -93.2780,
      dogPolicy: "Patio seating available for guests with dogs.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.fivewattcoffee.com/",
    },
    {
      name: "Angry Catfish Bicycle + Coffee Bar",
      address: "4208 28th Ave S, Minneapolis, MN 55406",
      lat: 44.9270,
      lng: -93.2310,
      dogPolicy: "Bike and dog-friendly spot with shaded patio seating.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.angrycatfishbicycle.com/",
    },
  ],
  dogParks: [
    {
      name: "Minnehaha Dog Park",
      address: "5399 S Minnehaha Park Dr, Minneapolis, MN 55417",
      lat: 44.9108,
      lng: -93.2098,
      offLeash: true,
      fenced: false,
      acres: 6.8,
      amenities: ["River access", "Walking trails", "Waste stations", "Parking lot"],
      rating: 4.6,
      imageUrl: "",
      description:
        "One of the most beloved off-leash parks in the Twin Cities, set along the Mississippi River gorge with sandy banks where dogs can splash and swim. Wooded trails wind through the bluffs above.",
    },
    {
      name: "Lake of the Isles Off-Leash Dog Park",
      address: "2500 Lake of the Isles Pkwy E, Minneapolis, MN 55405",
      lat: 44.9558,
      lng: -93.3055,
      offLeash: true,
      fenced: false,
      acres: 3.0,
      amenities: ["Lake access", "Paved path nearby", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A scenic off-leash area on the northeast shore of Lake of the Isles. Dogs can romp in the grassy open space and cool off in the lake while owners enjoy views of the Minneapolis skyline.",
    },
    {
      name: "Franklin Terrace Off-Leash Dog Park",
      address: "929 E Franklin Ave, Minneapolis, MN 55404",
      lat: 44.9626,
      lng: -93.2554,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Benches", "Shade trees", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      description:
        "A fully fenced neighborhood dog park tucked between residential streets, popular with downtown dog owners. The mature trees provide welcome shade on hot summer days.",
    },
    {
      name: "Loring Park Off-Leash Area",
      address: "1382 Willow St, Minneapolis, MN 55403",
      lat: 44.9695,
      lng: -93.2833,
      offLeash: true,
      fenced: false,
      acres: 2.0,
      amenities: ["Open green space", "Pond nearby", "Waste stations", "Walking paths"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A designated off-leash zone within Loring Park, one of Minneapolis's oldest and most central green spaces. The park sits steps from the Walker Art Center and the downtown core.",
    },
    {
      name: "Boom Island Dog Park",
      address: "724 Sibley St NE, Minneapolis, MN 55413",
      lat: 44.9930,
      lng: -93.2700,
      offLeash: true,
      fenced: false,
      acres: 4.0,
      amenities: ["River access", "Open fields", "Waste stations", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Located on the Mississippi riverfront in northeast Minneapolis, this expansive off-leash area offers wide-open fields and river access. Dogs love splashing in the shallow water near the shore.",
    },
  ],
};
