export const missoulaData = {
  city: {
    name: "Missoula",
    state: "Montana",
    region: "Mountain West",
    lat: 46.8721,
    lng: -113.994,
    dogFriendlinessScore: 8,
    description:
      "Nestled in a valley where five mountain ranges converge and three rivers meet, Missoula is a rugged outdoor paradise that treats dogs like first-class citizens. With miles of off-leash trails, dog-friendly breweries on every corner, and a culture that practically requires a four-legged hiking buddy, this university town is a tail-wagging wonderland for adventurous pups and their people.",
    heroImage: "https://images.unsplash.com/photo-1508389377389-918442e3626b?w=1200&fit=crop",
    climate: "Semi-arid Continental",
    population: 75516,
  },

  hotels: [
    {
      name: "The Limelight Hotel Missoula",
      address: "200 S Pattee St, Missoula, MT 59802",
      lat: 46.8715,
      lng: -113.994,
      priceRange: "$$$" as const,
      dogPolicy:
        "Dogs of all sizes welcome with a one-time pet fee. Complimentary dog bed and bowls at check-in.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: [
        "Dog bed",
        "Water and food bowls",
        "Treat bag",
        "Walking route map",
        "Pet-sitting referrals",
      ],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.limelighthotels.com/missoula",
      phone: "(406) 926-2400",
    },
    {
      name: "Hilton Garden Inn Missoula",
      address: "3720 N Reserve St, Missoula, MT 59808",
      lat: 46.8932,
      lng: -114.0258,
      priceRange: "$$" as const,
      dogPolicy:
        "Dogs up to 75 lbs welcome. Two dogs per room max with a nightly pet fee.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: [
        "Grassy pet relief area",
        "Waste bags",
        "Nearby trails",
        "Pet-friendly rooms on ground floor",
      ],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(406) 532-5300",
    },
    {
      name: "Residence Inn by Marriott Missoula Downtown",
      address: "125 N Pattee St, Missoula, MT 59802",
      lat: 46.8728,
      lng: -113.9953,
      priceRange: "$$" as const,
      dogPolicy:
        "Pet-friendly suites with full kitchens — perfect for packing your pup's favorite meals.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: [
        "Full kitchen",
        "Pet relief area",
        "Waste stations",
        "Walking distance to Caras Park",
      ],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(406) 549-0600",
    },
    {
      name: "Mountain Valley Inn",
      address: "420 W Broadway St, Missoula, MT 59802",
      lat: 46.8713,
      lng: -113.9998,
      priceRange: "$" as const,
      dogPolicy:
        "Budget-friendly and dog-friendly! All well-behaved dogs welcome with a small nightly fee.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: [
        "Fenced yard area",
        "Waste bags",
        "Free parking",
        "Close to river trail",
      ],
      rating: 3.8,
      imageUrl: "",
      website: "https://www.mountainvalleyinnmissoula.com",
      phone: "(406) 728-4500",
    },
    {
      name: "DoubleTree by Hilton Missoula–Edgewater",
      address: "100 Madison St, Missoula, MT 59802",
      lat: 46.8696,
      lng: -113.9929,
      priceRange: "$$$" as const,
      dogPolicy:
        "Riverfront property welcoming dogs up to 80 lbs. Walk right out to the Clark Fork River Trail.",
      maxDogWeight: 80,
      petFee: 50,
      amenities: [
        "Riverfront trail access",
        "Pet relief area",
        "Dog bowls on request",
        "Warm cookies at check-in (for humans)",
      ],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(406) 728-3100",
    },
  ],

  nationalParks: [
    {
      name: "Glacier National Park",
      state: "Montana",
      lat: 48.7596,
      lng: -113.787,
      dogPolicy:
        "Dogs are allowed in developed areas, along roads, in parking lots, and on bike paths. Not permitted on trails, in the backcountry, or on lake shores.",
      dogTrails: [
        "Going-to-the-Sun Road bike path",
        "Apgar Village area",
        "Fish Creek Campground roads",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash at all times",
        "Not allowed on any hiking trails",
        "Not permitted in backcountry or on lake shores",
        "Must clean up after pets",
      ],
      description:
        "The Crown of the Continent is breathtaking even from the roadside. While dogs can't hit the iconic trails, they can enjoy the stunning Going-to-the-Sun Road bike path and explore the charming Apgar Village area with mountain views that'll make any pup howl with joy.",
      imageUrl: "",
      website: "https://www.nps.gov/glac",
    },
    {
      name: "Yellowstone National Park",
      state: "Wyoming",
      lat: 44.428,
      lng: -110.5885,
      dogPolicy:
        "Dogs are allowed in developed areas, on roads, in parking lots, and in campgrounds. Not permitted on trails, boardwalks, or in the backcountry.",
      dogTrails: [
        "Old Faithful parking area",
        "Mammoth Hot Springs developed area",
        "Canyon Village roads",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash at all times",
        "Not allowed on any trails or boardwalks",
        "Must stay within 100 feet of roads and parking areas",
        "Not permitted in thermal areas",
        "Must clean up after pets",
      ],
      description:
        "America's first national park is a geothermal wonderland. While pups are limited to developed areas, they can still watch Old Faithful erupt from the parking lot and enjoy the scenic drives through some of the most spectacular landscapes on Earth.",
      imageUrl: "",
      website: "https://www.nps.gov/yell",
    },
    {
      name: "Nez Perce National Historical Park",
      state: "Montana",
      lat: 46.0988,
      lng: -115.0004,
      dogPolicy:
        "Leashed dogs welcome at most outdoor areas of the park sites. A great way to explore history with your furry companion.",
      dogTrails: [
        "Big Hole National Battlefield trails",
        "Bear Paw Battlefield trail",
        "White Bird Battlefield auto tour",
      ],
      restrictions: [
        "Dogs must be on a leash at all times",
        "Not allowed inside visitor centers",
        "Must clean up after pets",
      ],
      description:
        "Spanning multiple sites across Montana, Idaho, and Oregon, this park tells the story of the Nez Perce people. Several battlefield sites offer open grasslands and gentle trails where leashed dogs can stretch their legs amid sweeping mountain scenery.",
      imageUrl: "",
      website: "https://www.nps.gov/nepe",
    },
    {
      name: "Grant-Kohrs Ranch National Historic Site",
      state: "Montana",
      lat: 46.4087,
      lng: -112.7408,
      dogPolicy:
        "Leashed dogs welcome on the ranch grounds and trails. A wonderful spot to let your dog experience the wide-open Montana range.",
      dogTrails: [
        "Ranch Loop Trail",
        "Cottonwood Creek Trail",
        "Lower Ranch grounds",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash",
        "Not permitted inside historic buildings",
        "Keep away from livestock areas",
        "Must clean up after pets",
      ],
      description:
        "This working cattle ranch preserves the legacy of Montana's open-range cattle era. Leashed dogs can roam the sprawling grounds, sniff where cowboys once rode, and enjoy the sweeping views of the Deer Lodge Valley.",
      imageUrl: "",
      website: "https://www.nps.gov/grko",
    },
  ],

  restaurants: [
    {
      name: "Draught Works Brewery",
      address: "915 Toole Ave, Missoula, MT 59802",
      lat: 46.8694,
      lng: -113.9876,
      cuisine: "Brewery / Pub",
      priceRange: "$" as const,
      dogPolicy:
        "Dogs are the unofficial mascots here! Welcome on the huge outdoor patio and inside the taproom.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.draughtworks.com",
    },
    {
      name: "Biga Pizza",
      address: "241 W Main St, Missoula, MT 59802",
      lat: 46.8725,
      lng: -113.9969,
      cuisine: "Pizza / Italian",
      priceRange: "$$" as const,
      dogPolicy:
        "Leashed dogs welcome on the outdoor patio. Staff will often bring water bowls without asking.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bigapizza.com",
    },
    {
      name: "The Pearl Café",
      address: "231 E Front St, Missoula, MT 59802",
      lat: 46.8701,
      lng: -113.9915,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy:
        "Well-behaved leashed dogs welcome on the charming garden patio during dinner service.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.pearlcafe.us",
    },
    {
      name: "Imagine Nation Brewing",
      address: "1151 W Broadway St, Missoula, MT 59802",
      lat: 46.8722,
      lng: -114.0112,
      cuisine: "Brewery / Gastropub",
      priceRange: "$" as const,
      dogPolicy:
        "Super dog-friendly brewery with a big outdoor space. Dogs practically outnumber humans on sunny days.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.imaginenationbrewing.com",
    },
    {
      name: "Scotty's Table",
      address: "131 S Higgins Ave, Missoula, MT 59802",
      lat: 46.8712,
      lng: -113.9935,
      cuisine: "French-American Bistro",
      priceRange: "$$$" as const,
      dogPolicy:
        "Leashed dogs welcome on the seasonal patio. An upscale dining experience your pup can join.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.scottystable.com",
    },
    {
      name: "Tamarack Brewing Company",
      address: "231 W Front St, Missoula, MT 59802",
      lat: 46.8702,
      lng: -113.9955,
      cuisine: "American / Brewery",
      priceRange: "$$" as const,
      dogPolicy:
        "Dogs allowed on the outdoor patio with water provided. Great burgers, better beer, best company (your dog).",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tamarackbrewing.com",
    },
    {
      name: "Red Bird Restaurant",
      address: "111 N Higgins Ave, Missoula, MT 59802",
      lat: 46.8718,
      lng: -113.9935,
      cuisine: "Italian / Wine Bar",
      priceRange: "$$$" as const,
      dogPolicy:
        "Leashed dogs welcome on the sidewalk patio seating. Fresh water provided on request.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.redbirdrestaurant.com",
    },
    {
      name: "Market on Front",
      address: "201 E Front St, Missoula, MT 59802",
      lat: 46.87,
      lng: -113.9923,
      cuisine: "Deli / Casual American",
      priceRange: "$" as const,
      dogPolicy:
        "Grab a sandwich and sit on the patio with your pooch. Dogs welcome in all outdoor seating areas.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marketonfront.com",
    },
  ],

  cafes: [
    {
      name: "Break Espresso",
      address: "432 N Higgins Ave, Missoula, MT 59802",
      lat: 46.874,
      lng: -113.9937,
      dogPolicy:
        "Dogs are regulars on the outdoor patio. Known for giving pups extra attention and the occasional treat.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.breakespresso.com",
    },
    {
      name: "Clyde Coffee",
      address: "610 S Higgins Ave, Missoula, MT 59801",
      lat: 46.8672,
      lng: -113.9935,
      dogPolicy:
        "Hip coffee shop with a dog-friendly patio. Baristas keep a jar of biscuits behind the counter for four-legged visitors.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.clydecoffee.com",
    },
    {
      name: "Bernice's Bakery",
      address: "190 S 3rd St W, Missoula, MT 59801",
      lat: 46.8698,
      lng: -113.9975,
      dogPolicy:
        "Beloved local bakery with outdoor seating where dogs are always welcome. Homemade dog treats available!",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.bernicesbakery.com",
    },
    {
      name: "Black Coffee Roasting Co.",
      address: "525 S Higgins Ave, Missoula, MT 59801",
      lat: 46.8679,
      lng: -113.9935,
      dogPolicy:
        "Small-batch roaster with a sunny patio where dogs can hang while you sip world-class coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.blackcoffeeroasting.com",
    },
    {
      name: "Drum Coffee",
      address: "101 S Higgins Ave, Missoula, MT 59801",
      lat: 46.8713,
      lng: -113.9935,
      dogPolicy:
        "Cozy neighborhood café with patio seating. Dogs welcome outside while you enjoy expertly pulled espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.drumcoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Jacobs Island Dog Park",
      address: "Jacobs Island, Van Buren St, Missoula, MT 59802",
      lat: 46.869,
      lng: -113.988,
      offLeash: true,
      fenced: false,
      acres: 5,
      amenities: [
        "River access",
        "Walking trails",
        "Shade trees",
        "Waste stations",
        "Parking",
      ],
      rating: 4.6,
      imageUrl: "",
      description:
        "A dog's dream island! This off-leash paradise sits in the Clark Fork River, offering swimming access, shady trails, and open meadows. Watch your pup splash in the river and romp through the grass with a backdrop of mountain peaks.",
    },
    {
      name: "Blue Mountain Dog Park",
      address: "Blue Mountain Rd, Missoula, MT 59804",
      lat: 46.84,
      lng: -114.03,
      offLeash: true,
      fenced: false,
      acres: 12,
      amenities: [
        "Hiking trails",
        "Mountain views",
        "Shade trees",
        "Waste stations",
        "Parking lot",
      ],
      rating: 4.5,
      imageUrl: "",
      description:
        "A sprawling off-leash area at the base of Blue Mountain with trails winding through pine forests and open meadows. Dogs can explore to their heart's content with panoramic views of the Missoula valley.",
    },
    {
      name: "Fort Missoula Dog Park",
      address: "Fort Missoula Rd, Missoula, MT 59804",
      lat: 46.8555,
      lng: -114.014,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: [
        "Separate small dog area",
        "Water spigots",
        "Benches",
        "Waste stations",
        "Shade shelters",
      ],
      rating: 4.3,
      imageUrl: "",
      description:
        "A fully fenced off-leash park on the historic Fort Missoula grounds. Features separate areas for large and small dogs, water stations, and plenty of room to run. A favorite after-work gathering spot for Missoula's dog community.",
    },
    {
      name: "East Missoula Dog Run",
      address: "Hwy 200 E, East Missoula, MT 59802",
      lat: 46.873,
      lng: -113.957,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: [
        "Fenced area",
        "Benches",
        "Waste stations",
        "Parking",
        "Open play area",
      ],
      rating: 4.0,
      imageUrl: "",
      description:
        "A convenient fenced dog park on the east side of town. Perfect for a quick off-leash session when you're heading to or from adventures in the Blackfoot Valley. Simple but well-maintained and loved by locals.",
    },
    {
      name: "Northside Dog Park",
      address: "Elm St & Railroad St, Missoula, MT 59802",
      lat: 46.878,
      lng: -113.998,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: [
        "Double-gated entry",
        "Water fountain",
        "Benches",
        "Waste stations",
        "Agility features",
      ],
      rating: 4.2,
      imageUrl: "",
      description:
        "A cozy neighborhood off-leash park in Missoula's Northside. Fully fenced with agility features for energetic pups and benches for their humans. Great for socializing and a quick play session.",
    },
  ],
};
