export const moabData = {
  city: {
    name: "Moab",
    state: "Utah",
    region: "Mountain West",
    lat: 38.5733,
    lng: -109.5498,
    dogFriendlinessScore: 7,
    description:
      "Surrounded by towering red rock formations, two national parks, and endless desert trails, Moab is an adventure hub where dogs are part of the culture. While the national parks have strict leash and trail restrictions, the vast Bureau of Land Management lands surrounding town offer limitless off-trail exploration for dogs and their owners under wide-open desert skies.",
    heroImage: "https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=1200&fit=crop",
    climate: "Arid desert",
    population: 5366,
  },
  hotels: [
    {
      name: "Hoodoo Moab",
      address: "81 W 200 N, Moab, UT 84532",
      lat: 38.5759,
      lng: -109.5510,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a luxury desert retreat experience. Curio Collection by Hilton.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Dog bed", "Treats at check-in", "Pool area", "Trail maps", "Concierge trail recommendations"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hoodoo.com/",
      phone: "(435) 259-7261",
    },
    {
      name: "Red Cliffs Lodge",
      address: "Mile 14, Hwy 128, Moab, UT 84532",
      lat: 38.6251,
      lng: -109.4096,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in cabins and select rooms. Set on 220 acres along the Colorado River.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["River access", "220-acre property", "Horse stables", "Winery on site", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.redcliffslodge.com/",
      phone: "(435) 259-2002",
    },
    {
      name: "Gonzo Inn",
      address: "100 W 200 S, Moab, UT 84532",
      lat: 38.5717,
      lng: -109.5512,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms available with a retro-modern vibe. Walking distance to Main Street.",
      maxDogWeight: 50,
      petFee: 25,
      amenities: ["Dog bowls", "Pool area", "Patio", "Bike storage"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.gonzoinn.com/",
      phone: "(435) 259-2515",
    },
    {
      name: "Moab Springs Ranch",
      address: "1266 N Hwy 191, Moab, UT 84532",
      lat: 38.5954,
      lng: -109.5554,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select condos and townhomes. Spacious grounds with cottonwood trees.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Cottonwood-shaded grounds", "Dog bowls", "Full kitchen", "Outdoor patios"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.moabspringsranch.com/",
      phone: "(435) 259-7891",
    },
    {
      name: "Under Canvas Moab",
      address: "13784 N Hwy 191, Moab, UT 84532",
      lat: 38.7202,
      lng: -109.6791,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select safari-style tents. Glamping under the stars with red rock views.",
      maxDogWeight: 0,
      petFee: 100,
      amenities: ["Safari tent", "Private deck", "Stargazing", "Camp store", "Fire pit"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.undercanvas.com/camps/moab/",
      phone: "(801) 895-3987",
    },
  ],
  nationalParks: [
    {
      name: "Arches National Park",
      state: "Utah",
      lat: 38.7331,
      lng: -109.5925,
      dogPolicy: "Dogs allowed ONLY on paved roads, in parking areas, and in your vehicle. Not permitted on any trails, viewpoints, or unpaved areas.",
      dogTrails: [],
      restrictions: [
        "Dogs NOT allowed on any trails",
        "Not allowed at any viewpoints or overlooks",
        "Not allowed on unpaved surfaces",
        "Must remain in vehicle or on paved road shoulders",
        "Cannot be left unattended in vehicles in hot weather",
      ],
      description:
        "Home to over 2,000 natural sandstone arches, this iconic park has some of the strictest dog policies in the system. While dogs cannot join on trails, the scenic drive through the park offers dramatic views of Delicate Arch, Balanced Rock, and the Windows section from the car.",
      imageUrl: "",
      website: "https://www.nps.gov/arch/",
    },
    {
      name: "Canyonlands National Park",
      state: "Utah",
      lat: 38.3269,
      lng: -109.8783,
      dogPolicy: "Dogs allowed ONLY on paved roads and in developed campgrounds. Not permitted on any trails, overlooks, or in the backcountry.",
      dogTrails: [],
      restrictions: [
        "Dogs NOT allowed on any trails",
        "Not allowed at overlooks or viewpoints",
        "Not permitted in backcountry",
        "Must stay on paved surfaces",
        "Cannot be left unattended in vehicles",
      ],
      description:
        "A vast wilderness of canyons, mesas, and buttes carved by the Colorado and Green Rivers. Like Arches, the park severely restricts dog access, but the scenic drives through Island in the Sky district offer jaw-dropping views from the vehicle.",
      imageUrl: "",
      website: "https://www.nps.gov/cany/",
    },
    {
      name: "Dead Horse Point State Park",
      state: "Utah",
      lat: 38.4826,
      lng: -109.7385,
      dogPolicy: "Leashed dogs welcome on all trails and overlooks. One of the best dog-friendly alternatives to the national parks.",
      dogTrails: [
        "Dead Horse Point Rim Trail",
        "East Rim Trail",
        "West Rim Trail",
        "Intrepid Trail System",
      ],
      restrictions: [
        "Must be on leash no longer than 6 feet",
        "Clean up after your dog",
        "Not allowed in the visitor center",
        "Bring plenty of water — no shade on trails",
      ],
      description:
        "Perched 2,000 feet above the Colorado River, this state park offers the same breathtaking canyon views as Canyonlands but with full dog access on all trails. The rim trail is one of the most spectacular dog-friendly hikes in Utah.",
      imageUrl: "",
      website: "https://stateparks.utah.gov/parks/dead-horse/",
    },
    {
      name: "Sand Flats Recreation Area",
      state: "Utah",
      lat: 38.5597,
      lng: -109.4917,
      dogPolicy: "Dogs welcome on all trails including the famous Slickrock Bike Trail. Leash recommended but not always enforced.",
      dogTrails: [
        "Slickrock Bike Trail (hiking)",
        "Practice Loop",
        "Hell's Revenge 4x4 Trail (hiking)",
        "Porcupine Rim Trail",
      ],
      restrictions: [
        "Leash recommended",
        "Bring extra water — exposed desert terrain",
        "Watch for hot rock surfaces in summer",
        "Fee area — pay at entrance",
      ],
      description:
        "A BLM-managed recreation area famous for the Slickrock Bike Trail's undulating sandstone terrain. Dogs can explore the petrified sand dunes with their owners on foot, enjoying 360-degree views of the La Sal Mountains and surrounding canyon country.",
      imageUrl: "",
      website: "https://www.blm.gov/visit/sand-flats",
    },
  ],
  restaurants: [
    {
      name: "Moab Brewery",
      address: "686 S Main St, Moab, UT 84532",
      lat: 38.5667,
      lng: -109.5498,
      cuisine: "Brewery & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the large outdoor patio. Great post-hike spot.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.themoabbrewery.com/",
    },
    {
      name: "Quesadilla Mobilla",
      address: "89 N Main St, Moab, UT 84532",
      lat: 38.5742,
      lng: -109.5500,
      cuisine: "Mexican Food Truck",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly outdoor picnic table seating at this beloved food truck.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.quesadillamobilla.com/",
    },
    {
      name: "Desert Bistro",
      address: "36 S 100 W, Moab, UT 84532",
      lat: 38.5727,
      lng: -109.5511,
      cuisine: "Contemporary American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs allowed on the garden patio for dinner service.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.desertbistro.com/",
    },
    {
      name: "Fiesta Mexicana",
      address: "202 S Main St, Moab, UT 84532",
      lat: 38.5720,
      lng: -109.5500,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at covered outdoor tables.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.fiestamexicanamoab.com/",
    },
    {
      name: "Antica Forma",
      address: "267 N Main St, Moab, UT 84532",
      lat: 38.5765,
      lng: -109.5502,
      cuisine: "Neapolitan Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the small outdoor patio. Wood-fired Neapolitan-style pizza.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.anticaformamoab.com/",
    },
    {
      name: "Sunset Grill",
      address: "900 N Hwy 191, Moab, UT 84532",
      lat: 38.5870,
      lng: -109.5544,
      cuisine: "American Steakhouse",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs allowed on the outdoor terrace with panoramic valley views at sunset.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.moab-utah.com/sunsetgrill/",
    },
    {
      name: "Thai Bella",
      address: "98 E Center St, Moab, UT 84532",
      lat: 38.5733,
      lng: -109.5488,
      cuisine: "Thai",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome at outdoor seating.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.thaibellamoab.com/",
    },
    {
      name: "Love Muffin Cafe",
      address: "139 N Main St, Moab, UT 84532",
      lat: 38.5749,
      lng: -109.5501,
      cuisine: "Breakfast & Brunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor sidewalk tables. Excellent breakfast burritos.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.lovemuffincafe.com/",
    },
  ],
  cafes: [
    {
      name: "Moab Coffee Roasters",
      address: "90 N Main St, Moab, UT 84532",
      lat: 38.5742,
      lng: -109.5499,
      dogPolicy: "Dog-friendly patio seating with shade. Locally roasted beans and espresso.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.moabcoffeeroasters.com/",
    },
    {
      name: "Rave'N Image Coffee House",
      address: "96 E Center St, Moab, UT 84532",
      lat: 38.5733,
      lng: -109.5489,
      dogPolicy: "Leashed dogs welcome on the patio. Gallery and coffee shop combo.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.ravenimagecoffee.com/",
    },
    {
      name: "Red Rock Bakery & Net Cafe",
      address: "74 S Main St, Moab, UT 84532",
      lat: 38.5723,
      lng: -109.5499,
      dogPolicy: "Dogs allowed at outdoor tables. Fresh baked goods daily.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.redrockbakerymoab.com/",
    },
    {
      name: "EklectiCafe",
      address: "352 N Main St, Moab, UT 84532",
      lat: 38.5779,
      lng: -109.5504,
      dogPolicy: "Charming garden patio where dogs are always welcome. Eclectic breakfast and lunch menu.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.eklecticafe.com/",
    },
    {
      name: "Jailhouse Cafe",
      address: "101 N Main St, Moab, UT 84532",
      lat: 38.5744,
      lng: -109.5500,
      dogPolicy: "Dogs welcome at outdoor seating. Housed in the old county jail building.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.jailhousecafemoab.com/",
    },
  ],
  dogParks: [
    {
      name: "Moab Dog Park at Swanny City Park",
      address: "400 E 100 N, Moab, UT 84532",
      lat: 38.5754,
      lng: -109.5455,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Water spigots", "Benches", "Shade structures", "Waste stations"],
      rating: 4.1,
      imageUrl: "",
      description:
        "Moab's only fully fenced off-leash dog park, located within the larger Swanny City Park. A convenient and safe spot for dogs to run free after a day of desert adventures. Water access is essential in the arid climate.",
    },
    {
      name: "Corona Arch Trail & BLM Lands",
      address: "Potash Rd (Hwy 279), Moab, UT 84532",
      lat: 38.5780,
      lng: -109.6260,
      offLeash: true,
      fenced: false,
      acres: 500.0,
      amenities: ["Desert trails", "Arch views", "Natural terrain", "Parking area"],
      rating: 4.8,
      imageUrl: "",
      description:
        "The BLM lands surrounding the Corona Arch trailhead offer vast open desert where dogs can explore off-leash. The trail itself leads to the stunning Corona Arch, a 140-foot-wide sandstone arch rivaling those inside the national park — and dogs are welcome.",
    },
    {
      name: "Ken's Lake Recreation Area",
      address: "Ken's Lake Rd, Moab, UT 84532",
      lat: 38.5043,
      lng: -109.4352,
      offLeash: true,
      fenced: false,
      acres: 50.0,
      amenities: ["Lake swimming", "Camping", "Hiking trails", "Picnic areas", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A desert reservoir surrounded by red rock cliffs where dogs can swim and explore the shoreline trails. One of the few spots near Moab where dogs can cool off in the water, making it a favorite during hot summer months.",
    },
    {
      name: "Grandstaff Canyon Trail (formerly Negro Bill Canyon)",
      address: "Hwy 128, Mile 3, Moab, UT 84532",
      lat: 38.6050,
      lng: -109.5270,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Canyon trail", "Stream crossings", "Natural arch", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A scenic canyon trail on BLM land following a year-round creek to Morning Glory Natural Bridge. Dogs must be leashed but love the multiple stream crossings that keep them cool in the desert heat. The towering canyon walls provide welcome shade.",
    },
    {
      name: "Mill Creek Parkway",
      address: "100 E 300 S, Moab, UT 84532",
      lat: 38.5707,
      lng: -109.5480,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Paved pathway", "Creek access", "Shade trees", "Benches", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A paved multi-use path following Mill Creek through town, lined with cottonwood trees and offering creek access where dogs can wade and cool off. The shaded corridor is a welcome respite from the desert sun and connects several town parks.",
    },
  ],
};
