export const mobileData = {
  city: {
    name: "Mobile",
    state: "Alabama",
    region: "Southeast",
    lat: 30.6954,
    lng: -88.0399,
    dogFriendlinessScore: 6,
    description:
      "The birthplace of Mardi Gras in America, Mobile offers dogs a Gulf Coast experience with live oak-lined boulevards, a revitalized downtown waterfront, and the massive Bellingrath Gardens just outside town. The port city's warm climate and friendly Southern culture extend a genuine welcome to four-legged visitors.",
    heroImage: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 187041,
  },
  hotels: [
    {
      name: "The Battle House Renaissance Mobile Hotel & Spa",
      address: "26 N Royal St, Mobile, AL 36602",
      lat: 30.6900,
      lng: -88.0430,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a non-refundable pet fee. A grand historic hotel in the heart of downtown since 1852.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking map", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.marriott.com/hotels/travel/mobak",
      phone: "(251) 338-2000",
    },
    {
      name: "Homewood Suites Mobile Downtown",
      address: "150 Government St, Mobile, AL 36602",
      lat: 30.6890,
      lng: -88.0430,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a nightly pet fee. Extended-stay suites with kitchens near the waterfront.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Pet-friendly suites", "Full kitchen", "Waste bags", "Walking access to waterfront"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com/en/hotels/mobhwhw",
      phone: "(251) 432-7700",
    },
    {
      name: "Holiday Inn Mobile Downtown",
      address: "301 Government St, Mobile, AL 36602",
      lat: 30.6880,
      lng: -88.0410,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome with a per-night pet fee. Convenient downtown location with river views.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Pet-friendly rooms", "Water bowls", "Waste bags", "River walk access"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.ihg.com/holidayinn/hotels/us/en/mobile",
      phone: "(251) 694-0100",
    },
    {
      name: "La Quinta Inn Mobile North",
      address: "816 S Beltline Hwy, Mobile, AL 36609",
      lat: 30.6670,
      lng: -88.1010,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome at no additional charge. A budget-friendly option with easy highway access.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Pet-friendly rooms", "Waste bags", "Walking areas", "Parking"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta/mobile",
      phone: "(251) 343-4040",
    },
  ],
  nationalParks: [
    {
      name: "Gulf Islands National Seashore - Davis Bayou",
      state: "Mississippi",
      lat: 30.3880,
      lng: -88.7510,
      dogPolicy: "Dogs allowed in the Davis Bayou area on a 6-foot leash including trails and campground. Beach access varies by section.",
      dogTrails: ["Nature Trail", "Davis Bayou Trail", "Live Oak Bicycle Trail"],
      restrictions: ["6-foot leash required", "Not allowed on designated swimming beaches", "Must clean up after pet"],
      description: "About an hour east of Mobile in Ocean Springs, Mississippi, the Davis Bayou area of Gulf Islands National Seashore offers coastal trails through pine forests and along the bayou. Dogs enjoy the shaded paths and wildlife viewing.",
      imageUrl: "",
      website: "https://www.nps.gov/guis",
    },
    {
      name: "Chickasabogue Park",
      state: "Alabama",
      lat: 30.7760,
      lng: -88.1000,
      dogPolicy: "Dogs welcome on all trails on a leash. A 1,100-acre county park north of Mobile with diverse habitats.",
      dogTrails: ["Nature Trail", "Mountain Bike Trail", "River Trail", "Swamp Trail"],
      restrictions: ["Leash required", "Must clean up after pet", "Check seasonal conditions"],
      description: "Mobile County's largest park offers over 15 miles of trails through pine forests, hardwood bottomlands, and along Chickasaw Creek. Dogs love the varied terrain and creek access points.",
      imageUrl: "",
      website: "https://www.mobilecounty.gov/chickasabogue",
    },
    {
      name: "Blakeley State Park",
      state: "Alabama",
      lat: 30.7410,
      lng: -87.9080,
      dogPolicy: "Dogs welcome on trails and in campgrounds on a 6-foot leash. Site of the last battle of the Civil War.",
      dogTrails: ["Battlefield Trail", "Bluff Trail", "Nature Loop"],
      restrictions: ["6-foot leash required", "Not in buildings", "Must clean up after pet"],
      description: "Located on the Tensaw River delta about 30 minutes from downtown Mobile, this state park preserves the site of the last major battle of the Civil War. Dogs can explore miles of trails through wetlands and historic earthworks.",
      imageUrl: "",
      website: "https://www.blakeleypark.com",
    },
  ],
  restaurants: [
    {
      name: "Spot of Tea",
      address: "310 Dauphin St, Mobile, AL 36602",
      lat: 30.6910,
      lng: -88.0400,
      cuisine: "Southern Brunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the sidewalk patio on Dauphin Street. A beloved brunch destination with Southern flair.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.spotoftea.com",
    },
    {
      name: "The Noble South",
      address: "203 Dauphin St, Mobile, AL 36602",
      lat: 30.6910,
      lng: -88.0420,
      cuisine: "Southern Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the courtyard patio. Refined Southern cuisine using locally sourced Gulf Coast ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thenoblesouth.com",
    },
    {
      name: "Wintzell's Oyster House",
      address: "605 Dauphin St, Mobile, AL 36602",
      lat: 30.6920,
      lng: -88.0370,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. A Mobile institution since 1938 serving Gulf oysters and seafood.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.wintzellsoysterhouse.com",
    },
    {
      name: "Moe's Original BBQ",
      address: "6423 Old Shell Rd, Mobile, AL 36608",
      lat: 30.6840,
      lng: -88.1200,
      cuisine: "Barbecue",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the large patio. Alabama-style BBQ with a laid-back atmosphere and live music.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.moesoriginalbbq.com",
    },
    {
      name: "Serda's Coffee Co.",
      address: "55 S Royal St, Mobile, AL 36602",
      lat: 30.6895,
      lng: -88.0430,
      cuisine: "Cafe & Light Fare",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the sidewalk patio in the historic district. Fresh coffee and breakfast items downtown.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.serdascoffee.com",
    },
  ],
  cafes: [
    {
      name: "Serda's Coffee Co.",
      address: "55 S Royal St, Mobile, AL 36602",
      lat: 30.6895,
      lng: -88.0430,
      dogPolicy: "Dogs welcome on the Royal Street patio. Mobile's premier coffee shop in a historic downtown building.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.serdascoffee.com",
    },
    {
      name: "Carpe Diem Coffee & Tea Company",
      address: "4072 Old Shell Rd, Mobile, AL 36608",
      lat: 30.6870,
      lng: -88.1000,
      dogPolicy: "Dogs welcome on the outdoor patio. A neighborhood coffee house near the University of South Alabama.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.carpediemcoffee.com",
    },
    {
      name: "Cream & Sugar",
      address: "62 N Section St, Mobile, AL 36602",
      lat: 30.6910,
      lng: -88.0460,
      dogPolicy: "Dogs welcome at the outdoor tables. Specialty espresso drinks and homemade pastries downtown.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.creamandsugar.com",
    },
    {
      name: "Three Georges Southern Chocolates & Coffee",
      address: "226 Dauphin St, Mobile, AL 36602",
      lat: 30.6910,
      lng: -88.0415,
      dogPolicy: "Dog-friendly outdoor seating on Dauphin Street. Handcrafted chocolates and coffee since 1917.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.threegeorges.com",
    },
  ],
  dogParks: [
    {
      name: "Medal of Honor Dog Park",
      address: "1500 Broad St, Mobile, AL 36615",
      lat: 30.6720,
      lng: -88.0500,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade structures", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "Mobile's dedicated off-leash dog park within Medal of Honor Park offers separate areas for large and small dogs with shaded rest areas and water stations. A popular spot for the local dog community.",
    },
    {
      name: "Langan Park",
      address: "4001 Zeigler Blvd, Mobile, AL 36608",
      lat: 30.6880,
      lng: -88.0930,
      offLeash: false,
      fenced: false,
      acres: 720,
      amenities: ["Lake walking paths", "Gardens", "Shaded trails", "Benches", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "Mobile's largest public park features a lake, botanical gardens, and miles of walking paths. Dogs on leash enjoy the expansive grounds and shaded trails through azalea gardens and live oak groves.",
    },
    {
      name: "Bienville Square",
      address: "Dauphin St & St. Joseph St, Mobile, AL 36602",
      lat: 30.6900,
      lng: -88.0410,
      offLeash: false,
      fenced: false,
      acres: 2,
      amenities: ["Iron fountain", "Benches", "Shade trees", "Historic downtown setting", "Waste bag stations"],
      rating: 4.2,
      imageUrl: "",
      description: "Mobile's most iconic public square features a beautiful iron fountain shaded by massive live oaks. Dogs on leash enjoy strolling through this historic downtown gathering place surrounded by restaurants and shops.",
    },
    {
      name: "Cottage Hill Dog Park",
      address: "5951 Cottage Hill Rd, Mobile, AL 36609",
      lat: 30.6670,
      lng: -88.1200,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Benches", "Water station", "Shade trees", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      description: "A west Mobile neighborhood dog park providing a fenced off-leash area with separate sections for different-sized dogs. Convenient for pups staying on the western side of the city.",
    },
  ],
};
