export const mysticData = {
  city: {
    name: "Mystic",
    state: "Connecticut",
    region: "Northeast",
    lat: 41.3543,
    lng: -71.9662,
    dogFriendlinessScore: 7,
    description:
      "Mystic is a storybook New England seaport where dogs trot along cobblestone streets, sniff salty breezes off the harbor, and charm tourists at every turn. This tiny village straddles the Mystic River with a famous bascule drawbridge, historic tall ships, and some of the best seafood in the Northeast. Dog-friendly patios overlook the harbor, coastal trails wind through salt marshes, and the whole town has an easygoing nautical charm that makes it feel like your pup was born to be a salty sea dog.",
    heroImage: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 4403,
  },

  hotels: [
    {
      name: "Whaler's Inn",
      address: "20 E Main St, Mystic, CT 06355",
      lat: 41.3545,
      lng: -71.9660,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in the Noank House building with a per-night fee. Steps from the drawbridge and downtown Mystic's best restaurants.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowl", "Welcome treats", "Walking map", "Harbor proximity"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.whalersinnmystic.com",
      phone: "(860) 536-1506",
    },
    {
      name: "Hilton Mystic",
      address: "20 Coogan Blvd, Mystic, CT 06355",
      lat: 41.3620,
      lng: -71.9490,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a one-time pet fee. Close to Olde Mistick Village and Mystic Aquarium.",
      maxDogWeight: 75,
      petFee: 75,
      amenities: ["Dog bed", "Bowls", "Outdoor walking area", "Near nature trails", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.hilton.com/en/hotels/mystic",
      phone: "(860) 572-0731",
    },
    {
      name: "The Inn at Mystic",
      address: "3 Williams Ave, Mystic, CT 06355",
      lat: 41.3490,
      lng: -71.9730,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms at this hilltop inn overlooking Mystic Harbor. Fifteen acres of manicured grounds for sunset walks with your pup.",
      maxDogWeight: 0,
      petFee: 60,
      amenities: ["Dog bed", "Treats", "15 acres of walking grounds", "Harbor views", "Garden paths"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.innatmystic.com",
      phone: "(860) 536-9604",
    },
    {
      name: "Harbour Inne & Cottage",
      address: "15 Edgemont St, Mystic, CT 06355",
      lat: 41.3555,
      lng: -71.9650,
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly cottage accommodations just steps from the Mystic River. Cozy, historic, and perfectly situated for exploring with your pup.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Cottage yard", "Dog bed", "Water bowls", "Walking distance to downtown"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.harbourinne-cottage.com",
      phone: "(860) 572-9253",
    },
    {
      name: "Hyatt Place Mystic",
      address: "224 Greenmanville Ave, Mystic, CT 06355",
      lat: 41.3600,
      lng: -71.9550,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a per-night fee. Modern amenities with easy access to Mystic Seaport and the village.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Bowls", "Grassy walking area", "Near Mystic Seaport"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hyatt.com/en-US/hotel/connecticut/hyatt-place-mystic",
      phone: "(860) 536-9997",
    },
  ],

  nationalParks: [
    {
      name: "Bluff Point State Park",
      state: "Connecticut",
      lat: 41.3245,
      lng: -72.0230,
      dogPolicy: "Leashed dogs welcome on all trails. One of the last undeveloped coastal properties in Connecticut and an absolute gem for dog walks.",
      dogTrails: ["Bluff Point Trail", "Coastal Trail to Beach", "Bushy Point Loop"],
      restrictions: [
        "Must be on leash at all times",
        "Dogs not allowed on beach during summer season (April 15 - September 30)",
        "Year-round access to trails",
      ],
      description:
        "Just 10 minutes from Mystic, this 806-acre coastal reserve juts into Long Island Sound with trails through forests, along bluffs, and down to a beautiful sandy beach. Leashed dogs can hike the 3-mile loop to the point where views stretch across the sound. Off-season beach walks with your pup are magical.",
      imageUrl: "",
      website: "https://www.ct.gov/deep",
    },
    {
      name: "Haley Farm State Park",
      state: "Connecticut",
      lat: 41.3355,
      lng: -71.9888,
      dogPolicy: "Leashed dogs welcome on all trails. A beautiful coastal park with stone walls, meadows, and water views.",
      dogTrails: ["Haley Farm Trail", "Palmer Cove Loop", "Coastal Walkway"],
      restrictions: [
        "Must be on leash at all times",
        "Owners must clean up after dogs",
      ],
      description:
        "Minutes from downtown Mystic, this former farm features trails winding through stone-walled meadows down to the coast. Your leashed pup will love the mix of forest paths and waterside walking, with views of the Fisher's Island Sound. The trails connect to Bluff Point for a longer adventure.",
      imageUrl: "",
      website: "https://www.ct.gov/deep",
    },
    {
      name: "Mashantucket Brook State Park",
      state: "Connecticut",
      lat: 41.5295,
      lng: -71.9620,
      dogPolicy: "Leashed dogs welcome on all trails. A quiet, forested park perfect for dogs who love woodland hiking.",
      dogTrails: ["Brook Trail", "Ridge Trail", "Pond Loop"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed in swimming areas",
      ],
      description:
        "About 20 minutes north of Mystic, this peaceful park offers wooded trails along a bubbling brook, a scenic pond, and gentle terrain perfect for dogs of all fitness levels. It is a quieter alternative to the coastal parks and a lovely escape into New England forest.",
      imageUrl: "",
      website: "https://www.ct.gov/deep",
    },
  ],

  restaurants: [
    {
      name: "Oyster Club",
      address: "13 Water St, Mystic, CT 06355",
      lat: 41.3548,
      lng: -71.9665,
      cuisine: "New England Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the riverside patio. Farm-to-table seafood with views of the Mystic River and drawbridge. Your pup gets harbor breezes while you get the freshest oysters in town.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.oysterclubct.com",
    },
    {
      name: "Engine Room",
      address: "14 Holmes St, Mystic, CT 06355",
      lat: 41.3540,
      lng: -71.9668,
      cuisine: "American Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Craft cocktails and creative pub fare in a converted industrial space.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.engineroomct.com",
    },
    {
      name: "Mystic Pizza",
      address: "56 W Main St, Mystic, CT 06355",
      lat: 41.3542,
      lng: -71.9680,
      cuisine: "Pizza",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor tables in front. Yes, it is the pizza place from the movie, and the pizza actually lives up to the hype.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.mysticpizza.com",
    },
    {
      name: "S&P Oyster Co.",
      address: "1 Holmes St, Mystic, CT 06355",
      lat: 41.3543,
      lng: -71.9666,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the waterfront deck overlooking the Mystic River. Watch boats pass by while enjoying lobster and local clams.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.sp-oyster.com",
    },
    {
      name: "The Captain Daniel Packer Inne",
      address: "32 Water St, Mystic, CT 06355",
      lat: 41.3550,
      lng: -71.9662,
      cuisine: "Colonial American",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome in the outdoor courtyard. Dine in a 1756 colonial inn where the atmosphere is as rich as the history.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.danielpacker.com",
    },
    {
      name: "Bark & Bite Biscuit Company",
      address: "4 Pearl St, Mystic, CT 06355",
      lat: 41.3538,
      lng: -71.9672,
      cuisine: "Bakery & Cafe",
      priceRange: "$" as const,
      dogPolicy: "A bakery that makes treats for both humans and dogs. Your pup gets a handmade biscuit while you enjoy a scone. Pure Mystic magic.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.barkandbitemystic.com",
    },
    {
      name: "Pizzetta",
      address: "7 Water St, Mystic, CT 06355",
      lat: 41.3546,
      lng: -71.9663,
      cuisine: "Italian",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the riverside patio. Artisan Neapolitan-style pizza with a craft beer selection and harbor views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.pizzettamystic.com",
    },
    {
      name: "Grass & Bone",
      address: "50 Williams Ave, Mystic, CT 06355",
      lat: 41.3495,
      lng: -71.9720,
      cuisine: "Farm-to-Table Butcher & Eatery",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome in the outdoor seating area. A whole-animal butcher shop and restaurant celebrating local farms and the nose-to-tail philosophy.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.grassandbone.com",
    },
  ],

  cafes: [
    {
      name: "Sift Bake Shop",
      address: "5 Water St, Mystic, CT 06355",
      lat: 41.3545,
      lng: -71.9664,
      dogPolicy: "Nationally recognized bakery with a small outdoor seating area. Dogs welcome while you agonize over choosing between the croissants and the macarons.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.8,
      imageUrl: "",
      website: "https://www.siftbakeshop.com",
    },
    {
      name: "Mystic Coffee Roasters",
      address: "10 Cottrell St, Mystic, CT 06355",
      lat: 41.3552,
      lng: -71.9658,
      dogPolicy: "Cozy coffee shop with outdoor seating where dogs can soak up the village atmosphere. Locally roasted beans and friendly baristas.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.mysticcoffeeroasters.com",
    },
    {
      name: "Drawbridge Ice Cream",
      address: "2 W Main St, Mystic, CT 06355",
      lat: 41.3543,
      lng: -71.9668,
      dogPolicy: "Window-service ice cream shop with outdoor benches overlooking the drawbridge. Dogs can enjoy a pup cup while you watch the bridge open for sailboats.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.drawbridgeicecream.com",
    },
    {
      name: "Trade Winds Gallery & Cafe",
      address: "42 W Main St, Mystic, CT 06355",
      lat: 41.3541,
      lng: -71.9678,
      dogPolicy: "Art gallery and cafe with a garden patio where well-behaved dogs are welcome. Browse local art with a latte in hand and your pup at your feet.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tradewindsmystic.com",
    },
    {
      name: "Deviant Donuts",
      address: "8 Steamboat Wharf, Mystic, CT 06355",
      lat: 41.3547,
      lng: -71.9661,
      dogPolicy: "Waterfront donut shop with outdoor seating. Your pup sits harbor-side while you enjoy gourmet donuts that are worth getting out of bed for.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.deviantdonuts.com",
    },
  ],

  dogParks: [
    {
      name: "Mystic River Park",
      address: "Cottrell St, Mystic, CT 06355",
      lat: 41.3560,
      lng: -71.9655,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["River views", "Walking paths", "Benches", "Drawbridge views", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A charming riverside park in the heart of Mystic village with walking paths and views of the iconic drawbridge. Leashed dogs love the waterfront promenade, and the people-watching is first-rate for curious pups.",
    },
    {
      name: "Coogan Farm Nature & Heritage Center",
      address: "162 Greenmanville Ave, Mystic, CT 06355",
      lat: 41.3610,
      lng: -71.9570,
      offLeash: false,
      fenced: false,
      acres: 62.0,
      amenities: ["Nature trails", "Meadows", "Stone walls", "Historical farm buildings", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A preserved farmstead with trails through meadows, forests, and along old stone walls. Leashed dogs can explore this slice of Connecticut history while sniffing out the remnants of colonial-era farming. Peaceful, scenic, and wonderfully uncrowded.",
    },
    {
      name: "Pequotsepos Brook Trail",
      address: "109 Pequotsepos Rd, Mystic, CT 06355",
      lat: 41.3470,
      lng: -71.9530,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Forest trails", "Brook access", "Wildlife viewing", "Quiet setting"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A quiet woodland trail following a babbling brook through dense New England forest. Leashed dogs love splashing in the shallow stream crossings and sniffing the moss-covered rocks. A perfect peaceful morning walk just minutes from downtown Mystic.",
    },
    {
      name: "Groton Dog Park",
      address: "163 Flanders Rd, Groton, CT 06340",
      lat: 41.3480,
      lng: -72.0080,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Separate small dog area", "Water fountain", "Shade trees", "Benches", "Waste stations", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "The nearest fully fenced off-leash park to Mystic, located in neighboring Groton. Separate areas for large and small dogs give everyone room to romp. A reliable go-to for off-leash energy burns after a day of leashed village exploring.",
    },
    {
      name: "Williams Beach Park",
      address: "Williams Ave, Mystic, CT 06355",
      lat: 41.3480,
      lng: -71.9740,
      offLeash: false,
      fenced: false,
      acres: 4.0,
      amenities: ["Beach access (seasonal)", "Picnic area", "Harbor views", "Parking", "Restrooms"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A small public park with harbor views and seasonal beach access. Leashed dogs can walk the grounds year-round and access the beach in the off-season. The views of Mystic Harbor with sailboats bobbing at anchor are quintessential Connecticut coast.",
    },
  ],
};
