export const napaData = {
  city: {
    name: "Napa",
    state: "California",
    region: "West Coast",
    lat: 38.2975,
    lng: -122.2869,
    dogFriendlinessScore: 7,
    description:
      "Wine country and dogs make a surprisingly perfect pairing in Napa, where many wineries welcome four-legged visitors and downtown patios spill onto tree-lined streets. With rolling vineyard trails, gourmet dining, and a relaxed pace of life, Napa is an elevated dog-friendly getaway.",
    heroImage: "https://images.unsplash.com/photo-1560840067-ddcaeb7831d2?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 79068,
  },
  hotels: [
    {
      name: "Archer Hotel Napa",
      address: "1230 First St, Napa, CA 94559",
      lat: 38.2990,
      lng: -122.2860,
      priceRange: "$$$$" as const,
      dogPolicy: "Luxury downtown hotel welcoming dogs under 40 lbs. Rooftop bar with vineyard views and a walkable First Street location.",
      maxDogWeight: 40,
      petFee: 125,
      amenities: ["Dog bed", "Gourmet treats", "Water bowls", "Walking map", "Rooftop bar"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.archerhotel.com/napa",
      phone: "(707) 690-9800",
    },
    {
      name: "Andaz Napa",
      address: "1450 First St, Napa, CA 94559",
      lat: 38.2985,
      lng: -122.2840,
      priceRange: "$$$" as const,
      dogPolicy: "Hyatt boutique hotel with pet-friendly rooms in downtown Napa. Dogs under 50 lbs welcome with walking distance to wine tasting.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Dog bed", "Water bowls", "Treats", "Downtown location", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hyatt.com/andaz/napa",
      phone: "(707) 687-1234",
    },
    {
      name: "Best Western Plus Inn at the Vines",
      address: "100 Soscol Ave, Napa, CA 94559",
      lat: 38.2960,
      lng: -122.2810,
      priceRange: "$$" as const,
      dogPolicy: "Comfortable downtown hotel welcoming dogs of all sizes. Easy access to the Napa Valley Wine Trail and river walk.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Pet-friendly rooms", "Pool", "Walking trail access", "Parking", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(707) 257-1930",
    },
    {
      name: "The Meritage Resort and Spa",
      address: "875 Bordeaux Way, Napa, CA 94558",
      lat: 38.2750,
      lng: -122.2650,
      priceRange: "$$$$" as const,
      dogPolicy: "Estate resort set among vineyards welcoming dogs under 75 lbs. Spacious grounds with walking paths through vineyard rows.",
      maxDogWeight: 75,
      petFee: 150,
      amenities: ["Vineyard walks", "Dog bed", "Treats", "Spa", "Estate grounds"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.meritagecollection.com",
      phone: "(707) 251-1900",
    },
  ],
  nationalParks: [
    {
      name: "Bothe-Napa Valley State Park",
      state: "California",
      lat: 38.5500,
      lng: -122.5200,
      dogPolicy: "Dogs allowed on the History Trail and in campgrounds on leash. A shaded retreat in the heart of Napa Valley.",
      dogTrails: ["History Trail", "Ritchey Creek Campground Loop"],
      restrictions: ["6-foot leash required", "Dogs only on History Trail and campground", "Not allowed on hiking trails", "Day use fee required"],
      description: "Located between St. Helena and Calistoga, this state park offers a cool, shaded escape from the valley floor. While dogs are limited to the History Trail and campgrounds, the redwood and Douglas fir forest provides a welcome break from wine tasting.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/bothe-napa",
    },
    {
      name: "Skyline Wilderness Park",
      state: "California",
      lat: 38.2700,
      lng: -122.2400,
      dogPolicy: "Dogs welcome on all trails on leash. One of the most dog-friendly hiking areas in the Napa Valley with varied terrain.",
      dogTrails: ["Lake Marie Trail", "Rim Trail", "Buckeye Trail", "Skyline Trail"],
      restrictions: ["Leash required on all trails", "Day use fee required", "Carry water on warm days", "Mountain bikes on some trails"],
      description: "This community park on the eastern edge of Napa offers miles of dog-friendly trails through oak woodlands, grasslands, and chaparral. The varied terrain includes a lake, seasonal creek crossings, and hilltop views of the entire Napa Valley.",
      imageUrl: "",
      website: "https://www.skylinepark.org",
    },
    {
      name: "Robert Louis Stevenson State Park",
      state: "California",
      lat: 38.6600,
      lng: -122.6000,
      dogPolicy: "Dogs allowed on the trail to the summit of Mount St. Helena on leash. Panoramic views from the highest peak in the Napa area.",
      dogTrails: ["Mount St. Helena Trail", "Table Rock Trail"],
      restrictions: ["Leash required", "No water available on trail", "Strenuous climb to summit", "No shade on upper portions"],
      description: "At the northern end of Napa Valley, this undeveloped state park offers a challenging hike to the 4,339-foot summit of Mount St. Helena. Dogs can join the climb and enjoy sweeping views of wine country, the Pacific Coast, and the Sierra Nevada on clear days.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/rlstevenson",
    },
  ],
  restaurants: [
    {
      name: "Oenotri",
      address: "1425 First St, Napa, CA 94559",
      lat: 38.2987,
      lng: -122.2845,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Award-winning Italian restaurant with a dog-friendly patio on First Street. House-made pasta and wood-fired pizzas with Napa wines.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.oenotri.com",
    },
    {
      name: "Gott's Roadside",
      address: "644 First St, Napa, CA 94559",
      lat: 38.2995,
      lng: -122.2870,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Iconic Napa burger stand with outdoor picnic seating where dogs are welcome. Burgers, ahi tuna sandwiches, and milkshakes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.gotts.com",
    },
    {
      name: "Angele Restaurant & Bar",
      address: "540 Main St, Napa, CA 94559",
      lat: 38.2980,
      lng: -122.2880,
      cuisine: "French Bistro",
      priceRange: "$$$" as const,
      dogPolicy: "Charming French bistro with a waterfront patio along the Napa River. Dogs welcome while you enjoy country French cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.angelerestaurant.com",
    },
    {
      name: "Oxbow Public Market",
      address: "610 First St, Napa, CA 94559",
      lat: 38.2998,
      lng: -122.2875,
      cuisine: "Food Hall",
      priceRange: "$$" as const,
      dogPolicy: "Gourmet food hall with multiple outdoor seating areas welcoming dogs. Artisan food vendors, oyster bar, and wine tastings.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.oxbowpublicmarket.com",
    },
    {
      name: "La Taquiza",
      address: "2007 Redwood Rd, Napa, CA 94558",
      lat: 38.2800,
      lng: -122.2700,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Casual fish taco spot with outdoor picnic tables where dogs are welcome. Fresh ceviche and tacos in a no-fuss setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.lataquiza.com",
    },
  ],
  cafes: [
    {
      name: "Ritual Coffee Roasters Napa",
      address: "1300 First St, Napa, CA 94559",
      lat: 38.2992,
      lng: -122.2855,
      dogPolicy: "San Francisco roaster with a Napa outpost and outdoor seating where dogs are welcome. Precision-roasted single-origin coffees.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ritualroasters.com",
    },
    {
      name: "Napa Valley Coffee Roasting Company",
      address: "948 Main St, Napa, CA 94559",
      lat: 38.2970,
      lng: -122.2860,
      dogPolicy: "Local roaster with a cozy downtown location and sidewalk seating where dogs are welcome. A Napa morning tradition.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.napavalleycoffee.com",
    },
    {
      name: "Loveski Deli",
      address: "1245 First St, Napa, CA 94559",
      lat: 38.2988,
      lng: -122.2858,
      dogPolicy: "Jewish-style deli and café with outdoor seating on First Street. Dogs welcome at patio tables with water available.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.loveskideli.com",
    },
    {
      name: "Model Bakery",
      address: "644 First St, Napa, CA 94559",
      lat: 38.2996,
      lng: -122.2872,
      dogPolicy: "Famous Napa bakery known for their English muffins with a patio where dogs are welcome. Coffee and pastries in the heart of downtown.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.themodelbakery.com",
    },
  ],
  dogParks: [
    {
      name: "Alston Park Dog Park",
      address: "2099 Dry Creek Rd, Napa, CA 94558",
      lat: 38.3100,
      lng: -122.3100,
      offLeash: true,
      fenced: false,
      acres: 157,
      amenities: ["Hiking trails", "Open meadows", "Oak groves", "Views", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "Napa's premier off-leash destination with 157 acres of rolling hills, oak-studded meadows, and panoramic valley views. Dogs run free on the trails while enjoying the same vineyard-dotted landscape that makes wine country famous.",
    },
    {
      name: "Shurtleff Park Dog Area",
      address: "840 Shurtleff Ave, Napa, CA 94559",
      lat: 38.2940,
      lng: -122.2800,
      offLeash: true,
      fenced: true,
      acres: 1,
      amenities: ["Fenced area", "Water station", "Benches", "Shade trees", "Waste bag stations"],
      rating: 4.2,
      imageUrl: "",
      description: "A small fenced off-leash area within Shurtleff Park in downtown Napa. Convenient for a quick play session while exploring the city, with mature trees providing shade.",
    },
    {
      name: "Napa Valley Vine Trail",
      address: "500 Main St, Napa, CA 94559",
      lat: 38.2975,
      lng: -122.2880,
      offLeash: false,
      fenced: false,
      acres: 30,
      amenities: ["Paved trail", "River views", "Vineyard scenery", "Benches", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "A paved multi-use trail winding through the heart of Napa Valley alongside vineyards and the Napa River. Leashed dogs enjoy miles of scenic walking through wine country with their owners.",
    },
    {
      name: "Westwood Hills Park",
      address: "Browns Valley Rd, Napa, CA 94558",
      lat: 38.2900,
      lng: -122.3000,
      offLeash: false,
      fenced: false,
      acres: 110,
      amenities: ["Hiking trails", "Oak woodlands", "Valley views", "Wildflowers", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description: "A hillside park with trails through oak woodlands offering sweeping views of the Napa Valley. Leashed dogs enjoy the varied terrain and wildflower displays in spring, with moderate trails suitable for all fitness levels.",
    },
  ],
};
