export const naplesFlData = {
  city: {
    name: "Naples",
    state: "Florida",
    region: "Southeast",
    lat: 26.1420,
    lng: -81.7948,
    dogFriendlinessScore: 7,
    description:
      "Naples combines upscale Gulf Coast living with a surprisingly dog-friendly attitude, featuring a dedicated dog beach, lush nature preserves, and sophisticated patio dining along Fifth Avenue. The warm year-round climate and beautiful sunsets make every walk with your pup feel like a vacation.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&fit=crop",
    climate: "Tropical savanna",
    population: 22088,
  },
  hotels: [
    {
      name: "Inn on Fifth",
      address: "699 5th Ave S, Naples, FL 34102",
      lat: 26.1420,
      lng: -81.7980,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs under 20 lbs welcome in designated pet-friendly rooms with a nightly fee. Premier Fifth Avenue location.",
      maxDogWeight: 20,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking map", "Concierge pet services"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.innonfifth.com",
      phone: "(239) 403-8777",
    },
    {
      name: "La Playa Beach & Golf Resort",
      address: "9891 Gulf Shore Dr, Naples, FL 34108",
      lat: 26.2100,
      lng: -81.8110,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs under 25 lbs welcome with a non-refundable pet fee. A beachfront resort on Vanderbilt Beach.",
      maxDogWeight: 25,
      petFee: 150,
      amenities: ["Dog bed", "Water and food bowls", "Beach towel for pets", "Dog waste bags", "Pet-sitting referral"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.laplayaresort.com",
      phone: "(239) 597-3123",
    },
    {
      name: "Staybridge Suites Naples",
      address: "4805 Tamiami Trail N, Naples, FL 34103",
      lat: 26.1780,
      lng: -81.7950,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 80 lbs welcome with a non-refundable pet fee. Extended-stay suites with full kitchens.",
      maxDogWeight: 80,
      petFee: 75,
      amenities: ["Pet-friendly suites", "Full kitchen", "Waste bags", "Nearby walking areas", "Dog treat at check-in"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.ihg.com/staybridge/hotels/us/en/naples",
      phone: "(239) 643-8002",
    },
    {
      name: "Homewood Suites Naples",
      address: "5665 Naples Blvd, Naples, FL 34109",
      lat: 26.2220,
      lng: -81.7740,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome with a nightly pet fee. Comfortable suites with kitchens near shopping and dining.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Pet-friendly suites", "Full kitchen", "Waste bags", "Walking area", "Water bowls on request"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.hilton.com/en/hotels/apfnhw",
      phone: "(239) 566-0600",
    },
  ],
  nationalParks: [
    {
      name: "Everglades National Park",
      state: "Florida",
      lat: 25.2866,
      lng: -80.8987,
      dogPolicy: "Dogs are allowed only in parking lots, campgrounds, and on paved roads. Not permitted on trails, in the backcountry, or on boardwalks.",
      dogTrails: [],
      restrictions: ["No dogs on any trails", "No dogs on boardwalks", "Only in campgrounds and parking areas", "Must be on leash at all times", "Alligator danger"],
      description: "The largest subtropical wilderness in the United States lies about 90 minutes from Naples. While dog access is extremely limited due to sensitive ecosystems and alligator presence, the park entrance areas offer a glimpse of this unique landscape.",
      imageUrl: "",
      website: "https://www.nps.gov/ever",
    },
    {
      name: "Corkscrew Swamp Sanctuary",
      state: "Florida",
      lat: 26.3750,
      lng: -81.6100,
      dogPolicy: "Dogs are NOT permitted at Corkscrew Swamp Sanctuary to protect the wildlife habitat.",
      dogTrails: [],
      restrictions: ["No pets of any kind", "Wildlife sanctuary"],
      description: "While dogs are not allowed, this Audubon sanctuary protects the largest remaining stand of old-growth bald cypress in North America. Consider visiting without your pup and exploring dog-friendly parks on other days.",
      imageUrl: "",
      website: "https://www.corkscrew.audubon.org",
    },
    {
      name: "Delnor-Wiggins Pass State Park",
      address: "11135 Gulfshore Dr, Naples, FL 34108",
      state: "Florida",
      lat: 26.2260,
      lng: -81.8150,
      dogPolicy: "Dogs welcome on a 6-foot leash in the park but NOT on the beach. Walking along the river and mangrove areas is permitted.",
      dogTrails: ["Observation Tower Trail", "Mangrove Walk"],
      restrictions: ["No dogs on the beach", "6-foot leash required", "Not in picnic pavilions", "Must clean up after pet"],
      description: "This state park on the north end of Naples features a beautiful beach and coastal habitats. While dogs cannot access the beach, they can enjoy the mangrove-lined trails and observation areas.",
      imageUrl: "",
      website: "https://www.floridastateparks.org/delnorwiggins",
    },
  ],
  restaurants: [
    {
      name: "The Local",
      address: "5323 Airport-Pulling Rd, Naples, FL 34109",
      lat: 26.2140,
      lng: -81.7780,
      cuisine: "Farm-to-Table American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. A beloved locals' spot with farm-fresh seasonal menus and craft cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thelocalnaples.com",
    },
    {
      name: "Campiello",
      address: "1177 3rd St S, Naples, FL 34102",
      lat: 26.1380,
      lng: -81.7960,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the courtyard patio. Upscale Italian dining on charming Third Street South.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.campiello.damico.com",
    },
    {
      name: "Three60 Market",
      address: "2891 Bayview Dr, Naples, FL 34112",
      lat: 26.1190,
      lng: -81.7880,
      cuisine: "Cafe & Market",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. A gourmet market with prepared foods, coffee, and a waterfront setting.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.three60market.com",
    },
    {
      name: "Grouper & Chips",
      address: "338 9th St N, Naples, FL 34102",
      lat: 26.1490,
      lng: -81.7960,
      cuisine: "Seafood",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor picnic tables. A no-frills British-style fish and chips shop with super-fresh Gulf seafood.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.grouperandchips.com",
    },
    {
      name: "Barbatella",
      address: "1290 3rd St S, Naples, FL 34102",
      lat: 26.1380,
      lng: -81.7955,
      cuisine: "Italian",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor terrace. Rustic Italian small plates and housemade pasta on Third Street South.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.barbatellanaples.com",
    },
  ],
  cafes: [
    {
      name: "Narrative Coffee Roasters",
      address: "4838 Davis Blvd, Naples, FL 34104",
      lat: 26.1360,
      lng: -81.7670,
      dogPolicy: "Dogs welcome on the outdoor patio. A specialty roaster with carefully sourced beans and a modern aesthetic.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.narrativecoffee.com",
    },
    {
      name: "Gumby's Pizza & Wings",
      address: "862 5th Ave S, Naples, FL 34102",
      lat: 26.1410,
      lng: -81.7960,
      dogPolicy: "Dogs welcome at outdoor Fifth Avenue seating. Casual spot for coffee and light bites on a walk downtown.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.0,
      imageUrl: "",
      website: "https://www.gumbyspizza.com",
    },
    {
      name: "Grace & Shelly's Cupcakes",
      address: "819 5th Ave S, Naples, FL 34102",
      lat: 26.1410,
      lng: -81.7965,
      dogPolicy: "Dogs welcome at the outdoor sidewalk tables on Fifth Avenue. Gourmet cupcakes and coffee in the heart of downtown.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.graceandshellyscupcakes.com",
    },
    {
      name: "Kunjani Craft Coffee & Gallery",
      address: "2764 Tamiami Trail N, Naples, FL 34103",
      lat: 26.1650,
      lng: -81.7950,
      dogPolicy: "Dog-friendly outdoor seating. A unique combination of specialty coffee and local art gallery.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.kunjanicraftcoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Naples Dog Park at Sugden Regional Park",
      address: "4284 Avalon Dr, Naples, FL 34112",
      lat: 26.1180,
      lng: -81.7810,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade structures", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "The most popular dog park in Naples, located within Sugden Regional Park on Lake Avalon. Separate areas for large and small dogs with shade structures to beat the Florida heat.",
    },
    {
      name: "Rover Run Dog Park",
      address: "1500 Veterans Community Park, Naples, FL 34109",
      lat: 26.2130,
      lng: -81.7800,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Separate small dog area", "Water fountains", "Agility equipment", "Benches", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      description: "A well-equipped dog park in north Naples with agility equipment and separate sections for different-sized dogs. The park provides plenty of shade and water to keep dogs comfortable in the warm climate.",
    },
    {
      name: "Naples Dog Beach",
      address: "100 Bluebill Ave, Naples, FL 34108",
      lat: 26.2070,
      lng: -81.8150,
      offLeash: false,
      fenced: false,
      acres: 5,
      amenities: ["Beach access", "Gulf swimming", "Waste bag stations", "Parking", "Outdoor shower"],
      rating: 4.7,
      imageUrl: "",
      description: "One of Naples' most treasured spots for dog owners, this stretch of Vanderbilt Beach allows leashed dogs to enjoy the white sand and Gulf waters. Dogs can splash in the waves and dig in the sand alongside their owners.",
    },
    {
      name: "Canine Cove at North Collier Regional Park",
      address: "15000 Livingston Rd, Naples, FL 34109",
      lat: 26.2500,
      lng: -81.7670,
      offLeash: true,
      fenced: true,
      acres: 4,
      amenities: ["Large open fields", "Water stations", "Shade pavilion", "Separate small dog area", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "A spacious off-leash park within North Collier Regional Park featuring shaded pavilions and water stations. The large fenced area gives dogs plenty of room to run in the north Naples area.",
    },
  ],
};
