export const natchezData = {
  city: {
    name: "Natchez",
    state: "Mississippi",
    region: "Southeast",
    lat: 31.5604,
    lng: -91.4032,
    dogFriendlinessScore: 6,
    description:
      "Perched on bluffs overlooking the mighty Mississippi River, this antebellum treasure offers dogs scenic river walks, the historic Natchez Trace, and charming downtown strolls past grand plantation homes. The city's slower pace and natural beauty make it a peaceful retreat for dogs and their owners.",
    heroImage: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 14520,
  },
  hotels: [
    {
      name: "The Guest House at Natchez",
      address: "211 N Pearl St, Natchez, MS 39120",
      lat: 31.5610,
      lng: -91.3940,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a pet fee. An elegant boutique hotel in a restored historic building downtown.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking map", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.theguesthousenatchez.com",
      phone: "(601) 442-1054",
    },
    {
      name: "Magnolia Bluffs Casino Hotel",
      address: "7 Roth Hill Rd, Natchez, MS 39120",
      lat: 31.5540,
      lng: -91.4070,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a per-night pet fee. A riverfront hotel with Mississippi River views.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Pet-friendly rooms", "River views", "Walking paths", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.magnoliabluffscasino.com",
      phone: "(601) 235-0045",
    },
    {
      name: "Natchez Grand Hotel",
      address: "111 Broadway St, Natchez, MS 39120",
      lat: 31.5600,
      lng: -91.3950,
      priceRange: "$$" as const,
      dogPolicy: "Dogs under 40 lbs welcome in select rooms. A comfortable downtown hotel near the bluffs.",
      maxDogWeight: 40,
      petFee: 50,
      amenities: ["Pet-friendly rooms", "Walking access to bluffs", "Water bowls", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.natchezgrandhotel.com",
      phone: "(601) 446-9994",
    },
    {
      name: "Hampton Inn & Suites Natchez",
      address: "550 D'Evereux Dr, Natchez, MS 39120",
      lat: 31.5500,
      lng: -91.3830,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome with a nightly fee. Modern hotel on the east side of town.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Pet-friendly rooms", "Waste bags", "Walking areas", "Complimentary breakfast"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.hilton.com/en/hotels/hksnthx",
      phone: "(601) 446-0882",
    },
  ],
  nationalParks: [
    {
      name: "Natchez Trace Parkway",
      state: "Mississippi",
      lat: 31.5600,
      lng: -91.3500,
      dogPolicy: "Dogs welcome on trails and at overlooks on a 6-foot leash. The southern terminus of this 444-mile scenic parkway is in Natchez.",
      dogTrails: ["Emerald Mound Trail", "Loess Bluff Trail", "Natchez Trace Parkway Terminus Walk"],
      restrictions: ["6-foot leash required", "Not allowed in buildings", "Must clean up after pet", "Stay on marked trails"],
      description: "The Natchez Trace Parkway follows the historic route of Native Americans and early settlers for 444 miles from Natchez to Nashville. The southern sections offer bluff views, Native American mounds, and cypress swamps.",
      imageUrl: "",
      website: "https://www.nps.gov/natr",
    },
    {
      name: "Natchez National Historical Park",
      state: "Mississippi",
      lat: 31.5570,
      lng: -91.3960,
      dogPolicy: "Dogs welcome on the grounds of Melrose estate and Fort Rosalie on a 6-foot leash. Not permitted inside buildings.",
      dogTrails: ["Melrose Estate Grounds", "Fort Rosalie Walk"],
      restrictions: ["6-foot leash required", "Not allowed inside historic buildings", "Must clean up after pet"],
      description: "This national park preserves the rich history of Natchez through sites including the antebellum Melrose estate and Fort Rosalie. Dogs can walk the beautifully landscaped grounds and enjoy the river bluff views.",
      imageUrl: "",
      website: "https://www.nps.gov/natc",
    },
    {
      name: "Homochitto National Forest",
      state: "Mississippi",
      lat: 31.3100,
      lng: -91.1500,
      dogPolicy: "Dogs welcome on all trails. Over 189,000 acres of rolling pine forests south of Natchez.",
      dogTrails: ["Clear Springs Nature Trail", "Pipes Lake Trail", "Turkey Fork Trail"],
      restrictions: ["Leash recommended", "Check seasonal hunting dates", "Must clean up after pet"],
      description: "About 30 minutes south of Natchez, Homochitto National Forest offers gentle trails through longleaf pine forests and past clear springs. Dogs enjoy the quiet woodland paths and swimming holes.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/homochitto",
    },
  ],
  restaurants: [
    {
      name: "The Camp Restaurant",
      address: "44 1/2 Silver St, Natchez, MS 39120",
      lat: 31.5590,
      lng: -91.4050,
      cuisine: "Southern Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the deck overlooking the Mississippi River. Fresh Gulf seafood with stunning river views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thecampnatchez.com",
    },
    {
      name: "Fat Mama's Tamales",
      address: "303 S Canal St, Natchez, MS 39120",
      lat: 31.5570,
      lng: -91.3970,
      cuisine: "Tamales & Southern",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor picnic tables. Famous delta tamales and Knock-You-Naked margaritas.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.fatmamastamales.com",
    },
    {
      name: "Bowie's Tavern",
      address: "510 Franklin St, Natchez, MS 39120",
      lat: 31.5615,
      lng: -91.3960,
      cuisine: "American Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the front patio. Elevated pub fare with craft cocktails in a historic downtown building.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bowiestavern.com",
    },
    {
      name: "Magnolia Grill",
      address: "49 Silver St, Natchez, MS 39120",
      lat: 31.5585,
      lng: -91.4050,
      cuisine: "Cajun & Southern",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the patio at Silver Street Under-the-Hill. Casual Cajun eats with live music and river vibes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.magnoliagrill.com",
    },
    {
      name: "Restaurant 1818",
      address: "118 N Pearl St, Natchez, MS 39120",
      lat: 31.5615,
      lng: -91.3940,
      cuisine: "Fine Dining Southern",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the courtyard patio. Elegant Southern cuisine in a historic downtown setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.restaurant1818.com",
    },
  ],
  cafes: [
    {
      name: "Steampunk Coffee Roasters",
      address: "606 Franklin St, Natchez, MS 39120",
      lat: 31.5620,
      lng: -91.3960,
      dogPolicy: "Dogs welcome on the outdoor patio. A specialty roaster with steampunk decor and carefully crafted coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.steampunkcoffeeroasters.com",
    },
    {
      name: "Natchez Coffee Company",
      address: "510 Main St, Natchez, MS 39120",
      lat: 31.5610,
      lng: -91.3945,
      dogPolicy: "Dogs welcome at the outdoor tables. Fresh coffee and pastries in the heart of downtown Natchez.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.natchezcoffee.com",
    },
    {
      name: "The Parlor at Natchez",
      address: "200 N Pearl St, Natchez, MS 39120",
      lat: 31.5615,
      lng: -91.3940,
      dogPolicy: "Dogs welcome on the porch. A charming cafe in a historic building with coffee, tea, and homemade treats.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.theparlornatchez.com",
    },
    {
      name: "Silver Street Coffee",
      address: "30 Silver St, Natchez, MS 39120",
      lat: 31.5585,
      lng: -91.4040,
      dogPolicy: "Dog-friendly outdoor seating Under-the-Hill with river views. Coffee and light bites in a historic district.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.silverstreetcoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Natchez Bluff Park",
      address: "Broadway St, Natchez, MS 39120",
      lat: 31.5600,
      lng: -91.4000,
      offLeash: false,
      fenced: false,
      acres: 5,
      amenities: ["Mississippi River views", "Gazebos", "Benches", "Walking paths", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "Perched on the bluffs 200 feet above the Mississippi River, this scenic park offers some of the most dramatic river views in the South. Dogs on leash enjoy the breezy walkways and panoramic vistas.",
    },
    {
      name: "Duncan Park",
      address: "48 Duncan Park Dr, Natchez, MS 39120",
      lat: 31.5540,
      lng: -91.3850,
      offLeash: false,
      fenced: false,
      acres: 140,
      amenities: ["Golf course views", "Walking paths", "Open fields", "Shade trees", "Waste bag stations"],
      rating: 4.2,
      imageUrl: "",
      description: "One of the oldest golf courses in America doubles as a lovely walking area with mature trees and rolling landscapes. Dogs on leash enjoy the expansive grounds and shaded paths.",
    },
    {
      name: "Natchez Under-the-Hill",
      address: "Silver St, Natchez, MS 39120",
      lat: 31.5585,
      lng: -91.4050,
      offLeash: false,
      fenced: false,
      acres: 3,
      amenities: ["River access", "Historic district", "Restaurants nearby", "Benches"],
      rating: 4.3,
      imageUrl: "",
      description: "The historic riverfront district at the base of the bluffs offers scenic walks along the Mississippi River. Dogs on leash can explore the historic streets and enjoy the river breezes.",
    },
    {
      name: "Liberty Road Park",
      address: "200 Liberty Rd, Natchez, MS 39120",
      lat: 31.5480,
      lng: -91.3870,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Fenced area", "Water station", "Benches", "Shade trees", "Waste bag stations"],
      rating: 4.0,
      imageUrl: "",
      description: "A community park with a fenced off-leash dog area providing a rare off-leash opportunity in Natchez. The shaded fenced section lets dogs run freely while owners relax on benches.",
    },
  ],
};
