export const newHopeData = {
  city: {
    name: "New Hope",
    state: "Pennsylvania",
    region: "Northeast",
    lat: 40.3646,
    lng: -74.9513,
    dogFriendlinessScore: 7,
    description:
      "This artsy village along the Delaware River is a tail-wagging wonderland where Victorian charm meets bohemian spirit. With galleries that welcome browsing pups, canal towpath walks, and restaurant patios overlooking the river, New Hope proves that good things come in small, dog-friendly packages. The town's creative energy extends to its four-legged visitors — expect treats at every turn.",
    heroImage: "https://images.unsplash.com/photo-1520962880247-cfaf541c8724?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 2528,
  },

  hotels: [
    {
      name: "Ghost Light Inn",
      address: "46 S Main St, New Hope, PA 18938",
      lat: 40.3622,
      lng: -74.9510,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with a one-time pet fee. Boutique riverside hotel with theatrical flair.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Water bowls", "Walking distance to towpath", "River views"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ghostlightinn.com",
      phone: "(215) 862-9164",
    },
    {
      name: "Logan Inn",
      address: "10 W Ferry St, New Hope, PA 18938",
      lat: 40.3648,
      lng: -74.9520,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in designated rooms. One of the oldest inns in America, continuously operating since 1727.",
      maxDogWeight: 60,
      petFee: 50,
      amenities: ["Historic rooms", "Dog bed", "Bowls", "Garden courtyard", "Steps from Main Street"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.loganinn.com",
      phone: "(215) 862-2300",
    },
    {
      name: "Homewood Suites Doylestown",
      address: "3670 Bristol Rd, Doylestown, PA 18902",
      lat: 40.3185,
      lng: -75.0740,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a nightly fee. Extended-stay suites with full kitchens, 20 minutes from New Hope.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Full kitchen", "Grassy area", "Pool", "Complimentary breakfast", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com/homewood-suites",
      phone: "(215) 489-1800",
    },
    {
      name: "HawkRidge",
      address: "2600 N River Rd, New Hope, PA 18938",
      lat: 40.3830,
      lng: -74.9488,
      priceRange: "$$$$" as const,
      dogPolicy: "Select cottages welcome dogs with advance notice. Luxury Bucks County retreat on the Delaware River.",
      maxDogWeight: 0,
      petFee: 100,
      amenities: ["Private cottages", "River access", "Hiking trails", "Dog bed", "Gourmet treats"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.hawkridge.com",
      phone: "(215) 862-2224",
    },
    {
      name: "Best Western Plus New Hope Inn",
      address: "6426 Lower York Rd, New Hope, PA 18938",
      lat: 40.3520,
      lng: -74.9685,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a per-night fee. Reliable comfort close to downtown New Hope.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Dog bowls on request", "Grassy walking area", "Pool", "Complimentary breakfast", "Parking"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(215) 862-5221",
    },
  ],

  nationalParks: [
    {
      name: "Delaware Water Gap National Recreation Area",
      state: "Pennsylvania",
      lat: 41.0534,
      lng: -75.0150,
      dogPolicy: "Leashed dogs welcome on most trails, beaches, and picnic areas. One of the most dog-friendly NPS sites in the Northeast.",
      dogTrails: [
        "Dingmans Falls Trail",
        "Karamac Trail",
        "McDade Recreational Trail (32 miles)",
        "Buttermilk Falls Trail",
        "Smithfield Beach area",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Not allowed in swim-guarded beach areas during summer",
        "Not allowed in buildings",
        "Clean up after pets",
      ],
      description:
        "Stretching 40 miles along the Delaware River, this recreation area is a paradise for dogs with over 100 miles of trails, waterfalls, and river beaches. The McDade Recreational Trail alone offers 32 miles of scenic river-hugging paths perfect for leashed pups.",
      imageUrl: "",
      website: "https://www.nps.gov/dewa",
    },
    {
      name: "Valley Forge National Historical Park",
      state: "Pennsylvania",
      lat: 40.1006,
      lng: -75.4444,
      dogPolicy: "Leashed dogs welcome on all trails and grounds. A beautiful blend of history and nature with excellent dog access.",
      dogTrails: [
        "Joseph Plumb Martin Trail (6 miles)",
        "River Trail (3.8 miles)",
        "Grand Parade grounds",
        "Valley Creek Trail",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Not allowed inside historic buildings",
        "Not allowed in the visitor center",
      ],
      description:
        "Where Washington's army endured the harsh winter of 1777-78, your dog can now trot along miles of scenic trails through meadows and forests. The rolling hills and historic monuments make this a rewarding day trip from New Hope.",
      imageUrl: "",
      website: "https://www.nps.gov/vafo",
    },
    {
      name: "Washington Crossing Historical Park",
      state: "Pennsylvania",
      lat: 40.2942,
      lng: -74.8722,
      dogPolicy: "Leashed dogs welcome on the grounds and trails. Walk where Washington crossed the Delaware with your loyal companion.",
      dogTrails: [
        "River path along the Delaware",
        "Bowman's Hill Tower Trail",
        "Wildflower Preserve trails",
      ],
      restrictions: [
        "Must be on leash",
        "Not allowed in historic buildings",
        "Not allowed in the wildflower preserve during peak bloom",
      ],
      description:
        "This state park preserving the site of Washington's famous 1776 crossing offers riverside trails and the stunning Bowman's Hill Wildflower Preserve. Just minutes from New Hope, leashed dogs can soak up history along the Delaware.",
      imageUrl: "",
      website: "https://www.washingtoncrossingpark.org",
    },
  ],

  restaurants: [
    {
      name: "Marsha Brown",
      address: "15 S Main St, New Hope, PA 18938",
      lat: 40.3635,
      lng: -74.9508,
      cuisine: "Creole Steakhouse",
      priceRange: "$$$$" as const,
      dogPolicy: "Leashed dogs welcome on the garden patio. Upscale Creole cuisine in a converted stone church.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.marshabrowrestaurant.com",
    },
    {
      name: "The Landing",
      address: "22 N Main St, New Hope, PA 18938",
      lat: 40.3650,
      lng: -74.9510,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the spacious deck overlooking the Delaware River. A New Hope classic for decades.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.landingnewhope.com",
    },
    {
      name: "Havana",
      address: "105 S Main St, New Hope, PA 18938",
      lat: 40.3610,
      lng: -74.9505,
      cuisine: "Eclectic American & Bar",
      priceRange: "$$$" as const,
      dogPolicy: "Pups welcome on the back patio. Lively bar scene with creative cocktails and bistro fare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.havananewhope.com",
    },
    {
      name: "Bowman's Tavern",
      address: "1600 River Rd, New Hope, PA 18938",
      lat: 40.3380,
      lng: -74.9395,
      cuisine: "American Tavern",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio with a relaxed Bucks County atmosphere. Live music on weekends.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.bowmanstavern.com",
    },
    {
      name: "Nektar Wine Bar",
      address: "40 W Ferry St, New Hope, PA 18938",
      lat: 40.3646,
      lng: -74.9525,
      cuisine: "Wine Bar & Small Plates",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the patio. An extensive wine list with shareable plates in a cozy setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.nektarwinebar.com",
    },
    {
      name: "Karla's",
      address: "5 W Mechanic St, New Hope, PA 18938",
      lat: 40.3645,
      lng: -74.9518,
      cuisine: "Eastern European & American",
      priceRange: "$$" as const,
      dogPolicy: "Outdoor tables welcome leashed dogs. Hearty portions of pierogies and schnitzel alongside American classics.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.karlasnewhope.com",
    },
    {
      name: "Wildflowers Garden Restaurant",
      address: "8 W Mechanic St, New Hope, PA 18938",
      lat: 40.3644,
      lng: -74.9520,
      cuisine: "Asian Fusion",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in the outdoor garden dining area. Creative Asian-inspired dishes in a lush garden setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.wildflowersnewhope.com",
    },
    {
      name: "Triumph Brewing Company",
      address: "400 Union Square Dr, New Hope, PA 18938",
      lat: 40.3570,
      lng: -74.9545,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Large dog-friendly patio with house-brewed ales and a full pub menu. A great post-walk reward.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.triumphbrewing.com",
    },
  ],

  cafes: [
    {
      name: "Café Collective",
      address: "1 E Bridge St, New Hope, PA 18938",
      lat: 40.3652,
      lng: -74.9508,
      dogPolicy: "Leashed dogs welcome on the sidewalk patio. Artisan coffee and pastries in the heart of New Hope.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cafecollective.com",
    },
    {
      name: "C'est La Vie French Bakery",
      address: "20 S Main St, New Hope, PA 18938",
      lat: 40.3630,
      lng: -74.9505,
      dogPolicy: "Outdoor seating for dog owners. Authentic French pastries and coffee on New Hope's charming Main Street.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.cestlaviefrenchbakery.com",
    },
    {
      name: "Honey",
      address: "38 S Main St, New Hope, PA 18938",
      lat: 40.3625,
      lng: -74.9503,
      dogPolicy: "Patio tables welcome well-behaved dogs. Modern cafe with honey-infused specialties and local goods.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.honeynewhope.com",
    },
    {
      name: "Nina's Waffles & Ice Cream",
      address: "28 S Main St, New Hope, PA 18938",
      lat: 40.3628,
      lng: -74.9504,
      dogPolicy: "Sidewalk ordering window means easy pup access. Pup cups available alongside Belgian waffles.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Larksville Coffee",
      address: "402 York Rd, New Hope, PA 18938",
      lat: 40.3580,
      lng: -74.9560,
      dogPolicy: "Covered porch seating welcomes leashed dogs. House-roasted beans and cozy Bucks County vibes.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "",
    },
  ],

  dogParks: [
    {
      name: "Delaware Canal Towpath",
      address: "S Main St, New Hope, PA 18938",
      lat: 40.3615,
      lng: -74.9495,
      offLeash: false,
      fenced: false,
      acres: 60.0,
      amenities: ["60-mile towpath trail", "Canal views", "Flat terrain", "Shade trees", "Waste stations"],
      rating: 4.7,
      imageUrl: "",
      description:
        "The historic Delaware Canal towpath stretches 60 miles along a tranquil canal shaded by sycamores and oaks. Leashed dogs love the flat, easy surface and the chance to watch ducks paddling in the canal. The quintessential New Hope dog walk.",
    },
    {
      name: "New Hope-Lambertville Pedestrian Bridge",
      address: "Bridge St, New Hope, PA 18938",
      lat: 40.3655,
      lng: -74.9498,
      offLeash: false,
      fenced: false,
      acres: 1.0,
      amenities: ["River views", "Pedestrian bridge", "Connects to Lambertville NJ", "Photo opportunities"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Walk your leashed pup across the Delaware River on this pedestrian bridge connecting New Hope to charming Lambertville, NJ. The river views are stunning and your dog gets to visit two states in one walk.",
    },
    {
      name: "Bowman's Hill Wildflower Preserve",
      address: "1635 River Rd, New Hope, PA 18938",
      lat: 40.3345,
      lng: -74.9380,
      offLeash: false,
      fenced: false,
      acres: 134.0,
      amenities: ["Nature trails", "Wildflower meadows", "Bird watching", "Visitor center", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "This 134-acre preserve features trails through native plant communities and wildflower meadows. Leashed dogs can explore winding paths through forests and along streams. Seasonal restrictions may apply during peak bloom.",
    },
    {
      name: "Goat Hill Overlook Park",
      address: "Goat Hill Rd, Lambertville, NJ 08530",
      lat: 40.3680,
      lng: -74.9430,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["River overlook", "Hiking trails", "Forest canopy", "Parking", "Picnic area"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Just across the river in Lambertville, this hilltop park offers panoramic views of the Delaware River valley. Short but rewarding trails through forest lead to overlooks where your leashed pup can take in the scenery.",
    },
    {
      name: "Central Park of New Hope",
      address: "48 W Bridge St, New Hope, PA 18938",
      lat: 40.3660,
      lng: -74.9535,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["Green space", "Walking paths", "Benches", "Shade trees", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A charming town park in the center of New Hope where leashed dogs can stretch their legs on the walking paths. Mature shade trees and benches make it a relaxing stop between gallery hops and cafe visits.",
    },
  ],
};
