export const newOrleansData = {
  city: {
    name: "New Orleans",
    state: "Louisiana",
    region: "Southeast",
    lat: 29.9511,
    lng: -90.0715,
    dogFriendlinessScore: 8,
    description:
      "The Big Easy is surprisingly welcoming to four-legged friends with its abundance of outdoor patios, lush parks, and a laid-back culture that embraces dogs at cafes, bars, and even some Mardi Gras parades. From strolling the French Quarter to lounging in City Park, dogs are part of the family in New Orleans.",
    heroImage: "https://images.unsplash.com/photo-1568402102990-bc541580b59f?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 383997,
  },
  hotels: [
    {
      name: "Hotel Monteleone",
      address: "214 Royal St, New Orleans, LA 70130",
      lat: 29.9559,
      lng: -90.0659,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 35 lbs welcome in designated pet-friendly rooms. A historic French Quarter landmark with a revolving carousel bar.",
      maxDogWeight: 35,
      petFee: 100,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking map", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelmonteleone.com",
      phone: "(504) 523-3341",
    },
    {
      name: "Kimpton Hotel Fontenot",
      address: "501 Tchoupitoulas St, New Orleans, LA 70130",
      lat: 29.9488,
      lng: -90.0660,
      priceRange: "$$$" as const,
      dogPolicy: "All pets welcome at no extra charge regardless of size or breed. Kimpton's signature pet-friendly philosophy in the Warehouse District.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Loaner leashes", "Pet concierge"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.ihg.com/kimptonhotels/hotels/us/en/new-orleans",
      phone: "(504) 324-3000",
    },
    {
      name: "The Eliza Jane Hotel",
      address: "315 Magazine St, New Orleans, LA 70130",
      lat: 29.9503,
      lng: -90.0672,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a pet fee. Boutique hotel in the Central Business District with courtyard access.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Food and water bowls", "Courtyard access", "Waste bags", "Nearby park guide"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.theelizajane.com",
      phone: "(504) 203-2106",
    },
    {
      name: "La Quinta Inn & Suites New Orleans Downtown",
      address: "301 Camp St, New Orleans, LA 70130",
      lat: 29.9490,
      lng: -90.0705,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome at no additional fee. Convenient downtown location near the streetcar line.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Pet-friendly rooms", "Waste bags", "Nearby walking routes", "Water bowls on request"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta",
      phone: "(504) 598-9977",
    },
  ],
  nationalParks: [
    {
      name: "Jean Lafitte National Historical Park and Preserve",
      state: "Louisiana",
      lat: 29.7855,
      lng: -90.1109,
      dogPolicy: "Dogs are allowed on the Barataria Preserve trails on a 6-foot leash. Not permitted in buildings or on ranger-led walks.",
      dogTrails: ["Bayou Coquille Trail", "Marsh Overlook Trail", "Plantation Trail"],
      restrictions: ["6-foot leash required", "Not allowed in visitor center", "Not permitted on ranger programs", "Must clean up after pet"],
      description: "Just south of New Orleans, the Barataria Preserve offers a stunning look at Louisiana bayou country with boardwalk trails through cypress swamps and freshwater marshes. Dogs can explore the trails and spot alligators from a safe distance.",
      imageUrl: "",
      website: "https://www.nps.gov/jela",
    },
    {
      name: "City Park",
      state: "Louisiana",
      lat: 29.9863,
      lng: -90.0985,
      dogPolicy: "Dogs welcome throughout the park on a leash. One of the largest urban parks in the country with 1,300 acres of green space.",
      dogTrails: ["Big Lake Loop", "Couturie Forest Trail", "Sculpture Garden Path", "Lagoon Trail"],
      restrictions: ["Leash required at all times", "Not allowed in the playground areas", "Must clean up after pet"],
      description: "New Orleans' beloved City Park spans 1,300 acres of ancient live oaks, lagoons, and botanical gardens. Dogs can stroll beneath centuries-old trees draped in Spanish moss and enjoy the expansive green spaces year-round.",
      imageUrl: "",
      website: "https://www.neworleanscitypark.com",
    },
    {
      name: "Fontainebleau State Park",
      state: "Louisiana",
      lat: 30.3530,
      lng: -90.0602,
      dogPolicy: "Dogs welcome on all trails on a 6-foot leash. Campgrounds and picnic areas are also pet-friendly.",
      dogTrails: ["Lakeshore Trail", "Nature Trail", "Old Railroad Trail"],
      restrictions: ["6-foot leash required", "Not allowed on beaches", "Must clean up after pet", "Dogs not permitted in cabins"],
      description: "Located on the north shore of Lake Pontchartrain about an hour from downtown, this state park features sandy beaches, pine forests, and the ruins of a sugar mill. Dogs enjoy the shaded nature trails and lakeside breezes.",
      imageUrl: "",
      website: "https://www.lastateparks.com/parks-preserves/fontainebleau-state-park",
    },
  ],
  restaurants: [
    {
      name: "Dat Dog",
      address: "601 Frenchmen St, New Orleans, LA 70116",
      lat: 29.9635,
      lng: -90.0570,
      cuisine: "Hot Dogs & Sausages",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the spacious patio. Fittingly named, this spot celebrates dogs with a fun outdoor atmosphere on Frenchmen Street.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.datdog.com",
    },
    {
      name: "Bacchanal Fine Wine & Spirits",
      address: "600 Poland Ave, New Orleans, LA 70117",
      lat: 29.9635,
      lng: -90.0393,
      cuisine: "Wine Bar & Small Plates",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the lush outdoor courtyard where live jazz plays nightly. A magical evening experience with your pup.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bacchanalwine.com",
    },
    {
      name: "The Columns Hotel",
      address: "3811 St Charles Ave, New Orleans, LA 70115",
      lat: 29.9270,
      lng: -90.1000,
      cuisine: "Southern American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the iconic front porch overlooking St. Charles Avenue. A grand setting for cocktails and Southern fare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thecolumns.com",
    },
    {
      name: "Bud's Broiler",
      address: "500 City Park Ave, New Orleans, LA 70119",
      lat: 29.9790,
      lng: -90.0920,
      cuisine: "Burgers",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor picnic tables. A no-frills New Orleans burger institution since 1952.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.budsbroiler.com",
    },
    {
      name: "Lucy's Retired Surfers Bar & Restaurant",
      address: "701 Tchoupitoulas St, New Orleans, LA 70130",
      lat: 29.9465,
      lng: -90.0645,
      cuisine: "Tex-Mex & Bar Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the large covered patio. Casual beach-bar vibes in the Warehouse District with great tacos.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.lucysretiredsurfers.com",
    },
  ],
  cafes: [
    {
      name: "French Truck Coffee",
      address: "4536 Magazine St, New Orleans, LA 70115",
      lat: 29.9232,
      lng: -90.1037,
      dogPolicy: "Dogs welcome on the outdoor patio. A local roaster with bold coffee and a laid-back Magazine Street vibe.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.frenchtruckcoffee.com",
    },
    {
      name: "Mojo Coffee House",
      address: "1500 Magazine St, New Orleans, LA 70130",
      lat: 29.9389,
      lng: -90.0755,
      dogPolicy: "Dogs welcome in the courtyard garden. A cozy Lower Garden District hangout with strong coffee and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.mojocoffeehouse.com",
    },
    {
      name: "Revelator Coffee",
      address: "637 Tchoupitoulas St, New Orleans, LA 70130",
      lat: 29.9474,
      lng: -90.0652,
      dogPolicy: "Sleek Warehouse District cafe with a dog-friendly patio. Specialty espresso drinks in a stylish setting.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.revelatorcoffee.com",
    },
    {
      name: "Coffee Science",
      address: "410 S Broad St, New Orleans, LA 70119",
      lat: 29.9605,
      lng: -90.0870,
      dogPolicy: "Dogs welcome at outdoor tables. A neighborhood favorite known for precise brewing methods and friendly baristas.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.coffeescience.us",
    },
  ],
  dogParks: [
    {
      name: "NOLA City Bark",
      address: "City Park, New Orleans, LA 70124",
      lat: 29.9920,
      lng: -90.1010,
      offLeash: true,
      fenced: true,
      acres: 4,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade structures", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "The premier off-leash dog park in New Orleans is set within the beautiful City Park. Dogs romp freely in separate large and small dog areas beneath towering live oaks draped in Spanish moss.",
    },
    {
      name: "Cabrini Dog Park",
      address: "Moss St & N Dupre St, New Orleans, LA 70119",
      lat: 29.9780,
      lng: -90.0880,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Double-gated entry", "Water fountain", "Benches", "Shade trees", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      description: "A compact but popular neighborhood dog park in Mid-City near Bayou St. John. Local dogs gather here for off-leash play in a friendly, community-oriented setting.",
    },
    {
      name: "Algiers Dog Park",
      address: "900 Powder St, New Orleans, LA 70114",
      lat: 29.9460,
      lng: -90.0500,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Benches", "Water spigot", "Shade structures", "Gravel surface"],
      rating: 4.0,
      imageUrl: "",
      description: "Located on the West Bank in the Algiers neighborhood, this fenced park provides a quieter alternative to the busier parks across the river. Dogs enjoy ample running space with river breezes.",
    },
    {
      name: "Bonnabel Boat Launch Dog Park",
      address: "1 Bonnabel Blvd, Metairie, LA 70005",
      lat: 30.0170,
      lng: -90.1520,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Lake views", "Water access", "Benches", "Waste bag stations", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description: "Situated on the shores of Lake Pontchartrain in nearby Metairie, this dog park offers lakefront views and breezes. Dogs can enjoy off-leash play with the scenic lake as a backdrop.",
    },
  ],
};
