export const newportOrData = {
  city: {
    name: "Newport",
    state: "Oregon",
    region: "Pacific Northwest",
    lat: 44.6368,
    lng: -124.0535,
    dogFriendlinessScore: 7,
    description:
      "Newport is a classic Oregon coast town where dogs can run free on miles of sandy beaches, explore tide pools, and enjoy the salty ocean air. The historic Bayfront is full of dog-friendly seafood spots, and the dramatic coastal scenery from headlands and lighthouses makes every walk an adventure.",
    heroImage: "https://images.unsplash.com/photo-1541701494587-cb553e5e0b15?w=1200&fit=crop",
    climate: "Oceanic marine",
    population: 10630,
  },

  hotels: [
    {
      name: "Hallmark Resort & Spa Newport",
      address: "744 SW Elizabeth St, Newport, OR 97365",
      lat: 44.6310,
      lng: -124.0590,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in ocean-view pet rooms with a per-night fee. Direct beach access from the property.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Dog bed", "Water bowls", "Beach access", "Pet waste stations", "Ocean-view rooms"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hallmarkinns.com",
      phone: "(541) 265-2600",
    },
    {
      name: "Elizabeth Street Inn",
      address: "232 SW Elizabeth St, Newport, OR 97365",
      lat: 44.6315,
      lng: -124.0580,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a modest pet fee. Oceanfront inn with complimentary breakfast.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Beach access", "Ocean views", "Pet waste stations", "Grassy areas", "Water bowls"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.elizabethstreetinn.com",
      phone: "(541) 265-9400",
    },
    {
      name: "La Quinta Inn & Suites Newport",
      address: "45 SE 32nd St, Newport, OR 97365",
      lat: 44.6340,
      lng: -124.0440,
      priceRange: "$" as const,
      dogPolicy: "Two dogs per room welcome at no extra charge. Budget-friendly with easy access to the bay and beach.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Pet waste stations", "Grassy areas", "Near beach access", "Water bowls at front desk"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta",
      phone: "(541) 867-7727",
    },
    {
      name: "Sylvia Beach Hotel",
      address: "267 NW Cliff St, Newport, OR 97365",
      lat: 44.6380,
      lng: -124.0585,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the ground-floor pet room only. Unique literary-themed oceanfront hotel on Nye Beach.",
      maxDogWeight: 40,
      petFee: 30,
      amenities: ["Beach access", "Ocean views", "Library", "Dog bed"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sylviabeachhotel.com",
      phone: "(541) 265-5428",
    },
  ],

  nationalParks: [
    {
      name: "Oregon Coast National Wildlife Refuge",
      state: "Oregon",
      lat: 44.6400,
      lng: -124.0600,
      dogPolicy: "Dogs not allowed on most refuge lands to protect wildlife. Leashed dogs allowed on adjacent public beaches.",
      dogTrails: ["Adjacent Nye Beach walk", "South Beach State Park trails (nearby)"],
      restrictions: [
        "No dogs on refuge trails or beaches",
        "Must be on leash on adjacent public beaches",
        "Not allowed near seal haul-out areas",
      ],
      description:
        "The Oregon Coast refuges protect critical habitat for seabirds, marine mammals, and shorebirds. While dogs cannot access refuge lands, the adjacent public beaches and state parks provide excellent alternatives for coastal dog walks.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/oregon-coast",
    },
    {
      name: "Siuslaw National Forest",
      state: "Oregon",
      lat: 44.5000,
      lng: -123.9000,
      dogPolicy: "Leashed dogs welcome on most trails. Voice control acceptable on backcountry trails away from campgrounds.",
      dogTrails: ["Mike Miller Trail", "South Beach Dunes Trail", "Drift Creek Falls Trail", "Horse Creek Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on backcountry trails",
        "Not allowed in designated swimming areas",
      ],
      description:
        "The coastal forests and dunes around Newport provide excellent dog-friendly hiking. The Drift Creek Falls Trail, about 30 minutes inland, offers a dramatic suspension bridge and waterfall that dogs and owners both love.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/siuslaw",
    },
    {
      name: "South Beach State Park",
      state: "Oregon",
      lat: 44.6100,
      lng: -124.0530,
      dogPolicy: "Leashed dogs welcome on the beach and trails. Dogs allowed in the campground.",
      dogTrails: ["South Jetty Trail", "Beach Trail", "Cooper Ridge Nature Trail"],
      restrictions: [
        "Must be on leash in campground and day-use areas",
        "Off-leash allowed on the beach",
        "Not allowed in yurt interiors",
      ],
      description:
        "Just south of Newport, this state park offers miles of wide, sandy beach where dogs can run. The campground is dog-friendly and the jetty walk offers great views of the harbor and ocean.",
      imageUrl: "",
      website: "https://www.oregonstateparks.org",
    },
  ],

  restaurants: [
    {
      name: "Local Ocean Seafoods",
      address: "213 SE Bay Blvd, Newport, OR 97365",
      lat: 44.6340,
      lng: -124.0490,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the bayfront patio. Sustainably sourced seafood with bay views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.localocean.net",
    },
    {
      name: "Rogue Ales Bayfront Public House",
      address: "748 SW Bay Blvd, Newport, OR 97365",
      lat: 44.6335,
      lng: -124.0510,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor deck. Flagship Rogue Ales location with bayfront views and pub food.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.rogue.com",
    },
    {
      name: "Nana's Irish Pub",
      address: "613 NW 3rd St, Newport, OR 97365",
      lat: 44.6370,
      lng: -124.0540,
      cuisine: "Irish Pub",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the patio. Classic Irish pub fare and live music in Nye Beach.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.nanaspub.com",
    },
    {
      name: "Cafe Mundo",
      address: "209 NW Coast St, Newport, OR 97365",
      lat: 44.6375,
      lng: -124.0555,
      cuisine: "International Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor patio. Global-inspired cuisine in a cozy Nye Beach setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cafemundonewport.com",
    },
    {
      name: "Georgie's Beachside Grill",
      address: "744 SW Elizabeth St, Newport, OR 97365",
      lat: 44.6312,
      lng: -124.0588,
      cuisine: "American Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Dogs allowed on the outdoor terrace with ocean views. Classic beachside dining.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.georgiesbeachsidegrill.com",
    },
  ],

  cafes: [
    {
      name: "Nye Beach Cafe",
      address: "526 NW Coast St, Newport, OR 97365",
      lat: 44.6378,
      lng: -124.0558,
      dogPolicy: "Dogs welcome on the outdoor patio. Charming beachside cafe with fresh pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.nyebeachcafe.com",
    },
    {
      name: "Coffee House Too",
      address: "156 SW Bay Blvd, Newport, OR 97365",
      lat: 44.6338,
      lng: -124.0500,
      dogPolicy: "Dog-friendly outdoor seating on the bayfront. Coffee and breakfast with harbor views.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.coffeehousetooonline.com",
    },
    {
      name: "Panini Bakery",
      address: "232 NW Coast St, Newport, OR 97365",
      lat: 44.6372,
      lng: -124.0552,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Artisan bakery with Italian-inspired pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.paninibakery.com",
    },
    {
      name: "Coastal Coffee Company",
      address: "825 SW Bay Blvd, Newport, OR 97365",
      lat: 44.6333,
      lng: -124.0515,
      dogPolicy: "Outdoor patio welcomes dogs. Local roaster with views of the working waterfront.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.coastalcoffeecompany.com",
    },
  ],

  dogParks: [
    {
      name: "Nye Beach Off-Leash Area",
      address: "NW Beach Dr, Newport, OR 97365",
      lat: 44.6390,
      lng: -124.0600,
      offLeash: true,
      fenced: false,
      acres: 50.0,
      amenities: ["Sandy beach", "Ocean access", "Waste stations", "Parking", "Restrooms"],
      rating: 4.8,
      imageUrl: "",
      description:
        "Oregon's beaches are public land, and dogs can run off-leash on most Newport beaches under voice control. Nye Beach offers wide sandy stretches, tide pools, and crashing waves that dogs absolutely love.",
    },
    {
      name: "Agate Beach",
      address: "Agate Beach Wayside, Newport, OR 97365",
      lat: 44.6550,
      lng: -124.0630,
      offLeash: true,
      fenced: false,
      acres: 40.0,
      amenities: ["Sandy beach", "Agate hunting", "Parking", "Restrooms", "Beach access trail"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A popular beach north of Newport where dogs can run off-leash. Known for agate hunting, long stretches of sand, and beautiful views of Yaquina Head Lighthouse. Dogs love the wide open spaces.",
    },
    {
      name: "Don Davis Park",
      address: "NE Harney St & NE 12th St, Newport, OR 97365",
      lat: 44.6380,
      lng: -124.0420,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Separate small dog area", "Water station", "Benches", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Newport's dedicated off-leash dog park with fully fenced areas. A great alternative on rainy days when the beach is too windy, with separate spaces for large and small dogs.",
    },
    {
      name: "South Beach State Park Beach",
      address: "5580 S Coast Hwy, Newport, OR 97366",
      lat: 44.6100,
      lng: -124.0545,
      offLeash: true,
      fenced: false,
      acres: 60.0,
      amenities: ["Wide sandy beach", "Dunes", "Jetty access", "Parking", "Restrooms", "Campground"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Miles of wide sandy beach south of the Yaquina Bay Bridge. Dogs can run off-leash on the beach and explore the dunes. The south jetty walk offers views of the harbor and fishing boats.",
    },
  ],
};
