export const newportRiData = {
  city: {
    name: "Newport",
    state: "Rhode Island",
    region: "Northeast",
    lat: 41.4901,
    lng: -71.3128,
    dogFriendlinessScore: 7,
    description:
      "Newport's Cliff Walk, harbor views, and dog-friendly beaches make this sailing capital a wonderful destination for pups. The historic seaside town welcomes dogs on its famous coastal paths, at waterfront restaurants, and even on some of its gilded-age mansion grounds.",
    heroImage: "https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 24697,
  },
  hotels: [
    {
      name: "The Chanler at Cliff Walk",
      address: "117 Memorial Blvd, Newport, RI 02840",
      lat: 41.4725,
      lng: -71.3036,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs under 30 lbs welcome in select rooms with a $150 per stay fee. Luxury pet amenities including a Chanler dog bed.",
      maxDogWeight: 30,
      petFee: 150,
      amenities: ["Luxury pet bed", "Dog bowls", "Cliff Walk access", "Ocean views", "Concierge"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.thechanler.com",
      phone: "(401) 847-1300",
    },
    {
      name: "Hotel Viking",
      address: "1 Bellevue Ave, Newport, RI 02840",
      lat: 41.484,
      lng: -71.3125,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a $75 per stay fee. Historic downtown hotel with rooftop bar and garden.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Rooftop bar", "Downtown location", "Pet bed", "Walking maps", "Garden courtyard"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hotelviking.com",
      phone: "(401) 847-3300",
    },
    {
      name: "Newport Harbor Hotel & Marina",
      address: "49 Americas Cup Ave, Newport, RI 02840",
      lat: 41.4895,
      lng: -71.3218,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome with a $50 per night fee. Waterfront rooms overlook the harbor. Walking distance to Thames Street.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Harbor views", "Marina access", "Waterfront dining", "Downtown walkability"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.newporthotel.com",
      phone: "(401) 847-9000",
    },
    {
      name: "La Forge Suites",
      address: "78 Washington Square, Newport, RI 02840",
      lat: 41.4885,
      lng: -71.3157,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly suites with a $40 per night fee. Central location on Washington Square with kitchen amenities.",
      maxDogWeight: 60,
      petFee: 40,
      amenities: ["Kitchen", "Central location", "Near Touro Park", "Suite-style rooms"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.laforgesuites.com",
      phone: "(401) 847-4400",
    },
  ],
  nationalParks: [
    {
      name: "Cliff Walk",
      state: "Rhode Island",
      lat: 41.4688,
      lng: -71.2987,
      dogPolicy: "Leashed dogs welcome on the entire 3.5-mile coastal path. One of the most scenic dog walks on the East Coast.",
      dogTrails: ["Cliff Walk (3.5 miles)", "Forty Steps Section", "Rough Trail Southern Section"],
      restrictions: ["Leash required", "Rocky terrain in southern sections", "Clean up required"],
      description:
        "Newport's iconic Cliff Walk traces 3.5 miles along dramatic ocean cliffs with Gilded Age mansions on one side and crashing Atlantic waves on the other. Your leashed dog will love the salt air and ocean spray. The northern section is paved and accessible; the southern section gets rugged and adventurous.",
      imageUrl: "",
      website: "https://www.cliffwalk.com",
    },
    {
      name: "Norman Bird Sanctuary",
      state: "Rhode Island",
      lat: 41.5077,
      lng: -71.2761,
      dogPolicy: "Leashed dogs welcome on all trails. Over 300 acres of diverse habitats with seven miles of hiking trails.",
      dogTrails: ["Hanging Rock Trail", "Red Maple Trail", "Woodcock Trail", "Ridge Trail"],
      restrictions: ["Leash required at all times", "No dogs in barn area", "Clean up required"],
      description:
        "Over 300 acres of meadows, forest, rocky ridges, and coastal habitats with panoramic views of the ocean and Sachuest Point. The Hanging Rock Trail leads to a dramatic overlook, and the varied terrain keeps dogs engaged. A perfect alternative to the crowded Cliff Walk.",
      imageUrl: "",
      website: "https://www.normanbirdsanctuary.org",
    },
    {
      name: "Fort Adams State Park",
      state: "Rhode Island",
      lat: 41.4792,
      lng: -71.3377,
      dogPolicy: "Leashed dogs welcome on the grounds and along the waterfront. The massive fort and harbor views make for an epic walk.",
      dogTrails: ["Fort Adams Perimeter Trail", "Bay Walk", "Eisenhower House Grounds"],
      restrictions: ["Leash required", "No dogs inside fort during tours", "Clean up required"],
      description:
        "Home to the Newport Jazz and Folk Festivals, this state park surrounds a massive 19th-century coastal fort with sweeping views of Narragansett Bay and the Newport Bridge. The perimeter trail offers water views from every angle, and your dog can explore the fort's grassy grounds while sailboats glide by.",
      imageUrl: "",
      website: "https://www.fortadams.org",
    },
  ],
  restaurants: [
    {
      name: "The Mooring Seafood Kitchen & Bar",
      address: "1 Sayers Wharf, Newport, RI 02840",
      lat: 41.4896,
      lng: -71.3243,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Waterfront deck welcomes leashed dogs. Fresh seafood with panoramic harbor views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.mooringrestaurant.com",
    },
    {
      name: "Diego's",
      address: "11 Bowen's Wharf, Newport, RI 02840",
      lat: 41.4886,
      lng: -71.3236,
      cuisine: "Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly outdoor patio on Bowen's Wharf. Margaritas and tacos with harbor views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.diegosnewport.com",
    },
    {
      name: "The Red Parrot",
      address: "348 Thames St, Newport, RI 02840",
      lat: 41.4892,
      lng: -71.3178,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Sidewalk seating on Thames Street welcomes dogs. Classic American fare in a lively atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.redparrotrestaurant.com",
    },
    {
      name: "Brick Alley Pub",
      address: "140 Thames St, Newport, RI 02840",
      lat: 41.4874,
      lng: -71.3165,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Large outdoor patio area welcomes leashed dogs. A Newport institution with massive portions.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.brickalley.com",
    },
    {
      name: "The Lawn at Castle Hill Inn",
      address: "590 Ocean Ave, Newport, RI 02840",
      lat: 41.4624,
      lng: -71.3607,
      cuisine: "American",
      priceRange: "$$$$" as const,
      dogPolicy: "Sunset lawn dining with ocean views. Leashed dogs welcome on the lawn area. Reservations essential.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.castlehillinn.com",
    },
  ],
  cafes: [
    {
      name: "Empire Tea & Coffee",
      address: "22 Broadway, Newport, RI 02840",
      lat: 41.489,
      lng: -71.314,
      dogPolicy: "Cozy downtown coffee shop with outdoor benches on Broadway. Dogs welcome outside while you sip expertly brewed pour-overs.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.empireteaandcoffee.com",
    },
    {
      name: "The Coffee Grinder",
      address: "33 Bannisters Wharf, Newport, RI 02840",
      lat: 41.4885,
      lng: -71.3228,
      dogPolicy: "Waterfront coffee spot on Bannister's Wharf. Grab a coffee and stroll the docks with your leashed pup.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Simple Merchant Coffee",
      address: "388 Thames St, Newport, RI 02840",
      lat: 41.4895,
      lng: -71.3183,
      dogPolicy: "Specialty coffee on Thames Street with sidewalk seating. Dogs welcome at outdoor tables.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Spruce Cafe",
      address: "55 Memorial Blvd W, Newport, RI 02840",
      lat: 41.4782,
      lng: -71.3146,
      dogPolicy: "Charming neighborhood cafe near Bellevue Avenue. Outdoor patio with shaded seating and dog water bowls.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Brenton Point State Park",
      address: "Ocean Ave, Newport, RI 02840",
      lat: 41.4501,
      lng: -71.345,
      offLeash: false,
      fenced: false,
      acres: 89.0,
      amenities: ["Ocean views", "Kite flying", "Walking paths", "Parking", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A spectacular oceanfront park at the southern tip of Aquidneck Island where leashed dogs can run along the rocky coast with 270-degree ocean views. The constant sea breeze, crashing waves, and wide-open grassy fields make this one of the most dramatic dog walk locations in New England.",
    },
    {
      name: "Sachuest Beach (Second Beach) Dog Area",
      address: "474 Sachuest Point Rd, Middletown, RI 02842",
      lat: 41.4872,
      lng: -71.2638,
      offLeash: true,
      fenced: false,
      acres: 3.0,
      amenities: ["Beach access", "Off-leash seasonal", "Parking", "Restrooms", "Surf"],
      rating: 4.5,
      imageUrl: "",
      description:
        "One of Rhode Island's best dog beaches, Second Beach allows off-leash dogs during the off-season (October through March). Your pup can sprint along the sandy beach, splash in the waves, and roll in the surf to their heart's content. Summer requires leash and restricted hours.",
    },
    {
      name: "Miantonomi Park",
      address: "Hillside Ave, Newport, RI 02840",
      lat: 41.4942,
      lng: -71.3069,
      offLeash: false,
      fenced: false,
      acres: 17.0,
      amenities: ["City views", "Historic tower", "Walking paths", "Benches", "Shade trees"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A hilltop park in the heart of Newport with panoramic views from a historic stone observation tower. The grassy grounds and walking paths are popular with leashed dogs, and the elevated location catches ocean breezes. A peaceful spot away from the tourist crowds.",
    },
    {
      name: "Founders Brook Dog Park",
      address: "Boyd Ln, Portsmouth, RI 02871",
      lat: 41.5576,
      lng: -71.2867,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fully fenced", "Separate small dog area", "Water station", "Benches", "Shade"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A short drive from downtown Newport, this fenced dog park on Aquidneck Island offers separate areas for large and small dogs. The shaded, well-maintained space is a favorite for dogs who need some serious off-leash running time after a day of on-leash sightseeing.",
    },
  ],
};
