export const northConwayData = {
  city: {
    name: "North Conway",
    state: "New Hampshire",
    region: "Northeast",
    lat: 44.0537,
    lng: -71.1285,
    dogFriendlinessScore: 7,
    description:
      "North Conway is the gateway to the White Mountains and a paradise for dogs who love hiking, swimming, and rolling in autumn leaves. This small village in the Mount Washington Valley has been drawing adventurers for over a century, and these days many of them have four legs. The town offers a charming Main Street lined with shops and restaurants, tax-free shopping, and some of the most spectacular mountain scenery in the East. Your dog can summit 4,000-footers, swim in pristine rivers, and crash exhausted in a cozy mountain lodge. New England dog life at its absolute peak.",
    heroImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 2349,
  },

  hotels: [
    {
      name: "White Mountain Hotel and Resort",
      address: "2560 West Side Rd, North Conway, NH 03860",
      lat: 44.0680,
      lng: -71.1480,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in designated pet rooms with stunning views of White Horse Ledge. Sprawling grounds and hiking trail access right from the property.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Walking trails", "Mountain views", "Near Echo Lake State Park"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.whitemountainhotel.com",
      phone: "(603) 356-7100",
    },
    {
      name: "The Red Jacket Mountain View Resort",
      address: "2251 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0420,
      lng: -71.1190,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select rooms at this classic White Mountain resort. Large grounds, indoor pool, and mountain panoramas.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Grassy grounds", "Mountain views", "Near Saco River", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.redjacketresorts.com",
      phone: "(603) 356-5411",
    },
    {
      name: "Adventure Suites",
      address: "3440 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0720,
      lng: -71.1310,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in themed suite rooms. A quirky, fun hotel where you might sleep in a cave, a treehouse, or a jungle, and your dog is invited along for the adventure.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Themed rooms", "Dog bed", "Outdoor area", "Near village"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.adventuresuites.com",
      phone: "(603) 356-9744",
    },
    {
      name: "Comfort Inn & Suites North Conway",
      address: "2001 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0380,
      lng: -71.1170,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms with a per-night fee. Reliable and well-located for exploring the Mount Washington Valley with your pup.",
      maxDogWeight: 75,
      petFee: 35,
      amenities: ["Dog bed on request", "Outdoor walking area", "Near shopping", "Waste bags"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.choicehotels.com",
      phone: "(603) 356-8811",
    },
    {
      name: "Cranmore Mountain Lodge",
      address: "859 Kearsarge Rd, North Conway, NH 03860",
      lat: 44.0620,
      lng: -71.1100,
      priceRange: "$$" as const,
      dogPolicy: "A historic, dog-loving B&B with its own resident pups. Your dog will feel like part of the family at this warm, welcoming mountain lodge.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Dog bed", "Fenced yard", "Pool access", "Tennis courts", "Near Cranmore Mountain"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.cranmoremtnlodge.com",
      phone: "(603) 356-2044",
    },
  ],

  nationalParks: [
    {
      name: "White Mountain National Forest",
      state: "New Hampshire",
      lat: 44.1000,
      lng: -71.3000,
      dogPolicy: "Leashed dogs welcome on most trails. Over 1,200 miles of trails through spectacular mountain terrain, making it one of the best dog-hiking destinations in the Northeast.",
      dogTrails: ["Mount Willard Trail", "Diana's Baths Trail", "Arethusa Falls Trail", "Welch-Dickey Loop", "Mount Eisenhower via Edmands Path"],
      restrictions: [
        "Must be on leash in developed areas",
        "Voice control on most backcountry trails",
        "Some trails extremely steep and not suitable for all dogs",
        "Check trail conditions in winter",
      ],
      description:
        "The White Mountain National Forest is the crown jewel of New England hiking, with 48 peaks over 4,000 feet, roaring waterfalls, and alpine zones above treeline. Your dog can tackle everything from easy waterfall strolls to challenging summit climbs. The fall foliage here is the stuff of legend, painting the mountains in blazing oranges, reds, and golds.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/whitemountain",
    },
    {
      name: "Crawford Notch State Park",
      state: "New Hampshire",
      lat: 44.1480,
      lng: -71.3850,
      dogPolicy: "Leashed dogs welcome on all trails. A spectacular mountain notch with waterfalls, cliffs, and some of the best hiking in the White Mountains.",
      dogTrails: ["Arethusa Falls Trail", "Ripley Falls Trail", "Mount Willard Trail", "Ethan Pond Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed in swimming areas at designated beaches",
        "Owners must clean up after dogs",
      ],
      description:
        "This dramatic mountain pass 30 minutes from North Conway offers jaw-dropping scenery and incredible hiking. Your leashed pup can hike to New Hampshire's tallest waterfall (Arethusa Falls) or enjoy the famously rewarding Mount Willard hike with its spectacular notch views. Every White Mountain dog should hike here at least once.",
      imageUrl: "",
      website: "https://www.nhstateparks.org/visit/state-parks/crawford-notch-state-park",
    },
    {
      name: "Franconia Notch State Park",
      state: "New Hampshire",
      lat: 44.1411,
      lng: -71.6825,
      dogPolicy: "Leashed dogs welcome on most trails. Home to the Flume Gorge, a dramatic waterfall-filled chasm, and several outstanding mountain hikes.",
      dogTrails: ["Basin-Cascades Trail", "Lonesome Lake Trail", "Cannon Mountain trails", "Pemi Trail"],
      restrictions: [
        "Dogs not allowed in the Flume Gorge",
        "Must be on leash at all times",
        "Not allowed on Cannon Mountain aerial tramway",
      ],
      description:
        "About an hour from North Conway, Franconia Notch offers some of New Hampshire's most iconic scenery. While dogs cannot enter the Flume Gorge, the hike to Lonesome Lake is outstanding, and the Basin-Cascades Trail follows a beautiful stream. The notch is especially spectacular during fall foliage season.",
      imageUrl: "",
      website: "https://www.nhstateparks.org/visit/state-parks/franconia-notch-state-park",
    },
    {
      name: "Echo Lake State Park",
      state: "New Hampshire",
      lat: 44.0650,
      lng: -71.1550,
      dogPolicy: "Leashed dogs welcome on trails but not allowed on the beach during summer. The short hike to Cathedral Ledge offers incredible views.",
      dogTrails: ["Cathedral Ledge Trail", "White Horse Ledge Trail", "Echo Lake shoreline (off-season)"],
      restrictions: [
        "Dogs not allowed on beach (Memorial Day - Labor Day)",
        "Must be on leash at all times",
        "Year-round trail access",
      ],
      description:
        "Just minutes from North Conway, Echo Lake sits beneath the towering Cathedral Ledge cliff. Your leashed dog can hike to the top of the ledge for sweeping views of the valley and Mount Washington, and during the off-season, the lake itself is a beautiful spot for a shoreline walk.",
      imageUrl: "",
      website: "https://www.nhstateparks.org/visit/state-parks/echo-lake-state-park",
    },
  ],

  restaurants: [
    {
      name: "May Kelly's Cottage",
      address: "3002 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0580,
      lng: -71.1270,
      cuisine: "Irish Pub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio at this cozy Irish pub. Hearty comfort food and a pint of stout after a mountain summit with your best trail buddy.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.maykellys.com",
    },
    {
      name: "Flatbread Company",
      address: "2760 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0520,
      lng: -71.1250,
      cuisine: "Wood-Fired Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly outdoor seating area. Wood-fired flatbread pizzas made with local, organic ingredients that fill the air with irresistible aromas.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.flatbreadcompany.com",
    },
    {
      name: "Moat Mountain Smoke House & Brewing Co.",
      address: "3378 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0650,
      lng: -71.1300,
      cuisine: "Barbecue & Brewery",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio with mountain views. Smoked meats and house-brewed beers in a classic White Mountain setting.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.moatmountain.com",
    },
    {
      name: "Delaney's Hole in the Wall",
      address: "2966 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0560,
      lng: -71.1260,
      cuisine: "American Pub",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the deck. A beloved North Conway institution for burgers, nachos, and a cold one after conquering a 4,000-footer.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.delaneys.com",
    },
    {
      name: "Chef's Bistro",
      address: "2724 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0500,
      lng: -71.1240,
      cuisine: "French-American Bistro",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the garden patio. Fine dining with a relaxed mountain-town attitude and seasonal New England menus.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.chefsbistro.com",
    },
    {
      name: "Tuckerman's Restaurant & Tavern",
      address: "2260 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0425,
      lng: -71.1195,
      cuisine: "New England",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio seating. Classic New England fare including chowder, lobster rolls, and maple-glazed everything.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.tuckermansrestaurant.com",
    },
    {
      name: "Muddy Moose Restaurant & Pub",
      address: "2344 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0450,
      lng: -71.1210,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor deck. A family-friendly spot with generous portions that fuel up hikers and their trail dogs.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.muddymoose.com",
    },
    {
      name: "Local Grocer & Eatery",
      address: "3358 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0640,
      lng: -71.1295,
      cuisine: "Farm-to-Table Deli",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Fresh, locally sourced sandwiches, salads, and provisions for your next mountain adventure.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.localgrocerandeatery.com",
    },
  ],

  cafes: [
    {
      name: "White Mountain Cider Co.",
      address: "3542 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0700,
      lng: -71.1320,
      dogPolicy: "Dog-friendly patio at this beloved cafe and bakery. Fresh cider donuts in the fall that draw visitors from across New England.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.whitemtncider.com",
    },
    {
      name: "Frontside Coffee Roasters",
      address: "2708 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0495,
      lng: -71.1235,
      dogPolicy: "Locally roasted coffee with outdoor seating. The go-to morning spot before hitting the trails with your pup.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.frontsidecoffee.com",
    },
    {
      name: "Stairway Cafe",
      address: "2649 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0480,
      lng: -71.1230,
      dogPolicy: "Dog-friendly outdoor patio with a community feel. Breakfast and brunch favorites that fuel big mountain days.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.stairwaycafe.com",
    },
    {
      name: "Met Coffee House",
      address: "2680 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0488,
      lng: -71.1232,
      dogPolicy: "Cozy coffee house with sidewalk seating where dogs can join the Main Street scene. Espresso drinks and homemade pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.metcoffeehouse.com",
    },
    {
      name: "Black Cap Grind",
      address: "3000 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0575,
      lng: -71.1265,
      dogPolicy: "Mountain-inspired coffee shop with a patio where trail dogs are the majority clientele. Specialty espresso and homemade granola bars.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.blackcapgrind.com",
    },
  ],

  dogParks: [
    {
      name: "Schouler Park",
      address: "2800 White Mountain Hwy, North Conway, NH 03860",
      lat: 44.0535,
      lng: -71.1250,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["Village green", "Bandstand", "Benches", "Mountain views", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "The heart of North Conway village, this town green with its classic bandstand is the social hub where dog owners gather after a day on the trails. Leashed dogs enjoy the shaded grass and the steady stream of admirers. Mountain views in every direction.",
    },
    {
      name: "Diana's Baths",
      address: "Diana's Baths Rd, North Conway, NH 03860",
      lat: 44.0640,
      lng: -71.1670,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Waterfall pools", "Forest trail", "Swimming holes", "Parking (WMNF pass required)"],
      rating: 4.8,
      imageUrl: "",
      description:
        "A spectacular series of cascading waterfalls and natural swimming pools reached by an easy 1.2-mile forest trail. Leashed dogs love wading in the shallow pools and exploring the granite ledges. One of the most popular and beloved dog hikes in the Mount Washington Valley.",
    },
    {
      name: "Saco River Swimming Area",
      address: "River Rd, North Conway, NH 03860",
      lat: 44.0400,
      lng: -71.1300,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["River swimming", "Sandy banks", "Picnic area", "Shallow wading areas", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "The Saco River winds through the valley with sandy banks and gentle currents perfect for dog swimming. Leashed pups can wade in the shallows, fetch sticks from the sandy shores, and cool off after a hot summer hike. The mountain backdrop makes every river day feel special.",
    },
    {
      name: "Whitaker Woods Trail Network",
      address: "Whitaker Rd, North Conway, NH 03860",
      lat: 44.0600,
      lng: -71.1150,
      offLeash: false,
      fenced: false,
      acres: 75.0,
      amenities: ["Forest trails", "Cross-country skiing", "Mountain biking", "Quiet forest setting", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A network of groomed trails through forest right at the edge of North Conway village. Leashed dogs love the gentle, well-maintained paths through birch and pine forest. In winter it becomes a cross-country ski area, and in summer it is a cool, shaded escape for dogs who prefer forest to summit.",
    },
    {
      name: "North Conway Community Dog Park",
      address: "Norcross Pl, North Conway, NH 03860",
      lat: 44.0550,
      lng: -71.1220,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Separate small dog section", "Water fountain", "Benches", "Waste stations", "Shade"],
      rating: 4.3,
      imageUrl: "",
      description:
        "North Conway's fenced off-leash park gives tired trail dogs a place to socialize and burn off any remaining energy. Separate areas for large and small dogs, with mountain views peeking through the trees. The community here is warm and welcoming, just like the rest of the valley.",
    },
  ],
};
