export const northamptonData = {
  city: {
    name: "Northampton",
    state: "Massachusetts",
    region: "Northeast",
    lat: 42.3251,
    lng: -72.6412,
    dogFriendlinessScore: 8,
    description:
      "This progressive Pioneer Valley college town is a dog lover's utopia with its vibrant Main Street, rail trail network, and surrounding farmland. Northampton's culture of inclusivity extends to four-legged friends, and you'll see dogs at breweries, on patios, and on the extensive bike path system.",
    heroImage: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 29571,
  },
  hotels: [
    {
      name: "Hotel Northampton",
      address: "36 King St, Northampton, MA 01060",
      lat: 42.3199,
      lng: -72.6319,
      priceRange: "$$$" as const,
      dogPolicy: "Historic downtown hotel welcoming dogs with a $50 per stay fee. Walking distance to Main Street shops and restaurants.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Downtown location", "Historic charm", "Restaurant", "Rooftop bar", "Main Street access"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hotelnorthampton.com",
      phone: "(413) 584-3100",
    },
    {
      name: "The Ellery Hotel",
      address: "260 Elm St, Northampton, MA 01060",
      lat: 42.3227,
      lng: -72.6384,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms with a $30 per night fee. Near downtown and the Northampton Bike Path.",
      maxDogWeight: 75,
      petFee: 30,
      amenities: ["Near bike path", "Free parking", "Walking distance to downtown", "Pet exercise area"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.theelleryhotel.com",
      phone: "(413) 584-7660",
    },
    {
      name: "Fairfield Inn & Suites Northampton",
      address: "76 Conz St, Northampton, MA 01060",
      lat: 42.3175,
      lng: -72.6406,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a $75 non-refundable fee. Near the rail trail and downtown walking distance.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Free breakfast", "Near rail trail", "Indoor pool", "Pet relief area"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(413) 587-9800",
    },
    {
      name: "Autumn Inn",
      address: "259 Elm St, Northampton, MA 01060",
      lat: 42.323,
      lng: -72.638,
      priceRange: "$$" as const,
      dogPolicy: "Budget-friendly pet rooms with a $20 per night fee. Walking distance to Smith College and downtown.",
      maxDogWeight: 60,
      petFee: 20,
      amenities: ["Near Smith College", "Free parking", "Garden area", "Downtown walking distance"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.hampshirehospitality.com",
      phone: "(413) 584-7660",
    },
  ],
  nationalParks: [
    {
      name: "Arcadia Wildlife Sanctuary",
      state: "Massachusetts",
      lat: 42.3366,
      lng: -72.6611,
      dogPolicy: "Leashed dogs welcome on the trail system. Over 700 acres of Connecticut River floodplain forest and meadow.",
      dogTrails: ["Fern Trail", "Old Coach Road", "Meadow Trail", "Connecticut River Trail"],
      restrictions: ["Leash required at all times", "Stay on marked trails", "Clean up required"],
      description:
        "A Mass Audubon sanctuary along the Connecticut River with a beautiful mix of floodplain forest, meadows, and marsh. The flat trails are easy for any dog, and the rich riparian habitat provides amazing wildlife viewing. The ancient oxbow marsh is particularly scenic and your dog will love the earthy river smells.",
      imageUrl: "",
      website: "https://www.massaudubon.org/arcadia",
    },
    {
      name: "Mount Tom State Reservation",
      state: "Massachusetts",
      lat: 42.2615,
      lng: -72.6316,
      dogPolicy: "Leashed dogs welcome on all trails. Dramatic ridgeline hikes with Connecticut River valley views.",
      dogTrails: ["Metacomet-Monadnock Trail", "Bray Loop", "Lake Bray Trail", "DOC Trail"],
      restrictions: ["Leash required", "Rocky terrain on ridgeline", "No dogs in Bray Lake swimming area"],
      description:
        "A volcanic traprock ridge rising dramatically above the Connecticut River valley with miles of trails along exposed ridgeline offering panoramic views. The Metacomet-Monadnock Trail traverses the summit ridge with views stretching to the Berkshire Hills. Rocky and rugged, it's perfect for athletic dogs.",
      imageUrl: "",
      website: "https://www.mass.gov/locations/mount-tom-state-reservation",
    },
    {
      name: "Fitzgerald Lake Conservation Area",
      state: "Massachusetts",
      lat: 42.3521,
      lng: -72.6898,
      dogPolicy: "Dogs welcome on all trails. A hidden gem with a beautiful lake and diverse habitats.",
      dogTrails: ["Boggy Meadow Trail", "North Trail", "Cooke's Pasture Trail", "Lake Loop Trail"],
      restrictions: ["Leash required on weekends", "Off-leash under voice control on weekdays", "Clean up required"],
      description:
        "A 600-acre conservation area centered around a scenic lake, with trails winding through diverse habitats including meadows, wetlands, and upland forest. The weekday off-leash policy makes this a favorite for Northampton dog owners. The lake views and peaceful setting provide a wonderful escape from town.",
      imageUrl: "",
      website: "https://www.northamptonma.gov",
    },
  ],
  restaurants: [
    {
      name: "Northampton Brewery",
      address: "11 Brewster Ct, Northampton, MA 01060",
      lat: 42.3192,
      lng: -72.6306,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Pioneer Valley's oldest brewpub with a large rooftop deck. Dogs welcome on the outdoor deck overlooking downtown.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.northamptonbrewery.com",
    },
    {
      name: "Green Bean",
      address: "241 Main St, Northampton, MA 01060",
      lat: 42.3202,
      lng: -72.6339,
      cuisine: "Vegetarian",
      priceRange: "$" as const,
      dogPolicy: "Plant-based restaurant with outdoor seating. Dogs welcome on the sidewalk patio on Main Street.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Eastside Grill",
      address: "19 Strong Ave, Northampton, MA 01060",
      lat: 42.3191,
      lng: -72.6273,
      cuisine: "Cajun",
      priceRange: "$$" as const,
      dogPolicy: "Cajun-Creole restaurant with a charming patio. Leashed dogs welcome outside. Famous for their jambalaya.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.eastsidegrill.com",
    },
    {
      name: "Progression Brewing Company",
      address: "7 Armory St, Northampton, MA 01060",
      lat: 42.3199,
      lng: -72.629,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly nano-brewery with an outdoor seating area. Creative small-batch beers in a welcoming space.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.progressionbrewing.com",
    },
    {
      name: "Spoleto",
      address: "50 Main St, Northampton, MA 01060",
      lat: 42.3193,
      lng: -72.6286,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Upscale Italian with sidewalk dining on Main Street. Leashed dogs welcome at outdoor tables.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.spoletomainst.com",
    },
  ],
  cafes: [
    {
      name: "Woodstar Cafe",
      address: "60 Masonic St, Northampton, MA 01060",
      lat: 42.3209,
      lng: -72.634,
      dogPolicy: "Beloved neighborhood cafe with a garden patio. Dogs welcome outside. Famous for their scones and baked goods.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "",
    },
    {
      name: "Shelburne Falls Coffee Roasters",
      address: "170 Main St, Northampton, MA 01060",
      lat: 42.3198,
      lng: -72.6317,
      dogPolicy: "Quality roaster with outdoor seating on Main Street. Dogs welcome at sidewalk tables.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.sfcoffeeroasters.com",
    },
    {
      name: "Iconica Social Club",
      address: "20 Crafts Ave, Northampton, MA 01060",
      lat: 42.3174,
      lng: -72.633,
      dogPolicy: "Community-focused cafe with a spacious outdoor patio near the rail trail. Dogs are welcome and encouraged.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "The Roost",
      address: "1 Market St, Northampton, MA 01060",
      lat: 42.3195,
      lng: -72.6302,
      dogPolicy: "Cozy downtown coffee shop with outdoor benches. A quick caffeine stop while strolling Main Street with your pup.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Northampton Dog Park (Bark Park)",
      address: "Old Ferry Rd, Northampton, MA 01060",
      lat: 42.337,
      lng: -72.6461,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fully fenced", "Separate small dog area", "Water station", "Benches", "Shade trees"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Northampton's dedicated off-leash dog park is a community favorite with separate areas for large and small dogs. The well-maintained space is frequented by a friendly group of regulars, and the location near the Connecticut River allows for a riverside walk before or after playtime.",
    },
    {
      name: "Northampton Bike Path (Mass Central Rail Trail)",
      address: "State St, Northampton, MA 01060",
      lat: 42.3205,
      lng: -72.6394,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Paved trail", "Scenic views", "Multiple access points", "Benches", "Connects to Amherst"],
      rating: 4.6,
      imageUrl: "",
      description:
        "An 11-mile paved rail trail connecting Northampton to Amherst through farmland, forest, and Connecticut River valley scenery. The flat, wide path is perfect for leashed dog walks and jogs. Multiple access points and trailside amenities make it easy to customize your adventure.",
    },
    {
      name: "Look Memorial Park",
      address: "300 N Main St, Florence, MA 01062",
      lat: 42.3449,
      lng: -72.6625,
      offLeash: false,
      fenced: false,
      acres: 157.0,
      amenities: ["Paved paths", "Gardens", "Duck pond", "Picnic areas", "Playground"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A beautiful 157-acre park in Florence with paved walking paths, gardens, a duck pond, and wooded areas. Leashed dogs are welcome throughout the grounds, which offer a mix of manicured gardens and natural areas. The park is especially beautiful in autumn when the maples turn brilliant colors.",
    },
    {
      name: "Mineral Hills Conservation Area",
      address: "Rocky Hill Rd, Northampton, MA 01060",
      lat: 42.3088,
      lng: -72.6471,
      offLeash: false,
      fenced: false,
      acres: 45.0,
      amenities: ["Forest trails", "Rocky outcrops", "Views", "Quiet setting", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A lesser-known conservation area with trails through oak-hickory forest and over rocky ridgeline with views of the Connecticut River valley. The rugged terrain provides a satisfying hike for athletic dogs, and the quiet trails mean you'll likely have the woods to yourselves.",
    },
  ],
};
