export const olympiaData = {
  city: {
    name: "Olympia",
    state: "Washington",
    region: "Pacific Northwest",
    lat: 47.0379,
    lng: -122.9007,
    dogFriendlinessScore: 8,
    description:
      "Washington's capital city sits at the southern tip of Puget Sound with a progressive, dog-loving culture that rivals Portland. With waterfront trails, forested parks, a vibrant farmers market, and a downtown packed with dog-friendly breweries and cafes, Olympia is a Pacific Northwest gem for dog owners.",
    heroImage: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=1200&fit=crop",
    climate: "Oceanic",
    population: 55605,
  },
  hotels: [
    {
      name: "Hotel RL Olympia by Red Lion",
      address: "2300 Evergreen Park Dr SW, Olympia, WA 98502",
      lat: 47.0280,
      lng: -122.9100,
      priceRange: "$$" as const,
      dogPolicy: "Waterfront hotel on Capitol Lake welcoming dogs of all sizes. Walking trails along the lake and easy downtown access.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Lakefront location", "Walking trails", "Dog bed", "Water bowls", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.redlion.com",
      phone: "(360) 943-4000",
    },
    {
      name: "DoubleTree by Hilton Olympia",
      address: "415 Capitol Way N, Olympia, WA 98501",
      lat: 47.0440,
      lng: -122.9020,
      priceRange: "$$$" as const,
      dogPolicy: "Downtown hotel with pet-friendly rooms near the Capitol campus. Dogs under 75 lbs welcome with walking distance to waterfront.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Downtown location", "Dog bed", "Water bowls", "Capitol campus proximity", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(360) 570-0555",
    },
    {
      name: "Swantown Inn & Spa",
      address: "1431 11th Ave SE, Olympia, WA 98501",
      lat: 47.0350,
      lng: -122.8900,
      priceRange: "$$$" as const,
      dogPolicy: "Victorian B&B with select pet-friendly rooms. Small dogs welcome with advance notice in a charming residential neighborhood.",
      maxDogWeight: 30,
      petFee: 35,
      amenities: ["Victorian charm", "Garden", "Breakfast included", "Water bowls", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.swantowninn.com",
      phone: "(360) 753-9123",
    },
    {
      name: "GuestHouse Inn Olympia",
      address: "1600 74th Ave SW, Tumwater, WA 98501",
      lat: 47.0100,
      lng: -122.9300,
      priceRange: "$" as const,
      dogPolicy: "Budget-friendly option south of Olympia welcoming dogs of all sizes. Easy access to Tumwater Falls and Olympia attractions.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Pet-friendly rooms", "Parking", "Near Tumwater Falls", "Waste bags", "Water bowls"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.guesthouseintl.com",
      phone: "(360) 943-5040",
    },
  ],
  nationalParks: [
    {
      name: "Olympic National Forest",
      state: "Washington",
      lat: 47.5000,
      lng: -123.5000,
      dogPolicy: "Dogs welcome on national forest trails on leash. Note: dogs are NOT allowed on trails within Olympic National Park, but the surrounding national forest is dog-friendly.",
      dogTrails: ["Lena Lake Trail", "Mount Ellinor Trail", "Wynoochee Lake Shore Trail", "Staircase Rapids Loop (national forest portion)"],
      restrictions: ["Leash required", "Not allowed in Olympic National Park", "Carry extra water", "Weather can change rapidly"],
      description: "The Olympic National Forest surrounding Olympic National Park offers dog-friendly alternatives for exploring the Olympic Peninsula. Mountain lakes, old-growth forest, and alpine meadows are accessible on forest trails where dogs are welcome.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/olympic",
    },
    {
      name: "Capitol State Forest",
      state: "Washington",
      lat: 46.9500,
      lng: -123.1000,
      dogPolicy: "Dogs welcome on all trails on leash or under voice control. A vast working forest with extensive trail networks west of Olympia.",
      dogTrails: ["Capitol Peak Trail", "Rock Candy Mountain Trail", "McLane Creek Nature Trail", "Larch Mountain Trail"],
      restrictions: ["Leash or voice control required", "Watch for logging trucks on forest roads", "Hunting season requires caution", "Muddy trails in wet season"],
      description: "This 90,000-acre state forest west of Olympia offers miles of dog-friendly trails through second-growth forests, mountain ridges, and creek valleys. The McLane Creek Nature Trail is especially popular for salmon viewing in fall.",
      imageUrl: "",
      website: "https://www.dnr.wa.gov",
    },
    {
      name: "Nisqually National Wildlife Refuge",
      state: "Washington",
      lat: 47.0700,
      lng: -122.7200,
      dogPolicy: "Dogs allowed on the Nisqually Estuary Boardwalk Trail on leash only. A unique wetland ecosystem at the delta of the Nisqually River.",
      dogTrails: ["Twin Barns Loop Trail", "Nisqually Estuary Boardwalk"],
      restrictions: ["6-foot leash required", "Stay on boardwalks and trails", "Do not disturb wildlife", "Small entrance fee"],
      description: "Where the Nisqually River meets Puget Sound, this refuge offers miles of boardwalk trails through restored estuary habitat. Dogs on leash can explore while spotting bald eagles, herons, and seasonal migratory birds.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/nisqually",
    },
  ],
  restaurants: [
    {
      name: "Olympia Oyster House",
      address: "320 4th Ave W, Olympia, WA 98501",
      lat: 47.0460,
      lng: -122.9060,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Waterfront seafood restaurant with a patio overlooking Budd Inlet. Dogs welcome on the patio with fresh Olympia oysters and Pacific seafood.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.olympiaoysterhouse.com",
    },
    {
      name: "The Mark",
      address: "407 Legion Way SE, Olympia, WA 98501",
      lat: 47.0420,
      lng: -122.8980,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Downtown restaurant with a covered patio welcoming dogs. Seasonal Pacific Northwest cuisine with craft cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.themark-olympia.com",
    },
    {
      name: "Bread Peddler",
      address: "222 Capitol Way N, Olympia, WA 98501",
      lat: 47.0430,
      lng: -122.9010,
      cuisine: "Bakery & Café",
      priceRange: "$" as const,
      dogPolicy: "Artisan bakery with outdoor seating where dogs are welcome. Fresh bread, pastries, and sandwiches near the Capitol.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.breadpeddler.com",
    },
    {
      name: "Iron Rabbit Restaurant & Bar",
      address: "202 4th Ave W, Olympia, WA 98501",
      lat: 47.0455,
      lng: -122.9050,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Downtown restaurant with a dog-friendly patio. Comfort food and craft beers in a cozy Pacific Northwest atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.ironrabbitbar.com",
    },
    {
      name: "Nirvana Restaurant",
      address: "116 4th Ave E, Olympia, WA 98501",
      lat: 47.0445,
      lng: -122.8970,
      cuisine: "Indian-Nepali",
      priceRange: "$$" as const,
      dogPolicy: "Indian and Nepali cuisine with outdoor seating where dogs are welcome. Flavorful curries and naan in downtown Olympia.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.nirvanaoly.com",
    },
  ],
  cafes: [
    {
      name: "Olympia Coffee Roasting Co.",
      address: "600 4th Ave E, Olympia, WA 98501",
      lat: 47.0445,
      lng: -122.8950,
      dogPolicy: "Award-winning local roaster with a patio where dogs are welcome. Direct-trade specialty coffee from a true Olympia institution.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.olympiacoffee.com",
    },
    {
      name: "Burial Grounds Coffee",
      address: "403 Legion Way SE, Olympia, WA 98501",
      lat: 47.0418,
      lng: -122.8982,
      dogPolicy: "Cozy downtown coffee shop with outdoor seating and a dog-friendly attitude. Locally roasted coffee and baked goods.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.burialgroundscoffee.com",
    },
    {
      name: "Batdorf & Bronson Coffee Roasters",
      address: "516 S Capitol Way, Olympia, WA 98501",
      lat: 47.0380,
      lng: -122.9010,
      dogPolicy: "Pacific Northwest roasting pioneer with a tasting room and outdoor seating. Dogs welcome on the patio at this Olympia landmark.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.batdorf.com",
    },
    {
      name: "Orca Books & Coffee",
      address: "509 4th Ave E, Olympia, WA 98501",
      lat: 47.0443,
      lng: -122.8960,
      dogPolicy: "Independent bookstore café with a small patio where dogs are welcome. Browse books while sipping coffee with your pup.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.orcabooks.com",
    },
  ],
  dogParks: [
    {
      name: "Olympia Dog Park (Priest Point)",
      address: "2600 East Bay Dr NE, Olympia, WA 98506",
      lat: 47.0600,
      lng: -122.8800,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Shade trees", "Benches", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "Olympia's main off-leash dog park near Priest Point Park with separate areas for large and small dogs. The forested setting provides natural shade and a Pacific Northwest atmosphere.",
    },
    {
      name: "Priest Point Park",
      address: "2600 East Bay Dr NE, Olympia, WA 98506",
      lat: 47.0580,
      lng: -122.8820,
      offLeash: false,
      fenced: false,
      acres: 314,
      amenities: ["Hiking trails", "Old-growth forest", "Waterfront access", "Picnic areas", "Restrooms"],
      rating: 4.6,
      imageUrl: "",
      description: "A stunning 314-acre park with trails through old-growth forest to the Puget Sound shoreline. Leashed dogs enjoy the towering trees, fern-carpeted forest floor, and waterfront views at the end of the trail.",
    },
    {
      name: "Watershed Park",
      address: "2500 Henderson Blvd SE, Olympia, WA 98501",
      lat: 47.0200,
      lng: -122.8900,
      offLeash: false,
      fenced: false,
      acres: 153,
      amenities: ["Forested trails", "Creek", "Boardwalks", "Old-growth trees", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "A forested park with trails winding through ancient trees and along Moxlie Creek. Leashed dogs enjoy the boardwalk sections and the peaceful old-growth forest atmosphere.",
    },
    {
      name: "Tumwater Falls Park",
      address: "110 Deschutes Way SW, Tumwater, WA 98501",
      lat: 47.0100,
      lng: -122.9050,
      offLeash: false,
      fenced: false,
      acres: 15,
      amenities: ["Waterfall views", "Paved trails", "Salmon viewing", "Picnic areas", "Restrooms"],
      rating: 4.5,
      imageUrl: "",
      description: "A beautiful park along the Deschutes River with multiple waterfalls and salmon viewing platforms. Leashed dogs enjoy the paved trails along the river and the dramatic cascade scenery.",
    },
  ],
};
