export const omahaData = {
  city: {
    name: "Omaha",
    state: "Nebraska",
    region: "Midwest",
    lat: 41.2565,
    lng: -95.9345,
    dogFriendlinessScore: 7,
    description:
      "Omaha surprises visitors with its extensive off-leash dog park system and a thriving food scene that warmly welcomes four-legged friends. With miles of riverfront trails along the Missouri River and a growing number of pet-friendly patios, this Midwestern gem is a hidden treasure for dog owners.",
    heroImage: "https://images.unsplash.com/photo-1574786577068-92e7dabbc73e?w=1200&fit=crop",
    climate: "Humid continental",
    population: 486051,
  },

  hotels: [
    {
      name: "Kimpton Cottonwood Hotel",
      address: "302 S 36th St, Omaha, NE 68131",
      lat: 41.2558,
      lng: -95.9607,
      priceRange: "$$$" as const,
      dogPolicy: "All Kimpton hotels welcome dogs of any size at no extra fee. Treats and beds available at check-in.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking route maps", "Midtown location"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.ihg.com/kimpton",
      phone: "(402) 810-7600",
    },
    {
      name: "Hotel Deco",
      address: "1504 Harney St, Omaha, NE 68102",
      lat: 41.2583,
      lng: -95.9357,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 80 lbs welcome with a one-time pet fee. Art Deco elegance in the heart of downtown.",
      maxDogWeight: 80,
      petFee: 50,
      amenities: ["Dog bed", "Food and water bowls", "Treats", "Walking maps", "Near Gene Leahy Mall"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hoteldeco.com",
      phone: "(402) 991-4981",
    },
    {
      name: "Magnolia Hotel Omaha",
      address: "1615 Howard St, Omaha, NE 68102",
      lat: 41.2567,
      lng: -95.9340,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a nightly fee. Located steps from the Old Market district.",
      maxDogWeight: 75,
      petFee: 40,
      amenities: ["Pet bed", "Water bowls", "Evening wine reception", "Old Market access"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.magnoliahotels.com",
      phone: "(402) 341-2500",
    },
    {
      name: "Embassy Suites Downtown Old Market",
      address: "555 S 10th St, Omaha, NE 68102",
      lat: 41.2537,
      lng: -95.9314,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a non-refundable pet fee. Spacious suites with room to roam.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Suite layout", "Grassy walking area", "Near riverfront trail", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(402) 346-9000",
    },
  ],

  nationalParks: [
    {
      name: "Fontenelle Forest",
      state: "Nebraska",
      lat: 41.1753,
      lng: -95.9019,
      dogPolicy: "Leashed dogs allowed on designated trails including the Riverview Boardwalk and select woodland paths.",
      dogTrails: ["Riverview Boardwalk", "Stream Trail", "Oak Trail"],
      restrictions: [
        "Dogs must be on a 6-foot leash at all times",
        "Not permitted in the raptor recovery area",
        "Must stay on designated dog-friendly trails",
      ],
      description:
        "This 2,000-acre forest preserve along the Missouri River bluffs offers a rare urban wilderness experience. Ancient oak-hickory forests, wetlands, and stunning river views make it a wonderful escape just south of Omaha.",
      imageUrl: "",
      website: "https://www.fontenelleforest.org",
    },
    {
      name: "Indian Cave State Park",
      state: "Nebraska",
      lat: 40.2595,
      lng: -95.5577,
      dogPolicy: "Leashed dogs welcome on all trails and in campgrounds. Over 20 miles of hiking trails through wooded bluffs.",
      dogTrails: ["Hardwood Trail", "St. Deroin Trail", "River Bluff Trail", "Cave Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed inside the historic cave area",
        "Must clean up after your pet",
      ],
      description:
        "Set along the Missouri River about 90 minutes south of Omaha, this state park features ancient petroglyphs, dense forests, and over 3,000 acres of rolling bluffs. Dogs love the varied terrain and riverside trails.",
      imageUrl: "",
      website: "https://outdoornebraska.gov/indiancave",
    },
    {
      name: "Platte River State Park",
      state: "Nebraska",
      lat: 41.0120,
      lng: -96.2240,
      dogPolicy: "Leashed dogs allowed on trails, in cabins, and campgrounds. A scenic retreat between Omaha and Lincoln.",
      dogTrails: ["Iron Horse Trail", "Bluffs Trail", "Nature Center Trail"],
      restrictions: [
        "Must be on leash no longer than 6 feet",
        "Not allowed in the waterfall pool area",
        "Pet fee applies for cabin stays",
      ],
      description:
        "Nestled between the Platte River bluffs, this park offers wooded trails, scenic overlooks, and a beautiful waterfall. The park's cabin accommodations make it a perfect dog-friendly weekend getaway from Omaha.",
      imageUrl: "",
      website: "https://outdoornebraska.gov/platteriver",
    },
  ],

  restaurants: [
    {
      name: "Block 16",
      address: "1611 Farnam St, Omaha, NE 68102",
      lat: 41.2581,
      lng: -95.9338,
      cuisine: "Creative American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at the outdoor sidewalk tables. Known for inventive burgers and sandwiches.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.block16omaha.com",
    },
    {
      name: "Crescent Moon Alehouse",
      address: "3578 Farnam St, Omaha, NE 68131",
      lat: 41.2576,
      lng: -95.9614,
      cuisine: "Pub Fare",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the large outdoor patio and beer garden. Legendary Reuben sandwiches.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.beercorneromaha.com",
    },
    {
      name: "Dante Ristorante Pizzeria",
      address: "16901 Wright Plz, Omaha, NE 68130",
      lat: 41.2420,
      lng: -96.0910,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the covered patio. Wood-fired pizzas and handmade pasta.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.danteomaha.com",
    },
    {
      name: "Nite Owl",
      address: "3823 N 24th St, Omaha, NE 68110",
      lat: 41.2812,
      lng: -95.9480,
      cuisine: "American Brunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the patio. Beloved neighborhood brunch spot with creative dishes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.niteowlomaha.com",
    },
    {
      name: "Upstream Brewing Company",
      address: "514 S 11th St, Omaha, NE 68102",
      lat: 41.2540,
      lng: -95.9305,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the spacious Old Market patio. Craft beers and elevated pub food.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.upstreambrewing.com",
    },
  ],

  cafes: [
    {
      name: "Hardy Coffee Co.",
      address: "1319 Farnam St, Omaha, NE 68102",
      lat: 41.2580,
      lng: -95.9370,
      dogPolicy: "Dog-friendly outdoor seating with water bowls. Specialty coffee and pastries in the Old Market area.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hardycoffee.com",
    },
    {
      name: "Archetype Coffee",
      address: "3926 Farnam St, Omaha, NE 68131",
      lat: 41.2574,
      lng: -95.9650,
      dogPolicy: "Leashed dogs welcome on the outdoor patio. Third-wave coffee roasters with a loyal following.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.archetypecoffee.com",
    },
    {
      name: "Muglife Coffee",
      address: "1309 S 6th St, Omaha, NE 68108",
      lat: 41.2470,
      lng: -95.9280,
      dogPolicy: "Patio seating welcomes dogs. A cozy neighborhood spot with quality drinks.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.muglifecoffee.com",
    },
    {
      name: "Beansmith Coffee",
      address: "7013 Cass St, Omaha, NE 68132",
      lat: 41.2620,
      lng: -95.9900,
      dogPolicy: "Dog-friendly patio with a relaxed vibe. Fresh-roasted coffee and light bites.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.beansmithcoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Hefflinger Dog Park",
      address: "2614 Leavenworth St, Omaha, NE 68105",
      lat: 41.2494,
      lng: -95.9500,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: ["Separate small dog area", "Water fountains", "Shade shelters", "Waste stations", "Benches"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Omaha's most popular dog park features separate areas for large and small dogs, plenty of shade, and well-maintained grounds. The central location makes it a favorite for after-work visits.",
    },
    {
      name: "Benson Dog Park",
      address: "7002 Military Ave, Omaha, NE 68104",
      lat: 41.2870,
      lng: -95.9780,
      offLeash: true,
      fenced: true,
      acres: 3.5,
      amenities: ["Double-gated entry", "Water spigots", "Benches", "Waste bags", "Gravel paths"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Located in the eclectic Benson neighborhood, this well-fenced park offers ample room for dogs to run. The friendly community of regulars makes both dogs and owners feel welcome.",
    },
    {
      name: "Hanscom Dog Park",
      address: "3201 Woolworth Ave, Omaha, NE 68105",
      lat: 41.2440,
      lng: -95.9550,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Shade trees", "Water fountain", "Waste stations", "Benches", "Adjacent walking paths"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A charming dog park within the historic Hanscom Park, offering a shaded off-leash area surrounded by mature trees. The adjacent park trails provide nice on-leash walking options too.",
    },
    {
      name: "Chalco Hills Dog Park",
      address: "8901 S 154th St, Omaha, NE 68138",
      lat: 41.1910,
      lng: -96.1110,
      offLeash: true,
      fenced: true,
      acres: 8.0,
      amenities: ["Large open fields", "Water access", "Nature trails nearby", "Parking lot", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Omaha's largest dog park sits within the Chalco Hills Recreation Area, offering expansive fields and proximity to nature trails. Dogs love the wide-open space and the natural surroundings.",
    },
  ],
};
