export const orlandoData = {
  city: {
    name: "Orlando",
    state: "Florida",
    region: "Southeast",
    lat: 28.5383,
    lng: -81.3792,
    dogFriendlinessScore: 6,
    description:
      "Beyond the theme parks, Orlando has a thriving local scene with dog-friendly breweries, lakeside parks, and nature trails through cypress swamps. The year-round warm weather means outdoor patios are always open, and the chain of lakes offers miles of waterfront walking paths.",
    heroImage: "https://images.unsplash.com/photo-1575089776834-8be34c2bfc68?w=1200&fit=crop",
    climate: "Tropical Savanna",
    population: 307573,
  },
  hotels: [
    {
      name: "The Alfond Inn",
      address: "300 E New England Ave, Winter Park, FL 32789",
      lat: 28.5949,
      lng: -81.3485,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique hotel in charming Winter Park welcoming dogs under 40 lbs with a $75 per stay fee. Walking distance to Park Avenue shops.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Park Avenue location", "Art collection", "Pool", "Restaurant", "Near Central Park"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thealfondinn.com",
      phone: "(407) 998-8090",
    },
    {
      name: "Drury Inn & Suites Orlando near Universal",
      address: "7301 W Sand Lake Rd, Orlando, FL 32819",
      lat: 28.4498,
      lng: -81.4598,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a $50 non-refundable fee. Free hot breakfast and evening reception.",
      maxDogWeight: 80,
      petFee: 50,
      amenities: ["Free breakfast", "Evening reception", "Pool", "Pet relief area", "Near attractions"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.druryhotels.com",
      phone: "(407) 354-1101",
    },
    {
      name: "Aloft Orlando Downtown",
      address: "500 S Orange Ave, Orlando, FL 32801",
      lat: 28.5357,
      lng: -81.3798,
      priceRange: "$$" as const,
      dogPolicy: "Arf program welcomes dogs of any size at no extra charge. Downtown location near Lake Eola.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Downtown location", "Near Lake Eola", "Pool", "Pet treats"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(407) 380-3500",
    },
    {
      name: "The Delaney Hotel",
      address: "424 E Central Blvd, Orlando, FL 32801",
      lat: 28.5408,
      lng: -81.3735,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique downtown hotel welcoming dogs with a $50 per stay fee. Walking distance to Thornton Park and Lake Eola.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Downtown location", "Near Thornton Park", "Lake Eola walking distance", "Pool"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thedelaneyhotel.com",
      phone: "(407) 841-4000",
    },
  ],
  nationalParks: [
    {
      name: "Wekiwa Springs State Park",
      state: "Florida",
      lat: 28.7144,
      lng: -81.4603,
      dogPolicy: "Leashed dogs welcome on all trails and in the campground. A crystal-clear Florida spring with surrounding forest.",
      dogTrails: ["Sand Lake Trail", "Rock Springs Run Trail", "Nature Trail", "Multi-Use Trail"],
      restrictions: ["Leash required", "No dogs in spring swimming area", "No dogs in canoes", "Clean up required"],
      description:
        "A 7,800-acre park centered around a crystal-clear first-magnitude spring pumping millions of gallons daily. While dogs can't swim in the springs, the miles of trails through sand pine scrub, hardwood hammock, and along the spring run are excellent for hiking. The forest is home to bears, deer, and gopher tortoises.",
      imageUrl: "",
      website: "https://www.floridastateparks.org/parks-and-trails/wekiwa-springs-state-park",
    },
    {
      name: "Tibet-Butler Nature Preserve",
      state: "Florida",
      lat: 28.4762,
      lng: -81.5186,
      dogPolicy: "Leashed dogs welcome on the main trails. A diverse preserve with pine flatwoods, wetlands, and lake shores.",
      dogTrails: ["Palmetto Trail", "Pine Circle Trail", "Lake Trail"],
      restrictions: ["Leash required at all times", "Stay on boardwalks over wetlands", "Clean up required"],
      description:
        "A 440-acre nature preserve protecting longleaf pine flatwoods, cypress swamps, and lakefront habitats. The well-maintained trails and boardwalks wind through diverse Florida ecosystems. Your leashed dog will encounter an incredible variety of birds, butterflies, and the occasional gopher tortoise.",
      imageUrl: "",
      website: "https://www.orangecountyfl.net",
    },
    {
      name: "Shingle Creek Regional Trail",
      state: "Florida",
      lat: 28.4241,
      lng: -81.4117,
      dogPolicy: "Leashed dogs welcome on the paved multi-use trail. Follows the headwaters of the Everglades.",
      dogTrails: ["Shingle Creek Trail (paved)", "Nature Loop", "Creek Overlook Trail"],
      restrictions: ["Leash required", "Yield to cyclists", "Be alert for wildlife"],
      description:
        "A paved trail following Shingle Creek, considered the headwaters of the Florida Everglades. The trail passes through cypress swamps, pine flatwoods, and along the creek where herons, ibis, and the occasional alligator can be spotted. A surprisingly wild experience near the tourist corridor.",
      imageUrl: "",
      website: "https://www.orangecountyfl.net",
    },
  ],
  restaurants: [
    {
      name: "East End Market",
      address: "3201 Corrine Dr, Orlando, FL 32803",
      lat: 28.5634,
      lng: -81.3508,
      cuisine: "Food Hall",
      priceRange: "$$" as const,
      dogPolicy: "Artisan food hall with a dog-friendly courtyard. Multiple local food vendors and a community gathering space.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.eastendmkt.com",
    },
    {
      name: "Sideward Brewing Co.",
      address: "210 N Bumby Ave, Orlando, FL 32803",
      lat: 28.5497,
      lng: -81.3541,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly brewery in the Milk District. Large outdoor area welcomes pups. Creative craft beers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sidewardbrewing.com",
    },
    {
      name: "The Ravenous Pig",
      address: "565 W Fairbanks Ave, Winter Park, FL 32789",
      lat: 28.5924,
      lng: -81.3592,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Award-winning gastropub with a dog-friendly patio and in-house brewery. Farm-to-table cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.theravenouspig.com",
    },
    {
      name: "Se7en Bites",
      address: "617 N Primrose Dr, Orlando, FL 32803",
      lat: 28.5533,
      lng: -81.3527,
      cuisine: "Southern",
      priceRange: "$$" as const,
      dogPolicy: "Southern comfort food bakery with outdoor picnic tables. Dogs welcome in the outdoor seating area.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.se7enbites.com",
    },
    {
      name: "Prato",
      address: "124 N Park Ave, Winter Park, FL 32789",
      lat: 28.5954,
      lng: -81.3497,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Park Avenue Italian restaurant with a dog-friendly sidewalk patio. Wood-fired pizza and house-made pasta.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.prato-wp.com",
    },
  ],
  cafes: [
    {
      name: "Foxtail Coffee Co.",
      address: "1282 N Orange Ave, Orlando, FL 32804",
      lat: 28.562,
      lng: -81.3738,
      dogPolicy: "Orlando's favorite local coffee chain with a dog-friendly patio. Quality espresso in a bright, welcoming space.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.foxtailcoffee.com",
    },
    {
      name: "Lineage Coffee Roasting",
      address: "766 N Mills Ave, Orlando, FL 32803",
      lat: 28.5527,
      lng: -81.3649,
      dogPolicy: "Mills 50 coffee roaster with outdoor seating. Dogs welcome at patio tables. Single-origin pour-overs and espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.lineageroasting.com",
    },
    {
      name: "Barnie's Coffee & Tea Company",
      address: "118 S Park Ave, Winter Park, FL 32789",
      lat: 28.5943,
      lng: -81.3495,
      dogPolicy: "Winter Park institution with a shaded patio on Park Avenue. Dogs welcome. Known for their Santa's White Christmas coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.barniescoffee.com",
    },
    {
      name: "CFS Coffee",
      address: "947 N Mills Ave, Orlando, FL 32803",
      lat: 28.5557,
      lng: -81.3644,
      dogPolicy: "Neighborhood coffee shop with a garden patio. Dogs are welcome and treats are sometimes available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Lake Eola Park",
      address: "512 E Washington St, Orlando, FL 32801",
      lat: 28.5435,
      lng: -81.3735,
      offLeash: false,
      fenced: false,
      acres: 43.0,
      amenities: ["Lake loop trail", "Swan boats", "Amphitheater", "Farmers market", "Downtown views"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Orlando's iconic downtown park features a 0.9-mile paved path around a beautiful lake with a distinctive fountain. Leashed dogs are welcome on the loop and the Sunday farmers market is dog-friendly. The lake's swan population provides constant entertainment for curious pups.",
    },
    {
      name: "Fleet Peeples Park Dog Park",
      address: "2000 S Lakemont Ave, Winter Park, FL 32789",
      lat: 28.5756,
      lng: -81.3345,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Fenced", "Separate small dog area", "Lake views", "Water station", "Shade trees"],
      rating: 4.6,
      imageUrl: "",
      description:
        "One of the best dog parks in the Orlando area, set within Fleet Peeples Park with views of Lake Baldwin. The fenced off-leash area has separate sections for large and small dogs, and the adjacent lake trail adds walking distance. Well-maintained with a welcoming community.",
    },
    {
      name: "Dr. Phillips Dog Park",
      address: "8249 Buenavista Woods Blvd, Orlando, FL 32836",
      lat: 28.4547,
      lng: -81.4955,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced", "Water features", "Agility equipment", "Shade structures", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A well-designed dog park in the Dr. Phillips area with water features, agility equipment, and shade structures to combat the Florida sun. The park is popular with local dog owners and provides a fun, stimulating environment for pups of all sizes.",
    },
    {
      name: "West Orange Trail",
      address: "Multiple access points, Winter Garden, FL",
      lat: 28.5575,
      lng: -81.5857,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["22-mile paved trail", "Shade canopy", "Parks along route", "Water stations", "Bike shops"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A 22-mile paved rail-trail connecting downtown Winter Garden through citrus groves, lakefront parks, and shaded forest canopy. The flat, well-maintained trail is perfect for long walks or jogs with your leashed dog. The charming downtown Winter Garden at the western end has dog-friendly restaurants.",
    },
  ],
};
