export const outerBanksData = {
  city: {
    name: "Outer Banks",
    state: "North Carolina",
    region: "Southeast",
    lat: 35.5585,
    lng: -75.4665,
    dogFriendlinessScore: 8,
    description:
      "These windswept barrier islands stretching along the North Carolina coast are a dog's ultimate beach vacation. Miles of wide, uncrowded beaches where dogs can run free (especially in the off-season), wild horse sightings, lighthouses to explore, and a laid-back beach-town culture that celebrates the sandy, salty, tail-wagging life. From Corolla's wild mustangs to Hatteras' legendary surf, the OBX is a four-paw paradise.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 37000,
  },

  hotels: [
    {
      name: "Sanderling Resort",
      address: "1461 Duck Rd, Duck, NC 27949",
      lat: 36.1392,
      lng: -75.7556,
      priceRange: "$$$$" as const,
      dogPolicy:
        "Luxury resort on the sound and ocean with pet-friendly rooms. Dogs up to 75 lbs welcome with a premium pet amenity package.",
      maxDogWeight: 75,
      petFee: 100,
      amenities: [
        "Dog bed and bowls",
        "Dog treats",
        "Beach access",
        "Nature trails",
        "Pet concierge",
      ],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.sanderling-resort.com",
      phone: "(252) 261-4111",
    },
    {
      name: "The Inn on Pamlico Sound",
      address: "49684 NC-12, Buxton, NC 27920",
      lat: 35.2632,
      lng: -75.5356,
      priceRange: "$$$" as const,
      dogPolicy:
        "Soundfront B&B welcoming dogs in select rooms. Kayak launches and beautiful sunsets right from the property.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: [
        "Soundfront access",
        "Kayak rentals",
        "Dog-friendly grounds",
        "Water bowls",
        "Walking trails",
      ],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.innonpamlicosound.com",
      phone: "(252) 995-7030",
    },
    {
      name: "Shutters on the Banks",
      address: "405 S Virginia Dare Trail, Kill Devil Hills, NC 27948",
      lat: 36.019,
      lng: -75.668,
      priceRange: "$$" as const,
      dogPolicy:
        "Oceanfront hotel with pet-friendly rooms and easy beach access. Dogs of all sizes welcome with a small nightly fee.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: [
        "Oceanfront",
        "Beach access",
        "Pet-friendly rooms",
        "Pool",
        "Waste stations",
      ],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.shuttersonthebanks.com",
      phone: "(252) 441-5581",
    },
    {
      name: "Surf Side Hotel",
      address: "6701 S Virginia Dare Trail, Nags Head, NC 27959",
      lat: 35.928,
      lng: -75.614,
      priceRange: "$$" as const,
      dogPolicy:
        "Oceanfront rooms with pet-friendly options. Dogs welcome in designated rooms with direct beach access.",
      maxDogWeight: 80,
      petFee: 30,
      amenities: [
        "Oceanfront",
        "Direct beach access",
        "Pet-friendly rooms",
        "Balconies",
        "Free parking",
      ],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.surfsideobx.com",
      phone: "(252) 441-2105",
    },
    {
      name: "Cape Hatteras Motel",
      address: "46636 NC-12, Buxton, NC 27920",
      lat: 35.256,
      lng: -75.532,
      priceRange: "$" as const,
      dogPolicy:
        "Budget-friendly motel steps from the Cape Hatteras Lighthouse. Dogs of all sizes welcome with no breed restrictions.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: [
        "Close to lighthouse",
        "Pet-friendly rooms",
        "Beach nearby",
        "Free parking",
        "Outdoor shower",
      ],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.capehatterasmotel.com",
      phone: "(252) 995-5611",
    },
  ],

  nationalParks: [
    {
      name: "Cape Hatteras National Seashore",
      state: "North Carolina",
      lat: 35.2288,
      lng: -75.5276,
      dogPolicy:
        "Leashed dogs welcome on most beach areas and trails. A 70-mile stretch of pristine barrier island beaches — a dog's dream destination.",
      dogTrails: [
        "Buxton Woods Nature Trail",
        "Open beach walks (most areas)",
        "Lighthouse grounds trails",
        "Soundside nature trail at Ocracoke",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash at all times",
        "Not allowed in designated swimming beaches with lifeguards during summer",
        "Not permitted in bird nesting closures (seasonal)",
        "Must clean up after pets",
      ],
      description:
        "America's first national seashore stretches 70 miles across three barrier islands, and leashed dogs are welcome on most of this glorious coastline. Walk miles of wild, undeveloped beach with your pup, climb to lighthouse viewpoints, and explore maritime forests. The off-season is particularly magical when the beaches are nearly empty.",
      imageUrl: "",
      website: "https://www.nps.gov/caha",
    },
    {
      name: "Wright Brothers National Memorial",
      state: "North Carolina",
      lat: 36.0143,
      lng: -75.6681,
      dogPolicy:
        "Leashed dogs welcome on the grounds and around the memorial. Walk where flight first took to the skies — with your wingman.",
      dogTrails: [
        "Memorial grounds path",
        "Big Kill Devil Hill walk",
        "Flight line trail",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash",
        "Not allowed inside the visitor center or memorial building",
        "Must clean up after pets",
      ],
      description:
        "Stand on the windswept dunes where Orville and Wilbur Wright achieved the first powered flight in 1903. Leashed dogs can explore the sandy grounds, climb Big Kill Devil Hill for panoramic views, and walk along the original flight path markers. History and tail wags in perfect harmony.",
      imageUrl: "",
      website: "https://www.nps.gov/wrbr",
    },
    {
      name: "Fort Raleigh National Historic Site",
      state: "North Carolina",
      lat: 35.9384,
      lng: -75.7118,
      dogPolicy:
        "Leashed dogs welcome on the Thomas Hariot Nature Trail and park grounds. Explore the site of America's first English colony with your pup.",
      dogTrails: [
        "Thomas Hariot Nature Trail",
        "Freedom Trail",
        "Elizabethan Gardens adjacent path",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash",
        "Not allowed inside visitor center or Waterside Theatre",
        "Not permitted in Elizabethan Gardens",
        "Must clean up after pets",
      ],
      description:
        "The site of the mysterious Lost Colony offers peaceful walking trails through maritime forest on Roanoke Island. Leashed dogs can explore the nature trail, enjoy the shaded forest paths, and contemplate one of America's greatest mysteries alongside you.",
      imageUrl: "",
      website: "https://www.nps.gov/fora",
    },
    {
      name: "Pea Island National Wildlife Refuge",
      state: "North Carolina",
      lat: 35.6957,
      lng: -75.4926,
      dogPolicy:
        "Dogs NOT permitted on trails or in the refuge interior. However, leashed dogs are allowed on the ocean beach in front of the refuge.",
      dogTrails: ["Ocean beach walk (in front of refuge only)"],
      restrictions: [
        "No dogs on refuge trails including North Pond Trail",
        "No dogs in refuge interior or on soundside",
        "Leashed dogs allowed only on ocean beach",
        "Must clean up after pets",
      ],
      description:
        "While the refuge's trails and interior are off-limits to dogs, the stunning ocean beach in front of the refuge is fair game for leashed pups. The wide, wild beach is one of the most beautiful and least crowded stretches of the Outer Banks.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/pea-island",
    },
  ],

  restaurants: [
    {
      name: "Barefoot Bernie's Tropical Grill & Bar",
      address: "3730 N Croatan Hwy, Kitty Hawk, NC 27949",
      lat: 36.071,
      lng: -75.706,
      cuisine: "Tropical / American",
      priceRange: "$$" as const,
      dogPolicy:
        "Tropical outdoor tiki bar where sandy, salty dogs are always welcome. Kick off your shoes and let your pup lounge under the palms.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.barefootbernies.com",
    },
    {
      name: "Outer Banks Brewing Station",
      address: "600 S Croatan Hwy, Kill Devil Hills, NC 27948",
      lat: 36.02,
      lng: -75.671,
      cuisine: "Brewery / Seafood",
      priceRange: "$$" as const,
      dogPolicy:
        "Wind-powered brewery with a large dog-friendly patio. Craft beers and fresh seafood with your pup in a former gas station turned brewery.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.obbrewing.com",
    },
    {
      name: "The Blue Point",
      address: "1240 Duck Rd, Duck, NC 27949",
      lat: 36.156,
      lng: -75.755,
      cuisine: "Southern Seafood / Fine Dining",
      priceRange: "$$$" as const,
      dogPolicy:
        "Upscale waterfront restaurant with a soundside deck where leashed dogs are welcome during lunch. Stunning sunset views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thebluepoint.com",
    },
    {
      name: "Tortugas' Lie Shellfish Bar & Grille",
      address: "3014 S Virginia Dare Trail, Nags Head, NC 27959",
      lat: 35.957,
      lng: -75.623,
      cuisine: "Seafood / Caribbean",
      priceRange: "$$" as const,
      dogPolicy:
        "Laid-back beach joint with a dog-friendly deck. Fresh local catch, cold drinks, and that perfect OBX vibe your pup will love.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.tortugaslie.com",
    },
    {
      name: "Coastal Provisions",
      address: "600 Currituck Clubhouse Dr, Corolla, NC 27927",
      lat: 36.328,
      lng: -75.832,
      cuisine: "Market / Seafood",
      priceRange: "$$" as const,
      dogPolicy:
        "Gourmet market and restaurant with outdoor seating. Dogs welcome on the patio. Grab provisions for a beach picnic with your pup.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.coastalprovisions.com",
    },
    {
      name: "Stack 'Em High Pancakes",
      address: "3801 N Croatan Hwy, Kitty Hawk, NC 27949",
      lat: 36.075,
      lng: -75.707,
      cuisine: "Breakfast / American",
      priceRange: "$" as const,
      dogPolicy:
        "Classic OBX breakfast joint with an outdoor patio. Fuel up on pancakes with your pup before a day of beach adventures.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.stackemhighpancakes.com",
    },
    {
      name: "Uncle Ike's Sandbar & Grill",
      address: "46360 NC-12, Buxton, NC 27920",
      lat: 35.262,
      lng: -75.534,
      cuisine: "American / Seafood",
      priceRange: "$" as const,
      dogPolicy:
        "Casual Hatteras Island eatery with a pet-friendly patio. Your dog can watch the surfers while you enjoy fresh-caught fish tacos.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.uncleikessandbar.com",
    },
    {
      name: "Duck Donuts",
      address: "1190 Duck Rd, Duck, NC 27949",
      lat: 36.153,
      lng: -75.754,
      cuisine: "Bakery / Donuts",
      priceRange: "$" as const,
      dogPolicy:
        "The OBX original! Made-to-order donuts with a dog-friendly outdoor area. They even have dog-safe donut treats for your pup.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.duckdonuts.com",
    },
  ],

  cafes: [
    {
      name: "Front Porch Café",
      address: "2515 S Virginia Dare Trail, Nags Head, NC 27959",
      lat: 35.965,
      lng: -75.626,
      dogPolicy:
        "Charming oceanside café with a spacious porch where dogs are welcome. Start your beach day with coffee, a scone, and a sandy pup.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.frontporchcafeobx.com",
    },
    {
      name: "Kill Devil's Frozen Custard & Beach Fries",
      address: "1002 S Virginia Dare Trail, Kill Devil Hills, NC 27948",
      lat: 36.014,
      lng: -75.667,
      dogPolicy:
        "Walk-up window with outdoor picnic tables. Dogs welcome in the outdoor area and they often get their own small cup of custard.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.killdevilscustard.com",
    },
    {
      name: "Tullio's Bakery",
      address: "1159 Duck Rd, Duck, NC 27949",
      lat: 36.152,
      lng: -75.754,
      dogPolicy:
        "Italian bakery and coffee shop with a pet-friendly patio in the heart of Duck. Fresh pastries and dog-friendly vibes.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tulliosbakery.com",
    },
    {
      name: "Dancing Turtle Coffee Shop",
      address: "6564 NC-12, Ocracoke, NC 27960",
      lat: 35.115,
      lng: -75.981,
      dogPolicy:
        "Island coffee shop on Ocracoke with outdoor seating and a chill island vibe. Dogs welcome and the ferry ride over is half the fun.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.dancingturtlecoffee.com",
    },
    {
      name: "Duck's Cottage Coffee & Books",
      address: "1240 Duck Rd, Duck, NC 27949",
      lat: 36.155,
      lng: -75.755,
      dogPolicy:
        "A bookshop-café hybrid with an outdoor deck overlooking the Currituck Sound. Dogs welcome outside while you browse beach reads.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.duckscottage.com",
    },
  ],

  dogParks: [
    {
      name: "Corolla Beach (Off-Season Off-Leash)",
      address: "Corolla Village Rd, Corolla, NC 27927",
      lat: 36.372,
      lng: -75.83,
      offLeash: true,
      fenced: false,
      acres: 100,
      amenities: [
        "Wild beach",
        "Wild horse sightings",
        "Dune walks",
        "Free parking",
        "Waste stations at access points",
      ],
      rating: 4.8,
      imageUrl: "",
      description:
        "In the off-season, Corolla's wild beaches become an off-leash dog paradise. Miles of untouched shoreline where you might spot the famous wild Corolla horses galloping in the distance while your dog sprints through the surf. Keep your dog leashed if horses are nearby — an experience like no other.",
    },
    {
      name: "Nags Head Beach",
      address: "S Virginia Dare Trail, Nags Head, NC 27959",
      lat: 35.95,
      lng: -75.62,
      offLeash: true,
      fenced: false,
      acres: 60,
      amenities: [
        "Wide sandy beach",
        "Multiple beach access points",
        "Outdoor showers",
        "Waste stations",
        "Public restrooms",
      ],
      rating: 4.6,
      imageUrl: "",
      description:
        "Nags Head allows off-leash dogs on the beach from October through May, and leashed dogs year-round. The wide, sandy beaches with rolling dunes provide endless room for fetching, swimming, and the kind of full-speed zoomies only a beach can inspire.",
    },
    {
      name: "Jockey's Ridge State Park Dog Walk",
      address: "300 W Carolista Dr, Nags Head, NC 27959",
      lat: 35.9607,
      lng: -75.6316,
      offLeash: false,
      fenced: false,
      acres: 420,
      amenities: [
        "Sand dune trails",
        "Sound views",
        "Sunset watching",
        "Visitor center",
        "Waste stations",
      ],
      rating: 4.7,
      imageUrl: "",
      description:
        "The tallest active sand dune on the East Coast is an incredible place to walk your leashed dog. Climb the 80-foot dune for 360-degree views of the ocean, sound, and OBX. Your pup will love the sandy terrain and the wind-blown adventure. Sunsets from the top are legendary.",
    },
    {
      name: "Duck Town Park & Boardwalk",
      address: "1200 Duck Rd, Duck, NC 27949",
      lat: 36.154,
      lng: -75.755,
      offLeash: false,
      fenced: false,
      acres: 11,
      amenities: [
        "Boardwalk along Currituck Sound",
        "Gazebo",
        "Playground nearby",
        "Benches",
        "Waste stations",
      ],
      rating: 4.5,
      imageUrl: "",
      description:
        "The heart of the town of Duck features a beautiful soundside boardwalk where leashed dogs can stroll above the marsh. Watch herons fish, enjoy sound sunsets, and connect to shops and restaurants. The gentle boardwalk is perfect for dogs of all ages and abilities.",
    },
    {
      name: "Hatteras Island Beach Walk",
      address: "NC-12, Buxton, NC 27920",
      lat: 35.25,
      lng: -75.53,
      offLeash: true,
      fenced: false,
      acres: 80,
      amenities: [
        "Wild undeveloped beach",
        "Surfing waves",
        "Lighthouse views",
        "Beach access ramps",
        "Waste stations",
      ],
      rating: 4.7,
      imageUrl: "",
      description:
        "Hatteras Island is less developed and more wild than the northern OBX, making it ideal for off-leash beach adventures. Miles of wide, empty beach stretch in both directions from the iconic Cape Hatteras Lighthouse. Your dog can run free with the Atlantic on one side and the dunes on the other.",
    },
  ],
};
