export const oxfordMsData = {
  city: {
    name: "Oxford",
    state: "Mississippi",
    region: "Southeast",
    lat: 34.3665,
    lng: -89.5192,
    dogFriendlinessScore: 7,
    description:
      "This literary gem of a college town offers dogs a walkable historic square, shaded campus strolls at Ole Miss, and a food scene that rivals cities ten times its size. Oxford's Southern charm extends to its four-legged visitors with welcoming patios and scenic parks.",
    heroImage: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 28122,
  },
  hotels: [
    {
      name: "The Graduate Oxford",
      address: "400 N Lamar Blvd, Oxford, MS 38655",
      lat: 34.3680,
      lng: -89.5210,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome with a one-time pet fee. An Ole Miss-themed boutique hotel steps from the square.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Treats", "Waste bags", "Walking route suggestions"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.graduatehotels.com/oxford-ms",
      phone: "(662) 234-3031",
    },
    {
      name: "Chancellor's House Hotel",
      address: "141 University Ave, Oxford, MS 38655",
      lat: 34.3660,
      lng: -89.5180,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a non-refundable pet fee. An elegant boutique hotel on the Oxford square.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Walking map of the square", "Waste bags", "Treats at check-in"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.chancellorshouse.com",
      phone: "(662) 234-2431",
    },
    {
      name: "The Z Oxford",
      address: "729 N Lamar Blvd, Oxford, MS 38655",
      lat: 34.3710,
      lng: -89.5230,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a per-night fee. A modern boutique hotel with a rooftop bar and campus views.",
      maxDogWeight: 75,
      petFee: 40,
      amenities: ["Pet-friendly rooms", "Rooftop bar", "Water bowls", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.thezhotels.com/oxford",
      phone: "(662) 638-2370",
    },
    {
      name: "Hampton Inn Oxford-University",
      address: "100 Heritage Dr, Oxford, MS 38655",
      lat: 34.3700,
      lng: -89.5400,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a nightly fee. Reliable accommodations near the university and square.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Pet-friendly rooms", "Waste bags", "Walking areas", "Complimentary breakfast"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.hilton.com/en/hotels/oxfmshx",
      phone: "(662) 234-5565",
    },
  ],
  nationalParks: [
    {
      name: "Holly Springs National Forest",
      state: "Mississippi",
      lat: 34.5500,
      lng: -89.3500,
      dogPolicy: "Dogs welcome on all trails on a leash. Over 155,000 acres of rolling hills and pine forests northeast of Oxford.",
      dogTrails: ["Puskus Lake Trail", "Chewalla Lake Trail", "Davis Lake Nature Trail"],
      restrictions: ["Leash recommended", "Check seasonal hunting dates", "Must clean up after pet"],
      description: "About 30 minutes northeast of Oxford, Holly Springs National Forest offers pine-forested hills, small lakes, and quiet trails. Dogs can explore the peaceful woodland paths and lakeside areas.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/holly-springs",
    },
    {
      name: "Rowan Oak - Faulkner's Home",
      state: "Mississippi",
      lat: 34.3575,
      lng: -89.5220,
      dogPolicy: "Dogs welcome on the grounds and wooded paths on a leash. Not permitted inside the historic home.",
      dogTrails: ["Bailey Woods Trail", "Grounds Walk"],
      restrictions: ["Leash required", "Not allowed inside the house", "Must clean up after pet"],
      description: "William Faulkner's historic home features a beautiful cedar-lined driveway and 29 acres of wooded grounds. Dogs can walk the shaded paths through Bailey's Woods, now owned by the University of Mississippi.",
      imageUrl: "",
      website: "https://www.rfrmuseum.olemiss.edu",
    },
    {
      name: "Wall Doxey State Park",
      state: "Mississippi",
      lat: 34.5840,
      lng: -89.5560,
      dogPolicy: "Dogs welcome on trails and in campgrounds on a leash. A scenic state park about 20 minutes north of Oxford.",
      dogTrails: ["Nature Trail", "Lake Trail", "Beaver Dam Trail"],
      restrictions: ["Leash required", "Not allowed on swimming beach", "Must clean up after pet"],
      description: "Nestled in the Holly Springs National Forest, this state park features a spring-fed lake and forested trails. Dogs enjoy the woodland walks and lakeside scenery about 20 minutes from the Oxford square.",
      imageUrl: "",
      website: "https://www.mdwfp.com/parks-destinations/state-parks/wall-doxey",
    },
  ],
  restaurants: [
    {
      name: "Ajax Diner",
      address: "118 Courthouse Square, Oxford, MS 38655",
      lat: 34.3665,
      lng: -89.5190,
      cuisine: "Southern Soul Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the sidewalk patio overlooking the square. Classic Southern comfort food in a beloved Oxford institution.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ajaxdiner.net",
    },
    {
      name: "Snackbar",
      address: "721 N Lamar Blvd, Oxford, MS 38655",
      lat: 34.3705,
      lng: -89.5230,
      cuisine: "Southern French Bistro",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. James Beard-recognized Southern French cuisine with a chic atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.citysnackbar.com",
    },
    {
      name: "Proud Larry's",
      address: "211 S Lamar Blvd, Oxford, MS 38655",
      lat: 34.3650,
      lng: -89.5190,
      cuisine: "Pizza & Live Music",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. A legendary Oxford music venue and pizza joint since 1993.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.proudlarrys.com",
    },
    {
      name: "Saint Leo",
      address: "1101 Jackson Ave E, Oxford, MS 38655",
      lat: 34.3640,
      lng: -89.5100,
      cuisine: "Italian & Wood-Fired Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the spacious patio. Outstanding wood-fired pizzas and Italian fare in a converted gas station.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.saintleooxford.com",
    },
    {
      name: "Handy Andy",
      address: "1108 N Lamar Blvd, Oxford, MS 38655",
      lat: 34.3740,
      lng: -89.5240,
      cuisine: "Burgers & Shakes",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor window counter. A beloved roadside burger stand with hand-dipped milkshakes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.handyandyoxford.com",
    },
  ],
  cafes: [
    {
      name: "Bottletree Bakery",
      address: "923 Van Buren Ave, Oxford, MS 38655",
      lat: 34.3690,
      lng: -89.5210,
      dogPolicy: "Dogs welcome on the patio. A beloved Oxford bakery with fresh bread, pastries, and strong coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bottletreebakery.com",
    },
    {
      name: "The Coop Coffee House",
      address: "1112 Van Buren Ave, Oxford, MS 38655",
      lat: 34.3695,
      lng: -89.5190,
      dogPolicy: "Dogs welcome on the outdoor patio. A quirky coffee shop in a converted chicken coop with local character.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.thecoopoxford.com",
    },
    {
      name: "High Point Coffee",
      address: "305 S Lamar Blvd, Oxford, MS 38655",
      lat: 34.3640,
      lng: -89.5195,
      dogPolicy: "Dogs welcome at the sidewalk tables near the square. Specialty coffee and pastries in a warm setting.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.highpointcoffee.com",
    },
    {
      name: "Uptown Coffee",
      address: "236 S Lamar Blvd, Oxford, MS 38655",
      lat: 34.3655,
      lng: -89.5195,
      dogPolicy: "Dog-friendly outdoor seating just off the square. Locally roasted beans and a relaxed atmosphere.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.uptowncoffeeoxford.com",
    },
  ],
  dogParks: [
    {
      name: "Avent Park Dog Area",
      address: "Van Buren Ave, Oxford, MS 38655",
      lat: 34.3620,
      lng: -89.5230,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade trees", "Waste bag stations"],
      rating: 4.2,
      imageUrl: "",
      description: "Oxford's primary off-leash dog park with separate areas for large and small dogs. A community gathering spot shaded by mature hardwood trees near the university campus.",
    },
    {
      name: "University of Mississippi Grove",
      address: "University Ave, Oxford, MS 38655",
      lat: 34.3620,
      lng: -89.5410,
      offLeash: false,
      fenced: false,
      acres: 10,
      amenities: ["Shaded walks", "Historic oaks", "Benches", "Flat walking paths"],
      rating: 4.5,
      imageUrl: "",
      description: "The iconic Grove at Ole Miss is a beautiful shaded green space perfect for leashed walks beneath towering oak trees. Famous for football tailgating, it is a peaceful dog walking destination on non-game days.",
    },
    {
      name: "Lamar Park",
      address: "800 S Lamar Blvd, Oxford, MS 38655",
      lat: 34.3590,
      lng: -89.5210,
      offLeash: false,
      fenced: false,
      acres: 4,
      amenities: ["Walking trails", "Open green space", "Benches", "Playground area", "Waste bag stations"],
      rating: 4.1,
      imageUrl: "",
      description: "A pleasant neighborhood park south of the square with walking paths and open green space. Dogs on leash enjoy the shaded trails and proximity to nearby restaurants.",
    },
    {
      name: "FNC Park",
      address: "101 FNC Dr, Oxford, MS 38655",
      lat: 34.3680,
      lng: -89.5280,
      offLeash: false,
      fenced: false,
      acres: 6,
      amenities: ["Paved walking trails", "Open fields", "Benches", "Shade structures", "Waste bag stations"],
      rating: 4.0,
      imageUrl: "",
      description: "A newer community park with paved walking trails and open green spaces. Dogs enjoy the well-maintained paths and ample room for on-leash exercise.",
    },
  ],
};
