export const palmSpringsData = {
  city: {
    name: "Palm Springs",
    state: "California",
    region: "West Coast",
    lat: 33.8303,
    lng: -116.5453,
    dogFriendlinessScore: 7,
    description:
      "This mid-century modern desert oasis is surprisingly dog-friendly with pet-welcoming resorts, dog-friendly patios along Palm Canyon Drive, and scenic desert trails. The cooler months from October to April make Palm Springs an ideal winter escape for dogs and their owners.",
    heroImage: "https://images.unsplash.com/photo-1593246049226-ded77bf90326?w=1200&fit=crop",
    climate: "Desert",
    population: 44575,
  },
  hotels: [
    {
      name: "Kimpton Rowan Palm Springs",
      address: "100 W Tahquitz Canyon Way, Palm Springs, CA 92262",
      lat: 33.8310,
      lng: -116.5470,
      priceRange: "$$$$" as const,
      dogPolicy: "Kimpton's all-pets-welcome policy with no size limits and no fees. Rooftop pool with mountain views and downtown location.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treats", "Rooftop pool", "Loaner leashes"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.rowanpalmsprings.com",
      phone: "(760) 904-5015",
    },
    {
      name: "Arrive Palm Springs",
      address: "1551 N Palm Canyon Dr, Palm Springs, CA 92262",
      lat: 33.8400,
      lng: -116.5490,
      priceRange: "$$$" as const,
      dogPolicy: "Hip boutique hotel with a mid-century vibe welcoming dogs under 40 lbs. Pool parties and a chill desert atmosphere.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Pool", "Dog bed", "Water bowls", "Poolside lounge", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.arrivehotels.com",
      phone: "(760) 507-1650",
    },
    {
      name: "Caliente Tropics Resort",
      address: "411 E Palm Canyon Dr, Palm Springs, CA 92264",
      lat: 33.8250,
      lng: -116.5400,
      priceRange: "$$" as const,
      dogPolicy: "Retro Polynesian-themed resort with pet-friendly rooms. Dogs welcome with a laid-back Tiki vibe and poolside relaxation.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Pool", "Pet-friendly rooms", "Tiki bar", "Parking", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.calientetropics.com",
      phone: "(760) 327-1391",
    },
    {
      name: "Motel 6 Palm Springs Downtown",
      address: "660 S Palm Canyon Dr, Palm Springs, CA 92264",
      lat: 33.8210,
      lng: -116.5460,
      priceRange: "$" as const,
      dogPolicy: "Budget-friendly downtown option welcoming dogs of all sizes with no pet fee. Walking distance to shops and restaurants.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Pet-friendly rooms", "Pool", "Parking", "Downtown location", "Waste bags"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.motel6.com",
      phone: "(760) 327-4200",
    },
  ],
  nationalParks: [
    {
      name: "San Jacinto State Park & Mount San Jacinto",
      state: "California",
      lat: 33.8100,
      lng: -116.6700,
      dogPolicy: "Dogs NOT allowed on trails within the state wilderness area. However, leashed dogs can ride the Palm Springs Aerial Tramway and enjoy the Mountain Station area.",
      dogTrails: ["Mountain Station observation deck area"],
      restrictions: ["No dogs on wilderness trails", "Dogs allowed at Mountain Station only", "6-foot leash required at station", "Carry warm clothing for elevation change"],
      description: "While the wilderness trails are off-limits to dogs, the Palm Springs Aerial Tramway offers a dramatic ride from the desert floor to 8,516 feet. Dogs can enjoy the mountain station area and the cooler temperatures above the desert heat.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/sanjacinto",
    },
    {
      name: "Indian Canyons",
      state: "California",
      lat: 33.7700,
      lng: -116.5500,
      dogPolicy: "Dogs allowed on all trails on a leash. One of the most dog-friendly desert hiking experiences in the Palm Springs area.",
      dogTrails: ["Palm Canyon Trail", "Andreas Canyon Trail", "Murray Canyon Trail", "Victor Trail"],
      restrictions: ["Leash required at all times", "Tribal land admission fee", "Carry plenty of water", "Avoid midday heat in summer months"],
      description: "Owned by the Agua Caliente Band of Cahuilla Indians, Indian Canyons offer stunning palm oasis trails through desert canyons. Dogs can explore ancient fan palm groves, seasonal streams, and dramatic canyon walls.",
      imageUrl: "",
      website: "https://www.indian-canyons.com",
    },
    {
      name: "Joshua Tree National Park",
      state: "California",
      lat: 33.8734,
      lng: -115.9010,
      dogPolicy: "Dogs allowed in campgrounds, on paved roads, and within 100 feet of roads. Not permitted on any trails or in the backcountry.",
      dogTrails: ["Paved campground roads", "Parking area walks"],
      restrictions: ["Not allowed on any trails", "Must stay within 100 feet of roads", "6-foot leash required", "Not allowed in backcountry", "Summer heat is dangerous"],
      description: "While trail access is limited for dogs, the scenic drives through Joshua Tree's surreal landscape of twisted trees and boulder formations are accessible. The park is about an hour from Palm Springs and worth the drive even with dog restrictions.",
      imageUrl: "",
      website: "https://www.nps.gov/jotr",
    },
  ],
  restaurants: [
    {
      name: "Workshop Kitchen + Bar",
      address: "800 N Palm Canyon Dr, Palm Springs, CA 92262",
      lat: 33.8340,
      lng: -116.5480,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Stunning mid-century modern restaurant with a patio that welcomes dogs. Creative seasonal dishes in an architecturally striking space.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.workshoppalmsprings.com",
    },
    {
      name: "King's Highway",
      address: "701 E Palm Canyon Dr, Palm Springs, CA 92264",
      lat: 33.8230,
      lng: -116.5380,
      cuisine: "American Diner-Modern",
      priceRange: "$$" as const,
      dogPolicy: "Retro-chic diner at the Ace Hotel with a poolside patio welcoming dogs. Elevated comfort food in a hip desert setting.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.kingshighwaydiner.com",
    },
    {
      name: "Cheeky's",
      address: "622 N Palm Canyon Dr, Palm Springs, CA 92262",
      lat: 33.8330,
      lng: -116.5475,
      cuisine: "Brunch & Breakfast",
      priceRange: "$$" as const,
      dogPolicy: "Popular brunch spot with a shaded patio perfect for dogs. Inventive breakfast dishes with a menu that changes weekly.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cheekysps.com",
    },
    {
      name: "El Jefe",
      address: "100 W Tahquitz Canyon Way, Palm Springs, CA 92262",
      lat: 33.8310,
      lng: -116.5470,
      cuisine: "Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Vibrant poolside taqueria at the Kimpton Rowan with a dog-friendly patio. Street tacos and frozen margaritas with mountain views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.eljefeps.com",
    },
    {
      name: "Tyler's Burgers",
      address: "149 S Indian Canyon Dr, Palm Springs, CA 92262",
      lat: 33.8280,
      lng: -116.5465,
      cuisine: "Burgers",
      priceRange: "$" as const,
      dogPolicy: "No-frills burger shack with outdoor picnic tables where dogs are welcome. Cash only and consistently rated the best burger in town.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.tylersburgers.com",
    },
  ],
  cafes: [
    {
      name: "Ernest Coffee",
      address: "1101 N Palm Canyon Dr, Palm Springs, CA 92262",
      lat: 33.8370,
      lng: -116.5485,
      dogPolicy: "Stylish desert café with a courtyard patio where dogs are welcome. Specialty coffee and pastries in a mid-century modern setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ernestcoffee.com",
    },
    {
      name: "Koffi",
      address: "515 N Palm Canyon Dr, Palm Springs, CA 92262",
      lat: 33.8320,
      lng: -116.5478,
      dogPolicy: "Palm Springs institution with a large dog-friendly patio on Palm Canyon Drive. Locally roasted coffee and a social neighborhood vibe.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.koffi.com",
    },
    {
      name: "Townie Bagels",
      address: "190 N Sunrise Way, Palm Springs, CA 92262",
      lat: 33.8300,
      lng: -116.5400,
      dogPolicy: "Popular bagel shop with outdoor seating where dogs are welcome. New York-style bagels in the California desert.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.towniebagels.com",
    },
    {
      name: "Palm Greens Café",
      address: "611 S Palm Canyon Dr, Palm Springs, CA 92264",
      lat: 33.8220,
      lng: -116.5460,
      dogPolicy: "Health-focused café with a shaded patio welcoming dogs. Organic juices, smoothie bowls, and vegetarian fare.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.palmgreenscafe.com",
    },
  ],
  dogParks: [
    {
      name: "Palm Springs Dog Park",
      address: "222 Civic Dr N, Palm Springs, CA 92262",
      lat: 33.8360,
      lng: -116.5420,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Separate small dog area", "Water stations", "Shade structures", "Benches", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "The city's main off-leash dog park features separate areas for large and small dogs with shade structures to combat the desert sun. Water stations keep dogs hydrated, and the mountain backdrop adds scenic charm.",
    },
    {
      name: "Tahquitz Creek Park",
      address: "400 E Mesquite Ave, Palm Springs, CA 92264",
      lat: 33.8200,
      lng: -116.5420,
      offLeash: false,
      fenced: false,
      acres: 12,
      amenities: ["Walking paths", "Shade trees", "Green lawns", "Picnic areas", "Waste bag stations"],
      rating: 4.2,
      imageUrl: "",
      description: "A lush desert park along Tahquitz Creek with walking paths and green lawns. Leashed dogs enjoy the shade trees and grassy areas that feel like an oasis in the desert landscape.",
    },
    {
      name: "Demuth Park",
      address: "3601 E Mesquite Ave, Palm Springs, CA 92264",
      lat: 33.8190,
      lng: -116.5200,
      offLeash: false,
      fenced: false,
      acres: 25,
      amenities: ["Walking trails", "Sports fields", "Playground", "Restrooms", "Shade"],
      rating: 4.1,
      imageUrl: "",
      description: "One of Palm Springs' larger parks with walking paths through manicured grounds with mountain views. Leashed dogs enjoy the morning and evening walks when temperatures are comfortable.",
    },
    {
      name: "Cathedral City Dog Park",
      address: "38-600 Date Palm Dr, Cathedral City, CA 92234",
      lat: 33.8050,
      lng: -116.4650,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Water stations", "Shade structures", "Agility equipment", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "Just east of Palm Springs in Cathedral City, this well-equipped off-leash park features agility equipment, shade structures, and mountain views. A favorite for Coachella Valley dog owners.",
    },
  ],
};
