export const parkCityData = {
  city: {
    name: "Park City",
    state: "Utah",
    region: "Mountain West",
    lat: 40.6461,
    lng: -111.498,
    dogFriendlinessScore: 8,
    description:
      "This legendary ski town high in the Wasatch Mountains is just as magical for dogs as it is for powder hounds. Summer brings miles of dog-friendly hiking trails through wildflower meadows, while winter offers snowshoeing adventures and cozy firesides. Historic Main Street is lined with pet-friendly shops and restaurants, and the mountain culture here means your trail dog will fit right in with the locals.",
    heroImage: "https://images.unsplash.com/photo-1551524559-8af4e6624178?w=1200&fit=crop",
    climate: "Continental",
    population: 8467,
  },

  hotels: [
    {
      name: "The Lodges at Deer Valley",
      address: "2900 Deer Valley Dr E, Park City, UT 84060",
      lat: 40.6355,
      lng: -111.479,
      priceRange: "$$$$" as const,
      dogPolicy:
        "Luxury mountain lodge welcoming dogs up to 50 lbs with a premium pet package. Ski-in, ski-out in winter, trail access in summer.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: [
        "Dog bed and bowls",
        "Gourmet dog treats",
        "Trail access",
        "Concierge pet services",
        "Mountain views",
      ],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.thelodgesatdeervalley.com",
      phone: "(435) 615-2500",
    },
    {
      name: "Hotel Park City",
      address: "2001 Park Ave, Park City, UT 84060",
      lat: 40.658,
      lng: -111.498,
      priceRange: "$$$" as const,
      dogPolicy:
        "All-suite mountain hotel welcoming dogs of all sizes. Spacious rooms with kitchenettes and trail access from the property.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: [
        "Full kitchen",
        "Dog bed",
        "Trail access",
        "Spa on-site",
        "Grassy areas",
      ],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelparkCity.com",
      phone: "(435) 200-2000",
    },
    {
      name: "Marriott's MountainSide",
      address: "1305 Lowell Ave, Park City, UT 84060",
      lat: 40.6468,
      lng: -111.493,
      priceRange: "$$$" as const,
      dogPolicy:
        "Ski-in/ski-out resort with pet-friendly villas. Dogs up to 60 lbs welcome with a one-time cleaning fee.",
      maxDogWeight: 60,
      petFee: 75,
      amenities: [
        "Full kitchen",
        "Fireplace",
        "Hot tub access",
        "Ski storage",
        "Close to Main Street",
      ],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(435) 940-2000",
    },
    {
      name: "Best Western Plus Landmark Inn",
      address: "6560 N Landmark Dr, Park City, UT 84098",
      lat: 40.7,
      lng: -111.527,
      priceRange: "$$" as const,
      dogPolicy:
        "Dog-friendly hotel at the base of the Wasatch with easy access to trails and town. Two dogs max, all sizes.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: [
        "Pet relief area",
        "Free breakfast",
        "Pool",
        "Waste stations",
        "Free parking",
      ],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(435) 649-7300",
    },
    {
      name: "Treasure Mountain Inn",
      address: "255 Main St, Park City, UT 84060",
      lat: 40.645,
      lng: -111.498,
      priceRange: "$$" as const,
      dogPolicy:
        "Historic Main Street inn with pet-friendly condos. Dogs welcome with a nightly fee. Walk to everything from your door.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: [
        "Main Street location",
        "Full kitchen",
        "Hot tub",
        "Walking distance to lifts",
        "Waste bags",
      ],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.treasuremountaininn.com",
      phone: "(435) 649-7334",
    },
  ],

  nationalParks: [
    {
      name: "Wasatch Mountain State Park",
      state: "Utah",
      lat: 40.5483,
      lng: -111.4899,
      dogPolicy:
        "Leashed dogs welcome on all trails and campgrounds. A mountain playground just minutes from Park City.",
      dogTrails: [
        "Pine Creek Trail",
        "Snake Creek Trail",
        "Huber Grove Nature Trail",
        "Oak Hollow Loop",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash",
        "Not allowed on golf course",
        "Must clean up after pets",
      ],
      description:
        "Utah's most developed state park offers miles of trails through mountain meadows, oak forests, and alpine terrain. Leashed dogs can explore everything from easy nature loops to challenging mountain climbs. Summer wildflowers and autumn aspens make this a year-round stunner.",
      imageUrl: "",
      website: "https://stateparks.utah.gov/parks/wasatch-mountain",
    },
    {
      name: "Jordanelle State Park",
      state: "Utah",
      lat: 40.6,
      lng: -111.428,
      dogPolicy:
        "Leashed dogs allowed on trails and in campgrounds. The reservoir provides beautiful mountain lake scenery.",
      dogTrails: [
        "Perimeter Trail",
        "Nature Trail",
        "Rock Cliff boardwalk area",
      ],
      restrictions: [
        "Dogs must be on a leash",
        "Not allowed on swimming beaches",
        "Must clean up after pets",
      ],
      description:
        "A beautiful reservoir nestled in the Wasatch Mountains just east of Park City. Leashed dogs can hike the perimeter trail with gorgeous views of the blue water and surrounding peaks. The Rock Cliff area features boardwalks through wetlands where your pup might spot great blue herons.",
      imageUrl: "",
      website: "https://stateparks.utah.gov/parks/jordanelle",
    },
    {
      name: "Uinta-Wasatch-Cache National Forest",
      state: "Utah",
      lat: 40.68,
      lng: -111.51,
      dogPolicy:
        "Dogs welcome on-leash in most areas and off-leash in many backcountry sections. A massive mountain wilderness at Park City's doorstep.",
      dogTrails: [
        "Mid Mountain Trail",
        "Rob's Trail",
        "Armstrong Trail",
        "Bloods Lake Trail",
        "Lake Desolation Trail",
      ],
      restrictions: [
        "Dogs must be on-leash in developed recreation sites",
        "Off-leash allowed in most backcountry areas under voice control",
        "Must carry out waste",
        "Be aware of moose — keep dogs close",
      ],
      description:
        "This vast national forest surrounds Park City with world-class trails. The Mid Mountain Trail offers 22 miles of singletrack with wildflower meadows and mountain views. Rob's Trail is a local favorite for a quick after-work hike. In summer, the alpine lakes and wildflower bowls are absolutely breathtaking with your trail pup.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/uwcnf",
    },
  ],

  restaurants: [
    {
      name: "No Name Saloon",
      address: "447 Main St, Park City, UT 84060",
      lat: 40.6445,
      lng: -111.498,
      cuisine: "Pub / American",
      priceRange: "$$" as const,
      dogPolicy:
        "Legendary Main Street dive bar with a dog-friendly patio. Famous buffalo burgers and a vibe your pup will love.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.nonamesaloon.net",
    },
    {
      name: "High West Distillery & Saloon",
      address: "703 Park Ave, Park City, UT 84060",
      lat: 40.645,
      lng: -111.497,
      cuisine: "Western / New American",
      priceRange: "$$$" as const,
      dogPolicy:
        "Utah's first legal distillery since 1870, with a dog-friendly patio featuring mountain views and award-winning whiskey.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.highwest.com",
    },
    {
      name: "Wasatch Brew Pub",
      address: "250 Main St, Park City, UT 84060",
      lat: 40.645,
      lng: -111.498,
      cuisine: "Brewery / Pub",
      priceRange: "$$" as const,
      dogPolicy:
        "Legendary Park City brewery with a Main Street patio. Dogs welcome while you enjoy the famous Polygamy Porter.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.wasatchbeers.com",
    },
    {
      name: "Buona Vita",
      address: "804 Main St, Park City, UT 84060",
      lat: 40.643,
      lng: -111.497,
      cuisine: "Italian",
      priceRange: "$$" as const,
      dogPolicy:
        "Charming Italian trattoria with a small outdoor patio. Leashed dogs welcome for a taste of Italian mountain dining.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.buonavitapc.com",
    },
    {
      name: "Flanagan's on Main",
      address: "438 Main St, Park City, UT 84060",
      lat: 40.6445,
      lng: -111.498,
      cuisine: "Irish Pub / American",
      priceRange: "$$" as const,
      dogPolicy:
        "Cozy Irish pub with a heated outdoor patio. Dogs welcome year-round, even when the snow is flying.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.flanagansonmain.com",
    },
    {
      name: "Five5eeds",
      address: "1600 Snow Creek Dr, Park City, UT 84060",
      lat: 40.649,
      lng: -111.505,
      cuisine: "Australian / Brunch",
      priceRange: "$$" as const,
      dogPolicy:
        "Aussie-inspired brunch spot with a sunny patio. Dogs welcome outside while you enjoy avocado toast with mountain views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.five5eeds.com",
    },
    {
      name: "Squatters Roadhouse Grill",
      address: "1900 Park Ave, Park City, UT 84060",
      lat: 40.658,
      lng: -111.499,
      cuisine: "Brewery / American",
      priceRange: "$$" as const,
      dogPolicy:
        "Spacious patio with fire pit and mountain views. Dogs welcome and the craft beer selection is outstanding.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.squatters.com",
    },
    {
      name: "Harvest",
      address: "240 Heber Ave, Park City, UT 84060",
      lat: 40.645,
      lng: -111.496,
      cuisine: "Farm-to-Table / American",
      priceRange: "$$$" as const,
      dogPolicy:
        "Upscale farm-to-table dining with seasonal patio seating. Well-behaved leashed dogs welcome outside.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.harvestparkcity.com",
    },
  ],

  cafes: [
    {
      name: "Atticus Coffee, Books & Teahouse",
      address: "328 Main St, Park City, UT 84060",
      lat: 40.645,
      lng: -111.498,
      dogPolicy:
        "Bookstore-coffee shop combo on Main Street with outdoor seating. Grab a latte and a novel while your dog watches the skiers walk by.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.atticusteahouse.com",
    },
    {
      name: "Pink Elephant Coffee",
      address: "1167 Woodside Ave, Park City, UT 84060",
      lat: 40.649,
      lng: -111.493,
      dogPolicy:
        "Beloved local coffee spot with a dog-friendly patio. The baristas know most of the neighborhood dogs by name.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.pinkelephantcoffee.com",
    },
    {
      name: "Ritual Chocolate",
      address: "1105 Iron Horse Dr, Park City, UT 84060",
      lat: 40.641,
      lng: -111.49,
      dogPolicy:
        "Bean-to-bar chocolate maker with a café and outdoor seating. Dogs welcome on the patio while you taste some of America's finest craft chocolate.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.ritualchocolate.com",
    },
    {
      name: "Hugo Coffee Roasters",
      address: "1585 Ute Blvd, Park City, UT 84098",
      lat: 40.683,
      lng: -111.519,
      dogPolicy:
        "A coffee company literally founded to help rescue dogs! Dog treats at the counter and a patio where every dog is a VIP. Portion of proceeds go to dog rescue organizations.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.8,
      imageUrl: "",
      website: "https://www.hugocoffeeroasters.com",
    },
    {
      name: "Campos Coffee",
      address: "2000 Park Ave, Park City, UT 84060",
      lat: 40.658,
      lng: -111.498,
      dogPolicy:
        "Aussie-rooted specialty coffee with outdoor seating. Dogs welcome and the flat whites are Park City's best.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.camposcoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Run-A-Muk Dog Park",
      address: "5714 Trailside Dr, Park City, UT 84098",
      lat: 40.685,
      lng: -111.52,
      offLeash: true,
      fenced: true,
      acres: 4,
      amenities: [
        "Fenced area",
        "Separate small and large dog areas",
        "Water stations",
        "Shade structures",
        "Waste stations",
        "Parking",
      ],
      rating: 4.6,
      imageUrl: "",
      description:
        "Park City's premier dog park with stunning mountain views. Fully fenced with separate areas for big and small dogs, water stations, and enough room for epic zoomies. The mountain backdrop makes this one of the most scenic dog parks in Utah.",
    },
    {
      name: "Willow Creek Dog Park",
      address: "Willow Creek Park, Park City, UT 84098",
      lat: 40.695,
      lng: -111.525,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: [
        "Fenced area",
        "Water fountain",
        "Benches",
        "Shade trees",
        "Waste stations",
      ],
      rating: 4.3,
      imageUrl: "",
      description:
        "A neighborhood dog park with mountain views and a friendly local crowd. Fenced and well-maintained with water access and shade. A great spot to let your pup socialize after a day on the trails.",
    },
    {
      name: "Round Valley Trails",
      address: "Quinn's Junction, Park City, UT 84098",
      lat: 40.685,
      lng: -111.468,
      offLeash: true,
      fenced: false,
      acres: 400,
      amenities: [
        "Miles of multi-use trails",
        "Open meadows",
        "Mountain views",
        "Waste stations at trailheads",
        "Parking lots",
      ],
      rating: 4.8,
      imageUrl: "",
      description:
        "A massive open-space area with miles of rolling singletrack trails through sage meadows and aspen groves. Dogs can run off-leash (voice control required) with 360-degree mountain views. In summer, wildflowers carpet the meadows; in winter, snowshoers and their dogs share the trails. Absolutely spectacular.",
    },
    {
      name: "Mid Mountain Trail (Dog-Friendly Section)",
      address: "Park City Mountain Resort, Park City, UT 84060",
      lat: 40.65,
      lng: -111.51,
      offLeash: false,
      fenced: false,
      acres: 50,
      amenities: [
        "Mountain singletrack",
        "Alpine views",
        "Wildflower meadows",
        "Creek crossings",
        "Trailhead parking",
      ],
      rating: 4.7,
      imageUrl: "",
      description:
        "Part of the legendary 22-mile Mid Mountain Trail that traverses Park City at 8,000 feet elevation. Leashed dogs can enjoy alpine meadows, aspen forests, and jaw-dropping Wasatch Mountain panoramas. The trail is groomed for various uses and offers a true mountain hiking experience.",
    },
    {
      name: "Park City Rail Trail",
      address: "Bonanza Dr, Park City, UT 84060",
      lat: 40.65,
      lng: -111.49,
      offLeash: false,
      fenced: false,
      acres: 15,
      amenities: [
        "Paved trail",
        "Historic mining sites",
        "Creek views",
        "Benches",
        "Waste stations",
      ],
      rating: 4.4,
      imageUrl: "",
      description:
        "A paved rail-trail following the historic Union Pacific rail corridor through Park City. Leashed dogs can enjoy the easy, scenic walk past old mining sites, along Silver Creek, and through mountain meadows. Connects to multiple trailheads for longer adventures.",
    },
  ],
};
