export const pasoRoblesData = {
  city: {
    name: "Paso Robles",
    state: "California",
    region: "West Coast",
    lat: 35.6264,
    lng: -120.6910,
    dogFriendlinessScore: 7,
    description:
      "Paso Robles is Central California's wine country gem where dogs are welcome at many tasting rooms, outdoor restaurants, and rolling vineyard trails. With a charming downtown square, hot springs heritage, and over 200 wineries, Paso offers a relaxed wine country experience for dogs and their owners.",
    heroImage: "https://images.unsplash.com/photo-1504681869696-d977211a5f4c?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 32017,
  },
  hotels: [
    {
      name: "Hotel & Spa & Nature Reserve at Allegretto Vineyard Resort",
      address: "2700 Buena Vista Dr, Paso Robles, CA 93446",
      lat: 35.6100,
      lng: -120.6800,
      priceRange: "$$$$" as const,
      dogPolicy: "Luxury vineyard resort with pet-friendly rooms overlooking the vineyards. Dogs under 50 lbs welcome with resort grounds access.",
      maxDogWeight: 50,
      petFee: 125,
      amenities: ["Vineyard views", "Dog bed", "Walking paths", "Treats", "Resort grounds"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.allegrettovineyardresort.com",
      phone: "(805) 369-2500",
    },
    {
      name: "Paso Robles Inn",
      address: "1103 Spring St, Paso Robles, CA 93446",
      lat: 35.6265,
      lng: -120.6910,
      priceRange: "$$$" as const,
      dogPolicy: "Historic downtown hotel with hot springs and pet-friendly rooms. Dogs welcome in a walkable location on the town square.",
      maxDogWeight: 60,
      petFee: 50,
      amenities: ["Hot springs tubs", "Dog bed", "Downtown location", "Garden", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.pasoroblesinn.com",
      phone: "(805) 238-2660",
    },
    {
      name: "La Bellasera Hotel & Suites",
      address: "206 Alexa Ct, Paso Robles, CA 93446",
      lat: 35.6300,
      lng: -120.6950,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique hotel with spacious suites and pet-friendly rooms. Dogs under 40 lbs welcome near the downtown area.",
      maxDogWeight: 40,
      petFee: 50,
      amenities: ["Suites", "Dog bed", "Water bowls", "Walking paths", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.labellasera.com",
      phone: "(805) 238-2834",
    },
    {
      name: "Holiday Inn Express Paso Robles",
      address: "2455 Riverside Ave, Paso Robles, CA 93446",
      lat: 35.6350,
      lng: -120.7000,
      priceRange: "$$" as const,
      dogPolicy: "Reliable chain hotel welcoming dogs with easy access to wine country and downtown. Affordable pet-friendly rooms.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Pet-friendly rooms", "Pool", "Breakfast", "Parking", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(805) 238-6500",
    },
  ],
  nationalParks: [
    {
      name: "Lake Nacimiento",
      state: "California",
      lat: 35.7500,
      lng: -120.8700,
      dogPolicy: "Dogs allowed at the lake on leash. Swimming, boating, and lakeside camping make it a fun water destination for dogs.",
      dogTrails: ["Lakeshore Trail", "Heritage Trail", "Dam Overlook Trail"],
      restrictions: ["Leash required in developed areas", "Dogs allowed to swim in lake", "Clean up after pet", "Day use fee required"],
      description: "A scenic reservoir northwest of Paso Robles surrounded by oak-covered hills. Dogs love swimming in the lake and walking the shoreline trails while enjoying the peaceful hill country landscape.",
      imageUrl: "",
      website: "https://www.lakenacimiento.com",
    },
    {
      name: "Los Padres National Forest (Cerro Alto)",
      state: "California",
      lat: 35.4500,
      lng: -120.7500,
      dogPolicy: "Dogs welcome on most trails on leash. The Cerro Alto area offers accessible mountain hiking near Paso Robles.",
      dogTrails: ["Cerro Alto Summit Trail", "AT&T Trail", "Boy Scout Trail"],
      restrictions: ["Leash required", "Adventure Pass required at trailhead", "Carry extra water", "Poison oak on lower trails"],
      description: "South of Paso Robles, the Cerro Alto area of Los Padres National Forest offers a moderately challenging hike to a peak with 360-degree views of the coast and wine country. Dogs enjoy the oak-shaded lower trails and mountain scenery.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/lpnf",
    },
    {
      name: "Salinas River Trail",
      state: "California",
      lat: 35.6270,
      lng: -120.6850,
      dogPolicy: "Dogs welcome on the paved trail on leash. A scenic riverside trail through the heart of Paso Robles wine country.",
      dogTrails: ["Salinas River Trail"],
      restrictions: ["Leash required", "Shared multi-use trail", "Watch for cyclists", "Clean up after pet"],
      description: "A paved trail following the Salinas River through Paso Robles, connecting parks and neighborhoods. Dogs on leash enjoy the tree-lined riverside walk with views of the surrounding vineyard-dotted hills.",
      imageUrl: "",
      website: "https://www.prcity.com",
    },
  ],
  restaurants: [
    {
      name: "Thomas Hill Organics",
      address: "1313 Park St, Paso Robles, CA 93446",
      lat: 35.6275,
      lng: -120.6905,
      cuisine: "Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Farm-to-table restaurant on the town square with a garden patio welcoming dogs. Organic ingredients paired with local wines.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thomashillorganics.com",
    },
    {
      name: "Fish Gaucho",
      address: "1244 Park St, Paso Robles, CA 93446",
      lat: 35.6270,
      lng: -120.6908,
      cuisine: "Mexican Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Lively Mexican seafood restaurant with a patio on the square where dogs are welcome. Ceviche, tacos, and craft margaritas.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.fishgaucho.com",
    },
    {
      name: "The Hatch Rotisserie & Bar",
      address: "835 13th St, Paso Robles, CA 93446",
      lat: 35.6260,
      lng: -120.6920,
      cuisine: "American Rotisserie",
      priceRange: "$$" as const,
      dogPolicy: "Rotisserie restaurant with a spacious patio where dogs are welcome. Slow-roasted meats and local wines in a casual setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hatchpasorobles.com",
    },
    {
      name: "Tin City Cider Co.",
      address: "3005 Limestone Way, Paso Robles, CA 93446",
      lat: 35.6150,
      lng: -120.6700,
      cuisine: "Cider & Small Plates",
      priceRange: "$$" as const,
      dogPolicy: "Craft cider taproom in Tin City with a dog-friendly outdoor area. Hard ciders paired with small plates in a warehouse district.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tincitycider.com",
    },
    {
      name: "La Cosecha Bar & Restaurant",
      address: "835 12th St, Paso Robles, CA 93446",
      lat: 35.6262,
      lng: -120.6915,
      cuisine: "Latin American",
      priceRange: "$$$" as const,
      dogPolicy: "Upscale Latin American restaurant with a courtyard patio welcoming dogs. Pan-Latin cuisine with Central Coast wines.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.lacosechabar.com",
    },
  ],
  cafes: [
    {
      name: "Joe's Place",
      address: "1228 Pine St, Paso Robles, CA 93446",
      lat: 35.6268,
      lng: -120.6912,
      dogPolicy: "Downtown café near the square with a patio where dogs are welcome. Coffee, pastries, and breakfast in wine country.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.joesplacepaso.com",
    },
    {
      name: "Red Scooter Deli",
      address: "1102 Pine St, Paso Robles, CA 93446",
      lat: 35.6265,
      lng: -120.6918,
      dogPolicy: "Charming deli and café with outdoor seating where dogs are welcome. Fresh sandwiches and coffee in downtown Paso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.redscooterdeli.com",
    },
    {
      name: "Spearhead Coffee",
      address: "825 Pine St, Paso Robles, CA 93446",
      lat: 35.6258,
      lng: -120.6925,
      dogPolicy: "Specialty coffee shop with a small patio where dogs are welcome. Precision espresso and pour-overs in downtown Paso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.spearheadcoffee.com",
    },
    {
      name: "Kitchenette at Tin City",
      address: "3011 Limestone Way, Paso Robles, CA 93446",
      lat: 35.6152,
      lng: -120.6705,
      dogPolicy: "Café in the Tin City warehouse district with outdoor seating and a dog-friendly patio. Coffee and light bites among wineries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.kitchenettepaso.com",
    },
  ],
  dogParks: [
    {
      name: "Barney Schwartz Park",
      address: "2970 Union Rd, Paso Robles, CA 93446",
      lat: 35.6400,
      lng: -120.6700,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Shade structures", "Benches", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "Paso Robles' premier off-leash dog park within the larger Barney Schwartz Park complex. Fenced areas for large and small dogs with lake views and shade structures for hot Central Coast afternoons.",
    },
    {
      name: "Paso Robles City Park",
      address: "1100 Spring St, Paso Robles, CA 93446",
      lat: 35.6270,
      lng: -120.6910,
      offLeash: false,
      fenced: false,
      acres: 4,
      amenities: ["Shade trees", "Walking paths", "Downtown square", "Benches", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "The iconic town square park in the heart of Paso Robles surrounded by wine tasting rooms and restaurants. Leashed dogs enjoy the shaded walking paths and the vibrant downtown atmosphere.",
    },
    {
      name: "Larry Moore Park",
      address: "8th & Riverside Ave, Paso Robles, CA 93446",
      lat: 35.6290,
      lng: -120.6950,
      offLeash: false,
      fenced: false,
      acres: 20,
      amenities: ["Walking trails", "Picnic areas", "Playground", "Shade trees", "Restrooms"],
      rating: 4.2,
      imageUrl: "",
      description: "A large community park along the Salinas River with walking trails and shaded picnic areas. Leashed dogs enjoy the riverside scenery and the spacious grounds on this popular local park.",
    },
    {
      name: "Salinas River Nature Walk",
      address: "Niblick Rd, Paso Robles, CA 93446",
      lat: 35.6180,
      lng: -120.6850,
      offLeash: false,
      fenced: false,
      acres: 12,
      amenities: ["Nature trail", "River views", "Oak trees", "Bird watching", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description: "A peaceful nature trail along the Salinas River on the south side of Paso Robles. Leashed dogs enjoy the oak-shaded riverside walk with views of rolling vineyard hills in the distance.",
    },
  ],
};
