export const pensacolaData = {
  city: {
    name: "Pensacola",
    state: "Florida",
    region: "Southeast",
    lat: 30.4213,
    lng: -87.2169,
    dogFriendlinessScore: 7,
    description:
      "Where sugar-white sand meets emerald Gulf waters, Pensacola rolls out the welcome mat (and the beach towel) for traveling pups. This historic naval city blends Southern charm with beach-town ease — think dog-friendly seafood shacks, pet-welcoming beach stretches, and enough warm sunshine to keep tails wagging year-round. Your dog will dig the sand, and you'll dig the laid-back vibe.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 54312,
  },
  hotels: [
    {
      name: "The Pensacola Grand Hotel",
      address: "200 E Gregory St, Pensacola, FL 32502",
      lat: 30.4118,
      lng: -87.2108,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome in designated rooms. Two-pet maximum. Non-refundable pet fee applies per stay.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Downtown location", "Pet relief area", "Walking distance to parks", "Concierge"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.pensacolagrandhotel.com",
      phone: "(850) 433-3336",
    },
    {
      name: "Residence Inn by Marriott Pensacola Downtown",
      address: "601 E Chase St, Pensacola, FL 32502",
      lat: 30.4143,
      lng: -87.2065,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a $100 non-refundable fee. Grassy pet area on property.",
      maxDogWeight: 0,
      petFee: 100,
      amenities: ["Full kitchen suites", "Pet relief area", "Complimentary breakfast", "Evening social"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(850) 432-0202",
    },
    {
      name: "Hilton Pensacola Beach",
      address: "12 Via De Luna Dr, Pensacola Beach, FL 32561",
      lat: 30.3342,
      lng: -87.1463,
      priceRange: "$$$" as const,
      dogPolicy: "Small dogs under 25 lbs welcome in designated pet rooms. Beach access nearby with seasonal dog hours.",
      maxDogWeight: 25,
      petFee: 75,
      amenities: ["Beach access", "Gulf views", "Pet bed provided", "Near dog-friendly beach sections"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(850) 916-2999",
    },
    {
      name: "Home2 Suites by Hilton Pensacola I-10",
      address: "7170 Plantation Rd, Pensacola, FL 32504",
      lat: 30.4821,
      lng: -87.2291,
      priceRange: "$$" as const,
      dogPolicy: "All pets welcome with a per-stay fee. Large grassy exercise area behind property.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Pet exercise area", "Waste stations", "Suite-style rooms", "Laundry facilities"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(850) 696-2021",
    },
    {
      name: "Lee House Pensacola",
      address: "400 Bayfront Pkwy, Pensacola, FL 32502",
      lat: 30.4048,
      lng: -87.2101,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique B&B that welcomes well-behaved dogs. Gourmet dog biscuits and a water station in the courtyard.",
      maxDogWeight: 60,
      petFee: 40,
      amenities: ["Bayfront location", "Courtyard", "Gourmet breakfast", "Dog biscuits", "Walking distance to marina"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.leehousepensacola.com",
      phone: "(850) 912-8770",
    },
  ],
  nationalParks: [
    {
      name: "Gulf Islands National Seashore",
      state: "Florida",
      lat: 30.3067,
      lng: -87.2795,
      dogPolicy: "Dogs allowed on a six-foot leash on the Fort Pickens area roads, parking lots, and some beach sections. Not allowed on swim beaches or nature trails.",
      dogTrails: ["Fort Pickens Road (paved)", "Langdon Beach access road"],
      restrictions: ["No dogs on designated swim beaches", "No dogs on nature trails", "Leash required at all times", "No dogs in buildings"],
      description:
        "Pristine barrier islands with blindingly white sand and crystal-clear waters. While the best swimming beaches are off-limits to pups, the Fort Pickens area offers historic forts to sniff around and quieter beach sections where your leashed dog can dig their paws into Gulf Coast sand.",
      imageUrl: "",
      website: "https://www.nps.gov/guis",
    },
    {
      name: "Big Lagoon State Park",
      state: "Florida",
      lat: 30.3148,
      lng: -87.3862,
      dogPolicy: "Dogs welcome on leash on all trails and in the campground. Not allowed on the swimming beach.",
      dogTrails: ["Grand Lagoon Trail", "Long Pond Trail", "East Beach Boardwalk"],
      restrictions: ["Leash required (6 ft max)", "No dogs on swim beach", "Clean up required"],
      description:
        "A hidden gem of coastal ecology where salt marshes, tidal flats, and pine forests converge. Your leashed pup can explore nature trails teeming with shorebirds and maybe spot a dolphin from the observation platform. The boardwalks keep paws dry over the marshiest bits.",
      imageUrl: "",
      website: "https://www.floridastateparks.org/parks-and-trails/big-lagoon-state-park",
    },
    {
      name: "Blackwater River State Forest",
      state: "Florida",
      lat: 30.7825,
      lng: -86.8581,
      dogPolicy: "Dogs welcome on leash throughout the forest trails and recreation areas.",
      dogTrails: ["Sweetwater Trail", "Bear Lake Loop", "Jackson Trail"],
      restrictions: ["Leash required", "No dogs in swimming areas", "Pack out all waste"],
      description:
        "One of the largest state forests in Florida with one of the purest sand-bottom rivers in the world. Your pup can wade in the tea-colored Blackwater River, hike through longleaf pine savannas, and experience a wilder side of the Panhandle far from the beach crowds.",
      imageUrl: "",
      website: "https://www.fdacs.gov/Forest-Wildfire/Our-Forests/State-Forests/Blackwater-River-State-Forest",
    },
  ],
  restaurants: [
    {
      name: "The Fish House",
      address: "600 S Barracks St, Pensacola, FL 32502",
      lat: 30.4034,
      lng: -87.2079,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the waterfront patio. Water bowls available. Beautiful Pensacola Bay views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.fishhousepensacola.com",
    },
    {
      name: "Peg Leg Pete's",
      address: "1010 Fort Pickens Rd, Pensacola Beach, FL 32561",
      lat: 30.3291,
      lng: -87.156,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Dogs love the sandy outdoor patio. Water bowls always set out. A true beach-dog experience.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.peglegpetes.com",
    },
    {
      name: "The Grand Marlin",
      address: "400 Pensacola Beach Blvd, Pensacola Beach, FL 32561",
      lat: 30.3468,
      lng: -87.1539,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor deck overlooking Little Sabine Bay.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thegrandmarlin.com",
    },
    {
      name: "Native Cafe",
      address: "45A Via De Luna Dr, Pensacola Beach, FL 32561",
      lat: 30.3355,
      lng: -87.1437,
      cuisine: "Breakfast",
      priceRange: "$" as const,
      dogPolicy: "Super dog-friendly patio. Pups get water and the occasional scratch behind the ears from staff.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "",
    },
    {
      name: "Perfect Plain Brewing Co.",
      address: "50 E Garden St, Pensacola, FL 32502",
      lat: 30.4131,
      lng: -87.2138,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Extremely dog-friendly taproom with an outdoor courtyard. Water bowls, treats, and plenty of pup admirers.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.perfectplain.com",
    },
    {
      name: "Jaco's Bayfront Bar & Grille",
      address: "997 S Palafox St, Pensacola, FL 32502",
      lat: 30.4024,
      lng: -87.2138,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the waterfront patio. Casual atmosphere perfect for sandy paws and sunsets.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Carmen's Lunch Bar & Tapas",
      address: "400 E Gregory St, Pensacola, FL 32502",
      lat: 30.4117,
      lng: -87.2082,
      cuisine: "Tapas",
      priceRange: "$$" as const,
      dogPolicy: "Well-behaved dogs welcome at outdoor tables in the courtyard.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Shaggy's Pensacola Beach",
      address: "701 Pensacola Beach Blvd, Pensacola Beach, FL 32561",
      lat: 30.3481,
      lng: -87.1526,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "The name says it all. Dogs are stars here. Outdoor deck seating with Gulf breezes and pup treats.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.shaggys.com",
    },
  ],
  cafes: [
    {
      name: "Bodacious Brew",
      address: "407 E Gregory St, Pensacola, FL 32502",
      lat: 30.4118,
      lng: -87.208,
      dogPolicy: "Shaded patio perfect for pups. Dog treats behind the counter and water bowls by the door.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "Fosko Coffee Barre",
      address: "410 S Palafox St, Pensacola, FL 32502",
      lat: 30.4091,
      lng: -87.2143,
      dogPolicy: "Leashed dogs welcome on the sidewalk patio. Artisan coffee in a historic downtown setting.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "The Drowsy Poet Coffee Company",
      address: "800 N Palafox St, Pensacola, FL 32501",
      lat: 30.4199,
      lng: -87.2166,
      dogPolicy: "Drive-through and outdoor seating available. Dogs get free pup cups with whipped cream.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.drowsypoet.com",
    },
    {
      name: "Nom Sushi & Ramen (Coffee Bar)",
      address: "17 Palafox Pl, Pensacola, FL 32502",
      lat: 30.4107,
      lng: -87.2148,
      dogPolicy: "Patio seating allows leashed dogs. Grab a matcha and let your pup enjoy downtown foot traffic.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Ollie & Speed Coffee Traders",
      address: "300 E Intendencia St, Pensacola, FL 32502",
      lat: 30.4102,
      lng: -87.2093,
      dogPolicy: "Named after dogs! This pet-obsessed cafe has a full outdoor patio, dog treats, and pup-themed merch.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Bayview Park Off-Leash Dog Area",
      address: "2001 E Lloyd St, Pensacola, FL 32503",
      lat: 30.4225,
      lng: -87.1948,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Separate small dog area", "Water fountains", "Shade trees", "Benches", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A well-maintained fenced park tucked inside historic Bayview Park. Separate areas for big and small dogs, plenty of shade from live oaks, and a friendly local dog community that gathers every evening for the unofficial 'bark hour.'",
    },
    {
      name: "Pensacola Beach Dog Beach",
      address: "Ft Pickens Rd, Pensacola Beach, FL 32561",
      lat: 30.3254,
      lng: -87.1689,
      offLeash: true,
      fenced: false,
      acres: 10.0,
      amenities: ["Beach access", "Gulf swimming", "Waste bag stations", "Parking", "Rinse station"],
      rating: 4.8,
      imageUrl: "",
      description:
        "The holy grail for beach-loving dogs. A designated off-leash stretch of Pensacola's famous white-sand beach where pups can sprint, splash, and roll in the warm Gulf waters. The turquoise waves and powdery sand make this doggy heaven on Earth.",
    },
    {
      name: "Bruce Beach Dog Park",
      address: "601 W Main St, Pensacola, FL 32502",
      lat: 30.4031,
      lng: -87.2216,
      offLeash: true,
      fenced: true,
      acres: 1.0,
      amenities: ["Bay views", "Water fountain", "Benches", "Waste bags", "Shade pavilion"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A compact downtown dog park with stunning views of Pensacola Bay. Your pup can play off-leash while you watch sailboats glide by. Small but mighty, with a dedicated local following.",
    },
    {
      name: "Hitzman-Optimist Park",
      address: "670 Langley Ave, Pensacola, FL 32504",
      lat: 30.4391,
      lng: -87.2063,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Double-gated entry", "Water spigot", "Benches", "Waste stations", "Open field"],
      rating: 4.0,
      imageUrl: "",
      description:
        "A no-frills neighborhood dog park with a big grassy field for running and a double-gated entry for escape artists. The regulars are friendly and the morning crowd is always happy to share tips on dog-friendly spots around town.",
    },
    {
      name: "Maritime Park Waterfront Walk",
      address: "301 W Main St, Pensacola, FL 32502",
      lat: 30.4044,
      lng: -87.219,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Paved walkway", "Bay views", "Benches", "Water fountains", "Waste stations", "Shade pavilions"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A gorgeous bayfront promenade where leashed dogs strut their stuff along the water's edge. The wide paved path is perfect for long walks, and the sunset views over Pensacola Bay are absolutely spectacular. Stadium events bring extra excitement.",
    },
  ],
};
