export const petoskeyData = {
  city: {
    name: "Petoskey",
    state: "Michigan",
    region: "Midwest",
    lat: 45.3733,
    lng: -84.9553,
    dogFriendlinessScore: 8,
    description:
      "Petoskey is a charming lakeside resort town on Little Traverse Bay where dogs are embraced by the community. With Petoskey stone-strewn beaches, forested trails, and a walkable Gaslight District full of dog-friendly shops and eateries, it is a perfect Up North getaway for dog lovers.",
    heroImage: "https://images.unsplash.com/photo-1517483000871-1dbf64a6e1c6?w=1200&fit=crop",
    climate: "Humid continental with lake effect",
    population: 5701,
  },

  hotels: [
    {
      name: "Stafford's Perry Hotel",
      address: "100 Lewis St, Petoskey, MI 49770",
      lat: 45.3740,
      lng: -84.9555,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with a pet fee. Historic waterfront hotel with old-world charm.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Treats", "Waterfront walking", "Gaslight District access"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.staffords.com",
      phone: "(231) 347-4000",
    },
    {
      name: "Apple Tree Inn",
      address: "915 Spring St, Petoskey, MI 49770",
      lat: 45.3700,
      lng: -84.9500,
      priceRange: "$" as const,
      dogPolicy: "Very dog-friendly inn welcoming all sizes with no breed restrictions. Affordable and comfortable.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Grassy grounds", "Near Bear River", "Waste stations", "Walking paths"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.appletreeinnpetoskey.com",
      phone: "(231) 348-2900",
    },
    {
      name: "Odawa Hotel",
      address: "1444 US-131, Petoskey, MI 49770",
      lat: 45.3660,
      lng: -84.9430,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 80 lbs welcome in pet-friendly rooms with a nightly fee.",
      maxDogWeight: 80,
      petFee: 30,
      amenities: ["Spacious rooms", "Grassy exercise area", "Near nature trails", "Indoor pool"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.odawahotel.com",
      phone: "(231) 347-6041",
    },
    {
      name: "Crooked River Lodge",
      address: "6845 US-31 S, Alanson, MI 49706",
      lat: 45.4100,
      lng: -84.8540,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a one-time pet fee. Rustic lodge setting near the Inland Waterway.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["River access", "Dog bed", "Walking trails", "Outdoor fire pit", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.crookedriverlodge.com",
      phone: "(231) 548-5000",
    },
  ],

  nationalParks: [
    {
      name: "Petoskey State Park",
      state: "Michigan",
      lat: 45.3850,
      lng: -84.9430,
      dogPolicy: "Leashed dogs welcome on trails and in campgrounds. Beautiful Lake Michigan beach for Petoskey stone hunting.",
      dogTrails: ["Old Baldy Trail", "Portage Trail", "Beach Walk"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on the main swimming beach",
        "Must stay on designated trails",
      ],
      description:
        "This state park on Little Traverse Bay features forested dune trails and beaches famous for Petoskey stones. The Old Baldy Trail climbs to panoramic views of the bay and is a favorite dog walk.",
      imageUrl: "",
      website: "https://www.michigan.gov/petoskeysp",
    },
    {
      name: "North Country Trail - Northern Michigan",
      state: "Michigan",
      lat: 45.4200,
      lng: -84.8900,
      dogPolicy: "Leashed dogs welcome on all sections. Long-distance trail passing through forests and along rivers.",
      dogTrails: ["Jordan Valley Segment", "Mackinaw State Forest Segment", "Wilderness Area Section"],
      restrictions: [
        "Must be on leash in developed areas",
        "Voice control acceptable on remote sections",
        "Not allowed in wilderness area overnight without permit",
      ],
      description:
        "The North Country National Scenic Trail passes through northern Michigan near Petoskey, offering stunning forest hiking through the Jordan Valley and beyond. Dogs enjoy the rolling terrain and creek crossings.",
      imageUrl: "",
      website: "https://www.nps.gov/noco",
    },
    {
      name: "Headlands International Dark Sky Park",
      state: "Michigan",
      lat: 45.7570,
      lng: -84.8710,
      dogPolicy: "Leashed dogs welcome on trails and in park grounds. Michigan's first dark sky park on the Straits of Mackinac.",
      dogTrails: ["Dark Sky Trail", "Shoreline Trail", "Wilderness Loop"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed in the observatory",
        "White lights prohibited after sunset",
      ],
      description:
        "About 30 minutes north of Petoskey, this park on the Straits of Mackinac offers incredible stargazing and scenic trails. Evening visits with your dog under a blanket of stars are unforgettable.",
      imageUrl: "",
      website: "https://www.midarkskypark.org",
    },
  ],

  restaurants: [
    {
      name: "City Park Grill",
      address: "432 E Lake St, Petoskey, MI 49770",
      lat: 45.3742,
      lng: -84.9530,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Historic bar once frequented by Ernest Hemingway.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.cityparkgrill.com",
    },
    {
      name: "Palette Bistro",
      address: "321 Bay St, Petoskey, MI 49770",
      lat: 45.3738,
      lng: -84.9562,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved leashed dogs welcome on the patio with bay views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.palettebistro.com",
    },
    {
      name: "Beards Brewery",
      address: "215 E Lake St, Petoskey, MI 49770",
      lat: 45.3740,
      lng: -84.9540,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Extremely dog-friendly with outdoor seating and water bowls. Craft beer and pub snacks.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.beardsbrewery.com",
    },
    {
      name: "Chandler's",
      address: "215 1/2 Howard St, Petoskey, MI 49770",
      lat: 45.3735,
      lng: -84.9558,
      cuisine: "Fine Dining",
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome on the seasonal patio. Upscale lakeside dining with fresh Michigan ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.chandlerspetoskey.com",
    },
    {
      name: "Roast & Toast Cafe",
      address: "309 E Lake St, Petoskey, MI 49770",
      lat: 45.3741,
      lng: -84.9535,
      cuisine: "Breakfast & Lunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. A beloved local breakfast spot in the Gaslight District.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.roastandtoastcafe.com",
    },
  ],

  cafes: [
    {
      name: "Bread & Chocolate Bakery Cafe",
      address: "229 E Lake St, Petoskey, MI 49770",
      lat: 45.3740,
      lng: -84.9542,
      dogPolicy: "Dogs welcome at outdoor tables. Fresh-baked goods and quality coffee in the Gaslight District.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.breadandchocolatecafe.com",
    },
    {
      name: "Julienne Tomatoes",
      address: "13 Lake St, Petoskey, MI 49770",
      lat: 45.3737,
      lng: -84.9570,
      dogPolicy: "Leashed dogs welcome on the sidewalk patio. Coffee, smoothies, and fresh lunches.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.juliennetomatoes.com",
    },
    {
      name: "Higher Grounds Coffee",
      address: "406 E Mitchell St, Petoskey, MI 49770",
      lat: 45.3748,
      lng: -84.9520,
      dogPolicy: "Outdoor patio welcomes dogs. Specialty coffee and light bites in a relaxed setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.highergroundstrading.com",
    },
    {
      name: "Johan's Bakery & Bistro",
      address: "107 Howard St, Petoskey, MI 49770",
      lat: 45.3735,
      lng: -84.9560,
      dogPolicy: "Dogs welcome at outdoor seating area. European-style bakery with pastries and coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.johansbakery.com",
    },
  ],

  dogParks: [
    {
      name: "Bear River Valley Recreation Area",
      address: "Bear River Rd, Petoskey, MI 49770",
      lat: 45.3690,
      lng: -84.9480,
      offLeash: false,
      fenced: false,
      acres: 40.0,
      amenities: ["Paved trail", "River access", "Scenic overlooks", "Benches", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A beautiful paved trail following the Bear River through Petoskey. Dogs love the river access points and the scenic walk through wetlands and forests to Lake Michigan.",
    },
    {
      name: "Bayfront Park",
      address: "101 E Lake St, Petoskey, MI 49770",
      lat: 45.3745,
      lng: -84.9510,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Lake Michigan beach", "Walking paths", "Benches", "Restrooms", "Playground nearby"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A waterfront park on Little Traverse Bay with stunning views of Lake Michigan. While on-leash, dogs enjoy the beach walks and the chance to hunt for Petoskey stones along the shore.",
    },
    {
      name: "North Central Michigan College Nature Trails",
      address: "1515 Howard St, Petoskey, MI 49770",
      lat: 45.3780,
      lng: -84.9620,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Wooded trails", "Wildlife viewing", "Quiet setting", "Parking", "Trail markers"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A hidden gem of forested trails on the college campus. The quiet, wooded paths offer a peaceful walk for dogs who prefer a calmer environment away from busy parks.",
    },
    {
      name: "Magnus City Park",
      address: "East Mitchell St, Petoskey, MI 49770",
      lat: 45.3750,
      lng: -84.9490,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Water fountain", "Benches", "Waste bags", "Shade trees"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Petoskey's dedicated off-leash dog area within Magnus Park provides a safe, fenced space for dogs to play freely. The compact size keeps it manageable and social.",
    },
  ],
};
