export const philadelphiaData = {
  city: {
    name: "Philadelphia",
    state: "Pennsylvania",
    region: "Northeast",
    lat: 39.9526,
    lng: -75.1652,
    dogFriendlinessScore: 7,
    description:
      "The City of Brotherly Love extends its warmth to dogs with an impressive network of dog parks, pet-friendly patios, and the sprawling Wissahickon Valley Park. Philly's neighborhood culture means every block has dog lovers, and the restaurant scene's embrace of outdoor dining makes it easy to bring your pup along.",
    heroImage: "https://images.unsplash.com/photo-1569761316261-9a8696fa2ca3?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 1603797,
  },
  hotels: [
    {
      name: "Kimpton Hotel Monaco Philadelphia",
      address: "433 Chestnut St, Philadelphia, PA 19106",
      lat: 39.9494,
      lng: -75.1492,
      priceRange: "$$$$" as const,
      dogPolicy: "All pets welcome regardless of size with no additional fee. Hosted evening wine hour is dog-friendly. Pet beds and bowls provided.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pet bed", "Dog bowls", "Wine hour", "Old City location"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.monaco-philadelphia.com",
      phone: "(215) 925-2111",
    },
    {
      name: "Lokal Hotel Old City",
      address: "139 N 2nd St, Philadelphia, PA 19106",
      lat: 39.9524,
      lng: -75.1441,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique apartment-style hotel welcoming dogs with a $50 fee. Full kitchens and neighborhood feel.",
      maxDogWeight: 60,
      petFee: 50,
      amenities: ["Full kitchen", "Local neighborhood guides", "Dog-friendly parks nearby", "Apartment style"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.staylokal.com",
      phone: "(215) 627-1911",
    },
    {
      name: "The Notary Hotel",
      address: "21 S Juniper St, Philadelphia, PA 19107",
      lat: 39.9521,
      lng: -75.1637,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a $75 non-refundable pet fee. Treats and walking maps at check-in.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["City Hall views", "Walking maps", "Treats at check-in", "Center City location"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.thenotaryhotel.com",
      phone: "(215) 496-3200",
    },
    {
      name: "Home2 Suites Philadelphia Convention Center",
      address: "1200 Arch St, Philadelphia, PA 19107",
      lat: 39.9546,
      lng: -75.1607,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly suites with a $75 non-refundable fee. Kitchenette in every room and a pet relief area on property.",
      maxDogWeight: 75,
      petFee: 75,
      amenities: ["Kitchenette", "Pet relief area", "Laundry", "Free breakfast", "Convention Center location"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(215) 569-8300",
    },
  ],
  nationalParks: [
    {
      name: "Wissahickon Valley Park",
      state: "Pennsylvania",
      lat: 40.0537,
      lng: -75.2127,
      dogPolicy: "Dogs welcome on all trails. Off-leash permitted in designated areas. One of the best urban dog hiking destinations in the country.",
      dogTrails: ["Forbidden Drive", "Orange Trail", "Yellow Trail", "Cresheim Trail"],
      restrictions: ["Leash in parking areas", "Clean up required", "No dogs in creek during restoration periods"],
      description:
        "A 1,800-acre gorge cutting through Northwest Philadelphia that feels like the Appalachian Trail dropped into a city. Forbidden Drive is a seven-mile car-free gravel path along Wissahickon Creek that's the most popular dog walk in Philadelphia. Rocky side trails climb to overlooks with views of the forested gorge below.",
      imageUrl: "",
      website: "https://www.fow.org",
    },
    {
      name: "Valley Forge National Historical Park",
      state: "Pennsylvania",
      lat: 40.0993,
      lng: -75.4468,
      dogPolicy: "Leashed dogs welcome on all trails and throughout the park. A perfect day trip from the city.",
      dogTrails: ["Joseph Plumb Martin Trail", "River Trail", "Valley Creek Trail", "Mount Joy Loop"],
      restrictions: ["Six-foot leash required", "Clean up required", "No dogs inside historic buildings"],
      description:
        "Where Washington's army endured the winter of 1777-78, your dog can now roam 3,500 acres of rolling meadows, wooded trails, and historic monuments. The paved multi-use trail winds past reconstructed log cabins and across open fields where deer graze at dawn. History and nature in one magnificent outing.",
      imageUrl: "",
      website: "https://www.nps.gov/vafo",
    },
    {
      name: "John Heinz National Wildlife Refuge",
      state: "Pennsylvania",
      lat: 39.8878,
      lng: -75.2653,
      dogPolicy: "Leashed dogs welcome on the main impoundment trail. A surprising urban wetland teeming with wildlife.",
      dogTrails: ["Impoundment Loop Trail", "Boardwalk Trail", "Trolley Bed Trail"],
      restrictions: ["Leash required at all times", "Stay on designated trails", "No dogs on boardwalk sections during nesting season"],
      description:
        "The first urban national wildlife refuge in the country protects over 1,000 acres of freshwater tidal marsh just minutes from the airport. The flat trails loop around an impoundment lake where herons, egrets, and turtles are plentiful. Your dog will be fascinated by the sheer variety of smells.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/john-heinz",
    },
  ],
  restaurants: [
    {
      name: "Suraya",
      address: "1528 Frankford Ave, Philadelphia, PA 19125",
      lat: 39.9755,
      lng: -75.1341,
      cuisine: "Lebanese",
      priceRange: "$$$" as const,
      dogPolicy: "Stunning garden patio welcomes leashed dogs. Lebanese cuisine with a gorgeous outdoor dining experience in Fishtown.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.surayaphilly.com",
    },
    {
      name: "Wm. Mulherin's Sons",
      address: "1355 N Front St, Philadelphia, PA 19122",
      lat: 39.9686,
      lng: -75.1356,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Industrial-chic restaurant with a dog-friendly courtyard. Wood-fired Italian fare in a converted Fishtown whiskey blending house.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.wmmulherinssons.com",
    },
    {
      name: "Barkingham Palace at Revolution House",
      address: "200 Market St, Philadelphia, PA 19106",
      lat: 39.9499,
      lng: -75.1453,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Old City beer garden with a large dog-friendly patio. Craft beers and pub fare steps from Independence Hall.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.revolutionhouse.com",
    },
    {
      name: "Hungry Pigeon",
      address: "743 S 4th St, Philadelphia, PA 19147",
      lat: 39.9388,
      lng: -75.1485,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Queen Village gem with sidewalk tables. Leashed dogs welcome outside while you enjoy seasonal farm-to-table dishes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hungrypigeon.com",
    },
    {
      name: "Yards Brewing Company",
      address: "500 Spring Garden St, Philadelphia, PA 19123",
      lat: 39.9619,
      lng: -75.1475,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Massive beer hall with a dog-friendly outdoor beer garden. Philadelphia's iconic craft brewery.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.yardsbrewing.com",
    },
  ],
  cafes: [
    {
      name: "Elixr Coffee Roasters",
      address: "207 S Sydenham St, Philadelphia, PA 19102",
      lat: 39.9497,
      lng: -75.1655,
      dogPolicy: "Third-wave coffee roaster with outdoor seating in Rittenhouse. Dogs welcome at sidewalk tables.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.elixrcoffee.com",
    },
    {
      name: "Rival Bros Coffee",
      address: "2400 Lombard St, Philadelphia, PA 19146",
      lat: 39.9442,
      lng: -75.1805,
      dogPolicy: "Neighborhood coffee truck turned brick-and-mortar with a dog-friendly patio. Known for their cold brew.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.rivalbros.com",
    },
    {
      name: "ReAnimator Coffee",
      address: "1523 E Susquehanna Ave, Philadelphia, PA 19125",
      lat: 39.9739,
      lng: -75.1326,
      dogPolicy: "Fishtown roastery with a spacious outdoor patio. Leashed pups are regulars at this neighborhood favorite.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.reanimatorcoffee.com",
    },
    {
      name: "Menagerie Coffee",
      address: "18 S 3rd St, Philadelphia, PA 19106",
      lat: 39.9504,
      lng: -75.1465,
      dogPolicy: "Old City coffee shop with outdoor benches near cobblestone streets. Dogs enjoy watching the horse-drawn carriages pass by.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.menageriecoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Schuylkill River Dog Park",
      address: "2500 Walnut St, Philadelphia, PA 19103",
      lat: 39.9509,
      lng: -75.1842,
      offLeash: true,
      fenced: true,
      acres: 0.75,
      amenities: ["River views", "Separate small dog area", "Water fountain", "Benches", "Paved access"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Philadelphia's premier dog park sits along the Schuylkill River Trail with gorgeous water views. Separate areas for large and small dogs, plus a water fountain that keeps pups hydrated after spirited play sessions. The adjacent trail is perfect for pre- or post-park walks.",
    },
    {
      name: "Orianna Hill Dog Park",
      address: "900 N Orianna St, Philadelphia, PA 19123",
      lat: 39.9654,
      lng: -75.1422,
      offLeash: true,
      fenced: true,
      acres: 0.3,
      amenities: ["Fully fenced", "Benches", "Shade trees", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A neighborhood gem in Northern Liberties, this intimate fenced park has a loyal community of regulars. The shaded space is well-maintained and the neighborhood's walkability means there's always an interesting route to get there.",
    },
    {
      name: "Pretzel Park Dog Run",
      address: "4300 Silverwood St, Philadelphia, PA 19127",
      lat: 40.0271,
      lng: -75.2244,
      offLeash: true,
      fenced: true,
      acres: 0.2,
      amenities: ["Fenced", "Community garden adjacent", "Farmers market Saturdays", "Benches"],
      rating: 4.1,
      imageUrl: "",
      description:
        "Manayunk's community dog park is small but mighty, with a devoted group of neighborhood dogs who gather daily. The adjacent Pretzel Park hosts a farmers market on Saturdays, making it easy to combine errands with dog socializing.",
    },
    {
      name: "Seger Park Dog Run",
      address: "1100 Lombard St, Philadelphia, PA 19147",
      lat: 39.9432,
      lng: -75.1591,
      offLeash: true,
      fenced: true,
      acres: 0.35,
      amenities: ["Separate small dog area", "Water fountain", "Shade", "Benches", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "One of Philadelphia's most popular dog parks, tucked in the heart of the Bella Vista and Graduate Hospital neighborhoods. The separate small dog area is a big draw for owners of petite pups, and the park's central location makes it a social hotspot.",
    },
  ],
};
