export const phoenixData = {
  city: {
    name: "Phoenix",
    state: "Arizona",
    region: "Southwest",
    lat: 33.4484,
    lng: -112.0740,
    dogFriendlinessScore: 7,
    description:
      "Phoenix is a desert metropolis surrounded by stunning mountain preserves that welcome dogs on their trails. With over 300 sunny days a year, an extensive urban trail system, and a booming pet-friendly dining scene, the Valley of the Sun is a year-round destination for dog lovers who time their hikes wisely.",
    heroImage: "https://images.unsplash.com/photo-1558645836-e44122a743ee?w=1200&fit=crop",
    climate: "Hot desert",
    population: 1608139,
  },

  hotels: [
    {
      name: "Hotel Valley Ho",
      address: "6850 E Main St, Scottsdale, AZ 85251",
      lat: 33.4940,
      lng: -111.9290,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of any size welcome with a nightly pet fee. Mid-century modern style with VIP pet program.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Food bowls", "Treats", "Dog walking service", "Pool-adjacent pet relief area"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hotelvalleyho.com",
      phone: "(480) 376-2600",
    },
    {
      name: "Kimpton Hotel Palomar Phoenix",
      address: "2 E Jefferson St, Phoenix, AZ 85004",
      lat: 33.4480,
      lng: -112.0730,
      priceRange: "$$$" as const,
      dogPolicy: "All Kimpton properties welcome dogs of any size at no extra charge.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Dog bed", "Water bowls", "Treats", "Downtown location"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelpalomar-phoenix.com",
      phone: "(602) 253-6633",
    },
    {
      name: "Aloft Phoenix Airport",
      address: "4450 E Washington St, Phoenix, AZ 85034",
      lat: 33.4470,
      lng: -112.0170,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 40 lbs welcome with no pet fee. Modern, pet-friendly design.",
      maxDogWeight: 40,
      petFee: 0,
      amenities: ["ARF program", "Dog bed", "Toys", "Treats", "Walking area"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(602) 275-6300",
    },
    {
      name: "La Quinta Inn & Suites Phoenix West",
      address: "5121 W Olive Ave, Glendale, AZ 85302",
      lat: 33.4680,
      lng: -112.1650,
      priceRange: "$" as const,
      dogPolicy: "All dogs welcome at no extra charge. No breed or size restrictions.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Grassy area", "Near freeway", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(623) 846-0005",
    },
  ],

  nationalParks: [
    {
      name: "South Mountain Park & Preserve",
      state: "Arizona",
      lat: 33.3480,
      lng: -112.0620,
      dogPolicy: "Leashed dogs welcome on all trails. One of the largest municipal parks in the nation at 16,000 acres.",
      dogTrails: ["National Trail", "Mormon Trail", "Kiwanis Trail", "Desert Classic Trail"],
      restrictions: [
        "Must be on a 6-foot leash at all times",
        "Carry extra water for your dog",
        "Avoid hiking when temperatures exceed 100°F",
      ],
      description:
        "At over 16,000 acres, South Mountain is one of the largest urban parks in North America. The rugged desert trails offer stunning views of the Phoenix skyline and surrounding desert, but summer heat requires careful timing.",
      imageUrl: "",
      website: "https://www.phoenix.gov/parks/trails/locations/south-mountain",
    },
    {
      name: "Tonto National Forest",
      state: "Arizona",
      lat: 33.7300,
      lng: -111.4500,
      dogPolicy: "Dogs welcome on all trails. Leash recommended but voice control accepted on many trails.",
      dogTrails: ["Pine Creek Trail", "Sycamore Creek Trail", "Barnhardt Trail", "Fossil Creek Trail"],
      restrictions: [
        "Leash required in developed recreation areas",
        "Must have water for your dog",
        "Not allowed in some wilderness swimming holes",
      ],
      description:
        "The massive Tonto National Forest east of Phoenix offers desert lakes, mountain streams, and forested highlands. From saguaro-dotted desert to pine forest, the terrain variety is extraordinary for dog adventures.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/tonto",
    },
    {
      name: "Camelback Mountain Echo Canyon",
      state: "Arizona",
      lat: 33.5215,
      lng: -111.9710,
      dogPolicy: "Leashed dogs allowed on both summit trails. A challenging urban hike with spectacular views.",
      dogTrails: ["Echo Canyon Trail", "Cholla Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Extremely strenuous - assess your dog's fitness",
        "Banned from trails when temperature exceeds 100°F",
        "Carry at least 1 liter of water per person and dog",
      ],
      description:
        "Camelback Mountain is Phoenix's most iconic hike, rising 2,704 feet above the valley floor. Both trails are steep and challenging, but dogs who are fit hikers are rewarded with panoramic desert views.",
      imageUrl: "",
      website: "https://www.phoenix.gov/parks/trails/locations/camelback-mountain",
    },
  ],

  restaurants: [
    {
      name: "The Vig",
      address: "4041 N 40th St, Phoenix, AZ 85018",
      lat: 33.4900,
      lng: -111.9960,
      cuisine: "New American",
      priceRange: "$$" as const,
      dogPolicy: "Extremely dog-friendly with a large outdoor patio and yard. Water bowls and dog treats available.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thevig.us",
    },
    {
      name: "Postino WineCafe",
      address: "3939 E Campbell Ave, Phoenix, AZ 85018",
      lat: 33.5050,
      lng: -111.9980,
      cuisine: "Wine Bar & Bistro",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio. Famous bruschetta boards and wine in a lively atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.postinowinecafe.com",
    },
    {
      name: "The Parlor Pizzeria",
      address: "1916 E Camelback Rd, Phoenix, AZ 85016",
      lat: 33.5095,
      lng: -112.0340,
      cuisine: "Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor patio. Wood-fired Neapolitan pizza.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.theparlor.us",
    },
    {
      name: "Chelsea's Kitchen",
      address: "5040 N 40th St, Phoenix, AZ 85018",
      lat: 33.5000,
      lng: -111.9960,
      cuisine: "Southwest American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the beautiful garden patio. Upscale casual dining along the canal.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.chelseaskitchenaz.com",
    },
    {
      name: "Los Taquitos",
      address: "2620 N 35th Ave, Phoenix, AZ 85009",
      lat: 33.4650,
      lng: -112.1230,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Authentic Mexican street food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.lostaquitos.com",
    },
  ],

  cafes: [
    {
      name: "Lux Central",
      address: "4402 N Central Ave, Phoenix, AZ 85012",
      lat: 33.4960,
      lng: -112.0740,
      dogPolicy: "Dogs welcome on the spacious outdoor patio. A Phoenix coffee institution since 2004.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.luxcoffee.com",
    },
    {
      name: "Cartel Coffee Lab",
      address: "225 W University Dr, Tempe, AZ 85281",
      lat: 33.4220,
      lng: -111.9430,
      dogPolicy: "Leashed dogs welcome on the patio. Award-winning specialty coffee roasters.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cartelcoffeelab.com",
    },
    {
      name: "Press Coffee Roasters",
      address: "1616 N Central Ave, Phoenix, AZ 85004",
      lat: 33.4620,
      lng: -112.0740,
      dogPolicy: "Outdoor seating welcomes dogs. Phoenix-based specialty coffee roasters.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.presscoffee.com",
    },
    {
      name: "Be Coffee Roasters",
      address: "4712 N Central Ave, Phoenix, AZ 85012",
      lat: 33.4990,
      lng: -112.0740,
      dogPolicy: "Dogs welcome at outdoor tables. Micro-roastery with a focus on quality.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.becoffeeroasters.com",
    },
  ],

  dogParks: [
    {
      name: "Steele Indian School Dog Park",
      address: "300 E Indian School Rd, Phoenix, AZ 85012",
      lat: 33.4950,
      lng: -112.0700,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water fountains", "Shade ramadas", "Waste stations", "Lights for evening"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A popular central Phoenix dog park with evening lighting for cooler after-dark play during hot months. Separate areas for large and small dogs with good shade coverage.",
    },
    {
      name: "PETsMART Dog Park at Washington Park",
      address: "6655 N 23rd Ave, Phoenix, AZ 85015",
      lat: 33.5240,
      lng: -112.0970,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Splash pad", "Shade structures", "Water fountains", "Agility equipment", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "One of Phoenix's best dog parks featuring a splash pad for hot days, agility equipment, and excellent shade. The water features make summer visits manageable for dogs.",
    },
    {
      name: "Papago Park",
      address: "625 N Galvin Pkwy, Phoenix, AZ 85008",
      lat: 33.4570,
      lng: -111.9480,
      offLeash: false,
      fenced: false,
      acres: 1200.0,
      amenities: ["Desert trails", "Hole in the Rock landmark", "Lagoons", "Picnic areas", "Botanical garden nearby"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A 1,200-acre desert park with iconic red sandstone buttes and the famous Hole in the Rock formation. Leashed dogs enjoy the easy desert trails, and the lagoons provide a scenic backdrop.",
    },
    {
      name: "Rose Mofford Dog Park",
      address: "9833 N 25th Ave, Phoenix, AZ 85021",
      lat: 33.5600,
      lng: -112.0950,
      offLeash: true,
      fenced: true,
      acres: 4.0,
      amenities: ["Large open area", "Water stations", "Shade trees", "Benches", "Waste stations", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A spacious north Phoenix dog park with mature shade trees that provide critical relief from the desert sun. The large fenced area gives dogs plenty of room to stretch their legs.",
    },
  ],
};
