export const portTownsendData = {
  city: {
    name: "Port Townsend",
    state: "Washington",
    region: "Pacific Northwest",
    lat: 48.1170,
    lng: -122.7604,
    dogFriendlinessScore: 8,
    description:
      "Port Townsend is a Victorian seaport town on the Olympic Peninsula where dogs are treated like royalty. With miles of beach walks, Fort Worden's expansive grounds, and a walkable downtown full of dog-friendly shops and cafes, this maritime gem is a four-paw destination. The dramatic views of the Cascade and Olympic mountain ranges are an added bonus.",
    heroImage: "https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=1200&fit=crop",
    climate: "Oceanic marine",
    population: 9999,
  },

  hotels: [
    {
      name: "The Bishop Hotel",
      address: "714 Washington St, Port Townsend, WA 98368",
      lat: 48.1170,
      lng: -122.7570,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select pet-friendly rooms. Boutique hotel in a 1890s building in the heart of downtown.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Dog bed", "Water bowls", "Treat at check-in", "Walking map", "Beach access nearby"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bishophotel.com",
      phone: "(360) 385-6122",
    },
    {
      name: "Fort Worden State Park Lodging",
      address: "200 Battery Way, Port Townsend, WA 98368",
      lat: 48.1340,
      lng: -122.7650,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select vacation houses and NCO quarters. Expansive grounds for off-leash exploration.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Fenced yards in some units", "Beach access", "Miles of trails", "Historic grounds", "Water bowls"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.parks.wa.gov/fortworden",
      phone: "(360) 344-4434",
    },
    {
      name: "Tides Inn & Suites",
      address: "1807 Water St, Port Townsend, WA 98368",
      lat: 48.1148,
      lng: -122.7490,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome with a small pet fee. Waterfront location with easy beach access.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Waterfront walking", "Pet waste stations", "Grassy areas", "Beach access"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.tidesinnpt.com",
      phone: "(360) 385-0595",
    },
    {
      name: "The Swan Hotel",
      address: "222 Monroe St, Port Townsend, WA 98368",
      lat: 48.1175,
      lng: -122.7580,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in cottage suites with private entrances. Charming Victorian property with garden grounds.",
      maxDogWeight: 60,
      petFee: 45,
      amenities: ["Private entrance", "Garden area", "Dog bed", "Treats", "Walking distance to downtown"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.theswanhotel.com",
      phone: "(360) 385-1718",
    },
  ],

  nationalParks: [
    {
      name: "Olympic National Park",
      state: "Washington",
      lat: 47.8021,
      lng: -123.6044,
      dogPolicy: "Dogs are NOT allowed on any trails in Olympic National Park. They are permitted in parking areas, campgrounds, and on paved roads only.",
      dogTrails: ["Rialto Beach to Ellen Creek (leashed)", "Kalaloch Beach (leashed)"],
      restrictions: [
        "No dogs on any hiking trails",
        "Must be on leash (6 ft max) at all times",
        "Allowed only in parking areas, campgrounds, and on roads",
        "Limited beach access in leashed areas only",
      ],
      description:
        "While Olympic National Park is famously restrictive for dogs, the nearby beaches at Rialto and Kalaloch do allow leashed dogs. The park's incredible rainforests, mountains, and coastline are worth seeing, but plan dog-friendly activities outside park boundaries.",
      imageUrl: "",
      website: "https://www.nps.gov/olym",
    },
    {
      name: "Fort Worden State Park",
      state: "Washington",
      lat: 48.1340,
      lng: -122.7650,
      dogPolicy: "Leashed dogs welcome throughout the park including beaches, trails, and historic battery areas.",
      dogTrails: ["Beach Walk Trail", "Artillery Hill Loop", "Chinese Gardens Trail", "North Beach Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed in buildings or museum interiors",
        "Clean up after your pet",
      ],
      description:
        "This 434-acre former military base offers beaches, forested trails, historic gun batteries, and stunning views. Dogs love exploring the bunkers and running on the driftwood-strewn beaches. A must-visit for any dog visiting Port Townsend.",
      imageUrl: "",
      website: "https://www.parks.wa.gov/fortworden",
    },
    {
      name: "Fort Flagler State Park",
      state: "Washington",
      lat: 48.0910,
      lng: -122.7020,
      dogPolicy: "Leashed dogs welcome on all trails and beach areas. A quieter alternative to Fort Worden.",
      dogTrails: ["Bluff Trail", "Beach Loop", "Forest Trail", "Marrowstone Point Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed in buildings",
        "Clean up after your pet",
      ],
      description:
        "Located on nearby Marrowstone Island, this peaceful state park features miles of beach, forested bluffs, and historic military installations. Less crowded than Fort Worden, it offers a serene experience for dogs and their owners.",
      imageUrl: "",
      website: "https://www.parks.wa.gov/flagler",
    },
  ],

  restaurants: [
    {
      name: "Alchemy Bistro & Wine Bar",
      address: "842 Washington St, Port Townsend, WA 98368",
      lat: 48.1172,
      lng: -122.7560,
      cuisine: "Pacific Northwest",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the heated outdoor patio. Farm-to-table Northwest cuisine with an extensive wine list.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.alchemybistroandwinebar.com",
    },
    {
      name: "Finistere",
      address: "1025 Water St, Port Townsend, WA 98368",
      lat: 48.1165,
      lng: -122.7545,
      cuisine: "Seafood & Mediterranean",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the waterfront deck. Fresh local seafood with Mediterranean influences.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.finistererestaurant.com",
    },
    {
      name: "Doc's Marina Grill",
      address: "141 Hudson St, Port Townsend, WA 98368",
      lat: 48.1155,
      lng: -122.7600,
      cuisine: "Seafood & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio overlooking the marina. Casual waterfront dining with great fish and chips.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.docsmarina.com",
    },
    {
      name: "Pourhouse",
      address: "2231 Washington St, Port Townsend, WA 98368",
      lat: 48.1185,
      lng: -122.7520,
      cuisine: "Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio with a relaxed atmosphere. Craft cocktails and elevated pub fare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.pourhousept.com",
    },
    {
      name: "Hanazono Asian Noodle",
      address: "225 Taylor St, Port Townsend, WA 98368",
      lat: 48.1168,
      lng: -122.7575,
      cuisine: "Asian Noodles",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor sidewalk tables. Authentic hand-pulled noodles and Asian comfort food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hanazononoodle.com",
    },
  ],

  cafes: [
    {
      name: "Better Living Through Coffee",
      address: "106 Tyler St, Port Townsend, WA 98368",
      lat: 48.1173,
      lng: -122.7585,
      dogPolicy: "Dogs welcome on the patio. Community-focused coffee shop with locally roasted beans.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bltcoffee.com",
    },
    {
      name: "Velocity Coffee",
      address: "929 Water St, Port Townsend, WA 98368",
      lat: 48.1163,
      lng: -122.7550,
      dogPolicy: "Dog-friendly outdoor seating on the waterfront side. Specialty coffee and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.velocitycoffeept.com",
    },
    {
      name: "Sunrise Coffee",
      address: "308 10th St, Port Townsend, WA 98368",
      lat: 48.1180,
      lng: -122.7560,
      dogPolicy: "Outdoor patio welcomes dogs. Cozy uptown coffee spot with homemade baked goods.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.sunrisecoffeept.com",
    },
    {
      name: "Aldrich's Market & Cafe",
      address: "940 Lawrence St, Port Townsend, WA 98368",
      lat: 48.1178,
      lng: -122.7548,
      dogPolicy: "Leashed dogs welcome in the outdoor seating area. Gourmet market and cafe with local products.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.aldrichs.com",
    },
  ],

  dogParks: [
    {
      name: "Port Townsend Dog Park at Chetzemoka",
      address: "Jackson St & Blaine St, Port Townsend, WA 98368",
      lat: 48.1210,
      lng: -122.7530,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Separate small dog area", "Water station", "Benches", "Waste bags", "Shade trees"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Port Townsend's dedicated off-leash dog park near Chetzemoka Park. Fully fenced with separate areas and ocean views. A great spot for pups to socialize and burn off energy.",
    },
    {
      name: "Fort Worden Beach",
      address: "200 Battery Way, Port Townsend, WA 98368",
      lat: 48.1360,
      lng: -122.7680,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Beach access", "Driftwood", "Tidal pools", "Mountain views", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A spectacular beach at Fort Worden State Park with views of the Cascades and Admiralty Inlet. Leashed dogs love exploring the driftwood, tide pools, and sandy stretches along this stunning shoreline.",
    },
    {
      name: "Chetzemoka Park",
      address: "Jackson & Blaine St, Port Townsend, WA 98368",
      lat: 48.1215,
      lng: -122.7525,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Beach access", "Gardens", "Picnic area", "Playground", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A charming city park with manicured gardens, a gazebo, and beach access. Leashed dogs enjoy the paths through the gardens and the small beach area. Named after a S'Klallam chief.",
    },
    {
      name: "North Beach County Park",
      address: "San Juan Ave, Port Townsend, WA 98368",
      lat: 48.1380,
      lng: -122.7720,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Sandy beach", "Driftwood shelters", "Tidal exploration", "Parking", "Restrooms"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A long sandy beach north of Fort Worden with sweeping views of the Strait of Juan de Fuca. Leashed dogs love the wide open beach walks and the chance to chase waves along this quiet stretch of coastline.",
    },
  ],
};
