export const portsmouthData = {
  city: {
    name: "Portsmouth",
    state: "New Hampshire",
    region: "Northeast",
    lat: 43.0718,
    lng: -70.7626,
    dogFriendlinessScore: 8,
    description:
      "This charming New England seaport town welcomes dogs with open arms across its historic downtown, waterfront parks, and nearby beaches. Portsmouth's walkable brick streets, craft breweries, and dog-friendly restaurant patios make it an ideal weekend getaway for you and your pup.",
    heroImage: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 22006,
  },
  hotels: [
    {
      name: "Ale House Inn",
      address: "121 Bow St, Portsmouth, NH 03801",
      lat: 43.0765,
      lng: -70.7582,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique hotel in a converted brewery welcoming dogs with a $50 per stay fee. Waterfront location on the Piscataqua River.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Waterfront location", "Converted brewery", "Downtown walkability", "River views"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.alehouseinn.com",
      phone: "(603) 431-7760",
    },
    {
      name: "The Hotel Portsmouth",
      address: "40 Court St, Portsmouth, NH 03801",
      lat: 43.0766,
      lng: -70.7612,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with a $40 per night fee. Central location steps from Market Square.",
      maxDogWeight: 75,
      petFee: 40,
      amenities: ["Market Square location", "Rooftop deck", "Free bikes", "Walking maps"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thehotelportsmouth.com",
      phone: "(603) 433-1200",
    },
    {
      name: "Hampton Inn Portsmouth Central",
      address: "99 Durgin Ln, Portsmouth, NH 03801",
      lat: 43.0634,
      lng: -70.7714,
      priceRange: "$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a $50 non-refundable fee. Free breakfast and pet relief area.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Free breakfast", "Pet relief area", "Indoor pool", "Near downtown"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.hilton.com",
      phone: "(603) 431-6111",
    },
    {
      name: "Martin Hill Inn",
      address: "404 Islington St, Portsmouth, NH 03801",
      lat: 43.0729,
      lng: -70.7685,
      priceRange: "$$" as const,
      dogPolicy: "Charming B&B welcoming well-behaved dogs in select rooms with a $30 per night fee. Garden grounds for morning walks.",
      maxDogWeight: 40,
      petFee: 30,
      amenities: ["Garden grounds", "Full breakfast", "Historic property", "Walking distance to downtown"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.martinhillinn.com",
      phone: "(603) 436-2287",
    },
  ],
  nationalParks: [
    {
      name: "Odiorne Point State Park",
      state: "New Hampshire",
      lat: 43.0437,
      lng: -70.7172,
      dogPolicy: "Leashed dogs welcome on all trails and along the rocky coastline. New Hampshire's largest undeveloped stretch of coast.",
      dogTrails: ["Oceanside Trail", "Frost Point Trail", "Salt Marsh Trail", "Battery Seaman Trail"],
      restrictions: ["Leash required", "No dogs on Wallis Sands Beach", "Clean up required"],
      description:
        "A 135-acre coastal park where forest meets the Atlantic Ocean. Trails wind through maritime forest, past WWII bunker ruins, along rocky tide pools, and through salt marshes. Your dog will love exploring the diverse coastal terrain, and the tide pools are endlessly fascinating for curious noses.",
      imageUrl: "",
      website: "https://www.nhstateparks.org/visit/state-parks/odiorne-point-state-park",
    },
    {
      name: "Great Bay National Wildlife Refuge",
      state: "New Hampshire",
      lat: 43.0744,
      lng: -70.8633,
      dogPolicy: "Leashed dogs welcome on designated trails. A vast estuarine preserve with diverse wildlife viewing.",
      dogTrails: ["Ferry Way Trail", "Upper Peverly Pond Trail", "Depot Road Trail"],
      restrictions: ["Leash required at all times", "Stay on designated trails", "No dogs during waterfowl hunting season"],
      description:
        "Over 1,000 acres of tidal estuary, salt marsh, and upland forest on the shores of Great Bay. The trails offer views across the bay to distant church steeples and forested shores. Your leashed dog will encounter an incredible variety of scents from the salt marsh and forest habitats.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/great-bay",
    },
    {
      name: "Blue Job Mountain State Forest",
      state: "New Hampshire",
      lat: 43.3267,
      lng: -71.0214,
      dogPolicy: "Dogs welcome on leash. A short but rewarding hike to a fire tower with panoramic views.",
      dogTrails: ["Blue Job Mountain Summit Trail", "Crown Point Road Trail"],
      restrictions: ["Leash recommended", "Hunting in season", "Clean up required"],
      description:
        "About 45 minutes from Portsmouth, this quick summit hike rewards with 360-degree views from a historic fire tower. The trail is short enough for any dog to manage, and the summit meadow is a wonderful spot to rest and take in views stretching from the White Mountains to the ocean.",
      imageUrl: "",
      website: "https://www.nhstateparks.org",
    },
  ],
  restaurants: [
    {
      name: "The Friendly Toast",
      address: "113 Congress St, Portsmouth, NH 03801",
      lat: 43.0767,
      lng: -70.7596,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Funky breakfast spot with outdoor seating. Dogs welcome at sidewalk tables on Congress Street.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thefriendlytoast.net",
    },
    {
      name: "Earth Eagle Brewings",
      address: "175 High St, Portsmouth, NH 03801",
      lat: 43.0767,
      lng: -70.7555,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly brewery specializing in gruits (herbal ales). Covered outdoor area welcomes leashed pups.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.eartheaglebrewings.com",
    },
    {
      name: "Street 360",
      address: "801 Islington St, Portsmouth, NH 03801",
      lat: 43.0712,
      lng: -70.7744,
      cuisine: "Asian Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Outdoor patio with string lights welcomes leashed dogs. Creative Asian-inspired cuisine with craft cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.street360portsmouth.com",
    },
    {
      name: "Cure",
      address: "189 State St, Portsmouth, NH 03801",
      lat: 43.0779,
      lng: -70.758,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Upscale Italian with seasonal sidewalk dining. Leashed dogs welcome outside. House-made charcuterie and pasta.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.curerestaurantportsmouth.com",
    },
    {
      name: "Row 34",
      address: "5 Portwalk Pl, Portsmouth, NH 03801",
      lat: 43.0765,
      lng: -70.756,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Modern seafood restaurant with a dog-friendly waterfront patio. Fresh oysters and craft beer with river views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.row34.com",
    },
  ],
  cafes: [
    {
      name: "Breaking New Grounds",
      address: "14 Market Square, Portsmouth, NH 03801",
      lat: 43.0771,
      lng: -70.7592,
      dogPolicy: "Portsmouth's iconic coffee shop in Market Square. Outdoor tables are prime dog-watching territory in the heart of downtown.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.breakingnewgrounds.com",
    },
    {
      name: "Cafe Kilim",
      address: "163 Islington St, Portsmouth, NH 03801",
      lat: 43.075,
      lng: -70.766,
      dogPolicy: "Turkish-inspired cafe with a garden patio. Dogs welcome in the outdoor courtyard with Mediterranean vibes.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Popovers on the Square",
      address: "8 Congress St, Portsmouth, NH 03801",
      lat: 43.0772,
      lng: -70.7596,
      dogPolicy: "Famous for their popovers. Outdoor seating overlooks Market Square. Dogs welcome at patio tables.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.popoversonthesquare.com",
    },
    {
      name: "A&E Coffee Roastery",
      address: "65 Market St, Portsmouth, NH 03801",
      lat: 43.0769,
      lng: -70.759,
      dogPolicy: "Local micro-roaster with a cozy outdoor seating area. Dogs are regulars at this neighborhood coffee spot.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "South Mill Pond Dog Park",
      address: "Junkins Ave, Portsmouth, NH 03801",
      lat: 43.0738,
      lng: -70.7571,
      offLeash: true,
      fenced: true,
      acres: 0.5,
      amenities: ["Fully fenced", "Water access", "Benches", "Downtown location", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Portsmouth's central off-leash dog park sits beside South Mill Pond with water views. The fenced area is conveniently located within walking distance of downtown shops and restaurants, making it easy to combine a dog park visit with a stroll through the historic district.",
    },
    {
      name: "Leary Field Dog Park",
      address: "Leary Field, Portsmouth, NH 03801",
      lat: 43.0669,
      lng: -70.7734,
      offLeash: true,
      fenced: true,
      acres: 1.0,
      amenities: ["Large fenced area", "Open field", "Water fountain", "Benches", "Shade"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A spacious fenced dog park with plenty of room for running and playing fetch. The open field is well-maintained and the community is welcoming. Located slightly outside the downtown core, it tends to be less crowded than the South Mill Pond park.",
    },
    {
      name: "Prescott Park Waterfront",
      address: "105 Marcy St, Portsmouth, NH 03801",
      lat: 43.0751,
      lng: -70.7554,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Waterfront paths", "Gardens", "Harbor views", "Benches", "Events lawn"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A beautiful waterfront park along the Piscataqua River with formal gardens, walking paths, and views of tugboats and the harbor. Leashed dogs are welcome throughout this beloved public space. The gardens are stunning in summer and the riverfront promenade is a year-round dog walking favorite.",
    },
    {
      name: "New Castle Great Common",
      address: "Great Common, New Castle, NH 03854",
      lat: 43.0598,
      lng: -70.7239,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Ocean views", "Walking paths", "Historic fort nearby", "Parking", "Coastal access"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Just over the bridge from Portsmouth, this common on New Castle island offers ocean views, sea breezes, and the adjacent Fort Constitution historic site. Walk your leashed dog along coastal paths with views of lighthouses and the Isles of Shoals on the horizon.",
    },
  ],
};
