export const portlandData = {
  city: {
    name: "Portland",
    state: "Oregon",
    region: "Pacific Northwest",
    lat: 45.5152,
    lng: -122.6784,
    dogFriendlinessScore: 9,
    description:
      "Portland doesn't just tolerate dogs — it celebrates them. With more off-leash parks per capita than almost any US city, dog-friendly breweries on every corner, and a culture that genuinely believes dogs belong everywhere, PDX is a canine utopia. From misty forest hikes in Forest Park to splashing in the Willamette, your pup will fit right into the City of Roses.",
    heroImage: "https://images.unsplash.com/photo-1507245338956-18b5b4a1b433?w=1200&fit=crop",
    climate: "Oceanic",
    population: 652503,
  },
  hotels: [
    {
      name: "Kimpton Hotel Monaco Portland",
      address: "506 SW Washington St, Portland, OR 97204",
      lat: 45.5199,
      lng: -122.6764,
      priceRange: "$$$" as const,
      dogPolicy: "All pets welcome, no size or breed restrictions, no pet fee",
      maxDogWeight: 0,
      petFee: 0,
      amenities: [
        "Dog bed",
        "Food and water bowls",
        "Welcome treats",
        "Evening wine hour (for humans)",
        "Pet concierge",
      ],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.monaco-portland.com",
      phone: "(503) 222-0001",
    },
    {
      name: "Jupiter Hotel",
      address: "800 E Burnside St, Portland, OR 97214",
      lat: 45.5229,
      lng: -122.6564,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome, max 2 per room",
      maxDogWeight: 0,
      petFee: 30,
      amenities: [
        "Dog bed",
        "Treats at check-in",
        "Adjacent bar with dog-friendly patio",
      ],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.jupiterhotel.com",
      phone: "(503) 230-9200",
    },
    {
      name: "Canopy by Hilton Portland Pearl District",
      address: "425 NW 9th Ave, Portland, OR 97209",
      lat: 45.5249,
      lng: -122.6803,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome, 2 pets max",
      maxDogWeight: 75,
      petFee: 50,
      amenities: [
        "Dog bed",
        "Welcome kit",
        "Nearby park walking maps",
        "Pet relief station",
      ],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hilton.com/canopy-portland",
      phone: "(503) 235-0200",
    },
    {
      name: "The Heathman Hotel",
      address: "1001 SW Broadway, Portland, OR 97205",
      lat: 45.5173,
      lng: -122.6814,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome, quiet breeds preferred",
      maxDogWeight: 50,
      petFee: 75,
      amenities: [
        "Luxury dog bed",
        "Organic treats",
        "Dog walking service",
        "Pet-sitting referrals",
      ],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.heathmanhotel.com",
      phone: "(503) 241-4100",
    },
    {
      name: "Basecamp Brewing Hotel",
      address: "200 NW 21st Ave, Portland, OR 97209",
      lat: 45.5243,
      lng: -122.6942,
      priceRange: "$$" as const,
      dogPolicy: "All dogs welcome — this is Portland after all",
      maxDogWeight: 0,
      petFee: 25,
      amenities: [
        "Dog bandana at check-in",
        "Treats",
        "Outdoor lounge access",
        "Trail guide recommendations",
      ],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.basecampbrewinghotel.com",
      phone: "(503) 223-0505",
    },
  ],
  nationalParks: [
    {
      name: "Columbia River Gorge National Scenic Area",
      state: "Oregon",
      lat: 45.7117,
      lng: -121.5196,
      dogPolicy: "Dogs allowed on most trails on leash",
      dogTrails: [
        "Latourell Falls Trail",
        "Horsetail Falls Trail",
        "Catherine Creek Trail",
        "Beacon Rock Trail",
      ],
      restrictions: [
        "Must be on 6-foot leash",
        "Not allowed in Eagle Creek Trail",
        "Clean up after pet",
      ],
      description:
        "A jaw-dropping 80-mile gorge carved by the Columbia River with cascading waterfalls at every turn. Dogs can join you on many trails for misty waterfall views and dramatic basalt cliff scenery.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/crgnsa",
    },
    {
      name: "Mount Rainier National Park",
      state: "Washington",
      lat: 46.8523,
      lng: -121.7603,
      dogPolicy: "Dogs allowed in parking areas, campgrounds, and paved roads only",
      dogTrails: ["Westside Road (paved sections)", "Ohanapecosh Campground Trail"],
      restrictions: [
        "Must be on 6-foot leash",
        "Not allowed on any trails beyond pavement",
        "Not allowed in wilderness areas",
        "Cannot be left unattended",
      ],
      description:
        "The iconic volcanic peak towering over the Pacific Northwest. While trail access is limited for dogs, the scenic drives and campground walks still deliver breathtaking alpine meadow views.",
      imageUrl: "",
      website: "https://www.nps.gov/mora",
    },
    {
      name: "Crater Lake National Park",
      state: "Oregon",
      lat: 42.8684,
      lng: -122.1685,
      dogPolicy:
        "Dogs allowed in developed areas, parking lots, and along paved Rim Village paths",
      dogTrails: ["Rim Village Promenade", "Lady of the Woods Trail"],
      restrictions: [
        "Must be on 6-foot leash",
        "Not allowed on backcountry trails",
        "Not allowed below the rim",
        "Must stay on paved surfaces",
      ],
      description:
        "America's deepest lake fills an ancient volcanic crater with impossibly blue water. While dogs can't hike the backcountry, the Rim Village paths offer spectacular views of the sapphire lake that will leave both you and your pup speechless.",
      imageUrl: "",
      website: "https://www.nps.gov/crla",
    },
    {
      name: "Forest Park",
      state: "Oregon",
      lat: 45.5561,
      lng: -122.7634,
      dogPolicy: "Dogs welcome on all trails on leash",
      dogTrails: [
        "Wildwood Trail",
        "Leif Erikson Drive",
        "Firelane 1",
        "Maple Trail",
        "Balch Creek Trail",
      ],
      restrictions: [
        "Must be on leash",
        "Clean up after pet",
        "Stay on designated trails",
      ],
      description:
        "One of the largest urban forests in the United States, with over 80 miles of trails winding through towering Douglas fir and western red cedar. Your dog can explore misty old-growth groves just minutes from downtown Portland.",
      imageUrl: "",
      website: "https://www.portland.gov/parks/forest-park",
    },
  ],
  restaurants: [
    {
      name: "Tin Shed Garden Café",
      address: "1438 NE Alberta St, Portland, OR 97211",
      lat: 45.5589,
      lng: -122.6512,
      cuisine: "American Brunch",
      priceRange: "$$" as const,
      dogPolicy:
        "Dogs welcome on the garden patio — dedicated dog menu available",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.tinshedgardencafe.com",
    },
    {
      name: "Lucky Labrador Brew Pub",
      address: "915 SE Hawthorne Blvd, Portland, OR 97214",
      lat: 45.5118,
      lng: -122.6544,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy:
        "Legendarily dog-friendly — dogs welcome inside and on the patio",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.luckylab.com",
    },
    {
      name: "Bark City BBQ",
      address: "2155 NE Martin Luther King Jr Blvd, Portland, OR 97212",
      lat: 45.5366,
      lng: -122.6619,
      cuisine: "BBQ",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on patio, water bowls provided",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Pok Pok",
      address: "3226 SE Division St, Portland, OR 97202",
      lat: 45.5046,
      lng: -122.6332,
      cuisine: "Thai",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the covered outdoor drinking area",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.pokpokpdx.com",
    },
    {
      name: "The Goodfoot Lounge & Kitchen",
      address: "2845 SE Stark St, Portland, OR 97214",
      lat: 45.5193,
      lng: -122.6369,
      cuisine: "American Comfort",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on outdoor patio during daytime hours",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Lardo",
      address: "1205 SW Washington St, Portland, OR 97205",
      lat: 45.5199,
      lng: -122.6848,
      cuisine: "Sandwiches",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the sidewalk patio",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.lardopdx.com",
    },
    {
      name: "Screen Door",
      address: "2337 E Burnside St, Portland, OR 97214",
      lat: 45.5229,
      lng: -122.6413,
      cuisine: "Southern Brunch",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on outdoor patio, leash required",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.screendoorrestaurant.com",
    },
    {
      name: "Oven & Shaker",
      address: "1134 NW Everett St, Portland, OR 97209",
      lat: 45.5244,
      lng: -122.6824,
      cuisine: "Pizza & Cocktails",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor tables",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ovenandshaker.com",
    },
  ],
  cafes: [
    {
      name: "Never Coffee",
      address: "4243 SE Belmont St, Portland, OR 97215",
      lat: 45.5159,
      lng: -122.6239,
      dogPolicy: "Outdoor seating is fully dog-friendly, treats behind counter",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.nevercoffeelab.com",
    },
    {
      name: "Coava Coffee Roasters",
      address: "1300 SE Grand Ave, Portland, OR 97214",
      lat: 45.5139,
      lng: -122.6602,
      dogPolicy: "Patio friendly, minimalist vibes extend to well-behaved pups",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.coavacoffee.com",
    },
    {
      name: "Extracto Coffee Roasters",
      address: "2921 NE Killingsworth St, Portland, OR 97211",
      lat: 45.5631,
      lng: -122.6387,
      dogPolicy: "Covered patio with dog tie-ups and water bowls",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.extractocoffeeroasters.com",
    },
    {
      name: "Stumptown Coffee Roasters",
      address: "4525 SE Division St, Portland, OR 97206",
      lat: 45.5046,
      lng: -122.6199,
      dogPolicy: "Patio dogs welcome — Portland's original specialty coffee",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.stumptowncoffee.com",
    },
    {
      name: "Either/Or Café",
      address: "2638 SE Ankeny St, Portland, OR 97214",
      lat: 45.5221,
      lng: -122.6393,
      dogPolicy: "Garden patio is a dog haven with water and shade",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Sellwood Riverfront Park Off-Leash Area",
      address: "SE Spokane St & SE Oaks Park Way, Portland, OR 97202",
      lat: 45.4637,
      lng: -122.6584,
      offLeash: true,
      fenced: false,
      acres: 7.0,
      amenities: [
        "River swimming access",
        "Shade trees",
        "Walking paths",
        "Waste stations",
      ],
      rating: 4.6,
      imageUrl: "",
      description:
        "A lush riverside off-leash area where dogs can swim in the Willamette River, chase through meadows, and explore wooded trails. The gentle river bank makes it perfect for water-loving pups.",
    },
    {
      name: "Chimney Park",
      address: "9360 N Columbia Blvd, Portland, OR 97203",
      lat: 45.5898,
      lng: -122.7372,
      offLeash: true,
      fenced: true,
      acres: 16.0,
      amenities: [
        "Separate small dog area",
        "Agility equipment",
        "Water fountains",
        "Covered pavilion",
        "Benches",
      ],
      rating: 4.7,
      imageUrl: "",
      description:
        "Portland's largest fully fenced off-leash park is a dog's dream — 16 acres of rolling hills, wooded trails, and open meadows. The covered pavilion means rain never stops the fun.",
    },
    {
      name: "Gabriel Park Off-Leash Area",
      address: "SW 45th Ave & SW Vermont St, Portland, OR 97219",
      lat: 45.4723,
      lng: -122.7207,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: [
        "Agility equipment",
        "Water fountains",
        "Shade trees",
        "Double-gated entry",
        "Benches",
      ],
      rating: 4.4,
      imageUrl: "",
      description:
        "A well-maintained fenced dog park in Southwest Portland with agility obstacles and plenty of room to run. The mature trees provide great shade even on Portland's warmest summer days.",
    },
    {
      name: "Normandale Park Off-Leash Area",
      address: "NE 57th Ave & NE Hassalo St, Portland, OR 97213",
      lat: 45.5299,
      lng: -122.6078,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: [
        "Water fountains",
        "Benches",
        "Waste stations",
        "Open play field",
      ],
      rating: 4.3,
      imageUrl: "",
      description:
        "A friendly neighborhood dog park in the Hollywood District with a welcoming community of regulars. The open grassy field is perfect for fetch, and the double-gated entry keeps even the sneakiest escape artists contained.",
    },
    {
      name: "Mt. Tabor Off-Leash Area",
      address: "SE 60th Ave & SE Salmon St, Portland, OR 97215",
      lat: 45.5126,
      lng: -122.5942,
      offLeash: true,
      fenced: false,
      acres: 5.0,
      amenities: [
        "Forested trails",
        "Scenic overlook",
        "Water fountains",
        "Waste stations",
      ],
      rating: 4.6,
      imageUrl: "",
      description:
        "An off-leash area on a dormant volcanic cinder cone with panoramic views of Mount Hood. Dogs can explore forested paths, race up the hillside, and enjoy one of Portland's most iconic viewpoints.",
    },
  ],
};
