export const prescottData = {
  city: {
    name: "Prescott",
    state: "Arizona",
    region: "Southwest",
    lat: 34.54,
    lng: -112.4685,
    dogFriendlinessScore: 7,
    description:
      "Arizona's original capital sits a mile high in the ponderosa pines, serving up a refreshing escape from desert heat that both humans and hounds adore. With a historic Whiskey Row of dog-friendly saloons, a gorgeous town square perfect for people-and-pup watching, and miles of forested trails in the surrounding Prescott National Forest, this cowboy-chic mountain town proves the Southwest isn't all cactus and scorching sand.",
    heroImage: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&fit=crop",
    climate: "Semi-arid",
    population: 45827,
  },
  hotels: [
    {
      name: "Hotel St. Michael",
      address: "205 W Gurley St, Prescott, AZ 86301",
      lat: 34.5403,
      lng: -112.4695,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in pet-designated rooms. Historic downtown hotel overlooking Courthouse Plaza.",
      maxDogWeight: 50,
      petFee: 25,
      amenities: ["Downtown location", "Historic building", "Courthouse Plaza views", "Walking distance to trails"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.stmichaelhotel.com",
      phone: "(928) 776-1999",
    },
    {
      name: "The Grand Highland Hotel",
      address: "154 S Montezuma St, Prescott, AZ 86303",
      lat: 34.5387,
      lng: -112.4688,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique hotel welcoming dogs of all sizes. Dog bed and treats provided. $35 per night pet fee.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Dog bed", "Treats", "Whiskey Row location", "Rooftop patio"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thegrandhighlandhotel.com",
      phone: "(928) 776-0025",
    },
    {
      name: "Residence Inn by Marriott Prescott",
      address: "3599 Lee Cir, Prescott, AZ 86301",
      lat: 34.5523,
      lng: -112.4317,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a $100 non-refundable fee per stay. Grassy areas available on property.",
      maxDogWeight: 0,
      petFee: 100,
      amenities: ["Full kitchens", "Pet relief area", "Complimentary breakfast", "Outdoor pool"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(928) 775-2900",
    },
    {
      name: "SpringHill Suites by Marriott Prescott",
      address: "200 E Sheldon St, Prescott, AZ 86301",
      lat: 34.5416,
      lng: -112.4665,
      priceRange: "$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome. Non-refundable cleaning fee per stay. Close to Courthouse Plaza.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Downtown access", "Waste stations", "Suite-style rooms", "Complimentary breakfast"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(928) 776-0998",
    },
    {
      name: "Forest Villas Hotel",
      address: "3645 Lee Cir, Prescott, AZ 86301",
      lat: 34.553,
      lng: -112.4311,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly rooms available with a $20 per night fee. Surrounded by Prescott National Forest.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Forest setting", "Large property grounds", "Trail access nearby", "Outdoor spa"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.forestvillas.com",
      phone: "(928) 717-1200",
    },
  ],
  nationalParks: [
    {
      name: "Prescott National Forest",
      state: "Arizona",
      lat: 34.55,
      lng: -112.52,
      dogPolicy: "Dogs welcome on all trails and in campgrounds. Must be leashed in developed areas; voice control acceptable on trails.",
      dogTrails: ["Thumb Butte Loop Trail", "Lynx Lake Loop", "Granite Mountain Trail", "Goldwater Lake Trail"],
      restrictions: ["Leash in campgrounds and picnic areas", "Pack out waste", "Respect wildlife"],
      description:
        "Over 1.2 million acres of ponderosa pine forests, granite outcrops, and hidden lakes surround Prescott. The Thumb Butte trail is a local classic with panoramic views, while Lynx Lake offers a gentle shoreline stroll where water-loving pups can wade in. Your dog will think they've died and gone to squirrel-chasing heaven.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/prescott",
    },
    {
      name: "Watson Lake Recreation Area",
      state: "Arizona",
      lat: 34.5559,
      lng: -112.4242,
      dogPolicy: "Dogs allowed on leash on trails around the lake. Not permitted on the swim beach.",
      dogTrails: ["Peavine Trail", "Watson Lake Loop Trail", "Iron King Trail"],
      restrictions: ["Leash required", "No dogs on beach", "No dogs in water at designated swim area"],
      description:
        "Dramatic granite boulders called the Granite Dells frame this stunning lake, creating a landscape that looks like another planet. The Peavine Trail follows an old railroad grade and is wonderfully flat for easy dog-walking, while the boulder-hopping around the lake satisfies more adventurous pups.",
      imageUrl: "",
      website: "https://www.cityofprescott.net",
    },
    {
      name: "Montezuma Castle National Monument",
      state: "Arizona",
      lat: 34.6115,
      lng: -111.8351,
      dogPolicy: "Leashed dogs allowed on the main paved trail to view the cliff dwelling. Not permitted in the monument buildings.",
      dogTrails: ["Main Loop Trail (paved)"],
      restrictions: ["Leash required at all times", "No dogs in buildings", "Stay on paved paths"],
      description:
        "A 5-story, 20-room cliff dwelling built into a limestone alcove by the Sinagua people over 800 years ago. The short paved trail is stroller- and paw-friendly, and your leashed pup can gaze up at the ancient dwelling while you contemplate the ingenuity of early Southwest civilizations.",
      imageUrl: "",
      website: "https://www.nps.gov/moca",
    },
  ],
  restaurants: [
    {
      name: "The Palace Restaurant & Saloon",
      address: "120 S Montezuma St, Prescott, AZ 86303",
      lat: 34.5391,
      lng: -112.4689,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the historic Whiskey Row patio. A saloon experience with Old West flair.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.historicpalace.com",
    },
    {
      name: "Prescott Brewing Company",
      address: "130 W Gurley St, Prescott, AZ 86301",
      lat: 34.5403,
      lng: -112.4698,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Large dog-friendly patio on the plaza. Water bowls and a welcoming atmosphere for four-legged visitors.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.prescottbrewingcompany.com",
    },
    {
      name: "Farm Provisions",
      address: "217 W Gurley St, Prescott, AZ 86301",
      lat: 34.5404,
      lng: -112.4702,
      cuisine: "Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs allowed on the outdoor patio seating. Fresh, locally sourced menu changes seasonally.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "",
    },
    {
      name: "Lazy G Brewhouse",
      address: "110 S Cortez St, Prescott, AZ 86303",
      lat: 34.5391,
      lng: -112.4676,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Pups are welcome on the sunny patio. Dog biscuits available from the bar. Live music on weekends.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "El Gato Azul",
      address: "316 W Goodwin St, Prescott, AZ 86303",
      lat: 34.5413,
      lng: -112.4714,
      cuisine: "Mediterranean",
      priceRange: "$$" as const,
      dogPolicy: "Beautiful garden patio that welcomes well-behaved dogs. Tapas and sangria under the shade trees.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.elgatoazul.com",
    },
    {
      name: "The Raven Cafe",
      address: "142 N Cortez St, Prescott, AZ 86301",
      lat: 34.5411,
      lng: -112.4676,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Courtyard patio is dog-friendly. Live music venue at night; mellow cafe by day.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.theravencafe.com",
    },
    {
      name: "Barley Hound",
      address: "234 S Cortez St, Prescott, AZ 86303",
      lat: 34.5381,
      lng: -112.4675,
      cuisine: "Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Named after a dog — enough said. Outdoor patio welcomes pups with water bowls and treats.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.barleyhound.com",
    },
    {
      name: "Lone Spur Cafe",
      address: "106 W Gurley St, Prescott, AZ 86301",
      lat: 34.5402,
      lng: -112.4692,
      cuisine: "Breakfast",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor tables overlooking Courthouse Plaza. Hearty breakfasts for early hikers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
  ],
  cafes: [
    {
      name: "Wild Iris Coffeehouse",
      address: "124 S Granite St, Prescott, AZ 86303",
      lat: 34.539,
      lng: -112.4706,
      dogPolicy: "Large garden patio perfect for dogs. A local favorite with comfortable seating and homemade pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "",
    },
    {
      name: "Method Coffee Roasters",
      address: "3180 Willow Creek Rd, Prescott, AZ 86301",
      lat: 34.5401,
      lng: -112.4893,
      dogPolicy: "Leashed dogs welcome on the outdoor patio. Specialty roasts and a modern atmosphere.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "Cuppers Coffee House",
      address: "226 S Cortez St, Prescott, AZ 86303",
      lat: 34.5383,
      lng: -112.4676,
      dogPolicy: "Downtown coffee house with outdoor seating. Dogs welcome on the patio with treats available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Granite Mountain Brewing Coffee Bar",
      address: "188 S Montezuma St, Prescott, AZ 86303",
      lat: 34.5384,
      lng: -112.4688,
      dogPolicy: "Brewery and coffee bar with a dog-friendly patio. Espresso in the morning, craft beer in the afternoon.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "The Bean",
      address: "107 N Cortez St, Prescott, AZ 86301",
      lat: 34.5406,
      lng: -112.4677,
      dogPolicy: "Cozy corner cafe on the plaza. Sidewalk seating welcomes leashed dogs and offers prime people-watching.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Willow Creek Dog Park",
      address: "3181 Willow Creek Rd, Prescott, AZ 86301",
      lat: 34.5373,
      lng: -112.49,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water stations", "Shade ramadas", "Benches", "Waste bags", "Agility equipment"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Prescott's premier off-leash park in the ponderosa pines. Separate areas for large and small dogs, agility obstacles for the athletic pups, and enough shade to keep everyone cool even in summer. The mountain air and pine-needle carpet make this feel more like a resort than a dog park.",
    },
    {
      name: "Courthouse Plaza",
      address: "Courthouse Sq, Prescott, AZ 86301",
      lat: 34.5401,
      lng: -112.4689,
      offLeash: false,
      fenced: false,
      acres: 2.0,
      amenities: ["Paved paths", "Benches", "Shade trees", "Water fountains", "Central downtown location"],
      rating: 4.6,
      imageUrl: "",
      description:
        "The heart of Prescott is a beautiful grassy square surrounded by restaurants and shops. While dogs must be leashed, this is the ultimate dog-watching destination — on any given day you'll see more breeds than a Westminster catalog. The Saturday farmers market is especially pup-populated.",
    },
    {
      name: "Thumb Butte Recreation Area",
      address: "Thumb Butte Rd, Prescott, AZ 86303",
      lat: 34.5434,
      lng: -112.4941,
      offLeash: false,
      fenced: false,
      acres: 100.0,
      amenities: ["Hiking trails", "Scenic overlooks", "Picnic areas", "Parking", "Restrooms"],
      rating: 4.7,
      imageUrl: "",
      description:
        "Prescott's iconic thumb-shaped rock formation anchors a trail system that winds through pine and oak forests. The main loop is a moderate climb rewarded with sweeping views of the Bradshaw Mountains. Leashed dogs love the sights, smells, and occasional deer encounter.",
    },
    {
      name: "Heritage Park Dog Run",
      address: "1497 Heritage Park Rd, Prescott, AZ 86301",
      lat: 34.5312,
      lng: -112.4543,
      offLeash: true,
      fenced: true,
      acres: 1.0,
      amenities: ["Fenced area", "Water bowl", "Benches", "Waste bags"],
      rating: 4.0,
      imageUrl: "",
      description:
        "A small but well-maintained fenced dog run in a quiet residential area. Perfect for a quick off-leash session when you don't have time for a full trail adventure. The local regulars are friendly and always happy to see new snouts.",
    },
    {
      name: "Goldwater Lake Trail",
      address: "2900 Goldwater Lake Rd, Prescott, AZ 86303",
      lat: 34.5138,
      lng: -112.4771,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Lakeside trail", "Picnic areas", "Parking", "Restrooms", "Wildlife viewing"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A peaceful 2-mile loop around a pine-rimmed lake south of town. Your leashed pup can enjoy the shoreline trail, sniff for squirrels in the forest, and watch ducks paddle across the calm water. Early mornings often bring deer sightings that will test your pup's restraint.",
    },
  ],
};
