export const provincetownData = {
  city: {
    name: "Provincetown",
    state: "Massachusetts",
    region: "Northeast",
    lat: 42.0584,
    lng: -70.1867,
    dogFriendlinessScore: 9,
    description:
      "At the very tip of Cape Cod's curling fist, Provincetown is a gloriously eccentric, wildly welcoming haven where dogs are treated like royalty. Off-leash beaches stretch for miles within the Cape Cod National Seashore, Commercial Street's shops put out water bowls like welcome mats, and the local whale-watching fleet even lets well-behaved pups aboard. With an artistic spirit, fresh seafood, and more dog-per-capita energy than anywhere in New England, P-town is a 9 out of 10 for a reason.",
    heroImage: "https://images.unsplash.com/photo-1568515045052-f9a854d70bfd?w=1200&fit=crop",
    climate: "Oceanic",
    population: 2942,
  },
  hotels: [
    {
      name: "Salt House Inn",
      address: "6 Conwell St, Provincetown, MA 02657",
      lat: 42.0545,
      lng: -70.1841,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome with no size restrictions or breed limits. $50 per stay fee includes a dog bed and treat bag.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Treat bag", "Garden courtyard", "Walking distance to beach", "Outdoor shower for sandy paws"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.salthouseinn.com",
      phone: "(508) 487-6436",
    },
    {
      name: "Eben House",
      address: "90 Bradford St, Provincetown, MA 02657",
      lat: 42.055,
      lng: -70.1886,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique inn that enthusiastically welcomes dogs. No pet fee. Dog bowls and blankets provided.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Dog blankets", "Water bowls", "Garden", "Close to Commercial Street"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.ebenhouse.com",
      phone: "(508) 487-0386",
    },
    {
      name: "Carpe Diem Guesthouse & Spa",
      address: "12 Johnson St, Provincetown, MA 02657",
      lat: 42.0536,
      lng: -70.1854,
      priceRange: "$$$" as const,
      dogPolicy: "Pet-friendly rooms available. Dogs under 40 lbs welcome with a $40 per night fee. Spa services for stressed-out humans.",
      maxDogWeight: 40,
      petFee: 40,
      amenities: ["Spa", "Garden", "Wine & cheese hour", "Dog-friendly rooms", "Central location"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.carpediemguesthouse.com",
      phone: "(508) 487-4242",
    },
    {
      name: "Surfside Hotel & Suites",
      address: "543 Commercial St, Provincetown, MA 02657",
      lat: 42.0513,
      lng: -70.1815,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly waterfront hotel. Dogs welcome with a $35 per night fee. Direct beach access.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Beach access", "Waterfront rooms", "Pet relief area", "Parking", "Private balconies"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.surfsideinn.cc",
      phone: "(508) 487-1726",
    },
    {
      name: "Seaglass Inn & Spa",
      address: "166 Commercial St, Provincetown, MA 02657",
      lat: 42.0572,
      lng: -70.1912,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select rooms. $50 fee per stay. Walking path to West End beaches.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Heated pool", "Spa", "Pet rooms", "Walking path to beach", "Garden setting"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.seaglassinnptown.com",
      phone: "(508) 487-1233",
    },
  ],
  nationalParks: [
    {
      name: "Cape Cod National Seashore",
      state: "Massachusetts",
      lat: 41.9633,
      lng: -70.0478,
      dogPolicy: "Dogs allowed on leash on most beaches year-round. Off-leash permitted on select beaches from mid-September to mid-June. Not allowed on nature trails or in ponds.",
      dogTrails: ["Herring Cove Beach", "Race Point Beach", "Head of the Meadow Beach", "Great Island Trail"],
      restrictions: ["Leash required in summer on lifeguarded beaches", "No dogs on nature trails", "No dogs in freshwater ponds", "Seasonal shorebird closures"],
      description:
        "Forty miles of pristine sandy beaches, windswept dunes, and dramatic cliffs that belong to every American — and their dog. In the off-season, Herring Cove and Race Point become glorious off-leash playgrounds where dogs sprint along the surf line with pure, unbridled joy. Even in summer, early morning and evening walks offer magical beach time.",
      imageUrl: "",
      website: "https://www.nps.gov/caco",
    },
    {
      name: "Beech Forest Trail",
      state: "Massachusetts",
      lat: 42.0623,
      lng: -70.2014,
      dogPolicy: "Dogs allowed on leash on the paved trail and around the freshwater pond.",
      dogTrails: ["Beech Forest Loop (1 mile)", "Snail Road connector"],
      restrictions: ["Leash required at all times", "No swimming for dogs in the pond", "Stay on paved surfaces"],
      description:
        "A magical one-mile loop through a sunken beech forest that feels like walking through an enchanted woodland. The canopy creates a cathedral of green overhead, and the freshwater pond attracts herons and turtles. Your leashed pup will love the shaded, cool trail even on the hottest Cape Cod days.",
      imageUrl: "",
      website: "https://www.nps.gov/caco",
    },
    {
      name: "Province Lands Visitor Center & Trails",
      state: "Massachusetts",
      lat: 42.0725,
      lng: -70.21,
      dogPolicy: "Dogs allowed on the Province Lands Bike Trail on leash. Not permitted on the nature trail at the visitor center.",
      dogTrails: ["Province Lands Bike Trail (paved, 5.5 miles)"],
      restrictions: ["Leash required", "No dogs on the nature trail at visitor center", "Yield to cyclists on bike trail"],
      description:
        "The Province Lands offer a surreal landscape of shifting sand dunes, scrub pine forests, and cranberry bogs at Cape Cod's outermost tip. The bike trail doubles as a fantastic dog-walking path with rolling terrain and ocean glimpses through the dunes. The visitor center observation deck offers panoramic views.",
      imageUrl: "",
      website: "https://www.nps.gov/caco",
    },
    {
      name: "Pilgrim Monument & Provincetown Museum Grounds",
      state: "Massachusetts",
      lat: 42.0571,
      lng: -70.1876,
      dogPolicy: "Dogs welcome on leash on the grounds surrounding the monument. Not permitted inside the museum.",
      dogTrails: ["Monument grounds path"],
      restrictions: ["Leash required", "No dogs inside museum", "Clean up after your pet"],
      description:
        "The tallest all-granite structure in the US commemorates the Pilgrims' first landing (before Plymouth!). While dogs can't climb the 116 steps inside, the surrounding park grounds offer lovely views of the harbor and town, and the grassy hillside is a popular spot for a scenic rest with your pup.",
      imageUrl: "",
      website: "https://www.pilgrim-monument.org",
    },
  ],
  restaurants: [
    {
      name: "The Canteen",
      address: "225 Commercial St, Provincetown, MA 02657",
      lat: 42.0565,
      lng: -70.19,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Walk-up window with a sprawling outdoor patio. Dogs are everywhere and totally welcome. Water bowls aplenty.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.thecanteenptown.com",
    },
    {
      name: "The Mews Restaurant & Cafe",
      address: "429 Commercial St, Provincetown, MA 02657",
      lat: 42.0532,
      lng: -70.1838,
      cuisine: "American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the waterfront deck. Upscale dining with harbor views and an excellent vodka bar.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.mews.com",
    },
    {
      name: "Lobster Pot",
      address: "321 Commercial St, Provincetown, MA 02657",
      lat: 42.0548,
      lng: -70.1869,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome at the outdoor harborside tables. Iconic P-town landmark since 1979.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ptownlobsterpot.com",
    },
    {
      name: "Provincetown Brewing Co.",
      address: "141 Bradford St, Provincetown, MA 02657",
      lat: 42.0548,
      lng: -70.1893,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Super dog-friendly beer garden with water bowls, treats, and a 'dog of the day' photo board.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.provincetownbrewingco.com",
    },
    {
      name: "Joon Bar",
      address: "350 Bradford St, Provincetown, MA 02657",
      lat: 42.0546,
      lng: -70.1856,
      cuisine: "Mediterranean",
      priceRange: "$$$" as const,
      dogPolicy: "Garden patio welcomes dogs. Small plates and natural wines in a beautifully landscaped setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "",
    },
    {
      name: "Far Land on the Beach",
      address: "Herring Cove Beach, Provincetown, MA 02657",
      lat: 42.0424,
      lng: -70.2107,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Beachside eatery where sandy paws are practically required. Dogs welcome at all outdoor seating.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.farlandprovincetown.com",
    },
    {
      name: "Sal's Place",
      address: "99 Commercial St, Provincetown, MA 02657",
      lat: 42.0587,
      lng: -70.1933,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Romantic waterfront patio. Leashed dogs welcome outside while you enjoy house-made pasta and harbor sunsets.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.salsplaceptown.com",
    },
    {
      name: "Liz's Cafe Anybody's Bar",
      address: "315 Commercial St, Provincetown, MA 02657",
      lat: 42.055,
      lng: -70.187,
      cuisine: "Breakfast",
      priceRange: "$" as const,
      dogPolicy: "Sidewalk tables are prime dog-watching territory. Cash only, legendary omelets, zero pretension.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
  ],
  cafes: [
    {
      name: "Kohi Coffee Company",
      address: "199 Commercial St, Provincetown, MA 02657",
      lat: 42.0568,
      lng: -70.1906,
      dogPolicy: "Outdoor seating on Commercial Street. Dogs welcome and the people-watching is unbeatable.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "",
    },
    {
      name: "Joe Coffee & Cafe",
      address: "170 Commercial St, Provincetown, MA 02657",
      lat: 42.0571,
      lng: -70.1911,
      dogPolicy: "Walk-up counter with outdoor benches. Dogs welcome. A reliable coffee stop on the West End.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Wired Puppy",
      address: "379 Commercial St, Provincetown, MA 02657",
      lat: 42.0539,
      lng: -70.1852,
      dogPolicy: "With a name like Wired Puppy, you know dogs are welcome. Patio seating, dog treats, and espresso drinks.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.wiredpuppy.com",
    },
    {
      name: "Connie's Bakery",
      address: "291 Commercial St, Provincetown, MA 02657",
      lat: 42.0555,
      lng: -70.1879,
      dogPolicy: "Grab a pastry and sit outside with your pup. Dogs are a common and beloved sight at the sidewalk tables.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Purple Feather Cafe & Treatery",
      address: "334 Commercial St, Provincetown, MA 02657",
      lat: 42.0546,
      lng: -70.1865,
      dogPolicy: "Dessert cafe with outdoor seating. Your dog can join you for gelato (theirs will be a water bowl).",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Herring Cove Beach Off-Leash Area",
      address: "Province Lands Rd, Provincetown, MA 02657",
      lat: 42.0424,
      lng: -70.2107,
      offLeash: true,
      fenced: false,
      acres: 30.0,
      amenities: ["Beach access", "Ocean swimming", "Sunset views", "Parking", "Waste bags", "Rinse stations"],
      rating: 4.9,
      imageUrl: "",
      description:
        "The crown jewel of dog beaches. In the off-season, this becomes an enormous off-leash playground where dogs gallop through the surf, dig craters in the sand, and socialize with a rotating cast of fellow four-legged beachgoers. The sunsets here are legendary — made even better by a happy, sandy dog at your side.",
    },
    {
      name: "Race Point Beach",
      address: "Race Point Rd, Provincetown, MA 02657",
      lat: 42.0737,
      lng: -70.2183,
      offLeash: true,
      fenced: false,
      acres: 25.0,
      amenities: ["Open ocean beach", "Sand dunes", "Whale watching from shore", "Parking", "Restrooms"],
      rating: 4.8,
      imageUrl: "",
      description:
        "Wild, windswept, and facing the open Atlantic, Race Point feels like the edge of the world. Off-leash dogs run with the wind while waves crash dramatically. You might spot whales from shore, and your dog will certainly spot every seagull within a mile radius.",
    },
    {
      name: "Pilgrim Bark Park",
      address: "Shank Painter Rd, Provincetown, MA 02657",
      lat: 42.0522,
      lng: -70.194,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Water fountain", "Benches", "Waste bags", "Shade", "Agility obstacles"],
      rating: 4.5,
      imageUrl: "",
      description:
        "P-town's dedicated off-leash dog park is a social hub where locals and visitors mix over shared love of dogs. The fenced area gives nervous pup parents peace of mind, while the agility obstacles give energetic dogs something to conquer between beach trips.",
    },
    {
      name: "Long Point Beach Walk",
      address: "Long Point, Provincetown, MA 02657",
      lat: 42.0331,
      lng: -70.1688,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Lighthouse", "Harbor views", "Secluded beach", "Wildlife viewing"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A walk along the breakwater (or a water taxi ride) leads to the remote Long Point lighthouse and a gloriously secluded beach. Leashed dogs love the adventure of crossing to this sandy spit, and the sense of isolation makes it feel like your own private island.",
    },
    {
      name: "Snail Road Conservation Area",
      address: "Snail Rd, Provincetown, MA 02657",
      lat: 42.0605,
      lng: -70.1998,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Sandy trails", "Dune views", "Quiet setting", "Wildlife habitat"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A quiet sandy path through dunes and scrub forest connecting the town to Beech Forest. Leashed dogs enjoy the pine-scented trails and soft sandy footing. It feels wonderfully remote despite being just minutes from Commercial Street's bustle.",
    },
  ],
};
