export const raleighData = {
  city: {
    name: "Raleigh",
    state: "North Carolina",
    region: "Southeast",
    lat: 35.7796,
    lng: -78.6382,
    dogFriendlinessScore: 8,
    description:
      "The City of Oaks earns its dog-friendly reputation with an incredible greenway trail system, numerous off-leash dog parks, and a booming brewery scene that welcomes pups. Raleigh's combination of Southern hospitality and progressive urban culture means your dog will feel at home everywhere.",
    heroImage: "https://images.unsplash.com/photo-1587502536575-6dfba0a6e017?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 467665,
  },
  hotels: [
    {
      name: "The Umstead Hotel and Spa",
      address: "100 Woodland Pond Dr, Cary, NC 27513",
      lat: 35.8098,
      lng: -78.7646,
      priceRange: "$$$$" as const,
      dogPolicy: "Five-star resort welcoming dogs under 40 lbs with a $150 per stay fee. Set on 12 acres with walking trails.",
      maxDogWeight: 40,
      petFee: 150,
      amenities: ["12-acre property", "Walking trails", "Spa", "Fine dining", "Luxury pet amenities"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.theumstead.com",
      phone: "(919) 447-4000",
    },
    {
      name: "Aloft Raleigh Downtown",
      address: "111 Hampton Inn Ct, Raleigh, NC 27603",
      lat: 35.7762,
      lng: -78.645,
      priceRange: "$$" as const,
      dogPolicy: "Arf program welcomes dogs of any size at no extra charge. Walking distance to downtown and Dix Park.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Downtown location", "Near Dix Park", "Pool", "Pet treats"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(919) 828-9900",
    },
    {
      name: "The StateView Hotel",
      address: "2451 Alumni Dr, Raleigh, NC 27606",
      lat: 35.7859,
      lng: -78.6702,
      priceRange: "$$$" as const,
      dogPolicy: "NC State-adjacent hotel welcoming dogs with a $50 per stay fee. Lake Raleigh views and campus trails.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Lake views", "Near NC State", "Trail access", "Restaurant", "Pool"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thestateviewhotel.com",
      phone: "(919) 627-4200",
    },
    {
      name: "Origin Hotel Raleigh",
      address: "911 Hillsborough St, Raleigh, NC 27603",
      lat: 35.7843,
      lng: -78.6515,
      priceRange: "$$$" as const,
      dogPolicy: "Nature-inspired boutique hotel welcoming dogs with a $75 per stay fee. Walking distance to Warehouse District.",
      maxDogWeight: 75,
      petFee: 75,
      amenities: ["Nature-inspired design", "Warehouse District", "Bike rentals", "Restaurant", "Pet amenities"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.originhotel.com",
      phone: "(984) 261-6400",
    },
  ],
  nationalParks: [
    {
      name: "William B. Umstead State Park",
      state: "North Carolina",
      lat: 35.8695,
      lng: -78.7504,
      dogPolicy: "Leashed dogs welcome on all trails. Over 5,000 acres of forest and lake within the city limits.",
      dogTrails: ["Company Mill Trail", "Sycamore Trail", "Sal's Branch Trail", "Loblolly Trail"],
      restrictions: ["Leash required at all times", "No dogs in lake swimming areas", "Clean up required"],
      description:
        "A 5,599-acre oasis of Piedmont forest, streams, and lakes right within the Triangle metro area. The trail system ranges from easy creek-side walks to challenging ridge climbs. Big Lake and Sycamore Lake offer scenic destinations, and the forest is thick enough to make you forget you're in a major metro.",
      imageUrl: "",
      website: "https://www.ncparks.gov/william-b-umstead-state-park",
    },
    {
      name: "Falls Lake State Recreation Area",
      state: "North Carolina",
      lat: 36.0249,
      lng: -78.6891,
      dogPolicy: "Leashed dogs welcome on all trails and in campground areas. A massive reservoir with miles of shoreline trails.",
      dogTrails: ["Falls Lake Trail", "Mountains-to-Sea Trail Section", "Shinleaf Peninsula Trail", "Holly Point Trail"],
      restrictions: ["Leash required", "No dogs on designated swim beaches", "Clean up required"],
      description:
        "A 12,000-acre lake just north of Raleigh with over 26 miles of hiking trails, including a section of the Mountains-to-Sea Trail. The shoreline trails wind through hardwood forest with frequent lake overlooks and beach access points. Your dog can cool off at quiet coves while you take in the views.",
      imageUrl: "",
      website: "https://www.ncparks.gov/falls-lake-state-recreation-area",
    },
    {
      name: "Neuse River Trail",
      state: "North Carolina",
      lat: 35.7567,
      lng: -78.5472,
      dogPolicy: "Leashed dogs welcome on the entire 28-mile paved greenway. Raleigh's longest trail.",
      dogTrails: ["Neuse River Trail (28 miles paved)", "Falls of Neuse Connection", "Anderson Point Section"],
      restrictions: ["Leash required", "Yield to cyclists", "Clean up required"],
      description:
        "A 28-mile paved greenway following the Neuse River from Falls Lake to the Johnston County line. The trail passes through diverse habitats including river bluffs, bottomland forest, and wetlands. It's flat, well-maintained, and one of the best long-distance urban dog walks in the Southeast.",
      imageUrl: "",
      website: "https://www.raleighnc.gov/parks",
    },
  ],
  restaurants: [
    {
      name: "Trophy Brewing & Pizza",
      address: "827 W Morgan St, Raleigh, NC 27603",
      lat: 35.7795,
      lng: -78.6489,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Award-winning Raleigh brewery with a dog-friendly patio. House-brewed beers and wood-fired pizza.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.trophybrewing.com",
    },
    {
      name: "Beasley's Chicken + Honey",
      address: "237 S Wilmington St, Raleigh, NC 27601",
      lat: 35.7754,
      lng: -78.6371,
      cuisine: "Southern",
      priceRange: "$$" as const,
      dogPolicy: "Ashley Christensen's fried chicken spot with outdoor seating. Dogs welcome on the patio. Southern comfort at its finest.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ac-restaurants.com/beasleys",
    },
    {
      name: "Brewery Bhavana",
      address: "218 S Blount St, Raleigh, NC 27601",
      lat: 35.7742,
      lng: -78.635,
      cuisine: "Asian",
      priceRange: "$$" as const,
      dogPolicy: "Brewery, bookstore, flower shop, and dim sum restaurant. Dog-friendly outdoor area. One of Raleigh's most unique venues.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.brewerybhavana.com",
    },
    {
      name: "Transfer Co. Food Hall",
      address: "500 E Davie St, Raleigh, NC 27601",
      lat: 35.7733,
      lng: -78.6313,
      cuisine: "Food Hall",
      priceRange: "$$" as const,
      dogPolicy: "Vibrant food hall with dog-friendly outdoor spaces. Multiple local food vendors and community events.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.transfercofoodhall.com",
    },
    {
      name: "Wye Hill Kitchen & Brewing",
      address: "201 S Boylan Ave, Raleigh, NC 27603",
      lat: 35.7769,
      lng: -78.6467,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Brewery with Raleigh skyline views from the patio. Dogs welcome outdoors. Great food and house-brewed beers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.wyehill.com",
    },
  ],
  cafes: [
    {
      name: "Jubala Village Coffee",
      address: "3103 Hillsborough St, Raleigh, NC 27607",
      lat: 35.7873,
      lng: -78.6704,
      dogPolicy: "Neighborhood coffee shop near NC State with a dog-friendly patio. Known for their espresso and breakfast sandwiches.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.jubala.com",
    },
    {
      name: "Heirloom Brewshop",
      address: "219 Fayetteville St, Raleigh, NC 27601",
      lat: 35.7767,
      lng: -78.6389,
      dogPolicy: "AAPI-owned coffee and cocktail bar with outdoor seating on Fayetteville Street. Dogs welcome on the patio.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.heirloombrewshop.com",
    },
    {
      name: "Sir Walter Coffee",
      address: "8 W Hargett St, Raleigh, NC 27601",
      lat: 35.779,
      lng: -78.6393,
      dogPolicy: "Downtown coffee shop with outdoor seating. Dogs welcome at sidewalk tables. Quality espresso and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.sirwaltercoffee.com",
    },
    {
      name: "Yellow Dog Bread Company",
      address: "2828 Wake Forest Rd, Raleigh, NC 27609",
      lat: 35.8142,
      lng: -78.6226,
      dogPolicy: "Aptly named bakery-cafe with a patio. Dogs welcome outside (of course). Fresh-baked bread and coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.yellowdogbread.com",
    },
  ],
  dogParks: [
    {
      name: "Dix Park Dog Park",
      address: "101 Blair Dr, Raleigh, NC 27603",
      lat: 35.7706,
      lng: -78.6536,
      offLeash: true,
      fenced: true,
      acres: 4.0,
      amenities: ["Separate small dog area", "Water fountains", "Skyline views", "Large open space", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Raleigh's newest and most impressive dog park sits within the 308-acre Dorothea Dix Park with panoramic downtown skyline views. The large fenced area has separate sections for big and small dogs, and the surrounding park offers miles of additional walking paths through rolling meadows and tree-lined drives.",
    },
    {
      name: "Millbrook Exchange Dog Park",
      address: "1905 Spring Forest Rd, Raleigh, NC 27615",
      lat: 35.8488,
      lng: -78.6303,
      offLeash: true,
      fenced: true,
      acres: 3.5,
      amenities: ["Fenced", "Separate small dog area", "Water stations", "Shade trees", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "One of Raleigh's largest and most popular off-leash dog parks with separate areas for large and small dogs. The park features good shade coverage, water stations, and a friendly community. The adjacent tennis and sports complex means there's always activity nearby.",
    },
    {
      name: "Oakwood Dog Park",
      address: "910 Brookside Dr, Raleigh, NC 27604",
      lat: 35.7907,
      lng: -78.6304,
      offLeash: true,
      fenced: true,
      acres: 1.0,
      amenities: ["Fenced", "Near historic Oakwood", "Water fountain", "Benches", "Community events"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A neighborhood dog park in the historic Oakwood district with a loyal community of regulars. The fenced area is well-maintained and the location near Raleigh's most beautiful historic neighborhood makes for excellent before-and-after leashed walks past Victorian homes.",
    },
    {
      name: "Lake Johnson Park Trail",
      address: "4601 Avent Ferry Rd, Raleigh, NC 27606",
      lat: 35.7522,
      lng: -78.7058,
      offLeash: false,
      fenced: false,
      acres: 50.0,
      amenities: ["Lake loop trail", "Fishing pier", "Nature trails", "Boat rentals", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A beautiful 150-acre lake with a 3-mile paved loop trail and additional natural surface trails through surrounding forest. Your leashed dog can enjoy waterfront walking, bridge crossings, and wooded paths. The trail is popular but spacious enough to never feel crowded.",
    },
  ],
};
