export const rapidCityData = {
  city: {
    name: "Rapid City",
    state: "South Dakota",
    region: "Mountain West",
    lat: 44.0805,
    lng: -103.2310,
    dogFriendlinessScore: 6,
    description:
      "Rapid City is the gateway to the Black Hills and Mount Rushmore, offering a unique blend of Western history and natural beauty for dogs. While national parks restrict dog access, the surrounding Black Hills National Forest provides excellent trails, and the growing downtown has dog-friendly patios and breweries.",
    heroImage: "https://images.unsplash.com/photo-1517164850305-99a3e65bb47e?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 77503,
  },

  hotels: [
    {
      name: "Hotel Alex Johnson",
      address: "523 6th St, Rapid City, SD 57701",
      lat: 44.0805,
      lng: -103.2290,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a pet fee. Historic 1928 landmark hotel downtown.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Walking map", "Near downtown walks", "Treats"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.alexjohnson.com",
      phone: "(605) 342-1210",
    },
    {
      name: "Adoba Hotel Rapid City",
      address: "445 Mt Rushmore Rd, Rapid City, SD 57701",
      lat: 44.0790,
      lng: -103.2310,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a per-night fee. Modern hotel with a great downtown location.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Pet waste stations", "Grassy areas", "Water bowls", "Near walking paths"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.adobahotel.com",
      phone: "(605) 348-8300",
    },
    {
      name: "La Quinta Inn & Suites Rapid City",
      address: "1655 Discovery Cir, Rapid City, SD 57701",
      lat: 44.0730,
      lng: -103.2600,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome at no extra charge. Budget-friendly near Black Hills attractions.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Pet waste stations", "Grassy areas", "Near hiking trails", "Water bowls"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta",
      phone: "(605) 718-7600",
    },
    {
      name: "K Bar S Lodge",
      address: "434 Mount Rushmore Rd, Rapid City, SD 57701",
      lat: 44.0792,
      lng: -103.2312,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select rooms with a per-stay fee. Western-themed lodge near downtown.",
      maxDogWeight: 75,
      petFee: 35,
      amenities: ["Dog bed", "Walking distance to creek path", "Pet waste stations", "Water bowls"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.kbarslodge.com",
      phone: "(605) 342-2143",
    },
  ],

  nationalParks: [
    {
      name: "Black Hills National Forest",
      state: "South Dakota",
      lat: 44.0000,
      lng: -103.5000,
      dogPolicy: "Dogs welcome on most trails. Leash required in developed areas; voice control on backcountry trails.",
      dogTrails: ["Centennial Trail", "Flume Trail", "Sunday Gulch Trail", "Cathedral Spires Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on trails",
        "Not allowed in designated swimming areas at Sheridan Lake",
      ],
      description:
        "The Black Hills offer pine-covered mountains, granite spires, and scenic trails perfect for dogs. The Centennial Trail stretches 111 miles through the hills, and numerous shorter trails offer loops through forests, canyons, and meadows.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/blackhills",
    },
    {
      name: "Badlands National Park",
      state: "South Dakota",
      lat: 43.8554,
      lng: -102.3397,
      dogPolicy: "Dogs allowed on paved roads, in parking areas, and in campgrounds only. Not permitted on trails or in the backcountry.",
      dogTrails: ["Roadside pullout walks only"],
      restrictions: [
        "No dogs on any trails",
        "Must be on leash (6 ft max) at all times",
        "Allowed only on paved surfaces and in campgrounds",
        "Not allowed in buildings",
      ],
      description:
        "The dramatic eroded buttes and pinnacles of the Badlands are spectacular from the car and pullouts. While dogs cannot hike the trails, the 31-mile Badlands Loop Road offers numerous viewpoints where leashed dogs can enjoy the scenery.",
      imageUrl: "",
      website: "https://www.nps.gov/badl",
    },
    {
      name: "Custer State Park",
      state: "South Dakota",
      lat: 43.7600,
      lng: -103.4300,
      dogPolicy: "Leashed dogs welcome on most trails and in campgrounds. Excellent wildlife viewing opportunities.",
      dogTrails: ["Sylvan Lake Shore Trail", "Lovers Leap Trail", "Prairie Trail", "Legion Lake Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Keep distance from bison and other wildlife",
        "Not allowed in swim areas",
        "Not allowed in park lodges",
      ],
      description:
        "A 71,000-acre state park with free-roaming bison herds, granite spires, and beautiful lakes. Leashed dogs can hike many trails and enjoy the Wildlife Loop Road. One of the best dog-friendly alternatives to the national parks in the area.",
      imageUrl: "",
      website: "https://gfp.sd.gov/parks/detail/custer-state-park",
    },
  ],

  restaurants: [
    {
      name: "Hay Camp Brewing Company",
      address: "601 Kansas City St, Rapid City, SD 57701",
      lat: 44.0815,
      lng: -103.2260,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Craft brewery with Black Hills-inspired beer.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.haycampbrewing.com",
    },
    {
      name: "Firehouse Brewing Co.",
      address: "610 Main St, Rapid City, SD 57701",
      lat: 44.0808,
      lng: -103.2280,
      cuisine: "Brewpub & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio. South Dakota's first brewpub in a restored 1915 firehouse.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.firehousebrewing.com",
    },
    {
      name: "Tally's Silver Spoon",
      address: "530 6th St, Rapid City, SD 57701",
      lat: 44.0805,
      lng: -103.2295,
      cuisine: "American Fine Dining",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor patio during summer. Upscale dining with regional flavors.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.tallyssilverspoon.com",
    },
    {
      name: "Murphy's Pub & Grill",
      address: "510 9th St, Rapid City, SD 57701",
      lat: 44.0810,
      lng: -103.2250,
      cuisine: "Irish Pub",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Classic Irish pub fare in a friendly atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.murphyspubrc.com",
    },
    {
      name: "Colonial House",
      address: "2501 Mt Rushmore Rd, Rapid City, SD 57701",
      lat: 44.0650,
      lng: -103.2380,
      cuisine: "American Comfort Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the seasonal patio. Family-owned restaurant with generous home cooking.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.colonialhouserc.com",
    },
  ],

  cafes: [
    {
      name: "Harriet & Oak",
      address: "516 7th St, Rapid City, SD 57701",
      lat: 44.0802,
      lng: -103.2290,
      dogPolicy: "Dogs welcome on the outdoor patio. Specialty coffee and craft cocktails in an art deco space.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.harrietandoak.com",
    },
    {
      name: "Pure Bean Coffee",
      address: "507 Main St, Rapid City, SD 57701",
      lat: 44.0808,
      lng: -103.2290,
      dogPolicy: "Outdoor seating welcomes dogs. Locally roasted coffee with a community focus.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.purebeancoffee.com",
    },
    {
      name: "Black Hills Bagels",
      address: "913 Mt Rushmore Rd, Rapid City, SD 57701",
      lat: 44.0780,
      lng: -103.2330,
      dogPolicy: "Dog-friendly outdoor seating area. Fresh bagels and espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.blackhillsbagels.com",
    },
    {
      name: "Dakota Grind Coffee",
      address: "328 St Joseph St, Rapid City, SD 57701",
      lat: 44.0812,
      lng: -103.2275,
      dogPolicy: "Leashed dogs welcome at patio tables. Artisan coffee in the heart of downtown.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.dakotagrind.com",
    },
  ],

  dogParks: [
    {
      name: "Bark Park at Sioux Park",
      address: "West Blvd & Anamosa St, Rapid City, SD 57701",
      lat: 44.0750,
      lng: -103.2400,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water stations", "Agility equipment", "Waste bags", "Benches"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Rapid City's primary off-leash dog park with separate areas for large and small dogs, agility equipment, and well-maintained facilities. Mountain views add to the appeal.",
    },
    {
      name: "Rapid Creek Greenway",
      address: "Rapid Creek, Rapid City, SD 57701",
      lat: 44.0820,
      lng: -103.2300,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Paved bike path", "Creek access", "Benches", "Waste stations", "Multiple access points"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A greenway following Rapid Creek through the city with paved paths, bridges, and creek access. Leashed dogs enjoy the scenic walk past parks, through neighborhoods, and alongside the flowing creek.",
    },
    {
      name: "M Hill Trail",
      address: "Skyline Dr, Rapid City, SD 57701",
      lat: 44.0830,
      lng: -103.2400,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Hiking trails", "City overlooks", "Parking", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A short but rewarding hike up the hill above Rapid City marked with a large M. Leashed dogs enjoy the climb and the panoramic views of the city and Black Hills from the summit.",
    },
    {
      name: "Canyon Lake Park",
      address: "4181 Jackson Blvd, Rapid City, SD 57702",
      lat: 44.0780,
      lng: -103.2500,
      offLeash: false,
      fenced: false,
      acres: 25.0,
      amenities: ["Lake trail", "Picnic areas", "Playground", "Fishing", "Waste stations", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A beautiful park around Canyon Lake with walking paths, mature trees, and lake views. Leashed dogs enjoy the gentle trails and the peaceful setting on the west side of Rapid City.",
    },
  ],
};
