export const redLodgeData = {
  city: {
    name: "Red Lodge",
    state: "Montana",
    region: "Mountain West",
    lat: 45.1858,
    lng: -109.2468,
    dogFriendlinessScore: 7,
    description:
      "Red Lodge is a charming mountain town at the base of the Beartooth Highway, one of America's most scenic drives. Dogs thrive in this former coal mining town with its walkable main street, nearby Custer Gallatin National Forest trails, and easy access to the spectacular Absaroka-Beartooth Wilderness.",
    heroImage: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 2270,
  },

  hotels: [
    {
      name: "The Pollard Hotel",
      address: "2 N Broadway Ave, Red Lodge, MT 59068",
      lat: 45.1860,
      lng: -109.2470,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with advance notice. Historic 1893 hotel on Broadway Avenue.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Treats", "Walking map", "Downtown location", "Near trails"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thepollard.com",
      phone: "(406) 446-0001",
    },
    {
      name: "Rock Creek Resort",
      address: "6380 US-212, Red Lodge, MT 59068",
      lat: 45.1500,
      lng: -109.3100,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in lodge rooms and cabins. Resort set along Rock Creek with mountain views.",
      maxDogWeight: 0,
      petFee: 60,
      amenities: ["Creek access", "Mountain trails", "Dog bed", "Treats", "Expansive grounds"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.rockcreekresort.com",
      phone: "(406) 446-1111",
    },
    {
      name: "Yodeler Motel",
      address: "601 S Broadway Ave, Red Lodge, MT 59068",
      lat: 45.1830,
      lng: -109.2480,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome with a small pet fee. Classic mountain motel with Swiss theming.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Pet waste stations", "Grassy areas", "Near Coal Miners Park", "Water bowls"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.yodelermotel.com",
      phone: "(406) 446-1435",
    },
    {
      name: "Chateau Rouge",
      address: "1505 S Broadway Ave, Red Lodge, MT 59068",
      lat: 45.1790,
      lng: -109.2490,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in pet-friendly rooms. Comfortable lodge south of downtown.",
      maxDogWeight: 75,
      petFee: 25,
      amenities: ["Grassy areas", "Near creek trail", "Water bowls", "Pet waste stations"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.chateaurouge.com",
      phone: "(406) 446-1601",
    },
  ],

  nationalParks: [
    {
      name: "Absaroka-Beartooth Wilderness",
      state: "Montana",
      lat: 45.1000,
      lng: -109.5000,
      dogPolicy: "Dogs welcome off-leash under voice control in the wilderness. Spectacular alpine terrain.",
      dogTrails: ["West Fork Rock Creek Trail", "Glacier Lake Trail", "Basin Creek Lakes Trail", "Timberline Lake Trail"],
      restrictions: [
        "Must be under voice control",
        "Pack out all waste",
        "Be aware of grizzly bears",
        "Bear spray recommended",
      ],
      description:
        "One of the most spectacular wilderness areas in Montana with granite peaks, alpine lakes, and high plateaus above 10,000 feet. Dogs can roam free under voice control in this pristine backcountry paradise.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/custergallatin",
    },
    {
      name: "Custer Gallatin National Forest (Red Lodge District)",
      state: "Montana",
      lat: 45.1500,
      lng: -109.3000,
      dogPolicy: "Dogs welcome on all trails. Leash in campgrounds; voice control on trails.",
      dogTrails: ["West Fork Trail", "Nichols Creek Trail", "Wild Bill Lake Trail", "Basin Creek Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on trails",
        "Be aware of bears",
      ],
      description:
        "The national forest around Red Lodge provides easy access to mountain trails, alpine lakes, and the high country. Many trails begin right at the edge of town, making spontaneous hiking adventures easy.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/custergallatin",
    },
    {
      name: "Beartooth Highway Scenic Drive",
      state: "Montana",
      lat: 45.0000,
      lng: -109.4500,
      dogPolicy: "Leashed dogs welcome at all pullouts and short walks along the highway. The road reaches 10,947 feet.",
      dogTrails: ["Top of the World pullout walks", "Island Lake shoreline", "Beartooth Lake area"],
      restrictions: [
        "Must be on leash at pullouts",
        "Road closed October-May",
        "High altitude - acclimate dogs gradually",
      ],
      description:
        "Called the most beautiful drive in America, the Beartooth Highway climbs to nearly 11,000 feet with views of glaciers, alpine tundra, and 20 peaks over 12,000 feet. Dogs can enjoy the scenery from numerous pullouts and short walks.",
      imageUrl: "",
      website: "https://www.beartoothhighway.com",
    },
  ],

  restaurants: [
    {
      name: "Red Lodge Ales Brewing Company",
      address: "1445 N Broadway Ave, Red Lodge, MT 59068",
      lat: 45.1900,
      lng: -109.2460,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor beer garden. Montana craft beer with pub food.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.redlodgeales.com",
    },
    {
      name: "Cafe Regis",
      address: "501 S Word Ave, Red Lodge, MT 59068",
      lat: 45.1835,
      lng: -109.2450,
      cuisine: "Farm-to-Table Brunch",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the garden patio. Beloved farm-to-table breakfast and lunch spot.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.caferegis.com",
    },
    {
      name: "Bridge Creek Backcountry Kitchen & Wine Bar",
      address: "116 S Broadway Ave, Red Lodge, MT 59068",
      lat: 45.1855,
      lng: -109.2475,
      cuisine: "Pacific Northwest Fine Dining",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor patio. Seasonal fine dining with Montana ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.bridgecreekkitchen.com",
    },
    {
      name: "The Pub at Red Lodge",
      address: "208 N Broadway Ave, Red Lodge, MT 59068",
      lat: 45.1868,
      lng: -109.2468,
      cuisine: "Pub & American",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the patio. Casual pub with burgers, wings, and cold beer.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.thepubatredlodge.com",
    },
    {
      name: "Mas Taco",
      address: "304 N Broadway Ave, Red Lodge, MT 59068",
      lat: 45.1872,
      lng: -109.2465,
      cuisine: "Mexican Street Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Quick tacos after a day on the trails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.mastacoredlodge.com",
    },
  ],

  cafes: [
    {
      name: "Coffee Factory Roasters",
      address: "6 S Broadway Ave, Red Lodge, MT 59068",
      lat: 45.1857,
      lng: -109.2472,
      dogPolicy: "Dogs welcome on the outdoor patio. Local roaster with a following among hikers and skiers.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.coffeefactoryroasters.com",
    },
    {
      name: "Honey's Cafe",
      address: "14 N Broadway Ave, Red Lodge, MT 59068",
      lat: 45.1862,
      lng: -109.2470,
      dogPolicy: "Outdoor seating welcomes dogs. Cozy cafe with breakfast and baked goods.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.honeyscaferedlodge.com",
    },
    {
      name: "Montana Candy Emporium",
      address: "7 S Broadway Ave, Red Lodge, MT 59068",
      lat: 45.1858,
      lng: -109.2473,
      dogPolicy: "Dog-friendly outdoor benches. Candy shop with coffee and fudge on Broadway.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.montanacandy.com",
    },
    {
      name: "Prerogative Kitchen",
      address: "101 S Broadway Ave, Red Lodge, MT 59068",
      lat: 45.1852,
      lng: -109.2475,
      dogPolicy: "Leashed dogs welcome at patio tables. Morning coffee service with pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.prerogativekitchen.com",
    },
  ],

  dogParks: [
    {
      name: "Coal Miners Park",
      address: "S Broadway Ave, Red Lodge, MT 59068",
      lat: 45.1840,
      lng: -109.2480,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Open green space", "Playground", "Picnic areas", "Creek access", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A park in the heart of Red Lodge with open green space and Rock Creek access. Leashed dogs enjoy the spacious grounds and the chance to wade in the creek.",
    },
    {
      name: "Rock Creek Trail",
      address: "Rock Creek Rd, Red Lodge, MT 59068",
      lat: 45.1600,
      lng: -109.2800,
      offLeash: true,
      fenced: false,
      acres: 50.0,
      amenities: ["Mountain trails", "Creek access", "Forest hiking", "Parking", "Waste stations"],
      rating: 4.7,
      imageUrl: "",
      description:
        "Trails along Rock Creek south of Red Lodge into the Beartooth Mountains. Dogs can be off-leash under voice control, enjoying the rushing mountain creek and forested terrain.",
    },
    {
      name: "Lions Park & River Walk",
      address: "N Broadway Ave, Red Lodge, MT 59068",
      lat: 45.1900,
      lng: -109.2450,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Paved path", "Creek access", "Picnic areas", "Playground", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A path following Rock Creek through the north end of Red Lodge. Leashed dogs enjoy the easy creekside walking and the connections to Broadway's shops and restaurants.",
    },
    {
      name: "West Fork Rock Creek Trailhead",
      address: "West Fork Rd, Red Lodge, MT 59068",
      lat: 45.1200,
      lng: -109.3500,
      offLeash: true,
      fenced: false,
      acres: 200.0,
      amenities: ["Alpine trails", "Lake access", "Wilderness entry", "Parking"],
      rating: 4.8,
      imageUrl: "",
      description:
        "The gateway to the Absaroka-Beartooth Wilderness with trails leading to alpine lakes, granite peaks, and high plateaus. Dogs run free under voice control in some of Montana's most spectacular backcountry.",
    },
  ],
};
