export const rehobothBeachData = {
  city: {
    name: "Rehoboth Beach",
    state: "Delaware",
    region: "Northeast",
    lat: 38.7210,
    lng: -75.0760,
    dogFriendlinessScore: 7,
    description:
      "Delaware's favorite beach town is surprisingly dog-friendly with off-season beach access, a charming boardwalk, and nearby state parks. The tax-free shopping on Rehoboth Avenue is a bonus for humans, while dogs enjoy the miles of sandy coastline and Gordon's Pond trail.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 1588,
  },
  hotels: [
    {
      name: "The Bellmoor Inn & Spa",
      address: "6 Christian St, Rehoboth Beach, DE 19971",
      lat: 38.7195,
      lng: -75.0818,
      priceRange: "$$$" as const,
      dogPolicy: "Pet-friendly suites available with a $75 per stay fee. Garden courtyard and pool. Two blocks from the beach.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Garden courtyard", "Pool", "Spa", "Near beach", "Continental breakfast"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thebellmoor.com",
      phone: "(302) 227-5800",
    },
    {
      name: "Avenue Inn & Spa",
      address: "33 Wilmington Ave, Rehoboth Beach, DE 19971",
      lat: 38.7197,
      lng: -75.0792,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in designated rooms with a $50 per stay fee. Walking distance to the boardwalk.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Near boardwalk", "Spa services", "Pet exercise area", "Free parking"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.avenueinn.com",
      phone: "(302) 226-2000",
    },
    {
      name: "Dogfish Inn",
      address: "105 Savannah Rd, Lewes, DE 19958",
      lat: 38.7741,
      lng: -75.1384,
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly boutique inn by Dogfish Head Brewery with a $50 per stay fee. Bikes provided for the ride to the beach.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dogfish Head brewery connection", "Free bikes", "Pet-friendly", "Near Lewes Beach"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.dogfishinn.com",
      phone: "(302) 644-8292",
    },
    {
      name: "Boardwalk Plaza Hotel",
      address: "2 Olive Ave, Rehoboth Beach, DE 19971",
      lat: 38.7174,
      lng: -75.077,
      priceRange: "$$$$" as const,
      dogPolicy: "Oceanfront Victorian hotel welcoming small dogs with a $100 per stay fee. Direct boardwalk and beach access.",
      maxDogWeight: 25,
      petFee: 100,
      amenities: ["Oceanfront", "Boardwalk access", "Victorian charm", "Pool", "Restaurant"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.boardwalkplaza.com",
      phone: "(302) 227-7169",
    },
  ],
  nationalParks: [
    {
      name: "Cape Henlopen State Park",
      state: "Delaware",
      lat: 38.7833,
      lng: -75.0889,
      dogPolicy: "Leashed dogs welcome on trails and beach areas year-round. Off-leash on the beach October through April.",
      dogTrails: ["Gordon's Pond Trail", "Pinelands Trail", "Battery 519 Trail", "Seaside Nature Trail"],
      restrictions: ["Leash required May-September", "Off-leash October-April on beach", "No dogs in swimming areas in season"],
      description:
        "A stunning 5,193-acre park where the Delaware Bay meets the Atlantic Ocean. Gordon's Pond Trail is a paved 3-mile path through pristine dunes with ocean views. During the off-season, the beaches become a dog paradise with off-leash freedom on miles of sand. The WWII observation towers add historic interest.",
      imageUrl: "",
      website: "https://destateparks.com/Beaches/CapeHenlopen",
    },
    {
      name: "Delaware Seashore State Park",
      state: "Delaware",
      lat: 38.6334,
      lng: -75.0624,
      dogPolicy: "Leashed dogs welcome on trails and beach areas. Off-leash on designated beaches during off-season.",
      dogTrails: ["Burton Island Trail", "Bay Shore Trail", "Thompson Island Nature Trail"],
      restrictions: ["Leash required May-September", "Off-leash October-April on beach", "Clean up required"],
      description:
        "Six miles of ocean and bay shoreline south of Rehoboth Beach, this park offers both Atlantic surf and calm bay waters. The Burton Island Trail is a peaceful bayside walk, and the off-season beach access gives dogs miles of sand to explore. The Indian River Inlet is a dramatic spot to watch the tidal currents.",
      imageUrl: "",
      website: "https://destateparks.com/Beaches/DelawareSeashore",
    },
    {
      name: "Prime Hook National Wildlife Refuge",
      state: "Delaware",
      lat: 38.8315,
      lng: -75.2466,
      dogPolicy: "Leashed dogs welcome on designated trails. A vast coastal wetland teeming with migrating birds.",
      dogTrails: ["Boardwalk Trail", "Dike Trail", "Refuge Road Walk"],
      restrictions: ["Leash required", "Stay on designated trails", "No dogs during waterfowl hunting season"],
      description:
        "Over 10,000 acres of saltwater marsh, freshwater wetlands, and forest along the Delaware Bay. The flat trails and boardwalks offer easy walking through incredibly productive wildlife habitat. During migration season, thousands of shorebirds make this a birder's and dog walker's paradise.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/prime-hook",
    },
  ],
  restaurants: [
    {
      name: "Dogfish Head Brewings & Eats",
      address: "320 Rehoboth Ave, Rehoboth Beach, DE 19971",
      lat: 38.7197,
      lng: -75.0842,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "The original Dogfish Head location with a dog-friendly outdoor area. Craft beer and creative pub food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.dogfish.com",
    },
    {
      name: "Henlopen City Oyster House",
      address: "50 Wilmington Ave, Rehoboth Beach, DE 19971",
      lat: 38.7199,
      lng: -75.0789,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Upscale seafood with a dog-friendly patio. Fresh oysters and Chesapeake Bay specialties.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hfrgroup.com",
    },
    {
      name: "The Cultured Pearl",
      address: "301 Rehoboth Ave, Rehoboth Beach, DE 19971",
      lat: 38.7197,
      lng: -75.0838,
      cuisine: "Asian Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Zen garden patio welcomes leashed dogs. Sushi, ramen, and Asian-inspired cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.culturedpearl.us",
    },
    {
      name: "Bluecoast Seafood Grill & Raw Bar",
      address: "30 Wilmington Ave, Rehoboth Beach, DE 19971",
      lat: 38.7196,
      lng: -75.0792,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Seasonal outdoor patio welcomes dogs. Fresh seafood with a sophisticated beach town vibe.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bluecoastrehoboth.com",
    },
    {
      name: "Stingray Sushi Bar & Asian Latino Grill",
      address: "59 Lake Ave, Rehoboth Beach, DE 19971",
      lat: 38.7201,
      lng: -75.081,
      cuisine: "Asian-Latino Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Outdoor seating area welcomes leashed dogs. Creative fusion cuisine in a lively atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
  ],
  cafes: [
    {
      name: "Cafe a-Go-Go",
      address: "33 Baltimore Ave, Rehoboth Beach, DE 19971",
      lat: 38.7176,
      lng: -75.0789,
      dogPolicy: "Colorful beach cafe with outdoor seating. Dogs welcome on the patio. Great smoothies and coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Browseabout Books Coffee Corner",
      address: "133 Rehoboth Ave, Rehoboth Beach, DE 19971",
      lat: 38.7189,
      lng: -75.0804,
      dogPolicy: "Independent bookstore with a coffee corner and outdoor benches. Browse books then enjoy coffee with your pup outside.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.browseaboutbooks.com",
    },
    {
      name: "Taco Reho Coffee Counter",
      address: "3 N 1st St, Rehoboth Beach, DE 19971",
      lat: 38.717,
      lng: -75.0777,
      dogPolicy: "Beach-side coffee counter with outdoor seating near the boardwalk. Dogs welcome at the picnic tables.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
    {
      name: "Notting Hill Coffee",
      address: "26 Baltimore Ave, Rehoboth Beach, DE 19971",
      lat: 38.7177,
      lng: -75.0787,
      dogPolicy: "British-themed coffee shop steps from the boardwalk. Outdoor seating welcomes leashed dogs.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.nottinghillcoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Rehoboth Beach Dog Beach",
      address: "N Boardwalk, Rehoboth Beach, DE 19971",
      lat: 38.724,
      lng: -75.0734,
      offLeash: true,
      fenced: false,
      acres: 5.0,
      amenities: ["Beach access", "Off-leash seasonal", "Ocean swimming", "Open sand", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "During the off-season (October through April), dogs can run off-leash on the wide sandy beach north of the boardwalk. The broad beach, gentle surf, and fellow dog lovers create a perfect canine playground. In summer, dogs are welcome before 9:30am and after 5:30pm.",
    },
    {
      name: "Gordon's Pond Trail",
      address: "Cape Henlopen State Park, Rehoboth Beach, DE 19971",
      lat: 38.7413,
      lng: -75.0795,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Paved trail", "Ocean views", "Dune landscapes", "Bird watching", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A spectacular 3-mile paved trail through pristine coastal dunes between the ocean and Gordon's Pond. Your leashed dog will love the salt air and sand while you enjoy views of both the Atlantic and the freshwater pond. Migrating hawks soar overhead in autumn.",
    },
    {
      name: "Lake Gerar Park",
      address: "Lake Dr, Rehoboth Beach, DE 19971",
      lat: 38.7219,
      lng: -75.0821,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["Lake loop trail", "Benches", "Bird watching", "Shade trees", "Near downtown"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A pleasant loop walk around Silver Lake in downtown Rehoboth Beach. Your leashed dog can enjoy the lakeside path while watching swans and ducks. The lake connects to the downtown area making it easy to combine a walk with shopping and dining.",
    },
    {
      name: "Lewes Dog Park at Wolfe Neck",
      address: "Wolfe Neck Rd, Lewes, DE 19958",
      lat: 38.7682,
      lng: -75.1247,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced", "Separate small dog area", "Water station", "Shade", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A fenced off-leash dog park near Lewes with separate areas for large and small dogs. A short drive from Rehoboth Beach, it provides a reliable off-leash option when the beach has seasonal restrictions. Well-maintained with a friendly local community.",
    },
  ],
};
