export const renoData = {
  city: {
    name: "Reno",
    state: "Nevada",
    region: "Southwest",
    lat: 39.5296,
    lng: -119.8138,
    dogFriendlinessScore: 7,
    description:
      "Reno sits at the base of the Sierra Nevada with Lake Tahoe just 30 minutes away, offering dogs an extraordinary range of outdoor adventures. The 'Biggest Little City' has reinvented itself with a thriving arts scene, craft brewery district, and miles of riverside trails that dogs love.",
    heroImage: "https://images.unsplash.com/photo-1581373449483-37449f962b6c?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 264165,
  },

  hotels: [
    {
      name: "Whitney Peak Hotel",
      address: "255 N Virginia St, Reno, NV 89501",
      lat: 39.5290,
      lng: -119.8120,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a one-time pet fee. Non-gaming boutique hotel downtown.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Treats", "Indoor climbing wall", "Downtown location"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.whitneypeakhotel.com",
      phone: "(775) 398-5400",
    },
    {
      name: "Renaissance Reno Downtown Hotel",
      address: "1 Lake St S, Reno, NV 89501",
      lat: 39.5270,
      lng: -119.8150,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a non-refundable fee. Upscale Riverwalk District hotel.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Riverwalk access", "Near Truckee River", "Walking maps"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(775) 682-3900",
    },
    {
      name: "La Quinta Inn Reno",
      address: "4001 Market St, Reno, NV 89502",
      lat: 39.4960,
      lng: -119.7820,
      priceRange: "$" as const,
      dogPolicy: "All dogs welcome at no extra charge. No breed or size restrictions.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Grassy area", "Near freeway", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(775) 348-6100",
    },
    {
      name: "Peppermill Resort Spa Casino",
      address: "2707 S Virginia St, Reno, NV 89502",
      lat: 39.4990,
      lng: -119.7960,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 60 lbs welcome in select rooms with a pet fee. Full resort amenities.",
      maxDogWeight: 60,
      petFee: 40,
      amenities: ["Spacious rooms", "Grassy grounds", "Pet walking area", "Near trails"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.peppermillreno.com",
      phone: "(775) 826-2121",
    },
  ],

  nationalParks: [
    {
      name: "Humboldt-Toiyabe National Forest",
      state: "Nevada",
      lat: 39.3200,
      lng: -119.9100,
      dogPolicy: "Dogs welcome on all trails. The largest national forest in the lower 48 states.",
      dogTrails: ["Thomas Creek Trail", "Galena Creek Trail", "Jones Creek Trail", "Mount Rose Trail"],
      restrictions: [
        "Leash required in developed areas",
        "Voice control on backcountry trails",
        "Carry water above timberline",
      ],
      description:
        "The Sierra Nevada mountains south of Reno offer alpine hiking through meadows, forests, and along rushing creeks. The Mount Rose area provides access to trails ranging from gentle creek walks to challenging peak ascents.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/htnf",
    },
    {
      name: "Pyramid Lake",
      state: "Nevada",
      lat: 40.0060,
      lng: -119.5360,
      dogPolicy: "Leashed dogs welcome on the beaches and in camping areas with a tribal recreation permit.",
      dogTrails: ["Beach walks", "Tufa formation trails", "Pyramid Island viewpoint"],
      restrictions: [
        "Must be on leash",
        "Tribal permit required for recreation",
        "No dogs in fishing areas during spawning season",
      ],
      description:
        "A stunning desert lake about 30 minutes north of Reno on the Pyramid Lake Paiute Reservation. The turquoise water, tufa formations, and vast desert setting create an otherworldly experience for dogs and their owners.",
      imageUrl: "",
      website: "https://www.pyramidlake.us",
    },
    {
      name: "Washoe Lake State Park",
      state: "Nevada",
      lat: 39.2570,
      lng: -119.7840,
      dogPolicy: "Leashed dogs welcome on trails and in campgrounds. Desert lake park between Reno and Carson City.",
      dogTrails: ["Deadman Creek Trail", "Wetlands Trail", "Sandy Beach Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on designated swim beach",
        "Watch for wild mustangs",
      ],
      description:
        "Set between the Sierra Nevada and the Virginia Range, this park features a shallow lake, sand dunes, and wetlands. Dogs enjoy the diverse terrain and the chance to spot wild mustangs from a distance.",
      imageUrl: "",
      website: "https://www.parks.nv.gov/parks/washoe-lake",
    },
  ],

  restaurants: [
    {
      name: "Great Basin Brewing Co.",
      address: "846 Victorian Ave, Sparks, NV 89431",
      lat: 39.5340,
      lng: -119.7530,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Nevada's oldest craft brewery with iconic Icky IPA.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.greatbasinbrewingco.com",
    },
    {
      name: "Wild River Grille",
      address: "17 S Virginia St, Reno, NV 89501",
      lat: 39.5270,
      lng: -119.8130,
      cuisine: "American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the Truckee River patio. Scenic riverside dining downtown.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.wildrivergrille.com",
    },
    {
      name: "The Depot Craft Brewery Distillery",
      address: "325 E 4th St, Reno, NV 89512",
      lat: 39.5310,
      lng: -119.8060,
      cuisine: "Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the large outdoor patio. Craft beer, spirits, and food in the Freight House District.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thedepotcraftbrewery.com",
    },
    {
      name: "Campo Reno",
      address: "50 N Sierra St, Reno, NV 89501",
      lat: 39.5280,
      lng: -119.8140,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the patio. Artisan Italian in the Riverwalk District.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.camporeno.com",
    },
    {
      name: "Two Chicks",
      address: "232 W 2nd St, Reno, NV 89501",
      lat: 39.5290,
      lng: -119.8170,
      cuisine: "Breakfast & Brunch",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor sidewalk tables. Popular brunch spot downtown.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.twochicksreno.com",
    },
  ],

  cafes: [
    {
      name: "Hub Coffee Roasters",
      address: "1030 S Virginia St, Reno, NV 89502",
      lat: 39.5190,
      lng: -119.8090,
      dogPolicy: "Dogs welcome on the outdoor patio. Locally roasted specialty coffee in Midtown.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hubcoffeeroasters.com",
    },
    {
      name: "Old World Coffee Lab",
      address: "3516 S Virginia St, Reno, NV 89502",
      lat: 39.4980,
      lng: -119.7970,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Meticulous coffee preparation in a cozy setting.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.oldworldcoffeelab.com",
    },
    {
      name: "Magpie Coffee Roasters",
      address: "100 N Arlington Ave, Reno, NV 89501",
      lat: 39.5290,
      lng: -119.8170,
      dogPolicy: "Dog-friendly patio downtown. Small-batch coffee roasters.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.magpiecoffee.com",
    },
    {
      name: "Purple Bean Coffee",
      address: "1099 S Virginia St, Reno, NV 89502",
      lat: 39.5180,
      lng: -119.8080,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Midtown Reno coffee spot.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.purplebeancoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Whitaker Park Dog Park",
      address: "550 University Terrace, Reno, NV 89503",
      lat: 39.5350,
      lng: -119.8320,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water stations", "Shade trees", "Waste stations", "Benches"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Reno's most popular off-leash park in a central location with separate areas for large and small dogs. The mature shade trees provide welcome relief during the warm high-desert summers.",
    },
    {
      name: "Truckee River Walk",
      address: "Arlington Ave, Reno, NV 89501",
      lat: 39.5265,
      lng: -119.8160,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Paved riverwalk", "River views", "Kayak watching", "Restaurants nearby", "Public art"],
      rating: 4.6,
      imageUrl: "",
      description:
        "The Truckee River Walk runs through downtown Reno along the beautiful Truckee River. Dogs love the riverside path, and the connection to the longer Truckee River Trail extends the walk for miles.",
    },
    {
      name: "Virginia Lake Dog Park",
      address: "1980 Lakeside Dr, Reno, NV 89509",
      lat: 39.5080,
      lng: -119.8030,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Lake views", "Water fountain", "Shade structures", "Waste stations", "Walking path nearby"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A fenced off-leash area adjacent to Virginia Lake with nice views and a walking path around the lake for on-leash strolls. The combination makes it a two-for-one dog outing.",
    },
    {
      name: "Galena Creek Regional Park",
      address: "18350 Mt Rose Hwy, Reno, NV 89511",
      lat: 39.3380,
      lng: -119.8440,
      offLeash: false,
      fenced: false,
      acres: 400.0,
      amenities: ["Mountain trails", "Creek access", "Forest paths", "Visitor center", "Picnic areas"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A regional park in the Sierra foothills south of Reno with forested trails along Galena Creek. Dogs love the mountain terrain, creek wading, and the dramatic elevation change from Reno's desert floor.",
    },
  ],
};
