export const richmondData = {
  city: {
    name: "Richmond",
    state: "Virginia",
    region: "Southeast",
    lat: 37.5407,
    lng: -77.4360,
    dogFriendlinessScore: 7,
    description:
      "Richmond is a city where history meets hip, and dogs are invited to all of it. The James River runs through the heart of town, offering miles of trails, swimming holes, and rocky overlooks that pups adore. The craft brewery scene rivals any in the country, and nearly every taproom has a dog-friendly patio. From the cobblestoned streets of Shockoe Bottom to the murals of the Arts District, Richmond is a tail-wagging adventure where Southern charm meets urban cool.",
    heroImage: "https://images.unsplash.com/photo-1569878698889-7bffa1896872?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 226610,
  },

  hotels: [
    {
      name: "The Graduate Richmond",
      address: "301 W Franklin St, Richmond, VA 23220",
      lat: 37.5480,
      lng: -77.4500,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome at no extra charge. This hip hotel in the Fan District loves pups as much as it loves quirky design.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Bowls", "Treats at front desk", "Near Monroe Park", "Walking map"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.graduatehotels.com/richmond",
      phone: "(804) 644-9871",
    },
    {
      name: "Quirk Hotel",
      address: "201 W Broad St, Richmond, VA 23220",
      lat: 37.5470,
      lng: -77.4440,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 40 lbs welcome in this art-forward boutique hotel. Rooftop bar has stunning city views to share with your pup.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Dog bed", "Artisan treats", "Water bowl", "Rooftop access", "Downtown Arts District location"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.quirkhotels.com/richmond",
      phone: "(804) 340-6040",
    },
    {
      name: "Linden Row Inn",
      address: "100 E Franklin St, Richmond, VA 23219",
      lat: 37.5445,
      lng: -77.4355,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in this historic row house hotel dating to the 1840s. Pet-friendly rooms available in the garden wing with courtyard access.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Garden courtyard", "Historic walking tours nearby", "Water bowls"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.lindenrowinn.com",
      phone: "(804) 783-7000",
    },
    {
      name: "The Jefferson Hotel",
      address: "101 W Franklin St, Richmond, VA 23220",
      lat: 37.5460,
      lng: -77.4405,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs under 25 lbs welcome at this grand Beaux-Arts landmark. Pampered pups receive a bed, bowls, and a taste of Richmond's gilded-age luxury.",
      maxDogWeight: 25,
      petFee: 100,
      amenities: ["Luxury dog bed", "Monogrammed bowls", "Turndown treats", "Grand lobby walks"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.jeffersonhotel.com",
      phone: "(804) 649-4750",
    },
    {
      name: "Kimpton Hotel Monaco Richmond",
      address: "501 E Broad St, Richmond, VA 23219",
      lat: 37.5440,
      lng: -77.4325,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome at no extra charge, Kimpton style. Nightly wine hour in the lobby where your pup can socialize.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Bowls", "Treats", "Nightly hosted wine hour", "Near Capitol Square"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.monaco-richmond.com",
      phone: "(804) 412-6000",
    },
  ],

  nationalParks: [
    {
      name: "Richmond National Battlefield Park",
      state: "Virginia",
      lat: 37.4220,
      lng: -77.3100,
      dogPolicy: "Leashed dogs welcome on all trails throughout the battlefield sites. One of the most dog-friendly NPS units in Virginia.",
      dogTrails: ["Cold Harbor Battlefield Trail", "Gaines' Mill Trail", "Malvern Hill Trail", "Drewry's Bluff Trail"],
      restrictions: [
        "Must be on leash (6 ft max) at all times",
        "Not allowed in visitor center buildings",
        "Owners must clean up after dogs",
      ],
      description:
        "Spanning multiple sites around Richmond, these Civil War battlefields offer peaceful trails through forests and fields where some of the war's most pivotal battles took place. Your leashed pup can explore miles of well-maintained paths while you take in the profound history.",
      imageUrl: "",
      website: "https://www.nps.gov/rich",
    },
    {
      name: "Shenandoah National Park",
      state: "Virginia",
      lat: 38.4755,
      lng: -78.4535,
      dogPolicy: "Leashed dogs allowed on most trails except a few that are posted as no-pets. One of the more dog-friendly national parks with over 480 miles of trails.",
      dogTrails: ["Stony Man Trail", "Dark Hollow Falls", "Bearfence Mountain", "Blackrock Summit"],
      restrictions: [
        "Must be on leash (6 ft max) at all times",
        "Not allowed on Limberlost Trail or some posted trails",
        "Not allowed in buildings or cabins",
        "Not allowed on ranger-led programs",
      ],
      description:
        "About 90 minutes from Richmond, Shenandoah's Skyline Drive and vast trail network open up the Blue Ridge Mountains to you and your dog. Most of the park's trails welcome leashed pups, including routes to stunning waterfalls and panoramic overlooks. The fall foliage is unforgettable.",
      imageUrl: "",
      website: "https://www.nps.gov/shen",
    },
    {
      name: "James River Park System",
      state: "Virginia",
      lat: 37.5320,
      lng: -77.4580,
      dogPolicy: "Leashed dogs welcome throughout the park system. Off-leash swimming allowed at designated river access points where dogs can wade and play in the James River rapids.",
      dogTrails: ["Belle Isle Loop", "Buttermilk Trail", "North Bank Trail", "Pipeline Walk"],
      restrictions: [
        "Dogs must be on leash on trails",
        "Voice control required at river swimming areas",
        "Owners must clean up after dogs",
      ],
      description:
        "Richmond's crown jewel is its James River Park System, stretching over 600 acres along the river through the city. Dogs can hike rocky trails, splash in river pools, and scramble over boulders on Belle Isle. This is the reason Richmond dogs are the happiest city dogs in America.",
      imageUrl: "",
      website: "https://jamesriverpark.org",
    },
  ],

  restaurants: [
    {
      name: "The Veil Brewing Co.",
      address: "1301 Roseneath Rd, Richmond, VA 23230",
      lat: 37.5550,
      lng: -77.4685,
      cuisine: "Brewery & Food Trucks",
      priceRange: "$$" as const,
      dogPolicy: "One of RVA's most iconic breweries with a massive dog-friendly outdoor area. Hazy IPAs and happy dogs are the vibe.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.theveilbrewing.com",
    },
    {
      name: "Perch",
      address: "2918 W Broad St, Richmond, VA 23230",
      lat: 37.5575,
      lng: -77.4752,
      cuisine: "New American Brunch",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the sidewalk patio. Brunch favorites and creative cocktails in the Scott's Addition neighborhood.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.perchrva.com",
    },
    {
      name: "ZZQ Texas Craft Barbeque",
      address: "3201 W Moore St, Richmond, VA 23230",
      lat: 37.5570,
      lng: -77.4780,
      cuisine: "Texas Barbecue",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly outdoor picnic area. Some of the best barbecue on the East Coast, and the smoky aromas will have your pup drooling.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.8,
      imageUrl: "",
      website: "https://www.zzqrva.com",
    },
    {
      name: "Perly's",
      address: "111 E Grace St, Richmond, VA 23219",
      lat: 37.5438,
      lng: -77.4345,
      cuisine: "Jewish Deli",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome at outdoor tables. A classic deli reborn with towering sandwiches and Richmond charm.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.perlysrichmond.com",
    },
    {
      name: "The Answer Brewpub",
      address: "6008 W Broad St, Richmond, VA 23230",
      lat: 37.5890,
      lng: -77.5035,
      cuisine: "Brewpub & Vietnamese",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio at this unique brewery-meets-Vietnamese-restaurant. Pho and sours make an unexpectedly perfect pairing.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.theanswerbrewpub.com",
    },
    {
      name: "Stella's",
      address: "1012 Lafayette St, Richmond, VA 23221",
      lat: 37.5458,
      lng: -77.4600,
      cuisine: "Greek & Mediterranean",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio in the Fan District. Greek-inspired dishes and a lively neighborhood atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.stellasrichmond.com",
    },
    {
      name: "Can Can Brasserie",
      address: "3120 W Cary St, Richmond, VA 23221",
      lat: 37.5505,
      lng: -77.4755,
      cuisine: "French Brasserie",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the Carytown sidewalk patio. Classic French bistro fare in Richmond's favorite shopping district.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cancanbrasserie.com",
    },
    {
      name: "Proper Pie Co.",
      address: "2505 E Broad St, Richmond, VA 23223",
      lat: 37.5340,
      lng: -77.4145,
      cuisine: "British Pies & Pastries",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor window counter. Savory and sweet hand pies that make the perfect trail snack after a James River hike.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.properpieco.com",
    },
  ],

  cafes: [
    {
      name: "Lamplighter Coffee Roasters",
      address: "116 S Addison St, Richmond, VA 23220",
      lat: 37.5465,
      lng: -77.4525,
      dogPolicy: "Dog-friendly front patio on Addison Street. Richmond's beloved third-wave roaster with a loyal dog-owner community.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.lamplightercoffee.com",
    },
    {
      name: "Blanchard's Coffee Roasting Co.",
      address: "4017 MacArthur Ave, Richmond, VA 23227",
      lat: 37.5720,
      lng: -77.4490,
      dogPolicy: "Spacious outdoor area in the Northside neighborhood where dogs are always welcome. A tucked-away gem for serious coffee and relaxed pup hangs.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.blanchardscoffee.com",
    },
    {
      name: "Ironclad Coffee Roasters",
      address: "1805 E Grace St, Richmond, VA 23223",
      lat: 37.5385,
      lng: -77.4210,
      dogPolicy: "Church Hill coffee shop with outdoor seating and skyline views. Dogs welcome on the patio while you enjoy precision-roasted coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ironcladcoffee.com",
    },
    {
      name: "Roastology",
      address: "2960 Hathaway Rd, Richmond, VA 23225",
      lat: 37.5210,
      lng: -77.4755,
      dogPolicy: "Cozy southside cafe with a shady patio perfect for dogs. Specialty lattes and homemade baked goods.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.roastology.com",
    },
    {
      name: "Sugar & Twine",
      address: "2928 W Cary St, Richmond, VA 23221",
      lat: 37.5505,
      lng: -77.4730,
      dogPolicy: "Carytown bakery-cafe with sidewalk seating where dogs can watch the shopping crowds go by. Famous pastries and strong coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sugarandtwine.com",
    },
  ],

  dogParks: [
    {
      name: "Barker Field Dog Park",
      address: "900 N Boulevard, Richmond, VA 23220",
      lat: 37.5590,
      lng: -77.4570,
      offLeash: true,
      fenced: true,
      acres: 4.0,
      amenities: ["Separate small dog area", "Water spigots", "Shade trees", "Benches", "Waste stations", "Ample parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Richmond's most popular off-leash dog park sits in the Byrd Park area with separate spaces for large and small dogs. The mature shade trees keep it comfortable even in Virginia summers, and the friendly regular crowd makes every visit a social event for dogs and humans alike.",
    },
    {
      name: "Belle Isle",
      address: "Belle Isle, James River, Richmond, VA 23225",
      lat: 37.5290,
      lng: -77.4530,
      offLeash: false,
      fenced: false,
      acres: 54.0,
      amenities: ["River swimming", "Hiking trails", "Rocky terrain", "Historical ruins", "Suspension bridge access"],
      rating: 4.8,
      imageUrl: "",
      description:
        "An island paradise in the middle of the James River, accessed by a pedestrian suspension bridge. Leashed dogs can explore Civil War ruins, rocky shorelines, and forested trails. The real magic is watching dogs splash in the river pools on a hot Richmond day.",
    },
    {
      name: "Phideaux Field at Chimborazo Park",
      address: "3215 E Broad St, Richmond, VA 23223",
      lat: 37.5320,
      lng: -77.4100,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "City skyline views", "Waste stations", "Benches", "Water fountain"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Church Hill's beloved off-leash park offers panoramic views of the Richmond skyline and James River valley. The fenced area sits atop historic Chimborazo Hill, and the sunset views from here with your dog are absolutely unbeatable.",
    },
    {
      name: "North Bank Trail",
      address: "North Bank Trail, Richmond, VA 23225",
      lat: 37.5340,
      lng: -77.4650,
      offLeash: false,
      fenced: false,
      acres: 25.0,
      amenities: ["River views", "Rocky trail", "Mountain biking", "Nature setting", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A rugged trail along the north bank of the James River that winds through forest and over rocky outcrops with stunning river views. Leashed dogs love the varied terrain and the chance to watch kayakers navigate the rapids below.",
    },
    {
      name: "Ruff House Dog Park at Bryan Park",
      address: "4308 Hermitage Rd, Richmond, VA 23227",
      lat: 37.5835,
      lng: -77.4530,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Separate small dog area", "Water fountains", "Agility features", "Shade shelters", "Waste stations", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A northside off-leash park within the beautiful Bryan Park complex. After romping in the fenced dog area, leash up and explore the park's azalea gardens and Joseph Bryan Pond. A complete morning outing for Richmond dog lovers.",
    },
  ],
};
