export const ruidosoData = {
  city: {
    name: "Ruidoso",
    state: "New Mexico",
    region: "Southwest",
    lat: 33.3317,
    lng: -105.6731,
    dogFriendlinessScore: 7,
    description:
      "Nestled in the Sacramento Mountains of southern New Mexico, Ruidoso offers cool pine forests and mountain trails that dogs adore. With a laid-back mountain village vibe, dog-friendly patios, and miles of forest paths, it's a refreshing escape from the desert heat below.",
    heroImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&fit=crop",
    climate: "Mountain",
    population: 7791,
  },
  hotels: [
    {
      name: "MCM Elegante Lodge & Suites",
      address: "127 Sierra Blanca Dr, Ruidoso, NM 88345",
      lat: 33.3385,
      lng: -105.6610,
      priceRange: "$$$" as const,
      dogPolicy: "Pet-friendly rooms available with a two-pet maximum. Surrounded by tall pines with easy trail access from the property.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Pet relief area", "Forest trails nearby", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.mcmelegante.com",
      phone: "(575) 258-5500",
    },
    {
      name: "Shadow Mountain Lodge & Cabins",
      address: "107 Main Rd, Ruidoso, NM 88345",
      lat: 33.3350,
      lng: -105.6700,
      priceRange: "$$" as const,
      dogPolicy: "Select pet-friendly cabins nestled in the pines. Dogs love the wooded grounds and nearby creek access.",
      maxDogWeight: 60,
      petFee: 35,
      amenities: ["Fenced cabin yards", "Creek access", "Pet relief area", "Water bowls", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.shadowmountainlodge.com",
      phone: "(575) 257-4886",
    },
    {
      name: "Ruidoso River Resort",
      address: "200 Canyon Rd, Ruidoso, NM 88345",
      lat: 33.3290,
      lng: -105.6755,
      priceRange: "$$$$" as const,
      dogPolicy: "Luxury riverside cabins with pet-friendly options. Dogs enjoy the Rio Ruidoso running through the property.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["River access", "Private decks", "Dog bed", "Treats at check-in", "Waste bags"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.ruidosoriverresort.com",
      phone: "(575) 378-4422",
    },
    {
      name: "Best Western Plus Ruidoso Inn",
      address: "420 Mechem Dr, Ruidoso, NM 88345",
      lat: 33.3420,
      lng: -105.6640,
      priceRange: "$" as const,
      dogPolicy: "Affordable pet-friendly rooms with ground-floor access for easy dog walks. Two pets maximum per room.",
      maxDogWeight: 80,
      petFee: 20,
      amenities: ["Ground-floor rooms", "Pet relief area", "Waste bags", "Water bowls", "Parking"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(575) 257-9535",
    },
  ],
  nationalParks: [
    {
      name: "Lincoln National Forest",
      state: "New Mexico",
      lat: 33.3700,
      lng: -105.7200,
      dogPolicy: "Dogs welcome on all national forest trails on leash or under voice control. Miles of pine-covered mountain trails perfect for hiking with dogs.",
      dogTrails: ["Cedar Creek Trail", "Crest Trail", "South Fork Trail", "Bonito Creek Trail"],
      restrictions: ["Leash or voice control required", "Pack out waste", "Keep away from wildlife", "Hot days require extra water"],
      description: "The Lincoln National Forest surrounds Ruidoso with over a million acres of ponderosa pine, spruce, and fir forests. Dogs can explore countless trails through cool mountain terrain, from gentle creek-side paths to challenging ridge hikes with views of Sierra Blanca Peak.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/lincoln",
    },
    {
      name: "White Sands National Park",
      state: "New Mexico",
      lat: 32.7872,
      lng: -106.3257,
      dogPolicy: "Dogs allowed on the Dune Life Nature Trail and on the Interdune Boardwalk on a leash. Not permitted on backcountry trails.",
      dogTrails: ["Dune Life Nature Trail", "Interdune Boardwalk"],
      restrictions: ["6-foot leash required", "Not allowed on backcountry trails", "Hot sand can burn paws in summer", "Bring plenty of water"],
      description: "About 90 minutes southwest of Ruidoso, White Sands features the world's largest gypsum dune field. Dogs can experience the surreal white landscape on select trails, though the brilliant white sand can be hot in summer afternoons.",
      imageUrl: "",
      website: "https://www.nps.gov/whsa",
    },
    {
      name: "Valley of Fires Recreation Area",
      state: "New Mexico",
      lat: 33.6722,
      lng: -105.9361,
      dogPolicy: "Dogs welcome on the nature trail through the lava flow on a leash. A unique geological experience for adventurous dogs and their owners.",
      dogTrails: ["Malpais Nature Trail"],
      restrictions: ["Leash required", "Sharp lava rock can injure paws", "Stay on trail", "Pack out waste"],
      description: "Located about 45 minutes north of Ruidoso, this recreation area sits atop one of the youngest lava flows in the continental US. The nature trail winds through the dramatic black lava landscape, offering a unique hiking experience unlike anywhere else.",
      imageUrl: "",
      website: "https://www.blm.gov",
    },
  ],
  restaurants: [
    {
      name: "Hall of Flame Burgers",
      address: "2500 Sudderth Dr, Ruidoso, NM 88345",
      lat: 33.3305,
      lng: -105.6680,
      cuisine: "Burgers",
      priceRange: "$" as const,
      dogPolicy: "Casual burger joint with a dog-friendly patio. Dogs get water bowls and plenty of attention from the friendly staff.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hallofflameburgers.com",
    },
    {
      name: "Café Rio",
      address: "2547 Sudderth Dr, Ruidoso, NM 88345",
      lat: 33.3310,
      lng: -105.6670,
      cuisine: "New Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Popular New Mexican restaurant with a tree-shaded patio along the Rio Ruidoso. Dogs welcome on the patio.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.caferioruidoso.com",
    },
    {
      name: "Cornerstone Bakery Café",
      address: "1712 Sudderth Dr, Ruidoso, NM 88345",
      lat: 33.3340,
      lng: -105.6720,
      cuisine: "Bakery & Café",
      priceRange: "$" as const,
      dogPolicy: "Charming bakery with outdoor seating where dogs are welcome. Fresh pastries and breakfast fare in a mountain setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cornerstonebakery.com",
    },
    {
      name: "Tina's Café",
      address: "2811 Sudderth Dr, Ruidoso, NM 88345",
      lat: 33.3295,
      lng: -105.6650,
      cuisine: "New Mexican-American",
      priceRange: "$$" as const,
      dogPolicy: "Family-run restaurant with a seasonal patio that welcomes well-behaved dogs. Known for their green chile dishes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.tinascafe.com",
    },
    {
      name: "Lincoln County Grill",
      address: "2717 Sudderth Dr, Ruidoso, NM 88345",
      lat: 33.3300,
      lng: -105.6660,
      cuisine: "American Grill",
      priceRange: "$$" as const,
      dogPolicy: "Casual grill with a patio overlooking the street. Dogs welcome at outdoor tables with water available on request.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.lincolncountygrill.com",
    },
  ],
  cafes: [
    {
      name: "Sacred Grounds Coffee & Tea House",
      address: "2905 Sudderth Dr, Ruidoso, NM 88345",
      lat: 33.3288,
      lng: -105.6643,
      dogPolicy: "Bohemian coffee house with a pet-friendly garden patio. Dogs get treats and fresh water while owners enjoy craft coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sacredgroundscoffee.com",
    },
    {
      name: "Starbucks Ruidoso",
      address: "1101 Mechem Dr, Ruidoso, NM 88345",
      lat: 33.3480,
      lng: -105.6590,
      dogPolicy: "Standard Starbucks with outdoor patio seating. Dogs welcome at outdoor tables with puppuccinos available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.0,
      imageUrl: "",
      website: "https://www.starbucks.com",
    },
    {
      name: "The Village Buttery",
      address: "2107 Sudderth Dr, Ruidoso, NM 88345",
      lat: 33.3325,
      lng: -105.6695,
      dogPolicy: "Beloved local bakery and café with outdoor bench seating where dogs are welcome. Famous for their cinnamon rolls.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.villagebuttery.com",
    },
    {
      name: "Rio Ruidoso Roasters",
      address: "2200 Sudderth Dr, Ruidoso, NM 88345",
      lat: 33.3320,
      lng: -105.6690,
      dogPolicy: "Local roaster with a small patio where dogs are welcome. Specialty single-origin coffees in a cozy mountain atmosphere.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.rioruidosoroasters.com",
    },
  ],
  dogParks: [
    {
      name: "Ruidoso Dog Park",
      address: "200 Resort Dr, Ruidoso, NM 88345",
      lat: 33.3360,
      lng: -105.6710,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Waste bag stations", "Shade trees"],
      rating: 4.2,
      imageUrl: "",
      description: "A fenced off-leash park set among the pines with separate areas for large and small dogs. The mountain air and natural shade make it comfortable even during summer afternoons.",
    },
    {
      name: "Two Rivers Park",
      address: "100 Two Rivers Rd, Ruidoso, NM 88345",
      lat: 33.3270,
      lng: -105.6780,
      offLeash: false,
      fenced: false,
      acres: 8,
      amenities: ["Walking trails", "River access", "Picnic areas", "Restrooms", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description: "Located at the confluence of two streams, this park offers leashed walking trails through beautiful pine forests. Dogs love wading in the shallow creek waters, especially on warm summer days.",
    },
    {
      name: "Cedar Creek Picnic Area",
      address: "Cedar Creek Rd, Ruidoso, NM 88345",
      lat: 33.3450,
      lng: -105.6850,
      offLeash: false,
      fenced: false,
      acres: 12,
      amenities: ["Hiking trail", "Creek access", "Picnic tables", "Shade", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description: "A forested recreation area with a gentle trail along Cedar Creek. Dogs on leash can enjoy the shaded forest paths and splash in the creek while surrounded by towering ponderosa pines.",
    },
    {
      name: "Grindstone Lake Trail",
      address: "Grindstone Canyon Rd, Ruidoso, NM 88345",
      lat: 33.3180,
      lng: -105.6900,
      offLeash: false,
      fenced: false,
      acres: 35,
      amenities: ["Hiking trails", "Lake views", "Mountain biking trails", "Parking", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "A popular trail system around Grindstone Lake offering stunning mountain views and forested paths. Dogs on leash can enjoy the moderate trails with their owners while taking in views of Sierra Blanca Peak.",
    },
  ],
};
