export const sacramentoData = {
  city: {
    name: "Sacramento",
    state: "California",
    region: "West Coast",
    lat: 38.5816,
    lng: -121.4944,
    dogFriendlinessScore: 7,
    description:
      "California's capital city is a tree-lined urban gem with an extensive network of river trails, farm-to-fork restaurants with dog-friendly patios, and some of the best off-leash dog parks in the Central Valley. The American River Parkway alone offers 32 miles of dog-friendly trails.",
    heroImage: "https://images.unsplash.com/photo-1556388158-158ea5ccacbd?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 524943,
  },
  hotels: [
    {
      name: "Kimpton Sawyer Hotel",
      address: "500 J St, Sacramento, CA 95814",
      lat: 38.5803,
      lng: -121.5000,
      priceRange: "$$$$" as const,
      dogPolicy: "Kimpton's signature pet-friendly policy with no size limits and no fees. Rooftop pool and downtown location near the riverfront.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Loaner leashes", "Walking route map"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.kimptonsawyerhotel.com",
      phone: "(916) 545-7100",
    },
    {
      name: "The Citizen Hotel",
      address: "926 J St, Sacramento, CA 95814",
      lat: 38.5800,
      lng: -121.4950,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique hotel in a historic building welcoming dogs under 80 lbs. Walking distance to Capitol Park and Old Sacramento.",
      maxDogWeight: 80,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Walking map", "Water bowls", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thecitizenhotel.com",
      phone: "(916) 447-2700",
    },
    {
      name: "Delta King Hotel",
      address: "1000 Front St, Sacramento, CA 95814",
      lat: 38.5830,
      lng: -121.5050,
      priceRange: "$$" as const,
      dogPolicy: "Historic riverboat hotel on the Sacramento River with pet-friendly staterooms. Dogs enjoy the waterfront boardwalk.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Riverfront location", "Dog bed", "Water bowls", "Boardwalk access", "Waste bags"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.deltaking.com",
      phone: "(916) 444-5464",
    },
    {
      name: "Residence Inn Sacramento Downtown",
      address: "1121 15th St, Sacramento, CA 95814",
      lat: 38.5785,
      lng: -121.4870,
      priceRange: "$$" as const,
      dogPolicy: "Extended-stay hotel with spacious pet-friendly suites and full kitchens. Convenient for longer stays with dogs.",
      maxDogWeight: 0,
      petFee: 100,
      amenities: ["Full kitchen", "Pet-friendly suites", "Parking", "Waste bags", "Pet relief area"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(916) 443-0500",
    },
  ],
  nationalParks: [
    {
      name: "American River Parkway",
      state: "California",
      lat: 38.5900,
      lng: -121.3500,
      dogPolicy: "Dogs welcome on all 32 miles of the Jedediah Smith Memorial Trail on leash. One of the longest urban parkway trails in the country.",
      dogTrails: ["Jedediah Smith Memorial Trail", "Discovery Park Loop", "Ancil Hoffman Nature Trail", "Sailor Bar Trail"],
      restrictions: ["Leash required on paved trail", "Off-leash only in designated areas", "Clean up after pet", "Watch for cyclists on shared trail"],
      description: "The American River Parkway stretches 32 miles from Discovery Park to Folsom Lake, offering an incredible urban trail system through riparian forests and along the American River. Dogs and their owners can walk, run, or bike for miles through shaded riverside scenery.",
      imageUrl: "",
      website: "https://www.arpf.org",
    },
    {
      name: "Folsom Lake State Recreation Area",
      state: "California",
      lat: 38.7100,
      lng: -121.1600,
      dogPolicy: "Dogs allowed on designated trails and in picnic areas on leash. Some beach areas allow leashed dogs seasonally.",
      dogTrails: ["Pioneer Express Trail", "Rattlesnake Bar Trail", "Beal's Point Shore Trail"],
      restrictions: ["6-foot leash required", "Not allowed on some beaches during summer", "Day use fee required", "Carry water for hot days"],
      description: "East of Sacramento, Folsom Lake offers miles of trails along the lake shore and through oak woodlands. Dogs can enjoy water access at certain beaches and explore the rolling Sierra foothills terrain.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/folsomlakesra",
    },
    {
      name: "Cosumnes River Preserve",
      state: "California",
      lat: 38.2900,
      lng: -121.4400,
      dogPolicy: "Dogs allowed on the levee trail on leash only. A unique wetland preserve south of Sacramento along the Cosumnes River.",
      dogTrails: ["Levee Trail", "River Walk Trail"],
      restrictions: ["Leash required at all times", "Stay on designated trails", "Not allowed in wetland areas", "Seasonal trail closures possible"],
      description: "This preserve protects one of the last undammed rivers flowing out of the Sierra Nevada. Dogs on leash can walk the levee trail through valley oak groves and wetlands, with opportunities to spot sandhill cranes and other wildlife.",
      imageUrl: "",
      website: "https://www.cosumnes.org",
    },
  ],
  restaurants: [
    {
      name: "The Firehouse Restaurant",
      address: "1112 2nd St, Sacramento, CA 95814",
      lat: 38.5835,
      lng: -121.5040,
      cuisine: "Fine Dining",
      priceRange: "$$$$" as const,
      dogPolicy: "Historic Old Sacramento fine dining with a courtyard patio welcoming dogs. Award-winning California cuisine in a converted firehouse.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.firehouseoldsac.com",
    },
    {
      name: "Tower Café",
      address: "1518 Broadway, Sacramento, CA 95818",
      lat: 38.5680,
      lng: -121.4930,
      cuisine: "International",
      priceRange: "$$" as const,
      dogPolicy: "Iconic Sacramento café with a massive tree-shaded patio where dogs are enthusiastically welcomed. Eclectic international menu.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.towercafe.com",
    },
    {
      name: "Localis",
      address: "2031 S St, Sacramento, CA 95811",
      lat: 38.5650,
      lng: -121.4850,
      cuisine: "Farm-to-Fork",
      priceRange: "$$$$" as const,
      dogPolicy: "Sacramento's premier farm-to-fork restaurant with seasonal patio seating where dogs are welcome. Tasting menus featuring local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.localisrestaurant.com",
    },
    {
      name: "Broderick Roadhouse",
      address: "316 Riverside Ave, West Sacramento, CA 95605",
      lat: 38.5845,
      lng: -121.5100,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Riverfront restaurant with a sprawling dog-friendly patio. Classic American fare with views of the Sacramento River and Tower Bridge.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.broderickroadhouse.com",
    },
    {
      name: "Tres Hermanas",
      address: "2416 K St, Sacramento, CA 95816",
      lat: 38.5750,
      lng: -121.4820,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Midtown Mexican restaurant with a colorful patio that welcomes dogs. Margaritas and street tacos in a festive setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.treshermanassac.com",
    },
  ],
  cafes: [
    {
      name: "Temple Coffee Roasters",
      address: "1010 9th St, Sacramento, CA 95814",
      lat: 38.5790,
      lng: -121.4920,
      dogPolicy: "Sacramento's beloved specialty roaster with a shaded patio where dogs are welcome. Award-winning single-origin coffees.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.templecoffee.com",
    },
    {
      name: "Insight Coffee Roasters",
      address: "1901 8th St, Sacramento, CA 95811",
      lat: 38.5670,
      lng: -121.4940,
      dogPolicy: "Craft coffee roaster with a patio on the R Street corridor. Dogs welcome outside while you enjoy precision-roasted beans.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.insightcoffee.com",
    },
    {
      name: "Old Soul Co.",
      address: "1716 L St, Sacramento, CA 95811",
      lat: 38.5740,
      lng: -121.4860,
      dogPolicy: "Neighborhood coffee shop in a converted Victorian with a front porch patio. Dogs welcome while you sip locally roasted coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.oldsoulco.com",
    },
    {
      name: "Chocolate Fish Coffee Roasters",
      address: "4749 Folsom Blvd, Sacramento, CA 95819",
      lat: 38.5580,
      lng: -121.4500,
      dogPolicy: "East Sacramento coffee shop with a lovely garden patio. Dogs are welcome outside with treats sometimes available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.chocolatefishcoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Bannon Creek Dog Park",
      address: "5800 West El Camino Ave, Sacramento, CA 95833",
      lat: 38.6150,
      lng: -121.5300,
      offLeash: true,
      fenced: true,
      acres: 5,
      amenities: ["Separate small dog area", "Water stations", "Shade trees", "Agility equipment", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "One of Sacramento's best off-leash parks with five acres of fenced space including separate areas for large and small dogs. Agility equipment and mature shade trees make it a popular destination year-round.",
    },
    {
      name: "Granite Dog Park",
      address: "Ramona Ave & Power Inn Rd, Sacramento, CA 95826",
      lat: 38.5400,
      lng: -121.4200,
      offLeash: true,
      fenced: true,
      acres: 4,
      amenities: ["Separate small dog area", "Water fountains", "Benches", "Shade structures", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "A well-maintained fenced dog park in the Granite Regional Park complex. Open grassy areas give dogs plenty of room to run, and the shaded benches provide comfort for owners on Sacramento's warm summer days.",
    },
    {
      name: "River Bend Off-Leash Dog Area",
      address: "2300 Rod Beaudry Dr, Sacramento, CA 95833",
      lat: 38.6050,
      lng: -121.5400,
      offLeash: true,
      fenced: false,
      acres: 15,
      amenities: ["River access", "Open fields", "Walking trails", "Parking", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "An expansive off-leash area along the American River where dogs can swim, fetch, and explore the riverside terrain. The unfenced natural setting and river access make it a favorite for water-loving dogs.",
    },
    {
      name: "Partner Park Dog Park",
      address: "5699 S Land Park Dr, Sacramento, CA 95822",
      lat: 38.5250,
      lng: -121.5000,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade trees", "Waste bag stations"],
      rating: 4.2,
      imageUrl: "",
      description: "A popular Land Park neighborhood dog park with fenced off-leash areas for both large and small dogs. The tree-lined setting provides natural shade and a pleasant atmosphere for daily dog outings.",
    },
  ],
};
