export const saltLakeCityData = {
  city: {
    name: "Salt Lake City",
    state: "Utah",
    region: "Mountain West",
    lat: 40.7608,
    lng: -111.8910,
    dogFriendlinessScore: 7,
    description:
      "Salt Lake City is a gateway to world-class outdoor recreation, and dogs benefit tremendously. The Wasatch Mountains rise directly behind the city offering countless trails, while the urban core features a growing food and brewery scene with dog-friendly patios. From canyon hikes to craft beer gardens, SLC delivers for active pups.",
    heroImage: "https://images.unsplash.com/photo-1583115260445-f95fe37202ae?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 200133,
  },

  hotels: [
    {
      name: "Kimpton Hotel Monaco Salt Lake City",
      address: "15 W 200 S, Salt Lake City, UT 84101",
      lat: 40.7640,
      lng: -111.8920,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome at no extra charge. Boutique hotel with a hosted evening wine hour.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Loaner leashes", "Pet-sitting referrals"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.monaco-saltlakecity.com",
      phone: "(801) 595-0000",
    },
    {
      name: "Grand America Hotel",
      address: "555 S Main St, Salt Lake City, UT 84111",
      lat: 40.7570,
      lng: -111.8910,
      priceRange: "$$$$" as const,
      dogPolicy: "Small dogs welcome with advance notice and a pet deposit. Five-star luxury in downtown SLC.",
      maxDogWeight: 25,
      petFee: 100,
      amenities: ["Dog bed", "Gourmet treats", "Water bowls", "Garden walking area", "Concierge pet services"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.grandamerica.com",
      phone: "(801) 258-6000",
    },
    {
      name: "La Quinta Inn & Suites Salt Lake City Airport",
      address: "4905 W Wiley Post Way, Salt Lake City, UT 84116",
      lat: 40.7780,
      lng: -111.9700,
      priceRange: "$" as const,
      dogPolicy: "Two dogs per room at no extra charge. Budget-friendly near the airport.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Pet waste stations", "Grassy areas", "Water bowls at front desk"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta",
      phone: "(801) 366-4444",
    },
    {
      name: "Residence Inn by Marriott Downtown",
      address: "285 W Broadway, Salt Lake City, UT 84101",
      lat: 40.7630,
      lng: -111.8960,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a non-refundable pet fee. Extended stay suites with kitchens near downtown.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Dog bed", "Near Liberty Park", "Pet waste stations", "Grassy areas", "Walking paths"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(801) 355-3300",
    },
  ],

  nationalParks: [
    {
      name: "Wasatch-Cache National Forest",
      state: "Utah",
      lat: 40.7000,
      lng: -111.7000,
      dogPolicy: "Dogs welcome on most trails in Big and Little Cottonwood Canyons. Leash required in watershed areas.",
      dogTrails: ["Millcreek Canyon (odd days off-leash)", "Pipeline Trail", "Desolation Trail", "Lake Blanche Trail"],
      restrictions: [
        "Dogs prohibited in Big and Little Cottonwood Canyon watershed areas",
        "Leash required on even days in Millcreek Canyon",
        "Off-leash on odd days in Millcreek Canyon",
        "Must be on leash in all developed areas",
      ],
      description:
        "The Wasatch Mountains offer world-class hiking minutes from downtown SLC. Millcreek Canyon is the go-to for dog owners with its odd-day off-leash policy. The alpine scenery, streams, and mountain meadows are spectacular.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/uwcnf",
    },
    {
      name: "Antelope Island State Park",
      state: "Utah",
      lat: 41.0500,
      lng: -112.2500,
      dogPolicy: "Leashed dogs welcome on most trails and beach areas. A unique Great Salt Lake island experience.",
      dogTrails: ["Lakeside Trail", "Buffalo Point Trail", "Frary Peak Trail", "Bridger Bay Beach"],
      restrictions: [
        "Must be on leash at all times",
        "Keep distance from bison",
        "Not allowed in visitor center",
        "Beware of brine flies on beaches",
      ],
      description:
        "The largest island in the Great Salt Lake offers bison sightings, expansive beaches, and rugged mountain trails. Dogs can swim in the ultra-salty lake and hike to panoramic viewpoints. A unique and unforgettable experience.",
      imageUrl: "",
      website: "https://stateparks.utah.gov/parks/antelope-island",
    },
    {
      name: "Red Butte Garden & Arboretum Trails",
      state: "Utah",
      lat: 40.7660,
      lng: -111.8250,
      dogPolicy: "Leashed dogs welcome on the natural area trails above the garden. Dogs not allowed inside the formal garden.",
      dogTrails: ["Red Butte Canyon Trail", "Bonneville Shoreline Trail access"],
      restrictions: [
        "No dogs in the formal garden",
        "Must be on leash on trails",
        "Stay on designated trails",
      ],
      description:
        "The natural area above Red Butte Garden connects to the Bonneville Shoreline Trail, offering foothill hikes with views of the Salt Lake Valley. Leashed dogs enjoy the sage-covered slopes and canyon scenery.",
      imageUrl: "",
      website: "https://www.redbuttegarden.org",
    },
  ],

  restaurants: [
    {
      name: "Red Rock Brewing Company",
      address: "254 S 200 W, Salt Lake City, UT 84101",
      lat: 40.7630,
      lng: -111.8940,
      cuisine: "Brewpub & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Award-winning brewery with excellent pub fare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.redrockbrewing.com",
    },
    {
      name: "Laziz Kitchen",
      address: "912 S Jefferson St, Salt Lake City, UT 84101",
      lat: 40.7530,
      lng: -111.8890,
      cuisine: "Middle Eastern",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Authentic Middle Eastern cuisine with a modern twist.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.lazizkitchen.com",
    },
    {
      name: "Squatters Pub Brewery",
      address: "147 W Broadway, Salt Lake City, UT 84101",
      lat: 40.7635,
      lng: -111.8948,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the large outdoor patio. Pioneer of the SLC craft beer scene.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.squatters.com",
    },
    {
      name: "The Copper Onion",
      address: "111 E Broadway, Salt Lake City, UT 84111",
      lat: 40.7635,
      lng: -111.8880,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome at the sidewalk tables during warm months. Acclaimed farm-to-table dining downtown.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.thecopperonion.com",
    },
    {
      name: "Boltcutter",
      address: "57 E Gallivan Ave, Salt Lake City, UT 84111",
      lat: 40.7625,
      lng: -111.8885,
      cuisine: "Mexican Street Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor picnic tables. Trendy tacos and cocktails in a lively setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.boltcutterslc.com",
    },
  ],

  cafes: [
    {
      name: "Publik Coffee Roasters",
      address: "975 S West Temple, Salt Lake City, UT 84101",
      lat: 40.7520,
      lng: -111.8930,
      dogPolicy: "Dogs welcome on the outdoor patio. Specialty coffee in an industrial-chic space.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.publikcoffee.com",
    },
    {
      name: "Coffee Garden",
      address: "878 E 900 S, Salt Lake City, UT 84105",
      lat: 40.7520,
      lng: -111.8700,
      dogPolicy: "Dog-friendly patio in the 9th & 9th neighborhood. A SLC institution since 1993.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.coffeegarden.com",
    },
    {
      name: "Three Pines Coffee",
      address: "165 S Main St, Salt Lake City, UT 84111",
      lat: 40.7645,
      lng: -111.8910,
      dogPolicy: "Outdoor seating welcomes dogs. Minimalist specialty coffee shop downtown.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.threepinescoffee.com",
    },
    {
      name: "Blue Copper Coffee Room",
      address: "138 S W Temple, Salt Lake City, UT 84101",
      lat: 40.7648,
      lng: -111.8928,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Craft coffee roaster with a focus on single-origin beans.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bluecopper.coffee",
    },
  ],

  dogParks: [
    {
      name: "Tanner Park Off-Leash Dog Area",
      address: "2740 S Heritage Way, Salt Lake City, UT 84109",
      lat: 40.7150,
      lng: -111.8180,
      offLeash: true,
      fenced: false,
      acres: 8.0,
      amenities: ["Creek access", "Trail system", "Natural terrain", "Waste stations", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "SLC's most popular off-leash area features a creek where dogs can splash and swim, trails through natural vegetation, and a community of regulars. The unfenced natural area provides a true outdoor experience.",
    },
    {
      name: "Memory Grove Off-Leash Park",
      address: "300 N Canyon Rd, Salt Lake City, UT 84103",
      lat: 40.7720,
      lng: -111.8810,
      offLeash: true,
      fenced: false,
      acres: 5.0,
      amenities: ["Creek", "Walking paths", "City Canyon access", "Waste stations", "Historic monuments"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A beautiful off-leash area in City Creek Canyon just above the state capitol. Dogs love the creek, the paths, and the transition from city to canyon. One of the most scenic urban dog walks in the West.",
    },
    {
      name: "Lindsey Gardens Dog Park",
      address: "774 N 600 E, Salt Lake City, UT 84102",
      lat: 40.7740,
      lng: -111.8710,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Water fountain", "Benches", "Waste stations", "Shade trees"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A small but well-loved fenced dog park in the Avenues neighborhood. The fenced area provides a secure space for dogs to play, and the Avenues surroundings make for a pleasant walk to and from the park.",
    },
    {
      name: "Parley's Nature Park",
      address: "2760 S Heritage Way, Salt Lake City, UT 84109",
      lat: 40.7140,
      lng: -111.8170,
      offLeash: true,
      fenced: false,
      acres: 10.0,
      amenities: ["Creek trails", "Wetland boardwalks", "Nature viewing", "Paved and dirt paths", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Adjacent to Tanner Park, this nature preserve follows Parley's Creek through wetlands and cottonwood groves. Dogs can be off-leash and enjoy the creek access and varied terrain.",
    },
  ],
};
