export const sanDiegoData = {
  city: {
    name: "San Diego",
    state: "California",
    region: "West Coast",
    lat: 32.7157,
    lng: -117.1611,
    dogFriendlinessScore: 9,
    description:
      "San Diego might just be the best city in America to be a dog. With year-round perfect weather, legendary off-leash dog beaches, a sprawling urban park system, and a taco shop on every corner that happily serves patio pups, America's Finest City truly earns its title for the four-legged crowd. From Ocean Beach to Balboa Park, your dog will be living its absolute best life.",
    heroImage: "https://images.unsplash.com/photo-1538964173425-93884d739506?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 1386932,
  },
  hotels: [
    {
      name: "The Lafayette Hotel",
      address: "2223 El Cajon Blvd, San Diego, CA 92104",
      lat: 32.7581,
      lng: -117.1294,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome, all sizes, max 2 pets per room",
      maxDogWeight: 0,
      petFee: 75,
      amenities: [
        "Dog bed",
        "Welcome treats",
        "Pool area access",
        "Pet relief station",
        "Dog-friendly bar",
      ],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.lafayettehotelsd.com",
      phone: "(619) 296-2101",
    },
    {
      name: "Kimpton Hotel Palomar San Diego",
      address: "1047 5th Ave, San Diego, CA 92101",
      lat: 32.7164,
      lng: -117.1614,
      priceRange: "$$$" as const,
      dogPolicy: "All pets welcome — no size or breed restrictions, no fee",
      maxDogWeight: 0,
      petFee: 0,
      amenities: [
        "Dog bed",
        "Food and water bowls",
        "Welcome treats",
        "Pet concierge",
        "Evening wine hour",
      ],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.hotelpalomar-sandiego.com",
      phone: "(619) 515-3000",
    },
    {
      name: "The Pearl Hotel",
      address: "1410 Rosecrans St, San Diego, CA 92106",
      lat: 32.7375,
      lng: -117.2112,
      priceRange: "$$" as const,
      dogPolicy: "Dogs under 35 lbs welcome, 1 pet per room",
      maxDogWeight: 35,
      petFee: 50,
      amenities: [
        "Dog bed",
        "Poolside lounging",
        "Nearby Point Loma walking trails",
      ],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thepearlsd.com",
      phone: "(619) 226-6100",
    },
    {
      name: "Hotel del Coronado",
      address: "1500 Orange Ave, Coronado, CA 92118",
      lat: 32.6807,
      lng: -117.1783,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 40 lbs welcome in select rooms",
      maxDogWeight: 40,
      petFee: 150,
      amenities: [
        "Luxury dog bed",
        "Gourmet treat package",
        "Beach access",
        "Dog walking service",
        "Monogrammed leash",
      ],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.hoteldel.com",
      phone: "(619) 435-6611",
    },
    {
      name: "Ocean Beach Hotel",
      address: "5080 Newport Ave, San Diego, CA 92107",
      lat: 32.7481,
      lng: -117.2487,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome — steps from the off-leash dog beach",
      maxDogWeight: 0,
      petFee: 25,
      amenities: [
        "Beach towels for dogs",
        "Outdoor rinse station",
        "Dog waste bags",
        "Treats at check-in",
      ],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.obhotel.com",
      phone: "(619) 223-7191",
    },
  ],
  nationalParks: [
    {
      name: "Cabrillo National Monument",
      state: "California",
      lat: 32.6735,
      lng: -117.2425,
      dogPolicy: "Dogs allowed on Bayside Trail and in parking areas on leash",
      dogTrails: ["Bayside Trail"],
      restrictions: [
        "Must be on 6-foot leash",
        "Not allowed on tidepools area",
        "Not allowed in visitor center",
        "Not allowed on coastal trail",
      ],
      description:
        "Perched on the tip of Point Loma, this monument offers sweeping views of the San Diego skyline, Coronado, and the Pacific Ocean. Dogs can explore the Bayside Trail with stunning harbor panoramas.",
      imageUrl: "",
      website: "https://www.nps.gov/cabr",
    },
    {
      name: "Anza-Borrego Desert State Park",
      state: "California",
      lat: 33.0822,
      lng: -116.3174,
      dogPolicy: "Dogs allowed on dirt roads and in developed campgrounds on leash",
      dogTrails: [
        "Borrego Palm Canyon Nature Trail",
        "Yaqui Well Nature Trail",
        "Campground Loop Trails",
      ],
      restrictions: [
        "Must be on 6-foot leash",
        "Not allowed on wilderness trails during bighorn sheep season",
        "Bring extra water — desert conditions",
        "Check ground temperature before walking",
      ],
      description:
        "California's largest state park is a desert wonderland of wildflower blooms, slot canyons, and ancient fossils. Dogs can enjoy cool morning hikes through palm oases and surreal metal sculptures scattered across the desert landscape.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/anza-borrego",
    },
    {
      name: "Torrey Pines State Natural Reserve",
      state: "California",
      lat: 32.9221,
      lng: -117.2549,
      dogPolicy: "Dogs NOT allowed on trails; allowed on the beach below the bluffs",
      dogTrails: ["Torrey Pines State Beach (below bluffs)"],
      restrictions: [
        "Dogs prohibited on all trails within the reserve",
        "Beach access only via North Beach parking lot",
        "Must be on leash on beach",
      ],
      description:
        "While dogs cannot hike the bluff trails, the stunning beach below the sandstone cliffs is a memorable experience. The dramatic eroded formations and crashing waves make for an unforgettable coastal walk with your pup.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/torrey-pines",
    },
    {
      name: "Mission Trails Regional Park",
      state: "California",
      lat: 32.8379,
      lng: -117.0397,
      dogPolicy: "Dogs welcome on all trails on leash",
      dogTrails: [
        "Cowles Mountain Trail",
        "Father Junipero Serra Trail",
        "Oak Canyon Trail",
        "Visitor Center Loop",
        "Grasslands Crossing Trail",
      ],
      restrictions: [
        "Must be on 6-foot leash",
        "Clean up after pet",
        "Carry water for your dog — trails can be hot",
      ],
      description:
        "One of the largest urban parks in the country with rugged trails, a river valley, and panoramic city views from Cowles Mountain summit. Dogs love every inch of this 8,000-acre natural playground right in San Diego's backyard.",
      imageUrl: "",
      website: "https://mtrp.org",
    },
  ],
  restaurants: [
    {
      name: "The Patio on Lamont Street",
      address: "4445 Lamont St, San Diego, CA 92109",
      lat: 32.7963,
      lng: -117.2455,
      cuisine: "California Modern",
      priceRange: "$$$" as const,
      dogPolicy:
        "Extremely dog-friendly patio with dog menu and special events",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thepatiorestaurants.com",
    },
    {
      name: "Lazy Dog Restaurant & Bar",
      address: "1202 Camino Del Rio N, San Diego, CA 92108",
      lat: 32.7654,
      lng: -117.1472,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Dog menu available, water bowls, patio seating for dogs",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.lazydogrestaurants.com",
    },
    {
      name: "Hodad's",
      address: "5010 Newport Ave, San Diego, CA 92107",
      lat: 32.7483,
      lng: -117.2478,
      cuisine: "Burgers",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables — beachside burger bliss",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hodadies.com",
    },
    {
      name: "Puesto",
      address: "789 W Harbor Dr, San Diego, CA 92101",
      lat: 32.7091,
      lng: -117.1695,
      cuisine: "Mexican Street Food",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the waterfront patio",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.eatpuesto.com",
    },
    {
      name: "Cesarina",
      address: "4161 Voltaire St, San Diego, CA 92107",
      lat: 32.7498,
      lng: -117.2332,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on front patio, water bowls provided",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.8,
      imageUrl: "",
      website: "https://www.cesarinarestaurant.com",
    },
    {
      name: "Tacos El Gordo",
      address: "689 H St, Chula Vista, CA 91910",
      lat: 32.6393,
      lng: -117.0845,
      cuisine: "Tijuana-Style Tacos",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor ordering and seating area",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.tacoselgordobc.com",
    },
    {
      name: "Wonderland Ocean Pub",
      address: "5083 Santa Monica Ave, San Diego, CA 92107",
      lat: 32.7477,
      lng: -117.2491,
      cuisine: "Seafood & Pub",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly rooftop with ocean views — pup cups available",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.wonderlandob.com",
    },
    {
      name: "Breakfast Republic",
      address: "2867 5th Ave, San Diego, CA 92103",
      lat: 32.7406,
      lng: -117.1621,
      cuisine: "Brunch",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio, water bowls available",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.breakfastrepublic.com",
    },
  ],
  cafes: [
    {
      name: "Dark Horse Coffee Roasters",
      address: "3260 Adams Ave, San Diego, CA 92116",
      lat: 32.7665,
      lng: -117.1269,
      dogPolicy: "Large patio with dog tie-ups, water bowls, and treat jar",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.darkhorsecoffeeroasters.com",
    },
    {
      name: "Communal Coffee",
      address: "2335 University Ave, San Diego, CA 92104",
      lat: 32.7494,
      lng: -117.1413,
      dogPolicy: "Covered patio is fully dog-friendly, Instagram-worthy setup",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.communalcoffee.com",
    },
    {
      name: "Holsem Coffee",
      address: "2911 University Ave, San Diego, CA 92104",
      lat: 32.7494,
      lng: -117.1324,
      dogPolicy: "Patio friendly, dog water station always available",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.holsemcoffee.com",
    },
    {
      name: "Better Buzz Coffee",
      address: "4683 Cass St, San Diego, CA 92109",
      lat: 32.8018,
      lng: -117.2539,
      dogPolicy: "Beach-side patio welcomes dogs — just steps from the sand",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bfrsd.com",
    },
    {
      name: "Bird Rock Coffee Roasters",
      address: "5627 La Jolla Blvd, La Jolla, CA 92037",
      lat: 32.8116,
      lng: -117.2653,
      dogPolicy: "Outdoor seating welcomes dogs, premium single-origin vibes",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bfrsd.com",
    },
  ],
  dogParks: [
    {
      name: "Ocean Beach Dog Beach",
      address: "W Point Loma Blvd, San Diego, CA 92107",
      lat: 32.7487,
      lng: -117.2538,
      offLeash: true,
      fenced: false,
      acres: 5.0,
      amenities: [
        "Ocean swimming",
        "Waste stations",
        "Rinse stations nearby",
        "Adjacent to OB pier",
      ],
      rating: 4.8,
      imageUrl: "",
      description:
        "San Diego's original and most legendary off-leash dog beach. Dogs sprint across the sand, crash through waves, and socialize with hundreds of other pups in what can only be described as canine paradise. The sunsets here with your dog are unforgettable.",
    },
    {
      name: "Fiesta Island Off-Leash Park",
      address: "1500 Fiesta Island Rd, San Diego, CA 92109",
      lat: 32.7682,
      lng: -117.2237,
      offLeash: true,
      fenced: false,
      acres: 90.0,
      amenities: [
        "Bay swimming",
        "Sandy beaches",
        "Open fields",
        "Waste stations",
      ],
      rating: 4.7,
      imageUrl: "",
      description:
        "A massive 90-acre sandy island in Mission Bay where dogs can run completely free. With calm bay waters for swimming, endless sand for digging, and no roads to worry about, it's a dog's dream destination and one of the best off-leash areas in all of California.",
    },
    {
      name: "Nate's Point Dog Park (Balboa Park)",
      address: "2400 6th Ave, San Diego, CA 92101",
      lat: 32.7345,
      lng: -117.1551,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: [
        "Water fountains",
        "Shade trees",
        "Benches",
        "Canyon views",
        "Double-gated entry",
      ],
      rating: 4.5,
      imageUrl: "",
      description:
        "A fenced off-leash park right in iconic Balboa Park with stunning canyon views and mature eucalyptus shade. A favorite for downtown dog owners who want a quick but scenic off-leash session.",
    },
    {
      name: "Grape Street Dog Park",
      address: "3215 Grape St, San Diego, CA 92102",
      lat: 32.7322,
      lng: -117.1388,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: [
        "Separate small dog area",
        "Water fountains",
        "Agility equipment",
        "Benches",
        "Waste stations",
      ],
      rating: 4.4,
      imageUrl: "",
      description:
        "A well-loved community dog park in South Park with separate areas for large and small dogs. The agility equipment keeps active dogs entertained, and the shady benches let owners relax while their pups play.",
    },
    {
      name: "Capehart Dog Park",
      address: "4700 W Point Loma Blvd, San Diego, CA 92107",
      lat: 32.7441,
      lng: -117.2378,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: [
        "Water fountains",
        "Open grass area",
        "Benches",
        "Shade structures",
        "Waste stations",
      ],
      rating: 4.3,
      imageUrl: "",
      description:
        "A local favorite in Point Loma with a friendly community of regulars. The grassy terrain and ocean breezes make it a comfortable spot for dogs to play, and it's just a short walk from the famous Dog Beach.",
    },
  ],
};
