export const sanFranciscoData = {
  city: {
    name: "San Francisco",
    state: "California",
    region: "West Coast",
    lat: 37.7749,
    lng: -122.4194,
    dogFriendlinessScore: 8,
    description:
      "San Francisco is a paradise for pups, with fog-kissed parks, miles of off-leash beaches, and a café culture that welcomes four-legged friends at nearly every sidewalk table. From romping through the sandy stretches of Ocean Beach to exploring the wooded trails of the Presidio, dogs here live their best lives against a backdrop of iconic bridges and Victorian homes.",
    heroImage: "https://images.unsplash.com/photo-1521747116042-5a810fda9664?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 873965,
  },
  hotels: [
    {
      name: "Hotel Nikko San Francisco",
      address: "222 Mason St, San Francisco, CA 94102",
      lat: 37.7862,
      lng: -122.4095,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a signed pet waiver at check-in. Two dogs max per room.",
      maxDogWeight: 0,
      petFee: 100,
      amenities: ["Dog beds", "Water bowls", "Treat bags", "Pet-sitting referrals", "Nearby walking routes map"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelnikkosf.com",
      phone: "(415) 394-1111",
    },
    {
      name: "The Fairmont San Francisco",
      address: "950 Mason St, San Francisco, CA 94108",
      lat: 37.7923,
      lng: -122.4103,
      priceRange: "$$$$" as const,
      dogPolicy: "Canine guests receive the royal treatment with a personalized welcome package. One dog per room.",
      maxDogWeight: 50,
      petFee: 150,
      amenities: ["Luxury dog bed", "Gourmet treat turndown", "Dog-walking service", "Pet room service menu", "Branded bandana"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.fairmont.com/san-francisco",
      phone: "(415) 772-5000",
    },
    {
      name: "Kimpton Hotel Palomar",
      address: "12 Fourth St, San Francisco, CA 94103",
      lat: 37.7845,
      lng: -122.4047,
      priceRange: "$$$" as const,
      dogPolicy: "All Kimpton hotels welcome pets of every size and breed at no extra charge. No limits on number of pets.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Food and water bowls", "Treats at front desk", "Loaner leashes", "Pet-friendly minibar snacks"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hotelpalomar-laundry.com",
      phone: "(415) 348-1111",
    },
    {
      name: "The Ritz-Carlton San Francisco",
      address: "600 Stockton St, San Francisco, CA 94108",
      lat: 37.7916,
      lng: -122.4074,
      priceRange: "$$$$" as const,
      dogPolicy: "Pampered pooches welcome with advance notice. Concierge can arrange dog-walking and grooming.",
      maxDogWeight: 40,
      petFee: 125,
      amenities: ["Designer dog bed", "Custom pet menu", "Grooming referrals", "Welcome treats", "Pet ID tag"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.ritzcarlton.com/san-francisco",
      phone: "(415) 296-7465",
    },
    {
      name: "Hotel Vitale (1 Hotel San Francisco)",
      address: "8 Mission St, San Francisco, CA 94105",
      lat: 37.7935,
      lng: -122.3928,
      priceRange: "$$$" as const,
      dogPolicy: "Eco-conscious pet program with organic treats and sustainable pet amenities. Dogs up to 75 lbs.",
      maxDogWeight: 75,
      petFee: 75,
      amenities: ["Organic dog treats", "Recycled-material dog bed", "Water bowl", "Walking map of Embarcadero", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.1hotels.com/san-francisco",
      phone: "(415) 278-3700",
    },
  ],
  nationalParks: [
    {
      name: "Golden Gate National Recreation Area",
      state: "California",
      lat: 37.8199,
      lng: -122.4783,
      dogPolicy: "One of the most dog-friendly national park sites in the country. Off-leash areas at Crissy Field, Fort Funston, and Ocean Beach. Leashed dogs permitted on many trails.",
      dogTrails: ["Crissy Field Promenade", "Coastal Trail", "Fort Funston Sand Ladder Trail", "Lands End Trail", "Battery to Bluffs Trail"],
      restrictions: ["Dogs prohibited in wildlife protection areas", "Must be leashed in designated areas", "Voice control required in off-leash zones", "No dogs on Muir Beach during snowy plover season"],
      description: "Spanning over 80,000 acres across San Francisco, Marin, and San Mateo counties, the Golden Gate National Recreation Area is a dog owner's dream with sweeping coastal bluffs, dense eucalyptus groves, and sandy beaches where pups can run free.",
      imageUrl: "",
      website: "https://www.nps.gov/goga",
    },
    {
      name: "Point Reyes National Seashore",
      state: "California",
      lat: 38.0682,
      lng: -122.8808,
      dogPolicy: "Dogs allowed on four beaches and a few trails on-leash only. Many areas are closed to dogs due to sensitive wildlife habitat.",
      dogTrails: ["Kehoe Beach Trail", "Limantour Beach Trail", "South Beach Trail"],
      restrictions: ["Dogs must be on leash at all times", "Prohibited on most inland trails", "Not allowed in wilderness areas", "No dogs near elephant seal colonies", "Beach closures during snowy plover nesting"],
      description: "A windswept peninsula jutting into the Pacific, Point Reyes offers dramatic sea cliffs, sprawling beaches, and the chance to spot whales and tule elk. While access is limited for dogs, the beaches where they are allowed are spectacularly beautiful.",
      imageUrl: "",
      website: "https://www.nps.gov/pore",
    },
    {
      name: "Muir Woods National Monument",
      state: "California",
      lat: 37.8970,
      lng: -122.5811,
      dogPolicy: "Dogs are NOT permitted on any trails within Muir Woods. Service animals only. However, adjacent trails in the GGNRA are dog-friendly.",
      dogTrails: [],
      restrictions: ["No dogs allowed on any trail", "No dogs in shuttle buses", "Service animals only", "Nearby GGNRA trails are alternatives"],
      description: "Home to towering old-growth coast redwoods, Muir Woods is a cathedral of ancient trees just north of San Francisco. While dogs cannot join you under the giant canopy, nearby GGNRA trails offer dog-friendly alternatives with redwood views.",
      imageUrl: "",
      website: "https://www.nps.gov/muwo",
    },
    {
      name: "Pinnacles National Park",
      state: "California",
      lat: 36.4906,
      lng: -121.1825,
      dogPolicy: "Dogs are not allowed on any trails or in the backcountry. Permitted only in parking areas, picnic areas, and campground roads.",
      dogTrails: [],
      restrictions: ["No dogs on trails", "No dogs in backcountry", "Allowed only in developed areas", "Must be on leash at all times in allowed areas"],
      description: "About two hours south of San Francisco, Pinnacles features dramatic rock spires, talus caves, and a huge California condor population. While not dog-friendly on trails, the drive through the park offers stunning scenery.",
      imageUrl: "",
      website: "https://www.nps.gov/pinn",
    },
  ],
  restaurants: [
    {
      name: "Zazie",
      address: "941 Cole St, San Francisco, CA 94117",
      lat: 37.7655,
      lng: -122.4506,
      cuisine: "French Bistro",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the heated back patio. Water bowls and occasional scraps from the kitchen provided.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.zaziesf.com",
    },
    {
      name: "The Ramp",
      address: "855 Terry A Francois Blvd, San Francisco, CA 94158",
      lat: 37.7613,
      lng: -122.3871,
      cuisine: "American Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Waterfront patio is fully dog-friendly. A neighborhood favorite for weekend brunch with your pup.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.therampsf.com",
    },
    {
      name: "Pizzeria Delfina",
      address: "3611 18th St, San Francisco, CA 94110",
      lat: 37.7617,
      lng: -122.4243,
      cuisine: "Italian",
      priceRange: "$$" as const,
      dogPolicy: "Sidewalk tables welcome well-behaved dogs on leash. Staff often bring water for furry guests.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.pizzeriadelfina.com",
    },
    {
      name: "Presidio Social Club",
      address: "563 Ruger St, San Francisco, CA 94129",
      lat: 37.7999,
      lng: -122.4537,
      cuisine: "American",
      priceRange: "$$$" as const,
      dogPolicy: "Set inside the Presidio, dogs are welcome at outdoor tables. A perfect stop after a park hike with your dog.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.presidiosocialclub.com",
    },
    {
      name: "Outerlands",
      address: "4001 Judah St, San Francisco, CA 94122",
      lat: 37.7602,
      lng: -122.5085,
      cuisine: "Californian",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the small front patio. Popular brunch spot near Ocean Beach, perfect for a post-beach bite.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.outerlandssf.com",
    },
    {
      name: "Park Chalet Garden Restaurant",
      address: "1000 Great Hwy, San Francisco, CA 94121",
      lat: 37.7689,
      lng: -122.5102,
      cuisine: "American Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Spacious backyard garden patio welcomes dogs. Great for sunny afternoons after exploring Golden Gate Park.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.parkchalet.com",
    },
    {
      name: "Foreign Cinema",
      address: "2534 Mission St, San Francisco, CA 94110",
      lat: 37.7565,
      lng: -122.4190,
      cuisine: "Mediterranean-Californian",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs permitted on the iconic outdoor courtyard during off-peak hours. Check with host on arrival.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.foreigncinema.com",
    },
    {
      name: "Warming Hut Café & Bookstore",
      address: "983 Marine Dr, San Francisco, CA 94129",
      lat: 37.8078,
      lng: -122.4748,
      cuisine: "Cafe & Light Fare",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables with Golden Gate Bridge views. Grab a coffee and a pastry before hitting Crissy Field.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.parksconservancy.org/warming-hut",
    },
  ],
  cafes: [
    {
      name: "Trouble Coffee Co.",
      address: "4033 Judah St, San Francisco, CA 94122",
      lat: 37.7601,
      lng: -122.5092,
      dogPolicy: "Ultra-casual Outer Sunset spot where sandy dogs from the beach are a regular sight. Dogs welcome outside.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.troublecoffee.com",
    },
    {
      name: "Sightglass Coffee",
      address: "270 7th St, San Francisco, CA 94103",
      lat: 37.7770,
      lng: -122.4069,
      dogPolicy: "Dogs welcome on the sidewalk seating area. Baristas are known dog lovers and may sneak a pet or two.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sightglasscoffee.com",
    },
    {
      name: "Andytown Coffee Roasters",
      address: "3655 Lawton St, San Francisco, CA 94122",
      lat: 37.7568,
      lng: -122.5042,
      dogPolicy: "Dog-loving café with a community vibe. Pups welcome at outdoor tables and often spotted napping on the sidewalk.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.andytownsf.com",
    },
    {
      name: "Ritual Coffee Roasters",
      address: "1026 Valencia St, San Francisco, CA 94110",
      lat: 37.7565,
      lng: -122.4211,
      dogPolicy: "Mission District staple with sidewalk seating perfect for people (and dog) watching. Dogs welcome outside.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ritualroasters.com",
    },
    {
      name: "Equator Coffees (Presidio)",
      address: "1 Letterman Dr, Bldg A, San Francisco, CA 94129",
      lat: 37.7993,
      lng: -122.4498,
      dogPolicy: "Located in the Presidio, this café is a natural stop for dog walkers. Outdoor tables face a grassy lawn where dogs can relax.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.equatorcoffees.com",
    },
  ],
  dogParks: [
    {
      name: "Fort Funston Off-Leash Area",
      address: "Fort Funston Rd, San Francisco, CA 94132",
      lat: 37.7148,
      lng: -122.5024,
      offLeash: true,
      fenced: false,
      acres: 57,
      amenities: ["Beach access", "Cliff trails", "Hang glider viewing area", "Parking lot", "Waste bag stations"],
      rating: 4.8,
      imageUrl: "",
      description: "Perched on dramatic coastal bluffs, Fort Funston is San Francisco's crown jewel for off-leash dogs. Miles of sandy trails wind through ice plant and dune scrub before descending to a wild, windswept beach where dogs sprint with pure joy.",
    },
    {
      name: "Crissy Field Dog Area",
      address: "1199 E Beach, San Francisco, CA 94129",
      lat: 37.8040,
      lng: -122.4651,
      offLeash: true,
      fenced: false,
      acres: 28,
      amenities: ["Beach access", "Waterfront promenade", "Restrooms", "Water fountains", "Golden Gate Bridge views"],
      rating: 4.7,
      imageUrl: "",
      description: "With the Golden Gate Bridge towering overhead and the bay sparkling beside you, Crissy Field offers an unbeatable setting for off-leash romps. Dogs dash between the tidal marsh and sandy beach while owners soak in one of the world's great views.",
    },
    {
      name: "Dolores Park Dog Play Area",
      address: "Dolores St & 20th St, San Francisco, CA 94114",
      lat: 37.7582,
      lng: -122.4270,
      offLeash: true,
      fenced: false,
      acres: 2,
      amenities: ["City skyline views", "Hilly terrain", "Nearby restrooms", "Water fountains", "Adjacent playground"],
      rating: 4.4,
      imageUrl: "",
      description: "The south slope of Dolores Park doubles as an unofficial off-leash dog paradise with sweeping views of downtown and the Mission. Social dogs love it here, and the vibe is as friendly and laid-back as the city itself.",
    },
    {
      name: "Bernal Heights Off-Leash Area",
      address: "Bernal Heights Blvd, San Francisco, CA 94110",
      lat: 37.7430,
      lng: -122.4153,
      offLeash: true,
      fenced: false,
      acres: 26,
      amenities: ["360-degree views", "Hilltop trails", "Grassland paths", "Waste bag stations", "Street parking"],
      rating: 4.6,
      imageUrl: "",
      description: "Climb to the top of Bernal Hill for panoramic 360-degree views of the city while your dog gallops through open grassland. A beloved neighborhood gem where regulars know every dog by name.",
    },
    {
      name: "McLaren Park Dog Play Area",
      address: "Shelley Dr, San Francisco, CA 94134",
      lat: 37.7187,
      lng: -122.4201,
      offLeash: true,
      fenced: true,
      acres: 3.5,
      amenities: ["Fenced enclosure", "Separate small dog area", "Benches", "Water spigot", "Shaded sections"],
      rating: 4.2,
      imageUrl: "",
      description: "Tucked inside San Francisco's second-largest park, this fenced dog play area offers a secure space for off-leash play. It features separate areas for large and small dogs and plenty of shade from mature trees, making it a reliable retreat on warmer days.",
    },
  ],
};
