export const sanAntonioData = {
  city: {
    name: "San Antonio",
    state: "Texas",
    region: "Southwest",
    lat: 29.4241,
    lng: -98.4936,
    dogFriendlinessScore: 7,
    description:
      "San Antonio blends rich Texas history with a vibrant food scene that increasingly embraces dogs. Beyond the famous River Walk, the city offers miles of greenway trails, expansive parks, and a growing number of dog-friendly patios where your pup can enjoy the Tex-Mex alongside you.",
    heroImage: "https://images.unsplash.com/photo-1581542222610-4dff8e87a43b?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 1434625,
  },

  hotels: [
    {
      name: "Hotel Emma",
      address: "136 E Grayson St, San Antonio, TX 78215",
      lat: 29.4430,
      lng: -98.4790,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 40 lbs welcome with a pet fee. Luxury hotel in the historic Pearl District.",
      maxDogWeight: 40,
      petFee: 100,
      amenities: ["Dog bed", "Gourmet treats", "Water bowls", "Pearl District walking", "Pet-sitting referral"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.thehotelemma.com",
      phone: "(210) 448-8300",
    },
    {
      name: "Hotel Havana",
      address: "1015 Navarro St, San Antonio, TX 78205",
      lat: 29.4260,
      lng: -98.4900,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome with a nightly fee. Tropical boutique hotel on the River Walk.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "River Walk access", "Garden courtyard", "Walking maps"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.havanasanantonio.com",
      phone: "(210) 222-2008",
    },
    {
      name: "Drury Inn & Suites Riverwalk",
      address: "201 N St. Mary's St, San Antonio, TX 78205",
      lat: 29.4260,
      lng: -98.4930,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 80 lbs welcome with a nightly fee. Steps from the River Walk.",
      maxDogWeight: 80,
      petFee: 35,
      amenities: ["Near River Walk", "Grassy area", "Evening reception", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.druryhotels.com",
      phone: "(210) 212-5200",
    },
    {
      name: "La Quinta Inn San Antonio Downtown",
      address: "1001 E Commerce St, San Antonio, TX 78205",
      lat: 29.4240,
      lng: -98.4830,
      priceRange: "$" as const,
      dogPolicy: "All dogs welcome at no extra charge. Convenient downtown location.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Downtown location", "Near River Walk", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(210) 222-9181",
    },
  ],

  nationalParks: [
    {
      name: "San Antonio Missions National Historical Park",
      state: "Texas",
      lat: 29.3590,
      lng: -98.4790,
      dogPolicy: "Leashed dogs welcome on the Mission Trail and outdoor grounds. Not permitted inside mission buildings.",
      dogTrails: ["Mission Trail", "Espada Aqueduct Walk", "San Juan Mission Loop"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed inside mission buildings or churches",
        "Stay on designated paths",
      ],
      description:
        "A UNESCO World Heritage Site preserving four 18th-century Spanish missions. The Mission Trail connects all four missions along the San Antonio River, offering a historically rich walk with your dog.",
      imageUrl: "",
      website: "https://www.nps.gov/saan",
    },
    {
      name: "Government Canyon State Natural Area",
      state: "Texas",
      lat: 29.5510,
      lng: -98.7630,
      dogPolicy: "Leashed dogs welcome on the frontcountry trails only. Over 12,000 acres of Hill Country wilderness.",
      dogTrails: ["Sendero Balcones Trail", "Savannah Loop Trail", "Bluff Spurs Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on backcountry trails",
        "Must stay on designated dog-friendly trails",
        "Carry water - limited shade",
      ],
      description:
        "A 12,000-acre natural area on the northwest edge of San Antonio offering Hill Country hiking through grasslands, oak forests, and along limestone bluffs. The frontcountry trails welcome leashed dogs.",
      imageUrl: "",
      website: "https://www.tpwd.texas.gov/state-parks/government-canyon",
    },
    {
      name: "Friedrich Wilderness Park",
      state: "Texas",
      lat: 29.5570,
      lng: -98.6210,
      dogPolicy: "Leashed dogs welcome on all trails. A 600-acre Hill Country nature preserve within San Antonio.",
      dogTrails: ["Main Loop Trail", "Vista Loop Trail", "Restoration Way Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Trails close during wet conditions",
        "Watch for trail closures for endangered species protection",
      ],
      description:
        "A rugged Hill Country park with limestone trails through juniper and oak woodlands. The Vista Loop rewards hikers with panoramic views and is home to the endangered golden-cheeked warbler.",
      imageUrl: "",
      website: "https://www.sanantonio.gov/ParksAndRec/Parks-Facilities/All-Parks-Facilities/Parks/Friedrich-Wilderness-Park",
    },
  ],

  restaurants: [
    {
      name: "The Granary 'Cue & Brew",
      address: "602 Avenue A, San Antonio, TX 78215",
      lat: 29.4430,
      lng: -98.4770,
      cuisine: "Barbecue & Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the large patio in the Pearl District. Craft beer and smoked meats.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thegranarysa.com",
    },
    {
      name: "La Gloria",
      address: "100 E Grayson St, San Antonio, TX 78215",
      lat: 29.4425,
      lng: -98.4795,
      cuisine: "Mexican Street Food",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor patio. Authentic Mexican street food in the Pearl.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.lagloria.com",
    },
    {
      name: "Southerleigh Fine Food & Brewery",
      address: "136 E Grayson St, San Antonio, TX 78215",
      lat: 29.4428,
      lng: -98.4788,
      cuisine: "Southern",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the patio. Southern cuisine and craft beer in the Pearl.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.southerleigh.com",
    },
    {
      name: "Alamo Beer Company",
      address: "202 Lamar St, San Antonio, TX 78202",
      lat: 29.4290,
      lng: -98.4690,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Extremely dog-friendly with a large outdoor beer garden. Dogs are beloved regulars.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.alamobeer.com",
    },
    {
      name: "Cured at Pearl",
      address: "306 Pearl Pkwy, San Antonio, TX 78215",
      lat: 29.4435,
      lng: -98.4785,
      cuisine: "Charcuterie & American",
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome on the outdoor seating area in the Pearl District.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.caboresto.com",
    },
  ],

  cafes: [
    {
      name: "Local Coffee at the Pearl",
      address: "302 Pearl Pkwy, San Antonio, TX 78215",
      lat: 29.4434,
      lng: -98.4786,
      dogPolicy: "Dogs welcome on the Pearl District patio. Quality coffee in a vibrant setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.localcoffeesa.com",
    },
    {
      name: "Estate Coffee Company",
      address: "1320 E Houston St, San Antonio, TX 78205",
      lat: 29.4270,
      lng: -98.4790,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Specialty coffee east of downtown.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.estatecoffee.com",
    },
    {
      name: "Rosella Coffee Company",
      address: "203 E Jones Ave, San Antonio, TX 78215",
      lat: 29.4420,
      lng: -98.4780,
      dogPolicy: "Dog-friendly patio near the Pearl. Known for their iced lavender latte.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.rosellacoffee.com",
    },
    {
      name: "Brown Coffee Co.",
      address: "1203 S Flores St, San Antonio, TX 78204",
      lat: 29.4150,
      lng: -98.4940,
      dogPolicy: "Leashed dogs welcome at outdoor tables. A Southtown coffee favorite.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.browncoffeeco.com",
    },
  ],

  dogParks: [
    {
      name: "McAllister Dog Park",
      address: "13102 Jones Maltsberger Rd, San Antonio, TX 78247",
      lat: 29.5480,
      lng: -98.4710,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: ["Separate small dog area", "Water stations", "Shade trees", "Agility equipment", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "San Antonio's most popular dog park features great shade, agility equipment, and separate areas for large and small dogs. The park stays green year-round with good maintenance.",
    },
    {
      name: "Pearsall Park Dog Area",
      address: "4700 Old Pearsall Rd, San Antonio, TX 78242",
      lat: 29.3530,
      lng: -98.5850,
      offLeash: true,
      fenced: true,
      acres: 6.0,
      amenities: ["Large open field", "Hill for running", "Water stations", "Shade structures", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A spacious south-side dog park with a unique hill feature that dogs love to sprint up and down. The large fenced area gives high-energy dogs plenty of room to burn off steam.",
    },
    {
      name: "San Antonio River Walk (Museum Reach)",
      address: "Pearl Pkwy, San Antonio, TX 78215",
      lat: 29.4400,
      lng: -98.4800,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Paved river trail", "Public art", "Restaurants nearby", "Benches", "Shade trees"],
      rating: 4.6,
      imageUrl: "",
      description:
        "The Museum Reach section of the River Walk is more spacious and dog-friendly than the downtown section. The shaded path along the San Antonio River connects the Pearl District to downtown with art and nature.",
    },
    {
      name: "Phil Hardberger Park",
      address: "13203 Blanco Rd, San Antonio, TX 78216",
      lat: 29.5420,
      lng: -98.5180,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Skywalk bridge", "Nature trails", "Dog park area", "Water stations", "Shade"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A 330-acre park connected by the world's first land bridge for wildlife and people. The dedicated dog park area is excellent, and the on-leash nature trails through the oak savanna are beautiful.",
    },
  ],
};
