export const sanLuisObispoData = {
  city: {
    name: "San Luis Obispo",
    state: "California",
    region: "West Coast",
    lat: 35.2828,
    lng: -120.6596,
    dogFriendlinessScore: 8,
    description:
      "Nestled between the rolling hills of the Central Coast and the Pacific Ocean, San Luis Obispo — or SLO as the locals call it — is a college town that lives up to its acronym with a relaxed, dog-adoring vibe. From the creekside downtown filled with dog-friendly patios to wine country trails and some of California's most beautiful beaches, SLO is where the good life comes with a wagging tail.",
    heroImage: "https://images.unsplash.com/photo-1504681869696-d977211a5f4c?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 47536,
  },

  hotels: [
    {
      name: "Hotel San Luis Obispo",
      address: "877 Palm St, San Luis Obispo, CA 93401",
      lat: 35.2805,
      lng: -120.6588,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a one-time fee. Rooftop pool and downtown location steps from the creek walk.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Rooftop pool", "Dog bed", "Bowls", "Treats", "Walking distance to downtown"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hotelsanluisobispo.com",
      phone: "(805) 235-0700",
    },
    {
      name: "Madonna Inn",
      address: "100 Madonna Rd, San Luis Obispo, CA 93405",
      lat: 35.2620,
      lng: -120.6810,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select themed rooms with advance notice. Stay in the Caveman Room or Safari Room with your pup.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Unique themed rooms", "Hiking trails on property", "Dog bowls", "Bakery on-site", "Pool"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.madonnainn.com",
      phone: "(805) 543-3000",
    },
    {
      name: "La Quinta Inn & Suites SLO",
      address: "1625 Calle Joaquin, San Luis Obispo, CA 93405",
      lat: 35.2560,
      lng: -120.6640,
      priceRange: "$$" as const,
      dogPolicy: "All dogs welcome with no pet fee. Budget-friendly and genuinely welcoming to pets of every size.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pool", "Walking area", "Complimentary breakfast", "Waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta",
      phone: "(805) 544-0700",
    },
    {
      name: "Granada Hotel & Bistro",
      address: "1126 Morro St, San Luis Obispo, CA 93401",
      lat: 35.2818,
      lng: -120.6610,
      priceRange: "$$$" as const,
      dogPolicy: "Small dogs welcome in boutique rooms with a pet fee. Historic downtown hotel with modern design.",
      maxDogWeight: 30,
      petFee: 50,
      amenities: ["Boutique rooms", "Downtown location", "Dog bed", "Rooftop terrace", "On-site restaurant"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.granadahotelandbistro.com",
      phone: "(805) 544-9100",
    },
    {
      name: "Apple Farm Inn",
      address: "2015 Monterey St, San Luis Obispo, CA 93401",
      lat: 35.2895,
      lng: -120.6575,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select ground-floor rooms with a nightly fee. Victorian charm with a working grist mill.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Dog bed", "Garden grounds", "Creek-side setting", "On-site restaurant", "Dog bowls"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.applefarm.com",
      phone: "(805) 544-2040",
    },
  ],

  nationalParks: [
    {
      name: "Channel Islands National Park",
      state: "California",
      lat: 34.0069,
      lng: -119.7785,
      dogPolicy: "Dogs are NOT allowed on any of the islands, trails, or beaches. Listed for awareness so dog owners can plan accordingly.",
      dogTrails: [],
      restrictions: [
        "No dogs allowed anywhere in the park",
        "No pets on the island ferries",
        "No exceptions for any reason",
      ],
      description:
        "These five islands off the coast are spectacularly wild but completely off-limits to dogs. Arrange pet care in SLO before visiting. The mainland visitor center in Ventura has a small area outside where leashed dogs can wait.",
      imageUrl: "",
      website: "https://www.nps.gov/chis",
    },
    {
      name: "Pinnacles National Park",
      state: "California",
      lat: 36.4906,
      lng: -121.1825,
      dogPolicy: "Dogs allowed on paved roads, in parking areas, and in the campground only. Not permitted on any trails or in the caves.",
      dogTrails: [
        "Campground area paths",
        "Parking area viewpoints",
      ],
      restrictions: [
        "No dogs on any trails",
        "Not allowed in talus caves",
        "Must be on leash (6 ft max)",
        "Not allowed in the wilderness",
      ],
      description:
        "Dramatic volcanic rock spires and talus caves make Pinnacles visually stunning, though dog access is very limited. The campground area and scenic drive still offer impressive views of the rock formations. About two hours north of SLO.",
      imageUrl: "",
      website: "https://www.nps.gov/pinn",
    },
    {
      name: "Montano de Oro State Park",
      state: "California",
      lat: 35.2720,
      lng: -120.8820,
      dogPolicy: "Leashed dogs welcome on the Bluff Trail and in the campground. Spectacular coastal cliffs and tide pools on SLO's doorstep.",
      dogTrails: [
        "Bluff Trail (4 miles along the coast)",
        "Campground area paths",
        "Spooner's Cove beach area",
        "Sandspit Beach",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Not allowed on most backcountry trails",
        "Not allowed in the natural preserve areas",
        "Watch for rogue waves on the bluffs",
      ],
      description:
        "Arguably the most stunning state park on the Central Coast, Montano de Oro features rugged coastal bluffs, tide pools, and eucalyptus groves. The Bluff Trail is a dog-walking masterpiece with crashing waves, sea stacks, and ocean spray.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/?page_id=592",
    },
  ],

  restaurants: [
    {
      name: "Novo Restaurant & Lounge",
      address: "726 Higuera St, San Luis Obispo, CA 93401",
      lat: 35.2795,
      lng: -120.6595,
      cuisine: "Global Fusion",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the stunning creekside patio. Global flavors under string lights along San Luis Creek.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.novorestaurant.com",
    },
    {
      name: "Firestone Grill",
      address: "1001 Higuera St, San Luis Obispo, CA 93401",
      lat: 35.2815,
      lng: -120.6590,
      cuisine: "BBQ & Tri-Tip",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the patio. Home of the legendary Central Coast tri-tip sandwich that your pup will beg for.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.firestonegrill.com",
    },
    {
      name: "SLO Brew Rock",
      address: "855 Aerovista Pl, San Luis Obispo, CA 93401",
      lat: 35.2340,
      lng: -120.6280,
      cuisine: "Brewery & American",
      priceRange: "$$" as const,
      dogPolicy: "Huge dog-friendly outdoor area with live music and beer garden. The ultimate SLO hangout for pups and their people.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.slobrew.com",
    },
    {
      name: "Luna Red",
      address: "1023 Chorro St, San Luis Obispo, CA 93401",
      lat: 35.2822,
      lng: -120.6612,
      cuisine: "Mediterranean & Latin",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the Mission Plaza patio. Tapas and craft cocktails next to the historic mission.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.lunaredslo.com",
    },
    {
      name: "Big Sky Cafe",
      address: "1121 Broad St, San Luis Obispo, CA 93401",
      lat: 35.2825,
      lng: -120.6580,
      cuisine: "Eclectic American",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly sidewalk tables. Creative comfort food with a global twist and Central Coast ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bigskycafe.com",
    },
    {
      name: "Taqueria Santa Cruz",
      address: "838 Higuera St, San Luis Obispo, CA 93401",
      lat: 35.2800,
      lng: -120.6592,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Outdoor ordering window with bench seating where dogs are welcome. Authentic tacos and burritos.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Woodstock's Pizza",
      address: "1000 Higuera St, San Luis Obispo, CA 93401",
      lat: 35.2812,
      lng: -120.6588,
      cuisine: "Pizza",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the patio. Cal Poly's favorite pizza spot with custom pies and a lively atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.woodstocksslo.com",
    },
    {
      name: "Giuseppe's Cucina Rustica",
      address: "849 Monterey St, San Luis Obispo, CA 93401",
      lat: 35.2812,
      lng: -120.6605,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the charming sidewalk patio. Rustic Italian cuisine with a Central Coast wine list.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.giuseppesrestaurant.com",
    },
  ],

  cafes: [
    {
      name: "Scout Coffee Co.",
      address: "1130 Garden St, San Luis Obispo, CA 93401",
      lat: 35.2818,
      lng: -120.6575,
      dogPolicy: "Shaded patio where dogs are beloved regulars. SLO's favorite specialty coffee roaster.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.scoutcoffee.com",
    },
    {
      name: "Kreuzberg Coffee",
      address: "685 Higuera St, San Luis Obispo, CA 93401",
      lat: 35.2788,
      lng: -120.6598,
      dogPolicy: "Bohemian coffee house with a dog-friendly courtyard. Live music, art, and excellent espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.kreuzbergcalifornia.com",
    },
    {
      name: "Ascendo Coffee",
      address: "1030 Court St, San Luis Obispo, CA 93401",
      lat: 35.2820,
      lng: -120.6600,
      dogPolicy: "Sidewalk seating available for pup parents. Single-origin pour-overs and seasonal drinks.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ascendocoffee.com",
    },
    {
      name: "Blackhorse Espresso & Bakery",
      address: "1030 Chorro St, San Luis Obispo, CA 93401",
      lat: 35.2823,
      lng: -120.6610,
      dogPolicy: "Covered patio perfect for dogs. Fresh pastries and strong coffee to start your Central Coast adventure.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.blackhorseespresso.com",
    },
    {
      name: "Sally Loo's Wholesome Cafe",
      address: "1804 Osos St, San Luis Obispo, CA 93401",
      lat: 35.2785,
      lng: -120.6540,
      dogPolicy: "Garden patio where leashed dogs are family. Farm-fresh brunch, local coffee, and a community vibe.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sallylooscafe.com",
    },
  ],

  dogParks: [
    {
      name: "SLO Dog Park (Laguna Lake)",
      address: "Madonna Rd & Dalidio Dr, San Luis Obispo, CA 93405",
      lat: 35.2585,
      lng: -120.6755,
      offLeash: true,
      fenced: true,
      acres: 4.0,
      amenities: ["Separate small dog area", "Water stations", "Shade structures", "Agility equipment", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "SLO's premier off-leash dog park next to Laguna Lake features separate areas for large and small dogs, agility equipment, and plenty of room to run. The lake trail nearby extends the adventure for leashed walks.",
    },
    {
      name: "Laguna Lake Natural Reserve",
      address: "Madonna Rd, San Luis Obispo, CA 93405",
      lat: 35.2580,
      lng: -120.6780,
      offLeash: false,
      fenced: false,
      acres: 50.0,
      amenities: ["Lake loop trail", "Bird watching", "Fishing pier", "Picnic areas", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A scenic loop trail around Laguna Lake with views of the surrounding volcanic peaks. Leashed dogs can enjoy birdwatching, lakeside walks, and the occasional encounter with ducks and geese.",
    },
    {
      name: "Cerro San Luis (Madonna Mountain) Trail",
      address: "Marsh St Trailhead, San Luis Obispo, CA 93401",
      lat: 35.2690,
      lng: -120.6680,
      offLeash: false,
      fenced: false,
      acres: 100.0,
      amenities: ["Summit trail", "360-degree views", "Wildflowers", "Parking", "Moderate difficulty"],
      rating: 4.7,
      imageUrl: "",
      description:
        "Hike to the summit of one of SLO's iconic volcanic morros for breathtaking 360-degree views of the city, coast, and wine country. Leashed dogs love this moderately challenging trail that rewards with one of the best views on the Central Coast.",
    },
    {
      name: "Bishop Peak Trail",
      address: "Highland Dr Trailhead, San Luis Obispo, CA 93405",
      lat: 35.2945,
      lng: -120.6890,
      offLeash: false,
      fenced: false,
      acres: 80.0,
      amenities: ["Summit hike", "Panoramic views", "Rocky terrain", "Parking", "Challenging sections"],
      rating: 4.6,
      imageUrl: "",
      description:
        "SLO's tallest morro peak at 1,559 feet offers a challenging but rewarding hike with your leashed dog through oak woodland and rocky outcrops. The summit views of the Pacific Ocean and Nine Sisters volcanic chain are unforgettable.",
    },
    {
      name: "San Luis Obispo Creek Walk",
      address: "Higuera St, San Luis Obispo, CA 93401",
      lat: 35.2800,
      lng: -120.6595,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Paved path", "Creek views", "Downtown access", "Benches", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A paved creekside path running through the heart of downtown SLO, connecting parks, restaurants, and shops. The perfect leashed dog walk with easy access to water bowls and treats at nearby dog-friendly businesses.",
    },
  ],
};
