export const sandpointData = {
  city: {
    name: "Sandpoint",
    state: "Idaho",
    region: "Pacific Northwest",
    lat: 48.2766,
    lng: -116.5535,
    dogFriendlinessScore: 8,
    description:
      "Sandpoint sits on the shores of Lake Pend Oreille, Idaho's largest lake, surrounded by the Selkirk and Cabinet Mountains. Dogs love this outdoorsy town for its beaches, mountain trails, and a walkable downtown with dog-friendly breweries and restaurants. The natural beauty is unmatched in the inland Northwest.",
    heroImage: "https://images.unsplash.com/photo-1439853949127-fa647821eba0?w=1200&fit=crop",
    climate: "Humid continental",
    population: 9100,
  },

  hotels: [
    {
      name: "Hotel Ruby Ponderay",
      address: "477026 US-95, Ponderay, ID 83852",
      lat: 48.3050,
      lng: -116.5340,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a per-night pet fee. Retro-modern hotel near the lake and downtown Sandpoint.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Dog bed", "Water bowls", "Near lake access", "Pet waste stations", "Grassy areas"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hotelruby.com",
      phone: "(208) 263-5383",
    },
    {
      name: "Best Western Edgewater Resort",
      address: "56 Bridge St, Sandpoint, ID 83864",
      lat: 48.2780,
      lng: -116.5510,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with lake views. Waterfront resort on the shores of Lake Pend Oreille.",
      maxDogWeight: 50,
      petFee: 40,
      amenities: ["Lake access", "Beach", "Dog bed", "Water bowls", "Walking paths"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(208) 263-3194",
    },
    {
      name: "La Quinta Inn & Suites Sandpoint",
      address: "415 Bonner Mall Way, Ponderay, ID 83852",
      lat: 48.3020,
      lng: -116.5360,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome at no extra charge. Convenient location near downtown.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Pet waste stations", "Grassy areas", "Near trails", "Water bowls at front desk"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta",
      phone: "(208) 263-1514",
    },
    {
      name: "Lodge at Sandpoint",
      address: "41 Lakeshore Dr, Sandpoint, ID 83864",
      lat: 48.2720,
      lng: -116.5550,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in lakefront suites. Private beach access and stunning mountain and lake views.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Private beach", "Lake views", "Dog bed", "Gourmet treats", "Walking paths"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.lodgeatsandpoint.com",
      phone: "(208) 263-2211",
    },
  ],

  nationalParks: [
    {
      name: "Idaho Panhandle National Forests",
      state: "Idaho",
      lat: 48.2000,
      lng: -116.5000,
      dogPolicy: "Dogs welcome on all trails. Leash in developed areas, voice control in backcountry.",
      dogTrails: ["Gold Hill Trail", "Mickinnick Trail", "Mineral Point Trail", "Trestle Creek Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control in backcountry",
        "Not allowed in developed swim areas",
      ],
      description:
        "The national forests surrounding Sandpoint offer endless trails through cedar forests, along mountain ridges, and past alpine lakes. The Selkirk and Cabinet ranges provide some of Idaho's most stunning backcountry adventures for dogs and their owners.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/ipnf",
    },
    {
      name: "Schweitzer Mountain Trails",
      state: "Idaho",
      lat: 48.3680,
      lng: -116.6230,
      dogPolicy: "Dogs welcome on all summer hiking trails. Chairlift rides available for dogs during summer season.",
      dogTrails: ["Schweitzer Basin Trail", "Summit Trail", "Lakeview Trail", "Music Mountain Loop"],
      restrictions: [
        "Must be under voice control",
        "Dogs ride the chairlift on owner's lap or at feet",
        "Not allowed in lodge restaurants",
      ],
      description:
        "In summer, Schweitzer Mountain Resort opens its trails and chairlifts to hikers and their dogs. The views from the top of Lake Pend Oreille and the surrounding mountains are spectacular, and dogs love the alpine meadows.",
      imageUrl: "",
      website: "https://www.schweitzer.com",
    },
    {
      name: "Farragut State Park",
      state: "Idaho",
      lat: 47.9610,
      lng: -116.5850,
      dogPolicy: "Leashed dogs welcome on trails and in the campground. Former naval training station on Lake Pend Oreille.",
      dogTrails: ["Shoreline Trail", "Bernard Peak Trail", "Whitetail Trail", "Eagle Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed on swim beaches during summer",
        "Clean up after your pet",
      ],
      description:
        "This 4,000-acre state park at the south end of Lake Pend Oreille offers forested trails, lake access, and wide open meadows. The former WWII naval training station has been transformed into a premier outdoor recreation area.",
      imageUrl: "",
      website: "https://parksandrecreation.idaho.gov/parks/farragut",
    },
  ],

  restaurants: [
    {
      name: "Pend d'Oreille Winery",
      address: "301 Cedar St, Sandpoint, ID 83864",
      lat: 48.2770,
      lng: -116.5530,
      cuisine: "Wine Bar & Small Plates",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the garden patio. Idaho wines paired with artisan small plates.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.pendoreillwinery.com",
    },
    {
      name: "MickDuff's Brewing Company",
      address: "312 N 1st Ave, Sandpoint, ID 83864",
      lat: 48.2785,
      lng: -116.5520,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio with a relaxed mountain town vibe. Local craft beer and pub food.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.mickduffs.com",
    },
    {
      name: "Tango Cafe",
      address: "210 N 1st Ave, Sandpoint, ID 83864",
      lat: 48.2780,
      lng: -116.5525,
      cuisine: "Mediterranean & International",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the heated patio. Creative international cuisine in downtown Sandpoint.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.tangocafesandpoint.com",
    },
    {
      name: "Beet & Basil Kitchen",
      address: "315 N 2nd Ave, Sandpoint, ID 83864",
      lat: 48.2788,
      lng: -116.5515,
      cuisine: "Farm-to-Table",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Fresh, locally sourced seasonal menu.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.beetandbasil.com",
    },
    {
      name: "Thai Nigiri",
      address: "221 N 1st Ave, Sandpoint, ID 83864",
      lat: 48.2782,
      lng: -116.5522,
      cuisine: "Thai & Sushi",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the sidewalk patio. Thai and Japanese fusion in a casual setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.thainigirisandpoint.com",
    },
  ],

  cafes: [
    {
      name: "Evans Brothers Coffee",
      address: "524 Church St, Sandpoint, ID 83864",
      lat: 48.2775,
      lng: -116.5540,
      dogPolicy: "Dogs welcome on the outdoor patio. Specialty coffee roasted locally in Sandpoint.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.evansbrotherscoffee.com",
    },
    {
      name: "Monarch Mountain Coffee",
      address: "208 N 1st Ave, Sandpoint, ID 83864",
      lat: 48.2778,
      lng: -116.5524,
      dogPolicy: "Outdoor seating welcomes dogs. Cozy downtown coffee shop with homemade baked goods.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.monarchmountaincoffee.com",
    },
    {
      name: "Panhandler Pies",
      address: "120 S 1st Ave, Sandpoint, ID 83864",
      lat: 48.2765,
      lng: -116.5528,
      dogPolicy: "Dog-friendly outdoor seating. Famous for handmade pies and espresso.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.panhandlerpies.com",
    },
    {
      name: "The Blend",
      address: "315 Church St, Sandpoint, ID 83864",
      lat: 48.2770,
      lng: -116.5535,
      dogPolicy: "Leashed dogs welcome at the patio tables. Smoothies, coffee, and healthy light fare.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.theblendsp.com",
    },
  ],

  dogParks: [
    {
      name: "Sandpoint Dog Park",
      address: "Larch St, Sandpoint, ID 83864",
      lat: 48.2810,
      lng: -116.5480,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Separate small dog area", "Water stations", "Waste bags", "Benches", "Shade"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Sandpoint's fenced off-leash dog park with separate areas for large and small dogs. A welcoming community spot where local and visiting dogs can play and socialize.",
    },
    {
      name: "City Beach Park",
      address: "100 Bridge St, Sandpoint, ID 83864",
      lat: 48.2770,
      lng: -116.5560,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Beach access", "Lake swimming", "Grassy areas", "Playground", "Restrooms", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Sandpoint's beautiful city beach on Lake Pend Oreille offers swimming, walking paths, and grassy areas. Leashed dogs can enjoy the beach outside of peak summer hours and the surrounding park year-round.",
    },
    {
      name: "Pine Street Woods",
      address: "Pine St, Sandpoint, ID 83864",
      lat: 48.2900,
      lng: -116.5600,
      offLeash: true,
      fenced: false,
      acres: 40.0,
      amenities: ["Forest trails", "Mountain biking", "Running paths", "Waste stations", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A community-managed trail system in the forest above Sandpoint. Dogs can run off-leash under voice control on miles of singletrack through cedar and pine forest. Shared with mountain bikers.",
    },
    {
      name: "Sandpoint Waterfront Path",
      address: "Sand Creek, Sandpoint, ID 83864",
      lat: 48.2760,
      lng: -116.5545,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Paved path", "Lake views", "Bridge crossings", "Benches", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A scenic waterfront path along Sand Creek and the Lake Pend Oreille shoreline in downtown Sandpoint. Leashed dogs love this easy walk with water views and bridge crossings.",
    },
  ],
};
