export const sanduskyData = {
  city: {
    name: "Sandusky",
    state: "Ohio",
    region: "Midwest",
    lat: 41.4489,
    lng: -82.7080,
    dogFriendlinessScore: 6,
    description:
      "Sandusky sits on Lake Erie's southern shore and is best known for Cedar Point, but this waterfront city also offers dog-friendly beaches, island ferries, and charming downtown spots. The lakefront trails and nearby islands provide wonderful adventures for dogs who love water.",
    heroImage: "https://images.unsplash.com/photo-1517483000871-1dbf64a6e1c6?w=1200&fit=crop",
    climate: "Humid continental with lake effect",
    population: 25793,
  },

  hotels: [
    {
      name: "Hotel Kilbourne",
      address: "229 W Water St, Sandusky, OH 44870",
      lat: 41.4505,
      lng: -82.7120,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome with a one-time pet fee. Boutique hotel in a restored historic building downtown.",
      maxDogWeight: 75,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Treats", "Downtown waterfront location", "Walking maps"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hotelkilbourne.com",
      phone: "(419) 503-0400",
    },
    {
      name: "Kalahari Resorts Sandusky",
      address: "7000 Kalahari Dr, Sandusky, OH 44870",
      lat: 41.4240,
      lng: -82.6610,
      priceRange: "$$$$" as const,
      dogPolicy: "Pets welcome in select rooms with a nightly fee. Massive resort with waterpark.",
      maxDogWeight: 80,
      petFee: 75,
      amenities: ["Spacious rooms", "Outdoor walking paths", "Near nature trails", "Resort amenities"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.kalahariresorts.com",
      phone: "(877) 525-2427",
    },
    {
      name: "Bayshore Resort",
      address: "1024 W Water St, Sandusky, OH 44870",
      lat: 41.4510,
      lng: -82.7220,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a pet deposit. Waterfront motel with bay views.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Bay views", "Outdoor area", "Near bike trail", "Waste stations"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.bayshoresandusky.com",
      phone: "(419) 625-6280",
    },
    {
      name: "Sleep Inn & Suites",
      address: "5509 Milan Rd, Sandusky, OH 44870",
      lat: 41.4150,
      lng: -82.6830,
      priceRange: "$" as const,
      dogPolicy: "Pets welcome with a nightly fee. Budget-friendly option near attractions.",
      maxDogWeight: 50,
      petFee: 20,
      amenities: ["Grassy area", "Near restaurants", "Complimentary breakfast", "Waste bags"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.choicehotels.com",
      phone: "(419) 625-1811",
    },
  ],

  nationalParks: [
    {
      name: "Kelleys Island State Park",
      state: "Ohio",
      lat: 41.5960,
      lng: -82.6970,
      dogPolicy: "Leashed dogs welcome on trails and beaches. Accessible by ferry from Sandusky.",
      dogTrails: ["North Shore Loop Trail", "Glacial Grooves Trail", "East Quarry Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on designated swimming beaches in summer",
        "Must be leashed on the ferry",
      ],
      description:
        "Kelleys Island in Lake Erie features unique glacial grooves, limestone caves, and scenic shoreline trails. The ferry ride is an adventure in itself, and dogs enjoy exploring the island's trails and quiet beaches.",
      imageUrl: "",
      website: "https://www.ohiodnr.gov/kelleysisland",
    },
    {
      name: "East Harbor State Park",
      state: "Ohio",
      lat: 41.5460,
      lng: -82.7910,
      dogPolicy: "Leashed dogs welcome on trails, in campgrounds, and on the beach outside of swim areas.",
      dogTrails: ["Lakeshore Trail", "Marsh Trail", "Nature Center Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not allowed in designated swimming areas",
        "Not allowed in nature center building",
      ],
      description:
        "Located on the Marblehead Peninsula, this park offers a beautiful Lake Erie beach, marshland trails, and campgrounds. Dogs love the beach walks and the birding-rich marsh areas.",
      imageUrl: "",
      website: "https://www.ohiodnr.gov/eastharbor",
    },
    {
      name: "Sheldon Marsh State Nature Preserve",
      state: "Ohio",
      lat: 41.4600,
      lng: -82.6390,
      dogPolicy: "Leashed dogs welcome on the boardwalk and beach trail. A pristine Lake Erie wetland.",
      dogTrails: ["Boardwalk Trail", "Beach Trail"],
      restrictions: [
        "Must be on leash",
        "Stay on boardwalk and designated paths",
        "Do not disturb nesting birds",
      ],
      description:
        "A rare undeveloped stretch of Lake Erie shoreline with a boardwalk through coastal marshes leading to a sandy beach. The diverse bird life and lake access make this a sensory wonderland for dogs.",
      imageUrl: "",
      website: "https://www.ohiodnr.gov/sheldonmarsh",
    },
  ],

  restaurants: [
    {
      name: "Small City Taphouse",
      address: "129 E Water St, Sandusky, OH 44870",
      lat: 41.4503,
      lng: -82.7085,
      cuisine: "Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio. Craft beer and elevated pub food downtown.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.smallcitytaphouse.com",
    },
    {
      name: "Dockside Cafe",
      address: "6 E Shoreline Dr, Sandusky, OH 44870",
      lat: 41.4520,
      lng: -82.7100,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the waterfront deck. Fresh Lake Erie perch and walleye.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.docksidecafe.com",
    },
    {
      name: "Barra",
      address: "133 E Water St, Sandusky, OH 44870",
      lat: 41.4504,
      lng: -82.7083,
      cuisine: "Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Fresh tacos and margaritas in a lively setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.barrasandusky.com",
    },
    {
      name: "Zinc Brasserie",
      address: "231 W Water St, Sandusky, OH 44870",
      lat: 41.4506,
      lng: -82.7122,
      cuisine: "French-American",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the seasonal outdoor patio.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.zincbrasserie.com",
    },
    {
      name: "Berardi's Family Kitchen",
      address: "1019 W Perkins Ave, Sandusky, OH 44870",
      lat: 41.4425,
      lng: -82.7200,
      cuisine: "American Comfort",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor picnic-style seating. Beloved local institution for fried perch.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.berardis.com",
    },
  ],

  cafes: [
    {
      name: "Sandusky Artisan Coffee",
      address: "135 Columbus Ave, Sandusky, OH 44870",
      lat: 41.4495,
      lng: -82.7090,
      dogPolicy: "Dogs welcome at outdoor tables. Specialty coffee and pastries in downtown.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.sanduskyartisancoffee.com",
    },
    {
      name: "Crush Wine Bar & Coffee",
      address: "145 Columbus Ave, Sandusky, OH 44870",
      lat: 41.4496,
      lng: -82.7088,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Coffee by morning, wine by evening.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.crushsandusky.com",
    },
    {
      name: "The Galley Coffee House",
      address: "216 E Water St, Sandusky, OH 44870",
      lat: 41.4505,
      lng: -82.7070,
      dogPolicy: "Leashed dogs welcome on the patio. Waterfront coffee with lake views.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.galleycoffee.com",
    },
    {
      name: "Brew & Beans",
      address: "125 E Market St, Sandusky, OH 44870",
      lat: 41.4485,
      lng: -82.7080,
      dogPolicy: "Dogs welcome at outdoor sidewalk seating. Fresh coffee and baked goods.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.brewandbeans.com",
    },
  ],

  dogParks: [
    {
      name: "Sandusky Bay Pathway",
      address: "W Shoreline Dr, Sandusky, OH 44870",
      lat: 41.4530,
      lng: -82.7150,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Paved pathway", "Bay views", "Benches", "Waste stations", "Public art"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A scenic paved trail along Sandusky Bay offering beautiful water views and passing boats. Dogs love the lakefront breezes and the activity of the waterfront while on a pleasant on-leash walk.",
    },
    {
      name: "Sandusky Dog Park",
      address: "1600 Tiffin Ave, Sandusky, OH 44870",
      lat: 41.4340,
      lng: -82.7180,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water fountains", "Shade shelters", "Waste stations", "Benches"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Sandusky's dedicated off-leash park features separate areas for large and small dogs. Well-maintained with good drainage, it stays usable even after Lake Erie rain.",
    },
    {
      name: "Battery Park",
      address: "E Water St, Sandusky, OH 44870",
      lat: 41.4520,
      lng: -82.7040,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Lake Erie waterfront", "Marina views", "Walking paths", "Picnic areas", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A waterfront park at the eastern end of downtown with sweeping Lake Erie views and marina activity. The on-leash walks along the water are a treat for dogs who love watching boats.",
    },
    {
      name: "Pipe Creek Wildlife Area",
      address: "Milan Rd, Sandusky, OH 44870",
      lat: 41.4100,
      lng: -82.7300,
      offLeash: false,
      fenced: false,
      acres: 100.0,
      amenities: ["Nature trails", "Wetland viewing", "Wildlife observation", "Parking", "Quiet setting"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A large wildlife area south of Sandusky offering natural trails through wetlands and fields. Dogs enjoy the diverse scents and terrain on this quieter, nature-focused outing.",
    },
  ],
};
