export const santaFeData = {
  city: {
    name: "Santa Fe",
    state: "New Mexico",
    region: "Southwest",
    lat: 35.687,
    lng: -105.9378,
    dogFriendlinessScore: 8,
    description:
      "The oldest capital city in the United States pairs ancient adobe architecture with a deeply dog-friendly culture. Santa Fe's high-desert trails, art-gallery-lined streets, and relaxed outdoor dining scene make it an ideal destination for traveling with your pup. The dry climate and cool mountain air at 7,000 feet keep tails wagging year-round.",
    heroImage: "https://images.unsplash.com/photo-1570639027793-70eb1718e8ed?w=1200&fit=crop",
    climate: "Semi-arid",
    population: 88875,
  },
  hotels: [
    {
      name: "La Fonda on the Plaza",
      address: "100 E San Francisco St, Santa Fe, NM 87501",
      lat: 35.6869,
      lng: -105.9371,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome. Historic landmark hotel right on the Plaza.",
      maxDogWeight: 0,
      petFee: 100,
      amenities: ["Dog bed", "Food and water bowls", "Treats at check-in", "Concierge walking recommendations"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.lafondasantafe.com/",
      phone: "(505) 982-5511",
    },
    {
      name: "The Inn of the Five Graces",
      address: "150 E DeVargas St, Santa Fe, NM 87501",
      lat: 35.6854,
      lng: -105.9362,
      priceRange: "$$$$" as const,
      dogPolicy: "Small and medium dogs welcome in select suites. Prior arrangement required.",
      maxDogWeight: 40,
      petFee: 150,
      amenities: ["Plush dog bed", "Gourmet treats", "Courtyard access", "Dog-sitting referrals"],
      rating: 4.9,
      imageUrl: "",
      website: "https://www.fivegraces.com/",
      phone: "(505) 992-0957",
    },
    {
      name: "Drury Plaza Hotel Santa Fe",
      address: "828 Paseo de Peralta, Santa Fe, NM 87501",
      lat: 35.6889,
      lng: -105.9410,
      priceRange: "$$" as const,
      dogPolicy: "Up to two pets per room with no breed restrictions.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Pet relief area", "Dog bowls on request", "Complimentary breakfast", "Evening snacks"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.druryhotels.com/locations/santa-fe-nm/drury-plaza-hotel-santa-fe",
      phone: "(505) 424-2175",
    },
    {
      name: "Hotel Chimayo de Santa Fe",
      address: "125 Washington Ave, Santa Fe, NM 87501",
      lat: 35.6884,
      lng: -105.9383,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome. Close to the Plaza with easy walking access.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Walking map of dog-friendly trails", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hotelchimayo.com/",
      phone: "(505) 988-4900",
    },
    {
      name: "El Rey Court",
      address: "1862 Cerrillos Rd, Santa Fe, NM 87505",
      lat: 35.6658,
      lng: -105.9611,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in designated pet-friendly rooms. Sprawling courtyard grounds to explore.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Courtyard grounds", "Dog bowls", "Outdoor fire pits", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.elreycourt.com/",
      phone: "(505) 982-1931",
    },
  ],
  nationalParks: [
    {
      name: "Bandelier National Monument",
      state: "New Mexico",
      lat: 35.7786,
      lng: -106.2713,
      dogPolicy: "Dogs allowed on the main paved trail (Main Loop Trail) and in parking areas only. Not permitted on backcountry trails or in cliff dwellings.",
      dogTrails: ["Main Loop Trail (paved section)"],
      restrictions: [
        "Dogs must be on a leash no longer than 6 feet",
        "Not allowed on backcountry trails",
        "Not permitted in cliff dwellings or laddered areas",
        "Not allowed on Alcove House Trail",
      ],
      description:
        "Ancient Puebloan cliff dwellings carved into volcanic tuff canyons. While dogs are restricted from most trails, the main paved loop offers stunning views of the ancestral homes carved into Frijoles Canyon walls.",
      imageUrl: "",
      website: "https://www.nps.gov/band/",
    },
    {
      name: "Pecos National Historical Park",
      state: "New Mexico",
      lat: 35.5601,
      lng: -105.6811,
      dogPolicy: "Leashed dogs welcome on the Ancestral Sites Trail and in picnic areas.",
      dogTrails: ["Ancestral Sites Trail", "Civil War Battlefield Trail"],
      restrictions: [
        "Must be on leash at all times",
        "Not permitted inside the visitor center",
        "Clean up after your dog",
      ],
      description:
        "Ruins of a once-thriving Pueblo and Spanish colonial mission set against the Sangre de Cristo Mountains. The trails wind past crumbling adobe walls and through open grasslands rich with history.",
      imageUrl: "",
      website: "https://www.nps.gov/peco/",
    },
    {
      name: "Valles Caldera National Preserve",
      state: "New Mexico",
      lat: 35.8628,
      lng: -106.5189,
      dogPolicy: "Leashed dogs allowed on designated trails and in the main meadow areas.",
      dogTrails: ["Valle Grande Trail", "Coyote Call Trail", "History Grove Trail"],
      restrictions: [
        "Leash required at all times",
        "Not allowed in elk-sensitive areas during calving season",
        "Must stay on designated trails",
      ],
      description:
        "A massive volcanic caldera filled with vast alpine meadows, elk herds, and mountain streams. The preserve offers wide-open landscapes at over 8,000 feet where leashed dogs can explore alongside their owners.",
      imageUrl: "",
      website: "https://www.nps.gov/vall/",
    },
    {
      name: "Kasha-Katuwe Tent Rocks National Monument",
      state: "New Mexico",
      lat: 35.6742,
      lng: -106.4172,
      dogPolicy: "Dogs are NOT permitted on any trails within the monument. Service animals only.",
      dogTrails: [],
      restrictions: [
        "No dogs allowed on any trails",
        "Service animals only",
        "Pets may not be left unattended in vehicles",
      ],
      description:
        "Dramatic cone-shaped rock formations created by volcanic eruptions millions of years ago. While dogs cannot join on the trails, the slot canyon and tent rock formations are worth a visit if a travel partner can stay with your pup.",
      imageUrl: "",
      website: "https://www.blm.gov/visit/kktr",
    },
  ],
  restaurants: [
    {
      name: "The Shed",
      address: "113 1/2 E Palace Ave, Santa Fe, NM 87501",
      lat: 35.6878,
      lng: -105.9369,
      cuisine: "New Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the charming courtyard patio.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sfshed.com/",
    },
    {
      name: "Cafe Pasqual's",
      address: "121 Don Gaspar Ave, Santa Fe, NM 87501",
      lat: 35.6869,
      lng: -105.9388,
      cuisine: "Southwestern Fusion",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome at the outdoor sidewalk tables.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.pasquals.com/",
    },
    {
      name: "Tomasita's",
      address: "500 S Guadalupe St, Santa Fe, NM 87501",
      lat: 35.6833,
      lng: -105.9432,
      cuisine: "New Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Dogs allowed on the covered patio. Famous for their sopapillas.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.tomasitas.com/",
    },
    {
      name: "Santa Fe Brewing Co. Taproom",
      address: "35 Fire Pl, Santa Fe, NM 87508",
      lat: 35.6186,
      lng: -105.9650,
      cuisine: "Brewery & Pub Food",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly brewery with a large outdoor beer garden.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://santafebrewing.com/",
    },
    {
      name: "Cowgirl BBQ",
      address: "319 S Guadalupe St, Santa Fe, NM 87501",
      lat: 35.6843,
      lng: -105.9429,
      cuisine: "BBQ & Southwestern",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the large outdoor patio and play area.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cowgirlsantafe.com/",
    },
    {
      name: "Paper Dosa",
      address: "1397 Cerrillos Rd, Santa Fe, NM 87505",
      lat: 35.6713,
      lng: -105.9574,
      cuisine: "South Indian",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome at outdoor tables.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.paperdosa.com/",
    },
    {
      name: "Palacio Cafe",
      address: "209 E Palace Ave, Santa Fe, NM 87501",
      lat: 35.6880,
      lng: -105.9359,
      cuisine: "American Brunch",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio seating area along Palace Avenue.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.palaciocafe.com/",
    },
    {
      name: "La Choza",
      address: "905 Alarid St, Santa Fe, NM 87505",
      lat: 35.6788,
      lng: -105.9452,
      cuisine: "New Mexican",
      priceRange: "$" as const,
      dogPolicy: "Small patio available for guests with leashed dogs.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.lazchoza.com/",
    },
  ],
  cafes: [
    {
      name: "Iconik Coffee Roasters",
      address: "1600 Lena St, Suite A, Santa Fe, NM 87505",
      lat: 35.6672,
      lng: -105.9627,
      dogPolicy: "Spacious dog-friendly patio with shade structures and water bowls.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.iconikco.com/",
    },
    {
      name: "Ohori's Coffee Roasters",
      address: "507 Old Santa Fe Trail, Santa Fe, NM 87501",
      lat: 35.6838,
      lng: -105.9373,
      dogPolicy: "Leashed dogs welcome on the outdoor patio overlooking the trail.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ohoris.com/",
    },
    {
      name: "Collected Works Bookstore & Coffeehouse",
      address: "202 Galisteo St, Santa Fe, NM 87501",
      lat: 35.6854,
      lng: -105.9393,
      dogPolicy: "Well-behaved dogs welcome at the outdoor cafe tables. A local literary institution.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.collectedworksbookstore.com/",
    },
    {
      name: "Java Joe's",
      address: "2801 Rodeo Rd, Santa Fe, NM 87507",
      lat: 35.6541,
      lng: -105.9655,
      dogPolicy: "Dogs allowed on the outdoor patio. Quick and friendly service.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.javajoessf.com/",
    },
    {
      name: "Better Day Coffee",
      address: "330 W San Francisco St, Santa Fe, NM 87501",
      lat: 35.6873,
      lng: -105.9412,
      dogPolicy: "Dog-loving cafe with a shaded courtyard patio and free treats for pups.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.betterdaycoffee.com/",
    },
  ],
  dogParks: [
    {
      name: "Frank S. Ortiz Dog Park",
      address: "160 Camino de las Crucitas, Santa Fe, NM 87501",
      lat: 35.6996,
      lng: -105.9523,
      offLeash: true,
      fenced: false,
      acres: 135.0,
      amenities: ["Hiking trails", "Open desert terrain", "Waste stations", "Parking area", "Mountain views"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A massive 135-acre off-leash paradise set in the high-desert foothills northwest of town. Rolling pinon- and juniper-covered hills crisscrossed by trails offer panoramic views of the Sangre de Cristo and Jemez Mountains.",
    },
    {
      name: "Herb Martinez/La Resolana Dog Park",
      address: "2240 Camino Carlos Rey, Santa Fe, NM 87507",
      lat: 35.6539,
      lng: -105.9647,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Fenced area", "Separate small dog section", "Water spigots", "Benches", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A well-maintained fenced dog park with separate areas for large and small dogs. The park features water access, shade structures, and a friendly community of local dog owners.",
    },
    {
      name: "Cañada de los Alamos Open Space",
      address: "101 Calle Atajo, Santa Fe, NM 87501",
      lat: 35.6721,
      lng: -105.9270,
      offLeash: true,
      fenced: false,
      acres: 20.0,
      amenities: ["Desert trails", "Arroyo access", "Waste stations", "Natural terrain"],
      rating: 4.2,
      imageUrl: "",
      description:
        "An open-space preserve with sandy arroyo trails winding through classic high-desert landscape. Dogs love exploring the natural terrain dotted with chamisa, cactus, and piñon trees.",
    },
    {
      name: "Salvador Perez Park Dog Area",
      address: "601 Alta Vista St, Santa Fe, NM 87505",
      lat: 35.6759,
      lng: -105.9536,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced enclosure", "Benches", "Shade structures", "Water fountain", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      description:
        "A compact, fully fenced off-leash area within the larger Salvador Perez Park complex. Convenient for downtown visitors looking for a quick and safe place to let dogs run.",
    },
    {
      name: "Arroyo de los Chamisos Trail & Dog Area",
      address: "Yucca St & Cerrillos Rd, Santa Fe, NM 87505",
      lat: 35.6650,
      lng: -105.9585,
      offLeash: true,
      fenced: false,
      acres: 8.0,
      amenities: ["Paved trail", "Natural arroyo", "Waste stations", "Bike-friendly path"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A multi-use trail corridor following a dry arroyo through south Santa Fe. The open areas along the trail serve as informal off-leash zones where dogs can run through the sandy wash.",
    },
  ],
};
