export const santaCruzData = {
  city: {
    name: "Santa Cruz",
    state: "California",
    region: "West Coast",
    lat: 36.9741,
    lng: -122.0308,
    dogFriendlinessScore: 8,
    description:
      "This laid-back surf town on Monterey Bay is a dog lover's dream with off-leash beaches, redwood forest trails, and a counter-culture vibe that celebrates four-legged friends. From beach bonfires to forest hikes, Santa Cruz keeps dogs entertained year-round.",
    heroImage: "https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 64608,
  },
  hotels: [
    {
      name: "Dream Inn Santa Cruz",
      address: "175 W Cliff Dr, Santa Cruz, CA 95060",
      lat: 36.9570,
      lng: -122.0280,
      priceRange: "$$$$" as const,
      dogPolicy: "Oceanfront hotel on Cowell Beach with pet-friendly rooms and ocean views. Dogs under 50 lbs welcome with a one-time fee.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Ocean view rooms", "Dog bed", "Beach access", "Water bowls", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.dreaminnsantacruz.com",
      phone: "(831) 426-4330",
    },
    {
      name: "Hotel Paradox",
      address: "611 Ocean St, Santa Cruz, CA 95060",
      lat: 36.9720,
      lng: -122.0260,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique hotel welcoming dogs of all sizes with a peaceful courtyard. Walking distance to downtown and the beach.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Courtyard", "Walking map", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hotelparadox.com",
      phone: "(831) 425-7100",
    },
    {
      name: "Pacific Blue Inn",
      address: "636 Pacific Ave, Santa Cruz, CA 95060",
      lat: 36.9730,
      lng: -122.0250,
      priceRange: "$$" as const,
      dogPolicy: "Eco-friendly boutique inn on Pacific Avenue with pet-friendly rooms. Small dogs welcome in a walkable downtown location.",
      maxDogWeight: 25,
      petFee: 50,
      amenities: ["Downtown location", "Dog bed", "Water bowls", "Green certification", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.pacificblueinn.com",
      phone: "(831) 600-8880",
    },
    {
      name: "Quality Inn Santa Cruz",
      address: "1500 Ocean St, Santa Cruz, CA 95060",
      lat: 36.9800,
      lng: -122.0230,
      priceRange: "$" as const,
      dogPolicy: "Affordable pet-friendly option with easy access to Highway 1 and local attractions. Dogs of most sizes welcome.",
      maxDogWeight: 75,
      petFee: 25,
      amenities: ["Pet-friendly rooms", "Parking", "Breakfast included", "Waste bags", "Pool"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.choicehotels.com",
      phone: "(831) 423-1300",
    },
  ],
  nationalParks: [
    {
      name: "Henry Cowell Redwoods State Park",
      state: "California",
      lat: 37.0400,
      lng: -122.0600,
      dogPolicy: "Dogs allowed on the paved loop trail through old-growth redwoods and on fire roads. Not permitted on most single-track trails.",
      dogTrails: ["Redwood Grove Loop Trail", "Pipeline Road", "Powder Mill Fire Road", "Ridge Fire Road"],
      restrictions: ["6-foot leash required", "Dogs only on paved paths and fire roads", "Not allowed on most hiking trails", "Clean up after pet"],
      description: "Home to ancient old-growth redwood trees, this state park lets dogs experience the magic of walking among towering coastal redwoods on the paved loop trail. The fire roads offer longer hikes through mixed forest terrain.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/henrycowell",
    },
    {
      name: "Wilder Ranch State Park",
      state: "California",
      lat: 36.9600,
      lng: -122.0800,
      dogPolicy: "Dogs allowed on the Old Cove Landing Trail along the coast on leash. Not permitted on inland trails.",
      dogTrails: ["Old Cove Landing Trail", "Ohlone Bluff Trail"],
      restrictions: ["6-foot leash required", "Only allowed on coastal trails", "Not permitted on inland trails", "Clean up after pet"],
      description: "Just north of Santa Cruz, Wilder Ranch offers dramatic coastal bluff trails where dogs can walk along cliffs above the crashing Pacific. The Old Cove Landing Trail is one of the most scenic coastal walks in Santa Cruz County.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/wilderranch",
    },
    {
      name: "Nisene Marks State Park",
      state: "California",
      lat: 37.0200,
      lng: -121.9000,
      dogPolicy: "Dogs allowed on fire roads and the paved Aptos Creek Road. Not permitted on single-track trails. A beautiful redwood forest experience.",
      dogTrails: ["Aptos Creek Fire Road", "Bridge Creek Trail (fire road section)", "West Ridge Trail"],
      restrictions: ["6-foot leash required", "Dogs only on fire roads", "Not allowed on hiking trails", "Park closes at sunset"],
      description: "This 10,000-acre park in Aptos Canyon offers a peaceful escape into second-growth redwood forest. While dogs are limited to fire roads, these wide paths wind through beautiful canyon scenery along Aptos Creek.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/nisenmarks",
    },
  ],
  restaurants: [
    {
      name: "Laili Restaurant",
      address: "101 Cooper St, Santa Cruz, CA 95060",
      lat: 36.9735,
      lng: -122.0260,
      cuisine: "Afghan-Mediterranean",
      priceRange: "$$$" as const,
      dogPolicy: "Elegant Afghan-Mediterranean restaurant with a courtyard patio welcoming dogs. Kebabs, stews, and house-made bread.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.lailirestaurant.com",
    },
    {
      name: "Hula's Island Grill",
      address: "221 Cathcart St, Santa Cruz, CA 95060",
      lat: 36.9740,
      lng: -122.0270,
      cuisine: "Hawaiian-Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Tropical-themed restaurant with a fun outdoor patio where dogs are welcome. Island-inspired cocktails and fresh fish tacos.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hulastiki.com",
    },
    {
      name: "The Picnic Basket",
      address: "125 Beach St, Santa Cruz, CA 95060",
      lat: 36.9640,
      lng: -122.0190,
      cuisine: "Café & Sandwiches",
      priceRange: "$" as const,
      dogPolicy: "Casual beachside café near the Boardwalk with outdoor seating. Dogs welcome while you enjoy sandwiches and fresh juices.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.thepicnicbasket.com",
    },
    {
      name: "Bantam",
      address: "1010 Fair Ave, Santa Cruz, CA 95060",
      lat: 36.9850,
      lng: -122.0180,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Seasonal farm-to-table restaurant with a garden patio that welcomes dogs. Creative tasting menus with local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bantam.restaurant",
    },
    {
      name: "Tacos Moreno",
      address: "1053 Water St, Santa Cruz, CA 95062",
      lat: 36.9710,
      lng: -122.0150,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Legendary local taqueria with outdoor picnic tables where dogs are welcome. Massive burritos and fresh salsas.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.tacosmoreno.com",
    },
  ],
  cafes: [
    {
      name: "Verve Coffee Roasters",
      address: "1540 Pacific Ave, Santa Cruz, CA 95060",
      lat: 36.9790,
      lng: -122.0260,
      dogPolicy: "Santa Cruz's premier specialty roaster with a spacious patio. Dogs are welcome outside while you enjoy world-class coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.vervecoffee.com",
    },
    {
      name: "Cat & Cloud Coffee",
      address: "3600 Portola Dr, Santa Cruz, CA 95062",
      lat: 36.9650,
      lng: -121.9900,
      dogPolicy: "Beloved local roaster with outdoor seating in the Pleasure Point area. Dogs welcome on the patio with treats available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.catandcloud.com",
    },
    {
      name: "Lulu Carpenter's",
      address: "763 Pacific Ave, Santa Cruz, CA 95060",
      lat: 36.9750,
      lng: -122.0250,
      dogPolicy: "Classic downtown café with a large garden patio where dogs are always welcome. Coffee, pastries, and light bites.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.lulucarpenters.com",
    },
    {
      name: "11th Hour Coffee",
      address: "848 Almar Ave, Santa Cruz, CA 95060",
      lat: 36.9700,
      lng: -122.0350,
      dogPolicy: "Westside neighborhood roaster with a relaxed patio vibe. Dogs are part of the community at this beloved local spot.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.11thhourcoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Its Beach (Lighthouse Field State Beach)",
      address: "W Cliff Dr & Pelton Ave, Santa Cruz, CA 95060",
      lat: 36.9530,
      lng: -122.0310,
      offLeash: true,
      fenced: false,
      acres: 6,
      amenities: ["Beach access", "Ocean views", "Lighthouse views", "Waste bag stations", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description: "The most popular off-leash dog beach in Santa Cruz, located below the iconic Lighthouse. Dogs run free on the sand, swim in the surf, and play with dozens of other dogs against a backdrop of Monterey Bay.",
    },
    {
      name: "DeLaveaga Dog Park",
      address: "100 DeLaveaga Park Dr, Santa Cruz, CA 95065",
      lat: 36.9820,
      lng: -122.0100,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Shade trees", "Benches", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "A well-maintained fenced dog park within the larger DeLaveaga Park complex. Shaded by oak and pine trees, it provides a comfortable off-leash area for dogs to socialize and play.",
    },
    {
      name: "Pogonip Open Space",
      address: "Golf Club Dr, Santa Cruz, CA 95060",
      lat: 36.9880,
      lng: -122.0400,
      offLeash: false,
      fenced: false,
      acres: 640,
      amenities: ["Hiking trails", "Meadows", "Forest paths", "Historic lime kilns", "Views"],
      rating: 4.5,
      imageUrl: "",
      description: "A vast open space preserve with miles of trails through meadows, oak woodlands, and redwood forests. While dogs must be on leash, the extensive trail network and varied terrain make it an excellent dog hiking destination.",
    },
    {
      name: "Arana Gulch Dog Area",
      address: "Arana Gulch Trail, Santa Cruz, CA 95062",
      lat: 36.9680,
      lng: -122.0100,
      offLeash: false,
      fenced: false,
      acres: 67,
      amenities: ["Paved multi-use trail", "Coastal views", "Meadows", "Wildlife viewing", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description: "A greenbelt park with a paved trail connecting the harbor to the east side, winding through meadows with Monterey Bay views. Leashed dogs enjoy the gentle terrain and coastal breezes.",
    },
  ],
};
