export const santaBarbaraData = {
  city: {
    name: "Santa Barbara",
    state: "California",
    region: "West Coast",
    lat: 34.4208,
    lng: -119.6982,
    dogFriendlinessScore: 8,
    description:
      "Known as the American Riviera, Santa Barbara combines stunning beaches, Mediterranean architecture, and a wine country culture that enthusiastically welcomes dogs. With off-leash beaches, mountain hiking, and some of the best dog-friendly patios on the Central Coast, it's a top-tier destination for pups.",
    heroImage: "https://images.unsplash.com/photo-1553653924-39b70a080c80?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 88665,
  },
  hotels: [
    {
      name: "Kimpton Canary Hotel",
      address: "31 W Carrillo St, Santa Barbara, CA 93101",
      lat: 34.4215,
      lng: -119.7010,
      priceRange: "$$$$" as const,
      dogPolicy: "Kimpton's all-pets-welcome policy with no size or breed restrictions. Rooftop pool and downtown location steps from State Street.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treats", "Loaner leashes", "Rooftop pool"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.canarysantabarbara.com",
      phone: "(805) 884-0300",
    },
    {
      name: "Hotel Californian",
      address: "36 State St, Santa Barbara, CA 93101",
      lat: 34.4175,
      lng: -119.6920,
      priceRange: "$$$$" as const,
      dogPolicy: "Luxury waterfront hotel welcoming dogs under 50 lbs. Moorish-inspired architecture and ocean views with pet-friendly rooms.",
      maxDogWeight: 50,
      petFee: 150,
      amenities: ["Dog bed", "Gourmet treats", "Water bowls", "Waterfront walking", "Pet concierge"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.hotelcalifornian.com",
      phone: "(805) 882-0100",
    },
    {
      name: "The Wayfarer",
      address: "12 E Montecito St, Santa Barbara, CA 93101",
      lat: 34.4180,
      lng: -119.6970,
      priceRange: "$$" as const,
      dogPolicy: "Boutique hostel-hotel hybrid with pet-friendly private rooms. Dogs welcome with advance notice in a walkable downtown location.",
      maxDogWeight: 40,
      petFee: 50,
      amenities: ["Pet-friendly rooms", "Communal lounge", "Walking distance to beach", "Waste bags", "Water bowls"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.pacificahotels.com/the-wayfarer",
      phone: "(805) 845-1000",
    },
    {
      name: "Motel 6 Santa Barbara Beach",
      address: "443 Corona Del Mar Dr, Santa Barbara, CA 93103",
      lat: 34.4250,
      lng: -119.7100,
      priceRange: "$" as const,
      dogPolicy: "Budget-friendly motel near Leadbetter Beach welcoming dogs of all sizes. No pet fee makes it accessible for all travelers.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Pet-friendly rooms", "Beach proximity", "Parking", "Waste bags", "Pool"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.motel6.com",
      phone: "(805) 564-1392",
    },
  ],
  nationalParks: [
    {
      name: "Los Padres National Forest",
      state: "California",
      lat: 34.6000,
      lng: -119.7000,
      dogPolicy: "Dogs welcome on most trails on leash. Vast forest covering the mountains behind Santa Barbara with extensive trail networks.",
      dogTrails: ["Jesusita Trail", "Rattlesnake Canyon Trail", "Cold Spring Trail", "San Ysidro Trail"],
      restrictions: ["Leash required on most trails", "Adventure Pass required for some trailheads", "Fire restrictions may apply", "Carry extra water in warm months"],
      description: "The Los Padres National Forest rises dramatically behind Santa Barbara, offering hundreds of miles of dog-friendly trails through chaparral, oak woodlands, and pine forests. Many trails lead to swimming holes and panoramic ocean views.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/lpnf",
    },
    {
      name: "Channel Islands National Park (Visitor Center)",
      state: "California",
      lat: 34.4110,
      lng: -119.6850,
      dogPolicy: "Dogs are not allowed on the Channel Islands, but the Santa Barbara harbor area and nearby beaches welcome leashed dogs for waterfront walks.",
      dogTrails: ["Santa Barbara Harbor Walk", "Shoreline Park Trail"],
      restrictions: ["No dogs on Channel Islands", "Leash required on harbor trails", "Clean up after pet"],
      description: "While the islands are off-limits to dogs, the Santa Barbara waterfront near the Channel Islands visitor information offers beautiful harbor walks. Shoreline Park adjacent to the harbor provides stunning coastal trails for leashed dogs.",
      imageUrl: "",
      website: "https://www.nps.gov/chis",
    },
    {
      name: "Gaviota State Park",
      state: "California",
      lat: 34.4700,
      lng: -120.2280,
      dogPolicy: "Dogs allowed on the beach on leash and on select trails. A beautiful coastal park with beach access and mountain hiking.",
      dogTrails: ["Gaviota Peak Trail", "Beach Trail", "Trespass Trail"],
      restrictions: ["6-foot leash required", "Dogs not allowed in creek areas during steelhead season", "Day use fee required", "Carry water on peak trail"],
      description: "West of Santa Barbara, Gaviota State Park offers a dramatic coastal setting with a beach, hot springs, and a trail to Gaviota Peak with sweeping ocean views. Dogs can join their owners for beach walks and mountain hikes.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/gaviota",
    },
  ],
  restaurants: [
    {
      name: "The Lark",
      address: "131 Anacapa St, Santa Barbara, CA 93101",
      lat: 34.4190,
      lng: -119.6960,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Award-winning restaurant in a converted fish market with a gorgeous patio that welcomes dogs. Shareable plates and craft cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.thelarksb.com",
    },
    {
      name: "Mony's Mexican Food",
      address: "4650 Calle Real, Santa Barbara, CA 93110",
      lat: 34.4400,
      lng: -119.7600,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Beloved local taqueria with a casual outdoor patio where dogs are always welcome. Authentic tacos and burritos.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.monysmexicanfood.com",
    },
    {
      name: "Loquita",
      address: "202 State St, Santa Barbara, CA 93101",
      lat: 34.4185,
      lng: -119.6945,
      cuisine: "Spanish",
      priceRange: "$$$" as const,
      dogPolicy: "Vibrant Spanish tapas restaurant with a lively outdoor patio welcoming dogs. Paella, pintxos, and an excellent Spanish wine list.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.loquitasb.com",
    },
    {
      name: "The Shop Kitchen",
      address: "730 N Milpas St, Santa Barbara, CA 93103",
      lat: 34.4260,
      lng: -119.6860,
      cuisine: "Café & Sandwiches",
      priceRange: "$$" as const,
      dogPolicy: "Hip east-side café with a spacious dog-friendly patio. Creative sandwiches and seasonal salads in a relaxed garden setting.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.theshopkitchen.com",
    },
    {
      name: "Brophy Bros Clam Bar & Restaurant",
      address: "119 Harbor Way, Santa Barbara, CA 93109",
      lat: 34.4060,
      lng: -119.6930,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Iconic harbor seafood restaurant with waterfront patio seating where dogs are welcome. Fresh catches and harbor views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.brophybros.com",
    },
  ],
  cafes: [
    {
      name: "Handlebar Coffee Roasters",
      address: "128 E Canon Perdido St, Santa Barbara, CA 93101",
      lat: 34.4210,
      lng: -119.6960,
      dogPolicy: "Third-wave coffee shop in a converted auto garage with a patio where dogs are welcome. Locally roasted specialty coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.handlebarcoffee.com",
    },
    {
      name: "French Press",
      address: "1101 State St, Santa Barbara, CA 93101",
      lat: 34.4240,
      lng: -119.7030,
      dogPolicy: "State Street café with a sidewalk patio where dogs are welcome. French-inspired coffee drinks and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.frenchpresssb.com",
    },
    {
      name: "Dune Coffee Roasters",
      address: "1011 State St, Santa Barbara, CA 93101",
      lat: 34.4235,
      lng: -119.7025,
      dogPolicy: "Specialty roaster with a light-filled space and outdoor seating where dogs are welcome. Single-origin coffees and house-made pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.dunecoffee.com",
    },
    {
      name: "Caje Coffee",
      address: "1026 State St, Santa Barbara, CA 93101",
      lat: 34.4237,
      lng: -119.7027,
      dogPolicy: "Trendy State Street café with outdoor seating and dog-friendly vibes. Specialty espresso and smoothie bowls.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cajecoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Douglas Family Preserve",
      address: "Medcliff Rd, Santa Barbara, CA 93109",
      lat: 34.4020,
      lng: -119.7170,
      offLeash: true,
      fenced: false,
      acres: 70,
      amenities: ["Ocean views", "Cliff trails", "Shade trees", "Open meadows", "Waste bag stations"],
      rating: 4.8,
      imageUrl: "",
      description: "Santa Barbara's crown jewel off-leash park sits on bluffs overlooking the Pacific with sweeping ocean and island views. Seventy acres of meadows, trails through eucalyptus groves, and stunning cliff-edge paths make it one of the best dog parks in California.",
    },
    {
      name: "Hendry's Beach (Arroyo Burro Beach)",
      address: "2981 Cliff Dr, Santa Barbara, CA 93109",
      lat: 34.4030,
      lng: -119.7410,
      offLeash: true,
      fenced: false,
      acres: 5,
      amenities: ["Beach access", "Ocean swimming", "Restaurant nearby", "Parking", "Waste bag stations"],
      rating: 4.7,
      imageUrl: "",
      description: "One of the most beloved off-leash dog beaches in California, Hendry's offers a wide sandy stretch where dogs run free, swim in the waves, and socialize. The adjacent Douglas Family Preserve creates a seamless beach-to-bluff dog paradise.",
    },
    {
      name: "Tucker's Grove Dog Park",
      address: "805 San Antonio Creek Rd, Santa Barbara, CA 93111",
      lat: 34.4450,
      lng: -119.7700,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Water stations", "Shade trees", "Benches", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "A fenced off-leash park within the larger Tucker's Grove County Park, offering separate areas for large and small dogs. Mature oak trees provide shade, and the adjacent picnic areas make it great for a full day outing.",
    },
    {
      name: "Elings Park Off-Leash Area",
      address: "1298 Las Positas Rd, Santa Barbara, CA 93105",
      lat: 34.4180,
      lng: -119.7230,
      offLeash: true,
      fenced: false,
      acres: 10,
      amenities: ["Hilltop trails", "Ocean views", "Open fields", "Parking", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "A large off-leash area within Elings Park on a hilltop with panoramic views of the ocean, mountains, and city. Open grassy fields and trails give dogs plenty of room to run while owners enjoy spectacular scenery.",
    },
  ],
};
