export const saratogaSpringsData = {
  city: {
    name: "Saratoga Springs",
    state: "New York",
    region: "Northeast",
    lat: 43.0831,
    lng: -73.7846,
    dogFriendlinessScore: 8,
    description:
      "This elegant spa town in upstate New York combines mineral springs, horse racing culture, and a vibrant downtown that loves dogs. Saratoga Spa State Park offers miles of trails through pine forests, and Broadway's restaurant row features dog-friendly patios galore.",
    heroImage: "https://images.unsplash.com/photo-1520962880247-cfaf541c8724?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 28491,
  },
  hotels: [
    {
      name: "The Adelphi Hotel",
      address: "365 Broadway, Saratoga Springs, NY 12866",
      lat: 43.0815,
      lng: -73.7854,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs under 40 lbs welcome with a $100 per stay fee. Luxury pet amenities including designer dog bed and gourmet treats.",
      maxDogWeight: 40,
      petFee: 100,
      amenities: ["Designer dog bed", "Gourmet treats", "Broadway location", "Pool", "Spa"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.theadelphihotel.com",
      phone: "(518) 678-6000",
    },
    {
      name: "The Saratoga Hilton",
      address: "534 Broadway, Saratoga Springs, NY 12866",
      lat: 43.0803,
      lng: -73.7857,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome with a $75 non-refundable fee. Connected to the City Center with direct downtown access.",
      maxDogWeight: 75,
      petFee: 75,
      amenities: ["Downtown location", "Indoor pool", "Restaurant", "City Center access"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.saratogahilton.com",
      phone: "(518) 584-4000",
    },
    {
      name: "Saratoga Arms",
      address: "497 Broadway, Saratoga Springs, NY 12866",
      lat: 43.0807,
      lng: -73.7855,
      priceRange: "$$$" as const,
      dogPolicy: "Pet-friendly rooms in this boutique inn with a $50 per stay fee. Concierge provides dog-friendly dining and trail recommendations.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Boutique inn", "Concierge", "Full breakfast", "Broadway location", "Porch seating"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.saratogaarms.com",
      phone: "(518) 584-1775",
    },
    {
      name: "Residence Inn Saratoga Springs",
      address: "295 Excelsior Ave, Saratoga Springs, NY 12866",
      lat: 43.0628,
      lng: -73.7755,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a $100 non-refundable fee. Suite-style rooms with full kitchens and a pet relief area.",
      maxDogWeight: 0,
      petFee: 100,
      amenities: ["Full kitchen", "Pet relief area", "Free breakfast", "Pool", "Near Spa State Park"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(518) 584-9600",
    },
  ],
  nationalParks: [
    {
      name: "Saratoga Spa State Park",
      state: "New York",
      lat: 43.0582,
      lng: -73.7904,
      dogPolicy: "Leashed dogs welcome on all trails and park grounds. Miles of wooded trails through mineral spring territory.",
      dogTrails: ["Geyser Creek Trail", "Ferndell Trail", "Avenue of the Pines", "Perimeter Trail"],
      restrictions: ["Leash required", "No dogs in pool complex", "Clean up required"],
      description:
        "A 2,379-acre park famous for its natural mineral springs, this is a dog walker's paradise. Trails wind through towering pine forests past bubbling mineral springs and classical architecture. The Avenue of the Pines is a grand promenade, and the Geyser Creek Trail follows a spring-fed creek through a magical forest.",
      imageUrl: "",
      website: "https://parks.ny.gov/parks/saratogaspa",
    },
    {
      name: "Saratoga National Historical Park",
      state: "New York",
      lat: 42.9976,
      lng: -73.6391,
      dogPolicy: "Leashed dogs welcome on all trails and the tour road. Walk the battlefield where American independence was won.",
      dogTrails: ["Battlefield Trail", "Wilkinson Trail", "Boot Monument Trail", "Tour Road Walk"],
      restrictions: ["Leash required", "No dogs inside buildings", "Clean up required"],
      description:
        "The site of the turning point of the American Revolution offers rolling meadows, wooded trails, and sweeping Hudson Valley views. Your leashed dog can explore the same ground where a decisive battle changed history. The quiet beauty of the battlefield is a peaceful contrast to downtown Saratoga's bustle.",
      imageUrl: "",
      website: "https://www.nps.gov/sara",
    },
    {
      name: "Moreau Lake State Park",
      state: "New York",
      lat: 43.2313,
      lng: -73.7128,
      dogPolicy: "Leashed dogs welcome on all trails and in campground. A beautiful lake setting with mountain views.",
      dogTrails: ["Western Ridge Trail", "Nature Trail", "Lake Trail", "Red Oak Ridge Trail"],
      restrictions: ["Leash required", "No dogs on beach", "Clean up required"],
      description:
        "Just 20 minutes from Saratoga Springs, this state park wraps around a pristine lake with forested trails climbing to ridge-top overlooks. The Western Ridge Trail offers stunning views of the lake and distant Adirondack peaks. Dogs love the forest trails and the quiet lakeside atmosphere.",
      imageUrl: "",
      website: "https://parks.ny.gov/parks/moreaulake",
    },
  ],
  restaurants: [
    {
      name: "Hattie's Restaurant",
      address: "45 Phila St, Saratoga Springs, NY 12866",
      lat: 43.0827,
      lng: -73.7842,
      cuisine: "Southern",
      priceRange: "$$" as const,
      dogPolicy: "Legendary Saratoga fried chicken spot with outdoor seating. Leashed dogs welcome on the patio.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hattiesrestaurant.com",
    },
    {
      name: "Druthers Brewing Company",
      address: "381 Broadway, Saratoga Springs, NY 12866",
      lat: 43.0814,
      lng: -73.7854,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Spacious outdoor beer garden on Broadway is very dog-friendly. House-brewed beers and elevated pub fare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.druthersbrewing.com",
    },
    {
      name: "The Local Pub & Teahouse",
      address: "142 Grand Ave, Saratoga Springs, NY 12866",
      lat: 43.0823,
      lng: -73.7797,
      cuisine: "Farm-to-Table",
      priceRange: "$$" as const,
      dogPolicy: "Community-focused restaurant with a dog-friendly garden patio. Locally sourced seasonal menu.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thelocalpubandteahouse.com",
    },
    {
      name: "Max London's",
      address: "466 Broadway, Saratoga Springs, NY 12866",
      lat: 43.0809,
      lng: -73.7856,
      cuisine: "American",
      priceRange: "$$$" as const,
      dogPolicy: "Upscale Broadway dining with a dog-friendly sidewalk patio. Creative American cuisine with a wood-fired oven.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.maxlondons.com",
    },
    {
      name: "9 Maple Avenue",
      address: "9 Maple Ave, Saratoga Springs, NY 12866",
      lat: 43.0826,
      lng: -73.7866,
      cuisine: "American",
      priceRange: "$$$" as const,
      dogPolicy: "Jazz bar with seasonal sidewalk seating. Dogs welcome outside while you enjoy craft cocktails and live music.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.9mapleave.com",
    },
  ],
  cafes: [
    {
      name: "Uncommon Grounds",
      address: "402 Broadway, Saratoga Springs, NY 12866",
      lat: 43.0812,
      lng: -73.7855,
      dogPolicy: "Saratoga's go-to coffee spot with sidewalk seating on Broadway. Dogs welcome at outdoor tables year-round.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.uncommongrounds.com",
    },
    {
      name: "Mouzon House Coffee",
      address: "1 York St, Saratoga Springs, NY 12866",
      lat: 43.0828,
      lng: -73.7883,
      dogPolicy: "Garden cafe in a historic setting. Leashed dogs welcome in the courtyard while you enjoy espresso and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Caffe Lena Cafe",
      address: "47 Phila St, Saratoga Springs, NY 12866",
      lat: 43.0827,
      lng: -73.7841,
      dogPolicy: "Historic folk music venue with a cafe and outdoor seating. Dogs welcome on the patio at this beloved Saratoga institution.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.caffelena.org",
    },
    {
      name: "Spring Street Deli & Pizzeria Coffee Bar",
      address: "131 S Broadway, Saratoga Springs, NY 12866",
      lat: 43.078,
      lng: -73.7849,
      dogPolicy: "Casual coffee counter with outdoor benches. A quick stop for coffee and a pastry while walking your dog on Broadway.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.1,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Saratoga Spa State Park Dog Walk Area",
      address: "19 Roosevelt Dr, Saratoga Springs, NY 12866",
      lat: 43.0582,
      lng: -73.7904,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Forest trails", "Mineral springs", "Parking", "Restrooms", "Picnic areas"],
      rating: 4.6,
      imageUrl: "",
      description:
        "The expansive trail system within Saratoga Spa State Park offers miles of wooded paths through towering pines, past mineral springs, and along Geyser Creek. While leashes are required, the trails are wide and varied enough to give your dog an excellent adventure. The pine-scented air is invigorating.",
    },
    {
      name: "Saratoga Dog Park at East Side Recreation",
      address: "13 Vanderbilt Ave, Saratoga Springs, NY 12866",
      lat: 43.0846,
      lng: -73.7759,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fully fenced", "Separate small dog area", "Water station", "Benches", "Agility equipment"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Saratoga's dedicated off-leash dog park features separate areas for large and small dogs, agility equipment, and plenty of shade. The well-maintained space attracts a friendly community of regulars. Conveniently located near downtown for a quick post-brunch romp.",
    },
    {
      name: "Congress Park",
      address: "Broadway & Spring St, Saratoga Springs, NY 12866",
      lat: 43.0792,
      lng: -73.7856,
      offLeash: false,
      fenced: false,
      acres: 17.0,
      amenities: ["Historic fountains", "Mineral springs", "Walking paths", "Gardens", "Benches"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A beautiful Victorian park in the heart of downtown with winding paths, historic mineral springs, a reflecting pool, and the Canfield Casino. Your leashed dog can enjoy a genteel stroll past Daniel Chester French sculptures and lush gardens. The park connects directly to Broadway's shops and restaurants.",
    },
    {
      name: "Bog Meadow Brook Nature Trail",
      address: "Meadowbrook Rd, Saratoga Springs, NY 12866",
      lat: 43.0731,
      lng: -73.7527,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Boardwalk sections", "Wetland views", "Bird watching", "Peaceful setting", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A peaceful 2-mile nature trail following a brook through wetlands and woods on the eastern edge of Saratoga Springs. Boardwalk sections keep paws dry over marshy areas, and the rich wetland ecosystem provides endless sniffing opportunities. A quiet escape from the bustle of Broadway.",
    },
  ],
};
