export const sarasotaData = {
  city: {
    name: "Sarasota",
    state: "Florida",
    region: "Southeast",
    lat: 27.3364,
    lng: -82.5307,
    dogFriendlinessScore: 7,
    description:
      "Where white-sand beaches meet a thriving arts scene, Sarasota is a Gulf Coast gem that welcomes pups with open arms and sandy paws. From the legendary dog beach on Siesta Key to dog-friendly dining along St. Armands Circle, this sunny paradise proves that the good life in Florida absolutely includes your four-legged family.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&fit=crop",
    climate: "Tropical",
    population: 57738,
  },

  hotels: [
    {
      name: "The Ritz-Carlton Sarasota",
      address: "1111 Ritz-Carlton Dr, Sarasota, FL 34236",
      lat: 27.3345,
      lng: -82.5438,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 30 lbs welcome with luxury pet amenities. White-glove treatment for your pampered pup.",
      maxDogWeight: 30,
      petFee: 150,
      amenities: ["Luxury dog bed", "Gourmet treats", "Water bowls", "Dog walking service", "Pet-sitting referral"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.ritzcarlton.com/sarasota",
      phone: "(941) 309-2000",
    },
    {
      name: "Hotel Indigo Sarasota",
      address: "1223 Boulevard of the Arts, Sarasota, FL 34236",
      lat: 27.3380,
      lng: -82.5405,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with no pet fee. Boutique style in the arts district with pup-forward hospitality.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Dog bed", "Bowls", "Walking route maps", "Near bayfront park"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ihg.com/hotelindigo",
      phone: "(941) 487-3800",
    },
    {
      name: "Art Ovation Hotel",
      address: "1255 N Palm Ave, Sarasota, FL 34236",
      lat: 27.3395,
      lng: -82.5375,
      priceRange: "$$$" as const,
      dogPolicy: "Pet-friendly rooms with a creative flair. Dogs welcome with a one-time fee in this arts-inspired boutique hotel.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Water bowls", "Art supplies for humans", "Rooftop pool"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.artovationhotel.com",
      phone: "(941) 316-0808",
    },
    {
      name: "Hyatt Regency Sarasota",
      address: "1000 Boulevard of the Arts, Sarasota, FL 34236",
      lat: 27.3370,
      lng: -82.5420,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome in select rooms. Bayfront location with marina views.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Dog bed", "Food and water bowls", "Marina walking paths", "Bayfront access", "Concierge"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.hyatt.com",
      phone: "(941) 953-1234",
    },
    {
      name: "La Quinta Inn & Suites Sarasota Downtown",
      address: "1803 N Tamiami Trail, Sarasota, FL 34234",
      lat: 27.3485,
      lng: -82.5345,
      priceRange: "$$" as const,
      dogPolicy: "All dogs welcome with no pet fee or size limit. Budget-friendly and genuinely dog-loving.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Grassy walking area", "Pool", "Complimentary breakfast", "Waste stations"],
      rating: 3.9,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta",
      phone: "(941) 366-5128",
    },
  ],

  nationalParks: [
    {
      name: "Everglades National Park",
      state: "Florida",
      lat: 25.2866,
      lng: -80.8987,
      dogPolicy: "Dogs allowed in campgrounds, on paved roads, and in parking areas only. Very limited access for pets due to wildlife protection.",
      dogTrails: [
        "Long Pine Key Campground area",
        "Flamingo Campground roads",
        "Main park road pullouts",
      ],
      restrictions: [
        "No dogs on any trails or boardwalks",
        "Must be on leash (6 ft max) at all times",
        "Not allowed on boats or in backcountry",
        "Alligator and wildlife danger — never leave dog unattended",
      ],
      description:
        "The vast River of Grass is home to alligators, manatees, and the Florida panther. While dog access is extremely limited, the scenic drive and campground areas still offer a taste of this unique subtropical wilderness. A three-hour drive from Sarasota.",
      imageUrl: "",
      website: "https://www.nps.gov/ever",
    },
    {
      name: "De Soto National Memorial",
      state: "Florida",
      lat: 27.5230,
      lng: -82.6430,
      dogPolicy: "Leashed dogs welcome on the nature trail and grounds. A small but scenic NPS site right near Sarasota.",
      dogTrails: [
        "De Soto Nature Trail",
        "Cove Shoreline Walk",
        "Memorial grounds paths",
      ],
      restrictions: [
        "Must be on leash (6 ft max)",
        "Not allowed in the visitor center",
        "Watch for fire ants and wildlife",
      ],
      description:
        "This intimate memorial on Tampa Bay commemorates Hernando de Soto's 1539 expedition. A half-mile nature trail through mangrove forest leads to a beautiful shoreline where leashed dogs can enjoy the bay breeze. Just 30 minutes from Sarasota.",
      imageUrl: "",
      website: "https://www.nps.gov/deso",
    },
    {
      name: "Dry Tortugas National Park",
      state: "Florida",
      lat: 24.6285,
      lng: -82.8732,
      dogPolicy: "Dogs are NOT allowed anywhere in the park, including Fort Jefferson, the beaches, and the surrounding waters. Listed here for awareness.",
      dogTrails: [],
      restrictions: [
        "No dogs allowed anywhere in the park",
        "No pets on the ferry",
        "No exceptions",
      ],
      description:
        "This remote island fortress 70 miles west of Key West is spectacular but completely off-limits to dogs. Mentioned here so dog owners can plan accordingly — arrange pet-sitting if you want to visit this bucket-list destination.",
      imageUrl: "",
      website: "https://www.nps.gov/drto",
    },
  ],

  restaurants: [
    {
      name: "Owen's Fish Camp",
      address: "516 Burns Ct, Sarasota, FL 34236",
      lat: 27.3320,
      lng: -82.5330,
      cuisine: "Southern Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the lush garden patio. Fresh Gulf seafood in a funky Old Florida setting that pups adore.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.owensfishcamp.com",
    },
    {
      name: "Shore Diner",
      address: "465 John Ringling Blvd, Sarasota, FL 34236",
      lat: 27.3175,
      lng: -82.5622,
      cuisine: "American Diner",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio on St. Armands Circle. Classic diner fare with a tropical twist.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.shorediner.com",
    },
    {
      name: "The Old Salty Dog",
      address: "5023 Ocean Blvd, Siesta Key, FL 34242",
      lat: 27.2665,
      lng: -82.5540,
      cuisine: "Casual Seafood & Pub",
      priceRange: "$" as const,
      dogPolicy: "Extremely dog-friendly waterfront spot. Dogs are practically the main customers at this beloved island pub.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.theoldsaltydog.com",
    },
    {
      name: "Duval's Fresh Local Seafood",
      address: "1435 Main St, Sarasota, FL 34236",
      lat: 27.3350,
      lng: -82.5340,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome at sidewalk tables on Main Street. Sustainable Gulf-to-table seafood.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.duvalsfreshlocalseafood.com",
    },
    {
      name: "Station 400",
      address: "400 Lemon Ave, Sarasota, FL 34236",
      lat: 27.3358,
      lng: -82.5318,
      cuisine: "New American",
      priceRange: "$$" as const,
      dogPolicy: "Large pet-friendly patio with shade. Craft cocktails and elevated comfort food in the Rosemary District.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.station400.com",
    },
    {
      name: "Daiquiri Deck Raw Bar",
      address: "5250 Ocean Blvd, Siesta Key, FL 34242",
      lat: 27.2640,
      lng: -82.5542,
      cuisine: "Seafood & Tropical Bar",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor deck. Frozen drinks and raw bar bites steps from the beach.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.daiquirideck.com",
    },
    {
      name: "Indigenous",
      address: "239 S Links Ave, Sarasota, FL 34236",
      lat: 27.3310,
      lng: -82.5345,
      cuisine: "Farm-to-Table American",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the porch seating. James Beard-nominated chef using local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.indigenoussarasota.com",
    },
    {
      name: "Big Water Fish Market",
      address: "6641 Midnight Pass Rd, Siesta Key, FL 34242",
      lat: 27.2458,
      lng: -82.5330,
      cuisine: "Seafood Market & Restaurant",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Pick your fresh catch and have it prepared on the spot.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bigwaterfishmarket.com",
    },
  ],

  cafes: [
    {
      name: "Perq Coffee Bar",
      address: "1821 Hillview St, Sarasota, FL 34239",
      lat: 27.3245,
      lng: -82.5290,
      dogPolicy: "Dog-friendly patio in the Southside Village. Award-winning coffee and fresh pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.perqcoffeebar.com",
    },
    {
      name: "O&A Coffee Supply",
      address: "1566 Main St, Sarasota, FL 34236",
      lat: 27.3355,
      lng: -82.5325,
      dogPolicy: "Leashed dogs welcome on the sidewalk patio. Specialty espresso drinks and avocado toast.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.oacoffee.com",
    },
    {
      name: "Sun Garden Cafe",
      address: "210 Avenida Madera, Siesta Key, FL 34242",
      lat: 27.2690,
      lng: -82.5480,
      dogPolicy: "Garden patio welcomes leashed dogs. A Siesta Key breakfast institution surrounded by tropical plants.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.sungardencafe.com",
    },
    {
      name: "Kahwa Coffee",
      address: "1487 2nd St, Sarasota, FL 34236",
      lat: 27.3348,
      lng: -82.5350,
      dogPolicy: "Tampa Bay-born roaster with outdoor seating welcoming dogs. Smooth cold brew for Florida heat.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.kahwacoffee.com",
    },
    {
      name: "The Overton",
      address: "1420 Boulevard of the Arts, Sarasota, FL 34236",
      lat: 27.3385,
      lng: -82.5380,
      dogPolicy: "Covered patio with fans and misters where leashed dogs are welcome. Coffee and craft beer.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.theoverton.com",
    },
  ],

  dogParks: [
    {
      name: "Brohard Paw Park & Beach",
      address: "1600 Harbor Dr S, Venice, FL 34285",
      lat: 27.0888,
      lng: -82.4415,
      offLeash: true,
      fenced: false,
      acres: 5.0,
      amenities: ["Dog beach", "Gulf water access", "Rinse stations", "Waste stations", "Parking"],
      rating: 4.8,
      imageUrl: "",
      description:
        "One of Florida's best dog beaches, this Venice gem features a dedicated off-leash beach where dogs can swim in the warm Gulf waters, dig for prehistoric shark teeth, and roll in the sand to their heart's content.",
    },
    {
      name: "17th Street Paw Park",
      address: "1750 17th St, Sarasota, FL 34234",
      lat: 27.3465,
      lng: -82.5265,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small dog area", "Water fountains", "Shade structures", "Agility equipment", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Sarasota's most popular fenced dog park features separate areas for large and small dogs, agility equipment, and plenty of shade. The social scene among dog parents is almost as lively as the pups.",
    },
    {
      name: "Lakeview Park Dog Area",
      address: "7150 Lago St, Sarasota, FL 34241",
      lat: 27.2850,
      lng: -82.4850,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Water station", "Benches", "Shade trees", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A quieter neighborhood dog park with a fenced off-leash area shaded by mature oaks. A peaceful spot for dogs that prefer a calmer play environment away from the beach crowds.",
    },
    {
      name: "Bayfront Park Trail",
      address: "5 Bayfront Dr, Sarasota, FL 34236",
      lat: 27.3330,
      lng: -82.5445,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Waterfront path", "Bay views", "Benches", "Shade trees", "Waste stations", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A gorgeous bayfront walking path where leashed dogs can enjoy stunning views of Sarasota Bay, watch pelicans dive, and feel the Gulf breeze. Connects to downtown restaurants and shops.",
    },
    {
      name: "Siesta Key Beach (North End)",
      address: "948 Beach Rd, Siesta Key, FL 34242",
      lat: 27.2710,
      lng: -82.5560,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["World-famous white sand", "Gentle surf", "Parking", "Restrooms", "Picnic areas"],
      rating: 4.4,
      imageUrl: "",
      description:
        "While dogs must be leashed and are only allowed outside peak hours on certain sections, the powdery quartz sand on Siesta Key is so fine and cool that your pup will think they are walking on clouds. Check local regulations for seasonal hours.",
    },
  ],
};
