export const savannahData = {
  city: {
    name: "Savannah",
    state: "Georgia",
    region: "Southeast",
    lat: 32.0809,
    lng: -81.0912,
    dogFriendlinessScore: 8,
    description:
      "Savannah's moss-draped squares, cobblestone streets, and slow Southern pace make it one of the most charming dog-friendly cities in America. Nearly all 22 historic squares welcome leashed dogs, and the city's vibrant restaurant scene features countless patios where your pup can lounge beside you over shrimp and grits.",
    heroImage: "https://images.unsplash.com/photo-1520962880247-cfaf541c8724?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 147780,
  },

  hotels: [
    {
      name: "The Kimpton Brice Hotel",
      address: "601 E Bay St, Savannah, GA 31401",
      lat: 32.0815,
      lng: -81.0858,
      priceRange: "$$$" as const,
      dogPolicy: "All dogs welcome with no weight or breed restrictions. Complimentary pet amenities at check-in.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treat basket", "Walking map of nearby squares", "Pet-sitting referrals"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bricehotel.com",
      phone: "(912) 238-1200",
    },
    {
      name: "Perry Lane Hotel",
      address: "256 E Perry St, Savannah, GA 31401",
      lat: 32.0745,
      lng: -81.0914,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 75 lbs welcome. Luxury pet package includes a monogrammed bandana.",
      maxDogWeight: 75,
      petFee: 100,
      amenities: ["Plush dog bed", "Custom bandana", "Gourmet treats", "Water and food bowls", "Rooftop pool access"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.perrylanehotel.com",
      phone: "(912) 415-9000",
    },
    {
      name: "Thunderbird Inn",
      address: "611 W Oglethorpe Ave, Savannah, GA 31401",
      lat: 32.0802,
      lng: -81.1005,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly retro motel welcoming dogs of all sizes with a small nightly fee.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Grassy courtyard", "Waste bags", "Nearby dog-friendly squares", "Free parking"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.thethunderbirdinn.com",
      phone: "(912) 232-2661",
    },
    {
      name: "The Bohemian Hotel Savannah Riverfront",
      address: "102 W Bay St, Savannah, GA 31401",
      lat: 32.0816,
      lng: -81.0941,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a one-time fee. River walk access right outside.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Bowls", "Treats", "Riverfront walking path", "Concierge pet services"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bohemianhotelsavannah.com",
      phone: "(912) 721-3800",
    },
    {
      name: "East Bay Inn",
      address: "225 E Bay St, Savannah, GA 31401",
      lat: 32.0812,
      lng: -81.0893,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select pet-friendly rooms. Charming historic inn steps from River Street.",
      maxDogWeight: 60,
      petFee: 40,
      amenities: ["Dog bed", "Water bowl", "Waste bags", "Walking map"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.eastbayinn.com",
      phone: "(912) 238-1225",
    },
  ],

  nationalParks: [
    {
      name: "Fort Pulaski National Monument",
      state: "Georgia",
      lat: 32.0285,
      lng: -80.8901,
      dogPolicy: "Leashed dogs welcome on trails, grounds, and picnic areas. Not allowed inside the fort structure.",
      dogTrails: ["Cockspur Island Trail", "Lighthouse Overlook Trail", "Dike Trail"],
      restrictions: [
        "Dogs must be on a 6-foot leash at all times",
        "Not permitted inside the fort",
        "Must clean up after pets",
      ],
      description:
        "This beautifully preserved Civil War-era brick fort sits on Cockspur Island at the mouth of the Savannah River. Leashed dogs can explore the scenic trails around the fort with views of salt marshes, tidal creeks, and the Atlantic coast.",
      imageUrl: "",
      website: "https://www.nps.gov/fopu",
    },
    {
      name: "Cumberland Island National Seashore",
      state: "Georgia",
      lat: 30.8560,
      lng: -81.4477,
      dogPolicy: "Dogs are NOT permitted on Cumberland Island, including the ferry. Plan accordingly if traveling with pets.",
      dogTrails: [],
      restrictions: [
        "No pets allowed on the island",
        "No pets on the Cumberland Island ferry",
        "Service animals only",
      ],
      description:
        "Georgia's largest barrier island features pristine beaches, maritime forests, and wild horses, but unfortunately does not allow dogs. Included here so travelers can plan alternative activities for their pups.",
      imageUrl: "",
      website: "https://www.nps.gov/cuis",
    },
    {
      name: "Congaree National Park",
      state: "South Carolina",
      lat: 33.7948,
      lng: -80.7821,
      dogPolicy: "Leashed dogs welcome on most trails and in campgrounds. A rare dog-friendly national park with extensive trail access.",
      dogTrails: ["Boardwalk Loop Trail", "Weston Lake Loop", "Bluff Trail", "Kingsnake Trail"],
      restrictions: [
        "Dogs must be on a 6-foot leash",
        "Not allowed in buildings",
        "Must stay on designated trails",
      ],
      description:
        "About two hours from Savannah, Congaree protects the largest tract of old-growth bottomland hardwood forest in North America. Its extensive boardwalk and trail system is remarkably dog-friendly, making it a worthwhile day trip for hikers with pups.",
      imageUrl: "",
      website: "https://www.nps.gov/cong",
    },
  ],

  restaurants: [
    {
      name: "The Collins Quarter",
      address: "151 Bull St, Savannah, GA 31401",
      lat: 32.0784,
      lng: -81.0939,
      cuisine: "Australian-Southern Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio overlooking one of Savannah's most beautiful squares.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thecollinsquarter.com",
    },
    {
      name: "Treylor Park",
      address: "115 E Bay St, Savannah, GA 31401",
      lat: 32.0812,
      lng: -81.0900,
      cuisine: "Creative Southern",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the funky outdoor patio. Known for fun cocktails and inventive comfort food.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.treylorpark.com",
    },
    {
      name: "Husk Savannah",
      address: "12 W Oglethorpe Ave, Savannah, GA 31401",
      lat: 32.0807,
      lng: -81.0938,
      cuisine: "Southern",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome in the courtyard dining area.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.husksavannah.com",
    },
    {
      name: "Zunzi's",
      address: "108 E York St, Savannah, GA 31401",
      lat: 32.0792,
      lng: -81.0906,
      cuisine: "South African",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly outdoor picnic tables. Grab a famous Zunzi's sandwich and enjoy it with your pup.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.zunzis.com",
    },
    {
      name: "The Wyld Dock Bar",
      address: "2740 Livingston Ave, Savannah, GA 31406",
      lat: 32.0218,
      lng: -81.0569,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly waterfront bar with leashed dogs welcome throughout the outdoor seating area.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thewylddockbar.com",
    },
    {
      name: "Fox & Fig Cafe",
      address: "321 Habersham St, Savannah, GA 31401",
      lat: 32.0739,
      lng: -81.0884,
      cuisine: "Vegan",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the garden patio. A favorite among health-conscious pet parents.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.foxandfig.com",
    },
    {
      name: "Crystal Beer Parlor",
      address: "301 W Jones St, Savannah, GA 31401",
      lat: 32.0721,
      lng: -81.0968,
      cuisine: "American Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the front patio. A Savannah institution since 1933.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.crystalbeerparlor.com",
    },
    {
      name: "Sandfly BBQ",
      address: "8413 Ferguson Ave, Savannah, GA 31406",
      lat: 32.0145,
      lng: -81.0688,
      cuisine: "Barbecue",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor picnic tables. Casual, come-as-you-are vibe.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.sandflybbq.com",
    },
  ],

  cafes: [
    {
      name: "The Sentient Bean",
      address: "13 E Park Ave, Savannah, GA 31401",
      lat: 32.0697,
      lng: -81.0944,
      dogPolicy: "Dog-friendly patio facing Forsyth Park. A beloved community coffee shop.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sentientbean.com",
    },
    {
      name: "Gallery Espresso",
      address: "234 Bull St, Savannah, GA 31401",
      lat: 32.0762,
      lng: -81.0940,
      dogPolicy: "Leashed dogs welcome on the outdoor patio in beautiful Chippewa Square.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.galleryespresso.com",
    },
    {
      name: "Foxy Loxy Cafe",
      address: "1919 Bull St, Savannah, GA 31401",
      lat: 32.0574,
      lng: -81.0936,
      dogPolicy: "Gorgeous courtyard welcomes leashed dogs. Known for amazing coffee and tacos.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.foxyloxycafe.com",
    },
    {
      name: "Blends Coffee Boutique",
      address: "318 MLK Jr Blvd, Savannah, GA 31401",
      lat: 32.0782,
      lng: -81.0971,
      dogPolicy: "Small sidewalk patio area where leashed dogs are welcome.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.blendscoffeeboutique.com",
    },
    {
      name: "Mirabelle Savannah",
      address: "2 E Broughton St, Savannah, GA 31401",
      lat: 32.0800,
      lng: -81.0929,
      dogPolicy: "Dogs welcome at outdoor cafe tables on Broughton Street. Pastries and espresso in a chic setting.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.mirabellesavannah.com",
    },
  ],

  dogParks: [
    {
      name: "Forsyth Park",
      address: "Drayton St & Gaston St, Savannah, GA 31401",
      lat: 32.0684,
      lng: -81.0953,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Walking paths", "Iconic fountain", "Shaded areas", "Water fountains", "Waste stations"],
      rating: 4.7,
      imageUrl: "",
      description:
        "Savannah's crown jewel park features 30 acres of oak-shaded paths, the iconic tiered fountain, and a vibrant weekend farmers market. Dogs must be leashed but will love exploring every corner of this historic green space.",
    },
    {
      name: "Tom Triplett Community Park Dog Park",
      address: "100 Tom Triplett Dr, Pooler, GA 31322",
      lat: 32.1045,
      lng: -81.2421,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Separate small and large dog areas", "Agility equipment", "Water stations", "Shade structures", "Benches"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A well-maintained, fully fenced off-leash dog park in nearby Pooler with separate areas for large and small dogs, agility equipment, and plenty of shade for warm Savannah days.",
    },
    {
      name: "Lake Mayer Community Park",
      address: "1850 E Montgomery Crossroad, Savannah, GA 31406",
      lat: 32.0295,
      lng: -81.0655,
      offLeash: false,
      fenced: false,
      acres: 75.0,
      amenities: ["1.5-mile walking loop", "Lake views", "Picnic shelters", "Waste stations", "Parking"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A sprawling community park with a scenic 1.5-mile loop trail around the lake. While dogs must be leashed, the shaded path and waterside views make it a favorite for locals walking their pups.",
    },
    {
      name: "Daffin Park",
      address: "1301 E Victory Dr, Savannah, GA 31404",
      lat: 32.0588,
      lng: -81.0783,
      offLeash: false,
      fenced: false,
      acres: 77.0,
      amenities: ["Walking trails", "Large open fields", "Shade trees", "Pond", "Waste stations"],
      rating: 4.1,
      imageUrl: "",
      description:
        "One of Savannah's largest parks with wide open green spaces, a duck pond, and plenty of room for leashed dogs to enjoy a long walk. A great alternative to the busier Forsyth Park.",
    },
    {
      name: "Savannah Rapids Dog Park",
      address: "3300 Evans to Locks Rd, Martinez, GA 30907",
      lat: 33.5098,
      lng: -82.0567,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Double-gated entry", "Water station", "Benches", "Waste bags", "Shade trees"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A fenced off-leash dog park set along the Savannah River with a shaded environment and well-maintained grounds. A great spot for dogs to socialize and burn off energy.",
    },
  ],
};
