export const scottsdaleData = {
  city: {
    name: "Scottsdale",
    state: "Arizona",
    region: "Southwest",
    lat: 33.4942,
    lng: -111.9261,
    dogFriendlinessScore: 8,
    description:
      "Scottsdale combines desert luxury with an exceptional love for dogs. From resort spas offering doggy pampering packages to the stunning McDowell Sonoran Preserve trails, this upscale desert city treats dogs like VIP guests at every turn.",
    heroImage: "https://images.unsplash.com/photo-1569949381669-ecf31ae8e613?w=1200&fit=crop",
    climate: "Hot desert",
    population: 241361,
  },

  hotels: [
    {
      name: "The Scottsdale Resort at McCormick Ranch",
      address: "7700 E McCormick Pkwy, Scottsdale, AZ 85258",
      lat: 33.5430,
      lng: -111.9070,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a pet fee. Luxury resort with pet-pampering program.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Dog bed", "Gourmet treats", "Walking paths", "Pet-sitting service", "Near Greenbelt"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.thescottsdaleresort.com",
      phone: "(480) 991-9000",
    },
    {
      name: "Hotel Valley Ho",
      address: "6850 E Main St, Scottsdale, AZ 85251",
      lat: 33.4940,
      lng: -111.9290,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of any size welcome with nightly fee. VIP pet program with beds, bowls, and treats.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Food bowls", "Treats", "Dog walking service", "Pet relief area"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.hotelvalleyho.com",
      phone: "(480) 376-2600",
    },
    {
      name: "The Saguaro Scottsdale",
      address: "4000 N Drinkwater Blvd, Scottsdale, AZ 85251",
      lat: 33.4980,
      lng: -111.9250,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a per-stay pet fee. Colorful boutique hotel in Old Town.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Dog bed", "Bowls", "Old Town location", "Pool adjacent area", "Walking distance to shops"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.thesaguaro.com",
      phone: "(480) 308-1100",
    },
    {
      name: "Residence Inn Scottsdale North",
      address: "17011 N Scottsdale Rd, Scottsdale, AZ 85255",
      lat: 33.6440,
      lng: -111.9260,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a non-refundable fee. Extended-stay suites near desert preserves.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Full kitchen", "Near McDowell Preserve", "Grassy area", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(480) 563-4120",
    },
  ],

  nationalParks: [
    {
      name: "McDowell Sonoran Preserve",
      state: "Arizona",
      lat: 33.6850,
      lng: -111.8310,
      dogPolicy: "Leashed dogs welcome on all trails. Over 30,000 acres of pristine Sonoran Desert.",
      dogTrails: ["Tom's Thumb Trail", "Gateway Loop", "Windmill Trail", "Brown's Ranch Trail"],
      restrictions: [
        "Must be on a 6-foot leash at all times",
        "Carry water for your dog - no water on trails",
        "Avoid trails when temperatures exceed 100°F",
        "Watch for rattlesnakes",
      ],
      description:
        "One of the largest urban preserves in America, the McDowell Sonoran Preserve offers over 225 miles of trails through stunning saguaro-studded desert. Early morning hikes reveal the Sonoran Desert at its most magical.",
      imageUrl: "",
      website: "https://www.scottsdaleaz.gov/preserve",
    },
    {
      name: "Tonto National Forest - Four Peaks Wilderness",
      state: "Arizona",
      lat: 33.6870,
      lng: -111.3290,
      dogPolicy: "Dogs welcome on trails with leash recommended. Remote wilderness east of Scottsdale.",
      dogTrails: ["Brown's Peak Trail", "Amethyst Trail", "Butcher Jones Trail"],
      restrictions: [
        "Leash recommended",
        "Remote area - carry supplies",
        "No water available on most trails",
      ],
      description:
        "The Four Peaks area east of Scottsdale offers rugged mountain trails, Saguaro Lake recreation, and incredible desert vistas. The Butcher Jones Trail along Saguaro Lake is especially dog-friendly with water access.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/tonto",
    },
    {
      name: "Pinnacle Peak Park",
      state: "Arizona",
      lat: 33.7280,
      lng: -111.8560,
      dogPolicy: "Leashed dogs welcome on the 3.5-mile round trip trail. Popular North Scottsdale desert hike.",
      dogTrails: ["Pinnacle Peak Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Trail closes at sunset",
        "No dogs on trail when temp exceeds 100°F",
        "Carry water",
      ],
      description:
        "Pinnacle Peak offers a moderately challenging 3.5-mile out-and-back trail with panoramic views of the desert and distant mountains. The well-maintained trail and beautiful saguaro landscape make it a dog hiking favorite.",
      imageUrl: "",
      website: "https://www.scottsdaleaz.gov/parks/pinnacle-peak",
    },
  ],

  restaurants: [
    {
      name: "Farm & Craft",
      address: "4302 N Scottsdale Rd, Scottsdale, AZ 85251",
      lat: 33.5010,
      lng: -111.9260,
      cuisine: "Health-Conscious American",
      priceRange: "$$" as const,
      dogPolicy: "Extremely dog-friendly with a dedicated dog menu and large patio. Water bowls everywhere.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.farmandcraft.com",
    },
    {
      name: "Diego Pops",
      address: "4338 N Scottsdale Rd, Scottsdale, AZ 85251",
      lat: 33.5015,
      lng: -111.9260,
      cuisine: "Mexican Street Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the colorful outdoor patio. Fun, vibrant taco spot.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.diegopops.com",
    },
    {
      name: "The Mission",
      address: "3815 N Brown Ave, Scottsdale, AZ 85251",
      lat: 33.4970,
      lng: -111.9230,
      cuisine: "Latin-Inspired",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the patio. Upscale Latin cuisine in Old Town.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.themissionaz.com",
    },
    {
      name: "Oregano's Pizza Bistro",
      address: "3622 N Scottsdale Rd, Scottsdale, AZ 85251",
      lat: 33.4960,
      lng: -111.9260,
      cuisine: "Pizza & Italian",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor patio. Massive portions and a fun atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.oreganos.com",
    },
    {
      name: "Arcadia Farms Cafe",
      address: "7014 E 1st Ave, Scottsdale, AZ 85251",
      lat: 33.4940,
      lng: -111.9190,
      cuisine: "Garden Cafe",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the garden patio. Fresh, seasonal dishes in a beautiful setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.arcadiafarmscafe.com",
    },
  ],

  cafes: [
    {
      name: "Berdena's",
      address: "7119 E Shea Blvd, Scottsdale, AZ 85254",
      lat: 33.5810,
      lng: -111.9180,
      dogPolicy: "Dogs welcome on the patio. Health-forward cafe with specialty coffee and acai bowls.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.berdenas.com",
    },
    {
      name: "Maverick Coffee",
      address: "7020 E 2nd St, Scottsdale, AZ 85251",
      lat: 33.4935,
      lng: -111.9195,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Scottsdale's go-to specialty coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.maverickcoffee.com",
    },
    {
      name: "Sip Coffee & Beer House",
      address: "3620 N Scottsdale Rd, Scottsdale, AZ 85251",
      lat: 33.4958,
      lng: -111.9260,
      dogPolicy: "Very dog-friendly patio with treats available. Coffee by day, craft beer by night.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.sipcoffeeandbeer.com",
    },
    {
      name: "Provision Coffee Bar",
      address: "4501 N Scottsdale Rd, Scottsdale, AZ 85251",
      lat: 33.5030,
      lng: -111.9260,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Artisan coffee in a modern space.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.provisioncoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Chaparral Dog Park",
      address: "5401 N Hayden Rd, Scottsdale, AZ 85250",
      lat: 33.5280,
      lng: -111.9090,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: ["Separate small dog area", "Water stations", "Shade ramadas", "Waste stations", "Lights for evening use"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Scottsdale's most popular off-leash park features excellent shade structures critical for the desert climate. Evening lights allow for cooler play sessions during the hot months.",
    },
    {
      name: "Scottsdale Greenbelt",
      address: "Indian Bend Wash, Scottsdale, AZ 85251",
      lat: 33.5100,
      lng: -111.9190,
      offLeash: false,
      fenced: false,
      acres: 300.0,
      amenities: ["Paved multi-use path", "Lakes", "Grassy areas", "Shade trees", "Restrooms"],
      rating: 4.7,
      imageUrl: "",
      description:
        "An 11-mile green corridor running through the heart of Scottsdale with lakes, grass, and paved paths. This on-leash paradise is one of the best urban walking paths in the Southwest.",
    },
    {
      name: "Vista del Camino Dog Park",
      address: "7700 E Roosevelt St, Scottsdale, AZ 85257",
      lat: 33.4590,
      lng: -111.9050,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Double-gated entry", "Water fountains", "Shade structures", "Waste stations", "Benches"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A well-maintained south Scottsdale dog park with good shade coverage and water access. The friendly neighborhood atmosphere makes it a great spot for socializing dogs.",
    },
    {
      name: "Horizon Park Dog Run",
      address: "15444 N 100th St, Scottsdale, AZ 85260",
      lat: 33.6120,
      lng: -111.8530,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Desert landscape", "Water station", "Shade ramadas", "Waste stations", "Near preserve trails"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A north Scottsdale dog park near the McDowell Sonoran Preserve, perfect for an off-leash play session before or after a desert hike. The desert landscaping feels naturally integrated.",
    },
  ],
};
