export const seattleData = {
  city: {
    name: "Seattle",
    state: "Washington",
    region: "Pacific Northwest",
    lat: 47.6062,
    lng: -122.3321,
    dogFriendlinessScore: 8,
    description:
      "Seattle is a paradise for pups and their people, with miles of waterfront trails, lush parks, and a coffee culture that warmly welcomes four-legged friends on every patio. From off-leash beaches on Puget Sound to dog-friendly breweries in Ballard, the Emerald City makes it easy to explore with your canine companion rain or shine.",
    heroImage: "https://images.unsplash.com/photo-1502175353174-a7a70e73b4c3?w=1200&fit=crop",
    climate: "Oceanic",
    population: 737015,
  },

  hotels: [
    {
      name: "The Kimpton Hotel Monaco Seattle",
      address: "1101 4th Ave, Seattle, WA 98101",
      lat: 47.6069,
      lng: -122.3338,
      priceRange: "$$$" as const,
      dogPolicy: "All dogs welcome with no breed or size restrictions. Complimentary pet amenities at check-in.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowl", "Treats at check-in", "Walking routes map", "Pet-sitting referrals"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.monaco-seattle.com",
      phone: "(206) 621-1770",
    },
    {
      name: "Hotel Ballard",
      address: "5216 Ballard Ave NW, Seattle, WA 98107",
      lat: 47.6647,
      lng: -122.3825,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 80 lbs welcome. Two pets max per room.",
      maxDogWeight: 80,
      petFee: 50,
      amenities: ["Dog bed", "Food and water bowls", "Waste bags", "Nearby off-leash park"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelballardseattle.com",
      phone: "(206) 789-5012",
    },
    {
      name: "Lotte Hotel Seattle",
      address: "809 5th Ave, Seattle, WA 98104",
      lat: 47.6073,
      lng: -122.3301,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a one-time pet fee. Luxury pet amenities provided.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Plush dog bed", "Gourmet treats", "Water bowl", "Pet room service menu", "Dog walking service"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.lottehotel.com/seattle",
      phone: "(206) 800-8110",
    },
    {
      name: "The Staypineapple Hotel",
      address: "1113 6th Ave, Seattle, WA 98101",
      lat: 47.6082,
      lng: -122.3294,
      priceRange: "$$" as const,
      dogPolicy: "All dogs welcome regardless of size. No breed restrictions.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Dog bed", "Bowls", "Treats", "Poop bags", "Dog-friendly room floors"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.staypineapple.com",
      phone: "(206) 728-6299",
    },
    {
      name: "Watertown Hotel",
      address: "4242 Roosevelt Way NE, Seattle, WA 98105",
      lat: 47.6590,
      lng: -122.3177,
      priceRange: "$$" as const,
      dogPolicy: "Up to two dogs per room. All sizes welcome with a nightly pet fee.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Dog bed", "Water bowls", "Complimentary shuttle to downtown", "Nearby Burke-Gilman Trail"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.watertownseattle.com",
      phone: "(206) 826-4242",
    },
  ],

  nationalParks: [
    {
      name: "Olympic National Park",
      state: "Washington",
      lat: 47.8021,
      lng: -123.6044,
      dogPolicy: "Dogs allowed on leash in developed areas, campgrounds, and a few paved paths. Not permitted on park trails or beaches in most areas.",
      dogTrails: ["Rialto Beach (leashed, first mile)", "Kalaloch Beach", "Peabody Creek Trail"],
      restrictions: [
        "Dogs not allowed on most backcountry trails",
        "Must be on leash no longer than 6 feet",
        "Not permitted in buildings or on shuttle buses",
      ],
      description:
        "A vast wilderness spanning nearly a million acres of glacier-capped peaks, old-growth rainforests, and wild Pacific coastline. While trail access for dogs is limited, the stunning coastal beaches offer memorable leashed walks with jaw-dropping scenery.",
      imageUrl: "",
      website: "https://www.nps.gov/olym",
    },
    {
      name: "Mount Rainier National Park",
      state: "Washington",
      lat: 46.8523,
      lng: -121.7603,
      dogPolicy: "Dogs permitted in parking areas, campgrounds, and along roads only. No trail access for pets.",
      dogTrails: ["Campground loops at Cougar Rock", "Ohanapecosh Campground roads"],
      restrictions: [
        "No dogs on any trails",
        "Must be leashed at all times (6 ft max)",
        "Not allowed in buildings or wilderness areas",
      ],
      description:
        "Dominated by the iconic 14,411-foot volcanic peak, Mount Rainier is a landscape of alpine meadows, ancient forests, and cascading waterfalls. Dog access is very limited, but the drive-in campgrounds allow you to soak in the mountain atmosphere with your pup.",
      imageUrl: "",
      website: "https://www.nps.gov/mora",
    },
    {
      name: "North Cascades National Park",
      state: "Washington",
      lat: 48.7718,
      lng: -121.2985,
      dogPolicy: "Dogs allowed only on the Pacific Crest Trail section and in the Ross Lake and Lake Chelan National Recreation Areas.",
      dogTrails: [
        "Pacific Crest Trail (leashed)",
        "Ross Lake NRA trails",
        "Rainy Lake Trail (NRA section)",
      ],
      restrictions: [
        "Not allowed on most national park trails",
        "Must remain on leash (6 ft max)",
        "Not permitted in wilderness zones outside the NRA",
      ],
      description:
        "Known as the American Alps, North Cascades is a rugged expanse of jagged peaks, turquoise lakes, and over 300 glaciers. The adjacent recreation areas offer more trail options for leashed dogs amid some of the most dramatic mountain scenery in the lower 48.",
      imageUrl: "",
      website: "https://www.nps.gov/noca",
    },
  ],

  restaurants: [
    {
      name: "Norm's Eatery & Ale House",
      address: "460 N 36th St, Seattle, WA 98103",
      lat: 47.6519,
      lng: -122.3506,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the covered outdoor patio year-round.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.normseateryandalehouse.com",
    },
    {
      name: "The Lookout Bar & Grill",
      address: "500 E Pike St, Seattle, WA 98122",
      lat: 47.6149,
      lng: -122.3255,
      cuisine: "American Pub",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the large rooftop patio.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.thelookoutcapitolhill.com",
    },
    {
      name: "Stoneburner",
      address: "5214 Ballard Ave NW, Seattle, WA 98107",
      lat: 47.6646,
      lng: -122.3824,
      cuisine: "Mediterranean",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome at outdoor tables.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.stoneburnerseattle.com",
    },
    {
      name: "Hale's Ales Brewery & Pub",
      address: "4301 Leary Way NW, Seattle, WA 98107",
      lat: 47.6612,
      lng: -122.3729,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the outdoor beer garden and patio area.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.halesbrewery.com",
    },
    {
      name: "San Fermo",
      address: "5341 Ballard Ave NW, Seattle, WA 98107",
      lat: 47.6651,
      lng: -122.3832,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the heated sidewalk patio.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.sanfermoseattle.com",
    },
    {
      name: "Westward",
      address: "2501 N Northlake Way, Seattle, WA 98105",
      lat: 47.6520,
      lng: -122.3294,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs allowed on the outdoor waterfront deck. Stunning Lake Union views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.westwardseattle.com",
    },
    {
      name: "Peddler Brewing Company",
      address: "1514 NW Leary Way, Seattle, WA 98107",
      lat: 47.6629,
      lng: -122.3765,
      cuisine: "Brewery",
      priceRange: "$" as const,
      dogPolicy: "Very dog-friendly taproom with treats and water bowls throughout. Dogs welcome inside and on patio.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.peddlerbrewing.com",
    },
    {
      name: "Biscuit Bitch",
      address: "1909 1st Ave, Seattle, WA 98101",
      lat: 47.6112,
      lng: -122.3435,
      cuisine: "Southern Breakfast",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables in front of the restaurant.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.biscuitbitch.com",
    },
  ],

  cafes: [
    {
      name: "Cafe Ladro",
      address: "801 NW Market St, Seattle, WA 98107",
      lat: 47.6687,
      lng: -122.3714,
      dogPolicy: "Leashed dogs welcome on the front patio. Water bowls provided.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.cafeladro.com",
    },
    {
      name: "Bark Espresso",
      address: "1115 12th Ave, Seattle, WA 98122",
      lat: 47.6148,
      lng: -122.3165,
      dogPolicy: "Dog-themed cafe with a welcoming patio. Pup cups available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.barkespresso.com",
    },
    {
      name: "Milstead & Co.",
      address: "754 N 34th St, Seattle, WA 98103",
      lat: 47.6502,
      lng: -122.3488,
      dogPolicy: "Dogs welcome at outdoor tables in the Fremont neighborhood.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.milsteadandco.com",
    },
    {
      name: "Storyville Coffee",
      address: "1001 1st Ave, Seattle, WA 98104",
      lat: 47.6065,
      lng: -122.3399,
      dogPolicy: "Leashed dogs permitted at the outdoor seating area near Pike Place Market.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.storyville.com",
    },
    {
      name: "Fuel Coffee",
      address: "2300 24th Ave E, Seattle, WA 98112",
      lat: 47.6370,
      lng: -122.3024,
      dogPolicy: "Neighborhood favorite with a dog-friendly sidewalk patio. Biscuits for pups on request.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.fuelcoffeeseattle.com",
    },
  ],

  dogParks: [
    {
      name: "Magnuson Park Off-Leash Area",
      address: "7400 Sand Point Way NE, Seattle, WA 98115",
      lat: 47.6816,
      lng: -122.2569,
      offLeash: true,
      fenced: true,
      acres: 9.0,
      amenities: ["Lake access for swimming", "Separate small dog area", "Waste stations", "Benches", "Parking lot"],
      rating: 4.7,
      imageUrl: "",
      description:
        "Seattle's largest off-leash area features nearly nine acres of open fields and a shoreline beach where dogs can splash in Lake Washington. A separate small-dog section ensures all pups can play safely.",
    },
    {
      name: "Westcrest Park Off-Leash Area",
      address: "8806 8th Ave SW, Seattle, WA 98106",
      lat: 47.5223,
      lng: -122.3466,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: ["Double-gated entry", "Open meadow", "Wooded trails", "Waste stations", "Benches"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A spacious, fully fenced off-leash park in West Seattle with a mix of wide-open grass and shaded forest trails. The park has a peaceful, less-crowded feel compared to other Seattle dog parks.",
    },
    {
      name: "Golden Gardens Off-Leash Area",
      address: "8498 Seaview Pl NW, Seattle, WA 98117",
      lat: 47.6918,
      lng: -122.4032,
      offLeash: true,
      fenced: false,
      acres: 1.5,
      amenities: ["Beach access", "Puget Sound views", "Waste stations", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Located at the north end of Golden Gardens Park, this unfenced off-leash area lets dogs romp on the beach and wade into Puget Sound with the Olympic Mountains as a backdrop.",
    },
    {
      name: "Regrade Park Off-Leash Area",
      address: "2251 3rd Ave, Seattle, WA 98121",
      lat: 47.6162,
      lng: -122.3447,
      offLeash: true,
      fenced: true,
      acres: 0.5,
      amenities: ["Artificial turf", "Lighting for evening visits", "Waste stations", "Water fountain"],
      rating: 4.0,
      imageUrl: "",
      description:
        "A compact, fully fenced urban dog park in the heart of Belltown. The synthetic turf stays clean even in Seattle's rain, making it a reliable downtown spot for a quick off-leash romp.",
    },
    {
      name: "Genesee Park Off-Leash Area",
      address: "4316 S Genesee St, Seattle, WA 98118",
      lat: 47.5632,
      lng: -122.2826,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Large open field", "Shaded areas", "Waste stations", "Benches", "Free parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A popular off-leash park in southeast Seattle with rolling grassy hills and mature trees providing shade. Great for dogs who love to run in wide-open spaces.",
    },
  ],
};
