export const sedonaData = {
  city: {
    name: "Sedona",
    state: "Arizona",
    region: "Southwest",
    lat: 34.8697,
    lng: -111.7610,
    dogFriendlinessScore: 7,
    description:
      "Ringed by towering red rock formations that glow crimson at sunset, Sedona is a spiritual and scenic wonderland where dogs are welcome on most of the area's famous trails. The combination of world-class hiking, art galleries with open doors, and patio dining with jaw-dropping canyon views makes this high-desert town a must-visit for adventurous dog owners.",
    heroImage: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&fit=crop",
    climate: "Semi-arid",
    population: 10336,
  },
  hotels: [
    {
      name: "Kimpton Amara Resort & Spa",
      address: "100 Amara Ln, Sedona, AZ 86336",
      lat: 34.8711,
      lng: -111.7609,
      priceRange: "$$$$" as const,
      dogPolicy: "Kimpton's signature all-pets-welcome policy with no size limits and no fees. Creek-side setting with red rock views.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treats", "Loaner leashes", "Creek-side walking path"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.amararesort.com",
      phone: "(928) 282-4828",
    },
    {
      name: "L'Auberge de Sedona",
      address: "301 L'Auberge Ln, Sedona, AZ 86336",
      lat: 34.8714,
      lng: -111.7599,
      priceRange: "$$$$" as const,
      dogPolicy: "Luxury creek-side resort with select pet-friendly cottages. Dogs under 40 lbs in designated rooms with advance booking.",
      maxDogWeight: 40,
      petFee: 125,
      amenities: ["Luxury dog bed", "Gourmet treats", "Creek access", "Dog-walking trail", "Pet-sitting service"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.lauberge.com",
      phone: "(928) 282-1661",
    },
    {
      name: "Orchards Inn Sedona",
      address: "254 N Hwy 89A, Sedona, AZ 86336",
      lat: 34.8722,
      lng: -111.7614,
      priceRange: "$$$" as const,
      dogPolicy: "Uptown Sedona hotel with pet-friendly rooms offering private balconies with red rock views. Dogs under 50 lbs.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Red rock view balcony", "Trail guide", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.orchardsinnsedona.com",
      phone: "(928) 282-2405",
    },
    {
      name: "Sedona Rouge Hotel & Spa",
      address: "2250 W Hwy 89A, Sedona, AZ 86336",
      lat: 34.8633,
      lng: -111.7960,
      priceRange: "$$" as const,
      dogPolicy: "West Sedona hotel with spacious pet-friendly rooms and easy access to hiking trailheads. Two dogs max.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Treats", "Hiking trail proximity", "Pet relief area", "Water bowls"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.sedonarouge.com",
      phone: "(928) 203-4111",
    },
    {
      name: "GreenTree Inn Sedona",
      address: "90 Bell Rock Blvd, Sedona, AZ 86351",
      lat: 34.8078,
      lng: -111.7655,
      priceRange: "$" as const,
      dogPolicy: "Budget-friendly option in the Village of Oak Creek with pet-friendly rooms. Close to Bell Rock trailhead.",
      maxDogWeight: 60,
      petFee: 25,
      amenities: ["Pet-friendly room", "Nearby trailhead", "Waste bags", "Water bowl", "Parking"],
      rating: 3.9,
      imageUrl: "",
      website: "https://www.greentreeinn.com",
      phone: "(928) 284-9190",
    },
  ],
  nationalParks: [
    {
      name: "Coconino National Forest (Red Rock District)",
      state: "Arizona",
      lat: 34.8540,
      lng: -111.7890,
      dogPolicy: "Dogs welcome on all national forest trails on a leash or under voice control. One of the most dog-friendly trail systems in the Southwest.",
      dogTrails: ["Bell Rock Pathway", "Cathedral Rock Trail", "Devil's Bridge Trail", "Soldier Pass Trail", "West Fork of Oak Creek Trail"],
      restrictions: ["Must be on leash or under reliable voice control", "Not allowed in swimming areas at Slide Rock", "Pack out waste", "Hot rock surfaces in summer can burn paws"],
      description: "The red rock trails surrounding Sedona are part of the Coconino National Forest, offering some of the most visually stunning hiking in the country. Dogs can join you on nearly every trail, from gentle creek-side paths to scrambles up crimson buttes with sweeping views of the Verde Valley.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/coconino",
    },
    {
      name: "Montezuma Castle National Monument",
      state: "Arizona",
      lat: 34.6112,
      lng: -111.8351,
      dogPolicy: "Dogs allowed on the main paved trail loop on a leash. One of the more accessible national monuments for dog owners.",
      dogTrails: ["Castle Loop Trail"],
      restrictions: ["6-foot leash required", "Must stay on paved trail", "Not allowed in visitor center", "Clean up after pet"],
      description: "Twenty minutes south of Sedona, this remarkably preserved 12th-century cliff dwelling sits high in a limestone alcove above Beaver Creek. The short, paved loop trail is dog-friendly and offers fascinating views of ancient Sinagua architecture.",
      imageUrl: "",
      website: "https://www.nps.gov/moca",
    },
    {
      name: "Tuzigoot National Monument",
      state: "Arizona",
      lat: 34.7700,
      lng: -112.0267,
      dogPolicy: "Dogs allowed on outdoor trails on a leash. Not permitted inside the visitor center or pueblo ruins.",
      dogTrails: ["Tavasci Marsh Overlook Trail", "Main Loop Trail"],
      restrictions: ["6-foot leash required", "Not allowed in pueblo ruins", "Not allowed in visitor center", "Stay on designated trails"],
      description: "Perched on a desert hilltop overlooking the Verde River, Tuzigoot preserves a Sinagua pueblo ruin with panoramic views of the Verde Valley. The trails around the monument are dog-friendly and offer a peaceful escape into ancient history.",
      imageUrl: "",
      website: "https://www.nps.gov/tuzi",
    },
    {
      name: "Grand Canyon National Park",
      state: "Arizona",
      lat: 36.1069,
      lng: -112.1129,
      dogPolicy: "Dogs allowed only on the South Rim's paved Rim Trail and in developed areas. Not permitted below the rim or on unpaved trails.",
      dogTrails: ["South Rim Trail (paved sections)"],
      restrictions: ["Only allowed on South Rim Trail paved sections", "Not allowed below the rim", "Not permitted on shuttle buses", "6-foot leash required", "Kennel service available at South Rim"],
      description: "Two hours north of Sedona, the Grand Canyon needs no introduction. While dogs are limited to the rim, the paved South Rim Trail offers thirteen miles of unparalleled canyon views. A South Rim kennel lets you explore further while your dog is cared for.",
      imageUrl: "",
      website: "https://www.nps.gov/grca",
    },
  ],
  restaurants: [
    {
      name: "Elote Café",
      address: "350 Jordan Rd, Sedona, AZ 86336",
      lat: 34.8680,
      lng: -111.7580,
      cuisine: "Southwestern-Mexican",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the patio during temperate months. Famous fire-roasted corn and Oaxacan-inspired dishes.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.8,
      imageUrl: "",
      website: "https://www.elotecafe.com",
    },
    {
      name: "The Hudson",
      address: "671 Hwy 179, Sedona, AZ 86336",
      lat: 34.8413,
      lng: -111.7665,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Expansive patio with stunning red rock views welcomes dogs. Elevated cocktail program and creative seasonal menu.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thehudsoninsedona.com",
    },
    {
      name: "Creekside American Bistro",
      address: "251 N Hwy 89A, Sedona, AZ 86336",
      lat: 34.8720,
      lng: -111.7615,
      cuisine: "American Bistro",
      priceRange: "$$" as const,
      dogPolicy: "Creek-side patio with a dedicated dog menu and water bowls. One of Sedona's most beloved dog-friendly restaurants.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.creeksidesedona.com",
    },
    {
      name: "Mariposa Latin Inspired Grill",
      address: "700 Hwy 89A, Sedona, AZ 86336",
      lat: 34.8636,
      lng: -111.7960,
      cuisine: "Latin-Inspired Grill",
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs allowed on the terrace with prior arrangement. Panoramic views of Sedona's red rock formations.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.mariposasedona.com",
    },
    {
      name: "Indian Gardens Café & Market",
      address: "3951 N Hwy 89A, Sedona, AZ 86336",
      lat: 34.8884,
      lng: -111.7827,
      cuisine: "Cafe & Sandwiches",
      priceRange: "$" as const,
      dogPolicy: "Beloved Oak Creek Canyon café with a tree-shaded patio where dogs are always welcome. Sandwiches, salads, and baked goods.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.indiangardenscafe.com",
    },
    {
      name: "Mesa Grill Sedona",
      address: "1185 W Hwy 89A, Sedona, AZ 86336",
      lat: 34.8672,
      lng: -111.7810,
      cuisine: "Southwestern",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio with views of Thunder Mountain. Hearty Southwestern breakfasts and lunches.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.mesagrillsedona.com",
    },
    {
      name: "SaltRock Southwest Kitchen",
      address: "100 Amara Ln, Sedona, AZ 86336",
      lat: 34.8711,
      lng: -111.7609,
      cuisine: "Southwestern Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Located at the Kimpton Amara, dogs are welcome on the creek-side patio. Creative Southwest dishes with local ingredients.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.saltrocksedona.com",
    },
    {
      name: "Oak Creek Brewing & Grill",
      address: "336 Hwy 179, Sedona, AZ 86336",
      lat: 34.8570,
      lng: -111.7660,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Casual brewpub with a dog-friendly patio. Local craft beers and pub fare after a day on the trails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.oakcreekbrew.com",
    },
  ],
  cafes: [
    {
      name: "Creekside Coffee",
      address: "229 N Hwy 89A, Sedona, AZ 86336",
      lat: 34.8718,
      lng: -111.7617,
      dogPolicy: "Uptown café with a shaded patio overlooking Oak Creek. Dogs welcome while you enjoy locally roasted coffee and pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.creeksidecoffeesedona.com",
    },
    {
      name: "Sedona Memories Bakery & Café",
      address: "321 Jordan Rd, Sedona, AZ 86336",
      lat: 34.8680,
      lng: -111.7582,
      dogPolicy: "No-frills bakery with outdoor seating and generous portions. Dogs welcome at the picnic tables.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.sedonamemories.com",
    },
    {
      name: "The Chai Spot",
      address: "140 Hwy 179, Sedona, AZ 86336",
      lat: 34.8680,
      lng: -111.7625,
      dogPolicy: "Cozy chai house with a bohemian outdoor space where dogs can lounge on cushions. Traditional chai and Indian snacks.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thechaispot.com",
    },
    {
      name: "Pisa Lisa Artisan Pizza & Café",
      address: "1975 W Hwy 89A, Sedona, AZ 86336",
      lat: 34.8645,
      lng: -111.7912,
      dogPolicy: "West Sedona café with wood-fired pizzas and a relaxed patio where dogs are always part of the scene.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.pisalisapizza.com",
    },
    {
      name: "Red Rock Café",
      address: "100 Verde Valley School Rd, Sedona, AZ 86351",
      lat: 34.8103,
      lng: -111.7666,
      dogPolicy: "Popular Village of Oak Creek breakfast spot with a patio that welcomes dogs. Classic American breakfasts with a view.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.redrockcafe.com",
    },
  ],
  dogParks: [
    {
      name: "Sedona Dog Park",
      address: "525 Posse Ground Rd, Sedona, AZ 86336",
      lat: 34.8755,
      lng: -111.7555,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Shade ramadas", "Benches", "Red rock views"],
      rating: 4.5,
      imageUrl: "",
      description: "Sedona's premier dog park sits against a backdrop of red rock spires that makes even a routine fetch session feel cinematic. Fully fenced with separate large and small dog areas, it features covered ramadas for shade and water stations to keep dogs hydrated in the desert air.",
    },
    {
      name: "Posse Grounds Park (Leash-Optional Trails)",
      address: "525 Posse Ground Rd, Sedona, AZ 86336",
      lat: 34.8760,
      lng: -111.7545,
      offLeash: true,
      fenced: false,
      acres: 18,
      amenities: ["Walking trails", "Sports fields", "Restrooms", "Parking", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "Adjacent to the fenced dog park, Posse Grounds offers open trails and grassy fields where dogs under voice control can explore. The surrounding red rock scenery elevates a simple walk into something extraordinary.",
    },
    {
      name: "Bell Rock Pathway (Dog-Friendly Trail)",
      address: "Bell Rock Blvd & Hwy 179, Sedona, AZ 86351",
      lat: 34.8108,
      lng: -111.7652,
      offLeash: false,
      fenced: false,
      acres: 50,
      amenities: ["Scenic trail", "Red rock formations", "Trailhead parking", "Waste bag stations", "Interpretive signs"],
      rating: 4.8,
      imageUrl: "",
      description: "While not a traditional dog park, the Bell Rock Pathway is one of Sedona's most accessible and spectacular dog-friendly trails. The gentle, well-maintained path winds past Bell Rock and Courthouse Butte with panoramic views that make it a highlight of any dog-friendly visit to Sedona.",
    },
    {
      name: "Crescent Moon Ranch / Red Rock Crossing",
      address: "333 Red Rock Crossing Rd, Sedona, AZ 86336",
      lat: 34.8283,
      lng: -111.7932,
      offLeash: false,
      fenced: false,
      acres: 25,
      amenities: ["Creek access", "Picnic areas", "Cathedral Rock views", "Restrooms", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description: "Dogs on leash can wade in Oak Creek at Red Rock Crossing while Cathedral Rock towers magnificently overhead. This is the classic Sedona photo location and one of the best spots to let your dog cool off in the creek after a desert hike.",
    },
    {
      name: "Soldier Pass Trailhead Area",
      address: "Soldier Pass Rd, Sedona, AZ 86336",
      lat: 34.8814,
      lng: -111.7752,
      offLeash: false,
      fenced: false,
      acres: 30,
      amenities: ["Hiking trails", "Natural arches", "Sinkhole viewpoints", "Limited parking", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "The Soldier Pass area offers some of Sedona's most intriguing geological features, including the Devil's Kitchen sinkhole and the Seven Sacred Pools. Dogs on leash can tackle the moderate trails through red rock terrain with excellent views of the Sedona skyline.",
    },
  ],
};
