export const skaneatelesData = {
  city: {
    name: "Skaneateles",
    state: "New York",
    region: "Northeast",
    lat: 42.9470,
    lng: -76.4291,
    dogFriendlinessScore: 7,
    description:
      "Perched on the shores of one of the cleanest lakes in America, Skaneateles is a picture-perfect Finger Lakes village that warmly welcomes dogs. The lakefront parks, charming downtown, and surrounding wine country create an idyllic getaway for humans and their canine companions.",
    heroImage: "https://images.unsplash.com/photo-1520962880247-cfaf541c8724?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 7457,
  },
  hotels: [
    {
      name: "The Sherwood Inn",
      address: "26 W Genesee St, Skaneateles, NY 13152",
      lat: 42.9469,
      lng: -76.4305,
      priceRange: "$$$" as const,
      dogPolicy: "Historic lakefront inn welcoming dogs in select rooms with a $50 per stay fee. Lake views and downtown location.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Lakefront", "Historic inn", "Restaurant", "Downtown location", "Porch seating"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thesherwoodinn.com",
      phone: "(315) 685-3405",
    },
    {
      name: "Mirbeau Inn & Spa",
      address: "851 W Genesee St, Skaneateles, NY 13152",
      lat: 42.946,
      lng: -76.4528,
      priceRange: "$$$$" as const,
      dogPolicy: "Luxury spa resort welcoming dogs under 30 lbs with a $100 per stay fee. Monet-inspired gardens and pond.",
      maxDogWeight: 30,
      petFee: 100,
      amenities: ["Spa", "Gardens", "Fine dining", "Luxury suites", "Pet amenities"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.mirbeau.com",
      phone: "(315) 685-5006",
    },
    {
      name: "Skaneateles Suites",
      address: "4114 W Genesee St Rd, Skaneateles, NY 13152",
      lat: 42.9376,
      lng: -76.4658,
      priceRange: "$$" as const,
      dogPolicy: "Pet-friendly suites with a $25 per night fee. Full kitchens and a grassy pet area.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Full kitchen", "Pet area", "Free parking", "Near lake", "Suite-style"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.skansuites.com",
      phone: "(315) 685-7568",
    },
    {
      name: "Bird's Nest Motel",
      address: "1601 E Genesee St, Skaneateles, NY 13152",
      lat: 42.9437,
      lng: -76.3968,
      priceRange: "$" as const,
      dogPolicy: "Budget-friendly and dog-welcoming with a $15 per night fee. Clean rooms near the lake.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Budget-friendly", "Free parking", "Near lake", "Pet exercise area"],
      rating: 4.0,
      imageUrl: "",
      website: "",
      phone: "(315) 685-5641",
    },
  ],
  nationalParks: [
    {
      name: "Bear Swamp State Forest",
      state: "New York",
      lat: 42.8673,
      lng: -76.4036,
      dogPolicy: "Dogs welcome on all trails on leash or under voice control. Extensive trail network through forested hills.",
      dogTrails: ["Onondaga Trail", "Bear Swamp Loop", "Skaneateles Creek Trail"],
      restrictions: ["Leash recommended", "Hunting in season", "Pack out waste"],
      description:
        "A state forest south of Skaneateles Lake with rolling wooded trails through hardwood and evergreen forest. The trails follow ridgelines and creek valleys, offering a satisfying wilderness experience close to town. Your dog will enjoy the diverse terrain and the occasional creek crossing.",
      imageUrl: "",
      website: "https://www.dec.ny.gov",
    },
    {
      name: "Fillmore Glen State Park",
      state: "New York",
      lat: 42.7162,
      lng: -76.3949,
      dogPolicy: "Leashed dogs welcome on the Rim Trail and South Trail. A gorgeous gorge with five waterfalls.",
      dogTrails: ["Rim Trail", "South Trail", "North Meadow Trail"],
      restrictions: ["Leash required", "No dogs on Gorge Trail", "Clean up required"],
      description:
        "Named for President Millard Fillmore who was born nearby, this park features a dramatic gorge with five waterfalls. While dogs can't access the main gorge trail, the Rim Trail offers beautiful overlook views. About 30 minutes from Skaneateles, it makes an excellent day trip.",
      imageUrl: "",
      website: "https://parks.ny.gov/parks/fillmoreglen",
    },
    {
      name: "Charlie Major Nature Trail",
      state: "New York",
      lat: 42.9541,
      lng: -76.4219,
      dogPolicy: "Leashed dogs welcome on this paved lakeside trail connecting to downtown Skaneateles.",
      dogTrails: ["Charlie Major Trail (1.3 miles paved)", "Shotwell Park Connection"],
      restrictions: ["Leash required", "Yield to other trail users", "Clean up required"],
      description:
        "A paved 1.3-mile trail along the eastern shore of Skaneateles Lake connecting the village to the Austin Park area. The trail offers gorgeous lake views, shaded stretches, and access to waterfront parks. It's the most popular dog walk in the village — easy, scenic, and conveniently located.",
      imageUrl: "",
      website: "https://www.skaneateles.com",
    },
  ],
  restaurants: [
    {
      name: "The Sherwood Inn Restaurant",
      address: "26 W Genesee St, Skaneateles, NY 13152",
      lat: 42.9469,
      lng: -76.4305,
      cuisine: "American",
      priceRange: "$$$" as const,
      dogPolicy: "Historic inn restaurant with a lakefront porch. Leashed dogs welcome on the porch. Farm-to-table Finger Lakes cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.thesherwoodinn.com",
    },
    {
      name: "The Krebs",
      address: "53 W Genesee St, Skaneateles, NY 13152",
      lat: 42.9471,
      lng: -76.4313,
      cuisine: "New American",
      priceRange: "$$$$" as const,
      dogPolicy: "Upscale restaurant with seasonal garden dining. Dogs welcome in the outdoor garden area. Elegant Finger Lakes cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.thekrebs.com",
    },
    {
      name: "Skaneateles Brewery",
      address: "4022 Mill Rd, Skaneateles, NY 13152",
      lat: 42.9358,
      lng: -76.446,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Lake-view brewery with a dog-friendly patio. House-brewed beers and wood-fired pizza overlooking Skaneateles Lake.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.skaneatelesbrewery.com",
    },
    {
      name: "Blue Water Grill",
      address: "11 W Genesee St, Skaneateles, NY 13152",
      lat: 42.9468,
      lng: -76.4298,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Lakefront restaurant with a dog-friendly deck directly over the water. Fresh seafood with lake views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bluewatergrill.net",
    },
    {
      name: "Doug's Fish Fry",
      address: "8 Jordan St, Skaneateles, NY 13152",
      lat: 42.9472,
      lng: -76.4289,
      cuisine: "Seafood",
      priceRange: "$" as const,
      dogPolicy: "Beloved takeout fish fry with outdoor picnic tables. Dogs welcome at the tables. Cash only institution since 1982.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.dougsfishfry.com",
    },
  ],
  cafes: [
    {
      name: "Skaneateles Bakery",
      address: "19 Jordan St, Skaneateles, NY 13152",
      lat: 42.9473,
      lng: -76.4291,
      dogPolicy: "Village bakery with outdoor benches. Dogs welcome outside while you enjoy fresh pastries and coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "Elephant & the Dove",
      address: "43 E Genesee St, Skaneateles, NY 13152",
      lat: 42.9467,
      lng: -76.4277,
      dogPolicy: "Artisan cafe with outdoor seating on Genesee Street. Dogs welcome. Creative pastries and quality espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
    {
      name: "Mandana Coffee",
      address: "4 Fennell St, Skaneateles, NY 13152",
      lat: 42.9474,
      lng: -76.4285,
      dogPolicy: "Local coffee roaster with outdoor tables near the village center. Dogs welcome at patio seating.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Patisserie at Mirbeau",
      address: "851 W Genesee St, Skaneateles, NY 13152",
      lat: 42.946,
      lng: -76.4528,
      dogPolicy: "French patisserie at the Mirbeau resort with garden seating. Dogs welcome outside among the Monet-inspired gardens.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.mirbeau.com",
    },
  ],
  dogParks: [
    {
      name: "Clift Park & Thayer Park",
      address: "W Genesee St, Skaneateles, NY 13152",
      lat: 42.9472,
      lng: -76.4316,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Lake access", "Pier", "Gazebo", "Benches", "Village center"],
      rating: 4.6,
      imageUrl: "",
      description:
        "The heart of Skaneateles village where a beautiful lakefront park offers direct access to the crystal-clear water. Your leashed dog can wade at the lake's edge while you enjoy views from the pier and gazebo. The park connects to downtown shops and restaurants.",
    },
    {
      name: "Charlie Major Nature Trail",
      address: "E Genesee St, Skaneateles, NY 13152",
      lat: 42.9541,
      lng: -76.4219,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Paved trail", "Lake views", "Shade trees", "Benches", "Wildlife viewing"],
      rating: 4.5,
      imageUrl: "",
      description:
        "The village's premier walking trail follows the eastern lake shore for 1.3 paved miles through shaded forest with frequent lake overlooks. It's the most popular dog walk in Skaneateles for good reason — easy access, beautiful scenery, and a perfect length for a morning or evening stroll.",
    },
    {
      name: "Austin Park",
      address: "Austin St Extension, Skaneateles, NY 13152",
      lat: 42.9558,
      lng: -76.422,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["Lakeshore access", "Picnic tables", "Grassy lawn", "Boat launch nearby"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A lakeside park at the northern end of the Charlie Major Trail with picnic areas and a grassy lawn sloping to the water. Your leashed dog can wade in the clear lake water while you enjoy the peaceful setting away from the village center crowds.",
    },
    {
      name: "Shotwell Memorial Park",
      address: "State St, Skaneateles, NY 13152",
      lat: 42.9518,
      lng: -76.4246,
      offLeash: false,
      fenced: false,
      acres: 6.0,
      amenities: ["Sports fields", "Walking paths", "Open green space", "Playground", "Parking"],
      rating: 4.1,
      imageUrl: "",
      description:
        "A community park with open green spaces, walking paths, and sports fields. While not as scenic as the lakefront, it offers a reliable space for leashed dog walks with room to stretch. The paths connect to the Charlie Major Nature Trail for extended outings.",
    },
  ],
};
