export const spokaneData = {
  city: {
    name: "Spokane",
    state: "Washington",
    region: "Pacific Northwest",
    lat: 47.6588,
    lng: -117.4260,
    dogFriendlinessScore: 7,
    description:
      "The largest city in eastern Washington straddles the Spokane River with dramatic waterfalls in its downtown core and hundreds of miles of trails in the surrounding mountains. With a growing food scene, abundant parks, and an outdoor culture that embraces dogs, Spokane is an underappreciated dog destination.",
    heroImage: "https://images.unsplash.com/photo-1547483238-f400e65ccd56?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 228989,
  },
  hotels: [
    {
      name: "The Historic Davenport Hotel",
      address: "10 S Post St, Spokane, WA 99201",
      lat: 47.6580,
      lng: -117.4270,
      priceRange: "$$$$" as const,
      dogPolicy: "Grand historic hotel welcoming dogs under 80 lbs in designated rooms. Opulent lobby and walkable downtown Spokane location.",
      maxDogWeight: 80,
      petFee: 50,
      amenities: ["Dog bed", "Treats", "Downtown location", "Water bowls", "Walking map"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.davenporthotelcollection.com",
      phone: "(509) 455-8888",
    },
    {
      name: "Hotel Indigo Spokane",
      address: "110 S Madison St, Spokane, WA 99201",
      lat: 47.6570,
      lng: -117.4250,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique hotel near Riverfront Park with pet-friendly rooms. Dogs of all sizes welcome near the Spokane Falls.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Riverfront proximity", "Dog bed", "Water bowls", "Modern rooms", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(509) 747-3500",
    },
    {
      name: "Ruby Hotel",
      address: "901 W 1st Ave, Spokane, WA 99201",
      lat: 47.6560,
      lng: -117.4320,
      priceRange: "$$" as const,
      dogPolicy: "Modern downtown hotel welcoming dogs with easy access to the Centennial Trail and riverfront parks.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Trail access", "Dog bed", "Water bowls", "Parking", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.rubyhotelspokane.com",
      phone: "(509) 747-1041",
    },
    {
      name: "Quality Inn Downtown Spokane",
      address: "110 E 4th Ave, Spokane, WA 99202",
      lat: 47.6550,
      lng: -117.4200,
      priceRange: "$" as const,
      dogPolicy: "Affordable downtown option welcoming dogs of all sizes. Walking distance to Riverfront Park and the Centennial Trail.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: ["Pet-friendly rooms", "Parking", "Downtown location", "Breakfast", "Waste bags"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.choicehotels.com",
      phone: "(509) 838-6101",
    },
  ],
  nationalParks: [
    {
      name: "Riverside State Park",
      state: "Washington",
      lat: 47.7000,
      lng: -117.4900,
      dogPolicy: "Dogs welcome on all trails on leash. Over 10,000 acres of river canyons, pine forests, and basalt formations northwest of Spokane.",
      dogTrails: ["Bowl & Pitcher Loop", "Centennial Trail", "Deep Creek Trail", "Military Cemetery Trail"],
      restrictions: ["Leash required at all times", "Discover Pass required", "Rocky terrain on some trails", "River currents can be dangerous"],
      description: "One of Washington's largest state parks, Riverside offers dramatic basalt canyon scenery along the Spokane and Little Spokane rivers. Dogs can explore the iconic Bowl & Pitcher rock formations and miles of forested trails.",
      imageUrl: "",
      website: "https://www.parks.wa.gov/riverside",
    },
    {
      name: "Mount Spokane State Park",
      state: "Washington",
      lat: 47.9200,
      lng: -117.1100,
      dogPolicy: "Dogs welcome on trails on leash. Mountain summit offers panoramic views of the Inland Northwest and into Idaho and Canada.",
      dogTrails: ["Summit Loop Trail", "Trail 130", "Trail 140", "Kit Carson Loop"],
      restrictions: ["Leash required", "Discover Pass required", "Snow on upper trails into early summer", "Mountain weather can change quickly"],
      description: "Rising to nearly 6,000 feet northeast of Spokane, Mount Spokane offers alpine meadows, old-growth forest, and sweeping views from the summit. Dogs enjoy the mountain trails and cooler temperatures during Spokane's hot summers.",
      imageUrl: "",
      website: "https://www.parks.wa.gov/mountspokane",
    },
    {
      name: "Turnbull National Wildlife Refuge",
      state: "Washington",
      lat: 47.4200,
      lng: -117.5300,
      dogPolicy: "Dogs allowed on the auto tour route and in parking areas on leash only. Not permitted on walking trails during nesting season.",
      dogTrails: ["Auto Tour Loop (from vehicle)"],
      restrictions: ["Dogs only in parking areas and along roads", "Leash required", "Seasonal restrictions during nesting", "Entrance fee may apply"],
      description: "South of Spokane, this wildlife refuge protects channeled scablands habitat with lakes, marshes, and pine forests. While dog access is limited, the scenic auto tour offers excellent wildlife viewing including elk, moose, and waterfowl.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/turnbull",
    },
  ],
  restaurants: [
    {
      name: "Clinkerdagger",
      address: "621 W Mallon Ave, Spokane, WA 99201",
      lat: 47.6630,
      lng: -117.4300,
      cuisine: "Steakhouse",
      priceRange: "$$$" as const,
      dogPolicy: "Iconic Spokane steakhouse overlooking the river with a seasonal patio where dogs are welcome. Prime steaks with Spokane Falls views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.clinkerdagger.com",
    },
    {
      name: "No-Li Brewhouse",
      address: "1003 E Trent Ave, Spokane, WA 99202",
      lat: 47.6620,
      lng: -117.4050,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Award-winning riverside brewery with a large dog-friendly patio overlooking the Spokane River. Craft beers and pub fare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.nolibrewhouse.com",
    },
    {
      name: "Ruins",
      address: "825 N Monroe St, Spokane, WA 99201",
      lat: 47.6640,
      lng: -117.4340,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Creative seasonal restaurant in a converted laundry building with a patio welcoming dogs. Innovative Pacific Northwest cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.ruinsspokane.com",
    },
    {
      name: "Wandering Table",
      address: "1242 W Summit Pkwy, Spokane, WA 99201",
      lat: 47.6650,
      lng: -117.4400,
      cuisine: "Pacific Northwest",
      priceRange: "$$$" as const,
      dogPolicy: "Gastropub with a gorgeous patio in Kendall Yards. Dogs welcome on the terrace with views of the gorge below.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thewanderingtable.com",
    },
    {
      name: "Frank's Diner",
      address: "1516 W 2nd Ave, Spokane, WA 99201",
      lat: 47.6540,
      lng: -117.4360,
      cuisine: "Diner & Breakfast",
      priceRange: "$" as const,
      dogPolicy: "Beloved breakfast spot in a converted 1906 railcar with outdoor tables where dogs are welcome. Classic diner fare with Spokane charm.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.franksdiner.com",
    },
  ],
  cafes: [
    {
      name: "Indaba Coffee Roasters",
      address: "1425 W Broadway Ave, Spokane, WA 99201",
      lat: 47.6555,
      lng: -117.4350,
      dogPolicy: "Socially conscious roaster with a patio where dogs are welcome. Direct-trade coffee supporting global communities.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.indabacoffee.com",
    },
    {
      name: "Arctos Coffee & Roasting Co.",
      address: "232 W 2nd Ave, Spokane, WA 99201",
      lat: 47.6565,
      lng: -117.4275,
      dogPolicy: "Downtown roaster with outdoor seating and a warm atmosphere. Dogs welcome on the patio with craft espresso and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.arctoscoffee.com",
    },
    {
      name: "Vessel Coffee Roasters",
      address: "1425 S Lincoln St, Spokane, WA 99203",
      lat: 47.6400,
      lng: -117.4330,
      dogPolicy: "South Hill roaster with a patio and neighborhood feel. Dogs welcome outside with precision-roasted single-origin coffees.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.vesselcoffee.com",
    },
    {
      name: "Atticus Coffee & Gifts",
      address: "222 N Howard St, Spokane, WA 99201",
      lat: 47.6590,
      lng: -117.4255,
      dogPolicy: "Bookish downtown café with a small patio where dogs are welcome. Coffee and literary gifts in a cozy setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.atticuscoffeespokane.com",
    },
  ],
  dogParks: [
    {
      name: "High Bridge Dog Park",
      address: "A St & W 13th Ave, Spokane, WA 99201",
      lat: 47.6470,
      lng: -117.4500,
      offLeash: true,
      fenced: true,
      acres: 5,
      amenities: ["Separate small dog area", "Water stations", "Shade trees", "Benches", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "Spokane's largest fenced off-leash dog park with separate areas for large and small dogs. The park sits in a natural forested setting near the Spokane River with mature trees providing shade.",
    },
    {
      name: "Centennial Trail",
      address: "Spokane Falls Blvd, Spokane, WA 99201",
      lat: 47.6600,
      lng: -117.4260,
      offLeash: false,
      fenced: false,
      acres: 40,
      amenities: ["Paved trail", "River views", "Falls viewpoints", "Benches", "Waste bag stations"],
      rating: 4.7,
      imageUrl: "",
      description: "A 40-mile paved trail along the Spokane River stretching from Idaho to Nine Mile Falls. The downtown section passes through Riverfront Park with views of the dramatic Spokane Falls. Leashed dogs enjoy this scenic urban pathway.",
    },
    {
      name: "South Hill Dog Park",
      address: "2600 S Southeast Blvd, Spokane, WA 99203",
      lat: 47.6300,
      lng: -117.3900,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water fountain", "Benches", "Shade", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "A community dog park on Spokane's South Hill with fenced off-leash areas. Convenient for residential dog owners with shade trees and water access for dogs.",
    },
    {
      name: "Bowl & Pitcher Trail (Riverside State Park)",
      address: "4427 N Aubrey L White Pkwy, Spokane, WA 99205",
      lat: 47.6950,
      lng: -117.4850,
      offLeash: false,
      fenced: false,
      acres: 100,
      amenities: ["Hiking trails", "Basalt formations", "River views", "Suspension bridge", "Parking"],
      rating: 4.8,
      imageUrl: "",
      description: "The most scenic trail in the Spokane area winds past dramatic basalt rock formations along the Spokane River. Leashed dogs cross the iconic suspension bridge and explore the pine-forested canyon in this stunning section of Riverside State Park.",
    },
  ],
};
