export const stAugustineData = {
  city: {
    name: "St. Augustine",
    state: "Florida",
    region: "Southeast",
    lat: 29.9012,
    lng: -81.3124,
    dogFriendlinessScore: 7,
    description:
      "America's oldest city rolls out the red carpet for dogs with its cobblestone streets, horse-drawn carriage tours that welcome pups, and miles of pristine Atlantic beaches. St. Augustine's historic charm, world-class restaurants with courtyard dining, and a thriving arts scene all come with a four-legged-friendly twist. Your dog can soak up 500 years of history while soaking up Florida sunshine.",
    heroImage: "https://images.unsplash.com/photo-1569878698889-7bffa1896872?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 14309,
  },

  hotels: [
    {
      name: "Casa Monica Resort & Spa",
      address: "95 Cordova St, St. Augustine, FL 32084",
      lat: 29.8940,
      lng: -81.3123,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a one-time pet fee. Historic luxury in the heart of the old city.",
      maxDogWeight: 50,
      petFee: 100,
      amenities: ["Dog bed", "Ceramic bowls", "Gourmet treats", "Walking map", "Pet concierge"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.casamonica.com",
      phone: "(904) 827-1888",
    },
    {
      name: "The Collector Luxury Inn & Gardens",
      address: "749 S Ponce de Leon Blvd, St. Augustine, FL 32084",
      lat: 29.8870,
      lng: -81.3102,
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome in select rooms with advance notice. Beautifully landscaped gardens for morning walks.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Garden walking paths", "Dog bed", "Water bowls", "Courtyard access", "Treats"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.thecollectorinn.com",
      phone: "(904) 209-6800",
    },
    {
      name: "La Quinta Inn St. Augustine",
      address: "1300 N Ponce de Leon Blvd, St. Augustine, FL 32084",
      lat: 29.9095,
      lng: -81.3120,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with no pet fee. Budget-friendly with easy access to the historic district.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pet relief area", "Waste bags", "Pool", "Free breakfast"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(904) 824-3383",
    },
    {
      name: "St. George Inn",
      address: "4 St George St, St. Augustine, FL 32084",
      lat: 29.8945,
      lng: -81.3115,
      priceRange: "$$$" as const,
      dogPolicy: "Small dogs up to 25 lbs welcome in select rooms. Prime location on the pedestrian-only St. George Street.",
      maxDogWeight: 25,
      petFee: 50,
      amenities: ["Walking distance to everything", "Dog bed", "Water bowls", "Balcony views", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.stgeorgeinn.com",
      phone: "(904) 827-5740",
    },
    {
      name: "Bayfront Marin House",
      address: "142 Avenida Menendez, St. Augustine, FL 32084",
      lat: 29.8920,
      lng: -81.3075,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 35 lbs welcome in designated pet rooms. Charming B&B with Matanzas Bay views.",
      maxDogWeight: 35,
      petFee: 60,
      amenities: ["Bay views", "Garden", "Gourmet breakfast", "Dog bed", "Walking map"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bayfrontmarinhouse.com",
      phone: "(904) 824-4301",
    },
  ],

  nationalParks: [
    {
      name: "Fort Matanzas National Monument",
      state: "Florida",
      lat: 29.7150,
      lng: -81.2385,
      dogPolicy: "Leashed dogs welcome on the nature trail and grounds. Not permitted on the ferry to the fort or inside the fort.",
      dogTrails: ["Nature Boardwalk Trail (0.5 miles)", "Beach walk"],
      restrictions: [
        "Not allowed on ferry to fort",
        "Not allowed inside the fort",
        "Must be on a 6-foot leash",
        "Not allowed in visitor center",
      ],
      description:
        "About 15 miles south of St. Augustine, this monument features a beautiful boardwalk nature trail through coastal hammock and a pristine beach. While dogs cannot ride the ferry to the 1742 Spanish watchtower, the mainland trails and beach are wonderful for leashed pups.",
      imageUrl: "",
      website: "https://www.nps.gov/foma",
    },
    {
      name: "Castillo de San Marcos National Monument",
      state: "Florida",
      lat: 29.8980,
      lng: -81.3115,
      dogPolicy: "Leashed dogs welcome on the grounds outside the fort walls and along the seawall. Not permitted inside the coquina fortress.",
      dogTrails: ["Seawall walkway", "Fort grounds perimeter"],
      restrictions: [
        "Not allowed inside the fort",
        "Must be on leash",
        "Not allowed at ranger programs",
      ],
      description:
        "The oldest masonry fort in the continental United States sits right on the St. Augustine bayfront. While dogs cannot enter the 17th-century coquina walls, they can walk the scenic grounds with views of Matanzas Bay and the Bridge of Lions.",
      imageUrl: "",
      website: "https://www.nps.gov/casa",
    },
    {
      name: "Timucuan Ecological and Historic Preserve",
      state: "Florida",
      lat: 30.3930,
      lng: -81.4950,
      dogPolicy: "Leashed dogs welcome on trails and in picnic areas. A vast coastal wetland preserve with diverse ecosystems.",
      dogTrails: ["Willie Browne Trail", "Theodore Roosevelt Area trails", "Spanish Pond Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed in historic structures",
        "Must stay on designated trails",
      ],
      description:
        "About an hour north near Jacksonville, this 46,000-acre preserve encompasses salt marshes, coastal hammocks, and historic sites. Leashed dogs can explore the shaded trails and encounter an incredible variety of coastal wildlife.",
      imageUrl: "",
      website: "https://www.nps.gov/timu",
    },
  ],

  restaurants: [
    {
      name: "The Floridian",
      address: "72 Spanish St, St. Augustine, FL 32084",
      lat: 29.8950,
      lng: -81.3108,
      cuisine: "Southern Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the charming courtyard patio. Locally sourced Southern cuisine with creative twists.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.thefloridianstaug.com",
    },
    {
      name: "Cap's on the Water",
      address: "4325 Myrtle St, St. Augustine, FL 32084",
      lat: 29.8620,
      lng: -81.2765,
      cuisine: "Seafood",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the waterfront deck overlooking the Intracoastal. Fresh seafood with gorgeous sunset views.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.capsonthewater.com",
    },
    {
      name: "Dog Rose Brewing Co.",
      address: "77 Bridge St, St. Augustine, FL 32084",
      lat: 29.8855,
      lng: -81.3102,
      cuisine: "Brewery & Pub",
      priceRange: "$$" as const,
      dogPolicy: "Extremely dog-friendly brewery named after a wildflower. Dogs welcome inside and out with water bowls always ready.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.dogrosebrewing.com",
    },
    {
      name: "The Columbia Restaurant",
      address: "98 St. George St, St. Augustine, FL 32084",
      lat: 29.8955,
      lng: -81.3115,
      cuisine: "Spanish-Cuban",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the beautiful courtyard patio. Florida's oldest restaurant chain with authentic Spanish cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.columbiarestaurant.com",
    },
    {
      name: "Osprey Tacos",
      address: "55 Cordova St, St. Augustine, FL 32084",
      lat: 29.8938,
      lng: -81.3118,
      cuisine: "Mexican Street Food",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly outdoor seating with a laid-back vibe. Creative tacos and killer margaritas.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.ospreytacos.com",
    },
    {
      name: "Catch 27",
      address: "40 Charlotte St, St. Augustine, FL 32084",
      lat: 29.8948,
      lng: -81.3102,
      cuisine: "Seafood",
      priceRange: "$$$$" as const,
      dogPolicy: "Well-behaved dogs welcome at select outdoor tables. Upscale seasonal seafood in the historic district.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.catch27.com",
    },
    {
      name: "The Tasting Room",
      address: "25 Cuna St, St. Augustine, FL 32084",
      lat: 29.8952,
      lng: -81.3098,
      cuisine: "Wine Bar & Tapas",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome in the lush courtyard. Wine flights and tapas under Spanish moss-draped oaks.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thetastingroomstaug.com",
    },
    {
      name: "Jaybird's",
      address: "1021 A1A Beach Blvd, St. Augustine Beach, FL 32080",
      lat: 29.8510,
      lng: -81.2660,
      cuisine: "American Beach Bar",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly outdoor patio steps from the beach. Cold drinks, beach vibes, and happy pups.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.jaybirdsstaugbeach.com",
    },
  ],

  cafes: [
    {
      name: "Juniper Market",
      address: "12 S Castillo Dr, St. Augustine, FL 32084",
      lat: 29.8975,
      lng: -81.3100,
      dogPolicy: "Leashed dogs welcome on the patio. Specialty coffee, fresh juices, and gourmet bites near the bayfront.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.junipermarketstaug.com",
    },
    {
      name: "Kookaburra Coffee",
      address: "646 A1A Beach Blvd, St. Augustine Beach, FL 32080",
      lat: 29.8565,
      lng: -81.2672,
      dogPolicy: "Dog-friendly outdoor area at this Australian-inspired coffee shop near the beach. Great flat whites.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.kookaburracoffeestaug.com",
    },
    {
      name: "Corazon Coffee Roasters",
      address: "200 Anastasia Blvd, St. Augustine, FL 32080",
      lat: 29.8905,
      lng: -81.3010,
      dogPolicy: "Leashed dogs welcome at the shaded outdoor tables. House-roasted coffee in a vibrant setting.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.corazoncoffee.com",
    },
    {
      name: "The Kookaburra",
      address: "43 San Marco Ave, St. Augustine, FL 32084",
      lat: 29.9008,
      lng: -81.3125,
      dogPolicy: "Shaded patio with water bowls for your pup while you enjoy artisan pastries and espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.thekookaburra.com",
    },
    {
      name: "Georgie's Diner",
      address: "100 A1A Beach Blvd, St. Augustine Beach, FL 32080",
      lat: 29.8585,
      lng: -81.2665,
      dogPolicy: "Dog-friendly outdoor seating with a retro beach diner atmosphere. Coffee, breakfast, and fresh-squeezed OJ.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.georgiesdiner.com",
    },
  ],

  dogParks: [
    {
      name: "Treaty Park Dog Park",
      address: "1595 Wildwood Dr, St. Augustine, FL 32086",
      lat: 29.8710,
      lng: -81.3180,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Separate small and large dog areas", "Water stations", "Agility equipment", "Shade shelters", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "St. Augustine's best fenced dog park with separate areas for big and small dogs, agility equipment for active pups, and shaded shelters for when the Florida sun gets intense. A local favorite and social hub for the canine community.",
    },
    {
      name: "Anastasia State Park Beach",
      address: "300 Anastasia Park Rd, St. Augustine, FL 32080",
      lat: 29.8690,
      lng: -81.2710,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Beach access", "Nature trails", "Kayak launch", "Restrooms", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "This gorgeous state park offers miles of pristine Atlantic beach where leashed dogs can walk the shoreline and wade in the waves. The maritime hammock trails provide shaded walking through ancient live oaks and palms.",
    },
    {
      name: "Riverside Dog Park",
      address: "25 Riberia St, St. Augustine, FL 32084",
      lat: 29.8890,
      lng: -81.3148,
      offLeash: true,
      fenced: true,
      acres: 1.0,
      amenities: ["Fenced enclosure", "Water fountain", "Benches", "Shade trees", "Waste stations"],
      rating: 4.1,
      imageUrl: "",
      description:
        "A compact but well-maintained fenced dog park in the Lincolnville neighborhood. Perfect for a quick off-leash session when you are exploring the historic district with your pup.",
    },
    {
      name: "St. Augustine Beach Dog-Friendly Area",
      address: "A1A Beach Blvd, St. Augustine Beach, FL 32080",
      lat: 29.8460,
      lng: -81.2640,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Beach access", "Ocean swimming", "Outdoor showers", "Parking", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Leashed dogs are welcome on St. Augustine Beach, and the wide sandy shoreline gives plenty of room to stroll, play, and watch the waves. The hard-packed sand near the water's edge is perfect for those long beach walks your pup loves.",
    },
    {
      name: "Ron Parker Dog Park",
      address: "505 Pope Rd, St. Augustine, FL 32080",
      lat: 29.8582,
      lng: -81.2750,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Double-gated entry", "Separate areas", "Water spigot", "Benches", "Waste stations", "Shade canopy"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A friendly, fenced off-leash park near St. Augustine Beach with separate areas for large and small dogs. The community atmosphere means your pup will quickly make new friends under the Florida palms.",
    },
  ],
};
