export const stLouisData = {
  city: {
    name: "St. Louis",
    state: "Missouri",
    region: "Midwest",
    lat: 38.6270,
    lng: -90.1994,
    dogFriendlinessScore: 7,
    description:
      "The Gateway to the West offers dogs a surprising abundance of green space, including the massive Forest Park, a thriving food scene with generous patios, and a Midwestern friendliness that embraces pups. The city's many free attractions and walkable neighborhoods make it a budget-friendly dog-friendly destination.",
    heroImage: "https://images.unsplash.com/photo-1567460989031-68e03c0e7607?w=1200&fit=crop",
    climate: "Humid continental",
    population: 301578,
  },
  hotels: [
    {
      name: "Hotel Saint Louis",
      address: "705 Olive St, St. Louis, MO 63101",
      lat: 38.6290,
      lng: -90.1920,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of any size welcome with a per-stay fee. A boutique hotel in a restored historic building downtown.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Walking map", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelsaintlouis.com",
      phone: "(314) 621-2600",
    },
    {
      name: "Kimpton Hotel Monaco St. Louis",
      address: "501 Washington Ave, St. Louis, MO 63101",
      lat: 38.6320,
      lng: -90.1880,
      priceRange: "$$$" as const,
      dogPolicy: "All pets welcome regardless of size at no extra charge. Kimpton's signature pet-friendly hospitality on Washington Avenue.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Loaner leashes", "Pet concierge"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ihg.com/kimptonhotels/hotels/us/en/st-louis/stlkm",
      phone: "(314) 390-4700",
    },
    {
      name: "Drury Plaza Hotel St. Louis at the Arch",
      address: "2 S 4th St, St. Louis, MO 63102",
      lat: 38.6260,
      lng: -90.1860,
      priceRange: "$$" as const,
      dogPolicy: "Dogs up to 80 lbs welcome with a per-stay fee. Steps from the Gateway Arch with complimentary evening kickback.",
      maxDogWeight: 80,
      petFee: 50,
      amenities: ["Pet-friendly rooms", "Water bowls", "Waste bags", "Walking access to Arch grounds"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.druryhotels.com/locations/st-louis-mo",
      phone: "(314) 231-3003",
    },
    {
      name: "Moonrise Hotel",
      address: "6177 Delmar Blvd, St. Louis, MO 63112",
      lat: 38.6550,
      lng: -90.3010,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome with a per-night fee. A quirky boutique hotel on the Delmar Loop.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Dog bed", "Water bowls", "Rooftop bar access", "Waste bags", "Treats"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.moonrisehotel.com",
      phone: "(314) 721-1111",
    },
  ],
  nationalParks: [
    {
      name: "Gateway Arch National Park",
      state: "Missouri",
      lat: 38.6247,
      lng: -90.1848,
      dogPolicy: "Dogs welcome on the grounds and along the riverfront on a leash. Not permitted inside the Arch or visitor center.",
      dogTrails: ["Riverfront Trail", "Arch Grounds Walk", "Luther Ely Smith Square"],
      restrictions: ["Leash required", "Not inside the Arch", "Not in visitor center or museum", "Must clean up after pet"],
      description: "The iconic Gateway Arch stands 630 feet above the Mississippi River. While dogs cannot ride to the top, they can walk the expansive grounds and riverfront paths with stunning views of the monument.",
      imageUrl: "",
      website: "https://www.nps.gov/jeff",
    },
    {
      name: "Forest Park",
      state: "Missouri",
      lat: 38.6340,
      lng: -90.2840,
      dogPolicy: "Dogs welcome on all paths and in most areas on a leash. A 1,300-acre urban park larger than Central Park.",
      dogTrails: ["Forest Park Loop", "Kennedy Forest Trail", "Art Hill Walk", "Pagoda Circle Trail"],
      restrictions: ["Leash required except at dog parks", "Not in zoo", "Not in museums", "Must clean up after pet"],
      description: "At 1,300 acres, Forest Park is one of the largest urban parks in the US, home to the free St. Louis Zoo, art museum, and science center. Dogs enjoy the forested trails, lakes, and wide open spaces.",
      imageUrl: "",
      website: "https://www.forestparkforever.org",
    },
    {
      name: "Castlewood State Park",
      state: "Missouri",
      lat: 38.5720,
      lng: -90.5480,
      dogPolicy: "Dogs welcome on all trails on a leash. Dramatic bluffs and river views along the Meramec River.",
      dogTrails: ["River Scene Trail", "Bluff Trail", "Grotpeter Trail", "Creek Trail"],
      restrictions: ["Leash required", "Not on beach", "Must clean up after pet"],
      description: "About 25 minutes west of downtown, Castlewood features dramatic limestone bluffs above the Meramec River. Dogs can hike the blufftop trails with stunning river valley views.",
      imageUrl: "",
      website: "https://www.mostateparks.com/park/castlewood-state-park",
    },
  ],
  restaurants: [
    {
      name: "Pappy's Smokehouse",
      address: "3106 Olive St, St. Louis, MO 63103",
      lat: 38.6370,
      lng: -90.2180,
      cuisine: "Barbecue",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor picnic tables. Legendary St. Louis barbecue with Memphis-style ribs and smoked meats.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.pappyssmokehouse.com",
    },
    {
      name: "Urban Chestnut Brewing Company",
      address: "4465 Manchester Ave, St. Louis, MO 63110",
      lat: 38.6310,
      lng: -90.2560,
      cuisine: "Brewpub & German",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the beer hall and outdoor biergarten. A German-American brewery in the Grove neighborhood.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.urbanchestnut.com",
    },
    {
      name: "Cafe Natasha",
      address: "3200 S Grand Blvd, St. Louis, MO 63118",
      lat: 38.6110,
      lng: -90.2340,
      cuisine: "Persian",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the South Grand patio. Exceptional Persian cuisine on one of St. Louis's most diverse restaurant rows.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.cafenatasha.com",
    },
    {
      name: "Salt + Smoke",
      address: "6525 Delmar Blvd, St. Louis, MO 63130",
      lat: 38.6570,
      lng: -90.3080,
      cuisine: "Barbecue",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the Delmar Loop patio. Creative barbecue with smoked meats and inventive sides.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.saltandsmokestl.com",
    },
    {
      name: "Tower Taco",
      address: "3147 S Grand Blvd, St. Louis, MO 63118",
      lat: 38.6120,
      lng: -90.2340,
      cuisine: "Mexican Street Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor seating on South Grand. Fresh tacos and agua frescas in a casual setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.towertaco.com",
    },
  ],
  cafes: [
    {
      name: "Sump Coffee",
      address: "3700 S Jefferson Ave, St. Louis, MO 63118",
      lat: 38.6050,
      lng: -90.2250,
      dogPolicy: "Dogs welcome on the outdoor patio. A nationally acclaimed specialty coffee shop with meticulous preparation.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.sumpcoffee.com",
    },
    {
      name: "Blueprint Coffee",
      address: "6225 Delmar Blvd, St. Louis, MO 63130",
      lat: 38.6560,
      lng: -90.3030,
      dogPolicy: "Dogs welcome on the Delmar Loop patio. A quality-focused roaster with bright, clean coffees.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.blueprintcoffee.com",
    },
    {
      name: "Rise Coffee House",
      address: "4180 Manchester Ave, St. Louis, MO 63110",
      lat: 38.6300,
      lng: -90.2510,
      dogPolicy: "Dog-friendly outdoor seating in the Grove. A community coffee shop with a social mission and friendly atmosphere.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.risecoffeestl.com",
    },
    {
      name: "Comet Coffee",
      address: "5708 Oakland Ave, St. Louis, MO 63110",
      lat: 38.6340,
      lng: -90.2690,
      dogPolicy: "Dogs welcome at the outdoor tables near the Hill neighborhood. Specialty coffee with a neighborhood feel.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cometcoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Forest Park Dog Park",
      address: "5575 Grand Dr, St. Louis, MO 63112",
      lat: 38.6340,
      lng: -90.2870,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade trees", "Waste bag stations"],
      rating: 4.5,
      imageUrl: "",
      description: "Set within the sprawling Forest Park, this fenced dog park offers off-leash fun with the park's beautiful scenery as a backdrop. Separate areas for large and small dogs with water stations.",
    },
    {
      name: "Tower Grove Dog Park",
      address: "4257 Magnolia Ave, St. Louis, MO 63110",
      lat: 38.6090,
      lng: -90.2510,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Double-gated entry", "Water fountain", "Benches", "Shade canopy", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      description: "A beloved dog park within the historic Tower Grove Park. The fenced area provides off-leash play beneath mature shade trees, surrounded by the park's Victorian pavilions.",
    },
    {
      name: "Soulard Dog Park",
      address: "1400 Russell Blvd, St. Louis, MO 63104",
      lat: 38.6120,
      lng: -90.2060,
      offLeash: true,
      fenced: true,
      acres: 1,
      amenities: ["Double-gated entry", "Benches", "Water fountain", "Waste bag stations"],
      rating: 4.1,
      imageUrl: "",
      description: "A compact neighborhood dog park in the historic Soulard district. Convenient for dogs staying near the French Quarter-inspired neighborhood with its farmers market and brick-lined streets.",
    },
    {
      name: "Willmore Dog Park",
      address: "4777 Morganford Rd, St. Louis, MO 63116",
      lat: 38.5980,
      lng: -90.2580,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Open grassy area", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      description: "A south city dog park with separate areas for different-sized dogs and ample green space. The well-maintained park is a favorite for the surrounding neighborhood dog community.",
    },
  ],
};
