export const stPetersburgData = {
  city: {
    name: "St. Petersburg",
    state: "Florida",
    region: "Southeast",
    lat: 27.7676,
    lng: -82.6403,
    dogFriendlinessScore: 8,
    description:
      "St. Pete shines as one of Florida's most dog-friendly cities with its dedicated dog beaches, vibrant arts district with pet-welcoming galleries, and an incredible array of waterfront dining. The city's 361 days of sunshine per year mean nearly endless opportunities for outdoor adventures with your pup.",
    heroImage: "https://images.unsplash.com/photo-1563783850023-077d43f47308?w=1200&fit=crop",
    climate: "Tropical savanna",
    population: 258308,
  },
  hotels: [
    {
      name: "The Vinoy Renaissance Resort",
      address: "501 5th Ave NE, St. Petersburg, FL 33701",
      lat: 27.7740,
      lng: -82.6290,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs under 50 lbs welcome with a non-refundable pet fee. A grand 1925 waterfront resort with stunning bay views.",
      maxDogWeight: 50,
      petFee: 150,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Waterfront walking paths", "Pet concierge"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.marriott.com/hotels/travel/tpasr",
      phone: "(727) 894-1000",
    },
    {
      name: "The Birchwood",
      address: "340 Beach Dr NE, St. Petersburg, FL 33701",
      lat: 27.7720,
      lng: -82.6310,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 30 lbs welcome in select rooms. A charming boutique hotel on Beach Drive with a rooftop bar.",
      maxDogWeight: 30,
      petFee: 100,
      amenities: ["Dog bed", "Water bowls", "Walking map", "Waste bags", "Nearby park access"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thebirchwood.com",
      phone: "(727) 896-1080",
    },
    {
      name: "Hotel Zamora",
      address: "3701 Gulf Blvd, St. Pete Beach, FL 33706",
      lat: 27.7260,
      lng: -82.7370,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 40 lbs welcome with a nightly pet fee. A boutique beachfront hotel with Mediterranean flair.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Dog bed", "Water and food bowls", "Treats", "Beach access guide", "Dog waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hotelzamora.com",
      phone: "(727) 456-8957",
    },
    {
      name: "Hollander Hotel",
      address: "421 4th Ave N, St. Petersburg, FL 33701",
      lat: 27.7740,
      lng: -82.6370,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of any size welcome with a per-stay pet fee. A colorful, laid-back hotel in the heart of the arts district.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Pet-friendly rooms", "Pool area", "Water bowls", "Waste bags", "Walking suggestions"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hollanderhotel.com",
      phone: "(727) 873-7900",
    },
  ],
  nationalParks: [
    {
      name: "Fort De Soto Park",
      state: "Florida",
      lat: 27.6225,
      lng: -82.7370,
      dogPolicy: "Dogs welcome throughout the park and on the designated dog beach and Paw Playground. One of the top-rated dog beaches in the US.",
      dogTrails: ["North Beach Trail", "Bay Pier Trail", "Nature Trail", "Fort Trail"],
      restrictions: ["Leash required except at dog beach", "Not allowed at non-designated beaches", "Must clean up after pet"],
      description: "Fort De Soto Park consistently ranks as one of the best dog beaches in America. The designated dog beach and off-leash Paw Playground give dogs free rein to swim and play in the crystalline Gulf waters.",
      imageUrl: "",
      website: "https://www.pinellascounty.org/park/05_ft_desoto.htm",
    },
    {
      name: "Boyd Hill Nature Preserve",
      state: "Florida",
      lat: 27.7370,
      lng: -82.6340,
      dogPolicy: "Dogs welcome on all trails on a 6-foot leash. A 245-acre urban nature preserve with diverse ecosystems.",
      dogTrails: ["Lake Trail", "Willow Marsh Trail", "Scrub Loop Trail", "Pine Flatwoods Trail"],
      restrictions: ["6-foot leash required", "Not allowed in bird sanctuary areas", "Must clean up after pet"],
      description: "Just minutes from downtown St. Pete, Boyd Hill offers 245 acres of natural Florida habitats including pine flatwoods, sand scrub, and lake shoreline. Dogs enjoy the shaded trails and wildlife-watching opportunities.",
      imageUrl: "",
      website: "https://www.stpete.org/boyd-hill",
    },
    {
      name: "Weedon Island Preserve",
      state: "Florida",
      lat: 27.8450,
      lng: -82.6060,
      dogPolicy: "Dogs welcome on the boardwalk and trails on a 6-foot leash. A 3,190-acre natural area with mangrove ecosystems.",
      dogTrails: ["Boardwalk Trail", "Upland Trail", "Boy Scout Trail"],
      restrictions: ["6-foot leash required", "Not allowed in cultural center", "Must stay on marked trails", "Must clean up after pet"],
      description: "One of the largest urban preserves in the Southeast, Weedon Island features mangrove forests, tidal flats, and upland habitats. The elevated boardwalk trail offers stunning bay views and opportunities to spot manatees and dolphins.",
      imageUrl: "",
      website: "https://www.weedonislandpreserve.org",
    },
  ],
  restaurants: [
    {
      name: "The Mill",
      address: "200 Central Ave, St. Petersburg, FL 33701",
      lat: 27.7710,
      lng: -82.6390,
      cuisine: "New American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor patio along Central Avenue. Creative American fare in a restored industrial space.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.themillstpete.com",
    },
    {
      name: "Bodega on Central",
      address: "1120 Central Ave, St. Petersburg, FL 33705",
      lat: 27.7710,
      lng: -82.6520,
      cuisine: "Cuban & Latin",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor window seating. A Cuban street food counter with famous pressed sandwiches.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bodegaoncentral.com",
    },
    {
      name: "Taco Bus",
      address: "2324 Central Ave, St. Petersburg, FL 33713",
      lat: 27.7710,
      lng: -82.6660,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome in the outdoor courtyard. A converted school bus turned taco institution with generous outdoor seating.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.taco-bus.com",
    },
    {
      name: "Cassis American Brasserie",
      address: "170 Beach Dr NE, St. Petersburg, FL 33701",
      lat: 27.7710,
      lng: -82.6310,
      cuisine: "French-American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the Beach Drive patio with waterfront views. Upscale brasserie dining with a European flair.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cassisab.com",
    },
    {
      name: "The Canopy",
      address: "340 Beach Dr NE, St. Petersburg, FL 33701",
      lat: 27.7720,
      lng: -82.6310,
      cuisine: "Rooftop Bar & American",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the rooftop during select hours. Craft cocktails and small plates with panoramic bay views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.thebirchwood.com/the-canopy",
    },
  ],
  cafes: [
    {
      name: "Bandit Coffee Co.",
      address: "2662 Central Ave, St. Petersburg, FL 33712",
      lat: 27.7710,
      lng: -82.6700,
      dogPolicy: "Dogs welcome on the outdoor patio. A specialty coffee shop with meticulous brewing methods and a minimalist aesthetic.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.banditcoffee.com",
    },
    {
      name: "Black Crow Coffee",
      address: "722 1st Ave N, St. Petersburg, FL 33701",
      lat: 27.7740,
      lng: -82.6430,
      dogPolicy: "Dogs welcome in the outdoor garden area. A cozy neighborhood cafe with fresh pastries and strong espresso.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.blackcrowcoffee.com",
    },
    {
      name: "Craft Kafe",
      address: "539 Central Ave, St. Petersburg, FL 33701",
      lat: 27.7710,
      lng: -82.6440,
      dogPolicy: "Dogs welcome at the sidewalk tables on Central Avenue. Specialty coffee and plant-based food in the arts district.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.craftkafe.com",
    },
    {
      name: "Kahwa Coffee",
      address: "204 2nd Ave S, St. Petersburg, FL 33701",
      lat: 27.7700,
      lng: -82.6370,
      dogPolicy: "Dog-friendly outdoor seating. A local roaster born in St. Pete with multiple locations and a commitment to quality.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.kahwacoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Fort De Soto Paw Playground & Dog Beach",
      address: "3500 Pinellas Bayway S, Tierra Verde, FL 33715",
      lat: 27.6230,
      lng: -82.7375,
      offLeash: true,
      fenced: true,
      acres: 6,
      amenities: ["Dog beach", "Swimming area", "Wash stations", "Water fountains", "Waste bag stations"],
      rating: 4.8,
      imageUrl: "",
      description: "Consistently rated one of the best dog beaches in the United States, Fort De Soto's Paw Playground features a fenced area and a stunning beach where dogs swim freely in clear Gulf waters. An absolute must-visit.",
    },
    {
      name: "Crescent Lake Dog Park",
      address: "1320 5th St N, St. Petersburg, FL 33701",
      lat: 27.7810,
      lng: -82.6450,
      offLeash: true,
      fenced: true,
      acres: 2,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade trees", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "A popular in-town dog park within Crescent Lake Park offering fenced off-leash play with lake views. Separate areas for large and small dogs keep everyone safe.",
    },
    {
      name: "Walter Fuller Dog Park",
      address: "7891 26th Ave N, St. Petersburg, FL 33710",
      lat: 27.7910,
      lng: -82.6860,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water fountains", "Agility equipment", "Benches", "Waste bag stations"],
      rating: 4.2,
      imageUrl: "",
      description: "A well-maintained dog park in the Walter Fuller recreation complex with agility equipment and separate areas for large and small dogs. A neighborhood favorite on the west side of St. Pete.",
    },
    {
      name: "Vinoy Park Dog Area",
      address: "701 Bayshore Dr NE, St. Petersburg, FL 33701",
      lat: 27.7780,
      lng: -82.6260,
      offLeash: false,
      fenced: false,
      acres: 10,
      amenities: ["Waterfront walking paths", "Bay views", "Shade trees", "Waste bag stations", "Benches"],
      rating: 4.4,
      imageUrl: "",
      description: "While not off-leash, Vinoy Park offers one of the most scenic on-leash walks in St. Pete along the Tampa Bay waterfront. Dogs love the breezy paths with stunning views of the Vinoy hotel and the bay.",
    },
  ],
};
