export const stanleyData = {
  city: {
    name: "Stanley",
    state: "Idaho",
    region: "Mountain West",
    lat: 44.2127,
    lng: -114.9378,
    dogFriendlinessScore: 9,
    description:
      "Stanley is a tiny mountain town in central Idaho surrounded by some of the most spectacular and wild scenery in the lower 48. With the Sawtooth Range towering overhead, the Salmon River flowing through, and the largest wilderness area in the contiguous US nearby, dogs enjoy an unmatched backcountry paradise with virtually no restrictions.",
    heroImage: "https://images.unsplash.com/photo-1439853949127-fa647821eba0?w=1200&fit=crop",
    climate: "Subarctic continental",
    population: 63,
  },

  hotels: [
    {
      name: "Redfish Lake Lodge",
      address: "Redfish Lake Rd, Stanley, ID 83278",
      lat: 43.9500,
      lng: -114.9200,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in the motel rooms and select cabins. Iconic lodge on the shores of Redfish Lake.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Lake access", "Beach", "Hiking trails", "Dog bed", "Mountain views"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.redfishlake.com",
      phone: "(208) 774-3536",
    },
    {
      name: "Stanley High Country Inn",
      address: "21 Ace of Diamonds St, Stanley, ID 83278",
      lat: 44.2130,
      lng: -114.9380,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a per-night fee. Comfortable rooms in the heart of Stanley.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Mountain views", "River nearby", "Walking distance to trails", "Water bowls"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.stanleyhighcountryinn.com",
      phone: "(208) 774-2290",
    },
    {
      name: "Mountain Village Lodge",
      address: "100 Niece Ave, Stanley, ID 83278",
      lat: 44.2125,
      lng: -114.9370,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome with a small pet fee. Basic mountain lodging with big views.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Mountain views", "River access nearby", "Grassy areas", "Pet waste stations"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.mountainvillagelodge.com",
      phone: "(208) 774-3661",
    },
    {
      name: "Idaho Rocky Mountain Ranch",
      address: "HC 64 Box 9934, Stanley, ID 83278",
      lat: 44.1200,
      lng: -114.9100,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in select lodge rooms and cabins. Historic dude ranch with hot springs pool.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Hot springs", "Salmon River access", "Hiking trails", "Dog bed", "Ranch grounds"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.idahorocky.com",
      phone: "(208) 774-3544",
    },
  ],

  nationalParks: [
    {
      name: "Sawtooth National Recreation Area",
      state: "Idaho",
      lat: 44.0000,
      lng: -114.9000,
      dogPolicy: "Dogs welcome on all trails. Voice control throughout; leash in developed campgrounds only.",
      dogTrails: ["Redfish Lake Creek Trail", "Iron Creek to Sawtooth Lake", "Alpine Way Trail", "Bench Lakes Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control on trails",
        "Not allowed in designated swim areas at developed beaches",
      ],
      description:
        "The Sawtooth NRA encompasses over 756,000 acres of spectacular mountain scenery with alpine lakes, jagged granite peaks, and pristine rivers. The trail system is extensive and incredibly dog-friendly, with off-leash hiking under voice control on virtually every trail.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/sawtooth",
    },
    {
      name: "Frank Church-River of No Return Wilderness",
      state: "Idaho",
      lat: 44.5000,
      lng: -114.5000,
      dogPolicy: "Dogs welcome off-leash under voice control. The largest wilderness in the contiguous US at 2.4 million acres.",
      dogTrails: ["Middle Fork Salmon River Trail", "Loon Creek Trail", "Rapid River Trail"],
      restrictions: [
        "Must be under voice control",
        "Pack out all waste",
        "Be prepared for extreme remoteness",
        "Bear awareness required",
      ],
      description:
        "Accessible from Stanley, this 2.4-million-acre wilderness is the largest in the lower 48. Dogs can explore truly wild country with their humans on trails through deep canyons, past hot springs, and along wild rivers.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/sawtooth",
    },
    {
      name: "White Cloud Mountains",
      state: "Idaho",
      lat: 43.9000,
      lng: -114.7000,
      dogPolicy: "Dogs welcome on all trails under voice control. Spectacular alpine scenery with fewer crowds than the Sawtooths.",
      dogTrails: ["Fourth of July Creek Trail", "Born Lakes Trail", "Casino Lakes Trail"],
      restrictions: [
        "Must be under voice control",
        "Pack out waste in popular areas",
        "High altitude - acclimate dogs",
      ],
      description:
        "The White Cloud Mountains east of Stanley offer alpine lakes, 11,000-foot peaks, and some of the most beautiful backcountry in Idaho. Fewer visitors than the Sawtooths mean more solitude for dogs and their adventurous owners.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/sawtooth",
    },
  ],

  restaurants: [
    {
      name: "Stanley Baking Company & Cafe",
      address: "250 Wall St, Stanley, ID 83278",
      lat: 44.2128,
      lng: -114.9375,
      cuisine: "Bakery & Cafe",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the outdoor deck with Sawtooth views. Famous for pies and fresh-baked bread.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.stanleybakingco.com",
    },
    {
      name: "Bridge Street Grill",
      address: "21 Ace of Diamonds St, Stanley, ID 83278",
      lat: 44.2132,
      lng: -114.9382,
      cuisine: "American Grill",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio overlooking the Salmon River. Hearty mountain fare.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bridgestreetgrill.com",
    },
    {
      name: "Sawtooth Luce's",
      address: "52 Niece Ave, Stanley, ID 83278",
      lat: 44.2126,
      lng: -114.9372,
      cuisine: "Wood-Fired Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the large outdoor deck. Wood-fired pizza with mountain views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sawtoothluce.com",
    },
    {
      name: "The Kasino Club",
      address: "672 Niece Ave, Stanley, ID 83278",
      lat: 44.2124,
      lng: -114.9368,
      cuisine: "Western Bar & Grill",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome on the patio. Classic mountain saloon with burgers and cold beer.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.thekasino.com",
    },
    {
      name: "Redfish Lake Lodge Dining",
      address: "Redfish Lake Rd, Stanley, ID 83278",
      lat: 43.9502,
      lng: -114.9205,
      cuisine: "Northwest Lodge Cuisine",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the lakeside deck. Dining with Sawtooth Mountain and Redfish Lake views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.redfishlake.com",
    },
  ],

  cafes: [
    {
      name: "Stanley Baking Company",
      address: "250 Wall St, Stanley, ID 83278",
      lat: 44.2128,
      lng: -114.9375,
      dogPolicy: "Dogs welcome on the deck. Famous pies, fresh pastries, and strong coffee.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.stanleybakingco.com",
    },
    {
      name: "Papa Brunee's",
      address: "21 Ace of Diamonds St, Stanley, ID 83278",
      lat: 44.2130,
      lng: -114.9380,
      dogPolicy: "Outdoor seating welcomes dogs. Quick coffee and breakfast wraps for early morning trail starts.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.papabrunees.com",
    },
    {
      name: "Mountain View Coffee",
      address: "Ace of Diamonds St, Stanley, ID 83278",
      lat: 44.2129,
      lng: -114.9378,
      dogPolicy: "Dog-friendly patio. Espresso and light fare with Sawtooth Mountain views.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.mountainviewcoffee.com",
    },
    {
      name: "Redfish Lake General Store Coffee Bar",
      address: "Redfish Lake Rd, Stanley, ID 83278",
      lat: 43.9510,
      lng: -114.9210,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Coffee and snacks at the lake.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.redfishlake.com",
    },
  ],

  dogParks: [
    {
      name: "Salmon River Corridor",
      address: "Hwy 75, Stanley, ID 83278",
      lat: 44.2100,
      lng: -114.9400,
      offLeash: true,
      fenced: false,
      acres: 100.0,
      amenities: ["River access", "Swimming", "Fishing", "Scenic pullouts", "Waste stations"],
      rating: 4.8,
      imageUrl: "",
      description:
        "The Salmon River runs through Stanley with numerous access points where dogs can swim, fetch sticks, and explore the riverbanks. The cold, clear water and mountain scenery make this a dog's dream swimming hole.",
    },
    {
      name: "Redfish Lake Beach & Trails",
      address: "Redfish Lake Rd, Stanley, ID 83278",
      lat: 43.9520,
      lng: -114.9220,
      offLeash: false,
      fenced: false,
      acres: 50.0,
      amenities: ["Lake beach", "Mountain trails", "Boat launch", "Campground", "Restrooms"],
      rating: 4.7,
      imageUrl: "",
      description:
        "One of Idaho's most stunning alpine lakes with a sandy beach and trails along the shore with the Sawtooth Mountains rising behind. Leashed dogs can wade in the crystal-clear lake and hike the surrounding trails.",
    },
    {
      name: "Iron Creek to Sawtooth Lake Trailhead",
      address: "Iron Creek Rd, Stanley, ID 83278",
      lat: 44.1500,
      lng: -114.9700,
      offLeash: true,
      fenced: false,
      acres: 200.0,
      amenities: ["Alpine trail", "Lake access", "Spectacular scenery", "Parking", "Campground"],
      rating: 4.9,
      imageUrl: "",
      description:
        "The trail to Sawtooth Lake is one of Idaho's most spectacular hikes, climbing to a pristine alpine lake beneath jagged Sawtooth peaks. Dogs can hike off-leash under voice control on this iconic trail through some of the most beautiful scenery in the American West.",
    },
    {
      name: "Stanley Lake Creek Trail",
      address: "Stanley Lake Rd, Stanley, ID 83278",
      lat: 44.2300,
      lng: -115.0500,
      offLeash: true,
      fenced: false,
      acres: 80.0,
      amenities: ["Lake access", "Creek trails", "Mountain views", "Campground", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Trails around Stanley Lake and along the creek offer easy to moderate hiking with stunning Sawtooth views. Dogs can be off-leash under voice control and enjoy the lake swimming and creek access.",
    },
  ],
};
