export const steamboatSpringsData = {
  city: {
    name: "Steamboat Springs",
    state: "Colorado",
    region: "Mountain West",
    lat: 40.4850,
    lng: -106.8317,
    dogFriendlinessScore: 8,
    description:
      "Steamboat Springs is a genuine Colorado ranch town turned ski resort where dogs are a way of life. The Yampa River runs through town offering swimming and trails, while the surrounding Routt National Forest provides endless backcountry adventures. Hot springs, ranches, and a laid-back western vibe make this a paw-fect mountain escape.",
    heroImage: "https://images.unsplash.com/photo-1551524559-8af4e6624178?w=1200&fit=crop",
    climate: "Subarctic continental",
    population: 13430,
  },

  hotels: [
    {
      name: "The Steamboat Grand",
      address: "2300 Mt Werner Cir, Steamboat Springs, CO 80487",
      lat: 40.4570,
      lng: -106.8040,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a per-stay pet fee. Full-service ski resort hotel.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Near gondola", "Trail access", "Concierge services"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.steamboatgrand.com",
      phone: "(970) 871-5500",
    },
    {
      name: "Rabbit Ears Motel",
      address: "201 Lincoln Ave, Steamboat Springs, CO 80487",
      lat: 40.4845,
      lng: -106.8310,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome with a modest pet fee. Classic mountain motel on Main Street.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Pet waste stations", "Walking distance to trails", "Yampa River access", "Water bowls"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.rabbitearsmotel.com",
      phone: "(970) 879-1150",
    },
    {
      name: "Holiday Inn Steamboat Springs",
      address: "3190 S Lincoln Ave, Steamboat Springs, CO 80487",
      lat: 40.4720,
      lng: -106.8200,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a per-night fee. Comfortable hotel with indoor pool and hot tub.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Grassy areas", "Pet waste stations", "Near Yampa River Trail", "Water bowls"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(970) 879-2250",
    },
    {
      name: "Hotel Bristol",
      address: "917 Lincoln Ave, Steamboat Springs, CO 80487",
      lat: 40.4848,
      lng: -106.8280,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with advance notice. Historic boutique hotel in downtown Steamboat.",
      maxDogWeight: 40,
      petFee: 50,
      amenities: ["Dog bed", "Treats", "Downtown location", "Near Yampa River Core Trail", "Walking map"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.steamboathotelbristol.com",
      phone: "(970) 879-3083",
    },
  ],

  nationalParks: [
    {
      name: "Routt National Forest",
      state: "Colorado",
      lat: 40.5500,
      lng: -106.9000,
      dogPolicy: "Dogs welcome on all trails. Leash required in developed areas; voice control in backcountry.",
      dogTrails: ["Fish Creek Falls Trail", "Steamboat Lake Trail", "Mad Creek Trail", "Spring Creek Trail"],
      restrictions: [
        "Leash required in campgrounds and trailheads",
        "Voice control in backcountry",
        "Not allowed in developed swim areas",
      ],
      description:
        "The national forest surrounding Steamboat offers diverse hiking from waterfall hikes to alpine ridge walks. Fish Creek Falls is the most popular trail, and the extensive backcountry provides solitude for adventurous dogs and their humans.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/mbr",
    },
    {
      name: "Steamboat Lake State Park",
      state: "Colorado",
      lat: 40.7880,
      lng: -106.9780,
      dogPolicy: "Leashed dogs welcome on trails and in the campground. No dogs on swim beaches.",
      dogTrails: ["Tombstone Trail", "Lakeside Trail", "Sunrise Vista Trail"],
      restrictions: [
        "Must be on leash at all times",
        "No dogs on swim beaches",
        "Clean up after your pet",
      ],
      description:
        "A beautiful mountain reservoir about 30 minutes north of Steamboat with camping, hiking, and stunning Hahn's Peak views. Leashed dogs enjoy the lakeside trails and forested paths.",
      imageUrl: "",
      website: "https://cpw.state.co.us/placestogo/parks/steamboatlake",
    },
    {
      name: "Sarvis Creek Wilderness",
      state: "Colorado",
      lat: 40.3500,
      lng: -106.8500,
      dogPolicy: "Dogs welcome off-leash under voice control in the wilderness. Remote and uncrowded.",
      dogTrails: ["Sarvis Creek Trail", "Silver Creek Trail"],
      restrictions: [
        "Must be under voice control",
        "Pack out all waste",
        "Be aware of wildlife",
      ],
      description:
        "A small, quiet wilderness area south of Steamboat offering secluded forest trails and meadows. Few visitors mean dogs can enjoy a peaceful backcountry experience with abundant wildlife and wildflowers.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/mbr",
    },
  ],

  restaurants: [
    {
      name: "Mountain Tap Brewery",
      address: "910 Yampa St, Steamboat Springs, CO 80487",
      lat: 40.4840,
      lng: -106.8290,
      cuisine: "Brewery & American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the large outdoor patio. Local craft brewery with mountain town vibes.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.mountaintapbrewery.com",
    },
    {
      name: "Aurum Food & Wine",
      address: "811 Yampa St, Steamboat Springs, CO 80487",
      lat: 40.4842,
      lng: -106.8295,
      cuisine: "New American Fine Dining",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio overlooking the Yampa River. Seasonal tasting menus.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.aurumsteamboat.com",
    },
    {
      name: "Back Door Grill",
      address: "811 Yampa St, Steamboat Springs, CO 80487",
      lat: 40.4843,
      lng: -106.8296,
      cuisine: "Burgers & Comfort Food",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Famous burgers in a casual Steamboat setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.backdoorgrill.com",
    },
    {
      name: "Salt & Lime",
      address: "35 5th St, Steamboat Springs, CO 80477",
      lat: 40.4855,
      lng: -106.8325,
      cuisine: "Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly patio area. Modern Mexican cuisine with craft margaritas.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.saltandlimesteamboat.com",
    },
    {
      name: "Low Country Kitchen",
      address: "435 Lincoln Ave, Steamboat Springs, CO 80487",
      lat: 40.4850,
      lng: -106.8330,
      cuisine: "Southern & Cajun",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio. Southern comfort food in the mountains.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.lowcountrykitchensteamboat.com",
    },
  ],

  cafes: [
    {
      name: "Mountain Brew",
      address: "811 Yampa St, Steamboat Springs, CO 80487",
      lat: 40.4841,
      lng: -106.8293,
      dogPolicy: "Dogs welcome on the patio. Coffee, espresso, and fresh pastries in the heart of town.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.mountainbrewsteamboat.com",
    },
    {
      name: "Off the Beaten Path Bookstore & Coffee",
      address: "68 9th St, Steamboat Springs, CO 80487",
      lat: 40.4858,
      lng: -106.8340,
      dogPolicy: "Outdoor seating welcomes dogs. Independent bookstore with a cozy coffee bar.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.steamboatbooks.com",
    },
    {
      name: "Yampa Valley Coffee",
      address: "720 Lincoln Ave, Steamboat Springs, CO 80487",
      lat: 40.4848,
      lng: -106.8300,
      dogPolicy: "Dog-friendly patio seating. Locally roasted coffee with mountain views.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.yampavalleycoffee.com",
    },
    {
      name: "Freshies",
      address: "105 11th St, Steamboat Springs, CO 80487",
      lat: 40.4860,
      lng: -106.8350,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Health-focused cafe with smoothies and acai bowls.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.freshiessteamboat.com",
    },
  ],

  dogParks: [
    {
      name: "Rita Valentine Dog Park",
      address: "W of Pamela Ln, Steamboat Springs, CO 80487",
      lat: 40.4750,
      lng: -106.8450,
      offLeash: true,
      fenced: true,
      acres: 5.0,
      amenities: ["Separate small dog area", "Water stations", "Waste bags", "Benches", "Shade structures"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Steamboat's primary off-leash dog park with beautiful mountain views, separate areas for large and small dogs, and a welcoming community. One of the best dog parks in any mountain town.",
    },
    {
      name: "Yampa River Core Trail",
      address: "Yampa River Core Trail, Steamboat Springs, CO 80487",
      lat: 40.4850,
      lng: -106.8310,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Paved trail", "River access", "Swimming holes", "Benches", "Waste stations"],
      rating: 4.7,
      imageUrl: "",
      description:
        "A paved trail running along the Yampa River through town. Dogs must be leashed but love the river access, swimming holes, and the lively atmosphere as the trail passes breweries and parks.",
    },
    {
      name: "Spring Creek Trail",
      address: "Spring Creek Trailhead, Steamboat Springs, CO 80487",
      lat: 40.4780,
      lng: -106.8150,
      offLeash: true,
      fenced: false,
      acres: 50.0,
      amenities: ["Forest trails", "Creek access", "Mountain views", "Parking", "Waste stations"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A popular trail system east of town where dogs can run off-leash under voice control. The trails wind through aspen groves and along Spring Creek with views of the ski mountain.",
    },
    {
      name: "Emerald Mountain Trails",
      address: "Howelsen Hill, Steamboat Springs, CO 80487",
      lat: 40.4900,
      lng: -106.8400,
      offLeash: true,
      fenced: false,
      acres: 100.0,
      amenities: ["Mountain trails", "Forest loops", "Scenic overlooks", "Parking", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "The trail network on Emerald Mountain above Howelsen Hill offers forested loops with valley views. Dogs can be off-leash under voice control on these well-maintained trails popular with hikers and mountain bikers.",
    },
  ],
};
