export const stillwaterData = {
  city: {
    name: "Stillwater",
    state: "Minnesota",
    region: "Midwest",
    lat: 45.0564,
    lng: -92.8063,
    dogFriendlinessScore: 7,
    description:
      "Stillwater is a picturesque St. Croix River town with Victorian charm and a welcoming attitude toward dogs. The historic Main Street is lined with dog-friendly shops and restaurants, and the surrounding river bluffs offer beautiful hiking trails perfect for exploring with your pup.",
    heroImage: "https://images.unsplash.com/photo-1518991669955-9c7e78ec80ca?w=1200&fit=crop",
    climate: "Humid continental",
    population: 19715,
  },

  hotels: [
    {
      name: "Lora Hotel",
      address: "402 S Main St, Stillwater, MN 55082",
      lat: 45.0540,
      lng: -92.8057,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a one-time pet fee. Boutique riverfront luxury.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats", "River views", "Walking access to downtown"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.lorahotel.com",
      phone: "(651) 571-5672",
    },
    {
      name: "Water Street Inn",
      address: "101 Water St S, Stillwater, MN 55082",
      lat: 45.0555,
      lng: -92.8045,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in select rooms with advance notice. Historic inn on the St. Croix riverfront.",
      maxDogWeight: 50,
      petFee: 40,
      amenities: ["Dog bed", "River access", "Walking paths", "Historic charm"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.waterstreetinn.us",
      phone: "(651) 439-6000",
    },
    {
      name: "AmericInn by Wyndham Stillwater",
      address: "2200 W Frontage Rd, Stillwater, MN 55082",
      lat: 45.0530,
      lng: -92.8380,
      priceRange: "$" as const,
      dogPolicy: "Pets welcome with a nightly fee. Comfortable rooms with easy access to downtown.",
      maxDogWeight: 60,
      petFee: 25,
      amenities: ["Grassy walking area", "Near bike trail", "Waste stations", "Indoor pool"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(651) 430-1300",
    },
    {
      name: "Cover Park Manor",
      address: "15330 58th St N, Stillwater, MN 55082",
      lat: 45.0780,
      lng: -92.8210,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in the cottage suite with advance notice. A country estate retreat.",
      maxDogWeight: 40,
      petFee: 50,
      amenities: ["Cottage suite", "Sprawling grounds", "Garden walks", "Quiet setting"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.coverparkmanor.com",
      phone: "(651) 430-9292",
    },
  ],

  nationalParks: [
    {
      name: "St. Croix National Scenic Riverway",
      state: "Minnesota",
      lat: 45.0600,
      lng: -92.7900,
      dogPolicy: "Leashed dogs welcome along the riverway trails and in many access points. One of the original Wild and Scenic Rivers.",
      dogTrails: ["River Trail", "Boom Site Trail", "Arcola Bluffs Trail"],
      restrictions: [
        "Must be on a 6-foot leash at all times",
        "Not allowed in swimming beaches during peak season",
        "Clean up after your pet",
      ],
      description:
        "The St. Croix River, a National Wild and Scenic Riverway, flows past Stillwater's doorstep. The protected corridor offers trails, bluffs, and riverfront access that dogs adore, especially the cooling river wading spots in summer.",
      imageUrl: "",
      website: "https://www.nps.gov/sacn",
    },
    {
      name: "William O'Brien State Park",
      state: "Minnesota",
      lat: 45.2210,
      lng: -92.7650,
      dogPolicy: "Leashed dogs welcome on all hiking trails and in campgrounds. Scenic St. Croix River frontage.",
      dogTrails: ["Riverside Trail", "Savanna Trail", "Hardwood Hills Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on swimming beach",
        "Not permitted in park buildings",
      ],
      description:
        "Just north of Stillwater, this state park offers rolling terrain along the St. Croix River. The mix of prairies, hardwood forests, and river shoreline provides diverse sniffing adventures for dogs.",
      imageUrl: "",
      website: "https://www.dnr.state.mn.us/state_parks/william_obrien",
    },
    {
      name: "Afton State Park",
      state: "Minnesota",
      lat: 44.8550,
      lng: -92.7850,
      dogPolicy: "Leashed dogs allowed on all trails. Rugged bluff trails with stunning river valley views.",
      dogTrails: ["River Bluff Trail", "Prairie Loop", "Ravine Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed on the swimming beach",
        "Trails can be steep and rugged",
      ],
      description:
        "South of Stillwater, Afton State Park features challenging bluff trails overlooking the St. Croix River valley. The varied terrain of prairies, ravines, and forests gives athletic dogs a satisfying workout.",
      imageUrl: "",
      website: "https://www.dnr.state.mn.us/state_parks/afton",
    },
  ],

  restaurants: [
    {
      name: "LoLo American Kitchen",
      address: "233 S Main St, Stillwater, MN 55082",
      lat: 45.0545,
      lng: -92.8055,
      cuisine: "New American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the riverfront patio. Creative American cuisine with St. Croix views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.loloamericankitchen.com",
    },
    {
      name: "The Freight House",
      address: "305 Water St S, Stillwater, MN 55082",
      lat: 45.0535,
      lng: -92.8040,
      cuisine: "Steakhouse & Seafood",
      priceRange: "$$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the outdoor deck overlooking the St. Croix River.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thefreighthouse.com",
    },
    {
      name: "Lift Bridge Brewing Company",
      address: "1900 Tower Dr W, Stillwater, MN 55082",
      lat: 45.0510,
      lng: -92.8250,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Very dog-friendly taproom with outdoor patio. Named after Stillwater's iconic lift bridge.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.liftbridgebrewery.com",
    },
    {
      name: "Marx Wine Bar & Grill",
      address: "221 S Main St, Stillwater, MN 55082",
      lat: 45.0547,
      lng: -92.8056,
      cuisine: "Italian-American",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the sidewalk patio along Main Street.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marxstillwater.com",
    },
    {
      name: "Nacho Mama's",
      address: "325 S Main St, Stillwater, MN 55082",
      lat: 45.0538,
      lng: -92.8058,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Colorful, fun spot for tacos and margaritas.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.nachomamas.com",
    },
  ],

  cafes: [
    {
      name: "The Velveteen Speakeasy",
      address: "102 S Main St, Stillwater, MN 55082",
      lat: 45.0560,
      lng: -92.8054,
      dogPolicy: "Dogs welcome at the outdoor sidewalk tables. Craft coffee and cocktails in a unique atmosphere.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.velveteenstillwater.com",
    },
    {
      name: "Rivertown Coffee",
      address: "119 S Main St, Stillwater, MN 55082",
      lat: 45.0555,
      lng: -92.8053,
      dogPolicy: "Outdoor patio welcomes leashed dogs. Freshly roasted coffee on Main Street.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.rivertowncoffee.com",
    },
    {
      name: "Teddy Bear Park Coffee",
      address: "230 E Chestnut St, Stillwater, MN 55082",
      lat: 45.0565,
      lng: -92.8020,
      dogPolicy: "Dog-friendly patio near the park. Coffee and pastries in a family-friendly setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.teddybearcoffee.com",
    },
    {
      name: "Cream & Amber",
      address: "423 S Main St, Stillwater, MN 55082",
      lat: 45.0532,
      lng: -92.8060,
      dogPolicy: "Leashed dogs welcome outside. Coffee, craft cocktails, and a curated goods shop.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.creamandamber.com",
    },
  ],

  dogParks: [
    {
      name: "Lowell Park",
      address: "201 N Water St, Stillwater, MN 55082",
      lat: 45.0575,
      lng: -92.8040,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["St. Croix River access", "Walking paths", "Benches", "Picnic areas", "Historic lift bridge views"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Stillwater's signature riverside park offers scenic on-leash walks along the St. Croix with views of the iconic lift bridge. Dogs love the riverbank and the activity of the bustling waterfront.",
    },
    {
      name: "Brown's Creek State Trail",
      address: "Manning Ave, Stillwater, MN 55082",
      lat: 45.0520,
      lng: -92.8400,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Paved trail", "Creek views", "Bridges", "Benches", "Nature viewing"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A beautiful paved trail following Brown's Creek from the western outskirts into downtown Stillwater. The gentle grade and creek-side scenery make it a perfect on-leash walking route.",
    },
    {
      name: "Pioneer Park Dog Area",
      address: "600 Owens St N, Stillwater, MN 55082",
      lat: 45.0610,
      lng: -92.8100,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced area", "Water fountain", "Waste stations", "Benches", "Shade trees"],
      rating: 4.2,
      imageUrl: "",
      description:
        "Stillwater's designated off-leash area offers a fenced space for dogs to run and socialize. The hilltop location provides nice views of the surrounding neighborhood.",
    },
    {
      name: "Teddy Bear Park",
      address: "200 E Chestnut St, Stillwater, MN 55082",
      lat: 45.0565,
      lng: -92.8025,
      offLeash: false,
      fenced: false,
      acres: 3.0,
      amenities: ["Playground", "Walking paths", "River views", "Benches", "Picnic area"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A charming community park near the river with walking paths and lovely views. While on-leash, dogs enjoy the gentle paths and the proximity to downtown treats and shops.",
    },
  ],
};
