export const tacomaData = {
  city: {
    name: "Tacoma",
    state: "Washington",
    region: "Pacific Northwest",
    lat: 47.2529,
    lng: -122.4443,
    dogFriendlinessScore: 8,
    description:
      "Tacoma has transformed into a vibrant, dog-loving city with stunning Puget Sound views, world-class parks, and a thriving arts district. With Point Defiance Park, multiple off-leash areas, and a growing brewery scene with dog-friendly taprooms, Tacoma is an affordable and welcoming alternative to Seattle.",
    heroImage: "https://images.unsplash.com/photo-1561134643-668b26a3fe48?w=1200&fit=crop",
    climate: "Oceanic",
    population: 219346,
  },
  hotels: [
    {
      name: "Hotel Murano",
      address: "1320 Broadway, Tacoma, WA 98402",
      lat: 47.2530,
      lng: -122.4390,
      priceRange: "$$$" as const,
      dogPolicy: "Art-filled downtown hotel welcoming dogs under 80 lbs. Walking distance to the Museum District and waterfront.",
      maxDogWeight: 80,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Art collection", "Downtown location", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelmurano.com",
      phone: "(253) 238-8000",
    },
    {
      name: "McMenamins Elks Temple",
      address: "565 Broadway, Tacoma, WA 98402",
      lat: 47.2510,
      lng: -122.4380,
      priceRange: "$$" as const,
      dogPolicy: "Quirky McMenamins hotel in a historic lodge with pet-friendly rooms. Dogs welcome in this uniquely Pacific Northwest experience.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Historic building", "Pet-friendly rooms", "Multiple bars", "Water bowls", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.mcmenamins.com",
      phone: "(253) 300-8500",
    },
    {
      name: "Silver Cloud Inn Tacoma Waterfront",
      address: "2317 N Ruston Way, Tacoma, WA 98402",
      lat: 47.2770,
      lng: -122.4800,
      priceRange: "$$$" as const,
      dogPolicy: "Waterfront hotel on Ruston Way with pet-friendly rooms and bay views. Dogs welcome with walking trail access along the water.",
      maxDogWeight: 50,
      petFee: 35,
      amenities: ["Waterfront location", "Dog bed", "Bay views", "Walking trail", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.silvercloud.com",
      phone: "(253) 272-1300",
    },
    {
      name: "La Quinta Inn Tacoma",
      address: "1425 E 27th St, Tacoma, WA 98421",
      lat: 47.2420,
      lng: -122.4300,
      priceRange: "$" as const,
      dogPolicy: "Budget-friendly hotel welcoming dogs of all sizes with no pet fee. Easy access to I-5 and Tacoma attractions.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pet-friendly rooms", "Parking", "Breakfast", "Waste bags"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(253) 383-0146",
    },
  ],
  nationalParks: [
    {
      name: "Mount Rainier National Park",
      state: "Washington",
      lat: 46.8523,
      lng: -121.7603,
      dogPolicy: "Dogs allowed in campgrounds, parking areas, and along paved roads only. Not permitted on trails, in meadows, or in the backcountry.",
      dogTrails: ["Campground roads", "Paved viewpoint areas"],
      restrictions: ["Not allowed on any trails", "Not allowed in meadows or backcountry", "Must be on leash at all times", "Not allowed in buildings"],
      description: "While trail access is very limited for dogs, Mount Rainier's campgrounds and scenic viewpoints still offer incredible views of the iconic volcano. The scenic drives through the park are worthwhile even with restrictions.",
      imageUrl: "",
      website: "https://www.nps.gov/mora",
    },
    {
      name: "Point Defiance Park",
      state: "Washington",
      lat: 47.3050,
      lng: -122.5130,
      dogPolicy: "Dogs welcome on most trails on leash with a designated off-leash area. One of the largest urban parks in the US with old-growth forest.",
      dogTrails: ["Five Mile Drive", "Inside Loop Trail", "Spine Trail", "Owen Beach Trail"],
      restrictions: ["Leash required on most trails", "Off-leash only in designated area", "Not allowed in zoo or gardens", "Clean up after pet"],
      description: "At 760 acres, Point Defiance is one of the largest urban parks in the country. Dogs can explore miles of trails through old-growth forest, walk along Puget Sound beaches, and enjoy sweeping views of Mount Rainier and the Narrows Bridge.",
      imageUrl: "",
      website: "https://www.metroparkstacoma.org/point-defiance-park",
    },
    {
      name: "Gifford Pinchot National Forest",
      state: "Washington",
      lat: 46.3300,
      lng: -121.7700,
      dogPolicy: "Dogs welcome on most national forest trails on leash or under voice control. Volcanic landscapes and old-growth forests south of Tacoma.",
      dogTrails: ["Trail of Two Forests", "Ape Cave Trail", "Falls Creek Falls Trail", "Lewis River Trail"],
      restrictions: ["Leash or voice control required", "Not allowed in Mount St. Helens blast zone trails", "Northwest Forest Pass required", "Volcanic terrain can be rough on paws"],
      description: "South of Tacoma, the Gifford Pinchot National Forest offers dog-friendly trails through volcanic landscapes, old-growth forest, and along wild rivers. The Lewis River trails and waterfalls are especially scenic.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/giffordpinchot",
    },
  ],
  restaurants: [
    {
      name: "The Table",
      address: "716 Pacific Ave, Tacoma, WA 98402",
      lat: 47.2530,
      lng: -122.4370,
      cuisine: "Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Farm-to-table restaurant with a dog-friendly patio in the revitalized Pacific Avenue district. Seasonal menus with local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.thetabletacoma.com",
    },
    {
      name: "Odd Otter Brewing Company",
      address: "945 Broadway, Tacoma, WA 98402",
      lat: 47.2520,
      lng: -122.4380,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Downtown brewery with a dog-friendly patio. Craft beers and pub fare in a fun, community-oriented atmosphere.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.oddotterbrewing.com",
    },
    {
      name: "Shake Shake Shake",
      address: "5508 S Puget Sound Ave, Tacoma, WA 98409",
      lat: 47.2250,
      lng: -122.4700,
      cuisine: "Burgers & Shakes",
      priceRange: "$" as const,
      dogPolicy: "Retro burger joint with outdoor seating and a pup cup on the menu. Dogs welcome at outdoor tables.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.shakeshakeshake.com",
    },
    {
      name: "Marzano",
      address: "516 Garfield St S, Tacoma, WA 98444",
      lat: 47.2140,
      lng: -122.4530,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Italian restaurant with a garden patio welcoming dogs. Handmade pasta and Italian wines in a charming neighborhood setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.marzanorestaurant.com",
    },
    {
      name: "En Rama",
      address: "2811 6th Ave, Tacoma, WA 98406",
      lat: 47.2570,
      lng: -122.4600,
      cuisine: "Spanish Tapas",
      priceRange: "$$" as const,
      dogPolicy: "Spanish tapas bar with a small patio in the 6th Ave district. Dogs welcome with pintxos and craft cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.enramatacoma.com",
    },
  ],
  cafes: [
    {
      name: "Bluebeard Coffee Roasters",
      address: "2201 6th Ave, Tacoma, WA 98403",
      lat: 47.2560,
      lng: -122.4580,
      dogPolicy: "Specialty roaster in the 6th Ave district with a patio where dogs are welcome. Direct-trade coffees and house pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bluebeardcoffee.com",
    },
    {
      name: "Valhalla Coffee Co.",
      address: "741 Pacific Ave, Tacoma, WA 98402",
      lat: 47.2535,
      lng: -122.4375,
      dogPolicy: "Downtown coffee shop with outdoor seating and a Viking-themed atmosphere. Dogs welcome on the patio.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.valhallacoffee.com",
    },
    {
      name: "Manifesto Coffee",
      address: "602 Fawcett Ave, Tacoma, WA 98402",
      lat: 47.2490,
      lng: -122.4360,
      dogPolicy: "Cozy neighborhood roaster with a small patio. Dogs welcome outside while you enjoy carefully crafted espresso drinks.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.manifestocoffee.com",
    },
    {
      name: "Olympia Coffee Roasting Co. Tacoma",
      address: "2824 6th Ave, Tacoma, WA 98406",
      lat: 47.2575,
      lng: -122.4605,
      dogPolicy: "Award-winning Olympia roaster with a Tacoma outpost. Spacious patio where dogs are always welcome.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.olympiacoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Point Defiance Off-Leash Dog Park",
      address: "5400 N Pearl St, Tacoma, WA 98407",
      lat: 47.3000,
      lng: -122.5050,
      offLeash: true,
      fenced: true,
      acres: 5,
      amenities: ["Separate small dog area", "Water stations", "Forest setting", "Benches", "Waste bag stations"],
      rating: 4.6,
      imageUrl: "",
      description: "A forested off-leash park within Point Defiance Park, one of the largest urban parks in the US. Dogs play among towering Douglas firs with nearby trails and beach access.",
    },
    {
      name: "Rogers Off-Leash Dog Park",
      address: "4502 S 66th St, Tacoma, WA 98409",
      lat: 47.2200,
      lng: -122.4680,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Shade trees", "Benches", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "A well-maintained fenced dog park in south Tacoma with separate areas for large and small dogs. Mature trees provide shade and the community of regular visitors creates a friendly atmosphere.",
    },
    {
      name: "Ruston Way Waterfront",
      address: "Ruston Way, Tacoma, WA 98402",
      lat: 47.2800,
      lng: -122.4850,
      offLeash: false,
      fenced: false,
      acres: 20,
      amenities: ["Paved waterfront trail", "Bay views", "Mt. Rainier views", "Benches", "Restaurants"],
      rating: 4.7,
      imageUrl: "",
      description: "A scenic two-mile waterfront trail along Commencement Bay with sweeping views of Mount Rainier and the Olympic Mountains. Leashed dogs enjoy the paved path, beach access points, and the vibrant restaurant row.",
    },
    {
      name: "Wright Park",
      address: "501 S I St, Tacoma, WA 98405",
      lat: 47.2480,
      lng: -122.4450,
      offLeash: false,
      fenced: false,
      acres: 27,
      amenities: ["Walking paths", "Arboretum", "Pond", "Historic conservatory", "Benches"],
      rating: 4.4,
      imageUrl: "",
      description: "A beautiful urban park with an arboretum featuring over 600 trees from around the world. Leashed dogs enjoy the winding paths through this 130-year-old park in the heart of Tacoma's Stadium District.",
    },
  ],
};
