export const tampaData = {
  city: {
    name: "Tampa",
    state: "Florida",
    region: "Southeast",
    lat: 27.9506,
    lng: -82.4572,
    dogFriendlinessScore: 7,
    description:
      "Tampa's waterfront Riverwalk, dog-friendly breweries, and year-round sunshine make it an excellent destination for traveling with your pup. The city's casual outdoor lifestyle means dogs are welcome at more venues than you'd expect, and the nearby beaches offer off-leash fun.",
    heroImage: "https://images.unsplash.com/photo-1589083130544-0d6a2926e519?w=1200&fit=crop",
    climate: "Tropical Savanna",
    population: 384959,
  },
  hotels: [
    {
      name: "The Epicurean Hotel",
      address: "1207 S Howard Ave, Tampa, FL 33606",
      lat: 27.9382,
      lng: -82.4822,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 40 lbs welcome with a $75 per stay fee. South Tampa food-focused hotel near Bayshore Blvd.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Rooftop bar", "Near Bayshore Blvd", "Restaurant", "Food-focused", "Pool"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.epicureanhotel.com",
      phone: "(813) 999-8700",
    },
    {
      name: "Aloft Tampa Downtown",
      address: "100 W Kennedy Blvd, Tampa, FL 33602",
      lat: 27.9477,
      lng: -82.4593,
      priceRange: "$$" as const,
      dogPolicy: "Arf program welcomes dogs of all sizes at no extra charge. Walking distance to the Riverwalk.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Riverwalk access", "Pool", "Downtown location", "Pet treats"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(813) 680-2000",
    },
    {
      name: "The Westin Tampa Waterside",
      address: "725 S Harbour Island Blvd, Tampa, FL 33602",
      lat: 27.9412,
      lng: -82.4505,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs under 40 lbs welcome with a $50 per stay fee. Harbour Island location with waterfront views.",
      maxDogWeight: 40,
      petFee: 50,
      amenities: ["Waterfront", "Pool", "Riverwalk access", "Pet bed", "Near convention center"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(813) 229-5000",
    },
    {
      name: "Hotel Haya",
      address: "1412 E 7th Ave, Tampa, FL 33605",
      lat: 27.9596,
      lng: -82.4389,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique hotel in Ybor City welcoming dogs with a $50 per stay fee. Historic district with walkable nightlife.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Ybor City location", "Restaurant", "Garden courtyard", "Historic district"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hotelhaya.com",
      phone: "(813) 426-7000",
    },
  ],
  nationalParks: [
    {
      name: "Hillsborough River State Park",
      state: "Florida",
      lat: 28.1469,
      lng: -82.2324,
      dogPolicy: "Leashed dogs welcome on all trails and in campground. One of Florida's oldest state parks with beautiful river rapids.",
      dogTrails: ["Rapids Trail", "Wetlands Restoration Trail", "Nature Trail", "River Trail"],
      restrictions: ["Leash required at all times", "No dogs in swimming area", "Clean up required"],
      description:
        "One of Florida's most beautiful state parks features rare Class II rapids on the Hillsborough River — unusual for flat Florida. Trails wind through hardwood hammocks and along the riverbank where your dog can cool their paws. The rapids provide a surprisingly dramatic Florida landscape.",
      imageUrl: "",
      website: "https://www.floridastateparks.org/parks-and-trails/hillsborough-river-state-park",
    },
    {
      name: "Upper Tampa Bay Trail",
      state: "Florida",
      lat: 28.0129,
      lng: -82.5768,
      dogPolicy: "Leashed dogs welcome on the entire 7-mile paved trail through wetlands and along Tampa Bay.",
      dogTrails: ["Upper Tampa Bay Trail (7 miles)", "Nature Loop Trail", "Mangrove Boardwalk"],
      restrictions: ["Leash required", "Yield to cyclists", "Clean up required"],
      description:
        "A 7-mile paved trail through wetlands, mangrove forests, and along the shores of Tampa Bay. The flat terrain is perfect for dogs of all fitness levels, and the coastal habitats provide interesting wildlife viewing. Interpretive signs explain the ecology of this productive estuary.",
      imageUrl: "",
      website: "https://www.hillsboroughcounty.org",
    },
    {
      name: "Lettuce Lake Conservation Park",
      state: "Florida",
      lat: 28.0803,
      lng: -82.3787,
      dogPolicy: "Leashed dogs welcome on the main trail and boardwalk. A pristine cypress swamp within the city.",
      dogTrails: ["Boardwalk Trail", "Nature Trail Loop", "Fitness Trail"],
      restrictions: ["Leash required", "Stay on boardwalk over swamp", "Be alert for wildlife"],
      description:
        "A 240-acre park protecting a gorgeous cypress swamp along the Hillsborough River. The elevated boardwalk winds through towering cypress trees draped in Spanish moss, and alligators, turtles, and river otters are commonly spotted. Your leashed dog will be fascinated by the swamp sounds and smells.",
      imageUrl: "",
      website: "https://www.hillsboroughcounty.org",
    },
  ],
  restaurants: [
    {
      name: "Coppertail Brewing Co.",
      address: "2601 E 2nd Ave, Tampa, FL 33605",
      lat: 27.9558,
      lng: -82.4312,
      cuisine: "Brewpub",
      priceRange: "$$" as const,
      dogPolicy: "Massive dog-friendly brewery in Ybor City with a huge outdoor area. Dogs are welcome and celebrated here.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.coppertailbrewing.com",
    },
    {
      name: "Ulele",
      address: "1810 N Highland Ave, Tampa, FL 33602",
      lat: 27.9568,
      lng: -82.4648,
      cuisine: "Southern-Native",
      priceRange: "$$$" as const,
      dogPolicy: "Waterfront restaurant on the Riverwalk with a dog-friendly patio. Florida-Native inspired cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ulele.com",
    },
    {
      name: "Cigar City Brewing",
      address: "3924 W Spruce St, Tampa, FL 33607",
      lat: 27.9525,
      lng: -82.509,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Tampa's famous craft brewery with a dog-friendly taproom and outdoor area. Home of Jai Alai IPA.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.cigarcitybrewing.com",
    },
    {
      name: "The Columbia Restaurant",
      address: "2117 E 7th Ave, Tampa, FL 33605",
      lat: 27.96,
      lng: -82.4345,
      cuisine: "Spanish-Cuban",
      priceRange: "$$$" as const,
      dogPolicy: "Florida's oldest restaurant with a dog-friendly sidewalk patio in Ybor City. Spanish-Cuban classics since 1905.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.columbiarestaurant.com",
    },
    {
      name: "Armature Works",
      address: "1910 N Ola Ave, Tampa, FL 33602",
      lat: 27.9584,
      lng: -82.465,
      cuisine: "Food Hall",
      priceRange: "$$" as const,
      dogPolicy: "Waterfront food hall on the Riverwalk with dog-friendly outdoor areas. Multiple food vendors and bay views.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.armaborworks.com",
    },
  ],
  cafes: [
    {
      name: "Buddy Brew Coffee",
      address: "2020 W Kennedy Blvd, Tampa, FL 33606",
      lat: 27.9466,
      lng: -82.4738,
      dogPolicy: "Tampa's beloved local roaster with outdoor seating. Dogs welcome on the shaded patio. Excellent cold brew.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.buddybrew.com",
    },
    {
      name: "Foundation Coffee Co.",
      address: "1819 N 13th St, Tampa, FL 33605",
      lat: 27.9605,
      lng: -82.4433,
      dogPolicy: "Ybor City coffee shop in a converted cigar factory. Dog-friendly patio with industrial-chic vibes.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.foundationcoffeeco.com",
    },
    {
      name: "Blind Tiger Cafe",
      address: "1901 E 7th Ave, Tampa, FL 33605",
      lat: 27.9597,
      lng: -82.437,
      dogPolicy: "Speakeasy-themed cafe in Ybor City with outdoor seating. Dogs welcome on the patio. Creative coffee drinks.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.blindtigercafe.com",
    },
    {
      name: "Oceana Coffee",
      address: "1521 Gunn Hwy, Tampa, FL 33618",
      lat: 28.0465,
      lng: -82.5107,
      dogPolicy: "Neighborhood roaster with a garden patio. Dogs welcome outside. Direct-trade beans and thoughtful preparation.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.oceanacoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Davis Islands Dog Park",
      address: "1002 Severn Ave, Tampa, FL 33606",
      lat: 27.9207,
      lng: -82.4538,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Bay views", "Dog beach", "Fenced area", "Water fountain", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Tampa's most popular dog park features both a fenced off-leash area and an unfenced dog beach on Tampa Bay. Dogs can swim in the bay's calm waters with downtown Tampa as a backdrop. The park has separate areas for large and small dogs and the beach is a huge draw.",
    },
    {
      name: "Tampa Riverwalk",
      address: "Tampa Riverwalk, Tampa, FL 33602",
      lat: 27.9488,
      lng: -82.4572,
      offLeash: false,
      fenced: false,
      acres: 12.0,
      amenities: ["2.6-mile paved path", "Waterfront dining", "Public art", "Parks", "Downtown access"],
      rating: 4.6,
      imageUrl: "",
      description:
        "Tampa's award-winning 2.6-mile waterfront Riverwalk connects downtown parks, museums, restaurants, and the Convention Center along the Hillsborough River. Leashed dogs are welcome throughout, and the path passes numerous dog-friendly restaurant patios. It's the best urban dog walk in Tampa.",
    },
    {
      name: "Bayshore Boulevard",
      address: "Bayshore Blvd, Tampa, FL 33606",
      lat: 27.9185,
      lng: -82.4773,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["4.5-mile sidewalk", "Bay views", "Balustrade", "Benches", "South Tampa access"],
      rating: 4.7,
      imageUrl: "",
      description:
        "The longest continuous sidewalk in the world stretches 4.5 miles along Tampa Bay with gorgeous water views. Leashed dogs join joggers, walkers, and cyclists on this iconic Tampa path. The palm-lined boulevard with its balustraded seawall is beautiful at any time of day, but sunset is magical.",
    },
    {
      name: "Al Lopez Park Dog Park",
      address: "4810 N Himes Ave, Tampa, FL 33614",
      lat: 27.9758,
      lng: -82.4949,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced", "Separate small dog area", "Water fountains", "Shade trees", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A large fenced dog park within the 132-acre Al Lopez Park, with separate areas for large and small dogs. The surrounding park adds walking paths around a lake, making it easy to extend your outing. The mature oak trees provide welcome shade from Tampa's sunshine.",
    },
  ],
};
