export const traverseCityData = {
  city: {
    name: "Traverse City",
    state: "Michigan",
    region: "Midwest",
    lat: 44.7631,
    lng: -85.6206,
    dogFriendlinessScore: 7,
    description:
      "The Cherry Capital of the world is also a hidden gem for dogs who love freshwater beaches, vineyard hopping, and forest trails. Nestled on the shores of Grand Traverse Bay with crystal-clear turquoise water that rivals the Caribbean, Traverse City offers a laid-back Up North vibe where dogs are welcome at wineries, breweries, and along miles of stunning lakeshore. Your pup will fall nose-first in love.",
    heroImage: "https://images.unsplash.com/photo-1517483000871-1dbf64a6e1c6?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 15678,
  },

  hotels: [
    {
      name: "Hotel Indigo Traverse City",
      address: "263 Grandview Pkwy, Traverse City, MI 49684",
      lat: 44.7640,
      lng: -85.6220,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with no pet fee. Boutique waterfront hotel right on Grand Traverse Bay.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Dog bed", "Water bowls", "Bay views", "Near TART Trail", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(231) 929-8900",
    },
    {
      name: "Cambria Hotel Traverse City",
      address: "420 Munson Ave, Traverse City, MI 49686",
      lat: 44.7695,
      lng: -85.6135,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a nightly fee. Modern hotel with spacious rooms near West Bay.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Pet relief area", "Waste stations", "Modern rooms", "Near waterfront", "Free parking"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.choicehotels.com",
      phone: "(231) 421-5500",
    },
    {
      name: "Great Wolf Lodge Traverse City",
      address: "3575 N US-31 S, Traverse City, MI 49684",
      lat: 44.7275,
      lng: -85.6310,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 40 lbs welcome in select rooms. Family-friendly resort with indoor waterpark for the kids while pup relaxes.",
      maxDogWeight: 40,
      petFee: 75,
      amenities: ["Dog bed", "Treats", "Grassy pet area", "Waste stations", "Near state parks"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.greatwolf.com",
      phone: "(866) 478-9653",
    },
    {
      name: "Bayshore Resort",
      address: "833 E Front St, Traverse City, MI 49686",
      lat: 44.7660,
      lng: -85.6085,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a flat pet fee. Lakefront resort with private beach and stunning bay views.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Private beach", "Lakefront views", "Pet relief area", "Near downtown", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bayshore-resort.com",
      phone: "(231) 935-4400",
    },
    {
      name: "Cherry Tree Inn & Suites",
      address: "2345 US-31 N, Traverse City, MI 49686",
      lat: 44.7845,
      lng: -85.5920,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a per-night fee. Cherry-themed charmer near the East Bay shoreline.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Pet-friendly grounds", "Near beach", "Waste bags", "Kitchenette options", "Cherry welcome treats"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.cherrytreeinn.com",
      phone: "(231) 938-8888",
    },
  ],

  nationalParks: [
    {
      name: "Sleeping Bear Dunes National Lakeshore",
      state: "Michigan",
      lat: 44.8700,
      lng: -86.0550,
      dogPolicy: "Leashed dogs welcome on most mainland trails and beaches. Not permitted on the Dune Climb or Manitou Islands. Some beach restrictions in summer.",
      dogTrails: ["Empire Bluff Trail", "Platte Plains Trail", "Old Indian Trail", "Bay View Trail", "Peterson Beach"],
      restrictions: [
        "NOT allowed on Dune Climb",
        "NOT allowed on North or South Manitou Islands",
        "Must be on a 6-foot leash",
        "Some beaches restrict dogs June-August",
        "Not allowed in visitor center",
      ],
      description:
        "One of Michigan's most spectacular landscapes, just 30 minutes west of Traverse City. Towering sand dunes, turquoise waters, and forest trails await leashed dogs. Empire Bluff Trail rewards with panoramic views of the Sleeping Bear Dunes and South Manitou Island.",
      imageUrl: "",
      website: "https://www.nps.gov/slbe",
    },
    {
      name: "Pictured Rocks National Lakeshore",
      state: "Michigan",
      lat: 46.5600,
      lng: -86.3400,
      dogPolicy: "Leashed dogs welcome on some trails and beaches. Not permitted on certain cliff trails or at Miners Castle overlook.",
      dogTrails: ["Chapel Basin area trails", "Twelvemile Beach", "Sable Falls Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed at Miners Castle",
        "Check individual trail restrictions",
        "Not allowed in visitor center",
      ],
      description:
        "About 4 hours northeast, this stunning lakeshore features multicolored sandstone cliffs, waterfalls, and pristine beaches on Lake Superior. Select trails welcome leashed dogs through some of Michigan's most dramatic scenery.",
      imageUrl: "",
      website: "https://www.nps.gov/piro",
    },
    {
      name: "North Manitou Island (Sleeping Bear Dunes NL)",
      state: "Michigan",
      lat: 45.1100,
      lng: -86.0000,
      dogPolicy: "Dogs are NOT permitted on North or South Manitou Islands. This listing is informational for trip planning purposes.",
      dogTrails: [],
      restrictions: [
        "NO dogs allowed on either island",
        "No dogs on the ferry",
        "Plan alternative activities for your pet",
      ],
      description:
        "While the remote Manitou Islands are off-limits to dogs, they are worth knowing about for trip planning. Consider the dog-friendly mainland trails at Sleeping Bear Dunes instead, which offer equally stunning views without the ferry ride.",
      imageUrl: "",
      website: "https://www.nps.gov/slbe",
    },
  ],

  restaurants: [
    {
      name: "The Cook's House",
      address: "115 Wellington St, Traverse City, MI 49686",
      lat: 44.7630,
      lng: -85.6195,
      cuisine: "Farm-to-Table",
      priceRange: "$$$$" as const,
      dogPolicy: "Well-behaved dogs welcome at the outdoor courtyard tables. Seasonal tasting menus featuring local farms.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.8,
      imageUrl: "",
      website: "https://www.thecookshouse.net",
    },
    {
      name: "Jolly Pumpkin Brewery",
      address: "13512 Peninsula Dr, Traverse City, MI 49686",
      lat: 44.8265,
      lng: -85.5340,
      cuisine: "Brewery & American",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly outdoor patio on Old Mission Peninsula. Sour ales and wood-fired pizza with vineyard views.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.jollypumpkin.com",
    },
    {
      name: "Red Ginger",
      address: "237 E Front St, Traverse City, MI 49684",
      lat: 44.7638,
      lng: -85.6162,
      cuisine: "Pan-Asian",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the sidewalk patio downtown. Creative Asian fusion with fresh local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.redgingertc.com",
    },
    {
      name: "The Little Fleet",
      address: "448 E Front St, Traverse City, MI 49686",
      lat: 44.7642,
      lng: -85.6128,
      cuisine: "Food Trucks & Beer Garden",
      priceRange: "$" as const,
      dogPolicy: "Extremely dog-friendly outdoor beer garden with rotating food trucks. Dogs are basically the main attraction here.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.thelittlefleet.com",
    },
    {
      name: "Boathouse Restaurant on West Bay",
      address: "14039 Peninsula Dr, Traverse City, MI 49686",
      lat: 44.8310,
      lng: -85.5295,
      cuisine: "Seafood & American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the waterfront deck overlooking West Grand Traverse Bay. Sunset dining at its finest.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.boathouserestauranttc.com",
    },
    {
      name: "Brady's Bar",
      address: "401 S Union St, Traverse City, MI 49684",
      lat: 44.7600,
      lng: -85.6252,
      cuisine: "American Bar & Grill",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly outdoor area. Beloved local dive with burgers, wings, and a welcoming atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.bradysbar.com",
    },
    {
      name: "Warehouse MRKT",
      address: "422 W 14th St, Traverse City, MI 49684",
      lat: 44.7560,
      lng: -85.6295,
      cuisine: "Modern American",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome at outdoor tables in the warehouse district. Industrial-chic vibe with creative seasonal menus.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.warehousemrkt.com",
    },
    {
      name: "Bluebird Tavern & Restaurant",
      address: "625 W Front St, Traverse City, MI 49684",
      lat: 44.7632,
      lng: -85.6282,
      cuisine: "American Comfort",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio. Comforting American food with a focus on local Michigan ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.bluebirdtc.com",
    },
  ],

  cafes: [
    {
      name: "Higher Grounds Trading Company",
      address: "306 E Front St, Traverse City, MI 49684",
      lat: 44.7640,
      lng: -85.6148,
      dogPolicy: "Leashed dogs welcome at the outdoor sidewalk tables. Fair-trade coffee roasted locally since 1997.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.highergroundstrading.com",
    },
    {
      name: "Mundos Roasting & Co.",
      address: "422 Howard St, Traverse City, MI 49684",
      lat: 44.7625,
      lng: -85.6230,
      dogPolicy: "Dog-friendly outdoor seating in the Warehouse District. Single-origin micro-lot coffees and fresh pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.mundoscoffee.com",
    },
    {
      name: "Cuppa Joe",
      address: "252 E Front St, Traverse City, MI 49684",
      lat: 44.7638,
      lng: -85.6168,
      dogPolicy: "Leashed dogs welcome at outdoor tables on Front Street. A friendly neighborhood coffee spot.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.cuppajoetc.com",
    },
    {
      name: "Cherry Republic Cafe",
      address: "154 E Front St, Traverse City, MI 49684",
      lat: 44.7635,
      lng: -85.6185,
      dogPolicy: "Dogs welcome on the patio. Cherry-everything: cherry coffee, cherry scones, cherry soda. Welcome to cherry paradise.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.cherryrepublic.com",
    },
    {
      name: "Brewing Good Coffee Co.",
      address: "109 S Union St, Traverse City, MI 49684",
      lat: 44.7620,
      lng: -85.6252,
      dogPolicy: "Dog-friendly patio with treats available at the counter. Specialty espresso drinks and house-baked goods.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.brewinggoodcoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Grand Traverse Dog Park",
      address: "1995 N US-31 S, Traverse City, MI 49684",
      lat: 44.7345,
      lng: -85.6375,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Separate small and large dog areas", "Water stations", "Agility equipment", "Shade shelters", "Waste stations"],
      rating: 4.4,
      imageUrl: "",
      description:
        "The area's premier fenced dog park with separate zones for big and little dogs, agility equipment, and plenty of shade. A social hub where Traverse City's dogs gather for off-leash fun and new friendships.",
    },
    {
      name: "Clinch Park Beach",
      address: "111 E Grandview Pkwy, Traverse City, MI 49684",
      lat: 44.7655,
      lng: -85.6170,
      offLeash: false,
      fenced: false,
      acres: 4.0,
      amenities: ["Beach access", "Shallow bay swimming", "Walking path", "Restrooms", "Waste stations"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A downtown beach on Grand Traverse Bay where leashed dogs can walk the sandy shore and wade in the crystal-clear turquoise water. The gentle waves and shallow entry make it perfect for water-shy pups taking their first lake swim.",
    },
    {
      name: "TART Trail - Boardman Lake",
      address: "Boardman Lake Trail, Traverse City, MI 49684",
      lat: 44.7540,
      lng: -85.6210,
      offLeash: false,
      fenced: false,
      acres: 30.0,
      amenities: ["Paved trail", "Boardwalk sections", "Lake views", "Benches", "Waste stations", "Water fountains"],
      rating: 4.6,
      imageUrl: "",
      description:
        "A scenic paved trail circling Boardman Lake, part of the TART trail network. Leashed dogs love the waterside path with views of the lake, wetland boardwalks, and shaded stretches through woodlands. It connects to miles of additional trails.",
    },
    {
      name: "Hickory Meadows Natural Area",
      address: "5901 S Cedar Run Rd, Traverse City, MI 49684",
      lat: 44.7085,
      lng: -85.6435,
      offLeash: false,
      fenced: false,
      acres: 100.0,
      amenities: ["Nature trails", "Meadow walks", "Bird watching", "Parking", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A peaceful natural area with rolling meadows, forested trails, and abundant wildlife. Leashed dogs can explore the gentle terrain and take in the wildflower displays in summer. A quiet alternative to the busier in-town parks.",
    },
    {
      name: "Bryant Park",
      address: "270 Lake Ave, Traverse City, MI 49684",
      lat: 44.7628,
      lng: -85.6320,
      offLeash: false,
      fenced: false,
      acres: 8.0,
      amenities: ["Sandy beach", "Swimming", "Walking paths", "Picnic areas", "Restrooms", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A beautiful West Bay beach park where leashed dogs can enjoy the sand and water during off-peak hours. The wide beach and gentle bay waters make it a favorite for dogs who love to splash around.",
    },
  ],
};
