export const truthOrConsequencesData = {
  city: {
    name: "Truth or Consequences",
    state: "New Mexico",
    region: "Southwest",
    lat: 33.1284,
    lng: -107.2528,
    dogFriendlinessScore: 7,
    description:
      "This quirky hot springs town along the Rio Grande welcomes dogs with open arms and warm mineral waters. With natural hot springs, nearby Elephant Butte Lake, and a thriving arts community, T or C is a hidden gem for dog owners seeking relaxation and adventure in the desert.",
    heroImage: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&fit=crop",
    climate: "Desert",
    population: 5950,
  },
  hotels: [
    {
      name: "Sierra Grande Lodge & Spa",
      address: "501 McAdoo St, Truth or Consequences, NM 87901",
      lat: 33.1290,
      lng: -107.2530,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique hot springs lodge with pet-friendly rooms. Dogs welcome in designated rooms with private mineral soaking tubs.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Hot springs access", "Dog bed", "Water bowls", "Walking paths", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.sierragrandelodge.com",
      phone: "(575) 894-6976",
    },
    {
      name: "Pelican Spa & Motel",
      address: "306 S Pershing St, Truth or Consequences, NM 87901",
      lat: 33.1275,
      lng: -107.2525,
      priceRange: "$" as const,
      dogPolicy: "Budget-friendly motel with hot spring tubs and pet-friendly rooms. Dogs welcome with a small deposit.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Hot springs tubs", "Pet-friendly rooms", "Parking", "Water bowls", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.pelicanspa.com",
      phone: "(575) 894-0055",
    },
    {
      name: "Blackstone Hotsprings",
      address: "410 Austin Ave, Truth or Consequences, NM 87901",
      lat: 33.1282,
      lng: -107.2535,
      priceRange: "$$" as const,
      dogPolicy: "Artsy lodging with private hot spring tubs and select pet-friendly rooms. Small dogs welcome with advance notice.",
      maxDogWeight: 30,
      petFee: 25,
      amenities: ["Private hot springs", "Art-filled rooms", "Water bowls", "Garden courtyard", "Waste bags"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.blackstonehotsprings.com",
      phone: "(575) 894-0894",
    },
    {
      name: "Comfort Inn & Suites T or C",
      address: "2270 N Date St, Truth or Consequences, NM 87901",
      lat: 33.1400,
      lng: -107.2500,
      priceRange: "$$" as const,
      dogPolicy: "Chain hotel with reliable pet-friendly rooms. Close to Elephant Butte Lake for dog-friendly water activities.",
      maxDogWeight: 75,
      petFee: 30,
      amenities: ["Pet-friendly rooms", "Pool", "Breakfast included", "Parking", "Waste bags"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.choicehotels.com",
      phone: "(575) 894-9090",
    },
  ],
  nationalParks: [
    {
      name: "Elephant Butte Lake State Park",
      state: "New Mexico",
      lat: 33.1500,
      lng: -107.1900,
      dogPolicy: "Dogs welcome throughout the park on a leash. The lake beaches are popular spots for dogs to swim and play in the water.",
      dogTrails: ["Lakeshore Trail", "Dam Site Trail", "Desert Garden Trail"],
      restrictions: ["Leash required in developed areas", "Clean up after pet", "Watch for hot sand in summer", "Provide shade and water"],
      description: "New Mexico's largest state park surrounds the massive Elephant Butte Reservoir on the Rio Grande. Dogs love the lake beaches for swimming, and the desert trails offer scenic views of the dam and surrounding mountains.",
      imageUrl: "",
      website: "https://www.emnrd.nmsu.edu/spd/elephant-butte-lake",
    },
    {
      name: "Caballo Lake State Park",
      state: "New Mexico",
      lat: 32.9300,
      lng: -107.2900,
      dogPolicy: "Dogs welcome on leash throughout the park. A quieter alternative to Elephant Butte with desert trails and lake access.",
      dogTrails: ["Lakeshore Trail", "Cactus Trail", "Percha Creek Trail"],
      restrictions: ["Leash required", "Clean up after pet", "Carry extra water", "Watch for cacti on trails"],
      description: "Located south of T or C, Caballo Lake offers a more serene lake experience with fewer crowds than Elephant Butte. Dogs can explore desert trails with mountain views and cool off in the lake during warmer months.",
      imageUrl: "",
      website: "https://www.emnrd.nmsu.edu/spd/caballo-lake",
    },
    {
      name: "Bosque del Apache National Wildlife Refuge",
      state: "New Mexico",
      lat: 33.8000,
      lng: -106.8900,
      dogPolicy: "Dogs allowed on the auto tour loop road and in parking areas only. Not permitted on walking trails or in wildlife viewing areas.",
      dogTrails: ["Auto Tour Loop (from vehicle)"],
      restrictions: ["Dogs must remain in vehicle or in parking areas", "Not allowed on walking trails", "Leash required in parking areas", "Best visited during fall/winter crane migration"],
      description: "About an hour north of T or C, this refuge along the Rio Grande is famous for hosting thousands of sandhill cranes and snow geese in winter. While dogs are restricted to vehicles and parking areas, the scenic auto tour loop offers incredible wildlife viewing.",
      imageUrl: "",
      website: "https://www.fws.gov/refuge/bosque-del-apache",
    },
  ],
  restaurants: [
    {
      name: "Pacific Grill",
      address: "800 N Date St, Truth or Consequences, NM 87901",
      lat: 33.1320,
      lng: -107.2520,
      cuisine: "Pacific Rim-Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Creative fusion restaurant with a garden patio where dogs are welcome. Surprising culinary excellence in a small desert town.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.pacificgrilltoc.com",
    },
    {
      name: "Passion Pie Café",
      address: "406 Main St, Truth or Consequences, NM 87901",
      lat: 33.1285,
      lng: -107.2532,
      cuisine: "Café & Bakery",
      priceRange: "$" as const,
      dogPolicy: "Beloved local café with a shaded patio where dogs are always welcome. Famous for their pies and fresh-baked bread.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.passionpiecafe.com",
    },
    {
      name: "Los Arcos Steak & Lobster",
      address: "1400 N Date St, Truth or Consequences, NM 87901",
      lat: 33.1370,
      lng: -107.2510,
      cuisine: "Steak & Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Fine dining with a seasonal patio that welcomes well-behaved dogs. A T or C institution for steaks and New Mexican specialties.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.losarcosrestaurant.com",
    },
    {
      name: "Bella Luca Italian Ristorante",
      address: "303 Jones St, Truth or Consequences, NM 87901",
      lat: 33.1280,
      lng: -107.2540,
      cuisine: "Italian",
      priceRange: "$$" as const,
      dogPolicy: "Italian restaurant in a historic downtown building with a courtyard patio welcoming dogs. Handmade pasta and local wines.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.bellaluca.com",
    },
    {
      name: "Grapevine Bistro",
      address: "200 N Date St, Truth or Consequences, NM 87901",
      lat: 33.1295,
      lng: -107.2525,
      cuisine: "American Bistro",
      priceRange: "$$" as const,
      dogPolicy: "Casual downtown bistro with a dog-friendly patio. Salads, sandwiches, and local craft beer in a relaxed setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.grapevinebistro.com",
    },
  ],
  cafes: [
    {
      name: "Passion Pie Café",
      address: "406 Main St, Truth or Consequences, NM 87901",
      lat: 33.1285,
      lng: -107.2532,
      dogPolicy: "The heart of T or C's morning scene with excellent coffee, pastries, and a patio where dogs are part of the family.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.passionpiecafe.com",
    },
    {
      name: "Happy Belly Deli & Café",
      address: "313 Broadway St, Truth or Consequences, NM 87901",
      lat: 33.1288,
      lng: -107.2528,
      dogPolicy: "Quirky downtown café with outdoor seating where dogs are welcome. Fresh sandwiches, smoothies, and coffee.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.happybellydeli.com",
    },
    {
      name: "Desert Roasters Coffee",
      address: "500 N Date St, Truth or Consequences, NM 87901",
      lat: 33.1305,
      lng: -107.2518,
      dogPolicy: "Local coffee roaster with a small patio and desert views. Dogs welcome outside with complimentary water bowls.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.desertroasters.com",
    },
    {
      name: "Ingo's Art Café",
      address: "422 Main St, Truth or Consequences, NM 87901",
      lat: 33.1286,
      lng: -107.2533,
      dogPolicy: "Art gallery and café combination with a courtyard where dogs can relax while owners browse art and sip espresso.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.ingosartcafe.com",
    },
  ],
  dogParks: [
    {
      name: "Ralph Edwards Park",
      address: "Riverside Dr, Truth or Consequences, NM 87901",
      lat: 33.1270,
      lng: -107.2550,
      offLeash: false,
      fenced: false,
      acres: 5,
      amenities: ["Walking paths", "Picnic areas", "Shade trees", "Restrooms", "Parking"],
      rating: 4.1,
      imageUrl: "",
      description: "A pleasant park along the Rio Grande where leashed dogs can enjoy shaded walking paths and grassy areas. The river views and mature cottonwood trees make it a relaxing spot for dogs and their owners.",
    },
    {
      name: "Veterans Memorial Park",
      address: "300 S Foch St, Truth or Consequences, NM 87901",
      lat: 33.1260,
      lng: -107.2545,
      offLeash: false,
      fenced: false,
      acres: 3,
      amenities: ["Walking paths", "Benches", "Shade structures", "Waste bag stations", "Water fountain"],
      rating: 4.0,
      imageUrl: "",
      description: "A community park in the heart of T or C with shaded walking paths and benches. Leashed dogs enjoy the grassy areas and the chance to socialize with other local dog walkers.",
    },
    {
      name: "Elephant Butte Dog Beach",
      address: "Elephant Butte Lake State Park, NM 87935",
      lat: 33.1510,
      lng: -107.1880,
      offLeash: true,
      fenced: false,
      acres: 10,
      amenities: ["Lake swimming", "Sandy beach", "Open space", "Parking", "Restrooms"],
      rating: 4.6,
      imageUrl: "",
      description: "The sandy beaches at Elephant Butte Lake are a dog's paradise, offering swimming, splashing, and running along the shoreline. While technically leash-required, the expansive beach areas provide ample room for dogs to enjoy the water.",
    },
    {
      name: "T or C Dog Park",
      address: "500 S Pershing St, Truth or Consequences, NM 87901",
      lat: 33.1255,
      lng: -107.2520,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Separate small dog area", "Water stations", "Benches", "Shade", "Waste bag stations"],
      rating: 4.2,
      imageUrl: "",
      description: "The town's dedicated off-leash dog park with separate areas for large and small dogs. A fenced, safe space for dogs to play and socialize in the desert sun with shade structures for hot days.",
    },
  ],
};
