export const tucsonData = {
  city: {
    name: "Tucson",
    state: "Arizona",
    region: "Southwest",
    lat: 32.2226,
    lng: -110.9747,
    dogFriendlinessScore: 7,
    description:
      "Tucked in a desert valley ringed by five mountain ranges, Tucson is a sun-drenched haven where dogs can hike through saguaro forests, explore a vibrant food scene rooted in Mexican and Native American traditions, and enjoy over 350 days of sunshine a year. As a UNESCO City of Gastronomy with a fiercely independent spirit, Tucson welcomes pups to its patios, parks, and trails with open arms and full water bowls.",
    heroImage: "https://images.unsplash.com/photo-1578950435899-d1a3ffbe4dcf?w=1200&fit=crop",
    climate: "Semi-arid",
    population: 542629,
  },

  hotels: [
    {
      name: "Loews Ventana Canyon Resort",
      address: "7000 N Resort Dr, Tucson, AZ 85750",
      lat: 32.3310,
      lng: -110.8530,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a Loews Loves Pets program. Luxury desert resort with canyon trail access.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Food and water bowls", "Room service pet menu", "Walking trails", "Pet treats", "Waste bags"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.loewshotels.com/ventana-canyon",
      phone: "(520) 299-2020",
    },
    {
      name: "Hotel Congress",
      address: "311 E Congress St, Tucson, AZ 85701",
      lat: 32.2218,
      lng: -110.9680,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with no weight restrictions. Historic downtown hotel with live music and a legendary bar.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Downtown location", "Dog bed", "Water bowls", "Near El Presidio park", "Live music nightly"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.hotelcongress.com",
      phone: "(520) 622-8848",
    },
    {
      name: "La Quinta Inn by Wyndham Tucson East",
      address: "6404 E Broadway Blvd, Tucson, AZ 85710",
      lat: 32.2218,
      lng: -110.8855,
      priceRange: "$" as const,
      dogPolicy: "Dogs of all sizes welcome with no pet fee. Budget-friendly with easy access to Saguaro National Park East.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pet relief area", "Waste bags", "Pool", "Near Saguaro NP East"],
      rating: 3.9,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com",
      phone: "(520) 747-1414",
    },
    {
      name: "Arizona Inn",
      address: "2200 E Elm St, Tucson, AZ 85719",
      lat: 32.2405,
      lng: -110.9520,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 25 lbs welcome in select casita rooms with a one-time pet fee. A 1930s oasis with stunning gardens.",
      maxDogWeight: 25,
      petFee: 65,
      amenities: ["Garden grounds", "Dog bed", "Water bowls", "Walking paths", "Historic elegance"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.arizonainn.com",
      phone: "(520) 325-1541",
    },
    {
      name: "Drury Inn & Suites Tucson",
      address: "1199 N Oracle Rd, Tucson, AZ 85705",
      lat: 32.2385,
      lng: -110.9785,
      priceRange: "$$" as const,
      dogPolicy: "Up to two dogs welcome with no pet fee. Centrally located with free hot breakfast and evening kickback.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["No pet fee", "Pet relief area", "Free breakfast", "Waste bags", "Pool"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.druryhotels.com",
      phone: "(520) 292-3750",
    },
  ],

  nationalParks: [
    {
      name: "Saguaro National Park",
      state: "Arizona",
      lat: 32.2500,
      lng: -111.1660,
      dogPolicy: "Leashed dogs welcome on paved roads, in picnic areas, and on a few designated trails. Not permitted on most unpaved trails.",
      dogTrails: ["Cactus Garden Trail (paved)", "Desert Discovery Nature Trail", "Paved road shoulders"],
      restrictions: [
        "NOT allowed on most unpaved trails",
        "Must be on a 6-foot leash",
        "Not allowed in the backcountry",
        "Not allowed in visitor center",
        "Beware of extreme heat and cactus spines",
      ],
      description:
        "Split into two districts flanking Tucson, this park protects the iconic saguaro cactus forests. While trail access for dogs is limited, the paved paths and scenic drives through forests of towering saguaros are unforgettable. The East district's Cactus Forest Loop Drive is especially scenic.",
      imageUrl: "",
      website: "https://www.nps.gov/sagu",
    },
    {
      name: "Tumacacori National Historical Park",
      state: "Arizona",
      lat: 31.5675,
      lng: -111.0480,
      dogPolicy: "Leashed dogs welcome on the grounds and trails around the mission ruins. A peaceful Spanish colonial mission site.",
      dogTrails: ["Mission grounds trail", "Anza Trail segment", "Orchard walk"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed inside the church ruins",
        "Not allowed in visitor center/museum",
      ],
      description:
        "About an hour south of Tucson, this park preserves the ruins of three Spanish colonial missions along the Santa Cruz River. Leashed dogs can explore the scenic grounds, walk the Anza Trail, and soak in centuries of desert history.",
      imageUrl: "",
      website: "https://www.nps.gov/tuma",
    },
    {
      name: "Chiricahua National Monument",
      state: "Arizona",
      lat: 32.0130,
      lng: -109.3420,
      dogPolicy: "Leashed dogs welcome on paved roads and in the campground. Not permitted on hiking trails. The scenic drive is spectacular.",
      dogTrails: ["Bonita Canyon Drive (scenic road)", "Campground area"],
      restrictions: [
        "NOT allowed on hiking trails",
        "Must be on leash in campground",
        "Not allowed in visitor center",
        "Scenic drive only for pet access",
      ],
      description:
        "Known as the 'Wonderland of Rocks,' this remote monument about 2 hours southeast of Tucson features incredible volcanic rock spires. While dogs cannot hike the trails, the 8-mile Bonita Canyon Drive to Massai Point delivers breathtaking views of the rock formations.",
      imageUrl: "",
      website: "https://www.nps.gov/chir",
    },
  ],

  restaurants: [
    {
      name: "Prep & Pastry",
      address: "3073 N Campbell Ave, Tucson, AZ 85719",
      lat: 32.2580,
      lng: -110.9440,
      cuisine: "Brunch & Bakery",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the shaded patio. Instagram-worthy brunch dishes and house-made pastries.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.prepandpastry.com",
    },
    {
      name: "Barrio Brewing Co.",
      address: "800 E 16th St, Tucson, AZ 85719",
      lat: 32.2120,
      lng: -110.9630,
      cuisine: "Brewery & Pub",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly patio with water bowls. Tucson's first microbrewery with great pub food.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.barriobrewing.co",
    },
    {
      name: "El Charro Cafe",
      address: "311 N Court Ave, Tucson, AZ 85701",
      lat: 32.2248,
      lng: -110.9720,
      cuisine: "Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the courtyard patio. America's oldest Mexican restaurant, serving since 1922.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.elcharrocafe.com",
    },
    {
      name: "Cafe Poca Cosa",
      address: "110 E Pennington St, Tucson, AZ 85701",
      lat: 32.2230,
      lng: -110.9700,
      cuisine: "Contemporary Mexican",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome at limited outdoor seating. Elevated Mexican cuisine with a daily-changing menu.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.cafepocacosatucson.com",
    },
    {
      name: "Brushfire BBQ",
      address: "7080 E 22nd St, Tucson, AZ 85710",
      lat: 32.2145,
      lng: -110.8630,
      cuisine: "Southwest BBQ",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly outdoor seating with a large shaded patio. Mesquite-smoked BBQ with desert flair.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.brushfirebbq.com",
    },
    {
      name: "The Cup Cafe",
      address: "311 E Congress St, Tucson, AZ 85701",
      lat: 32.2218,
      lng: -110.9680,
      cuisine: "American Eclectic",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome at the outdoor sidewalk tables of this Hotel Congress favorite. Live music and late-night dining.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.hotelcongress.com/food-drink/cup-cafe",
    },
    {
      name: "Reforma Modern Mexican",
      address: "4574 N Oracle Rd, Tucson, AZ 85705",
      lat: 32.2720,
      lng: -110.9755,
      cuisine: "Modern Mexican",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the covered patio. Elevated Sonoran cuisine with mezcal cocktails.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.reformatucson.com",
    },
    {
      name: "Trident Pizza Pub",
      address: "689 E Speedway Blvd, Tucson, AZ 85719",
      lat: 32.2365,
      lng: -110.9595,
      cuisine: "Pizza & Pub",
      priceRange: "$" as const,
      dogPolicy: "Extremely dog-friendly with a large outdoor patio. Great pizza, cold beer, and happy dogs everywhere.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.tridentpizzapub.com",
    },
  ],

  cafes: [
    {
      name: "Exo Roast Co.",
      address: "403 N 6th Ave, Tucson, AZ 85705",
      lat: 32.2258,
      lng: -110.9735,
      dogPolicy: "Dog-friendly outdoor courtyard with shade and water bowls. Thoughtfully roasted specialty coffee in a hip setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.exocoffee.com",
    },
    {
      name: "Cartel Coffee Lab",
      address: "210 E Broadway Blvd, Tucson, AZ 85701",
      lat: 32.2210,
      lng: -110.9685,
      dogPolicy: "Leashed dogs welcome at the outdoor tables downtown. Precision coffee drinks and minimalist vibes.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cartelcoffeelab.com",
    },
    {
      name: "Savaya Coffee Market",
      address: "2803 E Speedway Blvd, Tucson, AZ 85716",
      lat: 32.2365,
      lng: -110.9310,
      dogPolicy: "Shaded patio perfect for pups. Tucson-born roaster with direct-trade beans from around the world.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.savayacoffee.com",
    },
    {
      name: "Presta Coffee Roasters",
      address: "2502 N 1st Ave, Tucson, AZ 85719",
      lat: 32.2490,
      lng: -110.9725,
      dogPolicy: "Dog-friendly courtyard seating. World-class espresso from a tiny Tucson roaster with a big reputation.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.prestacoffee.com",
    },
    {
      name: "Time Market",
      address: "444 E University Blvd, Tucson, AZ 85705",
      lat: 32.2320,
      lng: -110.9660,
      dogPolicy: "Leashed dogs welcome on the bustling patio. Gourmet market, coffee bar, and wood-fired pizza near the university.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.timemarket.xyz",
    },
  ],

  dogParks: [
    {
      name: "Jacobs Dog Park",
      address: "3300 N Fairview Ave, Tucson, AZ 85705",
      lat: 32.2620,
      lng: -110.9720,
      offLeash: true,
      fenced: true,
      acres: 4.0,
      amenities: ["Separate small and large dog areas", "Water stations", "Shade ramadas", "Agility equipment", "Waste stations", "Benches"],
      rating: 4.5,
      imageUrl: "",
      description:
        "Tucson's most popular fenced dog park with 4 acres of desert fun, separate areas for big and small pups, shade ramadas for escaping the Arizona sun, and agility equipment. The desert landscaping adds character you will not find at any other dog park.",
    },
    {
      name: "Palo Verde Dog Park",
      address: "300 S Mann Ave, Tucson, AZ 85710",
      lat: 32.2150,
      lng: -110.8720,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Separate areas", "Water fountains", "Shade structures", "Benches", "Waste stations", "Parking"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A well-designed fenced dog park on Tucson's east side near Saguaro National Park. The shade structures are essential for desert dogs, and the separate areas ensure safe play for pups of all sizes.",
    },
    {
      name: "Brandi Fenton Memorial Dog Park",
      address: "3482 E River Rd, Tucson, AZ 85718",
      lat: 32.2898,
      lng: -110.9340,
      offLeash: true,
      fenced: true,
      acres: 3.0,
      amenities: ["Large and small dog areas", "Water features", "Shade trees", "Benches", "Waste stations", "Splash pad"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A fantastic dog park with water features that help pups cool down in the desert heat. The splash pad is a huge hit during Tucson's long summers. Separate areas for large and small dogs with plenty of shade.",
    },
    {
      name: "Rillito Regional Park Trail",
      address: "4502 N 1st Ave, Tucson, AZ 85718",
      lat: 32.2790,
      lng: -110.9710,
      offLeash: false,
      fenced: false,
      acres: 50.0,
      amenities: ["Paved multi-use path", "River views", "Shade trees", "Water fountains", "Waste stations", "Benches"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A 12-mile paved river walk along the Rillito River running through central Tucson. Leashed dogs love this shaded urban trail with mountain views in every direction. Early morning and evening walks are magical when the desert sky puts on its color show.",
    },
    {
      name: "Christopher Columbus Park",
      address: "4600 N Silverbell Rd, Tucson, AZ 85745",
      lat: 32.2780,
      lng: -111.0285,
      offLeash: false,
      fenced: false,
      acres: 125.0,
      amenities: ["Lake", "Walking trails", "Fishing", "Picnic areas", "Shade ramadas", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "A sprawling park with a lake, grassy meadows, and walking trails on Tucson's northwest side. Leashed dogs enjoy the water's edge, the shaded trails, and watching the ducks. A great spot for a relaxed afternoon in the desert.",
    },
  ],
};
