export const venturaData = {
  city: {
    name: "Ventura",
    state: "California",
    region: "West Coast",
    lat: 34.2746,
    lng: -119.2290,
    dogFriendlinessScore: 8,
    description:
      "Ventura is a laid-back beach city with a thriving dog culture, featuring an off-leash dog beach, scenic coastal trails, and a walkable downtown packed with dog-friendly patios. With year-round mild weather and mountain-to-ocean recreation, it's one of Southern California's most underrated dog destinations.",
    heroImage: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=1200&fit=crop",
    climate: "Mediterranean",
    population: 109592,
  },
  hotels: [
    {
      name: "Crowne Plaza Ventura Beach",
      address: "450 E Harbor Blvd, Ventura, CA 93001",
      lat: 34.2690,
      lng: -119.2610,
      priceRange: "$$$" as const,
      dogPolicy: "Beachfront hotel welcoming dogs under 50 lbs. Steps from the beach and the Ventura Pier with ocean-view rooms.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Ocean views", "Dog bed", "Beach access", "Water bowls", "Waste bags"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(805) 648-2100",
    },
    {
      name: "Ashore Hotel",
      address: "1080 Schooner Dr, Ventura, CA 93001",
      lat: 34.2650,
      lng: -119.2700,
      priceRange: "$$$" as const,
      dogPolicy: "Boutique hotel near the harbor welcoming dogs of all sizes. Modern rooms with a courtyard and easy beach access.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Courtyard", "Beach proximity", "Fire pit", "Waste bags"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ashorehotel.com",
      phone: "(805) 654-1550",
    },
    {
      name: "Holiday Inn Express Ventura Harbor",
      address: "1080 Navigator Dr, Ventura, CA 93001",
      lat: 34.2640,
      lng: -119.2710,
      priceRange: "$$" as const,
      dogPolicy: "Comfortable hotel near the harbor with pet-friendly rooms. Dogs welcome with easy access to harbor walks and the beach.",
      maxDogWeight: 60,
      petFee: 35,
      amenities: ["Pet-friendly rooms", "Breakfast", "Pool", "Harbor proximity", "Waste bags"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.ihg.com",
      phone: "(805) 856-9533",
    },
    {
      name: "Vagabond Inn Ventura",
      address: "756 E Thompson Blvd, Ventura, CA 93001",
      lat: 34.2730,
      lng: -119.2580,
      priceRange: "$" as const,
      dogPolicy: "Budget-friendly motel welcoming dogs of all sizes. Central location with easy access to downtown and the beach.",
      maxDogWeight: 0,
      petFee: 15,
      amenities: ["Pet-friendly rooms", "Pool", "Parking", "Downtown access", "Waste bags"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.vagabondinn.com",
      phone: "(805) 648-5371",
    },
  ],
  nationalParks: [
    {
      name: "Channel Islands National Park (Visitor Center)",
      state: "California",
      lat: 34.2485,
      lng: -119.2630,
      dogPolicy: "Dogs are not allowed on the Channel Islands. The Ventura Harbor visitor center and surrounding harbor area welcome leashed dogs.",
      dogTrails: ["Ventura Harbor Promenade"],
      restrictions: ["No dogs on islands", "Leash required at harbor", "Clean up after pet"],
      description: "While the islands are off-limits to dogs, the Channel Islands National Park Visitor Center at Ventura Harbor offers exhibits and harbor walks. The surrounding marina and boardwalk provide pleasant waterfront strolling for dogs.",
      imageUrl: "",
      website: "https://www.nps.gov/chis",
    },
    {
      name: "Los Padres National Forest (Ventura District)",
      state: "California",
      lat: 34.4000,
      lng: -119.3000,
      dogPolicy: "Dogs welcome on most trails on leash. Mountain trails above Ventura offering ocean views and backcountry experiences.",
      dogTrails: ["Pratt Trail", "Gridley Trail", "Matilija Creek Trail", "Ojai Valley Trail"],
      restrictions: ["Leash required on most trails", "Adventure Pass required at some trailheads", "Fire closures possible", "Carry extra water"],
      description: "Rising above Ventura into the mountains, the Los Padres National Forest offers rugged trails through chaparral, oak woodlands, and riverside canyons. Dogs can hike from the coastal foothills to mountain peaks.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/lpnf",
    },
    {
      name: "Emma Wood State Beach",
      state: "California",
      lat: 34.2800,
      lng: -119.3300,
      dogPolicy: "Dogs allowed on the beach on leash. A quieter alternative to the main Ventura beaches with river mouth and cobblestone shore.",
      dogTrails: ["Beach Walk", "Ventura River Trail"],
      restrictions: ["6-foot leash required", "Day use fee required", "Rocky shore in some areas", "Strong currents near river mouth"],
      description: "Just north of Ventura where the Ventura River meets the ocean, Emma Wood offers a peaceful beach experience for leashed dogs. The cobblestone beach and river mouth create a unique coastal landscape.",
      imageUrl: "",
      website: "https://www.parks.ca.gov/emmawood",
    },
  ],
  restaurants: [
    {
      name: "Lure Fish House",
      address: "60 S California St, Ventura, CA 93001",
      lat: 34.2760,
      lng: -119.2930,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Award-winning seafood restaurant with a dog-friendly patio on Main Street. Fresh catches and raw bar in a vibrant downtown setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.lurefishhouse.com",
    },
    {
      name: "Rumfish y Vino",
      address: "249 E Main St, Ventura, CA 93001",
      lat: 34.2770,
      lng: -119.2900,
      cuisine: "Latin Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Lively Latin fusion restaurant with a large patio where dogs are welcome. Creative cocktails and ceviche in downtown Ventura.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.rumfishyvino.com",
    },
    {
      name: "Spencer Makenzie's Fish Company",
      address: "806 E Thompson Blvd, Ventura, CA 93001",
      lat: 34.2735,
      lng: -119.2570,
      cuisine: "Seafood",
      priceRange: "$" as const,
      dogPolicy: "Casual fish shack with outdoor seating and a famous dog-friendly attitude. Fish tacos and chowder in a surf-town vibe.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.spencermakenzies.com",
    },
    {
      name: "Social Tap",
      address: "1105 S Seaward Ave, Ventura, CA 93001",
      lat: 34.2660,
      lng: -119.2700,
      cuisine: "American",
      priceRange: "$$" as const,
      dogPolicy: "Neighborhood pub with a spacious dog-friendly patio near the beach. Craft beers and casual American fare.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.socialtapventura.com",
    },
    {
      name: "Café Fiore",
      address: "66 S California St, Ventura, CA 93001",
      lat: 34.2758,
      lng: -119.2928,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy: "Romantic Italian restaurant with a courtyard patio welcoming dogs. Handmade pasta and Italian wines in downtown Ventura.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cafefiore.com",
    },
  ],
  cafes: [
    {
      name: "Beacon Coffee",
      address: "515 Poli St, Ventura, CA 93001",
      lat: 34.2790,
      lng: -119.2920,
      dogPolicy: "Popular roaster with a dog-friendly patio overlooking downtown Ventura. Specialty coffee and pastries with ocean glimpses.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.beaconcoffee.com",
    },
    {
      name: "Simone's Coffee & Tea",
      address: "2550 E Main St, Ventura, CA 93003",
      lat: 34.2750,
      lng: -119.2600,
      dogPolicy: "Cozy neighborhood café with a garden patio where dogs are welcome. House-roasted coffee and homemade baked goods.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.simonescoffee.com",
    },
    {
      name: "Palm City Coffee",
      address: "397 E Main St, Ventura, CA 93001",
      lat: 34.2775,
      lng: -119.2885,
      dogPolicy: "Hip downtown café with outdoor seating and dog-friendly vibes. Craft coffee and avocado toast in the heart of Ventura.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.palmcitycoffee.com",
    },
    {
      name: "Prospect Coffee Roasters",
      address: "394 E Main St, Ventura, CA 93001",
      lat: 34.2773,
      lng: -119.2887,
      dogPolicy: "Specialty roaster on Main Street with outdoor seating where dogs are welcome. Single-origin coffees and house-made syrups.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.prospectcoffee.com",
    },
  ],
  dogParks: [
    {
      name: "Ventura Dog Beach",
      address: "Pierpont Blvd & Seaward Ave, Ventura, CA 93001",
      lat: 34.2630,
      lng: -119.2750,
      offLeash: true,
      fenced: false,
      acres: 6,
      amenities: ["Beach access", "Ocean swimming", "Open sand", "Waste bag stations", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description: "Ventura's popular off-leash dog beach where dogs run free on the sand and swim in the Pacific. The wide, sandy stretch and gentle waves make it ideal for dogs who love the water.",
    },
    {
      name: "Camino Real Park Dog Park",
      address: "400 S Dos Caminos Ave, Ventura, CA 93003",
      lat: 34.2550,
      lng: -119.2400,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: ["Separate small dog area", "Water stations", "Shade structures", "Agility equipment", "Waste bag stations"],
      rating: 4.4,
      imageUrl: "",
      description: "Ventura's largest fenced dog park with separate areas for large and small dogs plus agility equipment. Well-maintained grounds with shade structures and mountain views.",
    },
    {
      name: "Arroyo Verde Park",
      address: "300 Foothill Rd, Ventura, CA 93003",
      lat: 34.2900,
      lng: -119.2800,
      offLeash: false,
      fenced: false,
      acres: 132,
      amenities: ["Hiking trails", "Picnic areas", "Creek", "Shade trees", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description: "A beautiful foothill park with hiking trails through oak-shaded canyons and grassy meadows. Leashed dogs enjoy the varied terrain and seasonal creek while soaking in mountain and ocean views.",
    },
    {
      name: "Ventura River Trail",
      address: "Main St & Ventura Ave, Ventura, CA 93001",
      lat: 34.2850,
      lng: -119.3100,
      offLeash: false,
      fenced: false,
      acres: 20,
      amenities: ["Paved trail", "River views", "Shade", "Benches", "Waste bag stations"],
      rating: 4.3,
      imageUrl: "",
      description: "A scenic paved trail following the Ventura River from the foothills to the coast. Leashed dogs enjoy the riverside walk through riparian habitat with mountain views and bird watching opportunities.",
    },
  ],
};
