export const wallaWallaData = {
  city: {
    name: "Walla Walla",
    state: "Washington",
    region: "Pacific Northwest",
    lat: 46.0646,
    lng: -118.3430,
    dogFriendlinessScore: 7,
    description:
      "Walla Walla is a wine lover's paradise that also happens to adore dogs. With over 120 wineries offering dog-friendly tasting rooms and patios, plus scenic wheat fields and Blue Mountain foothills, your pup will enjoy every sip stop. The charming downtown and numerous parks make this a surprisingly great dog destination.",
    heroImage: "https://images.unsplash.com/photo-1504681869696-d977211a5f4c?w=1200&fit=crop",
    climate: "Semi-arid continental",
    population: 34060,
  },

  hotels: [
    {
      name: "Marcus Whitman Hotel & Conference Center",
      address: "6 W Rose St, Walla Walla, WA 99362",
      lat: 46.0648,
      lng: -118.3395,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in designated pet-friendly rooms. Historic boutique hotel in the heart of downtown wine country.",
      maxDogWeight: 50,
      petFee: 50,
      amenities: ["Dog bed", "Water bowls", "Walking route map", "Nearby parks", "Concierge pet recommendations"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.marcuswhitmanhotel.com",
      phone: "(509) 525-2200",
    },
    {
      name: "The Finch Hotel",
      address: "325 E Main St, Walla Walla, WA 99362",
      lat: 46.0650,
      lng: -118.3340,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs of all sizes welcome with advance notice. Upscale boutique hotel with wine country charm.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: ["Plush dog bed", "Gourmet treats", "Water bowls", "Dog walking service available", "Pet-sitting referrals"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.thefinchhotel.com",
      phone: "(509) 876-4540",
    },
    {
      name: "La Quinta Inn & Suites Walla Walla",
      address: "520 N 2nd Ave, Walla Walla, WA 99362",
      lat: 46.0700,
      lng: -118.3410,
      priceRange: "$" as const,
      dogPolicy: "Two dogs per room welcome at no extra charge. Budget-friendly option with easy highway access.",
      maxDogWeight: 0,
      petFee: 0,
      amenities: ["Pet waste stations", "Grassy walking areas", "Water bowls at front desk", "Continental breakfast"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.wyndhamhotels.com/laquinta",
      phone: "(509) 525-2522",
    },
    {
      name: "Inn at Abeja",
      address: "2014 Mill Creek Rd, Walla Walla, WA 99362",
      lat: 46.0420,
      lng: -118.2890,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in select cottage suites with a pet deposit. Set on a historic farmstead surrounded by vineyards.",
      maxDogWeight: 60,
      petFee: 100,
      amenities: ["Private cottage yards", "Dog bed", "Treats", "Vineyard walking paths", "Water bowls"],
      rating: 4.8,
      imageUrl: "",
      website: "https://www.abeja.net",
      phone: "(509) 522-1234",
    },
  ],

  nationalParks: [
    {
      name: "Whitman Mission National Historic Site",
      state: "Washington",
      lat: 46.0410,
      lng: -118.4580,
      dogPolicy: "Leashed dogs welcome on the grounds and paved paths. Dogs not allowed inside the visitor center.",
      dogTrails: ["Monument Hill Trail", "Oregon Trail segment", "Mission grounds walking path"],
      restrictions: [
        "Must be on leash (6 ft max) at all times",
        "No dogs in visitor center or buildings",
        "Clean up after your pet",
      ],
      description:
        "This historic site commemorates the Whitman Mission and is a peaceful place for a leashed walk. The gently rolling grounds with interpretive trails offer a nice outing for dogs who enjoy open fields and gentle terrain.",
      imageUrl: "",
      website: "https://www.nps.gov/whmi",
    },
    {
      name: "Umatilla National Forest",
      state: "Washington",
      lat: 46.1000,
      lng: -117.9500,
      dogPolicy: "Dogs welcome on all trails. Leash required in developed campgrounds and trailheads; voice control acceptable on backcountry trails.",
      dogTrails: ["South Fork Walla Walla Trail", "Bear Creek Trail", "Rough Fork Trail", "Mill Creek Trail"],
      restrictions: [
        "Leash required in campgrounds",
        "Voice control required on backcountry trails",
        "Not allowed in swimming areas at developed sites",
      ],
      description:
        "The Blue Mountains east of Walla Walla offer spectacular forested trails with creeks and mountain meadows. Dogs love the varied terrain, cool mountain streams, and abundant wildlife scents throughout this expansive national forest.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/umatilla",
    },
    {
      name: "Bennington Lake Recreation Area",
      state: "Washington",
      lat: 46.0220,
      lng: -118.3850,
      dogPolicy: "Leashed dogs welcome on trails around the lake. Dogs not permitted to swim in the reservoir.",
      dogTrails: ["Bennington Lake Loop Trail", "East Ridge Trail", "Wetland Boardwalk"],
      restrictions: [
        "Must be on leash at all times",
        "No dogs in the water",
        "Stay on designated trails",
      ],
      description:
        "A scenic reservoir just south of town with a popular loop trail offering views of the Blue Mountains. The flat, well-maintained paths are perfect for dogs of all fitness levels, and birdwatching opportunities abound.",
      imageUrl: "",
      website: "https://www.usace.army.mil",
    },
  ],

  restaurants: [
    {
      name: "Saffron Mediterranean Kitchen",
      address: "125 W Alder St, Walla Walla, WA 99362",
      lat: 46.0655,
      lng: -118.3405,
      cuisine: "Mediterranean",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the covered outdoor patio. Award-winning Mediterranean cuisine in a wine country setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.saffronmediterraneankitchen.com",
    },
    {
      name: "Brasserie Four",
      address: "4 E Main St, Walla Walla, WA 99362",
      lat: 46.0645,
      lng: -118.3390,
      cuisine: "French Bistro",
      priceRange: "$$$" as const,
      dogPolicy: "Leashed dogs welcome on the sidewalk patio. Classic French bistro fare with a Walla Walla twist.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.brasseriefour.com",
    },
    {
      name: "Grandma's Soda Fountain & Grill",
      address: "42 N Main St, Walla Walla, WA 99362",
      lat: 46.0660,
      lng: -118.3388,
      cuisine: "American Diner",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at the outdoor tables. Classic American diner with milkshakes and burgers.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.grandmassodafountain.com",
    },
    {
      name: "Public House 124",
      address: "124 E Main St, Walla Walla, WA 99362",
      lat: 46.0648,
      lng: -118.3370,
      cuisine: "American Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the patio. Craft cocktails and elevated pub fare in downtown Walla Walla.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.publichouse124.com",
    },
    {
      name: "Andrae's Kitchen",
      address: "1 S Palouse St, Walla Walla, WA 99362",
      lat: 46.0643,
      lng: -118.3395,
      cuisine: "German-Northwest Fusion",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the outdoor patio. Unique German-inspired dishes with local ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.andraeskitchen.com",
    },
  ],

  cafes: [
    {
      name: "Colville Street Patisserie",
      address: "40 S Colville St, Walla Walla, WA 99362",
      lat: 46.0640,
      lng: -118.3420,
      dogPolicy: "Dogs welcome on the sidewalk patio. French-inspired pastries and espresso in a charming setting.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.colvillestreetpatisserie.com",
    },
    {
      name: "Walla Walla Roastery",
      address: "15 S Colville St, Walla Walla, WA 99362",
      lat: 46.0645,
      lng: -118.3418,
      dogPolicy: "Dog-friendly patio with shade. Locally roasted specialty coffee beans and pour-overs.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.wallawallaroastery.com",
    },
    {
      name: "Maple Counter Cafe",
      address: "209 E Alder St, Walla Walla, WA 99362",
      lat: 46.0658,
      lng: -118.3375,
      dogPolicy: "Leashed dogs welcome at outdoor tables. Beloved breakfast spot with farm-fresh ingredients.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.maplecountercafe.com",
    },
    {
      name: "Bright's Coffee",
      address: "210 W Main St, Walla Walla, WA 99362",
      lat: 46.0648,
      lng: -118.3425,
      dogPolicy: "Outdoor seating area welcomes dogs. Cozy neighborhood coffee shop with house-baked goods.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.brightscoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Howard Tietan Park Off-Leash Area",
      address: "1515 Tietan St, Walla Walla, WA 99362",
      lat: 46.0580,
      lng: -118.3480,
      offLeash: true,
      fenced: true,
      acres: 2.5,
      amenities: ["Separate small dog area", "Water stations", "Waste bags", "Benches", "Shade trees"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Walla Walla's primary off-leash dog park with separate areas for large and small dogs. Well-maintained with good shade from mature trees and a friendly community of local dog owners.",
    },
    {
      name: "Pioneer Park Dog Area",
      address: "E Alder St & S Division St, Walla Walla, WA 99362",
      lat: 46.0625,
      lng: -118.3280,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Walking paths", "Aviary", "Duck pond", "Picnic areas", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "Walla Walla's historic city park offers extensive walking paths through beautiful gardens, past a duck pond, and through shaded groves. Dogs must be leashed but will love exploring this 20-acre park.",
    },
    {
      name: "Fort Walla Walla Park",
      address: "755 Myra Rd, Walla Walla, WA 99362",
      lat: 46.0520,
      lng: -118.3550,
      offLeash: true,
      fenced: true,
      acres: 1.5,
      amenities: ["Fenced area", "Open grass", "Walking trails", "Waste stations", "Parking"],
      rating: 4.2,
      imageUrl: "",
      description:
        "Adjacent to the Fort Walla Walla Museum, this park features a dedicated off-leash area plus extensive trail systems for leashed walks. The open fields and historic grounds make for an enjoyable outing.",
    },
    {
      name: "Wildwood Park Trail",
      address: "Wildwood Park, Walla Walla, WA 99362",
      lat: 46.0350,
      lng: -118.3200,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Creek access", "Hiking trails", "Nature paths", "Wildlife viewing", "Parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A natural area along Mill Creek offering forested trails and creek access. Leashed dogs love splashing in the shallow creek and exploring the wooded paths on the outskirts of town.",
    },
  ],
};
