export const whitefishData = {
  city: {
    name: "Whitefish",
    state: "Montana",
    region: "Mountain West",
    lat: 48.4106,
    lng: -114.3529,
    dogFriendlinessScore: 8,
    description:
      "This small mountain town at the gateway to Glacier National Park is a dog lover's paradise wrapped in alpine scenery. Whitefish combines world-class skiing, pristine lakes, and endless hiking trails with a walkable downtown where nearly every brewery, restaurant, and shop welcomes your four-legged adventure partner. With bears in the backcountry and dogs on every patio, Whitefish is where the wild meets the friendly.",
    heroImage: "https://images.unsplash.com/photo-1508389377389-918442e3626b?w=1200&fit=crop",
    climate: "Continental",
    population: 8032,
  },

  hotels: [
    {
      name: "The Lodge at Whitefish Lake",
      address: "1380 Wisconsin Ave, Whitefish, MT 59937",
      lat: 48.3958,
      lng: -114.3435,
      priceRange: "$$$$" as const,
      dogPolicy:
        "Luxury lakeside lodge welcoming dogs in select cabins and rooms. Walk right out to the lake for a morning swim with your pup.",
      maxDogWeight: 0,
      petFee: 75,
      amenities: [
        "Lakefront access",
        "Dog bed and bowls",
        "Walking trails",
        "Boat dock",
        "Pet-friendly cabins",
      ],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.lodgeatwhitefishlake.com",
      phone: "(406) 863-4000",
    },
    {
      name: "The Firebrand Hotel",
      address: "650 E 3rd St, Whitefish, MT 59937",
      lat: 48.4098,
      lng: -114.3478,
      priceRange: "$$$" as const,
      dogPolicy:
        "Boutique downtown hotel with a modern mountain vibe. Dogs of all sizes welcome with a one-time fee and a welcome treat.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: [
        "Dog treats at check-in",
        "Walking distance to downtown",
        "Rooftop bar",
        "Waste bags",
        "Trail maps",
      ],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.firebrandhotel.com",
      phone: "(406) 863-1900",
    },
    {
      name: "Pine Lodge",
      address: "920 Spokane Ave, Whitefish, MT 59937",
      lat: 48.4075,
      lng: -114.356,
      priceRange: "$$" as const,
      dogPolicy:
        "Comfortable lodge with a western Montana feel. Dogs welcome in pet-friendly rooms with easy access to walking paths.",
      maxDogWeight: 80,
      petFee: 35,
      amenities: [
        "Pet-friendly rooms",
        "Grassy areas",
        "Close to bike path",
        "Free parking",
        "Waste stations",
      ],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.pinelodgewhitefish.com",
      phone: "(406) 862-7600",
    },
    {
      name: "North Valley Hospital Best Western",
      address: "6510 US-93 S, Whitefish, MT 59937",
      lat: 48.378,
      lng: -114.322,
      priceRange: "$$" as const,
      dogPolicy:
        "Reliable chain hotel with a generous pet policy. Dogs of all sizes welcome with a nightly fee.",
      maxDogWeight: 0,
      petFee: 20,
      amenities: [
        "Pet relief area",
        "Free breakfast",
        "Pool",
        "Waste stations",
        "Free parking",
      ],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(406) 862-2569",
    },
    {
      name: "Whitefish Mountain Resort Village Condos",
      address: "3840 Big Mountain Rd, Whitefish, MT 59937",
      lat: 48.481,
      lng: -114.35,
      priceRange: "$$$" as const,
      dogPolicy:
        "Slope-side condos with select pet-friendly units. Ski with your dog nearby and come home to mountain village comfort.",
      maxDogWeight: 60,
      petFee: 50,
      amenities: [
        "Mountain views",
        "Full kitchen",
        "Ski-in/ski-out access",
        "Hiking trails",
        "Hot tub",
      ],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.skiwhitefish.com",
      phone: "(406) 862-2900",
    },
  ],

  nationalParks: [
    {
      name: "Glacier National Park",
      state: "Montana",
      lat: 48.7596,
      lng: -113.787,
      dogPolicy:
        "Dogs allowed in developed areas, along roads, in parking lots, and on some bike paths. Not permitted on trails or in the backcountry.",
      dogTrails: [
        "Apgar Bike Trail",
        "Going-to-the-Sun Road roadside areas",
        "Lake McDonald Lodge grounds",
        "Fish Creek Campground area",
      ],
      restrictions: [
        "Dogs must be on a 6-foot leash at all times",
        "Not allowed on any hiking trails",
        "Not permitted in backcountry, on lake shores, or in boats",
        "Must clean up after pets",
      ],
      description:
        "The crown jewel of Montana's national parks is just 30 minutes from Whitefish. While trail access is limited for dogs, the scenery visible from the roadside and developed areas is still world-class. Drive the Going-to-the-Sun Road with the windows down, explore Apgar Village, and soak in alpine lake views from the parking areas.",
      imageUrl: "",
      website: "https://www.nps.gov/glac",
    },
    {
      name: "Whitefish Trail",
      state: "Montana",
      lat: 48.42,
      lng: -114.38,
      dogPolicy:
        "Leashed dogs welcome on all sections of this growing trail system. A community-built masterpiece winding through forests and along Whitefish Lake.",
      dogTrails: [
        "Lion Mountain Loop",
        "Beaver Lakes Trail",
        "Smith Lake section",
        "Whitefish Lake section",
        "Swift Creek section",
      ],
      restrictions: [
        "Dogs must be on a leash",
        "Must clean up after pets",
        "Be bear aware — carry bear spray",
        "Yield to other trail users",
      ],
      description:
        "A world-class community trail system circling Whitefish with over 42 miles of non-motorized trails through forests, along lakeshores, and past beaver ponds. Leashed dogs can explore diverse terrain from easy lakeside strolls to challenging mountain climbs. The Lion Mountain section offers stunning views of Whitefish Lake and the surrounding peaks.",
      imageUrl: "",
      website: "https://www.whitefishlegacy.org",
    },
    {
      name: "Flathead National Forest",
      state: "Montana",
      lat: 48.3,
      lng: -114.1,
      dogPolicy:
        "Dogs welcome on-leash in developed areas and off-leash in many backcountry areas under voice control. Vast wilderness at your doorstep.",
      dogTrails: [
        "Danny On Memorial Trail",
        "Big Creek Trail",
        "Tally Lake Trail",
        "Jewel Basin trails (dogs allowed on some)",
      ],
      restrictions: [
        "Leash required in developed recreation sites and campgrounds",
        "Off-leash allowed in backcountry under voice control",
        "Must carry out waste",
        "Bear country — carry bear spray and keep dogs close",
      ],
      description:
        "Over 2.4 million acres of pristine Montana wilderness surrounding Whitefish. From alpine lakes to dense cedar forests, the hiking opportunities are endless. The Danny On Trail climbs to the summit of Big Mountain for breathtaking 360-degree views. This is grizzly country — keep your dog close and carry bear spray.",
      imageUrl: "",
      website: "https://www.fs.usda.gov/flathead",
    },
  ],

  restaurants: [
    {
      name: "Bonsai Brewing Project",
      address: "264 E 2nd St, Whitefish, MT 59937",
      lat: 48.4098,
      lng: -114.3505,
      cuisine: "Brewery / Food Trucks",
      priceRange: "$" as const,
      dogPolicy:
        "Community-focused brewery with a massive outdoor area, rotating food trucks, and a dog-friendly policy that makes every pup feel at home.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bonsaibrewingproject.com",
    },
    {
      name: "Craggy Range Bar & Grill",
      address: "10 Central Ave, Whitefish, MT 59937",
      lat: 48.4109,
      lng: -114.3531,
      cuisine: "American / Pub",
      priceRange: "$$" as const,
      dogPolicy:
        "Downtown pub with a dog-friendly patio. Great burgers, local brews, and a central location for post-hike refueling.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.craggyrange.com",
    },
    {
      name: "Whitefish Lake Restaurant",
      address: "1380 Wisconsin Ave, Whitefish, MT 59937",
      lat: 48.3958,
      lng: -114.3435,
      cuisine: "Pacific Northwest / Fine Dining",
      priceRange: "$$$" as const,
      dogPolicy:
        "Lakefront fine dining with a seasonal patio where well-behaved leashed dogs can join you. Watch the sunset over Whitefish Lake.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.whitefishlakerestaurant.com",
    },
    {
      name: "Bulldog Saloon",
      address: "144 Central Ave, Whitefish, MT 59937",
      lat: 48.4109,
      lng: -114.352,
      cuisine: "American / Bar",
      priceRange: "$" as const,
      dogPolicy:
        "Appropriately named for dog owners! Casual saloon with outdoor seating where your bulldog (or any breed) is welcome.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.bulldogsaloon.com",
    },
    {
      name: "Abruzzo Italian Kitchen",
      address: "110 Central Ave, Whitefish, MT 59937",
      lat: 48.4109,
      lng: -114.3523,
      cuisine: "Italian",
      priceRange: "$$$" as const,
      dogPolicy:
        "Rustic Italian dining with a covered patio. Leashed dogs welcome outside while you enjoy house-made pasta and Montana wines.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.abruzzowhitefish.com",
    },
    {
      name: "Swift Creek Café",
      address: "206 2nd St E, Whitefish, MT 59937",
      lat: 48.4095,
      lng: -114.3505,
      cuisine: "Breakfast / Brunch",
      priceRange: "$" as const,
      dogPolicy:
        "Beloved breakfast spot with a dog-friendly patio. Fuel up on huckleberry pancakes before hitting the trails with your pup.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.swiftcreekcafe.com",
    },
    {
      name: "Montana Tap House",
      address: "117 Central Ave, Whitefish, MT 59937",
      lat: 48.4109,
      lng: -114.3525,
      cuisine: "Gastropub / American",
      priceRange: "$$" as const,
      dogPolicy:
        "Huge craft beer selection with a patio that welcomes dogs. Over 40 Montana taps and a relaxed mountain-town atmosphere.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.montanataphouse.com",
    },
    {
      name: "Latitude 48 Bistro & Red Room",
      address: "147 Central Ave, Whitefish, MT 59937",
      lat: 48.4109,
      lng: -114.352,
      cuisine: "New American / Bistro",
      priceRange: "$$$" as const,
      dogPolicy:
        "Farm-to-table bistro with an elegant patio. Leashed dogs welcome while you enjoy locally sourced mountain cuisine.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.latitude48bistro.com",
    },
  ],

  cafes: [
    {
      name: "Montana Coffee Traders",
      address: "110 Central Ave, Whitefish, MT 59937",
      lat: 48.411,
      lng: -114.353,
      dogPolicy:
        "Whitefish's beloved coffee institution with a sunny patio. Dogs are regulars here and the baristas often keep treats on hand.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.coffeetraders.com",
    },
    {
      name: "Spotted Bear Spirits Tasting Room & Coffee",
      address: "435 E 2nd St, Whitefish, MT 59937",
      lat: 48.4095,
      lng: -114.348,
      dogPolicy:
        "Distillery and coffee combo with a patio where dogs are welcome. Morning coffee or afternoon whiskey — your pup is happy either way.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.spottedbearspirits.com",
    },
    {
      name: "Red Caboose Coffee",
      address: "Whitefish Depot, Whitefish, MT 59937",
      lat: 48.4105,
      lng: -114.354,
      dogPolicy:
        "Coffee served from a charming red caboose next to the historic train depot. Outdoor seating and dogs always welcome.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.redcaboosecoffee.com",
    },
    {
      name: "Stumptown Coffee at Whitefish Handmade",
      address: "301 E 2nd St, Whitefish, MT 59937",
      lat: 48.4098,
      lng: -114.35,
      dogPolicy:
        "Artisan shop and coffee spot with outdoor seating. Dogs welcome while you browse Montana-made goods.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.whitefishhandmade.com",
    },
    {
      name: "Joe's Parkway Coffee",
      address: "845 Wisconsin Ave, Whitefish, MT 59937",
      lat: 48.4,
      lng: -114.345,
      dogPolicy:
        "Neighborhood coffee shop with a drive-through and patio. Dogs welcome at the outdoor tables for a quick caffeine stop.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.joesparkway.com",
    },
  ],

  dogParks: [
    {
      name: "Smith Fields Dog Park",
      address: "Smith Fields, Whitefish, MT 59937",
      lat: 48.405,
      lng: -114.365,
      offLeash: true,
      fenced: true,
      acres: 3,
      amenities: [
        "Fenced area",
        "Mountain views",
        "Water station",
        "Benches",
        "Waste stations",
        "Parking",
      ],
      rating: 4.5,
      imageUrl: "",
      description:
        "Whitefish's main dog park with stunning mountain views in every direction. Fully fenced off-leash area where your pup can romp with the locals. The Whitefish Range provides a jaw-dropping backdrop to every game of fetch.",
    },
    {
      name: "Whitefish Lake State Park Beach",
      address: "1615 W Lakeshore Dr, Whitefish, MT 59937",
      lat: 48.396,
      lng: -114.38,
      offLeash: false,
      fenced: false,
      acres: 10,
      amenities: [
        "Lake swimming",
        "Beach access",
        "Hiking trails",
        "Picnic areas",
        "Waste stations",
      ],
      rating: 4.6,
      imageUrl: "",
      description:
        "A gorgeous state park on the shores of Whitefish Lake. Leashed dogs can enjoy the trails and designated beach areas (not the main swimming beach). The crystal-clear mountain lake and towering pines make every walk feel like a postcard.",
    },
    {
      name: "Lion Mountain Trail",
      address: "Lion Mountain Trailhead, Whitefish, MT 59937",
      lat: 48.42,
      lng: -114.37,
      offLeash: false,
      fenced: false,
      acres: 50,
      amenities: [
        "Mountain hiking trails",
        "Lake views",
        "Forest trails",
        "Trailhead parking",
        "Waste bags at trailhead",
      ],
      rating: 4.7,
      imageUrl: "",
      description:
        "Part of the Whitefish Trail system, Lion Mountain offers a moderate loop hike through forests with spectacular views of Whitefish Lake and the surrounding mountains. Leashed dogs love this trail and the summit views are reward enough for the climb. Bear spray recommended.",
    },
    {
      name: "Riverside Park Dog Area",
      address: "River Rd, Whitefish, MT 59937",
      lat: 48.415,
      lng: -114.36,
      offLeash: true,
      fenced: false,
      acres: 5,
      amenities: [
        "River access",
        "Open fields",
        "Shade trees",
        "Walking paths",
        "Waste stations",
      ],
      rating: 4.3,
      imageUrl: "",
      description:
        "A riverside open space where dogs can play off-leash (under voice control) along the Whitefish River. Shallow water for wading, grassy fields for running, and shade trees for resting. A favorite local spot for an easy after-work dog adventure.",
    },
    {
      name: "Beaver Lakes Trail",
      address: "Beaver Lakes Trailhead, Whitefish, MT 59937",
      lat: 48.44,
      lng: -114.39,
      offLeash: false,
      fenced: false,
      acres: 20,
      amenities: [
        "Forest trails",
        "Lake access",
        "Wildlife viewing",
        "Trailhead parking",
        "Waste stations",
      ],
      rating: 4.5,
      imageUrl: "",
      description:
        "A peaceful trail through dense forest leading to a series of small beaver-dammed lakes. Leashed dogs can explore the forested path and sniff around the marshy lakeshores. Keep your eyes peeled for beaver activity, moose, and all manner of Montana wildlife.",
    },
  ],
};
