export const wilmingtonData = {
  city: {
    name: "Wilmington",
    state: "North Carolina",
    region: "Southeast",
    lat: 34.2257,
    lng: -77.9447,
    dogFriendlinessScore: 8,
    description:
      "Wilmington is a coastal gem where river meets sea and every pup gets a warm Southern welcome. From the historic Riverwalk along the Cape Fear River to the wide sandy beaches of Wrightsville and Carolina Beach, tail-wagging adventures abound. Dog-friendly patios line the downtown streets, and the surrounding barrier islands offer off-leash beach time that will make your retriever's dreams come true.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&fit=crop",
    climate: "Humid Subtropical",
    population: 115451,
  },

  hotels: [
    {
      name: "Hotel Ballast Wilmington",
      address: "301 N Water St, Wilmington, NC 28401",
      lat: 34.2365,
      lng: -77.9490,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs up to 50 lbs welcome with a one-time pet fee. Riverfront luxury with stunning Cape Fear views.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["Dog bed", "Water bowls", "Treats at check-in", "Riverwalk access", "Pet relief area"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.hotelballast.com",
      phone: "(910) 763-5900",
    },
    {
      name: "The Bellevue Suites",
      address: "5725 Oleander Dr, Wilmington, NC 28403",
      lat: 34.2105,
      lng: -77.8930,
      priceRange: "$$" as const,
      dogPolicy: "All dogs welcome regardless of size. Extended-stay suites with full kitchens ideal for longer pup vacations.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Full kitchen", "Grassy pet area", "Waste stations", "Near Wrightsville Beach", "Dog walking path"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.bellevuesuiteswilm.com",
      phone: "(910) 256-2773",
    },
    {
      name: "Residence Inn by Marriott Wilmington Landfall",
      address: "1200 Culbreth Dr, Wilmington, NC 28405",
      lat: 34.2410,
      lng: -77.8350,
      priceRange: "$$" as const,
      dogPolicy: "Pets welcome with a nightly fee. Spacious suites with separate living areas give your pup room to stretch.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["Pet walking area", "Waste stations", "Suite-style rooms", "Breakfast included", "Near Mayfaire shops"],
      rating: 4.3,
      imageUrl: "",
      website: "https://www.marriott.com",
      phone: "(910) 256-0098",
    },
    {
      name: "Blockade Runner Beach Resort",
      address: "275 Waynick Blvd, Wrightsville Beach, NC 28480",
      lat: 34.2087,
      lng: -77.7964,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs up to 40 lbs welcome in designated pet-friendly rooms. Beachfront resort with direct ocean access.",
      maxDogWeight: 40,
      petFee: 100,
      amenities: ["Beach access", "Dog bed", "Water bowls", "Outdoor rinse station", "Pet sitting referrals"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.blockade-runner.com",
      phone: "(910) 256-2251",
    },
    {
      name: "Best Western Plus Coastline Inn",
      address: "503 Nutt St, Wilmington, NC 28401",
      lat: 34.2345,
      lng: -77.9510,
      priceRange: "$$" as const,
      dogPolicy: "Dogs of all sizes welcome with a modest pet fee. Steps from the Riverwalk and downtown dining.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Riverwalk access", "Pet relief area", "Waste bags", "Near downtown restaurants", "Parking included"],
      rating: 4.0,
      imageUrl: "",
      website: "https://www.bestwestern.com",
      phone: "(910) 763-2800",
    },
  ],

  nationalParks: [
    {
      name: "Fort Fisher State Recreation Area",
      state: "North Carolina",
      lat: 33.9645,
      lng: -77.9250,
      dogPolicy: "Leashed dogs welcome on the beach and trails year-round. One of the best dog-friendly beach experiences near Wilmington.",
      dogTrails: ["Basin Trail", "Fort Fisher beach strand", "Hermit Trail loop"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Clean up after your pet",
        "Not allowed in the aquarium",
      ],
      description:
        "A stunning stretch of undeveloped beach and maritime forest at the southern tip of Pleasure Island. Leashed dogs can roam the wide sandy shores, explore the Civil War earthworks, and sniff their way through the Basin Trail alongside tidal marshes and live oaks.",
      imageUrl: "",
      website: "https://www.ncparks.gov/fort-fisher-state-recreation-area",
    },
    {
      name: "Carolina Beach State Park",
      state: "North Carolina",
      lat: 34.0485,
      lng: -77.9070,
      dogPolicy: "Leashed dogs welcome on all trails and in campgrounds. A nature lover's paradise with carnivorous plants and coastal forests.",
      dogTrails: ["Flytrap Trail", "Sugarloaf Trail", "Snow's Cut Trail", "Campground Trail"],
      restrictions: [
        "Must be on a 6-foot leash at all times",
        "Not allowed in swim areas",
        "Must stay on designated trails",
      ],
      description:
        "Home to the rare Venus flytrap in its native habitat, this park offers miles of trails through longleaf pine forests and along the Cape Fear River. Leashed pups love the shaded Sugarloaf Trail and the marina-side paths.",
      imageUrl: "",
      website: "https://www.ncparks.gov/carolina-beach-state-park",
    },
    {
      name: "Moores Creek National Battlefield",
      state: "North Carolina",
      lat: 34.4580,
      lng: -78.1100,
      dogPolicy: "Leashed dogs welcome on the trail and grounds. A peaceful Revolutionary War site with gentle walking paths.",
      dogTrails: ["History Trail loop", "Tarheel Trail"],
      restrictions: [
        "Must be on leash",
        "Not allowed inside visitor center",
        "Must stay on designated trails",
      ],
      description:
        "About 30 minutes from Wilmington, this National Battlefield preserves the site of a pivotal 1776 Revolutionary War battle. Leashed dogs can join you on the mile-long History Trail through moss-draped forests and across the reconstructed bridge.",
      imageUrl: "",
      website: "https://www.nps.gov/mocr",
    },
  ],

  restaurants: [
    {
      name: "Catch",
      address: "6623 Market St, Wilmington, NC 28405",
      lat: 34.2520,
      lng: -77.8610,
      cuisine: "Seafood",
      priceRange: "$$$" as const,
      dogPolicy: "Well-behaved dogs welcome on the spacious outdoor patio. Fresh local seafood in an upscale-casual setting.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.catchwilmington.com",
    },
    {
      name: "The Fork N Cork",
      address: "122 Market St, Wilmington, NC 28401",
      lat: 34.2355,
      lng: -77.9478,
      cuisine: "American Gastropub",
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly outdoor seating in the heart of downtown. Great craft cocktails and hearty pub fare.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.theforkncorl.com",
    },
    {
      name: "Tower 7 Baja Mexican Grill",
      address: "15 N Lumina Ave, Wrightsville Beach, NC 28480",
      lat: 34.2098,
      lng: -77.7985,
      cuisine: "Mexican",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome on the covered rooftop deck with ocean breezes. Perfect post-beach tacos.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.tower7baja.com",
    },
    {
      name: "Manna",
      address: "123 Princess St, Wilmington, NC 28401",
      lat: 34.2350,
      lng: -77.9460,
      cuisine: "New American",
      priceRange: "$$$$" as const,
      dogPolicy: "Leashed dogs welcome at select outdoor tables on Princess Street. Farm-to-table fine dining.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.mannaavenue.com",
    },
    {
      name: "Flaming Amy's Burrito Barn",
      address: "4002 Oleander Dr, Wilmington, NC 28403",
      lat: 34.2175,
      lng: -77.8985,
      cuisine: "Mexican",
      priceRange: "$" as const,
      dogPolicy: "Dog-friendly picnic tables outside this beloved local burrito institution. Casual and fun.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.flamingamysburritobarn.com",
    },
    {
      name: "Boca Bay",
      address: "6604 N Yacht Basin Dr, Wrightsville Beach, NC 28480",
      lat: 34.2165,
      lng: -77.8090,
      cuisine: "Seafood & Sushi",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the waterfront deck overlooking the Intracoastal Waterway. Sunset views are spectacular.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.bocabay.com",
    },
    {
      name: "Copper Penny",
      address: "109 Chestnut St, Wilmington, NC 28401",
      lat: 34.2362,
      lng: -77.9465,
      cuisine: "American Comfort",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome at sidewalk tables. Classic diner fare with a Southern twist downtown.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.1,
      imageUrl: "",
      website: "https://www.copperpennywilmington.com",
    },
    {
      name: "South Beach Grill",
      address: "100 Fort Fisher Blvd S, Kure Beach, NC 28449",
      lat: 33.9968,
      lng: -77.9135,
      cuisine: "Seafood & American",
      priceRange: "$$" as const,
      dogPolicy: "Very dog-friendly outdoor patio just steps from the beach. Fresh catch and cold drinks in a laid-back atmosphere.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.southbeachgrillkurebeach.com",
    },
  ],

  cafes: [
    {
      name: "Bespoke Coffee",
      address: "202 N Front St, Wilmington, NC 28401",
      lat: 34.2380,
      lng: -77.9492,
      dogPolicy: "Leashed dogs welcome at outdoor tables along the Riverwalk. Specialty coffee and house-made pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.bespokecoffeenc.com",
    },
    {
      name: "Port City Java",
      address: "21 N Front St, Wilmington, NC 28401",
      lat: 34.2345,
      lng: -77.9488,
      dogPolicy: "Dog-friendly sidewalk seating at this beloved local chain. Born in Wilmington and proud of it.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.portcityjava.com",
    },
    {
      name: "Folks Cafe",
      address: "12 S Front St, Wilmington, NC 28401",
      lat: 34.2340,
      lng: -77.9485,
      dogPolicy: "Courtyard patio where leashed dogs are welcome to lounge while you sip espresso. A cozy local gathering spot.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.folkscafe.com",
    },
    {
      name: "Lighthouse Beer & Wine",
      address: "7209 Wrightsville Ave, Wilmington, NC 28403",
      lat: 34.2120,
      lng: -77.8250,
      dogPolicy: "Dogs welcome on the patio at this casual bottle shop and cafe near Wrightsville Beach.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.lighthousebeerandwine.com",
    },
    {
      name: "Canopy Coffee",
      address: "500 Market St, Wilmington, NC 28401",
      lat: 34.2365,
      lng: -77.9438,
      dogPolicy: "Shaded patio where your pup can relax while you enjoy single-origin pour-overs. Dog water bowl always available.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.canopycoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Wilmington Dog Park at Empie Park",
      address: "Park Ave & Independence Blvd, Wilmington, NC 28403",
      lat: 34.2180,
      lng: -77.8920,
      offLeash: true,
      fenced: true,
      acres: 1.0,
      amenities: ["Separate small and large dog areas", "Water fountains", "Benches", "Shade trees", "Waste stations"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A well-loved community dog park tucked inside Empie Park with separate areas for big and small pups. Shaded by mature trees, it is the go-to off-leash hangout for Wilmington's four-legged residents.",
    },
    {
      name: "Wrightsville Beach Dog-Friendly Zone",
      address: "N Lumina Ave, Wrightsville Beach, NC 28480",
      lat: 34.2165,
      lng: -77.7965,
      offLeash: true,
      fenced: false,
      acres: 5.0,
      amenities: ["Beach access", "Ocean swimming", "Outdoor showers", "Waste stations"],
      rating: 4.7,
      imageUrl: "",
      description:
        "During seasonal off-leash hours, dogs can run free on the wide sandy beach and splash in the Atlantic. Nothing beats watching your pup sprint across the shoreline with the salt breeze in their fur.",
    },
    {
      name: "Hugh MacRae Park",
      address: "314 Pine Grove Dr, Wilmington, NC 28403",
      lat: 34.2100,
      lng: -77.9050,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Walking trails", "Picnic shelters", "Playground nearby", "Shade trees", "Waste stations"],
      rating: 4.1,
      imageUrl: "",
      description:
        "A sprawling neighborhood park with walking paths winding through tall pines. Leashed dogs love the trails and the pond-side strolls. A peaceful spot for an afternoon walk with your best friend.",
    },
    {
      name: "Carolina Beach Off-Leash Area",
      address: "1000 S Lake Park Blvd, Carolina Beach, NC 28428",
      lat: 34.0310,
      lng: -77.8930,
      offLeash: true,
      fenced: false,
      acres: 3.0,
      amenities: ["Beach access", "Swimming", "Waste stations", "Free parking"],
      rating: 4.5,
      imageUrl: "",
      description:
        "The north end of Freeman Park at Carolina Beach allows off-leash dogs to frolic in the surf and dig in the sand. A true tail-wagging paradise for beach-loving pups.",
    },
    {
      name: "Halyburton Park",
      address: "4099 S 17th St, Wilmington, NC 28412",
      lat: 34.1925,
      lng: -77.9260,
      offLeash: false,
      fenced: false,
      acres: 58.0,
      amenities: ["Nature trails", "Boardwalks", "Wetland overlooks", "Benches", "Waste stations", "Education center"],
      rating: 4.4,
      imageUrl: "",
      description:
        "A nature preserve with 1.3 miles of trails through longleaf pine forests and wetlands. Leashed dogs can explore elevated boardwalks over swampy terrain and spot turtles and herons along the way.",
    },
  ],
};
