export const wimberleyData = {
  city: {
    name: "Wimberley",
    state: "Texas",
    region: "Southwest",
    lat: 29.9977,
    lng: -98.0986,
    dogFriendlinessScore: 8,
    description:
      "Wimberley is a magical Hill Country village where Cypress Creek and the Blanco River converge, creating swimming holes that dogs absolutely adore. The small-town arts community welcomes dogs into shops, restaurants, and galleries, making it a perfect weekend escape from Austin or San Antonio.",
    heroImage: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&fit=crop",
    climate: "Humid subtropical",
    population: 3010,
  },

  hotels: [
    {
      name: "Creekhaven Inn",
      address: "400 Mill Race Ln, Wimberley, TX 78676",
      lat: 29.9990,
      lng: -98.0970,
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome in select rooms with a pet fee. Creekside inn with swimming access.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Creek access", "Dog bed", "Walking paths", "Outdoor sitting areas", "Near town square"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.creekhaveninn.com",
      phone: "(512) 847-9344",
    },
    {
      name: "Blair House Inn",
      address: "100 W Spoke Hill Dr, Wimberley, TX 78676",
      lat: 30.0010,
      lng: -98.1050,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in the cottage with advance reservation. Luxury B&B on 85 acres.",
      maxDogWeight: 50,
      petFee: 75,
      amenities: ["85-acre grounds", "Walking trails", "Garden", "Pool", "Gourmet breakfast"],
      rating: 4.7,
      imageUrl: "",
      website: "https://www.blairhouseinn.com",
      phone: "(512) 847-1111",
    },
    {
      name: "Wimberley Inn",
      address: "200 RR 12, Wimberley, TX 78676",
      lat: 29.9980,
      lng: -98.0960,
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome with a pet deposit. Comfortable rooms in the heart of Wimberley.",
      maxDogWeight: 0,
      petFee: 30,
      amenities: ["Near town square", "Grassy area", "Walking distance to creek", "Parking"],
      rating: 4.2,
      imageUrl: "",
      website: "https://www.wimberleyinn.com",
      phone: "(512) 847-3750",
    },
    {
      name: "Cypress Creek Cottages",
      address: "100 Cypress Creek Rd, Wimberley, TX 78676",
      lat: 30.0000,
      lng: -98.0940,
      priceRange: "$$" as const,
      dogPolicy: "Dog-friendly cottages with fenced yards and creek access. A dog's dream vacation.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Fenced yard", "Creek access", "Private cottage", "BBQ grill", "Outdoor fire pit"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.cypresscreekcottages.com",
      phone: "(512) 847-2515",
    },
  ],

  nationalParks: [
    {
      name: "Jacob's Well Natural Area",
      state: "Texas",
      lat: 30.0360,
      lng: -98.1260,
      dogPolicy: "Leashed dogs welcome on the hiking trails but not allowed in the swimming area.",
      dogTrails: ["Jacob's Well Trail", "Creek View Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed in the swimming area at Jacob's Well",
        "Stay on designated trails",
        "Reservations required",
      ],
      description:
        "This natural area protects the famous Jacob's Well, a perennial karst spring that flows from deep underground. While dogs cannot swim at the well, the surrounding trails through Hill Country terrain are beautiful.",
      imageUrl: "",
      website: "https://www.co.hays.tx.us/jacobswell",
    },
    {
      name: "Blue Hole Regional Park",
      state: "Texas",
      lat: 30.0020,
      lng: -98.0920,
      dogPolicy: "Leashed dogs welcome on the nature trails but not in the swimming area.",
      dogTrails: ["Hill Country Trail", "Creek Trail", "Meditation Loop"],
      restrictions: [
        "Must be on leash",
        "Not allowed in the swimming hole",
        "Stay on hiking trails",
      ],
      description:
        "A beloved Wimberley swimming hole and nature preserve along Cypress Creek. Dogs enjoy the shaded trails through old-growth cypress trees even though the swimming hole itself is off-limits to pups.",
      imageUrl: "",
      website: "https://www.blueholeregionalpark.com",
    },
    {
      name: "Pedernales Falls State Park",
      state: "Texas",
      lat: 30.3080,
      lng: -98.2580,
      dogPolicy: "Leashed dogs welcome on all trails and in campgrounds. Scenic Hill Country waterfall park.",
      dogTrails: ["Wolf Mountain Trail", "Juniper Ridge Trail", "River Trail"],
      restrictions: [
        "Must be on a 6-foot leash",
        "Not allowed in the river swimming areas",
        "Flash flood danger - obey all closures",
      ],
      description:
        "About 30 minutes north of Wimberley, this state park features a dramatic stepped waterfall on the Pedernales River and miles of Hill Country trails. Dogs love the wooded paths and river-adjacent hiking.",
      imageUrl: "",
      website: "https://www.tpwd.texas.gov/state-parks/pedernales-falls",
    },
  ],

  restaurants: [
    {
      name: "The Leaning Pear",
      address: "111 River Rd, Wimberley, TX 78676",
      lat: 29.9985,
      lng: -98.0975,
      cuisine: "Farm-to-Table",
      priceRange: "$$$" as const,
      dogPolicy: "Dogs welcome on the creekside patio. Seasonal farm-to-table cuisine in the Hill Country.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.7,
      imageUrl: "",
      website: "https://www.theleaningpear.com",
    },
    {
      name: "Wimberley Brewing Company",
      address: "9595 RR 12, Wimberley, TX 78676",
      lat: 30.0080,
      lng: -98.1150,
      cuisine: "Brewpub",
      priceRange: "$" as const,
      dogPolicy: "Very dog-friendly with a large outdoor area. Craft beer and food trucks.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.wimberleybrewing.com",
    },
    {
      name: "Community Pizza & Beer Garden",
      address: "100 Wimberley Square, Wimberley, TX 78676",
      lat: 29.9978,
      lng: -98.0988,
      cuisine: "Pizza",
      priceRange: "$$" as const,
      dogPolicy: "Dogs welcome in the beer garden. Wood-fired pizza on the town square.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.communitypizza.com",
    },
    {
      name: "Rolling in Thyme & Dough",
      address: "14401 RR 12, Wimberley, TX 78676",
      lat: 30.0150,
      lng: -98.1300,
      cuisine: "Bakery & Cafe",
      priceRange: "$" as const,
      dogPolicy: "Dogs welcome at outdoor tables. Artisan breads and pastries in the Hill Country.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.rollinginthymeanddough.com",
    },
    {
      name: "Creek Road Cafe",
      address: "117 RR 12, Wimberley, TX 78676",
      lat: 29.9975,
      lng: -98.0990,
      cuisine: "American Comfort",
      priceRange: "$$" as const,
      dogPolicy: "Leashed dogs welcome on the patio overlooking Cypress Creek.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.creekroadcafe.com",
    },
  ],

  cafes: [
    {
      name: "River Rock Coffee",
      address: "100 River Rd, Wimberley, TX 78676",
      lat: 29.9983,
      lng: -98.0978,
      dogPolicy: "Dogs welcome at the creekside outdoor tables. Coffee with a view.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.riverrockcoffee.com",
    },
    {
      name: "The Wimberley Coffee House",
      address: "150 Wimberley Square, Wimberley, TX 78676",
      lat: 29.9977,
      lng: -98.0985,
      dogPolicy: "Outdoor seating welcomes leashed dogs. Cozy coffee shop on the square.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.wimberleycoffee.com",
    },
    {
      name: "Savage Goat Coffee",
      address: "14401 RR 12, Wimberley, TX 78676",
      lat: 30.0148,
      lng: -98.1298,
      dogPolicy: "Dog-friendly patio with Hill Country views. Quality espresso and pastries.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.4,
      imageUrl: "",
      website: "https://www.savagegoatcoffee.com",
    },
    {
      name: "Rough Draft Coffee Bar",
      address: "200 Wimberley Square, Wimberley, TX 78676",
      lat: 29.9976,
      lng: -98.0982,
      dogPolicy: "Leashed dogs welcome outside. Creative coffee drinks on the square.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.2,
      imageUrl: "",
      website: "https://www.roughdraftcoffee.com",
    },
  ],

  dogParks: [
    {
      name: "Cypress Creek at Wimberley Blue Hole",
      address: "333 Blue Hole Ln, Wimberley, TX 78676",
      lat: 30.0015,
      lng: -98.0930,
      offLeash: false,
      fenced: false,
      acres: 15.0,
      amenities: ["Creek access", "Nature trails", "Old-growth cypress trees", "Picnic areas", "Parking"],
      rating: 4.6,
      imageUrl: "",
      description:
        "The trails around Blue Hole offer beautiful on-leash walks through ancient cypress groves along the creek. While dogs cannot swim at the hole, the shaded trail system is magical.",
    },
    {
      name: "Wimberley Village Trail",
      address: "Wimberley Square, Wimberley, TX 78676",
      lat: 29.9978,
      lng: -98.0988,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Sidewalk paths", "Dog-friendly shops", "Creek access points", "Benches", "Restaurants"],
      rating: 4.4,
      imageUrl: "",
      description:
        "Walking through Wimberley's charming village with your dog is an experience in itself. Nearly every shop and gallery welcomes dogs, and the creek access points along the way are a bonus.",
    },
    {
      name: "Old Baldy Trail",
      address: "Old Baldy Trailhead, Wimberley, TX 78676",
      lat: 30.0060,
      lng: -98.0850,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Summit views", "Rocky trail", "Hill Country panoramas", "Parking", "Nature viewing"],
      rating: 4.5,
      imageUrl: "",
      description:
        "A short but rewarding hike to the top of Old Baldy, a prominent Hill Country peak near Wimberley. Leashed dogs enjoy the rocky trail and are rewarded with panoramic views from the summit.",
    },
    {
      name: "Wimberley Community Park",
      address: "100 Community Center Dr, Wimberley, TX 78676",
      lat: 30.0010,
      lng: -98.1010,
      offLeash: true,
      fenced: true,
      acres: 2.0,
      amenities: ["Fenced dog area", "Water fountain", "Shade trees", "Benches", "Waste stations"],
      rating: 4.2,
      imageUrl: "",
      description:
        "Wimberley's community park includes a fenced off-leash area where dogs can play freely. A nice complement to the many on-leash creek and trail options around town.",
    },
  ],
};
