export const woodstockVtData = {
  city: {
    name: "Woodstock",
    state: "Vermont",
    region: "Northeast",
    lat: 43.6234,
    lng: -72.5185,
    dogFriendlinessScore: 9,
    description:
      "Consistently ranked one of the prettiest small towns in America, Woodstock is a dog lover's dream. The covered bridges, village green, and surrounding Green Mountains create an idyllic setting. Vermont's famously relaxed attitude toward dogs means your pup is welcome practically everywhere.",
    heroImage: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=1200&fit=crop",
    climate: "Humid Continental",
    population: 3048,
  },
  hotels: [
    {
      name: "The Woodstock Inn & Resort",
      address: "14 The Green, Woodstock, VT 05091",
      lat: 43.6237,
      lng: -72.5187,
      priceRange: "$$$$" as const,
      dogPolicy: "Dogs welcome in designated pet-friendly rooms with a $50 per night fee. Dog beds, bowls, and treats provided. Access to resort trails.",
      maxDogWeight: 0,
      petFee: 50,
      amenities: ["Dog bed", "Treats", "Resort trails", "Village Green location", "Spa", "Golf course"],
      rating: 4.6,
      imageUrl: "",
      website: "https://www.woodstockinn.com",
      phone: "(802) 457-1100",
    },
    {
      name: "506 On The River Inn",
      address: "1653 W Woodstock Rd, Woodstock, VT 05091",
      lat: 43.6266,
      lng: -72.5625,
      priceRange: "$$$" as const,
      dogPolicy: "Dog-friendly rooms with a $35 per night fee. Riverside property with 5 acres and direct river access for dogs.",
      maxDogWeight: 0,
      petFee: 35,
      amenities: ["River access", "5 acres", "Pool", "Trail access", "Continental breakfast"],
      rating: 4.5,
      imageUrl: "",
      website: "https://www.ontheriverwoodstock.com",
      phone: "(802) 457-5000",
    },
    {
      name: "Sleep Woodstock Motel",
      address: "4963 Woodstock Rd, Woodstock, VT 05091",
      lat: 43.6192,
      lng: -72.4891,
      priceRange: "$$" as const,
      dogPolicy: "Budget-friendly and dog-friendly with a $25 per night pet fee. Clean, simple rooms with grassy areas for dogs.",
      maxDogWeight: 0,
      petFee: 25,
      amenities: ["Pet exercise area", "Free parking", "Near village center", "Mountain views"],
      rating: 4.1,
      imageUrl: "",
      website: "https://www.sleepwoodstock.com",
      phone: "(802) 332-6336",
    },
    {
      name: "Kedron Valley Inn",
      address: "4778 South Rd, South Woodstock, VT 05071",
      lat: 43.5753,
      lng: -72.5176,
      priceRange: "$$$" as const,
      dogPolicy: "Historic country inn warmly welcoming dogs with a $40 per stay fee. Swimming pond and 15 acres of grounds.",
      maxDogWeight: 0,
      petFee: 40,
      amenities: ["Swimming pond", "15 acres", "Historic inn", "Restaurant", "Country roads for walking"],
      rating: 4.4,
      imageUrl: "",
      website: "https://www.kedronvalleyinn.com",
      phone: "(802) 457-1473",
    },
  ],
  nationalParks: [
    {
      name: "Marsh-Billings-Rockefeller National Historical Park",
      state: "Vermont",
      lat: 43.6312,
      lng: -72.5301,
      dogPolicy: "Leashed dogs welcome on all carriage roads and trails. The only national park focused on conservation history.",
      dogTrails: ["The Pogue Loop", "Mount Tom Summit Trail", "South Peak Trail", "Carriage Road Network"],
      restrictions: ["Leash required", "No dogs inside mansion", "Clean up required"],
      description:
        "Vermont's only national park offers a network of carriage roads and forest trails climbing Mount Tom with stunning views of the village below. The Pogue, a peaceful mountain pond, is a highlight. Your leashed dog will love the diverse terrain — from groomed carriage roads to rugged summit trails through old-growth hemlock forests.",
      imageUrl: "",
      website: "https://www.nps.gov/mabi",
    },
    {
      name: "Quechee Gorge State Park",
      state: "Vermont",
      lat: 43.6369,
      lng: -72.4036,
      dogPolicy: "Leashed dogs welcome on all trails. Vermont's Little Grand Canyon is a must-see.",
      dogTrails: ["Quechee Gorge Trail", "Ottauquechee River Trail", "Rim Trail"],
      restrictions: ["Leash required", "Caution near gorge edge", "Clean up required"],
      description:
        "Vermont's deepest gorge plunges 165 feet to the Ottauquechee River below. The trail descends to the bottom where your dog can wade in the river, or you can walk the rim for dramatic overlook views. Just 10 minutes from Woodstock, it's a quick adventure that feels far more remote.",
      imageUrl: "",
      website: "https://vtstateparks.com/quechee.html",
    },
    {
      name: "Coolidge State Forest",
      state: "Vermont",
      lat: 43.5278,
      lng: -72.5369,
      dogPolicy: "Dogs welcome on all trails on leash or under voice control. Extensive backcountry trails through pristine Vermont forest.",
      dogTrails: ["Slack Hill Trail", "CCC Road Trail", "Shrewsbury Peak Trail", "Tinker Brook Trail"],
      restrictions: ["Leash recommended", "Hunting in season", "Pack out waste"],
      description:
        "Over 21,000 acres of working forest south of Woodstock with a network of trails through spruce-fir forests, across mountain streams, and up to panoramic summits. The Shrewsbury Peak hike rewards with 360-degree views of the Green Mountains. Your adventurous dog will thrive on these quiet backcountry trails.",
      imageUrl: "",
      website: "https://fpr.vermont.gov/coolidge-state-forest",
    },
  ],
  restaurants: [
    {
      name: "The Prince & The Pauper",
      address: "24 Elm St, Woodstock, VT 05091",
      lat: 43.6241,
      lng: -72.5172,
      cuisine: "French-American",
      priceRange: "$$$" as const,
      dogPolicy: "Fine dining with a dog-friendly garden patio. Seasonal Vermont cuisine with European flair.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.6,
      imageUrl: "",
      website: "https://www.princeandpauper.com",
    },
    {
      name: "Worthy Kitchen",
      address: "442 Woodstock Rd, Woodstock, VT 05091",
      lat: 43.6309,
      lng: -72.5369,
      cuisine: "Farm-to-Table",
      priceRange: "$$" as const,
      dogPolicy: "Extremely dog-friendly farmhouse restaurant with a spacious outdoor patio. Vermont craft beers and locally sourced food.",
      hasDogMenu: true,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.worthyvermont.com",
    },
    {
      name: "Mon Vert Cafe",
      address: "28 Central St, Woodstock, VT 05091",
      lat: 43.6235,
      lng: -72.5181,
      cuisine: "Cafe",
      priceRange: "$" as const,
      dogPolicy: "Village center cafe with outdoor seating on the green. Dogs welcome at patio tables.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.3,
      imageUrl: "",
      website: "https://www.monvertcafe.com",
    },
    {
      name: "The Red Rooster at The Woodstock Inn",
      address: "14 The Green, Woodstock, VT 05091",
      lat: 43.6237,
      lng: -72.5187,
      cuisine: "New American",
      priceRange: "$$$$" as const,
      dogPolicy: "Resort restaurant with a seasonal terrace overlooking the village green. Leashed dogs welcome on the terrace.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: true,
      rating: 4.5,
      imageUrl: "",
      website: "https://www.woodstockinn.com/dining",
    },
    {
      name: "Mangalitsa",
      address: "61 Central St, Woodstock, VT 05091",
      lat: 43.6233,
      lng: -72.5195,
      cuisine: "Eastern European",
      priceRange: "$$" as const,
      dogPolicy: "Cozy restaurant with seasonal outdoor seating. Dogs welcome outside. Creative Eastern European fare with Vermont ingredients.",
      hasDogMenu: false,
      outdoorSeating: true,
      waterBowls: false,
      rating: 4.4,
      imageUrl: "",
      website: "",
    },
  ],
  cafes: [
    {
      name: "Village Roost",
      address: "19 Central St, Woodstock, VT 05091",
      lat: 43.6236,
      lng: -72.5177,
      dogPolicy: "Charming village coffee shop with a patio facing the green. Dogs welcome outside with treats available at the counter.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.5,
      imageUrl: "",
      website: "",
    },
    {
      name: "Soulfully Good Cafe",
      address: "5 The Green, Woodstock, VT 05091",
      lat: 43.6239,
      lng: -72.5185,
      dogPolicy: "Organic cafe on the village green with outdoor seating. Leashed dogs are welcome and often get a friendly pat from locals.",
      hasOutdoorPatio: true,
      dogTreats: false,
      rating: 4.3,
      imageUrl: "",
      website: "",
    },
    {
      name: "Abracadabra Coffee Co.",
      address: "1639 W Woodstock Rd, Woodstock, VT 05091",
      lat: 43.6268,
      lng: -72.5619,
      dogPolicy: "Riverside coffee roaster with a patio overlooking the Ottauquechee River. Dogs welcome while you enjoy pour-overs and pastries.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.6,
      imageUrl: "",
      website: "",
    },
    {
      name: "Taftsville Country Store Coffee Counter",
      address: "486 Woodstock Rd, Taftsville, VT 05073",
      lat: 43.6313,
      lng: -72.4716,
      dogPolicy: "Historic general store with a coffee counter and outdoor benches near a covered bridge. Dogs welcome outside this Vermont icon.",
      hasOutdoorPatio: true,
      dogTreats: true,
      rating: 4.2,
      imageUrl: "",
      website: "",
    },
  ],
  dogParks: [
    {
      name: "Mount Tom Trails",
      address: "Faulkner Park, Mountain Ave, Woodstock, VT 05091",
      lat: 43.6283,
      lng: -72.5246,
      offLeash: false,
      fenced: false,
      acres: 20.0,
      amenities: ["Summit views", "Carriage roads", "Forest trails", "Interpretive signs", "Parking"],
      rating: 4.7,
      imageUrl: "",
      description:
        "The crown jewel of Woodstock hiking, Mount Tom offers switchback trails through old-growth forest to a summit with panoramic views of the village, the Ottauquechee River valley, and the Green Mountains. Your leashed dog will enjoy the varied terrain from gentle carriage roads to steeper woodland paths.",
    },
    {
      name: "The Woodstock Village Green",
      address: "The Green, Woodstock, VT 05091",
      lat: 43.6237,
      lng: -72.5185,
      offLeash: false,
      fenced: false,
      acres: 2.0,
      amenities: ["Village center", "Benches", "Shade trees", "Covered bridge nearby", "Shops"],
      rating: 4.4,
      imageUrl: "",
      description:
        "The heart of Woodstock, this classic New England village green is surrounded by Federal-style buildings, galleries, and shops. Walk your leashed dog past the Middle Covered Bridge and along the Ottauquechee River. It's the quintessential Vermont stroll.",
    },
    {
      name: "Billings Park",
      address: "River St, Woodstock, VT 05091",
      lat: 43.6252,
      lng: -72.5218,
      offLeash: false,
      fenced: false,
      acres: 5.0,
      amenities: ["Riverside paths", "Covered bridge views", "Open meadow", "Shade", "Benches"],
      rating: 4.3,
      imageUrl: "",
      description:
        "A riverside park with walking paths, open meadows, and views of the Middle Covered Bridge. Your leashed dog can explore the grassy areas and riverbank while you enjoy one of the most photographed scenes in Vermont. A peaceful spot for a morning walk.",
    },
    {
      name: "Suicide Six Recreation Area Trails",
      address: "247 Stage Rd, South Pomfret, VT 05067",
      lat: 43.6572,
      lng: -72.5347,
      offLeash: false,
      fenced: false,
      acres: 10.0,
      amenities: ["Mountain trails", "Meadow views", "Quiet setting", "Parking", "Seasonal access"],
      rating: 4.2,
      imageUrl: "",
      description:
        "In the off-season, this small ski area's trails become lovely hiking paths through mountain meadows and forest. The climb offers views of the surrounding Green Mountain foothills, and the quiet setting means your leashed dog may have the trails almost to themselves.",
    },
  ],
};
